### ISSUE TITLE
Use IMDS to retrieve EC2 tag data

### ISSUE THREAD

**Issue by EddieEldridge** [open-telemetry/opentelemetry-collector-contrib#10001]
**Describe the solution you'd like**
I would like to be able to use the ResourceDetection processor to retrieve tag info from my EC2 instance using IMDS and attach that tag info to my metrics, spans and logs as attributes.

I would like this process to use IMDS rather than EC2:DescribeTags to reduce the amount of DescribeTags calls my instances make.

**Describe alternatives you've considered**
I've used the existing method which works fine but I don't want to make DescribeTags calls.

**Additional context**
The process is outlined here https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#work-with-tags-in-IMDS.

**Comment by dmitryax** [comment]
cc @Aneurysm9

**Comment by fregatte** [comment]
Hi guys, do you have any plans here?

**Comment by fatsheep9146** [comment]
nicely ping @Aneurysm9 @jrcamp @dashpole

**Comment by Aneurysm9** [comment]
This is not on my radar at this time.  Happy to help review PRs if one becomes available.

**Comment by fatsheep9146** [comment]
@fregatte @EddieEldridge do you have interest in contributing this?

**Comment by EddieEldridge** [comment]
> @fregatte @EddieEldridge do you have interest in contributing this?

I don't at this time, no.

**Comment by fregatte** [comment]
> @fregatte @EddieEldridge do you have interest in contributing this?

Unfortunately, cannot take it right now too :(
