### ISSUE TITLE
Extend CloudFoundry receiver to support Logs

### ISSUE THREAD

**Issue by KarstenSchnitter** [open-telemetry/opentelemetry-collector-contrib#10025]
**Is your feature request related to a problem? Please describe.**
The Cloud Foundry receiver requested in #5320 currently only supports metrics.
Cloud Foundry also supports application and request logs over the same channel.

**Describe the solution you'd like**
Extend [cloudfoundryreceiver/stream.go#L69-L78](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9c710a37f4a20228db0e528827b79ca2a80970cc/receiver/cloudfoundryreceiver/stream.go#L69-L78) to subscribe to log events by adding the corresponding selector from [cloudfoundry/go-loggregator/examples/envelope_stream_connector/main.go#L15-L17](https://github.com/cloudfoundry/go-loggregator/blob/ebad62b6927a3a05f284bd12036e68494d9d729b/examples/envelope_stream_connector/main.go#L15-L17).

Add the appropriate mapping of the Loggregator `Envelope_Log` at [cloudfoundryreceiver/converter.go#L33](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9c710a37f4a20228db0e528827b79ca2a80970cc/receiver/cloudfoundryreceiver/converter.go#L33).
Of course, the log events cannot be added to a metrics slice. An additional log slice or similar has to bee introduced into the design.

All logs created by CloudFoundry applications can be collected that way. This comprises all logs written by the applications to stdout and stderr as well as the access logs written by the Gorouter, the central load balancer.

**Describe alternatives you've considered**
The alternative collection mechanism would be to use [syslog drains](https://docs.cloudfoundry.org/devguide/services/user-provided.html#syslog). CloudFoundry would forward the logs (application and access) of **one** application to a specific url using syslog (tcp or over https). This setup is cumbersome and creates a lot of overhead. It is hard to ensure proper security. If syslog-over-https is used, the receiver cannot be deployed to CloudFoundry itself, since every message is sent in a single HTTP request, generating access logs. Collecting the logs of **all** applications requires service bindings to all applications.

**Comment by dmitryax** [comment]
@KarstenSchnitter do you want to help with this enhancement?

**Comment by KarstenSchnitter** [comment]
@dmitryax any help would be greatly appreciated.
