### ISSUE TITLE
[processor/transform] Refactor function structure

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#10101]
[The transform processor currently uses reflection to call functions.](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e2d24b5a36ce989b58effaf8ea89d6474f6795a0/processor/transformprocessor/internal/common/functions.go#L143)  Reflection is working, but is complicated to maintain and adapt when new functions are added.

This issue will track the following steps to removing reflection and improving function add process:
- [x]  Update reflection in `NewFunctionCall`.  Any new functions should be able to access any parameters from `Value`
- [x] Refactor functions into their own files/modules.  This is how [log-collection](https://github.com/open-telemetry/opentelemetry-log-collection/tree/main/operator) is organized, and I think it helps organize the code.  If we continue to put all shared functions in `common/functions.go`, the file will become huge.  
- [x] Think about how to refactor unit tests for functions.  Right now each time a function is added it will need test scenarios in `common /functions_test.go` and each signal's `functions_test.go`.  This process has a lot of room for missed tests.  Want to figure out if there is a better way to handle testing functions for all the different scenarios.
- [ ] Add a CONTRIBUTING.md for how to add new functions and how to add new features to the parser.

**Comment by anuraaga** [comment]
Oh missed the issue - I left some comments on the PR but will comment on the text here too.

> but is complicated to maintain and adapt when new functions are added

In general, complicated to maintain is acceptable if it makes an API or user experience easier - we expect new functions to be added a lot forever, but while the reflection may not support everything yet it should reach a peak at some point where all resolvable types are implemented, but functions continue to be added. So we would want to prioritize the function definition experience at the expense of implementation. I left a suggestion on a possible alternative to reflection if it seems better, though I'm not convinced it is.

**Comment by TylerHelmuth** [comment]
My overall goal with this issue/PR is to make function adding easier.  When I added the `truncate_all` and `limit` functions I was tripped up by the need to update the reflection in `NewFunctionCall`, so I went looking for a way to avoid the need to modify that function when a new function is added.

Benefits of existing reflection solution:
- encapsulates all parsing logic.  Function creators can define their functions with the expected params.
- Handles paramater count and type checking for you.  Function definers only need to worry about parameter values themselves, not whether or not the query was written correctly.

Downsides of reflection solution:
- Until all possible parameter types are handled, new function creators might have to modify `NewFunctionCall`.  I had to do this and didn't like it.
- Performance.  I am not well educated on Go's reflection performance, but I am assuming it is slowing that using normal types.  Please correct me if I am wrong.

My main goal is to make it easy for functions to be defined, but I also wanted to boost performance.  My initial thought was that by forcing every function to have the same parameters 
 
`(arguments []Value, pathParser PathExpressionParser, functions map[string]TransformFunction)`  

function creators would know exactly what is getting passed in and performance would increase.  The downside i recognize while I was writing is that until all the `to...` functions are defined new function builder would have a similar challenge that I had with reflection (although I do think adding `to..` functions is simpler) and each function had to build in argument length and type checking.

The right solution might be for me to build out all the reflection cases so future function creators never have to worry about it.  If performance with reflection is not an issue, then I would agree that we keep reflection and the work will be to finish all reflection cases instead of refactoring.

**Comment by TylerHelmuth** [comment]
Whether or not we keep reflection, I do think that functions.go will get too large.  How do you feel about functions.go containing only the types/funcs necessary to build functions, and then individual functions be added via their own files/modules?

**Comment by anuraaga** [comment]
> If performance with reflection is not an issue, then I would agree that we keep reflection and the work will be to finish all reflection cases instead of refactoring.

The reflection only gets called when parsing the config but not during the hot path which is the telemetry pipeline. So I'd say we don't have to worry too much about the performance impact of reflection here.

> How do you feel about functions.go containing only the types/funcs necessary to build functions, and then individual functions be added via their own files/modules?

Yup this sounds like a good idea to me. Thanks.

**Comment by TylerHelmuth** [comment]
> The reflection only gets called when parsing the config but not during the hot path which is the telemetry pipeline.

Good point. 

> Yup this sounds like a good idea to me. 

I will move forward with updating the reflection.

**Comment by TylerHelmuth** [comment]
@anuraaga I started playing around with moving functions into their own packages but quickly ran into import cycles: `functions.go` needs reference to each function and each function needs references to `expression.go` and `expression,go` needs reference to `functions.go` due to the `NewFunctionCall` call in `NewGetter`.  `conditions.go` throws in some extra complexity because it uses `NewGetter` as well.

We can keep each function in `common` and add the function file and test file for each, but then `common` gets huge.

Any thoughts on how to deal with the cycles so we can have each function as its own package?

**Comment by TylerHelmuth** [comment]
After working on this today I'm leaning towards leaving things flat in the common folder. Maybe all function files and their test file would be prefaced with func_ to make it easy to find the functions in common?

**Comment by anuraaga** [comment]
@TylerHelmuth Ah yeah I get burned by circular imports too often. I guess one idea would be to remove `common.DefaultFunctions()` and copy-paste that into the signal factories (I think it'd work but not sure without trying the code). It's probably not worth it though - `func_` prefix seems totally fine too.

**Comment by TylerHelmuth** [comment]
I like flat more so far.  Here is an example: https://github.com/TylerHelmuth/opentelemetry-collector-contrib/tree/issue-10101-refactor-functions-flat/processor/transformprocessor/internal/common

**Comment by TylerHelmuth** [comment]
I think I got all the functions flatten today.  I really like how the unit tests turned out.  Once a couple other PRs are merged I'll open one for the function flattening.  Once that is merged, I'll open a final PR to remove a bunch of duplicate unit tests.

**Comment by TylerHelmuth** [comment]
I'll get started on the test refactoring.  The function tests have been already been added to function-specific test files, so now there are a lot of tests to remove from the signal specific `functions_test.go` files.  I think for signals that the processor tests will be the best place to test using functions with specific signals; those tests are full integration tests through all the different parts of the processor.
