### ISSUE TITLE
Flaky Test - windows-msi

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10113]
This check fails frequently, without much information. [Example](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6438283411?check_suite_focus=true).

```
Run .\internal\buildscripts\packaging\msi\make.ps1 Confirm-MSI
  .\internal\buildscripts\packaging\msi\make.ps1 Confirm-MSI
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    TEST_RESULTS: testbed/tests/results/junit/results.xml
Error: The operation was canceled.
```

As far as I can tell, the operation is not typically canceled intentionally. Possibly it is due to a resource being reallocated, but otherwise this would appear to be a bug.

---

I would like to re-establish whether we actually want to have this check at all. We do not currently produce an MSI in the releases repo. @open-telemetry/collector-contrib-approvers, any opinions on whether this check is really necessary?

**Comment by dmitryax** [comment]
I think this test is important enough to have. It verify full cycle of collector service on Windows. I may be a bug in the make.ps1 script that should be fixed. 

Can we skip the test for now as we did we other flay tests?

**Comment by djaglowski** [comment]
Seems reasonable. I'll open a new PR that skips the job.

**Comment by pjanotti** [comment]
Notice that core repo currently has a test to validate the collector running as a Windows service, see https://github.com/open-telemetry/opentelemetry-collector/pull/9726
