### ISSUE TITLE
Add status header to all components

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#10116]
In an effort to make finding the state of each component easier, the README for each component should contain a table which includes:

- stability level (should be one of: [in development](https://github.com/open-telemetry/opentelemetry-collector#in-development), [alpha](https://github.com/open-telemetry/opentelemetry-collector#alpha), [beta](https://github.com/open-telemetry/opentelemetry-collector#beta), [stable](https://github.com/open-telemetry/opentelemetry-collector#stable) or [deprecated](https://github.com/open-telemetry/opentelemetry-collector#deprecated))
- supported pipelines
- distributions which contain the component (can be none or any combination of: [core](https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol), [contrib](https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib)). Additionally, if other distributions include these components, they can be listed here.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10006 for an example table with embedded links:

```
| Status                   |           |
| ------------------------ | --------- |
| Stability                | [beta]    |
| Supported pipeline types | traces    |
| Distributions            | [contrib] |

<README contents>

[beta]: https://github.com/open-telemetry/opentelemetry-collector#beta
[contrib]: https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib
```

**NOTE**: For extensions, please remove the `Supported pipeline types` as it does not apply.

### Exporters
- [x] #10302
- [x] #10303
- [x] #10304
- [x] #10305
- [x] #10306
- [x] #10307
- [x] #12341
- [x] #10309
- [x] #10310
- [x] #10311 
- [x] #10312 
- [x] #10313 
- [x] Add status header for elastic
- [x] #10158
- [x] #10315
- [x] #10265
- [x] #10316
- [x] #10317
- [x] #10318
- [x] #10319 
- [x] #10320 
- [x] #10155
- [x] #10264
- [x] #10322 
- [x] #10323
- [x] #10324 
- [x] #10325 
- [x] #10326 
- [x] #10327 
- [x] #10328 
- [x] #10329 
- [x] #10330 
- [x] #10331 
- [x] Add status header for sentry
- [x] #10333
- [x] Add status header for skywalking
- [x] Add status header for splunkhec
- [x] Add status header for sumologic
- [x] Add status header for tanzuobservability
- [x] #10338
- [x] Add status header for zipkin

### Extensions

- [x] #12142
- [x] Add status header for awsproxy
- [x] Add status header for basicauth
- [x] Add status header for bearertokenauth
- [x] Add status header for fluentbit
- [x] Add status header for healthcheck
- [x] Add status header for httpforwarder
- [x] #11139
- [x] Add status header for oauth2clientauth
- [x] #12153
- [x] #10342 
- [x] #12154
- [x] #12155
- [x] Add status header for storage

### Processors

- [x] #11120
- [x] Add status header for cumulativetodelta (#10004)
- [x] Add status header for deltatorate
- [x] #11120
- [x] Add status header for groupbyattrs
- [x] Add status header for groupbytrace
- [x] Add status header for k8sattributes
- [x] Add status header for logstransform
- [x] Add status header for metricsgeneration
- [x] Add status header for metricstransform
- [x] #10118
- [x] Add status header for redaction
- [x] Add status header for resourcedetection
- [x] Add status header for resource
- [x] Add status header for routing
- [x] #12131
- [x] Add status header for spanmetrics
- [x] #11120
- [x] #10006
- [x] #10002

### Receivers

- [x] Add status header for activedirectoryds
- [x] Add status header for apache
- [x] #10441
- [x] #10442
- [x] #10443
- [x] Add status header for awsxray
- [x] Add status header for bigip
- [x] #10446 
- [x] #10447
- [x] #10448
- [x] Add status header for couchbase
- [x] Add status header for couchdb
- [x] #10451
- [x] #10452
- [x] #10159
- [x] Add status header for expvar
- [x] Add status header for filelog
- [x] #10455 
- [x] Add status header for googlecloudpubsub
- [x] Add status header for googlecloudspanner
- [x] Add status header for hostmetrics
- [x] Add status header for iis
- [x] #10460 
- [x] #10156
- [x] Add status header for jmx
- [x] Add status header for journald
- [x] Add status header for k8scluster
- [x] #10464
- [x] #10478
- [x] #12095
- [x] #12097
- [x] #10899
- [x] Add status header for mongodbatlas
- [x] #10900
- [x] Add status header for mysql
- [x] #10901
- [x] Add status header for nsxt
- [x] #11096
- [x] #11097
- [x] Add status header for postgresql
- [x] #11099
- [x] #11100
- [x] Add status header for rabbitmq
- [x] #11102
- [x] Add status header for redis
- [x] #11103
- [x] #11104
- [x] #11105
- [x] #11106
- [x] #11107
- [x] Add status header for skywalking
- [x] #11108
- [x] Add status header for sqlserver
- [x] #11110
- [x] #10890
- [x] #10891
- [x] #10892
- [x] #11111
- [x] #11112
- [x] Add status header for zipkin
- [x] Add status header for zookeeper

**Comment by TylerHelmuth** [comment]
#10002 is open for transformprocessor

**Comment by pmm-sumo** [comment]
A nit, but the template in the issue description seems to have a mistake. It says:

```
[beta]: https://github.com/open-telemetry/opentelemetry-collector-contrib#beta
```

It should be:
```
[beta]: https://github.com/open-telemetry/opentelemetry-collector#beta
```

**Comment by TylerHelmuth** [comment]
@codeboten several PRs have been opened with the `-contrib` link, can you update the issue's description?

**Comment by codeboten** [comment]
@TylerHelmuth good point, updated 👍

**Comment by Frapschen** [comment]
miss the mezmoexporter?

**Comment by Frapschen** [comment]
I have created PRs for all exporter components, pls review :)

**Comment by jkowall** [comment]
What are the options for the “stability” header? What are the options for the "distribution" header?

Thanks!

**Comment by codeboten** [comment]
@jkowall I updated the description, please take a look

**Comment by Frapschen** [comment]
@codeboten I want to apply become a member of opentelemetry community,can you sponsored me?

**Comment by Frapschen** [comment]
> > @codeboten I want to apply become a member of opentelemetry community,can you sponsored me?
> 
> @Frapschen sure, open an issue in the community repo https://github.com/open-telemetry/community/blob/main/community-membership.md#member 👍🏻

thx,I have opend an issue and have been became a member of counmity.

**Comment by TylerHelmuth** [comment]
@codeboten should we update this issue to include the [Warning Section](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11052) situation?

**Comment by Frapschen** [comment]
fluentbit extension's status header has added.

**Comment by atoulme** [comment]
@codeboten I just ran through all remaining open items and closed them as all had been completed. I think this issue is ready to be marked complete.

**Comment by djaglowski** [comment]
Thanks to all who helped organize and complete this standardization effort!
