### ISSUE TITLE
[receiver/hostmetrics] load scraper tests are failing on Windows

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#10143]
`TestStartSampling` and `TestSampleLoad` in  receiver/hostmetricsreceiver/internal/scraper/loadscraper/load_scraper_windows_test.go are causing race condition.

- https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6478751037?check_suite_focus=true
- https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6479735884?check_suite_focus=true

**Comment by lootek** [comment]
Hello, I'd love to help, can I take this one?

**Comment by joshdover** [comment]
I think this is a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10030
