### ISSUE TITLE
[receiver/elasticsearch] Add integration test

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10165]
It should be possible to add a containerized integration test to this receiver.

**Comment by Frapschen** [comment]
hi, l'd to help it, how can I start? any example?

**Comment by dmitryax** [comment]
@Frapschen Ok, assigned to you

**Comment by BinaryFissionGames** [comment]
Hey @Frapschen, thanks for volunteering to help out.

The task is essentially to create an integration test that:
1. Starts an elasticsearch docker container
2. Initializes the elasticsearchreceiver component from it's factory
3. Scrapes metrics from the docker container
4. Validates that the expected metrics are scraped (using the [scrapertest package](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal/scrapertest))

As far as examples go, there are a few components out there that have integration tests using the same pattern.
For instance:

[Mysql receiver integration test](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8eec12f2688309fe4bf0b97ad73128ab12d72861/receiver/mysqlreceiver/integration_test.go)
[Nginx receiver integration test](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8eec12f2688309fe4bf0b97ad73128ab12d72861/receiver/nginxreceiver/integration_test.go)

**Comment by Frapschen** [comment]
ok, I wil  check these pattern and work on the es one.
