### ISSUE TITLE
[receiver/zookeeper] Flaky TestZookeeperMetricsScraperScrape test, fails on Windows sometimes

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#10171]
```
=== RUN   TestZookeeperMetricsScraperScrape/Test_correctness_with_v3.4.14
    scraper_test.go:269: 
        	Error Trace:	scraper_test.go:269
        	Error:      	Received unexpected error:
        	            	number of resources does not match
        	Test:       	TestZookeeperMetricsScraperScrape/Test_correctness_with_v3.4.14`
```

See https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6514438768?check_suite_focus=true

**Comment by dmitryax** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6514630275?check_suite_focus=true

**Comment by djaglowski** [comment]
Similar case here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6523457323?check_suite_focus=true#step:8:2301

**Comment by dmitryax** [comment]
Here again https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6528289367?check_suite_focus=true
