### ISSUE TITLE
[receiver/jaeger] incompatible behavior with original jaeger receiver

### ISSUE THREAD

**Issue by holycheater** [open-telemetry/opentelemetry-collector-contrib#10186]
**Describe the bug**

When receiving traces through jaeger grpc protocol, span process information can be lost because jaegertranslator only inspects batch.Process and ignores span.Process completely during conversion

This is incosistent with original receiver behavior:
https://github.com/jaegertracing/jaeger/blob/v1.34.1/cmd/collector/app/handler/grpc_handler.go#L45-L49

Spans can have their own process information attached to them and batches does not necessarily contain data from a single process.
It breaks some clients with some custom delivery agent when moving from jaeger grpc receiver to otlp jaegerreceiver

**What version did you use?**
v0.51.0

**Additional context**
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.51.0/pkg/translator/jaeger/jaegerproto_to_traces.go
I am not sure what would be the proper approach to address this, there's some magic going on with trying to group spans by instrumentation library during conversion in jaegertranslator

We're currently running patched version where each jaeger span from batch is converted to individual ResourceSpan (jaeger_process -> resource, span -> span).
I can make a PR with this solution or with a different one if you have something other in mind.

**Comment by bogdanov1609** [comment]
@dmitryax friendly reminder

**Comment by dmitryax** [comment]
Hey @bogdanov1609 unfortunately I don't have time to work on this at point. May be will take it in August. If you are interested, feel free to submit a PR.

**Comment by jpkrohling** [comment]
This sounds indeed like a bug, or oversight in the original implementation. The godoc for the model.Batch is very clear about this:

```go
// Note that both Span and Batch may contain a Process.
// This is different from the Thrift model which was only used
// for transport, because Proto model is also used by the backend
// as the domain model, where once a batch is received it is split
// into individual spans which are all processed independently,
// and therefore they all need a Process. As far as on-the-wire
// semantics, both Batch and Spans in the same message may contain
// their own instances of Process, with span.Process taking priority
// over batch.Process.
```

I'm working on a fix for this, but I think @pmm-sumo has faced something similar before, or mentioned the need to group things by resourcespans before. Just to make sure I'm not missing anything, would you be able to review my plan, @pmm-sumo? Here's the outline I have at the moment:

```go
	// re-group batches
	// this is needed as there might be a Process within Batch and Span at the same
	// time, with the span one taking precedence
	// as we only have it at one level in OpenTelemetry, ResourceSpans, we split
	// each batch into potentially multiple other batches, with the sum of their
	// processes as the key to a map.
	// step 1) iterate over the batches
	// step 2) for each batch, calculate the batch's process checksum and store
	// it on a map, with the checksum as the key and the process as the value
	// step 3) iterate the spans for a batch: if a given span has its own process,
	// calculate the checksum for the process and store it on the same map
	// step 4) each entry on the map becomes a ResourceSpan
```

**Comment by jpkrohling** [comment]
I just opened a PR addressing this issue.
