### ISSUE TITLE
exporter/loadbalancingexporter: make dns resolver interval and timeout configurable

### ISSUE THREAD

**Issue by jvilhuber** [open-telemetry/opentelemetry-collector-contrib#10199]
**Is your feature request related to a problem? Please describe.**
I frequently see these errors in my logs:
```
{"level":"warn","ts":1653102273.0902977,"caller":"loadbalancingexporter@v0.51.0/resolver_dns.go:106","msg":"failed to resolve","kind":"exporter","name":"loadbalancing","resolver":"dns","error":"i/o timeout"}
```
Seems at times the cluster may just be slow and the default 1-second (every 5 seconds) timeout is too short.

**Describe the solution you'd like**
Make the dns lookup interval and timeout configurable.

**Describe alternatives you've considered**
No alternative comes to mind. Making the timeout longer across the board may make other environments unstable.

**Additional context**

**Comment by TylerHelmuth** [comment]
Seems like a good addition to the config. @jvilhuber is this something you plan to contribute?

**Comment by jvilhuber** [comment]
I can certainly give it a go! I'm currently waiting for my company to approve the CLA.

**Comment by jvilhuber** [comment]
This was recently fixed/merged.
