### ISSUE TITLE
[processor/transform] Add AND and OR capability to WHERE condition

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#10195]
**Is your feature request related to a problem? Please describe.**
The transform processor currently accepts a WHERE clause with a single condition:

`set(name, "test") where name != "test"`

But there are times where multiple conditions are needed in order to filter to the correct data.

**Describe the solution you'd like**
The processor's grammar should be updated to allow ANDing and ORing together any number of conditions.  AND conditions should take precedence.  Conditions should be able to be grouped using `(` `)`

Example:
 `set(name, "test") where (name != "test" and attribute["test"] != "something") or resource.attribute["test"] == "something"`

**Comment by TylerHelmuth** [comment]
proposed labels: priority:p2, help wanted, proc: transformprocessor

**Comment by kentquirk** [comment]
I'm intending to start working on this one this week. I have parser experience and it feels like a place I can help fairly quickly.

**Comment by TylerHelmuth** [comment]
@kentquirk how are things coming along? Are you still able to work on this?

**Comment by kentquirk** [comment]
Yes. I apologize -- I had forgotten I was away all of last week. I expect to be able to work on it starting Friday.
