### ISSUE TITLE
Flaky Test - tailsamplingprocessor/TestConcurrentTraceArrival

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10205]
```
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor	3.415s
```

Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6555994409?check_suite_focus=true

**Comment by djaglowski** [comment]
Here again: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6578368988?check_suite_focus=true#step:8:2701

**Comment by djaglowski** [comment]
Another related failure: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6928043103?check_suite_focus=true#step:7:2360

**Comment by dgoscn** [comment]
Hi @jpkrohling this issue still open?

**Comment by jpkrohling** [comment]
I believe it is! Do you want to take this one?

**Comment by dgoscn** [comment]
Yes, can assign to me @jpkrohling

**Comment by djaglowski** [comment]
@dgoscn, assigned to you

**Comment by jpkrohling** [comment]
@dgoscn, are you still available to work on this one?

**Comment by dgoscn** [comment]
@jpkrohling sure. I will return the work on this issue. Thanks for the reminder

**Comment by dgoscn** [comment]
@jpkrohling I will have to let for someone else. If no one else assign, I want to go back to work on this as soon as possible

**Comment by dgoscn** [comment]
Hi @djaglowski How are you? Happy new year. Do you know if this scenario still happening? The log for the events are expired. 
Thanks

**Comment by bryan-aguilar** [comment]
@dgoscn I was looking through the processor and was wondering if have you been able to replicate these flaky test locally? I ran the tests for a while on my machine and did not see any failures. Running it on an Intel MBP

**Comment by dgoscn** [comment]
Hey @bryan-aguilar. Thanks for the message, this sounds really good. I didn't made the tests again. But, sure I will do. Until the moment, I believe if you do not face the error, we can advance based on some advance from @jpkrohling .
Thanks

**Comment by ZenoCC-Peng** [comment]
Hello, I am currently review this test.

Upon running the GitHub Action on my personal branch, there were no test failures.
Here is the link to the [GitHub Action result sheet](https://docs.google.com/spreadsheets/d/1tIKOZiSODWzstJzoQpeM_4L-Tlt1K1zWqOGyMd5Kmeg/edit#gid=0)

I suspect that someone may have modified the code.


If everything seems fine, I will proceed with removing the test.

**Comment by atoulme** [comment]
Please go ahead, thanks!

**Comment by jpkrohling** [comment]
Thanks!
