### ISSUE TITLE
exporter/loadbalancingexporter: use hashicorp/memberlist instead of DNS to create hashring

### ISSUE THREAD

**Issue by jvilhuber** [open-telemetry/opentelemetry-collector-contrib#10200]
**Is your feature request related to a problem? Please describe.**
Doing DNS lookups every 5 seconds seems to put some strain on the infrastructure. Also scaling events that change the number of pods may change where a traceID goes, causing disruption. I've been thinking of adding an HPA for the load-balancer front-end and the tail-sampling backends, and during a load-increase, a scale-up of the backends would probably lose a lot of traces when we need them most (we're getting more load).

Grafana/tempo ingesters/distributors use a memberlist mechanism to distribute traces in a more reliable way, and I suspect we should move the load-balancer more in that direction for more robust trace-distribution.

**Describe the solution you'd like**
Seems https://github.com/hashicorp/memberlist is a robust system, used a lot in the loki and tempo backends (and many other places).

**Describe alternatives you've considered**
None come to mind.

**Additional context**

**Comment by jpkrohling** [comment]
The load balancer was made with extensibility in mind. While the initial implementation had static members, an update to the component brought DNS lookups as an alternative resolver. Wouldn't gossip be a good third resolver, or do you anticipate deeper changes to the component?

**Comment by jvilhuber** [comment]
I haven't thought that deeply about it, nor do I know how grafana/tempo uses the hashring in great details, so I'm honestly not sure.
I wondered if the hashring isn't more than just a resolver: it determines which 'backend' instance is responsible for the trace. I.e. the resolver merely finds the IP addresses of the backends, and then some internal hashing (based on the number of backends) determines where the spans is sent. If the number of instances changes, so does the destination of the spans, which means that at a time of change, traces could get lost (or misfiled). A hashring MIGHT bring more stability here.
But this is conjecture, as, like I said, I'm not that well versed in the hashring stuff.

**Comment by jpkrohling** [comment]
> the resolver merely finds the IP addresses of the backends, and then some internal hashing (based on the number of backends) determines where the spans is sent

This is indeed the case.

> A hashring MIGHT bring more stability here

Not sure how so. Any changes to the number of backends will require the backend allocation to be rebalanced, no matter how the changes were detected (DNS, gossip, static file changes, etcd, ...) 

On the hashing algorithm itself, we are currently using Karger et al, which should be the most stable algorithm for this problem, impacting only about 30% of the hash spectrum on a rebalance operation. I am open to hearing other alternatives though, as I might not be up to speed with newer research in this area.

**Comment by jpkrohling** [comment]
I'm closing this one, as I'm not convinced we'd be better served with hashring instead of the current solution. If @jvilhuber has new information, I'll reopen this issue.
