### ISSUE TITLE
[pkg/stanza] Field syntax behavior when "attributes" or "resource" are specified

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10280]
`entry.Entry.Attributes` and `entry.Entry.Resource` have been migrated from `map[string]string` to `map[string]interface{}` (See open-telemetry/opentelemetry-log-collection#190). Correspondingly, "field syntax" has been enhanced such that users are able to refer to all fields contained within arbitrarily deep Attributes and Resource objects. 

For the most part, interacting with Attributes and Resource is the same as interacting with Body. Like the Body, there are special considerations when interacting with the "root" field. However, unlike the Body, the root field is a restricted data type (`map[string]interface{}`). This raises questions that are not addressed by the Body's implementation of the `entry.Field` interface. For example, is the following a valid configuration? If so, what is the expected behavior?

```yaml
type: copy
from: somewhere
to: attributes
```

For the time being, field syntax does not allow users to reference the root `attributes` or `resource` fields.

This issue contains an analysis of how field syntax should behave for Attributes and Resource when interacting with the "root" field. It proposes some broad guidelines as a starting point, and then layers on specific implementation recommendations for each operator or class of operators. The goal is to ensure robust and intuitive functionality.

## General Guidelines

1. Attributes and Resource should have the same or equivalent implementation of the `entry.Field` interface (`Get`, `Set`, `Delete`).
3. Operators should not rely on custom implementations of the Field interface. Rather, they should use _compositions_ of `Get`, `Set`, and `Delete`.
4. Operators may opt to disallow references to the root fields, for any or all field parameters.
5. All operators should clearly document, for each field parameter, the expected behavior when a root field is specified.
6. Field parameters should be validated at build time. Validity should not be dynamic. i.e. should not depend on the contents of a particular log entry. 

## `entry.Field` implementation for the "root" Attributes and Resource

`Get` should return the entire contents as `map[string]interface{}`.

`Set` should accept only `map[string]interface{}` and `map[string]string` as valid types. These should be "merged onto" the existing map. That is, this operation should be non destructive, except where there is a collision, in which case the old value is overwritten. (This is the current behavior for map values in the Body.)

`Delete` should replace the root field with `map[string]interface{}` and return the previous map.

## Specific Behaviors

The following addresses all current field parameters, across all operators in this library.

#### `syslog_input`

This operator contains a `syslog_parser`, which uses field parameters. The implementation of that parser will be inherited by this operator.

#### `parse_from`

All parsers have a `parse_from` field that must indicate a string value that will be parsed. 

Since `attributes` and `resource` are both maps, neither is a valid value for `parse_from`.

#### `parse_to`

Several parsers (`severity`, `time`, and `trace`) have implicit destinations and do not allow customization.

The remaining parsers (`regex`, `json`, `csv`, and `syslog`) always produce a map that must be assigned to a field. Therefore, it is valid to parse to Attributes or Resource. `parse_to: attributes` or `parse_to: resource` should perform a merge onto Attributes or Resource, respectively.

#### `add`

Can set the value of any field to any value. In theory, we could allow users to specify a map that they would "add" to Attributes or Resource. This could follow standard behavior by performing a merge. However, this behavior seems unintuitive, so I recommend that we disallow `field: attributes` and `field: resource`.

```yaml
type: add
value: 123
field: attributes # Not allowed - often invalid, always ambiguous
```

#### `copy`

The `to` field has exactly the same considerations as the `add` operator's `field`, so should follow the same rules. (Disallow `to: attributes` and `to: resource`)

```yaml
type: copy
from: somewhere
to: attributes # Not allowed - could be any value
```

Users may want to copy the entire Attributes or Resource map elsewhere. This is intuitive and presents no identified issues. I suggest that `from: attributes` and `from: resource` be allowed.

```yaml
type: copy
from: attributes
to: body.attributes_backup
```

#### `flatten`

Users may want to flatten the entire `attributes` or `resource` map. This is intuitive and presents no identified issues.

```yaml
type: flatten
field: attributes
```

#### `move`

The `to` field has exactly the same considerations as `add.field` and `copy.to`, so should follow the same rules.

```yaml
type: move
from: somewhere
to: attributes # Not allowed - could be any value
```

Users may want to "move" (copy and clear) the entire Attributes or Resource map. This is somewhat intuitive and presents no identified issues. I suggest that `from: attributes` and `from: resource` be allowed.

```yaml
type: move
from: attributes # replaced with empty map
to: body.attributes_backup
```

#### `recombine`

This operator exposes two fields to users. Both of these fields must refer to string values, so referencing `attributes` and `resource` should not be allowed here.

#### `remove`

This operator is unique in that it already has custom support for referencing `attributes` and `resource`. In both cases, the behavior is to clear out the entire map. I believe there should be no change to the behavior here, but we should rework the implementation so that it is not a custom implementation of `entry.Field`.

```yaml
type: remove
from: attributes # replaced with empty map
```

#### `retain`

This operator allows the user to specify a list of fields that should _not_ be deleted. All other fields are deleted.

Arguably, intuitive behavior would be to allow the user to specify `body`, `attributes`, and `resource` as individual items in the list. Doing so would retain the entire map.

```yaml
type: retain
from: 
  - attributes 
  - body.foo
  - body.bar
  # deletes all of resource, none of attributes, and all but foo and bar in body

```

#### Other

`filter` and `noop` do not expose field syntax to users at all.

`router` uses expressions, which can include fields. However, the end result is a boolean, so no manipulation is expected.

### Outputs

No output operators make use of field syntax.

**Comment by hwo411** [comment]
It'd be great to allow specifying `attributes` and `resource` as target. For our case, we want to supply attributes from the app and currently the only possible way is to copy attributes one by one from json log, which is quite cumbersome. It'd be great if we could copy the whole dictionary to attributes.

**Comment by nityanandagohain** [comment]
I think copy and move should allow moving to `attributes` and `resources`

eg:
```
type: move
from: body.temp
to: attributes
```

**Comment by djaglowski** [comment]
> I think copy and move should allow moving to `attributes` and `resources`
> 
> eg:
> 
> ```
> type: move
> from: body.temp
> to: attributes
> ```

The problem is that `attributes` and `resource` are maps, so you need to specify a key.

In your example, if `body.temp` is a map, then in theory we could merge it in. However, if it is any other type of value, the meaning is ambiguous. This is why guideline 5 exists - to clarify how we should handle this.

> 5. Field parameters should be validated at build time. Validity should not be dynamic. i.e. should not depend on the contents of a particular log entry.

**Comment by djaglowski** [comment]
I believe the current state of things has proven to be sufficient but we can use this issue in the future if design changes become necessary.
