### ISSUE TITLE
[pkg/stanza] Make log rotation awareness and file tailing usable as independent features

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#10286]
There are uses cases other that log file collection that needs these capabilities. See for example https://github.com/open-telemetry/opentelemetry-collector/discussions/2457

It would be nice to refactor the codebase to allow using just these features without the need to collect logs from files.

This likely requires tailing binary files, so not a line-oriented tailing.

**Comment by djaglowski** [comment]
Closed by #11076
