### ISSUE TITLE
[processor/transform] Disallow metric attribute transforms

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-collector-contrib#10290]
**Describe the bug**
The transform processor allows you to transform metrics attributes as follows:
```
# Limit to 100 distinct attributes
limit(attributes, 100)
# Truncate attribute values to 4096 characters
truncate_all(attributes, 4096)
```

However, as discussed in the [metrics sdk](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#attribute-limits), "attribute truncation or deletion could affect identity of metric time series and the topic requires further analysis", and therefore metric attribute are exempt from common attribute limits.

Until work is done to address aggregation of data when attributes are dropped, the transform processor shouldn't allow limiting or truncating metric attributes.

**Comment by TylerHelmuth** [comment]
@jack-berg is it only attributes or are resource attributes disallowed as well?

**Comment by jack-berg** [comment]
[Resources](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/common#exempt-entities) are exempt from SDK attribute limits, but there's nothing special about resource attributes for metrics versus traces or logs. If the transform processor supports limiting resource attributes for traces and logs, it shouldn't be a problem to do so for metrics as well.

**Comment by TylerHelmuth** [comment]
We decided to continue to allow the transform processor to modify metrics in ways that could be potentially dangerous.  To warn users of the potential risk we have added a new [Warnings Section to the README](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11052).  Other components in the collector have similar risks, so this Warnings section may become a standard in our new [Headings Standard](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10116)
