### ISSUE TITLE
Add spans to clickhouse exporter

### ISSUE THREAD

**Issue by bputt-e** [open-telemetry/opentelemetry-collector-contrib#10300]
**Is your feature request related to a problem? Please describe.**
We're interested in storing spans to clickhouse vs using something like ES or Loki/Tempo as it reduces architectural complexity and gives us more freedom with implementing wrappers around the database for visualizations within tools like grafana

**Describe the solution you'd like**
Looking to add spans as a supported option for clickhouse exporter

**Describe alternatives you've considered**
We're utilizing loki + tempo, ideally we could replace those with just clickhouse

**Comment by bputt-e** [comment]
@hanjm do you have plans to implement this in the future?

**Comment by hanjm** [comment]
@bputt-e  plan but i not have much time, would you like to contrib it ? 😄 

grafana-clickhouse-datasource support query clickhouse logs in explore UI. it will also be useful to search spans. https://github.com/grafana/clickhouse-datasource/issues/23

**Comment by bputt-e** [comment]
@hanjm what are your thoughts on the following table schemas, ignore the fact there's no indexes or materialized columns for things like http_status

Option 1
`
CREATE TABLE spanszz
(
    `traceId` String,
    `spanId` String,
    `parentSpanId` String,
    `name` String,
    `kind` String,
    `createdTime` DateTime default now(),
    `startTime` DateTime64(9),
    `endTime` DateTime64(9),
    `ResourceAttributes` Nested (
        Key LowCardinality(String),
        Value String
    ),
    `attributes` Nested (
        Key LowCardinality(String),
        Value Nested(
            stringValue Nullable(String),
            boolValue Nullable(Bool),
            intValue Nullable(UInt32),
            doubleValue Nullable(Float64),
            mapValue Map(String, String),
            arrayValue Array(String),
            byteValue Array(String)
        )
    )
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(startTime)
ORDER BY (traceId);
`

Option 2
`
CREATE TABLE spans
(
    `traceId` String,
    `spanId` String,
    `parentSpanId` String,
    `name` String,
    `kind` String,
    `createdTime` DateTime default now(),
    `startTime` DateTime64(9),
    `endTime` DateTime64(9),
    `resourceAttr` Map(LowCardinality(String), String),
    `stringAttr` Map(LowCardinality(String), String),
    `intAttr` Map(LowCardinality(String), UInt32),
    `doubleAttr` Map(LowCardinality(String), Float64),
    `boolAttr` Map(LowCardinality(String), Bool),
    `mapAttr` Map(LowCardinality(String), Map(String, String)),
    `arrayAttr` Map(LowCardinality(String), Array(String)),
    `byteAttr` Map(LowCardinality(String), Array(String))
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(startTime)
ORDER BY (traceId);
`

Option 3
`
CREATE TABLE spansz
(
    `traceId` String,
    `spanId` String,
    `parentSpanId` String,
    `name` String,
    `kind` String,
    `createdTime` DateTime default now(),
    `startTime` DateTime64(9),
    `endTime` DateTime64(9),
    `ResourceAttributes` Nested (
        Key LowCardinality(String),
        Value String
    ),
    `StringAttributes` Nested (
        Key LowCardinality(String),
        Value String
    ),
    `IntAttributes` Nested (
        Key LowCardinality(String),
        Value String
    ),
    `DoubleAttributes` Nested (
        Key LowCardinality(String),
        Value String
    ),
    `BoolAttributes` Nested (
        Key LowCardinality(String),
        Value String
    ),
    `MapAttributes` Nested (
        Key LowCardinality(String),
        Value String
    ),
    `ArrayAttributes` Nested (
        Key LowCardinality(String),
        Value String
    ),
    `ByteAttributes` Nested (
        Key LowCardinality(String),
        Value String
    )
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(startTime)
ORDER BY (traceId);
`

**Comment by hanjm** [comment]
@bputt-e 
In my practise, I think Option 2 is prefered. the map keys and values could use bloom filter secondary index, and the query SQL is `stringAttr['key']='value'`, simply than the nested type `stringAttr.Value[indexOf(stringAttr.Key, 'key')]`. 
the clickhouse map type is introduced in 2021 later, the clickhouse system logs tables has change nested type to map type . https://github.com/ClickHouse/ClickHouse/issues/18698

we can only use string and number(float) for map values, string type for search tags, number type for compare operation (>= <=), the complex type (map/array) could store as json string, clickhouse also provide useful json functions.
```
    `stringAttr` Map(LowCardinality(String), String),
    `doubleAttr` Map(LowCardinality(String), Float64),
```

**Comment by alvinhom** [comment]
It maybe helpful to explore storing attributes using the JSON object type with dynamic subcolumns:

https://clickhouse.com/docs/en/guides/developer/working-with-json/json-semi-structured

That way the data should be stored in the optimal format with the inferred type and queries can just use the dot notation like select event.tag.db.host from spans instead of using the string array notation.

**Comment by hanjm** [comment]
> It maybe helpful to explore storing attributes using the JSON object type with dynamic subcolumns:
> 
> https://clickhouse.com/docs/en/guides/developer/working-with-json/json-semi-structured
> 
> That way the data should be stored in the optimal format with the inferred type and queries can just use the dot notation like select event.tag.db.host from spans instead of using the string array notation.

It is a excited experiment feature, currently it's advantage is extracting JSON fields into dedicated columns, store as seperate native columns, useful for create primary/order key for specific column. but it cannot create secondary index like map, the map type could use bloom filter secondary index. 
IMO, the object('json') suitable for the common semantic convention attribute,  if object('json') could add full keys and values bloom filter index like map type in the feature, it will also suitable for custom span attribute.

**Comment by bputt-e** [comment]
we're experimenting with map atm to determine its long-term usefulness. We're staying away from json atm because it isn't supported for distributed tables which is what something like this would benefit from

A potential problem with json is that if you're dealing with multiple customers and one decides to name their tag xxx and accidentally puts in a numeric value and it gets generated as a new column, how would you handle cases where they fix the value to be string or if another customer comes in and their tag xxx is of another type? We're using a materialized column to set a "tenantId" based on the auth information passed to otel, so this affords us the ability to use the same table in the db. Maps afford us the ability to separate string/numeric fields upfront too

**Comment by alvinhom** [comment]
According to the Clickhouse documentation, the type inference will do type coercion:

"This sort of coercion is supported for most types that have variable representation e.g. Int, Float. If necessary, ClickHouse will unify to the higher bit type that allows all current values to be represented. If necessary, converting to a String represents the least precise definition."

I am not sure how putting this into a map is more flexible.  If the data type is inconsistent, you would have to coerce to the higher type and do type casting at the query level.   You would need the same thing for the map.

The main advantage of the JSON approach is the simplified query, and better storage and performance.  For performance, since each key:value attribute is actually stored as a database column, it gets the performance improvement of the columnar database that Clickhouse is.  If you are retrieving only a specific key(column), it only has to scan that column's data.  Whereas map, they have to scan the entire map.  It should have better performance compare to bloom filters.

According to the recent video by Altinity, they posted some performance number differences:  about 5x to 6x better performance using the JSON type data at query time versus non native type.  

https://www.youtube.com/watch?v=FWUKxLS5slc 

As for not supporting distributed table, that is a problem and hopefully will be fixed soon.  Not sure the ETA though.

**Comment by alvinhom** [comment]
BTW, for those that understand Mandarin Chinese, there is a video by BiliBili on how they are using Clickhouse for large scale for logs (trace is very similar).

https://www.youtube.com/watch?v=nSfzu8Q0B4I

They are using implicit maps, which basically flattens very key/value pair into separate columns.  Which is basically what the JSON data type is doing.  They have some performance number attached on their slide showing the performance improvements.

**Comment by alvinhom** [comment]
It should be easy to just filter out null values in the query.  I wrote a Python programs to load some of my trace spans from Elasticsearch into Clickhouse using the JSON schema, and the query with attributes are quite natural.  The query looks something like this:

SELECT 
        **event.tags.code.namespace,**
        count(*) AS total_count,
        avg(duration) AS avg_duration,
        quantile(0.9)(duration) AS p90_duration
FROM otel_spans 
WHERE startTime >= '1659137086' AND startTime <= '1659223486' 
AND event.process.serviceName = 'testdv1b-platform' 
AND **event.tags.code.namespace** != ''
GROUP BY **event.tags.code.namespace**;

**Comment by bputt-e** [comment]
The null concern was around performance because the number of columns would increase based on the distinct number of attributes....I suppose it might be a non-issue, though, clickhouse prefers an empty string over null

**Comment by alvinhom** [comment]
I don't think null or empty value will cause much storage bloat since it is columnar db and column can use run length encoding or other compression to compress empty/null values.

Query performance with separate columns (even with lots of null values) will be much better than a map.

**Comment by bputt-e** [comment]
Wondering if this should omit certain attributes (KvlistValue, ArrayValue, BytesValue) similar to elastic's exporter when they were a part of otel
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4a72901b7b7bea01a15a814f1c13961b7336069c/exporter/elasticexporter/internal/translator/elastic/utils.go#L31

Attribute listing
https://github.com/open-telemetry/opentelemetry-collector/blob/4998703dadd19fa91a88eabf7ccc68d728bee3fd/model/pdata/common.go#L136

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13442
