### ISSUE TITLE
[processor/transform] Improve processor's ability to handle enums

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#10349]
The transform processor currently has messy support for fields that are enums in the protobufs.  Some fields, like `metric.aggregation_temporality`, use the numeric representation in some functions but a string representation in others.  Other fields are accessed using pdata representation that don't allow comparison with the query language's parse fields.  For example, the where clause `... where kind == 2` does not work because `kind` is returned for comparison as an int32 but `2` is interpreted by the parser as an `int64`

The processor as a whole needs a solution for handling enums.  Some enums, like `severity_number`, should be able to be interacted with via the numeric representation so that comparisons like `<` and `>` can be used, but should also be able to be represented as a string for readability. Others enums, such as `aggregation_temporality` might only ever needs represented as a string.

All fields should be usable in a condition.  At the moment comparisons's of literal values in a condition are always string, int64, or float64, so we need a way to access enums so that they are comparable with at least one of these types.

I've reviewed the access functions for each signal and identified this fields as needing dealt with

**Traces**
- `kind`:  Currently accessed as an int32 so does not work in conditions.  Should it be accessible as a string?
- `status.code`:  Currently accessed as an int32 so does not work in conditions.  Should it be accessible as a string?

**Metrics**
- `metric.type`: Currently accessed as a string.  This field isn't a enum in the protos but is represented as a numeric in pdata so adding it here to be reviewed.
- `metric.aggregation_temporality`:  Accessed as a int64, but that makes it hard to interpret queries.  Should be allowed to use a string representation ("unspecified, "delta", and "cumulative").
- `flags`: Accessed as a uint32 so doesn't work in comparison.  Should it be accessible as a string?

**Logs**
- `severity_number`: Accessed as an int32 so doesn't work in conditions.  Should it be accessible as a string?

**Additional context**
There are other fields that have access bugs when being used in a condition, but I will open a separate issue for those.

**Comment by tigrannajaryan** [comment]
Here is a possible approach:
- Expose all enum fields as int64 in the language.
- Define all valid enum values as named symbolic `consts` that are injected into the execution context, i.e. referencing SEVERITY_ERROR in the language should result in int64 value of 17 used at runtime.
- Ideally substitution of const names to values happens at parsing time (have some sort of const symbol table).
- Enum fields thus can be accessed just like any other int64 field, but you can use consts for comparison or setting purposes resulting in nice syntax (e.g. `where Severity_Number>=SEVERITY_ERROR` or `where Severity_Number!=0` are both valid).
- `metric.type` can follow the same approach, i.e. represent as int64 number and define symbolic constants for the valid types.
- `flags` - not sure if we want uint32 as data type in the language. Maybe also represent as int64 of which the low 32bits are usable.

**Comment by TylerHelmuth** [comment]
I really like this approach.  I like the uniformity it gives across the board (all enums are int64) which will give function creators guarantees, while at the same allows the queries themselves to be human-readable.  Reviewing the parser it should be possible to add the constants to the grammar so they can be properly interpreted during parsing.
