### ISSUE TITLE
Remove deprecated 'gke' and 'gce' resource detectors after v0.54.0 is released

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#10348]
The replacement is to use the single 'gcp' resource detector.  See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10347.

**Comment by jpkrohling** [comment]
@jrcamp @Aneurysm9 @dashpole, is this still relevant?

**Comment by dashpole** [comment]
Yes, this is still relevant.
