### ISSUE TITLE
[Prometheus remote-write receiver] Create a receiver to send metrics using Prometheus remote-write API

### ISSUE THREAD

**Issue by carlosjgp** [open-telemetry/opentelemetry-collector-contrib#10358]
**Is your feature request related to a problem? Please describe.**
We are trying to design an architecture where the metrics, traces and logs collectors have as a little CPU and memory footprint as possible on the K8s clusters where we deploy them
```
Cluster client                                                      Centralised receivers
--------------------------------------------|                      |---------------------------------------------|
Prometheus -- remote-write--->| OTEL agent--|-----otlp mTLS------> |---> OTEL deployment--->|---> Thanos receive |
Apps ----------otel traces--->|             |                      |                        |---> Grafana Tempo  |
Promtail--------logs--------->|             |                      |                        |---> Grafana Loki   |
--------------------------------------------|                      |---------------------------------------------|
```

**Describe the solution you'd like**
Create a receiver that is able to expose a port compatible with [Prometheus Remote writer API](https://prometheus.io/docs/prometheus/latest/storage/#remote-storage-integrations) so I can still use Prometheus capabilities to collect metrics and OTEL agent to receive traces, decorate (processors) and route them to the correct tracing, metrics and logging storage

**Describe alternatives you've considered**
Use OTEL agent to collect metrics as a Prometheus replacement but Rules are not part of the integration and I also use PrometheusOperator, which [seems to have a receiver proposal](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6344) but still no Rules support.

Prometheus Rules are evaluated per cluster and sent to the centralised cluster where Thanos Ruler will evaluate them and contact AlertManager

For now, I'll send the metrics directly from Prometheus to Thanos receive over HTTPS with TLS auth

**Additional context**

**Comment by dmitryax** [comment]
cc @Aneurysm9

**Comment by dmitryax** [comment]
We discussed adding prometheus remote write capabilities to the receiver on the SIG meeting today. Everyone agrees that we need it. It should be implemented as another receiver called `prometheusremotewrite`. No one of the active OTel contributors has plans to work on it at this point. So any help would be appreciated. cc @bogdandrutu @Aneurysm9

**Comment by nlamirault** [comment]
Nice feature ! With this one we could use the whole Prometheus Operator stack and OpenTelemetry together.

**Comment by dmitryax** [comment]
We are still looking for contributors to implement this. @nlamirault @carlosjgp let us know if you are interested in doing it

**Comment by arajkumar** [comment]
IIUC, the following works has to be done for this,

1. Add translator for [prompb.TimeSeries => pmetric.Metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheusremotewrite) conversion
2. Add a receiver/prometheusremotewrite

May be I can give a try if nobody is actively working on this.

**Comment by jpkrohling** [comment]
@arajkumar, @kovrus will work on this one, but your help is appreciated I reviewing the PR once it's ready and in trying it out.

**Comment by jpkrohling** [comment]
I realized that we do not have a formal new component proposal for this. From #14751, this is the proposed configuration for this component:

```yaml
receivers:
  prometheusremotewrite:
    endpoint: 0.0.0.0:19291
```

@adamkubon, @Norbertwnuk, are you committed to being code maintainers for this module? If so, we just need a sponsor for this component, which would be a current approver willing to be a "backup" code owner. The process is outlined here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components

**Comment by fatsheep9146** [comment]
@adamkubon are you still working on this?

**Comment by kovrus** [comment]
@fatsheep9146 https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14751 tracking issue for this component.

**Comment by fatsheep9146** [comment]
> @fatsheep9146 #14751 tracking issue for this component. Shall we close #10358?

Ok :)

**Comment by tomatopunk** [comment]
Hello team,

I hope you are all doing well. The tracking issue #14751 was closed because this component did not have a sponsor. I am requesting to re-open this proposal, as I will continue the work. 

I have found a sponsor, @Andrzej Stencel.
