### ISSUE TITLE
Failed to start the extension: unable to start, otelcol state is 3

### ISSUE THREAD

**Issue by gr4vitonn** [open-telemetry/opentelemetry-collector-contrib#10352]
Hello there,

I'm sure it is not a bug, I'm just trying to seek help.

I got the following error: "Failed to start the extension: unable to start, otelcol state is 3".

I've tried to figure it out, but I found nothing useful here or on stackoverflow.

I have a java lambda what I'm trying to integrate with Honeycomb. I followed this guide: https://aws-otel.github.io/docs/getting-started/lambda/lambda-java

Please let me know if you need additional information. What I'm looking for here is a direction to be able to solve the problem.

**Comment by dmitryax** [comment]
@gr4vitonn please share your config. it's unclear what's the problem oethrwise

**Comment by jpkrohling** [comment]
I'm closing this as there hasn't been any further feedback from @gr4vitonn. Feel free to reopen if you have new information.
