### ISSUE TITLE
[receiver/jaeger] Flaky TestJaegerAgentUDP_ThriftCompact

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10368]
```
=== RUN   TestJaegerAgentUDP_ThriftCompact
    jaeger_agent_test.go:204: 
        	Error Trace:	jaeger_agent_test.go:204
        	            				jaeger_agent_test.go:53
        	Error:      	Received unexpected error:
        	            	listen udp :55256: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
        	Test:       	TestJaegerAgentUDP_ThriftCompact
        	Messages:   	Start failed
--- FAIL: TestJaegerAgentUDP_ThriftCompact (0.23s)
```
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6614143811?check_suite_focus=true#step:7:4448

**Comment by djaglowski** [comment]
Reopening, as this is still failing intermittently.

Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6863664900?check_suite_focus=true#step:7:4483

**Comment by jpkrohling** [comment]
@frzifus, would you like to pick this one up?

**Comment by frzifus** [comment]
For me it looks like there is something wrong in this area. Unfortunately ive no emulation or windows machine in place. 

@dgoscn would you like to give it a try?

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/ed4cafc263667b8b57436e6413d83e9caf2cb2d7/internal/common/testutil/testutil.go#L42-L57

**Comment by dgoscn** [comment]
Yes @frzifus of course. Thanks

**Comment by dgoscn** [comment]
Hi @djaglowski. How are you?

I had some trouble to replicate this error that you mentioned here. But, I made some tries. I will try to replicate here what I did and please, if what I made makes no sense, just say 🦖 thank you

---

So, what I did:

In the function **GetAvailableLocalNetworkAddress** located at `/internal/commom/testutil/testutil.go` I added the following for to check the values of the port

```
	portFound := false
	if runtime.GOOS == "windows" {
		exclusions = getExclusionsList(t)
               // The line below were added
		for _, pp := range exclusions {
			fmt.Printf("From %s to %s \n", pp.first, pp.last)
		}
	}
```

And I added another Println just to get the result of the endpoint declared right below the code above, more precisely in line 60 :

```
	var endpoint string
	for !portFound {
		endpoint = findAvailableAddress(t, network)
		_, port, err := net.SplitHostPort(endpoint)
		require.NoError(t, err)
		portFound = true
		if runtime.GOOS == "windows" {
			for _, pair := range exclusions {
				if port >= pair.first && port <= pair.last {
					portFound = false
					break
				}
			}
		}
	}
fmt.Println(endpoint) // <------ line added
```
I executed a `go test` just to check the output and to see if were throwing some error or showing some blocked port. But I got the following output, for instance:

![image](https://user-images.githubusercontent.com/8397519/190497741-93b945a3-c655-44aa-9cc7-06d736a4493b.png)

So, let's go back to the `receiver/jaegerreceiver/jaeger_agent_test.go` where the function mentioned is used: **TestJaegerAgentUDP_ThriftCompact**

I went to this path, and made a -failtest to the `go test -run` with count of 3000 for 10minutes and received the following scenario, but I also made the test with the count value 4000 and 5000 receiving the same output.:

 `go test -run TestJaegerAgentUDP_ThriftCompact -v -count 3000 -failfast` and got the:
 
 
![image](https://user-images.githubusercontent.com/8397519/190506849-31055b25-9616-4206-a67b-b9464596138f.png)


 
 I let the test running for some minutes in all of the tests, it pass! I decreased the number of -count to 1000
 
 
![image](https://user-images.githubusercontent.com/8397519/190507594-2fd40576-7df8-44fb-959d-ea67883dc984.png)

 
And after decresead to 100:

![image](https://user-images.githubusercontent.com/8397519/190501283-d5c2bcd1-234a-41eb-b416-b71ad0b04afb.png)


I noticed that if I run the -count with the value **100** or a number less than **1000**, I get success and for a higher than, I could get the timout printed above. 

So, when I run for example the --count for a higher number than 3000, sometimes I can get the error that you mentioned on the top of the issue. But it's not always that I got the error. I made some workarounds, killing some process using a port that was in use or something like that, allowing in firewall etc, but I think that is not the right answer.


![image](https://user-images.githubusercontent.com/8397519/190659315-81a084f7-2b53-471f-acfe-f6480ecfd354.png)

I was wondering to make a check if the port is already in use, if this returns true, we can skip the port or something like that...  How we are getting some block binds to UDP ports, I found this piece of code that "maybe" we can "reuse", make some changes and resolve this definitively.

![image](https://user-images.githubusercontent.com/8397519/190660692-11b28d9d-cf2a-4b31-bee7-ecc995250187.png)

The path for the code above:
`pkg/stanza/operator/input/udp/udp_test.go line` 165


Do you think that makes sense? 

Thank you

**Comment by djaglowski** [comment]
@dgoscn, thanks for looking into this. It's great that you've determined a way to reproduce the issue.

> I was wondering to make a check if the port is already in use, if this returns true, we can skip the port or something like that... How we are getting some block binds to UDP ports, I found this piece of code that "maybe" we can "reuse", make some changes and resolve this definitively.

I'm not sure we can solve the problem by validating the port independently of the actual test, because some (tiny) amount of time will pass before we attempt to use it. But perhaps you are suggesting we just recover and retry the test? That may be reasonable if limited to a small number of retries.

**Comment by jpkrohling** [comment]
I don't remember seeing this issue happening anymore, but I also don't remember having this fixed. I'm leaving it open for some more time.

**Comment by dgoscn** [comment]
great @jpkrohling

**Comment by jpkrohling** [comment]
Closing, as there haven't been any new reports about this. Feel free to reopen or comment if this happens again.
