### ISSUE TITLE
metricstransformprocessor - delta histograms result in empty metric descriptor and no values

### ISSUE THREAD

**Issue by ransoor2** [open-telemetry/opentelemetry-collector-contrib#10420]
**Describe the bug**
Its not possible to use histograms with delta temporality with  metricstransformprocessor:
Internally the processor

1.  [transforms](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/metricstransformprocessor/metrics_transform_processor.go#L220) all metrics to OC format (using a deprecated method)
2. process the OC metrics
3. transforms back to otlp metrics

The issue is that during the first transform to OC metric, delta histograms type is translated to [`ocmetrics.MetricDescriptor_GAUGE_DISTRIBUTION`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e6ec2dca5250f0014f16dc84e24020770ea94e1e/pkg/translator/opencensus/metrics_to_oc.go#L185), but when transforming back you get [`pmetric.MetricDataTypeNone`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e6ec2dca5250f0014f16dc84e24020770ea94e1e/pkg/translator/opencensus/oc_to_metrics.go#L189) which results in a corrupted metric

**Comment by TylerHelmuth** [comment]
@dmitryax will your conversion to OTLP within this processor fix this issue?

**Comment by dmitryax** [comment]
Yes, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10817 fixes it. @ransoor2 PTAL at the PR if you interested
