### ISSUE TITLE
"Getting In Touch" references disused resource

### ISSUE THREAD

**Issue by jsumners** [open-telemetry/opentelemetry-collector-contrib#10467]
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6574d2ffcbf2feb595e15eb3542c60e060136e9a/README.md?plain=1#L9

The "Getting In Touch" link in the README points to a Gitter.im channel that is clearly abandoned. That abandoned channel says to use an `#opentelemetry-collector` channel in a CNCF Slack instance. As far as I can tell, the channel in the Slack instance is actually `#otel-collector`.

The link in the README should point to a document that describes how to join the Slack instance and which channel to join upon connecting.

**Comment by jpkrohling** [comment]
@jsumners, how do you feel about sending a PR with the change?

**Comment by jsumners** [comment]
@MalaSundaramoorthy thank you.

@jpkrohling sorry, this got lost in my pile. Is the information I wrote above even correct?

**Comment by MalaSundaramoorthy** [comment]
Yes, I see "Getting In Touch" link has wrong URL. I will update the link with right Github channel in the README file page.
