### ISSUE TITLE
Windows ARM/ARM64 support

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector-contrib#10479]
**Is your feature request related to a problem? Please describe.**

Windows ARM64 build currently fails with following ([per this discussion](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9758#discussion_r886154269)):
```
# github.com/open-telemetry/opentelemetry-collector-contrib/pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters
pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/pdh.go:345:89: undefined: PDH_FMT_COUNTERVALUE_DOUBLE
pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:120:12: undefined: PDH_COUNTER_INFO
pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:148:12: undefined: PDH_FMT_COUNTERVALUE_DOUBLE
pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:171:15: [1 << 20]PDH_FMT_COUNTERVALUE_ITEM_DOUBLE used as value
pkg/winperfcounters/internal/third_party/telegraf/win_perf_counters/performance_query.go:171:24: undefined: PDH_FMT_COUNTERVALUE_ITEM_DOUBLE
```

**Describe the solution you'd like**
Provide support for ARM64 build on Windows.

**Comment by Chinwendu20** [comment]
Hello @pmm-sumo and @codeboten, could I please work on this?

**Comment by codeboten** [comment]
@Chinwendu20 all yours!

**Comment by Chinwendu20** [comment]
Thanks a lot

**Comment by Chinwendu20** [comment]
Hello all, please I would need some help. I thought it just involved removing windows/arm64 from the exclude key in goreleaser and build-test.yml. I have tried googling the error message, but I cannot still grasp what I should actually do to bring about the support. I saw an issue on golang's github that shows go has support for window/arm64 already.I would be glad for any pointers on how to resolve this issue. Thanks
