### ISSUE TITLE
go.mod files are misconfigured. "go get" command fails with error

### ISSUE THREAD

**Issue by lefelys** [open-telemetry/opentelemetry-collector-contrib#1053]
**Describe the bug**
go.mod files are misconfigured. `go get` command fails with error:

`invalid version: unknown revision 000000000000`

**Steps to reproduce**
`go get -u  github.com/open-telemetry/opentelemetry-collector-contrib`

**What did you expect to see?**
installed package 

**What did you see instead?**
```
go get -u  github.com/open-telemetry/opentelemetry-collector-contrib                            
go: github.com/open-telemetry/opentelemetry-collector-contrib upgrade => v0.10.0
go get: github.com/open-telemetry/opentelemetry-collector-contrib@v0.10.0 requires
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/alibabacloudlogserviceexporter@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**What version did you use?**
v0.10.0
v0.9.0

v0.8.0 is ok

**What config did you use?**
No config

**Environment**
MacOS 10.15.6
go 1.15.2

**Additional context**
Problem occurs with some inner packages too:
`go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter`
returns error because it has a dependency in go.mod:
`github.com/open-telemetry/opentelemetry-collector-contrib/internal/awsxray v0.0.0-00010101000000-000000000000`

Looking at the project - I don't think that inner submodules are so independent from each other - they could be referenced by directories without version freezing in go.mod

**Comment by bogdandrutu** [comment]
> Looking at the project - I don't think that inner submodules are so independent from each other - they could be referenced by directories without version freezing in go.mod

Can you elaborate on this?

**Comment by lefelys** [comment]
Having multiple go modules under the same project makes sense if you want these modules to have a different lifecycle. 
In this project it is not the case - modules cross-referenced locally with `replace` directive and it makes it impossible to use `go get` on them. So why not have single go.mod in root?

**Comment by andrewhsu** [comment]
closing this as a dup of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1217#issuecomment-708304231
