### ISSUE TITLE
[k8sclusterreceiver] Some metric units don't follow Otel semantic conventions

### ISSUE THREAD

**Issue by bertysentry** [open-telemetry/opentelemetry-collector-contrib#10553]
**Describe the bug**
Some metrics don't follow [Otel semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md)

**Steps to reproduce**
Nothing to reproduce. The problem lies in the specification of the receiver itself.

**What did you expect to see?**
Metrics that count objects should use units with brackets `{}` and not `1`

Example:
* `k8s.container.restarts` ==> `Unit: "{restarts}"`
* `k8s.cronjob.active_jobs` ==> `Unit: "{jobs}"`
* `k8s.job.active_pods` ==> `Unit: "{pods}"`
* etc.

**What did you see instead?**
Many metrics specify unit `1` to report a count of objects:
* `k8s.container.restarts`
* `k8s.cronjob.active_jobs`
* `k8s.job.active_pods`
* etc.

Unit `1` must be used only for fractions and ratios.

**What version did you use?**
Main branch

**What config did you use?**
N/A

**Environment**
N/A

**Additional context**
N/A

**Comment by dmitryax** [comment]
> For now the plan is to add a feature gate, which when enabled will change metric units.

I think we can go without a feature gate. It's unlikely that changing units will break many backends

**Comment by bertysentry** [comment]
According to the [general rules for semantic conventions](https://sentrysoftware.atlassian.net/browse/MSHW-6024?focusedCommentId=66998), unit `1` is used for *utilization* metrics, i.e. percentages, ratios, and fractions.

What you are trying to represent with `k8s.container.ready`, `k8s.pod.phase`, and `k8s.namespace.phase` is a *StateSet*, or an 
*Enum*, [which hasn't been implemented yet in OpenTelemetry](https://github.com/open-telemetry/opentelemetry-specification/issues/1712).

When there are 2 states only (true or false, it's simple, you can push `1` for true, and `0` for false, which works well with `k8s.container.ready`. **IMPORTANT**: Unit must be *empty*, and metric type must be *UpDownCounter* (users will typically use `sum(k8s.container.ready)` to count the number of containers that are ready).

When there are more than 2 states, it is recommended to push 0 or 1 for each possible values of the *enum* through a `state` attribute.

Example: when the pod is in the `running` phase, you push 5 datapoints:

* `k8s.pod.phase{state="pending"} 0
* `k8s.pod.phase{state="running"} 1
* `k8s.pod.phase{state="succeeded"} 0
* `k8s.pod.phase{state="failed"} 0
* `k8s.pod.phase{state="unknown"} 0

It's not optimal, but it's the only way until we got proper support for StateSet in OpenTelemetry!

In the above case too, the unit must be *empty*, and the metric type *UpDownCounter*.

Hope this helps!

**Comment by TylerHelmuth** [comment]
We could update mdatagen to allow no unit, but it'll need to be implemented as a `opt-in`.  We don't want to remove the warning you hit because it is making sure that contributors don't write bad metrics in most metric cases.  Maybe we need a new, optional, `excludeUnit` field?

**Comment by bertysentry** [comment]
@TylerHelmuth Well, "empty unit" should be totally supported, it's a legitimate use case. Not all numbers have a unit of measure. Mandating a unit for all metrics ends up leading developers to use wrong units ("1" in this case, while it must be empty), which will have consequences when these metrics are converted to, say, Prometheus. (having a unit of "1" will add the "_ratio" suffix to the Prometheus metric name).

**Comment by TylerHelmuth** [comment]
I believe the check exists today as a safeguard as most of the metrics that the collector scrapes via mdatagen use units.  I agree that we could allow mdatagen to produce metrics that don't have a unit.  I also think that since most metrics that the collector scrapes do have a unit, that disabling the unit check should be explict.  mdatagen should default to expecting a unit, and only allow no unit when explicitly told.

**Comment by bertysentry** [comment]
I respectfully disagree. If the specification doesn't mandate a unit, then mdatagen should not trigger any error when unit is empty. We could have an option to report metrics with an empty unit, but the default behavior should strictly follow the specifications.

Again: enforcing non-empty unit by default is the cause of bugs in receivers that specify units even when metrics don't need a unit.

**Comment by TylerHelmuth** [comment]
I'm curious which is worse, a metric including a unit when it should not, or a metric missing a unit it should have? We should protect against whichever scenario is worse. I was under the impression that not including a unit was a worse spec incursion that including a wrong unit.

**Comment by mx-psi** [comment]
> Unit 1 must be used only for fractions and ratios.

> According to the [general rules for semantic conventions](https://sentrysoftware.atlassian.net/browse/MSHW-6024?focusedCommentId=66998), unit 1 is used for utilization metrics, i.e. percentages, ratios, and fractions.

I can't access Sentry's Atlassian instance, but I don't think UCUM says that `1` must be used only for fractions are ratios. Where does this rule come from?

**Comment by bertysentry** [comment]
@mx-psi Sorry, the link was wrong (bad copy-paste). I edited my post with the correct link to OpenTelemetry's documentation:
https://opentelemetry.io/docs/specs/semconv/general/metrics-general/#instrument-units

> Instruments for utilization metrics (that measure the fraction out of a total) are dimensionless and SHOULD use the default unit 1 (the unity).

Now, 2 things to consider:

1. [UCUM](https://ucum.org/ucum) doesn't say much about *state sets* and *enumerations*, and very little about [arbitrary units](https://ucum.org/ucum#section-Arbitrary-Units).
2. The Otel-to-Prometheus conversion must append the unit to the metric name to produce a valid Prometheus metric name. For fractions and ratios, it appends the suffix `_ratio` to the Otel metric name when the Otel unit is `1`.

Considering these 2 points, I strongly recommend we don't specify a unit where it's not required by UCUM. If we put `1` for *state sets* and *enumerations*, we'll break the Otel-to-Prometheus conversion, which is a large part of our ecosystem.

**Comment by dmitryax** [comment]
> Considering these 2 points, I strongly recommend we don't specify a unit where it's not required by UCUM. If we put 1 for state sets and enumerations, we'll break the Otel-to-Prometheus conversion, which is a large part of our ecosystem.

This makes sense to me.

Potentially we can tweek the mdatagen to explicitly require `unit` field while allowing it to be `""`

**Comment by bertysentry** [comment]
> Potentially we can tweek the mdatagen to explicitly require unit field while allowing it to be ""

If feasible, that would be the best way to handle this, thank you @dmitryax!

**Comment by mx-psi** [comment]
> I've looked thru some mores docs and [Otel Metrics API ](https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument) says that Instrument units are optional:
> 
> > An optional unit of measure
> > ...
> > A unit of measure.
> > Users can provide a unit, but it is up to their discretion. Therefore, this API needs to be structured to accept a unit, but > MUST NOT obligate a user to provide one.
> 
> So I think we should allow empty units.

Thanks for looking this up. Taking a quick look at opentelemetry-go it seems like the unit is left empty if not specified by the user so I agree we can leave this empty.
