### ISSUE TITLE
[zookeeperreceiver] Some metric units don't follow Otel semantic conventions

### ISSUE THREAD

**Issue by bertysentry** [open-telemetry/opentelemetry-collector-contrib#10567]
**Describe the bug**
Some metrics don't follow [Otel semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md)

**Steps to reproduce**
Nothing to reproduce. The problem lies in the specification of the receiver itself.

**What did you expect to see?**
`zookeeper.latency.avg`, `zookeeper.latency.max` and `zookeeper.latency.min` should be expressed in seconds, with unit `s`, and value type *Double*

**What did you see instead?**
`zookeeper.latency.avg`, `zookeeper.latency.max` and `zookeeper.latency.min` are expressed in milliseconds.

**What version did you use?**
Main branch

**What config did you use?**
N/A

**Environment**
N/A

**Additional context**
N/A

**Comment by djaglowski** [comment]
@bertysentry can you point out more specifically why the current data model for these metrics is not adherent to the semantic conventions?

I think you may be calling these out because they are not modeled in base units (`s`), but I cannot find any language in the semantic conventions suggesting that they should be.

**Comment by bertysentry** [comment]
@djaglowski I'm sorry, I can't find any reference to any requirement of using base units in Otel's semantic conventions. It's weird because I'm pretty sure saw that while working on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10028. I must have got confused with OpenMetrics requirements. Sorry about that, I'll close this one!

**Comment by djaglowski** [comment]
Thanks @bertysentry. Appreciate all the effort you've put into validating the metrics on this and many other components!
