### ISSUE TITLE
New component: AMQP/RabbitMQ receiver and exporter to move OTLP data

### ISSUE THREAD

**Issue by corentinaltepe** [open-telemetry/opentelemetry-collector-contrib#10592]
## The purpose and use-cases of the new component

In case of an infrastructure where telemetry can only be tunneled through an AMQP RabbitMQ exchange, it'd be great if one could use the OPTL Collector on both ends of that tunnel to proxy (export and receive) the telemetry data. I believe this is what the [Kafka Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter) and the [Kafka Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kafkareceiver) are for, though please correct me if I'm wrong.

The existing [RabbitMQ Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/rabbitmqreceiver) does not serve that purpose. Instead, it is used to collect the RabbitMQ instance's own telemetry.

## Example configuration for the component

The architecture would look like this:
```mermaid
  graph LR;
      ProdApp-->OPTLCollectorRabbitMQExporter-->RabbitMQExchange-->OPTLCollectorRabbitMQReceiver-->Backend
```

## Related Architecture
With such contraints, one can use this architecture with logstash to push logs. It is also possible to design a custom made client/proxy to pull and push metrics, resembling what the [Prometheus PushProx](https://github.com/prometheus-community/PushProx) does, but over AMQP insteand of HTTP.
For reference, here's how the [logstash output](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-rabbitmq.html) (exporter) plugin, and the [logstash input](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-rabbitmq.html) plugin (receiver) can be configured.

## Telemetry data types supported

All three: traces, metrics and logs.

**Comment by realbucksavage** [comment]
I'm also looking for an RabbitMQ/AMQP0-9-1 exporter. @djaglowski I can work on both receiver and exported implementation as time permits.

**Comment by realbucksavage** [comment]
Is this addition still on the roadmap?

**Comment by realbucksavage** [comment]
To add some more context to it, the exporter can Protobuf serialized traces, metrics, and logs. The sample configuration can look something like this:

```yaml
exporters:
  amqp091:
    address: amqp://guest:guest@localhost:5672/
    exchange: otlp
    traces_routing_key: otlp.traces
    metrics_routing_key: otlp.metrics
    logs_routing_key: otlp.logs
```
