### ISSUE TITLE
K8S Processor: configure the list of ignored pod names

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector-contrib#1077]
**Is your feature request related to a problem? Please describe.**

Currently, the names of pods that should be ignored while tagging (typically denoting agents) are [hardcoded and noted as TODO](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/k8sprocessor/kube/kube.go#L38-L42)

**Describe the solution you'd like**

Provide extra configuration entry:
* `ignored_pod_names` - by default, `[jaeger-agent, jaeger-collector]`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by owais** [comment]
Makes sense to me but I'd create separate issues (and PRs) for these.

**Comment by pmm-sumo** [comment]
> Makes sense to me but I'd create separate issues (and PRs) for these.

Sure, edited the issue and put the other fields into https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1079 , https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1078 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1080

**Comment by owais** [comment]
Thanks for updating. This sounds good to me. Perhaps we can support regexes here or do you think it'd be overkill?

**Comment by owais** [comment]
Actually, let's not support regex in the first version. It'd be easy to add down the line if we feel the need but removing might break things for users.

**Comment by eunice98k** [comment]
Hi, I would like to work on this!

cc @alolita

**Comment by alolita** [comment]
Fixed. Closing issue.
