### ISSUE TITLE
K8S Processor: configure ip extraction using incoming connection source IP

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector-contrib#1078]
**Is your feature request related to a problem? Please describe.**

It would be nice to have the ability for enabling/disabling tagging using the incoming connection source IP (from context, if available). E.g. when resource is missing information about source IP and records are coming through an intermediate agent (another OpenTelemetry Collector instance, `fluentd`, etc.), tagging using connection source IP would make the incorrect pod assignment.

**Describe the solution you'd like**

Add a configuration entry, e.g.:

* `ip_extraction_by_source_enabled` - by default, `true`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by owais** [comment]
If we implement a slightly modified version of #1079, we probably don't need this.
