### ISSUE TITLE
K8S Processor: configure tag name with source of the IP address

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector-contrib#1079]
**Is your feature request related to a problem? Please describe.**

It would be good to introduce some flexibility into name of the tag which includes source IP. Currently, following tags are being considered:
* `k8s.pod.ip` - typically added when passthrough mode is employed
* `ip` - legacy passthrough mode tag, also used by some clients (e.g. Jaeger)
* `host.hostname` - used by some metrics sources (e.g. Prometheus) - currently enabled only for metrics

**Describe the solution you'd like**
Introduce following configuration entry:

* `ip_extraction_by_attribute_labels` - by default `[ip, k8s.pod.ip, host.hostname]`

**Describe alternatives you've considered**

Perhaps `host.hostname` can be used as an attribute extracted by default for metrics only (which would match the current behaviour, though make the code it bit more complicated)

**Additional context**
N/A

**Comment by owais** [comment]
We currently support all three of these in some form. Are there other examples users might want to add? If the list is well-known, may be we can support them out of the box without a config option?

**Comment by pmm-sumo** [comment]
> We currently support all three of these in some form. Are there other examples users might want to add? If the list is well-known, may be we can support them out of the box without a config option?

My thinking is that especially in case of logs there might be some custom tags containing the source IP address (and to make things more complex, at a [record level](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1080))

On the other hand, it might be premature to solve this problem now and we should get a set of real-life examples before starting working on this one

**Comment by pmm-sumo** [comment]
I have prepared a doc with my research and some context into this: https://docs.google.com/document/d/1QlFbXz0eQUaKXK1WrnEs3VqRkcPD2RAdXJdJMjnOSd8/edit# - also #1146 contains some alternative proposal of the config entry
