### ISSUE TITLE
[receiver/prometheus] Convert Summary metric into two monotonic sums.

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-collector-contrib#10824]
**Is your feature request related to a problem? Please describe.**
When collecting Vault metrics using prometheus, a `summary` metric type is collected for `vault_gcs_list`.  

Example:
```json
{
  "name":"vault_gcs_list",
  "description":"vault_gcs_list",
  "summary":{
     "dataPoints":[
        {
           "startTimeUnixNano":"1654606313865000000",
           "timeUnixNano":"1654606313865000000",
           "count":"95",
           "sum":4811.074604034424,
           "quantileValues":[
              {
                 "quantile":0.5,
                 "value":"NaN"
              },
              {
                 "quantile":0.9,
                 "value":"NaN"
              },
              {
                 "quantile":0.99,
                 "value":"NaN"
              }
           ]
        }
     ]
  }
}
```
I would like to split the `sum` and the `count`  into two separate monotonic sums.

**Describe the solution you'd like**
Perhaps an enhancement to the `transformprocessor` to allow a change from summary to other metric types.

**Comment by TylerHelmuth** [comment]
As discussed during the SIG call, the transform processor is the proper place to do this. @Mrod1598 are you going to work on this?

**Comment by Mrod1598** [comment]
> As discussed during the SIG call, the transform processor is the proper place to do this. @Mrod1598 are you going to work on this?

yes, currently working it out.
