### ISSUE TITLE
Influxdb json format support

### ISSUE THREAD

**Issue by Vishnuvardhan-9** [open-telemetry/opentelemetry-collector-contrib#10831]
Hello Team,

We tried and tested the otelcollector-contrib Influxdbreceiver and Influxdbexporter with line protocol and it is working good. Is there any work in progress to update the collector to work with JSON Format?

**Comment by codeboten** [comment]
pinging @jacobmarble as code owner

**Comment by jacobmarble** [comment]
@Vishnuvardhan-9 what JSON format are you looking for? I'm not aware of anything specific to InfluxDB.
