### ISSUE TITLE
[internal/scrapertest] Add sortation functions that correspond to comparison function

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10837]
To handle unordered slices of resources/scopes/datapoints, we should add sortation functions to this package, which could be called before comparisons are made. The sortation likely needs to be sensitive to the same CompareOptions so that expected variables (unpredictable values, times, etc) do not influence the sort. I'll open another issue for this.

_Originally posted by @djaglowski in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10828#issuecomment-1150154297_

**Comment by Frapschen** [comment]
I would like help it :)

**Comment by djaglowski** [comment]
Thanks @Frapschen. I'll assign this to you then.

**Comment by djaglowski** [comment]
Closed by #10922
