### ISSUE TITLE
observer.EndpointsWatcher should support multiple Notify listeners

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-collector-contrib#10830]
If a component wants to be notified of endpoints by an observer instance that is already subscribed to by another component (like a receiver creator: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d6042eda45ec9d8a5df1ae553388eaca67d9d16c/receiver/receivercreator/receiver.go#L109), it will silently fail as the current implementation of [`observer.EndpointsWatcher`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/observer/endpointswatcher.go) assumes it will only be used once and overwrites internal state on subsequent invocations.

**Describe the solution you'd like**
Support an arbitrary number of `EndpointsWatcher.ListAndWatch(listener observer.Notify)` invocations/listeners and add a new ~ `EndpointWatcher.Unsubscribe(listener observer.Notify)`* method to remove individual notifications. This likely requires adding a `Notify.ID()` method for registrant handling.

**Describe alternatives you've considered**
Not changing existing signatures while adding capability but usage of [`StopListAndWatch()` is globally destructive](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0c691295193854523240b609c0c3cc06f9202b41/extension/observer/endpointswatcher.go#L108).

**Comment by dmitryax** [comment]
@rmfitzpatrick do you plan to work on this one? we are triaging issue

**Comment by rmfitzpatrick** [comment]
Yes, I've started looking at it just now.
