### ISSUE TITLE
googlecloudpubsub receiver dropped support for pubsub Emulator

### ISSUE THREAD

**Issue by k7k0** [open-telemetry/opentelemetry-collector-contrib#10844]
**Describe the bug**
Pubsub emulator is not supported anymore by the receiver, as the `endpoint`  and `insecure` configurations were made private here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8391/files#diff-c3c2b69e4538d56891424468d9ffd5bd0dfb2cf4f0d7bbcfddd23b9f901d6d09

Pubsub Emulator support is crucial for automation tests and local development pipelines.

**Steps to reproduce**
Start the pubsub emulator by running `gcloud beta emulators pubsub start` (more info on the [official guide](https://cloud.google.com/pubsub/docs/emulator)) and configure the googlecloudpubsub receiver using `endpoint: localhost:8085`

**What did you expect to see?**
Collector connecting correctly to the pubsub subscription of the emulator.

**What did you see instead?**

```Error: '' has invalid keys: endpoint, insecure```

**What version did you use?**
Version: 0.53.0

**What config did you use?**
```
receivers:
  googlecloudpubsub:
    project: "my-project-id"
    endpoint: localhost:8085
    insecure: true
```

**Additional context**

**Comment by djaglowski** [comment]
cc: @alexvanboxel as code owner

**Comment by alexvanboxel** [comment]
I had to remove them, but I don't remember why. We were not actively using them, so couldn't guarantee it worked. You will need to ping some main committers to make the tests run.
