### ISSUE TITLE
[receiver/rabbitmq] Add integration test

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10865]
The task is essentially to create an integration test that:
1. Starts an rabbitmq docker container
2. Initializes the rabbitmqreceiver component from it's factory
3. Scrapes metrics from the docker container
4. Validates that the expected metrics are scraped (using the [scrapertest package](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal/scrapertest))

As far as examples go, there are a few components out there that have integration tests using the same pattern.
For instance:

[Mysql receiver integration test](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8eec12f2688309fe4bf0b97ad73128ab12d72861/receiver/mysqlreceiver/integration_test.go)
[Nginx receiver integration test](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8eec12f2688309fe4bf0b97ad73128ab12d72861/receiver/nginxreceiver/integration_test.go)

_Adapted from post by @BinaryFissionGames in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10165#issuecomment-1133257413_

**Comment by Frapschen** [comment]
hi，I can help it like the es receiver :)
