### ISSUE TITLE
stackdriver exporter: Metrics are sent to Cloud Operations as Custom which has a limited quota

### ISSUE THREAD

**Issue by charles-bluett** [open-telemetry/opentelemetry-collector-contrib#1087]
There are separate quotas for external and custom metrics endpoints. Metrics from Prometheus are sent to Google as external.googleapis.com, but openTelemetry sends them as custom.googleapis.com.

Custom has a limit of 500 descriptors.
External has a limit of 10,000

https://cloud.google.com/monitoring/quotas

**Comment by Noremac201** [comment]
From what I can tell this is configurable by the `Prefix` config value.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/stackdriverexporter/config.go#L27

**Comment by charles-bluett** [comment]
Thanks.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/stackdriverexporter/README.md
Refers to the metric prefix as `metric_prefix (optional): MetricPrefix overrides the prefix of a Stackdriver metric names. `

Which is a bit confusing.
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors#MetricDescriptor
Implies that what you are setting is the metric type. 

I will submit a PR to change the readme to make this more clear, with an example and the default value.

**Comment by andrewhsu** [comment]
from the triage mtg today, looks like this can be closed because #1200 merged. feel free to reopen if not the case.
