### ISSUE TITLE
[internal/scrapertest] Add plog.Log comparison and golden functions

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#10896]
The [scrapertest](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal/scrapertest) package contains functions for comparing metrics, which is very useful when writing tests.

We should extend this package to also include similar functions for logs (ReadLogs, WriteLogs, and CompareLogs).

This package should also be renamed to clarify that it's useful beyond testing metric scrapers.

See: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10854#discussion_r894615687

**Comment by SergeyParamoshkin** [comment]
@djaglowski I try solve this, but I need help with tests

**Comment by jackycsl** [comment]
Can you please assign me to this issue?

**Comment by fatsheep9146** [comment]
Thanks! It's yours! @jackycsl
