### ISSUE TITLE
How to implement zookeeper server.state metrics in zookeeperreceiver?

### ISSUE THREAD

**Issue by justindesilets** [open-telemetry/opentelemetry-collector-contrib#10898]
**Describe the bug**
Zookeeper Receiver [documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/zookeeperreceiver/documentation.md) describes the resource attributes but does not show how to implement them. I am looking to enable the `server.state` metrics.

**Steps to reproduce**
If you try and use `server.state` as a metric if fails validation.

**What did you expect to see?**
A simple config example showing the correct key used to enable this metric.

**What did you see instead?**
No code example

**What version did you use?**
Version: v0.53.0

**What config did you use?**
```yaml
receivers:
  zookeeper:
    endpoint: "localhost:2181"
    collection_interval: 10s
```

**Environment**
OS: CentOS 7.9 / otelcol-contrib_0.53.0_linux_amd64.rpm

**Additional context**
I've tried to work backwards through the receiver to see if I could find the specific key required to enable this metric but I just don't know Go well enough yet. I would be happy to update the docs if I had code examples to work with.

**Comment by djaglowski** [comment]
@justindesilets, all metrics that this receiver collects are enabled by default. 

Since `server.state` is a resource attribute, you will find it in a different part of the same data packet. Roughly:
```
resource:
  attributes:
    zk.version: ...
    server.state: standalone
  metrics:
  - ...
  - ...

**Comment by justindesilets** [comment]
Using my above configuration, I am only seeing these zookeeper based metrics being exported:
```
# HELP zookeeper_connection_active Number of active clients connected to a ZooKeeper server.
# TYPE zookeeper_connection_active gauge
zookeeper_connection_active 3
# HELP zookeeper_data_tree_ephemeral_node_count Number of ephemeral nodes that a ZooKeeper server has in its data tree.
# TYPE zookeeper_data_tree_ephemeral_node_count gauge
zookeeper_data_tree_ephemeral_node_count 5
# HELP zookeeper_data_tree_size Size of data in bytes that a ZooKeeper server has in its data tree.
# TYPE zookeeper_data_tree_size gauge
zookeeper_data_tree_size 350271
# HELP zookeeper_file_descriptor_limit Maximum number of file descriptors that a ZooKeeper server can open.
# TYPE zookeeper_file_descriptor_limit gauge
zookeeper_file_descriptor_limit 100000
# HELP zookeeper_file_descriptor_open Number of file descriptors that a ZooKeeper server has open.
# TYPE zookeeper_file_descriptor_open gauge
zookeeper_file_descriptor_open 143
# HELP zookeeper_latency_avg Average time in milliseconds for requests to be processed.
# TYPE zookeeper_latency_avg gauge
zookeeper_latency_avg 0
# HELP zookeeper_latency_max Maximum time in milliseconds for requests to be processed.
# TYPE zookeeper_latency_max gauge
zookeeper_latency_max 17
# HELP zookeeper_latency_min Minimum time in milliseconds for requests to be processed.
# TYPE zookeeper_latency_min gauge
zookeeper_latency_min 0
# HELP zookeeper_packet_count The number of ZooKeeper packets received or sent by a server.
# TYPE zookeeper_packet_count counter
zookeeper_packet_count{direction="received"} 851558
zookeeper_packet_count{direction="sent"} 851557
# HELP zookeeper_request_active Number of currently executing requests.
# TYPE zookeeper_request_active gauge
zookeeper_request_active 0
# HELP zookeeper_watch_count Number of watches placed on Z-Nodes on a ZooKeeper server.
# TYPE zookeeper_watch_count gauge
zookeeper_watch_count 4
# HELP zookeeper_znode_count Number of z-nodes that a ZooKeeper server has in its data tree.
# TYPE zookeeper_znode_count gauge
zookeeper_znode_count 3759
```
Currently I am running the `confluent-zookeeper-6.2.2-1` if that has any possible impact for these metrics. Is there anything I could be overlooking that is preventing the server state metric from being exported. I had been using a `metricstransform` but I disabled it for this test to take it out of the equation.

**Comment by justindesilets** [comment]
To add some additional information, here are the results of querying this specific zookeeper.
```
echo "mntr" | nc localhost 2181
zk_version	3.5.9-83df9301aa5c2a5d284a9940177808c01bc35cef, built on 01/06/2021 20:03 GMT
zk_avg_latency	0
zk_max_latency	17
zk_min_latency	0
zk_packets_received	867807
zk_packets_sent	867806
zk_num_alive_connections	3
zk_outstanding_requests	0
zk_server_state	follower
zk_znode_count	3759
zk_watch_count	4
zk_ephemerals_count	5
zk_approximate_data_size	350271
zk_open_file_descriptor_count	143
zk_max_file_descriptor_count	100000
```

**Comment by djaglowski** [comment]
> preventing the server state metric from being exported

To be clear, this receiver does not export a server state metric. 

There is a `server.state` _resource attribute_, which you will find it in a different part of the result. Please see example [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10898#issuecomment-1159114103).

**Comment by djaglowski** [comment]
Closing this, as there appears to be no action to take.
