### ISSUE TITLE
[receiver/carbon] Flaky Test - Test_Server_ListenAndServe/udp

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10916]
```
=== RUN   Test_Server_ListenAndServe/udp
    server_test.go:63: 
        	Error Trace:	server_test.go:63
        	Error:      	Received unexpected error:
        	            	listen udp 127.0.0.1:60411: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
        	Test:       	Test_Server_ListenAndServe/udp
--- FAIL: Test_Server_ListenAndServe (0.01s)
    --- PASS: Test_Server_ListenAndServe/tcp (0.01s)
    --- FAIL: Test_Server_ListenAndServe/udp (0.00s)
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/carbonreceiver/transport	0.062s
```

Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6862350950?check_suite_focus=true#step:7:951

**Comment by djaglowski** [comment]
Possibly related to #1426, #10151, #10872. cc @bogdandrutu

**Comment by jspaleta** [comment]
pardon,
Looking at the testutil function being used to determine available ports.... it looks like the testutil function has tcp baked in.  But this test is meant to be a udp service.

Does the testutil function  `findAvailableAddress` appears to have `tcp` hardcoded in the `net.listen` call.

There doesn't appear to be a way to instruct the testutil functions to search for a free udp port.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6321d0d76e91a312b409a32df4f4ebe6193cd290/internal/common/testutil/testutil.go#L70

**Comment by djaglowski** [comment]
@jspaleta, thanks for looking into this. Are you willing to submit a PR for this? If so, I will assign the issue to you.

**Comment by jspaleta** [comment]
> @jspaleta, thanks for looking into this. Are you willing to submit a PR for this? If so, I will assign the issue to you.

Hey,
I'm sort of new in the otel space.  My preference would be to fix up the common testing utilities so it can work with udp(or any network the net.listen supports) as well, but that's a potential breaking change across a lot of tests as I would need to extend the logic of the testing utility so you can/must specify the network you want to listen on. I guess I could have it fallback to tcp if unspecified.

**Comment by jspaleta** [comment]
@djaglowski you can assign me, I think I'm up to speed enough know to do a PR to extend the test suite.

**Comment by jspaleta** [comment]
@djaglowski 
PR #12888 is up now with refactored testutil.  
The carbon and statsd tests will need to be modified after this PR is merged to make use of the new testutil function provided in the PR.

**Comment by jspaleta** [comment]
okay with this merged, I can now open the PRs to fix up the disabled tests for carbon an statsd

**Comment by jspaleta** [comment]
@djaglowski 
PR #12901 is up now with the changes to re-enable the udp listen service test for carbon and statsd receivers

**Comment by bogdandrutu** [comment]
@jspaleta PR does not have the effect we want, reverting now.

**Comment by jspaleta** [comment]
@bogdandrutu,
oh no that's unfortunate.
Is there a test log with error output I can look at with go file line context for where the failure is happening.  The UDP issue was definitely a real race issue..but there maybe another race.

**Comment by jspaleta** [comment]
@bogdandrutu 
is the problem happening for both carbon and statsd receiver?

**Comment by jspaleta** [comment]
Okay I've identified a bug in the reciever tests. It has noth ing to do with the udp port binding, which was a potential other problem.

The new test failure happens when the UDPserver reads in a 0 byte length message from its UDP packet connection. The deferred waitGroup.Done(), but there is not msg copied into the msg channel. 

I'll work on refactoring the tests now to catch this.

**Comment by jspaleta** [comment]
@djaglowski 
new PR up #12919  with additional race condition protection in place.

**Comment by djaglowski** [comment]
Thanks for digging into this @jspaleta.
