### ISSUE TITLE
Google Cloud Exporter removes attributes from log entries

### ISSUE THREAD

**Issue by jsirianni** [open-telemetry/opentelemetry-collector-contrib#10924]
**Describe the bug**

When sending logs to Google Cloud Logging, attributes are dropped from the log entry. When using logging exporter, attributes are present. 

**Steps to reproduce**

Create a configuration with `filelog` receiver and `googlecloud` exporter. The filelog receiver will create an attribute called `log.file.name`, which will be dropped by the Google exporter.

**What did you expect to see?**

The log data model suggests that `body` should remain a string representation of the log body while attributes should contain parsed values and useful metadata such as `log.file.name`. I would expect these values to be present within the Google Cloud Logging platform.

```
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: 2022-06-10T15:56:04.178-0400        DEBUG        loggingexporter/logging_exporter.go:82        ResourceLog #0
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Resource SchemaURL: https://opentelemetry.io/schemas/1.6.1
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Resource labels:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]:      -> host.name: STRING(fedora)
Jun 10 15:56:04 fedora observiq-otel-collector[499827]:      -> os.type: STRING(linux)
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: ScopeLogs #0
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: ScopeLogs SchemaURL:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: InstrumentationScope
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: LogRecord #0
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: ObservedTimestamp: 2022-06-10 19:56:04.076019131 +0000 UTC
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Timestamp: 1970-01-01 00:00:00 +0000 UTC
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Severity:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Body: a test message 2
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Attributes:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]:      -> log_type: STRING(file)
Jun 10 15:56:04 fedora observiq-otel-collector[499827]:      -> log.file.name: STRING(messages)
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Trace ID:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Span ID:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Flags: 0
```

**What did you see instead?**

The attributes are missing from the log entry within Google's Logging interface. 

![173367684-c0ef3cb1-8401-4c1d-bf21-791583d2a7b2](https://user-images.githubusercontent.com/23043836/173396428-63f786d3-4648-4f31-8f36-7c80da78668e.png)

**What version did you use?**

Contrib v0.53.0 compiled from source.

**What config did you use?**

```yaml
receivers:
  filelog:
    include: [ ./in ]
    start_at: beginning

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  attributes:
    actions:
      - key: gcp.log_name
        action: insert
        value: test

exporters:
  logging:
    loglevel: debug

  googlecloud:

service:
  pipelines:
    logs:
      receivers:
      - filelog
      processors:
      - resourcedetection
      - attributes  
      exporters:
      - googlecloud
      - logging
```

**Environment**

Go 1.17
Fedora 35

**Additional context**

The code for the Google exporter lives here, so I filed an issue which may contain more context: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/423

**Comment by jsirianni** [comment]
This may be fixed soon, see comment here: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/423

**Comment by damemi** [comment]
> This may be fixed soon, see comment here: [GoogleCloudPlatform/opentelemetry-operations-go#423](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/423)

Yup, that should be included in the next bump of GCP deps here
