### ISSUE TITLE
Exporting metdata of the collected data

### ISSUE THREAD

**Issue by jainaashish** [open-telemetry/opentelemetry-collector-contrib#10927]
Hi

Is there a way to export metadata of the collected data from OpenTelemetry collector? Fo example, for collected metric data, I want to know what is the metric name? associated Tags? timestamp of the data? etc... 

Is there already an extension which can help get this metadata? if not, is it possible to build such extension with current features? Appreciate any help or pointers in this regard.

**Comment by djaglowski** [comment]
@jainaashish, there is not currently, and I'm not aware of any plans at this point.

One pattern you may find useful is the `metadata.yaml` file that many metric-producing components maintain. [Example](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/rabbitmqreceiver/metadata.yaml) Perhaps some automation around these files may be sufficient.
