### ISSUE TITLE
TestMetrics in observability_test fails

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#1093]
The test seems unstable:
```
--- FAIL: TestMetrics (2.00s)
    observability_test.go:93: timedout waiting for metrics to arrive
FAIL
```

See https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/4074/workflows/992b2641-acb8-497e-a4e2-0e31e2d19306/jobs/28575

**Comment by tigrannajaryan** [comment]
Again: https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/5355/workflows/03070cb8-1734-4d07-a2f7-8998e4a83bf6/jobs/40363

**Comment by jpkrohling** [comment]
This is still failing:
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/5949/workflows/e2506093-59d4-47ea-9c22-f62d91f52e0f/jobs/46628

**Comment by jpkrohling** [comment]
cc owners (@owais @dmitryax @pmm-sumo)

**Comment by tigrannajaryan** [comment]
Failed again: https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/12215/workflows/b31e4f5f-5810-4ded-b464-5db5b9e0a750/jobs/104614

@owais can you help fix this since you are the author?

**Comment by pmalek-sumo** [comment]
I've pushed my attempt at fixing this issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3380

PTAL
