### ISSUE TITLE
[receiver/awscontainerinsightreceiver] Dead links

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10990]
```
(cd receiver/awscontainerinsightreceiver && make checklinks)

FILE: ./README.md
  [✖] (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html)

  6 links checked.

  ERROR: 1 dead links found!
  [✖] (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html) → Status: 400

FILE: ./design.md

  2 links checked.
```

**Comment by bryan-aguilar** [comment]
You can assign this to me and I will take a look at updating the links.

**Comment by bryan-aguilar** [comment]
This can probably be closed, this link is not dead. @djaglowski

**Comment by djaglowski** [comment]
Thanks for checking it @bryan-aguilar.

I'm going to keep this issue open until we figure out how to configure/fix the tooling such that it will not falsely report an error on this.

**Comment by cuichenli** [comment]
it is treated as dead due to the extra parentheses 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/16de0ab55f9b10f6704d1558fd23a84c06bff73b/receiver/awscontainerinsightreceiver/README.md?plain=1#L4
I will file a PR to fix it
