### ISSUE TITLE
[receiver/redisreceiver] Instructions for contributing more metrics

### ISSUE THREAD

**Issue by singku** [open-telemetry/opentelemetry-collector-contrib#11025]
**Describe the bug**
In our project, we would like Redisreceiver to collect more metrics like role, redis_version etc. Thought we should contribute directly to redisreceiver for adding them. I noticed that we can use mdatagen to generate those missing metrics by adding definitions in metadata.yaml. But I didn't see detailed instructions on how to re-generate metrics files. Do we have it somewhere I didn't see? Or can we add them?

**Comment by codeboten** [comment]
@singku some additional information about how to use mdatagen is available here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/mdatagen#metadata-generator

It would be great to information about adding metrics to CONTRIBUTING.md, can I assign this issue to you?

**Comment by singku** [comment]
@codeboten see pull/11043
