### ISSUE TITLE
New receiver that can tail a oltp json-file from disk

### ISSUE THREAD

**Issue by hterik** [open-telemetry/opentelemetry-collector-contrib#11062]
**Is your feature request related to a problem? Please describe.**
We are running some test suites against a distributed embedded system. This test harness is mostly run offline (containerized), manually by testers. When some interesting event happens, we want to upload the results to a central database, some of these results include traces, that get uploaded to a Tempo instance consuming OLTP.

To handle the offline scenario, we are thinking about exporting OLTP traces to a json file. 
They are exported from application to disk using https://opentelemetry-python.readthedocs.io/en/stable/sdk/trace.export.html#opentelemetry.sdk.trace.export.ConsoleSpanExporter with stream argument set to a file instead of stdout.
It comes out looking like what is described in https://opentelemetry.io/docs/concepts/signals/traces/ 

But i have found no way to easily consume such a json file.

**Describe the solution you'd like**
It would be nice if opentelemetry-collector could have a new receiver type. By finding json-files containing traces in a directory and process them as though they were received by any other receiver.
For log-files, this is a common pattern, consider examples Filebeat/Promtail/fluentd.
This method makes it easy to share traces from application container to exporter container via volume mounts, instead of setting up network between them.

**Describe alternatives you've considered**
Maybe this is the completely wrong approach to this? Should i just run oltp receiver listening to localhost instead?
What is problematic is that in such case the receiver+exporter is always on. This will generate insane amount of traces in our scenario, we only want to upload those that are relevant. I have briefly explored tail-based sampling but not enough in depth to see if it is enough yet.

**Comment by mx-psi** [comment]
Since this is about a new component, I have transferred it to contrib. Maybe #7840 is what you are looking for?

**Comment by djaglowski** [comment]
Closed by #7840
