### ISSUE TITLE
[extension/httpforwarder] Add testdata/config.yaml

### ISSUE THREAD

**Issue by SergeyParamoshkin** [open-telemetry/opentelemetry-collector-contrib#11128]
- [x]  create the `testdata` directory 
- [x] `testdata/config.yaml`, which is a sample configuration file for the collector
- [ ] add a test that loads and validates the config.yaml file

[Here is an example.](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11018/files)

_Originally posted by @djaglowski in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10973#issuecomment-1159142782_

**Comment by atoulme** [comment]
The test is now implemented here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/62da158b2565d8f6a2694d6f6922698a083f09fe/extension/httpforwarder/config_test.go#L30

I think this issue can be closed.
