### ISSUE TITLE
GCP Exporter should associate logs with traces 

### ISSUE THREAD

**Issue by ghost** [open-telemetry/opentelemetry-collector-contrib#11436]
**Is your feature request related to a problem? Please describe.**
Logs are not integrated with Traces by the GCP Exporter

**Describe the solution you'd like**
The format of the `trace` field that is exported by the GCP exporter should follow the official guidance [here](https://cloud.google.com/trace/docs/trace-log-integration).

for eg
instead of `trace: "4bf92f3577b34da6a3ce929d0e0e4736"` 
it should be `trace: projects/[PROJECT_ID]/traces/4bf92f3577b34da6a3ce929d0e0e4736`

**Describe alternatives you've considered**
Transforming logs using a processor; didn't work, I assume due to the validation performed over the trace_id field.

**Comment by mx-psi** [comment]
@dashpole feel free to reassign to someone else in Google!

**Comment by dashpole** [comment]
Thanks @CatalinAdlerDF

cc @damemi

**Comment by damemi** [comment]
Opened https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/440 to fix this, thanks @CatalinAdlerDF for reporting it

**Comment by CatalinAdlerDF** [comment]
Thanks @damemi !

Hope this gets released soon!

**Comment by dashpole** [comment]
This was fixed by https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/440
