### ISSUE TITLE
Support for accumulating Delta StatsD counter

### ISSUE THREAD

**Issue by datsabk** [open-telemetry/opentelemetry-collector-contrib#11434]
Ref: [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4909)
@huyan0 - I am deploying opentelemetry-collector-contrib as a standalone agent per node in Kubernetes. These agents gather the StatsD metrics and send out to AWS AMP instance. I am also in the same standstill given that StatsD receiver metrics can't be directly consumer by Prometheus exporter. I think there should be a simple utility function provided by the collector which can be leveraged by exporters to store such metrics in memory to calculate the value at any instant and write back to memory. 

I believe we can build an extension thats exact reverse of [cumulativetodelta](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/cumulativetodeltaprocessor) processor and put down a disclaimer that it works only if its used in Agent mode and not in distributed mode.

_Originally posted by @datsabk in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4909#issuecomment-1162825307_

**Comment by dmitryax** [comment]
@TylerHelmuth Did we discuss use cases like and whether they should be part of transform processor during one of SIG meetings? I don't remember what was the decision.

**Comment by datsabk** [comment]
@TylerHelmuth How is the cumulative to delta processing working then? They have a tracker that tracks these values. I think we can do it similarly here. 

I honestly feel it is not too much work to make this possible.

**Comment by TylerHelmuth** [comment]
@datsabk The cumulativetodelta processor does exactly what you said; it tracks the incoming metrics to do the transformation. This makes it [stateful](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/standard-warnings.md#statefulness) which isn't bad but is complicated. A deltatocumulative processor would be stateful in the same way. 

I'm not saying a processor like that isn't possible or that combining the conversions into a single processor isn't possible. [But there is a long term plan to handle transformations of telemetry using a Telemetry Query Language](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/processing.md#metric-temporality). A stateful processor using this language doesn't exist yet but we'd like it too. Long term, any processor that does basic stateful   transformations like this has to potential to be replaced.

**Comment by dmitryax** [comment]
@datsabk if you need the this capability sooner, I'd probably suggest reusing existing https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/cumulativetodeltaprocessor. Later we can replace it with another processor that uses TQL as @TylerHelmuth mentioned. 

cc @open-telemetry/collector-contrib-approvers and @TylerHelmuth as code owner

**Comment by TylerHelmuth** [comment]
Yes, reusing cumulativetodelta's logic would be the fastest solution. We could add the functionality to the existing processor as a config option but it would likely be hard for a user to discover. A temporality conversion processor could be created from the cumulativetodelta processor; it's core logic is going to need to be moved to a package anyways for the TQL. But might be nice just to start making the stateful transformer processor instead. 

If we can get this [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11771) (and the follow up PRs) through in the next release cycle then it is totally possible to start making a stateful TQL processor

**Comment by hardproblems** [comment]
@TylerHelmuth since we need it rather soon, our best course in the short term to would be 1. contribute to the existing cumulativetodelta processor  or 2. implement something like this internally. Then after the stateful processor lands we can replace our usage with it?

**Comment by TylerHelmuth** [comment]
@datsabk agreed, the tracker logic could be moved into either `pkg` so it could be reused.

**Comment by evan-bradley** [comment]
Closing this issue for now. If you'd like to contribute a component with this functionality in the future, please use the "new component" issue template to open a new issue detailing it. Thank you!
