### ISSUE TITLE
[receiver/windowsperfcounters] Flaky Test - Test_WindowsPerfCounterScraper

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#11445]
Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7008709942?check_suite_focus=true#step:7:2750

```
=== RUN   Test_WindowsPerfCounterScraper/Standard
    windowsperfcounters_scraper_test.go:184: 
        	Error Trace:	windowsperfcounters_scraper_test.go:184
        	Error:      	Received unexpected error:
        	            	A counter with a negative denominator value was detected.
        	Test:       	Test_WindowsPerfCounterScraper/Standard
=== RUN   Test_WindowsPerfCounterScraper/SumMetric
=== RUN   Test_WindowsPerfCounterScraper/NoMetricDefinition
=== RUN   Test_WindowsPerfCounterScraper/InvalidCounter
--- FAIL: Test_WindowsPerfCounterScraper (0.25s)
    --- FAIL: Test_WindowsPerfCounterScraper/Standard (0.25s)
```

**Comment by djaglowski** [comment]
cc @dashpole as code owner, and @Mrod1598 because I think you may have last updated this test

**Comment by Mrod1598** [comment]
Looking into it.

**Comment by djaglowski** [comment]
Again here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7651685515?check_suite_focus=true#step:8:2762

**Comment by djaglowski** [comment]
@Mrod1598, I am disabling this test because this has not been addressed.

**Comment by djaglowski** [comment]
Here again: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3234932072/jobs/5299147380#step:8:3784

@open-telemetry/collector-contrib-approvers, PTAL at #14343
