### ISSUE TITLE
Splunk multiple-metric format

### ISSUE THREAD

**Issue by zszia** [open-telemetry/opentelemetry-collector-contrib#11459]
**Is your feature request related to a problem? Please describe.**
The OTEL collector currently does not support [multiple-metric format].(https://docs.splunk.com/Documentation/Splunk/9.0.0/Metrics/GetMetricsInOther#Get_metrics_in_from_clients_over_HTTP_or_HTTPS)
Each metric measurement is stored in a separate event instead.
This is not very efficient for the large number of collected events.

**Describe the solution you'd like**
I was hoping that the collector would support both formats similar to the [Telegraf Agent](https://github.com/influxdata/telegraf/blob/master/plugins/serializers/splunkmetric/README.md#using-multimetric-output)

**Describe alternatives you've considered**
Using the [Telegraf input agent](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kubernetes)

**Additional context**
As discussed with @atoulme  in this Slack thread:
https://splunk-usergroups.slack.com/archives/C019460ACUW/p1655819225087029

**Comment by atoulme** [comment]
I am going to take this onnagain.
