### ISSUE TITLE
[receiver/prometheus] Flaky Test - TestLabelNameLimitConfig

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#11516]
Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7028898187?check_suite_focus=true#step:7:663

```
=== RUN   TestLabelNameLimitConfig
=== RUN   TestLabelNameLimitConfig/target1
    metrics_receiver_helper_test.go:170: 
        	Error Trace:	metrics_receiver_helper_test.go:170
        	            				metrics_receiver_labels_test.go:172
        	            				metrics_receiver_helper_test.go:608
        	Error:      	"1" is not less than or equal to "0"
        	Test:       	TestLabelNameLimitConfig/target1
        	Messages:   	want at least 1 valid scrapes, but got 0
=== RUN   TestLabelNameLimitConfig/target2
--- FAIL: TestLabelNameLimitConfig (5.22s)
    --- FAIL: TestLabelNameLimitConfig/target1 (0.00s)
    --- PASS: TestLabelNameLimitConfig/target2 (0.00s)
```

**Comment by djaglowski** [comment]
cc codeowners @Aneurysm9, @dashpole 

Also cc @bertysentry - this looks quite likely to be related to #10028

**Comment by bertysentry** [comment]
How do we run this test manually?

**Comment by djaglowski** [comment]
This works for me: `go test -run ^TestLabelNameLimitConfig$ github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver`

**Comment by dmitryax** [comment]
Setting Priority to 1 until it's disabled at least

**Comment by djaglowski** [comment]
Here again: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7046173714?check_suite_focus=true#step:7:664

I will open a PR to disable this for now

**Comment by dmitryax** [comment]
Thanks @djaglowski. I lowered the issue priority

**Comment by bertysentry** [comment]
I think this should be closed
