### ISSUE TITLE
support dissect feature to convert plain text to structured data

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#11533]
**Is your feature request related to a problem? Please describe.**
In elastic ecosystem, [filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/dissect.html), [logstash](https://www.elastic.co/guide/en/logstash/current/plugins-filters-dissect.html), [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/dissect-processor.html) all support dissect processor to convert plain text to structured data, which is pretty useful, given already exists filelogreceiver for log file ingestion, it seems to make sense to support this in otel collector as well.

**Describe the solution you'd like**
Support dissect processer.

**Describe alternatives you've considered**
Dissect operator in [filelogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver)

**Additional context**

**Comment by dmitryax** [comment]
Hey @newly12 , what data you want to process with this? traces, metrics, logs or some attributes?

**Comment by newly12** [comment]
@dmitryax in my use case, it's log line.

**Comment by dmitryax** [comment]
@TylerHelmuth this is something that will be possible to do with transform processor, right?

**Comment by newly12** [comment]
If we implement an in house processor that does dissect or something similar in a processor, a typical use case is that we want to parse the "log"(event) timestamp from a "dissected" field and set it as the log record's time, similar to what's currently in filelog receiver, the `json_parser` and then the `timestamp` operator. However currently time parsing can only be done by `timestamp` operator in this receiver, does it make sense to have this capability in a processor? would it be OTTL or a different processor? cc @linjunzhe

**Comment by newly12** [comment]
> If we implement an in house processor that does dissect or something similar in a processor, a typical use case is that we want to parse the "log"(event) timestamp from a "dissected" field and set it as the log record's time, similar to what's currently in filelog receiver, the `json_parser` and then the `timestamp` operator. However currently time parsing can only be done by `timestamp` operator in this receiver, does it make sense to have this capability in a processor? would it be OTTL or a different processor? cc @linjunzhe

Hi @TylerHelmuth any comment on this?

**Comment by TylerHelmuth** [comment]
IDK how I missed this for so long but thanks Stale Bot for the last ditch effort haha

I think this is definitely appropriate for the transformprocessor.  There are some open issues for improving how OTTL/transformprocessor interact with time: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16067 and we just made a `ParseJSON` function.
