### ISSUE TITLE
[processor/groupbytraceprocessor] how to use groupbytraceprocessor

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#11531]
is there any new information for groupbytraceprocessor?  Is it ready for use？

**Comment by Frapschen** [comment]
I notice that this processor is marked as `in development`. I used it to generate metrics, it seems to work normally. can you tell me which part of it is in development?

**Comment by dmitryax** [comment]
cc @jpkrohling as code owner

**Comment by dmitryax** [comment]
@Frapschen please feel free to play with it and file any issues that you find. If it's working fine I believe we can update the status

**Comment by pmm-sumo** [comment]
I was just experimenting with it a bit but haven't used it extensively. I don't have any objections against setting the status to "beta"

**Comment by jpkrohling** [comment]
Done in #12170
