### ISSUE TITLE
Processor to sample Logs

### ISSUE THREAD

**Issue by davidgargti20** [open-telemetry/opentelemetry-collector-contrib#11549]
Sampling of logs is as important as sampling of traces. We do have processors to sample traces Is there any way in which we can sample logs ( preferably tail based sampling ) . One scenario like grouping logs by traceid and sampling then based on the if those group of logs have a log that has severity error.

**Comment by TylerHelmuth** [comment]
@jpkrohling would the tailsampling processor handle this?  The transform processor is decidedly not going to do any transformations that require state.

**Comment by jpkrohling** [comment]
The tail-sampling does not currently handle this, and I'd prefer to have the current problems with the tail-samping to be solved before we expand it in this direction. The issue @atoulme linked seems doable, though.

**Comment by jpkrohling** [comment]
I'm closing this in favor of #9117 as proposed.
