### ISSUE TITLE
InfluxDB Line Protocol format into Clickhouse

### ISSUE THREAD

**Issue by gokulkrish21** [open-telemetry/opentelemetry-collector-contrib#11558]
We are retrieving some of the metrics using Open Telemetry in InfluxDB Line Protocol format. We are trying to store those metrics data in InfluxDB line format into Clickhouse database. Currently we do not seem to have functionality in Clickhouse Exporter available in Github. Can you include the Influx DB line format also into the solution while developing Clickhouse Exporter for metrics data as mentioned in the doc below

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/clickhouseexporter

**Comment by TylerHelmuth** [comment]
pinging @hanjm @dmitryax as code owners

**Comment by dmitryax** [comment]
@gokulkrish21 can you please provide more details about the InfluxDB Line Protocol format. 

Also feel free to suggest an approach and configuration interface first. I don't think this issue will be taken by someone else. So you need to start proposing and implementing it yourself if you need it.

**Comment by hanjm** [comment]
OpenTelemetry exporter amis to export Opentelemetry Line Protocol, not for InfluxDB Line Protocol format directly. You need to use [influxdb receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/influxdbreceiver) component to convert to OTLP firstly.

**Comment by hanjm** [comment]
working in progress about otlp metrics to clickhouse

**Comment by hanjm** [comment]
no stale

**Comment by Frapschen** [comment]
@hanjm If you have not time to do it, I can work on it. https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16478
