### ISSUE TITLE
[CI] Run `golangci-lint` with alternate build tags

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#11557]
> Hmm, if I'm understanding this correctly, then `make gofmt` includes all *.go files regardless of build tags, whereas the linter does not.

>Okay, yes, I think that's the case. Still, this doesn't feel like a problem specific to go fmt: it happens with all linters that we run as part of `golangci-lint`, right? The only difference is that gofmt can run on all files regardless of build tags, while other linters probably can't.
>
>I guess this is an easy solution for `go fmt`, just wondering if the 'correct' solution is to run `golangci-lint` multiple times with different build tag combinations.

_Originally posted by @mx-psi in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11440#issuecomment-1163129216_

**Comment by gord02** [comment]
Hello everyone. I'd like to try and work on this. What is an example of one of the build tag combinations that would potentially need to be used in a golangci-lint run?

**Comment by mx-psi** [comment]
> Hello everyone. I'd like to try and work on this. What is an example of one of the build tag combinations that would potentially need to be used in a golangci-lint run?

Based on the PR linked on the original post, the `e2e`, `integration` and `windows` build tags were the ones causing the most trouble. You can't enable the `windows` build tag without disabling the `linux` tag first.

Here are other build tags we use:
```
❯ rg 'go:build' --no-filename | sort | uniq | cut -d' ' -f 2-
darwin
darwin || freebsd || dragonfly || netbsd || openbsd
!darwin && !freebsd && !dragonfly && !netbsd && !openbsd && !linux && !solaris && !windows
e2e
integration
integration && !windows
!linux
linux
!linux && !darwin
linux || darwin
!linux && !darwin && !freebsd && !openbsd
linux || darwin || freebsd || openbsd
!linux && !darwin && !freebsd && !openbsd && !solaris
linux || darwin || freebsd || openbsd || solaris
linux || solaris
!linux && !windows
!linux && !windows && !darwin
!race
race
tools
!windows
windows
!windows && !linux
```

Not all of these are relevant but it should give you a starting point.

**Comment by pjanotti** [comment]
I got to this issue after noticing that lint is not been run for Windows. In my quick tests I can't get lint to consider the `windows` as a build-tag, it needed to be set as `GOOS`. I'm planning to start fixing lint issues on Windows and later to enable it as part of CI. Let me know if you have any concerns/recommendations in this regard.

/cc @mx-psi @djaglowski

**Comment by led0nk** [comment]
what's the status on this issue ? i can't see if its still needed or what we need to provide

**Comment by mx-psi** [comment]
@led0nk AFAIK nobody has been actively working on this. You may rerun the command on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11557#issuecomment-1774633993 (I used ripgrep but grep should also work) to get an initial list of build tag combinations (not all would be applicable)
