### ISSUE TITLE
[receiver/aerospikereceiver] Send info requests in parallel

### ISSUE THREAD

**Issue by dwelch-spike** [open-telemetry/opentelemetry-collector-contrib#11563]
**Is your feature request related to a problem? Please describe.**
Currently the aerospike receiver makes info requests to nodes sequentially when running in collect-cluster-metrics mode. For large clusters this could take a while, especially if nodes are timing out.

**Describe the solution you'd like**
By implementing a second client type that sends info commands to all nodes in parallel, the network wait time of a scrape cycle in collect-cluster-metrics node can be greatly reduced.

**Describe alternatives you've considered**
I've considered running scrapeDiscoveredNode as a go routine for each service discovered from the original node. Here are some reasons I'm leaning away from this. This requires the creation and initial login of node_count clients every scrape interval. This would require significant refactoring of the scraper methods. I am not sure if metricsBuilder is thread safe.

**Additional context**
Downsides of proposed solution: There will be 2 implementations of the aerospike interface in client.go to maintain.
I have a dev branch for the proposed solution in progress in my fork https://github.com/dwelch-spike/opentelemetry-collector-contrib/tree/aerospikereceiver-perf.
Initially discussed here https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11525 .

**Comment by TylerHelmuth** [comment]
pinging @djaglowski @antonblock as code owners

**Comment by djaglowski** [comment]
Is it necessary to keep the original client?

**Comment by antonblock** [comment]
Yeah I'm also not sure if the `metricsBuilder` is safe with Goroutines, which is why I didn't try to fanout with goroutines.

I don't see an issue with this, but like @djaglowski I'm wondering if this could simply replace the current client?

**Comment by dwelch-spike** [comment]
@djaglowski @antonblock I ended up pretty much replacing the client like you mentioned.

**Comment by dwelch-spike** [comment]
Hi @djaglowski PR is ready for review. Please let me know if I need to do anything else. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11877

**Comment by djaglowski** [comment]
Closed by #11877
