### ISSUE TITLE
RecordException event not visible in Azure Monitor

### ISSUE THREAD

**Issue by LarsAndreasEk** [open-telemetry/opentelemetry-collector-contrib#1163]
Hi,

I tried using this to record exceptions onto activities in dotnet (otel sdk): **Tracer.CurrentSpan.RecordException(e);**

As I understand, this is recorded as an event onto the existing span, but it does not end up in Azure Monitor it seems.

Is that by design, a missing feature, or me not getting it?

Best regards,
Lars Andreas Ek

Related: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1115

**Comment by LouisStAmour** [comment]
It's currently a missing feature. In fact, a cursory glance showed that  Independent of Microsoft, I've been noodling away at a PR that would add more support for events in spans, as well as exception events, metrics and logs.

A quick search through the existing codebase for contrib for SpanEvent showed that maybe only AWS X-Ray, Google Stackdriver and Honeycomb have explicit support in their exporters for span events?

**Comment by pcwiese** [comment]
> It's currently a missing feature. Independent of Microsoft, I've been noodling away at a PR that would add more support for events in spans, as well as exception events, metrics and logs.

@LouisStAmour have you made progress on these? Anything to share?

**Comment by LouisStAmour** [comment]
I've used my branch of the collector successfully for telemetry, but haven't updated it yet from 0.13 to a more modern codebase. Also I don't yet have tests written for the new functionality. 

I'm not yet using the Go client so it's harder to integrate usage testing for metrics and logging but I've plans over the next month or two to expand internal usage of metrics and log reporting.

But my branch seems to be reporting exceptions and other attributes reasonably well to Azure App Insights. I'll try to update it to modern collector code shortly.

**Comment by LouisStAmour** [comment]
@pcwiese Silly me, I forgot to share a link. It's at https://github.com/LouisStAmour/opentelemetry-collector-contrib/tree/azure-events-v0.13.x or https://github.com/users/LouisStAmour/packages/container/opentelemetry-collector-contrib%2Fotelcontribcol/354909 as a Docker image, but expects a 0.13 config file.

**Comment by LouisStAmour** [comment]
As an update, I've rebased the commits on the main branch of Otel Collector at https://github.com/LouisStAmour/opentelemetry-collector-contrib/tree/azure-events-v0.25.pre but I've yet to add tests or test it myself. About to build a new Docker image.
