### ISSUE TITLE
Extend groupbytrace processors to logs

### ISSUE THREAD

**Issue by davidgargti20** [open-telemetry/opentelemetry-collector-contrib#11770]
Currently groupbytrace processor works for traces only. It will be a good use if we can extend it to grouping logs based on traceId.

**Comment by davidgargti20** [comment]
@dmitryax

**Comment by dmitryax** [comment]
I'm curious what's the use case? What will you do with the logs grouped by trace id?

**Comment by davidgargti20** [comment]
By grouping logs by traceID I will use them to apply tail based sampling to logs.

**Comment by dmitryax** [comment]
Ok, I think this might be helpful. Feel free to add the this capability to `groupbytrace` processor

**Comment by davidgargti20** [comment]
@dmitryax should I simply implement or need to give some proposal or something here

**Comment by dmitryax** [comment]
I believe you need to start with adding logs support to https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor. Feel free to start with submitting another issue with detailed proposal for that change

**Comment by davidgargti20** [comment]
@dmitryax I currently just have idea in which I can have implemented one two policies of tailsamplingprocessor for logs. I would love some help from your side.

**Comment by dmitryax** [comment]
@davidgargti20 I can help with reviewing your PRs

**Comment by davidgargti20** [comment]
@dmitryax that would be a great help too thanks

**Comment by davidgargti20** [comment]
@dmitryax I am looking to add support of logs to groupbytrace processor as it solves the purpose of mine.

**Comment by dmitryax** [comment]
What purpose? Don't you need sampling?

**Comment by davidgargti20** [comment]
@dmitryax groupbytrace solves the major sampling task of grouping. After grouping I can just use filter processor for sampling that's why i consider It's better to have groupbbytrace support for logs.

**Comment by dmitryax** [comment]
How will you filter grouped logs with filter attribute? It doesn't support filtering by trace ID.

**Comment by davidgargti20** [comment]
@dmitryax I have added traceId to attributes using the transform processor.

**Comment by dmitryax** [comment]
> @dmitryax I have added traceId to attributes using the transform processor.
To the log record attributes or resource attributes?

**Comment by davidgargti20** [comment]
@dmitryax  to the log record attributes and then grouping them using groupbyattrs

**Comment by dmitryax** [comment]
> @dmitryax to the log record attributes and then grouping them using groupbyattrs

cool, why do you need `groupbytrace` then if you can use `groupbyattrs` instead?

**Comment by davidgargti20** [comment]
@dmitryax because groupbyattrs doesn't wait for traces like groupbytrace does

**Comment by dmitryax** [comment]
I see. ok, sounds reasonable

**Comment by jpkrohling** [comment]
Pinging @pmm-sumo, as he has more experience with the groupbyattrs. Wouldn't it work to just use the batch processor, followed by the groupbyattrs?

**Comment by pmm-sumo** [comment]
> Pinging @pmm-sumo, as he has more experience with the groupbyattrs. Wouldn't it work to just use the batch processor, followed by the groupbyattrs?

Interesting, moving the trace_id to attribute and then using batch + groupbyattrs would pretty much have the same outcome as groupbytrace processor. Good point @jpkrohling

**Comment by davidgargti20** [comment]
@pmm-sumo @jpkrohling  batch + groupbyattrs will not be same as groupbytrace
as batch just group logs regardless of trace

**Comment by davidgargti20** [comment]
@jpkrohling @dmitryax created a pull request
