### ISSUE TITLE
New component: Chrony Receiver

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#11789]
## The purpose and use-cases of the new component

The chrony receiver would report the statistics that would be captured by the c binary `chronyc tracking`. This would allow service operators to understand if there is any issues trying to sync host clocks with `chronyd` that would potentially impact any security / telemetry related problems.

An out of sync host clock would result in failed security operations that are based off system time (ie. to avoid replay attacks) or trying to gather telemetry from an instance where the system time is significantly wrong so correlation is not possible (without exemplars). 

## Example configuration for the component

An example of configuration would look like something like this:

```yaml
receiver:
  chrony:
    address: unix:///var/run/chrony.sock
    metrics:
      # Metrics to report from the receiver
```

## Telemetry data types supported

Only metrics

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?

No, chrony is an open source tool that part of many linux distributions.

## Sponsor (Optional)

Not sure if I can be my own sponsor, but I will look to see if anyone would be interested in this.

**Comment by TylerHelmuth** [comment]
@MovieStoreGuy you can be a code owner for this receiver if it is accepted but you will also need a sponsor from [this list.](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#rotating-sponsors)

**Comment by jamesmoessis** [comment]
I am happy to become a code owner and review each PR. I'm not on that list though.

**Comment by MovieStoreGuy** [comment]
@bogdandrutu , @dmitryax ,

Would either you be interested in sponsoring this component? 
It would be a good replacement for `collectd/chrony` receiver that was part of the SignalFx Smart Agent which is being deprecated.

**Comment by dmitryax** [comment]
I can be the sponsor but I'm busy til August and unlikely be able to review big PRs.

**Comment by dmitryax** [comment]
I still cannot guarantee a quick review :) Use my sponsorship as a fallback if no one else is interested

**Comment by MovieStoreGuy** [comment]
I may have had these ready...

**Comment by MovieStoreGuy** [comment]
Closing this ticket off since has been part of the release of the collector for some time now
