### ISSUE TITLE
Excluding logs using filtering by regex, but want to include some of those logs.

### ISSUE THREAD

**Issue by omkar-ti** [open-telemetry/opentelemetry-collector-contrib#11792]
### Discussed in https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/11786

<div type='discussions-op-text'>

<sup>Originally posted by **omkar-ti** June 29, 2022</sup>
I want to achieve something like this using the filter processor for logs in the otel collector config

Exclude all logs having `attributes[sample_key] = prefix.*` (regex)
BUT
don't exclude logs having `attributes[sample_key] = prefix_suffix` (strict)

If I understand the filter processor correctly, only the logs which survive all the applied filters are actually pushed ahead in the pipeline.
So one method is to have seperate `exclude` filters for all `attributes[sample_key] = prefix.*`, but it is too tedious

Since we are using re2 for regex, negative lookahead is not supported, so I cannot express "`attributes[sample_key]` should not match `prefix_suffix`" as regex.

How do I achieve this?</div>

**Comment by TylerHelmuth** [comment]
Pinging @boostchicken @pmm-sumo as code owners

**Comment by pmm-sumo** [comment]
Filter processor is very simple and if something cannot be expressed by re2, I think it won't be able to solve this one. However, you can consider extracting the post-prefix attribute part and then making filtering decision on it. This could be achieved via `extract` of `attributesprocessor` and perhaps also through [transformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) or [logstransformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/logstransformprocessor)
