### ISSUE TITLE
Support split string into arrays for a log attribute

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#11790]
**Is your feature request related to a problem? Please describe.**
For example, I have a log line like this
```
{"msg": "xxx", "flag": "A|B|C"}
```
with filelog receiver and its json_parser, I am able to access `flag` field, and I would like to split `A|B|C` by `|` so it will be an array, possible use cases are 1) filter the array elements by other processors 2) query if array contains certain elements at storage side if the storage supports array.

**Describe the solution you'd like**
Add string split operator in filelog receiver.

**Describe alternatives you've considered**
Add support in transform processor.

**Additional context**

**Comment by TylerHelmuth** [comment]
I think the transform processor could be updated to handle this. I am not very familiar with the filelog receiver or the logs-collection library, where does the `flag` field end up?  Is it an attribute of the LogRecord?  If `flag` is an attribute, is the goal to transform the attribute's value from `"A|B|C"` to `["A", "B", "C"]`?

**Comment by TylerHelmuth** [comment]
@djaglowski would a better place for this be right in the logs-collection package?

**Comment by djaglowski** [comment]
I believe you can already do this with the `csv_parser` but setting a custom `delimiter`. Docs are [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/csv_parser.md#configuration-fields).

**Comment by newly12** [comment]
Thanks. 

> Is it an attribute of the LogRecord? If flag is an attribute, is the goal to transform the attribute's value from "A|B|C" to ["A", "B", "C"]?

yes.

@djaglowski while looking at the `csv_parser` doc, it appears header or header_attribute must be set to get key value pairs, it looks like it has to be fixed total elements? for example, it seems not work if given few lines of the log to be something like
```
{"msg": "xxx", "flag": "A|B|C"}
{"msg": "xxx", "flag": "A|B"}
{"msg": "xxx", "flag": "B|C"}
```  
please correct me if anything.

**Comment by newly12** [comment]
@djaglowski thanks for confirmation. 

An open question, does it make sense to have this as an operator in `filelog` receiver, or will such use case be general enough to be built in `transform` processor, but I am guessing just `logs` telemetry data will have such case like this?

**Comment by djaglowski** [comment]
The long term plan is to re-implement all log parsing and transformation capabilities in the transform processor, so I think it makes sense to add this functionality directly there.

**Comment by newly12** [comment]
@djaglowski Thanks for the clarification. Was there any timeline at this point, if we'd like to contribute to some of the log parsing or transformation implementation in `transform` processor, any suggestion on how we should jump into this?

**Comment by djaglowski** [comment]
I don't believe there's any specific timeline yet. A contribution would likely be the fastest way.

@TylerHelmuth owns the `transformprocessor`, so I'd defer to him, but I think the next step would be to propose a specific function that would be added to that processor.

**Comment by TylerHelmuth** [comment]
@newly12 to add this functionality to the transform processor you would add a new function to the telemetry query language. I think the new function would be added generically (able to be used in all signals) and would convert a string attribute to an array of strings using a passed in delimiter. [Checkout the processor contributing guide if you'd like to add the functionality yourself](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/CONTRIBUTING.md). [Also be aware of the function syntax guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/processing.md#function-syntax).  If you're interest in taking this on I'll assign this to you.

**Comment by newly12** [comment]
Thanks for the guidance! I will check and get back here.

**Comment by newly12** [comment]
Closing this issue,`Split` is already added to OTTL.
