### ISSUE TITLE
[receiver/rabbitmq] Scraper test does not actually pass

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#11800]
The result of `scrapertest.Compare` is either an error or nil, but is not checked. This was unnoticed because the `errcheck` linter was not being used.

**Comment by Frapschen** [comment]
sorry, I fix it

**Comment by Frapschen** [comment]
I notice some receiver also miss check the resoult of `scrapertest.CompareMetrics`, like mysqlreceiver, nginx receiver...

**Comment by djaglowski** [comment]
No worries. I've already created #11801 for this one and am working through the rest
