### ISSUE TITLE
Remove usage of `direction` attribute

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#11815]
Follow-up to the change in specification: https://github.com/open-telemetry/opentelemetry-specification/pull/2617

The following actions are needed:
- [x] #11816
- [x] #11817
- [x] #11818
- [x] #11819
- [ ] #12191
- [ ] #12190
- [x] #12189
- [ ] #12188
- [x] #12164
- [x] #12165
- [ ] #12187
- [ ] #12186
- [x] #12185
- [x] #12184

**Comment by dmitryax** [comment]
@codeboten I'm not sure several feature gates for hostmetrics receiver provides a good user experience. Maybe we should have one feature gate for all host metrics with a single documentation? 

Also I would like to have all of them aligned to the same release schedule. So if we cannot resolve https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11816 by tomorrow's release, I would recommend adjusting it a bit (delaying the schedule for one more release).

**Comment by dmitryax** [comment]
I will submit a PR for ^ by tomorrow

**Comment by dmitryax** [comment]
Looks like https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12134 was prepared before https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12105 got merged. So we still have another kind of changelog race condition :)

I'll submit a PR to update the generated changelog and release notes

**Comment by dmitryax** [comment]
Submitted https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11815#issuecomment-1178204310

**Comment by crobert-1** [comment]
[exporter/signalfx] - Another place that needs updated

The signalfxexporter has functionality that "translates" input metrics into output metrics, and the default translation functionality references the direction attributes. These references should be updated for the new metric format.

Let me know if I should open a new issue for this instead of simply adding another TODO item here!

**Comment by dmitryax** [comment]
@codeboten can we slow down the adoption of the new metrics a bit? We are having troubles on Splunk Observability side to provide the backward compatibility. Can we introduce the new metrics feature-gated in silent mode for a few more releases, then start the transition in a more relaxed schedule? I believe our backend might be not the only one trying to do it gracefully. 

I'll be back in a week and can help with this effort.

**Comment by codeboten** [comment]
👍🏻 sure no problem

**Comment by mwear** [comment]
@dmitryax I'm happy to help push this work forward, and adjust the transition plan in whatever way makes the most sense. It sounds like it would be best if we:

* Implement the feature gates in each receiver, but leave them undocumented, and continue to emit metrics with direction attributes
* Once the feature gates exist for each receiver
  * Publish a revised transition plan
  * Document the gates
  * Add deprecation warnings
  * Push these changes out in one release, that will officially begin the transition plan
* At some later point in time (according to the transition plan), default to emitting metrics without direction, but keep the feature gate to allow users to enable emitting metrics with a direction attribute if needed
* When the transition period is over:
  * Remove the gates
  * Remove the documentation, warnings, etc around the transition plan
  
Let me know if this sounds reasonable or if you have any further suggestions on the plan and how we should carry it out.

**Comment by dmitryax** [comment]
Hi @mwear, this is exactly what I envisioned. Thanks for putting the plan together. Let's follow it

**Comment by mwear** [comment]
Great. One followup question. I think the answer is yes, but I wanted to clarify. Should we remove documentation about the feature gates and transition plan from the readmes where they are currently documented as well as any existing deprecation messages?

**Comment by dmitryax** [comment]
> Should we remove documentation about the feature gates and transition plan from the readmes where they are currently documented as well as any existing deprecation messages?

Yes, let's remove it for now

**Comment by mwear** [comment]
Is this work impacted by: https://github.com/open-telemetry/opentelemetry-specification/issues/2726. If so, should we continue with it, or wait for a resolution?

**Comment by dmitryax** [comment]
It is indeed. Let's hold off until it's resolved

**Comment by codeboten** [comment]
Closing this as the resolution was to not implement anything unless the specification declares any changes.
