### ISSUE TITLE
The build was hard code to amd64 for docker build

### ISSUE THREAD

**Issue by gyliu513** [open-telemetry/opentelemetry-collector-contrib#11873]
**Describe the bug**

After I run `make docker-otelcontribcol` on my mac, I found the binary name was `otelcontribcol_linux_amd64`, seems the makefile is hardcoding the GOARCH as amd64 https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/Makefile#L241 , any reason why? Thanks!

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by codeboten** [comment]
I think the docker make target is intended specifically to build a collector to run inside a container, `make otelcontribcol` is the target used to compile locally.

**Comment by gyliu513** [comment]
Thanks @codeboten , but still have a question: why hardcoding docker build to amd64? With docker build, it should also support multi-arch as well.

**Comment by codeboten** [comment]
It's a good question, based on git blame it looks like the decision was made over 2 years ago. I'm not sure why

**Comment by TylerHelmuth** [comment]
@gyliu513 Are you free to update the docker-otelcontribcol target to support more architectures?

**Comment by gyliu513** [comment]
@TylerHelmuth Yes, glad to help. Will fix early next week.

**Comment by dmitryax** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12217 doesn't seem like introduce multi arch image
