### ISSUE TITLE
Unable to export logs using google cloud exporter

### ISSUE THREAD

**Issue by davidgargti20** [open-telemetry/opentelemetry-collector-contrib#12072]
While sending logs to google cloud platform using google cloud exporter the exporter stops sending logs after few time. This generally happens with a memory spike. I am still able to see logs using the logging exporter.

the unusal thing that I noticed in logs is 
``` info	zapgrpc/zapgrpc.go:174	[transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"	{"grpc_log": true} ```

**Comment by punya** [comment]
I believe @damemi is already looking into this as part of https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/449.

**Comment by damemi** [comment]
Yeah, as @punya mentioned I was hoping to get more details about this in the linked issue (@davidgargti20 are these related?)

@codeboten you can assign me, thanks

**Comment by davidgargti20** [comment]
@damemi yes there are related

**Comment by damemi** [comment]
@davidgargti20 thanks for clarifying, we'll track this in the other repo since that's closer to the functionality.

**Comment by dashpole** [comment]
marking as fixed, since the issue was closed in the other repository.
