### ISSUE TITLE
[exporter/influxdb] Allow overriding of Measurename when using telegraf-prometheus-v2 in the Influxdb Exporter.

### ISSUE THREAD

**Issue by marcusjsford** [open-telemetry/opentelemetry-collector-contrib#12078]
I would like to stream OTLP metrics to Influxdb in `metrics_schema: telegraf-prometheus-v2` format. Unfortunately the measurement name is hardcoded to "prometheus". https://github.com/influxdata/influxdb-observability/blob/main/common/common.go#L18.  And so has a single measurement written to influx.

**Describe the solution you'd like**
I would like to be able to override the measurement name with a prefix, suffix or indeed replace it entirely in the same way that telegraf does. A config that allows a Name Prefix, Name Override or Name suffix for the measurename would be good.

I've considered using telegraf with a Kafka consumer Input Plugin to consume OTLP but there isn't an OTLP data format yet.
https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md

**Comment by codeboten** [comment]
@marcusjsford there is an input plugin for OTLP to telegraf: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/opentelemetry, will that work for your purpose?

Regarding the original issue, pinging @jacobmarble

**Comment by marcusjsford** [comment]
> @marcusjsford there is an input plugin for OTLP to telegraf: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/opentelemetry, will that work for your purpose?
> 
> Regarding the original issue, pinging @jacobmarble

Thanks @codeboten, The renaming works as expected in that plugin but does not fully serve my purpose.

I apologise, I should have been more verbose with my requirement. I want to be able push metrics to kafka in OTLP format from many services and then consume the metrics and send them into influxdb in prometheus-v2 format.  
Instead of having 50 services under a single "prometheus" measure i'd like to split them out into one measure per service. To do that I need to find a way to override the default measure name with a custom prefix or suffix and also add the value of one of the Resource Attributes to the Measure name aswell.

- Ability to override the prometheus Measure name.
- Ability to add a Resource Attribute Value into the Measure name.

**Comment by jacobmarble** [comment]
@codeboten you can assign this one to me.

**Comment by codeboten** [comment]
@jacobmarble done 👍🏻
