### ISSUE TITLE
[receiver/aerospikereceiver] Typo in metric name, not being collected

### ISSUE THREAD

**Issue by antonblock** [open-telemetry/opentelemetry-collector-contrib#12083]
**Describe the bug**
Aerospike metric `aeropsike.namespace.transaction.count` should be `aerospike.namespace.transaction.count`. Additionally,  

**Steps to reproduce**
Run collection on a typical Aerospike system

**What did you expect to see?**
Correctly named metrics about transactions on namespaces

**What did you see instead?**
Mislabeled and not collected metrics

**What version did you use?**
`fbaccad9134ac969ecf1301f6028a64be986d4af`

**What config did you use?**
```yaml
receivers:
  aerospike:
```

**Comment by djaglowski** [comment]
Closed by #12085
