### ISSUE TITLE
Stability level undefined

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#12104]
**Describe the bug**

With the current code in main, the following message is displayed for all components that are passing a stability level as an option to the factory.

```
Stability level of component undefined	{"kind": "receiver", "name": "hostmetrics", "pipeline": "metrics", "stability": "undefined"}
```

This may surprise users upgrading to this version. Some ways we could mitigate this:
1. change the log level to debug (or not log at all) for `undefined` stability level, until the next release
2. apply a stability level to all the components

I have a PR for option 1 [here](https://github.com/open-telemetry/opentelemetry-collector/pull/5635) and option 2 [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12099)

**Comment by jpkrohling** [comment]
Option 2 would be my preferred solution, but given that we have a release right around the corner, it might be safer to do option 1.

**Comment by tigrannajaryan** [comment]
Let's go with option 1.

**Comment by codeboten** [comment]
This is fixed, closing
