### ISSUE TITLE
[receiver/elasticapm] New component: Elastic APM Receiver

### ISSUE THREAD

**Issue by bilbof** [open-telemetry/opentelemetry-collector-contrib#12114]
## The purpose and use-cases of the new component

The Elastic APM receiver would receive [Elastic APM events](https://www.elastic.co/guide/en/apm/guide/current/api-events.html). 

This was previously requested at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3002#issuecomment-821021777.

This would enable applications instrumented with an Elastic APM Agent to use other telemetry backends without needing to rewrite the instrumentation for the apps.

## Example configuration for the component

```
receiver:
  elasticapm:
```

An [APM Event](https://www.elastic.co/guide/en/apm/guide/current/api-event-example.html) contains a Transaction, Span, MetricSet, and Error. The receiver would translate an Event into a single [Trace](https://opentelemetry.io/docs/concepts/signals/traces/). 
## Telemetry data types supported

Traces. In future it's possible other datasources (metrics, logs) could be supported.

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?

This is vendor specific, but I am not affiliated with Elastic.

**Comment by Aneurysm9** [comment]
> A vendor-specific component directly interfaces with a vendor-specific API and is expected to be maintained by a representative of the same vendor.

Without commitment from Elastic to maintain this I think we would need a maintainer/approver to act as sponsor.

**Comment by bilbof** [comment]
Just want to bump this to ask whether folks would be comfortable with me implementing this and submitting a PR? We have quite a few applications instrumented with APM and it would be a substantial effort to migrate them all to OpenTelemetry immediately (though that is the long term goal).

**Comment by bradleydamato** [comment]
Just want to bump this and see if there is any renewed interest/motivation for working on this? I'd be happy to contribute

**Comment by Aneurysm9** [comment]
> @Aneurysm9, as @jkowall mentioned in the linked issue, Elastic would probably have no interest in having their proprietary data sent to OpenTelemetry, unfortunately. I would not consider this a vendor component, but a community-driven one.

That's how I had seen it as well.  Since it is not a vendor component it requires a volunteer sponsor from among the approvers and maintainers.

**Comment by jpkrohling** [comment]
@bilbof, @bradleydamato, are you still interested in working on this component?

**Comment by jpkrohling** [comment]
I'm closing, as the original proponents are not interested in working on this.

**Comment by bilbof** [comment]
Hey @jpkrohling sorry, I must’ve missed this. We migrated most of our apps away from APM. I think this still would be worth adding, if I get time I will work on it. Thanks!
