### ISSUE TITLE
Statsd Receiver missing metric when one of the metrics tag has colon ( ":" ) in its value

### ISSUE THREAD

**Issue by dirceumaranhaopn** [open-telemetry/opentelemetry-collector-contrib#12120]
Statsd Receiver missing metric when one of the metrics tag has colon ( ":" ) in its value

It can be reproduced when publish a metric like this:
`echo "test.dnazareth.metric:42|c|#svc_addr:0.0.0.0:443" | nc -w 1 -u localhost 8125`

The expectation would be the metric go through and be publish

Instead, the metric would be considered not well parsed and got in this if statement
```
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/statsdreceiver/protocol/statsd_parser.go#L299-L301
```

**What version did you use?**
0.54.0

**What config did you use?**
[Similar to the one in the example
](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/statsdreceiver/testdata/config.yaml)

**Environment**
MacOs Monterey 12.4

**Additional context**
M1 Apple mac book pro

**Comment by dirceumaranhaopn** [comment]
Code was merged, and waiting for the release to close the issue.

**Comment by codeboten** [comment]
@dirceumaranhaopn we close issues as the fixes for them are merged, closing this one. Thanks for the contribution!
