### ISSUE TITLE
[exporter/prometheusremotewriteexporter] Go Panic when transmitting Histogram with no buckets

### ISSUE THREAD

**Issue by falken** [open-telemetry/opentelemetry-collector-contrib#12168]
While testing the sending of metric data through a pipeline of

Java Application -> Micrometer -> Micrometer Otlp -> Otel Collector Otlp receiver -> PrometheusRemoteWriter exporter

We found that one of the Histograms was incorrectly being sent, causing the remote write exporter to crash.

Our expectation was that this metric would be dropped. 

Instead Collector crashes with a Go Panic. Because these metrics are transmitted every minute our Collector would restart and be killed constantly. This blocks other applications from being able to submit to the collector.

Version: v0.54.0

Environment
OS: Collector Docker Container

**Comment by kovrus** [comment]
@Aneurysm9 we can close this one, it was fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12854.
