### ISSUE TITLE
When using receiver as fileLog and exporter as otlp/elastic getting following error:-

### ISSUE THREAD

**Issue by sunnycalsoft** [open-telemetry/opentelemetry-collector-contrib#12178]
COnfiguration:- 
receivers:
      filelog:
        include:
          - /path/varlogs/*.log
        start_at: beginning

exporters:
      logging:
        loglevel: debug
      otlp/elastic:
        endpoint: "http://ip:port"
        tls:
          insecure: true
          insecure_skip_verify: true

 
Error:-
error   exporterhelper/queued_retry.go:183      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "name": "otlp", "error": "Permanent error: rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.logs.v1.LogsService", "dropped_items": 2}

**Comment by codeboten** [comment]
It looks like the problem is the backend doesn't support logging, could the endpoint be configured incorrectly?

**Comment by sunnycalsoft** [comment]
> It looks like the problem is the backend doesn't support logging, could the endpoint be configured incorrectly?

EndPoint is configured correctly because i am receiving the metrics properly, it is the issue only with logs

**Comment by sunnycalsoft** [comment]
Issue resolved
