### ISSUE TITLE
[googlemanagedprometheusexporter] Include resource labels 

### ISSUE THREAD

**Issue by olekgo** [open-telemetry/opentelemetry-collector-contrib#12175]
**Is your feature request related to a problem? Please describe.**

In my use case, most of the labels are resource labels and they are ignored by the exporter, which leads to collisions  ( "duplicate timeseries enountered" errors).  I could be wrong, but I believe this issue is solved in prometheus and prometheusremotewrite exporters using [resourcetotelemetry](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/resourcetotelemetry) helper.

**Describe the solution you'd like**
Similar to how its implemented in `prometheusexporter` and `prometheusremotewriteexporter`. Probably using [resourcetotelemetry](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/resourcetotelemetry) helper

**Describe alternatives you've considered**
I tried to promote resource labels to metrics labels using a processor but didn't find anything that could do the job. But I wouldn't be surprised there's a way.

**Additional context**
N/A

**Comment by dashpole** [comment]
Just curious: which receiver are you using?

The GMP exporter relies primarily on [service.name, service.namespace, and service.instance.id(https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions#service) (mapped to `job` and `instance` in the [`prometheus_target`](https://cloud.google.com/monitoring/api/resources#tag_prometheus_target)).  The service resource attributes are required to be globally unique, which prevents this issue (in theory).  In practice, service resource attributes aren't consistently set, and often aren't globally unique when they are.

But regardless, the request to add the resourcetotelemetry helper is a good idea.

**Comment by olekgo** [comment]
> The GMP exporter relies primarily on [service.name, service.namespace, and service.instance.id](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions#service) (mapped to job and instance in the [prometheus_target](https://cloud.google.com/monitoring/api/resources#tag_prometheus_target)).

Interesting.. I am using [otlp receiver](https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver) together with `resourcedetection` processor (same as in the [doc](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlemanagedprometheusexporter#example-configuration)). Out of all labels listed [here](https://cloud.google.com/monitoring/api/resources#tag_prometheus_target), only `project_id`, `location` and `job` are defined, the rest are empty:
![Screenshot 2022-07-13 at 01 00 03](https://user-images.githubusercontent.com/90334925/178618332-309f7ea8-bf7e-4cb4-ad02-9cb6a7bea6f2.png)

When using both GMP exporter and file exporter simultaneously, I can confirm that the file exporter "sees" `instance` label, as well as all the other resource and metrics labels coming directly from the application (via otlp)

**Comment by dashpole** [comment]
Can you paste your resources from the file exporter?

**Comment by olekgo** [comment]
Thanks, it worked. A small note - I had to specify `action` eg:
```
processors:
  resource:
    attributes:
    - key: service.instance.id
      from_attribute: host.name
      action: insert
```

Looking forward to `resourcetotelemetry` support!

**Comment by olekgo** [comment]
Maybe someone will find this usefull. 

After playing with `resourcetotelemetry` feature (added to a forked version of the collector)  I realized that it wasn't what I needed - most of the resource attributes were junk I didn't need (eg. python lib version etc). What I needed is just a few resource attrs translated to metric attrs (-> GMP metric labels).
I was able to copy ressource attrs to metric labels using the following processor:

```
  transform:
    metrics:
      queries:
        # set metric labels from resource.attrs
        - set(attributes["config_version"], resource.attributes["service.config_version"])
        - set(attributes["version"], resource.attributes["service.version"])
````

This basically copies `service.config_version` and `service.version` resource attrs to `config_version` and `version` metric attrs, therefore makes them available as metrics labels in GMP.
