### ISSUE TITLE
Outbound HTTP Request Span Metrics Name is Too Generic

### ISSUE THREAD

**Issue by codeforaliving** [open-telemetry/opentelemetry-collector-contrib#12181]
**Describe the bug**
We are using the span metrics processor to generate metrics for trace spans.  Inbound HTTP requests are working as expected, but outbound/downstream HTTP requests are being sent with a name/operation that is just "HTTP {method}".  I would expect the name to have the url path and look similar to inbound HTTP request span metrics.

**Steps to reproduce**
Use auto-instrumentation with a Java or Golang service that listens over HTTP and makes outbound requests as part of the same transaction.

**What did you expect to see?**
I expected the outbound/downstream HTTP request span metrics to have a more descriptive name/operation.

**What did you see instead?**
Name/operation = "HTTP {method}" (see example below)

**What version did you use?**
0.53.0 and 0.55.0

**Additional context**
Sample span

```
InstrumentationScope io.opentelemetry.apache-httpclient-4.0 1.12.0-aws
Span #0
    Trace ID       : <redacted>
    Parent ID      : <redacted>
    ID             : <redacted>
    Name           : HTTP POST
    Kind           : SPAN_KIND_CLIENT
    Start time     : 2022-07-07 15:15:20.555796775 +0000 UTC
    End time       : 2022-07-07 15:15:20.572860989 +0000 UTC
    Status code    : STATUS_CODE_UNSET
    Status message : 
Attributes:
     -> http.url: STRING(https://redacted.url/path)
     -> thread.id: INT(739)
     -> http.method: STRING(POST)
     -> thread.name: STRING(<redacted>)
     -> http.status_code: INT(200)
     -> net.transport: STRING(ip_tcp)
     -> net.peer.name: STRING(<redacted>)
     -> http.flavor: STRING(1.1)
     -> net.peer.port: INT(443)
```

**Comment by codeboten** [comment]
@codeforaliving this is consistent with the opentelemetry semantic conventions, see https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#name.
