### ISSUE TITLE
[processor/jwtparser] Processor able to parse a Json Web Token from an attribute

### ISSUE THREAD

**Issue by amoscatelli** [open-telemetry/opentelemetry-collector-contrib#12180]
**Is your feature request related to a problem? Please describe.**
As far as I understand OTEL Collector already support OIDC Authentication : 
https://github.com/open-telemetry/opentelemetry-collector/blob/36351380c02c2364250ce265565275de7cb7ac8c/config/configauth/README.md

But, It seems to me that simply parsing a standard oidc JWT token, only when present, is not supported.
I have many web application with a public, non authenticated area.
I would like to have my OTEL Collector to NOT require a Bearer TOKEN, but parsing and optionally augmenting traces with data from the JWT when it is provided.

So, once my user authenticate, I could attach Authorization header with Bearer token in requests to OTEL Collector.

**Describe the solution you'd like**
I believe configauth is already able to parse a JWT.
Maybe the JWT parse functionality could be exposed as a processor also, when include_metadata is enabled, able to map fields from JWT Authorization header to standardized OTEL fields (for example enduser.id stands for authenticated username, for Java agent).
The JWT could be read from metadata or from a configurable attribute.

Such processor should not 'validate' the JWT, we are not talking about authentication here.

Essentially, we want to be able to access these informations when sent in form of JWT Authorization Bearer :

```
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "04Md4HKUsLyWuerIOGSuycB6b6LlO5daiS36tob79mI"
}
{
  "exp": 1657209638,
  "iat": 1657209338,
  "auth_time": 1657179484,
  "jti": "04a45972-0765-4959-bc67-20d044d5f433",
  "iss": "https://iam.visiontech.cloud/auth/realms/optoplus",
  "aud": "account",
  "sub": "06b76b95-6f1b-4ca4-8e0f-8e4b1728a323",
  "typ": "Bearer",
  "azp": "optoplus-calc",
  "nonce": "eTIxYkoxcUIuNHlWa3RWckJVWkRpWXZUdmh1dmdSRmFCQkdyV1FaQUVaRXh0",
  "session_state": "e3a4ba11-9114-4bc5-8999-f877ff032c70",
  "allowed-origins": [
    "https://calc.optoplus.cloud"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid profile email",
  "sid": "e3a4ba11-9114-4bc5-8999-f877ff032c70",
  "email_verified": false,
  "name": "emilio mazzocco",
  "preferred_username": "emilio.mazzocco",
  "given_name": "emilio",
  "family_name": "mazzocco"
}
```

This can be done ?
Do you need help ?

**Comment by mshoosht-cisco** [comment]
@jpkrohling I found this abandoned feature while looking for the ability to read attributes from JWT token to label metrics following authentication with the oidcauthextension. At Cisco, we could use the feature for a product and could perform the implementation you requested of @amoscatelli previously. I am working with @svrnm internally to add functionality to support a product.

Could this issue be re-opened with the Cisco open source team performing the development?

Thanks.
