### ISSUE TITLE
[chore] ping code owners when adding component label

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#12196]
It would be awesome to automatically ping code owners or even assign issues to them when a component label is set on an issue/PR

**Comment by TylerHelmuth** [comment]
@codeboten maybe a periodically run workflow?

**Comment by codeboten** [comment]
> @codeboten maybe a periodically run workflow?

I'm thinking of triggering from the `issues.labeled` event. The thinking being that triagers can apply a label and an action will add a comment to the issue pinging code owners.

**Comment by TylerHelmuth** [comment]
Nice, I wasn't aware we could trigger a workflow like that
