### ISSUE TITLE
[receiver/hostmetricsreceiver] add parent PID to hostmetricsreceiver process metrics

### ISSUE THREAD

**Issue by davidmirza408** [open-telemetry/opentelemetry-collector-contrib#12290]
**Is your feature request related to a problem? Please describe.**
when using hostmetricsreceiver to report process metrics, a user may not want to see the noise of all child processes that are running.  This request involves reporting parent PID so that a processor can be used to aggregate the child process metrics into the parent process.

**Describe the solution you'd like**
Report parent PID of all processes being scraped by hostmetricsreceiver/process so that the information can be used by the transformprocessor to aggregate child metrics into the parent process. 

**Describe alternatives you've considered**
natively providing a config option in hostmetricsreceiver to aggregate child metrics into the parent process.

cc: @dmitryax

**Comment by dmitryax** [comment]
I believe adding resource attribute for parent PID makes sense

**Comment by dmitryax** [comment]
@davidmirza408 will you work on this?

**Comment by davidmirza408** [comment]
@dmitryax, yes I can take this up

**Comment by dmitryax** [comment]
Also please update the issue header :)

**Comment by davidmirza408** [comment]
@dmitryax all attributes that hostmetricsreceiver sets are defined here https://github.com/open-telemetry/opentelemetry-collector/blob/semconv/v0.55.0/semconv/v1.6.1/generated_resource.go#L689.  When adding parent PID, is it a requirement that we add the attribute to the semantic conventions constants?  Do you have a preference for the name?  Does process.ppid work for you?

**Comment by dmitryax** [comment]
@davidmirza408 yes, lets start with a PR to specification. Maybe `process.parent_pid`?

**Comment by evan-bradley** [comment]
Closing #12290 as completed via #12637.
