### ISSUE TITLE
could kafka export hash parittion

### ISSUE THREAD

**Issue by tuyula** [open-telemetry/opentelemetry-collector-contrib#12318]
**Is your feature request related to a problem? Please describe.**
feature: we need kafka has hash parition use TraceId Key so that we can support mutiple consumer use tail_sampling

**Describe the solution you'd like**
cause consumer use tail_sampling,  so the same traceId must consumer in the same collector

**Describe alternatives you've considered**
add some config for kafka product, add hash_product

**Comment by CoderPoet** [comment]
Yes, I also do tail sampling in kafka consumers, so I modified kafka exporter

**Comment by arik-dig** [comment]
I think that issue is more than relevant. 
other than tail_sampling it will allow achieve a greater cause - **consumption scalability**
can you please address it?

**Comment by arik-dig** [comment]
> Yes, I also do tail sampling in kafka consumers, so I modified kafka exporter

@CoderPoet maybe you could propose a PR so all the community could benefit from it?
👍

**Comment by MovieStoreGuy** [comment]
I would love to have this feature in, but I am limited in my time to contribute and spend validating the fix. 

If  @CoderPoet already has something that exists, that be awesome to see as an addition to the component.

I know there is conversations of using something like OTTL to define the keyed topic which would provide some benefits.

**Comment by jwafle** [comment]
Open PR to resolve this issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29660
