### ISSUE TITLE
Filter spans by duration.

### ISSUE THREAD

**Issue by luozenglin** [open-telemetry/opentelemetry-collector-contrib#12319]
**Is your feature request related to a problem? Please describe.**
Our system generates a lot of spans per trace, but we only care about the longer duration spans.

**Describe the solution you'd like**
 ~~I know we can use filterprocessor to filter spans by SpanNames and tailsamplingprocessor to filter traces by duration. But how can we filter spans by duration or percentage of trace duration?~~

I want to filter spans based on duration, and the user can configure to filter spans that are greater or less than the specified duration.

**Describe alternatives you've considered**

**Additional context**

**Comment by boostchicken** [comment]
This maybe possible to add to the SpanProcessor, thats where it should probably belong or maybe enhance the tailsamplingprocessor.  I don't know much about the later.

**Comment by luozenglin** [comment]
Is it possible to filter spans by duration? Will we consider supporting this feature in the future?

**Comment by boostchicken** [comment]
I am one of the owners of the the filterprocessor, we could add it there. How do you want to filter it? Just greater than or less than?  Previously when I wrote code that dropped spans it was semi-frowned upon because it does break traces and we make no effort to fix it via updating parent_id.  

I am cc'ing @pmm-sumo on this as the other owner.  I think the code would be trivial.  I just want to confirm we want this.

**Comment by pmm-sumo** [comment]
Filtering spans might cause effects not anticipated by the users, like breaking the trace (and I believe this is why we were hesitant in adding it). Having said that, we have eventually included some span filtering capabilities, so I believe we can extend if further. Perhaps the README.md should come with some warning on using it

I also think there's a space for "trace-reshape" processor or so, which could e.g. join some spans together (or remove one and connect ancestor and descendant). That's just food for thought though

In any case, I am not against adding filtering by duration capability to span filter

**Comment by boostchicken** [comment]
I don't think its possible to have the length a trace in any context where we could do that.  A trace doesn't have an end time, its just a compiliation of spans that can come in out of order, so a single batching being processed might not have all of a trace.

**Comment by luozenglin** [comment]
Can we take the duration of the root span as the total time? This might be a bit like how the tailsamplingprocessor is implemented.

**Comment by boostchicken** [comment]
hmmm? the duration of the root span wont be the duration of the trace

**Comment by boostchicken** [comment]
> Filtering spans might cause effects not anticipated by the users, like breaking the trace (and I believe this is why we were hesitant in adding it). Having said that, we have eventually included some span filtering capabilities, so I believe we can extend if further. Perhaps the README.md should come with some warning on using it
> 
> I also think there's a space for "trace-reshape" processor or so, which could e.g. join some spans together (or remove one and connect ancestor and descendant). That's just food for thought though
> 
> In any case, I am not against adding filtering by duration capability to span filter

I am curious how we would do this.  Would we keep a rolling cache of every span we drop and if that id comes up we attach it the parent_id of the d ropped span? This won't help with out of order spans or spans in a different transaction than the one dropped (unless we start storing stuff in memory for a while).

What do you think @pmm-sumo

**Comment by boostchicken** [comment]
@luozenglin so just greater than or less than is fine?  Can you edit your issue to clearly request this feature

**Comment by luozenglin** [comment]
> @luozenglin so just greater than or less than is fine? Can you edit your issue to clearly request this feature

I've updated the issue, do I need to provide more?

**Comment by bmbferreira** [comment]
👋 I also want to filter spans by duration. I see that the pull request was closed without being merged. Can we reopen this and recover the pull request that was in progress?

**Comment by fantapop** [comment]
@boostchicken was there any blockers here?

**Comment by boostchicken** [comment]
Yes I am doing some career changes and need to make sure all the legalities are taken care of. I just got my forms and will be writing up for approval tonight. I will never make the mistake of accepting verbal approval again

**Comment by boostchicken** [comment]
If it's super critical let me know and I can probably work something out

**Comment by fantapop** [comment]
It's Not critical. Best of luck to you.

**Comment by chittalpatel** [comment]
You can filter spans by duration by simply doing this:
```
filter/duration:
  traces:
    span:
      - (end_time - start_time) <= Duration("1s")
```

**Comment by bmbferreira** [comment]
> You can filter spans by duration by simply doing this:
> 
> ```
> filter/duration:
>   traces:
>     span:
>       - (end_time - start_time) <= Duration("1s")
> ```

yup that works. Created this PR to add it as an example: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41889
