### ISSUE TITLE
OpenSearch exporter enhancements

### ISSUE THREAD

**Issue by StefanSa** [open-telemetry/opentelemetry-collector-contrib#12323]
**Is your feature request related to a problem? Please describe.**
Currently the OpenSearch exporter is made #10206, many thanks for that.
However, only with support for pipeline type `logs`.

**Describe the solution you'd like**
Since `opensearch` released the `observability plugin`, it would be great if the `OpenSearch exporter` would also
`support pipelines for metrics, logs and traces`.

**Describe alternatives you've considered**
Currently there is a partial solution, only metrics and traces, with the open source data collector `data preper`. 
It would be better if you could do without this (any) additional collector(s) and do everything with the `OpenSearch exporter`.

**Additional context**
n/a

**Comment by TylerHelmuth** [comment]
@StefanSa is the OpenSearch exporter you're referring to still housed in Contrib?

**Comment by StefanSa** [comment]
Hi @TylerHelmuth 
Yes, this is just created by this PR #10206 of @Tomaslongo.
If I'm not mistaken, this is based on the elasticserach-exporter and this currently only supports `logs`, it would be great if `metrics and traces were also supported here`.

**Comment by kroatti** [comment]
I can't find this opensearch exporter. How can I use it? Is there any docs or example?

**Comment by TylerHelmuth** [comment]
@kroatti the OpenSearch Exporter is only a component proposal at this point; it has not yet been accepted into this Contrib repository.  See the PR linked in the description for more details.
