### ISSUE TITLE
Failed to create stream token

### ISSUE THREAD

**Issue by NareshChinnusamy** [open-telemetry/opentelemetry-collector-contrib#12329]
### Failed to create stream token 

1. I have been trying to use the open telemetry collector in **Aws Ecs - Ec2 mode**.
2. I'm running the open telemetry collector using java agent with collector config of "--config=/etc/ecs/ecs-default-config.yaml".
3. aws-otel-collector was successfully started and came to the stage of "Everything is ready. Begin running and processing data.".
4. After that, It successfully starts processing resource metrics.
5. While exporting the resource metrics with awsemf, I have been facing the following issue : 
`2022-07-12T12:45:50.706Z	warn	cwlogs@v0.45.1/pusher.go:280	Failed to create stream token	
{
    "kind": "exporter",
    "name": "awsemf",
    "error": "RequestError: send request failed\ncaused by: Post \"https://logs.us-east-1.amazonaws.com/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
}` 
But I have successfully been able to export metrics to cloud watch with **Aws Ecs - Fargate mode**.
Can someone help me with this?

**Comment by boostchicken** [comment]
I am going to assume a client timeout means a routing / security group issue.  The request is sent but never gets a response.  Check to make sure your EC2 instances either have outbound to 0.0.0.0/0, or you have a vpcEndpoint configured for logs.us-east-1.amazonaws.com (recommended)

**Comment by NareshChinnusamy** [comment]
Hi @boostchicken, I checked the outbound rule. It's all good. I'm able to send the collector metrics using the Fargate approach(same security group) without any request time-out issues.

**Comment by NareshChinnusamy** [comment]
Hi @boostchicken, Otel collector via Ec2 Approach is successfully able to push metrics to cloud watch after configuring the VPC endpoint for logs.us-east-1.amazonaws.com and creating an inbound rule in sg with 443 port. Thanks, @boostchicken.

**Comment by NareshChinnusamy** [comment]
@boostchicken Are there any options without using the VPC end point for cloudwatch logs?

**Comment by NareshChinnusamy** [comment]
@boostchicken  Got it man thank you...
