### ISSUE TITLE
Logs gets missing in collector

### ISSUE THREAD

**Issue by davidgargti20** [open-telemetry/opentelemetry-collector-contrib#12321]
I am exporting logs from java app using otel agent to collector but I am not able to see some logs in output. used file,logging,googlecloud exporter all doesn't show some logs. Sometimes some logs are visble  in googlecloud but are missing in logs exported by logging.

**Comment by davidgargti20** [comment]
could you please give more detail by curl call you mean ?

**Comment by jpkrohling** [comment]
The Java app is sending data via OTLP to the collector by making an HTTP call (or gRPC). If you are able to reproduce this call, it would help us reproduce the problem. If you can't, try to provide a sample java project that reproduces the problem. The goal is to help us reproduce the problem you are reporting.
