### ISSUE TITLE
[sqlqueryreceiver] TestOracleDBIntegration test times out

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#12332]
See an example here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7303422652?check_suite_focus=true#step:5:1016

**Comment by crobert-1** [comment]
This is referenced in #12203. It looks like we may need to keep increasing the timeout level, or figure out another way to implement the `TestOracleDBIntegration` test that requires the longer timeout.

**Comment by dmitryax** [comment]
> It looks like we may need to keep increasing the timeout level, or figure out another way to implement the TestOracleDBIntegration test that requires the longer timeout.

2 option would be the best to try first. This takes currently takes too much time

**Comment by atoulme** [comment]
This is because the docker image itself used for this is quite large, and it takes a long time for it to download.

**Comment by dmitryax** [comment]
Should be fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14717
