### ISSUE TITLE
[receiver/postgresql] PostgreSQL Component Enhancements

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#12338]
**Is your feature request related to a problem? Please describe.**

The current component currently does not use any of the newer features like `resource_attributes` and does not collect in such a matter that `EmitForResource()` works nicely. 

Along with this I feel like the current receiver is missing the following metrics

```
postgresql.table.index.size
postgresql.table.index.scans
postgresql.table.query.duration
postgresql.bgwriter.checkpoint.count
postgresql.bgwriter.duration
postgresql.bgwriter.maxwritten.count
postgresql.bgwriter.buffers.allocated.count
postgresql.bgwriter.buffers.write.count
```

**Describe the solution you'd like**
I'd like to bring the component up to date with convention and also add aforementioned metrics.

**Describe alternatives you've considered**
I've contemplated just adding the metrics but feel as though it would be good to bring the component up to date. One thing to consider is this might cause some required changes based off current labeling of metrics not using resource attributes.

**Additional context**
I'm happy to attempt a draft PR before anyone signs off on this!

**Comment by schmikei** [comment]
> @schmikei, did you end up splitting this into separate issues? It seems to me that the resource attribute changes should be applied first, and then new metrics can be added once resources are being properly differentiated.

@djaglowski I initially attempted to get metrics in first thinking it was going to be more additive (#12889)  before breaking stuff out into their respective resource attributes but I think you may be right that this might be the preferred approach. I'll go ahead and see if I can cut a breaking change PR for that. Will keep you posted!

**Comment by evan-bradley** [comment]
@schmikei It looks like all the metrics listed in this issue have been addressed in the split-off issues. Can this be closed?

**Comment by schmikei** [comment]
> @schmikei It looks like all the metrics listed in this issue have been addressed in the split-off issues. Can this be closed?

Sure thing 👍
