### ISSUE TITLE
[receiver/vcenter] vcenter.vm.disk.utilization was inproperly calculated

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#12342]
**Describe the bug**
- Metric was improperly calculated like this:

> ```go
> diskUtilization := float64(diskUsed) / float64(diskFree) * 100
> ```

when it should be calculated like
>```go
>diskUtilization := float64(diskUsed) / float64(diskFree+diskUsed) * 100
>```

**Steps to reproduce**
Looking at a live environment in Google Cloud noticed the value was incorrect.

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/32067685/178582042-3a351328-4f91-46f8-b32f-c1082904b75b.png">

**What did you expect to see?**

For our example storage uncommitted was 10539597824 bytes and committed was 139787059517 bytes which should be calculated as 

```math
139787059517 bytes ÷ (10539597824 bytes + 139787059517 bytes) * 100% = 92.9888696985 %
```

<img width="270" alt="image" src="https://user-images.githubusercontent.com/32067685/178582965-efc31424-19b9-46af-8677-285e2704e651.png">

**What did you see instead?**

The value was rather 
139787059517 bytes ÷ (10539597824 bytes) * 100% = 1398 %

**Additional context**

Will have a PR shortly to fix calculation.

**Comment by djaglowski** [comment]
There appear to be three unrelated changes here, so an issue for the cpu metric, and another for the resource label.

**Comment by schmikei** [comment]
Alright I'll separate them out 👍

**Comment by schmikei** [comment]
@djaglowski I think this should work but let me know if anything needs changes!

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12343 
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12359 
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12360
