### ISSUE TITLE
Missing "Support Status" section on Azure Monitor exporter documentation

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-collector-contrib#12341]
**Describe the bug**
The documentation for the AzureMonitor exporter is lacking the standard table describing what status the plugin is in (dev, alpha, beta, etc), supported pipelines and distributions.

**Steps to reproduce**
Access the exporter page and check readme:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter

**What did you expect to see?**
I expected to see the table showing which support status the plugin is in at the top of the doc similar to how it is presented for all other components (example Elastic exporter):
![image](https://user-images.githubusercontent.com/461579/178578286-c26c65d5-8015-49d1-a017-df57e3a60620.png)

**What did you see instead?**
The support table is missing. Information about it supporting only logs and traces is available in text form however.

**What version did you use?**
N/A.

**What config did you use?**
N/A

**Environment**
N/A

**Additional context**

**Comment by atoulme** [comment]
The header was added as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14916 and this issue can now be resolved.
