### ISSUE TITLE
Split traces from batch

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#1235]
**Is your feature request related to a problem? Please describe.**

A new OpenTelemetry Collector might be needed to be placed before the load balancer (#1231), as it expects all spans in a batch to belong to the same trace. We have the groupbytrace processor which has a similar purpose, but it holds items in memory releasing all at once. This here is a variant of that, and will release the batch right away.

**Describe the solution you'd like**
A simple processor that will just get an incoming `pdata.Traces`, group all spans from the same trace into individual `pdata.Traces` and call the next consumer N times, one for each grouped `pdata.Traces`.

**Comment by chris-smith-zocdoc** [comment]
If the `splitByTrace` function from groupbytrace was exposed as a utility function, implementing this would be straightforward. I actually am using approach in our build of the collector for this exact use case

**Comment by objectiser** [comment]
@jpkrohling Would it be clearer to name the processor `batchPerTrace` or something like that? `splitbatch` doesn't clearly convey criteria it is using to determine the split.

**Comment by jpkrohling** [comment]
I was struggling to find a good name, and I think you just found one. `batchPerTrace` sounds good to me.
