### ISSUE TITLE
[exporter/datadog] api key needs to be provided as a plain value, instead of stored in a secret

### ISSUE THREAD

**Issue by gabrielqs** [open-telemetry/opentelemetry-collector-contrib#12414]
**Is your feature request related to a problem? Please describe.**
When configuring the datadog exporter a plain API key is required. From a security perspective this is a quite big risk i'd like to avoid.

**Describe the solution you'd like**
Similar to the [datadog agent configuration](https://github.com/DataDog/helm-charts/blob/main/examples/datadog/agent_basic_values.yaml#L8), I would like to configure the otel datadog exporter using an existing secret instead of providing it with a plain api key.

**Describe alternatives you've considered**
Haven't found any viable alternatives other than providing the key as plain text.

**Additional context**
In my current use case, where the open telemetry configuration is managed via fluxcd, this means i will need to store the key in our VCS. I understand this might be tricky given the generic nature of the otel collector and it not being intended solely for kubernetes usage, but as this is probably a common use case i do believe it's worth investigating alternatives.

**Comment by mx-psi** [comment]
👋 You can pass the API key through an environment variable; this is documented here: https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables

This is the recommended way of passing secrets on the configuration per [this document](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security.md#configuration):
> Sensitive information SHOULD be stored securely such as on an encrypted filesystem or secret store. Environment variables CAN be used to handle sensitive and non-sensitive data [...]

Does this answer your question?

**Comment by gabrielqs** [comment]
Oh my god, i am sorry. it does. i actually went through the process of creating an init container to inject the env vars into the config, I should have read the manual first. thank you so much!

**Comment by mx-psi** [comment]
No worries, glad to have helped :)
