### ISSUE TITLE
[Changelog] Determine requirements for denoting PR and/or Issue #'s

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#12417]
Changelog entries have historically denoted the PR # with which they are associated. Recently, with the introduction of the `chloggen` tool, contributors are asked to associate each entry with one or more Issue #'s.

This change was questioned and discussed in today's SIG. Several alternative approaches were suggested, but no decision was reached. As best I recall, the following options were discussed:

### Keep the current behavior. 

_Pros_
- Contributors do not need to push an additional change immediately after opening every PR.
- CI is not "double-triggered" due to the immediate followup commit that adds the PR number.
- Encourages good habits for creating tracking issues. 

_Cons_
- Navigating from the changelog to the PR that introduced the actual change is more complicated and less reliable.

### Require the pull request number. 

Pros & Cons are basically the inverse of those listed in the previous option.

### Accept both, require at least one or the other

Potentially, the chloggen's yaml format would be enhanced to allow issue #'s to be specified separately. Correspondingly, the changelog could call out whether each # is an issue or PR.

_Pros_
- Unambiguous, both for contributors and changelog readers
- Flexible for contributors

_Cons_
- Changelog format potentially cluttered

Alternately, the chloggen format does not differentiate between issues and PRs, and neither does the changelog, but either way a number is required. Possibly, contributors are asked to favor one or the other. It was noted that .NET uses this option with a bias towards PRs.

_Pros_
- Flexible for contributors
- Changelog format appears clean

_Cons_
- Linking from changelog provides inconsistent experience

**Comment by djaglowski** [comment]
cc @Aneurysm9 @TylerHelmuth @codeboten

**Comment by TylerHelmuth** [comment]
I think my favorite solution is one where we can use the PR in the changelog to address the CON `Navigating from the changelog to the PR that introduced the actual change is more complicated and less reliable.` and also at the same time keep the PRO `Contributors do not need to push an additional change immediately after opening every PR.`

Maybe there is a way to templatize the changelog entry and then have an initial job run that gets the PR number, inserts it into the change log.  That commit and push would probably kick off another round of workflows, which if we don't like we could probably handle by making the other workflows depended on this one or maybe there is another way to block until this workflow completes.  Having our workloads cancel when a new round kicks off would also be good. 

In lieu of a solution that can meet that, I think I'll vote for going back to PR.  I think the risk of not being able to get to the actual change that implemented the changelog entry is too much of a CON now that @Aneurysm9 has brought up that possibility.

**Comment by TylerHelmuth** [comment]
> I think this adds a lot of complexity with very little gain. 

you're probably not wrong.

> change the yaml format and associated documentation/comments to clarify that the PR number is preferred over the issue number(s), but ultimately both are acceptable

I'll be honest, if we do this I'll probably always add an issue because I don't like doing the immediate update with the PR number lol I am consistent with linking my PRs and Issues, but what does it say if an approver always does the opposite of the preferred method.

**Comment by djaglowski** [comment]
My preferred path forward would be to do the following:
1. Add a `pull_request` field to the template.
2. Validate that at least one of `issues` or `pull_request` is specified.
3. Update the changelog template to call out both issues and PR explicitly:
```
- `transformprocessor`: Update foo (PR: #2222)
- `transformprocessor`: Update foo (Issue: #1111)
- `transformprocessor`: Update foo (Issues: #1111, #3333)
- `transformprocessor`: Update foo (Issue: #1111) (PR: #2222)
```

This accomplishes the following:
- Creating issues is optional
- "Followup" commits for adding the PR number are optional
- Changelog is clear (though obviously does not cite PR for every change)

**Comment by djaglowski** [comment]
After playing with my proposed implementation, I found the categorized links eg. `(Issue: #1111) (PR: #2222)` to be too noisy. I ended up trying a variation that just asks for `github_nums` and keeps the concise format we currently use. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13121

**Comment by codeboten** [comment]
Keeping what we currently have makes sense to me. Closing this issue.
