### ISSUE TITLE
Otel Collector Prometheus writing to Metrics Endpoint Wire Type error

### ISSUE THREAD

**Issue by blakeromano** [open-telemetry/opentelemetry-collector-contrib#12412]
### What did you do?

I added a remoteWrite section to the Prometheus CRD that sends Metrics from Prometheus to the HTTP port of an Otel Collector. I added the url and a name as configuration parameters.

### What did you expect to see?

I expected to see metrics successfully going through the remoteWrite from Prometheus to OpenTelemetry Collector's Metrics endpoint.

### What did you see instead? Under which circumstances?

In the prometheus logs I see this
```text
ts=2022-07-12T19:12:03.665Z caller=dedupe.go:112 component=remote level=error remote_name=jamespace-dev
 url=https://opentelemetry-collector-http-host/v1/metrics msg="non-recoverable error" count=2 exemplarCount=0 err="server returned HTTP status 400 Bad Request: \u0008\u0003\u0012\u0019proto: illegal wireType 6"
```
And there is no logs from the Otel Collector to help. There is also no data being written according to the metrics endpoint on the Otel Collector's metrics port.

### System information

Running On Kubernetes CRD on EC2. And Open Telemetry Collector Helm Chart 

### Prometheus version

```text
kubectl get prometheus
NAME                 VERSION   REPLICAS   AGE
prom-jamespace-dev   2.35.0    2          308d
```

### Prometheus configuration 
```yaml
Spec:
  Remote Write:
    Name:  jamespace-dev
    URL:                     https://opentelemetry-collector-http-host/v1/metrics
```

### Logs in Prometheus Pod

```text
ts=2022-07-12T19:12:03.665Z caller=dedupe.go:112 component=remote level=error remote_name=jamespace-dev
 url=https://opentelemetry-collector-http-host/v1/metrics msg="non-recoverable error" count=2 exemplarCount=0 err="server returned HTTP status 400 Bad Request: \u0008\u0003\u0012\u0019proto: illegal wireType 6"
```

**Comment by fatsheep9146** [comment]
What's your configuration of otel-collector?

**Comment by gouthamve** [comment]
Hi, we don't have a `prometheusremotewritereceiver` yet. You can only write to OTel collector using the `/v1/metrics` endpoint via OTLP and not Prometheus Remote Write.

You can on the other hand use the opentelemetry operator: https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspectargetallocator to scrape the metrics directly into the Collector using the same Prometheus CRDs.

**Comment by blakeromano** [comment]
@gouthamve Is there a reason none of the helm charts allow the usage of the CRD? I would have never known that was even an option with the helm chart for Operator or Collector...

**Comment by VineethReddy02** [comment]
@blakeromano [here](https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#target-allocator) are some details on targetallocator, this is an optional configuration in operator, so isn't enabled by default. I agree that this feature needs documentation and positioning on the top level of Otel-Operator.
