### ISSUE TITLE
[processor/cumulativetodelta] Convert cumulative Histograms to delta temporality

### ISSUE THREAD

**Issue by mistodon** [open-telemetry/opentelemetry-collector-contrib#12423]
**Is your feature request related to a problem? Please describe.**
It seems that cumulative-to-delta at the moment only processes Sums, and just skips over other data types. This is a problem for us, as we have Histograms in our pipeline with cumulative temporality that we want to convert.

**Describe the solution you'd like**
Rather than bypass Histogram metrics, have the cumulative-to-delta processor convert their data points in a similar way to sums.

**Describe alternatives you've considered**
None, other than continuing to ignore non-Sum metrics.

**Comment by TylerHelmuth** [comment]
Yes I would love for this capability to exist.  Is it something you plan to work on?

**Comment by TylerHelmuth** [comment]
Sounds great

**Comment by mistodon** [comment]
There's definitely some things that could be refactored in the above PR, but I want to make sure people are happy with the general approach before I do that.
