### ISSUE TITLE
[prometheusreceiver] Use _created to set StartTimeUnixNano

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#12428]
Currently we're using [`MetricsAdjuster`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/otlp_metrics_adjuster.go) to set the `StartTimeUnixNano` for the metrics. But when `{name}_created` is available we should use that.

See: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12426

**Comment by dashpole** [comment]
We will also need to make some changes to the [prom specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#prometheus-compatibility) to support this:

* Prometheus exporters (including language + collector) SHOULD produce `_created` series for cumulative types, but this can be turned off.
* The prometheus receiver MUST drop the _created series, if present, and use it to set the start timestamp.

**Comment by dashpole** [comment]
I just noticed https://github.com/open-telemetry/opentelemetry-specification/pull/2645, so no spec change is needed
