### ISSUE TITLE
Add connection timeout to client example

### ISSUE THREAD

**Issue by ivanrusanov** [open-telemetry/opentelemetry-collector-contrib#12431]
**Describe the bug**
I'm trying to run `examples/demo/client/main.go` but it is stuck at `otlptrace.New(ctx, traceClient)`.

**Steps to reproduce**
I have no idea how to emulate such connection problems

**What did you expect to see?**
I expect to get connection timeout error.

**What did you see instead?**
It freezes

**What version did you use?**
Version: `v0.55.0`

**What config did you use?**
Default

**Environment**
OS: Ubuntu 20.04
Compiler(if manually compiled): go 1.18.3

**Additional context**
Consider add:
```
ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
defer cancel()
```
Before `traceExp, err := otlptrace.New(ctx, traceClient)` in _examples/demo/client/main.go:initProvider_

**Comment by fatsheep9146** [comment]
Do you start the otel-collector ?

**Comment by ivanrusanov** [comment]
@fatsheep9146 yes. But after starting collector, example client and server nothing new appears in collector log after `Everything is ready. Begin running and processing data.`.
