### ISSUE TITLE
[tracegen] should be under `cmd/` for consistency

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#12474]
`tracegen` is a command that really should be under `cmd/`

**Comment by TylerHelmuth** [comment]
I _think_ `tracegen` is being replaced by `telemetrygen` which is under command.  Not sure of the status of that work.

**Comment by mx-psi** [comment]
> I _think_ `tracegen` is being replaced by `telemetrygen` which is under `cmd/`. Not sure of the status of that work.

That's the plan, yes. We have an engineer from Datadog who will work on this, but the work has been delayed.

**Comment by codeboten** [comment]
@TylerHelmuth correct, I figured in the meantime there's no reason for `tracegen` not to also live in `cmd/` :)
