### ISSUE TITLE
Triager role request for @gouthamve

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#12484]
Formal request to grant triager scope to @gouthamve.

Reason for request: I am a Prometheus maintainer with with the focus on making all this Prometheus work seamlessly inside OTel and the Collector. I would like to help @dashpole close/tag and act on the Prometheus related issues. I've been contributing to the Collector since Januaray. 

I participate in the Prometheus WG and fulfill [the requirements for a triager role](https://github.com/open-telemetry/community/blob/main/community-membership.md).

**Comment by gouthamve** [comment]
I am also happy to expand the scope to all of collector issues as well (not just Prometheus), but I am not fully confident about the other areas. 

Please let me know if this is something you'd like me to work towards.

**Comment by TylerHelmuth** [comment]
Hello @gouthamve, a good start towards being added to this role would be attending the Weekly Collector triage meeting on Fridays at 10am PT.  [You can find a link to the meeting in the public calendar.](https://github.com/open-telemetry/community#calendar).  Let us know if the meeting's time does not work.

**Comment by gouthamve** [comment]
I've added the meeting to my calendar and didn't know about this. I live in Europe and 7PM on Fridays is a little tough sell tbh. Having said that, I will try my best to attend these and hopefully I'll see you in the next one!

**Comment by TylerHelmuth** [comment]
Ya thats a rough time slot.  Are you able to attend the Collector SIG meetings on Wednesday at 10am? @dashpole do you nominate @gouthamve? 

In the mean time it would be a huge help if while you are triaging issues you can pinging @open-telemetry/collector-contrib-approvers with the labels that should be added.

Thanks for being interested in this role! We desperately need triagers.
