### ISSUE TITLE
[pkg/telemetryquerylanguage] Add ordering inequalities to comparisons

### ISSUE THREAD

**Issue by kentquirk** [open-telemetry/opentelemetry-collector-contrib#12491]
**Is your feature request related to a problem? Please describe.**
Currently, TQL supports strict equality ('==') and inequality ('!='). It would be useful to support ordering comparisons as well -- specifically, ('<'), ('>'), ('<='), and ('>=').

Adding them to the grammar is pretty simple, but it's slightly trickier to extend the expression evaluators. 

**Describe the solution you'd like**
We need to define the semantics appropriately for comparing two values that may potentially be different base types.  The semantics should be symmetric (`a < b` should give the identical result to `b > a`). Also, there really can't be the concept of an error -- the condition just has to return a boolean result. 

We propose that comparisons between different types always evaluate to false. Anything else can be fixed with type coercion functions.

The details:

base type | bool | int | float | string | Bytes | nil 
-|-|-|-|-|-|-
bool | normal, T>F | false | false | false | false | false
int | false| normal | int coerced to float | false | false | false
float | false | int coerced to float | normal | false | false | false
string | false | false | false | normal (compared as utf8 strings) | false | false
Bytes | false | false | false | false | byte-for-byte comparison | false
nil | false | false | false | false | false | true for equality only

**Describe alternatives you've considered**
Alternatives are:
- Don't do it at all -- but people need this.
- Don't extend the grammar, provide functions that can compare values. This would look something like `Compare(http.return, 400, ">") == true`. I think this is unnecessarily wordy.

Within this proposal, we could try harder to coerce things into compatible types. For example, when comparing a string to a numeric value, we could try to parse the string as a numeric value. This would allow, say, comparing an http return of "500" to 500. Personally, I'd rather fix this with explicit type conversion functions like `int("500")`. Similarly, bools could be coerced to numeric values (0 and 1, or 0 and -1) with `int()` or `float()` functions.

**Comment by kentquirk** [comment]
@TylerHelmuth ^ thoughts?

**Comment by TylerHelmuth** [comment]
Also, I think "Missing" is the same as the literal "nil" case.  If a Getter returns nil it should be treated the same as nil.  I don't think we should assume `0`, or `0.0` for instance, I think comparison with nil would be false always.

**Comment by kentquirk** [comment]
@TylerHelmuth I have been implementing this, and I'm having second thoughts about a couple of things:

* the idea that all comparisons return false for noncomparable types. I now am thinking that `!=` Not Equals should have the inverted sense here -- `3 != "hello"` should be `true` (but `3 < "hello"` and `3 > "hello"` are both false).  I am arguing for this one.
* whether an empty Bytes should compare as equal to nil (I think it should but won't be too upset if there's a good argument not to)
* whether an empty string should be equal to nil (probably not, but I don't feel strongly)
* whether the zero value in general should be considered equivalent to nil (probably not, but again I'm not strong)

Thoughts?

**Comment by TylerHelmuth** [comment]
> I've dropped the idea that all comparisons return false for noncomparable types. I implemented it so that != (Not Equals) has the inverted sense -- 3 != "hello" should be true (but 3 < "hello" and 3 > "hello" are both false). I have implemented this.

I think this makes sense.

When the PR is ready let me know and I'll take an in-depth look.
