### ISSUE TITLE
Add Support for Jaeger Kafka Exporter

### ISSUE THREAD

**Issue by joe-elliott** [open-telemetry/opentelemetry-collector-contrib#125]
As discussed here:  https://github.com/open-telemetry/opentelemetry-collector/issues/500

Jaeger Kafka exporter support should be added to the collector through the contrib repo.

**Comment by yurishkuro** [comment]
What is the mechanism used to pull contrib code into the main binary?

**Comment by tigrannajaryan** [comment]
>What is the mechanism used to pull contrib code into the main binary?

@yurishkuro by adding a factory here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/cmd/otelcontribcol/components.go

**Comment by pavolloffay** [comment]
As an experiment, I have built https://github.com/jaegertracing/jaeger-opentelemetry-collector. At the moment it only includes Jaeger Elasticsearch exporter and the set of the default components. It might be easier to directly build the OTEL collector in the main Jaeger repository - it does not have to be hosted separately.

We should decide where Jaeger storage exporters will live. It depends if we want to add Jaeger specific functionality to the collector. For example one of the missing features is serving sampling strategies.

**Comment by joe-elliott** [comment]
@pavolloffay 
I am working on sampling strategies now to resolve this issue: https://github.com/open-telemetry/opentelemetry-collector/issues/500

**Comment by yurishkuro** [comment]
> It might be easier to directly build the OTEL collector in the main Jaeger repository

+1

**Comment by tigrannajaryan** [comment]
@yurishkuro @pavolloffay I am happy to see you are building on top of OpenTelemetry Collector. Do you mind sharing a bit more about what you plan to do? It would be great to know how the Collector is used by Jaeger.

**Comment by joe-elliott** [comment]
Per discussions with Jaeger this functionality is being implemented in https://github.com/jaegertracing/jaeger-opentelemetry-collector and probably does not make sense to implement here as well.

@ledor473, I believe that once jaeger-opentelemetry-collector is up to date with master (for the sampling json) and they add the Kafka exporter this project will meet your needs.

cc @pavolloffay

**Comment by pavolloffay** [comment]
+1 on what @joe-elliott said. I will just add that in Jaeger we are considering supporting OTEL proto as a first-class citizen. Therefore the contrib repository could provide kafka exporter and in the Jaeger collector there will be an importer for kafka in OT proto format.

**Comment by tigrannajaryan** [comment]
> Per discussions with Jaeger this functionality is being implemented in https://github.com/jaegertracing/jaeger-opentelemetry-collector and probably does not make sense to implement here as well.

Closing this issue as there is nothing else needed to be done in this repo.
