### ISSUE TITLE
[exporter/pulsar] Tests are failing on Windows with -race check

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#12518]
```
go test -race -v -timeout 300s --tags="" ./...
==3684==ERROR: ThreadSanitizer failed to allocate 0x000003379000 (53972992) bytes at 0x200dad33e0000 (error code: 87)
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/pulsarexporter	0.084s
FAIL
```

https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7330465915?check_suite_focus=true

**Comment by dmitryax** [comment]
Hey @tjiuming, I created an issue for the race issue for pulsar exporter. This means that it cause race conditions on Windows. Do you have a chance to take this ticket and investigate it further?

**Comment by tjiuming** [comment]
Sorry, I dont have a windows computer to locate the issue
