### ISSUE TITLE
[AWSXRayExporter]  it generates a new trace id when receiving a invalid trace id, which hide the true issues.

### ISSUE THREAD

**Issue by wyTrivail** [open-telemetry/opentelemetry-collector-contrib#1255]
**Describe the bug**
XRayExporter generates a new trace id if the incoming trace id is a invalid XRay format, it hide the true issues in some cases.

For example, we can see the trace data in XRay console, however the trace id is different with the one emitted by SDK. 

**Steps to reproduce**

We can send trace data with ids which are not the xray format. 

**What did you expect to see?**

I'd like to see an error thrown from XRayExporter, instead of quietly dropping the trace id and generating a new one.

**What did you see instead?**
I see no error, instead, i can see trace data in xray console, however the trace id is different than the one emitted from sdk.

**What version did you use?**
the latest one. 

I think we can start the discussion from "is it a right expected behavior and is there any customer relying on this feature?"

**Comment by anuraaga** [comment]
I agree that since the chance of the trace ID conversion working correctly (trace doesn't cross a seconds boundary) is fairly limited, it's a worse bandaid than the problem. @kbrockhoff do you happen to rely on this behavior? If not, let's remove it.

**Comment by kbrockhoff** [comment]
We do not rely on this behavior. The original objective was to no lose info if an originating application was generating non X-Ray compatible IDs. The missing span would tell us which component needed a traceID generation fix.

**Comment by wyTrivail** [comment]
maybe i can close this issue since it's merged?
