### ISSUE TITLE
[receiver/otlpjsonfile] Excessive errors created when consuming multi-signal files

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#12603]
This receiver can consume a file containing multiple signal types. However, each signal type will process all other signal types as errors.

**Comment by atingchen** [comment]
When the signal type does not match the processor‘s  signal type, should we ignore the signal instead of erroring?

**Comment by djaglowski** [comment]
Yes, I think so. The challenge is to efficiently determine if the signal matches the correct type.

**Comment by atingchen** [comment]
> Yes, I think so. The challenge is to efficiently determine if the signal matches the correct type.

Can we try to use `tlv` format  to solve this problem?
When fileexporter exports the data in JSON format, it uses the signal type as the tag, and then writes the tag, data length and json object to the file.
Then in the receiver, we first read the tag to determine whether the signal matches.
But I think this might be a breaking change that prevents the old data from being read.

**Comment by atingchen** [comment]
pdata.JSONUnmarshaler use `jsoniter` to unmarshalls from OTLP json bytes.[#5433](https://github.com/open-telemetry/opentelemetry-collector/pull/5433).
It ignores unknown fields instead of erroring. So  if the signal doesn't matches the correct type, there will be no errors.
Or can we tell if the signal matches based on whether the struct after unmarshal is empty?

**Comment by atingchen** [comment]
> pdata.JSONUnmarshaler use `jsoniter` to unmarshalls from OTLP json bytes.[#5433](https://github.com/open-telemetry/opentelemetry-collector/pull/5433). It ignores unknown fields instead of erroring. So if the signal doesn't matches the correct type, there will be no errors. Or can we tell if the signal matches based on whether the struct after unmarshal is empty?

This solution does not introduce breaking changes.

**Comment by djaglowski** [comment]
I think any non-breaking solution is a reasonable improvement for now. If performance appears to be an issue, someone can propose an alternate strategy.

I like the `tlv` idea, but I think that only works for a more generic receiver where it can be specified as the expected format.

**Comment by atingchen** [comment]
I'll think about how to implement it.

**Comment by atoulme** [comment]
I can take this on. Please assign to me unless @atingchen is still looking into it.

**Comment by atingchen** [comment]
> I can take this on. Please assign to me unless @atingchen is still looking into it.

Thank you for your willingness to take this on，I can't support it for the time being.

**Comment by atoulme** [comment]
@fatsheep9146 please assign to me when you get a chance, thanks!
