### ISSUE TITLE
[exporter/coralogixexporter] Add support for logs

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#12601]
**Is your feature request related to a problem? Please describe.**

Use OpenTelemetry Collector to send Log data to coralogix.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TylerHelmuth** [comment]
Closing based on merged PR.  Let me know if it needs reopened for any reason.
