### ISSUE TITLE
hostmetrics receiver: question about system.cpu.utilization

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#12602]
unit of system.cpu.utilization seems to be 1 instead of percentage(see [document](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/cpuscraper/documentation.md
)), according to  https://pkg.go.dev/github.com/shirou/gopsutil@v3.21.11+incompatible/cpu#TimesStat

> TimesStat contains the amounts of time the CPU has spent performing different kinds of work. Time units are in seconds. It is based on linux /proc/stat file.

and cpuscraper code [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper_linux.go#L28), also from our observation, the system.cpu.utilization in total equals the amount of CPU on the host.

**Comment by F21** [comment]
I am also seeing discrepancies between the `system.cpu.utilization` reported by the hostmetrics receiver and monitoring from my cloud provider. My understanding is that `system.cpu.utilization` is the percentage utilization andis between 0 and 1, but in my case, if I aggregate by mean, the usage is around 12.5%, whereas my cloud provider is logging around 1%.
