### ISSUE TITLE
[check-codeowners.sh] Validate entries in ALLOWLIST are not owned

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#12629]
The `.github/scripts/check-codeowners.sh` script is useful to validate that components have an owner by checking that all entries on CODEOWNERS are valid and are not in the ALLOWLIST file.

It would be useful to also validate that the ALLOWLIST file does not have any entries that actually have an owner, so that it accurately reflects the orphaned components.

**Comment by Chinwendu20** [comment]
Hello @mx-psi. Could I please work on this?

**Comment by mx-psi** [comment]
Assigned to you @Chinwendu20

**Comment by Chinwendu20** [comment]
Thanks for assigning this to me @mx-psi. So I plan on creating a function for this. Would it be okay if I put this in a separate file or  this should be in the check-codeowners.sh file?

**Comment by Chinwendu20** [comment]
Update, I am ready to push a PR just want to confirm the above, first.

**Comment by mx-psi** [comment]
@Chinwendu20 Either way works for me, just open the PR with whatever you have and we will resolve this on the PR :)

**Comment by Chinwendu20** [comment]
Thanks @mx-psi. I have pushed it. I am unsure if this requires a changelog.

**Comment by mx-psi** [comment]
No need for a changelog entry for this.
