### ISSUE TITLE
[exporter/kafka] Logs with custom schema

### ISSUE THREAD

**Issue by nanorobocop** [open-telemetry/opentelemetry-collector-contrib#12621]
**Is your feature request related to a problem? Please describe.**
We want to send logs to Kafka using our custom schema.
[Kafka exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter) sends logs in defined [LogsData](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L44) format.
In our case we already have predefined schema for logs in our storage, so we want to send logs using our own schema.
Currently Kafka exporter does not allows to modify schema.

**Describe the solution you'd like**
I'm thinking about several different approaches how to implement custom schema for kafka exporter:
* Send only Attributes. 
  * Attributes are dynamic map[string]Any fields, so would be easy to use.
* Mapping Fields.
  * This is similar to Elasticsearch [Fields](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/eacfde3fcbd46ba60a6db0e9a41977390c4883bd/exporter/elasticsearchexporter/config.go#L151-L152). Those Fields will be added as top level fields of original record.

First approach is more generic I think. 
It requires only attributes modification in standard opentelemetry-collector pipeline.

I'd like to hear what community thinks about it or if any other ideas.

**Describe alternatives you've considered**

**Additional context**

**Comment by nanorobocop** [comment]
This is probably depends on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12623
Custom schema should be applied to individual records, not set of records.

**Comment by MovieStoreGuy** [comment]
I think this warrants a further discussion than just applying to the KafkaExporter since this could also apply to the Kinesis Exporter, FileExporter and I am sure more in future.

I need to think more about this because it also comes with a performance impact as well

**Comment by nanorobocop** [comment]
Thanks for comment!

My implementation consists of 2 parts:
*  [exporter/kafka] Support sending individual log records #12657 
*  [exporter/kafka] Send log record attributes marshaler (for custom schema) #12658 

Custom schema implemented just by sending Attributes (which is dynamic map, could be constructed during Processing phase). So similar approach could be done in other exporters as well.
