### ISSUE TITLE
CircleCI windows-tests is missing gcc

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#1270]
**Describe the bug**

The Windows test suite recently added on PR #1228 can't install dependencies that use `cgo` since the `win/default` CircleCI image does not have the `gcc` compiler installed by default.

**Steps to reproduce**
Check the CI on `master`, which is failing because of a datadogexporter dependency:

```
go: found github.com/kardianos/osext in github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
# runtime/cgo
exec: "gcc": executable file not found in %PATH%
FAIL	github.com/DataDog/opentelemetry-collector-contrib/exporter/datadogexporter [build failed]
FAIL
```

**What did you expect to see?**
The test suite should be able to run

**What did you see instead?**
The test suite can't run

**What version did you use?**
Version: n/a

**What config did you use?**
Config: n/a

**Environment**
OS: n/a
Compiler(if manually compiled): n/a

**Additional context**

**Comment by tigrannajaryan** [comment]
We do not allow cgo in Collector. This has been discussed in the past and decided against.

**Comment by mx-psi** [comment]
Thanks for the reply. As I stated in #1271 we have a workaround for disabling the offending parts on Windows. I am closing this and we will open a new PR with the alternative fix.
