### ISSUE TITLE
[chore] Track unmaintained issues

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#12731]
With the creation of the [Unmaintained stability level](https://github.com/open-telemetry/opentelemetry-collector#unmaintained) and the ability to [automatically ping code owners when a component label is added](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12411), we need a way to keep track of issues that do not get any responses from the code owner.  

I think it would be good if we can automatically ping the code owner again in 3 weeks if the issue is still open, the issue is not assigned, and the code owner has not responded.  Then in another 3 weeks (6 weeks total since issue creation), the issue is marked Stale (or something equivalent).

Maintainers would then be able to look for Stale issues and start making judgements if the component should be marked unmaintained.  

The reason I feel this automation is necessary is because this repository gets so many issues, it feels unrealistic to go back through issues manually and check if code owners are responding.

**Comment by djaglowski** [comment]
I like this proposal in general, but I think we do not necessarily need to cross reference code owners directly. 

I think it might make sense to do the following:
- Apply the `Stale` label more aggressively to issues (but do not close issues based on staleness).
- Ping code owners whenever the `Stale` label is applied.

For the higher level goal of detecting unmaintained components, we can identify outliers based on a simple count of stale & untriaged issues for each component. If necessary, capturing these counts regularly and charting them over time would make it very easy to identify outlier components.

**Comment by TylerHelmuth** [comment]
> Apply the Stale label more aggressively to issues (but do not close issues based on staleness).

I thought about this too, but the tricky thing is that the label would come off whenever anyone comments on the issue.  I may be overthinking things, but we could find ourselves in a situation where an issue is opened and people interested in the issue periodically comment on the issue, but the code owner hasn't responded.  In this scenario the issue never gets marked `Stale` but it should have (Stale in this context meaning Code Owner isn't responding).  I think we could take advantage of setting [`remove-issue-stale-when-updated`](https://github.com/actions/stale#remove-issue-stale-when-updated) to false, but then there would be work for us to do in the scenarios where we do want the Stale label removed bc the Code Owner replied.

> Ping code owners whenever the Stale label is applied.

I played with this.  Whenever we want to ping code owners we need to know the component in question.  It would be nice to reuse the ping-codeowners workflow/script, but the Stale tag isn't enough because it doesn't identify the code owner.  I was able to use gh cli to get all the component labels added to an issue, then the next step would looping through them and reusing the ping-codeowners script.

**Comment by evan-bradley** [comment]
I'll look into this. I'd like to start small by implementing a flow like @djaglowski described:

1. After 60 days of inactivity, apply the `Stale` label to an issue. Exempt all issues with a `never stale` label.
2. Whenever the `Stale` label is applied, ping the code owners based on the labels applied to the issue.

This doesn't catch the case where there is activity on an issue, but there is no progress. If we repurpose the `needs triage` label such that it is only removed by code owners or when an issue is assigned, we could use the presence of the label as a way to detect this situation.
