### ISSUE TITLE
[receiver/prometheusreceiver] Metric datapoint reset when new attribute value introduced

### ISSUE THREAD

**Issue by balintzs** [open-telemetry/opentelemetry-collector-contrib#12746]
**Describe the bug**
The prometheus receiver incorrectly handles changes in the list of datapoints. It resets the start timestamp of existing datapoints when a new datapoint is introduced with a different attribute value.

**Steps to reproduce**
Make the following scrapes:
1. Scrape 1 at `timestamp1`:
    ```
    # TYPE http_requests_total counter
    http_requests_total{code="200"} 1
    http_requests_total{code="400"} 1
    ```
1. Scrape 2 at `timestamp2`:
    ```
    # TYPE http_requests_total counter
    http_requests_total{code="200"} 2
    http_requests_total{code="300"} 1
    http_requests_total{code="400"} 2
    ```

**What did you expect to see?**
Expect the following datapoints to be emitted at `timestamp2` for the metric `http_requests_total`:
1. Data point with attribute: `code="200"`
    - Value: 2
    - StartTimestamp: `timestamp1`
    - Timestamp: `timestamp2`
1. Data point with attribute: `code="300"`
    - Value: 1
    - StartTimestamp: `timestamp2`
    - Timestamp: `timestamp2`
1. Data point with attribute: `code="400"`
    - Value: 2
    - StartTimestamp: `timestamp1`
    - Timestamp: `timestamp2`

**What did you see instead?**
Datapoints that appear at an index that is greater or equal to the size of the previous list of datapoints have their start timestamp reset:
1. Data point with attribute: `code="200"`
    - Value: 2
    - StartTimestamp: `timestamp1`
    - Timestamp: `timestamp2`
1. Data point with attribute: `code="300"`
    - Value: 1
    - StartTimestamp: `timestamp2`
    - Timestamp: `timestamp2`
1. Data point with attribute: `code="400"`
    - Value: 2
    - StartTimestamp: `timestamp2` <-- **Reset**
    - Timestamp: `timestamp2`

**What version did you use?**
Version: `v0.55.0`

**Comment by balintzs** [comment]
I identified the root cause and managed to apply a fix locally. I'll submit a PR shortly.

**Comment by dashpole** [comment]
Thanks @balintzs!

**Comment by codeboten** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12765
