### ISSUE TITLE
processors : groupby sum metrics

### ISSUE THREAD

**Issue by raphaelauv** [open-telemetry/opentelemetry-collector-contrib#12759]
**Is your feature request related to a problem? Please describe.**

I have a level of granularity to high ( that mean to many metrics )

I would like to groupby and sum the values to reduce the number of metrics

my use case is that I have a prometheus endpoint giving the kafka consumer_lag metrics for each consumer_group on each topic and each partition

but I only need the consumer_lag of each consumer_group ( sum of each partitions of each topics )

in sql it would give

```sql
SELECT sum(value) AS NEW_METRIC_NAME
FROM consumer_lag
GROUP BY consumer_group
```

Is this something possible or maybe it's a bad idea to do that with otel-collector ? thanks

**Comment by codeboten** [comment]
@raphaelauv have you tried using https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor?

**Comment by raphaelauv** [comment]
thanks @codeboten 

I do not see how I can sum the metrics with the groupbyattrsprocessor

is it really possible with this processor ?

**Comment by rooque** [comment]
@raphaelauv I think you are looking for this

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor#aggregate-labels
