### ISSUE TITLE
Does OpenTelemetry Collector have a Prometheus Receiver for Remote Writes

### ISSUE THREAD

**Issue by perrinj3** [open-telemetry/opentelemetry-collector-contrib#12776]
I'm using the K6 Prometheus remote writer extension to generate metrics and want to know if there is an Otel Collector receiver that will work with this.
You have to start Prometheus with the flag --enable-feature=remote-writer-receiver to allow it to receive. 
In this configuration Prometheus doesn't need a  scraper config. It just receives.
K6 then has an extension which allows it to act as a Prometheus remote writer so it can write metrics to Prometheus

I've looked at the Prometheus receiver in the opentelemetry-collector-contrib but it's not clear if it can act in this mode.

Thanks

**Comment by TylerHelmuth** [comment]
Does this issue cover your needs: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10358

**Comment by perrinj3** [comment]
Hi Tyle
Yes it does cover our needs. Thanks for letting me know. I’ll track the issue. Hopefully someone will write the receiver  soon.
Regards,
John
