### ISSUE TITLE
New component: zabbix receiver

### ISSUE THREAD

**Issue by zhrebicek** [open-telemetry/opentelemetry-collector-contrib#12898]
## The purpose and use-cases of the new component
Receive [zabbix](https://www.zabbix.com/) metrics and whatnot by otlp collector.

It is aimed to be pull based receiver hooked on [zabix-api](https://www.zabbix.com/documentation/current/en/manual/api)

## Example configuration for the component
* endpoint
* username
* password
* collection_interval (in seconds)
* scrape_toggles
  * metrics (boolean)
  * etc.

## Telemetry data types supported
* [ ] metrics (to be supported first) 
* [ ] logs
* to-be-categorized
  * [ ] alert
  * [ ] event
  * [ ] problem

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?
No

## Sponsor (Optional)
TODO

**Comment by zhrebicek** [comment]
Created this issue to work on it, also added linked PR draft.
Should make it ready to review based on https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component hopefully this week.

**Comment by RalphSu** [comment]
push mode grpc receiver would also be great, specifically for migration usecases

**Comment by zhrebicek** [comment]
@RalphSu it would make sense, can you elaborate on how do you export data from zabbix with grpc? Doc link would be enough.

**Comment by RalphSu** [comment]
We have some legacy zabbix monitoring, which use https://www.zabbix.com/documentation/current/en/manual/config/items/itemtypes/trapper item type. 

I'm still figuring out the exact api that zabbix exposed for the pushed data.

**Comment by RalphSu** [comment]
https://www.zabbix.com/documentation/current/en/manual/appendix/items/trapper here looks the doc. Will try to test it upcoming days.

**Comment by oded-dd** [comment]
@RalphSu is Zabbix support push data? interesting, I was not familiar with it

**Comment by RalphSu** [comment]
Yes, there is "item type" call "zabbix trapper" which is to accept pushed data, check above document.

>>>>>>
Overview
Trapper items accept incoming data instead of querying for it.

It is useful for any data you might want to "push" into Zabbix.

To use a trapper item you must:

have a trapper item set up in Zabbix
send in the data into Zabbix

**Comment by zhrebicek** [comment]
So it is something server is receiving not something server is able to push out.

In other words receiver would need to "look like zabbix server" but it seems over specific to * something called sender https://www.zabbix.com/documentation/current/en/manual/concepts/sender
* not containing all data coming to zabbix from agents

Other option might be to implement https://www.zabbix.com/documentation/current/en/manual/appendix/protocols/server_proxy

**Comment by RalphSu** [comment]
not containing all data coming to zabbix from agents
---
True, build the trapper api, means custom metrics who sent to zabbix server can be accepted. but not include zabbix agent built ones.

https://www.zabbix.com/documentation/current/en/manual/appendix/protocols/server_proxy and https://www.zabbix.com/documentation/current/en/manual/appendix/protocols/real_time_export seems be an option for proxy the data out from zabbix.
