### ISSUE TITLE
[exporter/splunkhecexporter] traces and metrics pipeline use log content length config key.

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#12906]
**Describe the bug**
traces and metrics pipeline use log content length config key.

**Steps to reproduce**
The usage should not have a direct impact unless I missed something around the way we initialize the buffer for gzipping data.

**What did you expect to see?**
Content length set for metrics and traces properly.

**What did you see instead?**
The code uses the content length used by logs.

**What version did you use?**
latest

**What config did you use?**
N/A

**Environment**
N/A
**Additional context**

**Comment by TylerHelmuth** [comment]
closing based on linked PR
