### ISSUE TITLE
Adapt tql::metrics::flags to the new flags API

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#12924]

**Comment by TylerHelmuth** [comment]
Closing as PR is merged

**Comment by bogdandrutu** [comment]
@TylerHelmuth what I implemented is a bit of a hack :) You need to probably have "flags_no_record_value" func that works with `bool` and later we add other "flags_foo" instead of working on a int64

**Comment by TylerHelmuth** [comment]
Ah ok, I thought this issue was only tracking the switch to the new fields.  I'll probably hold off any removing the hack until `Flags` is completely removed and `FlagsStruct` is gets renamed to `Flags`

**Comment by TylerHelmuth** [comment]
Reviewing OTTL's use of flags today it looks like this issue can now be closed as we use `Flags()` during the GET (casted to `int64`) and `SetFlags` during the SET.  Helper functions are no longer used.
