### ISSUE TITLE
telemetrygen subcommand to generate OTLP log events

### ISSUE THREAD

**Issue by spencergilbert** [open-telemetry/opentelemetry-collector-contrib#12927]
**Is your feature request related to a problem? Please describe.**

Easily running integration tests for [Vector's](https://github.com/vectordotdev/vector) OTLP logs.

**Describe the solution you'd like**

The WIP `telemetrygen` currently has documented (WIP) support for traces and metrics, we should track in the implementation of logs as well.

**Describe alternatives you've considered**

Today I've just run the opentelemetry-collector to push logs with [otlpexporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter) and [otlphttpexporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter).

**Comment by fatsheep9146** [comment]
I'll help with this issue.

**Comment by mx-psi** [comment]
Thanks @fatsheep9146 :rocket: let me know if I can help

**Comment by fatsheep9146** [comment]
I think this issue is now blocked by #17898, since #17898 refract the code a lot. @mx-psi

**Comment by mx-psi** [comment]
We could split #17898 into a refactor only PR if @atoulme is okay with it and this is blocking you

**Comment by fatsheep9146** [comment]
> We could split part of #17898 into a refactor only PR if @atoulme is okay with it and this is blocking you

I agree with that. @mx-psi @atoulme

**Comment by atoulme** [comment]
Sure, sorry, this fell of my bucket list. I can cut a smaller PR to take care of refactoring.

**Comment by mx-psi** [comment]
@fatsheep9146 #17898 is merged, so this is now unblocked :)
