### ISSUE TITLE
[resourcedetectionprocessor] Add OS detector to gather metadata like OS hostname

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#1292]
**Is your feature request related to a problem? Please describe.**

Datadog telemetry data is usually identified with a given host identified by its OS hostname, cloud provider instance id or a user-set name. The "Resource Detection Processor" helps in this aim by allowing to add cloud provider or user set resoruces. This processor however does not gather info from the OS or network.

**Describe the solution you'd like**

The Resource Detection Processor would have an additional detector for OS/network related resource information like

- the [host attributes](https://github.com/james-bebbington/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/host.md) not yet covered outside of cloud envs (`host.hostname`, `host.name`, `host.type`...) and
- relevant [general network connection attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/span-general.md#general-network-connection-attributes).

**Describe alternatives you've considered**

For our specific use case we have some support to gather this data at the exporter level (which covers standalone installs); we have discussed porting this to a  new component but adding support on an already existing one would make more sense.

---

cc @james-bebbington. I would be willing to do some work on this if this sounds like a good idea to you.

**Comment by james-bebbington** [comment]
This seems like it would be a great addition to me

**Comment by mx-psi** [comment]
Awesome, I will do some initial work in the near future to address this then :)
