### ISSUE TITLE
[receivers/prometheusreceiver] ensure that TA scrapeconfigs are merged with statically defined ones

### ISSUE THREAD

**Issue by secustor** [open-telemetry/opentelemetry-collector-contrib#12938]
**Is your feature request related to a problem? Please describe.**
The imported code of Prometheus does not work with scrape configs which happen to conflicting each other.    
There there has to be a mechanism to prevent this. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
An alternative would be to simply not allow mixed operation of static configs and job retrieval from a target allocator. 

**Additional context**
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12586#discussion_r935888880

**Comment by dmitryax** [comment]
@secustor do you have a chance to work on this issue?

**Comment by secustor** [comment]
I habe some other tasks to do first, so not immediately.

**Comment by dmitryax** [comment]
Sure, just wanted to see if this can be assigned to you
