### ISSUE TITLE
New component: pkg/s3mapprovider

### ISSUE THREAD

**Issue by junhaoyu-aws** [open-telemetry/opentelemetry-collector-contrib#12939]
## The purpose and use-cases of the new component

An implementation of ConfigMapProvider for Amazon S3 (`s3mapprovider`) allows OTEL Collector the ability to load configuration for itself by fetching and reading config files stored in Amazon S3.

## Telemetry data types supported

Since this is just for config loading so it could be any. Keep the same as what [yaml/file/envproviders](https://github.com/open-telemetry/opentelemetry-collector/tree/main/confmap/provider) do.

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?

Yes, it is a vendor-specific component. Yes, I am contributing as a representative of AWS.

## Sponsor

@Aneurysm9

**Comment by mx-psi** [comment]
Is `pkg` the right place for this? I would argue we want this under `confmap/provider`

**Comment by junhaoyu-aws** [comment]
> Is `pkg` the right place for this? I would argue we want this under `confmap/provider`

Because it is a vendor-specific component, so both me and my teammates think it is the right place :)

**Comment by mx-psi** [comment]
> Because it is a vendor-specific component, so both me and my teammates think it is the right place :)

Being vendor-specific means it should be on opentelemetry-collector-contrib, but does not prescribe what folder it should be on. For components we generally copy the folder structure of opentelemetry-collector (e.g. exporters live under the `exporters` folder on both repositories), so I think we should also copy the repository structure in this case, and place this under `confmap/provider` on this repository.

**Comment by junhaoyu-aws** [comment]
> 
That makes sense to me, thank you!! I will do that when I submit my PR.
