### ISSUE TITLE
[processor/k8sattributes] k8s.deployment.name attribute can be set to a wrong value

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#12936]
`k8s.deployment.name` attribute value is taken from the pod name using regexp. This is not a robust approach. In some scenarios it can set the attribute to a wrong value. For example a Stateful Set called `sts-test` will create a pod called `sts-test-1`, telemetry from that pod will get the attribute `k8s.deployment.name: sts` which is incorrect, `k8s.deployment.name` should not be set for such pod.

There are two ways to solve the problem:

1. Make the [regexp](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/internal/kube/client.go#L64) more strict. This will lower chances for getting a wrong attribute, but it's impossible to completely eliminate the chances with the regexp approach

2. Use the k8s API to fetch an owner of the pod, check if it's replicaset controlled by a deployment, then set the correct value for `k8s.deplyment.name` attribute. This is a robust approach, but we need to make sure it doesn't introduce a significant computational overhead and load on k8s API.

**Comment by fatsheep9146** [comment]
I'd love to help with this, could I have a try? @dmitryax

**Comment by dmitryax** [comment]
@fatsheep9146 sure, it's yours

**Comment by fatsheep9146** [comment]
To extend the two ways of solving the problem.

- Make the [regexp](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/internal/kube/client.go#L64) more strict. 

I think we could first check whether the owner reference kind is ReplicaSet, if so, we then use regexp to extract the deployment name. But this may not cover the corner case that the user use replicaset directly not with deployment.

- Using k8s AP

I think we could build an informer of deployment and cached all deployment datas locally, when get deployment attributes, we could check all info of deployment from informer cache. This may increase more memory usage and require more rbac rules for collector.

which way do you think it better, in my opinion, if we only consider `k8s.deployment.name`, method 1 is better, despite the corner case.

**Comment by dmitryax** [comment]
@fatsheep9146 Option 1 looks good to me. And we are fetching the replicaset name from the owners already

**Comment by dmitryax** [comment]
We need to evaluate how big is the overhead for option 2. Based on that we can either do not add `k8s.deployment.uid` or go with the option 2.

@povilasv @fatsheep9146 WDYT?

**Comment by fatsheep9146** [comment]
> We need to evaluate how big is the overhead for option 2. Based on that we can either do not add `k8s.deployment.uid` or go with the option 2.
> 
> @povilasv @fatsheep9146 WDYT?

I do not encounter the use case that need deployment.uid, so @povilasv can help describe your use case =D

In terms of overhead, I think it definitely  contains the memory consumption of cached deployment data for informer locally and maybe cached deployment data for processor itself. The cpu overhead contains the logic of handler of deployment add, update, delete events, but I think this may be negligible. 

But the judgements above are all basic on logic, I think to ensure the judgements we should first implements option 2 and test it in some test environment to see the real overhead change?
@dmitryax

**Comment by dmitryax** [comment]
> But the judgements above are all basic on logic, I think to ensure the judgements we should first implements option 2 and test it in some test environment to see the real overhead change?

Yes we can start with option 1. Then can evaluate option 2 with addition of `k8s.deployment.uid` attribute.

**Comment by dmitryax** [comment]
I will keep this open until we move to Option 2 or decide to reject it

**Comment by dmitryax** [comment]
@fatsheep9146 will you work on trying the Option 2?

**Comment by fatsheep9146** [comment]
> @fatsheep9146 will you work on trying the Option 2?

No problem, I will start working on this.
