### ISSUE TITLE
[receiver/postgresql] Fix Collection To Use Resource Attributes

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#12960]
**Is your feature request related to a problem? Please describe.**
According to the [resource specification]( https://github.com/open-telemetry/opentelemetry-specification/blob/141a3ef0bf1eba0b6d260335bbe0ce7af9387cfc/specification/metrics/data-model.md#resource-attributes-1), the receiver metrics should not specify identifying information such as tables or databases on the metrics. The metric attributes `table` and `database` will be moved to resource attributes `postgresql.table` and `postgresql.database` respectively.

**Describe the solution you'd like**
Fix current metrics to use resource attributes.

**Additional context**
Initial issue found in #12338

**Comment by djaglowski** [comment]
@schmikei, please review the issue description. It appears incomplete.

**Comment by schmikei** [comment]
> @schmikei, please review the issue description. It appears incomplete.

Ahh sorry about that, thanks for the catch!

**Comment by djaglowski** [comment]
Since the component is beta stability, you will need to use feature gates to control this change. Here is an example:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12404/files

I believe it would be sufficient to have one pair of gates for the set of changes.

**Comment by schmikei** [comment]
Okay yeah sounds good; I'll look into implementing this in the PR. Just confirming, but is the window of time for the featuregate for this receiver going to be the same?

 I.e. 2 releases for `resource_attributes` and further changes to be hidden behind featuregates, 2 releases for it to become the default and 2 more releases until it becomes the only behavior?

**Comment by djaglowski** [comment]
@dmitryax, do you have an opinion on how to handle this situation?

We have a data point attribute that should be changed a resource attribute. 

I think this could be broken into two separate changes:
1. Add the resource attribute. It's not entirely clear to me if this needs to be considered a breaking change, but if so a feature gate could toggle whether `EmitForResource` is called with or without the attribute.
2. Remove the data point attribute. This is definitely a breaking change. In order for a feature gate to control this, I think we need mdatagen to support optional attributes, possibly just by excluding empty/nil attribute values. eg:
 ```go
func (m *metricPostgresqlBlocksRead) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, databaseAttributeValue string, tableAttributeValue string, sourceAttributeValue string) {
	if !m.settings.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntVal(val)

	// Always check all attribute values, or somehow tell mdatagen which attributes to check
	if databaseAttributeValue != "" {
		dp.Attributes().InsertString("database", databaseAttributeValue)
	}

	// dp.Attributes().InsertString("database", databaseAttributeValue)
	dp.Attributes().InsertString("table", tableAttributeValue)
	dp.Attributes().InsertString("source", sourceAttributeValue)
}
```

(Also, if these are two changes are controlled by separate feature flags, then I think we also need some logic to disallow the combination that would have neither the resource nor data point attribute.)

**Comment by dmitryax** [comment]
I wouldn't go to the route when we assume that zero attribute value means no attribute. It may work for strings, but not for int or bool attributes.

I would suggest just adding a file to the `internal/metadata` directory with a customized functionality that you need for feature gates instead of modifying `mdatagen`.
