### ISSUE TITLE
Introduce noop skeleton component directories as starting points for new component contributors

### ISSUE THREAD

**Issue by jspaleta** [open-telemetry/opentelemetry-collector-contrib#12965]
**Is your feature request related to a problem? Please describe.**
To lower the bar to component development for new contributors with an itch to scratch, it would be useful to have skeleton noop components that include commented boilerplate / factory calls. Contributors could copy and edit (following the hints in the comments) as a starting point for new component development.

**Describe the solution you'd like**
There could be a directory of skeleton components with just enough functional code to create a buildable, and callable component but not productively operational component. Such skeleton component directories, with minor tweaking, would be an appropriate starting point for the initial component PR in the iterative PR process documented in the contributor documentation.

Going further, there could be a helper tool that uses these skeleton components to provide a guided process to help new contributors fill in the minimum required customization to transition templated skeleton components into appropriately named new components.

**Additional context**
Here's an example of what I'm trying to describe for otel as currently implemented in the context of Sensu
https://github.com/sensu/sensu-plugin-tool

the sensu-plugin-tool helps new contributors spin up Sensu plugins including generating basic README documentation by asking a series of questions whose answers are used in string template substitution embedded in the template repositories the tool uses to generate new plugin projects.

Something like this should be possible for otel-collector using skeleton component directories.

**Comment by mx-psi** [comment]
Relates to open-telemetry/opentelemetry-collector/issues/5675

**Comment by jpkrohling** [comment]
I think it would make sense to have a tool like `ocb` for bootstrapping a component.

**Comment by jpkrohling** [comment]
cc @Chinwendu20, this is likely relevant for your Outreachy project.

**Comment by Chinwendu20** [comment]
Hello all. I created a project that would help out with this issue:

https://github.com/Chinwendu20/otel_components_generator

Do check it out and give me your suggestions

**Comment by atoulme** [comment]
@Chinwendu20 very cool, would you like to demo this at a SIG meeting?

**Comment by Chinwendu20** [comment]
Yes, thanks, the collector sig meeting by Wednesday 5 pm GMT+1. I plan on attending this week
