### ISSUE TITLE
AwsXray Exporter send request failed

### ISSUE THREAD

**Issue by NareshChinnusamy** [open-telemetry/opentelemetry-collector-contrib#12964]
**Im trying to export xray metrics using aws otel collector**

1. Configured VPC endpoint for x-ray service.
2. Running it as a sidecar container in ECS cluster.
3. Container starts running successfully.
4. After a few minutes, I was faced with this error.
`exporterhelper/queued_retry.go:149 Exporting failed. Try enabling retry_on_failure config option. { "kind": "exporter", "name": "awsxray", "error": "RequestError: send request failed\ncaused by: Post \"https://xray.us-east-1.amazonaws.com/TraceSegments\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" }
`
Can someone help me on this?

**Comment by TylerHelmuth** [comment]
tracking in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12961 instead
