### ISSUE TITLE
AwsXray Exporter send request failed

### ISSUE THREAD

**Issue by NareshChinnusamy** [open-telemetry/opentelemetry-collector-contrib#12961]
**Im trying to export xray metrics using aws otel collector**

1. Configured VPC endpoint for x-ray service.
2. Running it as a sidecar container in ECS cluster.
3. Container starts running successfully.
4. After a few seconds I was faced with this error.
`exporterhelper/queued_retry.go:149	Exporting failed. Try enabling retry_on_failure config option.	{
    "kind": "exporter",
    "name": "awsxray",
    "error": "RequestError: send request failed\ncaused by: Post \"https://xray.us-east-1.amazonaws.com/TraceSegments\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
}`
5. Can someone help me on this?

**Comment by NareshChinnusamy** [comment]
Hi @boostchicken, Can you help me with this?

**Comment by TylerHelmuth** [comment]
@NareshChinnusamy this feels like a networking issue in AWS and not an issue with the collector itself.  Maybe @Aneurysm9 can help out.

**Comment by NareshChinnusamy** [comment]
@TylerHelmuth I found out that the ports for the collector are not exposed and rectified it. Thanks

**Comment by likedustg** [comment]
Can you please give more details?
