### ISSUE TITLE
[metricstransformprocessor] convert resource attributes to metric labels

### ISSUE THREAD

**Issue by hossain-rayhan** [open-telemetry/opentelemetry-collector-contrib#1297]
**Is your feature request related to a problem? Please describe.**
When we gather metrics in the receiver, we set some resource attributes as well as metric labels based on the data definition. While sending these metrics to destination (AWS CloudWatch), some of the resource attributes should be converted to metric dimensions. However, it's not common that all exporters will read resource attributes to set them as metric dimensions. So, we need some kind of mechanism in the processor to convert the resource attributes to metric labels and I feel `metricstransform` processor is a good candidate for it.

**Describe the solution you'd like**
For our use case, one boolean settings in the processor is good enough. Like `convert_resource_attributes_to_labels=true` will convert all the resource attributes to metric labels and apply them to all metrics. However, for giving more custom settings like select specific metrics and specific resource attributes, we can consider extending the `add_label` operation. 

**Describe alternatives you've considered**
In our receiver, we can set all the resource attributes as metric labels also. Here is a PR [#1284] open but the reviewer raised concerns.

**Comment by tigrannajaryan** [comment]
Related to or a duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/1892

**Comment by hossain-rayhan** [comment]
This feature is implemented in the `exporterhelper` of core collector. Check the PR [2060](https://github.com/open-telemetry/opentelemetry-collector/pull/2060).
