### ISSUE TITLE
Load test set-up environment timed out

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#12984]
**Describe the bug**
During a build, the load test set-up environment step timed out after 15 minutes.

**Steps to reproduce**
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7663937443?check_suite_focus=true

**What did you expect to see?**
The test should pass. It passed the second time around.

**What did you see instead?**
The build was canceled after 15 minutes.

**Comment by djaglowski** [comment]
The 15m timeout was added on #12755 and extended to 30m yesterday on #12958. I'll close this since I believe it is now resolved.
