### ISSUE TITLE
[CI] Stability tests failure

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#12980]
**Describe the bug**
Stability test is flaky.

**Steps to reproduce**
See https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7696203557?check_suite_focus=true#step:8:7

**What did you expect to see?**
A passing test.

**What did you see instead?**
The test fails to run with:
```
GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ./bin/otelcontribcol_linux_amd64 \
	-ldflags "-X github.com/open-telemetry/opentelemetry-collector-contrib/internal/otelcontribcore/internal/version.Version=568aed3" -tags "" ./cmd/otelcontribcol
Stability tests are disabled until we have a stable performance environment.
To enable the tests replace this echo by make -C testbed run-stability-tests
```
Then the build fails when trying to upload tests:

```
tar: testbed/stabilitytests/results: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Error: Process completed with exit code 2.
```
**What version did you use?**
latest main

**Comment by djaglowski** [comment]
@open-telemetry/collector-contrib-approvers, stability tests were disabled nearly two years ago, yet we have continued to run this workflow on every PR. Any reservations with deleting the workflow at this point?

**Comment by dmitryax** [comment]
No objection from my side. I believe we discussed some plans to replace it with cpu/memory utilization dashboards based on benchmarks from every commit.

**Comment by TylerHelmuth** [comment]
If the workflow is doing nothing then I support disabling it.

**Comment by atoulme** [comment]
This happened here as well: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/2784117327

**Comment by djaglowski** [comment]
Sounds good. I'll make a PR to remove this workflow.

@dmitryax, I believe you may be referring to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9107, which is similar but was in regards to load tests, which at least are actually running.
