### ISSUE TITLE
Build go cache became slow and took hours

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#12983]
**Describe the bug**
During a build, go cache behaved slowly, taking hours to run.
The build kept going and had to be eventually cancelled.

**Steps to reproduce**
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7682176276?check_suite_focus=true

**What did you expect to see?**
A passing build, or at least, a reasonable timeout.

**What did you see instead?**
The build went on for 5h or more.

**What version did you use?**
latest main

**Comment by djaglowski** [comment]
This is due to https://github.com/Azure/azure-sdk-for-js/issues/22321. 

#10289 has some additional history.
