### ISSUE TITLE
[receiver/mongodb] Integration tests failure

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#12981]
**Describe the bug**
Flaky test.

**Steps to reproduce**
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7685164989?check_suite_focus=true

**What did you expect to see?**
Passing test

**What did you see instead?**
```
=== CONT  TestMongodbIntegration/Running_mongodb_4.0_as_LPU
    integration_test.go:285: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/integration_test.go:285
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/integration_test.go:200
        	Error:      	Received unexpected error:
        	            	Error response from daemon: No such image: 1931373c-eec0-40dd-a127-4d85cf8457c3:677e4494-07cf-4034-b0cd-051a854d949a: failed to create container
        	Test:       	TestMongodbIntegration/Running_mongodb_4.0_as_LPU
=== CONT  TestMongodbIntegration/Running_mongodb_3.0
```

**What version did you use?**
latest main

**Comment by djaglowski** [comment]
Looking into this, I noticed that we are running five tests in parallel. Each test runs a separate container, but they all expose the same port. Perhaps we are lucky this works as often as it does.

@JonathanWamsley, is this an issue you could take on?

**Comment by JonathanWamsley** [comment]
> 

Yeah, I can take care of this.

**Comment by djaglowski** [comment]
Again here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7787365963?check_suite_focus=true#step:5:746

**Comment by djaglowski** [comment]
Both failures observed so far appear to be specifically on the `Running_mongodb_4.0_as_LPU` test.

**Comment by JonathanWamsley** [comment]
Ok, I'll look to improve the script for `Running_mongodb_4.0_as_LPU`
