### ISSUE TITLE
[extension/jaegerremotesampling] Mark as alpha

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#13005]
This component is new and hasn't had exposure to production workloads yet. As such, it should be classified as alpha instead of beta.

**Comment by jpkrohling** [comment]
@frzifus, are you interested in this?

**Comment by frzifus** [comment]
Sure, thanks. I will have a more detailed look by the end of the week.

**Comment by frzifus** [comment]
Another thing, currently `extention/jaegerremotesampling` is not a [registered component](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.56.0/internal/components/components.go#L176). On what does the registration depend?

**Comment by jpkrohling** [comment]
This step is done at the same logical step as adding to a distribution. In the past, this would be required to have the component as part of the binary, while today I think it's mostly for convenience during tests.
