### ISSUE TITLE
Add audit abilities to receivers 

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#1302]
**Is your feature request related to a problem? Please describe.**
As part of our ability to debug, detect security issues or being replicate ingestion bugs, I would like a means to log the incoming request by providing information such as src ip, user agent, and request headers.

**Describe the solution you'd like**
I'd like to add some configurable means that allows for the request information to be logged, and the information that can be logged to be configurable.

**Describe alternatives you've considered**
Using something like ALB or nginx logs could also work however, it would limit the ability to debug issues that happen on receive. 

**Additional context**
Part of this is satisfy internal security requirements while also being able to replay problematic ingestion issues

**Comment by jpkrohling** [comment]
Looks like you want receivers to have tracing instrumentation. It should be doable with the obsreport facility we have in the core.

**Comment by atoulme** [comment]
Closing per comment from Juraci - Sean, please reopen if you see more work or specifics here.
