### ISSUE TITLE
[kinesisexporter] Support publishing of multiple data types in the kinesis exporter.

### ISSUE THREAD

**Issue by Excaleo** [open-telemetry/opentelemetry-collector-contrib#1305]
**Is your feature request related to a problem? Please describe.** 
Leverage the kinesisexporter to export otlp protobuff to kinesis streams. Currently, the format is fixed to the jaegar/zipkin format. In a more general sense, we would like support for format-agnostic, where specific data formats can be published by implementing marshaller classes.

**Describe the solution you'd like**
Use the marshallers pattern that the core collector library uses within the [kafka exporter.](https://github.com/open-telemetry/opentelemetry-collector/blob/master/exporter/kafkaexporter/marshaller.go) An otlp marshaller would be added to support the otlp protobuff format. A jaeger marshaller could also be added to support existing capabilities.

This requires swapping out the currently used producer library which only supports the jaeger format to a format-agnostic one. In our current fork we have chosen the [signalfx omnition producer](https://github.com/signalfx/omnition-kinesis-producer).

**Describe alternatives you've considered**
- Writing a new kinesis exporter - duplicate work as we could leverage existing code.

**Additional context**
- We have already implemented a functional version on the [atlassian fork](https://github.com/atlassian-forks/opentelemetry-collector-contrib/pull/9/files) of the repository. Some standardisation and feedback is needed to get it up to standard for a PR. 

- We've also added support for metrics marshalling and unit tests for files which lacked coverage. [PR link](https://github.com/atlassian-forks/opentelemetry-collector-contrib/pull/9/files)

**Comment by bogdandrutu** [comment]
@Excaleo that exporter needs a lot of love. It uses an old opencensus exporter as a base exporter, etc.

Happy to see that exporter refactored using OTLP.

**Comment by Excaleo** [comment]
@bogdandrutu awesome. @irisgve has drafted a PR, perhaps we could move the discussion there? Also I see @owais as the reviewer for the exporter, should we add him as the reviewer?

**Comment by bogdandrutu** [comment]
Make it non-draft automation should trigger everything (adding reviewers etc.)

**Comment by bogdandrutu** [comment]
Also by chance we maintain this. If interested to maintain this, after the PR gets merged consider to add your name as one of the owners to the list :)

**Comment by irisgve** [comment]
👋🏻 Hi! Just bringing up the discussion here from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1403 specifically the mentioned addtl functions in the exporter required to not break existing clients: 

> Use trace ID as the partition key. Means batches can't be published as they come and probably need to be re-batched by kinesis partitioning scheme as dictated by the trace ID.

For our case, we have a requirement that batches are published as they come in OTLP byte format for metrics and traces. The approach that the `kafkaexporter` in the core distribution works quite well for us and for adding support to export metrics too. I'm wondering if we could support both producers i.e. the opencensus-go-exporter for the existing jaeger support for traces and a byte interface producer using omnition for otlp. With this, we don't lose any existing functionality (I see that the opencensus exporter library has other things like trace-specific telemetry, hooks, etc.) and also can move forward with a design similar to `kafkaexporter`. Tho not sure if it's ideal that the kinesisexporter would push to partitions differently according to encoding format.

- Gzip the messages before publishing to kinesis. This reduces the overall size anywhere between 4-10x if my memory serves right
- Prepend the magic byte header to messages. The header should be the same as the one used by opencensus exporter when exporting in Jaeger. OTLP should use a different header. It is used by consumers to determine the encoding of the messages and whether they are gzipped or not.

As @Excaleo mentioned in the PR, we could also add this in the marshaling process for the OTLP producer interface and make gzipping configurable so users who opt not to use compression can do so.

**Comment by Saber-W** [comment]
Hi, I would like to pick up this one.
cc @alolita

**Comment by MovieStoreGuy** [comment]
Hi @Saber-W , my team and I have been working on this issue for some time now. 

I am more than happy to share what our intentions are and work with you if you like?

**Comment by MovieStoreGuy** [comment]
Hey @bogdandrutu , could I please get assigned to this? 

I want to get my team's work contributed back into the contrib if possible.

**Comment by mottibec** [comment]
Hey @MovieStoreGuy, we at [aspecto](http://aspecto.io) have a lot of interest in this. What are your plans for merging the changes from your fork into contrib?

**Comment by Saber-W** [comment]
Hi @MovieStoreGuy, I'm not working on this one, sorry for the misleading info. I tried to resolve this, then I see your couple of PRs related to this issue. So I thought it would be best to work on others.

**Comment by MovieStoreGuy** [comment]
Hey @mottibec,

The current plan is to migrate the current exporter to a function helper that in future can by dynamically set by the user. (Ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3655)

Once that is sorted, I would like to replace the current kinesis exporter that allows for protobuf types (not a byte array) to be passed in with a partitioner function (since I would like to keep the Jaeger partitioner stratergy of using the trace IDs.).

Then, tie all the work together by adding in user configuration and additional export types such as:
- OTLP
- Amazon's EMF

Any other vendor export types I will look at adding if there is a desire to use them with kinesis.

**Comment by MovieStoreGuy** [comment]
@Saber-W , Please feel free to join in. I am in the slack CNCF workspace if you wanted to chat further.
