### ISSUE TITLE
k8sattributesprocessor missing to consistently fetch pod attributes

### ISSUE THREAD

**Issue by rajatvig** [open-telemetry/opentelemetry-collector-contrib#13119]
**Describe the bug**

Seems like post 0.55.0 release of the Collector, the k8sattributesprocessor is behaving a little inconsistently when it comes to capturing resource metrics from pods. It was working fine in the 0.54.0 release. 

Looking at the commit log between the 2 releases - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8465 - is the only one I can see that could have changed the behaviour but I am unable to pin point at what exactly is wrong.

For the a deployment with 2 pods, one collector always looks up the metadata for one pod and the other pod goes to another collector but does not get anything. 

Restarting the collector pod or the deployment pod moves the problem to another collector pod and it just keeps bouncing that way. 

Turning on the debugging logs, I do see the requests land at the collector but it is not able to get it from the in memory list. RBAC is fine as some pods are getting the attributes and the configuration did not change between the releases.  

Tried adding pod_association rules but that did not help either.

**What version did you use?**
Version: 0.55.0

We upgraded to 0.57.2 and it has not helped though the misses are slightly fewer.

**What config did you use?**

```yaml
"k8sattributes":
  "auth_type": "serviceAccount"
  "passthrough": false
```

**Environment**
Using it on GKE as vanilla upstream docker image.

**Comment by dmitryax** [comment]
Hi @rajatvig. Thanks for reporting the issue.

It's possible that the issue is caused by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8465 . It changed the internal cache key structure.

@rajatvig if you can provide any more guidance on how to reproduce the issue, that would be awesome.

@sumo-drosiek please let us know if you have a chance to look into this. Otherwise I can take it.

**Comment by rajatvig** [comment]
@dmitryax What we have a very straightforward Otel Collector Setup with Collectors running as DaemonSets with passThrough on, which send to collectors running as a Gateway that add the rest. The RBAC is as documentation and there is very little load in some clusters. 

[Podinfo](https://github.com/stefanprodan/podinfo) is the sample application we have deployed and we see misses for one of the two pods almost all the time until we restart the collector or the pod.

The configuration as I noted is just

```
"k8sattributes":
  "auth_type": "serviceAccount"
  "passthrough": false
```

**Comment by dmitryax** [comment]
Thank you for providing the details, @rajatvig . I will take a look into this

**Comment by sumo-drosiek** [comment]
> @sumo-drosiek please let us know if you have a chance to look into this. Otherwise I can take it.

@dmitryax I was off until Today and will be off next week, so not much time to investigate :/
Thank you for looking into this

**Comment by hanikesn** [comment]
I can confirm this issue and we had to convert back to 0.54 as probably 2/3 off our traces didn't have k8s attributes attached.

**Comment by dmitryax** [comment]
@rajatvig @hanikesn can you please check if you still experience the issue in the latest collector versions?

**Comment by iateya** [comment]
@rajatvig 
Which collector version did you test the fix on?
I am still seeing the issue with version 0.64 and 0.66

**Comment by rajatvig** [comment]
We are on 0.64 now and the issue isn't there anymore.

**Comment by trexx** [comment]
Hi there, we are on 0.71 of the collectors, and I see this behaviour.
In our Kubernetes cluster we have collectors as sidecars to our workloads, forwarding on to cluster collectors.
I can see sometimes the k8s.pod.ip resource attribute is the only attribute that gets added, leading me to assume that the cluster collectors that's doing the enrichment is failing.

We can see this in Grafana by doing something like: `target{k8s_namespace_name="",k8s_pod_ip!=""}` and it results in a graph like this.
![image](https://user-images.githubusercontent.com/874158/222188769-1c615b08-34c5-440c-b7ab-b7cd60719623.png)

**Comment by cbertinato** [comment]
This issue appears to crop up even for the latest versions. Should this be closed?
