### ISSUE TITLE
kafkareceiver: kafka: client has run out of available brokers to talk to: EOF

### ISSUE THREAD

**Issue by liuqingyangsensetime** [open-telemetry/opentelemetry-collector-contrib#13118]
the kafkareceiver can not start when init the opentelemetry collector:
"
Error: cannot build pipelines: failed to create "kafka" receiver, in pipeline "logs": kafka: client has run out of available brokers to talk to: EOF
2022/08/09 09:27:43 collector server run finished with error: cannot build pipelines: failed to create "kafka" receiver, in pipeline "logs": kafka: client has run out of available brokers to talk to: EOF
"

**Comment by HarryEMartland** [comment]
I am having the same error. I assume it is something to do with our Kafka brokers as if I use the bitnami kafka example I can connect.

It would be great if the logs gave a bit more info or if anyone could share how they fixed this? I imagine it is just config I need to set.

Thanks
