### ISSUE TITLE
Allow using operators in otlp logs receiver

### ISSUE THREAD

**Issue by kushal-ti** [open-telemetry/opentelemetry-collector-contrib#13165]
**Is your feature request related to a problem? Please describe.**
I'm using the OTLP receiver for collecting logs into the otel collector. The body of my logs is JSON but is always parsed as a string by the receiver. I maybe able to use [json_parser operator](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/json_parser.md) for this purpose, but the otlp receiver doesn't support operators

**Describe the solution you'd like**
Allowing support for operators in otlp receiver

**Describe alternatives you've considered**
Using a filelog receiver instead of otlp receiver, however, this can be a headache in containerized environments like k8s and brings other problems like log rotations and log management with it

**Comment by djaglowski** [comment]
@kushal-ti, the [logstransformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/logstransformprocessor) allows you to use `json_parser` and the other operators that are available in `filelogreceiver`.

In the longer term the capability will reimplemented as a function on the `transformprocessor`.

**Comment by djaglowski** [comment]
Closing this as I do not believe there is any intention to support operators in the otlp receiver.
