### ISSUE TITLE
[processor/filter] Add metrics for dropped telemetry

### ISSUE THREAD

**Issue by ajsaclayan** [open-telemetry/opentelemetry-collector-contrib#13169]
**Is your feature request related to a problem? Please describe.**
We have a dashboard that shows the success rate of data flowing through a collector pipeline. We use four metrics to determine success rate:
1. Receiver accepted data point
2. Receiver refused data point
3. Processor dropped data point
4. Exporter sent data point

We have a filter processor configured for telemetry we don't care about. When telemetry gets dropped from a filter processor, we have no metrics to identify that they were dropped. Since they were dropped, our success rate calculation is lower than expected.

**Describe the solution you'd like**
As a developer, it would be nice to know how many traces/spans/logs are getting dropped by a filter processor.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dmitryax** [comment]
We are moving towards using OpenTelemetry SDK for reporting Collector metrics. I'm not sure if we want to add more metrics reported by OpenCensus it this point. Maybe we can wait for adoption of OTel SDK before tackling this issue, but It's not clear how long it'll take.

**Comment by ajsaclayan** [comment]
Bumping this can be this reconsidered?

**Comment by danelson** [comment]
@dmitryax In lieu of this I am curious if you any ideas how we can accurately determine success rate. We calculate this by doing 

```math
\frac{otelcol\_exporter\_sent_{signal}}{otelcol\_receiver\_accepted_{signal}+otelcol\_receiver\_refused_{signal}}
```
after we add the filter processor we need the following but it does not seem possible
```math
\frac{otelcol\_exporter\_sent_{signal}}{otelcol\_receiver\_accepted_{signal}+otelcol\_receiver\_refused_{signal}-otelcol\_processor\_filtered_{signal}}
```

**Comment by TylerHelmuth** [comment]
I think adding some metrics for the processor when it drops a span is a good idea.  We (Honeycomb) include similar metrics for Refinery and they are very useful.

**Comment by MacroPower** [comment]
I'm interested in working on this 🙂

**Comment by codeboten** [comment]
Thanks @MacroPower! Assigned
