### ISSUE TITLE
Implement AAD Integration for the Azure Monitor exporter

### ISSUE THREAD

**Issue by emileturcotte** [open-telemetry/opentelemetry-collector-contrib#13225]
**Is your feature request related to a problem? Please describe.**
According to the Components Developer guideline, components should use encryption and authentication by default.
When using Azure Application Insights, it is possible to disable local authentication, effectively enforcing Azure RBAC on all communications between the exporter and Azure Monitor.

However, as far as I can see, the Azure Monitor exporter does not support leveraging Azure RBAC to secure its communications. 

**Describe the solution you'd like**
The Azure Monitor exporter should have a configuration option to bind an identity to the exporter (via Service Principal, for instance, or any other way that Azure provides).

**Describe alternatives you've considered**
The only alternative right now is to not use the OpenTelemetry Collector and use the Azure Application Insights SDK directly, essentially rendering the collector useless. 

**Additional context**
Security Guidelines for Components Developers : 
![image](https://user-images.githubusercontent.com/64606429/184166735-ec2354d9-8e9d-421d-8dce-82d9a52d49fa.png)

**Comment by emileturcotte** [comment]
Any update on this ?
Pinging code owners: @pcwiese

**Comment by mkarbo** [comment]
We're also interested in this, in particular making it work with workload identity in AKS
