### ISSUE TITLE
[receiver/kafka] Add support for logs with raw data

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#13252]
**Is your feature request related to a problem? Please describe.**
Currently, we allow to ingest log data in the kafka receiver if it is encoded in OTLP format.
However, we see folks sending logs as data directly to Kafka, with no encoding.

**Describe the solution you'd like**
The Kafka receiver should support receiving entries and interpreting them as raw data to be encoded as log bodies.

**Describe alternatives you've considered**
N/A

**Additional context**
This would be useful to share the decoders with other receivers.

**Comment by bogdandrutu** [comment]
How would we decode that?

**Comment by atoulme** [comment]
Something very simple:
```
type directLogsUnmarshaler struct {
	encoding string
}

func (p directLogsUnmarshaler) Unmarshal(buf []byte) (plog.Logs, error) {
	l := plog.NewLogs()
	l.ResourceLogs().AppendEmpty().ScopeLogs().AppendEmpty().LogRecords().AppendEmpty().Body().SetBytesVal(pcommon.NewImmutableByteSlice(buf))
	return l, nil
}

func (p directLogsUnmarshaler) Encoding() string {
	return p.encoding
}

func newDirectLogsUnmarshaler(encoding string) LogsUnmarshaler {
	return directLogsUnmarshaler{
		encoding: encoding,
	}
}
```

**Comment by bogdandrutu** [comment]
You may want to at least batch few of them.

**Comment by atoulme** [comment]
I'd love to but... what if there's just one event every 5 minutes?
Isn't batching what the batch processor does?

**Comment by bogdandrutu** [comment]
Batching at source (if available, so read as many messages as possible) is cheaper than batch processor in terms of allocs etc.

**Comment by atoulme** [comment]
The unmarshaler interface does not allow to batch when unmarshaling however.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0fbb1a3ca83403936ff1607e0fa541c8a600aa6f/receiver/kafkareceiver/kafka_receiver.go#L551

Some refactoring required there then. Is that OK? Is the unmarshaler a good place to keep state?

**Comment by atoulme** [comment]
@bogdandrutu the way the code is built doesn't allow batching, as there is an atomic ack for each kafka message. In case of error, the kafka message is tagged.
