### ISSUE TITLE
[exporter/splunk_hec] Add min and max data points to metric data points sent for histogram

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#13264]
**Is your feature request related to a problem? Please describe.**
The Splunk HEC exporter maps from the OTLP data model to the Splunk metric events system.

Currently, it doesn't map min and max, which are optional, on histogram.

**Describe the solution you'd like**
Consider adding min and max data points as additional points to send to HEC.

**Describe alternatives you've considered**

**Additional context**

**Comment by andrewbanchich** [comment]
Seems related to #16714

**Comment by atoulme** [comment]
@andrewbanchich I don't think there is a relation, this is specific to how we send metrics with Splunk HEC.
