### ISSUE TITLE
datadog exporter not recognized

### ISSUE THREAD

**Issue by dustyhorizon** [open-telemetry/opentelemetry-collector-contrib#1336]
**Describe the bug**
Attempting to configure datadog as an exporter but keeps getting an error complaining that it is an `unknown exporters type`

**Steps to reproduce**
Add datadog as an exporter and start otel collector using the docker image from docker hub

**What did you expect to see?**
The collector running with no issues

**What did you see instead?**
The collector fatally exiting with `application run finished with error: cannot load configuration: unknown exporters type "datadog" for datadog`

**What version did you use?**
Version: 0.13.1 but I had this issue since 0.12.0

**What config did you use?**
Config: 
```
exporters:
  datadog:
    api:
      key: xxx
```

**Environment**
OS: docker image otel/opentelemetry-collector-contrib:0.13.1

**Additional context**
NIL

**Comment by mx-psi** [comment]
Hi, thanks for reporting this. The Datadog exporter is not yet added to the binary so you can't enable it yet, we hope to do that soon; I will keep you posted about this.

**Comment by mx-psi** [comment]
Hi again, the exporter will be available in the next release or in the `dev` builds like `otel/opentelemetry-collector-contrib-dev:latest`

**Comment by darjanbogdan** [comment]
Hi, is there a way to enable Datadog exporter outside of collector's binary? Will try the `dev` build you mentioned, thx.

**Comment by mx-psi** [comment]
Hi @darjanbogdan!

> is there a way to enable Datadog exporter outside of collector's binary

I am not sure what you mean by this. Do you want to use the Datadog exporter without using the OpenTelemetry Collector? What is the use case?

**Comment by darjanbogdan** [comment]
Ah sorry I was a bit unclear. It sounds strange to me that each new exporter must be first added to binary in order for collector to support it. But that's probably due to limited understanding of Go language and eco system.

It is working with the latest build indeed, and thank you for that.

**Comment by stephenhong** [comment]
May I ask when the Datadog exporter will be released to the prod build?

**Comment by mx-psi** [comment]
> May I ask when the Datadog exporter will be released to the prod build?

@stephenhong, the Datadog exporter should be available in the upcoming 0.14 release, which should happen soon. Following the normal release schedule 0.14 should have been released yesterday but it has been delayed, but hopefully it will happen later this week. I will let you all know when it is finally released.

**Comment by andrewhsu** [comment]
from the triage mtg today, closing this issue
