### ISSUE TITLE
[pkg/stanza] support parsing CRI-O logs

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#13377]
**Is your feature request related to a problem? Please describe.**
container logs from k8s are in CRI-O log format, i.e. something like following
```
2017-09-12T22:32:21.212861448+00:00 stdout 2017-09-12 22:32:21.212 [INFO][88] table.go 710: Invalidating dataplane cache ipVersion=0x4 reason="refresh timer" table="nat"
```

it will be nice to support parsing such logs and set timestamp, body, etc fields accordingly out of the box

**Describe the solution you'd like**
an input or a parser.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by djaglowski** [comment]
Typically, when evaluating whether or not to support a technology specific feature like this, we need to first establish whether or not the problem can be solved by configuration. In this case, I believe it can (see [example](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b82684c196d9ecc53babdbd4f25d4424c93b3323/examples/kubernetes/otel-collector-config.yml#L22)).

Assuming configuration is sufficient, there are a few reasons why we will typically not add out-of-the-box support. 
1. "Out-of-the-box" presently requires compiled code that has to be written and maintained. The number of real world log formats makes it untenable to pursue this approach broadly, so the default is to focus on generic capabilities.
2. In the future, a "plugin" system should allow technology specific formats to be encoded into predefined/reusable configurations.
3. Compiled code cannot easily be changed by the user, but configuration can.

**Comment by newly12** [comment]
cool, thanks for providing the example, given configuration is sufficient I agree we don't need out of the box support. Feel free to close this issue. Thanks @djaglowski !
