### ISSUE TITLE
Approvers are receiving GitHub notifications for every PR

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#1339]
Even with the inclusion of the bot that auto assigns people as reviewers, everyone in the approvers group is receiving a notification to review all the issues. Example:

Notifications page:
![image](https://user-images.githubusercontent.com/13387/96689653-fad6f600-1382-11eb-8b02-a865581c2d4d.png)

PR page:
![image](https://user-images.githubusercontent.com/13387/96690134-99635700-1383-11eb-87f2-3c95b75e354c.png)

In order to not cause "alert fatigue" to approvers, the group should not be added as reviewer, but instead, a specific person chosen by the bot.

**Comment by tigrannajaryan** [comment]
+1 on the idea. @bogdandrutu what was the problem that required all approvers to be listed for all directories?

**Comment by jpkrohling** [comment]
I didn't know about this until right now, but GitHub does have a feature that automatically assigns people as reviewers and has the ability to *not* notify the whole group:

![image](https://user-images.githubusercontent.com/13387/97582563-33677700-19f6-11eb-9b94-230a5df7282f.png)

Doc about this feature: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team

**Comment by MikeGoldsmith** [comment]
I like the idea of auto-assigning a single approver per PR to help reduce the noise generated to the whole group. However, we have seen two cases where a vendor span exporter has had PRs merged without approval from a vendor representative.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/291
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1162

There is a specific rule setup in the [CODEOWNERS](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/.github/CODEOWNERS#L24) file for the honeycomb exporter, but as the process selects only one approver, we just didn't get notified.

@paulosman @lizthegrey

**Comment by jpkrohling** [comment]
In the meantime, the following query works for me to find out which reviews are waiting for me individually: 

```
is:open is:pr review-requested:jpkrohling archived:false -team-review-requested:open-telemetry/collector-contrib-approvers 
```

**Comment by jpkrohling** [comment]
Ping @tigrannajaryan, @bogdandrutu

**Comment by mx-psi** [comment]
@bogdandrutu Could we give a try to the Github feature that @jpkrohling commented about in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1339#issuecomment-718766716 ? 

The auto assign Github Action we use seems to have some issues (e.g. PR assignment is not balanced across approvers and it is sometimes a bit slow) and it could help fix this issue

**Comment by jpkrohling** [comment]
Folks, it's becoming really hard to keep the sanity while working with OpenTelemetry. Right now, I have 148 notifications in my queue for opentelemetry-collector and opentelemetry-collector-contrib, and it's been only one business day since I had my queue cleared. I doubt they are all relevant. In fact, I doubt even 20 of them are relevant to me.

![image](https://user-images.githubusercontent.com/13387/119464240-d3923e00-bd42-11eb-9ca9-383e94dd7bd1.png)

I'm really about to resign as approver, as triaging this is consuming too much of my time.

**Comment by mx-psi** [comment]
I echo the concerns above, it is very time-consuming to go through the notifications even for some one who is an approver only for the contrib repo.  It should be easy to at least try the "Code review assignment" feature so that we are able to manage this better.

**Comment by anuraaga** [comment]
I'd appreciate if we could try out the code review assignment technique too, if it works can close #3337 without doing anything as it would probably solve my current notification overload issue.

**Comment by jpkrohling** [comment]
Yesterday before leaving for the day, I had no notifications. This morning:

![image](https://user-images.githubusercontent.com/13387/119785925-f867ec00-becf-11eb-89ab-fbe0418d1274.png)

**Comment by tigrannajaryan** [comment]
@jpkrohling sorry, just saw your proposal above about auto-assigment. So, instead of assigning all approvers to each PR which will round-robin PRs?

**Comment by jpkrohling** [comment]
It can use round-robin or load balancing so that folks with an already big review queue won't keep getting new items to review.

https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team

**Comment by tigrannajaryan** [comment]
@jpkrohling does that also stop the notifications?

**Comment by bogdandrutu** [comment]
I did this in the collector (not contrib) for the moment to test it.

<img width="923" alt="Screen Shot 2021-06-03 at 7 34 25 AM" src="https://user-images.githubusercontent.com/1373887/120662765-4172ef80-c43e-11eb-8475-e5c111769ba5.png">

**Comment by jpkrohling** [comment]
> does that also stop the notifications?

My understanding is that the notifications are sent because the group is assigned to review the PR. If the assignee is now an individual, the notification should stop as well.

**Comment by bogdandrutu** [comment]
Change contrib as well, we need to make a decision about the auto-assignment script, which runs in parallel and may assign a different person as `Assignees`.

**Comment by jpkrohling** [comment]
I just looked at a recently opened PR (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3701) and noticed that it got assigned to the team, instead of to an individual. The interesting part is this:

![image](https://user-images.githubusercontent.com/13387/120767167-3b9f0c00-c51b-11eb-98b4-f8cbf2b3b965.png)

Clicking on "code owners" led me to this:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/73753b799f4295b7013777403e75fd8cffa346ac/.github/CODEOWNERS#L23

Apparently, we might need to remove the group from the codeowners.

**Comment by jpkrohling** [comment]
>Changed contrib as well, we need to make a decision about the auto-assignment script, which runs in parallel and may assign a different person as Assignees.

I see the assigned person as the one responsible for making sure the PR is moving (reviewed, up to date, merged). I wouldn't mind being assigned to issues in addition to get review assignments.

**Comment by jpkrohling** [comment]
The latest changes did have an effect, and I'm now getting manageable levels of notifications! Thank you!
