### ISSUE TITLE
Prometheus metric name normalization disabled: inconsistent metrics naming

### ISSUE THREAD

**Issue by goto1134** [open-telemetry/opentelemetry-collector-contrib#13420]
**Describe the bug**
Metric name normalization is disabled by default (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheus#full-normalization)

**Steps to reproduce**
I have a spring app with grpc that uses micrometer grpc meter binder.

When I use  opentelemetry javaagent v0.16.0 with prometheus exporter, I get a counter metric named `grpc_server_requests_received_total`.
When I use opentelemetry javaagent v0.16.0 with otlp exporter to opentelemetry collector and configure prometheus exporter on the collector, the metric name is exported without postfix `_total`: `grpc_server_requests_received`.

**What did you expect to see?**
I expected the same metric name as in the javaagent: `grpc_server_requests_received_total`.

**What did you see instead?**
Not normalized metric name `grpc_server_requests_received`.

**What version did you use?**
`v0.56.0`

The related javaagent issue is here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6479

**Comment by dashpole** [comment]
What happens if you enable the normalization feature-gate?  Is this just a request to graduate that to beta?

**Comment by Aneurysm9** [comment]
> Is this just a request to graduate that to beta?

That's how it reads to me.  I think I'm okay with doing that.  We haven't had reports of significant issues with the gate enabled and still nobody has come forth with an explanation for the original difference in behavior.

**Comment by dashpole** [comment]
Sounds good.  Lets flip to beta after we have https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16071.

**Comment by dashpole** [comment]
Now blocked on https://github.com/open-telemetry/opentelemetry-specification/pull/3066
