### ISSUE TITLE
[receiver/aerospikereceiver] Improve integration test metric coverage.

### ISSUE THREAD

**Issue by dwelch-spike** [open-telemetry/opentelemetry-collector-contrib#13429]
**Is your feature request related to a problem? Please describe.**
The Aerospike receiver's integration tests currently leave many metrics empty making the tests less effective.

**Describe the solution you'd like**
The integration tests should be improved so that predictable load is put on the Aerospike server and metric reporting can be verified. This will probably involve making various requests with the Aerospike go client to the Aerospike container in the test code.

**Describe alternatives you've considered**
I could spin up another container in the test that writes to the Aerospike container. I think writing with the go client directly in the test code is simpler though.

**Additional context**
First mentioned in a metrics PR here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13295#discussion_r944781590

I will start work on a PR for this shortly.

**Comment by antonblock** [comment]
I think this makes sense, or alternatively running `asbenchmark` to generate some load
