### ISSUE TITLE
Reduce memory usage of Prometheus Receiver caches

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#13451]
Forked from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12215#issuecomment-1205439627.  We currently calculate a string timeseries signature: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/otlp_metrics_adjuster.go#L103, which is quite long.  It would be more memory efficient to use the [storage.SeriesRef](https://github.com/prometheus/prometheus/blob/a1fcfe62dbe82c6292214f50ee91337566b0d61b/storage/interface.go#L43) we are passed during [Append](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2793d7dc2707c0d3ba55b74cda92bd3633ccebde/receiver/prometheusreceiver/internal/otlp_transaction.go#L77).

In fact, the entire [JobsMap](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2793d7dc2707c0d3ba55b74cda92bd3633ccebde/receiver/prometheusreceiver/internal/otlp_metrics_adjuster.go#L164) can likely be replaced with a map[storage.SeriesRef]timeseriesInfo.

**Comment by CatherineF-dev** [comment]
QQ: do we have some metrics to know the memory usage of receiver caches?

**Comment by dashpole** [comment]
I think https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9998#issuecomment-1178752819 is the best we have to go off of right now.  But we already reduced some of that in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12765.

**Comment by dashpole** [comment]
I think this is fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/ea70008ccfe4d88efe78eec949944a471c3d1949
