### ISSUE TITLE
[splunkhecexporter] Tests are occasionally exceeding the 30s limit

### ISSUE THREAD

**Issue by nebffa** [open-telemetry/opentelemetry-collector-contrib#1346]
**Describe the bug**

The `splunkhecexporter` test runs are floating close to, and are sometimes exceeding, the 30s limit, which fails the build - an example is here - https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/5366/workflows/e82caba0-41f2-46e6-944c-4b27ce0666e3/jobs/40493.

Either the limit needs to be upped or these tests need to be optimised. It may be best to just up the limit - I think the reason these tests take longer is they do some work involving an in-memory HTTP server in `exporter_test.go`

**Comment by andrewhsu** [comment]
from triage mtg, assigning to tigran for now

**Comment by tigrannajaryan** [comment]
@atoulme will you be able to look into this?

**Comment by atoulme** [comment]
We have had a few changes in the exporter recently, and have 2 open PRs against it. We still use a HTTP server for testing - and I just opened an other PR using HTTP.
For right now, can we update the limit? What do you think Tigran?
Once we have landed the next couple PRs, I could possibly look at moving tests involving a HTTP server to integration tests.

**Comment by atoulme** [comment]
This commit https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/6e84f5221c9119e40ff4d8719cdc154c11ccbdc9 changes timeouts to a smaller value. This should help.

**Comment by tigrannajaryan** [comment]
Closing this, assuming https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1514 fixed it. Should reopen if we see this again.
