### ISSUE TITLE
[exporter/loki] Flatten the entry's JSON

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#13531]
Right now, the Loki entry in the exporter looks like this:

```go
type lokiEntry struct {
	Name       string                 `json:"name,omitempty"`
	Body       json.RawMessage        `json:"body,omitempty"`
	TraceID    string                 `json:"traceid,omitempty"`
	SpanID     string                 `json:"spanid,omitempty"`
	Severity   string                 `json:"severity,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	Resources  map[string]interface{} `json:"resources,omitempty"`
}
```

If the body itself is a json object, we might end up with a json embedded into a json. @cyriltovena has suggested inlining the body if it's a json, so that we have only one level, making it easier to run queries against this data.

**Comment by jpkrohling** [comment]
@mar4uk, would you like to take this one?

**Comment by mar4uk** [comment]
@jpkrohling yes, please assign it to me

**Comment by mar4uk** [comment]
@jpkrohling shall we close this issue for now?
Currently, there is no clear vision of what format of log entry is the most convenient for logs exploring in Loki. Probably flattening the body will not make the user experience more convenient

**Comment by wiardvanrij** [comment]
@mar4uk & @jpkrohling - I was kinda hoping on a solution some how. We even recently brought this up with Grafana Support because it has been a 'pain point' in our GEL evaluation :) 

To me it seems "simple"? Check if the body is JSON and if so, make it inline instead of the nested? Otherwise keep default behaviour.

**Comment by jpkrohling** [comment]
@wiardvanrij, while the solution is simple, the implications might not be that simple. After some discussion with the Loki team, we decided not to implement this, in favor of a longer-term solution that is under discussion at the moment.

We are super eager to hear more from you though: why do you need this, and can't you use logfmt instead? What makes you want to use a flat JSON?

**Comment by wiardvanrij** [comment]
Thanks @jpkrohling . We've setup a session to explain this (via our Grafana contact). I hope you get the summary after that session as well :)

**Comment by jpkrohling** [comment]
Sounds good. I'm asking them as well, but make sure they include someone from our squad (likely @mar4uk). We are interested in hearing directly from you.
