### ISSUE TITLE
[SQL receivers] Establish common practice for default metric queries

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#13547]
**Context**
This is related to issue #13546. There are already a few receivers that are used to query SQL databases that convert the query results into metrics. This issue to try to define best practices around user-experience for default queries.

For any SQL database system that the collector get metrics from, it can be expected that there is a default list metrics that we'd want from the SQL db. 

Examples:
[MySQL default metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/mysqlreceiver/documentation.md)
[PostgreSQL default metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/postgresqlreceiver/documentation.md)

The purpose of this issue is to determine best practices for defining default metrics for a SQL database.

**Current practice**
- For the `mysql` receiver, two queries are defined in code and executed, and all of the default metrics are returned by those two queries.
- The process is more involved for the `postgresql` receiver for two main reasons: there are both more queries, as well as queries that are dependent on other queries. For example, as the receiver is created, a (static) query is made to get a list of databases. That list is then used later to perform other (static) queries. Other queries can be changed based on options given (e.g. `groupBy` boolean), but from my findings, these values are also set in code, and not changing based on query results or any other factor.

For both `mysql` and `postgresql`, the user can choose to disable specific metrics that are enabled by default.

**Describe the solution you'd like**
For this issue, and #13546, I would propose creating essentially "thin" receivers for specific db technologies that would in turn reference the `sqlquery` receiver to connect to the db and to run queries.  

I think the best practice would be to define the list of default queries within the db-specific receiver, programmatically, and then use the `sqlquery` receiver internally to connect to the db and run the given queries.

Each receiver would still have config options to disable specific default metrics.

Using the `mysql` receiver as an example, it would essentially just define the two metric queries and use the `sqlquery` receiver for everything else.

I believe this is the best user-experience as it would allow users to be able to setup receivers based on name recognition. The two thoughts below summarize my thought on why this solution is better than my top proposed alternative.

Clear path from goal to execution:
- I want to receive MySQL metrics, so I should use the `mysql` receiver.

Unclear path from goal to execution:
-  I want to receive MySQL metrics, so I should setup the `sqlquery` receiver with the `mysql` driver set in the config file. 

**Feasibility Questions/Concerns**

- How can a query be changed based on results of another query, if queries are predefined in a list? The `postgresql` receiver will query a specific set of tables for metrics as determined by the [results of another query](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/postgresqlreceiver/client.go#L512). We could use a flag, or group queries together when defining them.

**Describe alternatives you've considered**

1. Define default queries for each db technology within the `sqlquery` receiver. When a specific db driver is specified in the config, the default metrics would automatically be enabled. Within the config the user would then have the option to choose to disable specific metrics, just as they can today. There would be the same feasibility issue with this approach as the proposed solution.
2. Use entirely separate receivers for each SQL database technology. I don't think this is the best option, because as described in #13546, it's a lot of duplicated code, resulting in more complexity.

**Additional context**

- We can define queries either in some kind of yaml file, or statically in code.
- Another point to consider is that these receivers are all querying databases for metrics. Some platforms expose metrics by storing them in databases, but also expose metrics through REST APIs (e.g. Oracle DB). We need to make sure documentation and naming is clear to properly set user expectations. If we have to create separate receivers for sql db platform metrics and sql db query metrics it will get confusing very quickly.

**Comment by dmitryax** [comment]
For the context: We are planning to add another receiver for Oracle BD that where we need to fetch metrics from the database the same way as done in postgresqlreceiver and mysqlreceiver. But given that now we have a generic `sqlquery` receiver, we are considering reusing it in one of the following ways:

1. Reuse the existing `sqlquery` receiver and have a set of statically predefined queries to fetch "system" metrics for each driver. The "system" metrics can be optionally scraped with just an additional configuration parameter e.g. `scrape_system_metrics: bool`.

2. Turn reusable code from `sqlquery` receiver into a library and reuse it in other `sql...` receivers.

Regardless of the approach that we take, we need to make sure that `mdatagen` is also somehow utilized so we can get the its functionality. 

I personally like the first approach as it reduces number of receivers to maintain, but I maybe less convenient for the end user.

@djaglowski do you have any thoughts/suggestions on this topic?

**Comment by djaglowski** [comment]
I think the general intention here makes a lot of sense. In the long term, we can save a lot of effort and prevent inconsistencies by absorbing functionality into a shared library based on the `sqlquery` receiver. 

> But given that now we have a generic sqlquery receiver, we are considering reusing it in one of the following ways:
>
> 1. Reuse the existing sqlquery receiver and have a set of statically predefined queries to fetch "system" metrics for each driver. The "system" metrics can be optionally scraped with just an additional configuration parameter e.g. scrape_system_metrics: bool.
> 
> 2. Turn reusable code from sqlquery receiver into a library and reuse it in other sql... receivers.

My preference would be that we pursue the second option, for a few reasons:
1. A generic sql query receiver is valuable in and of itself. Baking in technology specific usages will complicate that receiver and leaves the door open for technology specific "hacks" (eg `if system == "mysql" { /* special handling of result */ }`).
2. Thin technology specific receivers are valuable not only for usability, but for security. For some users, the ability to inject arbitrary queries via configuration will be unacceptable. Thin (ie. "hardcoded") receivers can be evaluated concretely.
3. I am not convinced that we _should_ or even _can_ write a shared library that will allow sufficient flexibility in the processing of query results. The example where postgresql performs a "list databases" query and then uses the result to perform followup queries is a good example of this, but we should anticipate the need for even more complex cases. In my opinion, attempting to generically handle all query result processing and followup querying will be overly complex and still insufficient. 
	- 2nd/3rd/4th level followup queries, potentially with different error handling at each level
	- Derived metrics based on multiple columns/rows
	- Conditional behavior based on queried values
	- Nonlinear handling of query results (eg. each record contains a resource attribute, scope attribute, metric attribute, and two metric value)
	- Performance optimizations

What I see as the overall best approach here looks like this:
1. Extract a shared library from the sqlquery receiver. The receiver itself will do very little besides call the library and report the result.
2. Attempt to rebase the mysql receiver on this shared library. Ensure the user-visible inputs and outputs of the receiver can remain the same. If not, the shared library may be insufficient for our needs. This can drive improvements to the library, or highlight use cases that a shared library should not attempt to handle. Ideally, the receiver code ends up quite simple though, just making two calls to the shared library and returning the results.
3. Do the same for postgresql. This will force the question of how the shared library should support the "list databases" query, where the results are not intended to be directly transformed into metrics.
5. Implement the oracle receiver. 
6. _If_, all of the technology specific receivers above prove to be easily implemented on the shared library, _then_ I think we can look at making the specific receivers "codeless".

**Comment by dmitryax** [comment]
Thanks for sharing your thoughts. It all makes sense to me. And pretty good course of action. Another thing that we should strive for is to make sure that `mdatagen` library is always utilized to provide ability to at least disable/enable particular metrics. That can become pretty complicated if we go with the first approach. So I'm good with keeping the receivers separate and gradually trying to utilize `sqlquery` as a library.

**Comment by djaglowski** [comment]
> Another thing that we should strive for is to make sure that mdatagen library is always utilized to provide ability to at least disable/enable particular metrics. 

100% agree
