### ISSUE TITLE
prometheusreceiver transaction enable label cache

### ISSUE THREAD

**Issue by Duncan-dsf** [open-telemetry/opentelemetry-collector-contrib#13548]
**Is your feature request related to a problem? Please describe.**
The [prometheusreceiver transaction](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/otlp_transaction.go#L76) always returns 0 to disable label caching. 
This causes the same series to be parsed multiple times by promParser, making the memory occupied by `promParser.Metrics()` higher than the actual size of the scrape response. 

**Describe the solution you'd like**
I would like to be able to config the switch of transaction cache. Even just returning a non-zero ref to enable the label cache of prometheus.

**Describe alternatives you've considered**
1. Just returning a fixed non-zero ref, for example always return 1. And provide a configuration to allow it to be turned on.
2. Transaction implements the caching capability of prometheus' appenders.

**Additional context**
Transaction code:
![image](https://user-images.githubusercontent.com/29371215/186346616-3a1767e6-e404-4ecd-9c2a-d19df3e0e42a.png)
The heap pprof of OTel collector. The memory occupied by `promParser.Metrics()` is over 90Mib. The actual size of the scrape response is only 38Mib.
![image](https://user-images.githubusercontent.com/29371215/186351623-466668a8-48d0-4651-a940-213ef0eda97e.png)

**Comment by dashpole** [comment]
This seems really great to do, but I'd like to understand more.  What does the return value actually do here, and why does 0 result in no caching?

**Comment by dashpole** [comment]
@gouthamve do you know anything about label caching?
