### ISSUE TITLE
prometheus exporter : has invalid keys: enable_open_metrics

### ISSUE THREAD

**Issue by marouanelkhebir** [open-telemetry/opentelemetry-collector-contrib#13551]
I m trying to use enable_open_metrics for prometheus
`
exporters:
  prometheus:
    endpoint: "1.2.3.4:1234"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true`

 and un got an error.

`Error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "prometheus": 1 error(s) decoding:

* '' has invalid keys: enable_open_metrics
2022/08/23 13:26:47 collector server run finished with error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "prometheus": 1 error(s) decoding:`

opentelemety-collecor-contib version : **0.58.0**

Thanks for your help

**Comment by florian-serraille** [comment]
The 'enable_open_metrics' property is only available since version 0.59.0, even though it appeared in the 'main' branch.
