### ISSUE TITLE
[pkg/telemetryquerylanguage] Add `drop` action support for metrics

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#13579]

**Comment by TylerHelmuth** [comment]
Metrics context already has access to the datapoint's metric and scope metrics slice so it is ready to be used with a general drop function

**Comment by dmitryax** [comment]
@TylerHelmuth should this be closed given that `drop` action is not supported yet?

**Comment by TylerHelmuth** [comment]
I slightly modified these subtasks to reflect the context's abilities to handle a function like `drop`.  The new drop function will be generic to any context and can get registered to the transform processor's common function registry once each context has access to the telemetry slice.

**Comment by TylerHelmuth** [comment]
Based on a potential need to access the scoped metrics slice I am going to reopen this for now
