### ISSUE TITLE
[exporter/prometheusremotewrite] Support dynamic AMP workspaces in endpoint

### ISSUE THREAD

**Issue by neyp** [open-telemetry/opentelemetry-collector-contrib#13574]
**Is your feature request related to a problem? Please describe.**
The exporter doesn't provide a way to assign a different Amazon Managed Service for Prometheus workspace according to incoming metrics. 

**Describe the solution you'd like**
Route to different workspaces.

**Comment by jeromeinsf** [comment]
Hi @neyp 

Thanks for logging this feature request. Could you detail what would be the routing logic based on? How do you see it configured, a mapping metric label-endpoints?
