### ISSUE TITLE
exporter/tanzuobservabilityexporter remove deprecated calls, see nolint:staticcheck

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#13583]

**Comment by oppegard** [comment]
I believe this will be addressed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13419.

**Comment by oppegard** [comment]
@evan-bradley @bogdandrutu: this should be fixed in #13419. Can someone with permissions close this?
