### ISSUE TITLE
[receiver/prometheusreceiver] identify telemetry scraped by the prometheus receiver

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-collector-contrib#13615]
**Is your feature request related to a problem? Please describe.**
I would like to be able to tell which metrics are scraped by the prometheus receiver.

**Describe the solution you'd like**
Most receivers set the scope name to the receiver name (e.g. `otelcol/postgresqlreceiver`). The most straightforward solution would be to set the scope name to `otelcol/prometheusreceiver`. 

**Describe alternatives you've considered**
If scope.name is reserved for other use with the prometheus receiver, we could use a different scope attribute, or even a resource attribute.

**Additional context**
* Possibly related to: https://github.com/open-telemetry/opentelemetry-specification/pull/2703
* Loosely related to: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4973

**Comment by atoulme** [comment]
See #20902 as duplicate.

**Comment by paologallinaharbur** [comment]
I think we can close this since this https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20903 has been merged
