### ISSUE TITLE
[receiver/prometheus] partial valid histogram metrics cause entire metrics being dropped

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#13623]
**Is your feature request related to a problem? Please describe.**
given histogram metrics like following, where some metrics do not contain `le` labels, the validation fails and entire metrics from this scrapping are dropped
```
# HELP ep_request_filter_duration_ns_seconds  
# TYPE ep_request_filter_duration_ns_seconds histogram
ep_request_filter_duration_ns_seconds{quantile="0.5",} 0.0
ep_request_filter_duration_ns_seconds{quantile="0.95",} 0.0
ep_request_filter_duration_ns_seconds{quantile="0.99",} 0.0
ep_request_filter_duration_ns_seconds_bucket{le="0.001",} 0.0
ep_request_filter_duration_ns_seconds_bucket{le="0.01",} 0.0
ep_request_filter_duration_ns_seconds_bucket{le="0.1",} 0.0
ep_request_filter_duration_ns_seconds_bucket{le="30.0",} 911.0
ep_request_filter_duration_ns_seconds_bucket{le="+Inf",} 911.0
ep_request_filter_duration_ns_seconds_count 911.0
ep_request_filter_duration_ns_seconds_sum 29.49554678

```

**Describe the solution you'd like**
if possible keeps all metrics

**Describe alternatives you've considered**
Allows best-effort validation for histogram metrics, if possible, only drops the ones without `le` bucket.

**Additional context**

**Comment by Aneurysm9** [comment]
I don't believe this is valid.  This is a combination of a summary (no suffix, `quantile` label) and a histogram (`_bucket` suffix, `le` label) overlapping on the `_count` and `_sum` metrics.  This is not permitted by the [OpenMetrics spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/draft-richih-opsawg-openmetrics-01.txt#L322-L323).

**Comment by dashpole** [comment]
I think keeping the histogram portion of the metric seems reasonable, if we can do it.

**Comment by newly12** [comment]
> I think keeping the histogram portion of the metric seems reasonable, if we can do it.

I am trying to figure out the solution of this, it looks a hard one to me and I might use some suggestions here. 

Looking at prometheus `Appender` interface, `Append()` appends one series

```go
type Appender interface {
	// Append adds a sample pair for the given series.
	// An optional series reference can be provided to accelerate calls.
	// A series reference number is returned which can be used to add further
	// samples to the given series in the same or later transactions.
	// Returned reference numbers are ephemeral and may be rejected in calls
	// to Append() at any point. Adding the sample via Append() returns a new
	// reference number.
	// If the reference is 0 it must not be used for caching.
	Append(ref SeriesRef, l labels.Labels, t int64, v float64) (SeriesRef, error)
```

It is not possible to tell the whole histogram metrics are valid or not, unless we swallow the error(missing bucket label for a histogram series) first and verify after all metrics are ingested, if we do so 

1 ) prometheus will consider the ingestion succeeded and `up` metric is 1 then.
2) verification can only be done before we build OTEL metrics, if we get invalid histogram metrics like all series are missing bucket label, we need to determine if we want to emit all other metrics, or fail the scrapping. However both would make some internal metrics inaccurate, i.e. `scrape_samples_scraped`, `scrape_series_added` do not match total emitted metrics, and if we fail the scrapping, `up` should be 0 but it's now 1, unless we change it before we send it.

**Comment by dashpole** [comment]
I think i'm missing something.  Why does the approach of returning error on invalid appends not give us what we want?

We know the type information (e.g. that the metric is a histogram).  If we get a metric that doesn't have one of the required suffixes (_count, _total, _bucket), we drop only that point.  What goes wrong in that case?

**Comment by newly12** [comment]
the we are returning the error to prometheus(from `Append()` method) and prometheus actually marks the scrape as error, it's like we get all metrics or nothing.

given such metrics 
```
# HELP foo
# TYPE foo gauge
foo 1
# HELP ep_request_filter_duration_ns_seconds
# TYPE ep_request_filter_duration_ns_seconds histogram
ep_request_filter_duration_ns_seconds{quantile="0.5",} 0.0
ep_request_filter_duration_ns_seconds{quantile="0.95",} 0.0
ep_request_filter_duration_ns_seconds{quantile="0.99",} 0.0
ep_request_filter_duration_ns_seconds_bucket{le="0.001",} 0.0
ep_request_filter_duration_ns_seconds_bucket{le="0.01",} 0.0
ep_request_filter_duration_ns_seconds_bucket{le="0.1",} 0.0
ep_request_filter_duration_ns_seconds_bucket{le="30.0",} 911.0
ep_request_filter_duration_ns_seconds_bucket{le="+Inf",} 911.0
ep_request_filter_duration_ns_seconds_count 911.0
ep_request_filter_duration_ns_seconds_sum 29.49554678
```

from the log there are only internal metrics, and up is 0
```
2022-10-13T17:04:57.907+0800    debug   scrape/scrape.go:1559   Unexpected error        {"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_pool": "prometheus", "target": "http://localhost:8000/metrics.txt", "series": "ep_request_filter_duration_ns_seconds{quantile=\"0.5\",}", "error": "'le' label on histogram metric id missing or empty"}
2022-10-13T17:04:57.908+0800    debug   scrape/scrape.go:1335   Append failed   {"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_pool": "prometheus", "target": "http://localhost:8000/metrics.txt", "error": "'le' label on histogram metric id missing or empty"}
2022-10-13T17:04:57.908+0800    warn    internal/transaction.go:111     Failed to scrape Prometheus endpoint    {"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_timestamp": 1665651897884, "target_labels": "{__name__=\"up\", instance=\"localhost:8000\", job=\"prometheus\"}"}
2022-10-13T17:04:58.019+0800    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 5}
2022-10-13T17:04:58.019+0800    debug   ingressprometheusremotewrite/exporter.go:105    convert metrics to time series  {"kind": "exporter", "data_type": "metrics", "name": "ingressprometheusremotewrite/victoria"}
2022-10-13T17:04:58.019+0800    info    ResourceMetrics #0
Resource SchemaURL: 
Resource attributes:
     -> http.scheme: Str(http)
     -> net.host.port: Str(8000)
     -> service.instance.id: Str(localhost:8000)
     -> service.name: Str(prometheus)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope  
Metric #0
Descriptor:
     -> Name: scrape_duration_seconds
     -> Description: Duration of the scrape
     -> Unit: seconds
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-10-13 09:04:57.884 +0000 UTC
Value: 0.024099
Metric #1
Descriptor:
     -> Name: scrape_samples_scraped
     -> Description: The number of samples the target exposed
     -> Unit: 
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-10-13 09:04:57.884 +0000 UTC
Value: 2.000000
Metric #2
Descriptor:
     -> Name: scrape_samples_post_metric_relabeling
     -> Description: The number of samples remaining after metric relabeling was applied
     -> Unit: 
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-10-13 09:04:57.884 +0000 UTC
Value: 1.000000
Metric #3
Descriptor:
     -> Name: scrape_series_added
     -> Description: The approximate number of new series in this scrape
     -> Unit: 
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-10-13 09:04:57.884 +0000 UTC
Value: 1.000000
Metric #4
Descriptor:
     -> Name: up
     -> Description: The scraping was successful
     -> Unit: 
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-10-13 09:04:57.884 +0000 UTC
Value: 0.000000
        {"kind": "exporter", "data_type": "metrics", "name": "logging"}

```

**Comment by dashpole** [comment]
Ah, I see.  Prometheus itself considers a failure to append to be fatal for the entire scrape.  I assume that is intentional from prometheus' perspective... Would a workaround be to use metric_relabel_configs to drop those metrics yourself?

**Comment by newly12** [comment]
Thanks, I think the workaround metric_relabel_configs would work, but the challenge is that we can not predict what histogram metrics could having such issue..

**Comment by dashpole** [comment]
I think this is a broader question about error handling.  Prometheus has taken the approach that a scape with 1 invalid metric should cause the entire scrape to fail.  We are essentially doing the same by returning the error.  The all-or-nothing approach is good in that it makes reasoning about metric presence easier: Either the up metric is 1, and I have all of the metrics on the endpoint, or the metric is 0, and I have none of them.

> we can not predict what histogram metrics could having such issue..

Is this a common pattern?  Its the first i've ever seen of it.

**Comment by Aneurysm9** [comment]
> Is this a common pattern? Its the first i've ever seen of it.

I've seen this a couple times.  I believe that Micrometer produces both a Histogram and a Summary for timer instruments.  I also yesterday had an internal customer who was manually producing a Summary and Counter with the same name as an optimization.  They were able to change the name of the Counter, but unless you've seen this before it's a pretty non-obvious problem, particularly with the detailed error message only appearing at the Debug level.

**Comment by newly12** [comment]
> I think this is a broader question about error handling. Prometheus has taken the approach that a scape with 1 invalid metric should cause the entire scrape to fail. We are essentially doing the same by returning the error. The all-or-nothing approach is good in that it makes reasoning about metric presence easier: Either the up metric is 1, and I have all of the metrics on the endpoint, or the metric is 0, and I have none of them.

this reminds me just another thing, currently scrape failure/error is logged by prometheus at debug level, the only way to understand why the scrapping failed is run collector with debug logs enabled, which is pretty inconvenient, do we have any plan to improve it, for example, be able to see the errors at error level.

**Comment by newly12** [comment]
I've also found such ask previously for prometheus: https://github.com/prometheus/prometheus/issues/7384

**Comment by Aneurysm9** [comment]
> do we have any plan to improve it, for example, be able to see the errors at error level.

No, we do not presently plan to change this for the same reasons that have been discussed upstream in Prometheus.
