### ISSUE TITLE
Request for Triager role for evan-bradley

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#13629]
I would like to take on a Triager role in the Collector contrib repository.

I have been joining the SIG and triage meetings nearly every week for the past two months, have been fairly active in issues, and have created PRs in the contrib repo. I would like to get more involved by helping to triage and prioritize issues.

I meet all the requirements listed in the [community guidelines](https://github.com/open-telemetry/community/blob/main/community-membership.md#triager) for the role.

**Comment by dmitryax** [comment]
I support!

**Comment by dmitryax** [comment]
Let's keep the issue open for couple days to see if there are any objections.

cc @open-telemetry/collector-contrib-maintainer

**Comment by TylerHelmuth** [comment]
I support!

**Comment by djaglowski** [comment]
I support!
