### ISSUE TITLE
[processor/spanmetricsprocessor] Add periodic metric reader

### ISSUE THREAD

**Issue by Yamakaky** [open-telemetry/opentelemetry-collector-contrib#13621]
**Is your feature request related to a problem? Please describe.**
Currently, a new metric value is generated every time a span is processed. With high activity, this can generate a huge amount of data.

**Describe the solution you'd like**
It would be nice to be able to configure a measurement rate, for example a new metric every 10s.

**Describe alternatives you've considered**
I don't think there is a way to configure a processor to do this outside of the spanmetrics?

One could also use a prometheus exporter + prometheus receiver with configurable scrap interval, but that seems complicated.

**Additional context**

**Comment by garry-cairns** [comment]
I'd be interested in having a go at implementing this as a first contribution. But I'm not sure I understand the problem description at present. Reading naively, I'd expect "Currently, a new metric value is generated every time a span is processed" to mean that each count metric produced would be 1, and each histogram would have exactly one value in one bucket. That doesn't match what I see when I run spanmetrics (see my recreation at https://gitlab.com/ilikewhenitworks/otel-example).

Do you mean it sends each time a *batch* of spans is processed and, if so, might the correct approach here be controlling this through the timeout on the batch processor (https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor)?

**Comment by Yamakaky** [comment]
I'm not sure what the problem is exactly. The symptom is that new metrics are generated very frequently, I assume per trace or batch. The traces are batched in upstream of spanmetrics, so maybe per batch. For now I use https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/processor/spanmetricsprocessor/v0.59.0/processor/spanmetricsprocessor/testdata/config-3-pipelines.yaml but that's not very user friendly.

**Comment by Yamakaky** [comment]
I understand that solution, it just adds a delay to the ingestion pipeline which is annoying when viewing traces in real time.

In the meantime, the doc could be updated to indicate that metrics are generated per batch (if that's how it works).

**Comment by garry-cairns** [comment]
Sorry I missed the last paragraph in your reply. I think this will likely need an experienced contributor/maintainer to opine rather than me. My initial view would be that it may not be possible to have the spans flow through the processor pipeline and on to the exporter without also releasing them from spanmetrics—in effect publishing the metrics as a result.
