### ISSUE TITLE
How to load balance by trace id for tail sampling?

### ISSUE THREAD

**Issue by lihaomin1010** [open-telemetry/opentelemetry-collector-contrib#13635]
@jpkrohling hi, i want to use tail sampling recently. But i maybe need multiple collector instances because of too many requests count. I see that you mentioned load balancing by trace-id, and i'm interested in your specific strategy. 
Could you tell me something about it? Thanks!
By the way, i think we can keep a hash table by collector number and hash trace id to it. But it seems to be difficult that how to keep the hash table consistent when we change collector count.

**Comment by habmic** [comment]
Hi @lihaomin1010 , you can use the "loadbalancing" exporter for that:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/loadbalancingexporter

**Comment by lihaomin1010** [comment]
> Hi @lihaomin1010 , you can use the "loadbalancing" exporter for that: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/loadbalancingexporter

Great! That's  what I'm interested in.
But i found i need change my config about list of ip when i change the collector instance.
 
In fact, i'm an user of k8s, ip changes frequently. So do you have some ideas about it?

**Comment by habmic** [comment]
Yes, you can use DNS resolver which will return a dynamic list of ips.

**Comment by lihaomin1010** [comment]
> Yes, you can use DNS resolver which will return a dynamic list of ips.

I hope I can describe my problem clearly and my poor English won't bother you ^-^

I think i need multiple instances for tail-sampling exporter which named collectors-TS, so i also need multiple instances for load-balancing exporter which named collectors-LB. I will use a Dns for collectors-TS in collectors-LB's config.

But if i change the ip of collectors-TS, the dns results in different instance of collectors-LB is also different in a short time. I think the load balancing strategy will be different duration this time.

Could you tell me something about it? We accept the different duration a short time? Or there is something could guarantee consistency.

**Comment by lihaomin1010** [comment]
> 

I found i don't need two sets of collector. Only need to config receive/exporter for two pipeline. But question is similar.

**Comment by jpkrohling** [comment]
> I think i need multiple instances for tail-sampling exporter which named collectors-TS, so i also need multiple instances for load-balancing exporter which named collectors-LB. I will use a Dns for collectors-TS in collectors-LB's config.

Correct, you'd ideally have two layers of collectors: one for the load balancers and one for the tail sampling. You *could* in theory, make that with two pipelines per collector, but I would advise against that: on such a setup, you likely want to isolate the layers to spread the risk.

> We accept the different duration a short time? Or there is something could guarantee consistency.

Right now, there are no consistency guarantees, as it would require a complexity that might not be warranted. The DNS resolver runs the query every 5 seconds, meaning that two load balancers would have differing views of the deployment for at most 10 seconds.

The load balancing exporter is made to have more "resolvers," and we have considered having one such resolver that would watch the Kubernetes API server for changes to a particular deployment. This would provide faster reaction times to scaling events while still not having the complexities that a consistent view would require. We just didn't have anyone interested in contributing that feature yet.

**Comment by lihaomin1010** [comment]
> 

Thanks, i Got it. We decided to run this solution in production for a while. If we need to use k8s list/watch to solve problems after a while, I am glad to contribute to the community.

**Comment by lihaomin1010** [comment]
> Correct, you'd ideally have two layers of collectors: one for the load balancers and one for the tail sampling. You _could_ in theory, make that with two pipelines per collector, but I would advise against that: on such a setup, you likely want to isolate the layers to spread the risk.

By the way, why don‘t you advise two pipeline? The risk of it is about memory, code bug or something else?

**Comment by jpkrohling** [comment]
Their usage profiles are quite different. The tail-sampling processor will keep data in memory, potentially doing extra processing. The load balancing will send data to the right backend and is mostly stateless apart from the list of backends. They can scale at different paces so that I would have them at different layers. 

Nothing prevents you from having two pipelines per instance though, and if you are brave enough, I would love to hear about your experience.

**Comment by jpkrohling** [comment]
I'm closing this as I believe this has been fully addressed. If you still require clarifications, feel free to reopen.
