### ISSUE TITLE
loadbalancingexporter: support metrics series hash based export

### ISSUE THREAD

**Issue by hanjm** [open-telemetry/opentelemetry-collector-contrib#13633]
**Is your feature request related to a problem? Please describe.**

Currently, loadbalancingexporter support traces and logs, based traceid or service, does not support metrics.

**Describe the solution you'd like**

support metrics. loadbalancing with series hash( metric name + all attribute ) and service.

**Comment by hanjm** [comment]
still valid

**Comment by hanjm** [comment]
ping @open-telemetry/collector-contrib-triagers

**Comment by jpkrohling** [comment]
Status update: I would still welcome a PR for this change, but I have no intention on working on it myself.

**Comment by jpkrohling** [comment]
I'm closing, as there hasn't been any movement on this for a long time. If there's still interest in contributing this feature, please reopen.
