### ISSUE TITLE
Split OTLP -> Loki conversion logic into its own package

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#13649]
To unify the conversion logic between OTLP and Loki on the OpenTelemetry Collector and Loki, we should split this into its package, similar to what we have for the Jaeger translator. This should be done following up on #12873.

**Comment by mar4uk** [comment]
pkg/translator/loki was created https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14106. This issue could be close
