### ISSUE TITLE
[exporter/sumologic] Exporter mutates pdata

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#13646]
The exporter mutates pdata:
- Logs: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/sumologicexporter/exporter.go#L171.
- Metrics: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/sumologicexporter/exporter.go#L314

 In order to avoid affecting other exporters configured alongside, the exporter has to be marked as mutating data so all pdata is copied over or it should be changed to not mutate the data.

**Comment by evan-bradley** [comment]
Closing this as resolved by #13647.
