### ISSUE TITLE
[receiver/mongodbreceiver]: Add lock metrics

### ISSUE THREAD

**Issue by sohampachpande** [open-telemetry/opentelemetry-collector-contrib#13661]
Enhancement
Add the following metrics for the mongodbeceiver:

| Name | Description | Unit | Type | Attributes |
| ---- | ----------- | ---- | ---- | ---------- |
| **mongodb.locks.acquire_count** | Number of times the lock was acquired in the specified mode. | {count} | Sum(Int) | <ul> <li>database</li> <li>lock_type</li> <li>lock_mode</li> </ul> |
| **mongodb.locks.acquire_wait_count** | Number of times the lock acquisitions encountered waits because the locks were held in a conflicting mode. | {count} | Sum(Int) | <ul> <li>database</li> <li>lock_type</li> <li>lock_mode</li> </ul> |
| **mongodb.locks.deadlock_count** | Number of times the lock acquisitions encountered deadlocks. | {count} | Sum(Int) | <ul> <li>database</li> <li>lock_type</li> <li>lock_mode</li> </ul> |
| **mongodb.locks.time_acquiring_micros** | Cumulative wait time in microseconds for the lock acquisitions. | {count} | Sum(Int) | <ul> <li>database</li> <li>lock_type</li> <li>lock_mode</li> </ul> |

**Comment by sohampachpande** [comment]
Creating PR #13662 to add this feature enhancement

**Comment by djaglowski** [comment]
Closed by #13662
