### ISSUE TITLE
[receiver/elasticsearchreceiver]: Add two cluster level metrics

### ISSUE THREAD

**Issue by davidji99** [open-telemetry/opentelemetry-collector-contrib#13748]
### Enhancement

Add the following cluster level metrics for the `elasticsearchreceiver`:

* `elasticsearch.cluster.pending_tasks`
* `elasticsearch.cluster.in_flight_fetch`

**Comment by djaglowski** [comment]
The cluster metric and cache metrics appear to be fairly unrelated, so please submit separate PRs for those.
