### ISSUE TITLE
To Access the secret of Kubernetes when using receiver-creator

### ISSUE THREAD

**Issue by jerryguowei** [open-telemetry/opentelemetry-collector-contrib#13744]
**Is your feature request related to a problem? Please describe.**
I try to use the receiver-creator to create an elasticsearch receiver on running time.  we need the password for the `elasticserach` receiver to access  `elasticsearch` cluster. But the secret is stored in the  kubernetes secret. It looks 
there is no way to access those secret. As the `pod` rule only have access to labels, annotations, but no access to secret

**Describe the solution you'd like**
It would be better to access the secret in the `create-creater` when the observer is k8s-observer and type is `pod` or `port`

**Comment by evan-bradley** [comment]
I think the way to solve this would be to use the Kubernetes secret with the password to set an environment variable in the Collector pod, then [use the environment variable](https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables) in the Elasticsearch receiver config. As I understand it, the rules provided by the receiver creator are for determining when to instantiate a receiver, and delegate the configuration for a receiver to that receiver.

**Comment by jerryguowei** [comment]
> I think the way to solve this would be to use the Kubernetes secret with the password to set an environment variable in the Collector pod, then [use the environment variable](https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables) in the Elasticsearch receiver config. As I understand it, the rules provided by the receiver creator are for determining when to instantiate a receiver, and delegate the configuration for a receiver to that receiver.

That's one option that I considered, but it does not seem to solve my problem.  We have multiple tenants in k8s environment, each tenant is deployed in a separated namespace. 
Each tenant would have an isolated Elasticsearch cluster and related user credential.  The tenants are created /destroyed at runtime. We can't expose the credentials via secret  to environment at runtime.
