### ISSUE TITLE
Flaky k8sprocessor/observability Test in CI

### ISSUE THREAD

**Issue by ericmustin** [open-telemetry/opentelemetry-collector-contrib#1374]
**Describe the bug**
This test is flaking in the build pipeline

```
--- FAIL: TestMetrics (2.00s)
    observability_test.go:93: timedout waiting for metrics to arrive
FAIL
coverage: 100.0% of statements
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor/observability	2.111s
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/5476/workflows/d658ff15-6d5b-4854-b4fd-05ae4647b696/jobs/41623

**Steps to reproduce**
see https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/5476/workflows/d658ff15-6d5b-4854-b4fd-05ae4647b696/jobs/41623

**What did you expect to see?**
Unit tests should pass, pr is not touching that test

**What did you see instead?**
Unit test failed

**What version did you use?**
CI/CD

**What config did you use?**
CI/CD

**Environment**
CI/CD

**Additional context**

**Comment by jpkrohling** [comment]
This is a duplicate of #1093.

**Comment by ericmustin** [comment]
Ok no worries thanks for pointing that out, had been asked to file this by some other maintainers in the gitter, but as long as it's being track by #1093 can close. Cheers!
