### ISSUE TITLE
[processor/cumulativetodelta] Heavy memory usage of histograms

### ISSUE THREAD

**Issue by balintzs** [open-telemetry/opentelemetry-collector-contrib#13751]
**Problem Description:**
The Cumulative to Delta processor needs to record all numerical values of cumulative datapoints in order to calculate the difference between them. Values are stored based on their identity, which contains all resource, scope and datapoint attributes.

For histograms, the sum, the count and all bucket counts are stored as separate values. This causes huge spikes of heap memory usage when a large number of histogram datapoints pass through the processor.

The following screenshots show the heap memory allocation bytes and working set bytes for the same amount of data:
A) With Cumulative to Delta Processor turned on:
![Screenshot 2022-08-31 at 16 51 33](https://user-images.githubusercontent.com/16084033/187722955-e904f41b-7fcb-41fe-af09-1e33df3bc838.png)
B) With Cumulative to Delta Processor turned off:
![Screenshot 2022-08-31 at 16 54 03](https://user-images.githubusercontent.com/16084033/187723478-ddf8b194-9538-4b13-a8ba-125487ab2254.png)

**Proposed Solution:**
After discussing the issue with @mistodon, we believe that instead of treating each numerical value in a histogram datapoint separately, we should store them together under a single entity, and add handling for calculating the delta of each value contained within.

**Comment by balintzs** [comment]
Link to issue requesting histogram support in Cumulative to Delta Processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12423

**Comment by TylerHelmuth** [comment]
@balintzs is this something you plan to work on?

**Comment by balintzs** [comment]
@TylerHelmuth, yes we have already started working on it.

**Comment by balintzs** [comment]
we found the cause of the memory issue and opened a PR with the fix: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14729
