### ISSUE TITLE
[pkg/telemetryquerylanguage] Change NewParser signature to have a list of Options

### ISSUE THREAD

**Issue by kentquirk** [open-telemetry/opentelemetry-collector-contrib#13759]
**Is your feature request related to a problem? Please describe.**
We expect that that Parser object will need to change over time, and we want the signature of NewParser to be stable over time, so we would like to convert the signature of NewParser to have a variadic list of ParserOptions, each of which can modify a parser. This way, new features wouldn't require existing consumers of NewParser to change when the Parser grows new capabilities.

**Describe alternatives you've considered**
Not doing this means that future changes are more costly, because they would require breaking changes or awkward defaults.

**Additional context**
See discussion in #13544

**Comment by kovrus** [comment]
@TylerHelmuth @kentquirk if you are not working on it, do you mind assigning it to me?

**Comment by TylerHelmuth** [comment]
@kovrus its yours.

**Comment by kovrus** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17394
