### ISSUE TITLE
Support the stdout operator in filelog operators

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#13758]
**Is your feature request related to a problem? Please describe.**
As a user of OTel native logging, it would be very helpful for debugging and user enablement, if I could use the stdout operator in the splunk otel collector to examine the entries as they pass through various filelog receiver operators. We frequently need to create custom operators to transform log entries and it is extremely difficult when it is not clear to users what the entries look like as they flow in through the filelog receiver and through the operators.

https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/operators/stdout.md

I attempted adding it to my pipeline and I get an error advising unsupported operator.

Originally reported https://github.com/signalfx/splunk-otel-collector/issues/1400

**Describe the solution you'd like**
Add support for stdout operator.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by atoulme** [comment]
@djaglowski for your review

**Comment by djaglowski** [comment]
@atoulme, this was recently enabled. (See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13397)
