### ISSUE TITLE
Influxdb receiver not passing optional K6 system-tags

### ISSUE THREAD

**Issue by perrinj3** [open-telemetry/opentelemetry-collector-contrib#13771]
When using K6 to output to the Influxdb Receiver in Opentel Collector Contrib the optional system-tags are ignored by Opentel and the default system-tags are surpressed

**Steps to reproduce**
run k6 command like this
k6 run --out influxdb=http://localhost:8086 --config "d:\k6\minimal_config.json"  "D:\k6\script_5154_apache_no_tags_1_endpoint.js"  --system-tags vu,iter

**What did you expect to see?**
Expect to see vu and iter  tags to be passed through OpenTel and exported in the same way that user defined tags are. Also expect to continue to see the default system tags. 
eg the following command line works in that the tags specified are passed through
k6 run --out influxdb=http://localhost:8086 --config "d:\k6\minimal_config.json"  "D:\k6\script_5154_apache_no_tags_1_endpoint.js"  --tags buildnumber=123

**What did you see instead?**
Exported file from Opentel does not contain specified system-tags and optional system tags no longer appear. Observing Opentel exporter output in debug mode also show they are not in the stream.

**What version did you use?**
Version": "6a1c247"  v0.39

**What config did you use?**
receivers:
  influxdb:
    endpoint: "0.0.0.0:8087"
  
exporters:
  file:
    path: ./k6_data.json 
 
  logging:
    loglevel: debug
    sampling_initial: 1
    sampling_thereafter: 1

service:
  pipelines:
    metrics:
     receivers: [influxdb]
     exporters: [logging,file]

**Environment**
Windows MSI

**Additional context**

**Comment by evan-bradley** [comment]
Passing the `--system-tags` flag to k6 causes it to only attach the system tags specified in the flag to metrics, which is why the default system tags do not appear in that case.

When specifying other additional system tags such as `ip` or `ocsp_status` status, I do see these tags, but only on some metrics. Can you verify whether k6 is attaching these attributes to the metrics where you expect to see them? The influxdb receiver doesn't filter tags to the best of my knowledge, so I think you should see them if k6 is attaching them.

Also please note that the latest released version of the Collector is 0.58.0, since you specified you are on 0.39.0. If you are able, please test with the latest version to see if it changes anything for you.

**Comment by perrinj3** [comment]
**Ok thanks. The behaviour is confined to the use of the  vu and iter system-tags. If I use other tags like ip it behaves as expected. 
I'm now using  otelcol-contrib_0.59.0windows_amd64.tar.gz and behaviour is the same.
If I use --system-tags vu,iter --test_tag=999 and put opentel into debug logging I get the following in the OpenTel debug logging**
```
Metric #0
Descriptor:
     -> Name: vus_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 00:56:38.0405963 +0000 UTC
Value: 1.000000
Metric #1
Descriptor:
     -> Name: vus_max_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 00:56:38.0405963 +0000 UTC
Value: 30.000000
Metric #2
Descriptor:
     -> Name: data_sent_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 00:56:38.064598 +0000 UTC
Value: 116.000000
Metric #3
Descriptor:
     -> Name: data_received_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 00:56:38.064598 +0000 UTC
Value: 12252.000000
```
**In this case the user defined tag appears but the system-tags do not. NOTE This behaviour only occurs for the optional K6 system tags being iter,vu** 

**In the JSON file I am writing to in parallel I can see that K6 is sending the vu and iter tags for data_sent and data_received. 
I've also verified that if I bypass OpenTel and connect to influxdbv1 I can see the vu and iter tags** 
```
{"type":"Point","data":{"time":"2022-09-02T10:56:33.0275022+10:00","value":1,"tags":{"test_tag":"999"}},"metric":"vus"}
{"type":"Point","data":{"time":"2022-09-02T10:56:33.0275022+10:00","value":30,"tags":{"test_tag":"999"}},"metric":"vus_max"}
{"type":"Point","data":{"time":"2022-09-02T10:56:33.0505004+10:00","value":116,"tags":{"vu":"1","iter":"1","test_tag":"999"}},"metric":"data_sent"}
{"type":"Point","data":{"time":"2022-09-02T10:56:33.0505004+10:00","value":12252,"tags":{"test_tag":"999","vu":"1","iter":"1"}},"metric":"data_received"}
```

**If I use --system-tags ip --test_tag=999 I get the following. In this case ip is appearing (as you observed)**
```
Metric #7
Descriptor:
     -> Name: http_req_duration_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> ip: STRING(10.53.138.70)
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 01:03:45.7434016 +0000 UTC
Value: 1.508400
Metric #8
Descriptor:
     -> Name: http_req_blocked_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> ip: STRING(10.53.138.70)
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 01:03:45.7434016 +0000 UTC
Value: 0.951700
Metric #9
Descriptor:
     -> Name: http_req_connecting_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> ip: STRING(10.53.138.70)
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 01:03:45.7434016 +0000 UTC
Value: 0.951700
Metric #10
Descriptor:
     -> Name: http_req_tls_handshaking_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> ip: STRING(10.53.138.70)
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 01:03:45.7434016 +0000 UTC
Value: 0.000000
Metric #11
Descriptor:
     -> Name: http_req_sending_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> ip: STRING(10.53.138.70)
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 01:03:45.7434016 +0000 UTC
Value: 0.000000
Metric #12
Descriptor:
     -> Name: http_req_waiting_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> ip: STRING(10.53.138.70)
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 01:03:45.7434016 +0000 UTC
Value: 1.508400
Metric #13
Descriptor:
     -> Name: http_req_receiving_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> ip: STRING(10.53.138.70)
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 01:03:45.7434016 +0000 UTC
Value: 0.000000
Metric #14
Descriptor:
     -> Name: http_req_failed_value
     -> Description:
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> ip: STRING(10.53.138.70)
     -> test_tag: STRING(999)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-09-02 01:03:45.7434016 +0000 UTC
Value: 0.000000
```
**In this case the same tags are also in the JSON file**
```
{"type":"Point","data":{"time":"2022-09-02T11:03:27.6657472+10:00","value":1.0184,"tags":{"ip":"10.53.138.70","test_tag":"999"}},"metric":"http_req_duration"}
{"type":"Point","data":{"time":"2022-09-02T11:03:27.6657472+10:00","value":0.9953,"tags":{"test_tag":"999","ip":"10.53.138.70"}},"metric":"http_req_blocked"}
{"type":"Point","data":{"time":"2022-09-02T11:03:27.6657472+10:00","value":0.9953,"tags":{"test_tag":"999","ip":"10.53.138.70"}},"metric":"http_req_connecting"}
{"type":"Point","data":{"time":"2022-09-02T11:03:27.6657472+10:00","value":0,"tags":{"test_tag":"999","ip":"10.53.138.70"}},"metric":"http_req_tls_handshaking"}
{"type":"Point","data":{"time":"2022-09-02T11:03:27.6657472+10:00","value":0,"tags":{"test_tag":"999","ip":"10.53.138.70"}},"metric":"http_req_sending"}
{"type":"Point","data":{"time":"2022-09-02T11:03:27.6657472+10:00","value":1.0184,"tags":{"test_tag":"999","ip":"10.53.138.70"}},"metric":"http_req_waiting"}
{"type":"Point","data":{"time":"2022-09-02T11:03:27.6657472+10:00","value":0,"tags":{"test_tag":"999","ip":"10.53.138.70"}},"metric":"http_req_receiving"}
{"type":"Point","data":{"time":"2022-09-02T11:03:27.6657472+10:00","value":0,"tags":{"test_tag":"999","ip":"10.53.138.70"}},"metric":"http_req_failed"}
```

This is odd as I can't understand why the collector would reject some tags but not others. Please check if you can reproduce the behaviour.

**Comment by evan-bradley** [comment]
Thanks for that information. After looking into it further, I can reproduce the issue, though I am not sure what to do about it. However, I believe it is either an issue with k6, or the library used to parse the InfluxDB line protocol, not an issue within the receiver itself. Here is what I have found:

From what I can tell, k6 is sending the `vu` and `iter` system tags as string-typed fields on the metric data points instead of as tags. Here is a couple lines of the raw InfluxDB line protocol data sent to the collector:
```
http_req_waiting,ip=52.70.134.36,ocsp_status=unknown,test=test iter="0",value=52.795516,vu="1" 1662145520898775240
http_req_receiving,ip=52.70.134.36,ocsp_status=unknown,test=test iter="0",value=0.246273,vu="1" 1662145520898775240
```

The library can't determine the type of the data points, so tries to parse each field as a separate metric. It appends the name of the field to the end of the original metric name from the line protocol [as seen here](https://github.com/influxdata/influxdb-observability/blob/main/influx2otel/metrics.go#L213) (which is why in the Collector logs the metric names are all `*_value`). It checks the type of each field on the original data point, and `vu` and `iter` don't have valid values since they are strings, so it [prints out an error message](https://github.com/influxdata/influxdb-observability/blob/main/influx2otel/metrics.go#L209) and drops them.

Given that InfluxDB appears to handle this case, I believe it is an issue with the pdata conversion library, but I don't have enough context to say for sure.

**Comment by perrinj3** [comment]
Thanks for that investigation. I contacted K6 and they advised me to use the environment variable
 ``` K6_INFLUXDB_TAGS_AS_FIELDS = "" ```
This changed the iter and vu tags to numeric type and they are now accepted by the Opentelemtry collector.
