### ISSUE TITLE
azuremonitorexporter metrics support

### ISSUE THREAD

**Issue by tobiasvdp** [open-telemetry/opentelemetry-collector-contrib#13856]
**Is your feature request related to a problem? Please describe.**
No, just a question if there are plans for this.

**Describe the solution you'd like**
Currently we still have to rely on direct azuremonitor libs to send metrics over. 
We would like to trow out the vendor lock for this, and make the application unaware of cloud integrator.

**Describe alternatives you've considered**
direct lib currently in testing phase

**Additional context**
-

**Comment by evan-bradley** [comment]
Hi, thanks for your question. This should be covered by https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13552, please follow that issue to determine whether there are plans to implement it. I'm closing this for now, please let me know if that issue doesn't cover some aspect you'd like to know about, or feel free to follow up there.
