### ISSUE TITLE
[exporter/elasticsearch] Support Dynamic Index?

### ISSUE THREAD

**Issue by waterfeeds** [open-telemetry/opentelemetry-collector-contrib#13855]
my opentelemetry-collector version is 0.59.0

test config in file /opentelemetry-collector-contrib/exporter/elasticsearchexporter/testdata/config.yaml
exporters:
  elasticsearch:
    endpoints: [https://elastic.example.com:9200]
  elasticsearch/customname:
    endpoints: [https://elastic.example.com:9200]
    cloudid: TRNMxjXlNJEt
    timeout: 2m
    headers:
      myheader: test
    index: myindex
    pipeline: mypipeline
    user: elastic
    password: search
    api_key: AvFsEiPs==
    discover:
      on_start: true
    flush:
      bytes: 10485760
    retry:
      max_requests: 5

Are there any plans to support dynamic index in the near future? I wish to build the log index with datetime and environment variables.

**Comment by JaredTan95** [comment]
duplicated issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5854
