### ISSUE TITLE
Rename "TQL" (telemetry query language) for better clarity while it's still painless to do so

### ISSUE THREAD

**Issue by bhs** [open-telemetry/opentelemetry-collector-contrib#13919]
Not news: there's a sensible and valuable domain-specific language (DSL) built into the OTel collector that basically takes telemetry data and transforms it into other telemetry data. All good and makes sense. 👍

The "bug" here is that the DSL in question is called the "Telemetry Query Language" (aka "TQL" – see more [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/telemetryquerylanguage/tql))... when I heard about it, I assumed it was a language that performs *analysis* of the telemetry data... presumably due to the naming association with SQL? I brought this up with the @open-telemetry/governance-committee last week and others had the same concern.

Along those lines, can we come up with a different name before this one is too hard to change? I am glad to make suggestions (e.g., "Telemetry Transformation Language" or "Telemetry Transformation Expression Language"), but I'm not picky as long as it's clear that this is not an *analytical* query language.

**Comment by bhs** [comment]
cc @bogdandrutu :eyes:

**Comment by mx-psi** [comment]
cc @TylerHelmuth

**Comment by TylerHelmuth** [comment]
@bhs I'm interested in hearing more on this idea. Sounds like a good topic of discussion for the SIG meeting. I'll be on PTO during the meeting on the 7th, can we discuss on the 14th?

**Comment by bhs** [comment]
@TylerHelmuth the collector SIG meeting, yes? I could join for the first 30m though have a hard conflict at :30...

That being said, IMO it's better if we can briefly discuss objections and/or other ideas here where (a) it's easier for the entire community to follow and contribute to the discussion, and (b) it doesn't require an additional meeting 😅. If we hit some sort of roadblock or need a deeper conversation about a few options, that would be great for zoom/etc.

**Comment by bogdandrutu** [comment]
I understand the confusion, and I think renaming is good. Not good with names though :)

**Comment by dyladan** [comment]
This also frees up the namespace "Telemetry Query Language" if we ever decide to spec one. Currently we define a data format to push telemetry data (OTLP) but in the future we may also want to be able to pull it (TQL?).

**Comment by bhs** [comment]
Yeah, I harbor some anxieties about increasing OTel's scope to include the analytical side of observability (slippery slope, etc), but def agree that any sort of "QL" will make people think "pull+analyze".

**Comment by AloisReitbauer** [comment]
I also agree that the query name is confusing for a transformation language. 

On the topic of a dedicated "query language". Given there are semantic conventions available it would be possible to define the query language. Right now access to data is a very vendor/implementation specific and provides a lot of lock in. Once you have started to use one query provide it is almost impossible to switch. It is also quite impossible to provide good practice out-of-the-box queries to assess the state and health of an application.

**Comment by kentquirk** [comment]
I've been around long enough to remember when TTL stood for Transistor-Transistor Logic and was the standard for digital integrated circuits. :) But even though I'm not personally bothered by TQL, I would support the idea of renaming it to Telemetry Transformation Language (TTL) instead.

**Comment by dyladan** [comment]
A PR is likely going to touch a lot of files. I think it's probably smart to settle on a name before going into that level of work.

**Comment by jpkrohling** [comment]
Given this was born as part of the transform processor to let users express how to change the incoming data points, how about something like "Transformation Expression Language"?

**Comment by evan-bradley** [comment]
Another alternative could be "Telemetry Processing Lanugage" (or "Telemetry Processor Expression Lanugage" or similar), which covers a few [use cases](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/processing.md#use-cases-for-processing) described in the Processor Exploration document. This could cover aspects outside transformation, including filtering, enrichment, and routing that use the condition expressions to determine which telemetry data to act on.

**Comment by codeboten** [comment]
OpenTelemetry Transformation Expression Language or OTEL?

**Comment by dyladan** [comment]
> OpenTelemetry Transformation Expression Language or OTTEL?

OTelTEL?

Is this language ever meant to be used outside the collector? I like Telemetry Expression Language the best so far. It also gives a good short name of "telemetry expression" to refer to a telemetry expression language snippet.

**Comment by austinlparker** [comment]
I don't hate telemetry expression language. Quick google seems like we'd have pretty clear air cover in terms of defining it and ranking well.

Only real "confusing" part I could think of would be people thinking of it like regular expressions, but maybe that's not the _worst_ thing given its purpose?

**Comment by bhs** [comment]
So in terms of alternative names, these are the suggestions we've seen in this thread thus far:
* "Transformation Expression Language" (TEL)
* "OpenTelemetry Expression Language" (OTelEL?)
* "OpenTelemetry Transformation Expression Language" (OTelTEL)
* "OpenTelemetry Transformation Language" (OTTL)
* "Telemetry Transformation Language" (TTL)
* meta-option: do nothing / "Telemetry Query Language" (TQL)

Any other contenders? Just thought it would be helpful to make a list of the concrete possiblitiies.

**Comment by jpkrohling** [comment]
I'm with @dyladan's Telemetry Transformation Language.

**Comment by TylerHelmuth** [comment]
I'm gone for a week and miss out on all this discussion; choosing a name always brings everyone together 😄.

I am ok changing the name.  My choice would also be Telemetry Transformation Language (TTL).  

> Is this language ever meant to be used outside the collector

With the current implementation of TQL: yes.  The package itself is designed to be usable with any Context and functions, so it does support transforming any type of data.  This was the original author's vision.  The processor/package has grown since then and there have been recent questions around whether or not the generality of the package should be preserved or if it should be made specific to OTEL/the collector.  Personally, I like the concept of keeping the grammar generic, but I do concede that if we made it specific to the collector there are some benefits.  We can have that discussion in a different issue, though, if others have thoughts.

**Comment by Aneurysm9** [comment]
I think I would prefer `Telemetry Expression Language`.  I think it is useful for more than just transformation and the name should reflect that.

**Comment by bogdandrutu** [comment]
Preference `OpenTelemetry Transformation Language (OTTL)`. @TylerHelmuth it is opentelemetry specific since it works on top of otel concepts (resource, scope, etc.)

**Comment by codeboten** [comment]
Please vote: 
    "Transformation Expression Language" (TEL) 👍🏻 
    "OpenTelemetry Expression Language" (OTelEL?) 🎉 
    "OpenTelemetry Transformation Expression Language" (OTelTEL) 🚀 
    "OpenTelemetry Transformation Language" (OTTL) 🚢 
    "Telemetry Transformation Language" (TTL) 🥇 
    meta-option: do nothing / "Telemetry Query Language" (TQL) 🔕

**Comment by bogdandrutu** [comment]
@TylerHelmuth @codeboten looks like we have a winner, OTTL :)

**Comment by TylerHelmuth** [comment]
I will start the MASSIVE PR to switch the name lol

**Comment by bogdandrutu** [comment]
"OpenTelemetry **Transform** Language"?

**Comment by bhs** [comment]
thank you, all! surely the least dramatic and most efficient tech-project-renaming in OSS history 🏆 :)
