### ISSUE TITLE
Audit unit metadata for kBy vs KiBy and similar units

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#13935]
[UCUM](https://ucum.org/ucum) defines kBy as 1000 bytes, and KiBy as 1024 bytes. We should audit current locations where this is used and make sure that these are consistent (kBy = 1000 bytes, and KiBy = 1024 bytes).

We should also audit for similar units elsewhere (MBy, GBy vs MiBy, GiBy)

Currently, KBy is in use in the following receivers:
- [x] vcenterreceiver (#14108)
- [ ] nsxtreceiver

KiBy is in use in the following receivers:
- [ ] mongodbatlasreceiver

MBy:
- [x] vcenterreceiver (#14108)

MiBy:
- [ ] mongodbatlasreceiver

The prometheus normalization also has mappings for these units that seem like they may be inconsistent with UCUM:
- [ ] prometheus normalization

**Comment by evan-bradley** [comment]
@BinaryFissionGames Do you plan to work on this?

**Comment by BinaryFissionGames** [comment]
@evan-bradley Yes, you can assign me to this issue.
