### ISSUE TITLE
[receiver/elasticsearchreceiver] Fix client request nodeStatsPath to collect supported metrics

### ISSUE THREAD

**Issue by JonathanWamsley** [open-telemetry/opentelemetry-collector-contrib#13983]
**Describe the bug**
When metrics where added, a mock was done correctly but the client request path were never updated. 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/db6987e83c05080891e12ef96c1b3f394d62a9ad/receiver/elasticsearchreceiver/client.go#L85-L88

`os`, `script` should be added to the `nodeStatsMetrics`
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/db6987e83c05080891e12ef96c1b3f394d62a9ad/receiver/elasticsearchreceiver/internal/model/nodestats.go#L25-L40

`translog` should be included in the `nodeStatsIndexMetrics`
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/db6987e83c05080891e12ef96c1b3f394d62a9ad/receiver/elasticsearchreceiver/internal/model/nodestats.go#L166-L178

This can be seen in the 7.16 integration test that was recently updated for the following metric paths:
- [x] `os`
Example of a metric that should be non-zero:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/db6987e83c05080891e12ef96c1b3f394d62a9ad/receiver/elasticsearchreceiver/testdata/integration/expected.7_16_3.json#L4841-L4847

- [x] `script`
Example of a metric that should be non-zero:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/db6987e83c05080891e12ef96c1b3f394d62a9ad/receiver/elasticsearchreceiver/testdata/integration/expected.7_16_3.json#L1675-L1680

- [x] `translog`
Example of a metric that should be non-zero:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/db6987e83c05080891e12ef96c1b3f394d62a9ad/receiver/elasticsearchreceiver/testdata/integration/expected.7_16_3.json#L4808-L4813

**Steps to reproduce**
Running ES or integration test and observing zero metric values for said metrics.

**What did you expect to see?**
In the client request, the above metric paths.

**What did you see instead?**
In the client request, the above metric paths missing `os`, `script` and `translog`.
This can be easily observed with the zero metric values in the integration test.

**What version did you use?**
elasticsearchreceiver v0.59.0

**Comment by JonathanWamsley** [comment]
@djaglowski Is one PR good or would you prefer 3 different PR's for the `os` , `script` and `translog` separately?

**Comment by djaglowski** [comment]
@JonathanWamsley, separate please

**Comment by JonathanWamsley** [comment]
Resolved with #13985 #13986 and #13988
