### ISSUE TITLE
[exporter/elasticsearchexporter] Unable to use elasticsearchexporter

### ISSUE THREAD

**Issue by jsanant** [open-telemetry/opentelemetry-collector-contrib#13982]
**Describe the bug**
When deploying OTel Collector using [helm charts](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector), we are running into this error:
```
2022/09/08 13:56:30 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/09/08 13:56:30 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
Error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "elasticsearch/trace": 1 error(s) decoding:

* '' has invalid keys: traces_index
2022/09/08 13:56:31 collector server run finished with error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "elasticsearch/trace": 1 error(s) decoding:

* '' has invalid keys: traces_index
```

**Steps to reproduce**
Deploy the Helm template and edit the config map to use elasticsearch as a trace exporter. 

**What did you expect to see?**
The OTel Collector is up and running without any issues.

**What did you see instead?**
Unmarshal error for `traces_index` key

**What version did you use?**
Version: `0.59.0`
Docker Image: `docker.io/otel/opentelemetry-collector-contrib:0.59.0`

**What config did you use?**
Config:
```
exporters:
  elasticsearch/trace:
    endpoints:
      - 'https://opensearch:9200'
    tls:
      insecure: true
    traces_index: test-index
    user: <redacted>
    password: <redacted>
extensions:
  health_check:
  memory_ballast:
processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_mib: 409
    spike_limit_mib: 128
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'
      http:
        endpoint: '0.0.0.0:4318'
service:
  extensions:
    - health_check
    - memory_ballast
  pipelines:
    traces:
      exporters:
        - elasticsearch/trace
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
  telemetry:
    metrics:
      address: '0.0.0.0:8888'
```

**Environment**
OTel Collector docker image downloaded in the Helm chart.

**Additional context**
N/A.

**Comment by evan-bradley** [comment]
Hello, thanks for the detailed information. The `traces_index` config key was just added two days ago in this PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10180. It will not be available in a published Docker container until the next release. To use it before the next release, you will need to build an image from the `main` branch and use it in the Helm chart [like this](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L113).

**Comment by jsanant** [comment]
Hey @evan-bradley! 

Yes, we saw the PR after we raised the issue, will wait for the next release cycle. Thanks!
