### ISSUE TITLE
Instana exporter didn't work properly.

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-collector-contrib#14009]
**Describe the bug**
The collector send data to Instana backend got an error message and instana backend cannot detect the trace.
Please check the attached image. 
Sender failed {kind: process, name: batch,pipeline,traces,error: failed to send a request: Post http://10.x.x.x:1444 bundle
HTTP/1.x transport connection broken: malformed HTTP response.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.
Just use the opentelemetry-collector-contrib, start the collector and use the opentelemetry javaagent set the exporter as the collector, and set the collector's exporter as instana exporter.

**What did you expect to see?**
A clear and concise description of what you expected to see.
There should have no error message during the trace transfer.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
Centos
go 19
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by jpkrohling** [comment]
cc @hickeyma

**Comment by hickeyma** [comment]
@sweetxiaodai Looks like you are using HTTP instead of HTTPS. Can you retry with HTTPS instead.

**Comment by sweetxiaodai** [comment]
It works, changed to https and import CA to Linux truststore

**Comment by hickeyma** [comment]
@sweetxiaodai Great to hear that this is working for you now.

The documentation is correct in [Exporter configuration](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/instanaexporter#exporter-configuration) as it states that the endpoint starts with `https://serverless-`.

I have raised #14323 to improve the validation in the exporter.

**Comment by sweetxiaodai** [comment]
@hickeyma 
@evan-bradley 
@hickeyma 
@tmc 
Hello, I got same error when I replace instana server's certificate as a self-signed certificate.
Would you mind kindly check on this issue again.
[https://github.com/open-telemetry/opentelemetry-collector-releases/issues/201](url)

**Comment by hickeyma** [comment]
@sweetxiaodai I suggest closing [https://github.com/open-telemetry/opentelemetry-collector-releases/issues/201](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/url) and opening a new issue in this repo.  When you add the error stack to the description, can you add it as text within "```console" markdown and avoid screenshot. It's difficult to read the screenshot.

**Comment by sweetxiaodai** [comment]
@hickeyma Sure, I will create a new one. BTW, I am working on a company which is using Instana, we’d like to cooperate with IBM to make this feature(Instana exporter) more stable and build a reliable support channel. If you don’t mind, is it possible that provide me an email address?

**Comment by willianpc** [comment]
Hi @sweetxiaodai I suggest you / the company who is a customer of Instana to file a ticket via https://support.instana.com/hc/en-us

This channel will be faster and you will get more information.
Also, I noticed that you shared the agent key in the issue. That kind of information is better kept in private. Maybe you may consider to edit your issue where the agent key is seen from the OTel config file.

Best,
_ Willian

**Comment by hickeyma** [comment]
Thanks for responding @willianpc.

@sweetxiaodai There is a response in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14602#issuecomment-1263398517 by @hughluo where he will lease with the support team for you.

**Comment by sweetxiaodai** [comment]
Thanks so much, Already done. 
And changed the agent key

发自我的iPhone

**Comment by sweetxiaodai** [comment]
﻿
Thanks so much, Already done. 
And changed the agent key

发自我的iPhone
