### ISSUE TITLE
sigv4auth assume_role => bad AWS credentials error

### ISSUE THREAD

**Issue by ThaiDangFr** [open-telemetry/opentelemetry-collector-contrib#14006]
**Describe the bug**
I followed the tutorial here (https://docs.aws.amazon.com/eks/latest/userguide/deploy-deployment.html) and it works well when the prometheus remote write is on the same account than the EKS
Now I have a separate account for EKS and Managed Prometheus, so I need to assume a role to be able to write to the prometheus remote write. I used this yaml https://raw.githubusercontent.com/aws-observability/aws-otel-community/master/sample-configs/operator/collector-config-amp.yaml
And I modified the extensions/sigv4auth like this :

apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector-amp
spec:
  mode: deployment
  serviceAccount: adot-collector
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8888'
  config: |
    extensions:
      sigv4auth:
        assume_role:
          arn: "arn:aws:iam::1234567890:role/prometheus_remote_write_assumerole"
        region: "us-west-2"
        service: "aps"

**Steps to reproduce**
Follow the official guide : https://docs.aws.amazon.com/eks/latest/userguide/opentelemetry.html
Use 2 separate accounts, one for EKS and another for Prometheus
Use the assume_role configuration 

To check my role prometheus_remote_write_assumerole, on the CLI I assumed the role and export the aws id and secrets then, I used : 
awscurl --service="aps" --region="us-west-2" "https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-123/api/v1/query?query=adot_test_gauge0"
And received a success message, so the role is correctly defined

**What did you expect to see?**
No error in the pod my-collector-amp-collector

**What did you see instead?**
Error: failed to get config: invalid configuration: extension "sigv4auth" has invalid configuration: bad AWS credentials
2022/09/08 13:57:32 application run finished with error: failed to get config: invalid configuration: extension "sigv4auth" has invalid configuration: bad AWS credentials

**What version did you use?**
EKS 1.23
ADOT addon v0.56.0-eksbuild.1

**Comment by bryan-aguilar** [comment]
Is the `adot-collector` service account using an an IAM Role setup using the clusters OIDC Provider? For reference see this [doc](https://aws.amazon.com/blogs/containers/cross-account-iam-roles-for-kubernetes-service-accounts/). 

If IRSA is set up as linked above could you try with a collector configuration that does not use the `arn` field in the `sigv4auth` extension.
