### ISSUE TITLE
add triaged label

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#14014]
The current triaging process adds various labels, but it's difficult to determine if an issue has been triaged with many labels being used. The proposal here is to add a `triaged` label to make it clear that an issue has been looked at.

**Comment by mx-psi** [comment]
An alternative is to add a `needs-triage` label by default in the issue templates, and remove it once it's triaged

**Comment by codeboten** [comment]
@mx-psi i like this idea. This would require adding a github action to ensure all new issues receive the label (including the ones not created via a template) correct?

**Comment by mx-psi** [comment]
> @mx-psi i like this idea. This would require adding a github action to ensure all new issues receive the label (including the ones not created via a template) correct?

@codeboten I think you can just add it on the `labels` field of issue templates (e.g. alonside `bug` [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)) without using an action
