### ISSUE TITLE
Inheritable Attribute

### ISSUE THREAD

**Issue by anuragagarwal561994** [open-telemetry/opentelemetry-collector-contrib#14026]
**Is your feature request related to a problem? Please describe.**
This is somewhat related to a feature requirement as stated here:
https://github.com/open-telemetry/opentelemetry-specification/issues/1337

Sometimes we want to track spans relatable to specific business use case like `customerId`, `userId` etc.

If we would like to use `SpanMetricsProcessor` and aggregate metrics based upon these custom attributes, we would like them to present in subsequent child spans, instead of asking the user to manually propagate the details to all the spans.

Moreover even if we say that this is doable or expected, when we are doing auto-instrumentation this becomes very difficult to achieve for the spans which are not under our control.

Moreover we can pass the information once and can let the collector do the processing of populating these attributes to the child spans.

**Describe the solution you'd like**
A span processor which can take attribute from the parent span and populate to child span would be great for this use case. If the child span already has the attribute, user can be given an option to `update`.

If the user doesn't want this behaviour for certain spans, then there are 2 approaches:
* either allowing the user to select the spans using regex or basis on some attributes where this information needs to be propagated
* use the existing attributes span processor to remove extra attributes

This combined with `SpanMetricsProcessor` would give users superpower to browse through their business metrics with respect to system resources being consumed.

**Describe alternatives you've considered**
Currently I am using a custom `SpanProcessor` at the client side to do the same.

Although this approach is not bad, but there are 2 issues with this:
* this is not language agnostic, meaning that this might work for me in let us say `java` but another service which is using `go` will have to re-implement for their language. Making it as part of the `collector-contrib` will save multiple language specific implementations and the troubles associated with that.
* Another minor issue which can still be discounted is the extra processing added at the application layer and the data transfer which I believe for the concerned audience can be made the part of the collector.

**Additional context**
Further design and the configuration discussion can be discussed with the community.

**Comment by dmitryax** [comment]
I can imagine that this is not desirable behavior for most of the use cases. So if we want this functionality it should be optional and configurable for some specific set attributes (regexp?).

A bigger problem here is that currently span processor is applied to a span at a time. `pdata.Traces` batch doesn't guarantee that all the trace spans are there. So in order to implement this, you would need to introduce a state to span processor which is not desirable. It maybe worth introducing another processor if this feature is really important.

I would like to see if this feature is needed for other users and get some more feedback.

cc @open-telemetry/collector-contrib-approvers

**Comment by Aneurysm9** [comment]
I think that this is a generally useful feature, but I think it should probably live on the client side and needs specification and standardization of the behavior there, including cross-process propagation of such attributes.  There has been discussion of doing this before, but no concrete proposals.
