### ISSUE TITLE
[receiver/hostmetrics/disk] When running on windows, receiver crashes collector when perf counter is unavailable

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#14032]
**Describe the bug**
Running on Windows, the collector fails to start up [if the "LogicalDisk" performance counter is not available](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/aa298997cb19718ee267fdc7f969573a594698f2/receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows.go#L105).

**Steps to reproduce**
Run collector w/ a user that does not have access to the performance counter. (User belongs to neither Administrators nor Performance Monitor Users group.)

**What did you expect to see?**
The collector should start up successfully and run. The scraper should return an error from the scraper funciton.

**What version did you use?**
Windows 10

**Additional context**
Although this error may be essentially permanent, I do not believe it should cause the collector to crash during startup because this pattern causes the collector to be fragile. To illustrate the point, consider a collector that runs 20 scrapers, each of which may crash the collector during startup if their respective target is not available.

**Comment by djaglowski** [comment]
cc @dmitryax

**Comment by djaglowski** [comment]
The load and paging scrapers also appear to error during start, if an expected counter is not available.

**Comment by BinaryFissionGames** [comment]
I can take a look into this.
