### ISSUE TITLE
FluentForward Receiver to support Secure Forward (TLS)

### ISSUE THREAD

**Issue by nunojca** [open-telemetry/opentelemetry-collector-contrib#14030]
We are using FluentBit to collect logs from our applications and then sending to Otel Collector via FluentForward. The problem we have today is that the OtelCollector FluentForward Receiver doesn't support Secure Forward (TLS) and this is an issue from a security perspective.

I'm opening this issue to improve the existing [OtelCollector FluentForward Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/fluentforwardreceiver) to support [Secure Forward](https://docs.fluentbit.io/manual/pipeline/outputs/forward).

An alternative we are considering is to use Fluentd instead of OtelCollector as it is the natural target for FluentForward and supports TLS.

**Comment by nunojca** [comment]
I'm tagging @jpkrohling on this issue because we have been discussing this topics before.

**Comment by jpkrohling** [comment]
@dmitryax, do you know if there's a reason for this receiver not to use the HTTP Server Settings? I understand it might support other protocols than HTTP, but perhaps the code could just ignore the other HTTP server settings based on the protocol

**Comment by lrivera-verimatrix** [comment]
I wanted to know if supporting TLS was being worked on, but it seems it is not. I hope someone does soon because having encryption of data in transit is a must for production pipelines. Without it I cannot really use the collector or logging pipelines.

**Comment by dmitryax** [comment]
Hey. @nunojca , @lrivera-verimatrix . I don't have any spare cycles to work on this issue. So any help is appreciated

**Comment by jpkrohling** [comment]
I'm picking this for myself, but it might take a while for me to send in a PR. I'll leave another comment here once I start, until then it's up for grabs.

**Comment by jpkrohling** [comment]
This is way different than what I had in mind originally, and I'm removing myself as assignee, as I'm not expected to be able to work on this in the foreseeable future.
