### ISSUE TITLE
Prometheusremotewriteexporter: Support sending to Prometheus public API

### ISSUE THREAD

**Issue by jonnor** [open-telemetry/opentelemetry-collector-contrib#14139]
### Is your feature request related to a problem? Please describe.

I want to send metrics to Prometheus, from a process which does not have a HTTP port available. I have a Prometheus instance already configured with API access and the remote_write feature enabled. I am typically use the Prometheus local storage for testing/development and in production I use a hosted Prometheus which does not expose the storage backend to me. For these using the remote write of the storage backend is not so useful.

### Describe the solution you'd like

I would like the remote write plugin to use the Prometheus remote write API. 
This way the underlying storage system used remains an internal detail of the Prometheus instance.
This feature was made stable in Prometheus 2.33: 
https://promlabs.com/blog/2022/01/30/whats-new-in-prometheus-2-33#remote-write-receiver-marked-stable

**Comment by Aneurysm9** [comment]
This appears to duplicate #10358.  If that is not the case, please re-open with additional details.
