### ISSUE TITLE
[exporter/pkg/translator/prometheus] colon in metric names is being replaced with underscore, even when featureGate is used

### ISSUE THREAD

**Issue by premendrasingh** [open-telemetry/opentelemetry-collector-contrib#14135]
### Is your feature request related to a problem? Please describe.

When following metrics are harvested, leading colon is removed and rest of the colons are replaced with underscore.
Using feature flag **pkg.translator.prometheus.NormalizeName** I was expecting to retain the colons.

Prometheus allows these metrics to be harvested and does not changes the metric name. Check attached screenshot of Prometheus showing metrics with colon.

```
# HELP foobar with colon
# TYPE foobar counter
:foo::bar_total 7736
```

<img width="898" alt="foobar-metrics-with-colon" src="https://user-images.githubusercontent.com/7782889/190335793-61688534-d66c-4fd4-9f87-7d3d5cf1b2b2.png">

### Describe the solution you'd like

Fix behavior of featureGate ** pkg.translator.prometheus.NormalizeName** to allow colons in metric names so that behavior is same as Prometheus client.

### Describe alternatives you've considered

Add another featureGate to translator to allow colon in metric names.
pkg.translator.prometheus.AllowColonInMetricNames

**Comment by bogdandrutu** [comment]
Where is the name format for Prometheus?

**Comment by premendrasingh** [comment]
Metric name format taken from -

https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

`The metric name specifies the general feature of a system that is measured (e.g. http_requests_total - the total number of HTTP requests received). It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*`

**Comment by vjsamuel** [comment]
thank you @bogdandrutu and @Aneurysm9 for comments on slack. Per https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#text-format it is safe to assume that `:` can be a first character and a character after that. that being said, we can file a fix for the same.  @premendrasingh @newly12 can one of you please file a PR to address this?
