### ISSUE TITLE
Support for scraping a system "uptime" metric

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-collector-contrib#14130]
### Is your feature request related to a problem? Please describe.

The problem is that there is no "uptime" metric emitted from the collector's receivers. For us, many existing systems rely on this metric being scraped, and so not having this metric blocks migration. An entirely new receiver for this seems overkill. 

Other agents, such as the signalfx agent, [have scrapers](https://github.com/signalfx/signalfx-agent/blob/main/docs/monitors/collectd-uptime.md) for this.

### Describe the solution you'd like

A scraper in the `hostmetricsreceiver` that retrieves uptime, in the Linux case, from `/proc/uptime`. Also open to suggestions if there are any other suitable receivers. Potentially there could be a scraper in the hostmetrics receiver that scrapes miscellaneous system information. Also open to suggestions here. 

### Describe alternatives you've considered

I've considered writing my own receiver that collects the metric.

**Comment by astencel-sumo** [comment]
I believe this is a reasonable request. I think a new `system` scraper could be created to provide general system information like uptime and other information (to be honest no other examples come to mind at the moment).

We would probably need a semantic convention established for the metric name. I allowed myself to create a proposal here: https://github.com/open-telemetry/opentelemetry-specification/issues/2813.

**Comment by jamesmoessis** [comment]
@astencel-sumo I like your idea of a `systemreceiver` that scrapes general system info. I would be interested in working with anyone to create such a scraper, providing that we had support and sponsorship from a maintainer. I wonder if any maintainer has had similar thoughts and ideas. 

I don't think we need to wait for something like `system.uptime` to be in the semantic convention to start work on a `systemreceiver`. There are plenty of scrapers that emit metrics that aren't part of the semconv. If at some stage the metric names require adjusting due to semconv additions, then that is acceptable. We will keep the systemscraper in alpha until that presumably happens.

**Comment by jamesmoessis** [comment]
I've also noticed there is an `InfoStat` struct in `gopsutils` (the same lib that `hostmetricsreceiver` uses) which exposes uptime and a bunch of other system data. I think exposing that data as a scraper in the host metrics receiver would fit in quite nicely. 

Perhaps we can get some thoughts on the above from the codeowner of host metrics - @dmitryax any thoughts?

**Comment by kevinnoel-be** [comment]
Still useful

**Comment by kernelpanic77** [comment]
Can we sort of reopen this issue ? I think it is still relevant.

**Comment by omkarumarani** [comment]
We are looking for this matrix

**Comment by andrzej-stencel** [comment]
This issue was closed due to inactivity some time ago. Recently a new issue has been raised for this: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31627, so there's a chance this will be implemented.
