### ISSUE TITLE
[receiver/chronyreceiver] Improve context and timeout handling

### ISSUE THREAD

**Issue by jordanbertasso** [open-telemetry/opentelemetry-collector-contrib#14131]
### Describe the issue you're reporting

Currently the chronyreceiver uses `net.Dial` instead of `net.Dialer.DialContext`. This means that if a timeout were to occur during dialling, then no action would be taken to abort the current job.

The chronyreceiver should use `net.Dialer.DialContext` instead of `net.Dial`.

This enhancement has been implemented in #13841.

**Comment by MovieStoreGuy** [comment]
This can be closed now since it is merged in :)
