### ISSUE TITLE
[receiver/sqlquery] Support limiting queries using last collection time

### ISSUE THREAD

**Issue by dehaansa** [open-telemetry/opentelemetry-collector-contrib#14145]
### Is your feature request related to a problem? Please describe.

There are certain performance tables that contain timestamps identifying the time the data point was calculated or collected. It would be great to avoid duplicating data points incorrectly by filtering the metrics by only collecting when the relevant timestamp is after the previous collection time. In situations where collection frequency is controlled this is straightforward, but it's more complex if queries are static and end users can configure collection frequency.

### Describe the solution you'd like

I see two solutions, neither of which feel perfect.
1. Some kind of placeholder in the query for $$LAST_COLLECTION_TIME, in a documented format so a developer can write a query that only collects the metric when appropriate (`WHERE TIME_COLUMN > TO_DATE($$LAST_COLLECTION_TIME, 'date_format')`).
2. An attribute added to the query config that only creates metrics from rows with dates more recent that last collection time. 
``` 
timestamp_column: END_TIME
filter_metrics_older_than_last_collection: true #this name could probably use some work
```

### Describe alternatives you've considered

I've attempted to dynamically alter the queries used at config creation time based on the provided collection interval, but this doesn't appropriately factor in the amount of time consumed querying the database and can lead to missed data points.

**Comment by atoulme** [comment]
Would you like to work on this @dehaansa ?

**Comment by dehaansa** [comment]
I don't have time right now to dedicate to this issue, sorry.

**Comment by astencel-sumo** [comment]
Recently logs support has been added to the receiver () and with it, a solution that could likely be applied to metrics as well. See the description here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/9a5f72317d1e2af34c69eae68a0b9836451958d7/receiver/sqlqueryreceiver#tracking-processed-results

This description is specific to logs, but it looks like it could be easily implemented for metrics a well, right?
