### ISSUE TITLE
Move kafka marshaler/unmarshaler to be reused by other components

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#14152]
The Kafka marshaler and unmarshalers are useful for other components, such as the upcoming Azure event hub receiver.

Please consider moving them to a separate library so they may be reused.

**Comment by bogdandrutu** [comment]
we have the pdata `Marshaler` and `Unmarshaler` which should be used instead of the Kafka once.

**Comment by atoulme** [comment]
I want all the (un)marshalers: raw, zipkin, jaeger, pdata.
* https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkareceiver/jaeger_unmarshaler.go
* https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkareceiver/raw_unmarshaler.go
* https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkareceiver/zipkin_unmarshaler.go
* https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkareceiver/pdata_unmarshaler.go

**Comment by atoulme** [comment]
I didn't understand this @bogdandrutu sorry. I am going to move past this and just implement raw for azure event hubs.

**Comment by atoulme** [comment]
I have now implemented a different approach, and have not reused the codecs offered by kafka receiver. It turns out the azure event hub data is highly structured anyways and needs a specific parser, so not sure we'd be able to reuse much. Closing this issue.
