### ISSUE TITLE
`[receiver/hostmetrics/processscraper]`: memory metric names do not adhere to semantic conventions

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector-contrib#14327]
### Description

The memory metrics reported by the `hostmetrics` receiver's `process` scraper do not adhere to the semantic conventions:

- [`process.memory.physical_usage`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.60.0/receiver/hostmetricsreceiver/internal/scraper/processscraper/metadata.yaml#L61) should be `process.memory.usage` according to the [spec]
- [`process.memory.virtual_usage`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.60.0/receiver/hostmetricsreceiver/internal/scraper/processscraper/metadata.yaml#L70) should be `process.memory.virtual`  according to the [spec]

[spec]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/metrics/semantic_conventions/process-metrics.md

### Steps to Reproduce

Run the collector with `hostmetrics` receiver enabled and the `process` scraper configured (see example config below).

### Expected Result

The following metrics should be reported for memory usage:

- `process.memory.usage`
- `process.memory.virtual`

### Actual Result

The following metric names are reported for memory usage:

- `process.memory.physical_usage`
- `process.memory.virtual_usage`

## Collector version

v0.60.0

## Environment information

OS: Any (tested on Ubuntu 20.04)

## OpenTelemetry Collector configuration

```yaml
exporters:
  logging:
    loglevel: debug

receivers:
  hostmetrics:
    collection_interval: 3s
    scrapers:
      process:

service:
  pipelines:
    metrics:
      receivers:
      - hostmetrics
      exporters:
      - logging
```

## Log output

```console
Metric #2
Descriptor:
     -> Name: process.memory.physical_usage
     -> Description: The amount of physical memory in use.
     -> Unit: By
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
StartTimestamp: 2022-09-20 10:07:12 +0000 UTC
Timestamp: 2022-09-20 10:07:13.425679646 +0000 UTC
Value: 528384
Metric #3
Descriptor:
     -> Name: process.memory.virtual_usage
     -> Description: Virtual memory size.
     -> Unit: By
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
StartTimestamp: 2022-09-20 10:07:12 +0000 UTC
Timestamp: 2022-09-20 10:07:13.425679646 +0000 UTC
Value: 10870784
```

**Comment by kentquirk** [comment]
In the meeting today, people were talking about putting the switch behind a feature flag. 

What's wrong with sending the metric under both a new name and an old one for a while, and putting the old one behind a feature flag that initially defaults to ON?
