### ISSUE TITLE
Support credential profiles in AWS exporter

### ISSUE THREAD

**Issue by wangzlei** [open-telemetry/opentelemetry-collector-contrib#1437]
**Is your feature request related to a problem? Please describe.**
AWS supports credential profiles to deploy multiple credentials on one host, users can specify a profile option in creating session. See [doc](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_profiles.html).

Both `awsemfexporter` and `awsxrayexporter` in Collector use aws go SDK to create AWS service connection, we want to support `profile` option in `awsemfexporter` and `awsxrayexporter`, by setting profile property in Collector config.yml.

**Describe the solution you'd like**
Refer: https://github.com/aws/aws-xray-daemon/pull/76

**Describe alternatives you've considered**
No

**Additional context**
[AWS credential profiles](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_profiles.html)

**Comment by anuraaga** [comment]
@wangzlei Did we ever find why the standard `AWS_PROFILE` env var doesn't work?

**Comment by wangzlei** [comment]
> @wangzlei Did we ever find why the standard `AWS_PROFILE` env var doesn't work?

Thanks for your remind, the environment variable `AWS_PROFILE` works. Cancel this feature request.
