### ISSUE TITLE
Revert #1442

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#1443]
I reverted #1433 in #1442 

The PR breaks the ability to run make gotidy or go mod tidy on the main package because that generates a diff compare to go generate in the go.sum. It looks some missing dependencies that are not tracked are added when running go generate.

**Comment by andrewhsu** [comment]
This PR needs to be reverted: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1442
