### ISSUE TITLE
Duplicate/Stale metrics reported to Prometheus by load balanced collectors

### ISSUE THREAD

**Issue by ZackJaime** [open-telemetry/opentelemetry-collector-contrib#14456]
### Describe the issue you're reporting

Hi, apologies if this isn't the correct place for this question but I can't seem to find any other information on the problem I'm having with our collector deployment.

So the scenario we have is, in a Kubernetes cluster we have:
**n** nodes, **n** collector pods deployed as a daemonset, and 1 service pod that is emitting metrics via the opentelemetry .NET SDK. Where **n** in our current setup is 11
As far as we can tell we've pretty much deployed it in line with the helm chart, in that the collector pods are load balanced.
The collectors are set up with Prometheus scrape endpoints and each pod is scraped by our Prometheus instance.

The problem we're having is that since the collectors are load balanced, multiple collectors will expose the same metrics stream emitted by the same service pod, and Prometheus will effectively have between 1 - **n** copies of the same stream. Or more commonly, because metrics only get sent to collectors every 30 seconds, collector pods will have not only have the same stream reported multiple times, but the values will also vary for each of them.

The only deployment type that I think this wouldn't be an issue for is the sidecar deployment since each pod would have it's dedicated collector. But we'd prefer to not use that approach due to the multiplicative effects of having an extra container per pod as we horizontally scale out our services.

We also thought that perhaps we were supposed to set up the collectors with some kind of affinity so that metrics for a given pod only ever go to the collector on the same node as that pod, though there are still issues around when a collector pod fails and the metrics start being sent to a collector on a different node out of necessity.

This seems to be a pretty fundamental issue, so it feels like it must have already been solved (and to be honest somewhat obvious) but I've been unable to find any guidance on this in the documentation or anywhere else.

Has anyone else had this problem? am I being stupid?

**Comment by jpkrohling** [comment]
You are not being stupid, this is indeed not well-documented anywhere from what I remember. What I would recommend is using at least two types of collectors: one for receiving pull-based data, and another one for the remaining cases. The sidecar example you mentioned would fit this. Two types of deployments running side-by-side would also work if you use the OpenTelemetry Operator with the Target Allocator for one of those types. Or perhaps having one instance for metrics and one for traces/logs (more on that here: https://www.youtube.com/watch?v=WhRrwSHDBFs ). 

There are (were?) plans to add something similar to the Target Allocator to the collector proper, skipping the operator altogether, just not sure what the current state is. @Aneurysm9 might know more.

I tried to find some documentation for the target allocator but was unable to. @yuriolisa, do you know where to find that?

**Comment by Aneurysm9** [comment]
There are not, AFAIK, any plans to add the functionality of the Operator's Target Allocator directly to the collector.

In the topology described (collectors as daemon set pods) It would probably be desirable for application pods to emit their telemetry to the collector on the local node.  This affinity would avoid the disjoint view of the metrics that can happen when pushed to a load-balanced collector pool.  Similar to a sidecar, the collector generally has a shared fate with the workloads producing to it and if something disrupts the node a collector is running on it has likely also disrupted those workloads.

**Comment by kien-truong** [comment]
I'm also seeing this problem now; have we made any improvements in maintaining the continuity of timeseries across load-balanced OTEL collectors?

**Comment by jpkrohling** [comment]
Not from the load-balancer exporter perspective.
