### ISSUE TITLE
[receiver/kafkareceiver] Support zipkin_json(v1) 

### ISSUE THREAD

**Issue by jjmm0312** [open-telemetry/opentelemetry-collector-contrib#14472]
### Is your feature request related to a problem? Please describe.

Hello. I am using kafkareceiver with zipkin format v1 and v2.
But it supports zipkin_proto(v2), zipkin_json(v2), zipkin_thrift(v1).

### Describe the solution you'd like

I need zipkin_json(v1). Is there any reason that it doesn't support zipkin_json(v1)?
I found zipkin v1 unmarshal code as well.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0ea5dc49876c2298c06e235d22229ef0d4244c14/pkg/translator/zipkin/zipkinv1/json.go.

**Comment by MovieStoreGuy** [comment]
I don't believe there is any reason why we can't add this, I think it is just an oversight.

/good-first-issue

**Comment by Subhasish-Behera** [comment]
Hello i am new here! if no one is working can i take this issue as my first issue.

**Comment by fatsheep9146** [comment]
@Subhasish-Behera are you still willing to contribute this? If so, I can assign this to you.

**Comment by Subhasish-Behera** [comment]
> @Subhasish-Behera are you still willing to contribute this? If so, I can assign this to you.

Yeah, please assign it to me.
