### ISSUE TITLE
[pkg/ottl] Add back ability to pass logger to functions

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#14471]
We should probably add this case back so that functions can explicitly ask for a logger and not the entire telemetry settings struct.

_Originally posted by @TylerHelmuth in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14389#discussion_r979444035_

**Comment by bogdandrutu** [comment]
Please provide the motivation for this? We should standardize on fewer things, hard to develop a very generic language.
