### ISSUE TITLE
[receiver/k8seventsreceiver] Support for semantic attributes

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#14474]
### Describe the issue you're reporting

Would be cool to make some refactorings in k8s event receiver :)

One thing I was thinking about is parsing `involvedObject` to Kubernetes Resource Attributes using https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md

For example, this Event:
```
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2022-09-26T10:42:38Z"
  involvedObject:
    apiVersion: apps/v1
    kind: Deployment
    name: opentelemetry-collector
    namespace: sys-mon
    resourceVersion: "15905558"
    uid: f875e269-0e76-4735-a02d-a254ed056111
  kind: Event
  lastTimestamp: "2022-09-26T10:42:38Z"
  message: Scaled down replica set opentelemetry-collector-55c485d665 to 0
  metadata:
    creationTimestamp: "2022-09-26T10:42:38Z"
    name: opentelemetry-collector.1718630a415e713e
    namespace: sys-mon
    resourceVersion: "15905574"
    uid: 5b8fc5bb-3f64-47a5-bf21-d02f45377af5
  reason: ScalingReplicaSet
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: deployment-controller
  type: Normal

```

Would end up with the following Resource attributes:
```
k8s.deployment.name =   opentelemetry-collector
k8s.deployment.id = f875e269-0e76-4735-a02d-a254ed056111
k8s.namespace.name =  sys-mon
```

Also, currently namespace is in Log attribute, not Resource -> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8seventsreceiver/k8s_event_to_logdata.go#L77-L85

So I would like to move that to Resource :)

Thoughts @dmitryax ? :)

**Comment by scheler** [comment]
@povilasv I will work on modifying the spec language to allow for this. The attribute `event.domain` is only meant to be a logical separation across different event systems, so it allows for similar looking names in different domains but with a completely different purpose. However, within each domain we don't have to have any uniqueness constraints but leave it to whatever is idiomatic to the particular event system the domain represents.

Separately, I've a question on Kubernetes Events for my understanding - is the namespace+name combination unique across clusters? that is, (cluster+namespace+name) is unique and not just (namespace+name)?

**Comment by scheler** [comment]
@jack-berg The [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14603/files#diff-f4ba972b9039427bcc6b145203d6504639b9c7bc828c1b30e19c476f8e9b0ca3R80) associated with this issue is mapping the Kubernetes Event's name to `event.name`.

**Comment by jack-berg** [comment]
In those examples the Kubernetes event name is `nginx-deployment` for the first, and `nginx-deployment-68d7dcf58` for the second, correct? If so, I actually think these are not good matches for `event.name`. My interpretation of `event.name` (and I _think_ this has been the consensus based on conversations) is that along with `event.domain`, it forms an identifier for a particular class of events. Events with the same `event.domain` / `event.name` should generally follow the same structure, which may be defined via semantic conventions. For example, within the `browser` domain, we may emit events with `event.name` of `click`. All click events would adhere to a similar structure.

The kubernetes event.name appears to be an identifier for a particular kubernetes resource, which is a different concept. For one, kubernetes event.name will be high cardinality. Although not yet explicitly stated in the spec, opentelemetry `event.name` is expected to be low-ish cardinality. Additionally, a particular kubernetes resource will have lots of distinct types of things performed on it, so records with the same `event.name` wouldn't follow a similar structure.

Looking at the examples you've shown there, I'd say an appropriate `event.name` might be something like `involvedObject.kind` + `reason`. So `Deployment.ScalingReplicaSet` and `ReplicaSet.SuccessfulCreate` for the two examples shown here.

**Comment by dmitryax** [comment]
> I think using involvedObject.kind + reason or just reason sounds reasonable for event.name.

I agree. Reason seems the best candidate for `event.name`.

> Why do we need to record event.name and event.domain attributes for Kubernetes event? What's the purpose of doing it, what problem does it solve?

Probably just comply with the the event API spec.

**Comment by dmitryax** [comment]
Also I believe we need to put the full k8s event payload into the log body. Thats my understanding from reading the new OTel Events spec. 

This approach is taken in the new receiver proposed in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14185 which does a bit more then events collection. 

If we agree on the approach, we can probably replace the k8s events receiver with the new one going forward

**Comment by scheler** [comment]
> Why do we need to record event.name and event.domain attributes for Kubernetes event? What's the purpose of doing it, what problem does it solve?

I thought this is to conform the definition of Event in OpenTelemetry. If these attributes are missing, then these messages would be termed as logs. So if the backends are okay receiving Kubernetes events as logs then we can omit these attributes.

Btw, recording metadata.name for `event.name` or `k8s.event.name` is incorrect and misleading, it is the name of the object reported in the event and not the name of the event itself.

**Comment by Aneurysm9** [comment]
> > Why do we need to record event.name and event.domain attributes for Kubernetes event? What's the purpose of doing it, what problem does it solve?
> 
> I thought this is to conform the definition of Event in OpenTelemetry. If these attributes are missing, then these messages would be termed as logs. So if the backends are okay receiving Kubernetes events as logs then we can omit these attributes.

I think this gets at the question I was trying to ask in the SIG meeting today but maybe not expressing well.  What is the purpose of the `event.name` and `event.domain` attributes?  It seems that they should be to identify the `LogRecord` as an `Event` and to allow determination of how to interpret other attributes in the `Event`.  If, instead, we're meant to already know that we're looking for k8s events and check for `k8s.kind == Event` and  `k8s.reason` as an attribute then what is the purpose of the `Event` type?  What distinguishes the RUM events that are supposed to use `event.domain` and `event.name`?

**Comment by tigrannajaryan** [comment]
>What is the purpose of the event.name and event.domain attributes?

My understanding of the purpose of the `event.domain` attribute is to:
- Provide efficient means to route OTLP data by looking at the `event.domain` field only.
- Isolate the domains at the design phase, so that if producers in one domain design a poor event schema, the blast radius  of their poor choices is limited to that domain only and does not pollute someone else's domain.

**Comment by dmitryax** [comment]
> There is no blanket requirement that every LogRecord produced by Collector complies with Events API spec. Events API is a spec for events produced by OpenTelemetry API, it is not a requirement for the Collector (at least it is not in the current understanding of the spec).

The receiver actually produces events not logs. So I was thinking that having `event.domain` and `event.name` is a needed to distinguish events from log records.

**Comment by tigrannajaryan** [comment]
> The receiver actually produces events not logs. So I was thinking that having `event.domain` and `event.name` are needed to distinguish events from log records.

Events are logs (mostly) :-)

We need to be careful with extending Otel API concepts unnecessarily to the Collector. We introduced an Otel Events helper API that allows to create LogRecords with a specific shape easily (with `event.domain` and `event.name`) because users told us this is a frequent case. However, it does not automatically mean that LogRecords we want to emit in Collector needs to comply with that same shape.

For now I still do not understand why the data that is produced by k8s events receiver needs to match the shape of LogRecord that is produced by Otel Events API. What is the rationale for this?

I have a feeling that we are trying to shoehorn the data produced by k8s events receiver into the shape that Otel Events API defined because there is a co-incidence of terminology (both have the word "events" in them).

Also keep in mind that `event.domain` is recorded as a Scope attribute, so there MUST be a Scope for this to be even applicable. What's the Scope for k8s events? What's the Name of that Scope? As far as I can tell the Scope produced by k8sevents receiver is currently empty.

**Comment by tigrannajaryan** [comment]
> The backends can have different processing pipelines for logs and events, so the telemetry producers should decide on what they are emitting and freeze it.

Right, but why are deciding that k8s events are more likely to be processed similar to RUM events than similar to for example K8s pod logs collected by filelog using Helm Chart (which are plain LogRecords)?

Again, I think we should not by default assume every new kind of log record becomes an event. If that is the case then we failed with defining why we needed both the Events API and the Logs API. In that case we shouldn't have a Logs API and we should have event.name and event.domain as hard-coded fields of the log data model instead of being semantic conventions. I disagree with this approach. To me the default is exactly the opposite: every new source of logs is a LogRecord. Only if there is a strong evidence that it precisely fits the Otel API's Event definition then it should be shaped as an Event with event.name attribute on LogRecord and event.domain attribute on the Scope.

**Comment by Aneurysm9** [comment]
> For RUM events, we want to have expectation on the set of attributes for each value of `event.name` for the purpose of doing validation. and to avoid conflicts with events from other domains having same event names, we introduced the attribute `event.domain` for isolation. Now it felt natural to extend this convention to everyone that's generating events.

Shouldn't this be the case for every structured log record?  You need to know how to interpret the data contained in the record.  That can come from an implicit expectation that all records in a given log stream conform to a set of conventions or by an explicit indication on each record.  Why would RUM events be any different than k8s events from this perspective?

> Right, but why are deciding that k8s events are more likely to be processed similar to RUM events than similar to for example K8s pod logs collected by filelog using Helm Chart (which are plain LogRecords)?

k8s events are emitted in a different way by a different system than pod logs.  Pod logs are application logs that may or may not have structure and may or may not be part of an event-driven system.  k8s events are events emitted by actors in an event-driven system and have shapes that can be determined based on the name of the event.

> Again, I think we should not by default assume every new kind of log record becomes an event. If that is the case then we failed with defining why we needed both the Events API and the Logs API. 

I'm worrying that we have decided that RUM events are somehow special and need to have their own API created for them which will be named as if it is generic but then people will be told that it isn't and they shouldn't use it as if it were.  `Event` is a terribly general term and even if we try to give it a specific meaning it is likely that definition will be ignored in favor of intuition.  Many different systems are going to have events and I'm not sure we should try to be gatekeepers protecting the One True Event.  

In my view, every log record represents an event.  Every structured log record may represent an Event.  Most probably do, but `event.domain` is implicit or simply the log stream name and `event.name` is the message with the two combined enabling identification of how to interpret the remaining fields in the event.  

> We need to be careful with extending Otel API concepts unnecessarily to the Collector. We introduced an Otel Events helper API that allows to create LogRecords with a specific shape easily (with event.domain and event.name) because users told us this is a frequent case. However, it does not automatically mean that LogRecords we want to emit in Collector needs to comply with that same shape.

Why would this only apply to `LogRecords` created by an OTel API?  Don't we assume that metrics or spans may be constructed by systems that do not use an OTel API?  Whether directly into OTLP or in some other format through the collector.  Shouldn't logs be the same?  

> Also keep in mind that event.domain is recorded as a Scope attribute, so there MUST be a Scope for this to be even applicable. What's the Scope for k8s events? What's the Name of that Scope? As far as I can tell the Scope produced by k8sevents receiver is currently empty.

That should be easily fixed.  There has to be a scope in the `plogs.Logs` emitted by the receiver.  If it isn't populated with attributes then that can be fixed.  The receiver's import path becomes the scope name and the `event.domain` value can be `k8s` or it could be `io.k8s.{{.kind}}.{{.apiVersion}}`, which should give something like `io.k8s.Event.v1`.  That seems to fulfill the stated purpose of "avoid[ing] conflicts with events from other domains having same event names".

**Comment by tigrannajaryan** [comment]
OK, looks like some clarifications and guidance is due in the Logs spec. I will try to put together something and will link from here.

**Comment by tigrannajaryan** [comment]
I submitted https://github.com/open-telemetry/opentelemetry-specification/pull/2863, let's discuss.
