### ISSUE TITLE
Supporting schemas in Otel for logging (ECS)

### ISSUE THREAD

**Issue by jkowall** [open-telemetry/opentelemetry-collector-contrib#14528]
### Describe the issue you're reporting

Is your feature request related to a problem? Please describe.
When Otel ingest logs which are unrelated to other signals, there doesn't seem to be standard parsers for this data in otel. Meaning if we ingest a log from a webserver, we would want to parse the log correctly to allow us to correlate the data with application level logging for higher value. The idea was to add a schema to handle this, for example, ECS to allow better correlation. The spec for that is about to be merged (https://github.com/open-telemetry/oteps/pull/199). The issue remains that the parsing is not there. We should provide a library of configurations to enable parsing of common log formats which are not using otel today.
 
Describe the solution you'd like
Parsing for ECS in otel, to enable users to get more value from additional context.

Discuss :)

**Comment by djaglowski** [comment]
I agree with the vision here, that if ECS is officially adopted we should provide ways for users to easily transform logs to match the format.

> The issue remains that the parsing is not there.

I believe the collector already has all the parsing and transformation capabilities necessary to process logs into ECS. 

The primary issue is that predefined configurations must be developed and made available to users. We have an [examples directory](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/kubernetes/otel-collector-config.yml) in `collector-contrib` which contains a few specific configurations, such as one for collecting and parsing k8s logs, though this was not developed with ECS in mind. Still, this would seem to be the obvious starting point for contributing standardized configurations.

From there, we can improve the mechanism for making these configurations available to users. A configuration-focused plugin system for the collector has been discussed but not formally proposed. The general idea would be that partial configurations could be extracted, parameterized, and distributed. I am curious if there are any other suggestions for simplifying and or sharing configuration.
