### ISSUE TITLE
Set the Elasticsearch exporter as Unmaintained

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#14525]
### Describe the issue you're reporting

We've been pinging the code owners for the Elasticsearch exporter for almost 2 months now, with no reaction whatsoever. Following the component stability policy, I would like to start labeling Elasticsearch-related PRs and issues as "Unmaintained".

Current code owners: @urso @faec @blakerouse

An example where we asked for their feedback and didn't hear back is this PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12933

I suggest we wait until Sep 30 and start labeling issues as Unmaintained on Oct 3rd.

cc @open-telemetry/collector-contrib-maintainer

**Comment by JaredTan95** [comment]
@jpkrohling I am working enhancement the `elasticsearch exporter`, so I would like to be the maintainer of `elasticsearch exporter`. :-P
related PR:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10180

**Comment by djaglowski** [comment]
@JaredTan95, that's great, thank you.

Will you please open a PR adding yourself as code owner of the component? The current owners should be removed.

**Comment by djaglowski** [comment]
Please also take a look through the [related issues](https://github.com/open-telemetry/opentelemetry-collector-contrib/labels/exporter%2Felasticsearch) when you have some time.

**Comment by JaredTan95** [comment]
> Please also take a look through the [related issues](https://github.com/open-telemetry/opentelemetry-collector-contrib/labels/exporter%2Felasticsearch) when you have some time.

okay
