### ISSUE TITLE
Metrics filtering

### ISSUE THREAD

**Issue by quequiere** [open-telemetry/opentelemetry-collector-contrib#14536]
### Describe the issue you're reporting

Hi Guys ! I got metrics and I want to do a filter on "Data point attributes" in the collector. Is it possible ?
I already tried to use filter processor but this one can only filter on resource attributes.
```
  filter:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - http\.server\.requests
        resource_attributes:
          - Key: service.name
            Value: svcname
```
I haven't found a filter based on data point attributes and I need to remove specifics metrics from their uri attribues. E.G:
```
ScopeMetrics SchemaURL: 
InstrumentationScope io.opentelemetry.micrometer-1.5 
Metric #0
Descriptor:
  -> Name: http.server.requests
  -> Description: 
  -> Unit: ms
  -> DataType: Histogram
  -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
HistogramDataPoints #0
Data point attributes:
  -> application: STRING(appname)
  -> exception: STRING(None)
  -> instance: STRING(someInstance)
  -> method: STRING(GET)
  -> outcome: STRING(CLIENT_ERROR)
  -> status: STRING(401)
  -> uri: STRING(NEED_TO_BE_FILTERED)
```

**Comment by evan-bradley** [comment]
Expressions can be used in the filter processor to exclude metrics that contain a matching data point. For example, this configuration will filter metrics that include a data point that has a `state` attribute with value `user`, `system` or `wait`:
```yaml
filter:
  metrics:
    exclude:
      match_type: expr
      expressions:
      - Label("state") matches "^user|system|wait$"
```

Would this achieve what you are looking for?

**Comment by quequiere** [comment]
Yes, perfect it's working ! Thank you.
