### ISSUE TITLE
[ping-codeowners] Should ping multiple sets of code owners when an issue has multiple component labels

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#14568]
### Describe the issue you're reporting

I created #14567, which describes a simple change that should be applied to multiple components. Therefore, I labeled the issue with each affected component. I noticed that the ping bot does not handle this well. 

This does not come up often so may not be a priority, but to capture the ideal behavior, I suggest it would:
1. Generate a ping for each component label.
2. Include the name of the component in the comment. eg: "Pinging code owners for `receiver/foo`: @djaglowski. See [Adding Labels via Comments](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-labels-via-comments) if you do not have permissions to add labels yourself."

**Comment by jpkrohling** [comment]
Should this be closed? I believe this is already the case, as I added a few labels for different components on the issue below, and the different code owners were pinged in different comments:

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5749#event-7914612828

**Comment by djaglowski** [comment]
Before we close this, I'm curious if anyone (maybe @evan-bradley) agrees with the second suggestion, that we should include the component name in the ping message. It's minor improvement in my opinion.

"Pinging code owners for receiver/foo: @djaglowski. See [Adding Labels via Comments](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-labels-via-comments) if you do not have permissions to add labels yourself."

**Comment by evan-bradley** [comment]
@djaglowski I agree, we are already doing this in other ping messages. I've created a PR for this: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16552.
