### ISSUE TITLE
[exporter/prometheusremotewriteexporter] ambiguous import: found package cloud.google.com/go/compute/metadata in multiple module

### ISSUE THREAD

**Issue by gr0l0rg** [open-telemetry/opentelemetry-collector-contrib#14565]
## Description

Cannot do the `go mod tidy` command while importing the `github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter` module in my code

## Steps to Reproduce

1. `go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter`
2. `go mod tidy`

## Expected Result

`go mod tidy` exits with success

## Actual Result

`go mod tidy` exits with the following error

```
MY/MODULE.com imports
        go.opentelemetry.io/collector/config/configgrpc imports
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc tested by
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.test imports
        google.golang.org/grpc/interop imports
        golang.org/x/oauth2/google imports
        cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
        cloud.google.com/go v0.65.0 (~/go/pkg/mod/cloud.google.com/go@v0.65.0/compute/metadata)
        cloud.google.com/go/compute v1.7.0 (~/go/pkg/mod/cloud.google.com/go/compute@v1.7.0/metadata)
```

### Collector version

v0.60.0

**Comment by evan-bradley** [comment]
Can you provide any more information about your setup, such as other dependencies in your project's go.mod? Starting a new project and pulling in the Prometheus remotewrite exporter module doesn't produce any errors when I try this. My initial impression is that you are using another package with a conflicting dependency.

**Comment by gr0l0rg** [comment]
@evan-bradley This weird error was also being discussed in https://github.com/aws-observability/aws-otel-collector/issues/926
Somebody just stated the fix which is adding this replacement in `go.mod`
```
replace cloud.google.com/go => cloud.google.com/go v0.100.2
```
And it worked for me.

**Comment by lesovsky** [comment]
Have the similar issue when building custom collector with imported `exporter/prometheusexporter`

builder.yaml:
```
dist:
  name: otelcol-dev
  description: "OTel Collector distribution for PostgreSQL"
  output_path: ./otelcol-dev

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.62.0
```

got (formatted by me):
```
ocb --config builder.yaml 
2022-10-19T11:51:35.770+0600    INFO    internal/command.go:121 OpenTelemetry Collector Builder {"version": "0.62.1", "date": "2022-10-13T20:44:07Z"}
2022-10-19T11:51:35.770+0600    INFO    internal/command.go:154 Using config file       {"path": "builder.yaml"}
2022-10-19T11:51:35.770+0600    INFO    builder/config.go:103   Using go        {"go-executable": "/opt/go-1.18.7/bin/go"}
2022-10-19T11:51:35.771+0600    INFO    builder/main.go:76      Sources created {"path": "./otelcol-dev"}
Error: failed to update go.mod: exit status 1. Output: "go: finding module for package github.com/rogpeppe/go-internal/fmtsort
go: found github.com/rogpeppe/go-internal/fmtsort in github.com/rogpeppe/go-internal v1.9.0
go.opentelemetry.io/collector/cmd/builder imports
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter tested by
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.test imports
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver imports
        github.com/prometheus/prometheus/discovery/install imports
        github.com/prometheus/prometheus/discovery/gce imports
        golang.org/x/oauth2/google imports
        cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
        cloud.google.com/go v0.65.0 (/home/lesovsky/go/pkg/mod/cloud.google.com/go@v0.65.0/compute/metadata)
        cloud.google.com/go/compute v1.10.0 (/home/lesovsky/go/pkg/mod/cloud.google.com/go/compute@v1.10.0/metadata)"
```

After adding 'replaces' directive mentioned above, collector compiled successfully with no errors.

**Comment by Aneurysm9** [comment]
@dashpole it looks like this might need to be solved either in Prometheus or the Google OAuth2 library.  Are you able to connect the right people on the Google side to this issue to see how it should be addressed?

**Comment by dashpole** [comment]
Based on my digging, this is because https://github.com/spf13/afero is still using golang.org/x/oauth2 v0.0.0-20210218202405-ba52d332ba99, which depends on cloud.google.com/go@v0.65.0.  It seems a bunch of things depend on that.

I don't know if there is much that cloud.google.com/go could do, as it is mostly about users updating usage beyond v0.100.2.  This seems to be made much worse by the fact that many modules within cloud.google.com/go reference older versions of each other in cycles, which means even relatively new imports import the old molule.

I tried pinning prometheus, and pointing the PRW exporter at my fork, but it didn't help... https://github.com/prometheus/prometheus/compare/main...dashpole:prometheus:ambiguous_import

I think we might have to make due with replace statements for now.
