### ISSUE TITLE
[exporter/splunk_hec] Support Basic-Auth token authentication

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#14584]
### Is your feature request related to a problem? Please describe.

The HEC receiver also supports reading the token through Basic Auth.

You can use any username (even none) with the token as the password, and it'll work! Especially handy in environments where you can't add a custom header, but where basic auth is supported. A curl one-line example:
```
curl "https://:tokenhere@splunkindexer:8088/services/collector/event" -d '{"event":"it worked!"}'
```

### Describe the solution you'd like

We should support this for the receiver and exporter of HEC in OpenTelemetry as an alternative to the default Authorization header.

### Describe alternatives you've considered

N/A

**Comment by jpkrohling** [comment]
Every exporter using the default confighttp and configgrpc can be protected with any one of our authentication extensions. Isn't this exporter using confighttp/configgrpc to start the listener?

**Comment by atoulme** [comment]
Sorry, I'm plainly reporting a feature request. I have no insights to offer. This enhancement is open for anyone to participate.

**Comment by neelayu** [comment]
I believe Splunk HEC does not support basic authentication. 
https://community.splunk.com/t5/Getting-Data-In/HEC-Basic-Authentication/m-p/575525

**Comment by traytonwhite** [comment]
This is a feature that's not as commonly known as using the custom authentication header, but is documented:

https://docs.splunk.com/Documentation/Splunk/9.0.1/Data/HECExamples#Example_10:_Basic_authentication

The question linked is asking about using a Splunk account to auth with HEC - which is not supported. The person posting the question does mention they can get HEC token auth to work, though:

> The username:HEC token works as is hinted in the documentation

**Comment by neelayu** [comment]
Okay. Thanks for clarifying. @atoulme does the request work when the basic auth in provided in the header and the contents are base64 encoded?
For eg
```bash
curl -H 'Authorization: Basic <base64encoded :tokenhere>' "https://splunkindexer:8088/services/collector/event" -d '{"event":"it worked!"}'
```

**Comment by atoulme** [comment]
I think these are functionally equivalent yes.

**Comment by fatsheep9146** [comment]
@neelayu do you have interest in contributing this?

**Comment by neelayu** [comment]
Sure. But I am a little busy these days. Will take it up in a couple of weeks, if that's okay!

**Comment by fatsheep9146** [comment]
It's yours! @neelayu

**Comment by atoulme** [comment]
@fatsheep9146 can we remove the stale label on this issue please?

**Comment by atoulme** [comment]
@neelayu any progress?

**Comment by atoulme** [comment]
I'm going to unassign @neelayu and open this up to the community.

**Comment by atoulme** [comment]
Going to close this issue without implementing this as the code of the HEC exporter and receiver is complex as it is, and I'm not sure anymore this is worth the cost:
* Both Basic and Splunk realm authentications use the same HTTP header
* There is no auth by default for the receiver. This is done by the auth extensions. So it should be a generic authentication mechanism.
