### ISSUE TITLE
[receiver/aerospike] Integration test cannot run on arm systems

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#14598]
### Describe the issue you're reporting

Aerospike does not publish a docker image that is compatible with arm systems such as M1. Given that M1 is such a popular developer laptop, we really ought to have an integration test that can run on it.

**Comment by djaglowski** [comment]
@dwelch-spike, any thoughts on this?

I've noticed that there is a [related issue on the associated aerospike repo](https://github.com/aerospike/aerospike-server.docker/issues/33), but it has not been acknowledged since M1 has been in use.

**Comment by dwelch-spike** [comment]
@djaglowski we are working on arm/M1 compatibility right now, including docker images.

**Comment by kportertx** [comment]
6.2 has been released with ARM support: https://download.aerospike.com/download/server/notes.html#6.2.0.0

**Comment by djaglowski** [comment]
Thank you @kportertx!

Not sure the image is published yet, so I'll leave this open until we update the integration test.

**Comment by kportertx** [comment]
The images published by us are available:
- [Aerospike Server Community 6.2.0.0](https://hub.docker.com/layers/aerospike/aerospike-server/6.2.0.0/images/sha256-4ac019b1b3f2e4aa4138b87a607bf05158a85034cdb7ce0844083986eb11583d?context=explore)
- [Aerospike Server Enterprise 6.2.0.0](https://hub.docker.com/layers/aerospike/aerospike-server-enterprise/6.2.0.0/images/sha256-ac33275fde0e8ea53e518d866bef7fd0badfaf17a003a2810aefd5e5806c5c4a?context=explore)

The "[Docker Official Image](https://hub.docker.com/_/aerospike)" will likely appear soon, typically at most 2 weeks after we publish.

**Comment by kportertx** [comment]
The docker official images took quite a bit longer than expected, but they are now published. This issue can probably be marked as resolved.

**Comment by djaglowski** [comment]
Thanks @kportertx! I've opened #17966 to update our integration test to use the new image. I've confirmed it works on my local arm environment.
