### ISSUE TITLE
Instana exporter get invalid response when enable https

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-collector-contrib#14595]
I attached the error message for the Instana exporter. 
 
![502A3B06-2012-434C-9153-933A2D6E2953](https://user-images.githubusercontent.com/90817719/192753892-db89b1a4-af21-46c9-8073-cdf4872999a6.png)

can the latest version fix this issue?

**Comment by jpkrohling** [comment]
cc @hickeyma

**Comment by sweetxiaodai** [comment]
closed. Merge to #14602

**Comment by sweetxiaodai** [comment]
merged to #14602 and close this one
