### ISSUE TITLE
exporter/datadogexporter: reported memory usage incorrect in Kubernetes

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/opentelemetry-collector-contrib#14618]
### What happened?

The memory usage reported by Datadog is incorrect in some setups (such as Kubernetes/Docker). The reported numbers are significantly different than the original hostmetrics.

This is because of hacky configuration used with the metricstransform processor. It can be fixed by manually doing the conversion.

### Collector version

0.61.0

**Comment by mx-psi** [comment]
This was fixed by #14619
