### ISSUE TITLE
Implement CLP-like parser for logs

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#14620]
### Is your feature request related to a problem? Please describe.

We have a number of parsers for logs that help to convert unstructured logs to structured. CLP is a novel technique for parsing and compressing logs: https://www.usenix.org/system/files/osdi21-rodrigues.pdf

### Describe the solution you'd like

It would be great to have a CLP-parser in the Collector that can extract the fields according to CLP's parsing algorithms. The user-defined rules should be part of the parser's configuration.

For example given input log message
```
2020-01-02T03:04:05.006 INFO Task task_12 assigned to container: [NodeAddress:172.128.0.41, ContainerID:container_15], operation took 0.335 seconds
```

it would extract a LogRecord Body like this:
```
INFO Task \x11\x00 assigned to container: [NodeAddress:\x11\x01, ContainerID:\x11\x02], operation took \x12\x13 seconds
```
and 3 variables:
```
task_12 
172.128.0.41
container_15 
```

It would be also beneficial to augment the parsed LogRecord with an attribute that indicates CLP parsing is used so that the backends that receive it know how to interpret the Body and substitute the variable values back for displaying.

Open question: CLP uses indexed variables , not named. Should extracted variable be named so that they become LogRecord attributes? How do we specify parsing schema? 

Note: CLP also defines compression and use of dictionaries. These could be very useful as an extension to OTLP, but it is a separate topic. This issue is about the parser only.

**Comment by tigrannajaryan** [comment]
cc @djaglowski this may be interesting for you.

**Comment by djaglowski** [comment]
Very interesting. Seems promising. 

The indexing does seem potentially problematic in the context of normalizing attributes across instances of the parser. eg. the index referring to schema `task_\d+` depends on its position in each parser's config. Naming the schemas in the config would be much more consistent across instances, if managed carefully. Working with the indices of "log types" and "variables", as they call them, could be challenging too.
