### ISSUE TITLE
GoogleCloudSpannerReceiver: Fix/surpass errors when Spanner databases are not found

### ISSUE THREAD

**Issue by makrilavy** [open-telemetry/opentelemetry-collector-contrib#14624]
### Describe the issue you're reporting

We are running an automation script on jenkins that will fetch the current list of spanner database instances for the day and update the config file for the collector and upgrade the installation. Unfortunately, the table that contains the current list of spanner instances is only updated once a day, and throughout the day, a few of the instances may end up getting deleted which will not be reflected when we run our automation script. This causes the following error to come up:

Error scraping metrics {"kind": "receiver", "name": "googlecloudspanner", "pipeline": "metrics", "error": "cannot read data for data points databaseReader \"active queries summary [project_name]::[instance_name]::[database_name]\" because of an error: query \"SELECT * FROM SPANNER_SYS.ACTIVE_QUERIES_SUMMARY LIMIT @topMetricsQueryMaxRows\" failed with error: spanner: code = \"NotFound\", desc = \"Database not found: projects/[project_name]/instances/[instance_name]/databases/[database_name]\"", "scraper": "googlecloudspanner"}

This error hangs up the collector and doesn't make it move on to the next instance. It is very similar to the issue stated in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14189. We'd like a solution so that we can surpass this error if it arises and move on to the next instance. Would you be able to help us with this? Thanks!

**Comment by afarbos** [comment]
Is there any plan to fix this issue? this seems to be a big miss here.
