### ISSUE TITLE
[processor/spanmetrics] Duplicate metrics sent to prometheus when deployed as a daemonset/sidecar.

### ISSUE THREAD

**Issue by albertteoh** [open-telemetry/opentelemetry-collector-contrib#14631]
### Is your feature request related to a problem? Please describe.

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9551 defines the problem well.

Essentially, when otel collector is deployed as a daemonset per node instance or as a sidecar with spanmetrics processor, because they can potentially receive spans from the same service, but different replica, they would generate the same metric "signature". That is, with the same dimensions/labels.

If they're configured to send these metrics directly via prometheusremotewrite without any sort of federation layer to merge the metric, it seems prometheus gets quite confused (as seen in issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9551) because different counter values are being sent over time while some could also be dropped if the timestamp is not monotonically increasing (I haven't confirmed this).

Other users have also approached me about a similar problem they're facing. 

I'm also interested to know if other users of the spanmetrics processor have experienced the same problems; given the daemonset/sidecar deployment strategy should be fairly commonly used.

### Describe the solution you'd like

The spanmetrics processor is a _source_ of metrics and a simple solution to this problem is to, by default, insert a dimension/label that uniquely identifies the collector.

There are a few open questions:
- What is the right dimension name to use? Is there a recommended convention?
  - Propose following the [existing documented trace attribute naming convention](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#general-thread-attributes) for storing `enduser.id` and `thread.id`.
- How will the ID be defined?
  - Preference is to minimise the need for user intervention/configuration.
  - Therefore, by default, one possible solution is to use a randomly generated v4 UUID.
  - Allow user to override this with their own collector ID.

### Describe alternatives you've considered

Of course, the proposed solution above will mean users cannot easily differentiate one collector from another. That is, if they want to know which collector produced the metrics, given the ID would be randomly generated (not a stable ID).

In this scenario, the user would need to either override the ID themselves as mentioned in the solution above, or configure an upstream span processor to add a span/resource attribute.

However, IMO, this is something that users should _not_ be expected to do every time if they want to use the spanmetrics processor when deploying the collector as a sidecar or daemonset.

**Comment by albertteoh** [comment]
@evan-bradley I'd like to contribute to this if there are no objections to the proposal.

**Comment by srikanthccv** [comment]
Doesn't `service.instance.id` already address (or exist to address) this problem? Why introduce an additional ID?

**Comment by albertteoh** [comment]
IIUC the `service.instance.id` attribute seems to be the semantic convention used to help uniquely identify a service instance (generated by an SDK). 

If we consider a service instance's opentelemetry SDK inserts `service.instance.id` attributes into its spans say, with the value `foo`, and sends these spans to OTEL collector.
Let's say the OTEL collector is configured with the spanmetrics processor which, in turn, inserts the `service.instance.id` label into the metric, wouldn't that clash with the span's `service.instance.id`, while also preventing users from configuring this as a custom metric dimension in spanmetrics processor?
