### ISSUE TITLE
Migrate fraughtful language from Redis telemetry

### ISSUE THREAD

**Issue by hughesjj** [open-telemetry/opentelemetry-collector-contrib#14688]
### Describe the issue you're reporting

While working on getting Redis metrics in I noticed we're still using non-inclusive terminology for some of the Redis telemetry.  Redis has deprecated the use of terminology such as `slave` as of [2018](https://github.com/redis/redis/issues/5335).  I see we've been migrating such language across the project, and wanted to track the same effort for Redis.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/redisreceiver/metadata.yaml#L249

Might be cool to resurrect https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3282 seeing as how it's Apache Licensed now

**Comment by jpkrohling** [comment]
@hughesjj, would you like to submit a PR for that?

**Comment by fatsheep9146** [comment]
@hughesjj Any progress?
