### ISSUE TITLE
[receiver/rabbitmqreceiver] Integration test fails on TestRabbitmqIntegration

### ISSUE THREAD

**Issue by atingchen** [open-telemetry/opentelemetry-collector-contrib#14708]
## Description
Integration test fails on TestRabbitmqIntegration

## Expected Result
Passed the test
## Actual Result
=== RUN   TestRabbitmqIntegration
=== RUN   TestRabbitmqIntegration/Running_rabbitmq_3.9
=== PAUSE TestRabbitmqIntegration/Running_rabbitmq_3.9
=== CONT  TestRabbitmqIntegration/Running_rabbitmq_3.9
2022/10/04 16:40:10 Starting container id: 73a35bb4430c image: docker.io/testcontainers/ryuk:0.3.3
2022/10/04 16:40:10 Waiting for container id 73a35bb4430c image: docker.io/testcontainers/ryuk:0.3.3
2022/10/04 16:40:11 Container is ready id: 73a35bb4430c image: docker.io/testcontainers/ryuk:0.3.3
2022/10/04 16:40:18 Starting container id: 7bfe81c274e1 image: d4163118-50c4-4d66-bb89-cc94b8419130:d4ebb5fc-5cf9-4871-845f-fc9e0f79b31b
2022/10/04 16:40:18 Waiting for container id 7bfe81c274e1 image: d4163118-50c4-4d66-bb89-cc94b8419130:d4ebb5fc-5cf9-4871-845f-fc9e0f79b31b
2022/10/04 16:40:21 Container is ready id: 7bfe81c274e1 image: d4163118-50c4-4d66-bb89-cc94b8419130:d4ebb5fc-5cf9-4871-845f-fc9e0f79b31b
    integration_test.go:99: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/rabbitmqreceiver/integration_test.go:99
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/rabbitmqreceiver/integration_test.go:53
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 64
        	Test:       	TestRabbitmqIntegration/Running_rabbitmq_3.9
--- FAIL: TestRabbitmqIntegration (0.00s)
    --- FAIL: TestRabbitmqIntegration/Running_rabbitmq_3.9 (12.20s)

### Collector version

v0.61.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Additional context

workflow:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3183783304/jobs/5191441744
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3183620109/jobs/5191141258

**Comment by dmitryax** [comment]
Reopened as it was seen in https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3367795815/jobs/5585640601

**Comment by djaglowski** [comment]
Here again: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3384051562/jobs/5620655150#step:5:912

**Comment by djaglowski** [comment]
@cpheps, any ideas on this one?

**Comment by cpheps** [comment]
@djaglowski I don't have any ideas off the top of my head. I didn't write the integration tests so I'm not as familiar with them. I can take a deeper look at some point today.

**Comment by dmitryax** [comment]
One more https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3431416984/jobs/5719553179
