### ISSUE TITLE
Deprecated Elastic exporter in v0.57.2

### ISSUE THREAD

**Issue by art-licis** [open-telemetry/opentelemetry-collector-contrib#14731]
### Describe the issue you're reporting

I tried to upgrade OTEL Collector Contrib to version 0.57.2 because it seems it's the last version before multiple deprecated components (including Elastic APM exporter we are using) were removed. However, on startup I'm getting error:
```
2022/10/05 15:05:38 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
Error: failed to get config: cannot unmarshal the configuration: unknown exporters type "elastic" for "elastic" (valid values: [otlp clickhouse f5cloud file tanzuobservability awsxray googlecloud loadbalancing loki sumologic otlphttp awsemf dynatrace elasticsearch kafka alibabacloud_logservice humio sentry skywalking carbon mezmo opencensus prometheusremotewrite sapm datadog influxdb jaeger_thrift logzio prometheus tencentcloud_logservice logging coralogix googlecloudpubsub googlemanagedprometheus signalfx splunk_hec awscloudwatchlogs awskinesis azuremonitor jaeger zipkin])
```

Checking codebase for tag 0.57.2 it seems that it should be there:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.57.2/exporter/elasticexporter
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.57.2/versions.yaml#L38

Maybe there's some flag I'm not aware to enable deprecated components? Or it was simply not included in that release?

P.S. I'm aware about Elastic move to OTLP format, but the upgrade is still pending.

**Comment by jpkrohling** [comment]
This component was removed from the distribution on 0.57.2: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/174

Here's the manifest for the contrib distribution v0.57.2: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/v0.57.2/distributions/otelcol-contrib/manifest.yaml
