### ISSUE TITLE
Add support to attributes with array values in processors that manipulate attributes

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-collector-contrib#14782]
### Is your feature request related to a problem? Please describe.

[The spec states](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute) that attribute values can be "An array of primitive type values. The array MUST be homogeneous, i.e., it MUST NOT contain values of different types.".

The following processors manipulate attribute values:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor
* https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor
* https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor

However they don't support arrays of primitive type. 

When I try to do something like: 

```
  resource:
    attributes:
      - key: "aws.log.group.names"
        action: insert
        value: [sample-app-trace-logs]
```

I get back the following from the collector stdout:
```
Error: cannot build pipelines: failed to create "resource" processor, in pipeline "traces": error creating "resource" processor: error unsupported value type "[]interface {}"
```

### Describe the solution you'd like

I'd like that any type or processor that manipulate attributes to support arrays of primitive types.

**Comment by dmitryax** [comment]
@rapphil, do you intend to work on this issue?
