### ISSUE TITLE
Not able to send correct data to metrices in aws cloudwatch in web api signalR .net core application

### ISSUE THREAD

**Issue by rajumakade** [open-telemetry/opentelemetry-collector-contrib#14878]
### Describe the issue you're reporting

Hi,

We are able to send correct data to metrices in aws cloudwatch in web api .net core project.
When we tried same thing in web api signalR .net core application using WebSocket connection not able to send correct data.

Request you to please help on this.

**Below code snippet using for same**
this.Meter.CreateObservableCounter<double>("NoOfWebsocketConnection", () => GetCount())

Also tried with 
Counter<double> connCounter ;
this._connCounter.Add(GetCount())

Thanks

**Comment by evan-bradley** [comment]
Could you give more details about your setup? From the information in your report, it sounds like you may be experiencing an issue with the OpenTelemetry .NET SDK. If you are having trouble with the OpenTelemetry Collector, could you post your Collector configuration and any relevant logs?

**Comment by rajumakade** [comment]
Hi @evan-bradley,
Please find below more details
The otel collector configuration is 

-----------------------------------------------------------------------------
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  batch:
    timeout: 30s
    send_batch_size: 10000
exporters:
  logging:
    loglevel: info
  awsemf:
    log_group_name: "log_group_name"
    log_stream_name: "TestEvenService_23"
    region: "us-west-2"
    #endpoint: "logs.us-west-2.amazonaws.com"
    namespace: "TestEvenService"
    output_destination: "cloudwatch"
  awscloudwatchlogs:
    log_group_name: "log_group_name"
    log_stream_name: "TestEvenService_23"
    region: "us-west-2"
    #endpoint: "logs.us-west-2.amazonaws.com"
    sending_queue:
      queue_size: 50
    retry_on_failure:
      enabled: false
      initial_interval: 10ms
  file:
    path: /etc/output/logs.json

service:
  pipelines:
    metrics:
      receivers:
        - otlp
      exporters:
        - logging
        - awsemf
      processors:
        - batch 
    logs:
      receivers:
        - otlp
      exporters:
        - logging
        - awscloudwatchlogs
        - file
----------------------------------------------------------------------------------------------------

**in . net web api project** 
**Startup class**
![image](https://user-images.githubusercontent.com/88999028/199423516-c061dbff-6d99-4173-8d9a-0a4bba8bc725.png)

**in signalR hub class
Method- OnConnectedAsync**

System.Diagnostics.Metrics.Counter.Add(1)

Request you to please help us with this as we are able to send correct data to metrices in aws cloudwatch in web api .net core project.
**By default, otel sending data after every 1 min which is maintained until next counter add in cloudwatch logs**
![image](https://user-images.githubusercontent.com/88999028/199424339-4fd5a91a-0f57-4069-a939-186b474c32c6.png)


**But in signal R otel sending data after every 1 min which is resetting to zero in cloudwatch logs**
![image](https://user-images.githubusercontent.com/88999028/199424585-c54482b9-a741-4c32-9a57-48f5cad155a4.png)

**Comment by rajumakade** [comment]
Hi @evan-bradley,
Request you to please help with this issue.

**Comment by evan-bradley** [comment]
I see you're using the logging exporter in your metrics and logs pipelines, can you set the log level to `debug` and see if the same issue occurs in the Collector's logs?

**Comment by rajumakade** [comment]
Hi @evan-bradley ,
I have checked by setting log level to debug but not able to locate cause of issue . it will be helpful if get any help.
Please note tried with  AggregationTemporality: Cumulative as well.
Log as follows
<img width="766" alt="image" src="https://user-images.githubusercontent.com/88999028/200309562-9d67eebb-291c-4912-b1da-1c55b1878b30.png">

**Comment by evan-bradley** [comment]
Unfortunately the screenshot only includes one data point, so I can't tell for sure whether the value is being reset in the logging exporter output. If you allow the service to emit multiple data points for the metric, do you see the value reset in the logs? If so, then it's likely that you are having an issue with your instrumentation code and not with the Collector.
