### ISSUE TITLE
dependabot PRs (from github action) don't trigger CI

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#14884]
### Describe the issue you're reporting

There's a github action that approvers/maintainers use to trigger a summary PR of all the dependabot recommendations. However, when a new PR is created by this action, the github workflows aren't queued until someone closes and reopens the PR.

This is a mild annoyance, but it would be great to fix. Unrelated to this, it would be great to automate the generation of this summary PR.

**Comment by fatsheep9146** [comment]
Does the problem still exist? @codeboten

**Comment by codeboten** [comment]
This has been fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18008
