### ISSUE TITLE
OpenTelemetry configuration with Localstack (AwsCloudwatch)

### ISSUE THREAD

**Issue by hpaikrao** [open-telemetry/opentelemetry-collector-contrib#14896]
### Describe the issue you're reporting

Hi Team,

Does opentelemetry supports to log into Localstack AwsCloudwatch service?
As we would like to push logs into Localstack AwsCloudwatch service though OpenTelemetry, I didn't get any reference for the same.

We are able to push logs into AwsCloudwatch infrastructure but not on Localstack.

Please provide any reference/suggestion for the same. Appricated!!!

Thanks;
Harish Paikrao

**Comment by Aneurysm9** [comment]
We are not presently supporting logs as a signal via ADOT, and LocalStack is not an AWS product or service that we support.  I will bring this to the team to see if anyone has experience in the area and can help, but can make no guarantees.

**Comment by jpkrohling** [comment]
I'm closing this, feel free if further clarification is needed.
