### ISSUE TITLE
Update github.com/getsentry/sentry-go from 0.13.0 to 0.14.0 causes issues

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#14903]
The dependency cannot be upgraded automatically, see https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3235788640

<img width="699" alt="Screen Shot 2022-10-12 at 9 43 57 AM" src="https://user-images.githubusercontent.com/223565/195401067-cd3a33ae-ae43-45f2-84c5-6e7df791919a.png">

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14796#issuecomment-1276462411_

**Comment by AbhiPrasad** [comment]
This is because of https://github.com/getsentry/sentry-go/pull/444 and https://github.com/getsentry/sentry-go/issues/479#issuecomment-1269475954. Will fix and bump!
