### ISSUE TITLE
hostmetrics: Remove slab reclaimable from cache

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-collector-contrib#14909]
### Is your feature request related to a problem? Please describe.

Currently the library used by the hostmetrics receiver to report cached memory [includes slab reclaimable memory in its calculation](https://github.com/shirou/gopsutil/blob/0969c9436bc0d9bf190face9c4a3c4a430b98523/mem/mem_linux.go#L303) despite this not being the literal value provided by /proc/meminfo (introduced in https://github.com/shirou/gopsutil/pull/617). This can be unexpected as the receiver's memory scraper also provides usage and utilization values for the slab reclaimable value itself and the fact that this happens isn't advertised in this project.

### Describe the solution you'd like

Calculate the linux cached memory by subtracting the advertised slab reclaimable memory so the reported values reflect what's provided by procfs.

### Describe alternatives you've considered

Leaving this alone is viable, but I think at minimum the aggregate value should be advertised in the scraper readme.

### Additional context

I've not done a comprehensive audit of different offerings but anecdotally sysstat/sar and the legacy sfx smart agent don't conflate the two values.

**Comment by fatsheep9146** [comment]
@rmfitzpatrick do you have interest in contributing this?

**Comment by rmfitzpatrick** [comment]
@fatsheep9146 yes I'd be happy to open a PR w/ the proposed change.

**Comment by dmitryax** [comment]
There is an ongoing effort to move slab states to another metric: 
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417 
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19149

@rmfitzpatrick feel free to weigh in

I believe we can keep the cached state as is if we remove the slab states

**Comment by rogercoll** [comment]
I think this solution will also need to modify the `used` value provided by Gosputils as it is made by `cached` state: https://github.com/shirou/gopsutil/blob/0969c9436bc0d9bf190face9c4a3c4a430b98523/mem/mem_linux.go#L313

```Go
    // Total memory removing slab from catched
    memStats, _ := mem.VirtualMemory()
    newCached := memStats.Cached - memStats.SReclaimable
    newUsed := memStats.Total - memStats.Free - memStats.Buffers - newCached
    fmt.Println(memStats.Total == newUsed+newCached+memStats.Free+memStats.Buffers)
```
