### ISSUE TITLE
Guide to create custom contrib component

### ISSUE THREAD

**Issue by lesovsky** [open-telemetry/opentelemetry-collector-contrib#14919]
Is there any guide to create custom receiver/processor/exporter and implement it into collector?

As I know there is possible to build custom distribution, based on code generated by `ocb` tool and i saw it's possible to import custom components (like receivers, etc.). But, component's code should be written from scratch? Or maybe there is template code exists or such code could be generated?

**Comment by jessberg** [comment]
With the disclaimer that I am not one of the official OpenTelemetry collector people, I had to create my own custom exporters and receivers, and I found this medium article really helpful:

https://medium.com/opentelemetry/extending-the-opentelemetry-collector-with-your-own-components-64c10cf675db

I also have an example of how I built exporters and receivers here:
https://github.com/dyn-tracing/microservices_env/tree/throughput_experiments

The folder loadbalancerhttp is a receiver, and custom_opentelemetry_collector is an exporter. I build them into the existing opentelmetry collector through the Dockerfile in that repository, and then I can use that image as my custom collector. The Dockerfile works by downloading that ocb tool you mentioned.

Each component works by having a certain template, and you can figure out what exactly that template looks like by browsing around the receiver, processsor, exporter folders in this repo.

**Comment by evan-bradley** [comment]
Related:
- https://github.com/open-telemetry/opentelemetry-collector/issues/5675
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12965

**Comment by lesovsky** [comment]
Thanks for answers, these could help

**Comment by Chinwendu20** [comment]
Adding to this conversation. Component generation is one of the outreachy projects by open telemetry this year.
