### ISSUE TITLE
[pkg/ottl] Set method should allow dynamically setting map values to attributes

### ISSUE THREAD

**Issue by rupeshnemade** [open-telemetry/opentelemetry-collector-contrib#14946]
### Is your feature request related to a problem? Please describe.

While using transform processor, we tried setting set kubernetes labels to a single attribute 'labels' in a body as below.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/31383439/195792617-5d53d391-285c-40cb-aca4-07888e379e2c.png">

But Set method doesn't iterate through the map of values & instead needs all keys in array to be explicitly mentioned like below-
     `set(attributes["kubernetes.labels"], resource.attributes["pod_labels_app"])`

Kubernetes labels is something dynamic things & we can't explicitly mention label name in OTEL processor rules. 

### Describe the solution you'd like

Set method in [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/ottlfuncs/func_set.go) should allow iterate through the map & fetch all values so that we can perform something like this-

`      set(attributes["kubernetes.labels"], resource.attributes["pod_labels_*"])`

**Comment by TylerHelmuth** [comment]
I can think of two ways to handle this situation:

1. Update all contexts used by the transform processor to understand that wildcard (*) in a key means "all fields in a map that match that key".
2. Create a new Factory Function that knows how to take a map and a string pattern and returns a map that contains all the fields from the input map that match the pattern.  It would behave similarly to `replace_all_patterns`.  

I would opt for the second because I like the flexibility that Factory Functions provide.  I prefer putting business logic in the function vs the contexts.  

@bogdandrutu @kentquirk @evan-bradley what do you think?

**Comment by evan-bradley** [comment]
I agree, I think a function would be better for this sort of operation. In addition to keeping business logic out of the contexts I think it also provides a good pattern for doing other types of matching (regex, filtering, etc.), and makes it more explicit what is going on.

**Comment by odubajDT** [comment]
Is this functionality still required? If yes, I would like to have a look

**Comment by TylerHelmuth** [comment]
@odubajDT some solution to make dynamic interactions in OTTL is still desired. I havent spent much time on this problem so I'm open to suggestions. I do know I don't want to change how set works, so the solution should be something else.

**Comment by odubajDT** [comment]
One of the solutions that comes into my mind is creating a separate `Compile(input, pattern)` function which will parse the input object and return the same object type but only with values/keys matching the pattern. Therefore setting up map should be possible like this

```
set(attributes["kubernetes.labels"], Compile(resource.attributes,"pod_labels_*"))
```

where `resource.attributes` will look like the following:

```
{
    "pod_labels_cpu": "cpu_label"
    "pod_labels_memory": "memory_label"
    "random_label":"random"
}
```

And the resulting `attributes["kubernetes.labels"]` will have the following content:

{
    "pod_labels_cpu": "cpu_label"
    "pod_labels_memory": "memory_label"
}
```

WDYT @evan-bradley @TylerHelmuth ?

Thanks for the opinions!

Just and additional though here, when implementing this function, would it makes sense to actually also implement a `Flatten(input, delimiter)` function which will be able to convert a map to a string with specified delimiter. Just thinking about the possible enhancements, since I recently ran into a use-case, where `Flatten()` function might be very useful. If you would agree, I would create a separate issue for this.

**Comment by odubajDT** [comment]
Created a draft implementation of the potential solution, will appreciate your opinions!

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35553

@evan-bradley @TylerHelmuth

**Comment by evan-bradley** [comment]
Sorry for the delay in taking a look at this.

We have [keep_matching_keys](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#keep_matching_keys) now, would it be possible to do something like the following to solve this case?

```
- set(cache["attrs"], resource.attributes)
- keep_matching_keys(cache["attrs"], "pod_labels_.*")
- set(attributes["kubernetes.labels"], cache["attrs"])
```

I think it should be functionally equivalent to having a single Converter for both copying and modifying the map, and shouldn't be much less performant.

>Just and additional though here, when implementing this function, would it makes sense to actually also implement a Flatten(input, delimiter) function which will be able to convert a map to a string with specified delimiter. 

I think we should have this with the [flatten](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#flatten) Editor. Does that match what you have in mind?

**Comment by odubajDT** [comment]
> Sorry for the delay in taking a look at this.
> 
> We have [keep_matching_keys](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#keep_matching_keys) now, would it be possible to do something like the following to solve this case?
> 
> ```
> - set(cache["attrs"], resource.attributes)
> - keep_matching_keys(cache["attrs"], "pod_labels_.*")
> - set(attributes["kubernetes.labels"], cache["attrs"])
> ```
> 
> I think it should be functionally equivalent to having a single Converter for both copying and modifying the map, and shouldn't be much less performant.

That's probably true, do you think we should close the issue and the PR?

**Comment by TylerHelmuth** [comment]
@evan-bradley's solution is acceptable for now.  Let's not close this issue tho until that example solution for this scenario is documented in the transformprocessor's readme.  This is a common scenario but that solution isn't easy to think up unless you know OTTL well.

**Comment by odubajDT** [comment]
Opened an issue to document the example configuration https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35893

@evan-bradley @TylerHelmuth
