### ISSUE TITLE
Zipkin exporter and collector do not agree on wire representation of status codes

### ISSUE THREAD

**Issue by mterwill** [open-telemetry/opentelemetry-collector-contrib#14965]
### Description
The Zipkin exporter and collector do not agree on wire representation of status codes. And neither of which are in line with the spec. (See https://github.com/open-telemetry/opentelemetry-go/issues/3287)

The Zipkin exporter serializes status codes as `Unset`, `Error`, and `Ok`:

https://github.com/open-telemetry/opentelemetry-go/blob/5568a3072367bb8ac4d2d9e759e7deb5a975b9f5/exporters/zipkin/model.go#L211-L213

https://github.com/open-telemetry/opentelemetry-go/blob/d616df61f5d163589228c5ff3be4aa5415f5a884/codes/codes.go#L38-L42

However, the collector expects `STATUS_CODE_UNSET`, `STATUS_CODE_OK`, or `STATUS_CODE_ERROR`, see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/54c0a2e13f6d2e168804212d288cb808f179683e/pkg/translator/zipkin/zipkinv2/to_translator.go#L160).

### Environment
opentelemetry-go v1.11.0
opentelemetry-collector-contrib v0.62.0

### Steps To Reproduce
Using Grafana Tempo's [local example](https://github.com/grafana/tempo/tree/main/example/docker-compose/local):

```go
package main

import (
	"context"
	"log"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/exporters/zipkin"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

func main() {
	ctx := context.Background()

	exporter, err := zipkin.New("")
	if err != nil {
		log.Fatalf("creating exporter: %s", err)
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithSampler(sdktrace.AlwaysSample()),
		sdktrace.WithBatcher(exporter),
	)
	defer tp.Shutdown(ctx)
	otel.SetTracerProvider(tp)

	_, span := otel.Tracer("foo").Start(ctx, "foo")
	log.Printf("trace ID: %s", span.SpanContext().TraceID())
	span.SetStatus(codes.Error, "something went wrong")
	span.End()
}
```

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5882053/195914066-0f296782-5a2f-4c39-a0c7-2fe4770c64ba.png">

### Expected behavior
Status is correctly passed between exporter and collector.

### Collector version

v0.62.0

**Comment by jpkrohling** [comment]
We don't seem to have a Zipkin code owner, it's unlikely that a maintainer is going to work on this. If a PR is sent, tag me and I'll gladly review it.

**Comment by jpkrohling** [comment]
@jonatan-ivanov, I think you expressed interest in Zipkin in the past. Would you be interested in taking a look at this one?

**Comment by jonatan-ivanov** [comment]
@jpkrohling Thank you for thinking of me but now and in the near future I don't think I will have time to do this.
