### ISSUE TITLE
ECS resource detection processor - add tags

### ISSUE THREAD

**Issue by mattk-ce** [open-telemetry/opentelemetry-collector-contrib#14960]
### Is your feature request related to a problem? Please describe.

There is a significant disparity between the EC2 resource detection processor and ECS - EC2 supports tag metadata, ECS does not.  When creating Fargate ECS tasks, this means you're left with replicating tags as environment variables for label extraction.

### Describe the solution you'd like

It could be as simple as modifying the [TaskMetadataPath](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4266fd11e9664210eb33c21a802c029d55e2f08d/internal/aws/ecsutil/endpoints/metadata.go#L28) to be `/taskWithTags`.  Or, more likely, make it somehow configurable?

### Describe alternatives you've considered

Replicate the necessary tags as environment variables for label extraction via the env resource detection processor.

**Comment by mattk-ce** [comment]
Still desperately needed.

**Comment by mcaxtrzen** [comment]
That would be very convenient
