### ISSUE TITLE
Transform processor should allow JSON structure in log body

### ISSUE THREAD

**Issue by rupeshnemade** [open-telemetry/opentelemetry-collector-contrib#14977]
### Is your feature request related to a problem? Please describe.

While using Transform processor to move resource attribute at record level so that custom values can be added in logs body, the processor doesn't allows setting values under JSON object under single key.
Due to this the same key (kubernetes.<>) needs to be repeated with every field which in turn increase log size.

<img width="239" alt="image" src="https://user-images.githubusercontent.com/31383439/196196941-1232f4a3-94b8-4f47-bfe0-c251412fbb27.png">

### Describe the solution you'd like

The processor should allow setting values for common JSON object key-

<img width="215" alt="image" src="https://user-images.githubusercontent.com/31383439/196197279-a83af49b-32f9-417e-a934-c5300af3ea52.png">

**Comment by evan-bradley** [comment]
Related issue on reading from log bodies: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14938. There are also some thoughts on a comprehensive approach to log processing in the OTTL in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9410.

cc @bogdandrutu @TylerHelmuth @kentquirk
