### ISSUE TITLE
Can't run the testbed

### ISSUE THREAD

**Issue by yutingcaiyt** [open-telemetry/opentelemetry-collector-contrib#14975]
## Description
After I download the source code, I try the way described in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/testbed to run the test case, however, it shows me the error:
`yuting@yutingdeMacBook-Pro testbed % TESTS_DIR=./tests ./runtests.sh

=== RUN   TestIdleMode
2022/10/17 19:35:59 Starting Agent (/Users/yuting/Desktop/project/opentelemetry-collector-contrib/bin/otelcontribcol_testbed_darwin_amd64)
2022/10/17 19:35:59 Writing Agent log to /Users/yuting/Desktop/project/opentelemetry-collector-contrib/testbed/tests/results/TestIdleMode/agent.log
2022/10/17 19:35:59 cannot start executable at /Users/yuting/Desktop/project/opentelemetry-collector-contrib/bin/otelcontribcol_testbed_darwin_amd64: fork/exec /Users/yuting/Desktop/project/opentelemetry-collector-contrib/bin/otelcontribcol_testbed_darwin_amd64: no such file or directory
    test_case.go:303: cannot start executable at /Users/yuting/Desktop/project/opentelemetry-collector-contrib/bin/otelcontribcol_testbed_darwin_amd64: fork/exec /Users/yuting/Desktop/project/opentelemetry-collector-contrib/bin/otelcontribcol_testbed_darwin_amd64: no such file or directory
2022/10/17 19:35:59 Stopped generator. Sent:         0 items
--- FAIL: TestIdleMode (0.00s)
`
## Steps to Reproduce
go version: 1.18.3 
### Collector version

v0.62.0

## Environment
OS: (e.g., "macOS")
Compiler(if manually compiled): (e.g., "1.18.3")

**Comment by evan-bradley** [comment]
It looks like the docs are outdated. From what I can tell, the simplest way to run all tests locally is to run the following from the repository root:

```bash
make e2e-test
```

I can update the docs on this.

**Comment by yutingcaiyt** [comment]
Thanks a lot, I hope these docs can be updated as soon as possible 0.0
