### ISSUE TITLE
Add Sumo Logic exporter

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#1498]
**Is your feature request related to a problem? Please describe.**

I added this issue to track progress of initial implementation of the [Sumo Logic](https://www.sumologic.com/) exporter:

List of planned PRs:
 - init PR (configuration, README.md) #1565
 - add filtering structure to manage and extract metadata from OTC attributes #1681
 - add sender #1693
 - add compression to the sender #1747
 - evaluate source headers #1756 
 - enable logs #1859 
 - add support for prometheus format #1890 
 - add support for metrics #2117 
 - add support for carbon2 metrics #2523 #2543 #2562 
 - add support for graphite metrics #2695

In case of any change of the planned implementation, I will update list of PRs

**Comment by mx-psi** [comment]
@pmm-sumo @sumo-drosiek can this be closed?

**Comment by pmm-sumo** [comment]
Oh, for sure! Thank you for bringing this up @mx-psi
