### ISSUE TITLE
tailsamplingprocessor: Sampling decision from OnDroppedSpans() is not honoured 

### ISSUE THREAD

**Issue by annanay25** [open-telemetry/opentelemetry-collector-contrib#1500]
In the tail sampling processor, the following lines of code delete the trace from memory without honouring the sampling decision from `OnDroppedSpans()` for the given policies.

https://github.com/open-telemetry/opentelemetry-collector/blob/fe3782c76de259c34c381e7e2d0a732c014a87fc/processor/samplingprocessor/tailsamplingprocessor/processor.go#L341-L346

We could either - 
- Modify the `OnDroppedSpans()` signature to never return a sampling decision (force the drop of an old trace). Currently the implementation nullifies the `always_sample` policy.
- Modify the `dropTrace()` / `ConsumeTraceData()` method to incorporate for custom use cases where the user might want to stop trace ingestion if the queue is full, instead of dropping old traces which are already batched for processing.

**Comment by jpkrohling** [comment]
@annanay25 , I think you are one of the consumers of this processor. What's your preference?
@chris-smith-zocdoc , are you using this processor as well?

**Comment by annanay25** [comment]
Will be a consumer once horizontally scalable tail sampling processor is merged :) I would prefer option 2 because it saves processing cycles.

**Comment by chris-smith-zocdoc** [comment]
Yes I'm using the processor. I think either 
- respect the sampling decision in dropTrace
Or 
- modify the method signature to not return a sampling decision

would be fine. Changing the processor to block/apply back pressure is a much larger change that requires a separate design discussion imo
