### ISSUE TITLE
Azure Application Insights Metrics Exporter

### ISSUE THREAD

**Issue by jgarces21** [open-telemetry/opentelemetry-collector-contrib#1507]
**Is your feature request related to a problem? Please describe.**
At the moment I can not export the metrics received by otel collector to Azure Application Insights.

**Describe the solution you'd like**
There should be an exporter that can send the metrics related info to Azure Application Insights.

**Describe alternatives you've considered**
None

**Additional context**
Traces are being exported successfully to Azure Application Insights

**Comment by fswane** [comment]
Hi

Was this feature implemented and is it working now?

Thanks
Regards
Francois
