### ISSUE TITLE
[prometheusreceiver] `honor_labels: true` doesn't work properly

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#15239]
## Description

`honor_labels: true` does not work properly

case 1. given metrics 
```
# HELP foo
# TYPE foo gauge
foo{instance="",job="a"} 1
```

got error 
```
2022-10-18T13:42:19.300+0800    debug   scrape/scrape.go:1559   Unexpected error        {"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_pool": "prometheus", "target": "http://127.0.0.1:8000/metrics.txt", "series": "foo{instance=\"\",job=\"a\"}", "error": "job or instance cannot be found from labels"}
```

case 2. given metrics
```
# HELP bar
# TYPE bar gauge
bar 1
# HELP foo
# TYPE foo gauge
foo{instance="",job="a"} 1
```

got metrics

```
bar  {instance: 127.0.0.1:8000, job: prometheus}
foo  {instance: 127.0.0.1:8000, job: prometheus}
```

## Steps to Reproduce
provide metrics and start otel

## Expected Result
case 1
```
foo{instance="", job="prometheus"} 1 
```

case 2
```
bar{instance="127.0.0.1:8000", job="prometheus"} 1
foo{instance="", job="prometheus"} 1 

```

## Actual Result
see above

### Collector version

latest master branch

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by Aneurysm9** [comment]
I suspect this is related to the conversion of `job` and `instance` into resource attributes.  It looks like only a single resource will ever be created but we probably need one per `job`/`instance` pair.
