### ISSUE TITLE
Create a command line tool to generate configschema yaml files

### ISSUE THREAD

**Issue by pmcollins** [open-telemetry/opentelemetry-collector-contrib#15231]
### Is your feature request related to a problem? Please describe.

Documentation generators and tools could benefit from access to the data generated by the [configschema API](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/configschema). If this data were written as YAML files to each component directory, it would be relatively straightforward for writers of tools and documentation to access them.

Also, the zip archive mode of this command will be useful for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13991 so that that tool can live in a separate repo and have access to the data it needs to run.

### Describe the solution you'd like

A simple CLI tool to generate, based on CLI flags, either config schema YAML files for each component, or a single zip archive containing all of the YAML files.

### Additional context

Additional details provided in the readme of a PR to be opened shortly.

**Comment by abeach-nr** [comment]
another potential feature for this could be the metrics for each component that are emitted to the prometheus metrics for the collector. It would be useful to have this information in the metadata.yaml files.

**Comment by dmitryax** [comment]
> another potential feature for this could be the metrics for each component that are emitted to the prometheus metrics for the collector. It would be useful to have this information in the metadata.yaml files.

This seems like a good idea even if most of the component expose the same metrics. In order to achieve that, we need to parse the code and generate that file automatically, but this probably should wait until we switch from OpenCensus instrumentation. And this a completely different topic, @abeach-nr if you want to continue the discussion let's create an a separate issue.

**Comment by fatsheep9146** [comment]
This issue is solved by #15233, right? @dmitryax

**Comment by atoulme** [comment]
Closed as fixed per #15233, please reopen if more work is needed.
