### ISSUE TITLE
azuremonitorexporter not working with Java app logging

### ISSUE THREAD

**Issue by jay-annapureddy** [open-telemetry/opentelemetry-collector-contrib#15275]
### Describe the issue you're reporting

Hi,

**Issue**
I found that this exporter is not working with Java app logging and log4j, could you please help here, is there any way I can send Java app logs to Azure Monitoring ?

**Requirement:** I am in a need of sending emitted telemetry data from a Java app to Azure monitor.

**Details:**
I am having a Java app instrumented with otel java agent and then I am using the otelcol-contrib collector azuremonitorexporter to send data to azure monitor

https://github.com/open-telemetry/opentelemetry-java-instrumentation

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/exporter/azuremonitorexporter/v0.60.0/exporter/azuremonitorexporter

**Note**
I already explored azure application insights java agent but looking for vendor agnostic open telemetry instrumentation and sending data to backend

**Error**
Oct 18 20:30:03 depfVM1 otelcol-contrib[3036144]: 2022-10-18T20:30:03.043Z        warn        azuremonitorexporter@v0.60.0/**log_to_envelope.go:79**        **Unknown Severity Level**        {"kind": "exporter", "data_type": "logs", "name": "azuremonitor", "Severity Level": "**INFO**>

Attached files are file exporter output and otelcol-contrib configuration

[file-ouput.txt](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/9815241/file-ouput.txt)
[config.txt](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/9815242/config.txt)

**Comment by pcwiese** [comment]
Looks like there is a severity map that is used to map the incoming log record to an appinsights/azure monitor level
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/81935cf01dfe8e54045a32ee6314a81296421ce9/exporter/azuremonitorexporter/log_to_envelope.go#L26

so, in your case INFO must be Information for the current code to map it properly I guess.

@eedorenko  added this feature. Is this a valid mapping? Something is obviously off here

**Comment by eedorenko** [comment]
I will look into that

**Comment by jay-annapureddy** [comment]
thank you @eedorenko, when will be the new release ?

https://github.com/open-telemetry/opentelemetry-collector-releases/releases

**Comment by mx-psi** [comment]
Releases happen every other Wednesday https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#release-schedule, there will be one today.
