### ISSUE TITLE
[prometheusremotewrite] invalid temporality and type combination when remote write to thanos backend

### ISSUE THREAD

**Issue by Dongqi-Guo** [open-telemetry/opentelemetry-collector-contrib#15281]
## Description
I tried to use promethrus remote write to thanos backend and then display metrics on Grafana. I found there are many errors in otel collector log like "Permanent error: invalid temporality and type combination", In result, thanos lacks many metrics used in Grafana dashboard, any idea or solution about this?

## Steps to Reproduce
1. fluentbit node_metrics output
2. prometheus remote write exporter
3. thanos as the backend

### Collector version

0.61.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
2022-10-19T11:27:07.375+0800    error   exporterhelper/queued_retry.go:395      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: invalid temporality and type combination;
```

**Comment by krupyansky** [comment]
The problem is reproduced also with VictoriaMetrics as the backend

**Comment by krupyansky** [comment]
Clarification

The error occurs because https://github.com/open-telemetry/opentelemetry-go sends metrics that have 0 DataPoints

**Comment by Aneurysm9** [comment]
> Clarification
> 
> The error occurs because https://github.com/open-telemetry/opentelemetry-go sends metrics that have 0 DataPoints

Is there an existing issue on the OTel-Go repo that can be linked here?  If not, can you create one with steps to reproduce?

**Comment by krupyansky** [comment]
Exactly

I make issue for https://github.com/open-telemetry/opentelemetry-go

https://github.com/open-telemetry/opentelemetry-go/issues/3394

**Comment by krupyansky** [comment]
@montag do you use open-telemetry library https://github.com/open-telemetry/opentelemetry-go?

Try update version to latest
https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.11.2

**Comment by montag** [comment]
Thanks, @krupyansky. I'm using the otel collector helm chart via terraform.

**Comment by krupyansky** [comment]
@montag do you send metrics from your application to otel collectore via https://github.com/open-telemetry/opentelemetry-go?

**Comment by montag** [comment]
@krupyansky I'm using the python open-telemetry instrumentation libs to send to the otel collector (otlp receiver), which then uses the prometheusremotewrite exporter to push to prom. I see the above error every few minutes.

**Comment by krupyansky** [comment]
@montag try to write issue to the python open-telemetry instrumentation libs like my issue https://github.com/open-telemetry/opentelemetry-go/issues/3394

Most likely the error occurs in your case because the python open-telemetry sends metrics that have 0 DataPoints

**Comment by montag** [comment]
@krupyansky Any idea how I might verify that?

**Comment by edawader** [comment]
In same boat as @montag - No idea how we could be sending metrics with 0 Datapoints.

**Comment by GorodentsevD** [comment]
Hi! Could you please clarify, do we have some showstoppers to upgrade `opentelemetry-go` version with the fix? Got the same bug on the` 0.74.0` version of `opentelemetry-contrib`. And if i am correct, it seems that the collector is using `v1.0.0-rc8 opentelemetry-go` https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheusremotewrite/go.mod#L11

**Comment by Aneurysm9** [comment]
> Hi! Could you please clarify, do we have some showstoppers to upgrade `opentelemetry-go` version with the fix? Got the same bug on the `0.74.0` version of `opentelemetry-contrib`. And if i am correct, it seems that the collector is using `v1.0.0-rc8 opentelemetry-go` https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheusremotewrite/go.mod#L11. And version with the fix starts from `v1.11.2`

That dependency is on the `pdata` module from the collector core repository, not on the OTel Go SDK.  The issue here is with data produced by an application using the OTel Go SDK and not any use of the SDK within the collector framework or components.

**Comment by GorodentsevD** [comment]
Thank you for the answer! Sorry, misunderstand the discussion, now i get it. I have the same issue with [Kong statsd plugin](https://github.com/Kong/kong/tree/master/kong/plugins/statsd)

**Comment by eugene-chernyshenko** [comment]
I have the same issue with opentelemetry-collector-contrib 0.81.0

**Comment by xsevy** [comment]
Having similar error. Here's my config
```
opentelemetry-collector  | 2023-08-15T07:17:46.708Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "resource metrics": 1, "metrics": 2, "data points": 2}
opentelemetry-collector  | 2023-08-15T07:17:46.710Z	info	ResourceMetrics #0
opentelemetry-collector  | Resource SchemaURL:
opentelemetry-collector  | Resource attributes:
opentelemetry-collector  |      -> service.name: Str(http-influx-translation-service)
opentelemetry-collector  | ScopeMetrics #0
opentelemetry-collector  | ScopeMetrics SchemaURL:
opentelemetry-collector  | InstrumentationScope opentelemetry.instrumentation.fastapi 0.39b0
opentelemetry-collector  | Metric #0
opentelemetry-collector  | Descriptor:
opentelemetry-collector  |      -> Name: http.server.active_requests
opentelemetry-collector  |      -> Description: measures the number of concurrent HTTP requests that are currently in-flight
opentelemetry-collector  |      -> Unit: requests
opentelemetry-collector  |      -> DataType: Sum
opentelemetry-collector  |      -> IsMonotonic: false
opentelemetry-collector  |      -> AggregationTemporality: Cumulative
opentelemetry-collector  | NumberDataPoints #0
opentelemetry-collector  | Data point attributes:
opentelemetry-collector  |      -> http.method: Str(GET)
opentelemetry-collector  |      -> http.flavor: Str(1.1)
opentelemetry-collector  |      -> http.scheme: Str(http)
opentelemetry-collector  |      -> http.host: Str(172.18.0.2:8000)
opentelemetry-collector  |      -> http.server_name: Str(localhost:8000)
opentelemetry-collector  | StartTimestamp: 2023-08-15 06:37:48.46090959 +0000 UTC
opentelemetry-collector  | Timestamp: 2023-08-15 07:17:46.680389214 +0000 UTC
opentelemetry-collector  | Value: 0
opentelemetry-collector  | NumberDataPoints #1
opentelemetry-collector  | Data point attributes:
opentelemetry-collector  |      -> http.method: Str(POST)
opentelemetry-collector  |      -> http.flavor: Str(1.1)
opentelemetry-collector  |      -> http.scheme: Str(http)
opentelemetry-collector  |      -> http.host: Str(172.18.0.2:8000)
opentelemetry-collector  |      -> http.server_name: Str(127.0.0.1:8000)
opentelemetry-collector  | StartTimestamp: 2023-08-15 06:37:48.46090959 +0000 UTC
opentelemetry-collector  | Timestamp: 2023-08-15 07:17:46.680389214 +0000 UTC
opentelemetry-collector  | Value: 0
opentelemetry-collector  | Metric #1
opentelemetry-collector  | Descriptor:
opentelemetry-collector  |      -> Name: http.server.duration
opentelemetry-collector  |      -> Description: measures the duration of the inbound HTTP request
opentelemetry-collector  |      -> Unit: ms
opentelemetry-collector  |      -> DataType: Empty
opentelemetry-collector  | 	{"kind": "exporter", "data_type": "metrics", "name": "logging"}
opentelemetry-collector  | 2023-08-15T07:17:46.799Z	error	exporterhelper/queued_retry.go:391	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "metrics", "name": "otlp/data-prepper", "error": "Permanent error: rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type \"text/plain; charset=utf-8\"", "dropped_items": 2}
opentelemetry-collector  | go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
opentelemetry-collector  | 	go.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/queued_retry.go:391
opentelemetry-collector  | go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
opentelemetry-collector  | 	go.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/metrics.go:125
opentelemetry-collector  | go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
opentelemetry-collector  | 	go.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/queued_retry.go:195
opentelemetry-collector  | go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
opentelemetry-collector  | 	go.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/internal/bounded_memory_queue.go:47
```

here's my config
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  logging:
    loglevel: debug
  otlp/data-prepper:
    endpoint: ${dataprepper_endpoint}:${dataprepper_otel_trace_source_port}
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters:
        - logging
        - otlp/data-prepper
    metrics:
      receivers: [otlp]
      exporters:
        - logging
        - otlp/data-prepper
```

traces going through without any issue

**Comment by ElementalWarrior** [comment]
We were experiencing this for the python metrics instrumentation.

You can resolve it with a filter processor:

```
processors:
  filter/empty_http_server_duration:
    error_mode: ignore
    metrics:
      metric:
          - 'name == "http.server.duration" and type != METRIC_DATA_TYPE_HISTOGRAM'
          - 'name == "http.client.duration" and type != METRIC_DATA_TYPE_HISTOGRAM'
```

**Comment by francescopotenziani** [comment]
Any updates? I've the same issue of @montag: I'm using:

- otel/opentelemetry-collector-contrib:0.67.0
- "@opentelemetry/sdk-node": "0.33.0"

**Comment by AlexAkulov** [comment]
I still have the issue with `opentelemetry-collector-contrib:0.115.1` and `victoria-metrics:v1.101.0`

**Comment by AlexAkulov** [comment]
I found a solution
https://github.com/open-telemetry/opentelemetry-demo/issues/1432#issuecomment-2009553040

**Comment by ringerc** [comment]
A colleague found that the sample request from https://github.com/open-telemetry/opentelemetry-proto/blob/v1.5.0/examples/README.md uses delta, so it won't be accepted by Thanos. But due to a bug in the node otel sdk the docs there (https://open-telemetry.github.io/opentelemetry-js/enums/_opentelemetry_sdk_metrics.AggregationTemporality.html#CUMULATIVE) give incorrect enumeration values, making it look like `"aggregationTemporality": 1,` means `CUMULATIVE` when in fact it means `DELTA`.
