### ISSUE TITLE
awsxrayexporter can send its telemetry data via xray:PutTelemetryRecords

### ISSUE THREAD

**Issue by dennisyuan98** [open-telemetry/opentelemetry-collector-contrib#1534]
As xray service team, we'd like to collect metrics from client side to understand what version of collector the customer is using and the type of errors the customer has observed using xray.  AWS X-Ray has an API [PutTelemetryRecords](https://docs.aws.amazon.com/xray/latest/api/API_PutTelemetryRecords.html) can be used to collect the error metrics; the version info can be built into the user agent.   Alternatively, we can use the user agent in [PutTraceSegments](https://docs.aws.amazon.com/xray/latest/api/API_PutTraceSegments.html) to send similar information to the back end.   User should have an option to disable that feature if he doesn't want to share that information.

**Comment by willarmiros** [comment]
Hi @andrewhsu and other maintainers, it seems several valid feature requests for the X-ray exporter were recently marked stale, can they be exempted?

**Comment by jefchien** [comment]
Done as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19415
