### ISSUE TITLE
[exporter/loki] add support for logfmt

### ISSUE THREAD

**Issue by domasx2** [open-telemetry/opentelemetry-collector-contrib#15351]
### Is your feature request related to a problem? Please describe.

I have a use case for sending logfmt-formatted log records through the otelcol to Loki. But loki exporter encodes them in JSON, ending up with `{ "Body": "{{message}}" }`. This requires workarounds down the line to unwrap the JSON.
It would be great to have direct logfmt support for the Loki exporter.

### Describe the solution you'd like

Add a `loki.format` attribute hint, that, if provided with value `logfmt`, will cause exporter to format logs using logfmt instead of JSON.

**Comment by jpkrohling** [comment]
@domasx2, is this still relevant? I remember you mentioning that you might not even use logfmt after all.

**Comment by domasx2** [comment]
This is implemented: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15286 my bad, should have closed the issue
