### ISSUE TITLE
[translator/jaeger] When translating binary tags back to Jaeger return them as binary instead of string

### ISSUE THREAD

**Issue by alejandrodnm** [open-telemetry/opentelemetry-collector-contrib#15350]
### Is your feature request related to a problem? Please describe.

When translating binary tags from Jaeger to OTEL they are based64 encoded and put as a Str attribute

https://github.com/alejandrodnm/opentelemetry-collector-contrib/blob/47870dedc479a9a6acc3a6128a5d3030240dadcc/pkg/translator/jaeger/jaegerproto_to_traces.go#L253-L254

When translating back to Jaeger no attempt is made to decode the value and return it as binary

https://github.com/alejandrodnm/opentelemetry-collector-contrib/blob/47870dedc479a9a6acc3a6128a5d3030240dadcc/pkg/translator/jaeger/traces_to_jaegerproto.go#L138-L140

Meaning that binary Jaeger tags are returned as the base64 string representation of the binary.

### Describe the solution you'd like

When translating a Jaeger binary tag to OTEL and back to Jaeger I expect the tag returned as binary instead of the base64 string representation

### Describe alternatives you've considered

In our project, when translating binary tags we prefix them with `data:application/octet-stream; base64,` from the "data" URL scheme RFC https://www.rfc-editor.org/rfc/rfc2397#section-2 

Ex:

For the base64 encoded string `dGVzdA==`  we store it as `data:application/octet-stream; base64,dGVzdA==`

https://github.com/timescale/promscale/blob/a6d486c41ea6bd78cf75dbddfc872c1dfe983965/pkg/jaeger/store/binary_tags.go#L61-L97

When translating back from OTEL to Jaeger if the attribute is a string and it has the prefix, then it's decoded back to binary:

https://github.com/timescale/promscale/blob/a6d486c41ea6bd78cf75dbddfc872c1dfe983965/pkg/jaeger/store/binary_tags.go#L30-L59

The inconvenience is that we have to go through all the tags to encode the binary ones before passing the Jaeger spans through the translator, and when converting back from OTEL to Jaeger we have to do another pass through the tags to look for the ones that should be decoded.

### Additional context

If you think the approach of adding the prefix is good enough, I will submit a PR with the required changes.

Thanks :)

**Comment by jpkrohling** [comment]
cc @frzifus

**Comment by alejandrodnm** [comment]
Hi @frigus02 @jpkrohling have you had a change to review this?

**Comment by frigus02** [comment]
I feel like you tagged me by accident. I don't think I can offer any help here.

**Comment by alejandrodnm** [comment]
@frigus02 I'm so sorry 🙈  I meant @frzifus

**Comment by frzifus** [comment]
Unfortunately, I won't be able to make it this week. But i made a note to have a look next week :)

**Comment by alejandrodnm** [comment]
My company stopped supporting the observability product that we were working on, so I don't think I'll be able to provide a PR for this.

Feel free to close it. Sorry.

**Comment by fatsheep9146** [comment]
ping @frzifus

**Comment by jpkrohling** [comment]
@frzifus, are you able to take a look at this one?

**Comment by frzifus** [comment]
> If you think the approach of adding the prefix is good enough, I will submit a PR with the required changes.

My personal preference would be a proper decoding in place. This kind of change should also not be to in immersive. wdyt @jpkrohling ?

The diff I see here is:
```golang
attributeToJaegerProtoTag(key string, attr pcommon.Value) model.KeyValue
// to
attributeToJaegerProtoTags(key string, attr pcommon.Value) []model.KeyValue
```
And adding more or less [your decoding logic](https://github.com/timescale/promscale/blob/a6d486c41ea6bd78cf75dbddfc872c1dfe983965/pkg/jaeger/store/binary_tags.go#L30-L59).

**Comment by jpkrohling** [comment]
>But I like to know why this comment was added:

Where did you see that comment?

**Comment by frzifus** [comment]
@jpkrohling its coming from [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24012/files#diff-5ee265bf81e78e5c79f0e6bfb5560060b153bc020850ef65b74df0ca4db7c197L129).

**Comment by jpkrohling** [comment]
Looks like it comes from this: https://github.com/open-telemetry/opentelemetry-collector/pull/866 , made by @dmitryax.

@dmitryax, I know it's asking too much, but do you remember what was the comment about?

**Comment by dmitryax** [comment]
At that point, we didn't attribute values of bytes type. So it was put there to avoid performance hit on translating the most common type - string. I think now we should encode jaeger bytes into OTel bytes instead of a string.

**Comment by fatsheep9146** [comment]
ping @frzifus
