### ISSUE TITLE
[receiver/filelog] storage config option doesn't have a default value in the docs

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#15364]
`storage` config option is not marked as _Required_ and doesn't have a default value in the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/filelogreceiver/README.md)

Similar with `multiline` but it's clear what's the default value

**Comment by djaglowski** [comment]
`storage` is not required and does not have a default. Are you suggesting that the doc should specify `""` as the default? I'm not sure that's helpful to the user.
