### ISSUE TITLE
[exporter/loki] The docs for loki.resource.labels is incorrect

### ISSUE THREAD

**Issue by Jontem** [open-telemetry/opentelemetry-collector-contrib#15386]
### Describe the issue you're reporting

In the [example](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/example/otelcol.yaml) and [readme](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md) it's shown that `loki.resource.labels` should be placed under resource processor.
```
  resource:
    attributes:
    - action: insert
      key: loki.resource.labels
      value: host_name, pod_name
```

But i couldn't get it to work. Looking at the actual implementation it seems that it looks for resourceHints in log attributes 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/loki/convert.go#L48
```go
// get the hint from the log attributes, not from the resource
// the value can be a single resource name to use as label
// or a slice of string values
if resourcesToLabel, found := logAttrs.Get(hintResources); found {
  labels := convertAttributesToLabels(resAttrs, resourcesToLabel)
  out = out.Merge(labels)
}
```

**Comment by kovrus** [comment]
@Jontem @zirain you are right, it seems like a bug. Do you want to open a pull request with a fix?

**Comment by zirain** [comment]
cc @kovrus #16088
