### ISSUE TITLE
[exporter/lokiexporter] Remove deprecated loki exporter configuration parameters.

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/opentelemetry-collector-contrib#15653]
### Describe the issue you're reporting

Remove deprecated in versions 0.57 and 0.59 loki exporter configuration parameters. The support of `labels.{attributes/resource}`, `labels.record`, `tenant`, and `format` configuration parameters are dropped in favor of attribute hints for configuring the exporter.

**Comment by koepalex** [comment]
Sorry to hijack this thread, I would like to use open-telemetry collector to export to loki and it seems, that loki isn't supported out of the box anymore: `Error: failed to get config: cannot unmarshal the configuration: unknown exporters type "loki" for "loki" (valid values: [zipkin otlp otlphttp jaeger prometheus prometheusremotewrite logging file kafka opencensus])`. Is there an setting to activate the loki exporter or another image I can use? (I'm currently using `otel/opentelemetry-collector:latest`).

**Comment by hanouard** [comment]
hello @koepalex 
you probably should use the otelcol-contrib for the linux package or otel/opentelemetry-collector-contrib for docker

**Comment by jpkrohling** [comment]
@kovrus, should I assign this to you or should it go to @mar4uk ?

**Comment by mar4uk** [comment]
@jpkrohling I think it should be assigned to me

**Comment by mar4uk** [comment]
@jpkrohling is there anything that holds us from removing the legacy loki exporter?

**Comment by BenjaminKeffer** [comment]
Thanks a lot for you response!

The reasons make sense to me. As far as I understand, the Derived Field only works in one direction, and that is for tracing. If I have understood it correctly, the reverse way is not possible via the Derived Field (from tracing to log), but only via an indexed label. Is that so or do I understand something wrong?

**Comment by gouthamve** [comment]
We can jump from trace to logs without indexing it. See: https://grafana.com/docs/grafana/latest/explore/trace-integration/#trace-to-logs and https://grafana.com/docs/grafana/next/datasources/tempo/#trace-to-logs
