### ISSUE TITLE
[docs] Add support tables for all components

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector-contrib#15654]
### Describe the issue you're reporting

Most of the components (exporters, extensions, processors, receivers) have a table at the top of their README files describing the stability level, supported pipeline types and distribution in which they are included. Some of them don't though. I propose that I add the tables for the components without them:

Exporters:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/mezmoexporter

Extensions:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/awsproxy

Processors:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/deltatorateprocessor
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/logstransformprocessor
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricsgenerationprocessor

Receivers:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/receivercreator
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/solacereceiver
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/sqlqueryreceiver

I figured I'd create an issue for this before jumping on the code and sending a PR.

**Comment by gbbr** [comment]
I have noticed some of this myself. It would be very helpful 👍🏻 Before opening a PR, you'd have to know the actual stability levels from the authors of those components 🤞🏻
