### ISSUE TITLE
Introduce e2e tests for kubernetes story

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#15651]
## Problem statement

Kubernetes related components, especially [k8s attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor) are used pretty extensively in the field. At the same time they don't have good e2e test coverage. Recently we had a significant change that introduced a few regressions. We want to make sure that such regressions are caught by CICD going forward.

## Proposed solution

We need to introduce a GitHub actions job that would spin up a k8s cluster with a collector built from the current branch. 

Proposed steps:

1. Build a collector docker image with required k8s related components.
2. Spin up a [kind k8s cluster](https://kind.sigs.k8s.io/docs/user/quick-start/).
3. Spin up a collector with applications generating a predictable load: metrics, logs, and traces. We can use https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-demo. The collector should be configured with [file exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter)
4. The OTLP JSON files written by the collector should be parsed and compared against expected values, e.g. k8s pod/deployment/namespace UIDs/names/labels/annotations etc.

## Action items

- [x] Spike to verify (or change) the proposed solution
- [x] e2e test for k8s attributes processor: traces
- [x] #18514
- [x] #18391
- [x] #18392
- [x] #18393
- [x] #18394
- [x] #18395

Once it's introduced in the contrib repo, we can potentially reuse the same tests in the helm repo.

**Comment by dmitryax** [comment]
@povilasv as we discussed, PTAL if it makes sense and if you can work on it

**Comment by dmitryax** [comment]
> This is cool! Makes sense to me. Do we have something similar somewhere else I can use to bootstrap this?

https://github.com/open-telemetry/opentelemetry-helm-charts has some smoke tests spinning up a cluster and installing the charts, so they can be used as a starting point

**Comment by dmitryax** [comment]
@povilasv please let us know if you have time to work on this, otherwise, we will look if someone else can take it

**Comment by fatsheep9146** [comment]
> * Should we make a pipeline that pushes the image before we spin up a kind cluster? (I tried to do that but got docker login error)

For this question, could we consider only build image locally, but instead of pushing to docker hub, we just use `kind load docker-image` to load local image to kind node?
@povilasv

**Comment by fatsheep9146** [comment]
Any progress? @povilasv

**Comment by fatsheep9146** [comment]
Do you have time on this? @povilasv If not, I'm willing to continue on this work.

**Comment by dmitryax** [comment]
> For this question, could we consider only build image locally, but instead of pushing to docker hub, we just use kind load docker-image to load local image to kind node?

I agree, we can build a small image locally with needed components only and use it in the kind cluster for testing.

**Comment by fatsheep9146** [comment]
> > For this question, could we consider only build image locally, but instead of pushing to docker hub, we just use kind load docker-image to load local image to kind node?
> 
> I agree, we can build a small image locally with needed components only and use it in the kind cluster for testing.

Yes, I already tried to do like in this way, but encounter some questions to be solved.

**Comment by dmitryax** [comment]
@fatsheep9146 feel free to share your findings here

**Comment by fatsheep9146** [comment]
hi @dmitryax @povilasv  #17410 
I add first version of workflow to verify the proposed solution

the whole workflow basically contains following steps

1. checkout collector-contrib code and build otel-collector-contrib image
2. start a test kind cluster
3. use `kind load docker-image` command to load otel-collector-contrib image into kind cluster
4. fetch helm charts of collector and install it into kind with the newly built image, some details
	- use fileexporter to exporter trace data
	- collector work in statefulset mode to make it easier to copy the trace data out of pod
6. start a pod by (job/statefulset/deployment) with image telemetrygen to produce raw telemetry data and export to collector 
        - I do not use opentelemetry-demo as proposed solution designs, because the whole demo is too large to run, I test it in my own virtual machine with 8U16G, I still take minutes to start them all
7. use `kubectl cp` command to copy the trace data out of pod, into the `processor/k8sattributeprocessor/testdata`
8. cd to `processor/k8sattributeprocessor` , run test `TestJobE2E`, the test will scan the traces data found the attributes are correctly added

Since this version is used to verify the solution, some codes are not very carefully wrote, feel free to give any comments.

**Comment by fatsheep9146** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4071680942/jobs/7013700000

here is a successful run

**Comment by dmitryax** [comment]
This is an amazing start! Thanks a lot, @fatsheep9146!

**Comment by dmitryax** [comment]
@fatsheep9146 @povilasv I created items for other k8s components. Feel free to add more tickets or take those that are unassigned

**Comment by fatsheep9146** [comment]
> @fatsheep9146 @povilasv I created items for other k8s components. Feel free to add more tickets or take those that are unassigned

I will start to complete other items :)

**Comment by fatsheep9146** [comment]
> By the way, should we also enhance the k8sattribute tests and check for common cases like Deployments / StatefulSets / DaemonSets?

Yes, I agree with that, feel free to make a contribution :)
