### ISSUE TITLE
Redaction of SpanEvents

### ISSUE THREAD

**Issue by KevinCammarata** [open-telemetry/opentelemetry-collector-contrib#15671]
### Is your feature request related to a problem? Please describe.

SpanEvents have the potential to leak sensitive data, particularly when exception stack traces are automatically attached.  Currently, the redaction plugin only has the ability to act upon attribute values.  

### Describe the solution you'd like

I would like the ability to apply blocked value regex to span events as well.

**Comment by dmitryax** [comment]
Hi @KevinCammarata, thanks for submitting the issue. I don't believe any of the code owners have cycles to implement this at the moment. But if you have a chance, feel free to submit a PR

**Comment by jaBuaillon** [comment]
Hello
As a workaround I used the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) with following:
`      transform:
        trace_statements:
          - context: spanevent
            statements:
              - replace_all_patterns(attributes, "value", "pattern to hide", "***/")`

**Comment by fatsheep9146** [comment]
so, I think the problem is sloved? @KevinCammarata

**Comment by KevinCammarata** [comment]
Yes - this looks good.  I'll check it out.

**Comment by jpkrohling** [comment]
If this is not solved, let me know and I'll reopen this.
