### ISSUE TITLE
extension/awsproxy: stability not specified.

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/opentelemetry-collector-contrib#15693]
### Describe the issue you're reporting

Stability of [awsproxy](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/awsproxy) not specified. Can we please do so? What is it?

**Comment by fatsheep9146** [comment]
I think this is duplicate of #15654.

Should we use #15654 to track the problems? @open-telemetry/collector-contrib-approvers

**Comment by gbbr** [comment]
I agree this is a duplicate. Let's close it, if that's ok with you.
