### ISSUE TITLE
Upgrade github.com/go-redis/redis/v7 to github.com/go-redis/redis/v9

### ISSUE THREAD

**Issue by molian6** [open-telemetry/opentelemetry-collector-contrib#15697]
### Is your feature request related to a problem? Please describe.

Hi to whom it may concern,

I believe nowadays, Redis 6 and Redis 7 are more commonly used. According to https://github.com/go-redis/redis#installation, we should use v8 for Redis 6, and v9 for Redis 7.

More importantly, the v9 now support map[string]interface{} command parsing [1]. This would be an important feature to have, the interface concept is be widely used in Redis 7 (CLUSTER SHARDS being an example). The caveat is v9 currently is in beta, therefore I want to consult with the community whether it is okay to do the upgrade. If it sounds reasonable, I can go ahead and make a PR about the upgrade.

[1] https://github.com/go-redis/redis/blob/v9.0.0-beta.3/command.go#L3575

### Describe the solution you'd like

Upgrade github.com/go-redis/redis/v7 to github.com/go-redis/redis/v9

**Comment by dmitryax** [comment]
@molian6 thanks for submitting the issue. We should migrate to the new version. I don't think code owners currently have cycles to work on this. If you have a chance, feel free to take a shot
