### ISSUE TITLE
Need event metric like span metric

### ISSUE THREAD

**Issue by illidanzen163** [open-telemetry/opentelemetry-collector-contrib#15708]
### Is your feature request related to a problem? Please describe.

I have use span metric for some time. And I found in some other platform , it provide event metric. I think it's a good idea. 

### Describe the solution you'd like

Add event metric in span metric processor. Maybe just calls_total is enough, and add some event attribute to the metric.

**Comment by albertteoh** [comment]
I'm not very familiar with event metrics, can you please elaborate or provide relevant links/examples?
