### ISSUE TITLE
Ability to reload configs on the fly

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#15714]
### Is your feature request related to a problem? Please describe.

configs could change from time to time(add, update, remove), live reload should be support instead of restarting the collector.

### Describe the solution you'd like

periodically reload configs on the disk, spawning pipelines.

### Describe alternatives you've considered

n/a

**Comment by jpkrohling** [comment]
This is a feature of the collector core, I'm pretty sure we have this tracked there already. Please look at the issues/PRs we have there and let me know if you can't find them.

https://github.com/open-telemetry/opentelemetry-collector/issues?q=is%3Aissue+is%3Aopen+reload
