### ISSUE TITLE
Duplication of Resource Detectors with opentelemetry-go-contrib

### ISSUE THREAD

**Issue by dackroyd** [open-telemetry/opentelemetry-collector-contrib#1590]
**Is your feature request related to a problem? Please describe.**

Resource detectors implemented in this repository duplicate those available in opentelemetry-go-contrib, or otherwise would benefit from being included there.

**Describe the solution you'd like**

Rather than maintaining independent implementations in both places, with inconsistencies and requiring maintenance in both places, resource detectors are implemented in opentelemetry-go-contrib, and used as a dependency.

This would also mean that those resource detectors are available when not using this collector (say the Jaeger variant, or another custom one?)

**Describe alternatives you've considered**

Having both projects maintain their own copies (as applies currently) likely provides more implementation flexibility, since not tied to changes being made in the other project and waiting on releases.

**Additional context**

AWS EC2: [Collector Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/processor/resourcedetectionprocessor/internal/aws/ec2) / [Go Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/detectors/aws/aws.go)
AWS ECS: [Collector Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/resourcedetectionprocessor/internal/aws/ecs/ecs.go) / Go Contrib not implemented (submit?)
GCP GCE: [Collector Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/resourcedetectionprocessor/internal/gcp/gce/gce.go) / [Go Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/detectors/gcp/gce.go)
GCP GKE: Collector Contrib not implemented? / [Go Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/detectors/gcp/gke.go)
Env: [Collector Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/resourcedetectionprocessor/internal/env/env.go) / [OTel Go](https://github.com/open-telemetry/opentelemetry-go/blob/e22a48de5a1353fb5450783ca9bb5edf651e9849/sdk/resource/env.go) Available OOTB with OTel Go
System (OS type, hostname): [Collector Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/resourcedetectionprocessor/internal/system/system.go) / OTel Go/Go Contrib not implemented?

**Comment by dackroyd** [comment]
I was looking into adding resource attributes for AWS and Kubernetes to applications running on that infrastructure. These could be detected at the application level, but that adds complexity and dependencies at that level which are likely undesirable.

For example, using the OpenTelemetry-go-contrib implementation from the application to detect AWS attributes requires a dependency on the AWS SDK, even if the app doesn't use any of the AWS apis otherwise. That library is quite large, and OpenTelemetry-go-contrib doesn't have the resources to maintain an implementation that doesn't have this dependency: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/429

I think it is preferable not to have each application trying to detect these resource attributes themselves, but instead to have this done by the agent/collector for the infrastructure where the app is running. Other setups however may call for the application to do so, and there are other collectors (the Jaeger collector, or a customised one?) which would benefit from being able to reuse the same detection code, maintained in the one place (OpenTelemetry-go-contrib).

**Comment by bogdandrutu** [comment]
@dackroyd completely agree, I think collector should be used for resource detection in general.

**Comment by jrcamp** [comment]
I looked into this as part of adding EKS and GKE. There are some differences between detectors in go-contrib and here. e.g. they add container.id because they can determine what container the app is running in. If we were to include container.id we would put in the collector's own container id. You could configure the processor not to override existing attributes but it's also just not clear if collector should ever insert container.id (unless it's for self-metrics).

go-contrib may also be more sensitive to dependencies being pulled in given their not using k8s client API in EKS for instance. (Though I haven't discussed it with them, I'm just inferring.) In collectors case it's less of a concern.

**Comment by willarmiros** [comment]
Hi @jrcamp @bogdandrutu can we untag `aws-xray` from this feature request (or resolve if the resource detectors have been migrated)? Seems reasonable to have aws tagged, but there's nothing specific to X-Ray in this issue I can see.

**Comment by jpkrohling** [comment]
@Aneurysm9, is this something your team would be interested in working on?

**Comment by Aneurysm9** [comment]
I'm not sure I see the need for, or value in, sharing implementations here.  Would like to hear from other @open-telemetry/go-approvers, but I would currently lean toward closing this issue.

**Comment by dackroyd** [comment]
Happy for the issue to be closed. Clear to me that there is a need for each to be implemented separately
