### ISSUE TITLE
Allow k8s.container.cpu_request and k8s.container.memory_request to be exported by the SignalFx exporter

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#16009]
### Is your feature request related to a problem? Please describe.

The SignalFx exporter excludes some metrics proactively. The metrics k8s.container.cpu_request and k8s.container.memory_request are currently excluded.

### Describe the solution you'd like

k8s.container.cpu_request and k8s.container.memory_request should be allowed to be exported.

**Comment by evan-bradley** [comment]
Closing as solved via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16010.
