### ISSUE TITLE
[servicegraphprocessor] Edge loss attributes from client-side or server-side

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#16002]
### Describe the issue you're reporting

Edge attributes are set by `p.upsertDimensions()` whatever `span.kind` is client or server:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/304196f51b12804846e24d060d0f9b9e2b6df059/processor/servicegraphprocessor/processor.go#L198-L231

it does't handle a sense that the two spans have a attribute with same name but different value, like client span have attribute of `cluster: A` but server span have attribute of `cluster: B`

we can add prefix to distinguish them: 
client_cluster: A
server_cluster: B

**Comment by JaredTan95** [comment]
make sense.
