### ISSUE TITLE
[pkg/stanza] helper.Encoding should avoid to create byte array slice every time

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#16028]
### Describe the issue you're reporting

The idea is to avoid making `[]byte` every time to improve performance. In fact we had previously done benchmark against v0.52.0 and recently v0.60.0 and noticed the performance regression, give it one CPU and 40 files to be ingested, emitted logs/s reduced from ~254k/s to ~140k/s. most of cpu time is used by decoding and underlying `runtime.makeslice`.

**Comment by djaglowski** [comment]
@newly12, thanks for writing this up. Are there any more details you can provide about specifically whereyou see an unnecessary allocation?
