### ISSUE TITLE
[processor/spanmetrics] Label values escaping

### ISSUE THREAD

**Issue by edenkoveshi** [open-telemetry/opentelemetry-collector-contrib#16029]
## Description
We are using NodeJS auto instrumentation on a NodeJS application that uses PostgreSQL
The developers mistakenly wrote a query beginning with "\n" and the trace was generated with operation "pg.query:\n"
This works fine on the OpenTelemetry and Jaeger level but then the processor translates it to metrics with a label operation="pg.query:\n" and Prometheus cannot handle it when querying for it
I know this is a programming bug and it can also be handled with other processors. Still I think the metrics should be escaped and not let buggy input into Prometheus.

## Steps to Reproduce
Create a trace with operation ending with "\n" (any other escape character should work too I suppose)

## Expected Result
Query Prometheus for `calls_total{operation="pg.query:\n"}` and get a valid result

## Actual Result
Prometheus throws an error
The label value should not contain \n

### Collector version

contrib 0.60.0

**Comment by albertteoh** [comment]
Hi @edenkoveshi, I had a go a reprooducing this and it seems to work for me. 

The only odd behaviour I noticed was the autocomplete in the Prometheus UI where it actually evaluates the LF char like so (and similar to other control chars):
<img width="378" alt="Screenshot 2023-01-29 at 9 34 25 am" src="https://user-images.githubusercontent.com/26584478/215294154-9a4e0316-4373-47ac-863b-76c23f963e56.png">

But replacing this with the query your provided above: `calls_total{operation="pg.query:\n"}` seems to successfully query the metric:

<img width="1372" alt="Screenshot 2023-01-29 at 9 30 05 am" src="https://user-images.githubusercontent.com/26584478/215294028-678e2738-93b9-4bba-a3c0-b00c304fb6a0.png">

This is consistent with how Jaeger displays the operation:
<img width="1784" alt="Screenshot 2023-01-29 at 9 31 38 am" src="https://user-images.githubusercontent.com/26584478/215294075-1c489564-1e55-436f-bd39-7869e5538764.png">

As well as in Grafana:
<img width="1292" alt="Screenshot 2023-01-29 at 9 29 22 am" src="https://user-images.githubusercontent.com/26584478/215294123-c64a3cdf-d38f-40b0-bbcf-6f866cb5571b.png">

I also tested with other control chars like `\0` (nul) and `\b` (break) and they seem to be queryable in Prometheus, too, given the appropriate escape characters are used in the query.

Please let me know if I've misunderstood something.

**Comment by fatsheep9146** [comment]
nicely ping @edenkoveshi

**Comment by mx-psi** [comment]
Closing this as wontfix since we haven't heard back from OP. Please comment if you want to reopen the issue!
