### ISSUE TITLE
Ability to ping code owners in PRs and discussions 

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#16036]
I'd be nice to be able to automatically ping code owners by adding labels in PRs and discussions, not only issues.

**Comment by dmitryax** [comment]
@evan-bradley WDYT?

**Comment by evan-bradley** [comment]
I like that idea. Code owners who are not approvers/maintainers do not get notified automatically in PRs because of how the GitHub CODEOWNERS file works, so that could simplify the process of asking for a review. Discussions could also benefit since they're like issues.

**Comment by dmitryax** [comment]
> Discussions aren't supported in the GitHub CLI, so we will only be able to do PRs for now.

Sounds good. Thanks for adding the support of PRs!

**Comment by dmitryax** [comment]
@evan-bradley I see that PRs are getting labels automatically

**Comment by evan-bradley** [comment]
Do you have an example where it isn't requesting a review? I have seen a few instances where code owners aren't added to a PR, which I believe is because someone in the request isn't part of the OpenTelemetry organization. For normal cases it appears to add code owners when it adds the label.

**Comment by dmitryax** [comment]
You're right. They are not members of the organization. For example, I submitted https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16302 and none of the 3 code owners weren't notified. I think we should ping them if we cannot assign reviewers

**Comment by evan-bradley** [comment]
That makes sense to me. It's a little more involved than adding them as reviewers, so I've opened an issue here to outline approaches we can take: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16326.
