### ISSUE TITLE
[receiver/mysql] Add database resource attributes

### ISSUE THREAD

**Issue by portertech** [open-telemetry/opentelemetry-collector-contrib#16063]
### Component(s)

receiver/mysql

### Is your feature request related to a problem? Please describe.

Need human-friendly identifiers of the database to be used for filtering etc.

### Describe the solution you'd like

Considering the following attributes at this time:

#### `db.cluster.name`

Name of the database cluster (configured manually by the user), it serves as a human-friendly database identifier. Tracing uses `db.name`, but it has a caveat: “In some SQL databases, the database name to be used is called “schema name”. In case there are multiple layers that could be considered for database name (e.g. Oracle instance name and schema name), the database name to be used is the more specific layer (e.g. Oracle schema name)“.

#### `db.cluster.address`

Network address used by end users to connect to the database. There can be several addresses used to connect to a single database and they may be different than the address used to collect metrics. Tracing has `net.peer.addr`, but this attribute doesn’t make much sense in the metrics context.

#### `db.cluster.port`

Network port used by end users to connect to the database. Tracing has `net.peer.port`, but this attribute doesn’t make much sense in the metrics context.

### Additional context

[ Add database resource specification #2916](https://github.com/open-telemetry/opentelemetry-specification/issues/2916) 
[[receiver/mysql] add support for more metrics #14138 ](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14138)

**Comment by atoulme** [comment]
Please try to get this on the agenda of the specification SIG. Open an issue on opentelemetry-specification with your rationale and come to a SIG meeting to get this under review.
