### ISSUE TITLE
k8s.node.uid not available

### ISSUE THREAD

**Issue by Bhogayata-Keval** [open-telemetry/opentelemetry-collector-contrib#16087]
### Component(s)

receiver/kubeletstats

### Describe the issue you're reporting

kubeletstats receiver does not provide "k8s.node.uid" as a resource attribute, which is considered recommended field at https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/k8s/.
I was hoping to get this value to co-relate data between k8sclusterreceiver & kubeletstatsreceiver. 
Q1: Is UID going to be added in kubeletstatsreceiver in near future ? (should it be added ?)
Q2: If not, what is the workaround to co-relate data between k8sclusterreceiver & kubeletstatsreceiver ? (k8s.node.name is not a good option as per my opinion)

**Comment by dmitryax** [comment]
@Bhogayata-Keval This is a valid request, and it would be great to add `k8s.node.uid` attribute to kubelet node metrics, but I don't think code owners can work on it in the near future. Feel free to contribute if you're interested
