### ISSUE TITLE
[Host Metrics Receiver] Extend documentation for running in docker

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#16093]
### Is your feature request related to a problem? Please describe.

With reference to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16026,

The PR is making changes to ensure that it can operate within a docker container and still capture the host metrics _as if_ it were running natively on the host and in the default linux namespace(s). This does require that the docker container mount particular paths on linux based systems (`/proc/*`), however, there should be some consideration on what mounts are _absolutely_ required in order to effectively monitor the system.

### Describe the solution you'd like

The `hostmetrics` receiver has a detail description of what paths from the host system are used and recommendations on how they should be mounted by the container.

### Describe alternatives you've considered

I haven't considered much but I would love this to be discussed further on what others would recommend when trying to monitor the host using a docker container.

### Additional context

I don't think it is strictly common place to monitor the host system from the container, however, I believe this would be more important for those running in k8s wanting to monitor the kubelet directly.

**Comment by shafeequeaslam** [comment]
I've achieved this. Please assign this issue to me.

**Comment by MovieStoreGuy** [comment]
Oh right, yes misunderstood you.

It is all yours!
