### ISSUE TITLE
Enhance metrics collection in Host Metrics receiver

### ISSUE THREAD

**Issue by stephenhong** [open-telemetry/opentelemetry-collector-contrib#16226]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

The Host Metrics receiver generates metrics about the host system scraped from various sources and I noticed that some metrics are present with the New Relic infrastructure agent and not with the Opentelemetry collector.
e.g.
host.disk.totalBytes
host.disk.usedPercent
host.disk.freePercent
host.disk.inodesFree
host.disk.inodesTotal
host.disk.inodesUsed
host.disk.inodesUsedPercent

The intend of this request is to enhance the Host Metrics receiver so that the missing metrics can be collected.

### Describe the solution you'd like

Both [New Relic infrastructure agent](https://github.com/newrelic/infrastructure-agent/blob/master/pkg/metrics/storage/storage_sampler.go#L15) and [Host Metrics receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_others.go#L25) leverage the [gopstuil](https://github.com/shirou/gopsutil) (process and system utilities for golang) library, which is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors). This library contains many structs that store collections of different metric fields, so we create new functions in the Host Metrics receiver that reference these fields to generate new metrics.

**Comment by dmitryax** [comment]
Hi @stephenhong, please take a look at filesystem metrics https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/documentation.md and see if there is still anything not covered

**Comment by astencel-sumo** [comment]
Here's a related issue:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14117

In [this comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14117#issuecomment-1265535792) on that issue, I describe how to find:
- number of free inodes on a mount - possibly this would be `host.disk.inodesFree`
- total number of inodes - this is probably `host.disk.inodesTotal`

@stephenhong I think you should be able to get the other metrics too, based on the above.

**Comment by stephenhong** [comment]
@dmitryax @astencel-sumo Thank you for the references. The filesystem metrics [documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/documentation.md) lists only three metrics that are scrapped by the filesystem scrapper: system.filesystem.inodes.usage, system.filesystem.usage, system.filesystem.utilization. The [UsageStat](https://github.com/shirou/gopsutil/blob/master/disk/disk.go#L12-L23) struct in gopsutil library contains multiple fields that have not been implemented in the receiver yet. Would it be possible for myself to contribute to add those fields in the filesystem scrapper?

**Comment by astencel-sumo** [comment]
As I said above, you should be able to get all information from the available metrics. Let's break down this [UsageStat](https://github.com/shirou/gopsutil/blob/v3.22.10/disk/disk.go#L12-L23) structure:

| UsageStat field | Host Metrics receiver equivalent | Reference |
|---|---|---|
| `Path` | `mountpoint` attribute | [link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go#L30-L34) |
| `Fstype` | `type` attribute | [link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go#L30-L34) |
| `Total` | `system.filesystem.usage{type="used"}` + `system.filesystem.usage{type="reserved"}` + `system.filesystem.usage{type="free"}` | [unix](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go#L40-L44) [windows](https://github.com/shirou/gopsutil/blob/v3.22.10/disk/disk_windows.go#L72) |
| `Free` | `system.filesystem.usage{type="free"}` | [unix](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go#L35-L39) [windows](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_others.go#L35-L39) |
| `Used` | `system.filesystem.usage{type="used"}` | [unix](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go#L30-L34) [windows](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_others.go#L30-L34) |
| `UsedPercent` | `system.filesystem.utilization` | [unix](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go#L45-L48) [windows](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_others.go#L40-L43) |
| `InodesTotal` | `system.filesystem.inodes.usage{state="used"}` + `system.filesystem.inodes.usage{state="free"}` | [gopsutil](https://github.com/shirou/gopsutil/blob/v3.22.10/disk/disk_unix.go#L45) |
| `InodesUsed` | `system.filesystem.inodes.usage{state="used"}` | [link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go#L56-L59) |
| `InodesFree` | `system.filesystem.inodes.usage{state="free"}` | [link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v1.64.0/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_scraper_unix.go#L60-L63) |
| `InodesUsedPercent` | 100 * `system.filesystem.inodes.usage{state="used"}` / (`system.filesystem.inodes.usage{state="used"}` + `system.filesystem.inodes.usage{state="free"}`) | [gopsutil](https://github.com/shirou/gopsutil/blob/v3.22.10/disk/disk_unix.go#L50) |

**Comment by stephenhong** [comment]
I see. I want to make sure I'm understanding this correctly. There is no need to add fields in the filesystem metadata, such as **system.filesystem.inodes.total** or **system.filesystem.inodes.utilization**, since it can be inferred by existing metrics (i.e. inodes total = system.filesystem.inodes.usage{state="used"} + system.filesystem.inodes.usage{state="free"}). Is the design here to have end users calculate these fields themselves rather than presenting it to them as a standalone field?

**Comment by stephenhong** [comment]
I see. I want to make sure I'm understanding this correctly. Are you telling me that there is no need to add fields in the filesystem metadata, such as **system.filesystem.inodes.total** or **system.filesystem.inodes.utilization**, since it can be inferred by existing metrics (i.e. inodes total = system.filesystem.inodes.usage{state="used"} + system.filesystem.inodes.usage{state="free"})? Is the design here to have end users calculate these fields themselves rather than presenting it to them as a standalone field?

**Comment by astencel-sumo** [comment]
My opinion is it wouldn't hurt for the Host Metrics receiver to expose optional metrics like these. But I'm afraid it's not a popular opinion.

**Comment by stephenhong** [comment]
Understood. I did more research and I found that the following process metrics are not available with the receiver:
**host.process.ioReadBytesPerSecond
host.process.ioReadCountPerSecond
host.process.ioWriteBytesPerSecond
host.process.ioWriteCountPerSecond
host.process.ioTotalReadCount
host.process.ioTotalWriteCount**
_(the naming convention comes from New Relic metric data)_

Currently, the only available process metric for disk is [process.disk.io](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/documentation.md#metrics). I propose to add metrics such as **process.disk.operations** and **process.disk.operation_time** so that the above metrics can be calculated. Would this be a valid enhancement request?

**Comment by astencel-sumo** [comment]
As for the process disk IO read/write bytes per second, I believe this is just the `process.disk.io` metric with a rate operator applied.

As for the process disk IO read/write operations, this one is indeed missing.

I proposed this metric to be added `process.disk.operations` https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14566, but the semantic convention proposal for this metric was unfortunately rejected: https://github.com/open-telemetry/opentelemetry-specification/pull/2845. If I understand correctly, the implementation proposal cannot be accepted without a naming convention for the metric existing in the first place.

**Comment by astencel-sumo** [comment]
@stephenhong The pull request https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14566 has been thankfully accepted and the `process.disk.operations` metric is now available in the Host Metrics receiver.

The rate operator calculates the per-second rate of change between consecutive data points. You can get more information about it if you search for "metric rate operator" on the web. Here's the Prometheus description (admittedly not very beginner-friendly in my opinion): https://prometheus.io/docs/prometheus/latest/querying/functions/#rate.

**Comment by dmitryax** [comment]
@stephenhong do you need to add some metrics or the issue can be closed?
