### ISSUE TITLE
k8sattributes processor - sidecar mode

### ISSUE THREAD

**Issue by maxsargentdev** [open-telemetry/opentelemetry-collector-contrib#16268]
### Component(s)

processor/k8sattributes

### Describe the issue you're reporting

Hi

I would of messaged on slack, but I cannot access the slack workspace.

---

Does the k8sattributes processor support the sidecar mode of the opentelemetry collector?

The go docs are not very clear, it says:

~~~

The processor does not support detecting containers from the same pods when running as a sidecar. While this can be done, we think it is simpler to just use the kubernetes downward API to inject environment variables into the pods and directly use their values as tags.

~~~

Does this mean its only the ability to detect containers in the same pod that doesnt work?

If so, how does one configure the RBAC for this processor? Given that it would in sidecar mode.

Do I need to grant permissions for the entire deployment, such that the mounted service account token gives the required access?

An example of the configuration for each mode would be useful.

Thanks,
Max Sargent

**Comment by maxsargentdev** [comment]
Can someone please let me know if what I am describing is possible.

Could opentelemetry running as a sidecar, read the label of its own deployment and use it for rewriting attributes in trace data?

**Comment by maxsargentdev** [comment]
Sorry to drag this up again but I have a test environment working now.

My sidecar is getting injected via the controller as I have an annotation configured on my deployment. 

When I connect a debug container to the otel sidecar I cannot see **OTEL_RESOURCE_ATTRIBUTES** in its environment, therefore the configured resource detection processor is not working picking up any attributes.

**Comment by atoulme** [comment]
There is no relation between OTEL_RESOURCE_ATTRIBUTES and the resource detection processor, they perform different tasks AFAIK. The OTEL_RESOURCE_ATTRIBUTES env var is used to set resource attributes on metrics, traces and logs from the application instrumented. The resource detection processor uses calls to k8s API, ec2 API, and so forth, to inject resource attributes into data.

**Comment by fatsheep9146** [comment]
I think this issue could be closed, since this is not the problem that k8sattribute processor should resolve.
