### ISSUE TITLE
[receiver/solace] Flaky Test - TestReceiverDialFailureContinue (windows)

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#16267]
### What happened?

Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3445016616/jobs/5748248417#step:8:3135

### Collector version

main

### Environment information

Windows CI

**Comment by dmitryax** [comment]
Seen here as well https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3525726228/jobs/5912800313

**Comment by mcardy** [comment]
Is this still being seen?

**Comment by dmitryax** [comment]
Seen here https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6451437603/job/17512067909

**Comment by pjanotti** [comment]
Another hit https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6800339059/job/18488651617#:~:text=%2D%2D%2D%20FAIL%3A%20TestReceiverDialFailureContinue%20(0.11s,327

```
--- FAIL: TestReceiverDialFailureContinue (0.11s)
    messaging_service_test.go:702: timed out waiting for dial to be called
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/solacereceiver	4.590s
FAIL
```
