### ISSUE TITLE
[Azure Monitor Exporter] Span Events support

### ISSUE THREAD

**Issue by JorTurFer** [open-telemetry/opentelemetry-collector-contrib#16260]
### Component(s)

exporter/azuremonitor

### Is your feature request related to a problem? Please describe.

Open Telemetry supports Span Events, and we use them in our applications because they are used for sending exceptions (as the protocol says at least for dotnet).  We are checking the collector to remove the process in the apps but azure monitor exporter doesn't support any type of Span Events.

### Describe the solution you'd like

I'd like to have full implemented behavior for Span Events in azure monitor, sending the exceptions to the azure monitor exceptions table and the other events to the custom events table.

### Describe alternatives you've considered

There isn't any alternative, this is a blocker for us because we need at least the exceptions part implemented, or we can't move to collector because we would lose very valuable information. 
The only alternative is forking and detaching our branch from the upstream, what we would like to avoid.

### Additional context

I'm willing to contribute with the feature and opening a PR if you find it useful

**Comment by fatsheep9146** [comment]
I think this issue is solved by #16354, closed.
