### ISSUE TITLE
See if we can use dyladan/component-owners instead of CODEOWNERS

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#16274]
We rely on the CODEOWNERS file a lot and built a lot of tooling on top of it. 

Looks like https://github.com/dyladan/component-owners can be a good fit for our use case. I also like the YAML format, no need for manual parsing of the CODEOWNERS file anymore.

cc @evan-bradley @TylerHelmuth

**Comment by TylerHelmuth** [comment]
I love that this action does both assigned and reviewers, the ones I found only did reviewers. 

I think my primary concern would be if GitHub starts using the CODEOWNERS file for something else and then we don't have it. But it's not a big concern bc we could just add it back.

**Comment by evan-bradley** [comment]
I think this action would work well for us. We would likely want to also implement adding component labels and assigning an approver to the PR to either this action or to another action working from the same component definition file. Additionally, if we use this action, we should either look to move to using a common format for component definitions (see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16313) or look at parsing the component-owners YAML file in our other workflows, which I think `yq` would make fairly easy. We could probably leave the CODEOWNERS file in place while using this action, but ideally we don't have to maintain two files.

Overall, I would like to make most of our issue and PR workflow scripts into published GitHub Actions that we then use in our workflows. I think using a general-purpose programming language over shell scripts in particular would help make the workflows easier to understand and maintain, and would make it easier to use better formats than the CODEOWNERS file for hosting component definitions.
