### ISSUE TITLE
New component: AWS Timestream Exporter

### ISSUE THREAD

**Issue by fredthomsen** [open-telemetry/opentelemetry-collector-contrib#16271]
### The purpose and use-cases of the new component

AWS Timestream Exporter send data to the AWS Timestream metric store.  Timestream is a time-series serverless database for storing and analyzing metrics in the AWS platform.  There are a number of analytics use cases, for example the data stored in Timestream can be used by various AWS products, like SageMaker, and/or visualized in Graphana.  Lifecycle management per metric datapoint is also supported.

### Example configuration for the component

```yaml
awstimestream:
  database: sample-db
  table: sample-table
  region: us-east-1
```

### Telemetry data types supported

metrics

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

Currently we have developed this for internal use and need to make things more generic and configurable, hence the current configuration above is fairly barebones.

**Comment by codeboten** [comment]
@Aneurysm9 @bryan-aguilar is this a component folks from AWS would be interested in sponsoring?

**Comment by fredthomsen** [comment]
Without a sponsor from AWS, looking at the language in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components, I assume this is a no-go.  I'll let this sit a bit longer, and if there is no sponsor, we'll open source this in our own repo.

**Comment by Gaganjuneja** [comment]
Any update on this?

**Comment by fredthomsen** [comment]
@Gaganjuneja we are likely moving away from timestream usage and thus I am hesitant to open source in our own company repo given that it would languish, so I'd rather do it here, but again there is no sponsor.
