### ISSUE TITLE
[exporter/googlecloud] Support mapping log resource attributes to labels

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#16270]
### Component(s)

exporter/googlecloud

### Is your feature request related to a problem? Please describe.

When exporting to GCP, resource attributes on the log are dropped if they aren't a specific subset of labels that map to a monitoring resource.

These resource attributes are sometimes key to understanding where your logs are coming from, so having them completely dropped means that the logs often become unusable without them (e.g. the mongodbatlasreceiver logs won't have the cluster mapped in GCP, so it's impossible to tell where the log came from).

Metrics currently have the ability to map resource attributes to labels in GCP, so it would be nice to have a similar ability for logs.

### Describe the solution you'd like

Map the resource attributes to labels, just like normal attributes.

It could be implemented similar to how it's implemented for metrics, allowing you to define a list of prefixes, where a resource attribute will be translated to labels if it has one of the defined prefixes.

This could also be done through a `resource_to_telemetry_conversion` option, like the prometheus exporter supports for metrics: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter#getting-started

### Describe alternatives you've considered

Using the transform processor to move resource attributes to log record attributes.

The issue with this approach is that it's error prone, and requires users to know the exact names of the resource attributes they want to move. It also means you likely will need a separate pipeline just for sending logs using the googlecloud exporter, because other exporters may want to keep those attributes as resource attributes.

**Comment by damemi** [comment]
I don't see a problem with this, especially with a flag to turn it on like you suggested @BinaryFissionGames 

@dashpole can you think of any reason for us not to add it?

**Comment by dashpole** [comment]
Seems reasonable to me.

**Comment by damemi** [comment]
Created a PR to add this downstream https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/531
Will close this issue once that is released and updated here
/assign

**Comment by BinaryFissionGames** [comment]
Thanks @damemi!
