### ISSUE TITLE
Require resource attributes about the host for hostmetricsreceiver

### ISSUE THREAD

**Issue by liurui-1** [open-telemetry/opentelemetry-collector-contrib#16303]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

Right now the `hostmetrics` receiver does not provide any resource attributes. (Only the `process` ResourceMetrics has some resource attributes about that particular collector process which we do not need).
We need those resource attributes recommended at [https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/host/](https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/host/) for example `host.name` .

### Describe the solution you'd like

There are various APIs and system calls to get those resource attributes mentioned at [https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/host/](https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/host/).

**Comment by mx-psi** [comment]
You can use the resource detection processor (e.g. the [`system`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor/internal/system) detector) for this (but maybe we also need something specific in the host metrics receiver, I will leave that decision to Dmitrii)

**Comment by mx-psi** [comment]
@dmitryax can you help us decide if this is something we should support on the hostmetrics receiver or if we should recommend the resource detection processor instead?

**Comment by liurui-1** [comment]
We can use `resourcedetection` processor to enrich the data with required resource attribute for example `host.name`, but it cannot get the right host name if we run this contrib collector in a Docker container. Both `hostmetrics` receiver and `resourcedetection` processor cannot correctly detect the metrics and resource attributes of the host instead of the container. For example we cannot detect the `host.name` attribute of the host with `resourcedetection` processor. I have tried various configurations. Finally I have to set this `host.name` attribute directly.

**Comment by mx-psi** [comment]
You can use Docker's `--hostname` option to override the container hostname and make this work: e.g. if running on bash you can pass ` --hostname $(hostname)` on your Docker call to make the container have the host's hostname. Would that work for you?

Regardless, I think this is a separate issue: it would be a problem whether or not the hostmetrics receiver is the one that does this.

**Comment by liurui-1** [comment]
Thanks @mx-psi . 
` --hostname $(hostname)` is a better solution. And yes, this is a separate issue. 
So you can close this ticket.
