### ISSUE TITLE
Centralize contrib component definitions

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#16313]
Follow up to [this PR comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15721#issuecomment-1297643066).

We currently have the following places where we have to maintain a list of components within the contrib repo:
- `versions.yaml`
- `.github/CODEOWNERS`
- `.github/dependabot.yml`

It would be helpful to have a single definition for these lists with a Make target to generate component lists in other files where they are used. The definition format would need to support at a minimum:
- The path of the component
- Ownership for the component
- Metadata related to the component to help filter output

YAML would likely be an ideal format for this since it is a conventional format and is easy to write and parse for this purpose. It is likely we will want a Go CLI that is hosted in a separate repository to read the YAML definition and generate the outputs. Our CI workflows should also be updated to ensure the generated lists stay up-to-date with the definition file.

cc @dmitryax

**Comment by atoulme** [comment]
It looks like metadata.yaml files might be a good conduit for this component information, now that we have status generated from it.
