### ISSUE TITLE
Publish release cadence for collector-contrib

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector-contrib#1631]
What is the release cadence for the collector-contrib binaries? We'd like to get the latest merged changes in a collector-contrib release. 

Can you please publish the release cadence for collector-contrib and the Collector (e.g. every week, 2 weeks) for when to expect a new release? This helps us test with published artifacts instead of cherry-picking commits to build artifacts.

Can this release process be automated with a GHA workflow? We can help build this workflow.

**Comment by tigrannajaryan** [comment]
Collector core and contrib are released biweekly (today is a release day). The release process is described here https://github.com/open-telemetry/opentelemetry-collector/blob/master/docs/release.md
Further automation of the process is very welcome.

**Comment by alolita** [comment]
Hi @tigrannajaryan Thanks for the link. I looked at release.md but it doesn't seem to state the release frequency for the Collector builds to be available. I'm working with @AzfaarQureshi and @shovnik on migrating the Collector release workflows from CircleCI to GitHub Actions. Feel free to ping me if there are other workflows you have in mind that we can automate for nightly  and stable release builds. See related issue [here](https://github.com/open-telemetry/opentelemetry-collector/issues/1234).

**Comment by astencel-sumo** [comment]
I suppose this can be closed now, what do you think @evan-bradley? Given that the [release.md](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md) file now includes the release schedule table at the bottom.

**Comment by evan-bradley** [comment]
I would agree, closing this as completed. Thanks @astencel-sumo.
