### ISSUE TITLE
Ping code owners who are not OpenTelemetry organization members in PRs

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#16326]
### Is your feature request related to a problem? Please describe.

Code owners who are not members of the OpenTelemetry organization cannot be added as reviewers to PRs. We would still like these users to be aware of and review changes to the components they own.

### Describe the solution you'd like

When a request to add code owners to a PR fails, ping all code owners in the request in a comment and add a `codeowners pinged` or similar label to indicate the code owners have been notified. The workflow will not add another comment if this label is already added to a PR. The worklflow to add code owners to a PR runs when the PR is opened and on every change to the PR, which is why it is necessary to keep track of whether the comment has been sent. Otherwise all code owners will be pinged on every change.

### Describe alternatives you've considered

1. We could make it a hard requirement that code owners are members of the OpenTelemetry organization. This is currently [a requirement in our contributing document](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner), but making it a hard requirement could dissuade potential code owners who are unable to get community membership.
2. We could potentially perform some check to determine whether a user is an organization member or add reviewers individually to verify whether they are valid, but this would be slow, potentially noisy, and would risk being rate limited.
3. We could remove the requirement to use the label to track state by only running the workflow on issue open, but this would miss additional code owners if the scope of a PR changed to include more components.
4. We could also remove the requirement for the label by checking for the ping comment in the PRs comments list, but this would likely be slower than just checking for the label.

**Comment by mx-psi** [comment]
Should we close this one since we are doing #20868? cc @evan-bradley

**Comment by evan-bradley** [comment]
Agreed, this won't be necessary now that all code owners will be organization members. Closing.
