### ISSUE TITLE
[pkg/ottl] Unable to use ottl lists in a Getter

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#16320]
### Component(s)

pkg/ottl

## Description
While trying to set an attribute to a list of strings I ran into an issue trying to use `set` with OTTL lists.  The exact statement was 

```yaml
- context: span
  statements:
    - 'set(attributes["list-attr"], ["this", "is", "a", "list"])'
```

which resulted in a parsing error during collector startup.  Digging into the issue it looks like `newGetter` doesn't know how to handle `val.List`.

I see two solutions:
1. Update `newGetter` to return a `literal[K]` with the value being the list, like `return &literal[K]{value: val.List}, nil`.  This is probably undesireable because it ends up exposing the grammar structure to functions and contexts.  The `set` function, for example, will end up passing the `list` struct to the context which doesn't know how to handle it.
2. Update `newGetter` to return a `literal[K]` with the value being a go slice representation of the list.  This means looping through the list and building out a slice based on the grammar values.

I think option 2 is the better solution.

## Steps to Reproduce

Pass a list as the Getter parameter to a function.

## Expected Result

The function knows how to use the list.

## Actual Result

The collector errors during config validation.

**Comment by TylerHelmuth** [comment]
@evan-bradley do you have time to look at this?

**Comment by evan-bradley** [comment]
I'll look into this. I agree that option 2 is better here.
