### ISSUE TITLE
[processor/spanmetrics] Allow turning off default dimensions

### ISSUE THREAD

**Issue by adam-kiss-sg** [open-telemetry/opentelemetry-collector-contrib#16344]
### Component(s)

processor/spanmetrics

### Is your feature request related to a problem? Please describe.

I would like to use the spanmetrics processor to extract http call metrics. I'm not intrested in the operation/status.code dimensions.

### Describe the solution you'd like

I would like an option to turn off default dimensions (service.name, operation, span.kind, status.code), preferably one-by-one.

### Describe alternatives you've considered

I tried using `metricstransform` processor's `aggregate_labels` option. With v0.64.0 it doesn't work because the timestamp of each data point is slightly different, so the transformer won't merge them.

I think it might be resolved in main by [this change](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/bd43d6f#diff-78f9e7446e0e4fb474786b4b2c262486887bf27479f1f8bc598376d6c3c29b72R339), but i'm not sure how to build the main branch with the collector builder, so I couldn't test it.

**Comment by JaredTan95** [comment]
Did you have tried with empty dimensions like:
```yaml
spanmetrics
    dimensions: []
```

**Comment by adam-kiss-sg** [comment]
@JaredTan95 that only controls the "extra" dimensions, the default dimensions are always added.

In the docs:
```
Each metric will have _at least_ the following dimensions because they are common across all spans:
- Service name
- Operation
- Span kind
- Status code
```

In the code:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/24ac3f844c3caa3d13a236f68ed301e5360280df/processor/spanmetricsprocessor/processor.go#L462

```
// buildKey builds the metric key from the service name and span metadata such as operation, kind, status_code and
// will attempt to add any additional dimensions the user has configured that match the span's attributes
// or resource attributes. If the dimension exists in both, the span's attributes, being the most specific, takes precedence.
//
// The metric key is a simple concatenation of dimension values, delimited by a null character.
func buildKey(dest *bytes.Buffer, serviceName string, span ptrace.Span, optionalDims []dimension, resourceAttrs pcommon.Map) {
	concatDimensionValue(dest, serviceName, false)
	concatDimensionValue(dest, span.Name(), true)
	concatDimensionValue(dest, traceutil.SpanKindStr(span.Kind()), true)
	concatDimensionValue(dest, traceutil.StatusCodeStr(span.Status().Code()), true)

	for _, d := range optionalDims {
		if v, ok := getDimensionValue(d, span.Attributes(), resourceAttrs); ok {
			concatDimensionValue(dest, v.AsString(), true)
		}
	}
}
```

**Comment by albertteoh** [comment]
> I think it might be resolved in main by [this change](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/bd43d6f#diff-78f9e7446e0e4fb474786b4b2c262486887bf27479f1f8bc598376d6c3c29b72R339), but i'm not sure how to build the main branch with the collector builder, so I couldn't test it.

@adam-kiss-sg have you tried:  `make docker-otelcontribcol` and referencing the `otelcontribcol` tag of the built image in docker/docker-compose?

**Comment by adam-kiss-sg** [comment]
@albertteoh 

Thanks, using that method I could test it and the timestamp issue is resolved.

Unfortunately the same commit caused another issue for me: #16387 and #16388

**Comment by albertteoh** [comment]
Hi @adam-kiss-sg, is this requirement still useful to you? 

If so, and if your requirement is to get a call count of all HTTP requests, just wondering if this can be achieved through a query in your metrics storage layer by not filtering on any dimensions (i.e. `calls_total{}`). 

For example, to get the total request rate (calculated in a 1m window) across all services, I _think_ the following prometheus query can achieve this:

```
sum(rate(calls_total[1m]))
```

**Comment by adam-kiss-sg** [comment]
Hi @albertteoh !

Yes, this would still be useful. Even thought i could get the metric the way you recommend, having all these labels increases metric cardinality by a lot. On self-hosted prometheus this could potentially result in performance issues. On cloud services (like what we use), they charge based on metrics cardinality. This is most troublesome for Operation.

**Comment by LaserPhaser** [comment]
I think we can close it now.

**Comment by evan-bradley** [comment]
Closing as completed via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23039.
