### ISSUE TITLE
[metrics builder] Add ability to enable/disable resource attributes

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#16373]
User should be able to enable and disable resource attributes the same way as it's currently done for metrics:

### metadata.yaml interface changes for receiver authors

All resource attributes should get an additional field `enabled`. For now, let's keep all the existing attributes enabled by default, but receiver authors will be able to add (or turn existing) resource attributes into optional attributes. hostmetrics/processscraper example:

```yaml
resource_attributes:
  process.pid:
    enabled: true
    description: Process identifier (PID).
    type: int
```

### User config interface changes

This capability should generate additional struct for user configs that receiver authors have to include in their config the same way as done for `MetricsSettings`.  Using the same example for `process.pid` resource attribute, the generated structs should look like this:

```golang
type ResourceAttributeSettings struct {
	Enabled bool `mapstructure:"enabled"`
}

type ResourceAttributesSettings struct {
	ProcessPid     ResourceAttributeSettings `mapstructure:"process.pid"`
}
```

**Comment by fatsheep9146** [comment]
This issue is resolved, right ? @dmitryax

**Comment by dmitryax** [comment]
Right, [this PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17967) will resolve it
