### ISSUE TITLE
[processor/spanmetrics] Please group datapoints into metrics by dimensions

### ISSUE THREAD

**Issue by adam-kiss-sg** [open-telemetry/opentelemetry-collector-contrib#16388]
### Component(s)

processor/spanmetrics

### Is your feature request related to a problem? Please describe.

Currently there is no way to filter out specific spans from the metrics. Previously it was possible to do this with the filter processor, but after #16102 this is no longer possible (see: #16387)

### Describe the solution you'd like

Group datapoints by attributes into separate metrics, so datapoints in the same metric share the same attributes.

Eg:
before:
```
ResourceMetrics #0
Resource SchemaURL: 
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope spanmetricsprocessor 
Metric #0
Descriptor:
     -> Name: calls_total
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> service.name: Str(dummy-service)
     -> operation: Str(middleware - query)
     -> span.kind: Str(SPAN_KIND_INTERNAL)
     -> status.code: Str(STATUS_CODE_UNSET)
     -> http.method: Str(UNKOWN)
StartTimestamp: 2022-11-21 09:37:33.646666564 +0000 UTC
Timestamp: 2022-11-21 09:38:23.476303012 +0000 UTC
Value: 6
NumberDataPoints #1
Data point attributes:
     -> service.name: Str(dummy-service)
     -> operation: Str(GET /healthz)
     -> span.kind: Str(SPAN_KIND_SERVER)
     -> status.code: Str(STATUS_CODE_UNSET)
     -> net.host.port: Int(80)
     -> http.method: Str(GET)
     -> http.status_code: Int(200)
StartTimestamp: 2022-11-21 09:37:33.646666564 +0000 UTC
Timestamp: 2022-11-21 09:38:23.476303012 +0000 UTC
Value: 6
```

after:
```
ResourceMetrics #0
Resource SchemaURL: 
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope spanmetricsprocessor 
Metric #0
Descriptor:
     -> Name: calls_total
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> service.name: Str(dummy-service)
     -> operation: Str(middleware - query)
     -> span.kind: Str(SPAN_KIND_INTERNAL)
     -> status.code: Str(STATUS_CODE_UNSET)
     -> http.method: Str(UNKOWN)
StartTimestamp: 2022-11-21 09:37:33.646666564 +0000 UTC
Timestamp: 2022-11-21 09:38:23.476303012 +0000 UTC
Value: 6
Metric #1
Descriptor:
     -> Name: calls_total
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> service.name: Str(dummy-service)
     -> operation: Str(GET /healthz)
     -> span.kind: Str(SPAN_KIND_SERVER)
     -> status.code: Str(STATUS_CODE_UNSET)
     -> net.host.port: Int(80)
     -> http.method: Str(GET)
     -> http.status_code: Int(200)
StartTimestamp: 2022-11-21 09:37:33.646666564 +0000 UTC
Timestamp: 2022-11-21 09:38:23.476303012 +0000 UTC
Value: 6
```

### Describe alternatives you've considered

see: #16387

**Comment by adam-kiss-sg** [comment]
@albertteoh  I no longer need this feature because the filter processor can now filter out individual data-points (see: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16369)

I don't fully understand the best practices around resource/metric/datapoint grouping, or the reason why metrics don't have attributes, but datapoints do.

Feel free to close this ticket if you decide this is not something that should be done or it's just not worth the trouble.

**Comment by albertteoh** [comment]
Thanks for confirming @adam-kiss-sg. I also don't have a good understanding of the [OTEL metrics data model](https://opentelemetry.io/docs/reference/specification/metrics/data-model/#opentelemetry-protocol-data-model) but I found this [recommendation in the specification](https://opentelemetry.io/docs/reference/specification/metrics/data-model/#opentelemetry-protocol-data-model-producer-recommendations):

> Producers SHOULD prevent the presence of multiple Metric identities for a given name with the same Resource and Scope attributes.

I think this makes sense; where `calls_total` should be a single `Metric`, each containing streams which are identified by a unique set of `Attributes` (A.K.A dimensions/labels) such as the `service.name`, `operation`, `span.kind`, etc.

As such, I think how `spanmetricsprocessor` populates metrics data seems consistent with the specification and recommendations, so I think we can close this issue (I don't have permissions to close issues though 😅 ).
