### ISSUE TITLE
remove //nolint:errcheck add in #16377

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#16392]
This is a follow up item to #16377 to ensure the `//nolint:errcheck` added are addressed.

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16377#discussion_r1028214654_

**Comment by fatsheep9146** [comment]
@codeboten hi, is this issue solved?
