### ISSUE TITLE
[processor/logstransform] Issue with replace_pattern transform function

### ISSUE THREAD

**Issue by kumachop2** [open-telemetry/opentelemetry-collector-contrib#16391]
### Component(s)

processor/logstransform

### Describe the issue you're reporting

We are using below transform processor rule to replace phone number. It is working fine with regex101 but some issues with splunk client v0.61.0 or v0.63.0 process (AKS). Here are the details. Please check and advice

rule: - replace_pattern(body.message, "([\\\"> ])?([0-9]{3})[- ]*([0-9]{3})[- ]*([0-9]{4})([\\\"< ])?", "$1**$4$5")

Message:
Address { addressType: Permanent address1: 1017 THRUSH LN address2: null city: AUDUBON state: PA zip: 19403 }] contact: class Contact { eMail: [t-rex@example.com](mailto:t-rex@example.com) phoneNumber: 2745888692 } citizenshipStatus: class

Regex101 output:
address2: null city: AUDUBON state: PA zip: 19403 }] contact: class Contact { eMail: [t-rex@example.com](mailto:t-rex@example.com) phoneNumber: **8692 } citizenshipStatus: class

Splunk Log Observer output:
addresses: [class Address { addressType: Permanent address1: 1017 THRUSH LN address2: null city: AUDUBON state: PA zip: 19403 }] contact: class Contact { eMail: [t-rex@example.com](mailto:t-rex@example.com) phoneNumber: **2 } citizenshipStatus: class CitizenshipStatus {

**Comment by dehaansa** [comment]
@kumachop2  Is this still an issue?

If so, can you provide a better example representative of the situation? The log you've shown would not match the provided pattern as there are not spaces or dashes in the phone number, so it's difficult to properly understand the problem based on what you've provided. At first glance everything seems like it should be in order.

Thi may also be an issue with other rules interacting with the logs in unexpected ways, like for example if you have another rule attempting to mask other identifying information that's typically a ~10 digit number that might be the cause. If you can, please provide any other rules being applied to the logs, thanks.
