### ISSUE TITLE
[processor/filter] Ensure OTTL configuration provides same features as existing configuration

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#16413]
### Component(s)

processor/filter

### Is your feature request related to a problem? Please describe.

The OTTL package is being added to the filterprocessor to support generic filtering of spans, span events, metrics, data points, and log records.  To simplify the filterprocessor and its config, I propose that only the OTTL is needed, but before any existing configuration can be deprecated and removed the existing feature set of the processor must be reviewed to ensure that OTTL can handle all existing user situations. Any missing features must be added to the OTTL before this issue can be closed.

### Describe the solution you'd like

Filterprocessor feature set is reviewed and it is confirmed that OTTL can handle all existing features.

Feature gaps:
- [x] Support for `include` statements
- [x] Regex matching where the input is converted to a string if it is a bool, int, or double. https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16434
- [x] OTTL metric conditions support dropping the metric if any of the metrics datapoints have a specific attribute or have a specific attribute with a specific value.

**Comment by TylerHelmuth** [comment]
The filterprocessor configuration for spans, metrics, and logs allows for `include` conditions and `exclude` conditions.  

From the README:
- `include`: Any names NOT matching filters are excluded from remainder of pipeline
- `exclude`: Any names matching filters are excluded from remainder of pipeline

The OTTL implementation acts like `exclude`; if telemetry matches the OTTL condition, then it is dropped.  The OTTL implementation does not have support for `include`; telemetry that does not match the OTTL condition is kept.

In order to deprecate any existing configuration the OTTL configuration will need to be update to allow for the concept of `include`.

**Comment by TylerHelmuth** [comment]
When filtering span, the filterprocessor has access to service name, span name, attributes, scopes, resource attributes, and span kind.  Both strict and regex is supported.  When checking attributes, converting attribute values from bool, double, and int to string is supported

The OTTL has access to each of these properties.  The Factory Function, `IsMatch`, can be used to perform regex matching, but it does not support converting bool, double, or int to string.

**OTTL needs to be able to perform regex where the input is converted to the string if it is a bool, int, or double.**

There are other situations in the transformprocessor where type conversion is needed, so adding a `String` conversion function could be a solution.  Or `IsMatch` can be made more intelligent.

**Comment by TylerHelmuth** [comment]
When filtering logs, the filterprocessor configuration allows matching by resource attributes, attributes, severity text, body, and severity number.   Both strict and regex is supported. When checking attributes, converting attribute values from bool, double, and int to string is supported.  When matching severity number, a minimum log severity can be used and any values equal to or greater than the severity match.  You can also specify if an undefined severity number can be match.

The OTTL has access to all of these fields for logs.  Like before, regex matching will need to be improved to handle type conversion.  The OTTL supports inequalities and the severity number ENUMS so it can handle the existing severity number logic.

**Comment by TylerHelmuth** [comment]
When filtering metrics the filter processor configuration allows matching by metric name, resource attributes and datapoint attributes via expressions.  When checking attributes, converting attribute values from bool, double, and int to string is supported.  The expression allows for checking a datapoint's attribute value or the presence of an attribute.  If any datapoint within a metric matches then the entire metric is dropped.

The OTTL has access to all of these fields.  Like before, regex matching will need to be improved to handle type conversion. The OTTL metric context has access to the datapoints for the metric, but there are not any functions that can check the attributes of these data points.  The datapoint context has access to the datapoint attributes, but there is no way to drop the entire metric if a single datapoint matches.

**The OTTL will need to be able to handle an ottlmetric condition that can check individual attributes.**

**Comment by bogdandrutu** [comment]
I agree about the "OTTL needs to be able to perform regex where the input is converted to the string if it is a bool, int, or double.".

I do understand the difference between include/exclude which were added because we could not do "!=" in the filters language. But we the current OTTL this seem reasonable to me `'resource.attributes["service.name"] != "app_3"'`.

"The OTTL will need to be able to handle an ottlmetric condition that can check individual attributes." this may be very hard, let's focus on the first 2 first.

**Comment by TylerHelmuth** [comment]
@bogdandrutu with negation and the IsMatch updates I believe we've covered the first 2 gaps. 

How do you want to handle the third? A function could be made specifically for the metric context that can use the datapoints accessor and loop through looking for the specified attributes.

**Comment by TylerHelmuth** [comment]
All gaps have been addressed.  Old configs can now be deprecated.
