### ISSUE TITLE
[metrics builder] Non-string support for enum attributes

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#16419]
Currently, only strings can be specified in [`attribute.enum` field](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/mdatagen/metric-metadata.yaml#L28). We need a way to set different enum values when type is not a string. The type must be validated against the [`type` field](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/mdatagen/metric-metadata.yaml#L30). Must be applicable to both metric attributes and resource attributes.

**Comment by abhide** [comment]
@dmitryax I would like to work on this issue. Can you please assign it to me?

**Comment by dmitryax** [comment]
@abhide, thanks! Assigned
