### ISSUE TITLE
[kafkaexporter] Failed authentication with /INTERNAL_IP

### ISSUE THREAD

**Issue by gfes980615** [open-telemetry/opentelemetry-collector-contrib#16426]
### Component(s)

exporter/kafka

## Description
I got the error message on the broker logs
```
INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] 
Failed authentication with /INTERNAL_IP (Unexpected Kafka request of type METADATA during SASL handshake.) 
(org.apache.kafka.common.network.Selector)
```
## Steps to Reproduce
1. Use AWS MSK
2. Set the IAM authentication type
3. Execute otel collector
## Expected Result
otel collector can start success
## Actual Result
otel collector start failed

### Collector version

v0.64.0

### OpenTelemetry Collector configuration

```yaml
exporters:
  kafka:
    brokers:
      - <broker>:9098
      - <broker>:9098
      - <broker>:9098
    protocol_version: 2.8.1
```

### Log output

```shell
INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] 
Failed authentication with /INTERNAL_IP (Unexpected Kafka request of type METADATA during SASL handshake.) 
(org.apache.kafka.common.network.Selector)
```

### Additional context

According the error message I set `metadata.full` to `false` like following configuration, it can start successfully!
```yaml
exporters:
  kafka:
    brokers:
      - <broker>:9098
      - <broker>:9098
      - <broker>:9098
    protocol_version: 2.8.1
    topic: otlp_span
    metadata:
      full: false
```

Is this a kind of bug?
Will any concerned when I set the `metadata.full` to **false** ? (default is **true**)

**Comment by MovieStoreGuy** [comment]
Thank you for reporting the issue, I believe this issue comes from the fact that the underlying library doesn't official support SASL auth and the approach taken doesn't work.

As a workaround, you will need to use a different auth mechanism to be able to use this exporter.
