### ISSUE TITLE
Support for query and transaction percentile-latency statistics

### ISSUE THREAD

**Issue by architjugran** [open-telemetry/opentelemetry-collector-contrib#16430]
### Component(s)

receiver/googlecloudspanner

### Is your feature request related to a problem? Please describe.

Recently Cloud Spanner Stats tables added [Latency distributions](https://cloud.google.com/spanner/docs/release-notes#September_28_2022) which made possible to see the percentiles of latencies using the SPANNER_SYS.DISTRIBUTION_PERCENTILE GoogleSQL function.
Our customers have been demanding the ability to view 50th, 95th, 99th percentile latencies on our OpenTelemetry's receiver too.

### Describe the solution you'd like

Solution is to simply enhance the list of columns of the Spanner stats tables, which are queried by the receiver component.

**Comment by architjugran** [comment]
I am unable to find the option to edit labels. 

I want to remove the "needs triage" label and add the "receiver/googlecloudspanner" label

**Comment by fatsheep9146** [comment]
resolve by #16429
