### ISSUE TITLE
Change the hashing algorithm for probabilistic sampler

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#16456]
In the probabilistic sampler, we seem to use a hashing algorithm of our own, instead of relying on a library to do so, as it's done in other modules. We should try to follow the guideline we have on this:

https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#recommended-libraries--defaults

_Originally posted by @MovieStoreGuy in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14920#discussion_r1019684154_

**Comment by moonbox3** [comment]
I'd like to work on this issue, if possible. I'm new to the project and will spend time time wrapping my head around things. I'll most likely come back with questions.

**Comment by fatsheep9146** [comment]
@moonbox3 It's yours! Thanks!

**Comment by moonbox3** [comment]
Created the PR for this [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17837).

**Comment by jpkrohling** [comment]
Thank you!
