### ISSUE TITLE
[gh-actions] build-package jobs are failing on the ubuntu-22.04 runners

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#16450]
GitHub actions runner `ubuntu-latest` tag was recently upgraded from Ubuntu 20.04.5 to Ubuntu 22.04.1.

The `build-package` job is failing now. We need to investigate and update it to work on the latest Ubuntu version.

Failing job examples:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3528442298/jobs/5918829725#logs
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3528442298/jobs/5918829832

**Comment by jlabatut** [comment]
Hi, is this issue still open ? If so, can I be assigned to it ?
(Also, the jobs log examples have expired)

**Comment by jlabatut** [comment]
Hi @dmitryax, is this issue still open ? If so, can I be assigned to it ?
(Also, the jobs log examples have expired)

**Comment by dmitryax** [comment]
@jlabatut, thanks for offering help!

**Comment by bogdandrutu** [comment]
Fixed on 22.05

**Comment by TylerHelmuth** [comment]
This issue is not solved yet

**Comment by cwegener** [comment]
Are there any examples of the failures? The original links that Dmitrii posted are expired and there's no way to see the failures.

**Comment by TylerHelmuth** [comment]
Here is one: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7266701238/job/19799801676

**Comment by cwegener** [comment]
Thanks. I guess this comment is related to the failure too?

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23816#issuecomment-1787437956

> No there was an issue w/ cgroups permission + docker socket in the latest ubuntu. I tested some workaround but couldn't get it to work. I'm guessing we may need to change how rpm/deb packages are built in this repo if we want to see it work....

> an alternative i hadn't thought about until just now would be to change those workflows to use the goreleaser since that's what we use in the releases repo anyways.

**Comment by cwegener** [comment]
Ok. I understand now.

It's the "running SystemD inside of a container" part that is currently broken during the testing stage of the .deb and .rpm packages.

**Comment by cwegener** [comment]
I published a fix in #30202
