### ISSUE TITLE
Create opamp extension

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#16462]
See [design document](https://docs.google.com/document/d/1KtH5atZQUs9Achbce6LiOaJxLbksNJenvgvyKLsJrkc/edit#heading=h.ioikt02qpy5f).

Depends on:
- https://github.com/open-telemetry/opentelemetry-collector/issues/6596
- https://github.com/open-telemetry/opentelemetry-collector/issues/6599

Todo
- [x] #16618
- [x] #16619
- [x] open-telemetry/opentelemetry-collector-contrib#32452
- [x] #27293
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29277

_Edit (by Evan): more comprehensive health reporting will be tracked by this issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32304_

**Comment by tigrannajaryan** [comment]
@open-telemetry/collector-contrib-approvers is anyone interested in being the sponsor for this component?

I believe @portertech is interested in implementing it (provided we agree on the design) and I am happy to be a co-owner of the extension and will also review the PRs.

**Comment by evan-bradley** [comment]
I'll sponsor this.

**Comment by dmitryax** [comment]
I can help with reviewing PRs. @portertech feel free to ping me as well

**Comment by pavankrish123** [comment]
Thanks for starting this @tigrannajaryan and @dmitryax. Are we planning this to implement this as an extension or as a config provider?

**Comment by portertech** [comment]
@tigrannajaryan To confirm, the extension will now live in contrib and not in the collector itself? I'll move my WIP if that's the case 👍

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan To confirm, the extension will now live in contrib and not in the collector itself? I'll move my WIP if that's the case 👍

contrib is probably a better place, @open-telemetry/collector-maintainers WDYT?

**Comment by codeboten** [comment]
i'd assume that in the future this would become a core component, but for now i think it's ok for it to live in contrib. there are other components I imagine will likely move from contrib to core in the future (jaeger/zipkin/prometheus receivers/exporters)

**Comment by evan-bradley** [comment]
The extension is now at alpha stability and is in the contrib distro, so I think we can say it is in a good state.

**Comment by MSA0208** [comment]
Hi have tried the same steps given by you @brightzheng100 ,
but getting the below error, i tried starting the server from /root/OTEL98/opamp-go-main/internal/examples/server and it started and when i tried the extension from my collector getting below error
extensions:
opamp:
server:
ws:
endpoint: wss://127.0.0.1:4321/v1/opamp
tls:
insecure_skip_verify: false # Set to true if you're using self-signed certificates
ca_file: "/root/certs/sac-hvm03662.swinfra.net.pem"

error opampextension@v0.98.0/logger.go:26 Connection failed (tls: first record does not look like a TLS handshake), will retry. {"kind": "extension", "name": "opamp", "client": "ws"}

The Other way i tried was , started the opampsupervisor from /root/OTEL98/opentelemetry-collector-contrib-main/cmd/opampsupervisor using the command ./opampsupervisor --config supervisor.yaml and my yaml is below
OpAMP backend server settings.
server:
endpoint: wss://127.0.0.1:4320/v1/opamp
tls:
insecure_skip_verify: true

capabilities:
accepts_remote_config: true # false if unspecified

reports_effective_config: true # true if unspecified

accepts_packages: true # false if unspecified

reports_own_metrics: # true if unspecified

reports_own_logs: # true if unspecified

accepts_other_connection_settings: true # false if unspecified

accepts_restart_command: true # true if unspecified

reports_health: true # true if unspecified

storage:
agent:
executable: /root/OTEL98/opentelemetry-collector-contrib-main/cmd/otelcontribcol/OutputBinaries/NGxConnector

args: --config /root/OTEL98/opentelemetry-collector-contrib-main/cmd/otelcontribcol/config.yaml

env:

run_as: root
config_file: /root/OTEL98/opentelemetry-collector-contrib-main/cmd/otelcontribcol/config.yaml
access_dirs:
read:
allow: [/var/log]
deny: [/var/log/secret_logs]
write:
allow: [/var/otelcol]
am getting the error below,
[root@sac-hvm03662 opampsupervisor]# ./opampsupervisor --config supervisor.yaml
2024-05-07T10:40:22.536-0700 DEBUG commander/commander.go:74 Starting agent {"agent": "/root/OTEL98/opentelemetry-collector-contrib-main/cmd/otelcontribcol/OutputBinaries/NGxConnector"}
2024-05-07T10:40:22.537-0700 DEBUG commander/commander.go:93 Agent process started {"pid": 63200}
2024-05-07T10:40:25.540-0700 ERROR opampsupervisor/main.go:31 Failed to initialize supervisor {"error": "could not get bootstrap info from the Collector: collector's OpAMP client never connected to the Supervisor"}
main.main
/root/OTEL98/opentelemetry-collector-contrib-main/cmd/opampsupervisor/main.go:31
runtime.main
/usr/local/go/src/runtime/proc.go:271

please help me out to solve these issues

**Comment by mx-psi** [comment]
@MSA0208 please file a separate issue for this, thanks! This issue has been completed and is about creating the extension
