### ISSUE TITLE
[exporter/clickhouse] Sent metrics to clickhouse

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#16478]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

support sent metrics to clickhouse.

### Describe the solution you'd like

Clickhouse exporter receives metrics from the pipeline and inserts them into different clickhouse tables by metrics type.

current support metrics type:
- sum
- gauge
- histogram
- exponential histogram
- summary

**Comment by JaredTan95** [comment]
@Frapschen from your description, seems you already implemented this feature?

**Comment by Frapschen** [comment]
> @Frapschen from your description, seems you already implemented this feature?

yes, but need more test.

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16477
