### ISSUE TITLE
Add health endpoint to Splunk HEC exporter

### ISSUE THREAD

**Issue by omrozowicz-splunk** [open-telemetry/opentelemetry-collector-contrib#16479]
### Component(s)

exporter/splunkhec

### Is your feature request related to a problem? Please describe.

Splunk HEC has an API health endpoint `/services/collector/health`, which returns `200` if the service is up. Currently, we don't make use of that in the exporter, we only send a chunk of data and observe if it was successful or not. 
Would be good to run one call to the health endpoint when the exporter starts, before we process the data.

### Describe the solution you'd like

The `/services/collector/health` should be configurable (as there is an option to do that in Splunk HEC), and the GET request to that API would be inserted before `pushLogData`, `pushMetricsData`, `pushTracesData`,  in `sync.Once`, so that the request would be done only once. If it fails, `consumererror` should be returned.

**Comment by atoulme** [comment]
Is there any more work on this issue? Can it be closed at this time?

**Comment by omrozowicz-splunk** [comment]
@atoulme no, no more work is required. It can be closed.
