### ISSUE TITLE
Azure Data Explorer Exporter Stability

### ISSUE THREAD

**Issue by tmeadon** [open-telemetry/opentelemetry-collector-contrib#16486]
### Component(s)

exporter/azuredataexplorer

### Describe the issue you're reporting

This is more of a question than an issue to be honest.  I’ve come across the Azure Data Explorer exporter and it looks like it will be perfect for a project I’m currently scoping out for a customer.

I can see it’s currently in alpha - are you able to give me a sense of when it might be ‘production ready’ please?  I’d also be interested to know what else needs to happen before this exporter can be marked as stable, and if I can help out in any areas 👍

**Comment by ag-ramachandran** [comment]
@tmeadon , thanks for reaching out.This was the first release we made for the component & hence the default was chosen as alpha to initially look at adoption. We will make this into stable soon with internal changes that we are doing on the GO-SDK internally (for migration to MSAL). This however should have no effect on using in Production. We have some customers who are trying this in production currently & thus far we have not heard back of any limitations.

**Comment by tmeadon** [comment]
That's great news!  Thanks for clarifying.
