### ISSUE TITLE
[processor/filter] OTTL config field does not match example 

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/opentelemetry-collector-contrib#16488]
### Component(s)

processor/filter

## Description
 Filter processor [OTTL config section](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#ottl) has a table that lists `spans.span` as the correct config field for `Span` context. . The sample shown has `traces.span` instead though. The table also lists `logs.log` but the example shows `logs.log_record`. 

This may also be a misunderstanding related to the docs but I had that the `config -> ottlcontext` was supposed to represent the necessary config fields for the filter processor. 

### Collector version

latest

## Environment
Docs

**Comment by TylerHelmuth** [comment]
I can fix the README tomorrow.
