### ISSUE TITLE
[Exporter/loki] include InstrumentationScope to Log object

### ISSUE THREAD

**Issue by AlexLi88** [open-telemetry/opentelemetry-collector-contrib#16485]
### Component(s)

exporter/loki

### Is your feature request related to a problem? Please describe.

Currently, the `InstrumentationScope` object is not being include in the Loki logs object, can we add this feature to include this object in the log data. 

### Describe the solution you'd like

Better user experience, user can query logs by Java class name. Also this is nice to have since the `InstrumentationScope` object is provided by opentelemetry.

**Comment by jpkrohling** [comment]
Sounds like a good idea. @mar4uk, what do you think?

**Comment by mar4uk** [comment]
agree, sounds good. @AlexLi88 would you like to create a PR?

**Comment by AlexLi88** [comment]
Not a go expert, but I can take a look on it.

**Comment by mar4uk** [comment]
no worries, I will take care of this issue then :)

**Comment by mar4uk** [comment]
this issue is fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17071
