### ISSUE TITLE
[exporter/datadog] Metrics not getting exported 

### ISSUE THREAD

**Issue by mwei0210** [open-telemetry/opentelemetry-collector-contrib#16527]
### Component(s)

exporter/datadog

## Description
I have a go microservice with multiple pods sitting in k8s with `service.instance.id` set and sending metrics to otel collector sitting in same cluster, the otel collector is having OTLP>Batch>Datadog&Logging&awsemf pipeline for metrics. In logging I could see all the metrics from microservices in logging exporter like below, but datadog didn't get all these metrics

## Steps to Reproduce
running micriservices with multiple pods sending metrics to otel collector

## Expected Result
metrics showing in datadog

## Actual Result
metrics showed in logging&awsemf exporter, but not in datadog

### Collector version

0.66.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  exporters:
    datadog:
      api:
        key: ${dd_api_key}
    logging:
      loglevel: debug

  processors:
    batch:
      # Datadog APM Intake limit is 3.2MB. Let's make sure the batches do not
      # go over that.
      send_batch_max_size: 1000
      send_batch_size: 100
      timeout: 10s

  service:
    pipelines:
      metrics:
        receivers: 
          - otlp
        processors: 
          - batch
        exporters: 
          - datadog
          - logging
```

### Log output

```shell
Resource SchemaURL: https://opentelemetry.io/schemas/1.11.0
Resource attributes:
     -> deployment.environment: Str(production)
     -> service.instance.id: Str(myservice-76dc57dc5b-tqtmw)
     -> service.name: Str(myservice)
     -> service.namespace: Str(acr)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope feedback 
Metric #0
Descriptor:
     -> Name: proxy.matching_response
     -> Description: match response from matching server to proxy
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> type: Str(match)
StartTimestamp: 2022-11-29 19:09:37.732666977 +0000 UTC
Timestamp: 2022-11-29 20:22:37.73460628 +0000 UTC
Value: 22257
NumberDataPoints #1
Data point attributes:
     -> type: Str(no_match)
StartTimestamp: 2022-11-29 19:09:37.732666977 +0000 UTC
Timestamp: 2022-11-29 20:22:37.73460628 +0000 UTC
Value: 17192
Metric #1
Descriptor:
     -> Name: proxy.category_match
     -> Description: category match response to TV
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> type: Str(no_match)
StartTimestamp: 2022-11-29 19:09:37.732691538 +0000 UTC
Timestamp: 2022-11-29 20:22:37.734624829 +0000 UTC
Value: 17132
NumberDataPoints #1
Data point attributes:
     -> type: Str(match)
StartTimestamp: 2022-11-29 19:09:37.732691538 +0000 UTC
Timestamp: 2022-11-29 20:22:37.734624829 +0000 UTC
Value: 17076
Metric #2
Descriptor:
     -> Name: proxy.matching_response_time
     -> Description: matching response time
     -> Unit: microseconds
     -> DataType: Histogram
     -> AggregationTemporality: Cumulative
HistogramDataPoints #0
StartTimestamp: 2022-11-29 19:09:37.732708568 +0000 UTC
Timestamp: 2022-11-29 20:22:37.734628301 +0000 UTC
Count: 39449
Sum: 6836476246.000000
Min: 3496.000000
Max: 3487687.000000
ExplicitBounds #0: 0.000000
ExplicitBounds #1: 5.000000
ExplicitBounds #2: 10.000000
ExplicitBounds #3: 25.000000
ExplicitBounds #4: 50.000000
ExplicitBounds #5: 75.000000
ExplicitBounds #6: 100.000000
ExplicitBounds #7: 250.000000
ExplicitBounds #8: 500.000000
ExplicitBounds #9: 750.000000
ExplicitBounds #10: 1000.000000
ExplicitBounds #11: 2500.000000
ExplicitBounds #12: 5000.000000
ExplicitBounds #13: 7500.000000
ExplicitBounds #14: 10000.000000
Buckets #0, Count: 0
Buckets #1, Count: 0
Buckets #2, Count: 0
Buckets #3, Count: 0
Buckets #4, Count: 0
Buckets #5, Count: 0
Buckets #6, Count: 0
Buckets #7, Count: 0
Buckets #8, Count: 0
Buckets #9, Count: 0
Buckets #10, Count: 0
Buckets #11, Count: 0
Buckets #12, Count: 70
Buckets #13, Count: 1041
Buckets #14, Count: 2687
Buckets #15, Count: 35651
ScopeMetrics #1
ScopeMetrics SchemaURL: 
InstrumentationScope matching 
Metric #0
Descriptor:
     -> Name: proxy.request_consumed
     -> Description: match request into proxy
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
StartTimestamp: 2022-11-29 19:09:37.732724992 +0000 UTC
Timestamp: 2022-11-29 20:22:37.734632994 +0000 UTC
Value: 16015
Metric #1
Descriptor:
     -> Name: proxy.matching_request
     -> Description: match request from proxy to matching server
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
StartTimestamp: 2022-11-29 19:09:37.732734432 +0000 UTC
Timestamp: 2022-11-29 20:22:37.734635183 +0000 UTC
Value: 16015
```
```


### Additional context

_No response_

**Comment by mx-psi** [comment]
Hi @mwei0210 are you missing all metrics or only some of them? If only some, what are the names? Additionally, for how long and how many points are you sending in your timeseries (if you know)?

**Comment by mwei0210** [comment]
It's inconsistent, sometimes everything is missing, sometimes only those under `InstrumentationScope matching`, i would see metrics after a restart sometimes, then stopped seeing it sometime after that. How do i check how long and number of points that I am sending in? I am using the default setting that comes under otel go api.

**Comment by mx-psi** [comment]
One possibility is that the SDK is frequently resetting the internal cumulative counters or that your application has frequent restarts, this would make the Datadog exporter have to reset its internal cache and lose points. To remove this possible issue, you can configure your SDK to use delta aggregation temporality instead; I can provide a code example on how to do this if you tell me the OTel Go SDK version you are using.

Let's try changing this first and we can come back to check the actual data you are sending and the expected output for it.

**Comment by mwei0210** [comment]
Let's do that, I am using `v0.33.0`

**Comment by mx-psi** [comment]
Alright, then you have to use the `metric.WithTemporalitySelector` option when building the reader. Here is a MWE:

<details>
<summary>Example Go program setting temporality selector to delta (click to expand)</summary>

```go
package main

import (
	"context"
	"log"

	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"
	"go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/view"
)

func main() {
	ctx := context.Background()
	exp, err := otlpmetrichttp.New(ctx)
	if err != nil {
		log.Fatalln(err)
	}

	reader := metric.NewPeriodicReader(
		exp,
		// This is the important line: specify the temporality selector
		metric.WithTemporalitySelector(func(_ view.InstrumentKind) metricdata.Temporality { return metricdata.DeltaTemporality }),
	)

	meterProvider := metric.NewMeterProvider(
		metric.WithReader(reader),
	)

	defer func() {
		err := meterProvider.Shutdown(context.Background())
		if err != nil {
			log.Fatalln(err)
		}
	}()

	// Use meterProvider here
}
```
</details>

**Comment by mwei0210** [comment]
Thanks! I am seeing metrics showing up on dashboard now, but both instrument scope has different points and frequency, but if I add up the point in the same period, both match around the same count (which is expected to be so), how do I sum&match their points and interval, say a minute? Is that done in collector or the datadog dashboard? Your analysis seemed to be right where I shouldn't be using cumulative but delta..

**Comment by mx-psi** [comment]
Awesome, glad that worked :) 

> how do I sum&match their points and interval, say a minute?

On the OTel side you can configure your Reader's collection interval to be a minute. For instruments with sum aggregation semantics (e.g. a Counter) this should give you the sum of your instrument's measurements every minute.

You can also customize Datadog's in-app aggregation through the [`rollup`](https://docs.datadoghq.com/dashboards/functions/rollup/) function.

Depending on how your application is configured and how closely the intervals match the numbers may not line up 100% but you can get closer to a fair comparison by leveraging those two tools.

**Comment by mwei0210** [comment]
I am able to match the numbers up nicely now! Thanks @mx-psi , you have been a great help!
