### ISSUE TITLE
Upgrade doublestar on pkg/stanza

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#16528]
### Component(s)

pkg/stanza

### Is your feature request related to a problem? Please describe.

pkg/stanza uses [doublestar v](https://github.com/bmatcuk/doublestar) v3 which has been released a while ago.

### Describe the solution you'd like

v4 has been out for a little while, featuring better performance and fixes for Windows.

**Comment by djaglowski** [comment]
Assuming there are no breaking changes to the syntax, this sounds like a welcome improvement.

**Comment by atoulme** [comment]
Feels like a good ticket for someone to get started with OpenTelemetry - there should be enough test coverage to detect regressions, right?
