### ISSUE TITLE
[processor/servicegraph] Different Metric Name with specification

### ISSUE THREAD

**Issue by jjmm0312** [open-telemetry/opentelemetry-collector-contrib#16578]
### Component(s)

processor/servicegraph

## Description
Metric Name is different with specification.

service graph processor specification : https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/servicegraphprocessor#metrics
tempo specification : https://grafana.com/docs/tempo/latest/metrics-generator/service_graphs/#metrics

## Expected Result
traces_service_graph_request_server_seconds
traces_service_graph_request_client_seconds

## Actual Result
traces_service_graph_request_duration_seconds
(https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/servicegraphprocessor/processor.go#L412)

### Collector version

v0.66.0

**Comment by sherifkayad** [comment]
@jjmm0312 I can also confirm that this is the case on my end .. The following metrics are the ones exported:
- `traces_service_graph_request_total`
- `traces_service_graph_request_duration_seconds_sum`
- `traces_service_graph_request_duration_seconds_count`
- `traces_service_graph_request_duration_seconds_bucket`

With the following being missing (as per the spec):
- `traces_service_graph_request_failed_total`
- `traces_service_graph_request_server_seconds`
- `traces_service_graph_request_client_seconds`
- `traces_service_graph_unpaired_spans_total`
- `traces_service_graph_dropped_spans_total`

**Comment by jpkrohling** [comment]
@mapno, are you able to take a look at this one?

**Comment by mapno** [comment]
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18743.

**Comment by mapno** [comment]
I'll open a PR with the proposal from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18743#issuecomment-1453800781

**Comment by sherifkayad** [comment]
keep alive I guess ..

**Comment by jpkrohling** [comment]
This has been addressed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21098.
