### ISSUE TITLE
New component: crash report extension

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#16598]
### The purpose and use-cases of the new component

When the collector crashes, it prints information to stdout and stderr which might be useful to capture.

the crash report extension would consist in a module recovering from panics, sending data to a remote location, and then exiting as it does now.

### Example configuration for the component

```
extensions:
  crashreport:
    endpoint: http://www.example.com
```

Additionally, this extension can be enabled through a cli parameter such as —crashreport=http://www.example.com

### Telemetry data types supported

None.

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

**Comment by dmitryax** [comment]
How the reporting protocol will be implemented? Is there some standardized protocol for crash reporting or each endpoint provider will be added separately added as a "plugin" to the extension?

> Additionally, this extension can be enabled through a cli parameter such as —crashreport=http://www.example.com/

Why is this needed? We've been going away from CLI arguments and migrated all the cli args to the config

**Comment by atoulme** [comment]
I'm not aware of a standardized crash report protocol. My intent is to send a report of the error as recovered from a panic, printed out as a block of text. We can iterate over this design as we learn more.

In my mind, this crash report tool specifically addresses panics using a `recover` listener registered in a goroutine on start of the extension. See https://gobyexample.com/recover for context. 


The only reason you'd want CLI is if the crash happens during the config load. I think we can leave that out of scope for now and look into it again. Maybe CLI is not the right approach, env vars, whatever makes the most sense. But maybe for now keep the scope small.

**Comment by atoulme** [comment]
This is very early, and authentication would make sense. Initially, I thought I'd allow sending to a public HTTP server accepting POST requests and leave it that simple for now. The HTTP server would need to build some level of protection.

If we add auth, we could target a Splunk HEC raw endpoint to ingest data next.

Again, I'm proceeding with very small steps and with as small a scope as possible so others get a chance to chime in, offer better solutions. I know there are crash report solutions out there - a quick google turns up vendors like backtrace.io, or see this article with quite a few options: https://raygun.com/blog/best-ios-crash-reporting-tools/

**Comment by atoulme** [comment]
Now that I dug more into the utilities offered by the collector helpers, I think we can get a http client using HTTPClientSettings to get a client that supports auth, proxies and anything else we want to have supported. This will allow us to set authentication.

**Comment by mx-psi** [comment]
Who is the sponsor of this component?

**Comment by atoulme** [comment]
It could be you! There’s no sponsor yet :)
