### ISSUE TITLE
Create opamp extension component

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#16618]
This is just to create the extension boilerplate (Start/Stop/etc). The meat of the opamp functionality is captured in other issues linked from the [summary item](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16462).

**Comment by atoulme** [comment]
Would you please indicate if this issue is being worked by a contributor, or if you're looking for someone to contribute this extension?

**Comment by tigrannajaryan** [comment]
There is a [draft](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16594) from @open-telemetry/build-tools-approvers

**Comment by tigrannajaryan** [comment]
@evan-bradley you are working on OpAMP generally, right? So we want to keep this open I guess?

**Comment by evan-bradley** [comment]
Yeah, I'm working on it generally within the Collector. I'd agree, let's keep this open as the first step for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16462.
