### ISSUE TITLE
make generate-gh-issue-templates

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#16721]
### Component(s)

scripts

### What happened?

Does not produce the same result using macOS `sed` command. That is a bit different than gnu-sed, but lots of devs are using macOS, so would be good to fix.

Concrete: It does not remove the prefix, so will generate `receiver/mongodbreceiver` instead of `receiver/mongodb`.

### Collector version

head

**Comment by bogdandrutu** [comment]
If I replace the "gnu-sed" here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/scripts/add-component-options.sh#L46 (install `brew install gnu-sed` then replace sed with gsed) everything works as expected.

**Comment by evan-bradley** [comment]
Thanks for the detailed report. I'll see if there's something else we can use that is more portable.
