### ISSUE TITLE
Root span logic in the tailsampling processor

### ISSUE THREAD

**Issue by afishler** [open-telemetry/opentelemetry-collector-contrib#16730]
### Component(s)

processor/tailsampling

### Is your feature request related to a problem? Please describe.

The tail sampling processor offers a reach set of logic functionality. The building blocks are highly technical and it is sometimes quite hard to translate them to complex use cases that make sense for users.

For example - if I want to sample a specific service by 50% and a different service by 30% I can create a policy that seems straightforward:

```
tail_sampling:
    policies:
      [
        {
          name: service-a-traces,
          type: and,
          and: {
            and_sub_policy:
            [
              {
                name: service-a,
                type: string_attribute,
                string_attribute: { key: service.name, values: [ "service-a" ]}
              },
              {
                name: probability-policy-1,
                type: probabilistic,
                probabilistic: {sampling_percentage: 50}
              }
            ]
          }
        },
        {
          name: service-b-traces,
          type: and,
          and: {
            and_sub_policy:
            [
              {
                name: service-b,
                type: string_attribute,
                string_attribute: { key: service.name, values: [ "service-b" ]}
              },
              {
                name: probability-policy-2,
                type: probabilistic,
                probabilistic: {sampling_percentage: 30}
              }
            ]
          }
        }
      ]
```

The fact is that setting probability values on different services does not ensure a certain percentage because ALL rules are evaluated and since the decisions include full traces, spans from different services may be sampled by these rules resulting in a percentage that is not absolute.

It seems very useful to have logic that allows setting a condition that will only be applied on "root spans". Currently this is not available for the processor.

Root spans are set by checking that the field parentSpanId that exists for every span is empty (""). Currently there is no logic item in the processor that checks for it

### Describe the solution you'd like

Add a rule type that will check for root span existance:

`{
      name: test-policy-8,
      type: root_span
  }`

### Describe alternatives you've considered

I checked for all the current rules if they cover the parentSpanId field - found that Attributes (used for string_attribute) is not considering this field, also checked for trace_state.

Examined also the possibility to use the attribute processor to add it in some way that will make it available. This is an awkward way in any case but nevertheless I could not find an easy way to add it.

Adding a processor that checks on is quite simple

**Comment by jpkrohling** [comment]
I think I understood what you meant, but there are a couple of places that confused me a bit. Like:

> Add a rule type that will check for root span existance:

This could mean that traces with a root span will be accepted (as in, the root span was not lost mid-flight).

I think your proposal has value, but I would like you to enhance it by adding config examples and the expected outcomes.

**Comment by jpkrohling** [comment]
I'm closing this. If there's still interest in working on this, feel free to reopen.
