### ISSUE TITLE
loadbalancingexporter: periodicallyResolve don't work as expected

### ISSUE THREAD

**Issue by ZhengHe-MD** [open-telemetry/opentelemetry-collector-contrib#1677]
**Describe the bug**

`periodicallyResolve` will only resolve the dns once, and the ip addresses won't change thereafter.

**Steps to reproduce**

very easy. just add logs to `periodicallyResolve` method in `exporter/loadbalancingexporter/resolver_dns.go`, you will see that only run once.

**What did you expect to see?**

dnsResolver will request the dns server periodically

**What did you see instead?**

only one resolution

**What version did you use?**
Version: 170cac0bc1eded767efcc418269b42b3ca61bc8a

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS:  macOS
Compiler(if manually compiled): go 1.14

**Additional context**

I've already fixed this locally, just add the for loop : ). I'll be glad to open a PR for this, to both fix the logic and the unit test.

**Comment by ZhengHe-MD** [comment]
@jpkrohling please have a look when you're convenient.

**Comment by jpkrohling** [comment]
Interesting, I do remember fixing this during the PR reviews. I remember testing it using coredns locally to play with the DNS changes and confirmed that it worked, but perhaps that change went missing... In any case, as you have a PR and the unit test, feel free to submit it!
