### ISSUE TITLE
Result `make generate-gh-issue-templates` is not aligned with the current components list

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#16801]
We need to update the list and investigate why https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/551e5c97b32588c33a3852f2635052813e727c2e/.github/workflows/build-and-test.yml#L186 is not blocking the CI

**Comment by dmitryax** [comment]
@evan-bradley can you please help with this?

**Comment by dmitryax** [comment]
Looks like CI check is actually good, but I'm getting different result from `make generate-gh-issue-templates` locally

**Comment by evan-bradley** [comment]
@dmitryax What does your local setup look like? I've opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16766 to fix issues with the Make target on macOS.

**Comment by dmitryax** [comment]
Yes, I'm using MacOS. Sory missed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16721. Closing this one a s a duplicate
