### ISSUE TITLE
New component: HAProxy receiver

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#16829]
### The purpose and use-cases of the new component

HAProxy offers useful statistics.
We have a haproxy collectd monitor that is currently able to poll metrics by calling out to a socket exposed by haproxy, sending commands and parsing its output:
https://github.com/signalfx/collectd-haproxy

I would like to offer an OpenTelemetry native replacement.

### Example configuration for the component

```
haproxy:
  socket: /var/run/haproxy

```

### Telemetry data types supported

metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

**Comment by MovieStoreGuy** [comment]
I am happy to sponsor this one since my team's would appreciate a replacement, though I don't have a lot of time within this calendar year to be able to help get this out.

**Comment by atoulme** [comment]
Thanks @MovieStoreGuy !

**Comment by atoulme** [comment]
Closing as the component is accepted. Will open further issues for development.
