### ISSUE TITLE
[exporter / newrelicexporter] Add support for queued retries

### ISSUE THREAD

**Issue by jodeev** [open-telemetry/opentelemetry-collector-contrib#1695]
Queued_retry processor is being deprecated: https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor/queuedprocessor

The recommendation is to use the exporter queue and retry options, but that doesn’t seem to have been coded in yet to the newrelicexporter.

See an exporter conf that has implemented it: https://github.com/open-telemetry/opentelemetry-collector/blob/cb6014387d166b69dd7580002752ecd78a1ace2b/exporter/kafkaexporter/config.go#L28

... vs. newrelic: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3404d16495a832ae85b043a83e502d180b4f6f7a/exporter/newrelicexporter/config.go#L26

**Comment by jodeev** [comment]
@MrAlias

**Comment by juldou** [comment]
is there any workaround till the feature will be implemented?
