### ISSUE TITLE
Issue/PR auto-assign is making us miss contributions

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-collector-contrib#1698]
**Describe the bug**

We have seen on a number of occasions where the auto-assign feature combined with CODEOWNERS does not notify all parties of a new issue / PR, against a sub-directory we should be. Myself, @paulosman & @lizthegrey are all in the CODEOWNERS file alongside the @open-telemetry/collector-contrib-approvers, for the Honeycomb exporter but the auto-assign feature picks someone from the overall group.

This has lead to a number of PRs being submitted, approved & merged without our knowledge:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/291
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1162

And most recently: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1689
(@bogdandrutu did catch this after the fact, but it shouldn't be on an individual to remember / fix retrospectively)

I did originally raise this as part [this issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1339#issuecomment-721944848) as there was some discussion around too many people getting notified.

**Comment by mx-psi** [comment]
We (@mx-psi, @ericmustin and @KSerrania) are having similar issues with PRs made against the Datadog exporter.

**Comment by bogdandrutu** [comment]
Any solution?

**Comment by MikeGoldsmith** [comment]
I think we need to review the auto-assign feature being used to select an individual from the pool of reviewers. Ideally it would pick one from the (first) **collector-contrib-approvers** team, and subsequent entries in the CODEOWNERS file ass approvers. However, I'm not sure that is possible.

An alternative would be manual process, where whenever any PR that directly affects a vendor managed exporter, there should be approvable from them first.

The fallback solution, would be to disable the auto-assign feature to ensure all participants in the CODEOWNERS file are notified.

**Comment by mx-psi** [comment]
> The fallback solution, would be to disable the auto-assign feature to ensure all participants in the CODEOWNERS file are notified.

I don't think this would work for this repo, Github docs [say](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners)

> "The people you choose as code owners must have write permissions for the repository."

which would not be the case here.

**Comment by MikeGoldsmith** [comment]
Interesting, so CODEOWNERS only works with users who have write permissions.

With that in mind, I think a general process of getting approval from a vendor contributor should be required before merging, alongside an approval from the OTel contrib approvers of course.

**Comment by mx-psi** [comment]
@open-telemetry/collector-contrib-maintainer should we try adding read access to test if notifications work?

**Comment by gbbr** [comment]
Has there been any resolution on this issue? We have a similar problem on the `datadogexporter`, where I am responsible for APM code but I keep missing changes and PRs because of not getting notified, relying on @mx-psi to let me know, which is not a sustainable method. Any chance I could be added to the org and to CODEOWNERS to ensure I see these changes to be able to efficiently maintain this component?

**Comment by mx-psi** [comment]
Thanks to the improvements by @open-telemetry/collector-contrib-triagers I think the only thing missing here is to allow adding the component labels to PRs as well as issues. This would allow approvers/maintainers to more easily ping code owners. I think this would amount to changing the triggering conditions here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/eee0daf88dec900b51df416d1964f6426428a65e/.github/workflows/ping-codeowners.yml#L3-L4

**Comment by evan-bradley** [comment]
This was also requested in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16036 and an implementation for automatically assigning code owners without write access was tested in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14582. I'll take a look into implementing something to help solve this.

**Comment by TylerHelmuth** [comment]
I think the reason my PR falls short is bc it causes us to have to maintain a second CODEOWNERS file essentially to take advantage of existing actions. 

It would be good to try a solution that uses the existing CODEOWNERS file and is able to detect the directory changes in the PR on every push.

**Comment by TylerHelmuth** [comment]
Also I haven't found an existing workflow yet that can automatically assign/request review for CODEOWNERS using the CODEOWNERS file. In general this problem is harder than what we've done for issues bc of the permissions needed to interact with a PR.
