### ISSUE TITLE
[receiver/purefa] Go metrics should be ignored

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#16991]
### Component(s)

receiver/purefa

### What happened?

Currently, the Go metrics are being included in the Pure FA receiver, but should be ignored.

### Collector version

current main

### Additional context

cc @dgoscn

**Comment by chrroberts-pure** [comment]
We could consider creating a ‘include exporter go performance metrics if available’ configuration item that’s off by default.

The problem with these go metrics rarely have context like what endpoint was called since that’s not a label on the exporter. 

I can also see a few cases where these metrics will no longer be exposed in the future. 

If it’s going to take more than 15 minutes to implement the config item; it’s probably not worth it.

**Comment by jpkrohling** [comment]
> go metrics rarely have context like what endpoint was called since that’s not a label on the exporter

We should be able to add more labels there.

**Comment by dgoscn** [comment]
> > go metrics rarely have context like what endpoint was called since that’s not a label on the exporter
> 
> We should be able to add more labels there.

Of course.

**Comment by jpkrohling** [comment]
@dgoscn, is this still in your radar?

**Comment by dgoscn** [comment]
Hey @jpkrohling, yes, of course. I will keep you updated on this issue for this week.

**Comment by james-laing** [comment]
@dgoscn any progress on this?

Since Dynatrace are deprecating their own exporter in favour of the native `otlphttp exporter` the logs are full of errors relating to dropped `go_` metrcis

```
2023-11-13T07:42:57.003-0500    error   exporterhelper/retry_sender.go:145      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "metrics", "name": "otlphttp", "error": "Permanent error: OTLP partial success: The following issues were encountered while ingesting OTLP metrics:\nErrors:\nUnsupported metric: 'go_memstats_mallocs_total' - Reason: UNSUPPORTED_METRIC_TYPE_MONOTONIC_CUMULATIVE_SUM\nUnsupported metric: 'go_gc_duration_seconds' - Reason: UNSUPPORTED_METRIC_TYPE_SUMMARY\nWarnings:\nMetric key too short - normalized from: 'up' to: 'up_' - Reason: METRIC_KEY_TOO_SHORT\n (2 rejected)", "dropped_items": 100}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/retry_sender.go:145
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
        go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/metrics.go:176
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).start.func1
        go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/queue_sender.go:126
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start.func1
```

**Comment by jpkrohling** [comment]
ping @dgoscn

**Comment by claudiobastos** [comment]
I would like to take a look

**Comment by chrroberts-pure** [comment]
Hi! @claudiobastos this may be closed.

these metrics are now longer exported with the latest version of the Pure Storage exporter. 

https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/commit/95c532b9c7f335a1aa083fff75ee8b40adaf12d3
