### ISSUE TITLE
Metrics endpoints other than /array not working

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#16992]
### Component(s)

receiver/purefa

### What happened?

Apparently, the non-array metrics are not currently working as expected. This issue is to manually test and ensure that this is actually working. Bonus points if tests can be added to ensure that non-array metrics are processed as well.

### Collector version

current main

### Additional context

cc @dgoscn

**Comment by chrroberts-pure** [comment]
I am still hitting this issue with v0.69 

Here's my configuration that I am using.


```
receivers:
  purefa:
    endpoint: http://exporter-host01:9490/metrics
    arrays:
    - address: array01
      auth:
        authenticator: bearertokenauth/array01
    - address: array05
      auth:
        authenticator: bearertokenauth/array05
    env: dev
    settings:
      reload_intervals:
        array: 10s
        host: 15s
        directories: 15s
        pods: 30s
        volumes: 25s

```
Looking at the output of the logs, it looks like it's only creating 1 scraper job per endpoint. I would assume that it would create a different scrape job per metric type as well.

```
2023-01-12T13:10:56.382-0600	info	prometheusreceiver@v0.69.0/metrics_receiver.go:255	Starting discovery manager	{"kind": "receiver", "name": "purefa", "pipeline": "metrics"}
2023-01-12T13:10:56.385-0600	info	prometheusreceiver@v0.69.0/metrics_receiver.go:243	Scrape job added	{"kind": "receiver", "name": "purefa", "pipeline": "metrics", "jobName": "purefa/array/gse-array01"}
2023-01-12T13:10:56.385-0600	info	prometheusreceiver@v0.69.0/metrics_receiver.go:243	Scrape job added	{"kind": "receiver", "name": "purefa", "pipeline": "metrics", "jobName": "purefa/array/gse-array05"}
2023-01-12T13:10:56.385-0600	info	service/pipelines.go:109	Receiver started.	{"kind": "receiver", "name": "purefa", "pipeline": "metrics"}
```

**Comment by chrroberts-pure** [comment]
We also need to document how you can exclude different metric endpoints. (for instance if someone wants to only scrape /metrics/hosts or /metrics/directories)

**Comment by dgoscn** [comment]
> I am still hitting this issue with v0.69
> 
> Here's my configuration that I am using.
> 
> ```
> receivers:
>   purefa:
>     endpoint: http://exporter-host01:9490/metrics
>     arrays:
>     - address: array01
>       auth:
>         authenticator: bearertokenauth/array01
>     - address: array05
>       auth:
>         authenticator: bearertokenauth/array05
>     env: dev
>     settings:
>       reload_intervals:
>         array: 10s
>         host: 15s
>         directories: 15s
>         pods: 30s
>         volumes: 25s
> ```
> 
> Looking at the output of the logs, it looks like it's only creating 1 scraper job per endpoint. I would assume that it would create a different scrape job per metric type as well.
> 
> ```
> 2023-01-12T13:10:56.382-0600	info	prometheusreceiver@v0.69.0/metrics_receiver.go:255	Starting discovery manager	{"kind": "receiver", "name": "purefa", "pipeline": "metrics"}
> 2023-01-12T13:10:56.385-0600	info	prometheusreceiver@v0.69.0/metrics_receiver.go:243	Scrape job added	{"kind": "receiver", "name": "purefa", "pipeline": "metrics", "jobName": "purefa/array/gse-array01"}
> 2023-01-12T13:10:56.385-0600	info	prometheusreceiver@v0.69.0/metrics_receiver.go:243	Scrape job added	{"kind": "receiver", "name": "purefa", "pipeline": "metrics", "jobName": "purefa/array/gse-array05"}
> 2023-01-12T13:10:56.385-0600	info	service/pipelines.go:109	Receiver started.	{"kind": "receiver", "name": "purefa", "pipeline": "metrics"}
> ```

Hey @chrroberts-pure thanks for your feedback. Sure, I am already working on solution for this response.

**Comment by jpkrohling** [comment]
I'm closing this as I believe this has been addressed already.
