### ISSUE TITLE
[exporter/humioexporter] Mark Obsolete and remove

### ISSUE THREAD

**Issue by ryanfaircloth** [open-telemetry/opentelemetry-collector-contrib#17013]
### Component(s)

exporter/humio

### Collector version

*

## Environment
NA

### Log output

```shell
NA
```

### Additional context

Humio now known as LogScale beginning with version 1.68 supports OTLP using HTTP and no longer requires a product specific exporter. See https://library.humio.com/humio-server/endpoints.html

**Comment by Xitric** [comment]
Great to see native support for OTLP! I am sure that will work better than this custom-made exporter.

**Comment by atoulme** [comment]
Can I work on this bug? If so, please assign to me, thanks!

**Comment by atoulme** [comment]
Done!
