### ISSUE TITLE
[receiver/filelogreceiver]: Add performance metrics

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#17025]
### Component(s)

receiver/filelog

### Is your feature request related to a problem? Please describe.

I am unable to deduct how many bytes is processed by filelog receiver.

### Describe the solution you'd like

It would be nice to have metric which would keep that information

### Describe alternatives you've considered

Not reaslly see any. There is `otelcol_receiver_accepted_log_records`, but it doesn't show how many bytes has been processed.

### Additional context

I would like to be able to see how performant is filelog receiver on different pods/nodes

**Comment by djaglowski** [comment]
This would be great to have, but we need to consider the performance impact. If there is a notable impact, we can likely keep it disabled by default and provide a config flag.
