### ISSUE TITLE
[receiver/mongodb] Emit metrics around status and uptime of mongodb

### ISSUE THREAD

**Issue by davidji99** [open-telemetry/opentelemetry-collector-contrib#17021]
### Component(s)

receiver/mongodb

### Is your feature request related to a problem? Please describe.

Currently, the mongodb receiver does not emit the following metrics:
- status of mongodb
- uptime

### Describe the solution you'd like

Post-enhancement, the receiver emits the following metrics.

**Comment by djaglowski** [comment]
Closed by #17022
