### ISSUE TITLE
Can skywalking exporter could support a trace exporter

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-collector-contrib#17034]
### Is your feature request related to a problem? Please describe.

Skywalking exporter can only export metric and logs, however, I need to export trace to skywalking backend.

### Describe the solution you'd like

Simply forward the trace from skywalking receiver to skywalking exporter would be fine.

**Comment by liqiangz** [comment]
@sweetxiaodai Not yet supported,  you can refer https://github.com/apache/skywalking/issues/7848.

**Comment by wu-sheng** [comment]
There would not be a trace exporter in theory. SkyWalking's trace context is a superset of the traditional otel trace format. They are designed for different purposes.

@jpkrohling Feel free to close this.

**Comment by zephyrpathsofglory** [comment]
> There would not be a trace exporter in theory. SkyWalking's trace context is a superset of the traditional otel trace format. They are designed for different purposes.
> 
> @jpkrohling Feel free to close this.

Can you explain it in a more detailed way? Otel skywalking receiver can converted to otel trace format, why can not converted back to skywalking format ? I am confused, does the convertion have  information loss so that it can't be converted back ?

**Comment by wu-sheng** [comment]
> > There would not be a trace exporter in theory. SkyWalking's trace context is a superset of the traditional otel trace format. They are designed for different purposes.
> > @jpkrohling Feel free to close this.
> 
> Can you explain it in a more detailed way? Otel skywalking receiver can converted to otel trace format, why can not converted back to skywalking format ? I am confused, does the convertion have information loss so that it can't be converted back ?

Yes. SkyWalking context has more information than OTEL in-wire propagation context. So, logically, there is not able to transfer for that.
You could learn SkyWalkng's propagation protocol here, https://skywalking.apache.org/docs/main/latest/en/api/x-process-propagation-headers-v3/
From the use case perspective, SkyWalking provides 100% trace collection to archive accurate metrics, topology, and 100% trace persistence, and the extra fields in the context could make SkyWalking OAP server to build these service topologies and metrics(such as API/endpoint dependency) in a high performance and don't need large scale big-data system to do aggregation.
