### ISSUE TITLE
receiver/promtailreceiver not in release v0.67.0

### ISSUE THREAD

**Issue by joshua-heidrich** [open-telemetry/opentelemetry-collector-contrib#17082]
### Component(s)

receiver/promtail

### Describe the issue you're reporting

Promtail-receiver is nowhere to be found in release v0.67.0. (https://github.com/open-telemetry/opentelemetry-collector-releases/blob/v0.67.0/distributions/otelcol-contrib/manifest.yaml)

But the release-description says it is. (https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.67.0)

Would be nice if you could include it as soon as possible :)

**Comment by codeboten** [comment]
This is currently blocked on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16722

**Comment by mar4uk** [comment]
The promtail receiver was removed from the collector completely https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18459

I'm working on a new loki receiver https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18635 that will have much less dependencies and implement only push ingestion

This issue could be closed

**Comment by joshua-heidrich** [comment]
Is the promtail receiver completely gone now or will it come back in the future when the security vulnerabilites are resolved?

**Comment by jpkrohling** [comment]
We do not have plans to add the promtail receiver again. Which features would you be interested in using from promtail that are lacking here?

**Comment by joshua-heidrich** [comment]
To scrape logs from the kubernetes cluster. I hope I haven't overlooked anything, but I can't find any other way than using promtail.

**Comment by jpkrohling** [comment]
There's one solution documented here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/kubernetes/otel-collector.yaml

IMO, it's not the ideal world, but it's a solution that works.
