### ISSUE TITLE
New component: in-trace sampler

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-collector-contrib#17086]
### The purpose and use-cases of the new component

A typical OpenTelemetry user might start by installing an off-the-shelf SDK distribution that includes many/all instrumentation libraries with the default configuration. While good for some users, instrumenting everything in the program might not be desirable due to the following reasons:
- cost - many vendors charge by the # spans. for production payloads, the number of spans might be too costly and technics such as sampling are heavily used in order to reduce costs.
- verbosity - some spans are too verbose. They describe low-level operations such as network libraries and DNS, which can be rarely useful and might give little to no value to the organization
- noise - a human user that needs to look at a single trace and derive useful insights for it might find some spans to be too noisy - giving less or little value and distracting the attention from the important spans, harming UX.

Instrumentation libraries many times come with configuration options to control the noise and verbosity of the generated telemetry data. These are added by community members with the above problems, wishing to adjust the generated traces to their specific use cases and needs. Another common practice for reducing noise and cost is the practice of sampling, which is supported by both OpenTelemetry SDKs and the collector, by processors such as `tailsampler` and `probabilistic_sampler`.

A very popular sampling mechanism is to apply the same sampling decision to the entire trace, whether collect all trace spans or not. Examples of that are the [ParentBased Sampler](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#parentbased) and [Tail Sampling Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor). However, it is common for users to request removing some less-interesting spans from a given trace and keep other more-interesting spans.

There are many tools in the observability engineer toolbox designed to address the above issues, and this proposal is for adding a new one: a collector processor for unsampling specific spans from within a completed trace.

The benefits of this processor are:
- implemented in the collector. Unlike implementing a sampler in SDK which requires writing and maintaining code in 11 languages, this sampler is written once and can be used on any trace data no matter who generated it.
-  Works on "complete" traces - since we aggregate the spans prior and apply sampling logic only after we (heuristically) have all the spans for a trace, a user can configure much more sophisticated rules such as removing spans only from non-erroneous traces and removing internal spans while adjusting children to point to the correct (new) parent.

Some real-life examples (mainly around nodejs and ruby, as this is what I am familiar with):

- `@opentelemetry/instrumentation-net` and `@opentelemetry/instrumentation-dns` in nodejs can introduce many "boring" spans that users may wish to opt-out from. While they can simply disable the instrumentation, they may wish to sample a small number of "full" traces with all the lower-level information or collect it only on errors or long-duration traces.

- `@opentelemetry/instrumentation-express` is a nodejs instrumentation library for the `express` HTTP framework. It will by default record a span for each middleware invocation, also for built-in middlewares like parsing query params, request bodies etc. A user [can configure](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-express#express-instrumentation-options) which layer to ignore, but that requires deploying services, browsing config options which may or may not be adequate, having deep knowledge on the span structures etc. An alternative might be to keep just those middlewares that have "continuation" - downstream spans with actual work. This is only known when waiting for the entire trace to arrive.

- `OpenTelemetry::Instrumentation::ActiveRecord` is a ruby ORM for databases. see (here)[https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/35]. The instrumentation currently creates span per operation, which for transactions and complex operations, might yield dozens of expensive, rarely interesting spans which are way too verbose. Users express the need to capture just the "root" active record span for each such sub-tree, which is the operation that the user actually invoked. Internal library details might be too noisy for most users.

Therefore, I think the observability pipeline is currently lacking a sampler that acts on complete traces (much like the tail sampler) but can unsample away specific spans from a given trace, some or all of the time.

I call this sampler "In Trace Sampler" (open for better names). It should be placed in the pipeline after "groupbytrace" or "tail_sampling" which will hand it a batch of spans all belonging to a (heuristically) complete trace. It will then build a tree from these spans, and remove specific spans based on the knowledge of the entire trace structure.

I want to start with a simple rule that unsamples only leaf spans (direct or transitive) from a list of scope names. A user can use the sampler to remove lower level network spans (if they are leaves), HTTP framework middlewares that do not continue to downstream real operations (leaf middleware), and more. Since we are removing only leaves in the tree, there is no need to change parentSpanID for any span we remove which makes it easier. I have already implemented this logic and tested it against real instrumentation and known cases based on feedback from users.

For the next steps, more rules can be added and extended to support more complex scenarios. 

### Example configuration for the component

processors:
  in_trace_sampler:
    scope_leaves:
      - "@opentelemetry/instrumentation-net"
    sampling_percentage: 15.3
    hash_seed: 22

### Telemetry data types supported

traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

I don't have a sponsor for this yet

**Comment by atoulme** [comment]
I cannot sponsor myself but I think this is a valuable processor. Thank you for the contribution!

**Comment by atoulme** [comment]
I can sponsor this now. Marking as accepted.

**Comment by hkrutzer** [comment]
Can this be kept open?

**Comment by atoulme** [comment]
Are you interested in contributing to this sampler @hkrutzer ?
