### ISSUE TITLE
Host Metrics Receiver

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/opentelemetry-collector-contrib#171]
Add a receiver to generate Host Metrics about the machine the collector is running on. Initially this will be for Windows only, but extendable so that the same receiver can be used to collect Linux metrics when implemented

**Comment by jrcamp** [comment]
This [Host Metrics](https://docs.google.com/document/d/1i-QG-TxkIWVbdx86UM2GXcFvpeCV7zSBsPmMyMkOEBk/edit?usp=sharing) document captures the metrics we intend to collect.

**Comment by jrcamp** [comment]
According to @flands @bogdandrutu @tigrannajaryan this can go into core.

**Comment by james-bebbington** [comment]
Moved issue to collector core repo: https://github.com/open-telemetry/opentelemetry-collector/issues/847
