### ISSUE TITLE
[CI] Failing Windows unit tests do not cause the job to fail

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#17181]
It looks like https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17037 was solved only for Linux.

Windows tests are still silently failing. See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3744658264/jobs/6358274789 with the following errors:

```
--- FAIL: TestFileTracesReceiver (1.01s)
=== RUN   TestFileMetricsReceiver
if [ "true" = "true" ]; then \
	go test -race -timeout 300s --tags="" -v ./... 2>&1 | tee -a ./foresight-test-report.txt; \
else \
	go test -race -timeout 300s --tags="" ./...; \
fi
    file_test.go:93: 
        	Error Trace:	D:\a\opentelemetry-collector-contrib\opentelemetry-collector-contrib\receiver\otlpjsonfilereceiver\file_test.go:93
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestFileMetricsReceiver
--- FAIL: TestFileMetricsReceiver (1.00s)
=== RUN   TestFileLogsReceiver
    file_test.go:119: 
        	Error Trace:	D:\a\opentelemetry-collector-contrib\opentelemetry-collector-contrib\receiver\otlpjsonfilereceiver\file_test.go:119
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestFileLogsReceiver
--- FAIL: TestFileLogsReceiver (1.02s)
=== RUN   TestLoadConfig
--- PASS: TestLoadConfig (0.00s)
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otlpjsonfilereceiver	3.124s
FAIL
```

**Comment by dmitryax** [comment]
cc @MovieStoreGuy in case you know how to apply your fix on Windows. 

Otherwise, I think we can vote to remove Foresight. I played with it but didn't find it super helpful.

**Comment by MovieStoreGuy** [comment]
Do you have a link to the action that failed? Sorry just need a bit more information of the environment to help understand the setup.

**Comment by dmitryax** [comment]
Yes, the job with silently failing tests is in the description

**Comment by MovieStoreGuy** [comment]
> Yes, the job with silently failing tests is in the description https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3744658264/jobs/6358274789

I will say I am still waking up and leave it at that... :disappears:

**Comment by MovieStoreGuy** [comment]
I am trying to test something here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17183 but it appears the windows steps are skipped and I am not sure why

**Comment by dmitryax** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17183
