### ISSUE TITLE
receiver/saphana not in release v0.67.0 

### ISSUE THREAD

**Issue by kand617** [open-telemetry/opentelemetry-collector-contrib#17189]
### Component(s)

receiver/saphana

### Describe the issue you're reporting

Describe the issue you're reporting
Promtail-receiver is nowhere to be found in release v0.67.0. (https://github.com/open-telemetry/opentelemetry-collector-releases/blob/v0.67.0/distributions/otelcol-contrib/manifest.yaml)

Would be nice if you could include it as soon as possible :)

**Comment by fatsheep9146** [comment]
@kand617 
I think you can create a pr like https://github.com/open-telemetry/opentelemetry-collector-releases/pull/243

**Comment by atoulme** [comment]
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18524 - promtail receiver has been removed. Closing this issue.
