### ISSUE TITLE
[docs] Add guidelines for writing platform agnostic code in CONTRIBUTIONS.md

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#17195]
The collector should work on both Windows and Linux platforms. We need to promote using libraries that provide such guarantees as path/filepath.

Originally posted by @MovieStoreGuy in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17194#pullrequestreview-1226969016

**Comment by saimadhav2k2** [comment]
assign it to me

**Comment by saimadhav2k2** [comment]
- [x] Added guidelines

**Comment by saimadhav2k2** [comment]
Can you confirm it?

**Comment by dmitryax** [comment]
> Can u confirm it?

Confirm what?

**Comment by saimadhav2k2** [comment]
@dmitryax sorry my bad, i am new to open source, so a little bit confusion
Like are these 2 points enough or should i add more

![image](https://user-images.githubusercontent.com/62380398/209425801-86492dd6-1602-4263-a3ab-df727b400355.png)

**Comment by dmitryax** [comment]
@saimadhav2k2 please read https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md on how to make contribute to the progect

**Comment by fatsheep9146** [comment]
@saimadhav2k2 any progress?

**Comment by swapnilashtekar** [comment]
Can you please assign this to me? 
I have pull request ready for document update.

**Comment by TylerHelmuth** [comment]
Closed via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18188
