### ISSUE TITLE
Graduate exporter.googlecloud.OTLPDirect feature-gate to GA

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#17192]
### Component(s)

exporter/googlecloud

### Describe the issue you're reporting

The feature gate has been in beta since v0.50.0, so it is well past time to remove it.

**Comment by dmitryax** [comment]
Closing as completed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17191
