### ISSUE TITLE
OCB

### ISSUE THREAD

**Issue by Gauravmeenu** [open-telemetry/opentelemetry-collector-contrib#17278]
### Describe the issue you're reporting

How can I use my custom collector distribution as a docker image in the docker 
compose file.

**Comment by frzifus** [comment]
Hi @Gauravmeenu, does that help?
https://github.com/open-telemetry/opentelemetry-demo/blob/85c268feaab334de158063f51ddb0ea25d6cdd3e/docker-compose.yml#L610-L629

**Comment by Gauravmeenu** [comment]
Actually I just want to use my custom distribution which I had created some files like (component.go or main.go) with the help of ocb and manifest.yaml file and then I'll compile the files and create the binary output and then using that binary output with config.yaml file amd my distribution is running.  So basically I want to create docker image as well as output binary with the help of docker which I'll be  using in my docker compose file and running with the attach config.yml file .

**Comment by Gauravmeenu** [comment]
@codeboten thank you so much I'm going to check out this

**Comment by jpkrohling** [comment]
This repository can also serve as inspiration to you, as it contains quite everything related to building your custom distribution: https://github.com/grafana/opentelemetry-collector-components

If you still need help, let me know and I'll reopen this.
