### ISSUE TITLE
How to add the file chekpoint in filelog receiver 

### ISSUE THREAD

**Issue by Manikanth-Lilly** [open-telemetry/opentelemetry-collector-contrib#17274]
### Component(s)

receiver/filelog

### Describe the issue you're reporting

I was trying to read an application log file which won't be actively writing by using filelog receiver. I am to onboard the log data successfully into Splunk Observability Logging. But whenever restarting  otel agent the entire log file is re-indexing to Splunk. is there way to give the file check point which can allow to pickup of data where it left off in the case of a collector restart.

**Configuration:**
filelog/IIQAlerts:
    include: [ /tmp/IIQAlerts.log ]
    start_at: beginning
    include_file_path: true
    encoding: utf-8
    operators:
    - type: regex_parser
      regex: '^Threshold Exceeded: (?P<ThresholdType>.*) configured threshold = (?P<configuredThreshold>.*).$'
    - type: regex_parser
      regex: '^Failed Performing Verification Check: (?P<FailedPerformanceVerificationMessage>.*).$'

As per document there was **storage** attribute where we can mention checkpoint, but I did not find any example. So anyone please help in this.

Reference: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver

**Comment by atoulme** [comment]
You can read more on this here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage

I have added an example to our examples here: https://github.com/signalfx/splunk-otel-collector/pull/2428

**Comment by atoulme** [comment]
I recommend we move this to the discussions forum.

**Comment by Manikanth-Lilly** [comment]
Thanks for your help @atoulme, I have updated and configured with the file_stroge and its working fine.
