### ISSUE TITLE
How to understand decision_wait of tail_sampling

### ISSUE THREAD

**Issue by Liubey** [open-telemetry/opentelemetry-collector-contrib#17275]
### Component(s)

processor/tailsampling

## Description
the decision_wait describe by:
```
decision_wait (default = 30s): Wait time since the first span of a trace before making a sampling decision

````

When I make two policies to get long-request-time traces and the error traces like this:
```
  tail_sampling:
    decision_wait: 60s 
    num_traces: 5000
    expected_new_traces_per_sec: 10
    policies:
      [          
        {
          name: errors-policy,
          type: numeric_attribute,
          numeric_attribute: {key: http.status_code, min_value: 499, max_value: 600}
        },
        {
          name: latency-5s,
          type: latency,
          latency: {threshold_ms: 5000}
        },
      ]  
```
So if the trace is error already, the processor will delivery the trace in 60s later?

In the real world, Microservice cross call make more than 60s long-request. So If I want to catch the threshold_ms>60000, the decision_wait must more than 60s, better about decision_wait=80s. And all the trace will store to the Jaeger at least delay decision_wait=80s later?

Correct me if I'm wrong, Thank you.

### Collector version

0.68.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jpkrohling** [comment]
The tail sampling processor will wait for the decision waiting time to elapse, and then evaluate the trace. So, every trace will be delayed in at least 60s (or 80s) in your example, even if the very first span for that trace already matches the condition for the sampling policy.

**Comment by Liubey** [comment]
May I ask something about "best practice"?
under balance memory and cpu cost for these collectors,  these config:
```
decision_wait: 60s     
num_traces: 5000
```
Whether it is safety and rational?
Cause my system have 2% long-time-request and many long-time async  task job.
