### ISSUE TITLE
Root Span in tailsampling processor will directly through the processor and go to exporter?

### ISSUE THREAD

**Issue by Liubey** [open-telemetry/opentelemetry-collector-contrib#17280]
### Component(s)

processor/tailsampling

## Description
When I use tailsampling processor to tailsampling traces in that case:
the config 
```
  tail_sampling:
    decision_wait: 60s 
    num_traces: 5000
    expected_new_traces_per_sec: 10
    policies:
      [          
        {
          name: errors-policy,
          type: numeric_attribute,
          numeric_attribute: {key: http.status_code, min_value: 499, max_value: 600}
        },
        {
          name: latency-5s,
          type: latency,
          latency: {threshold_ms: 5000}
        },
      ]   
```
the logic is: parent span -->child span and sleep 6s-->parant span sleep 10s:
```
    with tracer.start_span('TestSpan') as span:
        span.log_kv({'event': 'test message', 'life': 42})

        with tracer.start_span('ChildSpan', child_of=span) as child_span:
            time.sleep(6)
            child_span.set_tag('CTag', '1')
            child_span.log_kv({'event': 'down below'})
            logging.info(u'child is done')

        time.sleep(240)
        logging.info(u'parent is done')

```

I found the root span's phenomenon:

- 1) after 60s(decision_wait) of child done, tailsampling print and I can got the trace without in jaeger(It is right):
```
2022-12-28T12:58:20.422Z debug tailsamplingprocessor@v0.68.0/processor.go:204 Sampling policy evaluation completed {"kind": "processor", "name": "tail_sampling", "pipeline": "traces", "batch.len": 1, "sampled": 2, "notSampled": 0, "droppedPriorToEvaluation": 0, "policyEvaluationErrors": 0}“
```
- 2) the jaeger got warning one the UI, said "invalid parent span IDs=ed541f049ba40b85; skipping clock skew adjustment“"
- 3) after 240, the parent span done
- 4) the tailsampling print nothing and exporter print "2022-12-28T13:01:19.734Z info TracesExporter {"kind": "exporter", "data_type": "traces", "name": "logging", "#spans": 1}"
- 5) I get the whole trace, both parent and child in jaeger

Is it right? How to explain with tailsampling processor' configration?
Thanks very much.

### Collector version

0.68.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by mizhexiaoxiao** [comment]
The tailsamplingprocessor will make a sampling decision after the `decision_wait` set time ends. The child span hits the latency strategy and should be sent to the next consumer. This trace will be marked as a sampled `trace.FinalDecision=Sampled` in memory, so all spans received after the same trace will be sent directly without making a decision

**Comment by Liubey** [comment]
@mizhexiaoxiao trace.FinalDecision=Sampled is cache?How long?
 In my case, parent span done after 240S ,but decision_wait only 60s.

**Comment by mizhexiaoxiao** [comment]
> @mizhexiaoxiao trace.FinalDecision=Sampled is cache?How long? In my case, parent span done after 240S ,but decision_wait only 60s.

It depends on the `num_traces` you set. When the number of traces stored in the processor memory is greater than `num_traces`, the frist traceID will be deleted, First In First Out.
code segment:
`tsp.deleteChan = make(chan pcommon.TraceID, cfg.NumTraces)`

In theory, `num_traces` need to be set as large as possible to ensure that the traceID in memory is not deleted before all spans enter the processor.

`otelcol_processor_tail_sampling_sampling_trace_dropped_too_early` metrics can be seen whether your `num_traces` setting is large enough, if it is not 0, it means that your traceID has been deleted when making a decision

**Comment by Liubey** [comment]
@mizhexiaoxiao Thank you so much.
Seems like I need to "monitor" these collectors as a part of the trace system.
