### ISSUE TITLE
[ci] Switch from impi to gci linter

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#17281]
### Describe the issue you're reporting

We currently use [`impi`](https://github.com/pavius/impi) for enforcing Go import order. An alternative called [`gci`](https://github.com/daixiang0/gci) exists, which has the following advantages:
- builtin on golangci-lint (which implies no need for a separate binary/test step and possibly faster results),
- higher repo activity (commited in the last ~month, recent release, higher number of stars and forks)
- supports auto-fixing 

We should replace our usage of `impi` by `gci` on this repository.

**Comment by atoulme** [comment]
I need this! I can take it.
