### ISSUE TITLE
[exporter/dynatrace] Use configopaque for api_token field

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#17293]

**Comment by dyladan** [comment]
done by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/62da158b2565d8f6a2694d6f6922698a083f09fe https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17077

**Comment by dyladan** [comment]
Looks like I don't have power to close this
