### ISSUE TITLE
Splunk HEC only accepts flat JSON object (not nested)

### ISSUE THREAD

**Issue by harshit-splunk** [open-telemetry/opentelemetry-collector-contrib#17308]
### Component(s)

exporter/splunkhec, receiver/splunkhec

## Description

According to the [Splunk HEC doc](https://docs.splunk.com/Documentation/Splunk/9.0.3/Data/FormateventsforHTTPEventCollector),
`fields` key specifies a JSON object that contains a flat (not nested) list of explicit custom fields to be defined at index time. 

## Steps to Reproduce

Execute the following curl request
```sh
curl -k -H "Authorization: Splunk 00000000-0000-0000-0000-000000000000" https://splunk:8088/services/collector -d '{"fields":{"keyArray":["A", [1]]}, "event": "hello world"}'
```
```sh
curl -k -H "Authorization: Splunk 00000000-0000-0000-0000-000000000000" https://splunk:8088/services/collector -d '{"fields":{"keyMap":{"field": "value"}}, "event": "hello world"}'
```
It throws this error

```json
{"text":"Error in handling indexed fields","code":15,"invalid-event-number":0}
```

The implementation of the splunkhec exporter and receiver doesn't handle it explicitly. It can lead to unexpected failure/invalid behaviour in both the exporter/receiver

### Collector version

v0.67.0

**Comment by harshit-splunk** [comment]
CC: @dmitryax @atoulme

**Comment by atoulme** [comment]
Thank you for finding this bug!

**Comment by harshit-splunk** [comment]
@atoulme, I am thinking of fixing this bug later this week. For the receiver, it should return the same error as an actual Splunk HEC does. 
But, I am not sure about the exporter. I can think of 3 ways to handle this:
1. Drop the entire event (unreasonable)
2. Drop the nested field
3. Flatten the nested map and drop the nested array (I prefer this)

Please share your thoughts.

**Comment by fatsheep9146** [comment]
can this issue be assigned to you? @atoulme

**Comment by atoulme** [comment]
3. seems ok with me. Serialize the map to a string?

@fatsheep9146 please feel free to assign to me, but it looks like @harshit-splunk is the one doing the work. It should probably go to him.

**Comment by fatsheep9146** [comment]
ok, I assigned this to @harshit-splunk

**Comment by harshit-splunk** [comment]
> Serialize the map to a string?

But we can serialise nested arrays, but not sure about the map. AFAIK, Splunk will not populate search-time fields from the indexed field if the indexed field contains any serialised map. User has to write their own field extraction logic in splunk.

**Comment by atoulme** [comment]
Could we flatten the map, prefixing with the top key?

**Comment by harshit-splunk** [comment]
>  Could we flatten the map, prefixing it with the top key?

Yes, that's what I am going to do.

**Comment by harshit-splunk** [comment]
Closing as fixed.
