### ISSUE TITLE
exporter/stackdriver: allow credentials file

### ISSUE THREAD

**Issue by sbernierlacapitale** [open-telemetry/opentelemetry-collector-contrib#1734]
**Is your feature request related to a problem? Please describe.**
Traces are exported to Google Cloud Trace to the application's project. It is currently impossible (?) to specify another project as the target for these traces, or to use a specific service account.

For example, the traces sent to a collector hosted on GKE cannot easily be exported to Cloud Trace in another project, using another service account.

**Describe the solution you'd like**
Specifying a credentials file's path in the collector config would solve this issue. This file is the JWT public key specified at https://cloud.google.com/iot/docs/how-tos/credentials/jwts.

**Describe alternatives you've considered**
The only alternative that I know of is to clone this repo, manually add this ability, and build a new image to deploy.

**Additional context**
The modified code is essentially
```
if cfg.CredentialsPath != "" {
    copts = append(copts, option.WithCredentialsFile(cfg.CredentialsPath))
}
```

The collector's config file can then contain the following:
```
exporters:
  stackdriver:
    project: "my_project"
    credentials_path: "/path/to/credentials.json"
```

If this is considered as an interesting change, I can make a PR with the changes if needed.

**Comment by andrewhsu** [comment]
from the triage session at the sig mtg today, @dashpole volunteered to be assignee of this issue

**Comment by dashpole** [comment]
This was fixed by https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/527
