### ISSUE TITLE
[receiver/mongodb] Add `oplog.size` metric

### ISSUE THREAD

**Issue by davidji99** [open-telemetry/opentelemetry-collector-contrib#17368]
### Component(s)

receiver/mongodb

### Is your feature request related to a problem? Please describe.

Add mongodb.oplog.size metric to the receiver. I believe this metric only exists when mongodb is set up with replication: https://www.mongodb.com/docs/manual/core/replica-set-oplog/

### Describe the solution you'd like

The receiver will emit the specified metric.

**Comment by djaglowski** [comment]
To recap the conversation about this on #17041 - [the proposed solution would depend on an unsupported admin command](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17041#issuecomment-1410486066). It would be great to collect this metric, but I do not think we should switch to using that command.
