### ISSUE TITLE
[exporter/datadog] Exclude DataDog/agent-payload/v5 v5.0.59

### ISSUE THREAD

**Issue by PaurushGarg** [open-telemetry/opentelemetry-collector-contrib#17381]
### Component(s)

exporter/datadog

## Description
Inclusion of `github.com/DataDog/agent-payload/v5 v5.0.59 // indirect` in [gomod](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/76771863a86bd4d8aecb5a8446d23b26a92b36cc/go.mod#L222) file is throwing error on local environment: `unknown revision v5.0.59` or `module found but does not contain package`. 

`v5.0.59` seems to have been removed from [source repository](https://github.com/DataDog/agent-payload/releases) but is still part of [proxy package](https://pkg.go.dev/github.com/DataDog/agent-payload/v5?tab=versions). The versioning number `v5.0.59` seems not to be inline as well with previous versions. 

To fix this we excluded this dependency: `exclude github.com/DataDog/agent-payload/v5 v5.0.59 // indirect`

## Steps to Reproduce
`go mod tidy `
or `github.com/DataDog/agent-payload/v5@v5.0.59`
## Expected Result
No errors/issues

## Actual Result
![](https://user-images.githubusercontent.com/41936996/210611760-82bc5037-a5c5-4dbc-98de-029091d56853.png)

### Collector version

v0.68.0

## Environment
OS: Mac ARM 64

**Comment by dineshg13** [comment]
Thanks for reporting. Am able to reproduce this 
```    github.com/moby/term: github.com/DataDog/agent-payload/v5@v5.0.59: reading github.com/DataDog/agent-payload/go.mod at revision v5.0.59: unknown revision v5.0.59
````
we Will fix this at earliest.

**Comment by mx-psi** [comment]
#17393 should fix this, I also reported this upstream at DataDog/agent-payload/issues/218 so that this version is retracted on the next release
