### ISSUE TITLE
Support Prometheus remote_read on a receiver or other way to scrape instance

### ISSUE THREAD

**Issue by nazarewk** [open-telemetry/opentelemetry-collector-contrib#17395]
### Component(s)

receiver/prometheus

### Is your feature request related to a problem? Please describe.

I did not figure out the way to scrape Prometheus instance using otelcol.

I would like to:
1. gather metrics  (mostly) on a Prometheus instance for compatibility with Prometheus Operator
2. enhance them through Open Telemetry Collector
3. feed them further to Thanos for long-term storage and querying

### Describe the solution you'd like

I would like to use `remote_read` configs to scrape Prometheus instance

**Comment by jaronoff97** [comment]
Are you unable to replace your usage of prometheus using an otel collector? Rather than setting up a remote read, could you not have the collector scrape all of the targets for your prometheus instance?

**Comment by nazarewk** [comment]
I would like to keep all those established Prometheus Operator resources (ServiceMonitors etc.) being present in many deployments OOTB working with the metrics pipeline.

**Comment by jaronoff97** [comment]
Have you looked in to using the OpenTelemetry Operator to run your collector with the target allocator? It supports ServiceMonitor and PodMonitor CRDs to dynamically generate scrape configurations. Using the target allocator in conjunction with the collector also lets you horizontally scale your collectors. I wrote a quick-start doc [here](https://docs.lightstep.com/docs/otel-collector-k8s-quick-start) if you'd like to try it out. Admittedly, the target allocator needs some more docs, but this quick start should do enough to get you started. Please reach out in the CNCF slack in the `#otel-operator` channel if you'd like to learn more.

**Comment by nazarewk** [comment]
> Have you looked in to using the OpenTelemetry Operator to run your collector with the target allocator? It supports ServiceMonitor and PodMonitor CRDs to dynamically generate scrape configurations. Using the target allocator in conjunction with the collector also lets you horizontally scale your collectors. I wrote a quick-start doc [here](https://docs.lightstep.com/docs/otel-collector-k8s-quick-start) if you'd like to try it out. Admittedly, the target allocator needs some more docs, but this quick start should do enough to get you started. Please reach out in the CNCF slack in the `#otel-operator` channel if you'd like to learn more.

sounds like it would solve my problem, looking into it

**Comment by atoulme** [comment]
@nazarewk did it solve your problem?

**Comment by nazarewk** [comment]
I have solved it by not storing intermediate metrics in Prometheus, but go through otelcol all the way with those Service/PodMonitors

**Comment by atoulme** [comment]
OK. Leaving the issue open as the enhancement request seems to still be valid.
