### ISSUE TITLE
[exporter/clickhouse] Add instrumentation scope to span attribute

### ISSUE THREAD

**Issue by huynhtehoa** [open-telemetry/opentelemetry-collector-contrib#17408]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

Currently, attributes such as `otel.library.name`, `otel.library.version` are not added to span attributes. Those attributes are parts of `InstrumentationScope`, which is provided by opentelemetry https://opentelemetry.io/docs/reference/specification/logs/data-model/#field-instrumentationscope

### Describe the solution you'd like

It would be nice to include `otel.library.name` and `otel.library.version` in span attributes

**Comment by hanjm** [comment]
looks good.  I think store it to resource attribute is reasonable.

**Comment by Frapschen** [comment]
Is there some scenes need to do that? in jaeger, those attribute are include in UI:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/35491170/216751792-f0ece165-21a1-49f9-9149-79209ff480cf.png">

**Comment by huynhtehoa** [comment]
Hi @Frapschen, we are storing traces in Clickhouse to build our custom monitoring dashboards and this library info will help us filter data better. For example, we can find out the slowest libraries, the most frequently used libraries

**Comment by Frapschen** [comment]
got it,I agree with @hanjm, I will add this to my work list. I notice that the clickhouse log exporter also have same issue, I will create new issue and fix it.

**Comment by huynhtehoa** [comment]
Thank you guys :heart:

**Comment by dmitryax** [comment]
@huynhtehoa @Frapschen see the spec translation guidelines https://github.com/open-telemetry/opentelemetry-specification/blob/7116e72cff72a825bbb83e103c2756706d3106ee/specification/common/mapping-to-non-otlp.md#instrumentationscope . They should be mapped to `otel.scope.name` and `otel.scope.version`
