### ISSUE TITLE
Make sure all components can shutdown even if skip lifecycle is set.

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#17400]
## Description
In https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17199, we added support for checking that components would behave properly if shutdown before starting. But this doesn't extend to components which are marked as skipped as their lifecycle is not fit for tests.

For this test, we should disregard this flag and extend the test to all components. 

See https://github.com/signalfx/splunk-otel-collector-chart/issues/623 for an occurrence of the issue with k8sclusterreceiver.

### Collector version

0.67.0

**Comment by frzifus** [comment]
Is there an easy check to see which components are effected?

**Comment by atoulme** [comment]
Click on the PRs associated and look at the labels. They contain the names of components affected.

**Comment by atoulme** [comment]
This is now fixed. Onwards!
