### ISSUE TITLE
[pkg/stanza/adapter] Unused Convert helper

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#17429]
`Convert` helper was introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3125. It was expected to be used in tests but was never used. 

Now we have pkg/stanza/adapter exposed as a public API, it's important to limit its scope.

**Comment by dmitryax** [comment]
@djaglowski I see [your comment ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/filelogreceiver/storage_test.go#L185) but don't understand how the `Convert` function can help there. Please let me know if I'm missing something.

If this function isn't needed, I suggest deprecating it to see if other distros use it. WDYT?

**Comment by dmitryax** [comment]
@djaglowski Sounds good. Submitted a PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17450

**Comment by djaglowski** [comment]
@dmitryax, do you agree this can be closed?

**Comment by dmitryax** [comment]
@djaglowski https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18259 will close it
