### ISSUE TITLE
SpanId and TraceId not storing in ADX with OTeL Collector ADX exporter for classic jaeger traces

### ISSUE THREAD

**Issue by raz08** [open-telemetry/opentelemetry-collector-contrib#17437]
### Component(s)

exporter/azuredataexplorer

### Describe the issue you're reporting

As part of our project, we are trying to ingest our observability data(traces) to ADX with OTel collector. We have Jaeger client which instruments the traces in classic jaeger tracing format (not otlp). In this below design or pipeline spanID and traceID not stored in ADX, Is it something we are missing, or do we need to use any plugin or processor to convert the classic jaeger tracing data before ADX exporter?. Please advise us here. Thanks, in advance.

![jaegeradx](https://user-images.githubusercontent.com/20836472/211139449-dae2c260-3b6e-471c-8f05-1872e333569b.png)
![jaegeradxspans](https://user-images.githubusercontent.com/20836472/211139450-b0a57626-c4b7-48ff-81c6-b4a71d9bcb4d.png)

**Comment by frzifus** [comment]
How does your OpenTelemetry Collector config look like?

**Comment by raz08** [comment]
@frzifus , Here is my OpenTelemerty HELM config.

`config:
  exporters:
    azuredataexplorer:
      cluster_uri: https://**********.kusto.windows.net
      application_id: "343488d5-b699-4562-a43c-a79b8322897nn"
      application_key: "g8Q8Q~mu.ISqZn2slI4w3ek5W~DayKJHDI999DDKNN"
      tenant_id: "2e05f471-5822-4046-ae52-93cfbfj9hh8nn"
      db_name: "Otest"
      metrics_table_name: "test_metrics"
      logs_table_name: "test_logs"
      traces_table_name: "test_traces"
      ingestion_type : "managed"       
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
         endpoint: 0.0.0.0:14268
        thrift_compact:
          endpoint: 0.0.0.0:6831
  service:
    pipelines:
      traces:
        exporters:
          #- logging
          - azuredataexplorer
        processors:
          - memory_limiter
          - batch
        receivers:
          - jaeger
`

And I have used https://learn.microsoft.com/en-us/azure/data-explorer/open-telemetry-connector#create-tables link for creating table in ADX.

**Comment by ag-ramachandran** [comment]
@raz08 , Thanks for reporting
The case of Id field seems to be mismatched. It should be TraceID (as opposed to TraceId).
Please create the table as per the README here and check if these fields get populated

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/azuredataexplorerexporter/README.md


`.create-merge table <Traces-Table-Name> (TraceID:string, SpanID:string, ParentID:string, SpanName:string, SpanStatus:string, SpanKind:string, StartTime:datetime, EndTime:datetime, ResourceAttributes:dynamic, TraceAttributes:dynamic, Events:dynamic, Links:dynamic) `

**Comment by raz08** [comment]
@ag-ramachandran Thanks you, This solved the issue. 

And one more thing, I'm using jaeger kusto query for visualization. I see service names and operation in dropdown but when I select any service it is not showing traces/spans in UI.

**Comment by ag-ramachandran** [comment]
@raz08 we can help you with that. Can you shoot me an email at ramacg (at) microsoft and we can help you with this. If this issue is fixed, you can close this ticket

**Comment by raz08** [comment]
Ok. thanks
