### ISSUE TITLE
[extension/httpforwarder] Promote httpforwarder as stable

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#17435]
### Component(s)

extension/httpforwarder

### Describe the issue you're reporting

I would like to propose that the extension httpforwarder be considered stable, as it has not changed for some time, is used in production in many environments, and no further development is expected.

**Comment by dmitryax** [comment]
Can we resolve https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11128 first?

**Comment by dmitryax** [comment]
The reason this extension was added is to proxy Signalfx property updates that should be replaced with something that is OTel-compliant. Not sure if this exporter is being used for any other use cases. I suggest keeping this issue open to gather more evidence that this extension is being used for something else before declaring it stable.

**Comment by atoulme** [comment]
On 1/11, we had during the SIG meeting a discussion of this issue.
This [ongoing issue](https://github.com/open-telemetry/opentelemetry-collector/issues/5686) needs to be resolved first.
Juraci also noted that if the component depends on a library such as confighttp or configtls which are not marked stable yet, that blocks the component from being declared stable.

**Comment by atoulme** [comment]
Closing as we are not going to work on this right now. We can reopen when it's time to move to stable.
