### ISSUE TITLE
Script to ping code owners on new issues is failing

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#17488]
### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3877045093/jobs/6611597910#step:3:31
```
./.github/workflows/scripts/ping-codeowners-on-new-issue.sh: line 68: PINGED_COMPONENTS["${TITLE_COMPONENT}"]: bad array subscript
```

**Comment by frzifus** [comment]
hm. seems `TITLE_COMPONENT` is always empty :octocat:

**Comment by TylerHelmuth** [comment]
closing based on linked PR
