### ISSUE TITLE
Routing processor and/or OTTL support for randomized routing

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector-contrib#17502]
### Component(s)

Routing processor, OTTL functions.

### Is your feature request related to a problem? Please describe.

I would like to gradually deploy changes in my OTel Collector pipeline configuration. I would like to configure a pipeline that sends 10% of data items into an experimental exporter configuration, for example.

### Describe the solution you'd like

I would like to perform randomized routing similar to Envoy, as in

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routematch-runtime-fraction 

and

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/traffic_splitting#traffic-shifting-between-two-upstreams

and

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/traffic_splitting#traffic-splitting-across-multiple-upstreams

Note that there are several mechanisms shown in the links above

### Describe alternatives you've considered

I considered overly-simple solutions, including a OTTL primitive named `runtime_fraction(N, D)` that would randomly choose N out of D items, which is actually all I need.  The Envoy runtime_fraction method is based on a routing key however, like the routing processor has, but it also edits that key to support consistent routing decisions, which the routing processor does not (IIUC) support.

We could use a hash function of the data itself, however for my goal I want to route entire batches of data, not individual items, so we could hash the serialized data or a concatenation of certain fields, but this leads to a more complex solution than I'd like.

The envoy mechanism supports weighted routing as well, which is more complex than a simple OTTL function.

### Additional context

The simple OTTL function would look something like:

```
type runtimeFraction[K any] struct {
	intnFunc func(N int) int
}

func RuntimeFraction[K any](num, denom int) (ottl.ExprFunc[K], error) {
	if num < 1 {
		return nil, fmt.Errorf("runtime fraction numerator must be >= 1: %d", num)
	}
	if denom < 1 {
		return nil, fmt.Errorf("runtime fraction denominator must be >= 1: %d", denom)
	}
	if num > denom {
		return nil, fmt.Errorf("runtime fraction numerator must be <= denominator: %d, %d", num, denom)
	}
	rf := runtimeFraction[K]{
		intnFunc: rand.New(rand.NewSource(rand.Int63())).Intn,
	}
	return rf.evaluate(num, denom), nil
}

func (rf runtimeFraction[K]) evaluate(num, denom int) ottl.ExprFunc[K] {
	return func(_ context.Context, _ K) (interface{}, error) {
		// The 1+ below places the value in range [1, N]
		x := 1 + rf.intnFunc(denom)
		return num >= x, nil
	}
}
```

I created the `runtimeFraction[K]` type to facilitate deterministic testing. If anyone wants this, I have a test but I'm not sure this is worth finishing.

**Comment by kovrus** [comment]
@jpkrohling can you assign it to me?

**Comment by jmacd** [comment]
I've written a simple experimental-routing processor in https://github.com/f5/otel-arrow-adapter/pull/82

**Comment by jpkrohling** [comment]
That sounds like a great idea. Would you be open to sending in a PR with this new feature?

**Comment by jpkrohling** [comment]
Are you still interested in this, @jmacd? If so, perhaps this should be part of the routing connector instead?
