### ISSUE TITLE
Nomination: @atoulme as triager

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#17516]
### Describe the issue you're reporting

I would like to nominate @atoulme as triager for this repository. He has expressed interest in being one during today's SIG call, and I can attest he has been around for long enough to qualify as a triager.

**Comment by codeboten** [comment]
I support this 👍🏻

**Comment by atoulme** [comment]
Just reiterating that I have indeed expressed interest in this role. Thank you for the opportunity!

**Comment by djaglowski** [comment]
I support this as well 👍
