### ISSUE TITLE
[exporter/mezmo] component stability differs from readme

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#17514]
### Component(s)

exporter/mezmo

## Description

The readme marked the component as stable, but the code wasn't changed and is still reporting beta: https://github.com/logdna/opentelemetry-collector-contrib/blob/c10532dc4e76de3a703fb485afcffae663dc7b8c/exporter/mezmoexporter/factory.go#L29

### Collector version

latest

**Comment by jsumners** [comment]
@codeboten what are the ramifications of marking it stable? If we have to implement breaking changes in the future, does that imply a major version bump for the whole project?
