### ISSUE TITLE
[internal/comparetest] Add support for all metric types

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#17538]
Currently, comparetest.CompareMetrics only support Sum and Gauge metric types. It should support all metric types including Histogram, ExponentialHistogram, and Summary.

**Comment by dmitryax** [comment]
@fatsheep9146 please let us know if you can work on this, given that you added support for traces.

**Comment by fatsheep9146** [comment]
> @fatsheep9146 please let us know if you can work on this, given that you added support for traces.

Of course! I will support this. @dmitryax

**Comment by dmitryax** [comment]
@fatsheep9146 I submitted a PR because I need this feature for other work. PTAL https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17579.

Support of exemplars are still to be added
