### ISSUE TITLE
[internal/comparetest] Make all the exported functions not mutating

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#17549]
Currently, the defensive copying is done before applying Sort only for functions comparing top-level entities like `CompareMetrics`, `CompareTraces`, and `CompareLogs`. All other exported functions e.g. `CompareLogRecordSlices` are mutating because they apply Sort on the provided entities without making a copy before that. This should be fixed. All exported `Compare...` functions must be not mutating.

**Comment by jackycsl** [comment]
Can I work on this issue?

**Comment by dmitryax** [comment]
@jackycsl . Sure. Thansk

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17553
