### ISSUE TITLE
[internal/comparetest] comparetest enhancement  

### ISSUE THREAD

**Issue by fatsheep9146** [open-telemetry/opentelemetry-collector-contrib#17544]
The comparetest package has several enhancements need to be done. This issue is used to record

Metrics:
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17538
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17580

Traces:
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17414
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17588
- [x]  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18030
- [x] #18049

All types:
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17549
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17551
- [x] #17865

@open-telemetry/collector-contrib-approvers @open-telemetry/collector-contrib-maintainer Please feel free to add more enhancements!

**Comment by dmitryax** [comment]
Thanks, @fatsheep9146. I added couple of issues

**Comment by dmitryax** [comment]
All tasks are resolved! 🎉

**Comment by djaglowski** [comment]
Thanks for all the work on this @fatsheep9146. The package is much cleaner and more useful.
