### ISSUE TITLE
[exporter/clickhouse] moving database creation prcocess to a start function

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#17558]
### Component(s)

exporter/clickhouse

### Describe the issue you're reporting

origin :https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16477/files#r1051319797

moving all database creation(trace,log,metrics) prcocess to a start function.

**Comment by bputt-e** [comment]
it would be great if there was a setting to not attempt to create the database....for example, we'd generate the database (using distributed merge tree instead of just merge tree) and the user the collector uses only has insert capabilities

**Comment by dmitryax** [comment]
@bputt-e I see the database is created with `CREATE DATABASE IF NOT EXISTS`. So it shouldn't be a problem if you have your own database as long it's compatible with insert queries, right?

**Comment by bputt-e** [comment]
@dmitryax  from what I understand, when looking at the code, it doesn't matter what I name my database because it replaces it with the defaultDatabase, so the collector will always attempt to create the database in the default namespace

**Comment by dmitryax** [comment]
> @dmitryax from what I understand, when looking at the code, it doesn't matter what I name my database because it replaces it with the defaultDatabase, so the collector will always attempt to create the database in the default namespace

I cannot find this in the code. If that's the case, please submit an issue with more details

**Comment by bputt-e** [comment]
> > @dmitryax from what I understand, when looking at the code, it doesn't matter what I name my database because it replaces it with the defaultDatabase, so the collector will always attempt to create the database in the default namespace
> 
> I cannot find this in the code. If that's the case, please submit an issue with more details

Will do once I test further, code I'm referencing is https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/exporter_logs.go#L221

**Comment by hanjm** [comment]
> so the collector will always attempt to create the database in the default namespace

@bputt-e This code switch to default database is just to create another database in dsn, otherwise it could return `no such database` error when connect to the database use dsn.  it will not create table in default database.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/72d590e8e76a18bbec6d4ce8b6200520c5e94732/exporter/clickhouseexporter/exporter_logs.go#L194-L195

> it would be great if there was a setting to not attempt to create the database

I agree with you, add a config field like `create_database` `create_traces_table` etc..

**Comment by dmitryax** [comment]
> I agree with you, add a config field like create_database:bool create_traces_table:bool etc..

I still don't understand why do we need these config options if we have a configuration for a database name which is created only if it doesn't exist?

**Comment by hanjm** [comment]
> I still don't understand why do we need these config options if we have a configuration for a database name which is created only if it doesn't exist?

create database will do 1. dial to clickhouse 2. execute sql `create database if not exist` 3. close connection, i think it will slow a bit for start up when scale the collector or restart collector.

**Comment by dmitryax** [comment]
> create database will do 1. dial to clickhouse 2. execute sql create database if not exist 3. close connection, i think it will slow a bit for start up when scale the collector or restart collector.

Are you sure it's significantly slower? I don't think that was the concern raised by @bputt-e. Also, I see a benefit in doing it: we are validating the connection during the start time instead of potentially failing on each insert query.

**Comment by hanjm** [comment]
> I don't think that was the concern raised by @bputt-e.

Yes, `slow a bit` is just my option to agree add config setting. it not significantly slower, just a bit.

> we are validating the connection during the start time instead of potentially failing on each insert query.

This point is useful, the current logic is looks good for me.
