### ISSUE TITLE
Enhance the hostreceiver metrics to add OS information for each metric

### ISSUE THREAD

**Issue by ndsilva-splunk** [open-telemetry/opentelemetry-collector-contrib#17555]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

The [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver#getting-started) for the host metrics receiver lists the available scrapers and mentions which scrapers are OS specific.
This is helpful, but it would be even more useful if each scraper provided OS specific information for each metric.

### Describe the solution you'd like

Enhance the metadata.yaml in each of the /hostreceiver/internal/scraper/* directories to add a tag or attribute indicating whether or not the metric is available for a given OS.

**Comment by astencel-sumo** [comment]
Can you help me understand this issue better @ndsilva-splunk? Is it that there's missing information, or is it about making the existing information more visible or easier to read (perhaps by a machine)?

If I understand correctly, the current state is that:
1. For each scraper, there's information in the receiver's README about which platforms the metrics from the scraper are available on - e.g. the metrics from the `process` scraper are only available on Linux and Windows
2. For some metrics, there's additional information in the metric's description - e.g. the `process` scraper's `process.paging.faults` metrics has "This metric is only available on Linux" in its description.

**Comment by atoulme** [comment]
IIRC some memory metrics, for example iowait, are not available on Windows. We need to document which of the metrics and dimensions will show for each OS.

**Comment by astencel-sumo** [comment]
I just noticed that not all Linux-only metrics in the `process` scraper of the `hostmetrics` receiver mention this in their description. Namely [process.context_switches](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/documentation.md#processcontext_switches) and [process.open_file_descriptors](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/documentation.md#processopen_file_descriptors). This definitely needs to be updated.

Is it enough to just mention this in the metrics' description, as it is currently done e.g. for [process.paging.faults](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/documentation.md#processpagingfaults) - "This metric is only available on Linux.", or do we want some other mechanism?

**Comment by atoulme** [comment]
I wonder if that could be somehow added to metadata.yaml so it's easier to generate this info as part of documentation, and maybe down the road used in code generation.

**Comment by astencel-sumo** [comment]
I agree @atoulme it might be a good idea to add OS support information into the metadata.

For now though, can we just update the descriptions of the Linux-only metrics? I guess it's better than the current state?

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18051

**Comment by atoulme** [comment]
ok let's split this in 2 and fix the issue at hand for now manually. Adding this info to metadata.yaml is out of scope and should be a separate issue.
