### ISSUE TITLE
Support kubeConfig auth_type for kubeletstat receiver

### ISSUE THREAD

**Issue by hypnoce** [open-telemetry/opentelemetry-collector-contrib#17561]
### Component(s)

receiver/kubeletstats

### Is your feature request related to a problem? Please describe.

Some clusters require authenticated access to the kubelet endpoint using a token, usually provided in a kubeconfig file.

### Describe the solution you'd like

To have a seamless experience using the k8s_observer who is using kubeConfig auth_type, make kubeletstat receiver support kubeConfig auth_type as well.

**Comment by hypnoce** [comment]
@pmcollins @dmitryax any input on this ? Thanks.

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17562
