### ISSUE TITLE
[exporter/prometheusexporter] Implement exporting of `_created` metrics.

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/opentelemetry-collector-contrib#17567]
### Component(s)

exporter/prometheus

### Describe the issue you're reporting

Implement exporting of the `_created` metric in the `exporter/prometheusexporter` exporter. See [spec](https://opentelemetry.io/docs/reference/specification/compatibility/prometheus_and_openmetrics/#start-time).

The `_created` metric is supported in:

- `exporter/remotewriteexporter`, see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17417
- `receiver/prometheusreceiver`, see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17498

Dependency: https://github.com/prometheus/client_golang/issues/685

**Comment by fatsheep9146** [comment]
I think this issue is solved, right? @kovrus

**Comment by kovrus** [comment]
> I think this issue is solved, right? @kovrus

No, that is the issue for `exporter/prometheusexporter`, the `_created` metric is currently supported in `exporter/remotewriteexporter` and `receiver/prometheusreceiver` but not it `exporter/prometheusexporter`.
