### ISSUE TITLE
[pkg/translator/prometheusremotewrite] Implement Exponential Histogram downscaling

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/opentelemetry-collector-contrib#17565]
### Component(s)

pkg/translator/prometheusremotewrite

### Is your feature request related to a problem? Please describe.

When converting the Exponential Histogram to Prometheus Native Histogram its data points will be dropped if their scale is not in the `[-4, 8]` range.

### Describe the solution you'd like

Exponential Histogram data points should be downscaled to a scale accepted by Prometheus (range [-4,8]) if its scale is greater than 8. 

### Describe alternatives you've considered

Exponential Histogram data points can be dropped if their scales are greater than 8. 

### Additional context

See comments in https://github.com/open-telemetry/opentelemetry-specification/pull/3079

**Comment by krajorama** [comment]
I've started to work on this. I will _not_ introduce configuration to select the cutoff for downscaling (8), but I'll keep the code generic that it can be introduced later as needed.

**Comment by kovrus** [comment]
@krajorama thanks! I've assigned this issue to you.
