### ISSUE TITLE
Release v0.69.0 tagged with wrong dependency on pdata

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#17571]
### Describe the issue you're reporting

The v0.69.0 release was tagged with an depedency on pdata

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e3d2bd5041ffa8ab7eb1404420d9cdb46f0e051e/go.mod#L577

It should have been: `v1.0.0-rc3`

**Comment by dmitryax** [comment]
There must be no changes in pdata from `v1.0.0-rc3.0.20230109164642-7d168dd20efd` is the v1.0.0-rc3. Should we ignore it and fix in the next release?

**Comment by codeboten** [comment]
Yes, the reason i opened this issue was to make sure we catch this in the future

**Comment by mx-psi** [comment]
Should we close this as wontfix?
