### ISSUE TITLE
AWS Lambda Resource Detection Processor

### ISSUE THREAD

**Issue by burck1** [open-telemetry/opentelemetry-collector-contrib#17584]
### Component(s)

processor/resourcedetection

### Is your feature request related to a problem? Please describe.

Currently there is no seamless way to add AWS Lambda resource information into traces, metrics, and logs. Since there is support for running the Open Telemetry collector [within the AWS Lambda runtime](https://github.com/open-telemetry/opentelemetry-lambda), ideally there would be an easy way collect the AWS Lambda _host_ resource information via the collector.

### Describe the solution you'd like

Add a new AWS Lambda Resource Detection Processor, similar to the existing [aws](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor/internal/aws) resource detection processors.

The implementation should be similar the the [lambda detector](https://github.com/bhautikpip/opentelemetry-go-contrib/tree/main/detectors/aws/lambda) built into the `opentelemetry-go-contrib` repo where we can simply use the AWS Lambda [reserved environment variables](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime) to gather the necessary resource information.

Additionally, it would be nice if, like the [AWS EC2](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor#aws-ec2) resource detection processor, the lambda resource detection processor supported gathering tags for the Lambda Function. Like the EC2 resource detection processor, this would require that users add an IAM permission to the Lambda Function IAM role in order to get the function's tags, specifically the `lambda:ListTags` permission.

### Describe alternatives you've considered

Since the AWS Lambda Function resource information is exposed as environment variables, technically it should be possible to use the [Resource Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor) to insert / upsert attributes using environment variable values, but this would mean all users would need to know and understand the correct standard open telemetry attribute names and their corresponding AWS Lambda [reserved environment variable](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime) values. Also, this would not support collecting the lambda function's tags.

Another alternative that most users likely do today is to use a resource detector built into their programming language's open telemetry instrumentation library, like Go's [lambda detector](https://github.com/bhautikpip/opentelemetry-go-contrib/tree/main/detectors/aws/lambda), Python's [AwsLambdaResourceDetector](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/sdk-extension/opentelemetry-sdk-extension-aws/src/opentelemetry/sdk/extension/aws/resource/_lambda.py), Java's [LambdaResource](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-resources/src/main/java/io/opentelemetry/contrib/aws/resource/LambdaResource.java), .NET's [AWSLambdaResourceDetector](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Contrib.Extensions.AWSXRay/Resources/AWSLambdaResourceDetector.cs), JavaScript's [AwsLambdaDetector](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsLambdaDetector.ts), etc.

### Additional context

Assuming a new AWS Lambda Resource Detection Processor is created, likely the [OpenTelemetry Lambda](https://github.com/open-telemetry/opentelemetry-lambda) project and the corresponding [AWS managed OpenTelemetry Lambda Layers](https://github.com/aws-observability/aws-otel-lambda) project would need to be updated to include the Resource Detection Processor in their distributions.

**Comment by burck1** [comment]
I'd be willing to take a stab at making this update. Looks like I _should_ be able to use this [recent PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16840) as an example for what kind of changes would be required for adding in a new resource detector. I'd be interested in hearing feedback on the idea first though since I have never contributed to this repo before.

**Comment by atoulme** [comment]
It’s yours @burck1 !

**Comment by burck1** [comment]
@atoulme, [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17830) created. I decided to stick to just reading the AWS Lambda [reserved environment variables](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime) values for this PR. I figure that the lambda function tags support can always be added in a separate PR.

**Comment by burck1** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17830 has been merged. Closing.
