### ISSUE TITLE
Feature request: Add process metrics receiver MacOS

### ISSUE THREAD

**Issue by 8naama** [open-telemetry/opentelemetry-collector-contrib#17863]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

We want to collect process metrics for Mac. Currently the hostmetrics process metrics receiver is only implemented for windows and linux. 

### Describe the solution you'd like

Receiver that supports collecting process metrics in mac using shirou/gopsutil/process package.

**Reference**
- [Relevant file to implement](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_others.go)
- [functions supported for Mac processes in shirou/gopsutil ](https://github.com/shirou/gopsutil/tree/master#process-class)

**Limitations**
1. [Cwd()](https://pkg.go.dev/github.com/shirou/gopsutil/process#Process.Cwd) function is [not supported](https://github.com/shirou/gopsutil/blob/master/process/process_darwin_nocgo.go#L16) in mac with no cgo
2. disk usage for process is [not implemented](https://github.com/shirou/gopsutil/blob/master/process/process_darwin.go#L186) for darwin
3. PID 1 returns error `error reading parent pid for process "launchd" (pid 1): invalid pid 0` which seems to be related to this [open issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14311).

### Describe alternatives you've considered

I created a [Fork](https://github.com/8naama/opentelemetry-collector-contrib) of the repository that can collect Mac process metrics and handles the limitation like so:

1. using [Exe()](https://pkg.go.dev/github.com/shirou/gopsutil/process#Process.Exe) function returns errors when used in the collector:
	- `bad call to lsof: exit status 1` -  seems like the process has 'root' as the process owner
	- `missing txt data returned by lsof;` - seems like the process have a memory address in DEVICE or NAME params (running `lsof -p <PID>` in the terminal)

Instead of [Exe()](https://pkg.go.dev/github.com/shirou/gopsutil/process#Process.Exe) or [Cwd()](https://pkg.go.dev/github.com/shirou/gopsutil/process#Process.Cwd), we can use [Cmdline()]() and regex to cut the used path in the command. The issue is it's not always perfect:
```go
package main

import(
	"fmt"
	"regexp"
	"github.com/shirou/gopsutil/process"
)

func main() {
	processes, err := process.Processes()
	if err != nil {
		fmt.Println(err)
	}

	for _,p := range processes {
		processExecutablePath, err := p.Exe()
		if err != nil {
			fmt.Println(err)
		}
		processCmdArgument, err := p.Cmdline()
		if err != nil {
			fmt.Println(err)
		}
		regex, _ := regexp.Compile("^\\S+")
		processCmdArgument = regex.FindString(processCmdArgument)
		if processExecutablePath != processCmdArgument {
			fmt.Printf("CMDLINE command got different value than EXE for process %v\nExe(): %v\nCmdline(): %v\n\n", p, processExecutablePath, processCmdArgument)
		}
	}
}
```

2. Exclude darwin in the [scrapeAndAppendDiskMetrics](https://github.com/8naama/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go#L279) function to not collect the disk usage metrics
3. Exclude PID 1 in darwin in [parentPid](https://github.com/8naama/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/process.go#L134) function

### Additional context

Would be happy if anyone has any recommendations and feedback or other possible solution and would be happy to help implement such solution. Are there any plans to develop this receiver?

**Comment by codeboten** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18723
