### ISSUE TITLE
[telemetrygen] offer a rate per second rather than a time or number of records to emit

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#17888]
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

The current telemetrygen executable can either generate traces/metrics for a given duration or a fixed number of traces/metrics. 

### Describe the solution you'd like

In effect, neither are what we want: we'd instead like to be able to reliably emit a number of traces or metrics per second, so we can exercise testing flexibly.

**Comment by mx-psi** [comment]
This sounds like a reasonable feature to have, I would like to figure out the CLI first so that we have something consistent for all ways of expressing 'I want to emit data with this frequency/period/number/duration/[something else]'. Any proposals?

**Comment by jpkrohling** [comment]
`tracegen` has an integer as parameter, which is then interpreted as "traces per second": https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/tracegen/internal/tracegen/config.go#L79

I found that to be good enough for all cases I had so far.

**Comment by atoulme** [comment]
I discovered the `rate` parameter afterwards, I don't think it's documented quite yet.
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/telemetrygen#traces

So the scope of this ticket might be to make the docs reflect this parameter, as indeed it seems to fit our need.
