### ISSUE TITLE
[statsdreceiver] Counters are marked as monotonic

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#1789]
**Describe the bug**

Statsd count metrics are being reported as monotonic when they are not. This can cause other components to incorrectly assume monotonicity (currently the SignalFx exporter and in the future the Datadog exporter).

**Steps to reproduce**

Run an OpenTelemetry Collector with the statsd receiver and send a count metric to it.

**What did you expect to see?**

Statsd metrics being reported as non-monotonic.

**What did you see instead?**

Statsd metrics being reported as monotonic. For a metric sent as `counter.name:1|c`.

```
Metric #28
Descriptor:
     -> Name: counter.name
     -> Description:
     -> Unit:
     -> DataType: IntSum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
IntDataPoints #0
StartTime: 0
Timestamp: 1607442068000000000
Value: 1
```
**What version did you use?**
313a5a5b77ddb36ef947ab137e65806240bbac02

**What config did you use?**
Config: 

```yaml
receivers:
  statsd:
    endpoint: "localhost:8125"

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [statsd]
      exporters: [logging]
```

**Environment**
OS: macOS 10.15
Compiler(if manually compiled): go 1.15.5

**Additional context**

In StatsD, counters are not monotonic and work like deltas that are aggregated on the server side.

From [b/statsd_spec](https://github.com/b/statsd_spec):

> A counter is a gauge calculated at the server. Metrics sent by the client increment or decrement the value of the gauge rather than giving its current value.

From [statsd/statsd](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#counting):

> `gorets:1|c` This is a simple counter. Add 1 to the "gorets" bucket. At each flush the current count is sent and reset to 0.

They can increment or decrement and the instrumented application should report these increments or decrements rather than the whole value.

In the statsd receiver they are set as cumulative OpenCensus metrics:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a20a6f4f796244441f1cb9167dab0569b06f937f/receiver/statsdreceiver/protocol/statsd_parser.go#L169-L172

Cumulative values are [described by the OpenCensus proto as](https://github.com/census-instrumentation/opencensus-proto/blob/54c9a4c53e1fa422b92e3ae1cd6c72e181f744db/src/opencensus/proto/metrics/v1/metrics.proto#L89-L96):
> Floating [resp. Integer] point cumulative measurement. The value cannot decrease [...].
> Recorded values are always >= 0.

The OpenCensus translator then [maps this type into an IntSum with cumulative aggregation and monotonic](https://github.com/open-telemetry/opentelemetry-collector/blob/65588cc97912989f533e647a6caba5e99c50e1fe/translator/internaldata/oc_to_metrics.go#L199-L204).

I am not sure if they should be marked as cumulative either, given the [OpenTelemetry proto description](https://github.com/open-telemetry/opentelemetry-proto/blob/d0e9c0c92e9defe96251be18ce82991e6ec30b54/opentelemetry/proto/metrics/v1/metrics.proto#L180-L182):

>  aggregation_temporality describes if the aggregator reports delta changes
>  since last report time, or cumulative changes since a fixed start time.

but this seems to be more common (e.g. some components on the core repo do this too, like the [hostmetrics receiver](https://github.com/open-telemetry/opentelemetry-collector/blob/65588cc97912989f533e647a6caba5e99c50e1fe/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/filesystem_metadata.go#L41-L51)), so I am not sure if this last part should be considered a bug.

**Comment by mx-psi** [comment]
cc @keitwb @jmacd since you are CODEOWNERS of this component.

**Comment by gavindoudou** [comment]
Thanks for that, the new version has changed the type already: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/receiver/statsdreceiver/protocol/statsd_parser.go#L220
Please take a look if the issue can be resolved.

**Comment by mx-psi** [comment]
Closing since I can no longer reproduce the issue. Thanks for the fix!

**Comment by jmacd** [comment]
Hmmm. I think the correct output point for a Statsd counter should be the non-monotonic delta sum, not the gauge, but we can revisit this.
