### ISSUE TITLE
[receiver/prometheus] Do not clone the attributes map to create a signature

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#17901]
See if we can avoid adding empty attribute values to the datapoints, so we don't need to make a copy in [getAttributesSignature](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/metrics_adjuster.go#L134)

Originally raised by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17869#discussion_r1083322875

**Comment by bogdandrutu** [comment]
@dmitryax in the meantime instead of cloning, can we remove if empty? I think that should be faster.

**Comment by dmitryax** [comment]
> @dmitryax in the meantime instead of cloning, can we remove if empty? I think that should be faster.

Not sure I understand how you suggest removing it. We cannot mutate the original map, right? So making a full copy and removing empty values?
