### ISSUE TITLE
[pkg/stanza] Incorrect Stanza References

### ISSUE THREAD

**Issue by Dylan-M** [open-telemetry/opentelemetry-collector-contrib#17989]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

Some things from when Stanza was a standalone logging application, but not appropriate to OpenTelemetry, slipped into the pkg/stanza docs.

First, we have: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/file_input.md

Which I don't believe should even exist, since we use the filelog receiver instead.

Additionally, here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/csv_parser.md#parse-the-field-message-using-dynamic-field-names
We reference both the `file_input` operator, and reading dynamic field names using `label_regex`, which also does not exist as far as I'm aware.

This was reported by a customer to me, and they state it causes this error:
`1 error(s) decoding:\n\n* error decoding 'operators[0]': unmarshal to file_input: 1 error(s) decoding:\n\n* '' has invalid keys: label_regex`
Which makes it seem like `file_input` actually exists, so I could be wrong about that part.
I was not provided with a config, so I don't know exactly what they're attempting to do.

**Comment by djaglowski** [comment]
I think it is appropriate to retain the `file_input` doc (as well as the other input operator docs). It may not be a concern for users of the collector, but our docs also serve developers who can benefit here.

I agree that the `label_regex` reference is incorrect and should be removed.
