### ISSUE TITLE
telemetrygen command to generate metrics

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#17986]
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

The metrics command associated with telemetrygen outputs a message indicating metric generation is not currently supported.

### Describe the solution you'd like

Implement a metrics command similar to the traces command, generating metrics with the same argument as the traces command of telemetrygen.

**Comment by fatsheep9146** [comment]
Does this issue still have some unresolved tasks need to be done? @atoulme
