### ISSUE TITLE
[CI] Windows integration tests are not being run

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#18006]
### What happened?

There is no way to run tests with `//go:build windows && integration` in the CI, e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/activedirectorydsreceiver/integration_test.go. They should be run if `Run Windows` label is applied

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by Freedisch** [comment]
Hello @dmitryax , that seems like a good first issue for me, I would like work it. Do u have tips for me regarding the implementation?

**Comment by dmitryax** [comment]
Hi @Freedisch. Feel free to take it. We have an integration tests job that currently run on linux. we should also run it windows is `Run Windows` label is aplied

**Comment by Freedisch** [comment]
@dmitryax Hello, sorry to have taken some time before starting. I would like to know where I could find the CI that runs the integration test on Linux. I checked in the workflow directory and I didn't find it . Maybe i missed it🥲

**Comment by atoulme** [comment]
Please look under .github/workflows to get started.

**Comment by Freedisch** [comment]
> Please look under .github/workflows to get started.

I found did it, sorry i didn't pay attention

**Comment by pjanotti** [comment]
@dmitryax @atoulme @codeboten I think this one can be closed. If not let me know what is lacking to close it.

**Comment by pjanotti** [comment]
I reached the same conclusion as mentioned [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22480#issuecomment-1560145724): this requires a working Domain Controller (DC) and to setup one it requires rebooting the runner. My recommendation is to close this issue since the cost of setting the removed test is pretty high.

**Comment by dmitryax** [comment]
Ok, sounds good to me.
