### ISSUE TITLE
[receiver/splunk_hec] Add server authentication and security features

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#18000]
### Component(s)

receiver/splunkhec

### Is your feature request related to a problem? Please describe.

The splunk_hec receiver lacks features allowing it to be directly available on the public Internet.

### Describe the solution you'd like

Add multiple server authentication and security features so that the server can be exposed to the public:
* [ ] Add token authentication
* [x] Add basic auth authentication
* [x] Add any other authentication helper such as oauth, bundled with opentelemetry helpers
* [ ] Add allowed IPs allowlist and rejectlists

**Comment by shalper2** [comment]
Curious if there might be a way to create a solution as part of the overall SDK to allow for inclusion in other push based components?
