### ISSUE TITLE
[tools] Several local Makefile targets are broken

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#18009]
## Description
Prior to the recent tooling changes in #17849, it was possible to run each module's make targets against only that module. That changes appear to have introduced an assumption about the current directory which interfere single module make targets.

## Steps to Reproduce
Change working directory to any module other than the root module and run a make target. e.g. `(cd receiver/snmpreceiver && make lint)`

## Expected Result
The target runs successfully. `make lint` is run against the single module only.

Expectations are also described in [`CONTRIBUTING.md`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#module-level-targets).

## Actual Result
`No rule to make target `/Users/djaglowski/go/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/snmpreceiver/.tools/golangci-lint', needed by `lint'.`

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by djaglowski** [comment]
cc: @MovieStoreGuy

**Comment by djaglowski** [comment]
A possible solution may be to define (or determine) `TOOLS_BIN_DIR` in each individual Makefile.

**Comment by Aneurysm9** [comment]
Instead of `(cd receiver/snmpreceiver && make lint)` can you use `make -C receiver/snmpreceiver lint`?

**Comment by djaglowski** [comment]
Thanks @Aneurysm9, that works. Would be nice if it were a bit more resilient but I'm happy to adapt to this usage.

If anyone else is tripped up by this, feel free to ping me to reopen.

**Comment by djaglowski** [comment]
Reopening because to link to #18018

**Comment by MovieStoreGuy** [comment]
Sorry for this.
