### ISSUE TITLE
Mezmo Exporter does not support new pipeline URL format.

### ISSUE THREAD

**Issue by gjanco** [open-telemetry/opentelemetry-collector-contrib#18011]
### Component(s)

exporter/mezmo

## Description
Mezmo's pipeline offering uses a different url pattern than what the config of mezmoexport was supporting

## Steps to Reproduce
Setup a pipeline in Mezmo with a HTTP source
Copy the URL for the source
Use this URL as the ingest_url in the config.

## Expected Result
OTEL-collector should send logs to Mezmo Pipeline

## Actual Result
An error is thrown as the config is verified.

### Collector version

v0.70.0

## Environment
OS: Any

**Comment by fatsheep9146** [comment]
the issue is solved by #18012
