### ISSUE TITLE
[extension/jaegerremotesampling] This extension may be broken after importing Jaeger v1.42 code

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-collector-contrib#18047]
### Component(s)

extension/jaegerremotesampling

### Describe the issue you're reporting

This is just a heads-up issue with some pointers.

This extension uses `json.Marshal` from stdlib to render the sampling strategy:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8049c8c9ca22a722568cb16f3494094d8fb4da9a/extension/jaegerremotesampling/internal/http.go#L117

and has a unit test that validates the format (kudos):
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8049c8c9ca22a722568cb16f3494094d8fb4da9a/extension/jaegerremotesampling/internal/http_test.go#L90

However, it passes an auto-inferred type from `samplingStore` to `json.Marshal`, which happens to be Thrift-gen struct. This is changing in the next Jaeger release (https://github.com/jaegertracing/jaeger/pull/4181) to return Protobuf-gen struct, that may not work with stdlib `json.Marshal` (in Jaeger we're using `jsonpb.Marshal` from gogoproto).

Related issues:
  * https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3184
  * https://github.com/open-telemetry/opentelemetry-specification/issues/3126

Also, this extension attempts to emulate Jaeger agent endpoints, but their behavior on `/` and `/sampling` endpoint is actually different (explained in https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3184)

**Comment by jpkrohling** [comment]
@frzifus, are you able to handle this one?

**Comment by jpkrohling** [comment]
ping @frzifus
