### ISSUE TITLE
Add OS support to metadata.yaml

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#18055]
### Component(s)

cmd/mdatagen

### Is your feature request related to a problem? Please describe.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17555 for original ticket.

### Describe the solution you'd like

Please consider this as an enhancement request for discussion:
* Add supported OS to metrics metadata as part of metadata.yaml, optionally
* Generate documentation showing this so it's easier for end users to read

**Comment by dmitryax** [comment]
This probably should be a part of a generic system that defines constrains because these particular constrains are applicable to hostmetrics receiver only. We have an issue for that https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15995. Will need to think more about it
