### ISSUE TITLE
[extension/jaegerremotesampling] Misleading implementation on two endpoints

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-collector-contrib#18058]
### Component(s)

extension/jaegerremotesampling

## Description

This extension serves the same output on two HTTP endpoints `/` and `/sampling`, which presumably was meant to emulate the Jaeger Agent's behavior. However, in the Jaeger Agent the `/` endpoint returns a legacy format (see https://www.jaegertracing.io/docs/1.41/apis/#remote-sampling-configuration-stable).

This difference either needs to be called out in the README or fixed (although returning legacy format from this extension does not make sense, I'd rather it did not support this endpoint).

### Collector version

0.70.0

## Environment
any

**Comment by jpkrohling** [comment]
@frzifus, are you able to handle this?

**Comment by frzifus** [comment]
Sure, i will have a more detailed view next week.

**Comment by yurishkuro** [comment]
🎉
