### ISSUE TITLE
[exporter/loki] Do not retry permanent errors

### ISSUE THREAD

**Issue by wiardvanrij** [open-telemetry/opentelemetry-collector-contrib#18059]
### Component(s)

exporter/loki

## Description

Legacy exporter has: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/legacy_exporter.go#L164

New exporter hasn't: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/next_exporter.go#L105

This is pretty painful on 400 requests, like `has timestamp too old` = http 400. Which causes a ton of retries.

### Collector version

latest

**Comment by jpkrohling** [comment]
@wiardvanrij would you like to send a PR for this one?

**Comment by wiardvanrij** [comment]
Sure, I can take a look

**Comment by jpkrohling** [comment]
We release every two weeks, the next one on Feb 6th: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#release-schedule

**Comment by jpkrohling** [comment]
closed by #18083
