### ISSUE TITLE
Create a new receiver to accept logstash output generated by filebeat

### ISSUE THREAD

**Issue by shrenikjain38** [open-telemetry/opentelemetry-collector-contrib#18069]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like

Create a receiver which can spin up a go-lumber [server](https://github.com/elastic/go-lumber/tree/main/server) which will be accepting events from filebeat agent when logstash is configured as output in filebeat yaml.

### Describe alternatives you've considered

Looked for existing receiver which can support the lumberjack protocol but it is not available in opentelemetry-collector-contrib repo.

**Comment by shrenikjain38** [comment]
I am already working on this. Can you please assign it to me?

**Comment by jpkrohling** [comment]
Please, follow the guide on how to add new components outlined in the contributing guidelines. Among other requirements, you need to find a sponsor before opening the PR.
