### ISSUE TITLE
BasicAuth and HeadersSetter auth extension support for multiple header values

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector-contrib#18065]
### Component(s)

extension/basicauth, extension/headerssetter

## Description

Broader issue described in https://github.com/open-telemetry/opentelemetry-collector/issues/6965.

I am trying to make a gRPC streaming connection carry `client.Info.Metadata` for OTLP-Arrow over a "Bridge" that is meant to convey authorization so that it can be used in a multi-tenant environment where the "Edge" collector receives standard OTLP and sends via Arrow to the "SaaS" collector. I am trying to make metadata propagate and integrate with the client and server `Auth` extensions.

## Steps to Reproduce

I have tried to make the OTLP-Arrow components support the Auth extensions, including emulation of per-rpc-credentials for data items crossing the bridge that carry the original request headers. With an example shown in https://github.com/f5/otel-arrow-adapter/pull/107, I configure the `basicauth` extension for the edge OTLP standard receiver, the `headerssetter` extension for the edge OTLP arrow exporter, the `basicauth` extension for the saas OTLP arrow receiver, and the `headerssetter` extension for the saas OTLP standard exporter. This bridge configuration almost works, but due to a behavior of headerssetter I am required to modify basicauth.

As there is only one Auth extension API and instance, the Arrow streaming mechanism will call it once for the stream setup and once for each data item. (See again discussion in https://github.com/open-telemetry/opentelemetry-collector/issues/6965). The exporter's stream connection, which uses a background context, will have both the Auth extension and the exporter's static Headers configured. To be concrete, the OTLP-Arrow exporter is starting a stream, the headerssetter extension is called, and the result is a two-valued header, where in the one from `headersetter` is the empty string (because no client context) and the one from the exporter (via gRPC Outgoing Metadata) is set accordingly.

On the saas side the Arrow receiver sees new stream connections with "authorization" mapped to ["", "correct-auth"]. 

## Expected Result

I would like the basicauth mechanism to work in this case, one of its header values is empty and one is correct.

## Actual Result

The saas side's Auth fails the request because `basicauth` unconditionally uses the 0th value of the header, which in this case is the one from headersetter for a background context. If basicauth would take the first non-empty value, my example would work. 

### Collector version

v0.68

## Environment
v0.69.1 collector code base, v0.68 extensions

### OpenTelemetry Collector configuration

See the example configs in https://github.com/f5/otel-arrow-adapter/tree/main/collector/examples/metadata-bridge

### Additional context

If the headersetter extension were modified in one of several ways, _to avoid placing an empty value into the headeters_, that would also solve the problem. In situations where a header is configured statically and the value is not found in the context, if we could somehow let the static value through, then basicauth would work w/o modification.

**Comment by jpkrohling** [comment]
Coming back to this issue here: @jmacd, are you able to create a simple reproducer, perhaps on a self-contained collector config? Looking at the code, I wonder if you are using upsert as the headersetter action, or insert?
