### ISSUE TITLE
mysqlreceiver using "schema" and "table" attributes instead of "db.name" and "db.sql.table"

### ISSUE THREAD

**Issue by damiangarbacz** [open-telemetry/opentelemetry-collector-contrib#18073]
### Component(s)

receiver/mysql

## Description
mysql receives seems to be using a different naming convention than the one described in the semantic convention [database.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md). 

"schema" and "table" attributes should instead be labeled "db.name" and "db.sql.table" to follow recommendations:

In some SQL databases, the database name to be used is called "schema name". In case there are multiple layers that could be considered for database name (e.g. Oracle instance name and schema name), the database name to be used is the more specific layer (e.g. Oracle schema name).

## Expected Result
Schema name and table name should be stored in "db.name" and "db.sql.table" attributes.

## Actual Result
Schema name and table name are be stored in "schema" and "table" attributes.

### Collector version

67380f

**Comment by djaglowski** [comment]
I think overall intention here is to enable cross-signal correlation. However, it's not clear to me that this is achieved simply by changing these attribute names. Assuming the attribute names are aligned, we still need to be clear on _where_ these attributes belong.

Cross-signal correlation via attributes, as I understand it, is primarily concerned with matching resource attributes. However, the linked portion of the specification appears to be describing span attributes, and the attributes mentioned here are data point attributes.

I think there is a strong case to be made that schemas/databases/tables should be modeled as resources, and I would support that change in this receiver. However, I'm not a tracing expert and am unclear on whether it would be expected that the corresponding tracing attributes should also be resource attributes vs span attributes. Any thoughts on this?

**Comment by damiangarbacz** [comment]
Thanks for the answer @djaglowski! I'm not an expert on what should be the right naming convention but this example seemed like an inconsistency to me. I would like to understand what should be the right approach. 

I noticed that "schema" and "table" were defined in the receiver but are called differently in the specification. When referring to the same "thing" the logical approach for me would be to use a consistent naming convention, regardless of the type of the attribute. Moreover, as you mentioned, this would help a lot with correlating different types of signals. IMHO there should be a best practice approach documented somewhere - otherwise the naming convention across different receivers might easily diverge. 

I can see how having a "table" attribute both as a resource and a span attribute can duplicate the data. Perhaps the alternative could be moving some of the span attribute to the resource section and have it referenced by different signals? Otherwise, not providing any guidance can result in plenty of inconsistencies that might be even more difficult to fix later on. 

Then again - I'm new to OTel and it would be great to understand what how to best deal with such problems.
