### ISSUE TITLE
Groupbytraceprocessor gets overloaded in heavy pipeline

### ISSUE THREAD

**Issue by pkositsyn** [open-telemetry/opentelemetry-collector-contrib#1807]
**Describe the bug**
In https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1504 the leak of goroutines was fixed. It occured when there was heavy following processing. But still there is another issue - even though goroutines aren't leaked, `doWithTimeout` function waits for the processing (at most 1s but it is a lot). This overloads the processing queue resulting in an infinite grow of goroutines count.

**Steps to reproduce**
The same as for abovementioned issue

@jpkrohling This issue is addressed to you I think :)
The possible solutions:
1. Omit observability for `onTraceReleased`. The metrics are not actually relevant for this case. Only error handling is really important
2. Run `doWithTimeout` in a separate goroutine. This includes making a separate function of handling with observability (which only difference with the current in `go` word).

I like the first variant the most. I'll make a PR

**Comment by jpkrohling** [comment]
I took a look at the PR, and I'm not sure running the `onTraceReleased` on a separate go routine is the best solution. All events are processed by the machine as part of the same thread, and that changes with the PR. Async processing should probably made in the callback.

**Comment by pkositsyn** [comment]
This is the last event, so I don't see any problem in making it async - no work with queue should be done there. However, I agree, that for consistency it would be better to do as you said.

If we agree, that no work with queue should be done in `onTraceReleased`, then I think there's still no purpose in running this with observability.

**Comment by jpkrohling** [comment]
The problem isn't the observability itself, but that it synchronously waits for the onTraceReleased results, right? If you need to fire and forget, it might be better to add a new config option instead, no?

**Comment by pkositsyn** [comment]
To be honest, I don't like additional config option for whether showing 5 additional metrics or not. I'd better leave observability as it is now

**Comment by pkositsyn** [comment]
Done
