### ISSUE TITLE
Clickhouse - Use std batch api to insert data

### ISSUE THREAD

**Issue by StarpTech** [open-telemetry/opentelemetry-collector-contrib#18090]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

Hi, according to https://github.com/StarpTech/opentelemetry-collector-contrib/blob/feat/improve_clickhouse_conn_mgmnt/exporter/clickhouseexporter/exporter_logs.go#L94 we issue a request per log / trace. Is there any reason for that? This must be very inefficient. We can improve it by switching to https://github.com/ClickHouse/clickhouse-go/blob/main/examples/std/batch.go

```
begin->prepare->(in loop exec)->commit
```

### Describe the solution you'd like

Use prepared statement https://github.com/ClickHouse/clickhouse-go/blob/main/examples/std/batch.go

**Comment by hanjm** [comment]
> we issue a request per log / trace. 

no, whenuse batch processor, exporter will do batch insert. 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/650e62407f750c349bcb9c0419732dc6135528ea/exporter/clickhouseexporter/README.md?plain=1#L17-L20

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/650e62407f750c349bcb9c0419732dc6135528ea/CONTRIBUTING.md?plain=1#L154-L159

**Comment by StarpTech** [comment]
How does it work? Isn't `ExecContext` synchronous?

**Comment by hanjm** [comment]
clickhouse-go driver do that, when start a tx, `statement. ExecContext` only do insert at commit.

https://github.com/ClickHouse/clickhouse-go/blob/b2f9409ba1c7bb239a4f6553a6da347f3f5f1330/clickhouse_std.go#L280-L294

https://github.com/ClickHouse/clickhouse-go/blob/b2f9409ba1c7bb239a4f6553a6da347f3f5f1330/clickhouse_std.go#L314-L332

**Comment by StarpTech** [comment]
@hanjm great, thanks for clarifying.
