### ISSUE TITLE
LightStep exporter missing parentid

### ISSUE THREAD

**Issue by yoann-ls** [open-telemetry/opentelemetry-collector-contrib#181]
When the otel collector is configured to receive Zipkin spans and export them into Lightstep and Zipkin, it sounds like the parentId is not propagated with the LightStep exporter.

In LightStep, the spans are then not linked, so all traces are unique to the service operation and not fully assembled as they are with the Zipkin exporter. The expected behavior is that the traces are fully assembled in LightStep as well.

How to reproduce it:
- Context propagation is properly setup and configured with B3 headers and working in Zipkin.
- The otel collector version: v0.3.x 
- The configuration is similar to this:
receivers:
zipkin:
endpoint: "0.0.0.0:80"
exporters:
zipkin:
url: "http://localhost:8080/api/v2/spans"
lightstep:
access_token: "Lightstep access token"
service:
pipelines:
traces:
receivers: [zipkin]
exporters: [zipkin, lightstep]

**Comment by bogdandrutu** [comment]
Lightstep exporter was removed.
