### ISSUE TITLE
New component: Generic Webhook Receiver

### ISSUE THREAD

**Issue by shalper2** [open-telemetry/opentelemetry-collector-contrib#18101]
### The purpose and use-cases of the new component

Create a receiver which can take generic push based data. This would expose similar functionality as the SplunkHEC receiver when configured to receive raw inputs but would not support vendor specific data formats and would simplify the ingestion of webhook data. 

This would allow people to leverage otel's pipelines, processors, and exporters to broaden the applications that webhook data can be applied to. Additionally it could allow a user to take a single webhook input and fan it out to multiple upstream consumers.

### Example configuration for the component

```yaml
receivers:
  genericwebhook:
    tls:
      certfile: '/path/to/cert'
      keyfile: '/path/to/key'
    endpoint: 'webhook/endpoint'
```

### Telemetry data types supported

logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

The idea here is really to separate the general use case of ingesting push based data from the vendor specific implementation that is the SplunkHEC receiver. This will hopefully reduce confusion and allow for quicker adoption when this use case arises for a user who is not experienced with or is not using Splunk HEC.

**Comment by jpkrohling** [comment]
This would likely also help with #18098.

**Comment by atoulme** [comment]
Happy to sponsor this effort.

**Comment by shalper2** [comment]
I believe [this pr](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23239) closes out this issue. Component has been merged as the [webhook event receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/webhookeventreceiver)
