### ISSUE TITLE
[receiver/datadog] Replace gorilla mux

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#18191]
One thing to be conscious of is that this project is no longer being maintained, so in a future PR we may need to change it.

_Originally posted by @MovieStoreGuy in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5836#discussion_r1087639361_

**Comment by boostchicken** [comment]
This is resolved in the original pr #5836
