### ISSUE TITLE
[exporter/prometheus] Add exemplar support for monotonic sum metrics in Prometheus exporter

### ISSUE THREAD

**Issue by jlawrienyt** [open-telemetry/opentelemetry-collector-contrib#18201]
### Component(s)

exporter/prometheus

### Is your feature request related to a problem? Please describe.

While working on the [opentelemetry-demo](https://github.com/open-telemetry/opentelemetry-demo) project, adding exemplars to instrumentation, I discovered that the Prometheus exporter currently only adds exemplars to Histograms type metrics. 

### Describe the solution you'd like

To fully support exemplars, they should also been added, when available, to monotonic sum metrics.

**Comment by atoulme** [comment]
Looks like the work here is done, @jlawrienyt is it good to close?
