### ISSUE TITLE
[receiver/kafka] Allow Kafka Receiver to accept Azure Resource Log format

### ISSUE THREAD

**Issue by cparkins** [open-telemetry/opentelemetry-collector-contrib#18210]
### Component(s)

receiver/kafka

### Is your feature request related to a problem? Please describe.

When trying to ingest Infrastructure logs and metrics from Azure Resources through Diagnostic Settings using the Kafka Receiver the format used by Azure is not in an accepted format.

### Describe the solution you'd like

Allow the Kafka Receiver to ingest data from Azure Resource Logs and convert it into OpenTelemetry format.

### Describe alternatives you've considered

Using the Azure Event Hub Receiver or Azure Blob Storage Receiver.

**Comment by atoulme** [comment]
@MovieStoreGuy we can make our codecs shared across kafka and azureeventhub so users can reuse the logic. Azure event hub looks very similar to kafka, to the point it can be exposed as a kafka endpoint apparently.

**Comment by atoulme** [comment]
This is the formatter @cparkins references fwiw: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/azureeventhubreceiver/azure_formatter_impl.go

**Comment by MovieStoreGuy** [comment]
> @MovieStoreGuy we can make our codecs shared across kafka and azureeventhub so users can reuse the logic. Azure event hub looks very similar to kafka, to the point it can be exposed as a kafka endpoint apparently.

I had a proposal some time ago about having a an encoding package that provides a factory that can be passed around since other components like file receiver | exporter, kinesis exporter, kafka receiver | exporter, and even potentially the HTTP client could adopt.

I don't have an issue for it in principle, since we don't have this shared encoding package and we keep the kafka code generic enough that we can add other formats.

**Comment by martinjt** [comment]
I'm about to pickup expanding out the EventHub receiver to allow Diagnostic (audit etc.) logs and metrics to be taken by the eventhub receiver. This was likely to be quite hacky in the eventhub receiver. I was originally going to expand the kafka receiver to use the right authentication, and add the formats into that, but my feeling is that the eventhubs might be the better place?

My feeling is that with the eventhub receiver, we can detect what format the the event is and choose the right data type and transformation as it's more specific to event hubs?

I need this for a client, however, I'm more than happy for it to be work directly against the contrib repo. I'm no go-programmer, so it will likely need more of a thorough review.

**Comment by atoulme** [comment]
Nothing is hacky. Everything is a work in progress. @cparkins just landed metric support in azureeventhubreceiver, please take a look and feel free to open issues and PRs to make things better.

**Comment by cparkins** [comment]
Currently working to rebase, test and publish a PR for this.

**Comment by dmitryax** [comment]
@cparkins can you please summarize why you chose the kafka receiver instead of extending Azure Event Bus receiver? It's not clear from the issue. Without any details, it seems like Azure Event Bus is a better place.

**Comment by cparkins** [comment]
@dmitryax This feature already existed for Azure Event Hubs.  This will allow the traffic to be routed to Kafka as well, if desired.  For testing you can use Event Hubs to mimic Kafka and test that the traffic can be received by a Kafka instance.  In the future I may use this feature to read data from Kafka instead of Event Hubs.  For now it just makes the Kafka Receiver able to receive this data in case anyone is routing traffic to Kafka in Azure Resource Logs format.

**Comment by dmitryax** [comment]
> This feature already existed for Azure Event Hubs

Do you mean https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/azureeventhubreceiver? If that's the case, I don't understand why do we need this functionality in the kafka receiver... Can you please elaborate more on your use case?

**Comment by cparkins** [comment]
@dmitryax My use case was streaming Azure Resource Logs to Kafka before the Event Hubs Receiver existed.  I'm currently not using this feature but I think I may in the future. This will not limit the technology choices that I would make in the future for ingesting data from Azure.  I can see use cases where I would Stream data in this format from Azure into Kafka.

**Comment by martinjt** [comment]
It's probably worth noting that the Azure Event Hubs is Kafka compatible, therefore not maintaining 2 separate receivers would probably be better in the long run.

**Comment by cparkins** [comment]
Can we remove the stale label as I have an updated PR that is ready to be reviewed using the new Azure Translator Package pushed earlier this week.
