### ISSUE TITLE
Support negative lookahead in multiline config

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#18243]
### Component(s)

receiver/filelog

### Is your feature request related to a problem? Please describe.

In filebeat, multiline supports 4 kinds of behavior, below screenshot is taken from its [doc](https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html).

![image](https://user-images.githubusercontent.com/14903757/216261722-6723053d-6241-4b39-bdc2-027fbcd46acb.png)

but currently `multiline` only supports configure `line_start_pattern` or `line_end_pattern`, which doesn't cover all of them. Though this can be workaround by `recombine_operator`, however it seems require `source_identifier` to be set properly, i.e. based on log file path, which means `include_file_path` has to be true, and it has to be dropped by a processor later on(if it's not really needed).

Also because golang doesn't support negative lookahead, this can not be simply done by updating the regexp's negative lookahead.

### Describe the solution you'd like

An additional option to set negative in `multiline` config.

### Describe alternatives you've considered

* negate: false, match: after
  * is_first_entry: not (body matches '\<pattern\>')
* negate: false, match: before
  * is_last_entry: not (body matches '\<pattern\>')
* negate: true, match: after
  * is_first_entry: body matches '\<pattern\>'
* negate: true, match: before
  * is_last_entry: body matches '\<pattern\>'

**Comment by newly12** [comment]
Hi @djaglowski, question for this feature request, do you think it makes sense to support this in `multiline` config, if so, shall the implementation be done in the [multiline's](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/helper/multiline.go#L68-L85) `splitFunc` maybe?

**Comment by djaglowski** [comment]
@newly12, allowing negation of `line_start_pattern` or `line_end_pattern` seems reasonable.

It should be possible to pass a configurable boolean into `NewFooSplitFunc` and then include that when interpreting the result of `FindIndex`. (Basically [these lines](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e506d194e43c07e8deb326d475a97173c471dc8f/pkg/stanza/operator/helper/multiline.go#L153-L156)). I would start there and try work out appropriate behavior within the split funcs.

**Comment by newly12** [comment]
@djaglowski I might be able to spent some time on this, let me know if you'd like me to pick it up.

**Comment by djaglowski** [comment]
Thanks @newly12.

**Comment by newly12** [comment]
@djaglowski while I work on the implementation, I noticed for some test cases, it does not really check line breaker, but only consider the pattern regex, for example following ones, there is no newline characters, which means one log line could even be split to multiple lines, given its name multiline, it seems to be confusing.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d200d2e50fa0e086ea91fbcb76764294040754cf/pkg/stanza/operator/helper/multiline_test.go#L37-L58

and for your reference, with negate enabled, log lines might be split like this

https://github.com/newly12/opentelemetry-collector-contrib/commit/990afdae9fc7bb880823d4f0166243d411f10778#diff-cc019b3fd9d41ce1ca0cbc72fa94e708ca95ab9ea48896915887ab3bb0376aebR149-R162

**Comment by djaglowski** [comment]
> I noticed for some test cases, it does not really check line breaker, but only consider the pattern regex

one log line could even be split to multiple lines, given its name multiline, it seems to be confusing

I think I see what you are saying, that the name indicates combining multiple lines into one log, not for splitting multiple logs from one line. Maybe there is a better name but I think the name still works for the more common use case but users can understand that it's functionality may be applied to split logs from one line.

**Comment by newly12** [comment]
ok... I think the [doc](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver#multiline-configuration 
) states clearly

> If set, the multiline configuration block instructs the file_input operator to split log entries on a pattern other than newlines.

it is a splitter instead of something like recombining multiple log entries into one based on patterns, in this case, I think I should stay with the `recombine` operator and not adding new things to multiline config, thus I think this issue can be closed. Please let me know your thought on this.
