### ISSUE TITLE
Calculate delta for sum and count with histogram datapoints

### ISSUE THREAD

**Issue by khanhntd** [open-telemetry/opentelemetry-collector-contrib#18245]
### Component(s)

exporter/awsemf

## Description
Currently, `awsemfexporter` will calculate the delta value depends on the OTEL metric type (e.g [Counter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsemfexporter/datapoint.go#L113-L125), [Summary Count and Sum](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsemfexporter/datapoint.go#L161-L172)) by using [AdjustToDelta as a signal](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsemfexporter/datapoint.go#L66). The reason for this would be to avoid the values out of [2^64 which is not supported by CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html). However, one of the cases being missed here would be the Histogram Sum and Count where [Histogram Sum and Count returns the original value](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsemfexporter/datapoint.go#L135-L150). Therefore, it would be better for us to have a delta calculation for histogram Sum and Count 
### Collector version

v0.70.0 or all latest version

## Environment
A behavior in `awsemf` exporter. Therefore, any environment is affected.

**Comment by atoulme** [comment]
@khanhntd is this issue now fixed?
