### ISSUE TITLE
[receiver/postgresql] Resources attributes "database" and "table" not present in metrics

### ISSUE THREAD

**Issue by Alex-Garg** [open-telemetry/opentelemetry-collector-contrib#18246]
### Component(s)

receiver/postgresql

## Description
All metrics with resource attributes "database" and "table" (eg: postgresql.db_size, postgresql.operation...) are not splited by database.name

## Steps to Reproduce
Plug open-telemetry on a Postgres with 4 databases

## Expected Result
1 line per database for postgresql.db_size, postgresql.operation...

## Actual Result
Only 1 line, for the last database configure in postgresql.databases param without the database attribute

### Collector version

v0.69.0

## Environment
docker containers

### Log output

```shell
Metric #2
Descriptor:
     -> Name: postgresql.db_size
     -> Description: The database disk usage.
     -> Unit: By
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> environment: Str(xxx)
     -> node: Str(xxxx)
StartTimestamp: 2023-02-02 10:27:27.003422931 +0000 UTC
Timestamp: 2023-02-02 10:50:27.012141047 +0000 UTC
Value: 8172335
```

**Comment by djaglowski** [comment]
@Alex-Garg, I believe you may find the resource attributes in a separate section prior to the metrics. This is a common confusion with the logging exporter. Note that the resource attributes are printed once per resource, followed by all metrics for that resource, so you should not expect to see them in the section that you have shared.

**Comment by Alex-Garg** [comment]
@djaglowski, I am using otlp and prometheus exporter and I only have 1 line for de db_size (I have 4 databases so I was thinking to have 1 line for each of them). The size is the size of the last database.
I don't understand hwo I can retrieve the metric for each database.

**Comment by djaglowski** [comment]
It's not clear to me what you mean by "1 line". The sample output you posted appears to be from the file exporter, so I assumed you were referencing the output of that exporter.

We have test cases that validate that database and table names are correctly populated as resource attributes. See [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6b073849ddfa2ede5ee05767c4d6d5d8d8558e44/receiver/postgresqlreceiver/testdata/integration/expected_multi_db.json#L4-L19). Of course there could be a bug, but I do not believe your description matches the intended or typical behavior of the receiver.

**Comment by Alex-Garg** [comment]
Here is what I got this prometheus exporter :

# HELP postgresql_db_size The database disk usage.
# TYPE postgresql_db_size gauge
postgresql_db_size{environment="TST",instance="tgoipdbesba11",node="tgoipdbesba11",platform="GOIP",qualifier="V105"} 8.729391e+06

I just have this line when I'm calling the metrics.
This line concerns only the last database.

**Comment by djaglowski** [comment]
I'm not familiar enough with the prometheus exporter to say whether it is properly handling resource attributes.

I do not believe there is a problem with the postgresql receiver. However, we can determine this more clearly if you would please use the file exporter and post the full output here.

**Comment by Alex-Garg** [comment]
[postresql.log](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/10663923/postresql.log)
Hello,
Here is the log containing only postgresql logs

**Comment by djaglowski** [comment]
It appears to me that the receiver is working correctly. Each resource object contains the database and table names as resource attributes.

```json
{
  "resource": {
    "attributes": [
      {
        "key": "postgresql.database.name",
        "value": {
          "stringValue": "exchangemanager"
        }
      },
      {
        "key": "postgresql.table.name",
        "value": {
          "stringValue": "public.ref_half_flow"
        }
      },
```
