### ISSUE TITLE
Add support for metrics from the DataDog Agent

### ISSUE THREAD

**Issue by dsobolev-nr** [open-telemetry/opentelemetry-collector-contrib#18278]
### Component(s)

receiver/datadog

### Is your feature request related to a problem? Please describe.

Customers of DataDog that wish to use OpenTelemetry on their data encounter a problem with the current receiver as it only supports trace and not metrics or logs.

### Describe the solution you'd like

Customers of DataDog should be able to point any agent at an OpenTelemetry collector and process the metrics data emitted.

**Comment by jpkrohling** [comment]
@dsobolev-nr, I'm sure @boostchicken will be happy to review PRs implementing this.

**Comment by boostchicken** [comment]
Yeah absolutely, I don't know Datadogs format for metrics or logs, It doesn't use the trace agent format, I believe it goes direct to the API like in datadogexporter

**Comment by boostchicken** [comment]
https://docs.datadoghq.com/api/latest/logs/#send-logshttps://docs.datadoghq.com/api/latest/logs/#send-logs

https://docs.datadoghq.com/api/latest/metrics/#submit-metrics

I believe these are the API's it would need to support

**Comment by mvadu** [comment]
> https://docs.datadoghq.com/api/latest/logs/#send-logs
> 
> https://docs.datadoghq.com/api/latest/metrics/#submit-metrics
> 
> I believe these are the API's it would need to support

Those endpoints are more about if you want to send the metrics directly from code to DataDog HQ. But not about how the trace agent (dd-agent.jar for example) itself is sending them to datadog agent. I think this https://docs.datadoghq.com/tracing/metrics/metrics_namespace/ makes more send from trace metrics stand point. 

@dsobolev-nr  if you original usecase is related to custom metrics generated from your code using DataDog SDK, then it probably uses dogstatds method https://docs.datadoghq.com/metrics/custom_metrics/dogstatsd_metrics_submission/ and we have been successful in replacing the `dogstatsd` with [statsd exporter](https://github.com/prometheus/statsd_exporter) and translate custom metrics into Prometheus metrics.

**Comment by boostchicken** [comment]
This a totally different datadog agent,  The current receiver has t he Trace Agent API implemented, Metrics I do believe go directly to datadogs SaaS api.  

https://docs.datadoghq.com/api/latest/metrics/#submit-metrics

That is the API we need to create receiver for.  In theory not a ton of work. there are a lot of other APIs for querying and stuff that we won't since we don't store the data.  

If that approach sounds good I could whip something pretty quickly.

**Comment by ledor473** [comment]
Based on the [Vector implementation](https://github.com/vectordotdev/vector/blob/master/src/sources/datadog_agent/metrics.rs), it seems that datadog-agent relies on atleast 3 APIs (one of which doesn't seems to be documented) to submit the metrics to the SaaS:
```
/api/beta/sketches
/api/v1/series
/api/v2/series
```

**Comment by boostchicken** [comment]
So what do we want to implement here?  We just want to take in their format format for all of those endpoints and translate to OTel?  Quite a bit of work, happy get it rolling once we agree on the requirements.

**Comment by boostchicken** [comment]
Regarding attaching metrics to traces, I believe that is a specific featuere that will show metrics on the trace flame graph for datadog and does not really mean metric ingestion at large, at least last time I usd that was the case.  Feel free to correct me, your statsd approach probably works well, but dogstatsd does have some protocol changes you might run into, should we look at enhancing statsreciever to support dogstatsd offically?

> This a totally different datadog agent, The current receiver has t he Trace Agent API implemented, Metrics I do believe go directly to datadogs SaaS api.
> 
> https://docs.datadoghq.com/api/latest/metrics/#submit-metrics
> 
> That is the API we need to create receiver for. In theory not a ton of work. there are a lot of other APIs for querying and stuff that we won't since we don't store the data.
> 
> @MovieStoreGuy @jpkrohling
> 
> If that approach sounds good I could whip something pretty quickly.

**Comment by mvadu** [comment]
> To me, this means that I could point a datadog-agent to an OpenTelemetry Collector rather than to Vector to process the metrics before being sent to Datadog SaaS.

In my usecase, we have some legacy code instrumented with datadog way of tracing, with few custom metrics. We want to keep that generation code as is, and being able to send those metrics to non datadog SaaS (due to cost reasons). So getting the metrics tranlated to a prometheus standard similar to the DataDog receiver work done for traces will be cool.

**Comment by ledor473** [comment]
> Can you link the vector repo? 
> @boostchicken 

I believe the main function where the HTTP endpoint gets created is here: https://github.com/vectordotdev/vector/blob/master/src/sources/datadog_agent/metrics.rs#L37C15-L53

It's in Rust so I don't think we can reuse that easily but the logic to decode the message is in that metrics.rs file as well

**Comment by jpkrohling** [comment]
I'm all for implementing those endpoints, perhaps using Vector as the reference implementation.

**Comment by tejaskokje-mw** [comment]
Another reference implementation is by Victoria Metrics [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/f897d5241d4651bb4109ad5c9a94b8a2d96ec96b/app/vmagent/datadog/request_handler.go)
