### ISSUE TITLE
[receiver/mysql] Flaky integration test

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#18286]
### Component(s)

receiver/mysql

### What happened?

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4089471343/jobs/7052232713#step:6:544

```
    integration_test.go:70: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mysqlreceiver/integration_test.go:70
        	Error:      	Received unexpected error:
        	            	resource "map[mysql.instance.endpoint:localhost:3306]": scope "otelcol/mysqlreceiver": number of metrics doesn't match expected: 21, actual: 20
        	Test:       	TestMySqlIntegration/Running_mysql_version_8.0
--- FAIL: TestMySqlIntegration (0.00s)
    --- FAIL: TestMySqlIntegration/Running_mysql_version_8.0 (31.22s)
FAIL
```

origin from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18284

### Collector version

N/A

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by atoulme** [comment]
Hit it again just now https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4448508173/jobs/7811439053?pr=19754

**Comment by djaglowski** [comment]
Here again: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5026409038/jobs/9014709539#step:5:254

```
--- FAIL: TestMySqlIntegration (54.70s)
    integration_test.go:64: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mysqlreceiver/integration_test.go:64
        	Error:      	Condition never satisfied
        	Test:       	TestMySqlIntegration
FAIL
```

--- 

Not much detail with the error message returned by `pmetrictest`, so I will add more verbose debugging info to the scraper integration test framework (See #22022, #22104).

**Comment by djaglowski** [comment]
Thanks for capturing this. With the enhanced error message, it's now apparent that the metric we keep missing is `mysql.buffer_pool.limit`, which is the only metric retrieved with [`getInnodbStats`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fedfa255e5ecd87cc097619428cfc170e47e3762/receiver/mysqlreceiver/client.go#L20).

There's possibly a fix at the mysql level, but I'll also look into whether there's another reasonable place to retry within the framework.
