### ISSUE TITLE
Log group autodiscovery capped at 50

### ISSUE THREAD

**Issue by fcoeguiguren** [open-telemetry/opentelemetry-collector-contrib#18293]
### Component(s)

receiver/awscloudwatch

## Description
Documentation mentions that log group autodiscovery has a default value of 50, but if you put any value greater than that, you get an error mentioning that 50 is the max value. Even the example in the docs has 100 as limit but when you run it, it does not allow it.

## Steps to Reproduce
Launch the collector, configure the Cloudwatch log receiver with an autodiscovery value greater than 50

## Expected Result
The receiver can discover more than 50 log groups

## Actual Result
The receiver complains that it can only discover up to 50 log groups

### Collector version

v0.70.0

## Environment
Kubernetes 1.23

### OpenTelemetry Collector configuration

```yaml
extensions:
      health_check: {}
      memory_ballast:
        size_in_percentage: 40
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      resourcedetection:
        detectors: [ec2]
        timeout: 10s
    receivers:
      awscloudwatch:
        region: ap-northeast-1 
        logs:
          poll_interval: 1m
          groups:
            autodiscover:
              limit: 100
              prefix: /aws/lambda
       
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${MY_POD_IP}:8888
    exporters:
      logging:
        loglevel: debug
    service:
      extensions:
      - health_check
      - memory_ballast
      pipelines:
        logs:
          receivers: [awscloudwatch]
          exporters: [logging]
      telemetry:
        logs:
          level: "debug"
        metrics:
          address: ${MY_POD_IP}:8888
```

### Log output

```shell
2023-02-06T00:51:32.504Z	debug	awscloudwatchreceiver@v0.70.0/logs.go:267	attempting to discover log groups.	{"kind": "receiver", "name": "awscloudwatch", "pipeline": "logs", "limit": 100}
2023-02-06T00:51:32.555Z	error	awscloudwatchreceiver@v0.70.0/logs.go:168	unable to perform discovery of log groups	{"kind": "receiver", "name": "awscloudwatch", "pipeline": "logs", "error": "unable to list log groups: InvalidParameterException: 1 validation error detected: Value '100' at 'limit' failed to satisfy constraint: Member must have value less than or equal to 50"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscloudwatchreceiver.(*logsReceiver).startPolling
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscloudwatchreceiver@v0.70.0/logs.go:168
```

**Comment by schmikei** [comment]
So it turns out this is a limitation of the aws-sdk-go API I believe.

https://github.com/aws/aws-sdk-go/blob/740c2dd94c8d75423d045be60a10384107376268/service/cloudwatchlogs/api.go#L6589-L6591

I think we can try to process paginated results in the autodiscovery stage rather than just a singular call. I will look into that. I also think we'll need to update the validation if that's the case since at most it appears we can process 50 Log Groups per discovery request. 

@djaglowski could you assign me to this?
