### ISSUE TITLE
Loki Exporter Tenant auth behaviour

### ISSUE THREAD

**Issue by wiardvanrij** [open-telemetry/opentelemetry-collector-contrib#18302]
### Component(s)

exporter/loki

### Is your feature request related to a problem? Please describe.

We utilise open-telemetry as a central gateway. 
- We have a Loki cluster in each region
- In front of Loki we have open-telemetry collector

This provide us multiple benefits:
- We can use DNS weights on where clients should forward their logs
- It allows us to 'gatekeep' before it hits Loki
- It allows us to dynamically define "things" such as tenants (and gatekeep if needed). I.e.:
```
      - action: insert
        key: loki.tenant
        value: tenant
```
- Clients have a single domain and are never required to alter this, as we can "route" their logs to whatever backend

The problem I'm facing is that I do not see a method to define and/or pass-through GEL authentication. GEL uses a username + token and as far as I can see, I only have a method to define the auth layer as a 'singleton' that controls the auth layer for _everything_. This is quite troublesome for multi tenant clusters and/or those central endpoints. 

### Describe the solution you'd like

I would like to see a method to define and/or pass-through GEL authentication more dynamically. I want to have to option to base it on receiving headers and other wise fall back to inferring it from the logs. 

Furthermore I would like to have an option where I can set only the username, and leave the token more static. It's actually possible in GEL to generate a token that allows ingesting logs for multiple tenants. This is especially useful in multi tenant clusters where you have multiple tenants, but each can (re)use the same token. 

### Describe alternatives you've considered

An OTeL collector per tenant (and thus also endpoint) but this becomes as mess when you have 100's of tenants

### Additional context

I'm happy to elaborate this further in some session if needed.

**Comment by jpkrohling** [comment]
I have the impression we talked about this before, haven't we? I believe @kovrus might have had this case in mind when designing the header setter. Can you please take a look and see if it solves your main use case? https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/headerssetterextension

> Furthermore I would like to have an option where I can set only the username, and leave the token more static. It's actually possible in GEL to generate a token that allows ingesting logs for multiple tenants. This is especially useful in multi tenant clusters where you have multiple tenants, but each can (re)use the same token.

This should also be possible with the header setter: Similarly, you can use the header setter to both insert a static token and use the tenant id from the incoming connection.

**Comment by wiardvanrij** [comment]
Hm I can't recall we discussed it. I did however recently discussed it with the Loki team.

As for the header setter, I should explore it further but when I did it before I could not entirely figure out to define it for a "basic auth" type of header (user/password) for GEL.

**Comment by jpkrohling** [comment]
> Hm I can't recall we discussed it. I did however recently discussed it with the Loki team.

Then someone else in the community asked for something similar. I clearly remember discussing something like this before, and it wasn't with the Loki team :-)

**Comment by wiardvanrij** [comment]
ha, well let me take some time to explore the headersetter and I'll report back my findings :) Thanks!

**Comment by jpkrohling** [comment]
@wiardvanrij, do you think there's still something for us to do here?

**Comment by wiardvanrij** [comment]
I still need to test this (been so busy :D) - so, leave it closed for now. Thanks!
