### ISSUE TITLE
[receiver/k8sobjects] e2e test

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#18395]

**Comment by dmitryax** [comment]
@harshit-splunk we started adding e2e tests for k8s components. Please feel free to take this one if you have some capacity

**Comment by jinja2** [comment]
I am trying this receiver for some usecases and can add an e2e test. Please assign it to me.

**Comment by TylerHelmuth** [comment]
Thank you!

**Comment by atoulme** [comment]
Closing as complete, thanks @jinja2
