### ISSUE TITLE
Add proper  opencensus.resourcetypes for kubelet stats metrics

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector-contrib#1839]
**Is your feature request related to a problem? Please describe.**
All the metrics derived from kubeletstats receiver are marked with opencensus.resourcetypes as "k8". 

However the semantics have defined different resource types for pods, container and nodes. It would be beneficial to have correct resource type marked for different metrics for pod (k8s.pod.* metrics) nodes (k8.node.*) and containers (k8s.containers.*)  

**Describe the solution you'd like**

Resource initializes in resource.go of kubelet stats eg. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/receiver/kubeletstatsreceiver/kubelet/resource.go#L37 need to have proper semantics for types as defined in the semantics document https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/k8s.md#pod 

**Describe alternatives you've considered**

**Additional context**

**Comment by bogdandrutu** [comment]
Not going to fix since we will no longer produce OpenCensus data.
