### ISSUE TITLE
[processor/k8sattributes] e2e test for metrics

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#18391]

**Comment by dmitryax** [comment]
@fatsheep9146 can you take this along with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18392 ?

**Comment by fatsheep9146** [comment]
> @fatsheep9146 can you take this along with #18392 ?

Absolutely!

**Comment by fatsheep9146** [comment]
I think this issue is now blocked by #17898, since the telemetrygen is now not be able to generate metric data.

**Comment by dmitryax** [comment]
Sure. makes sense!
