### ISSUE TITLE
[pkg/stanza] Log converter has significant memory footprint at scale

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector-contrib#18411]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

The log converter logic in `pkg/stanza` to convert from a stanza entry to a plog Log has a large memory footprint at scale. 

Doing some pprof heap dumps it appears the largest memory footprint is from making copies of the plog entries in the aggregationLoop [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/adapter/converter.go#L204). It's also observed if the aggregationLoop gets blocked pushing it's logs to the `flushChan` [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/adapter/converter.go#L223) that two copies of all the plogs currently in `workerItems` exists in memory at a time.

I wrote out a possible solution of combining the workerLoops and aggregationLoop in a way where the stanza entries are converted into the final plog payload sent to the `flushChan`. This eliminated the need to aggregate plogs by resource in a separate goroutine.  I ran a test against a 1 million log file sending to GCP for 5 minutes. I used two versions of the collector, the v0.70.0 release and with my condensed loop change. I've included the process memory graphs below  collected by the hostmetrics receiver.

<img width="1663" alt="Screenshot 2023-02-06 at 3 03 06 PM" src="https://user-images.githubusercontent.com/11877763/217313917-bdeada27-5236-4af3-95d1-1869f958c210.png">

The condensed loop change uses significantly less memory over the same period of time. I've also included the pprof svg images that were collect at the end of each run. These show that the `copyTo` hotspot has been eliminated and less memory is used. 

Given these performance increases I'd like to propose opening a PR with the condensed loop change.

[Here](https://github.com/observIQ/opentelemetry-collector-contrib/blob/log-remove-aggregation/pkg/stanza/adapter/converter.go#L150-L207) is the code I first pass of code I wrote to condense the loops.

pprof images:
Collector v0.70.0:
![collector_v0 70 0](https://user-images.githubusercontent.com/11877763/217314977-10dd8556-c191-4adf-87db-6bba3fc54bc8.svg)

Condensed loop:
![condensed_loop](https://user-images.githubusercontent.com/11877763/217314973-74239fed-da19-459b-a60e-2a0a5286ccab.svg)

**Comment by djaglowski** [comment]
I'm very much in favor of removing complexity from the converter. 

It's not clear to me that we really should be batching within the package anyways. We removed all user-facing configuration before declaring `filelog` as `beta`. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16452#issuecomment-1408783863 is potentially another indication that we would be better emitting immediately.

In any case, I'd be happy to review a PR for your changes.
