### ISSUE TITLE
Use Go 1.19 `sync/atomic` wrappers instead of `go.uber.org/atomic`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#18456]
### Describe the issue you're reporting

Go 1.19 includes new builtin [atomic wrappers](https://go.dev/doc/go1.19#atomic_types) that can replace the usage of `go.uber.org/atomic`. We should switch to using these and ban the usage of `go.uber.org/atomic` via `depguard` (basically, inverting [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e506d194e43c07e8deb326d475a97173c471dc8f/.golangci.yml#L112)).

Counterpart of open-telemetry/opentelemetry-collector/issues/7160.

This is **blocked by** #18454

**Comment by mx-psi** [comment]
This is now unblocked

**Comment by dubonzi** [comment]
Hi @mx-psi, can I work on this?

**Comment by mx-psi** [comment]
@dubonzi sure, feel free to take a look at open-telemetry/opentelemetry-collector/pull/7220 for inspiration
