### ISSUE TITLE
New component: OpAMP Supervisor

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#18461]
### The purpose and use-cases of the new component

The OpAMP Supervisor is a binary that connects to an OpAMP server to receive configuration (Collector binary, user, Collector configuration, etc.), then will manage a Collector instance using that configuration. The Supervisor will work with the [OpAMP extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16462) to receive information from the Collector. There is a [design document](https://docs.google.com/document/d/1KtH5atZQUs9Achbce6LiOaJxLbksNJenvgvyKLsJrkc/edit) that provides an in-depth description about how this will work. There are still open questions on some aspects of the design, but most of the broad strokes should be in place.

There already exists an [example Supervisor implementation](https://github.com/open-telemetry/opamp-go/tree/main/internal/examples/supervisor/supervisor) that should show a little of how this might work, which will also likely serve as a starting point for this component.

If there is agreement that the supervisor should live in the Collector contrib repo, I can start working on the implementation.

cc @tigrannajaryan @portertech

### Example configuration for the component

There is an [example configuration](https://docs.google.com/document/d/1KtH5atZQUs9Achbce6LiOaJxLbksNJenvgvyKLsJrkc/edit#heading=h.6sh2emmccxhp) provided in the design document.

### Telemetry data types supported

N/A, this will run a Collector, which can be configured to receive or export any type of telemetry.

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

**Comment by tigrannajaryan** [comment]
I support implementing a Supervisor and I commit to review the PRs for it.

**Comment by atoulme** [comment]
I will sponsor this component.

**Comment by mhausenblas** [comment]
WIP

**Comment by evan-bradley** [comment]
Resolved via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19143
