### ISSUE TITLE
file exporter failed

### ISSUE THREAD

**Issue by yockgen** [open-telemetry/opentelemetry-collector-contrib#18482]
### Component(s)

exporter/file

## Description
otelcol service failed to start once change the only exporter from "logging" to "file" (see configuration file)

## Steps to Reproduce
1. Modified exporter to file (see Collector configuration file)
2. sudo service otelcol restart
3. sudo systemctl status otelcol

## Expected Result
Data to store in file that defined by fileexporter

## Actual Result
Collector even failed to start

## How I installed the OTEL collector
1. wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.53.0/otelcol_0.53.0_linux_amd64.deb

2. sudo dpkg -i otelcol_0.53.0_linux_amd64.deb

### Collector version

v0.53

## Environment
OS: Ubuntu 22.04

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:

  otlp:
    protocols:
      grpc:
      http:

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:

exporters:
  file:
    path: /data/temp/testyockgen.json

service:

  pipelines:

    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [logging]

    metrics:
      receivers: [otlp, opencensus, prometheus]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check, pprof, zpages]
```

### Log output

```shell
root@node1:/data/otel/config# sudo service otelcol restart
root@node1:/data/otel/config# sudo systemctl status otelcol
× otelcol.service - OpenTelemetry Collector
     Loaded: loaded (/lib/systemd/system/otelcol.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-02-09 15:40:56 +08; 506ms ago
    Process: 430230 ExecStart=/usr/bin/otelcol $OTELCOL_OPTIONS (code=exited, status=1/FAILURE)
   Main PID: 430230 (code=exited, status=1/FAILURE)
        CPU: 43ms

Feb 09 15:40:56 node1 systemd[1]: otelcol.service: Scheduled restart job, restart counter is at 5.
Feb 09 15:40:56 node1 systemd[1]: Stopped OpenTelemetry Collector.
Feb 09 15:40:56 node1 systemd[1]: otelcol.service: Start request repeated too quickly.
Feb 09 15:40:56 node1 systemd[1]: otelcol.service: Failed with result 'exit-code'.
Feb 09 15:40:56 node1 systemd[1]: Failed to start OpenTelemetry Collector.
```

**Comment by atingchen** [comment]
I will try to reproduce the problem.

**Comment by yockgen** [comment]
> I will try to reproduce the problem.

Thanks! I just tried InfluxDB exporter as below, same error observed when try to restart the service :
```
exporters:
  influxdb:
    endpoint: http://localhost:8086
    timeout: 500ms
    org: intel
    bucket: intel
    token: .xxx
    metrics_schema: telegraf-prometheus-v1

    sending_queue:
      enabled: true
      num_consumers: 3
      queue_size: 10

    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 3s
      max_elapsed_time: 10s
```

**Comment by atingchen** [comment]
otelcol --config=file:/etc/otelcol/config.yaml

**Comment by atingchen** [comment]
@yockgen Execute this command, you can see your error log.

**Comment by yockgen** [comment]
> @yockgen Execute this command, you can see your error log. Is there no /data/temp directory？

@atingchen I do not see the error run manually "otelcol --config=file:/etc/otelcol/config.yaml" (file exporter works fine), but seeing error  as descrbed in this issue if try to run as service:
1. sudo service otelcol restart
2. sudo systemctl status otelcol

**Comment by atoulme** [comment]
@yockgen unfortunately the status report does not contain logs of the collector, just that it failed to start. You might be able to get more logs using journalctl. Would you please post the following:
* Your service fiie
* The output of `ls -la /data/temp/`

**Comment by yockgen** [comment]
> 

I've found the root cause: 
1. the file output was created by the process first time and permission set as read-only
2. When the service restart again, the file created previously still there, and hit into "permission denied" error to write the file, journalctl reported as below
```
eb 13 10:39:24 node1 otelcol-contrib[45855]: 2023/02/13 10:39:24 collector server run finished with error: cannot build pipelines: failed to create "file" exporter, in pipeline "traces": open /data/temp/otel_db.json: permission denied
```
To resolve it, just need to remove the output file manually. Is it an expected behavior?

**Comment by atingchen** [comment]
> > 
> 
> I've found the root cause:
> 
> 1. the file output was created by the process first time and permission set as read-only
> 2. When the service restart again, the file created previously still there, and hit into "permission denied" error to write the file, journalctl reported as below
> 
> ```
> eb 13 10:39:24 node1 otelcol-contrib[45855]: 2023/02/13 10:39:24 collector server run finished with error: cannot build pipelines: failed to create "file" exporter, in pipeline "traces": open /data/temp/otel_db.json: permission denied
> ```
> 
> To resolve it, just need to remove the output file manually. Is it an expected behavior?

Thanks for your feedback.I don't think this is an expected behavior, I will try to fix this.

**Comment by atingchen** [comment]
> > 
> 
> I've found the root cause:
> 
> 1. the file output was created by the process first time and permission set as read-only
> 2. When the service restart again, the file created previously still there, and hit into "permission denied" error to write the file, journalctl reported as below
> 
> ```
> eb 13 10:39:24 node1 otelcol-contrib[45855]: 2023/02/13 10:39:24 collector server run finished with error: cannot build pipelines: failed to create "file" exporter, in pipeline "traces": open /data/temp/otel_db.json: permission denied
> ```
> 
> To resolve it, just need to remove the output file manually. Is it an expected behavior?
Thanks for your feedback. I don't think this is an expected behavior.

**Comment by atingchen** [comment]
Hi, @yockgen.The output of the file exporter is not read-only, by executing the command `ls -la testyockgen.json`, we can get the following results.
```shell
-rw------- 1 root root 6127 Feb 13 15:46 testyockgen.json
```
Instead of manually deleting the output files, we can also execute this command `sudo chmod 666 testyockgen.json` to solve this problem.
But I feel this is still not elegant and I'll try to find a better way to do this.

**Comment by atingchen** [comment]
We can start the otelcol service through the command `sudo systemctl start otelcol`, but sometimes it fails to start, and the startup failure log is as follows:
`
Error: cannot start exporters: open /data/otel/test.json: permission denied
`

Default otelcol.service is as follows:

```shell
[Unit]
Description=OpenTelemetry Collector
After=network.target

[Service]
EnvironmentFile=/etc/otelcol/otelcol.conf
ExecStart=/usr/bin/otelcol $OTELCOL_OPTIONS
KillMode=mixed
Restart=on-failure
Type=simple
User=otel
Group=otel

[Install]
WantedBy=multi-user.target
```

`otelcol.service` runs as `otel`, and this user does not have the operation permission of `/data/otel`, so the exporter fails to start.

Solution 1: We can modify the permissions of `/data/otel` through the command `chown otel:otel /data/otel`

Solution 2: Export the data to the `/tmp`
