### ISSUE TITLE
[receiver/awsxray] set `service.name` attributes 

### ISSUE THREAD

**Issue by p1ass** [open-telemetry/opentelemetry-collector-contrib#18480]
### Component(s)

receiver/awsxray

### Is your feature request related to a problem? Please describe.

When using the awsxray receiver, the required `service name` attribute is not set.
As a result, when I view traces, it is not always clear which service it is.

### Describe the solution you'd like

Copy the value of the `Name` field of `awsxray.Segment` to Resource attribute.

**Comment by atoulme** [comment]
Marking as fixed, thanks @p1ass !
