### ISSUE TITLE
support k8s.pod.hostname

### ISSUE THREAD

**Issue by alburthoffman** [open-telemetry/opentelemetry-collector-contrib#18494]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

Spans from our client contain a host attribute, which is pod's hostname in the metadata. 
And the bad news is pod's name is a little different from hostname. 

### Describe the solution you'd like

refer to this function: https://github.com/alburthoffman/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/internal/kube/client.go#L288 

We want to associate pod metadata based on the host attribute. But since k8s processor only support pod name, we could not do this.

### Describe alternatives you've considered

had tried to constructs the pod name from the host attribute, but it requires using regex to extract substring. 
And it also assumes that the name convention as well.

Overall it is not a good idea to do that by binding the name convention in our side.

**Comment by dmitryax** [comment]
@alburthoffman you can fetch `host.name` attribute with the resource detection processor:

```
processors:
  resourcedetection/env:
    detectors: [system]
``` 

Then you can rename it if needed with attributes or transform processor

**Comment by dmitryax** [comment]
@alburthoffman how would you fetch the pod host name from k8s API?

**Comment by alburthoffman** [comment]
the hostname is a part of pod spec, which is described here: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields

**Comment by dmitryax** [comment]
I see. Ideally the hostname first should be added here https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/resource/k8s.yaml#L48 ? Can you submit a PR for semantic conventions and the k8sattributes processor?

**Comment by alburthoffman** [comment]
sounds good. working on it. Thx

**Comment by codeboten** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18506
