### ISSUE TITLE
spanmetricsprocessor: Set resource attributes where possible

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#18502]
### Component(s)

processor/spanmetrics

### Is your feature request related to a problem? Please describe.

I was using the `spanmetricsprocessor` with `prometheusexporter` and was surprised to find the `service_name` as a label instead of `job`. 

Digging deeper, this is because the processor only sets metric attributes but not resource attributes.

### Describe the solution you'd like

I think we should set resource attributes _if we are aggregating by a resource attribute_. 

For example, if we are aggregating by `service.name` and `service.instance.id`, the dimensions in the metrics emitted should be part of resource attributes and not metric attributes.

### Describe alternatives you've considered

Use the transform processor to move the metric attributes to resource attributes.

**Comment by kovrus** [comment]
@gouthamve @albertteoh I'll implement it only for the `spanmetrics` connector, I'll keep the processor as it is.
