### ISSUE TITLE
error decoding 'receivers': unknown type: "pulsar" for id: "pulsar"

### ISSUE THREAD

**Issue by SyntaxEvg** [open-telemetry/opentelemetry-collector-contrib#18516]
### What happened?

 error decoding 'receivers': unknown type: "pulsar" for id: "pulsar" (valid values: [awsecscontainermetrics k8s_events prometheus signalfx aerospike awscloudwatch cloudfoundry collectd filelog fluentforward k8s_cluster kafka bigip carbon receiver_creator mysql googlecloudpubsub influxdb tcplog syslog vcenter flinkmetrics podman_stats skywalking apache dotnet_diagnostics nsxt purefa otlpjsonfile postgresql prometheus_simple zipkin awscontainerinsightreceiver elasticsearch rabbitmq riak wavefront otlp httpcheck kubeletstats googlecloudspanner jaeger mongodb mongodbatlas sqlquery couchdb jmx nginx windowsperfcounters active_directory_ds expvar statsd udplog zookeeper solace splunk_hec iis memcached opencensus sqlserver snmp docker_stats hostmetrics journald k8sobjects kafkametrics redis sapm awsfirehose awsxray])

Docker-compose otel/opentelemetry-collector-contrib:latest

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Additional context

![image](https://user-images.githubusercontent.com/94603687/218312547-a616df8f-f89e-4e8d-8db5-0fcb08667415.png)

**Comment by tjiuming** [comment]
OK, I'll track the issue. 
Pulsar receiver/export are `Alpha` features, did you tried the following steps?
https://github.com/open-telemetry/opentelemetry-collector/tree/main/featuregate#controlling-gates

**Comment by SyntaxEvg** [comment]
> OK, I'll track the issue. Pulsar receiver/export are `Alpha` features, did you tried the following steps? https://github.com/open-telemetry/opentelemetry-collector/tree/main/featuregate#controlling-gates

Hello, you can include this plugin in the image, how long do you have to wait for it to be enabled, I really need it

**Comment by tjiuming** [comment]
The related PR: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/293

**Comment by atoulme** [comment]
This is now fixed. Closing.
