### ISSUE TITLE
[CICD] [e2e/k8s] Run tests on 4 latest kubernetes versions

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#18514]
We need to run the k8s e2e tests on all supported k8s versions, the latest 4: https://kubernetes.io/releases/

**Comment by dmitryax** [comment]
@fatsheep9146 will you have a chance to take this one as well?

**Comment by fatsheep9146** [comment]
> @fatsheep9146 will you have a chance to take this one as well?

No problem :)
