### ISSUE TITLE
[connectors/spanmetrics] Use OTel Exponential Histogram to observe measurements for the latency metric.

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/opentelemetry-collector-contrib#18528]
### Component(s)

processor/spanmetrics
connector/spanmetrics

### Is your feature request related to a problem? Please describe.

Currently, the [fixed bucket histogram](https://opentelemetry.io/docs/reference/specification/metrics/data-model/#histogram) is used to observe latency measurements which requires providing the explicit bucket boundaries as the configuration parameter. It can be improved with adoption of the [exponential histogram](https://opentelemetry.io/docs/reference/specification/metrics/data-model/#exponentialhistogram). We should probably use `seconds` as units, see https://github.com/open-telemetry/opentelemetry-specification/issues/2977

### Describe the solution you'd like

Support OTel Exponential Histogram to observe measurements for the latency metric in the `spanmetrics` processor. It can be hidden behind feature gate for now.

**Comment by kovrus** [comment]
cc: @albertteoh

**Comment by gouthamve** [comment]
Note that the default aggregation for histograms is still `Explicit Bucket Histogram Aggregation`: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#default-aggregation

Not all backends support exponential histograms, but we should give the option to the users to produce exponential histograms if they want to.

However, we should switch to `seconds` probably in any case.

**Comment by kovrus** [comment]
> However, we should switch to seconds probably in any case.

It should be probably a separate issue on the `connectors/spanmetrics`.
