### ISSUE TITLE
[connector/spanmetrics] Rename the `operation` attribute to `span.name` 

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/opentelemetry-collector-contrib#18529]
### Component(s)

connector/spanmetrics

### Describe the issue you're reporting

It should bring [data point attributes produced](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/processor.go#L41-L46) by the `spanmetrics` connector closer to the specification, see [Span spec](https://opentelemetry.io/docs/reference/specification/trace/api/#span).

It is the change that will be done in the new (not yet enabled) component, so it does not break anything for the existing users. However, we have to inform users about these changes when migrating from spanmeterics processor to spanmeterics connector.

**Comment by albertteoh** [comment]
I think it's good, in principal, to bring this dimension name closer to the specification; so I have no objections.

Note that if we agree to rename `operation` to `span.name`, it will be a breaking change, which will also impact [Jaeger SPM](https://www.jaegertracing.io/docs/1.42/spm/).

**Comment by kovrus** [comment]
@albertteoh Maybe we can do this change in the new component `spanmetrics` [connector component](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18535) and mark `operation` as deprecated in the `spanmetrics` processor component.

**Comment by Frapschen** [comment]
I recommend the metric name in the new 'spanmetric' can follow [Prometheus's best practices](https://prometheus.io/docs/practices/naming/#metric-names). Giving a prefix to the metric name and keeping the `_total`.

**Comment by kovrus** [comment]
> I recommend the metric name in the new 'spanmetric' can follow [Prometheus's best practices](https://prometheus.io/docs/practices/naming/#metric-names). Giving a prefix to the metric name and keeping the `_total`.

The new `spanmetric` connector is the OTel component, by keeping `_total` as the metrics name we mix OTel data model and its naming convention with Prometheus conventions. I think, [Prometheus's best practices](https://prometheus.io/docs/practices/naming/#metric-names) have to be respected when generated metrics will be exported, e.g. with `prometheusremovewrite` and `prometheus` exporters  (and that is already implemented). See also discussion [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18199).

**Comment by albertteoh** [comment]
> @albertteoh Maybe we can do this change in the new component `spanmetrics` [connector component](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18535) and mark `operation` as deprecated in the `spanmetrics` processor component? Also, we can drop `_total` from the metric name in the `spanmetrics` connector. So we won't do any breaking changes in the processor now and will give users some time to migrate to the new `spanmetrics` connector that has these breaking changes. WDYT?

Great suggestion, and good timing with the new `spanmetrics` being recently merged! 👍🏼

**Comment by Cluas** [comment]
The current `spanmetrics connector` implementation is just a port, can we add a config like `standardized`, https://github.com/Cluas/opentelemetry-collector-contrib/commit/453042366c199ad5a01ca05d95b65141d204a7c7

**Comment by djaglowski** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18746
