### ISSUE TITLE
Improved logging for kafkaexporter

### ISSUE THREAD

**Issue by fredthomsen** [open-telemetry/opentelemetry-collector-contrib#18612]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

Currently the kafkaexporter has no info or debug level logs anywhere.  This makes it very difficult when debugging issues to see what is happening on the kafkaexporter and if it is even doing anything.

### Describe the solution you'd like

At the very least a simple message after sending data via the producer saying `X messages sent onto topic Y`.

### Describe alternatives you've considered

Muttering to myself and just checking the dumping data from the topic manually.

### Additional context

Happy to help with this.

**Comment by atoulme** [comment]
It's yours @fredthomsen ! Did you try to run with debug logging though?

**Comment by fredthomsen** [comment]
@atoulme yes I had debug logging enabled.  I turned it on and was surprised at first, as most other components give some informational logs, but then looking at code I saw that there are none.

**Comment by MovieStoreGuy** [comment]
> @atoulme yes I had debug logging enabled. I turned it on and was surprised at first, as most other components give some informational logs, but then looking at code I saw that there are none.

I have been very conscious about adding logging for the kafka receiver/exporter mostly because of performance risks, not saying we can't but I didn't want to accidentally generate noise that is wasting resources. 

If you have any suggestions in what you'd need to investigate issues, please feel free to mention them here.

**Comment by fredthomsen** [comment]
> > @atoulme yes I had debug logging enabled. I turned it on and was surprised at first, as most other components give some informational logs, but then looking at code I saw that there are none.
> 
> I have been very conscious about adding logging for the kafka receiver/exporter mostly because of performance risks, not saying we can't but I didn't want to accidentally generate noise that is wasting resources.
> 
> If you have any suggestions in what you'd need to investigate issues, please feel free to mention them here.

I understand your concerns.  Right now there is no indication whatsoever when looking at logs that the exporter has even started or is running which threw me off a bit when I had enabled debug logging and saw nothing.  Even some basic "metrics/logs/traces exporter created and pushing to topic X" log message that only shows up at initialization could do the trick.

**Comment by fredthomsen** [comment]
That would mostly cover the concern.  Again I think at least on initialization/startup something should be logged about how the receiver/exporter is configured and that is ready,but you two can make the final call there.

**Comment by atoulme** [comment]
Take a look here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/monitoring.md Would this help you, in particular the `otelcol_exporter_sent_metric_points` and `otelcol_exporter_send_failed_metric_points` metrics ?

**Comment by MovieStoreGuy** [comment]
@fredthomsen if you're using logging level info, the collector does log when it starts a component so those details should be there.

**Comment by fredthomsen** [comment]
👍🏻 Yup I see this.  This provides some sort of indication that the exporter has started.
