### ISSUE TITLE
[receiver/azureblobreceiver] Update github.com/Azure/azure-sdk-for-go/sdk/storage/azblob causes issues

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#18637]
### Component(s)

receiver/azureblob

### What happened?

The following errors occurred when updating the dependency. See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4175641197/jobs/7230841592#step:4:49

```
 Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:49:59: undefined: azblob.BlockBlobClient
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:49:83: undefined: azblob.UploadStreamToBlockBlobOptions
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:49:123: undefined: azblob.BlockBlobCommitBlockListResponse
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:52:56: undefined: azblob.BlockBlobClient
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:52:80: undefined: azblob.HighLevelUploadToBlockBlobOption
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:63:25: undefined: azblob.TransferManager
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:86:75: undefined: azblob.BlockBlobClient
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:86:107: undefined: azblob.UploadStreamToBlockBlobOptions
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:273:49: undefined: azblob.ContainerClient
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:325:84: undefined: azblob.ContainerClient
Error: /home/runner/go/pkg/mod/github.com/!azure/azure-kusto-go@v0.9.2/kusto/ingest/internal/queued/queued.go:86:107: too many errors
```

### Collector version

not-released-yet

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by mx-psi** [comment]
I think the issue is on a dependency on the `azuredataexplorer` exporter (grepping shows this dependency is only being used in that component)

**Comment by mx-psi** [comment]
The latest release of this dependency uses `v0.6.1` of the `azblob` module (https://github.com/Azure/azure-kusto-go/blob/v0.11.0/go.mod#L10 ) so we need to ask for a new release on their side

**Comment by mx-psi** [comment]
Reported upstream on: Azure/azure-kusto-go/issues/163

**Comment by ag-ramachandran** [comment]
Hello @codeboten and @mx-psi, we'll look at an upgrade to this week and raise a request with the latest version of the libs

**Comment by mx-psi** [comment]
I think I was wrong on the 'need to ask for a new release upstream' (see discussion on linked issue). We should update `azure-kusto-go` to v0.11.0, although there are some breaking changes to be addressed if I try to do that:

```
# github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuredataexplorerexporter
../../exporter/azuredataexplorerexporter/adx_exporter.go:221:3: unknown field 'Config' in struct literal of type kusto.Authorization
../../exporter/azuredataexplorerexporter/adx_exporter.go:224:27: cannot use config.ClusterURI (variable of type string) as type *kusto.ConnectionStringBuilder in argument to kusto.New
../../exporter/azuredataexplorerexporter/adx_exporter.go:224:46: cannot use authorizer (variable of type kusto.Authorization) as type kusto.Option in argument to kusto.New
```

cc @ag-ramachandran

**Comment by ag-ramachandran** [comment]
Hello @mx-psi, we're [on it](https://github.com/ag-ramachandran/opentelemetry-collector-contrib/tree/feature/UpgradeGoSDK) . This fixes the compilation, working in the changes to some test failures due to the version bump. We will get it done with a PR by the 2nd or 3rd (next week). Is that okay
cc : @asaharn

**Comment by ag-ramachandran** [comment]
Hello @mx-psi : We tried to address this in the PR. Kindly have a review when you get a chance
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19136
