### ISSUE TITLE
Flaky test: TestTraceE2E/statefulset

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#18676]
### Component(s)

processor/k8sattributes, testbed

### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4181235503/jobs/7242982697
```
=== RUN   TestTraceE2E/statefulset
    e2e_test.go:179: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/k8sattributesprocessor/e2e_test.go:179
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/k8sattributesprocessor/e2e_test.go:[14](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4181235503/jobs/7242982697#step:24:15)6
        	Error:      	Received unexpected error:
        	            	the following errors occurred:
        	            	 -  k8s.annotations.workload attribute not found
        	            	 -  k8s.statefulset.uid attribute not found
        	            	 -  container.id attribute not found
        	            	 -  k8s.pod.name attribute not found
        	            	 -  k8s.node.name attribute not found
        	            	 -  container.image.tag attribute not found
        	            	 -  k8s.labels.app attribute not found
        	            	 -  k8s.pod.uid attribute not found
        	            	 -  k8s.pod.start_time attribute not found
        	            	 -  k8s.statefulset.name attribute not found
        	            	 -  k8s.namespace.name attribute not found
        	            	 -  container.image.name attribute not found
        	Test:       	TestTraceE2E/statefulset
```

### Collector version

0.71.0

**Comment by dmitryax** [comment]
@fatsheep9146 can you please take a look?

**Comment by fatsheep9146** [comment]
> @fatsheep9146 can you please take a look?

ok, I take a look at it.

**Comment by atoulme** [comment]
One more occurrence: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4236028533/jobs/7360366830

**Comment by dmitryax** [comment]
@fatsheep9146 did you have a chance to look into this?

**Comment by fatsheep9146** [comment]
> @fatsheep9146 did you have a chance to look into this?

I already looking into this, but not have a good idea, I still keep digging this. 

For now, I assume that maybe the processor does not watch the creation of the pod in time, which result the info about the pod does not exists in cache. 

So when the traces data is coming, the processor can not find the pod info from cache, so it will not add attributes to trace data.

If so, we can only add more wait time for the processor to watch the pod.

@dmitryax

**Comment by dmitryax** [comment]
> If so, we can only add more wait time for the processor to watch the pod.

It might be an actual bug in the processor that we need to fix. If pod can send data, the processor should be able to fetch its details from k8s api

**Comment by fatsheep9146** [comment]
> > If so, we can only add more wait time for the processor to watch the pod.
> 
> It might be an actual bug in the processor that we need to fix. If pod can send data, the processor should be able to fetch its details from k8s api. I don't think we should adjust tests to make them pass

Ok i will continue check about the code.

**Comment by fatsheep9146** [comment]
I think I found the root cause.
I create a test pr to try to reproduce the failed cases and finally found one: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4239826943/jobs/7369683723

In this test case, I output the raw trace data and found the data of `job` workload is like following
line 1, there only exists several attributes not provided by `k8sattributeprocessor`, like following
```
{  
    "resourceSpans": [
        {
            "resource": {
                "attributes": [
                    {  "key": "k8s.container.name", "value": {} },
                    {  "key": "k8s.container.restart_count", "value": {}},
                    {  "key": "service.name", "value": {}},
                    {  "key": "k8s.pod.ip", "value": {}}
                ]
            },
            "scopeSpans": [...]
        }            
}
```

line 2 and all the others, the attributes are appended by  `k8sattributeprocessor` 
```
{  
    "resourceSpans": [
        {
            "resource": {
                "attributes": [
                    {  "key": "k8s.container.name", "value": {} },
                    {  "key": "k8s.container.restart_count", "value": {}},
                    {  "key": "service.name", "value": {}},
                    {  "key": "k8s.pod.ip", "value": {}},
                    {  "key": "k8s.pod.name", "value": {}},
                    {  "key": "k8s.pod.uid", "value": {}},
                    {  "key": "k8s.job.name", "value": {}},
                    {  "key": "k8s.node.name", "value": {}},
                    {  "key": "k8s.labels.app", "value": {}},
                    ....
                ]
            },
            "scopeSpans": [...]
        }            
}
```

I think this may happen when the pod cache is not ready in processor, but the span data is already comming.

The e2e test function now scan the trace data line by line, and will assert fail immedietly when it first meet the line which do not contain the attributes of k8sattributes processor, which will failed in this case.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c079a8fa8614e7c69422ba30783c9da5a3826ba8/processor/k8sattributesprocessor/e2e_test.go#L169-L180

So we should modify like this
```
	var err error
	for scanner.Scan() {
                ....
		len := traces.ResourceSpans().Len()
		for i := 0; i < len; i++ {
			resourceSpans := traces.ResourceSpans().At(i)

			service, exist := resourceSpans.Resource().Attributes().Get("service.name")
			assert.Equal(t, true, exist, "span do not has 'service.name' attribute in resource")

			if service.AsString() != expectedService {
				continue
			}
			err = resourceHasAttributes(resourceSpans.Resource(), kvs)
		}
	}
	assert.NoError(t, err)
```
In this logic, the test will still succeed when only the first several lines may not satisfy, and the test only failed if all the trace datas do not satisfy.
