### ISSUE TITLE
[connectors/spanmetrics] Drop `_total` from generated metrics names.

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/opentelemetry-collector-contrib#18677]
### Component(s)

connector/spanmetrics

## Description

The `spanmeterics` connector generates a metric with `_total` which is done to follow the Prometheus naming convention. The `spanmeterics` connector is OTel component and should be agnostic to any downstream components, we would like to drop `_total` from metrics names. In the case of Prometheus exporters, exporters will automatically add `_total` where it is needed. See discussion https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18199#issuecomment-1426002784

It is the change that will be done in the new (not yet enabled) component, so it does not break anything for the existing users. However, we have to inform users about these changes when migrating from `spanmeterics`  processor to `spanmeterics` connector.

**Comment by kovrus** [comment]
cc: @Claus @albertteoh

**Comment by albertteoh** [comment]
cc: @Cluas

**Comment by djaglowski** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18744
