### ISSUE TITLE
Does the azuremonitor exporter component support the new AppIns connection string?

### ISSUE THREAD

**Issue by jeffhostetler** [open-telemetry/opentelemetry-collector-contrib#18685]
### Component(s)

exporter/azuremonitor

### Is your feature request related to a problem? Please describe.

In [1,2] Microsoft describes how the existing "instrumentation key" is being deprecated 
and will be replaced with a "connection string".  

Does the `azuremonitor` exporter support this new API and/or is this work planned?
I skimmed the source, but didn't see any mention of it.

[1] https://github.com/microsoft/ApplicationInsights-dotnet/issues/2560
[2] https://learn.microsoft.com/en-us/azure/azure-monitor/app/migrate-from-instrumentation-keys-to-connection-strings

### Describe the solution you'd like

Update the config.yaml to support a new `connection_string` field to replace the
existing `instrumentation_key` field.  Update Azure API calls accordingly.

**Comment by mustaFAB53** [comment]
Hi Team,
Any updates on this?

**Comment by jeffhostetler** [comment]
I could do the work if there is interest in the feature and the area owners don't have time.  Any guidance or suggestions would be welcome.  IIRC MSFT said the deprecation will be around March 2024, so we still have time here.

**Comment by jeffhostetler** [comment]
Yes, this still relevant. MSFT will be deprecating the instrumentation key in/around March 2024.

**Comment by pcwiese** [comment]
If you have the time, please proceed with a PRSent from my iPhoneOn Jun 12, 2023, at 17:41, Jeff Hostetler ***@***.***> wrote:﻿
Yes, this still relevant. MSFT will be deprecating the instrumentation key in/around March 2024.

**Comment by jeffhostetler** [comment]
Will do.  Thanks.

**Comment by JesseEstum** [comment]
Interested in this feature as well.

**Comment by jeffhostetler** [comment]
It's on my TODO list, but it'll be a few weeks before I can get to it. If you want to take a stab at it, that would be fine.
