### ISSUE TITLE
[exporter/signalfx] Flaky test TestConsumeMetadata/Test_property_updates

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#18696]
```
=== RUN   TestConsumeMetadata/Test_property_updates
    exporter_test.go:1079: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/signalfxexporter/exporter_test.go:1079
        	Error:      	Should be true
        	Test:       	TestConsumeMetadata/Test_property_updates
        	Messages:   	timeout waiting for response
```

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4189853372/jobs/7262741303

**Comment by dmitryax** [comment]
The functionality is there and hasn't been changed for couple years. I'm putting p3 for now, if it happens again, will make it p2 and take care sooner

**Comment by rmfitzpatrick** [comment]
This was related to a too aggressive timeout with my recent changes: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18728
