### ISSUE TITLE
[receiver/azureeventhub] Allow Metrics in Azure Resource Log format to be received

### ISSUE THREAD

**Issue by cparkins** [open-telemetry/opentelemetry-collector-contrib#18690]
### Component(s)

receiver/azureeventhub

### Is your feature request related to a problem? Please describe.

Currently when receiving events in from Azure Event Hubs only log events are supported.  When working with Azure Monitor (Diagnostic Settings) there are two types of Events supported: Log and Metrics.

### Describe the solution you'd like

Allow the Azure Event Hub Receiver to receive metrics by converting the Azure Resource Logs into Open Telemetry Metrics to be processed by the Collector pipeline.

### Describe alternatives you've considered

Creating a process to convert from Log Events into Metrics in Splunk.

### Additional context

I think logically it makes sense to separate the two types to allow Azure Metrics to be processed in a separate pipeline for use cases where the Metrics may or may not be processed elsewhere.

**Comment by atoulme** [comment]
That's a good idea. @cparkins you showed me a fragment of such a metric doc as json, and I guess we could directly translate that to metric data and have the receiver deal with metrics.

Please let us know if you're interested to help out on this.

**Comment by cparkins** [comment]
I'm absolutely interested in helping.  Still working through my companies CLA process (I should have a meeting sometime soon to discuss my contributions).

**Comment by atoulme** [comment]
@cparkins did this land? I think it did but can't remember off the top of my head.

**Comment by cparkins** [comment]
@a

> @cparkins did this land? I think it did but can't remember off the top of my head.

It absolutely did. I'm using it in a container so it's there.

**Comment by atoulme** [comment]
Closing! Thanks!
