### ISSUE TITLE
[processor/transformprocessor] Add functionality to convert gauge metrics to histograms

### ISSUE THREAD

**Issue by kebroad** [open-telemetry/opentelemetry-collector-contrib#18731]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

We can instrument applications to export histograms, however some metrics, specifically defined ones from receivers, are not exported as histograms and it would be very helpful to be able to convert or reorganize these to histograms. This may also allow for some merging and aggregation capabilities when grouped with the groupbyattrs processor. 

### Describe the solution you'd like

A function, convert_gauge_to_histogram, that accepts 4 arguments:

- aggregation_temporality
- bucket_count
- upper_bound (optional)
- lower_bound (optional)

and takes the datapoints for that gauge metric and re-organizes them as a histogram.

### Describe alternatives you've considered

I've considered either lumping this into the metricstransformprocessor as a sort of aggregation, but those aggregations are many-to-one (sum,min,max,mean, etc.). This truly converts one metric to another.

### Additional context

I have written the functionality for this function and have a PR to follow. Thanks!

**Comment by TylerHelmuth** [comment]
@kebroad converting between metrics is not defined in the [OpenTelemetry metrics data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main//specification/metrics/data-model.md), so special care has to be considered for these situations.  For the conversions we've done in the past we had in-depth discussion about the use case and whether or not Contrib is willing to maintain this type of solution going forward.

- Can you add more details about why you'd like to do this conversion? 
- Which receivers are not reporting data like you wish?  
- What about the is the Gauge data type is not meeting your needs that a histogram does?  
- What is your proposal for a meaningful conversion between a gauge and a histogram?

**Comment by kebroad** [comment]
Hey @TylerHelmuth  and @Aneurysm9 , thanks for your feedback on this! I understand that this is somewhat of an interpretation and not necessarily an implementation of a standard, and do not want to contribute anything that is against the vision of the collector!

To answer your questions:
> Can you add more details about why you'd like to do this conversion?

Sure! We are using this function to convert gauges with grouped datapoints (from the `groupbyattrs` processor) into histograms, and then sending those to a backend to have a representation  of many machine's host metrics. We have collectors on each host sending utilization hostmetrics (cpu, memory, and fs utilization) on an interval which are received by a more centralized collector  described above. Due to constraints on the backend, we cannot send the metric from each machine directly to the backend for aggregation processing there.**Our main goal is that we want to do some sort of spatial aggregation to avoid storing high-cardinality metrics, and have that sent in a data type that can represent many hosts' metrics** 

> Which receivers are not reporting data like you wish?

I don't necessarily have a problem with the way with the structure that receivers are reporting data (ie [system.filesystem.utilization](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/documentation.md#systemfilesystemutilization), [system.cpu.utilization](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/cpuscraper/documentation.md#systemcpuutilization), [system.memory.utilization](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/documentation.md#systemmemoryutilization)). It makes sense that they are represented as gauges and I think it should stay that way. Perhaps if these metrics were received as histograms we could [merge them ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/metricstransformprocessor/operation_aggregate_labels.go#L262)with the `metricstransformprocessor`, however, this seems like  a large departure from the data model.

> What about the is the Gauge data type is not meeting your needs that a histogram does?

Touched upon this in the previous question, but essentially sending many individual metrics to the backend, especially at a large scale, cannot work in our situation.

> What is your proposal for a meaningful conversion between a gauge and a histogram?

To break it down into individual parts, the way I'd implement the conversion, given a gauge with multiple datapoints, is essentially:
1. Determine min/max/count/sum of the datapoints
2. Determine bucket/min width, count and bounds, or receive these from the parameters
3. Iterate over the datapoints and update the bucket's counts based on where the datapoint's value falls.

Currently, in my PR, I have bucket counts, upper bounds, and lower bounds as parameters to the function you can just set. This enables for consistent fixed buckets across histograms, assuming equal width buckets. Obviously this is not the most optimal way of grouping the data, and there are [many ways of doing this](https://en.wikipedia.org/wiki/Histogram#Number_of_bins_and_width), but I figured this would be a good start.

Given a gauge with a single datapoint, I would populate min/max/count/sum but would not necessarily populate the explicitBounds field. Perhaps a single bucket with a count of 1 would work here too, but I skip bucketing for a single datapoint gauge input.

Another wrinkle in this whole thing is the Aggregation Temporality. From what I can understand, in our use case, Delta temporality is what we are doing, as gauges intrinsically are based only on the last sampled metric:
```
Gauges do not provide an aggregation semantic, instead “last sample value” is used when performing operations like temporal alignment or adjusting resolution.
```
Therefore the values are a representation of the interval only and have no cumulative nature. Just like the above, I thought I would give the option for the user to define it, as this seemed like something for the backend to interpret.

This might be an overly simplistic approach to the problem, and I totally understand if there are fundamental changes to the PR needed, and will accommodate them as necessary!

> Are you willing and available to discuss this topic during the Collector SIG meeting?

I want to first gauge your thoughts on this, and if you feel like this is a path worth pursuing, I would have no problem discussing this in a SIG meeting!

 I can imagine other people may have this issue as well, as they need some way of ingesting data representing large amounts of similar or identical workloads. Perhaps they are just using sampling. I think the [metrics aggregation processor proposal ](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4968) could be a better way to solve this, however I haven't seen much traction on this from an implementation standpoint, at least what I can see from github.

Thanks again for your time and thoughts looking at this!

**Comment by seankhliao** [comment]
I recall inquiring about this at some point
https://cloud-native.slack.com/archives/C01N6P7KR6W/p1671184268749999

For us, it's a nice to have to reduce the total volume of metrics when you don't need the resolution of individual sources.
I had fuzzy thoughts on how this maps into the data models

**Comment by hughesjj-splunk** [comment]
> upper_bound (optional)
> lower_bound (optional)

these are for the values of the datapoints able to be ingested and not the number (ordinal/cardinality) of metrics for the histogram to be emitted right? 98% sure the former is intended.

**Comment by seankhliao** [comment]
exponential histograms would save us from needing to think about bucket bounds, though not sure about exporter / backend support for them.

**Comment by seankhliao** [comment]
On temporality, I think it would have to wait for https://github.com/open-telemetry/opentelemetry-specification/issues/2714 ?
Neither cumulative or delta makes sense to me for gauges

---

as it's not mentioned, datapoints keep all their attributes when converted to a histogram right? 
so you'd need a separate step to match up attributes for merging/aggregation

**Comment by ernest-liftoff** [comment]
i would be interested in this, with the advent of exponential metrics, it makes even more sense for operators to generate histogram from gauges, without needing to modify metric sources

**Comment by AndrewWinterman** [comment]
I just found this thread. Is there any advice for folks in this situation? Prometheus and Mimir are both constrained by the number of series, so my options seem to be either dropping fidelity and being unable to detect e.g. poor load balancing or blow out our metrics cost to maintain per pod dat.
