### ISSUE TITLE
Need a way to get emf logs from udp/tcp

### ISSUE THREAD

**Issue by sethAmazon** [open-telemetry/opentelemetry-collector-contrib#18758]
### Component(s)

exporter/awscloudwatchlogs, exporter/awsemf

### Is your feature request related to a problem? Please describe.

We want to match the cloud watch agent way of exporting emf logs to cw from json over tcp/udp. 

### Describe the solution you'd like

Add functionality to be able to export emf logs. 

### Describe alternatives you've considered

None

### Additional context

This is part of cloud watch agent task to move from telegraf to opentelemotry.

**Comment by atoulme** [comment]
Closing as fixed, thanks!
