### ISSUE TITLE
Enable  the `spanmetrics` connector component.

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/opentelemetry-collector-contrib#18760]
### Component(s)

connector/spanmetrics

### Describe the issue you're reporting

The `spanmetrics` connector is a port of the `spanmetrics` processor, but since it is going to be a new component, we thought that it can be a good time to fix some issues of the former `spanmetrics` processor in the new connector and bring the connector closer to the OTel spec, drop any related Prometheus specific conventions that the processor heavily uses, etc. 
 
We can deprecate the processor and keep both components for some time to give users time to migrate. It should not be that critical anyways because the `spanmetrics` processor's stability level is `in development`. 

 **TODO when enabling the component:**
- Enable the component
- Add a change log entry listing all the breaking changes and instructions on how to migrate from the `spanmetrics` processor to the `spanmetrics` connector 
   - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18529
   - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18678
   - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18677
   - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18502 
   - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19214
   - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18698
   - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18528
- Update READMEs of the processor and connector
- Deprecate the `spanmetrics` processor

**Comment by kovrus** [comment]
cc: @Cluas @albertteoh @djaglowski

**Comment by djaglowski** [comment]
Thanks for writing this up @kovrus. Sounds like a good plan, for both before and after enabling the connector.
