### ISSUE TITLE
Collect metric based on /proc/locks

### ISSUE THREAD

**Issue by ItsLastDay** [open-telemetry/opentelemetry-collector-contrib#18829]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

We're interested in metrics "how many file locks are taken right now" to understand the performance of our system better. I did not find a receiver that would export such metrics at a system level.

### Describe the solution you'd like

Extend `hostmetricsreceiver`'s "filesystem" scraper, so that it reads /proc/locks file on Linux systems and export the following metric:

system.filesystem.locks
Unit: {lock}
Metric type: gauge
Value type: Int

Attributes:
- device: Identifier of the filesystem, e.g. "fe:00"
- lock_type: The type of lock, "FLOCK" or "OFDLCK" or "POSIX"
- rw_type: "read" or "write"
- adv_type: "ADVISORY" or "MANDATORY"

/proc/locks also contains PID of the process that holds the lock, and [start, end] offset of the lock. We're not interested in that.

### Describe alternatives you've considered

Create a separate receiver just for lock-related metrics. 

### Additional context

Documentation: https://man7.org/linux/man-pages/man5/proc.5.html.

Here's example raw data:

```
$ cat /proc/locks
1: POSIX  ADVISORY  WRITE 3438608 fe:00:3815356 0 EOF
2: POSIX  ADVISORY  WRITE 3438608 fe:00:3815614 1073741824 1073742335
3: POSIX  ADVISORY  WRITE 3438608 fe:00:3815260 0 EOF
4: FLOCK  ADVISORY  WRITE 2010 00:33:87 0 EOF
5: POSIX  ADVISORY  WRITE 3438608 fe:00:3817093 0 EOF
6: POSIX  ADVISORY  WRITE 3438608 fe:00:3817103 0 EOF
7: POSIX  ADVISORY  WRITE 3438608 fe:00:3819367 0 EOF
8: POSIX  ADVISORY  WRITE 3438608 fe:00:3815247 1073741824 1073742335
9: POSIX  ADVISORY  WRITE 3438608 fe:00:3850011 0 EOF
10: POSIX  ADVISORY  WRITE 3438608 fe:00:3817087 0 EOF
11: FLOCK  ADVISORY  WRITE 1873 fe:00:664289 0 EOF
12: POSIX  ADVISORY  WRITE 3438608 fe:00:3939304 0 EOF
13: POSIX  ADVISORY  WRITE 3438608 fe:00:3815553 0 EOF
14: FLOCK  ADVISORY  WRITE 4301 00:1a:9 0 EOF
```

**Comment by ItsLastDay** [comment]
Side note: is there a general way to create metrics out of any file? 

I imagine that once connectors are ready to perform "logs -> metrics" conversions, I will be able to use filelogreceiver to read any file, then do some parsing with `transformprocessor` and create metrics like "count of lines with such and such properties". 

Is that a realistic image?

**Comment by astencel-sumo** [comment]
Regarding your proposal for a `system.filesystem.lock_count` metric, I think in general it fits the purpose of the Host Metrics receiver. Here are some questions/remarks I have to further refine the understanding of this proposal:

- The description of the metric you provided works for Linux. Are you able to provide this metric on other platforms, like Windows or MacOS?
- I think the metric name `system.filesystem.locks`would be more in line with the [pluralization docs](https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/#pluralization)
- The `Unit` of the metric would technically be `{locks}`, not `1`.

Regarding your question about a generic way to create metrics out of any data, here's a proposal that goes in this direction https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14753. (Haven't seen much activity on it recently though.)

**Comment by ItsLastDay** [comment]
> The description of the metric you provided works for Linux. Are you able to provide this metric on other platforms, like Windows or MacOS?

Not sure, I lack knowledge about those systems. Maybe that's doable.

> I think the metric name system.filesystem.lockswould be more in line with the [pluralization docs](https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/#pluralization)
> The Unit of the metric would technically be {locks}, not 1.

I agree, thanks for remarks! I'll edit the first message.

> Regarding your question about a generic way to create metrics out of any data, here's a proposal that goes in this direction https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14753. (Haven't seen much activity on it recently though.)

Thanks, I'll subscribe to that discussion.

**Comment by dmitryax** [comment]
I think this is a good metric to have. @ItsLastDay do you want to work on this?
