### ISSUE TITLE
Health Check: Support static response

### ISSUE THREAD

**Issue by ledor473** [open-telemetry/opentelemetry-collector-contrib#18824]
### Component(s)

extension/healthcheck

### Is your feature request related to a problem? Please describe.

Some load balancer or proxy ([like Envoy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#envoy-v3-api-msg-config-core-v3-healthcheck-httphealthcheck)) can be configured to check the response body for a specific match.
There might be cases where a standard response is expected and the load balancer can't easily be changed.
Currently the `healtchcheckextension` returns an empty body which wouldn't work.

### Describe the solution you'd like

Add a new `response_body` field in the configuration of the `healtchcheckextension` to always return that value when it's healthy.

**Comment by atoulme** [comment]
What should be the default value of that field?

**Comment by ledor473** [comment]
I think it’s probably best to not have any default. That way the current behavior won’t change while still allowing this unlocking this use-case.

I’d be happy to send a PR to support this

**Comment by atoulme** [comment]
Assigned to you!
