### ISSUE TITLE
(httpcheck-receiver): ability to set multiple targets

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-collector-contrib#18823]
### Component(s)

receiver/httpcheck

### Is your feature request related to a problem? Please describe.

One needs to setup multiple receivers one for each endpoint to enable synthetic checks against the HTTP endpoints.

### Describe the solution you'd like

Ability to specify multiple targets with just one receiver.

### Describe alternatives you've considered

Work around the limitation by adding one receiver for each endpoint.

**Comment by atoulme** [comment]
@srikanthccv would you like to work on this?

**Comment by codeboten** [comment]
This was fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23439
