### ISSUE TITLE
[pkg/telemetrygen] log subcommand support --otlp-insecure flag to be true

### ISSUE THREAD

**Issue by fatsheep9146** [open-telemetry/opentelemetry-collector-contrib#18868]
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

telemetrygen log subcommand should support --otlp-insecure flag to `true`, in order to send data with tls configuration.

### Describe the solution you'd like

telemetrygen log subcommand should support --otlp-insecure flag to `true`, in order to send data with tls configuration.

**Comment by graphaelli** [comment]
This should be flipped - allow `--otlp-insecure` to be false.  Right now it must be true for logs.

**Comment by Frapschen** [comment]
Close as already implemented in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/telemetrygen/internal/common/config.go#L122.

If anyone has any other questions, please reopen.

**Comment by graphaelli** [comment]
Thanks, looks like this was fixed by #29681
