### ISSUE TITLE
[pkg/telemetrygen] log subcommand support --otlp-http flag 

### ISSUE THREAD

**Issue by fatsheep9146** [open-telemetry/opentelemetry-collector-contrib#18867]
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

telemetrygen log subcommand should support --otlp-http flag to send log data by http scheme.

### Describe the solution you'd like

telemetrygen log subcommand should support --otlp-http flag to send log data by http scheme.

**Comment by axw** [comment]
I'll work on this issue.

**Comment by codeboten** [comment]
All yours @axw, thanks!
