### ISSUE TITLE
k8sattributes tests failing

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#18866]
### Component(s)

processor/k8sattributes

### Describe the issue you're reporting

e2e tests for kubernetes are failing. See

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4236650784/jobs/7361708703#step:24:16

Likely related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18767

**Comment by dmitryax** [comment]
Looks like a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18676

**Comment by codeboten** [comment]
👍🏻
