### ISSUE TITLE
Nightly Build

### ISSUE THREAD

**Issue by nicolastakashi** [open-telemetry/opentelemetry-collector-contrib#18877]
### Component(s)

All

### Describe the issue you're reporting

Would be awesome if `opentelemetry-collector-contrib` have nightly builds, so that users can leverage some improvements made (at their own risk) without waiting for a release.

**Comment by atoulme** [comment]
We have a docker build pushing the latest main here: https://hub.docker.com/r/otel/opentelemetry-collector-contrib-dev

does that work for your needs?

**Comment by nicolastakashi** [comment]
Hey @atoulme sure, helps of course.
BTW I don't find any doc about this.
Is this written in some place?

**Comment by atoulme** [comment]
I am not sure! Definitely worth documenting.

**Comment by nicolastakashi** [comment]
I didn't have the change to look at that!
I'll try to write something next week
