### ISSUE TITLE
[exporter/azuredataexplorer] deprecated dependency

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#18886]
### Component(s)

exporter/azuredataexplorer

### Describe the issue you're reporting

The component relies on a library being deprecated: https://github.com/Azure/go-autorest
>NOTE: The modules in this repo will go out of support by March 31, 2023. Additional information can be found [here](https://azure.microsoft.com/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/).

**Comment by ag-ramachandran** [comment]
Hello @atoulme , @codeboten , we're testing a newer version of the release that removes this deprecations and will get this out for a PR soon. @asaharn

**Comment by ag-ramachandran** [comment]
Hello @atoulme @codeboten. Fixed this in the PR : https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19136
Kindly have a look when you get a chance

**Comment by ag-ramachandran** [comment]
This is merged and can be closed

**Comment by codeboten** [comment]
Thanks @ag-ramachandran!
