### ISSUE TITLE
Support BooleanAttributes in the telemetrygen tool

### ISSUE THREAD

**Issue by petercline** [open-telemetry/opentelemetry-collector-contrib#18928]
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

Support was just merged for a BooleanAttribute PolicyType for tail sampling (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18764).  The telemetrygen tool should be able to generate traces with boolean attributes to facilitate testing and development of tail sampling policies that leverage this new PolicyType

### Describe the solution you'd like

In writing the referenced PR above, I made these changes locally.  The basic idea is to introduce a new struct type clled OtlpAttributes that includes two maps, one for string attributes and another for boolean.  this could be extended in the future to support numeric attributes as well.  The same --otlp-attribute flag is supported for backwards compatibility but now values that aren't quoted will be treated as boolean values if they are true or false, and as errors like previously otherwise

### Describe alternatives you've considered

We could support different flags for attributes of differing types.

**Comment by mx-psi** [comment]
This would be pretty simple to implement, would you be willing to open a PR @petercline?

To do this we would need to:
- Change `KeyValue` to be `map[string]any` here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/94e40253bc8375b8d22f9cfdfaa0656ac2e6bb6c/cmd/telemetrygen/internal/common/config.go#L31
- Check if `val` is `true` or `false` right before this line https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/94e40253bc8375b8d22f9cfdfaa0656ac2e6bb6c/cmd/telemetrygen/internal/common/config.go#L45

**Comment by petercline** [comment]
I already have an implementation of this locally @mx-psi and would be happy to open a PR.  My implementation differs slightly from what you suggest above.  I need to go through the approval process with my employer but that is relatively quick.  I should be able to post the PR later this week.  Thanks!

**Comment by mx-psi** [comment]
@petercline any updates on this?

**Comment by petercline** [comment]
Sorry, I still plan to tackle this, it has just been sidetracked by other
priorities.  I will get to it before the end of this month.
