### ISSUE TITLE
[Feature] Simple docker container metadata?

### ISSUE THREAD

**Issue by rwjack** [open-telemetry/opentelemetry-collector-contrib#18920]
### Component(s)

processor/k8sattributes, processor/resourcedetection

### Is your feature request related to a problem? Please describe.

Is there a way of gathering docker container metadata from `resourcedetection.detectors["docker"]`, such as container name, compose stack name, image name/tag?

Something similar to the k8sattributes processor?

### Describe the solution you'd like

A processor that collects basic docker metadata:
- container name
- compose stack name
- image name/tag

### Describe alternatives you've considered

Using logsprout as per:

https://github.com/SigNoz/signoz/issues/1597#issuecomment-1259234665

**Comment by dmitryax** [comment]
I think this is a valid feature request for the docker detector. @rwjack, feel free to contribute if you're interested
