### ISSUE TITLE
Add parsing of Go stack traces to AWS X-Ray Exporter

### ISSUE THREAD

**Issue by KKelvinLo** [open-telemetry/opentelemetry-collector-contrib#1893]
**Is your feature request related to a problem? Please describe.**
Currently the OpenTelemetry Go SDK does not contain the attributes in its span for a stack trace exception nor does it throw one. See [Issue#764](https://github.com/open-telemetry/opentelemetry-specification/issues/764).

**Describe the solution you'd like**
Implement the parsing of Go Exceptions and Errors in the awsxrayexporter when this fix is implemented in the OpenTelemetry Go SDK.

**Comment by mxiamxia** [comment]
This issue should have been fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4670
