### ISSUE TITLE
Export logs to Loki

### ISSUE THREAD

**Issue by gramidt** [open-telemetry/opentelemetry-collector-contrib#1894]
**Is your feature request related to a problem? Please describe.**
I would like to send log data to Loki (https://grafana.com/docs/loki/latest/)

**Describe the solution you'd like**
Have an exporter that sends log data to Loki.

**Additional context**
A PR will soon be provided that accomplishes this request. The primary driver for Loki is that its design is similar to that of Cortex and reduces the cost of operating a logging solution at scale. 

**Progress**
1. Initial structure and documentation of exporter (✔️  #1900 #1928 #1929)
2. Exporter implementation (✔️  #2262 #2385 #2389)
3. Add exporter to binary

**Comment by gramidt** [comment]
Update: PR #1952 will be finished and ready for review this coming week.

**Comment by gramidt** [comment]
@andrewhsu - Could you assign this to me?

**Comment by slim-bean** [comment]
Apologies @gramidt have not forgotten about this but haven't had a chance just yet to follow up!

**Comment by gramidt** [comment]
No worries at all, @slim-bean! I appreciate you taking the time to review and ensure that the implementation is the best it can be. 

On a side note, I would love https://github.com/grafana/loki-client-go to have an official versioned release, and assurance that it will be kept in sync, so that this implementation can use it for the generated protos and maybe eventually use the client pieces too.

**Comment by gramidt** [comment]
The exporter has been added to the binary. Other enhancements for the exporter exist as other GH issues. Closing this issue.
