### ISSUE TITLE
[Datadog] Deploment Tracking is not working

### ISSUE THREAD

**Issue by cemo** [open-telemetry/opentelemetry-collector-contrib#1896]
**Describe the bug**
Deployment tracking is not working on Datadog Exporter

**Steps to reproduce**
Add a value to *service.version*

**What did you expect to see?**
Deployments on Datadog side.

**What did you see instead?**
![image](https://user-images.githubusercontent.com/44156/102964335-6a40a180-44fc-11eb-8eee-119bd8f7ed3d.png)

**What version did you use?**
0.17.9

**Additional context**
Here is a part of a span and relevant tags for it.
![image](https://user-images.githubusercontent.com/44156/102964269-42e9d480-44fc-11eb-90c3-89c118bc8704.png)

Would you please take a look? 

CC: @KSerrania @mx-psi ,

**Comment by ericmustin** [comment]
👋 Hey there. @cemo  We're running a bit light over the holidays but wanted to try to help

A couple things to check quickly that could be culprits here

- Do you have a resource attribute `service.name` ? or are you setting the `service` setting in the datadog exporter config? I believe we rely on `service.name` and not `service.namespace` here when looking at resource attributes

- Do you have a `deployment.environment` resource attribute or an `env` setting in the datadog exporter config?

I believe, as per the [unified service tagging documentation](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes#overview), that service, env, and version are all required in order for deployment tracking to function as expected. 

If we verify the above and this is still not working as expected we'd probably want to investigate specific traces in your account, and so for the sake of not sharing PII over open issues i'd encourage you at that point to open a support ticket with datadog [here](https://www.datadoghq.com/support/), and we can share the findings/resolution in this issue for future users

**Comment by cemo** [comment]
Hi @ericmustin,

Our all environments (production, staging and test) are on the same kubernetes cluster. That is why we are not using datadog exporter config.

We are setting deployment.environment, service.name and service.version (You can see on our previous comment). 

![image](https://user-images.githubusercontent.com/44156/103007811-20c87480-4545-11eb-87dc-bb7695430ab1.png)

1.  We set `service.name` too. `service.name` is not visible on the trace attributes but I can see the app name in the ui. Before setting it, It was another name. 

2. `deployment.environment` is visible on the trace too. I can also see at the ui it is set. I can change environment.

So I can clearly say that deployment.environment, service.version and service.name are set. However `service.version` is not working. There may be another issue too I would be glad if you can check it.

**Comment by ericmustin** [comment]
@cemo Indeed, taking a look at some of your traces in the backend it seems like environment, service, and version are being correctly added to the traces. It's possible there is some additional work needed on the exporter's use of datadog-agent specific packages to ensure that the `version` tag is correctly appended to your trace related metrics. I am investigating this internally now, will try to follow up here as soon as I have some next steps or a resolution for you.

**Comment by cemo** [comment]
thanks @ericmustin, I guessed same because datadog agent can set it. I will be waiting your answer.

**Comment by mx-psi** [comment]
Hi, generally the same comments apply here https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1909#issuecomment-755969384 Traces issues are (for the most part) handled by Eric

**Comment by ericmustin** [comment]
@cemo 👋 hey there, just wanted to ping that we've put in a PR that should address this, and will aim to have this included as soon as possible, pending review https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2010

**Comment by mx-psi** [comment]
This should be fixed, if you are still having issues feel free to reopen it!
