### ISSUE TITLE
upgrade github.com/observiq/nanojack from 0.0.0-20201106172433-343928847ebc to 2.0.0+incompatible causes issues

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#19134]
### Component(s)

receiver/filelog

### Describe the issue you're reporting

```
Error: filelog_test.go:244:14: undeclared name: `nanojack` (typecheck)
make[2]: *** [../../Makefile.Common:166: lint] Error 1
make[1]: *** [Makefile:167: receiver/filelogreceiver] Error 2
make[1]: *** Waiting for unfinished jobs....
	rotator := &nanojack.Logger{
	            ^
Error: filelog_test.go:28:2: "github.com/observiq/nanojack" imported but not used as lumberjack (typecheck)
	"github.com/observiq/nanojack"
	^
```

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4287036996/jobs/7467507669#step:9:173 for details

**Comment by djaglowski** [comment]
As far as I can tell, #19075 attempted to upgrade nanojack to a non-existent version. This likely has something to do with nanojack being a fork of lumberjack. Perhaps it recognized the relationship and applied a lumberjack version bump to nanojack? In any case, I don't believe there's anything actionable unless there is a persistent problem w/ dependabot here.

**Comment by mx-psi** [comment]
Probably the implementation in dependabot/dependabot-core/pull/6713 is wrong?

**Comment by codeboten** [comment]
@djaglowski thanks for looking into it, i'll close this and re-open if it continues to be an issue.
