### ISSUE TITLE
[receiver/hostmetrics] Unit tests don't match implementation for darwin

### ISSUE THREAD

**Issue by antonblock** [open-telemetry/opentelemetry-collector-contrib#19141]
### Component(s)

receiver/hostmetrics

## Description

Since https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18723, a subset of process metrics is supported on Darwin. When I run unit tests locally on a Mac, the `processscraper/TestCreateResourceMetricsScraper` test fails because the method no longer returns an error. Additionally, the `skipTestOnUnsupportedOS` helper disables tests for metrics that are now supported on Darwin.

## Steps to Reproduce

On Darwin, run unit tests from the `github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver` package.

## Expected Result

Tests pass, and all metrics supported on Darwin are tested.

## Actual Result

The `TestCreateResourceMetricsScraper` test fails, most `process_scraper` methods are not tested.

### Collector version

11f8ed16b32359ef7f7b55e1b5df4789febd63c5

## Environment
OS: macOS 13.2.1
Compiler(if manually compiled): go 1.20.1

### Log output

```shell
--- FAIL: TestCreateResourceMetricsScraper (0.00s)
    factory_test.go:42:
        	Error Trace:	/Users/nico/contrib/receiver/hostmetricsreceiver/internal/scraper/processscraper/factory_test.go:42
        	Error:      	An error is expected but got nil.
        	Test:       	TestCreateResourceMetricsScraper
    factory_test.go:43:
        	Error Trace:	/Users/nico/contrib/receiver/hostmetricsreceiver/internal/scraper/processscraper/factory_test.go:43
        	Error:      	Expected nil, but got: &scraperhelper.baseScraper{StartFunc:(component.StartFunc)(0x1052db640), ShutdownFunc:(component.ShutdownFunc)(nil), ScrapeFunc:(scraperhelper.ScrapeFunc)(0x1052db5c0), id:component.ID{typeVal:"process", nameVal:""}}
        	Test:       	TestCreateResourceMetricsScraper
FAIL
```

**Comment by dmitryax** [comment]
@8naama, do you have a chance to submit a PR to update the tests?

**Comment by dmitryax** [comment]
Thanks, @astencel-sumo. Assigned to you

**Comment by 8naama** [comment]
hey guys @dmitryax @astencel-sumo, really sorry! I completely missed this!
Let me know if it's still relevant and I'll check

**Comment by astencel-sumo** [comment]
No worries @8naama, great to see you back! 😄 If you can contribute the fix, that would be great 👍

**Comment by astencel-sumo** [comment]
I've unassigned my self from this issue, @8naama should probably be assigned if I'm understanding correctly, is this right @8naama?

**Comment by 8naama** [comment]
@astencel-sumo yes you can assign to me 🙏🏼

**Comment by dmitryax** [comment]
Thanks, @8naama. Assigned to you

**Comment by 8naama** [comment]
Solved in [#20538](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20538)

**Comment by astencel-sumo** [comment]
Thank you so much @8naama. Looking forward to your future contributions!  :slightly_smiling_face:

**Comment by 8naama** [comment]
Thank you @astencel-sumo!! :)
