### ISSUE TITLE
[all] Enable govulncheck linter

### ISSUE THREAD

**Issue by lootek** [open-telemetry/opentelemetry-collector-contrib#19154]
### Describe the issue you're reporting

As a part of work in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9109 it would be beneficial to have [govulncheck](https://go.dev/blog/vuln) scans running in CI as well.

I think it's a great tool since it's part of the official Go toolset and as they state:
> Go provides tooling to analyze your codebase and surface known vulnerabilities. This tooling is backed by the Go vulnerability database, which is curated by the Go security team. Go’s tooling reduces noise in your results by only surfacing vulnerabilities in functions that your code is actually calling.

Also, please note it's NOT a part of `golangci-lint` (yet): https://github.com/golangci/golangci-lint/issues/3094.

**Comment by atoulme** [comment]
@lootek do you want to work on this? Happy to assign to you. Should we wait for this linter to be included in golangci-lint?

**Comment by lootek** [comment]
Yes, please. I don't feel like GH actions guru though but would be happy to help and give it a try :)
