### ISSUE TITLE
Flaky test: test-telemetrygen-job in kubernetes-test (v1.26.0)

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#19163]
### Component(s)

cmd/telemetrygen

## Description
Flaky test in `kubernetes-test (v1.26.0)` `test-telemetrygen-job`

## Steps to Reproduce

See recent failures:
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4304243979/jobs/7505000680#logs

## Expected Result
Test passed

## Actual Result
Test failed

### Collector version

HEAD of main branch

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by mx-psi** [comment]
@fatsheep9146 could you have a look?

**Comment by fatsheep9146** [comment]
> @fatsheep9146 could you have a look?

Ok, I will take a look.

**Comment by mx-psi** [comment]
@fatsheep9146 do you know if this issue can be closed?

**Comment by songy23** [comment]
I haven't seen this issue for a while, so I think it's safe to close it for now. We can reopen if it reoccurs.

**Comment by fatsheep9146** [comment]
> @fatsheep9146 do you know if this issue can be closed?
@mx-psi @songy23 
Sorry for my late response, I think this issue is safe to be closed, I did not see this problem happen any more.
