### ISSUE TITLE
[cmd/mdatagen] Add warnings in resource_attributes section

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#19174]
Author of metadata.yaml should be able to specify the same warnings in `resource_attributes` section as available in the `metrics` section. This is needed to provide a graceful way to handle changes to default/optional resource_attributes.

**Comment by abhide** [comment]
@dmitryax I would like to work on this issue. Can you please assign it to me?

**Comment by dmitryax** [comment]
Thanks, @abhide . Assigned to you
