### ISSUE TITLE
could load-balancing exporter support otlp http

### ISSUE THREAD

**Issue by ypwlal** [open-telemetry/opentelemetry-collector-contrib#19185]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

load-balancing exporter now only support otlp grpc exporter, could it support otlp http exporter? it will be friendly deploy in k8s cluster. Thks

**Comment by Aneurysm9** [comment]
> I think this issue should be transferred to https://github.com/open-telemetry/opentelemetry-collector. 

Why?  The [loadbalancing exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/loadbalancingexporter) lives in this repo.

**Comment by jpkrohling** [comment]
Given that we now have connectors, I would like to consider how to best evolve this component before accepting new features. 

@kovrus, perhaps you also have something in mind for this?

**Comment by jpkrohling** [comment]
@kovrus, I think there's still value in having the load balancing as an exporter, but I'm eager to hear your opinion before accepting a new feature for this component.
