### ISSUE TITLE
[receiver/receivercreator] Add support for traces

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#19206]
### Component(s)

receiver/receivercreator

### Is your feature request related to a problem? Please describe.

Currently the receivercreator only supports metrics.

### Describe the solution you'd like

Add support for traces.

**Comment by rmfitzpatrick** [comment]
This was resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19641
