### ISSUE TITLE
[exporter/loki] Auto convert OpenTelemetry ResourceAttributes to log labels

### ISSUE THREAD

**Issue by fkalinowski** [open-telemetry/opentelemetry-collector-contrib#19215]
### Component(s)

exporter/loki

### Is your feature request related to a problem? Please describe.

The `Resource Attributes` are very interesting to use as labels in the log events.

With the current implementation, I need to declare an explicit mapping in my collector's configuration for each `Resource Attribute`. This approach requires to reconfigure my `opentelemetry-collector` each time an application introduces a new `Resource Attribute` (available in SemConv or not).

Moreover due to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14113 I need to declare each ResourceAttribute twice - which can be tedious.

### Describe the solution you'd like

Since Loki's backend is largely inspired by the Prometheus backend (Loki uses Mimir implementation of Prometheus compliant backend), that seems natural to apply the same constraint and have the same feature sets than [exporter/prometheusremotewriteexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusremotewriteexporter).

That would be great if the feature `resource_to_telemetry_conversion` could be ported into the `lokiexporter`.

### Additional context

@gouthamve https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14113#issuecomment-1456263808

**Comment by kago-dk** [comment]
Were you still planning to implement resource_to_telemetry_conversion in the Loki Exporter?

**Comment by mar4uk** [comment]
Yes, it would be good to have

**Comment by mar4uk** [comment]
still relevant

**Comment by sathieu** [comment]
This issue is still relevant.

But another road will be possible in the next loki version: https://grafana.com/docs/loki/next/send-data/otel/

**Comment by jpkrohling** [comment]
@sandeepsukhani, do we have a logic like that already on the Loki side?

**Comment by sandeepsukhani** [comment]
> @sandeepsukhani, do we have a logic like that already on the Loki side?

Hey @jpkrohling, [we have this logic documented](https://grafana.com/docs/loki/next/send-data/otel/#format-considerations). The code for converting otlp format to loki format can be found [here](https://github.com/grafana/loki/blob/46c6118eb2a2d56406042431dfbed288df6e924b/pkg/loghttp/push/otlp.go#L104)

**Comment by jpkrohling** [comment]
@mar4uk, do you think the logic can be reused?

**Comment by jpkrohling** [comment]
Yes, sounds good to me!

**Comment by mhulscher** [comment]
I found this issue because I am also looking to store attributes as structured metadata. After the seeing the (static) list of converted attributes I was a little skeptical of the proposed solution. However, the docs clearly mention that it will be possible to extend or even replace this list. That would be amazing!

**Comment by mk-raven** [comment]
Also interesting about this issue.
Any updates?

**Comment by crutonjohn** [comment]
this is a feature i'd like as well. been spending hours and hours trying to get otelcol to send "native" loki labels. a plug-and-play option would be awesome.

**Comment by jpkrohling** [comment]
@mhulscher , @mk-raven , @crutonjohn , given that Loki 3.0 supports OTLP natively, I'm interested in knowing whether you still see the need for the Loki exporter.

**Comment by mk-raven** [comment]
@jpkrohling hello! We needed this exporter because some service, use loki api for store telemetry data in Clickhouse DB.
There are products like qryn, oteldb and other could integrate loki api for natively support logs querying in Grafana UI. Without manage custom plugins. Its great feature for many companies and teams.

**Comment by jpkrohling** [comment]
> qryn, oteldb

A quick look into both makes me believe they support OTLP natively as well.

**Comment by mk-raven** [comment]
Its true, but Grafana UI doesn't support query in otlp format. Its has Clickhouse plugin, but for many people its hard to using. Better use  natively LogQL, PromQL and TraceQL

**Comment by mk-raven** [comment]
But from otlp logs there no query filters in Grafana, if You use LogQL and Loki datasource.

**Comment by jpkrohling** [comment]
It's certainly possible to use LogQL to query a Loki data source containing logs that were ingested via OTLP.

**Comment by jpkrohling** [comment]
I'm closing, as the Loki exporter will be deprecated soon and this won't likely be sorted out on that component.
