### ISSUE TITLE
[SplunkHecReceiver] Align receiver errors messages to splunk enterprise 

### ISSUE THREAD

**Issue by splunkericl** [open-telemetry/opentelemetry-collector-contrib#19219]
**Is your feature request related to a problem? Please describe.**
Currently the HEC receiver error messages and HTTP status code is different than splunk enterprise. 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-717f2348-7fff-cadc-b408-8369ff28c8d6"><div dir="ltr" style="margin-left:0pt;" align="left">

Status Code + Message | Splunk Enterprise | Otel HEC Receiver | Explanation
-- | -- | -- | --
200 Success | X | X |  
403 Token disabled | X |   | Token management is not supported on EP.
401 Token is required | X |   | Token validation is not supported on EP.
401 Invalid authorization | X |   | Token validation is not supported on EP.
403 Invalid token | X |   | Token validation is not supported on EP.
400 No data | X |   | We can contribute back to otel.
400 Invalid data format | X |   | We can contribute back to otel.
400 Incorrect Index | X |   | This requires EP to fetch information about supported index configured for the HEC token from Splunk, which isn’t supported.
500 Internal server error | X | X |  
503 Server is busy | X |   |  
400 Data channel is missing | X |   | Data channel is used for ack.
400 Invalid data channel | X |   | Data channel is used for ack.
400 Event field is required | X |   | Receiver will just respond with ‘failed to unmarshall data’ with 400
400 Event field cannot be blank | X |   | Receiver will just respond with ‘failed to unmarshall data’ with 400
400 ACK is disabled | X |   | Ack is not supported
400 Error in handling indexed fields | X | X |  
400 Query string authorization is not enabled | X |   | Query string authorization not supported on receiver

</div></b>

**Describe the solution you'd like**
Some of the HTTP responses should be implemented:
- [ ] 400 No data
- [ ] 400 Invalid Data Format
- [ ] 400 Event field is required
- [ ] 400 Event field cannot be blank
- [ ] 400 ACK is disabled
- [ ] 400 Querey string authorization is not enabled

**Describe alternatives you've considered**
N/A

**Comment by splunkericl** [comment]
yeah there is more documentation on the [endpoint page](https://docs.splunk.com/Documentation/Splunk/9.0.4/RESTREF/RESTinput#services.2Fcollector).

But for splunk enterprise, the "No data" error is returned if the payload is rejected. This can be because the payload has invalid quotes. In the context of SplunkHECReceiver, it might be more fitting to return "Invalid Data Format" instead since this is just a decoding problem.

The http response status code would be 400 and its body would look like:
```
{"text":"Invalid data format","code":6}
```

**Comment by atoulme** [comment]
Is the code 6 attribute defined somewhere?

**Comment by splunkericl** [comment]
yeah it is defined in the response documentation on the [page](https://docs.splunk.com/Documentation/Splunk/9.0.4/RESTREF/RESTinput#services.2Fcollector) (expand under "Send events to the HTTP Event Collector.").



0 | 200 | OK | Success
-- | -- | -- | --
1 | 403 | Forbidden | Token disabled
2 | 401 | Unauthorized | Token is required
3 | 401 | Unauthorized | Invalid authorization
4 | 403 | Forbidden | Invalid token
5 | 400 | Bad Request | No data
6 | 400 | Bad Request | Invalid data format
7 | 400 | Bad Request | Incorrect index
8 | 500 | Internal Error | Internal server error
9 | 503 | Service Unavailable | Server is busy
10 | 400 | Bad Request | Data channel is missing
11 | 400 | Bad Request | Invalid data channel
12 | 400 | Bad Request | Event field is required
13 | 400 | Bad Request | Event field cannot be blank
14 | 400 | Bad Request | ACK is disabled
15 | 400 | Bad Request | Error in handling indexed fields
16 | 400 | Bad Request | Query string authorization is not enabled

**Comment by timannguyen** [comment]
@atoulme i will be working on this.

**Comment by timannguyen** [comment]
` 400 ACK is disabled` is a splunk indexer feature that the receiver can be validate the token. so it will not be implemented.

**Comment by splunkericl** [comment]
Re-commenting this thread again as one of the user runs into this problem. the HTTP client is expecting a json response like `{"text": "Success", "code": 0}` when hec receiver returns `OK`.

We can work on this so customers moving from Splunk HEC to EP HEC doesn't have to make any changes.
