### ISSUE TITLE
Lost all nodeStatsMetrics for es version < 7.9

### ISSUE THREAD

**Issue by junhuangli** [open-telemetry/opentelemetry-collector-contrib#19389]
### Component(s)

receiver/elasticsearch

## Description
1. All "[nodeStatsMetrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/elasticsearchreceiver/client.go#L89)" are retrieved in a single es request
2. If one or more of those metrics have wrong name or doesn't exist, the whole request will fail and the users end up getting no data for all nodeStatsMetrics.
## Steps to Reproduce
Use any es version < 7.9 (metric - "indexing_pressure" only exist on and after 7.9)
Setup es receiver

## Expected Result
Get other nodeStatsMetrics except indexing_pressure

## Actual Result
No nodeStatsMetrics at all.

### Collector version

v0.70.0

**Comment by djaglowski** [comment]
Thanks for capturing this issue @junhuangli. Should I assign this to you?

**Comment by junhuangli** [comment]
sure, it will be my honor to help
