### ISSUE TITLE
Container tagging for traces in the datadog exporter

### ISSUE THREAD

**Issue by nils-borrmann-y42** [open-telemetry/opentelemetry-collector-contrib#19398]
### Component(s)

exporter/datadog

### Is your feature request related to a problem? Please describe.

In my service instrumentation I am tagging my traces with the attributes `container.id` and `container.name`, in order for traces to be linked to the respective infrastructure container metrics in Datadog. The trace attributes do arrive in datadog, and are also transformed into the datadog format of `container_id` and `container_name`, but Datadog still does not connect the trace to the infrastructure container metrics.

Looking through the code, I figured out that the datadog exporter would need to set the attribute `_dd.tags.container`. This even seems to have been implemented in the past (originally implemented in #1895, removed in #9693 ?). 

I confirmed this by manually setting the `_dd.tags.container` attribute in my service instrumentation code, and alas, traces and container metrics were connected in Datadog. 

(For anyone with the same problem stumbling on this issue: What you need to do is set this attribute in your otel resource: `"_dd.tags.container": "container_id:{},container_name:{}"` where container_id is a 64-char hexadecimal string and container_name is the plain text name of the container in k8s.)

### Describe the solution you'd like

Populate the `_dd.tags.container` tag with the container attributes needed to connect traces and infrastructure metrics.

### Additional context

I also opened a ticket with Datadog (1121695) about this, their response helped to get me on the right track here.

**Comment by mx-psi** [comment]
I am going to close this as completed given we released a fix for it and we haven't gotten a reply on this thread. If the problem persists please comment so we can reopen the issue, thanks!
