### ISSUE TITLE
[CI] CodeQL-Build job is frequently failing

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#19393]
### What happened?

The build process in the job is frequently being killed. 

Examples:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4356670579/jobs/7614997238
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4361662175/jobs/7625759590
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4361171864/jobs/7624812783
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4361122311/jobs/7624712810

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by atoulme** [comment]
I don't think we can run CodeQL on a public Github action runner. They recommend 64GB of RAM: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/recommended-hardware-resources-for-running-codeql

We currently get the otelcontribcol build to use so much memory that the job gets killed by the OOM killer.

**Comment by TylerHelmuth** [comment]
I am going to start digging into this.

**Comment by TylerHelmuth** [comment]
I noticed while looking into this that even when the action does complete I don't think it is working as expected. You can see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/security/code-scanning/tools/CodeQL/status) that is is only saying it scanned 4 files and if you download the results they say extraction was not successful for many files that I believe should have been scanned.
