### ISSUE TITLE
Run into a limit on the number of modules that dependabot can handle

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#19410]
.github/dependabot.yml validation fails with 

```
The property '#/updates' had more items than the allowed 200
```

https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/11858014604

Any suggestions are welcome. 

For now, I'm going to limit the number of update rules to unblock dependabot

The error says the limit is 200, but we hit it after updating it from 220 to 221

**Comment by dmitryax** [comment]
Bringing it back to 220 didn't help — still the same error. Probably the limit was updated recently, and we run into it after updating `dependabot.yml`. I submitted a GitHub support ticket.

**Comment by codeboten** [comment]
I'll take a look at renovate next week, to see if it would be a good replacement. It may help with some of the other toil we have in the repo. It's also already in use in the opentelemetry-js repository.

**Comment by codeboten** [comment]
I think renovatebot can help us here. I've already started using it for docker/docker-compose/github action updates. I'm testing out ways we can use it for go packages as well.

**Comment by MitchellGale** [comment]
Has there been any update on this? I believe we have hit the updated limit of 220 now. Should the limit be bumped to 240?

**Comment by atoulme** [comment]
I propose that we overhaul how dependabot is used by adding a metadata entry that selects if the module should be considered for dependabot updates. For similar components, we can then just elect one to be the receiver of updates, and drop all other ones. This should allow us to stay under the 200 components. We can also set a score of dependabot for components from 1 to 5, and sort them by score and pick the first 200 components.
