### ISSUE TITLE
Elasticsearch exporter dedot and dedup config has no effect

### ISSUE THREAD

**Issue by CarsonCook** [open-telemetry/opentelemetry-collector-contrib#19419]
### Component(s)

exporter/elasticsearch

## Description
`mapping.dedup` and `mapping.dedot` configuration have no effect, they are always enabled and disabled, respectively:

```
// TODO: Apply encoding and field mapping settings.
model := &encodeModel{dedup: true, dedot: false}
```

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/elasticsearchexporter/logs_exporter.go#L65

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/elasticsearchexporter/trace_exporter.go#L61

## Steps to Reproduce
1. Set `mapping.dedot` to `true` in the receiver's config.
2. Run and see dots are preserved

## Expected Result
`mapping.dedup` and `mapping.dedot` config values are used.

Alternatively, change documentation to reflect these fields are not operational.

## Actual Result
Fields have no effect.

### Collector version

0.71.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  elasticsearch:
    mappings:
        dedot: true
```

### Additional context

PR fixing bug: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19420

**Comment by evan-bradley** [comment]
Re-closing as completed via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19420.
