### ISSUE TITLE
[pkg/stanza/fileconsumer] Compare the oldReader.offset and newReader.file.size when creating newReader

### ISSUE THREAD

**Issue by maokitty** [open-telemetry/opentelemetry-collector-contrib#19428]
### Component(s)

pkg/stanza

### Is your feature request related to a problem? Please describe.

If newReader.file and oldReader.file have the same fingerprint,the data in newReader.file between 0 and oldReader.file.size will be lost

### Solution
if newReader.file.size is less than oldReader.offset , then newReader.file and oldReader.file must be different

### Why this solution works
When a file is found in the current poll cycle, [newReader](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/fileconsumer/file.go#L282) is called  , let's call it newReader.file for short, [oldReader.file](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/fileconsumer/roller_other.go) is the poll cycle file just before newReader file ,and otel will store the read offset of this file , let's call it oldReader.offset

There is no other logic for otel to update oldReader.offset before newReader , so for the same file ,the file size will always be greater than or equal to the oldReader.offset

But the situation is different for rotation 

1. if the rotation strategy is copy/truncate ,then before truncate ,  copy file will be greater than or equal to oldReader.offset,and  after truncate , newFile.size will be less than oldReader.offset, and otel should make a new reader for the rotation file
2. if someone copies a file and otel finds it ,the copy file size will be equal to  oldReader.offset

### Bad case
If newReader.file grows fast ,and it's size is larger than oldReader.offset , it works as current logic, and that's why i think this method is an enhancement , not a bugfix

### Describe alternatives you've considered

There is a function [os.sameFile](https://pkg.go.dev/os#SameFile) which compares file.devicenumber and file.inode in Unix style system , and it has logic for Windows too

Actually there is a talk about fingerprint : [16266](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16266), and the [design of fingerprint](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/fileconsumer/design.md#deduplication-of-files) says that otel should think about replicated/copied situation, and this is what os.sameFile cannot handle

But 

- People  don't usually copy their log manually  , even if they did it ,they would "remember" their operation
- And for the copy/truncated rotation strategy , otel users can exclude the rotation file via config

So if we can accept that  otel users should  take responsibility for their config, os.sameFile will be  a good strategy for identifying the file

### Additional context

i am suggest compare size first because it will handle most case ,and os.sameFile is a break change for filelog receiver , it drop the fingerprint strategy

**Comment by djaglowski** [comment]
> If newReader.file and oldReader.file have the same fingerprint,the data in newReader.file between 0 and oldReader.file.size will be lost

Isn't it more accurate to say that the data was already consumed?

I'm not convinced there is a problem here. If the files have the same fingerprint, then we _should_ consider them as the same file and ignore the data that was already consumed. This is exactly why we use fingerprints, so we can deduplicate copies of the same file when this is observed during rotation.

**Comment by djaglowski** [comment]
> There is a function [os.sameFile](https://pkg.go.dev/os#SameFile) which compares file.devicenumber and file.inode in Unix style system , and it has logic for Windows too
> 
> Actually there is a talk about fingerprint : [16266](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16266), and the [design of fingerprint](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/fileconsumer/design.md#deduplication-of-files) says that otel should think about replicated/copied situation, and this is what os.sameFile cannot handle

Correct, the fingerprinting strategy is designed to handle situations that the operating system does not track.

> * People  don't usually copy their log manually  , even if they did it ,they would "remember" their operation
> * And for the copy/truncated rotation strategy , otel users can exclude the rotation file via config
> 
> So if we can accept that otel users should take responsibility for their config, os.sameFile will be a good strategy for identifying the file

I think you are incorrect to assert that this is a matter of users needing to take responsibility for their config. What you are suggesting would 1) make configuration more challenging for users, and 2) introduce loss of data.

> for the copy/truncated rotation strategy , otel users can exclude the rotation file via config

This is exactly a case where the user should _not_ exclude rotated files from the config. A rotated file will often contain some additional data that was not read before the rotation took place. Example:
1. Poll cycle reads file to end.
2. More lines are written to the file.
3. File is copied and truncated.
4. Next poll cycle excludes copy of file that contains the latest lines.

**Comment by maokitty** [comment]
> Isn't it more accurate to say that the data was already consumed?

For example , if fingerprint config   is 6 and there is a file a.log, the contents are 
```
aaaaaa
bbbb
ccc
```
after reader has read the whole content , reader.offset will be 15, then a rotation  has happened ,new logs are inserted in a.log , the new content is 
```
aaaaaa
1111
222
33
```
Since the original file and the rotation file have the same fingerprint , the current logic is to reuse the old offset which is 15, and the data of the rotation file is lost.

In most cases the file and its rotation file fingerprint are different, but there is still comes the probability, and we can increase the size of the fingerprint , let's say up it to 10 for our example ,  problem solved . 

But it's more complicated in real user case , it's hard to set a proper fingerprint size , and when bad case happens , it's hard to find out because there are so many file to collect for a company

Comparing the newReader.file.size and oldReader.offset will be helpful for otel to handle this case , as the  file usually does not grow fast during the poll interval period.

**Comment by maokitty** [comment]
> 1) make configuration more challenging for users

Well , i think there is some room for us to talk about configuration challenging. 
For example ,  If people want to collect data in the   /var/log directory , they can configure  it in the include option : 
```
include:
- /var/log/*
```
Under /var/log, there is a file  a.log , and a.log is rotated based on size or time , the filename after rotation will usually add number or time after the original name , for example a.log.2023-03-10,  and it should not be collect ,so the configuration of include can be changed to 

```
include:
- /var/log/*.log
```

and I believe there is no configuration challenge for users to make such  a change .

I have to admit that there is some challenge , which is that otel users should know how to include exactly the file they want to collect , this is one of the responsibilities i am thinking about: they should know which file they want to collect

The other responsibility is that if the user's configuration include file is * ,  the data will be collected as confgured

**Comment by maokitty** [comment]
> 2) introduce loss of data.

If filename is  exclude the pattern after rotation ,  we have a detectLostFile logic , which i think can collect the whole file content

Or am I missing something ?

**Comment by djaglowski** [comment]
> If filename is exclude the pattern after rotation , we have a detectLostFile logic , which i think can collect the whole file content
> 
> Or am I missing something ?

The logic for detecting lost files does not work for copy/truncate scenarios. It relies on having an open file handle from the previous poll cycle. In the copy/truncate case, the "lost" file is a new copy of the old file, so we don't have a handle to it.

**Comment by djaglowski** [comment]
> > Isn't it more accurate to say that the data was already consumed?
> 
> For example , if fingerprint config is 6 and there is a file a.log, the contents are
> 
> ```
> aaaaaa
> bbbb
> ccc
> ```
> 
> after reader has read the whole content , reader.offset will be 15, then a rotation has happened ,new logs are inserted in a.log , the new content is
> 
> ```
> aaaaaa
> 1111
> 222
> 33
> ```
> 
> Since the original file and the rotation file have the same fingerprint , the current logic is to reuse the old offset which is 15, and the data of the rotation file is lost.
> 
> In most cases the file and its rotation file fingerprint are different, but there is still comes the probability, and we can increase the size of the fingerprint , let's say up it to 10 for our example , problem solved .
> 
> But it's more complicated in real user case , it's hard to set a proper fingerprint size , and when bad case happens , it's hard to find out because there are so many file to collect for a company
> 
> Comparing the newReader.file.size and oldReader.offset will be helpful for otel to handle this case , as the file usually does not grow fast during the poll interval period.

I see what you are saying here. The fingerprint length is the key factor here to determine if the files are different, but it is difficult for the user to identify when it is not long enough.

In the case where `newReader.file.size < oldReader.offset`, I believe we would hit [this error condition](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/reader.go#L72-L75). Do you agree? If so, perhaps we can use this to log a more specific error that advises about fingerprint size.

In theory we could also use this to recognize that it is a new file and immediately consume it from the first byte. However, it will still have the same fingerprint as the other file, so we may have erratic behavior from there.

**Comment by maokitty** [comment]
By the way , I am not sure why the datastructure of [knownFiles](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/file.go#L48) is an array, it seems set or map will be more effective .The current logic will make the fingerprint 4 times bigger in both memory and file storage (if we use it in filelogreceiver), and this is an important reason for not making the fingerprint too big for now. 

And maybe we could open another issue to take about it

**Comment by djaglowski** [comment]
> By the way , I am not sure why the datastructure of [knownFiles](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/file.go#L48) is an array, it seems set or map will be more effective .The current logic will make the fingerprint 4 times bigger in both memory and file storage (if we use it in filelogreceiver), and this is an important reason for not making the fingerprint too big for now.
> 
> And maybe we could open another issue to take about it

What key would you use if `knownFiles` was a map? We can't use fingerprint because fingerprints are designed to grow. 

It would be possible to segregate files with full-size fingerprints from those that are still growing. Then we can have an array only for those that are still growing. This is more complicated code but in theory could be more performant.

**Comment by maokitty** [comment]
> It relies on having an open file handle from the previous poll cycle. In the copy/truncate case, the "lost" file is a new copy of the old file, so we don't have a handle to it.

I found a man page for [logrotate copytruncate ](https://man.archlinux.org/man/core/logrotate/logrotate.8.en#copytruncate), it says "thus might continue writing (appending) to the previous log file forever."  it seems that the new copy file is no longer appending data anymore , and we are still reading the old file . 

The lost data is happend in the old file that apend after copy , because of truncate operation? not otel . and the lost data will not be there in new copy file too ,  I am not sure in this part ,please correct me if i am wrong

**Comment by maokitty** [comment]
> It would be possible to segregate files with full-size fingerprints from those that are still growing. Then we can have an array only for those that are still growing

it seems a good idea

**Comment by djaglowski** [comment]
> > I believe we would hit [this error condition](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/reader.go#L72-L75). Do you agree?
> 
> It seems that even if the offset is greater than the file size , file.seek do not return an error. I have done some experiments with go versions 1.18.4 and 1.20.1
> 
> I am suggest we can add some logic in [newReader](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/file.go#L284) and [findFingerprintMatch](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/file.go#L292) like this
> 
> ```
> func (m *Manager) newReader(file *os.File, fp *Fingerprint) (*Reader, error) {
> 	// Check if the new path has the same fingerprint as an old path
> 	info, e := file.Stat()
> 	if e!=nil {
> 		return nil, e
> 	}
> 	if oldReader, ok := m.findFingerprintMatch(fp,info.Size()); ok {
> 		return m.readerFactory.copy(oldReader, file)
> 	}
> 
> 	// If we don't match any previously known files, create a new reader from scratch
> 	return m.readerFactory.newReader(file, fp)
> }
> 
> func (m *Manager) findFingerprintMatch(fp *Fingerprint, fileSize int64) (*Reader, bool) {
> 	// Iterate backwards to match newest first
> 	for i := len(m.knownFiles) - 1; i >= 0; i-- {
> 		oldReader := m.knownFiles[i]
> 		if oldReader.Offset < fileSize && fp.StartsWith(oldReader.Fingerprint) {
> 			return oldReader, true
> 		}
> 	}
> 	return nil, false
> }
> ```
> 
> Then a new reader will be created. and because each reader read file desparetly , it will be work fine when reading file . As for the other logic , there is already the same fingerprint in konwnFiles ,because of the logic in [saveCurrent](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/file.go#L268), so i think the code still works well

I think we would still have problems because the fingerprints are the same. Yes, we would create separate readers , but if the fingerprints continue to match, then we cannot correctly track an offset for future cycles and will end up double-ingesting data from one file when we incorrectly use the offset from the other.

**Comment by djaglowski** [comment]
> > It relies on having an open file handle from the previous poll cycle. In the copy/truncate case, the "lost" file is a new copy of the old file, so we don't have a handle to it.
> 
> I found a man page for [logrotate copytruncate ](https://man.archlinux.org/man/core/logrotate/logrotate.8.en#copytruncate), it says "thus might continue writing (appending) to the previous log file forever." it seems that the new copy file is no longer appending data anymore , and we are still reading the old file .
> 
> The lost data is happend in the old file that apend after copy , because of truncate operation? not otel . and the lost data will not be there in new copy file too , I am not sure in this part ,please correct me if i am wrong

These are two separate cases.
1. Move/create rotates the original file into a place where the receiver can no longer discover it based on its path/name. However, we still have an open handle to the moved file. We can detect that this has happened and ingest the remainder of the file. This is what the "lost files" logic is doing.
2. As you found in the man page, copy/truncate can lost a small amount of data during rotation and there is nothing we can do about that case.

Neither of these cases is same as we would see if copy/truncate is used in combination with excluding rotated files from `include`.

**Comment by maokitty** [comment]
No two new readers will have the same fingerprint in one poll cycle, which is guaranteed by the current logic

The current logic is

1. start a new poll, get all include files,and exclude those configured to be excluded
2. open the batch of files , and read their fingerprint
3. compare the file fingerprint of newly opened file, delete the duplicate , then all  files  left now will all have different fingerprints
4. start to make reader for the left file, first compare with knownFiles, which contains the file fingerprint and read offset that come from file_storage or last poll cycle. according to [knownFiles append rule](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/file.go#L268) , the latest poll cycle will have the largest index , so fingerprint compare logic [read knownFiles from largest index to 0](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/file.go#L294)  , and for the fingerprint that are same in the last poll cycle and the current poll cycle will hit the latest offset that exactly connects to the  last read position.   
- The logic I am suggesting is just to make new reader other than copy offset from old reader ,all logic in step 4 will not append a new reader that not included in step 3
- There are two readers with the same fingerprint , one is in the new reader array , the other is in the old reader array created in the last poll cycle, and there are at least 4 readers with the same fingerprint in the knownFiles
5. after the function makeReader execute over. otel will filter the file that exists in the last poll cycle but is not found in the current poll cycle , by comparing its fingerprint
- Here comes a bug : since [readfactory](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/reader_factory.go#L46) copy offset from oldreader , but use new file ,and [readLostFile](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/roller_other.go#L33) will not add the oldreader to lostReader , since they have same fingerprint, if the old file is not read to end ,and rotation happen , it will be lost forever.
6. read each file in new reader array
7. delete  the fully read file if  configured
8. save current reader as last latest reader
9. delete readers whose generation is greater than 3
10. store current readers in filestorage , in the same  order as in memory
11. back to step 1 after poll interval

**Comment by maokitty** [comment]
> What key would you use if `knownFiles` was a map?

Is there any reason to keep three generations of oldReaders in konwnFiles? i just realise thedetectLostFiles.oldReaders will be enough, we can save it to filestorage and recover it from filestorage to it too

**Comment by maokitty** [comment]
> These are two separate cases.

I agree with you in these two cases. and what do you think of the os.sameFile strategy

**Comment by maokitty** [comment]
By the way , if the fingerprint grows to config size , and  the file  size is not too big than the config fingerprint value , a log of same the fingerprint found in [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/file.go#L239) will be great , because only one will be collected ,and others  will be completely ignored

**Comment by djaglowski** [comment]
> what do you think of the os.sameFile strategy?

I addressed this above, but will state again more clearly.

The fingerprinting strategy is designed to handle situations that the operating system does not track. `os.sameFile` is not a reliable indicator that two log files are the "same" because it is not able to track a file that is rotated via the copy/truncate strategy.

**Comment by maokitty** [comment]
> 2\. As you found in the man page, copy/truncate can lost a small amount of data during rotation and there is nothing we can do about that case.

I think I misunderstood your words  that since we have nothing to do with copy/truncate , then os.sameFile might be a good strategy , so i asked the question to make sure that we are consistent in this

What about the others :

1.  Compare the oldReader.offset and the newReader.file.size , since there is no same fingerprint in a poll ,and it can  reduce the probability of the same fingerprint causing lost data between rotation and its original file
2.  The bug:  [readfactory](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/reader_factory.go#L46) copy offset from oldreader , but use new file ,and [readLostFile](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/roller_other.go#L33) will not add the oldreader to lostReader , since they have same fingerprint, if the old file is not read to end ,and rotation happen , it will be lost forever. 
3. Use  thedetectLostFiles.oldReaders and drop konwFiles
4. A log of that indicate the same fingerprint founded in [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b0f6db7858f3897f4cc1fb7580e33d67703ae084/pkg/stanza/fileconsumer/file.go#L239)

If we can agree  on about these four things , you can assign them to me ,and I will submit PR for each of them

**Comment by djaglowski** [comment]
@maokitty, I'm afraid we agree on much here. Frankly, I think my points have been lost in all the tangents.

Here's what I suggest: Please open a new issue for each specific change you'd like to propose, and let's stick to the immediate topic as much as possible.

---

As far as the original proposal of this issue, I am focused on two points:
1. The receiver is acting as intended, so I do not consider there to be a bug. The current design works as long as the fingerprint size is sufficiently large. The fingerprint size can be configured when necessary.
2.  Using a volatile piece of information to partially identify a file is an unreliable strategy. I do not understand what change you are proposing that would guarantee that we are _repeatably_ able to differentiate between two files that have the same fingerprint. Perhaps for this you will have to make a PR to show me.

**Comment by maokitty** [comment]
I will open a new issue for each of them , Thanks for your advice
