### ISSUE TITLE
`num_consumers > 1` and writing points in order

### ISSUE THREAD

**Issue by kwapik** [open-telemetry/opentelemetry-collector-contrib#19442]
### Component(s)

exporter/googlemanagedprometheus

### Is your feature request related to a problem? Please describe.

In my setup I have noticed quite a lot of data points being rejected with error like
```
One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older end time than the most recent point.
```

I have followed some advice to fill all the needed labels to ensure each instance is writing metrics with unique set of labels. This reduced number of data points being rejected, but some still were being dropped.

After investigating this more, I have noticed that I am using default configuration for the exporter queue, which includes `num_conumers: 10`.

Figured out that this may be a race, like the following. Imagine queue like the following (assume that all data points are for the same metric):
1. data point A with time=0
2. data point B with time=1
3. data point C with time=2

Now the order of events:
1. Consumer 1 takes data point A from the queue
2. Consumer 2 takes data point B from the queue
3. Consumer 2 writes data point B to GCP successfully
4. Consumer 1 writes data point A to GCP, but it is rejected, as the data point is older that data point A

### Describe the solution you'd like

1. I'd like to have confirmation that my understanding of the issue is correct
2. If it is correct, this should be mentioned in the docs of this exporter
3. Maybe a label like `consumer_uuid: <uuid>` should be added to make sure the issue does not happen

### Additional context

Setting `num_consumers` to `1` is not an ideal solution as now the exporter queue can grow quite fast.

**Comment by damemi** [comment]
The race you're describing sounds like it could be the issue, but I think this is more of a question for the exporter helper component than the GMP.

Adding a label like `consumer_uuid` could help confirm the race, but I don't know if that's a good long term solution. I imagine over time (with collector restarts) that cardinality could get pretty high. Adding this label might also be a change for the exporter helper rather than GMP too

**Comment by kwapik** [comment]
@damemi Order of writing is not always important. In case of GMP it is, so it seemed logical to put it here. Will open a ticket in main collector repo, just to get confirmation this is working as intended. Thanks!

**Comment by damemi** [comment]
@kwapik yeah, what I mean is that I don't know if our exporter has any ability to differentiate between which consumer it receives each data point from. So even though the ordering isn't important for other exporters, if you want to make a change like adding a `consumer_uuid` label, it probably needs to happen in that helper.

**Comment by AkselAllas** [comment]
I have the same error but without `num_consumers > 1`

**Comment by ismailyenigul** [comment]
Hi @AkselAllas 
Where you able to find a solution for 
`Points must be written in order. One or more of the points specified had an older start time than the most recent point` on Google Cloud Run?

**Comment by AkselAllas** [comment]
I have 2 hypothesis:

1. We need to use proper resource detector: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31374
2. Any change of timeseries definition (e.g. new label) requires a new timeseries name
