### ISSUE TITLE
[exporters/dynatraceexporter] add exporter to cmd

### ISSUE THREAD

**Issue by PatrikSteuer** [open-telemetry/opentelemetry-collector-contrib#1945]
**Is your feature request related to a problem? Please describe.**
Consuming the `dynatraceexporter` requires a dedicated build. This reduces the comfort in consuming the exporter. It should be possible to use the dynatrace exporter using the default docker image otel/opentelemetry-collector-contrib.

**Describe the solution you'd like**
Adding the `dynatraceexporter` component to the otelcontribcol cmd.

**Describe alternatives you've considered**
NAN, since I am unaware of the current state of development and maybe this missing functionality is by intent.

**Comment by dyladan** [comment]
This was fixed by #2002 and can be closed

**Comment by PatrikSteuer** [comment]
Thanks a lot
