### ISSUE TITLE
Feature request for https://github.com/signalfx/splunk-otel-collector-chart/issues/666

### ISSUE THREAD

**Issue by VihasMakwana** [open-telemetry/opentelemetry-collector-contrib#19465]
### Component(s)

pkg/stanza, receiver/filelog

### Is your feature request related to a problem? Please describe.

By using helm chart's `useSplunkIncludeAnnotation: true` feature, it only forwards the logs from the pods annotated with `splunk.com/include: true` annotation.

Although the filtering works, they discovered that logs from non-annotated pods are still being processed in the log processing pipeline, where they are internally decorated and filtered, which can result in high CPU usage for no benefit (as those logs are just being discarded). This really starts to become a problem (high CPU usage and throttling) with the pods that are producing large amount of logs, like tens of thousands of log records per second.

As mentioned in [#666](https://github.com/signalfx/splunk-otel-collector-chart/issues/666):

> Thanks for your suggestion. However, maintaining an include list would not be a sustainable solution for our use case. We are trying to collect Docker logs from the Kubernetes nodes, and since the file paths for these logs look like /var/log/pods/<namespace_name>_<pod_name>_<pod_uid>/<container_name>/<restart_count>.log, we would have to update the list every time a namespace or a pod is added, which happens frequently. This would require us to make very frequent deployments of splunk-otel-collector, which is not practical for us.
> 
> Regarding the CPU usage issue, we have observed that just one pod writing 20,000 log records per second consumes about 0.5 CPU in splunk otel collector agent pod, and causes CPU throttling. As splunk-otel-collector runs as a daemonset, if we were to trade off some efficiency for convenience to still allow for filtering this pod's logs by splunk.com/include annotation, we would have to allocate 0.5 CPU more to the daemonset. In a Kubernetes cluster with 30 nodes, this means we would be wasting 15 CPUs just to prevent throttling caused by that one pod. That's why relying solely on the splunk.com/include annotation filtering with the current implementation becomes very expensive at scale.

### Describe the solution you'd like

As manually keeping track of excluding pods and updating`logsCollection.containers.excludePaths` is labor-intensive and require frequent deployments, an approach I can think of is to create a kubeclient with `opentelemetry-collector-contrib/processor/k8sattributesprocessor/internal/kube` in operator and find the annotations of the pods and add unnecessary pods to `Exclude` setting dynamically.

### Describe alternatives you've considered

Haven't thought of any, open to any alternative ideas!

**Comment by vihas-splunk** [comment]
@djaglowski please take a look at this at your convenience

**Comment by djaglowski** [comment]
@vihas-splunk, I think there must be better ways to handle this, rather than adding a k8s client to a file reading package.

The `fileconsumer` package is intended to be used as a dependency in multiple components. I recommend that you propose a new component that manages both the k8s client and the `fileconsumer`.

**Comment by vihas-splunk** [comment]
@djaglowski what about adding this k8s client to filelogreceiver in some way? I'll work on that and update you!

**Comment by djaglowski** [comment]
> @djaglowski what about adding this k8s client to filelogreceiver in some way? I'll work on that and update you!

I would prefer not to complicate the filelog receiver for such a special case.
