### ISSUE TITLE
Elastic exporter not picking up DB queries

### ISSUE THREAD

**Issue by bhupesh-sf** [open-telemetry/opentelemetry-collector-contrib#1961]
I am using elastic exporter and when I go to elastic it shows me trace and shows only one pg query whereas it has 4-5 queries. If I use elastic agent it shows me all.

**Steps to reproduce**
My flow is I call a facade from postman which calls a service which makes DB request 3-4 times and then calls another service which again calls db and then fails.

**What did you expect to see?**
I should be seeing everything logged in trace as its been with elastic agent.

**What did you see instead?**
DB queries are completely missing also no 40 not found badge which comes when I use elastic agent

**What version did you use?**
Version: v0.17.0

**What config did you use?**
Config: 

`

receivers:
   
	otlp:
      protocols:
        http:
          endpoint: 127.0.0.1:55681
          cors_allowed_origins:
          - http://*
          - https://*

	  processors:
	      batch: null
	      queued_retry: null
	      resourcedetection/system:
	        detectors: [env, system]
	        timeout: 2s
	        override: false
	  
	  exporters:
	      elastic:
	        apm_server_url: 'http://localhost:8200'
	  
	  service:
	      pipelines:
	        traces:
	          receivers: [otlp]
	          processors: [batch, resourcedetection/system]
	          exporters: [elastic]

**Environment**
OS: Ubuntu 20.04

**Comment by bhupesh-sf** [comment]
Any update here?

**Comment by andrewhsu** [comment]
from the collector sig triage today, cc @axw @simitt @jalvz for this issue because it is related to elasticexporter

**Comment by axw** [comment]
Thanks for the ping @andrewhsu!

@bhupesh-sf can you please add a logging exporter to the traces pipeline, capture the output, and point out which spans are not being captured in Elastic APM? Providing a screenshot of a trace waterfall in Elastic APM may also be helpful.

**Comment by cyrille-leclerc** [comment]
Hello @bhupesh-sf , friendly ping, can you provide more details as @axw asked?
