### ISSUE TITLE
New component: websocket processor

### ISSUE THREAD

**Issue by pmcollins** [open-telemetry/opentelemetry-collector-contrib#19633]
### The purpose and use-cases of the new component

The [Websocket Processor](https://github.com/pmcollins/opentelemetry-collector-contrib/tree/websocketviewer/processor/websocketprocessor) provides a way to repeat telemetry data through a websocket in real-time while also sending the data to the next component in the pipeline. Its primary purpose is to enable real-time debugging and analysis of telemetry data. Users can configure one or more Websocket Processors in front of and/or behind their other processors to see and analyze data flowing through the pipeline in real time. Rate-limiting is built in to prevent overwhelming any websocket listeners.

The Websocket Processor can be used with any websocket client, including command line tools such as [websocat](https://github.com/vi/websocat), and it will work in combination with the [Websocket Viewer Extension](https://github.com/pmcollins/opentelemetry-collector-contrib/tree/websocketviewer/extension/websocketviewerextension), which will present, on a web page, data from all Websocket processors running in a Collector.

### Example configuration for the component

```
websocket:
    port: 12001
    limit: 1 # rate limit 1 msg/sec
```

### Telemetry data types supported

Metrics, traces, and logs. Will start with metrics.

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

@atoulme

**Comment by atoulme** [comment]
I will sponsor this component!

**Comment by seankhliao** [comment]
This looks quite interesting, I've wanted something like [vector.dev's tap](https://vector.dev/guides/level-up/vector-tap-guide/) functionality

**Comment by MovieStoreGuy** [comment]
Could I ask to give it a more descriptive name than websocket processor?

It wasn't clear to me from the name what the purpose was and I assumed it should have been a receiver until I had read the issue. 

What do you think of any of the following:

- RemoteObserverProcessor
- DebugStreamingProcessor
- ListenerProcessor

**Comment by MovieStoreGuy** [comment]
Hey @atoulme , 

I saw the PR https://github.com/open-telemetry/opentelemetry-collector-releases/pull/365 but the naming of the component does not align with the intent. 

Are you able to update this?

**Comment by atoulme** [comment]
Oh true, we talked about renaming it. OK I'll get on that.

**Comment by atoulme** [comment]
#23856 is filed for this.

**Comment by ringerc** [comment]
This component is rather confusing given that there's both a Websocket Processor / Remote Tap Processor ( `remotetapprocessor` https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/remotetapprocessor  ) and a  Remote Observer extension https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/remotetapextension 

See also https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27873

**Comment by atoulme** [comment]
It's the same component. It was renamed.

**Comment by ringerc** [comment]
@atoulme The docs for `processor/remotetapprocessor` and `extension/remotetapextension` make no reference to each other. Are they both parts of the same "remote tap" feature? It's unclear if/how they interact.

**Comment by atoulme** [comment]
You can see the impl of the extension in this PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29726

It didn't make it because of lack of interest and bandwidth from other reviewers. It should give you an idea of what is possible.

**Comment by ringerc** [comment]
@atoulme So `extension/remotetapextension` in `main` is incomplete and abandoned due to lack of reviewer interest in merging the changes required to finish it?

It's not clear to me if either `processor/remotetapprocessor` or `extension/remotetapextension` is supposed to work at present, or whether `processor/remotetapprocessor` can be used standalone without the extension. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31096#issuecomment-1931187643 .

If it's not supposed to work, I'll update my docs PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31096 to say so.

**Comment by ringerc** [comment]
@atoulme Are you able to confirm whether `processor/remotetapprocessor` is suppoesd to work without `extension/remotetapextension`, by making a direct websocket connection to the listening port? Or can they only be used together?

I'm trying to update the docs, but want to know if it's supposed to be usable at all in the current state or not.

**Comment by atoulme** [comment]
Yes, it works without the extension.
