### ISSUE TITLE
Export data to F5 Cloud

### ISSUE THREAD

**Issue by gramidt** [open-telemetry/opentelemetry-collector-contrib#1964]
**Is your feature request related to a problem? Please describe.**
I would like the possibility to send metric, trace, and log data to [F5 Cloud](https://portal.cloudservices.f5.com/)

**Describe the solution you'd like**
Have an exporter that sends metric, trace, and log data to F5 Cloud.

**Additional context**
A PR will soon be provided that accomplishes this request.

**Comment by gramidt** [comment]
Initial exporter is now complete. Future enhancement will follow the standard contributions flow [Issue -> PR -> Review](https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#report-a-bug-or-requesting-feature). 

@andrewhsu - Should we add an `enhancement`  label for this issue?

**Comment by andrewhsu** [comment]
closing this because resolved with PRs
