### ISSUE TITLE
[pkg/ottl] IsMatch works on maps and slices in contradiction to documentation

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-collector-contrib#19652]
### Component(s)

pkg/ottl

## Description

According to [documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/ottlfuncs/README.md#ismatch) `IsMatch` should return false for non-atomic types:

> The function matches the target against the pattern, returning true if the match is successful and false otherwise. If target is a boolean, int, or float it will be converted to a string. If target is nil or not a string, boolean, int, or float false is always returned.

In reality, it serializes maps and slices to a string using JSON: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/ottlfuncs/func_is_match.go#L56

Both the documentation and the code were added in the same PR (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16503) so I'm not sure what is actually intended, but the documented behavior makes more sense to me. 

### Collector version

v0.73.0

### Additional context

What I'm actually trying to do is detect if a value is a map, so if there's a simpler way of doing that, I'd appreciate some guidance.

**Comment by TylerHelmuth** [comment]
@swiatekm-sumo thanks for finding this discrepancy.  With the new concept of typed-getters I think this lets itself to using a `StringLikeGetter` in the future, so I would opt for the code being accurate and the documentation being inaccurate.

**Comment by swiatekm-sumo** [comment]
Allright, let's just update the documentation then.
