### ISSUE TITLE
New component: filestatsreceiver

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#19729]
### The purpose and use-cases of the new component

This receiver communicates metrics related to file information.

The component exposes the following metrics:
* `file.size`: size of the file or folder in bytes.
* `file.mtime`: last modification timestamp of the file, in seconds since Epoch.
* `file.ctime`:  last modification or permission change timestamp of the file, in seconds since Epoch.
* `file.atime`:  last access timestamp of the file, in seconds since Epoch.

Each metric will come with the following attributes:
```
* `file.path`: the absolute path to the file or folder
```

 This receiver acts like a scraper, with a default collection interval of 30s. The receiver accepts the following configuration:

| Field                           | Default  | Description                                                                                                        |
| ---                             | ---      | ---                                                                                                                |
| `include`                       | required | A list of file glob patterns that match the file or folder paths to be scraped                                                  |
| `exclude`                       | []       | A list of file or folder glob patterns to exclude from scraping

In case of error with a specific file during scraping, the receiver will log a partial scraping error and continue to try on other files.

### Example configuration for the component

```
filestats:
  include: ["/etc/apache/sites-enabled/*"]
  exclude: ["/etc/apache/sites-enabled/README"]
  metrics:
    file.size:
      enabled: false
    file.atime:
      enabled: true
```

### Telemetry data types supported

metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

**Comment by dmitryax** [comment]
I'll sponsor this component
