### ISSUE TITLE
[receiver/awsecscontainermetricsreceiver] Add `ServiceName ` metadata to be retrieved from task metadata endpoint

### ISSUE THREAD

**Issue by erichsueh3** [open-telemetry/opentelemetry-collector-contrib#19728]
### Component(s)

receiver/awsecscontainermetrics

### Is your feature request related to a problem? Please describe.

Currently, the `awsecscontainermetricsreceiver` returns "undefined" for `ServiceName`, see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/awsecscontainermetricsreceiver/internal/awsecscontainermetrics/resource.go#L66). This is likely because this was implemented before `ServiceName` was available from the task metadata endpoint, however for Amazon ECS container agent versions 1.63.1 or later, it is available. [1.63.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.63.1) has been available for over 6 months now, and `ServiceName` should be added to the `awsecscontainermetricsreceiver`.

### Describe the solution you'd like

Update the code for the `awsecscontainermetricsreceiver` to include `ServiceName` when receiving ECS container metrics.

**Comment by codeboten** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19744
