### ISSUE TITLE
[processor/spanmetrics] Deprecate component 

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#19736]
### Component(s)

connector/spanmetrics, processor/spanmetrics

### Describe the issue you're reporting

This is a tracking issue relating to https://github.com/open-telemetry/opentelemetry-collector/issues/7370

The processor has been reimplemented as a connector. (See #18760) 

We should deprecate the processor when the code owners believe the time is appropriate.

**Comment by kovrus** [comment]
The processor was deprecated by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19751
