### ISSUE TITLE
[processor/servicegraph] Deprecate component

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#19737]
### Component(s)

connector/servicegraph, processor/servicegraph

### Describe the issue you're reporting

This is a tracking issue relating to https://github.com/open-telemetry/opentelemetry-collector/issues/7370

The processor has been reimplemented as a connector. (See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18389) 

We should deprecate the processor when the code owners believe the time is appropriate.

**Comment by djaglowski** [comment]
@jpkrohling, it seems to me that it would be appropriate to deprecate it at this point. I believe we were just waiting for a code owner to give the go ahead. :)

**Comment by jpkrohling** [comment]
Alright, I'm on it.
