### ISSUE TITLE
Update timestamp to include milliseconds

### ISSUE THREAD

**Issue by wzchua** [open-telemetry/opentelemetry-collector-contrib#19746]
### Component(s)

exporter/datadog

### Is your feature request related to a problem? Please describe.

logs shipped via datadog exporter are missing milliseconds

### Describe the solution you'd like

Update https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/897db04f747f0bda1707c916b1ec9f6c79a0c678/exporter/datadogexporter/internal/logs/translator.go#L152
to generate unix milliseconds or iso with milliseconds included

### Describe alternatives you've considered

I tried adding `timestamp` attribute but `@timestamp` is preferred by datadog. And the exporter overwrites `@timestamp` attribute

**Comment by canadianveggie** [comment]
Note: It looks like the code in question has refactored into a different repository: https://github.com/DataDog/opentelemetry-mapping-go/blob/0a32610fd1a87d46b4b499bc3e70ef1f23b169e4/pkg/otlp/logs/logs_translator.go#L159

**Comment by canadianveggie** [comment]
New issue logged here: https://github.com/DataDog/opentelemetry-mapping-go/issues/152
