### ISSUE TITLE
receiver: add missing metadata.yaml files to components

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/opentelemetry-collector-contrib#19759]
According to the [current documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/mdatagen#metadata-generator) and the [first two lines](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/mdatagen/metric-metadata.yaml#L1-L2) in the `metadata.yaml` file documentation, each component should include at least a metadata.yaml file with its name (consider it is not creating any signals).

As we are today, there are a bunch of components which are lacking the metadata.yaml file, some of them even emitting metrics. What I'm proposing is:

* We should create metadata.yaml files for _all_ receivers with at least the `name` field filled in, regardless on whether they emit metrics or not
* We should validate this as best we can via tests (CI)

The following receiver components are currently lacking the file:

* receivercreator
* windowsperfcountersreceiver
* googlecloudspannerreceiver
* purefbreceiver
* wavefrontreceiver
* sqlqueryreceiver
* purefareceiver
* otlpjsonfilereceiver
* jmxreceiver
* opencensusreceiver
* fluentforwardreceiver
* k8sclusterreceiver
* syslogreceiver
* solacereceiver
* podmanreceiver
* snmpreceiver
* awsecscontainermetricsreceiver
* udplogreceiver
* filereceiver
* awsfirehosereceiver
* prometheusreceiver
* sapmreceiver
* skywalkingreceiver
* tcplogreceiver
* dotnetdiagnosticsreceiver
* hostmetricsreceiver
* pulsarreceiver
* signalfxreceiver
* carbonreceiver
* filelogreceiver
* googlecloudpubsubreceiver
* simpleprometheusreceiver
* zipkinreceiver
* awscontainerinsightreceiver
* awsxrayreceiver
* azureblobreceiver
* cloudfoundryreceiver
* k8seventsreceiver
* awscloudwatchreceiver
* datadogreceiver
* influxdbreceiver
* webhookeventreceiver
* prometheusexecreceiver
* azureeventhubreceiver
* collectdreceiver
* statsdreceiver
* windowseventlogreceiver
* splunkhecreceiver
* cloudflarereceiver
* jaegerreceiver
* journaldreceiver
* k8sobjectsreceiver
* kafkareceiver

Unless there are any objections, I'd like to create individual tickets for each of these, so that the owners can add the missing metadata.yaml files.

I am happy to add the tests to CI myself, once completed.

**Comment by atoulme** [comment]
I am not sure of the value of adding the file for otlpjsonfilereceiver or splunkhecreceiver for example. These components just ingest metrics over disk or http. Others make a lot of sense to me.


What CI validation would you like to see?

**Comment by gbbr** [comment]
@atoulme is there any way I can help with this? I could work on introducing a test in CI which validates that this file exists in all receiver folders (if there are any exceptions needed, we can configure them)

**Comment by atoulme** [comment]
It’s a big early but sure. You can help by migrating more components and prep CI

**Comment by atoulme** [comment]
It looks like I forgot about this conversation and filed a different bug for all components: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21213

**Comment by gbbr** [comment]
Then we should close this right?
