### ISSUE TITLE
service graph processor does not generate metrics

### ISSUE THREAD

**Issue by joyeahzhang** [open-telemetry/opentelemetry-collector-contrib#19758]
### Describe the issue you're reporting

I used the service graph processor, but it did not correctly generate various metrics as stated in the document:

- described in the documentation
![image](https://user-images.githubusercontent.com/77308895/225842826-3a977d27-04a5-455f-88a1-9dd605609e4d.png)

- what i got
![image](https://user-images.githubusercontent.com/77308895/225842891-95efb7c8-9895-40f2-921b-c4ee8c40b5fd.png)

I follow the official example to configure, don't know where the problem is

**Comment by kovrus** [comment]
Related to discrepancy between the documentation and implementation https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18743

**Comment by GoodGuyPlus** [comment]
> Related to discrepancy between the documentation and implementation #18743
So for the current implementation, how can I use service graph processor and tempo together? I didn't find the relevant documentation, please give an example

**Comment by JaredTan95** [comment]
@joyeahzhang What you got metrics with `service_graph_` prefix, you need to if check the prometheus exporter configured label with `namespace` you used for `service graph processor`?

**Comment by joyeahzhang** [comment]
> @joyeahzhang What you got metrics with `service_graph_` prefix, you need to if check the prometheus exporter configured label with `namespace` you used for `service graph processor`? e.g:
> 
> ```yaml
>   prometheus/servicegraph:
>     endpoint: localhost:9090
> -   namespace: servicegraph # remove this
> ```


it works, thanks a lot
