### ISSUE TITLE
[servicegraph] Check if virtual client nodes have orphan server spans

### ISSUE THREAD

**Issue by mapno** [open-telemetry/opentelemetry-collector-contrib#19764]
### Component(s)

processor/servicegraph

### Describe the issue you're reporting

Only create client virtual nodes when server spans are orphans. Otherwise, any server span without a match will create a virtual node.

Ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17350#discussion_r1099949579

**Comment by JaredTan95** [comment]
finished by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19763
this issue can be closed.

**Comment by atoulme** [comment]
Closing.
