### ISSUE TITLE
Problems getting metric data from persistent volumes (k8s)

### ISSUE THREAD

**Issue by Dannhausen** [open-telemetry/opentelemetry-collector-contrib#19797]
### Describe the issue you're reporting

Hi, 
i´m trying for several days to get metric data from my persistent volumes using the otel collector and report it to Splunk, but i didn´t found the right informations about this particulary.

This is, what i tried so far.

[exampel.txt](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/11018181/exampel.txt)

If i search for metrics in splunk with
| mcatalog values(metric_name) WHERE index=myownindexname
i get the following results
[splunk_metrics.csv](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/11018161/splunk_metrics.csv)

Someone got a hint for me?

**Comment by atoulme** [comment]
Not sure we can help you here. Your configuration points to a kubeletstats receiver and you are exporting to logging. I guess that's not your actual runtime configuration.
You then point to a CSV of results of the SPL command which points to valid results showing k8s metrics typically showing from kubernetes metrics collections. Several of those metrics report to storage and disk utilization, which I guess is what you are after.

What are you specifically looking for?

**Comment by Dannhausen** [comment]
I am kinda new in this k8s theme and therefor not that skilled...yet. As i understood so far, the kubeletstats receiver gives me all the information, the k8s api provides. Then, the processor model the information and give them to the exporter, logging in my case. Is the choosen exporter the problem here? Do i have to use a specific splunk exporter?

The metric information i get actually are valid, but i miss the metric information for the persistent volume. k8s.pod.volume for example isnt the persistent volume (it seems so, because it delivers totally different values in compare of my manually checkings).

I tried to get my informations about configuring the otel collector on different sites and readme´s, but for this specific part im unable too :(

**Comment by atoulme** [comment]
Please contact Splunk support if you are using our helm chart. If you are deploying things yourself, maybe look at the k8s cluster receiver as well to get information about persistent volumes.

**Comment by mochaab** [comment]
Did you manage to figure out how to access information about PV or PVC?
