### ISSUE TITLE
stanzareceiver docs are not correct regarding "pipeline" setting

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#1990]
After https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1535/files was done the README is no longer correct and testdata/config.yaml is also wrong.

We need to fix the README and also add tests for config that verify testdata/config.yaml.

**Comment by bogdandrutu** [comment]
Fixed by #2000
