### ISSUE TITLE
Access nested attributes in log count using count connector

### ISSUE THREAD

**Issue by greatestusername** [open-telemetry/opentelemetry-collector-contrib#19930]
### Component(s)

connector/count

### Is your feature request related to a problem? Please describe.

Currently the Count Connector can add attributes as dimensions (YAY!!) but it does not seem to be able to add nested attributes separated by `.` characters, only attributes in the base level of the attributes payload.

Would like to be able to add nested attributes as dimensions also;
E.G.
Currently `ref` can be used to create dimensions but `repository.name` cannot (as far as I can ascertain) from the example attributes below. This seems to be true of any nested attribute value.
```
{
    "attributes":
    [
        {
            "key": "ref",
            "value":
            {
                "stringValue": "refs/heads/main"
            }
        },
        {
            "key": "repository",
            "value":
            {
                "kvlistValue":
                {
                    "values":
                    [
                        {
                            "key": "name",
                            "value":
                            {
                                "stringValue": "my-repo-name"
                            }
                        },
                        {
                            "key": "repo-owner",
                            "value":
                            {
                                "stringValue": "username"
                            }
                        }
                    ]
                }
            }
        }
    ]
}
```

### Describe the solution you'd like

Essentially just want to be able to use the nested values from attributes as well.

If I'm doing it wrong please show me how its done! :smile:

**Comment by djaglowski** [comment]
@greatestusername, this sounds like a nice feature. Please let me know if you want to take this on and I will assign the issue to you.

**Comment by greatestusername** [comment]
Sure @djaglowski will try to squeeze some work in on this. :+1: 

Appreciate your work making this thing possible!

**Comment by jpkrohling** [comment]
Just wanted to mention that you seem to have the greatest username here, @greatestusername!
