### ISSUE TITLE
Review usage of foresight

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#19932]
### Describe the issue you're reporting

We've been sending data to foresight for some time now, and it's unclear to me whether we're using the tool at all. I've only logged into foresight a handful of times and did not immediately get anything from using the tool I wasn't already getting through github action logs.

I'm opening this issue to capture a discussion on whether we should discontinue the use of the tool and simplify the build pipeline. One of the downsides currently is that foresight immediately comments on new PRs, making it somewhat harder to identify PRs that have not been reviewed at all.

**Comment by serkan-ozal** [comment]
Hi @codeboten @TylerHelmuth,

This is Serkan, co-founder and CTO of Thundra, which is the company behind Foresight.

We would like to schedule a quick meeting to get your feedbacks and present a demo about how you can use Foresight to monitor flaky tests and CI pipelines.

Other than that, do you see any missing feature or issues with the Foresight?

**Comment by dmitryax** [comment]
@serkan-ozal, looks like the main use case for foresight is to highlight the tests run time and flakiness. It's a valid use case, but based on our experience, it didn't provide enough value to justify the added complexity. 

We are looking for a solution to another important use case. It's described in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20718. Essentially, we want to be able to send the performance test results somewhere where we can see the data on charts and be able to fetch them programmatically.

Do you think foresight can help with that?
