### ISSUE TITLE
Export data to Uptrace.dev

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-collector-contrib#2021]
**Is your feature request related to a problem? Please describe.**
I would like the possibility to send trace data to [Uptrace.dev](https://uptrace.dev)

**Describe the solution you'd like**
I have an exporter that sends trace data to Uptrace.dev.

**Additional context**
A PR will soon be provided that accomplishes this request.

**Comment by evan-bradley** [comment]
Closing as resolved by #2384.
