### ISSUE TITLE
Incorrect values in metadata container.image.name & container.image.tag

### ISSUE THREAD

**Issue by dmanojbaba** [open-telemetry/opentelemetry-collector-contrib#20239]
### Component(s)

processor/k8sattributes

## Description
Incorrect values in extracted metadata
```
- "container.image.name"
- "container.image.tag"
```

## Steps to Reproduce
We use self-hosted JFrog Artifactory for our local container images.
Also, we use the Docker Registry Ports method to connect to remote registries.
```
Example: local images
foo.bar.com:port0/my-app:my-tag

Example: dockerhub
foo.bar.com:port1/splunk/fluentd-hec:1.3.1

Example: quay.io
foo.bar.com:port2/signalfx/splunk-otel-collector:0.72.0
```
For these images, the `container.image.name` & `container.image.tag` are extracted incorrectly.

## Expected Result
```
container.image.name = foo.bar.com:port1/splunk/fluentd-hec
container.image.tag = 1.3.1
```

## Actual Result
```
container.image.name = foo.bar.com
container.image.tag = port1/splunk/fluentd-hec
```

### Collector version

v0.72.0

### Additional context

Error Source Code Lines:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/51612fb4a194f4e96b29e097179e8b0752fd4900/processor/k8sattributesprocessor/internal/kube/client.go#L380-L392

Because there is a `:port_number` in the `spec.Image` url, the `imageParts[0]` and `imageParts[1]` are incorrect.

Could this be fixed?

References:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/recommended_practices_for_container_development/naming

https://docs.docker.com/engine/reference/commandline/tag/#description

https://www.jfrog.com/confluence/display/JFROG/Getting+Started+with+Artifactory+as+a+Docker+Registry#GettingStartedwithArtifactoryasaDockerRegistry-ThePortsMethod

**Comment by dmitryax** [comment]
@dmanojbaba, thanks for the detailed report. Let me submit a fix
