### ISSUE TITLE
Dependencies only support go1.20

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#20245]
### Describe the issue you're reporting

Starting an issue here to capture some of the packages that cannot be upgraded due to minimum go requirements in those packages:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20177
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20478
- #23546

**Comment by codeboten** [comment]
Jaeger will support N-1 go versions starting with go 1.20, so we'll be blocked on upgrading that dependency until go 1.21 is released

**Comment by mx-psi** [comment]
Added #20478

**Comment by codeboten** [comment]
Now that we've bumped the go dep to 1.21, this issue can be closed
