### ISSUE TITLE
[receiver/zipkin][exporter/zipkin] Add codeowners to zipkin components

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#20269]
### Component(s)

exporter/zipkin, receiver/zipkin

### Describe the issue you're reporting

The zipkin components do not have explicit codeowners besides the approvers. It would be best to have several members of the community step up to become explicit codeowners of those components, as we distribute them with the core and contrib distributions.

**Comment by MovieStoreGuy** [comment]
I'm hope to be a code owner for this, but I would appreciate some extra hands on this.

**Comment by astencel-sumo** [comment]
Incidentally, I've just dipped my toes in these two components, fixed some docs issues:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22701
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22703

Given that there are currently no code owners at all, I'm willing to help @MovieStoreGuy with it

**Comment by crobert-1** [comment]
I can help out as well 👍

**Comment by MovieStoreGuy** [comment]
Let me raise a PR to include the three of us.
