### ISSUE TITLE
Need documentation for a working setup for fileexporter

### ISSUE THREAD

**Issue by Juliaj** [open-telemetry/opentelemetry-collector-contrib#20279]
### Describe the issue you're reporting

fileexporter is a good choice for debugging, especially with intermittent metrics errors. However, there is no instruction to help set it up. The readme states,   
```
The official opentelemetry-collector-contrib container does not have a writable filesystem by default since it's built using the special from scratch layer. As such, you will need to create a writable directory for the path, potentially by creating writable volumes or creating a custom image.
```
If users want to explore the path of creating a writable directory for the path, there are a few obstacles on the way. 
- No interactive access point to OpenTelemetryCollector pod to discover a proper value for `hostPath` , i.e. `kubectl exec -it` doesn't work.
- `initContainers` is not allowed thus creating custom path is impossible. 

Experts, please help document the setup to promote the usage of this good tool.

**Comment by atingchen** [comment]
I'll try to add this documentation and would love to see you improve it.

**Comment by atingchen** [comment]
@Juliaj  I'm sorry for replying to you so late.

We will follow the [documentation](https://opentelemetry.io/docs/k8s-operator/) to first install the operator in an existing cluster and then  create an OpenTelemetry Collector (otelcol) instance, like:

```shell
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: fileexporter
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:

    exporters:
      logging:
      file:
        path: /data/metrics.json

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging,file]
  volumes:
    - name: file
      emptyDir: {}
  volumeMounts: 
    - name: file
      mountPath: /data
EOF
```
