### ISSUE TITLE
[CI] lint-matrix (other) job is failing after enabling govulncheck

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#20274]
The lint-matrix (other) job is failing (timing out?) most of the times after https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19400 is merged.

Examples:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4493502284/jobs/7904820009
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4494191226/jobs/7907345218
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4494191226/jobs/7906977684
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4494191226/jobs/7906479473

```
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Using go1.19.7 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev (last modified 21 Mar 23 23:29 UTC).
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Using go1.19.7 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev (last modified 21 Mar 23 23:29 UTC).

Scanning your code and [31](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4493502284/jobs/7904820009#step:9:32)2 packages across 30 dependent modules for known vulnerabilities...
No vulnerabilities found.
/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/golangci-lint run --allow-parallel-runners --build-tags integration
make[2]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/mdatagen'
Running target 'lint' in module 'cmd/otelcontribcol' as part of group 'other'
make -C cmd/otelcontribcol lint
make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/otelcontribcol'
cd /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/tools && go build -o /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/golangci-lint -trimpath github.com/golangci/golangci-lint/cmd/golangci-lint
cd /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/tools && go build -o /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/addlicense -trimpath github.com/google/addlicense
cd /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/tools && go build -o /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/misspell -trimpath github.com/client9/misspell/cmd/misspell
/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/govulncheck ./...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Using go1.19.7 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev/ (last modified 21 Mar 23 23:29 UTC).
make[2]: *** [../../Makefile.Common:171: govulncheck] Killed
make[1]: *** [Makefile:178: cmd/configschema] Terminated
make: *** [Makefile:107: golint] Terminated
make[2]: *** [../../Makefile.Common:171: govulncheck] Terminated
Error: Process completed with exit code 1[43](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4493502284/jobs/7904820009#step:9:44).
```

**Comment by dmitryax** [comment]
cc @lootek

**Comment by lootek** [comment]
huh, that's really weird...

**Comment by lootek** [comment]
@dmitryax do you think it hit a timeout or maybe some memory limit? What do you think about extracting this scanner from the lint group to run it separately?

It's interesting since on the PR commit everything has passed https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4493269399 and also the running times look very similar to runs from the previous commits.

Since we don't use a fixed `govulncheck` version here I thought there might be some issue introduced recently but nothing interesting is on the top of the list https://github.com/golang/go/labels/vulncheck%20or%20vulndb

**Comment by dmitryax** [comment]
> do you think it hit a timeout or maybe some memory limit?

Yeah, maybe some VM resources exhaustion. Didn't look deeper

> What do you think about extracting this scanner from the lint group to run it separately?

I think it can be part of `checks` Github actions job or a separate job. I'm not sure lint target is a good fit for vulnerability checks

**Comment by lootek** [comment]
> > do you think it hit a timeout or maybe some memory limit?
> 
> Yeah, maybe some VM resources exhaustion. Didn't look deeper
> 

I was trying but didn't find any additional clues.

> > What do you think about extracting this scanner from the lint group to run it separately?
> 
> I think it can be part of `checks` Github actions job or a separate job. I'm not sure lint target is a good fit for vulnerability checks

Yeah, to me it was not the ideal place either but the best among the existing steps. Can I take this item and try moving this away from lint to its own job?

**Comment by atoulme** [comment]
It’s yours @lootek

**Comment by lootek** [comment]
This issue here was fixed 2 months ago by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20342
