### ISSUE TITLE
otelcol_exporter_queue_size and otelcol_exporter_queue_capacity is not available in 0.71 version. Can you please confirm ?

### ISSUE THREAD

**Issue by Leela-SR** [open-telemetry/opentelemetry-collector-contrib#20288]
### What happened?

I am not able to see the otelcol_exporter_queue_size and otelcol_exporter_queue_capacity metrics in the latest version of 0.71 otel_collector.

I am able to view other metrics otelcol_exporter_send_failed_spans

### Collector version

v0.71.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by astencel-sumo** [comment]
You need to provide a configuration that allows to reproduce this behavior. I'm not able to reproduce this with the OTLP/HTTP exporter either with v0.71.0 or with the latest v0.74.0.

My config file `otlp.yaml`:

```yaml
exporters:
  otlphttp:
    endpoint: http://localhost:8888

receivers:
  otlp:
    protocols:
      http:
    
service:
  pipelines:
    logs:
      exporters:
      - otlphttp
      receivers:
      - otlp
```

When I run:

```shell
./otelcol-contrib-0.71.0 --config ./otlp.yaml
```

then I can see the metrics you mention:

```shell
$ curl -s localhost:8888/metrics | grep ^otelcol_exp
otelcol_exporter_enqueue_failed_log_records{exporter="otlphttp",service_instance_id="043e1adc-b120-4022-9cfb-69364ef337e9",service_name="otelcol-contrib",service_version="0.71.0"} 0
otelcol_exporter_enqueue_failed_metric_points{exporter="otlphttp",service_instance_id="043e1adc-b120-4022-9cfb-69364ef337e9",service_name="otelcol-contrib",service_version="0.71.0"} 0
otelcol_exporter_enqueue_failed_spans{exporter="otlphttp",service_instance_id="043e1adc-b120-4022-9cfb-69364ef337e9",service_name="otelcol-contrib",service_version="0.71.0"} 0
otelcol_exporter_queue_capacity{exporter="otlphttp",service_instance_id="043e1adc-b120-4022-9cfb-69364ef337e9",service_name="otelcol-contrib",service_version="0.71.0"} 5000
otelcol_exporter_queue_size{exporter="otlphttp",service_instance_id="043e1adc-b120-4022-9cfb-69364ef337e9",service_name="otelcol-contrib",service_version="0.71.0"} 0
```

**Comment by Leela-SR** [comment]
Thanks @astencel-sumo . Please find my configuration below:
# set mode
mode: "deployment"

podAnnotations: 
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8888"
  prometheus.io/scrape: "true"

# Configuration for ports
ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false

presets:
  kubernetesAttributes:
    enabled: true
config:
  exporters:
    logging:
      loglevel: debug
    awsxray:
      region: us-east-1
      max_retries: 3
      proxy_address: <masked>
      index_all_attributes: true
      
  extensions:
    # The health_check extension is mandatory for this chart.
    # Without the health_check extension the collector will fail the readiness and liveliness probes.
    # The health_check extension can be modified, but should never be removed.l
    health_check: {}
    memory_ballast: {}
  processors:
    batch/traces:
      timeout: 120s
      send_batch_size: 500
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter:
      limit_mib: 100
      check_interval: 10s
    k8sattributes:
      passthrough: false
      pod_association:
      - sources:
        - from: resource_attribute
          name: k8s.pod.ip
      - sources:
        - from: resource_attribute
          name: k8s.pod.uid
      - sources:
        - from: connection
      extract:
        metadata:
         - "k8s.namespace.name"
         - "k8s.deployment.name"
         - "k8s.statefulset.name"
         - "k8s.daemonset.name"
         - "k8s.cronjob.name"
         - "k8s.job.name"
         - "k8s.pod.name"
         - "k8s.pod.uid"
         - "k8s.node.name"
         - "k8s.pod.start_time"
      filter:
        node_from_env_var: K8S_NODE_NAME
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${MY_POD_IP}:4317
        http:
          endpoint: ${MY_POD_IP}:4318
  service:
    extensions:
      - health_check
      - memory_ballast
    pipelines:      
      traces:
        exporters:
          - awsxray
          - logging
        processors:
          - k8sattributes
          - memory_limiter
          - batch/traces
        receivers:
          - otlp

clusterRole:
  # Specifies whether a clusterRole should be created
  create: true
  # Annotations to add to the clusterRole
  annotations: {}
  # The name of the clusterRole to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # A set of rules as documented here : https://kubernetes.io/docs/reference/access-authn-authz/rbac/
  rules:
   - apiGroups:
     - ''
     resources:
     - 'pods'
     - 'nodes'
     verbs:
     - 'get'
     - 'list'
     - 'watch'

  clusterRoleBinding:
    # Annotations to add to the clusterRoleBinding
    annotations: {}
    # The name of the clusterRoleBinding to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

**Comment by Leela-SR** [comment]
Please do let me know if I am missing anything to not to see otelcol_exporter_queue_capacity and otelcol_exporter_queue_size

**Comment by astencel-sumo** [comment]
If I'm understanding correctly the config you provided:

```yaml
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    traces:
      exporters:
      - awsxray
      - logging
      processors:
      - k8sattributes
      - memory_limiter
      - batch/traces
      receivers:
      - otlp
```

I reason that you're using the [AWS X-Ray exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.71.0/exporter/awsxrayexporter) and the [Logging exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.71.0/exporter/loggingexporter) in your Otelcol config. I don't think either of them uses queue, so that would explain why the queue metrics are not reported.

Why do you expect these metrics to be present? Are they present when you use a different version of Otelcol? Are they present when you use a different Otelcol config?

**Comment by astencel-sumo** [comment]
> Our understanding is that, irrespective of the exporters, Otel has inbuilt queue which holds the traces

To my knowledge, that's not true.

Looking at your specific pipeline, the [Batch processor](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.71.0/processor/batchprocessor) is a component that will buffer data before forwarding it, depending on how it's configured. In your case, it seems to be:

```yaml
processors:
  batch/traces:
    timeout: 120s
    send_batch_size: 500
```

So it buffers the spans (in memory) until it receives 500 of them, then it sends them out further down the pipeline - i.e. to the exporters. It also has a timeout, so it will send all the spans it has every 2 minutes, even if it hasn't collected 500 spans.

I'm afraid the `batch` processor does not produce any metrics on the state of its internal buffer - e.g. how many spans it currently has buffered.

If you remove the `batch` processor from your configuration, you should be able to see the spans show up in your exporters without any delay.

Does this help?

**Comment by astencel-sumo** [comment]
Reading your comment again (and again and again :wink: ), if you want to ensure that the collector has an internal queue and does not drop the data that it fails to send to a remote endpoint for some time, the collector does have built-in queue and retry mechanisms that are described here: https://github.com/open-telemetry/opentelemetry-collector/tree/v0.71.0/exporter/exporterhelper, but **it's up to a specific exporter to use them**. Some exporters support these features, like the core [OTLP exporter](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.71.0/exporter/otlphttpexporter/README.md), but not all of them do. Looking at the [AWS X-Ray exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.71.0/exporter/awsxrayexporter), it doesn't look to me like it supports those. It seems to have its own implementation of retries, judging by the `max_retries` configuration property. But if those retries are done, I'd guess the data is dropped. Disclaimer: I haven't this exporter, it's just my guess based on its configuration options.

**Comment by Leela-SR** [comment]
@astencel-sumo 

Thanks for your description. 

1. Yes, we did try configuring [AWS X-Ray Exporter] (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.71.0/exporter/awsxrayexporter) but facing issues in configuring the same raised issue on that with open telemetry.

[Configuring request_timeout in exporter -> awsxray causes server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding error · Issue #20433 · open-telemetry/opentelemetry-collector-contrib (github.com)](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20433)
 

> > Our understanding is that, irrespective of the exporters, Otel has inbuilt queue which holds the traces
> 
> To my knowledge, that's not true.
> 
> Looking at your specific pipeline, the [Batch processor](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.71.0/processor/batchprocessor) is a component that will buffer data before forwarding it, depending on how it's configured. In your case, it seems to be:
> 
> ```yaml
> processors:
>   batch/traces:
>     timeout: 120s
>     send_batch_size: 500
> ```
> 
> So it buffers the spans (in memory) until it receives 500 of them, then it sends them out further down the pipeline - i.e. to the exporters. It also has a timeout, so it will send all the spans it has every 2 minutes, even if it hasn't collected 500 spans.
> 
> I'm afraid the `batch` processor does not produce any metrics on the state of its internal buffer - e.g. how many spans it currently has buffered.
> 
> If you remove the `batch` processor from your configuration, you should be able to see the spans show up in your exporters without any delay.
> 
> Does this help?

@astencel-sumo 
Isn't it efficient to have batch processing considering your application (platform) is huge? Also, open telemetry highly recommends having batch processing.

**Comment by Leela-SR** [comment]
> Reading your comment again (and again and again 😉 ), if you want to ensure that the collector has an internal queue and does not drop the data that it fails to send to a remote endpoint for some time, the collector does have built-in queue and retry mechanisms that are described here: https://github.com/open-telemetry/opentelemetry-collector/tree/v0.71.0/exporter/exporterhelper, but **it's up to a specific exporter to use them**. Some exporters support these features, like the core [OTLP exporter](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.71.0/exporter/otlphttpexporter/README.md), but not all of them do. Looking at the [AWS X-Ray exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.71.0/exporter/awsxrayexporter), it doesn't look to me like it supports those. It seems to have its own implementation of retries, judging by the `max_retries` configuration property. But if those retries are done, I'd guess the data is dropped. Disclaimer: I haven't used this exporter, it's just my guess based on its configuration options.

Thank you for the above information. 

We did try to explore on configuring max_retries and request_timeout, so that Otel holds the traces for a descent amount of time before dropping off them (assuming queue has the capacity to hold the traces). 

Unfortunately, on configuring the request_timeout, I am getting the following error which is raised in Otel channel.
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20433

If you have information on configuring this parameter/Error, please share it across.

Appreciating your comments and support on this. Thanks again!

**Comment by astencel-sumo** [comment]
> > If you remove the batch processor from your configuration, you should be able to see the spans show up in your exporters without any delay.
> 
> Isn't it efficient to have batch processing considering your application (platform) is huge? Also, open telemetry highly recommends having batch processing.

Yes, having the `batch` processor in the pipeline is definitely recommended in a production scenario. My comment was referring to a test scenario, in the sense "to understand how the `batch` processor works, see what happens when you remove it from the pipeline". But after reading your comment again, I realized that's probably not what you're after, and I added another comment. :slightly_smiling_face: 

> Unfortunately, on configuring the request_timeout, I am getting the following error which is raised in Otel channel. #20433 

I have replied in the issue. Please try using `request_timeout_seconds: 120` instead of `request_timeout: 120s`.

**Comment by Leela-SR** [comment]
Many Thanks @astencel-sumo.

**Comment by astencel-sumo** [comment]
I'm closing this as it seems it is resolved.
