### ISSUE TITLE
[processor/traces] Action/sampling on resources attributes based on span attributes

### ISSUE THREAD

**Issue by yehaotian** [open-telemetry/opentelemetry-collector-contrib#20294]
### Component(s)

traces related processors

### Is your feature request related to a problem? Please describe.

**Usecase**:
We have some debug span attributes and would like to 100% sample it in `tailsamplingprocessor` policy. At this moment tail sampling processor does not support policy on span attributes but only on resource and record `string_attribute`.

Currently we do not have status code on span, so that the workaround is using `spanprocessor` to set `ERROR` status when match the debug span attribute and leverage `status_code` policy for 100% sampling.
However, we have a new case need to send the trace(debug trace) contains the debug span attribute to a different destination instead sending all ERROR cases, how can we use the current attribute/filter/span/resources/tailsampling processors to achieve that?

**Note**: The debug span attribute only exist in the root span, not all spans in the trace.

### Describe the solution you'd like

If the current processors cannot make it happen, several solutions can be applied:

1. Have `spanprocessor` able to set resource and record attributes instead of just status code.
2. Have `resourcesprocessor` able to insert/set resource and record attributes when match span attributes.
3. Have  `attributesprocessor` able to insert/set resource and record attributes when match span attributes.
4. Have `tailsamplingprocessor` policy on span attributes (unlikely due to performance?)
5. ...

**Comment by yehaotian** [comment]
cc: @TylerHelmuth

**Comment by TylerHelmuth** [comment]
@jpkrohling I'm not familiar with the tailsamplingprocessor config, but when I hear "I wish I had access to this piece of telemetry" I think of OTTL.  Is there a place in tailsamplingprocessor where we could utilize OTTL conditions?

**Comment by yehaotian** [comment]
Hi @jpkrohling @TylerHelmuth any updates on this? Are we expecting OTTL policy for tail sampling processor soon?

**Comment by TylerHelmuth** [comment]
I think OTTL can help here, but I won't be able to work on it soon.

**Comment by jpkrohling** [comment]
Same. I'm happy to review your PR, @yehaotian, in case you want to send one, but I don't have time to work on it myself.

**Comment by TylerHelmuth** [comment]
Couple quick suggestions:
- replace `query` with `statement`.
- Drop the Invocation (`sample`) and right the statement as if it were an OTTL condition.  We don't have a condition-only parser yet for OTTL (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13545) but the condition can be appended to a noop invocation during startup.  This is the pattern the filterprocessor and countconnector use.

Hopefully the tailsamplingprocesor would be able to take advantage of `internal/filter/filterottl` to do the matching.

@jpkrohling I haven't read through the tailsamplingprocessor code myself, but if `internal/filter/filterottl` slots in nicely to some boolean check somewhere then I think this is a relatively straightforward approach.

**Comment by jpkrohling** [comment]
> some boolean check somewhere then I think this is a relatively straightforward approach

Yes, it boils down to that. We have more states than just booleans, but a policy can decide to return only a "sample" or "not sampled" if it wants.

**Comment by jiekun** [comment]
@yehaotian Please check the OTTL condition policy and see if it mets your requirement :P

**Comment by TylerHelmuth** [comment]
Closing this for now as the OTTL condition policy will allow conditions based any telemetry field.  Please ping me if you think it should be reopened.

**Comment by yehaotian** [comment]
Thanks for the change!!
I have following policy and **it seems not working**:
```
        {
          name: debug-policy,
          type: ottl_condition,
          ottl_condition: {
            error_mode: ignore,
            span: [
              "attributes[\"debug-id\"] != nil",
            ]
          }
        },
```
btw no error messages.

**Comment by yehaotian** [comment]
Debug log:
```
{"level":"debug","ts":1685482015.4306045,"caller":"sampling/ottl.go:59","msg":"Evaluating with OTTL conditions filter","kind":"processor","name":"tail_sampling","pipeline":"traces","traceID":"061c3f37e4c300ec350e3f9d9bd75e67"}
{"level":"debug","ts":1685482015.4307067,"caller":"tailsamplingprocessor@v0.78.0/processor.go:199","msg":"Sampling policy evaluation completed","kind":"processor","name":"tail_sampling","pipeline":"traces","batch.len":1,"sampled":0,"notSampled":4,"droppedPriorToEvaluation":0,"policyEvaluationErrors":0}
```
The span does have **debug-id** attribute

**Comment by TylerHelmuth** [comment]
@yehaotian is `debug-id` definitely an attribute and not a resource attribute?

**Comment by yehaotian** [comment]
Yes, this is something can be added in the business logic for debug.
Also it is listed in **Attribute** not **Resource** category

**Comment by TylerHelmuth** [comment]
@yehaotian Out of curiosity what happens if you do == instead? I want to make sure we didn't accidentally inverse the condition.

**Comment by jiekun** [comment]
@TylerHelmuth @yehaotian I believe this should work. test case as below:
https://github.com/jiekun/opentelemetry-collector-contrib/blob/1a42bceb9a1cf10bc11e427628a4042843514847/processor/tailsamplingprocessor/internal/sampling/ottl_test.go#L66

```go
		{
			"OTTL conditions inverse match(!=) span attributes 2",
			[]string{"attributes[\"attr_k_1\"] != \"attr_v_1\""},  // this is my ottl condition
			[]string{},
			[]spanWithAttributes{{SpanAttributes: map[string]string{"attr_k_1": "attr_v_2"}}},  // span attributes
			false,
			Sampled,  // it should be sampled
		},
```

I will check it again today with " != nil" condition.

**Comment by yehaotian** [comment]
After enabling debug logging exporter, I notice sometimes the attributes fail to be reported to otel collector which seems super wired to me.
FYI, we are using Jaeger opentracing instrumentation with otel collector Jaeger receiver, perhaps there are issues during schema transformation

**Comment by TylerHelmuth** [comment]
For our testing purposes we need to reduce variability.  Can you use the attributeprocessor or transformprocessor to add the attribute to the telemetry before the tailsamplingprocessor to ensure that it is always present?

**Comment by jiekun** [comment]
> After enabling debug logging exporter, I notice sometimes the attributes fail to be reported to otel collector which seems super wired to me. FYI, we are using Jaeger opentracing instrumentation with otel collector Jaeger receiver, perhaps there are issues during schema transformation

Thanks for clarifying this. I check check the `!= nil` condition with unit test as well, which works correctly. I am putting those test cases here FYI. Feel free to provide more info / feedback.

```Go
		{
			Desc:                "OTTL conditions 1",
			SpanConditions:      []string{"attributes[\"attr_k_1\"] == \"attr_v_1\""},
			SpanEventConditions: []string{},
			Spans:               []spanWithAttributes{{SpanAttributes: map[string]string{"attr_k_1": "attr_v_1"}}},
			WantErr:             false,
			Decision:            Sampled,
		},
		{
			Desc:                "OTTL conditions 2",
			SpanConditions:      []string{"attributes[\"attr_k_1\"] != \"attr_v_1\""},
			SpanEventConditions: []string{},
			Spans:               []spanWithAttributes{{SpanAttributes: map[string]string{"attr_k_1": "attr_v_1"}}},
			WantErr:             false,
			Decision:            NotSampled,
		},
		{
			Desc:                "OTTL conditions 3",
			SpanConditions:      []string{"attributes[\"attr_k_1\"] != nil"},
			SpanEventConditions: []string{},
			Spans:               []spanWithAttributes{{SpanAttributes: map[string]string{"attr_k_1": "attr_v_1"}}},
			WantErr:             false,
			Decision:            Sampled,
		},
```
