### ISSUE TITLE
[receiver/skywalking]Need to achieve the collection of metric data

### ISSUE THREAD

**Issue by aheling11** [open-telemetry/opentelemetry-collector-contrib#20315]
### Component(s)

receiver/skywalking

### Is your feature request related to a problem? Please describe.

I found that skywalking receiver can only accept tracing data, metrics like JVM runtime metrics are not supported. And opentelemetry already has a [standard](https://github.com/open-telemetry/opentelemetry-specification/blob/b290f35266182a58f6ff2e753cd337ee400436c1/specification/metrics/semantic_conventions/runtime-environment-metrics.md) for JVM runtime metrics. It would be great if the skywalking receiver could also support metrics such as JVM runtime metrics and convert them into `otlp` metrics 

### Describe the solution you'd like

I noticed that the skywalking receiver has reserved the Collect interface for JVM metrics. Just implement the interface and translate the data format to otlp.

**Comment by JaredTan95** [comment]
Thank you for your proposal, which is also a feature I intend to implement soon. 
But I may not be able to dedicate immediate energy to achieving it lately. 
If you want, your contribution is also welcome :-P

**Comment by aheling11** [comment]
I'll be happy to implement this feature  
please assign this issure to me :)

**Comment by fatsheep9146** [comment]
It's yours! @aheling11

**Comment by JaredTan95** [comment]
hi, @aheling11 How is it going? just friendly ping make this issue `no-stale` :-P

**Comment by aheling11** [comment]
> hi, @aheling11 How is it going? just friendly ping make this issue `no-stale` :-P

hi, after completing the first step of the code refactoring, I'm currently finishing up the remaining parts. :)

**Comment by maokitty** [comment]
hi, @aheling11 are you still working on the remaining parts? i have some needs for the skywalking jvm metric recently, if you are still working on it just ignore me or i can see what i can do for this issue

**Comment by fatsheep9146** [comment]
@maokitty could you take this issue?

**Comment by aheling11** [comment]
> hi, @aheling11 are you still working on the remaining parts? i have some needs for the skywalking jvm metric recently, if you are still working on it just ignore me or i can see what i can do for this issue

I'm sorry for not following up on this for a long time. I have completed half of the remaining work and will submit a PR to merge the code into the main branch as soon as possible.

**Comment by jiekun** [comment]
Thanks for your contribution. I'm also looking for a receiver to collect some jvm metrics reported by skywalking SDK. Looking forward to next release!

**Comment by jiekun** [comment]
I assume this feature is implemented with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26315 ?
