### ISSUE TITLE
[coralogixexporter] default to gzip

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#20337]
### Component(s)

exporter/coralogix

### Is your feature request related to a problem? Please describe.

Make coralogixexporter default to gzip to save on network costs.

### Describe the solution you'd like

Make coralogixexporter default to gzip to save on network costs.

**Comment by codeboten** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20336
