### ISSUE TITLE
update github.com/golangci/golangci-lint from 1.51.1 to 1.52.2 causes issues

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#20424]
### Component(s)

- [x] #22858
- [x] #22859
- [x] #22860
- [x] #22861
- [ ] 

### Describe the issue you're reporting

This upgrades causes many lint failures. Creating a separate issue to address them.

**Comment by fatsheep9146** [comment]
This issue could be closed? @codeboten
