### ISSUE TITLE
Implement a Persistent Buffer in OpenTelemetry Collector to Prevent Data Loss

### ISSUE THREAD

**Issue by moonbox3** [open-telemetry/opentelemetry-collector-contrib#20422]
### Component(s)

A persistent buffer

### Is your feature request related to a problem? Please describe.

The Otel collector normally operates as a stateless pipeline. Due to the statelessness, data can be dropped at any point in the pipeline if an error is encountered. It is possible to set up retries and the exporter helper's retry queue, but the sending queue is asynchronous as the operation is fire-and-forget. I'd like a better handle around which data is actually sent from component to component in the pipeline so I am assured that nothing is dropped.

### Describe the solution you'd like

To be able to manage state I'd like a new processing or consumer component that integrates a persistent buffer layer (i.e. some key-value store). This buffer will precede each defined Otel consumer (processors or exporters) to ensure data can be passed from one component to another without issues. In the case of errors, the component that failed can be identified, and retries can be performed within set thresholds. This configuration introduces state management to the Otel pipeline, which is typically stateless, enhancing data reliability and minimizing the risk of data loss.

**The following outlines a ConsumeLogs call in the buffer processor, as an example:**

The incoming plog.Logs are iterated over first by the resource logs, then by the scope logs and finally by the logs where the log body data is persisted. The call to persist the data needs to be as robust as possible with its own retry mechanism in the event of any failure. Once the call to persist the data succeeds, it is possible to push the logs to the next consumer. The error case is covered below.

**Calling the next processor:**

In the persist buffer processor, if the nextConsumer is not nil, then proceed to send the logs.

**In the event of a failure after calling the next processor:**

If a failure is encountered while sending the logs, the buffer consumer should attempt to retry sending the logs within some configured threshold. If the threshold is exceeded, depending upon the desired configuration, the pipeline can either enter a terminal state or continue on to the next component for processing.

**Collector shutdown:**

Upon collector shutdown, data will remain in the persistent buffer. The next section (collector startup/restart) helps define if the data persisted will be sent further along in the collector or not.

**Collector startup/restart:**

When the collector is started or restarted, the persistent buffer can check if there is data still present. If so, similar to the [OTLP protocol](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#duplicate-data), duplicate data will be sent. Otherwise if data failed to send before due to the machine powering down, or the process crashing, the data is retrieved from the buffer and sent along for the first time. There would need to be some sort of identifier that the buffer processor can use so it knows if it should be sending the data that is present in the buffer or if it should discard it given that the pipeline changed or was re-configured and the old data is stale.

**Persistent buffer data removal:**

Data doesn't stay in the persistent buffer forever. When the call to the nextConsumer is successful, the data added to the buffer is removed. To avoid stale data and causing the buffer to grow too large, a TTL can also be configured. 

### Describe alternatives you've considered

I've investigated the following alternatives:

- Relying on the exporter helper's retry queue: This a great feature to have, but I want to have more control over knowing if data was retried successfully. The current retry mechanism is essentially fire-and-forget and if the retry doesn't end up succeeding after the allowed number of retries, the data is lost.
- Callbacks: there is a possibility that callbacks could work in some Otel scenarios; however, things get complicated when using batch processors that are able to slice the logs, metrics, or traces based on a threshold of allowed data to be sent per batch. The callback story gets too complicated because an incoming callback gets split into how many returning callbacks?

### Additional context

I am currently working on this, and welcome any feedback. Thank you!

**Comment by atoulme** [comment]
Please consider joining a SIG meeting and presenting your design.

**Comment by moonbox3** [comment]
@atoulme Is there a design doc template I should follow? I will work on this and hopefully have it ready to present by next week's meeting, if not the week after.

**Comment by atoulme** [comment]
I haven't seen a particular doc template for design docs on this project. Worth asking on Slack, others might be aware.

**Comment by moonbox3** [comment]
In doing more research, it looks like the [persistent queue](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper#persistent-queue) and the [file storage extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage) may get me 90-95% of the way there. That's good news.

One question I do have is that I felt like I saw a discussion somewhere which I am unable to find again. It talked about the ability to wrap other components (like processors) with some sort of buffer. Is this true or did I mis-read/remember? Tagging @djaglowski as I thought it was something you wrote.

**Comment by djaglowski** [comment]
@moonbox3, unfortunately I'm only aware of the functionality that you found. I hope it does what you need.

**Comment by moonbox3** [comment]
Closing this issue. I've tested the persistent queue and the file storage extension and they are working well. This should meet my requirement for now.

**Comment by vasilemihali** [comment]
I do see is closed, but the need is valid :)

hi @moonbox3 can you share a configuration you used ?
I tried to use https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage and was able to start, but I have same challenge and I get into following issue:

my config is from file_receiver to file (NFS mount to OTEL).
`
    receivers:
      filelog:
        ...
        start_at: end
        storage: file_storage/receiver
        
     exporters:
      debug:
        verbosity: normal
      file/nfs:

    service:
      extensions:
      - health_check
      - file_storage/receiver
      pipelines:
        logs:
          receivers:
          - filelog
          processors:
          - memory_limiter
          - transform/group_path
          - batch
          exporters:
          - file/nfs 
`

let's say in current day file in NFS I have 10 logs (also 10 in docker pod log)
1. OTEL collector gets restarted (manual, so I can test storage)
2. 2 more logs are being created in docker pod log
3. current day file in NFS I have 2 logs (also 12 in docker pod log)

so, somehow filelog or file exporter, not sure who to blame, does overwrite current day content, instead to append.

Many thanks.
