### ISSUE TITLE
Add @astencel-sumo as triager

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector-contrib#20431]
### Describe the issue you're reporting

Hey, I wasn't able to find the exact steps to request [triager](https://github.com/open-telemetry/community/blob/main/community-membership.md#triager) role documented, so creating an issue to add myself as triager on the contrib repo.

I've been an active contributor to contrib and a Collector SIG attendee for a couple months now, I also try to help with the issue backlog whenever I can. Having more permissions as a triager would help me do this job better.

**Comment by atoulme** [comment]
Great! Thank you for all your work and volunteering!

@open-telemetry/collector-contrib-maintainer please review.

**Comment by dmitryax** [comment]
I support

**Comment by astencel-sumo** [comment]
Thank you all, so many thumbs up 😍☺️🙏

**Comment by astencel-sumo** [comment]
Not sure if I'm looking at the right thing, but I have an impression that I still don't have the "triager" permissions on the repo :sweat_smile: I'm not able to change labels on issues etc.

Shouldn't I be added to the [@collector-contrib-triagers](https://github.com/orgs/open-telemetry/teams/collector-contrib-triagers/members) team?

**Comment by djaglowski** [comment]
@astencel-sumo, this last step is often overlooked. Thanks for calling it out. I've invited you now.
