### ISSUE TITLE
Return memory usage in percentage

### ISSUE THREAD

**Issue by 4s3ti** [open-telemetry/opentelemetry-collector-contrib#20449]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Host metrics contains a metric with percentage of memory usage (free/used).

**Comment by atoulme** [comment]
Can you compute this from existing metrics?

**Comment by 4s3ti** [comment]
It might be hard for me to explain this very well as I am quite new to this, 
but from the metrics I can see, 

Can calculate the Total memory with the sum of all memory attributes state
And with that value the rest can then be computed as well with something like of: 

Used memory percentage: ` ((Free Memory + Cached Memory) / Total memory) * 100`
Free Memory percentage: `(Free Memory / Total Memory) * 100`

I am sure there might be a more accurate way of doing it, but in a nutshell I believe yes, existing metrics can be used to compute this.

**Comment by 4s3ti** [comment]
Well, I was asking if it could be possible to have that metric coming already computed from the collector as i've realized that for example when using opensearch / elasticsearch it seems to be somewhat over complicated to make those calculations, therefore could be handy have that metric coming already computed form the collector. but if its too much trouble or if its considered bad practice to to so, please feel free to close this feature request.

**Comment by atoulme** [comment]
It's out of scope of the collector and you can perform this calculation in your observability solution of choice. You could create your own metric by using the transformprocessor to compute a derived metric by combining 2 host metrics.
