### ISSUE TITLE
Instana exporter removes service.name

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-collector-contrib#20454]
### Component(s)

exporter/instana

### Describe the issue you're reporting

We are currently facing the problem, that the instanaexporter removes the `service.name` tag from the spans. Therefore the service mapping in instana does not work properly - as stated in the [docs](https://www.ibm.com/docs/en/instana-observability/current?topic=applications-services#apply-the-call-tag-servicename), the calls service.name tag will be used for service mappings.

Span in Instana:

![Bildschirm­foto 2023-03-29 um 15 31 31](https://user-images.githubusercontent.com/377953/228554633-1af828c7-c66e-4575-a5c6-886d2fa957cb.png)

Same Span in Tempo:

![Bildschirm­foto 2023-03-29 um 15 32 18](https://user-images.githubusercontent.com/377953/228554701-ba94dfba-a816-4f09-99d0-2f537ac1a830.png)

Is this known and is there a way to workaround here? 

EDIT: Looks like instana-exporter does not include the [resource informations](https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/) when converting the span

**Comment by atoulme** [comment]
Closing as fixed.
