### ISSUE TITLE
[receiver/vcenter] Enhance performance metrics collection

### ISSUE THREAD

**Issue by gsanchezgavier** [open-telemetry/opentelemetry-collector-contrib#20523]
### Component(s)

receiver/vcenter

### Is your feature request related to a problem? Please describe.

I would like to increase the number of metrics coming from Performance Queries, but some enhancement would need to be done in the current implementation to prevent overloading vcenter, like disabling collection when metrics are disabled and [batching query requests](https://developer.vmware.com/docs/6611/vmware-vsphere-web-services-sdk-programming-guide/doc/GUID-FD5B96DD-7A74-44CB-8FAF-A7845ABCEBEE.html).

### Describe the solution you'd like

As a main goal of the feature, I would like to extend the support for more performance metrics by adding new the two mechanisms listed below and a few new metrics.

Adding the mechanism to skip performance metric collection if metrics are disabled

Batching the performance metrics queries to follow vmware recommendations to query in batches between 10 and 50 entities.

Support performance metrics from different resource types, currently there is only VM and Host with Real-time intervals.

Adding new datastore [capacity counters](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/disk_storutil_counters.html) to Vm and Datastores. They are going to be a total of 7 new metrics, 3 for the VM and 4 for the datastore.

### Additional context

This is part of a NewRelic initiative to adopt the vcenter receiver as a source of instrumentation. We have identified that there are around 60 performance metrics used by our customers at the moment.

**Comment by gsanchezgavier** [comment]
Forgot to mention that I can work on it once the proposal gets refined/approved.

**Comment by djaglowski** [comment]
@gsanchezgavier, I am supportive of making such improvements as long as we can do so carefully, which I'm sure is possible. I suggest we identify relatively small changes from this proposal and carve those out as separate PRs. What would be the first step or two?

**Comment by gsanchezgavier** [comment]
Thanks for the fast response @djaglowski, totally agree. 

I think that disabling the collection of disabled metrics in the config could be the first small step.
At initialization time remove disabled metrics from the corresponding list (ie [vm](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7f4e051bd7976a7b1108d5ed9f2e319523a53743/receiver/vcenterreceiver/metrics.go#L149)) so they are not queried. 

As a second step, I would add the 1 datastore metrics which also will need to implement the collection of them in a similar way that is done by the VM and Hosts.

WDYT?

**Comment by gsanchezgavier** [comment]
just passing here to mention that I'm waiting for the availability of a vcenter dev environment to start working on this. Even if vcsim can simulate these metrics I would like to have the environment to do some extra tests, and not rely completely in the simulator.
