### ISSUE TITLE
[receiver/vcenter] Standard Metrics expansion

### ISSUE THREAD

**Issue by carlossscastro** [open-telemetry/opentelemetry-collector-contrib#20526]
### Component(s)

receiver/vcenter

### Is your feature request related to a problem? Please describe.

I would like improve the vcenter receiver with the addition of more
standard metrics and attributes (not performance metrics).

### Describe the solution you'd like

There are 3 different implementations that I see necessary to add these metrics:

1. Some of these metrics are already being retrieved by the current sdk calls made by the receiver. They just need to be added to the metadata definition file.
   This would account approximately 15 new metrics
   Example - [VM Cpu OverallUsage](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/fe08899f-1eec-4d8d-b3bc-a6664c168c2c/7fdf97a1-4c0d-4be0-9d43-2ceebbc174d9/doc/vim.vm.Summary.QuickStats.html)
   
2. A few others would require other properties to be added in the api calls in order to retrieve them.
   This would account approximately 20 new metrics
   Example - [VM Storage TotalUncommitted](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/fe08899f-1eec-4d8d-b3bc-a6664c168c2c/7fdf97a1-4c0d-4be0-9d43-2ceebbc174d9/doc/vim.vm.StorageInfo.UsageOnDatastore.html)

3. Introduce new metric groups (i.e Snapshot metrics).
   This would account approximately 17 new metrics
   Example - Snapshot TotalMemoryInDisk

### Additional context

This is part of a NewRelic initiative to adopt the vcenter receiver as a source of instrumentation.

**Comment by schmikei** [comment]
Seems like it would be a welcome change to add more metrics/attributes if applicable to the [metrics data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md). Is there any chance you could outline _each_ metric you are proposing to add? 

@djaglowski and I are happy to look them over in a PR and see if they fit nicely into the receiver/data model :)

**Comment by carlossscastro** [comment]
Hi @schmikei 

Thanks for the quick reply.
I'm going to work on the list of new proposed metrics/attributes and will send it shortly

**Comment by djaglowski** [comment]
@carlossscastro, I have a few questions about the proposal:

1. How does `Properties` relate to the OpenTelemetry data model?
2. There are several boolean and enumerated values. How are you proposing that these would be modeled as metrics? One option is to use one-hot encoding, where a metric will contain a data point for each possible state, where the data points representing the current state has a value of 1, and the other data points have a value of 0. ([example](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/13bcae344506fe2169b59d213361d04094c651f6/receiver/elasticsearchreceiver/metadata.yaml#L608-L620))

**Comment by djaglowski** [comment]
Thanks for the clarifications, @carlossscastro. This sounds good to me.

**Comment by atoulme** [comment]
@carlossscastro would you like to be assigned this issue?

**Comment by carlossscastro** [comment]
@atoulme That sounds good. Once the list is complete I will be working on the implementation.

**Comment by carlossscastro** [comment]
@schmikei @djaglowski 

Here the proposal for VM Metrics: https://docs.google.com/document/d/1uGyxsM6GsqKdB0ie94ZGxzthudczlsineCaXB_PNM6g/edit?usp=sharing

Let me know if you prefer to have 1 single doc and merge everything in the same doc

**Comment by carlossscastro** [comment]
@djaglowski @schmikei 

These are the last 3 proposals:
* Data Stores: https://docs.google.com/document/d/19RAbysnr6SmRSdfT8U1gi-lz2OEvrcqiTLnU7WoMqaU/edit?usp=sharing
* Resource Pools: https://docs.google.com/document/d/1IzLW4i5sx4_SaMXEtPyzVaRu0Jrk4qdw2j64kLOcmyE/edit?usp=sharing
* Snapshots: https://docs.google.com/document/d/1ibph8dwzsWqQKAKVmyvSCqRdk58KPl4b7fvT4K_lAfU/edit?usp=sharing

Let me know if you prefer all this in a single doc

**Comment by djaglowski** [comment]
@carlossscastro, these generally look good to me. I left one comment where I think changes are needed, but otherwise I think we can proceed with implementation and we can work through minor details on the PRs as necessary.

**Comment by carlossscastro** [comment]
Thanks for the quick reply @djaglowski .

I agree we can proceed to the next steps and agree on any implementation details as we work through the PRs.
I would suggest separate PRs to implement each category of metrics (as per each document) to keep them as short as possible to make them easier for review. WDYT?
