### ISSUE TITLE
Make splunkhec exporter http idle timeout lower/configurable

### ISSUE THREAD

**Issue by matthewmodestino** [open-telemetry/opentelemetry-collector-contrib#20543]
### Component(s)

exporter/splunkhec

### Is your feature request related to a problem? Please describe.

The default http connection idle timeout is apparently [hard coded at 30 seconds](https://pkg.go.dev/net/http#:~:text=10%2C%0A%09IdleConnTimeout%3A%20%20%20%2030%20*-,time,-.Second%2C%0A%09DisableCompression%3A%20true), which is higher than Splunk's, which is set by `busyKeepAliveIdleTimeout` and defaults to 12 seconds. 

This causes "EOF" errors/retries on the collector side.

```
2022-04-05T12:55:27.607Z info exporterhelper/queued_retry.go:215 Exporting failed. Will retry the request after interval. {"kind": "exporter", "name": "splunk_hec/platform_logs", "error": "Post \"https://foo.bar.com:8088/services/collector\": EOF", "interval": "3.985412818s"}
2022-04-04T16:39:44.614Z    info    exporterhelper/queued_retry.go:218    Exporting failed. Will retry the request after interval.    {"kind": "exporter", "name": "splunk_hec/platform_logs", "error": "Post \"https://foo.bar.com:443/services/collector/event\": EOF", "interval": "4.623187485s"} 
```

This causes unnecessary retries and buffering on the OTel collector. 

### Describe the solution you'd like

I would like the http idle connection timer to be configurable, or set much lower, like we did in fluentd-hec, where the idle connection timer is 5 seconds, to explicitly avoid this situation. 

https://github.com/splunk/fluent-plugin-splunk-hec#idle_timeout-integer

### Describe alternatives you've considered

We have tried the workaround of raising the Splunk `busyKeepAliveIdleTimeout` to a value higher than OTel or the load balancer that may be between OTel agent and Splunk, and while it does help reduce the instances of EOF, it requires users to customize the default Splunk deployment and is not as easy as tuning the collector in many cases. 

### Additional context

This has been tracked in Splunk's distro [here](https://github.com/signalfx/splunk-otel-collector/issues/1453)

**Comment by atoulme** [comment]
This is not a proper response, but some context here:

Our default timeout is set to 10s: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/splunkhecexporter/factory.go#L69
The exporter takes advanced http settings as well: https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/README.md

**Comment by atoulme** [comment]
It looks like the fix is to change the default idle timeout to 10s, (or at least make it configurable) - we can look into that.

**Comment by matthewmodestino** [comment]
Ah! Good find! In fact all these settings likely play a role here:

[max_idle_conns](https://golang.org/pkg/net/http/#Transport)
[max_idle_conns_per_host](https://golang.org/pkg/net/http/#Transport)
[max_conns_per_host](https://golang.org/pkg/net/http/#Transport)
[idle_conn_timeout](https://golang.org/pkg/net/http/#Transport)

Will read up on them. I can override these settings as part of the "advanced configs"?

**Comment by atoulme** [comment]
yes, here is how:
```
exporters:
  splunk_hec/foo:
    ...
    idle_conn_timeout: 10s
```

I have opened a PR to make default 10s instead of 30s.

**Comment by matthewmodestino** [comment]
amazing, will try with a customer.

**Comment by Dylan-M** [comment]
I don't see these documented anywhere outside of this issue and the PRs. Was that intentional?
