### ISSUE TITLE
Receive logs in normal JSON or plain text from Kafka.

### ISSUE THREAD

**Issue by h0cheung** [open-telemetry/opentelemetry-collector-contrib#20734]
### Component(s)

receiver/kafka

### Is your feature request related to a problem? Please describe.

Some tools and cloud services may send logs to Kafka in JSON format or even as plain text. We don't have a way to receive them yet. The `raw` unmarshaler can only receive them as bytes, and we can't even find any component to decode them into strings. Also, it doesn't add `ObservedTime` to the logs, which should be added.

### Describe the solution you'd like

We should add a text unmarshaler to decode the logs from Kafka messages into strings, and add `ObservedTime` to them. For compatibility, encodings rather than `UTF-8`, such as `GBK`, `BIG5`, `SHIFT_JIS`, etc. should be supported.

**Comment by atoulme** [comment]
That sounds like a good enhancement to me (I implemented raw support, maybe raw should move from byte array to string).

**Comment by crobert-1** [comment]
It looks like this was actually resolved by #24028, I'll mark it as such.
