### ISSUE TITLE
[processor/cumulativetodelta] make first point drop configurable

### ISSUE THREAD

**Issue by seankhliao** [open-telemetry/opentelemetry-collector-contrib#20770]
### Component(s)

processor/cumulativetodelta

### Is your feature request related to a problem? Please describe.

PR #18224 unconditionally drops the first first point in converting a metric from cumulative to delta temporality, using the initial point to establish a baseline for future deltas.
Somewhat unsurprisingly, we have received feedback that it drops too much data, 
especially if an instance has started due to a scale up (so the initial point contains a significant value).

Thinking about it some more, the need to drop the first point comes from unaligned service instance lifecycles: a "first" point is observed on the start of the application or the collector.

I think the impact of trying to do an out of application cumulative to delta conversion may be reduced by running the collector as a sidecar, tying its lifecycle to that of the application, removing the need to drop first points.

### Describe the solution you'd like

A config field similar to [awsemfexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter)'s
`retain_initial_value_of_delta_metric` setting that controls where the initial data point is dropped.

### Describe alternatives you've considered

give the processor a file to persist state across restarts

**Comment by mx-psi** [comment]
I still haven't gotten around to do open an issue around this but we have found the behavior described on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18224#issuecomment-1412039394 to be helpful for end users across Datadog's OpenMetrics and OpenTelemetry offering. The rule we follow is:

> send the first point iff the startime is set AND the starttime happens after the component started AND the starttime is different from the timestamp

Maybe this is an alternative mode that can also be added to the cumulativetodelta processor.

**Comment by seankhliao** [comment]
> starttime is different from the timestamp

This would still drop the first point right?
In our collector deployments, I'm concerned that the gap between application start and (target allocator watch sync, collector http sd refresh, first scrape delay) is too large of a time interval.

maybe a 3-values config?:

`initial_value: drop|auto|keep` defaulting to auto (the hearistic you described above)?

**Comment by mx-psi** [comment]
> This would still drop the first point right?

The spec defines two cases on the [Resets and gaps](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#resets-and-gaps) section. This would drop the first point for sequences which had "a reset at an unknown start time". For metrics coming from an OpenTelemetry SDK I think we would always know the start time. For metrics coming from other sources this may indeed drop the first point, but it is the best we can do without risking end-users seeing a spike on their dashboards.

**Comment by mx-psi** [comment]
> maybe a 3-values config?:

> initial_value: drop|auto|keep defaulting to auto (the hearistic you described above)?

This makes sense to me :)

**Comment by TylerHelmuth** [comment]
👍

**Comment by seankhliao** [comment]
We've run this for a few months and I initially didn't notice any issues with `auto`.
But on a 0.79 -> 0.82 upgrade, we're seeing points from the prometheus receiver slip through conversion much more frequently.
Looking back at historical data, it seems like an env of ours with less churn has been having this issue for quite some time.

**Comment by mx-psi** [comment]
> slip through conversion much more frequently.

Not sure I understand what 'slip through conversion' is here, are you saying the literal cumulative value is sent instead of the delta? Also, could this be related to #22810?

**Comment by seankhliao** [comment]
yes, the literal value is going through, our expected value is '2', while we see values like 150k being reported

perhaps, though it's infrequent enough that catching an instance of the issue is difficult

**Comment by mx-psi** [comment]
I think it is hard to figure out what is wrong exactly without having the actual OTLP payloads (unless you have any ideas or things to test?). I would be inclined to say this is a bug in Prometheus but without more data it is hard to tell definitively
