### ISSUE TITLE
[processor/transform] Metric conversion functions use datapoint context instead of metric context

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#20773]
### Component(s)

processor/transform

### Describe the issue you're reporting

The function `convert_gauge_to_sum`, `convert_sum_to_gauge`, `convert_summary_sum_val_to_sum` and `convert_summary_count_val_to_sum` all are using the `datapoint` context, but I'm not sure I understand why. 

They all operate on the top-level "metric", so I think they should be using the `metric` context, since they should each run only once for each metric, and not once for each datapoint.

It seems like this was just retaining the old behavior before contexts were introduced, but I think these functions are actually better suited on the `metric` context.

**Comment by TylerHelmuth** [comment]
At the time of their creation, which was during transformprocessor/OTTL infancy, we didn't have the concept of the metrics context, we only had spans, datapoints, and log records. You are correct that these are better suited for the metrics context.

**Comment by BinaryFissionGames** [comment]
That makes sense. Are we OK with changing these to be on the metrics context (with a feature flag, since it would be a breaking change)?

I'd be willing to take that on, if you think so.

**Comment by TylerHelmuth** [comment]
As long as we follow the feature gate deprecation process go for it.

**Comment by BinaryFissionGames** [comment]
Got it, thanks for the heads up on that.

**Comment by evan-bradley** [comment]
The plumbing to handle this was added in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24446. `convert_summary_sum_val_to_sum` and `convert_summary_count_val_to_sum` will likely be deprecated sometime after https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22853 is closed, but I think `convert_gauge_to_sum` and `convert_sum_to_gauge` could be updated to take advantage of this.

**Comment by evan-bradley** [comment]
@BinaryFissionGames are you still interested in working on this? It should be ready for implementation.
