### ISSUE TITLE
[pkg/stanza] Data lost in specified state

### ISSUE THREAD

**Issue by maokitty** [open-telemetry/opentelemetry-collector-contrib#20851]
### Component(s)

pkg/stanza, receiver/filelog

## Description
If two files have the same fingerprint and the fingerprint size is smaller than config , if only one file keep append data and stop append to the other one.  the content of the other one will be lost
## Steps to Reproduce
```
func TestDataLoss(t *testing.T) {
	t.Parallel()
	tempDir := t.TempDir()
	cfg := NewConfig().includeDir(tempDir)
	cfg.FingerprintSize = 18
	cfg.StartAt = "beginning"
	operator, emitCalls := buildTestManager(t, cfg)
	operator.persister = testutil.NewMockPersister("test")

	// Both of they will be include
	file1 := openTempWithPattern(t, tempDir, "*.log1")
	file2 := openTempWithPattern(t, tempDir, "*.log2")

	// Two same fingerprint file , and smaller than  config size
	content := "aaaaaaaaaaa"
	writeString(t, file1, content+"\n")
	writeString(t, file2, content+"\n")
	operator.poll(context.Background())
	// one file will be exclude, ingest only one content
	waitForToken(t, emitCalls, []byte(content))
	expectNoTokens(t, emitCalls)
	operator.wg.Wait()

	// keep append data to file1
	newContent1 := "dddddddd"
	writeString(t, file1, newContent1+"\n")
	operator.poll(context.Background())

	// file1 and file2  has different fingerprint
	waitForTokens(t,emitCalls,[][]byte{[]byte(newContent1),[]byte(content)})

}
```
## Expected Result
no error
## Actual Result
the output of emitcalls is   newContent1 only or empty

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by maokitty** [comment]
ping ~ make sure it is still open
As I have other things to focus on these days, I will do a pr in the future if it still exists, and any other commits are welcome

**Comment by djaglowski** [comment]
Thanks @maokitty. This is still on my radar. I'm gradually making the fileconsumer package more testable so we can very precisely define expected behaviors in these nuanced cases.

**Comment by djaglowski** [comment]
I've updated the test and added it in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31171. This appears to no longer be a problem after the past year's refactoring.

@maokitty, thanks for your patience on this. If you care to validate the test, please take a look.
