### ISSUE TITLE
flaky test: TestTimeoutWhenAggregationKeepHappen

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#20877]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4676595428

```
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/transformer/noop	0.023s
--- FAIL: TestTimeoutWhenAggregationKeepHappen (0.10s)
    recombine_test.go:507: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/stanza/operator/transformer/recombine/recombine_test.go:507
        	Error:      	Not equal: 
        	            	expected: "startnext"
        	            	actual  : "startnextnext"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-startnext
        	            	+startnextnext
        	Test:       	TestTimeoutWhenAggregationKeepHappen
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/transformer/recombine	0.139s
```

**Comment by djaglowski** [comment]
@yutingcaicyt, do you mind taking a look at this? It appears to be related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20742

**Comment by TylerHelmuth** [comment]
Another occurrence here: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4680950414/jobs/8292960563?pr=20754

**Comment by TylerHelmuth** [comment]
Another: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4680950414/jobs/8293618768?pr=20754

**Comment by yutingcaicyt** [comment]
> [pkg/stanza] Skip flaky test #20880

Sorry for making this mistake, I will fix it

**Comment by djaglowski** [comment]
Resolved by #20877

**Comment by dmitryax** [comment]
Another case https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4745947060/jobs/8429056047?pr=20426

**Comment by djaglowski** [comment]
@yutingcaicyt, do you mind taking another look at this one?

**Comment by yutingcaicyt** [comment]
> @yutingcaicyt, do you mind taking another look at this one?
Yeah, I've created a pr #20899

**Comment by djaglowski** [comment]
Unforutnately, this test failed here again: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5177697361/jobs/9328121525#step:6:749

**Comment by djaglowski** [comment]
Here again: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5535880476/jobs/10102789011#step:6:348
