### ISSUE TITLE
[connector/spanmetrics] Allow create histogram for spans with specific attribute

### ISSUE THREAD

**Issue by weyert** [open-telemetry/opentelemetry-collector-contrib#20892]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

I am having a web-application that generates spans and I would like to use the span duration to create a histogram metric that resembles the `http.server.duration` from the http semantic convention

For example recently Next.js added instrumentation using OpenTelemetry and it creates spans (see image below) which resemble the http request. As the span includes useful information as the route name which difficult to get outside of Next.js world. I wanted to use `spanmetrics` to create the http server duration histogram for my Next.js application. The span would have an attribute like `next.span_type=handleRequest` and from all its spans I would like to change into a histogram.

### Describe the solution you'd like

Allow to create dedicated metrics for a select set of spans, e.g. spans that meet specific criteria

### Describe alternatives you've considered

None

**Comment by fatsheep9146** [comment]
Could `dimensions ` of the configuration solve your problem?
```
connectors:
  spanmetrics:
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code
```

**Comment by kovrus** [comment]
> Allow to create dedicated metrics for a select set of spans, e.g. spans that meet specific criteria

You should be able to use the `filterprocessor` before the `spanmetrics` to achieve that. We probably won't add span filtering capabilities to the `spanmetrics` connector.
