### ISSUE TITLE
REQUEST: Add @JaredTan95 as triager

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-collector-contrib#20897]
### Describe the issue you're reporting

Hi, 
Currently, I am the code owner of `Skywalking Receiver` and `ElasticSearch Exporter`, and  I also contributed a lot of features to other `processors`.

I am also currently a member of the OTEL organization and I love to be involved and help the community grow positively.
So, I would like to request to become a `Triager` now.

My Github account: @JaredTan95
My PRs: https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3AJaredTan95+is%3Aclosed

@atoulme thx for your guidelines~

**Comment by TylerHelmuth** [comment]
I support!

**Comment by jpkrohling** [comment]
I support.

**Comment by fatsheep9146** [comment]
I support

**Comment by atoulme** [comment]
I support!

**Comment by codeboten** [comment]
👍🏻

**Comment by atoulme** [comment]
@JaredTan95 please open a PR adding yourself as triager in README.md and ask for maintainers to review and merge. They will add you to the right github team as well.
