### ISSUE TITLE
Consider adding requirement to use metadata.yaml in new components

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#20908]
Do we want to require that the skeleton PR have a `metadata.yaml` and generated code? If so should we include this guidance in the [contributing guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component)?

_Originally posted by @pmcollins in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20891#discussion_r1167041519_

**Comment by mx-psi** [comment]
I think before requiring this we need to have documentation on what the fields are, filed #21800 for this
