### ISSUE TITLE
Add VM memory utilization metric

### ISSUE THREAD

**Issue by padraicbc** [open-telemetry/opentelemetry-collector-contrib#20917]
### Component(s)

vcenterreceiver

### Is your feature request related to a problem? Please describe.

VM memory usage is recorded but utilization is not. It is a very relevant metric to monitor so an important addition. 

### Describe the solution you'd like

Add logic to  `RecordVcenterVMMemoryUtilizationDataPoint` in `VMUsages`  alongside `RecordVcenterVMMemoryUsageDataPoint`. All the necessary fields are available.

**Comment by atoulme** [comment]
Which component is this for?

**Comment by padraicbc** [comment]
> Which component is this for?

The vcenter receiver.

**Comment by djaglowski** [comment]
Completed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20918
