### ISSUE TITLE
New component: Metrics DeDuplicator processor

### ISSUE THREAD

**Issue by nicolastakashi** [open-telemetry/opentelemetry-collector-contrib#20921]
### The purpose and use-cases of the new component

Engineers may want to set up a highly available environment to collect metrics by having pairs of data sources collecting the same set of targets and then sending the samples to the OpenTelemetry collector to enrich and export the data to the metrics backend (e.g Thanos).

Although many of the metrics backends provide support for metrics deduplication on the query runtime, it requires customers to store duplicate samples which requires more computing resources such as storage or it may increase their bills if using a vendor backend (depending on the vendor pricing strategy). With that in mind would be amazing if the OpenTelemtry Collector provided some deduplication processor.

This processor may work based on some existing implementation like Thanos, Grafana Mimir, Cortex, or any other valuable implementation.

### Example configuration for the component

```yaml
metricsdeduplicator:
  replica_label: 
    - prometheus_replica
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

**Comment by nicolastakashi** [comment]
There's one issue #17874 asking a processor to deduplicate traces, maybe we can join efforts, don't know.

**Comment by atoulme** [comment]
Would you please expand on the use case? I am not sure you can safely in parallel scrape a Prometheus metrics endpoint since it is stateful. The approach I have heard folks tend to take is to use a leader election mechanism to pick a specific collector to perform collection, with a failover.

**Comment by nicolastakashi** [comment]
Indeed most of the current implementations are leveraging only one instance to deduplicate metrics, this could be an initial state, like ensuring this exporter is not running in multiple replicas.

But exploring feature implementations we may have a similar strategy as the existing one to load balancer traces based on the trace id, we may discuss the idea of how to load balance metrics between collectors.


This processor is more suitable to run on central collectors which are receiving metrics from other agents, so it's easier to ensure only one replica running or feature lb implementation.

**Comment by nicolastakashi** [comment]
I still think it's relevant

**Comment by nicolastakashi** [comment]
Bringing this subject back!
I've been testing some implementation available in this repo: https://github.com/nicolastakashi/metricsdedupprocessor

I'd like to get feedback around that
