### ISSUE TITLE
Support reporting ExtraMetrics in prometheus client internally used by PrometheusReceiver in otel collector

### ISSUE THREAD

**Issue by premendrasingh** [open-telemetry/opentelemetry-collector-contrib#21040]
### Component(s)

receiver/prometheus

### Is your feature request related to a problem? Please describe.

We use prometheus receiver to scrape metrics, however many times the prometheus endpoints return huge number of time series. We use body_size_limit to drop data but there is no way to report for which endpoints the data has been dropped.

Prometheus client has a featureFlag options.ExtraMetrics which reports content size metric ([scrape_body_size_bytes](https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L1770)) for successful scrapes and -1 for dropped data. This metric will help us collect data and setup alert for dropped data. However the prometheus receiver does not have a way to enable this feature flag. Please suggest a solution to enable this metric - [scrape_body_size_bytes](https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L1770)

Feature flag used for collecting metric
https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L1798-L1808

### Describe the solution you'd like

New scrape manager is created in PrometheusReceiver [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/metrics_receiver.go#L284), it can be enhanced to pass a flag to enable ExtraMetrics in [Prometheus client](https://github.com/prometheus/prometheus/blob/7309ac272195cb856b879306d6a27af7641d3346/scrape/manager.go#L125-L127).

For example something like
`r.scrapeManager = scrape.NewManager(&scrape.Options{PassMetadataInContext:true, ExtraMetrics:r.cfg.ReportExtraMetrics}, logger, store)
`

**Comment by JaredTan95** [comment]
@premendrasingh  make sense, and would you be interested in contributing to this `flag`?

**Comment by premendrasingh** [comment]
Thanks @JaredTan95 I will submit a PR for this change.

**Comment by premendrasingh** [comment]
@JaredTan95 Please help review the PR #21064  Thanks

**Comment by premendrasingh** [comment]
@JaredTan95 Please help review PR and let me know whether any more changes are needed. Thanks.
