### ISSUE TITLE
Apache Spark Receiver

### ISSUE THREAD

**Issue by Caleb-Hurshman** [open-telemetry/opentelemetry-collector-contrib#21046]
### The purpose and use-cases of the new component

The purpose of this component is to allow monitoring of Apache Spark applications and jobs through the collection of performance metrics like memory utilization, CPU utilization, executor duration, etc. gathered through the exposed Spark REST API.

### Example configuration for the component

The configuration parameters are all optional:

- endpoint (default: localhost:4040)

```yaml
receivers:
  spark:
    endpoint: localhost:4040
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

No sponsor yet

**Comment by atoulme** [comment]
There is some ongoing work with the databricks receiver that may intersect with this proposal. @pmcollins fyi

**Comment by djaglowski** [comment]
> There is some ongoing work with the databricks receiver that may intersect with this proposal.

@atoulme, can you clarify what you're referring to here?

I'm willing to sponsor this unless there is some reason it would be unified with another component.

**Comment by atoulme** [comment]
See this issue for context: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18724

**Comment by djaglowski** [comment]
Thanks @atoulme. I agree there's some overlap.

I think work can proceed on this one, though we should look for ways to make some portion of this receiver's codebase reuseable by the databricks receiver.

**Comment by djaglowski** [comment]
Closed by #22163
