### ISSUE TITLE
[cmd/opampsupervisor] Handle OpAMP connection settings messages

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#21043]
### Is your feature request related to a problem? Please describe.

[Per the OpAMP specification](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#connection-settings-management), OpAMP servers should be able to configure network connection configurations for connections that agents make. Since it is acting on behalf of the Collector as an OpAMP agent, the Supervisor should support these messages.

### Describe the solution you'd like

Handle the [ConnectionSettingsOffers](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#connectionsettingsoffers-message), in particular fields with the following message types:
1. [OpAMPConnectionSettings](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#opampconnectionsettings)
2. [TelemetryConnectionSettings](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#telemetryconnectionsettings)

### Additional context

An issue for handling [OtherConnectionSettings](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#otherconnectionsettings) messages will follow.

**Comment by srikanthccv** [comment]
@evan-bradley please assign this to me. I started working on this.

**Comment by evan-bradley** [comment]
Closing as resolved via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30237
