### ISSUE TITLE
To add processing for the event field

### ISSUE THREAD

**Issue by shaohuading** [open-telemetry/opentelemetry-collector-contrib#21069]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

Missing the processing of the Events field. Hope to add it.
![image](https://user-images.githubusercontent.com/88264066/233018219-c9d23262-b83a-474b-81f0-d65297bdec60.png)

### Describe the solution you'd like

Add processing for the event field.

**Comment by JaredTan95** [comment]
Do you mean event attributes? like fixed in this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21063?

**Comment by JaredTan95** [comment]
@shaohuading any update?
