### ISSUE TITLE
[cmd/opampsupervisor] Handle restart command

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#21077]
### Is your feature request related to a problem? Please describe.

The OpAMP specification defines a restart command that can be issued by servers to agents. The Supervisor can be handled either by restarting itself upon receiving these requests, or by restarting the Collector.

### Describe the solution you'd like

Document the intended approach in the Supervisor design document, and implement that approach in the Supervisor. We will likely just want to have the Supervisor restart the Collector without processing config updates upon receiving this message.

**Comment by srikanthccv** [comment]
>Document the intended approach in the Supervisor design document, and implement that approach in the Supervisor. We will likely just want to have the Supervisor restart the Collector without processing config updates upon receiving this message.

I think it is implicitly assumed that the restart command will be applied to the agent collector like any other field which is part of `ServerToAgent` message. @tigrannajaryan is that a correct assumption to make? Or are there any settings that apply to Supervisors?

**Comment by tigrannajaryan** [comment]
> > Document the intended approach in the Supervisor design document, and implement that approach in the Supervisor. We will likely just want to have the Supervisor restart the Collector without processing config updates upon receiving this message.
> 
> I think it is implicitly assumed that the restart command will be applied to the agent collector like any other field which is part of `ServerToAgent` message. @tigrannajaryan is that a correct assumption to make? Or are there any settings that apply to Supervisors?

You are right. Restart should apply to the Agent. 

Conceptually the Supervisor exists merely for the purpose of easier/more robust implementation of the commands targeted to the Agent. For example, if Agent restarted itself, it may not be able to start and the OpAMP connection will be forever lost. The presence of highly reliable and always running Supervisor avoids this sort of problems.
