### ISSUE TITLE
[cmd/opampsupervisor] Persist Collector instance ID

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#21073]
### Is your feature request related to a problem? Please describe.

The Supervisor should create Collector instance ID to set in the Collector's resource attributes, and should also persist this ID so that it stays the same across Supervisor restarts. For more, see the [design document](https://docs.google.com/document/d/1KtH5atZQUs9Achbce6LiOaJxLbksNJenvgvyKLsJrkc/edit#heading=h.8szgxmjard0e).

### Describe the solution you'd like

Allow configuring where the Supervisor persists information according to the config schema defined in the design document and store the instance ID in this location.

**Comment by BinaryFissionGames** [comment]
I'll work on adding this
