### ISSUE TITLE
Alternative Docker registry

### ISSUE THREAD

**Issue by achetronic** [open-telemetry/opentelemetry-collector-contrib#21070]
### Describe the issue you're reporting

Hello there,

Have you thought about (or may be already exists) pushing your Docker images to an alternative repository, like ghcr, or quay?

**Comment by atoulme** [comment]
I don't think that came up before. Do you have a specific requirement that the current repository cannot satisfy?

**Comment by achetronic** [comment]
Hello @atoulme Thanks for your response

One of the main problems I detect with Docker Hub is the rate limit. When a huge company, with autoscaler configured, and OTEL in daemonset gets a lot of traffic, it's impossible to doenload the image in some moments. We fixed it of course mirroring automatically the image, but IMHO it would be easy to have several official repositories for OTEL :)
