### ISSUE TITLE
flaky test: TestSnmpReceiverIntegration

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#21086]
### Component(s)

receiver/snmp

### Describe the issue you're reporting

Seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4752971094/jobs/8444004878?pr=21085

```
--- FAIL: TestSnmpReceiverIntegration (39.14s)
    --- FAIL: TestSnmpReceiverIntegration/Integration_test_with_v2c_configuration (16.02s)
        integration_test.go:91: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/snmpreceiver/integration_test.go:91
            	Error:      	Received unexpected error:
            	            	number of resources doesn't match expected: 4, actual: 0
            	Test:       	TestSnmpReceiverIntegration/Integration_test_with_v2c_configuration
    --- FAIL: TestSnmpReceiverIntegration/Integration_test_with_v3_configuration (11.02s)
        integration_test.go:91: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/snmpreceiver/integration_test.go:91
            	Error:      	Received unexpected error:
            	            	number of resources doesn't match expected: 4, actual: 0
            	Test:       	TestSnmpReceiverIntegration/Integration_test_with_v3_configuration
FAIL
```

**Comment by TylerHelmuth** [comment]
Had 3 occurrences here: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4749588917/jobs/8450973140?pr=21063.  Might be time to skip it temporarily.

**Comment by djaglowski** [comment]
@StefanKurek, any idea what could be going wrong here?

**Comment by StefanKurek** [comment]
@djaglowski not quite sure right off the bat. Also not quite sure "flaky" is the accurate word here. It looks like the test started failing at some point in time. From that point on CI consistently failed until this test was turned off.

**Comment by StefanKurek** [comment]
Alright, I'll be looking at this a little deeper sometime within the next week.
