### ISSUE TITLE
[receiver/dockerstats] Optionally Include `container.image.id` and `container.command` resource attributes

### ISSUE THREAD

**Issue by sigilioso** [open-telemetry/opentelemetry-collector-contrib#21092]
### Component(s)

receiver/dockerstats

### Is your feature request related to a problem? Please describe.

I would like to include two additional resource attributes: `container.image.id` and `container.command` as those can be handy while container images are being changed (during development).

### Describe the solution you'd like

I would like the receiver to support both resource attributes. Those could be disabled by default and enabled by configuration.

- `container.image.id`: would contain the value `container.Image` from docker  inspect API. During development is common to keep the image name. Eg: `container-dev` while introducing changes. Therefore, the currently reported `container.image` may not be enough.

- `container.cmd`: would contain the value from `container.Config.Cmd` (the command displayed when doing `docker ps`).

### Additional context

This is part of a NewRelic initiative to adopt the dockerstats receiver as a source of instrumentation. We are ready to work on it if we agree on optionally including the new resource attributes.

**Comment by atoulme** [comment]
As long as they are disabled by default, I think we're good here. I can assign the issue to you if you'd like.

**Comment by jamesmoessis** [comment]
This looks reasonable to add @sigilioso, happy to review.

**Comment by sigilioso** [comment]
#21185 and https://github.com/open-telemetry/semantic-conventions/pull/39 are addressing this.

**Comment by sigilioso** [comment]
I'm closing this since the new attributes are already included.
