### ISSUE TITLE
Provide better tooling for creating push/server receivers

### ISSUE THREAD

**Issue by hughesjj** [open-telemetry/opentelemetry-collector-contrib#21095]
### Component(s)

cmd/mdatagen, receiver/carbon, receiver/statsd

### Is your feature request related to a problem? Please describe.

So, I've recently went ahead and implemented my first otel-contrib-based "pushed-based"/listening server receiver.  In the process of such, I've realized that things such as `transport` and `reporter` as defined in [`receiver/statsdreceiver`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/carbonreceiver) and [`receiver/carbonreceiver`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/carbonreceiver) are a bit boilerplate/copypasta.

I see we've [recently](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19772) started paying more attention to non scraping receivers in `mdatagen`, and figured this topic would be the logical next iteration on such.

### Describe the solution you'd like

I'd like to have some common scaffolding or consistently defined interfaces such as we have for scraping receivers.  [`confighttp.HTTPClientSettings`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/confighttp.go#L265) has a pretty slick `ToServer` method, but there's still a fair amount of boilerplate we might be able to abstract away.

Is there a SIG/Working group I should join for this? As of now, I'd assume the [collector SIG](https://github.com/open-telemetry/community#implementation-sigs)

(Feel free to ping me on the CNCF otel slack for any adhoc brainstorming etc)

### Additional context

I've checked for [existing issues](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?page=5&q=is%3Aissue+is%3Aopen+receiver+server+NOT+Bump) but didn't see anything relevant for this request, but I admittedly haven't scraped other repos.  I figure this is the right place to cut an issue given `mdatagen` is also vendored from `-contrib`

**Comment by atoulme** [comment]
Do you have a specific enhancement in mind? The collector SIG is the right place to discuss, yes.
