### ISSUE TITLE
[receiver/dockerstats] Container memory metrics calculation 

### ISSUE THREAD

**Issue by gsanchezgavier** [open-telemetry/opentelemetry-collector-contrib#21097]
### Component(s)

receiver/dockerstats

### Is your feature request related to a problem? Please describe.

Hi 👋 , I found that two of the memory metrics, are calculated from metrics stats that are only present in cgroups v1, and also the calculation doesn't take into account come use-case referenced below.

`container.memory.usage.total`: Currently this metric is [calculated](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/74836e91bd0490fa489a33b98123806cbb34ae8a/receiver/dockerstatsreceiver/receiver.go#L160) based on a cgroup v1 metric [total_cache](https://github.com/moby/moby/blob/7103efac9d737e8b202126e8c8e2227805e70771/daemon/stats_unix.go#L105) so when running on [cgroups v2](https://github.com/moby/moby/blob/7103efac9d737e8b202126e8c8e2227805e70771/daemon/stats_unix.go#L195) [this](https://github.com/moby/moby/issues/40727#issue-584876576) computation isn’t performed.

<details>
    <summary>Examples</summary>
Running this example([details](https://github.com/moby/moby/issues/40727)):

```sh
docker run --shm-size=256MB --memory=256MB -it alpine sh -c "
        dd if=/dev/urandom of=/dev/shm/file bs=32M
        ls -lh /dev/shm
        read
"
```

`curl --unix-socket /var/run/docker.sock http://localhost/containers/<ID>/stats?stream=0 | jq`
<details>
    <summary>cgroups v1 </summary>

```json
{
  "read": "2023-04-21T06:35:58.69761055Z",
  "preread": "2023-04-21T06:35:57.694393101Z",
  "pids_stats": {
    "current": 1
  },
  "blkio_stats": {
    "io_service_bytes_recursive": [
      {
        "major": 8,
        "minor": 0,
        "op": "Read",
        "value": 2060288
      },
      {
        "major": 8,
        "minor": 0,
        "op": "Write",
        "value": 0
      },
      {
        "major": 8,
        "minor": 0,
        "op": "Sync",
        "value": 2060288
      },
      {
        "major": 8,
        "minor": 0,
        "op": "Async",
        "value": 0
      },
      {
        "major": 8,
        "minor": 0,
        "op": "Total",
        "value": 2060288
      }
    ],
    "io_serviced_recursive": [
      {
        "major": 8,
        "minor": 0,
        "op": "Read",
        "value": 31
      },
      {
        "major": 8,
        "minor": 0,
        "op": "Write",
        "value": 0
      },
      {
        "major": 8,
        "minor": 0,
        "op": "Sync",
        "value": 31
      },
      {
        "major": 8,
        "minor": 0,
        "op": "Async",
        "value": 0
      },
      {
        "major": 8,
        "minor": 0,
        "op": "Total",
        "value": 31
      }
    ],
    "io_queue_recursive": [],
    "io_service_time_recursive": [],
    "io_wait_time_recursive": [],
    "io_merged_recursive": [],
    "io_time_recursive": [],
    "sectors_recursive": []
  },
  "num_procs": 0,
  "storage_stats": {},
  "cpu_stats": {
    "cpu_usage": {
      "total_usage": 1017068737,
      "percpu_usage": [
        22394613,
        994674124
      ],
      "usage_in_kernelmode": 960000000,
      "usage_in_usermode": 30000000
    },
    "system_cpu_usage": 246387850000000,
    "online_cpus": 2,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "precpu_stats": {
    "cpu_usage": {
      "total_usage": 1017068737,
      "percpu_usage": [
        22394613,
        994674124
      ],
      "usage_in_kernelmode": 960000000,
      "usage_in_usermode": 30000000
    },
    "system_cpu_usage": 246385850000000,
    "online_cpus": 2,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "memory_stats": {
    "usage": 235646976,
    "max_usage": 268435456,
    "stats": {
      "active_anon": 65536,
      "active_file": 135168,
      "cache": 234086400,
      "dirty": 0,
      "hierarchical_memory_limit": 268435456,
      "hierarchical_memsw_limit": 0,
      "inactive_anon": 233316352,
      "inactive_file": 843776,
      "mapped_file": 405504,
      "pgfault": 12012,
      "pgmajfault": 0,
      "pgpgin": 68937,
      "pgpgout": 11719,
      "rss": 40960,
      "rss_huge": 0,
      "total_active_anon": 65536,
      "total_active_file": 135168,
      "total_cache": 234086400,
      "total_dirty": 0,
      "total_inactive_anon": 233316352,
      "total_inactive_file": 843776,
      "total_mapped_file": 405504,
      "total_pgfault": 12012,
      "total_pgmajfault": 0,
      "total_pgpgin": 68937,
      "total_pgpgout": 11719,
      "total_rss": 40960,
      "total_rss_huge": 0,
      "total_unevictable": 0,
      "total_writeback": 0,
      "unevictable": 0,
      "writeback": 0
    },
    "failcnt": 235,
    "limit": 268435456
  },
  "name": "/intelligent_agnesi",
  "id": "6e9ac45f5e60cc665c2a5ec7a48f1c5ab9a5eb3da753f3925bf3487f8b316870",
  "networks": {
    "eth0": {
      "rx_bytes": 1186,
      "rx_packets": 15,
      "rx_errors": 0,
      "rx_dropped": 0,
      "tx_bytes": 0,
      "tx_packets": 0,
      "tx_errors": 0,
      "tx_dropped": 0
    }
  }
}
```
</details>
<details>
    <summary>cgroups v2 </summary>

```json
{
  "read": "2023-04-21T06:35:12.199820698Z",
  "preread": "2023-04-21T06:35:11.19562925Z",
  "pids_stats": {
    "current": 1,
    "limit": 4694
  },
  "blkio_stats": {
    "io_service_bytes_recursive": [
      {
        "major": 8,
        "minor": 0,
        "op": "read",
        "value": 94208
      },
      {
        "major": 8,
        "minor": 0,
        "op": "write",
        "value": 0
      }
    ],
    "io_serviced_recursive": null,
    "io_queue_recursive": null,
    "io_service_time_recursive": null,
    "io_wait_time_recursive": null,
    "io_merged_recursive": null,
    "io_time_recursive": null,
    "sectors_recursive": null
  },
  "num_procs": 0,
  "storage_stats": {},
  "cpu_stats": {
    "cpu_usage": {
      "total_usage": 866815000,
      "usage_in_kernelmode": 850527000,
      "usage_in_usermode": 16287000
    },
    "system_cpu_usage": 437157240000000,
    "online_cpus": 2,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "precpu_stats": {
    "cpu_usage": {
      "total_usage": 866815000,
      "usage_in_kernelmode": 850527000,
      "usage_in_usermode": 16287000
    },
    "system_cpu_usage": 437155230000000,
    "online_cpus": 2,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "memory_stats": {
    "usage": 234647552,
    "stats": {
      "active_anon": 4096,
      "active_file": 0,
      "anon": 61440,
      "anon_thp": 0,
      "file": 233844736,
      "file_dirty": 0,
      "file_mapped": 0,
      "file_writeback": 0,
      "inactive_anon": 233902080,
      "inactive_file": 0,
      "kernel_stack": 16384,
      "pgactivate": 7,
      "pgdeactivate": 6,
      "pgfault": 9456,
      "pglazyfree": 0,
      "pglazyfreed": 0,
      "pgmajfault": 2,
      "pgrefill": 6,
      "pgscan": 23,
      "pgsteal": 23,
      "shmem": 233844736,
      "slab": 662048,
      "slab_reclaimable": 591888,
      "slab_unreclaimable": 70160,
      "sock": 0,
      "thp_collapse_alloc": 0,
      "thp_fault_alloc": 0,
      "unevictable": 0,
      "workingset_activate": 0,
      "workingset_nodereclaim": 0,
      "workingset_refault": 0
    },
    "failcnt": 1,
    "limit": 268435456
  },
  "name": "/serene_goldberg",
  "id": "839449a81100d22618a8a5f31b4363b3556e2a93ffc197dd36c5e1013a534fce",
  "networks": {
    "eth0": {
      "rx_bytes": 1226,
      "rx_packets": 15,
      "rx_errors": 0,
      "rx_dropped": 0,
      "tx_bytes": 0,
      "tx_packets": 0,
      "tx_errors": 0,
      "tx_dropped": 0
    }
  }
}
```

</details>
</details>
</details>

`container.memory.percent`: Similar to the container.memory.usage.total this metric is calculated by using [cache](https://github.com/moby/moby/blob/7103efac9d737e8b202126e8c8e2227805e70771/daemon/stats_unix.go#L88) stats from cgroupsv1 not compatible with [cgroups v2](https://github.com/moby/moby/blob/7103efac9d737e8b202126e8c8e2227805e70771/daemon/stats_unix.go#L195).

### Describe the solution you'd like

* `container.memory.usage.total`: The proposal is to support both versions of cgroups and use the same method of the [docker cli](https://github.com/docker/cli/blob/d4f2609ce8fe63dcfca862677a50fb6c184e072f/cli/command/container/stats_helpers.go#L227) is using which represents better usage for some use-cases according to [this](https://github.com/moby/moby/issues/40727) discussion. 

* `container.memory.percent`: Similar proposal to use the same method of the [docker cli](https://github.com/docker/cli/blob/d4f2609ce8fe63dcfca862677a50fb6c184e072f/cli/command/container/stats_helpers.go#L251), based on the total usage previously calculated.

* Add to the existing metric documentation description(metadata.yaml) a note if the metric is only present in a particular version of cgroups.

I would also like to add two new metrics present in the cgroups v2 memory stats:

- `container.memory.file`

- `container.memory.anon`

### Additional context

This is part of a NewRelic initiative to adopt the `docker_stats` receiver as a source of instrumentation. I or one of my team members can work on it after discussed/approved :)

Here are some links to the data sources I have used to check the data:

- [Docker API](https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerStats):

  - cg1 docker api [available metrics](https://github.com/moby/moby/blob/7103efac9d737e8b202126e8c8e2227805e70771/daemon/stats_unix.go#L86)
    -  cg1 containerd api [available metrics](https://github.com/containerd/cgroups/blob/main/cgroup1/stats/metrics.pb.go#L450)

  - cg2 docker api [available metrics](https://github.com/moby/moby/blob/7103efac9d737e8b202126e8c8e2227805e70771/daemon/stats_unix.go#L195)
    - cg2 containerd api [available metrics](https://github.com/containerd/cgroups/blob/main/cgroup2/stats/metrics.pb.go)

Docker cli [metrics calculation](https://github.com/docker/cli/blob/d4f2609ce8fe63dcfca862677a50fb6c184e072f/cli/command/container/stats_helpers.go#L105)

Kernel [cgroups v1 metrics doc](https://docs.kernel.org/admin-guide/cgroup-v1/memory.html)

Kernel [cgroups v2 metrics doc](https://docs.kernel.org/admin-guide/cgroup-v2.html#memory-interface-files)

**Comment by gsanchezgavier** [comment]
I just noticed that the same docker cli approach was being followed but the code used became outdated
[Old Docker CLI calculation](https://github.com/docker/cli/blob/dbd96badb6959c2b7070664aecbcf0f7c299c538/cli/command/container/stats_helpers.go#L228).
[New Docker CLI calculation](https://github.com/docker/cli/blob/master/cli/command/container/stats_helpers.go#L239) from version > 19.03.

**Comment by jamesmoessis** [comment]
Thanks for raising this @gsanchezgavier. Those memory calculations should definitely support cgroups v2, and I would probably call what you've discovered a bug. Happy to review a PR to fix that.

> I would also like to add two new metrics present in the cgroups v2 memory stats:

Please raise a separate PR for this 😄

**Comment by gsanchezgavier** [comment]
Thanks for the reviews and merging this!

There is a Pending PR I need to work on regarding these items left:

> * Add to the existing metric documentation description(metadata.yaml) a note if the metric is only present in a particular version of cgroups.
>
>I would also like to add two new metrics present in the cgroups v2 memory stats:
>- `container.memory.file`
>- `container.memory.anon`

**Comment by gsanchezgavier** [comment]
I'm closing this since all points of this issue have been addressed, thanks!
