### ISSUE TITLE
[receiver/splunkhecreceiver] [exporter/splunkhecexporter] Add unit tests validating tls validation on splunkhecreceiver and splunkhecexporter

### ISSUE THREAD

**Issue by zpzhuSplunk** [open-telemetry/opentelemetry-collector-contrib#21104]
### Describe the issue you're reporting

Currently, the HEC receiver and exporter do not have sufficient unit tests to verify the tls behavior. See https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/splunkhecreceiver/receiver_test.go and https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/splunkhecexporter/client_test.go

We should add unit tests to the components verifying the following cases:

- Happy path

 - Cert is not signed by CA
 
 - Cert is expired
 - Cert is using outdated TLS version

**Comment by timannguyen** [comment]
ill be taking up this work
