### ISSUE TITLE
[exporter/kafkaexporter] Zipkin JSON encoding support

### ISSUE THREAD

**Issue by yaroliakh** [open-telemetry/opentelemetry-collector-contrib#21102]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

I would like Kafka exporter to have an option of sending traces in Zipkin JSON format.

### Describe the solution you'd like

Following Kafka [marshaler](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a6c7576fed18ad7287fc85504b9a33c665d20a04/exporter/kafkaexporter/marshaler.go#L25) pattern adding Zipkin JSON encoding would be similar to existing Jager and OTLP_JSON encoders.  

### Additional context

We'd like to start using Kafka for Zipkin trances and have this feature upstream. I can work on the implementation if this request finds positive feedback.

**Comment by atoulme** [comment]
You will need the kafka receiver to also support receiving zipkin traces.

**Comment by yaroliakh** [comment]
> You will need the kafka receiver to also support receiving zipkin traces.

In our particular case zipkin traces are received over HTTP, then exported to kafka and transformed by consumers into Zipkin. We'd like to avoid extra transformation outside OTel.

**Comment by MovieStoreGuy** [comment]
I had thought this was done, but I happy to see it added.
