### ISSUE TITLE
[receiver/mongodbatlas] Add mongodb_atlas.cluster.name on metrics resource

### ISSUE THREAD

**Issue by dehaansa** [open-telemetry/opentelemetry-collector-contrib#21154]
### Component(s)

receiver/mongodbatlas

### Is your feature request related to a problem? Please describe.

Cluster Name is a very useful attribute to have when identifying issues using MongoDB Atlas metrics.

### Describe the solution you'd like

As noted in the client in code, the API does not draw the connection for you from Process (mongod/mongos) to Cluster, but the connection can be easily drawn by using the Cluster's MongoURI and the Process's UserAlias.

```
"mongo_uri": "mongodb://host1.mongodb.net:27017,host2.mongodb.net:27017,host3.mongodb.net:27017"

"user_alias": "host1.mongodb.net"
```

### Describe alternatives you've considered

There does not appear to be a way in the Atlas API to connect these objects and appropriately label the metrics emitted without using the mentioned connection.

**Comment by dehaansa** [comment]
I will make this default-disabled, like the `user_alias` addition in #18881

**Comment by atoulme** [comment]
Closing as fixed, thanks!
