### ISSUE TITLE
Offer to move serializers and deserializers used across components of the contrib repo to codecs

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#21152]
### Describe the issue you're reporting

This idea is originally from @MovieStoreGuy discussed during an APAC SIG meeting.

We are seeing a proliferation of encodings in this repository. The Kafka exporter is particularly popular right now with multiple new contributions offering to add support for various encodings.

It might make sense to move all those codecs to a library that is shared across components to reduce the burden of maintaining the same serialization code across multiple components. It would also allow any component to tap into the existing codecs. 

The following codecs can be extracted from the code:
* [ ] open-telemetry/opentelemetry-collector-contrib/pull/21254
* [ ] String
* [ ] Raw
* [ ] Jaeger
* [ ] Zipkin

**Comment by cparkins** [comment]
@atoulme - I've done some preliminary work to move the Azure Resource Logs format into a shared directory for use between Kafka and Event Hubs.  I'll try to get it rebased and create a preliminary PR of my work soon.
