### ISSUE TITLE
Support for Sarama Proxy

### ISSUE THREAD

**Issue by padraicbc** [open-telemetry/opentelemetry-collector-contrib#21158]
### Is your feature request related to a problem? Please describe.

I am running a collector in an environment using a Squid Proxy for external comunication.
This requires enabling a tcp proxy in go-sarama [config](https://github.com/Shopify/sarama/blob/main/config.go#L113) and I don't see any way to currently achieve that.

### Describe the solution you'd like

Checking for `HTTP(S)_PROXY` envs and addding a [proxy.FromURL](FromURL)  to `Net.Proxy` if  any are set.

**Comment by MovieStoreGuy** [comment]
I would personally like to see this as a configurable field in the configuration so that we don't accidentally step on other components that would cause issues.

However, I am open to having PRs open for this.
