### ISSUE TITLE
[receiver/mongodbatlas] Disk Partition Utilization metrics are incorrect

### ISSUE THREAD

**Issue by dehaansa** [open-telemetry/opentelemetry-collector-contrib#21180]
### Component(s)

receiver/mongodbatlas

## Description
Disk Usage (percentage of space used) metrics are being reported under the Disk Utilization (percent of time partition was in use) metric for MongoDB Atlas Disk Partitions. The Disk Utilization metrics are not being collected.

See documentation https://www.mongodb.com/docs/atlas/reference/api/process-disks-measurements/#measurement-values

## Expected Result
Disk Utilization & Disk Usage metrics are both collected correctly.

## Actual Result
Disk Usage metrics are reported as Disk Utilization, and Disk Utilization metrics are not collected.

### Collector version

v0.75.0

### Environment information

-

**Comment by atoulme** [comment]
Closing as fixed, thanks!
