### ISSUE TITLE
[receiver/dockerstats] swap metrics are not being reported

### ISSUE THREAD

**Issue by gsanchezgavier** [open-telemetry/opentelemetry-collector-contrib#21190]
### Component(s)

receiver/dockerstats

### What happened?

Metrics:
* `container.memory.total_swap`
* `container.memory.swap`

Would never be populated since they are not part of the Memory Stats metrics on the Docker API on cgroupsV1 or cgroupsV2. 

I tried to find if they were present at some version of the docker engine without luck. 
Memory stats [doesn't](https://github.com/moby/moby/blob/7103efac9d737e8b202126e8c8e2227805e70771/api/types/stats.go#L68) have defined types for each variable, and the metrics doesn't appear in the API examples for the [minimum supported](https://github.com/moby/moby/blob/7103efac9d737e8b202126e8c8e2227805e70771/docs/api/v1.22.md?plain=1#L890) neither [in the code ](https://github.com/moby/moby/search?q=total_swap).

### Collector version

v0.75.0

### Environment information

The metric is not present in the mock [testdata](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/dockerstatsreceiver/testdata/mock/single_container/stats.json#L114) files either from containers on cgroups v1

### Additional context

I think having those metrics could create confusion so I think they should be removed. 

I checked if was possible to get the swap usage metric from the Docker API but I didn't find it. Looks like the [memory.memsw.*](https://docs.kernel.org/admin-guide/cgroup-v1/memory.html#benefits-and-purpose-of-the-memory-controller) or [memory.swap.*](https://docs.kernel.org/admin-guide/cgroup-v2.html#memory-interface-files) metrics are mapped in the API.

**Comment by gsanchezgavier** [comment]
@jamesmoessis re-pinging just in case you missed the notification. Thanks

**Comment by jamesmoessis** [comment]
Sounds good @gsanchezgavier happy to review a PR

**Comment by carlossscastro** [comment]
Hi @jamesmoessis 

I have submitted a [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21890) to address these issue on behalf of my colleague @gsanchezgavier.

Thanks

**Comment by crobert-1** [comment]
@gsanchezgavier Since #21890 has been merged, can you confirm this issue has been resolved? It would be good to close this issue if it's been fixed.

**Comment by gsanchezgavier** [comment]
Yes, this is resolved,  both metrics were the ones detected. Thanks @carlossscastro !
