### ISSUE TITLE
Scaffold components with mdatagen

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#21200]
### Component(s)

cmd/mdatagen

### Is your feature request related to a problem? Please describe.

I want to reduce the amount of boilerplate that my component requires.

### Describe the solution you'd like

I would like mdatagen to scaffold most of the code of the component for me using the medata available.

**Comment by dmitryax** [comment]
It'd be a nice feature. It'll also help to bring all the boilerplate code to a consistent form across all the components. I'd approach it gradually moving it piece by piece to the generated code.
