### ISSUE TITLE
Checking of Release Timeline

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#21211]
### Component(s)

receiver/file

### Describe the issue you're reporting

Hi,

May I know when is the release date for V0.76.0, please? 
Where can I get the V0.76.0 and beyond Release Date information, please?

Thank you.

Best Regards,
Erica Ooi

**Comment by atoulme** [comment]
The release is ongoing and will be available shortly.

**Comment by ericashi** [comment]
Hi,

May I know if there is an eta for this release (V0.76.0) so that I can plan my development work, please? 

Thank you.

Best Regards,
Erica Ooi

**Comment by djaglowski** [comment]
Hi @ericashi. You can find the release schedule [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#release-schedule).

This release has not gone smoothly. It's being worked on and will be available as soon as possible.

**Comment by ericashi** [comment]
Hi @djaglowski ,

Thanks for the information provided. It is very helpful.

Best regards,
Erica Ooi
