### ISSUE TITLE
Add status metadata to all components

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#21213]
### Describe the issue you're reporting

We now have a way to set status metadata on components to auto-generate portions of the components.
See for example https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21178.

This issue tracks the component list:

* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22800
* [x] connector/servicegraphconnector
* [x] connector/spanmetricsconnector
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22112
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22113
* [x] exporter/awsemfexporter
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22114
* [x] exporter/awss3exporter
* [x] exporter/awsxrayexporter
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22084
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22082
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22081
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21388
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22085
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22089
* [x] exporter/datadogexporter
* [x] exporter/dynatraceexporter
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22088
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22091
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22108
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22090
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22109
* [x] exporter/googlemanagedprometheusexporter
* [x] exporter/influxdbexporter
* [x] exporter/instanaexporter
* [x] exporter/jaegerexporter
* [x] exporter/jaegerthrifthttpexporter
* [x] exporter/kafkaexporter
* [x] exporter/loadbalancingexporter
* [x] exporter/logicmonitorexporter
* [x] exporter/logzioexporter
* [x] exporter/lokiexporter
* [x] exporter/mezmoexporter
* [x] exporter/opencensusexporter
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21386
* [x] exporter/prometheusexporter
* [x] exporter/prometheusremotewriteexporter
* [x] exporter/pulsarexporter
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21259
* [x] exporter/sentryexporter
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21258
* [x] exporter/skywalkingexporter
* [x] exporter/splunkhecexporter
* [x] exporter/sumologicexporter
* [x] exporter/tanzuobservabilityexporter
* [x] exporter/tencentcloudlogserviceexporter
* [x] exporter/zipkinexporter
* [x] extension/asapauthextension
* [x] open-telemetry/opentelemetry-collector-contrib/pull/20328
* [x] extension/basicauthextension
* [x] extension/bearertokenauthextension
* [x] extension/headerssetterextension
* [x] extension/healthcheckextension
* [x] extension/httpforwarder
* [x] extension/jaegerremotesampling
* [x] extension/oauth2clientauthextension
* [x] extension/observer/dockerobserver
* [x] extension/observer/ecsobserver
* [x] extension/observer/ecstaskobserver
* [x] extension/observer/hostobserver
* [x] extension/observer/k8sobserver
* [x] extension/oidcauthextension
* [x] extension/pprofextension
* [x] open-telemetry/opentelemetry-collector-contrib/pull/20326
* [x] extension/storage
* [x] processor/attributesprocessor
* [x] processor/cumulativetodeltaprocessor
* [x] processor/datadogprocessor
* [x] processor/deltatorateprocessor
* [x] processor/filterprocessor
* [x] processor/groupbyattrsprocessor
* [x] processor/groupbytraceprocessor
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21399
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22760
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22745
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22746
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22759
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22758
* [x] processor/resourcedetectionprocessor
* [x] processor/resourceprocessor
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22753
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22754
* [x] processor/servicegraphprocessor
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22756
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22755
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22757
* [x] processor/transformprocessor
* [x] receiver/activedirectorydsreceiver
* [x] receiver/aerospikereceiver
* [x] receiver/apachereceiver
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21846
* [x] receiver/awscontainerinsightreceiver
* [x] receiver/awsecscontainermetricsreceiver
* [x] receiver/awsfirehosereceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21781
* [x] receiver/azureblobreceiver
* [x] receiver/azureeventhubreceiver
* [x] receiver/azuremonitorreceiver
* [x] receiver/bigipreceiver
* [x] receiver/carbonreceiver
* [x] receiver/chronyreceiver
* [x] receiver/cloudflarereceiver
* [x] receiver/cloudfoundryreceiver
* [x] receiver/collectdreceiver
* [x] receiver/couchdbreceiver
* [x] receiver/datadogreceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22767
* [x] receiver/dotnetdiagnosticsreceiver
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21191
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22765
* [x] receiver/filelogreceiver
* [x] receiver/filereceiver
* [x] receiver/filestatsreceiver
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21192
* [x] receiver/fluentforwardreceiver
* [x] receiver/googlecloudpubsubreceiver
* [x] receiver/googlecloudspannerreceiver
* [x] receiver/haproxyreceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21827
* [x] receiver/httpcheckreceiver
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21218
* [x] receiver/influxdbreceiver
* [x] receiver/jaegerreceiver
* [x] receiver/jmxreceiver
* [x] receiver/journaldreceiver
* [x] receiver/k8sclusterreceiver
* [x] receiver/k8seventsreceiver
* [x] receiver/k8sobjectsreceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22766
* [x] receiver/kafkareceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22764
* [x] receiver/lokireceiver
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21230
* [x] receiver/mongodbatlasreceiver
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21232
* [x] receiver/mysqlreceiver
* [x] receiver/nginxreceiver
* [x] receiver/nsxtreceiver
* [x] receiver/opencensusreceiver
* [x] receiver/oracledbreceiver
* [x] receiver/otlpjsonfilereceiver
* [x] receiver/podmanreceiver
* [x] receiver/postgresqlreceiver
* [x] receiver/prometheusexecreceiver
* [x] receiver/prometheusreceiver
* [x] receiver/pulsarreceiver
* [x] receiver/purefareceiver
* [x] receiver/purefbreceiver
* [x] receiver/rabbitmqreceiver
* [x] receiver/receivercreator
* [x] receiver/redisreceiver
* [x] receiver/riakreceiver
* [x] receiver/saphanareceiver
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21261
* [x] receiver/signalfxreceiver
* [x] receiver/simpleprometheusreceiver/examples/federation/prom-counter
* [x] receiver/simpleprometheusreceiver
* [x] receiver/skywalkingreceiver
* [x] receiver/snmpreceiver
* [x] receiver/snowflakereceiver
* [x] receiver/solacereceiver
* [x] receiver/splunkhecreceiver
* [x] receiver/sqlqueryreceiver
* [x] receiver/sqlserverreceiver
* [x] receiver/sshcheckreceiver
* [x] open-telemetry/opentelemetry-collector-contrib/pull/21286
* [x] receiver/syslogreceiver
* [x] receiver/tcplogreceiver
* [x] receiver/udplogreceiver
* [x] receiver/vcenterreceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21669
* [x] receiver/webhookeventreceiver
* [x] receiver/windowseventlogreceiver
* [x] receiver/windowsperfcountersreceiver
* [x] receiver/zipkinreceiver
* [x] receiver/zookeeperreceiver
* [x] testbed/mockdatareceivers/mockawsxrayreceiver
* [x] testbed/mockdatasenders/mockdatadogagentexporter

**Comment by codeboten** [comment]
All the items in this issue are completed, thanks for all the work everyone!
