### ISSUE TITLE
Add more metrics to k8sclusterreceiver

### ISSUE THREAD

**Issue by ashlee3209** [open-telemetry/opentelemetry-collector-contrib#21234]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

I tried to do a comparison of metrics collected by k8sclusterreceiver and exposed metrics listed in [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/tree/main/docs). 

It seems like the receiver has fewer metrics. For example, node metric **kube_node_status_capacity** is missing in the receiver. Here is the metrics I collected from the receiver: 

> opentelemetry_k8s_container_cpu_limit
> opentelemetry_k8s_container_cpu_request
> opentelemetry_k8s_container_management_workload_openshift_io_cores_limit
> opentelemetry_k8s_container_management_workload_openshift_io_cores_request
> opentelemetry_k8s_container_memory_limit
> opentelemetry_k8s_container_memory_request
> opentelemetry_k8s_container_ready
> opentelemetry_k8s_container_restarts
> opentelemetry_k8s_cronjob_active_jobs
> opentelemetry_k8s_daemonset_current_scheduled_nodes
> opentelemetry_k8s_daemonset_desired_scheduled_nodes
> opentelemetry_k8s_daemonset_misscheduled_nodes
> opentelemetry_k8s_daemonset_ready_nodes
> opentelemetry_k8s_deployment_available
> opentelemetry_k8s_deployment_desired
> opentelemetry_k8s_job_active_pods
> opentelemetry_k8s_job_desired_successful_pods
> opentelemetry_k8s_job_failed_pods
> opentelemetry_k8s_job_max_parallel_pods
> opentelemetry_k8s_job_successful_pods
> opentelemetry_k8s_namespace_phase
> opentelemetry_k8s_node_allocatable_cpu
> opentelemetry_k8s_node_allocatable_ephemeral_storage
> opentelemetry_k8s_node_allocatable_memory
> opentelemetry_k8s_node_condition_disk_pressure
> opentelemetry_k8s_node_condition_memory_pressure
> opentelemetry_k8s_node_condition_network_unavailable
> opentelemetry_k8s_node_condition_pid_pressure
> opentelemetry_k8s_node_condition_ready
> opentelemetry_k8s_pod_phase
> opentelemetry_k8s_replicaset_available
> opentelemetry_k8s_replicaset_desired
> opentelemetry_k8s_resource_quota_hard_limit
> opentelemetry_k8s_resource_quota_used
> opentelemetry_k8s_statefulset_current_pods
> opentelemetry_k8s_statefulset_desired_pods
> opentelemetry_k8s_statefulset_ready_pods
> opentelemetry_k8s_statefulset_updated_pods
> opentelemetry_target_info

It is good if we could have more metrics as listed in  [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/tree/main/docs). 

### Describe the solution you'd like

This might wait until https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4367 is done so we can add more metrics more easily.

**Comment by atoulme** [comment]
Which of those metrics do you need? All of them? Any sorting by priority?

**Comment by ashlee3209** [comment]
Hi, thanks for following up. We do not have any priority. We are in the phase evaluating which kind of metrics we could get from opentelemetry receivers compared to prometheus. If it is easy and not too much work for you, it is nice to have them all. Because I am thinking this k8sclusterreceiver will be some replacement for kube-state-metrics, please correct me if I am wrong. Thank you very much!

**Comment by dmitryax** [comment]
@ashlee3209  k8sclusterreceiver will be some replacement for kube-state-metrics, but we don't want to copy all the metrics that kube-state-metrics blindly. Please describe your use cases and provide a list of metrics missing in k8sclusterreceiver that you depend on.

**Comment by atoulme** [comment]
I would like to flag this for discussion for a SIG meeting to raise more attention around this.

It would also be great if you can prioritize the metrics you want to see, which are just optional, and how you would like to proceed. My thinking is that you would create an issue per metric, and offer a metadata.yaml fragment for each explaining the metric usage and description, so the community can understand how this can help.

**Comment by crobert-1** [comment]
Closing based on @povilasv's comment. Please feel free to open another issue to propose adding metrics.
