### ISSUE TITLE
SplunkHEC exporter triggers incorrect linecount in Splunk

### ISSUE THREAD

**Issue by matthewmodestino** [open-telemetry/opentelemetry-collector-contrib#21236]
### Component(s)

exporter/splunkhec

### Describe the issue you're reporting

When OTel Splunk HEC exporter sends logs to Splunk, there is a `\n` appended to the end of the body. Because of this when Splunk receives the event, it computes the event as having a "linecount=2", when in reality, it is actually a single line event. 

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/31549209/234984564-329e25e2-4b8f-490b-990e-a9b0e8993895.png">

Wanted to check if this insertion of a new line is required for anything specific. Believe if we did not insert the new line it would not trigger the incorrect linecount. 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e811e7039997fbd881bb171501fcd59e8bea5111/exporter/splunkhecexporter/client.go#L206

Will test some other options on the back end to see if its possible to ditch it on the Splunk side as well

**Comment by dmitryax** [comment]
The `b = []byte(logs.At(k).Body().AsString() + "\n")` line is only applied when exporting raw event with `export_raw` config option. In your case, the `\n` at the end must be part of the original logs. AFAIR, it's always added by the docker container engine, not sure about containerd. Anyway, it's not a HEC exporter or collector issue. I believe we can add an operator config option to strip the trailing `\n`

**Comment by matthewmodestino** [comment]
Ah! Ok.

I checked containerd based cluster and saw the same. Will double check the raw logs. 

Docker needs it to denote partial in some cases to don't want to mess around too much.

Will dig a little deeper.
