### ISSUE TITLE
[exporter/syslog] Performance improvements

### ISSUE THREAD

**Issue by kkujawa-sumo** [open-telemetry/opentelemetry-collector-contrib#21244]
### Component(s)

exporter/syslog

### Describe the issue you're reporting

It would be great to following improvements in exporter:
- It seems that performing a separate network request for each Resource Log is not needed - perhaps all ResourceLogs could be sent in one request?
- Also not sure if/why we need to close the network connection after each request (with the call to sender.close() in the sender.sendSyslogs() method).

Issue related to review comment: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19647#pullrequestreview-1366958832 and it is necessary to be completed to move exporter from development to alpha.

**Comment by kkujawa-sumo** [comment]
This still needs to be done, I'm going to work on this.

**Comment by astencel-sumo** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27799
