### ISSUE TITLE
[exporter/syslog] Improve documentation

### ISSUE THREAD

**Issue by kkujawa-sumo** [open-telemetry/opentelemetry-collector-contrib#21242]
### Component(s)

exporter/syslog

### Describe the issue you're reporting

It would be great to add some improvements to documentation:
- Include some examples in docs - input vs. output.
- Document the default values being used when data is missing (like default priority or default facility).

Issue related to review comment: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19647#pullrequestreview-1366958832 and it is necessary to be completed to move exporter from development to alpha.

**Comment by kkujawa-sumo** [comment]
This still needs to be done, I'm going to work on this.

**Comment by astencel-sumo** [comment]
@kkujawa-sumo do you want this issue to be assigned to you?

**Comment by kkujawa-sumo** [comment]
yes, you can assign this issue to me ;)
