### ISSUE TITLE
[exporter/syslog] Add integration tests

### ISSUE THREAD

**Issue by kkujawa-sumo** [open-telemetry/opentelemetry-collector-contrib#21245]
### Component(s)

exporter/syslog

### Describe the issue you're reporting

Integration tests for syslog exporter need to be added.

Issue related to review comment: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19647#pullrequestreview-1366986258 and it is necessary to be completed to move exporter from development to alpha.

**Comment by kkujawa-sumo** [comment]
This still needs to be done, I'm going to work on this.

**Comment by astencel-sumo** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27464
