### ISSUE TITLE
Please ask when the tracking model of "SkyWalking gRPC Exporter" will be supported

### ISSUE THREAD

**Issue by shoogoome** [open-telemetry/opentelemetry-collector-contrib#21266]
### Component(s)

exporter/skywalking

### Describe the issue you're reporting

I need to export to skywalking trace through otel collector

**Comment by leopardrota** [comment]
@shoogoome Excuse me, I want to manually provide metrics data to SkyWalking via OpenTelemetry in a java project. Do you know how to do that in detail?

**Comment by wu-sheng** [comment]
There would not be a trace exporter in theory. SkyWalking's trace context is a superset of the traditional otel trace format. They are designed for different purposes.

@jpkrohling  Feel free to close. This had been discussed for a long time in SkyWalking channel.
