### ISSUE TITLE
OOM caused by span metrics connector

### ISSUE THREAD

**Issue by alburthoffman** [open-telemetry/opentelemetry-collector-contrib#21290]
### Component(s)

connector/spanmetrics

### Describe the issue you're reporting

We tried to switch from span metrics processor to span metrics connector, and found OOM issue.

Below is the pod heap memory after using span metrics connector. The pod traffic is around 20K spans per second:
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/863684/235493358-00fb75e1-7e6b-45c5-80e2-08d5627b9757.png">

before this, span metrics processor is quite stable.
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/863684/235493697-5280a2da-f841-4388-aa17-991f8fadc8ce.png">

the profile shows the pmap takes lots of memory for span metrics connector.
<img width="967" alt="image" src="https://user-images.githubusercontent.com/863684/235493851-bcc629be-b83a-4186-987e-4f67e11831ab.png">

which is in `createAtrributes`.
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/863684/235494010-467ad4c6-9254-4c0c-a5ab-07c8c3afa5ca.png">

**Comment by alburthoffman** [comment]
@albertteoh @kovrus please help

**Comment by albertteoh** [comment]
@alburthoffman apologies for the slow response.

I suggest trying the following:
- Inspect the metrics sent to spanmetrics connector to see if there are any high cardinality metrics.
- Reduce the `dimensions_cache_size`
- It looks like the explicit histogram metrics are taking up most of the memory. Try reducing the number of `dimensions` buckets.

**Comment by vjsamuel** [comment]
@alburthoffman  please try these and get back to @albertteoh

**Comment by alburthoffman** [comment]
@albertteoh the old span processor can handle the same config without OOM issue. So it should not be a config issue.

**Comment by albertteoh** [comment]
> @albertteoh the old span processor can handle the same config without OOM issue. So it should not be a config issue.

Thanks for confirming, @alburthoffman. Is this something that's can be reproduced locally by any chance?

**Comment by aishyandapalli** [comment]
@albertteoh I have done a quick round of testing for this one. When we enable histogram metrics in spanmetrics connector, the memory usage is very high. I tried disabling the histogram metrics and memory usage was very low. Reducing the number of buckets didn't help much. Memory usage reduced a bit but didn't help much. 

Can you please help identify the root cause?

**Comment by alburthoffman** [comment]
we did a new round of testing, and still see this issue

<img width="1684" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/863684/84dbf202-1501-42a5-8507-008f9b761447">

**Comment by portertech** [comment]
@alburthoffman does this issue persist with the latest release?

Related, I wonder if further reducing/aggregating on fewer resource attributes would help, see: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29711

**Comment by aishyandapalli** [comment]
This issue is resolved. We have added a config to limit the number of exemplars to be added for sum metrics in spanmetrics connector. It's merged and deployed. @alburthoffman We can close this issue

**Comment by alburthoffman** [comment]
Thx @aishyandapalli
