### ISSUE TITLE
Redis receiver improvements (PR feedback)

### ISSUE THREAD

**Issue by pmcollins** [open-telemetry/opentelemetry-collector-contrib#2136]
* [ ] Create DataPoints() then Resize instead of using Append https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1889#discussion_r551591997
* [ ] Use pdata types to create static counters https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1889#discussion_r551596159
* [x] Populate a metadata.yaml

**Comment by mx-psi** [comment]
I believe all tasks are completed now
