### ISSUE TITLE
Do we want to list not-otel distros in the components metadata headers?

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#21383]
In the metadata README.md headers we list only two distributions released in the OTel https://github.com/open-telemetry/opentelemetry-collector-releases?

```
| Status                   |           |
| ------------------------ |-----------|
| Stability                | [alpha]   |
| Supported pipeline types | metrics   |
| Distributions            | [contrib] |
```

Do we want to allow listing other distributions like ADOT, Sumo Logic, Splunk, and others?

cc @open-telemetry/collector-contrib-approvers

**Comment by TylerHelmuth** [comment]
We actually already have precedence for doing this: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsxrayexporter.

**Comment by dmitryax** [comment]
Ok, if there are no objection, we should probably start adding them to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/mdatagen/statusdata.go#L17 so it can be generated

**Comment by TylerHelmuth** [comment]
Hmm that's definitely more annoying :/. I love the idea of code owners being able to maintain their READMEs and list whatever distros are appropriate, I don't really love us having to keep a curated list of possible repos.  I don't love the idea of maintaining that list for everyone.  Maybe it is easy and not a problem?

**Comment by dmitryax** [comment]
> Hmm that's definitely more annoying :/. I love the idea of code owners being able to maintain their READMEs and list whatever distros are appropriate, I don't really love us having to keep a curated list of possible repos. I don't love the idea of maintaining that list for everyone. Maybe it is easy and not a problem?

We don't need to keep the curated list. It'll be the same per component definition, just in `metadata.yaml` instead of `README.md`. And it'll be on the component code owners to define which distributions are supported, but they don't have to figure that out. They can set core/contrib only and allow distribution owners to contribute. 

I'm good with any approach, but we need to define the rules here

**Comment by dmitryax** [comment]
> Ok, if there are no objections, we should probably start adding them to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/mdatagen/statusdata.go#L17 so it can be generated

To clarify what I mean by this ^: It's a one time thing to define possible supported distro links that can be referenced in the metadata.yaml/README.md

**Comment by TylerHelmuth** [comment]
Ya its only one time initially, but as links change code owners start having to mess with mdatagen to fix their READMEs instead of updating their README directly. I don't have a better solution yet and I think we should allow listing any possible distro, but that leakage of separation is annoying.

**Comment by codeboten** [comment]
i suppose alternatively, we could allow users to provide their own URLs (i think the original status block included this but ended up being so repetitive that i removed it) A single list of distributions is less annoying to maintain than a bunch of references everywhere.

**Comment by bryan-aguilar** [comment]
Jumping in here, I am more than happy to start updating components that are included in the ADOT distribution once a method is agreed upon.

**Comment by bryan-aguilar** [comment]
As a distribution maintainer I am in support of the onus being on us to ensure that a components `metadata.yaml` file is correct. I am also in support of maintaining a single list in in the location linked above. 

Do we need to define which distributions will be allowed into the [main list](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2d65254ce3f42dd11934aa3f33ae77f242b0ed20/cmd/mdatagen/statusdata.go#L17)? Which distributions will qualify? 

Question, how are we guaranteeing that auto generated README content is continuously updated? If I change the URL to my distribution in the `mdatagen` package will that cause an alarm/failure to go off somewhere? Is this a separate issue?

**Comment by atoulme** [comment]
> Question, how are we guaranteeing that auto generated README content is continuously updated? If I change the URL to my distribution in the mdatagen package will that cause an alarm/failure to go off somewhere? Is this a separate issue?

It runs on every CI and fails if the generated data differs from what is in the PR.

**Comment by atoulme** [comment]
We currently have 4 components listing the AWS distribution:
```
 git grep Distributions | grep -i \\\[aws
exporter/awsxrayexporter/README.md:| Distributions            | [contrib], [AWS] |
exporter/datadogexporter/README.md:| Distributions            | [contrib], [AWS] |
exporter/dynatraceexporter/README.md:| Distributions            | [contrib], [AWS] |
receiver/awsxrayreceiver/README.md:| Distributions            | [contrib], [AWS] |
```

**Comment by bryan-aguilar** [comment]
I'm not sure if we need to use the current AWS links as precedent. They seem to rely on ADOT maintaining documentation in our developer portal. I would be in favor of standardizing around a single link for these, most likely to our repository README.md.

**Comment by dmitryax** [comment]
> I would be in favor of standardizing around a single link for these, most likely to our repository README.md.

I agree that having a link to a repository is probably a better consistent approach.

**Comment by TylerHelmuth** [comment]
> Which distributions will qualify?

I think the rules around managing the list could be:
- The distribution must be open source.
- The link should be to the distributions public repository.

**Comment by dmitryax** [comment]
@TylerHelmuth submitted a PR with your suggestions https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21470

**Comment by astencel-sumo** [comment]
Hmm I wonder how useful and how readable it will be to list all the distributions that use a specific component in the component's README. For some widely used components, the list might get quite long and I'm not sure if it will bring much value to the end user.

The good thing is this decision can always be changed, so I have no problem with taking this approach for now (of listing all distros in the world).

**Comment by dmitryax** [comment]
We should not worry about filling the list ourselves.

Another benefit of doing this: if we find an unmaintained component, we can ping the distribution owners, and let them know. If they worry about the potential removal, they can step in and take the responsibility to maintain it.

**Comment by bryan-aguilar** [comment]
When the OTEL Collector takes over the monitoring world and we have a much larger number of distributions we may have to consider putting them somewhere other than the README header though. I think that would be a good problem to have and we can solve it when we get there :)

**Comment by codeboten** [comment]
> For some widely used components, the list might get quite long and I'm not sure if it will bring much value to the end user.

For our concern, the distributions list is really helpful for newcomers to figure out if they should try otelcol or otelcontrib. 

If a user is using a particular distro and looks at the README first to figure out if it's supported, and realizes there's a mistake, or that a distro isn't listed, they can always open an edit or push the owners of that distro to do so.

But that's a problem for future us, we only have a handful of distros to worry about at the moment :) Maybe in the future when there are 1.2 million distros, we'll have a separate doc that we link to ;)

**Comment by TylerHelmuth** [comment]
> But that's a problem for future us

The best kind of problem

**Comment by dmitryax** [comment]
A couple of questions on how we list them:

Case: Currently, `core` and `contrib` are lowercase as well as the stability level and data types like `beta` and `traces`. Do we want to require other distros to be lowercased as well like `aws`, `splunk` `sumo-logic`? If not, should we rename core and contrib to something else like `OTelCol Core` and `OTelCol Contrib` or `OpenTelemetry Collector` and  `OpenTelemetry Collector Contrib`

Order: core/contrib + others in alphabetical order?

**Comment by atoulme** [comment]
I am in favor of full name and ordered like you mentioned, core and contrib first then alphabetical order.

**Comment by TylerHelmuth** [comment]
Will the table be able to handle full name or will it be crowded? There are several components that will need to list every distribution, such as attribute processor. 

If full name doesn't fit I vote all lowercase like we've been doing it. 

I agree we list all OTEL community distributions first (including ones we may add in the future), and then alphabetical.

**Comment by dmitryax** [comment]
Given we reached an agreement, established rules and started the work, I'm closing the issue
