### ISSUE TITLE
Intra-repo dependency doc proposal (CONTRIBUTING.md)

### ISSUE THREAD

**Issue by Caleb-Hurshman** [open-telemetry/opentelemetry-collector-contrib#21404]
### Describe the issue you're reporting

As a new contributor to the OTel collector, I have found the process and documentation around starting a new component to be unclear. Two specific issues in my experience are the lack of specificity for where to update intra-repository dependencies. Ideally, this should not be an issue with the `make crosslink` command, but I have had issues with the command not adding references to all the correct places, specifically `cmd/otelcontribcol/builder-config.yaml`. I propose the documentation be updated to explicitly list the intra-repository locations where references to a receiver must be added. This will provide redundancy in case the make crosslink command becomes unreliable for whatever reason.

**Comment by atoulme** [comment]
Sure thing. We have some guidelines on how to contribute a new component here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components
We can do a lot more as evidenced by recent contributions, with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20733 being a good one for example.

**Comment by Caleb-Hurshman** [comment]
@atoulme After digging further, I found out another previous issue with the `make crosslink` command, in which it added the line `"github.com/influxdata/telegraf/plugins/inputs/apache"` to `cmd/otelcontribcol/components.go`. This caused some of the automated checks to fail when I created a pr. 
I'm glad the docs exist, and they are for the most part a useful reference, but I found this one area to be lacking. I'd be happy to make this minor update myself. Unfortunately I am going to be offline for the next couple weeks and will not have time to dig deeper into the reasons why `make crosslink` is behaving unpredictably.

**Comment by bryan-aguilar** [comment]
Crosslink is not currently built to support adding replace statement in `cmd/otelcontribcol/builder-config.yaml`. That is out of scope for the tool. Giving crosslink to supplement OCB configurations would be a good feature request though. 

> After digging further, I found out another previous issue with the make crosslink command, in which it added the line "github.com/influxdata/telegraf/plugins/inputs/apache" to cmd/otelcontribcol/components.go. This caused some of the automated checks to fail when I created a pr.

I am interested in this behavior. Could you document a bit more about what happened vs what you expected and what the solution was? Could you open a specific issue in [`go-build-tools`](https://github.com/open-telemetry/opentelemetry-go-build-tools) with all the info? You can tag me in the issue and I will find some time to take a look at it.
