### ISSUE TITLE
Update existing README headers that list ADOT distro

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/opentelemetry-collector-contrib#21479]
### Component(s)

exporter/awsxray, exporter/datadog, exporter/dynatrace, receiver/awsxray

### Describe the issue you're reporting

Related issue #21383 

Some components currently have AWS listed as a distro in their README.md headers. These links point to different destinations. `mdatagen` supports a list of distributions and will generate a README header with a list of distribution links. Existing READMEs with AWS distribution header should be updated to us `mdatagen`. Some components may require a `metadata.yaml` file to be created for them. 

This issue can be assigned to me when a @open-telemetry/collector-contrib-triagers sees this.

**Comment by dmitryax** [comment]
@bryan-aguilar, can this be assigned to you?
