### ISSUE TITLE
Multi Tenancy for Loki Exporter

### ISSUE THREAD

**Issue by psangamkar** [open-telemetry/opentelemetry-collector-contrib#21489]
We have otel collector and loki-distributed stack deployed on K8s cluster using helm chart. Where in the Otel loki exporter we are using X-scope-OrgID as header for multi tenancy but we want more than 1 tenant as header. 

**oter config :** 
  
   exporters:
        loki/multitenant:
          endpoint: "http://loki-gateway:80/loki/api/v1/push"
          tls:
            insecure: true
            insecure_skip_verify: true
          headers:
            "X-Scope-OrgID": acme
            "X-Scope-OrgID": abc

We are facing this error
`Error: failed to get config: cannot resolve the configuration: cannot retrieve the configuration: yaml: unmarshal errors:
  line 32: mapping key "X-Scope-OrgID" already defined at line 31
2023/05/02 13:32:48 collector server run finished with error: failed to get config: cannot resolve the configuration: cannot retrieve the configuration: yaml: unmarshal errors:
  line 32: mapping key "X-Scope-OrgID" already defined at line 31`

Along with that How can we update **X-Scope-OrgID** dynamically from log attribute?

**Comment by mar4uk** [comment]
To set `X-Scope_OrgID` header dynamically you should use `loki.tenant` hint attribute:
Example:
```
processors:
  resource:
    attributes:
    - action: insert
      key: loki.tenant
      value: host.name
```
More detailed info on the tenant could be found in loki exporter README https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter#tenant-information

Hope it helps! Let me know if it is not

**Comment by mar4uk** [comment]
the issue is still valid

**Comment by mar4uk** [comment]
this issue is fixed and could be closed

**Comment by kadhamecha-conga** [comment]
hi @mar4uk ,

is  loki.tenant hint attribute work, if we are running otel agent on 0.47 version ?

we are running otel as agent and server model and there is difference in version running on both agent and collector.
the X-Scope-OrgID is not coming as attribute from agent to collector.

do we need to upgrade otel on agent to any specific version ?
can you please confirm which version support X-Scope-OrgID ?

thanks.
