### ISSUE TITLE
[receiver/sshcheck] Promote sshcheckreceiver to alpha

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#21488]
### Component(s)

receiver/sshcheck

### Is your feature request related to a problem? Please describe.

We are getting requests from end users to include the sshcheckreceiver as part of our distribution.

### Describe the solution you'd like

Consider promoting sshcheckreceiver to alpha.

**Comment by codeboten** [comment]
@nslaughter can I assign you this one?

**Comment by nslaughter** [comment]
> @nslaughter can I assign you this one?

yes. ty

**Comment by codeboten** [comment]
This was addressed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21886
