### ISSUE TITLE
[receiver/k8sobjects] move k8sobjects receiver to beta

### ISSUE THREAD

**Issue by omrozowicz-splunk** [open-telemetry/opentelemetry-collector-contrib#21503]
### Component(s)

receiver/k8sobjects

## Proposal

I'd like to discuss what it takes to mark k8sobjects receiver as beta. It's already over 6 months available, and only small enhancements were added during the last 3 months - no breaking changes. Some customers are reluctant to use it because of its alpha status. The only currently open issue/enhancement request is about adding e2e tests https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18395

**Comment by atoulme** [comment]
Would it be possible to close #18395 first?

**Comment by TylerHelmuth** [comment]
The k8sobjects receiver has had a lot of work done this summer that pushes it closer to beta.  I feel once the e2e test that @jinja2 is implementing is finished we can call this receiver beta.
