### ISSUE TITLE
Splunk HEC message time field can be sent as a String

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#2158]
**Describe the bug**
Splunk HEC consumes an optional time field that represents the time of the event or metric.
The latest versions of HEC recommend to use a number representing the number of seconds since epoch with a precision of 3 decimals. Some libraries, such as Docker logging, use a string representation of the time field instead of a number.

**Steps to reproduce**
Use Docker logging pointed at the otel collector log pipeline.

**What did you expect to see?**
A 200 OK response from the Otel Collector.

**What did you see instead?**
```2021-01-20T22:42:45.912Z        debug   splunkhecreceiver/receiver.go:342       Splunk HEC receiver request failed      {"component_kind": "receiver", "component_type": "splunk_hec", "component_name": "splunk_hec", "http_status_code": 400, "msg": "\"Failed to unmarshal message body\"", "error": "json: cannot unmarshal string into Go struct field Event.time of type float64", "receiver": "splunk_hec"}```

**What version did you use?**
Latest dev snapshot

**Comment by andrewhsu** [comment]
Closing this because taken care of in PR #2159
