### ISSUE TITLE
Rename Kinesis exporter to awskinesisexporter

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector-contrib#2164]
In order to have consistency with other Amazon/AWS exporters, move the kinesisexporter into awskinesisexporter.

The official name for Kinesis is Amazon Kinesis, but we named Amazon Managed Service for Prometheus exporter as "awsprometheusremotewriteexporter". For consistency, I think it's ok to use "aws" as a prefix.

**Comment by bogdandrutu** [comment]
I think it is ok because Kinesis is an AWS product only :)
