### ISSUE TITLE
[exporter/loki]: Add Flags to the lokiEntry

### ISSUE THREAD

**Issue by bgranetzke** [open-telemetry/opentelemetry-collector-contrib#21650]
### Component(s)

exporter/loki

### Is your feature request related to a problem? Please describe.

There is currently no way to get the Flags field from plog.LogRecord into Loki.

### Describe the solution you'd like

I would like the Flags to be treated the same way as TraceID and SpanID

### Describe alternatives you've considered

An alternative is to treat it as an attribute on the LogRecord. 

### Additional context

Upstream, I'm using the filelogreceiver trace_parser to parse the flags (hex) into LogRecord.Flags.   https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/trace_parser.md

If the omission of Flags was intentional, I can work around the issue by retaining the attribute I'm parsing from.

**Comment by mar4uk** [comment]
Hi! By Flags field in LogRecord, do you mean [TraceFlags](https://opentelemetry.io/docs/reference/specification/logs/data-model/#field-traceflags)?

**Comment by bgranetzke** [comment]
@mar4uk Yes, however, it is just Flags in the current generated LogRecord: https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/plog/generated_logrecord.go#L98

**Comment by jpkrohling** [comment]
I'm closing this, as I believe this has been done. If that's not the case, let me know and I'll reopen it.
