### ISSUE TITLE
GMP Exporter: Retain all resource labels

### ISSUE THREAD

**Issue by algchoo** [open-telemetry/opentelemetry-collector-contrib#21654]
### Component(s)

exporter/googlemanagedprometheus

### Is your feature request related to a problem? Please describe.

The problem is that this exporter just drops important information attached to resource labels. If the resource labels don't align with what is documented [here](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-otel#detect-resource-attributes) they are dropped.

### Describe the solution you'd like

Ideally, it'd be handled the same way it's handled in the following exporters:
* [Prometheus Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter)
* [Prometheus Remote Write Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusremotewriteexporter)

I see an issue exists [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12175), but also that the associated [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13616) has been closed, for now.

**Comment by damemi** [comment]
The cloud monitoring exporter has [`resource_filters`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudexporter#configuration-reference), which does what you're asking (though the attributes are added as metric labels, not monitored resource labels). I don't know if there's a reason we couldn't do that for GMP as well

**Comment by damemi** [comment]
Opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24392 which would allow `resource_filters` to be set on the GMP exporter. For the purpose of this issue, all resource labels could be copied using a regex that matches everythign.
