### ISSUE TITLE
AzureMonitor Receiver does not fetch combinational dimensions of metric values.

### ISSUE THREAD

**Issue by rajim17** [open-telemetry/opentelemetry-collector-contrib#21715]
### Component(s)

receiver/azuremonitor

### Describe the issue you're reporting

If metric has multiple dimensions, metricValues are fetched by single dimension instead of combining all dimensions.  With single dimension metric value is average value of other dimensions. 

In below example without all dimensions in the filter, 'metadata_nodepool' provides average value of 2 'metadata_node' datapoints. But cannot combine dimensions of metadata_node under  'metadata_nodepool' dimensions.

```
Metric #44
Descriptor:
     -> Name: azure_node_cpu_usage_millicores_total
NumberDataPoints #0
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_nodepool: Str(general1)
Value: 625.500000

NumberDataPoints #1
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_node: Str(aks-general1-vmss00006x)
Value: 506.000000

NumberDataPoints #2
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_node: Str(aks-general1-vmss000062)
Value: 745.000000
```

With all Dimensions applied:
 Here each datapoint provides all related dimension values. With this information, it is easy to apply multiple filters.

```
Metric #44
Descriptor:
     -> Name: azure_node_cpu_usage_millicores_total

NumberDataPoints #0
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_node: Str(aks-general1-vmss00006x)
     -> metadata_nodepool: Str(general1)
Value: 506.000000

NumberDataPoints #1
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_node: Str(aks-general1-vmss000062)
     -> metadata_nodepool: Str(general1)
Value: 745.000000

```

In Azuremonitor receiver, [getResourceMetricsValuesRequestOptions](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/azuremonitorreceiver/scraper.go#L372-L374) func, sinlge dimension key alone provided. Instead all possible dimension keys for the metric have to be given. 

Sample MetricClient REST Request with all dimensions.

`https://management.azure.com/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue/providers/Microsoft.Insights/metrics?timespan=2023-04-29T02:20:00Z/2023-05-04T04:20:00Z&interval=PT1H&api-version=2018-01-01&metricnamespace=Microsoft.ContainerService/managedClusters&metricnames=node_cpu_usage_millicores&$filter=nodepool eq '*' and node eq '*'`

**Comment by codeboten** [comment]
@rajim17 is this functionality you'd like to add yourself? @altuner any thoughts on this issue?

**Comment by codeboten** [comment]
thanks @altuner, i see the `#` was missing in the description, which is why the PR didnt get linked to the issue :)

**Comment by rajim17** [comment]
@altuner - The fix applies for all services. I gave an example of "Microsoft.ContainerService"

**Comment by rajim17** [comment]
Yes @altuner . I tested for few other services like Microsoft.storageAccounts , Microsoft.eventhub/namespaces .

**Comment by rajim17** [comment]
@altuner. I also added data in the testcase to handle multiple dimensions for the same metric.
