### ISSUE TITLE
[kafkareceiver] - Add string unmarshaler

### ISSUE THREAD

**Issue by VihasMakwana** [open-telemetry/opentelemetry-collector-contrib#21730]
### Is your feature request related to a problem? Please describe.

I can't send and receive raw strings.

### Describe the solution you'd like

Currently, if I use a console producer and console consumer, kafkareceiver only allows to unmarshal otlp, zipkin or jaeger.
If I'm just sending raw string, the only option I have is to select raw unmarshaler and it will send data in bytes.
It would be great to have a string unmarshaler.

**Comment by VihasMakwana** [comment]
Yeah actually.
here's my setup 
1). Kafka console consumer
2). [OTEL] Kafka receiver
3). [OTEL] Splunk HEC exporter

I'm sending a string "Event" in kafka consumer and I receive "RXZlbnQ=" in Splunk Dashboard i.e. base64 encoding of "Event".
So, I think we can have a string unmarshaller.
I'm setting encoding as "raw"

**Comment by atoulme** [comment]
See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20734

**Comment by VihasMakwana** [comment]
Closing as there's a duplicate
