### ISSUE TITLE
[servicegraph] Allow span name to be added as a dimension on the metrics

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#21802]
### Component(s)

connector/servicegraph

### Is your feature request related to a problem? Please describe.

The current service graph connector/processor solution only allows resource / span attributes to be added custom dimensions, but we have a usecase where we want to add the span name to the labels as well.

### Describe the solution you'd like

Allow adding the span name to the dimensions.

**Comment by JaredTan95** [comment]
If that, we can calculate the `endpoint graph` by metrics within `span name`. But, the `servicegraph` need to rename or something?

**Comment by gouthamve** [comment]
Sorry. Let me explain. We would like to visualise which neighbors are being called upstream / downstream for a particular operation. Adding a label to the metrics would allow for that.

Ideally, we should be able to see the service graph for the entire request for the span name. For example, see the write path service graph vs read path service graph, but I don't think metrics are a good fit for that usecase.
