### ISSUE TITLE
aws s3 exporter - support custom endpoint configuration 

### ISSUE THREAD

**Issue by guyfrid** [open-telemetry/opentelemetry-collector-contrib#21833]
### Component(s)

exporter/awss3

### Is your feature request related to a problem? Please describe.

The exporter configuration lacks support for configuring the S3 endpoint, which can be inconvenient during local development. Adding the ability to configure the S3 endpoint would enhance flexibility and ease of use in different environments.

### Describe the solution you'd like

The configuration for the AWS S3 exporter includes support for specifying a custom endpoint. The endpoint parameter is optional and can be provided during session creation if needed. If the endpoint parameter is not provided, the exporter will fallback to using the default value specified in the AWS_ENDPOINT_URL environment variable. This allows flexibility in defining the endpoint for the exporter, enabling seamless integration with different AWS S3 service configurations.

**Comment by guyfrid** [comment]
I want to work on this feature. please assign it to me

**Comment by atoulme** [comment]
It's yours @guyfrid !

**Comment by cwegener** [comment]
This is very useful indeed. Thanks for implementing this.

I wonder if `S3ForcePathStyle` would also be needed in addition to the endpoint in order to use  a single label hostname in the URL?
