### ISSUE TITLE
[exporter/prometheusremotewrite] Make `maxBatchByteSize` configurable

### ISSUE THREAD

**Issue by yotamloe** [open-telemetry/opentelemetry-collector-contrib#21911]
### Component(s)

exporter/prometheusremotewrite

### Is your feature request related to a problem? Please describe.

The `maxBatchByteSize` in the `prometheusremotewrite` exporter which is currently set to a static value of ~2.861 MB (as seen [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/exporter.go#L43)).

### Example use case 
My remote storage ingestion endpoint can handle around 9 MB per POST request. I'm thinking that if we increase the `maxBatchByteSize` value, we could potentially send metrics from the queue faster, and this could lead to better performance when scaling up.

### Describe the solution you'd like

I'd like to suggest making `maxBatchByteSize` a configurable parameter. This would allow users to adjust it based on the capabilities of their specific remote storage, offering more flexibility and potentially improving performance. Something like:
```yaml
exporters:
  prometheusremotewrite:
    endpoint: "https://my-cortex:7900/api/v1/push"
    max_batch_byte_size: 5000000
```

### Describe alternatives you've considered

N/A

### Additional context

I would be happy to contribute to this feature and open a PR for it.
I'm also curious to know if there are any inherent limitations with the `maxBatchByteSize`. I'd love to understand why it's currently static. Any insights on this would help me understand the current design better.

**Comment by JaredTan95** [comment]
@yotamloe could you pls submit a PR to support it? :-P

**Comment by yotamloe** [comment]
@JaredTan95 Sure I will open a pr for the feature, I hope I will manage to do it this week or early next week.
