### ISSUE TITLE
Histogram metric type should support count with float64 type.

### ISSUE THREAD

**Issue by adam-mateen** [open-telemetry/opentelemetry-collector-contrib#21913]
**Is your feature request related to a problem? Please describe.**
The problem is supporting statsd receivers.
For statsd timing metrics the "count" may not be an integer.

The statsd protocol allows "timing" metrics, which the statsd receiver converts into OTEL histograms.
Statsd supports the concept of "samplerate" which is typically a float between 0 and 1.
more details - https://thenewstack.io/collecting-metrics-using-statsd-a-standard-for-real-time-monitoring/

If user sends a statsd timing metric with a count of 7 and a sample rate of 0.3, then the statsd receiver should use an effective count of 7/0.03 = 23.333...

Here is the function which sets the "count" for an OTEL histogram:
https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/pmetric/generated_histogramdatapoint.go#L87

Here is the statsd receiver acknowledging the loss of precision due to type conversion:
https://github.com/amazon-contributing/opentelemetry-collector-contrib/blob/main/receiver/statsdreceiver/protocol/metric_translator.go#L151-L178

**Describe the solution you'd like**
Either modify the existing histogram structure to allow "count" to be stored and retrieved as a float64, or create another Histogram metric type that allows "count" to be stored and retrieved as a float64.

**Describe alternatives you've considered**
1. Accept a loss of precision due to type conversion.
2. Bypass OTEL framework and create a "receiver" which directly passes data to an exporter.
3. Stringify the bucket values and counts and put them in special ATTRIBUTES, which only the statsd exporter would know how to parse and use.

**Comment by atoulme** [comment]
This seems like a discussion for the https://github.com/open-telemetry/opentelemetry-specification repository.

**Comment by atoulme** [comment]
Please read more about how count is computed here: https://github.com/open-telemetry/opentelemetry-proto/blob/c5c8b28012583fda55b0cb16f73a820722171d49/opentelemetry/proto/metrics/v1/metrics.proto#LL452C11-L452C16

I believe this issue must be reviewed by the statsdreceiver codeowners to follow up. Tagging them now.
