### ISSUE TITLE
unknown receivers type "filelog" error in v0.77.0

### ISSUE THREAD

**Issue by kezhenxu94** [open-telemetry/opentelemetry-collector-contrib#21916]
### Component(s)

receiver/filelog

## Description

I can see `filelog` receiver is added in the release

https://github.com/open-telemetry/opentelemetry-collector-releases/blob/ca497576e06ef42f7a00c679fef1c3eeae49d963/distributions/otelcol-contrib/manifest.yaml#L123

but when I try to use it in `otel/opentelemetry-collector:0.77.0`, it reports error

```
opentelemetry-logs-example-otel-collector-1  | Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
opentelemetry-logs-example-otel-collector-1  | 
opentelemetry-logs-example-otel-collector-1  | * error decoding 'receivers': unknown type: "filelog" for id: "filelog" (valid values: [prometheus zipkin otlp hostmetrics jaeger kafka opencensus])
opentelemetry-logs-example-otel-collector-1  | 2023/05/15 03:30:19 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
opentelemetry-logs-example-otel-collector-1  | 
opentelemetry-logs-example-otel-collector-1  | * error decoding 'receivers': unknown type: "filelog" for id: "filelog" (valid values: [prometheus zipkin otlp hostmetrics jaeger kafka opencensus])
opentelemetry-logs-example-otel-collector-1 exited with code 1
```

## Steps to Reproduce

```shell
cat <<EOF > docker-compose.yaml
version: '3.0'

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.77.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]

EOF

cat <<EOF > otel-collector-config.yaml
receivers:
  filelog:
    include: [ /var/log/test/*.json ]

processors:
  batch:

exporters:
  otlp:
    endpoint: host.docker.internal:4317

service:
  pipelines:
    logs:
      receivers:
        - filelog
      processors:
        - batch
      exporters:
        - otlp
EOF

docker compose up
```

## Expected Result

The opentelemetry collector should start successfully

## Actual Result

An error was reported and opentelemetry exited with code 1

### Collector version

v0.77.0

## Environment
OS: macOS 13.3.1 (a)
Docker: 

```
Client:
 Version:           23.0.3
 API version:       1.42
 Go version:        go1.19.7
 Git commit:        3e7cbfd
 Built:             Tue Apr  4 22:02:29 2023
 OS/Arch:           darwin/amd64
 Context:           orbstack

Server:
 Engine:
  Version:          23.0.3
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       59118bff500fc0d95d0560a9788735a8d89568ce
  Built:            Thu Apr  6 02:18:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc:
  Version:          1.1.5
  GitCommit:        f19387a6bec4944c770f7668ab51c4348d9c2f38
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include: [ /var/log/test/*.json ]

processors:
  batch:

exporters:
  otlp:
    endpoint: host.docker.internal:4317

service:
  pipelines:
    logs:
      receivers:
        - filelog
      processors:
        - batch
      exporters:
        - otlp
```

**Comment by shivanshu1333** [comment]
+1 on moving it to the core collector repo
cc: @djaglowski

**Comment by kezhenxu94** [comment]
> You're using `otel/opentelemetry-collector` which doesn't have filelog receiver [included](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol/manifest.yaml), as the error says. Use `otel/opentelemetry-collector-contrib` instead.
> 
> Since filelog receiver represents such a core piece of functionality, maybe the core distro should have it? WDYT @djaglowski ?

OK thanks! Let me close this issue for now

**Comment by neilmcguigan** [comment]
> You're using `otel/opentelemetry-collector` which doesn't have filelog receiver [included](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol/manifest.yaml), as the error says. Use `otel/opentelemetry-collector-contrib` instead.
> 
> Since filelog receiver represents such a core piece of functionality, maybe the core distro should have it? WDYT @djaglowski ?

how did you make a telemetry system that doesn't support log files? lol

**Comment by swiatekm** [comment]
> > You're using `otel/opentelemetry-collector` which doesn't have filelog receiver [included](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol/manifest.yaml), as the error says. Use `otel/opentelemetry-collector-contrib` instead.
> > Since filelog receiver represents such a core piece of functionality, maybe the core distro should have it? WDYT @djaglowski ?
> 
> how did you make a telemetry system that doesn't support log files? lol

Some people don't need to read logs from files. Either they don't need logs at all, because they get enough information from traces, or they use otel instrumentation, and get logs via the OTLP protocol. The opentelemetry collector is very modular, and you can, and are in fact encouraged to build a collector binary with only the components you actually need. The original author of this thread was using a distribution which didn't have the component used for reading logs from files.

If you want to learn about the official distributions and why they contain the components they do, feel free to check out the [releases repository](https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions). At a higher level, there's also the following issue: https://github.com/open-telemetry/opentelemetry-collector/issues/8555.
