### ISSUE TITLE
Support Managed Identity Auth for Azure Data Explorer

### ISSUE THREAD

**Issue by ben-childs-docusign** [open-telemetry/opentelemetry-collector-contrib#21924]
### Component(s)

exporter/azuredataexplorer

### Is your feature request related to a problem? Please describe.

Currently the azure data explorer exporter requires an App ID + Secret in order to authenticate to ADX. For services running in Azure that can use Azure Managed Identity it would be more convenient to just configure an App ID and authenticate using managed identity.

### Describe the solution you'd like

azuredataexplorer exporter should support specifying just Application ID rather than Application ID + Client ID + Tenant ID. When only the Application ID is specified it should pass this to azure-kusto-go client using "WithUserManagedIdentity".

it could also optionally support providing no credentials at all in which case it could use "UseDefaultAzureCredential"

### Describe alternatives you've considered

No alternatives were considered. Using application + client secret auth requires us to manage additional secrets and rotate them, managed identity would allow us to authenticate without having to manage additional secrets.

**Comment by ag-ramachandran** [comment]
Hello @ben-childs-docusign, will pick this up for use with managed Identity as well. We're planning to have a couple of PR's, one for MI and the other for go-sdk update

**Comment by ben-childs-docusign** [comment]
Hi @ag-ramachandran do you have any estimate for when you would be able to implement this?

**Comment by ag-ramachandran** [comment]
Hello @ben-childs-docusign, Apologies for not picking this up yet. We're thinking of picking this up early next week. The fix should not be too hard itself, we can try a dev complete and submit for review next week!. Would that timeline work.

**Comment by ag-ramachandran** [comment]
hello @ben-childs-docusign , Quick update : we should have the PR out by this Friday on this

**Comment by asaharn** [comment]
Hi @ben-childs-docusign, the feature is completed. Can you close this issue please.

**Comment by mx-psi** [comment]
Closing based on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21924#issuecomment-1702923403
