### ISSUE TITLE
Add k8s.cluster.uid to k8sattributes processor

### ISSUE THREAD

**Issue by smithclay** [open-telemetry/opentelemetry-collector-contrib#21974]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

Per the semantic conventions, we should add support for `k8s.cluster.uid` in the `k8sattributes` processor.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md#cluster

>  k8s.cluster.uid: A pseudo-ID for the cluster, set to the UID of the kube-system namespace.

This allows any users of the k8sattributes processor to uniquely identify their clusters.

### Describe the solution you'd like

An optional metadata field that annotates telemetry with `k8s.cluster.uid`

**Comment by dmitryax** [comment]
Sounds good to me. @smithclay would you work on this?

**Comment by shivanshu1333** [comment]
@dmitryax I think I can take this up, can you assign it to me?
Thanks!

**Comment by shivanshu1333** [comment]
Hi I've been looking into it, though I have one question.

_**What is the standard way of querying for the cluster id in kubernetes?**_

From my research we can use kube-system namespace UID for this purpose, this is what upstream kubernetes suggests to do (and there are many resources pointing in same direction)
Ref:
1) https://github.com/kubernetes/kubernetes/issues/77487
2) https://groups.google.com/g/kubernetes-sig-architecture/c/mVGobfD4TpY/m/nkdbkX1iBwAJ

Should I implement to use the above mentioned UID as cluster ID by default?

**Comment by shivanshu1333** [comment]
cc: @dmitryax any sugggestions on the above suggested method?

**Comment by dmitryax** [comment]
@shivanshu1333 yes, we should use UID of kube-system namespace as prescribed in https://github.com/open-telemetry/semantic-conventions/blob/156f9424fe5d83d8543119224c3af6ae9af518cf/specification/resource/semantic_conventions/k8s.md?plain=1#L28-L51

**Comment by shivanshu1333** [comment]
Thanks for the confirmation, let me open a PR.
(I wasn't aware about the above semantic conventions, thanks for sharing)

**Comment by shivanshu1333** [comment]
@smithclay @dmitryax reviews requested for the link PR, thanks!!
