### ISSUE TITLE
[pkg/ottl] Mathematical Expressions are able to handle `time.Time` and `time.Duration` types.

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#22009]
In order to support complex interactions with time we need to support the following cases in our mathematical expressions:

- Subtracting a `time.Time` from `time.Time` must result in a `time.Duration`.
- Adding a `time.Duration` to a `time.Time` must result in a `time.Time`
- Subtracting a `time.Duration` from a `time.Time` must result in a `time.Time`
- Adding a `time.Duration` to a `time.Duration` must result in a `time.Duration`
- Subtracting a `time.Duration` from a `time.Duration` must result in a `time.Duration`

Only these type interactions should be supported. For example, the following SHOULD NOT be allowed:
- adding/subtracting an integer from a `time.Time`.
- adding/subtracting an integer from a `time.Duration`.

At the moment these rules cannot be enforced by the grammar, instead we will have to enforce these rules in the execution of the mathematical expressions.  This is the existing pattern we use for other type checking.

**Comment by kamalmarhubi** [comment]
Does this mean adding `time.Duration` as the difference type?

**Comment by TylerHelmuth** [comment]
I will detail these cards next week, but yes.
