### ISSUE TITLE
[pkg/ottl] Boolean expressions are update to be able to handle comparing `time.Time` types

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#22008]
In order to facilitate contexts returning time fields as `time.Time` we need to be able to compare `time.Time` values in boolean expressions.  Although not supported by the grammar as literals, OTTL should allow working with these types.

When comparing `time.Time` fields, the following rules should be followed:
- `time.Equal` should be used to check if 2 times are equal.
- `time.Before` should be used to check if 1 time is earlier than another.
- `time.After` should be used to check if 1 time is later than another.

Given 2 times, A and B:
- `A < B` is true if and only if `A.Before(B)` is true.
- `A <= B` is true if `A.Before(B)` is true OR `A.Equal(B)` is true.
- `A > B` is true if and only if `A.After(B)` is true.
- `A >= B` is true if `A.After(B)` is true OR `A.Equal(B)` is true.
- `A == B` is true if and only if `A.Equal(B)` is true.
- `A != B` is true if and only if `A.Equal(B)` is false.

If either A or B is not a time, the comparison is false.

**Comment by fchikwekwe** [comment]
I'm working on this ticket. Please assign me @TylerHelmuth
