### ISSUE TITLE
Collect Fargate EphermalStorage and ClockDrift Metrics in the awsecscontainermetrics Receiver

### ISSUE THREAD

**Issue by ollypom** [open-telemetry/opentelemetry-collector-contrib#22006]
### Component(s)

receiver/awsecscontainermetrics

### Is your feature request related to a problem? Please describe.

There are metrics that are exposed in the Task metadata v4 endpoint on AWS Fargate that are correctly not exposed as [available metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awsecscontainermetricsreceiver#available-metrics) in the `awsecscontainermetrics` receiver. Specifically these are the [Ephemeral Storage metrics](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-fargate-monitoring-storage-utilization/) and the [Clock Drift Metrics](https://aws.amazon.com/about-aws/whats-new/2021/09/monitoring-clock-aws-fargate-amazon-ecs/).

These metrics are available on the `/task` Endpoint on the [Task Metadata endpoint](https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html#task-metadata-endpoint-v4-fargate-response) on a Fargate Task.

Ephemeral Storage Metrics look like:

```
  "EphemeralStorageMetrics": {
    "Reserved": 20496,
    "Utilized": 289
  },
```

Clock Drift Metrics look like:

```
  "ClockDrift": {
    "ClockErrorBound": 0.44391449999999993,
    "ClockSynchronizationStatus": "SYNCHRONIZED",
    "ReferenceTimestamp": "2023-05-16T10:35:39Z"
  },
```

### Describe the solution you'd like

It would be great if the receiver could collect this metrics, so I can forward them on the CW Metrics or Prometheus.

**Comment by cadrake** [comment]
I would like to work on this issue if it is still a desired feature

**Comment by cadrake** [comment]
receiver/awsecscontainermetrics: @Aneurysm9

**Comment by ollypom** [comment]
Thanks @cadrake , while I'm not involved in this project. I'd still very much like to see this feature exist, right now I am having to work around the problem with additional sidecar containers.
