### ISSUE TITLE
[pkg/ottl] Converter Function that is able to create a new `time.Duration` type from a string.

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#22015]
In order to facilitate proper time manipulation, arithmetic, and comparison it will be very useful to have Durations.

Create an OTTL Converter Function, probably called `Duration`, that is able to create a new `time.Duration` type from a string.  Something similar to https://pkg.go.dev/time#ParseDuration can be used.

The function should take 1 parameters, a string (represented as a `StringGetter`) that represents the duration in Go format, such as `1s` for 1 second or `2h` for 2 hours or `3m30s` for 3 minutes and 30 seconds.

**Comment by fchikwekwe** [comment]
@TylerHelmuth please assign me
