### ISSUE TITLE
[pkg/ottl] Make SpanID and TraceID converters accept strings

### ISSUE THREAD

**Issue by kamalmarhubi** [open-telemetry/opentelemetry-collector-contrib#22026]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

Right now, the TraceID and SpanID converters only accept byte slices. Plenty of source data uses the standard hex-encoded string representation. I don't know of any straightforward way to convert that to bytes to pass to the existing converter implementations.

### Describe the solution you'd like

 I'd like to make the following changes:
- TraceID accepts strings which are interpreted as 16 hex-encoded bytes
- SpanID accepts strings which are interpreted as 8 hex-encoded bytes

### Additional context

If this would be accepted, I can submit a PR.

**Comment by TylerHelmuth** [comment]
@kamalmarhubi what problem are you hoping to solve by allowing string in `TraceID` and `SpanID`?  If you are trying to set the span ID or trace ID using a string you can use the `span_id.string` and `trace_id.string` path accessors.

**Comment by kamalmarhubi** [comment]
🤦 nothing to see here.

(thanks @TylerHelmuth!)
