### ISSUE TITLE
[pkg/ottl]: Add Double converter

### ISSUE THREAD

**Issue by kamalmarhubi** [open-telemetry/opentelemetry-collector-contrib#22056]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

There's currently an `Int` converter, but no obvious way to force a value to be a `Double`. If you have an attribute that's a string representation of a double, it'd be nice to just parse it the way you currently for string representations of integers with `Int`.

### Describe the solution you'd like

Add a `Double` converter that can convert `Double`, `Int`, `String` values.

### Describe alternatives you've considered

The best I've come up with is going via JSON:
```
ParseJSON(Concat(["{\"value\":", attributes["some_attr"], "}"], ""))["value"]
```
which does in fact work for Double, Int, and String.

**Comment by TylerHelmuth** [comment]
@kamalmarhubi that is an ingenious workaround.

This is definitely something we want to do.  We already have `FloatLikeGetter` so this function is ready to be added.  Would you like to work on it?

**Comment by kamalmarhubi** [comment]
@TylerHelmuth sure. Should it be called Float or Double? I thought Double made more sense because it's the name of the ValueType in pcommon, but open to either.

**Comment by TylerHelmuth** [comment]
Probably Double. @dmitryax @evan-bradley do you have an opinion?

**Comment by dmitryax** [comment]
I agree with using Double

**Comment by evan-bradley** [comment]
Double makes sense to me as well.

**Comment by gord02** [comment]
Hello everyone! I have recently joined the community and I have started my contributions by working on "good first issue" tasks like this one. I wrote some code for this task here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27457. Please let me know of any suggestions you have for it.
