### ISSUE TITLE
Support for a Google Cloud Storage exporter

### ISSUE THREAD

**Issue by danieljimenez** [open-telemetry/opentelemetry-collector-contrib#22083]
### Is your feature request related to a problem? Please describe.

I'd like to have my data exported to Google Cloud Storage (similar to the AWS S3 exporter) so I can report on it via BigQuery

### Describe the solution you'd like

Build an exporter to Google Cloud Storage

### Describe alternatives you've considered

Possibly porting the S3 code to a new exporter and contributing back to OpenTelemetry project.

**Comment by JaredTan95** [comment]
hi, @danieljimenez there is no `Google Cloud Storage`, maybe you can make a proposal and contribute is welcome :-P
