### ISSUE TITLE
Send only when metrics differ from t-1

### ISSUE THREAD

**Issue by garry-cairns** [open-telemetry/opentelemetry-collector-contrib#22100]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

Persistent back ends will waste storage from collectors sending spanmetrics periodically when they don't change what was last sent.

Additionally, there's a reported "bug" (not really a bug if it's an instance of what I describe) [for which I've suggested a workaround](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21101#issuecomment-1554135248) in which setups with multiple hosts that might host the same service at different times can get weird looking metrics from the collectors on those hosts. My fix above works for this but at the expense of additional storage for persistent back ends such as influx. Only sending metrics when they show a change from t-1 would resolve this too.

### Describe the solution you'd like

If I have spanmetrics with a count of 1 at t, and a count of 1 again at t+1 (cumulative) or a delta of 0, there should be no export for those metrics.

### Describe alternatives you've considered

The alternative is to solve this at the exporter or even storage layer, but this means one needs n solutions instead of 1.

**Comment by albertteoh** [comment]
If I understand correctly, prometheus components [can mark a metric as stale](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1de40deebf2aa4993f46d2b98131e9be1817fa07/exporter/prometheusexporter/config.go#L41) if no new data points are received for a configured period of time, and handle this accordingly when [writing to](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6620)/or [responding to scrapes](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6879) from prometheus.

I'm wondering that, if we implement this enhancement, would we potentially send the wrong signal to metrics consumers that a metric is stale (i.e. failed scrape), when in fact, it's still an "active" metric but just unchanged? In particular, some prometheus functions explicitly handle stale values: https://www.robustperception.io/staleness-and-promql/.

**Comment by garry-cairns** [comment]
@albertteoh would you consider having the behaviour be configurable? Prometheus is stateless in a lot of configurations but other backends aren't, and persistent backends in particular might benefit from this I think.

**Comment by albertteoh** [comment]
Yup, I think making this configurable helps in mitigating any potential negative impact it will have on both consumers of the metrics and the collector itself (increased memory pressure and CPU load). 

However, I'd like to be convinced that this will be a useful feature for the majority of users of this component, to make it worth the effort of introducing this feature in the codebase, which I think would not be trivial, particularly if it's configurable.

@kovrus do you have any thoughts on this?

**Comment by garry-cairns** [comment]
@albertteoh makes sense. At the risk of solutionizing I think memory pressure could be kept down as it'll be effectively nil for DELTA (if 0 don't send) and 1 integer per unique service name at any given time in CUMULATIVE, which I can't imagine will ever become pathological.

**Comment by albertteoh** [comment]
A PR would be much appreciated.
