### ISSUE TITLE
Flaky test: TestRabbitmqIntegration

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#22134]
### Component(s)

receiver/rabbitmq

### Describe the issue you're reporting

go test -race -timeout 360s -parallel 4 -tags=integration,"" -run=Integration -coverprofile=integration-coverage.txt -covermode=atomic ./...
2023/05/20 00:29:42 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 20.10.24+azure-1
  API Version: 1.41
  Operating System: Ubuntu 22.04.2 LTS
  Total Memory: 6943 MB
2023/05/20 00:29:42 🐳 Creating container for image docker.io/testcontainers/ryuk:0.4.0
2023/05/20 00:29:43 ✅ Container created: 37b416e0eaaf
2023/05/20 00:29:43 🐳 Starting container: 37b416e0eaaf
2023/05/20 00:29:43 🚧 Waiting for container id 37b416e0eaaf image: docker.io/testcontainers/ryuk:0.4.0
2023/05/20 00:29:43 ✅ Container started: 37b416e0eaaf
2023/05/20 00:29:53 🐳 Creating container for image 
2023/05/20 00:29:53 ✅ Container created: dbca0177c869
2023/05/20 00:29:53 🐳 Starting container: dbca0177c869
2023/05/20 00:29:53 🚧 Waiting for container id dbca0177c869 image: 2590bc74-26ff-4986-adfc-233152809893:27da8be1-cd86-4e28-b50a-595e1e590ee4
2023/05/20 00:29:57 ✅ Container started: dbca0177c869
--- FAIL: TestRabbitmqIntegration (15.90s)
    scraperint.go:72: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/coreinternal/scraperinttest/scraperint.go:72
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/rabbitmqreceiver/integration_test.go:55
        	Error:      	Received unexpected error:
        	            	Error: this command requires the 'rabbit' app to be running on the target node. Start it with 'rabbitmqctl start_app'.Arguments given:list_users[1mUsage[0mrabbitmqctl [--node <node>] [--longnames] [--quiet] list_users [--no-table-headers] [--timeout <timeout>]: failed to start container
        	Test:       	TestRabbitmqIntegration
FAIL
coverage: 1.2% of statements
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/rabbitmqreceiver	15.952s
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/rabbitmqreceiver/internal/metadata	0.050s	coverage: 0.0% of statements [no tests to run]
?   	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/rabbitmqreceiver/internal/mocks	[no test files]
?   	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/rabbitmqreceiver/internal/models	[no test files]
FAIL

**Comment by codeboten** [comment]
happened again here https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5414732836/jobs/9842235770?pr=23837#step:5:277

**Comment by djaglowski** [comment]
I propose this test can be deleted. Riak does not provide an arm compatible image and I don't recall seeing much user activity with the receiver. The risk/reward seems worth it here.

**Comment by djaglowski** [comment]
w/r/t why this test is flaky despite being run by the `scraperinttest` framework - it has an unusually complex setup script . It's not clear how to validate or properly wait for its success, so it must be failing more than a reasonable retry loop should accommodate.
