### ISSUE TITLE
datadogexporter: Add warning to user for insecure storage of user credentials at rest

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector-contrib#2230]
**Is your feature request related to a problem? Please describe.**

When using the the datadogexporter to connect with the backend service the user has to input API tokens in plain text which is exposed at rest. This is a security exposure that needs to be communicated to the user.

**Describe the solution you'd like**

The solution proposed includes -
* adding a warning which is actively communicated to the user 
* recommend storing the token securely at rest (encryption at rest)
* recommend adding clear documentation itemizing security risks bundled in the exporter folder

**Additional context**

Unit tests exists but is not enough for an user to understand this security risk. See related unit test
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/metadata/metadata_test.go#L101

**Comment by mx-psi** [comment]
@alolita I replied on issue #2232 to see if we can find a solution shared across exporters with similar needs.
