### ISSUE TITLE
dynatraceexporter: Add warning to user for insecure storage of user credentials at rest 

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector-contrib#2231]
**Is your feature request related to a problem? Please describe.**
When using the the dynatraceexporter to connect with the vendor backend service the user has to input API tokens in plain text which is exposed at rest. This is a security exposure that needs to be communicated to the user.

**Describe the solution you'd like**
The solution proposed includes -
* adding a warning which is actively communicated to the user 
* recommend storing the token securely at rest (encryption at rest)
* recommend adding clear documentation itemizing security risks bundled in the exporter folder

**Additional context**
Unit tests exist for checking unauthorized access but these tests are not enough for an user to understand this security risk. See related unit test - 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/dynatraceexporter/metrics_exporter_test.go#L29

**Comment by arminru** [comment]
Thanks for bringing this up @alolita.
Following the discussion on #2232, I agree that we should aim for a common solution to make users aware of the risks and provide guidance. I suggest adding a link to the security document being added in https://github.com/open-telemetry/opentelemetry-collector/pull/2461 to `exporter/dynatraceexporter/README.md` (as well as the other exporters) once it is merged to make it more visible to users.
