### ISSUE TITLE
[receiver/activedirectoryds] Integration test broken

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#22480]
### Component(s)

receiver/activedirectoryds

## Description
This integration test appears to be in a broken state. It has not been running as part of the `build-and-test-windows` workflow because the "integration" build tag excludes it. (And the `integration-tests` job doesn't run it because of the "windows" build tag.)

## Steps to Reproduce
Run the test.

## Expected Result
The test runs and passes within the `build-and-test-windows` workflow.

## Actual Result
```
--- FAIL: TestIntegration (0.41s)
    integration_test.go:38: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/activedirectorydsreceiver/integration_test.go:38
        	Error:      	Received unexpected error:
        	            	failed to create performance counter watchers: failed to create perf counter with path \DirectoryServices(NTDS)\DRA Inbound Bytes Compressed (Between Sites, After Compression) Since Boot: No data to return.
        	Test:       	TestIntegration
FAIL
```

Reference: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5049858599/jobs/9059867392?pr=22157#step:7:451

### Collector version

main

### Environment information

CI

### Additional context

I noticed the failure when attempting to migrate this test to the new integration test framework in #22157. I will revert the changes, but will fix the build tags and use `t.Skip` instead.

**Comment by djaglowski** [comment]
@BinaryFissionGames, do you mind peeking at this to tell if it is an easy fix? If not I can dig into it more.

**Comment by djaglowski** [comment]
Wasn't this test working at some point? What changed that it's now impossible?

**Comment by BinaryFissionGames** [comment]
It seemed to me from this description and a (very brief) glance at the history that this test was just never running in CI. It doesn't seem like it was running on the initial commit, anyways.
