### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/opentelemetry-collector-contrib#227]
Hello,

I am aware of a k8s operator to deploy the collector but would like to propose providing a helm chart. If so  we could have a repo such as `open-telemetry/helm-charts`

**Comment by dmitryax** [comment]
I can take this task

**Comment by naseemkullah** [comment]
Please let me know if you need any help @dmitryax, [this chart](https://github.com/fluent/helm-charts/tree/master/charts/fluent-bit/templates) is great example of a chart that can be deployed as a deployment or a daemonset

**Comment by dmitryax** [comment]
Hi @naseemkullah , sorry for the delay. I'll prepare a PR next week in this repo to start with. Eventually I think we need a separate repo with it's own CI pipeline. And we would need a helm repository to host releases. Let me know if you have any other suggestions

**Comment by naseemkullah** [comment]
> Eventually I think we need a separate repo with it's own CI pipeline. And we would need a helm repository to host releases. 

💯 

Seeing that GA is approaching and I'm not sure how distributing the chart from this repo would work I suggest we go straight ahead and create `open-telemetry/helm-charts` and follow https://github.com/helm/charts-repo-actions-demo (to the T pretty much) to setup CI and release hosting.

> Let me know if you have any other suggestions

As for the chart itself what I would do, at least to get started is:
1) `helm create opentelemetry-collector` with the latest helm binary
2) [Put the pod in a helper template](https://github.com/fluent/helm-charts/blob/master/charts/fluent-bit/templates/_pod.tpl) as to avoid duplicating pod spec in the [Deployment](https://github.com/fluent/helm-charts/blob/3c4a3dbe6ad8bb50a3a6d9e3261a5bcb5d8cb211/charts/fluent-bit/templates/deployment.yaml#L23) and [DaemonSet](https://github.com/fluent/helm-charts/blob/3c4a3dbe6ad8bb50a3a6d9e3261a5bcb5d8cb211/charts/fluent-bit/templates/daemonset.yaml#L22) templates

**Comment by scottrigby** [comment]
This all makes sense. A number of projects now provide both a Helm chart and operator for installing on k8s, which is helpful depending on specific user needs and preference 👍

**Comment by dmitryax** [comment]
I have a draft PR for the helm chart https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1026. 
I'll test it more and polish this week. Any feedback would be appreciated.

Also submitted a ticket to have helm github repo from the start first https://github.com/open-telemetry/community/issues/504

**Comment by dmitryax** [comment]
The initial version of the helm chart is released in this repo https://github.com/open-telemetry/opentelemetry-helm-charts . Closing the ticked
