### ISSUE TITLE
[docs] Explicitly define component configuration documentation requirements

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/opentelemetry-collector-contrib#22710]
### Describe the issue you're reporting

Currently there is no explicit documentation regarding what percentage of configuration options must be documented in a components `README` file. This can lead to some components missing configuration options present in `config.go` but not a components `README`. 

This can present a problem for end users of that component. They will be required to read `config.go` to discover all configuration options. This also can lead to a lack of documentation for specific configuration options also by having no `README` entry or comments within `config.go`. 

I believe there should be explicit instructions around how much documentation is required when adding a new component or configuration option to an existing component. This will provide a better experience for end users of the component and contributors to that component. 

My suggestion would be to require 100 percent documentation of all configuration options in a components `README`.  Once this is resolved a follow on issue should be opened asking "how do we autogenerate component configuration docs" to ease the burden of keeping a `README` up to date.

**Comment by astencel-sumo** [comment]
In terms of autogenerating docs for configurations, I think this is related?
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5006

There was some work towards this goal:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15233

**Comment by bryan-aguilar** [comment]
It definitely looks related to me. I am not aware of the status or if it's being used anywhere though.
