### ISSUE TITLE
A new ottl function/converter to convert telemetry data to its hash value or digest

### ISSUE THREAD

**Issue by rnishtala-sumo** [open-telemetry/opentelemetry-collector-contrib#22725]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

A new ottl function/converter when invoked will transform the underlying telemetry data to a hash value or digest.

Hashing is commonly used for
- data integrity checks
- password storage (where the password itself is not stored but its hash value is)
- verifying data authenticity.

### Describe the solution you'd like

The hashing converter/function could be used with the `replace_all_matches` editor like below
- replace_all_matches(target, pattern, sha256)
- replace_all_matches(target, pattern, sha1)

The replace_all_matches function replaces any matching string value with its hash value.
`target` is a path expression to a `pdata.Map` type field. pattern is a string following [filepath.Match syntax](https://pkg.go.dev/path/filepath#Match).`sha1` is the hashing function.
Each string value in target that matches pattern will get replaced with its hash value. Non-string values are ignored.
We could define two hash functions for the following two algorithms
- SHA-256
- SHA-1 (the attributes processor uses this)

or with the `set` editor like below
- set(target, hash(value))

### Describe alternatives you've considered

An alternative to using this could be to use the attributes processor

- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor

With the hash action

```
# Key specifies the attribute to act upon.
- key: <key>
  action: hash
  # Rule specifies the regex pattern for attribute names to act upon.
  pattern: <regular pattern>
```

**Comment by TylerHelmuth** [comment]
This is functionality we should provide an a necessary step towards eventually replacing the attributes processor with OTTL (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18643).  

I think to start providing a `Hash` Converter function is the most like-for-like replacement of attributesprocessor's functionality.  If there is a need to convert all matching keys in a map then I think we should add a new function, like `hash_all_patterns`, that is specific to that use case.

The converter function should take a `StringGetter` that represents the value to be hashed. Unless there is a need I'd stick with the attributesprocessor solution and only hash with SHA-1.

**Comment by TylerHelmuth** [comment]
With @bogdandrutu suggestion we should name the function based on its algorithm like `SHA1()` as an example.

**Comment by rnishtala-sumo** [comment]
@TylerHelmuth @jpkrohling wanted to confirm, the suggestion was to use to consider using fnv hashing (non-cryptographic) instead of sha1 or sh256?

**Comment by TylerHelmuth** [comment]
I think we could provide functions for all the needed hash functions, but based on the link you provided starting with fnv is in line with collector guidelines.

**Comment by evan-bradley** [comment]
Closing as resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22968. These functions are now provided in OTTL's [standard set of Converters](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/ottlfuncs/functions.go#L34).

@TylerHelmuth I see you removed the stale label a few months ago, please reopen this if you don't feel it has been resolved.
