### ISSUE TITLE
[pkg/ottl] Add an error mode to ignore errors and silence warnings

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#22743]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

Some Collector users have requested that we add an option to silence the warning messages printed when errors occur in a set of statements running with error mode set to `ignore`. 

### Describe the solution you'd like

Add a new error mode that continues processing statements, but doesn't print error messages.

We should probably rename the `ignore` error mode if we add a new option, since `ignore` also implies that error messages may not be printed. I would propose renaming `ignore` to `warn` and adding a new `silent` error mode that accomplishes this functionality.

We should also provide guidance on when to use this feature, since if possible users should try to address error conditions in their statements.

### Describe alternatives you've considered

See if we can provide tools to address the conditions that cause the errors themselves (e.g. providing more checks for avoiding mismatched types). Allowing users to silence error messages should be considered an advanced feature since it provides the possibility of making errors invisible to users.

**Comment by TylerHelmuth** [comment]
I like the rename.  Should probably do this sooner rather than later since it is a breaking change.

**Comment by TylerHelmuth** [comment]
I think we waited too long on this name change, but I am still open to adding a `silent` options
