### ISSUE TITLE
Define K8s_Processor RBAC Setup requirements

### ISSUE THREAD

**Issue by ericmustin** [open-telemetry/opentelemetry-collector-contrib#2274]
Hello friends, 

As we approach the "1.0" phase of tracing, we've noticed a fair number of users looking to leverage the k8s_processor in the collector setup. RBAC is a common pain point here, it would be good to improve the documentation and define what requirements are needed. it seems like there are some open TODOs in this regard and if there's any clarity on timeline or roadmap here that would help greatly.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9f137ea75d249631c411b9d845e83a179032a5b8/processor/k8sprocessor/doc.go#L26-L28

**Comment by flands** [comment]
@owais @jrcamp can we get this added?

**Comment by omamoo** [comment]
Can someone attach the RBAC he uses?
