### ISSUE TITLE
issuegenerator does not work for windows in circleci

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector-contrib#2276]
It tries to run issuegenerator but it's not installed.

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/9354/workflows/0ddde697-706f-48f0-a970-7bfe4bb53e60/jobs/77180

**Comment by mx-psi** [comment]
For the specific issue on this job log see #2272 for a fix

**Comment by atoulme** [comment]
Closing, we don't use CircleCI anymore.
