### ISSUE TITLE
When adding or removing filelog receivers, offsets cannot be resumed. Because the storage are isolated from each other.

### ISSUE THREAD

**Issue by h0cheung** [open-telemetry/opentelemetry-collector-contrib#22774]
### Component(s)

pkg/stanza, receiver/filelog

## Description
Sometimes we need to use multiple filelog receivers for different files. After adding or removing receivers, the offset cannot be resumed as expected.

That's because the storage is isolated. 

## Steps to Reproduce
1. Use `filelog/1` to read both `1.log` and `2.log`. Offsets of both files will be saved.
2. Edit the config to split it to two receivers: `filelog/1`, which reads `1.log`, and `filelog/2`, which reads `2.log`. There will be a problem that `filelog/2` can't get the offset of `2.log`.
3. Then revert the change of config to use only `filelog/1`. It can't get the offset of `2.log`.

## Expected Result
All offsets should be resumed.

## Actual Result
- In step 2, `filelog/2` can't get the offset of `2.log`
- in step 3, `filelog/1` can't get the offset of `2.log`

### Collector version

v0.71.0

### Additional context

We should allow a filelog receiver to resume offsets from storage of all filelog receivers, including those removed from the configuration.

**Comment by djaglowski** [comment]
I don't believe this is a feature we should support. Storage extensions are isolated from one another by design. My suggestion is to look at implementing a custom storage extension, which wraps multiple storage extensions and manages the kind of data sharing that you'd like to see..
