### ISSUE TITLE
Azure Data Explorer Exporter permanently fails on init due to lack of retries in dependency

### ISSUE THREAD

**Issue by ben-childs-docusign** [open-telemetry/opentelemetry-collector-contrib#22771]
### Component(s)

exporter/azuredataexplorer

## Description

When using the azure data explorer exporter on a machine with a flaky network (in this case it was a windows container which was seeing network issues on launch), I saw the data explorer fail permanently due to a failed network call during initialization which gets memoized and never retried.

## Steps to Reproduce

Try to init azure data explorer exporter in an environment with flaky network.

## Expected Result

The init eventually succeeds

## Actual Result

The exporter gets stuck in a permanent failed state due to memoization in the azure-kusto-go component

### Collector version

v0.77.0

## Environment
OS: Windows 2019
Compiler(if manually compiled): go 1.19.8

### Log output

```shell
Kind(KInternal): Error while getting token : Get \"https://****.eastus.kusto.windows.net/v1/rest/auth/metadata\": net/http: TLS handshake timeout
```

### Additional context

This issue was logged in azure-kusto-go and fixed in 0.13.1
https://github.com/Azure/azure-kusto-go/issues/188

I have tested the fix locally and confirmed the issue is resolved.

**Comment by ag-ramachandran** [comment]
Hello @ben-childs-docusign, Thanks for reporting the issue, will have a look at this. 
Will try out a way if there can be retries initiated in case of network flakiness. Will keep this issue posted based on internal discussions we have.

**Comment by ag-ramachandran** [comment]
Hello @codeboten , @mx-psi. We've made a small PR:: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22933 with the SDK update and fix of all deprecations related to that.  Kindly review when you get a chance!
