### ISSUE TITLE
insecure_skip_verify=true is not working while sending trace data in datadog exporter 

### ISSUE THREAD

**Issue by sreejithav** [open-telemetry/opentelemetry-collector-contrib#22772]
### Component(s)

exporter/datadog

## Description
i am getting this error even if i set insecure_skip_verify=true ... "debug datadogexporter@v0.70.0/zaplogger.go:39 Retrying to flush trace payload; error: Post "https://trace.agent.us5.datadoghq.com/api/v0.2/traces": x509: certificate signed by unknown authority {"kind": "exporter", "data_type": "metrics", "name": "datadog"} . looks like insecure_skip_verify works only for logs not for traces.
## Steps to Reproduce
I am using opentelemetry demo apps and using Datadog exporter. 
opentelemetricSDK --> collector--> datadog 
## Expected Result
if i set insecure_skip_verify=true , it should skip certificate validation.
## Actual Result
if i set insecure_skip_verify=true , it is skipping certificate validation for logs and metrics but not for traces.

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      load:
      memory:
      network:
      processes:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: false
      ca_file: /etc/ssl/certs/cert.pem
  logging:
  prometheus:
    endpoint: "otelcol:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
  datadog:
    api:
      site: "us5.datadoghq.com"
      key: "XXXX"
    tls:
      insecure_skip_verify: true
processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
  transform:
    metric_statements:
      - context: metric
        statements:
          - set(description, "Measures the duration of inbound HTTP requests") where name == "http.server.duration"
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      exporters: [otlp, logging, datadog]
    metrics:
      receivers: [otlp]
      processors: [filter, transform, batch]
      exporters: [prometheus, logging, datadog]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]

**Comment by gbbr** [comment]
Hi there! Thanks for flagging. Indeed you are right, this is a bug. I opened a PR to fix it.
