### ISSUE TITLE
A new ottl function/editor to replace a regex pattern match with its hash value or digest

### ISSUE THREAD

**Issue by rnishtala-sumo** [open-telemetry/opentelemetry-collector-contrib#22787]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

This function/editor would be used to replace substrings (identified with a regex pattern) with a hash value/digest

### Describe the solution you'd like

There could be two approaches to this:

- Re-using the `replace_all_patterns` editor

```replace_all_patterns(target, mode, regex, sha1(replacement))```
Please refer to: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#replace_all_patterns

- Defining a new function/editor

```hash_all_patterns(target, mode, regex, sha1(replacement))```
Which is similar to `replace_all_patterns`, but accepts a `converter` as  the last argument.

### Describe alternatives you've considered

None exist.

### Additional context
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22725#issuecomment-1561534851

_No response_

**Comment by TylerHelmuth** [comment]
OTTL has no way to accept a converter as a parameter, it will always execute the converter first and use the value returned.  If we want to do either of the proposed strategies we'd need to update the grammar and the parser.

If we went with `replace_all_patterns` I think we'd first want to get https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20879 resolved.  This would allow us to pass the Converter as an optional parameter.

**Comment by rnishtala-sumo** [comment]
There currently seems to be one example of a function/editor that accepts a converter as a parameter as below

Example: ```merge_maps(attributes, ParseJSON(body), "upsert")```

where `ParseJSON` is a [converter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#parsejson)

taken from: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#merge_maps

**Comment by TylerHelmuth** [comment]
Converts can be used in parameters, but they are executed before the main function is executed.  In that example `ParseJSON` is executed and the resulting string is passed to the `merge_maps` function.

For this issue, in order for the capture group logic to work, the literal Converter function would need passed into the `replace_all_patterns` function so that it could be executed once the capture group can be expanded.

**Comment by rnishtala-sumo** [comment]
Considering the above limitation with passing a converter function, could we do this instead for the first iteration?

```hash_all_patterns(target, mode, regex, hashType)```
where hashType could take the following values

- sha1
- sha256
- fnv

`hash_all_patterns` would then call the appropriate [ottl hash function](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22725#issuecomment-1563439356), a bit like the convertCase function below:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/ottlfuncs/func_convert_case.go#L50

**Comment by TylerHelmuth** [comment]
I think I'd rather see this handled in `replace_all_patterns` with optional parameters (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20879).

**Comment by TylerHelmuth** [comment]
For extra clarity, resolving the 2 issues linked above will allow all existing users of `replace_all_patterns` to be unaffected but will also allow something like `replace_all_patterns(attributes, "value", "^kube_([0-9A-Za-z]+_)", "k8s.$$1.", converter=SHA265)`

The function already allows looking through all the attribute values for a specific pattern and then changing them dynamically based on those values; adding in extra manipulation to that action feels reasonable to enable flexible and complex transformations.

Open question: should the optional parameter accept a list of converters or can that functionality be handled via multiple statements? I believe accepting a list would be more efficient.

**Comment by TylerHelmuth** [comment]
We should also highlight in the function's documentation that the extra converters only need to be used if you are using capture groups.  If you are replacing patterns with static values you can use the existing converter logic: `replace_all_patterns(attributes, "value", "^kube_([0-9A-Za-z]+_)", SHA265("my static value"))`

**Comment by TylerHelmuth** [comment]
Ya those are definitely concerns that will need to be worked through for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22961.  The ability to pass a convert to a function may need to be "typed" so that the functions accepting them as parameters can set expectations.  Hopefully a strategy similar to `StringGetter` or `StringLikeGetter` can be used.

**Comment by rnishtala-sumo** [comment]
Also currently, `replace_pattern(target, regex, replacement)` only allows a `replacement` string. Should we also allow `replacement` to be a path expression to a string telemetry field? For example

`replace_pattern(attributes["message"], "^device=([0-9A-Za-z]+)", attributes["device_name"])`

In the above, we're replacing the device name using an attribute field.

**Comment by TylerHelmuth** [comment]
@rnishtala-sumo yes I think we can allow the replacement value to come from another attribute using `StringGetter`.  That is also a non-breaking change.

**Comment by rnishtala-sumo** [comment]
ok great, I raise a PR for this soon, supporting this would allow the user to `extract`, `hash`(using ottl functions) and `replace` as an alternative, example below:

```
  attributes/example:
    actions:
      - key: message
        pattern: "^device=(?P<device_name>\\w+)$"
        action: extract
  transform/replace:
    log_statements:
      - context: log
        statements:
          - set(attributes["device_name"], FNV(attributes["device_name"]))
          - replace_pattern(attributes["message"], "^device=([0-9A-Za-z]+)", attributes["device_name"])
```
not ideal maybe, but would love to hear thoughts on this.

**Comment by rnishtala-sumo** [comment]
Created the following PR for review based on the above discussion
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23210
