### ISSUE TITLE
[cmd/telemetrygen] Traces get dropped when generating large numbers of traces consecutively

### ISSUE THREAD

**Issue by liustanley** [open-telemetry/opentelemetry-collector-contrib#22827]
## Description
Found an issue while working on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21629 when trying to run telemetrygen with large numbers of traces, and noticed that it doesn't generate the correct number of traces. I got these results when testing:

Number of traces to be generated | Number of traces actually generated
-- | --
100 | 100
500 | 500
1000 | 997
2000 | 1530
3000 | 2300
4000 | 2050
5000 | 2920
10000 | 4360
50000 | 17700
100000 | 32200

The issue went away after adding sleep between traces.

## Steps to Reproduce

Run telemetrygen with the following command, and substitute the number of traces as needed:
```
./telemetrygen traces --otlp-insecure --traces 10000
```

Afterwards, can look at Collector logs to see how many traces were actually generated.

### Collector version

v0.77.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by edwintye** [comment]
From my limited manual testing (while trying to some load testing myself), changing [traces.go L74](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.81.0/cmd/telemetrygen/internal/traces/traces.go#L74) from/to

```go
- ssp := sdktrace.NewBatchSpanProcessor(exp, sdktrace.WithBatchTimeout(time.Second))
+ ssp := sdktrace.NewBatchSpanProcessor(exp, sdktrace.WithBatchTimeout(time.Second), sdktrace.WithBlocking())
```

resolves the issue as it blocks when exporting is slower than creating new spans. This introduces a slight penalty on the performance, but considering that generating 100000 spans takes about a second on my laptop it is probably not important.  However, I am not sure how we can write a test to verify the solution or indeed if there is another limit/value on the number of traces that can be generated even with this solution implemented.

**Comment by Frapschen** [comment]
@liustanley Hi, Can this issue close, since the PR is merged?
