### ISSUE TITLE
Cloud Monitoring (Stackdriver) receiver

### ISSUE THREAD

**Issue by ocervell** [open-telemetry/opentelemetry-collector-contrib#2286]
**Is your feature request related to a problem? Please describe.**
Query metrics from Cloud Monitoring (ex-Stackdriver) and forward push them into any export destination that OpenTelemetry support.

**Describe the solution you'd like**
Implementation of a Cloud Monitoring receiver scraping Cloud Monitoring API every X seconds.

**Describe alternatives you've considered**
Exporting metrics included in Cloud Monitoring product (not planned).

**Comment by weyert** [comment]
Yes, this would be nice to have

**Comment by weyert** [comment]
Yes, still relevant

**Comment by jpkrohling** [comment]
On behalf of the OpenTelemetry Squad at Grafana Labs, I would like to volunteer as a sponsor for this component. In addition to the component's author, the code owners (as sponsors) will be:

* @jpkrohling
* @mar4uk

While we would very much prefer the affected vendor to support this receiver, we understand they might not be interested in translating their proprietary formats into OTLP, only the other way around.

We believe that the community wants this receiver, and if community members are willing to contribute code for this, we are willing to support the community.

**Comment by dashpole** [comment]
> While we would very much prefer the affected vendor to support this receiver, we understand they might not be interested in translating their proprietary formats into OTLP, only the other way around.

Speaking for Google Cloud Monitoring, I would be happy to sponsor this receiver.  We fully support customers’ decisions to use other monitoring solutions, and are willing to help with the design and review for the component to ensure it works well.  It won’t be an officially-supported GCP product (hopefully I'll have more to share in the future), but we will do what we can to enable the community.

A few pointers, if anyone is interested in picking this up (the top section of this [GCM export architecture](https://cloud.google.com/architecture/stackdriver-monitoring-metric-export#reference_implementation_details) may also be helpful):

* Use [projects.metricDescriptors.list](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/list) to get metadata (descriptions, units, etc.) about metrics.  Do this once at the beginning and cache it, or call again as needed.
* Use [projects.timeseries.list](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list) ([go client](https://github.com/googleapis/google-api-go-client/blob/50fc7c423d3d904fa541fb2794e20dde0de8cdee/monitoring/v3/monitoring-gen.go#L14451) to query the API.  * The configuration of the component should probably mirror the query parameters
* Recommended query interval: 5 minutes
* Convert the returned TimeSeries to pdata using the reverse of the [conversion from our exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/c6c6d07a2f234db42a09cba63bcd5a94e93c2e8a/exporter/collector/metrics.go#L400).

**Comment by fatsheep9146** [comment]
@ocervell do you have time to contribute this?

**Comment by weyert** [comment]
Yes, still relevant

**Comment by dashpole** [comment]
I've spoken with someone who is interested in implementing this.

**Comment by datsabk** [comment]
@dashpole - Thanks for bringing this thread alive. I'd like to start working on this receiver and would love to collaborate with the sponsors and any others contributors alongside. 

I understand that in the past things might have changed for how GCP - We would prefer to call the component `gcpcloudmetricsreceiver`. If I have the go-ahead from the maintainers and sponsors herewith, I'd like to proceed.

**Comment by dashpole** [comment]
Other google-related components in contrib use "google" or "googlecloud" rather than "gcp", and include the name of the product if needed (googlecloudexporter, googlecloudpubsubexporter, googlemanagedprometheusexporter, googlecloudpubsubreceiver, googlecloudspannerreceiver), so please try to stay consistent with existing names if possible.  "googlecloudreceiver" or "googlecloudmonitoringreceiver" are probably the closest matches.

**Comment by datsabk** [comment]
`googlecloudmetricsreceiver` seems more relevant as Monitoring is a broader term in general. Let me know your thoughts.

**Comment by dashpole** [comment]
The reason I suggested "monitoring" is because the product name is "Google Cloud Monitoring".  E.g. the receiver for "Azure Monitor" is named `azuremonitorreceiver`.  I'm asking around to see if there are any naming conventions that can help us here.

**Comment by dashpole** [comment]
It doesn't seem like there are any existing component naming conventions.

**Comment by datsabk** [comment]
Ack @dashpole - We'll go with `googlecloudmonitoringreceiver`.

**Comment by dashpole** [comment]
See https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components for the new component process.  For the first PR, see the "First PR should include the overall structure of the new component" section.

**Comment by dashpole** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33762
