### ISSUE TITLE
Bump github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics from 0.2.1 to 0.2.3 causes issue

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#22917]
### Component(s)

exporter/datadog

### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5114664886/jobs/9195143629#step:5:189 for more info:

```
Error: ../../exporter/datadogexporter/metrics_exporter.go:189:9: assignment mismatch: 1 variable but exp.tr.MapMetrics returns 2 values
```

**Comment by mx-psi** [comment]
@liustanley can you take a look at this? It relates to DataDog/opentelemetry-mapping-go/pull/81

**Comment by songy23** [comment]
Stanley is out today, I'll take a look

**Comment by codeboten** [comment]
Thanks @mx-psi @songy23!
