### ISSUE TITLE
[SplunkHecExporter] Splunk hec exporter should not parse unknown resource attributes into log record attributes

### ISSUE THREAD

**Issue by splunkericl** [open-telemetry/opentelemetry-collector-contrib#22921]
### Component(s)

exporter/splunkhec

## Description
As an user of splunk hec exporter, I don't want data from resource attributes added into log record attributes. 
- see [source code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/splunkhecexporter/logdata_to_splunk.go#L63-L66)

There can be different resource attributes defined by different receivers. If splunk hec exporter takes in these attributes, the log records will be bloated with data unexpected. Following the standard defined in the [document](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions), there can be more resource attributes added that are not related to the logs.

## Steps to Reproduce
- Use a receiver that sends data along with resource attributes. Uses splunk hec exporter to export data

## Expected Result
- data from resource attributes aren't added as part of log record when it is sent to splunk

## Actual Result
- resource attributes data are present in splunk

### Collector version

latest

## Environment
OS: N/A
Compiler(if manually compiled): N/A

### OpenTelemetry Collector configuration

```yaml
receivers: [customReceiver]
exporters: [splunkhecexporter]
service:
  log:
    receiver: customReceiver
    exporter: splunkhecexporter
```

**Comment by atoulme** [comment]
The current mapping of resource attributes to Splunk events assumes that the user is using resource attributes as general attributes to avoid repeating them at the level of each log record.

The transformation therefore applies the following logic: first, apply resource attributes to the log record, then overlay with log record attributes. If the same attribute is present in both levels, the log record attribute overrides.

The mapping also explicitly excludes a number of specific resource attributes used to represent information that is mapped elsewhere in the event, such as source or sourcetype, or explicitly ignored, such as the token passthrough resource attribute.

If you would like to store transient information associated with a pipeline, a good way to do this is with the context. This doesn't work if batching is used however, as batching is asynchronous and will break the context.

We can also look at extending the mapping logic to allow users to exclude specific resource attributes from the transformation.

Right now, your best bet is to use a processor to drop unwanted resource attributes from the resource logs ahead of going ahead with the export.

**Comment by dmitryax** [comment]
> Right now, your best bet is to use a processor to drop unwanted resource attributes from the resource logs ahead of going ahead with the export.

This would be the right setup for users that want to reduce the payload. The HEC exporter should not maintain a "vetted" list of resource attributes and drop everything else. We need to deliver all the information and resource is a source of very important information that we cannot control.
