### ISSUE TITLE
arrow library compilation issue

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#22958]
### Describe the issue you're reporting

Compiling the binary for arm64 currently fails, see https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5124412282/jobs/9216584810?pr=22955:

```
# github.com/apache/arrow/go/v12/arrow/compute/internal/exec
Error: /home/runner/go/pkg/mod/github.com/apache/arrow/go/v12@v12.0.0/arrow/compute/internal/exec/utils.go:247:18: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)
make: *** [Makefile:275: otelcontribcol] Error 2
```

**Comment by dmitryax** [comment]
It's reported in https://github.com/apache/arrow/issues/34784 and should be fixed in the next versions
