### ISSUE TITLE
[receiver/filestats] Missing configuration documentation

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector-contrib#22974]
### Component(s)

receiver/filestats

### What happened?

The File Stats receiver is already in contrib distro, but the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.78.0/receiver/filestatsreceiver/README.md) lacks any documentation on configuring the receiver.

### Collector version

v0.78.0

**Comment by astencel-sumo** [comment]
That would be great @DewaldDeJager - assigning this to you then! Thanks!

**Comment by DewaldDeJager** [comment]
@MovieStoreGuy beat me to it. You can review the latest config [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/filestatsreceiver/README.md) and if you're happy this issue can be closed.

**Comment by astencel-sumo** [comment]
Fixed in #23030
