### ISSUE TITLE
Document max_event_size on splunkhecexporter

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#22988]
### Component(s)

exporter/splunkhec

## Description
`max_event_size` is now part of config but not listed in README.

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by JaredTan95** [comment]
closed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22999
