### ISSUE TITLE
Document which components are included in the AWS Distro for OpenTelemetry Collector (ADOT)

### ISSUE THREAD

**Issue by DewaldDeJager** [open-telemetry/opentelemetry-collector-contrib#22980]
### Describe the issue you're reporting

The ADOT repo lists the components that are included in the distribution in [this table](https://github.com/aws-observability/aws-otel-collector/#adot-collector-built-in-components).

The Metadata Generator allows us to specify in this repo which distributions components are bundled in. The ADOT is already listed as one of the distributions recognized:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/cd428dedc54848327c9cb16546fdd318e58e745d/cmd/mdatagen/statusdata.go#L17

Most of the components listed in the table referenced above don't have the ADOT listed in their metadata file. For example, the `prometheusreceiver` is included in the table in the ADOT repo but ADOT is not listed in it's metadata file:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/cd428dedc54848327c9cb16546fdd318e58e745d/receiver/prometheusreceiver/metadata.yaml#L7

The purpose of this issue is to add ADOT to the list of distributions in the metadata file of each of the components that are bundled in the ADOT.

**Comment by DewaldDeJager** [comment]
I would like to work on this issue if we are happy to add this to the metadata.

**Comment by dmitryax** [comment]
@DewaldDeJager, thanks for offering the help

**Comment by DewaldDeJager** [comment]
This issue can be closed as the PR was merged.
