### ISSUE TITLE
[receiver/httpcheck] make `httpcheck.duration` metric optional

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector-contrib#22996]
### Component(s)

receiver/httpcheck

### Version

v0.78.0

### Is your feature request related to a problem? Please describe.

Currently, the default metrics emitted by the HTTP Check receiver are:
- httpcheck.duration - 1 data point per scrape
- httpcheck.status - 5 data points per scrape
- httpcheck.error - only in case of error connecting to the endpoint

I believe a reasonable default is to only emit the `httpcheck.status` metric, with the `httpcheck.duration` metric as optional.

### Describe the solution you'd like

Make `httpcheck.duration` metric optional.

### Describe alternatives you've considered

Users can use a filtering processor in the pipeline to remove the `httpcheck.duration` if they don't want it.

UPDATE: Users can also of course disable the metric in the reciever's configuration:

```yaml
receivers:
  httpcheck:
    metrics:
      httpcheck.duration:
        enabled: false
```

### Additional context

Telemetry is costly. We want to be wary introducing default metrics. This component is in `Development` stability level, which is a good time to make changes like this.

**Comment by codeboten** [comment]
The `httpcheck.duration` metric is really useful to identify changes or issues in the networking to the destination they're checking. Someone could continue to receive the same status with significant variations in the duration, which could indicate an issue the status alone wouldn't.

I wonder if only sending the status code that contains a `1` value would be a useful feature for folks interested in reducing the amount of telemetry this receiver is producing.

**Comment by astencel-sumo** [comment]
I agree that there is value in the duration metric, but I'm not convinced this is what a user would expect as a default metric. To me, when I think of an "HTTP check", i see a single value of "0" or "1" - succeeded or not. That's the basic information. Duration is valuable, but I'd make it optional.

Anyway, this is not a big deal, as the metric can be simply disabled via configuration.
