### ISSUE TITLE
[receiver/httpcheck] `endpoint` property should have no default

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector-contrib#22995]
### Component(s)

receiver/httpcheck

### Version

v0.78.0

### Is your feature request related to a problem? Please describe.

Currently, the default value for the `endpoint` property is `localhost:80`. I don't think it makes a good default.

### Describe the solution you'd like

The `endpoint` property should be required, without a default. I believe this is what what most other components do.

**Comment by codeboten** [comment]
I would be ok with changing this 👍🏻

**Comment by astencel-sumo** [comment]
Great, thanks! I'll prepare a PR.

**Comment by astencel-sumo** [comment]
Created the PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23018

**Comment by codeboten** [comment]
Thanks @astencel-sumo!
