### ISSUE TITLE
prometheus exporter metric & label naming allows unicode chars

### ISSUE THREAD

**Issue by vishiy** [open-telemetry/opentelemetry-collector-contrib#23015]
## Description
世 is not a valid character allowed in prometheus metric name/label name, but otel --> prometheusexporter exposes that as a valid character with 世 in name

### Collector version

latest

### Environment information

ubuntu 20.4

**Comment by vishiy** [comment]
@eata7

**Comment by crobert-1** [comment]
This functionality is done by the [prometheus translator package](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheus/README.md), rather than at the exporter level. Please enable this and see if it resolves the issue.
