### ISSUE TITLE
[receiver/receivercreator] Make documentation clear on the effects of using the receiver across different signals

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23014]
### Component(s)

receiver/receivercreator

### Is your feature request related to a problem? Please describe.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19641#discussion_r1212732157

### Describe the solution you'd like

We should make sure the documentation is accompanied by a few examples to clarify the use case of using the receivercreator across different signals.

**Comment by theletterf** [comment]
@atoulme Happy to help. I indeed got wrong the part about the Collector crashing. What I understand now from the previous PR is that a receiver instantiated in pipelines with incompatible telemetry types might *not* crash when they should? 

We need to get the following clear:

- Why this is an issue, in practical terms.
- What are the conditions for this to happen.
- How can this be avoided or mitigated.

The existing note only partially covers the second item.
