### ISSUE TITLE
[receiver/httpcheck] collection interval is documented as 60s but is in fact 10s

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector-contrib#23019]
### Component(s)

receiver/httpcheck

## Description

The README describes `collection_interval` to have a default of `60s` ([source](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.78.0/receiver/httpcheckreceiver/README.md?plain=1#L35)), but in reality it is implemented as `10s` ([source](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.78.0/receiver/httpcheckreceiver/factory.go#L36)).

Which one should it be?

### Collector version

v0.78.0

**Comment by crobert-1** [comment]
Also, just for context, this mismatch has been around since the httpcheck receiver was [created](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/bf9686b926d088f4d1c1726d536ee85f50951e82), it's not the result of a later change.
