### ISSUE TITLE
Clarify "Rotating Sponsors" section of CONTRIBUTING.md

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23024]
### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#rotating-sponsors

This section mentions a few things that are unclear to me:
> The following GitHub users are the currently available sponsors, either by being an approver or a maintainer of the contrib repository.

Is that to be updated to add more people as they join the approver and maintainer roles?

> Whenever a sponsor is picked from the top of this list, please move them to the bottom.

Who moves them to the bottom?

**Comment by djaglowski** [comment]
The intent is to assign sponsors from this list only when a vendor-specific component is proposed. It's mentioned [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b5c037793d2418bcf49dfc2ab5947497e2f31aa1/CONTRIBUTING.md?plain=1#L100) but not in the section you linked. Perhaps some reorganization or linking of the content is in order.

**Comment by atoulme** [comment]
Closing as it seems rereading this again that we can make this work.
