### ISSUE TITLE
User should have a way to authorize HTTP requests

### ISSUE THREAD

**Issue by splunkericl** [open-telemetry/opentelemetry-collector-contrib#23022]
### Component(s)

receiver/splunkhec

### Is your feature request related to a problem? Please describe.

As an user of splunk hec receiver, I want a way to authorize HTTP requests.

Similar to splunk enterprise validating HEC http requests with HEC tokens, some customers are looking similar ways to authorize HEC tokens for http requests their hec receiver receive. This prevents their otel collector instances to ingest data from potential attackers.
- e.g: hec receiver -> s3 exporter would have no validation on data ingestions

### Describe the solution you'd like

We can start with something very simply. Let the users configure a list of hec tokens that can be allowed to ingest data.
- users are forced to provide hec token in HTTP request
- if the token in a HTTP request doesn't match from the provided list, request is rejected with 401. 

### Describe alternatives you've considered

An alternative is to create a processor to validate these tokens sent along. However, throwing an error in the processor returns 500 errors up, which is the unexpected status code for such scenarios.

**Comment by atoulme** [comment]
This is currently supported via extensions that extend the behavior of the http server serving requests as part of the hec receiver.

You should be able to use the following extensions:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/bearertokenauthextension
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oidcauthextension
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oauth2clientauthextension

You can also implement your own auth extension to fulfill your requirements using the package https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/auth and relying on https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/configauth.

The receiver gets this ability through its config extending HTTPServerSettings:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/splunkhecreceiver/config.go#L21

HTTPServerSettings itself brings the auth settings under the `auth` key here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/confighttp.go#L55

Please let me know if this fulfills your use case.

**Comment by splunkericl** [comment]
@atoulme I think the bearer token auth would make sense for us to use. However, it seems that extension only supports one token. Is there a ticket to support multiple tokens?

The use case we are thinking is token rotation:
- If there is only one token, the users have to stop ingesting data, change token, change token it will set for the HTTP client, then start ingesting data again. The process is disruptive.
- If multiple tokens are accepted, users just need to add the new token, update HTTP client to use it, then they can remove the old token without stopping data ingestion.

**Comment by atoulme** [comment]
We can decompose this a bit I think. You're not really advocating for multiple tokens at the same time, you're saying that we should allow to rotate an existing token using a config update, and we should be able to update the http client when that config change takes place to update the token in use.

Would you want that token change to be transactional, ie the token change and client update happens in the same call and return once the token has updated successfully?

Would you want this to be eventually consistent, where the token update and the client update happens out of band later, or based off a mechanism such as a date and time?

My strong preference would go to the second approach, in which case we can load multiple tokens at once and examine them in sequence and pick the one that is currently effective.

Updating the configuration is a separate mechanism that is of debate. I'm not sure how we'd go about that. In your case, I take it that you'd programmatically update the `*Config` object we have on the exporter. Is that correct?

**Comment by splunkericl** [comment]
> My strong preference would go to the second approach, in which case we can load multiple tokens at once and examine them in sequence and pick the one that is currently effective.

For the second approach, by eventual consistent, do you mean:
1. the extension would accept two tokens for a short period and eventually get rid of the new one?
2. or the extension will eventually toggle from the old token to the new token?
The second method will still have a small gap.

And maybe all these can be the eventual state so clients can control the token programatically. But the immediate state for us is that customer will specify the tokens on the UI and the tokens will propagate to our otel collector instance and configs are updated.
