### ISSUE TITLE
Looking for an example to use AWS kinesis as exporter/collector in AWS lamabda java

### ISSUE THREAD

**Issue by pradeepkusingh** [open-telemetry/opentelemetry-collector-contrib#23021]
### Describe the issue you're reporting

Looking for an example to use AWS kinesis as exporter/collector in AWS lamabda java

**Comment by astencel-sumo** [comment]
If I understand correctly, you want to export telemetry (logs/metrics/traces) from an AWS lambda function instrumented with the [OpenTelemetry Java](https://opentelemetry.io/docs/instrumentation/java/) instrumentation to AWS Kinesis?

If that's the case, I believe Java instrumentation does not support exporting straight to AWS Kinesis. You'd need to set up the instrumentation to export to OTLP, and have an OpenTelemetry Collector instance with an [OTLP receiver](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.80.0/receiver/otlpreceiver) (to accept the telemetry from the Java instrumentation) and the [AWS Kinesis exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.80.0/exporter/awskinesisexporter).

Does this make sense?

**Comment by bryan-aguilar** [comment]
this may be better suited for https://github.com/open-telemetry/opentelemetry-lambda
