### ISSUE TITLE
Metric metadata in  exporter/prometheusremotewriteexporter as provided in exporter/prometheusexporter

### ISSUE THREAD

**Issue by gayatrigunnala** [open-telemetry/opentelemetry-collector-contrib#23032]
### Component(s)

exporter/prometheusremotewrite

### Is your feature request related to a problem? Please describe.

Please add export of metric metadata from prometheusremotewriteexporter along with metric data,
Thank you in Advance

for reference: prometheusexporter ,
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a33b9021422a000ed3feeaa8d522c31f055e7c34/exporter/prometheusexporter/collector.go#L137

Example output data:
prometheus-remote-write output:
curl -G http://localhost:6002/prometheus/api/v1/metadata?metric=pressure
{"status":"success"}

prometheus-output:
curl 'http:/-G http://localhost:9090/api/v1/metadata?metric=otelcol_prom_pressure           
{"status":"success","data":{"otelcol_prom_pressure":[{"type":"gauge","help":"","unit":""}]}}

expected: proper metadata

### Describe the solution you'd like

Please add export of metric metadata from prometheusremotewriteexporter along with metric data,

**Comment by kovrus** [comment]
related issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13849
