### ISSUE TITLE
Support sending arbitrary tracing events to Elastic APM Server

### ISSUE THREAD

**Issue by ohadravid** [open-telemetry/opentelemetry-collector-contrib#2305]
**Is your feature request related to a problem? Please describe.**
When using the Elasticsearch exporter, tracing events generated as part of a span are not sent to Elasticsearch.
For example, this code:
```
from opentelemetry import trace

tracer = trace.get_tracer(__name__)

with tracer.start_as_current_span("my_span") as span:
    span.add_event("my_event")
```
will only generate the `my_span` span, while `my_event` will be ignored.

This is line with [this comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/elasticexporter/internal/translator/elastic/traces.go#L371) in the exporter, saying it's a TODO.

**Describe the solution you'd like**
I'd like those events to be sent to Elasticsearch, just like they are sent to other backends.

**Describe alternatives you've considered**
We currently work around this by doing something like `def add_event(name): with tracer.start_as_current_span(name): pass` in Python, but in Rust for example that's not as easy.

Thanks!

**Comment by cyrille-leclerc** [comment]
As Elastic APM is now exposing an OTLP intake that is intended to replace the Otel Collector Exporter for Elastic, this issue is now tracked on https://github.com/elastic/apm-server/issues/4715
