### ISSUE TITLE
Adopt gopsutil context passing locations instead of using env vars

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23055]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

With https://github.com/shirou/gopsutil/issues/1438 resolved, the next release of gopsutil will allow to pass values as part of the context rather than using environment variables.

### Describe the solution you'd like

Use this approach with hostmetricsreceiver and any other receiver that needs this.

**Comment by atoulme** [comment]
This should touch this code in particular: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/44c888201235e2a81e52a4a71300aeb96676298c/receiver/hostmetricsreceiver/hostmetrics_linux.go#L45

**Comment by braydonk** [comment]
I'd like to work on this for KubeCon NA Contribfest.

**Comment by braydonk** [comment]
Just kidding it looks like this is already done but the issue was left open
