### ISSUE TITLE
[processor/k8sattributes] Excessive heap usage from `k8sattributes` processor after 0.78.0 upgrade

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-collector-contrib#23067]
### Component(s)

processor/k8sattributes

## Description
We recently upgraded the collector to 0.78.0 and are noticing a massive increase in CPU utilization.  It seems that the main cause is increase in GC activity.  Looking at the heap profile I see k8sattributes processor as a top culprit

```
(pprof) top15 -cum
Showing nodes accounting for 0, 0% of 235.31MB total
Dropped 133 nodes (cum <= 1.18MB)
Showing top 15 nodes out of 111
      flat  flat%   sum%        cum   cum%
         0     0%     0%   206.69MB 87.84%  sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).object
         0     0%     0%   206.69MB 87.84%  sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).unmarshal
         0     0%     0%   206.69MB 87.84%  sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).value
         0     0%     0%   206.69MB 87.84%  sigs.k8s.io/json/internal/golang/encoding/json.Unmarshal
         0     0%     0%   205.69MB 87.42%  k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).unmarshal
         0     0%     0%   205.69MB 87.42%  sigs.k8s.io/json.UnmarshalCaseSensitivePreserveInts (inline)
         0     0%     0%   204.69MB 86.99%  k8s.io/apimachinery/pkg/runtime.WithoutVersionDecoder.Decode
         0     0%     0%   204.69MB 86.99%  k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode
         0     0%     0%   203.69MB 86.57%  sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).array
         0     0%     0%   187.18MB 79.55%  k8s.io/client-go/rest.Result.Into
         0     0%     0%   186.18MB 79.12%  k8s.io/client-go/kubernetes/typed/apps/v1.(*replicaSets).List
         0     0%     0%   182.68MB 77.63%  github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor/internal/kube.replicasetListFuncWithSelectors.func1
```

### Collector version

0.78.2

## Environment
Kubernetes

### OpenTelemetry Collector configuration

```yaml
processors:
  k8sattributes:
    filter:
      node_from_env_var: K8S_NODE_NAME
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: resource_attribute
        name: k8s.namespace.name
      - from: resource_attribute
        name: k8s.pod.name
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: connection
    extract:
      labels:
      - key: app.kubernetes.io/name
        from: pod
```

### Additional context

This appears to be caused by  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14003 where the processor started tracking replica sets.

CPU usage before/after upgrade
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/381302/e6958e83-29b9-4fb5-9a77-60f5dfe98173)

**Comment by sirianni** [comment]
Disabling metadata extraction for `k8s.deployment.name` and `k8s.deployment.uid` significantly improves CPU utilization

```yaml
    extract:
      metadata:
      - k8s.namespace.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.node.name
      - container.image.name
      - container.image.tag
```

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/381302/faa2622e-60b4-4fda-a5d8-85db7d2c2df9)

**Comment by dmitryax** [comment]
@fatsheep9146, can you please work on this issue and see what allocations we can avoid?

**Comment by dmitryax** [comment]
@sirianni thanks for reporting!

> Disabling metadata extraction for k8s.deployment.name and k8s.deployment.uid significantly improves CPU utilization

Does it go back to the original (pre-upgrade) level?

**Comment by sirianni** [comment]
Is there a way to get the (perhaps imperfect?) `k8s.deployment.name` attribute back?  We don't really care about the deployment UID but would like to avoid all of this overhead of replicaset bookkeeping.

**Comment by fatsheep9146** [comment]
> @fatsheep9146, can you please work on this issue and see what allocations we can avoid?

No problem, I will check about this. @dmitryax

**Comment by dmitryax** [comment]
@fatsheep9146 I think I know what's going on. Eric runs it on the agent with a node selector, so the pods informer has a limited set of pods to watch. The replicaset informer, on the other hand, cannot have a node selector, so we keep a state about all the replicasets in the whole cluster, which can be pretty big.

One option is to get rid of the replicaset informer and populate the pod -> rs -> deployment data right in the `Pod` struct every time a pod added/updated.

**Comment by fatsheep9146** [comment]
The replicaset informer was added due to the issue of , which want to add k8s.deployment.uid support. In that issue, we have discussed about how to produce the `k8s.deployment.name`

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12936#issuecomment-1208944998

So I think maybe we can do like this way
- if only 'k8s.deployment.name' is specified, we use the pod struct to parse the deployment name with regex 
- if 'k8s.deployment.uid' is specified, we use replicaset informer.

@dmitryax WDYT

**Comment by dmitryax** [comment]
I don't believe we have to use the replicaset informer. We don't need any dynamic data from it that can be changed without rolling the pod. So we need to watch for pods only, not replicasets. We can fetch replicaset and deployment data only when pod got changed or added. To avoid high-frequency calls to k8s API for a pod in crash loop, we can utilize some lru cache for replicasets instead of the informer.

**Comment by fatsheep9146** [comment]
> I don't believe we have to use the replicaset informer. We don't need any dynamic data from it that can be changed without rolling the pod. So we need to watch for pods only, not replicasets. We can fetch replicaset and deployment data only when pod got changed or added. To avoid high-frequency calls to k8s API for a pod in crash loop, we can utilize some lru cache for replicasets instead of the informer.

Ok, I got your point, you mean we don't need cache all replicaset data through informer, but we should use lru cache to cache the replicasets which has pods we already watched. And only update the caches when a new pod is added.
I thinks the existing pod is updated should not indicate the replicase it updated, because if the replicaset is changed, it should always create new pod and remove old pods.

@dmitryax

**Comment by dmitryax** [comment]
> Ok, I got your point, you mean we don't need cache all replicaset data through informer, but we should use lru cache to cache the replicasets which has pods we already watched. And only update the caches when a new pod is added.

Yes

> I thinks when the existing pod is updated, it should not indicate that the replicaset is also updated, because if the replicaset is changed, it should always create new pod and remove old pods.

Not sure I understand this. We have a handler for a new pod, as well as a handler for a pod update. The first one would always be a cache miss for the replicaset cache, so we need to make another call to k8s api to fill it. The second one is likely always a cache hit.

**Comment by fatsheep9146** [comment]
> > Ok, I got your point, you mean we don't need cache all replicaset data through informer, but we should use lru cache to cache the replicasets which has pods we already watched. And only update the caches when a new pod is added.
> 
> Yes
> 
> > I thinks when the existing pod is updated, it should not indicate that the replicaset is also updated, because if the replicaset is changed, it should always create new pod and remove old pods.
> 
> Not sure I understand this. We have a handler for a new pod, as well as a handler for a pod update. The first one would always be a cache miss for the replicaset cache, so we need to make another call to k8s api to fill it. The second one is likely always a cache hit.

Ok, I basically understand your idea, I will try to fix this in this way.

Speak of LRU cache, do you know any component in collector-contrib has similar implementation that I can import?

@dmitryax

**Comment by fatsheep9146** [comment]
> @fatsheep9146 looks like `github.com/hashicorp/golang-lru/simplelru` is [commonly](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b96a789084aa34a47d1e848b188020a0106666d3/connector/spanmetricsconnector/internal/cache/cache.go#L18) [used](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b96a789084aa34a47d1e848b188020a0106666d3/extension/observer/ecsobserver/fetcher.go#L17) in this repository. Seems like a good option.

Thanks! @gbbr

**Comment by dmitryax** [comment]
@swiatekm-sumo sounds like a good idea to reduce the size of the items fetched by the informer. It'd be great if you can upstream it. But we still need to solve this issue to avoid fetching all the replicasets in the agent mode.

**Comment by dmitryax** [comment]
@fatsheep9146 github.com/hashicorp/golang-lru/simplelru or `internal/common/ttlmap` as another option

**Comment by swiatekm-sumo** [comment]
> > keep the ReplicaSet footprint low enough that we could just store all of them.
> 
> I agree with @dmitryax that if the `Node` (or `NodeFromEnvVar`) filter is specified then the processor should make a very strong attempt to only store metadata for pods related to that node. We run some very large Kubernetes clusters (600+ nodes) and it's very inefficient and unnecessary for a DaemonSet collector to store metadata for resources not on its local node.
> 
> No matter how small the footprint is, it's very desirable to have memory usage be `O(# pods on node)` instead of `O(# pods on cluster)`, since the former is much more fixed.
> 
> Also, when running in agent / DaemonSet mode, it's critical for the collector's footprint to be as low as possible. Storing any unnecessary metadata should be avoided.

This is a good point, and I agree that controlling resource consumption for DaemonSet Pods is very important. For the SetTransform optimization, this isn't an either/or thing - we can do it anyway for Pods, and reduce the memory footprint further even without having enabled any metadata requiring ReplicaSets.

I do want to point out though, that in this case (of the solution discussed in this issue) the agent and gateway requirements are somewhat opposed. The agent running as a DaemonSet wants to only store the metadata relevant to Pods on its Node, and is (presumably, as we haven't tested this) fine doing some synchronous requests to the API Server if that means avoiding having to store global cluster state. On the other hand, the gateway *needs* the whole cluster state, and is definitely not fine making a single synchronous request for each ReplicaSet in a busy cluster.

In an ideal world, we would use different approaches for these use cases, but that significantly increases the maintenance burden and complexity of the processor. So we might need to compromise one way or another.

Out of curiosity, if we implemented the SetTransform optimizations and achieved lower memory consumption even while storing all ReplicaSets, would you be unhappy with that outcome?

**Comment by dmitryax** [comment]
@swiatekm-sumo, thanks for pointing this out. I agree differentiating the logic based on the collector's deployment topology is not an ideal solution. Let's apply your optimization both to pods and replica sets informers first and see what the outcome will be. @swiatekm-sumo, do you have a chance to submit a PR given that you did in your fork?

**Comment by fatsheep9146** [comment]
I also agree with @swiatekm-sumo, the `SetTransform` optimization is beneficial to both gateway mode and daemonset mode.
I think the optimization for daemonset model is better to be based on the `SetTransform` optimization.

@dmitryax @sirianni

**Comment by swiatekm-sumo** [comment]
Yep, I can work on it. You want to assign this issue to me or should we track the SetTransform change separately?

**Comment by dmitryax** [comment]
@sirianni the new version 0.80.0 is out. Can you please try this out and see what is the RAM usage in your cluster with `k8s.deployment.name` enabled?

**Comment by fatsheep9146** [comment]
ping @sirianni , do you have tried this?

**Comment by sirianni** [comment]
We are still seeing significantly elevated memory usage and GC churn (CPU) after the upgrade.

I don't think it's quite as bad as before, but it's still elevated enough that we'll have to resort to a workaround of disabling that `k8s.deployment.name` attribute.  Again, this is a daemonset pod that runs co-located with all of our actual applications, so CPU and Memory is at a premium.

I realize the code complexity you are dealing with trying to balance "agent mode" vs. "gateway mode", but I would very much appreciate restoring the previous behavior that didn't have this issue.  I'd rather have a slightly imperfect `k8s.deployment.name` attribute (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12936#issuecomment-1208944998) then this increase in resource utilization.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/381302/124387e9-ebcf-4251-be07-9c2533f0a53d)

**Comment by sirianni** [comment]
```
$ go tool pprof ./bin/collector http://localhost:1777/debug/pprof/heap
File: collector
Build ID: 79c5900955e9865a447786690c0e370565a2dd56
Type: inuse_space
Time: Jul 11, 2023 at 1:13pm (EDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top15 -cum
Showing nodes accounting for 11.51MB, 23.48% of 49.04MB total
Showing top 15 nodes out of 285
      flat  flat%   sum%        cum   cum%
         0     0%     0%    11.51MB 23.48%  k8s.io/client-go/tools/cache.(*DeltaFIFO).Resync
       1MB  2.04%  2.04%    11.51MB 23.48%  k8s.io/client-go/tools/cache.(*DeltaFIFO).queueActionLocked
         0     0%  2.04%    11.51MB 23.48%  k8s.io/client-go/tools/cache.(*DeltaFIFO).syncKeyLocked
         0     0%  2.04%    11.51MB 23.48%  k8s.io/client-go/tools/cache.(*Reflector).startResync
         0     0%  2.04%       11MB 22.44%  runtime.main
         0     0%  2.04%    10.51MB 21.44%  github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor/internal/kube.New.func2
   10.51MB 21.44% 23.48%    10.51MB 21.44%  github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor/internal/kube.removeUnnecessaryReplicaSetData (inline)
         0     0% 23.48%        6MB 12.24%  main.main
         0     0% 23.48%     5.53MB 11.29%  runtime.doInit
         0     0% 23.48%     5.52MB 11.25%  k8s.io/apimachinery/pkg/runtime.WithoutVersionDecoder.Decode
         0     0% 23.48%     5.52MB 11.25%  k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode
         0     0% 23.48%     5.52MB 11.25%  k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).unmarshal
         0     0% 23.48%     5.52MB 11.25%  k8s.io/client-go/tools/cache.(*ListWatch).List
         0     0% 23.48%     5.52MB 11.25%  k8s.io/client-go/tools/cache.(*Reflector).list.func1
         0     0% 23.48%     5.52MB 11.25%  k8s.io/client-go/tools/cache.(*Reflector).list.func1.2
```

**Comment by dmitryax** [comment]
I attribute the high churn to the creation of new instances in the `removeUnnecessaryReplicaSetData` function. @swiatekm-sumo, maybe we can reuse exiting instances and cut off the redundant fields instead?

**Comment by swiatekm-sumo** [comment]
> I'd attribute the high churn to the creation of new instances in the `removeUnnecessaryReplicaSetData` function. @swiatekm-sumo, maybe we can reuse exiting instances and cut off the redundant fields instead?

We could. I originally didn't because it's more complicated to reason about and maintain. If we do want to change it, I'd like to see a benchmark showing it actually shows improvement before we merge the change.

**Comment by swiatekm-sumo** [comment]
Strange, it should only create that one if you have either `k8s.deployment.name` or `k8s.deployment.uid` in your metadata attributes list.

**Comment by sirianni** [comment]
> emulate it using the transform processor

Here is the YAML for anyone else reading
```yaml
  transform/k8s_attributes:
    metric_statements:
    - context: resource
      statements:
      - set(attributes["k8s.deployment.name"], attributes["k8s.replicaset.name"])
      - replace_pattern(attributes["k8s.deployment.name"], "^(.*)-[0-9a-zA-Z]+$", "$$1")
      - delete_key(attributes, "k8s.replicaset.name")
    trace_statements:
    - context: resource
      statements:
      - set(attributes["k8s.deployment.name"], attributes["k8s.replicaset.name"])
      - replace_pattern(attributes["k8s.deployment.name"], "^(.*)-[0-9a-zA-Z]+$", "$$1")
      - delete_key(attributes, "k8s.replicaset.name")
```

**Comment by matej-g** [comment]
This is still needed, should not be stale.

**Comment by robincw** [comment]
Issue coming up to 1 year birthday 🍰

**Comment by swiatekm-sumo** [comment]
Thinking about this more, I'd be surprised if optimizing the transform function would help much here as suggested by @dmitryax in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23067#issuecomment-1631206263. We're really only allocating an additional struct, all the data we put in it is already allocated and shouldn't trigger any copies. My expectation would be that the churn is simply from deserializing ReplicaSet structs in the Watch.

I don't think we can do much about that cost, but maybe we can update less frequently? For Deployment/StatefulSet/DaemonSet names, we only care about the ReplicaSet owner references. While those references are technically mutable, they will only really change due to relatively rare events. So maybe we could set the ReplicaSet watch to only trigger on Create, and let periodic resync take care of any owner reference discrepancies?

**Comment by swiatekm** [comment]
Having looked into this a bit more, I don't think the K8s API lets us have a watch on only ADDED notifications. We can of course ignore the notification based on type, but at that point we've already deserialized it, and probably paid most of the final cost of processing it.

I think what we could do instead is ask for only metadata updates for ReplicaSets (and probably other resource types as well). client-go has a metadata-only informer, and for a lot of resources, metadata is all we need. That should help with memory usage and GC pressure.

**Comment by mildmojo** [comment]
I don't see why this issue should be closed if the performance problem still exists. AFAICT, it's currently unsafe to use `k8sattributesprocessor` without the cumbersome replicaset workaround detailed in the comments on this issue.

Perhaps the workaround should be the default behavior of the processor, and the expensive, correct behavior should be put behind a configuration flag?

**Comment by swiatekm** [comment]
@mildmojo it's closed because currently nobody is working on it. If you'd like to contribute a fix, we'd be happy to accept it. There is a way to make the correct behavior cheap, as I've described in my earlier [comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23067#issuecomment-2206809451), so I'd strongly prefer that over going back to the somewhat incorrect workaround.

**Comment by ChristianCiach** [comment]
I've been reading past issues and PRs involving the code and I don't understand why we need to actually retrieve the ReplicaSets *at all*. Yes, there is no way around it to retrieve `k8s.deployment.uid`, but `k8s.deployment.name` can be easily retrieved per RegEx from `.metadata.ownerReferences` of the pod-spec by finding the element where `kind: ReplicaSet` (and optionally `controller: true` to be absolutely sure).

There has been a bug in the past where the `k8s.deployment.name` has been wrongly set for StatefulSets, but this obviously won't happen when extracting the the name from the ReplicaSet-owner-reference.

At first I thought there was a slight risk in this approach in cases where the originally deployed resource wasn't a `Deployment` but a `ReplicaSet` (but who uses these in this day and age?), but those ReplicaSets are extremely unlikely to match the deployment-extraction-regex. 

This would make it easily possible and robust to retrieve `k8s.deployment.name` without any need to retrieve the actual ReplicaSets from the Kubernetes API.

**Comment by swiatekm** [comment]
@ChristianCiach if you can show an approach that does this and is based on properties guaranteed by the K8s API (and not just conventions it currently happens to follow), then we'll definitely consider it.

**Comment by ChristianCiach** [comment]
@swiatekm This is, in isolation, a fair request. But it ignores the fact that the k8sattributes-processor relies on such conventions *right now* to extract replicaset-names and cronjob-names from pods and jobs respectively: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/61876636df27d7eec8de3581b8edc257d8f661cc/processor/k8sattributesprocessor/internal/kube/client.go#L96-L103

I don't see a compelling reason for why this is fine for extracting replicaset- and cronjob-information, but is somehow not fine for extracting deployment information from a replicaset-name

**Comment by swiatekm** [comment]
We should fix those as well. As you say, there's no need to do the ReplicaSet extraction from Pod names, and there should be a justification for the CronJob regex.

**Comment by ChristianCiach** [comment]
> We should fix those as well. 

This is questionable. Yes, this would be more *correct*, no question there! But this would incur even more memory usage and kubernetes api requests for absolutely no in-real-world gain. It would also require additional RBAC permissions, which I would like to avoid if possible.

**Comment by swiatekm** [comment]
The real-world gain is that the processor won't break because of a change Kubernetes might make in a minor release. If you believe they won't make such a change, please provide some justification for that belief. I'd accept, for example, an argument that Kubernetes hasn't changed this since 1.0 and that maintainers of the relevant SIG have stated it can only be changed via the standard feature promotion process.

To be clear, this isn't a gotcha or a roundabout rejection of your idea. I don't know how stable these naming conventions are.

**Comment by ChristianCiach** [comment]
> To be clear, this isn't a gotcha or a roundabout rejection of your idea. I don't know how stable these naming conventions are.

Well, at the very least they haven't changed in the last 5 years or so (since I've started doing Kubernetes stuff :) ) and changing the naming scheme would be a breaking change for all existing ReplicaSets/Deployments/Jobs out there.

But I don't feel very strongly about this, so I won't pursue this further. If you think the processor should use the proper APIs for this, this is a fine opinion and I won't try to convince you otherwise. I just tend to be a bit more pragmatic about this stuff. If it works in real life and there is an extremely low chance of breaking (which I believe this to be the case here), then this is usually good enough for me.

**Comment by ChristianCiach** [comment]
At the very least I won't create a PR until there is a consensus about how this should be done. Either we rely on the naming scheme (as its currently the case for cronjobs and replicasets), or we don't, which would mean removing the existing Regexes and require additional permissions and API requests. Both is fine with me, but we should decide for one or the other, although I would prefer the pragmatic solution that would work with "read pods" permissions only.

**Edit:**

(In theory we could do both: First try to read the resources we're interested in, and if this doesn't work due to missing permissions, we could fall back to parse the names from the owner-references of the pod. I don't say that I am in favour of doing this, but it would be a backward-compatible solution, as it doesn't strictly require new permissions).

**Comment by ChristianCiach** [comment]
@swiatekm You win: https://github.com/kubernetes/kubernetes/issues/121687#issuecomment-1930505115 😄 

>  As folks mentioned above we don't support or encourage parsing names,

Although the naming scheme is *documented*, there doesn't seem to be a *specification*: 

> Notice that the name of the ReplicaSet is always formatted as [DEPLOYMENT-NAME]-[HASH]. This name will become the basis for the Pods which are created.
> 
> The HASH string is the same as the pod-template-hash label on the ReplicaSet. 

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment

**Comment by ChrsMark** [comment]
@ChristianCiach @swiatekm I've filed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/44831 to revisit the metadata extraction based on the regexp patterns.
