### ISSUE TITLE
[receiver/datadog] span.Resource is dropped

### ISSUE THREAD

**Issue by hughsimpson** [open-telemetry/opentelemetry-collector-contrib#23150]
### Component(s)

receiver/datadog

## Description

As of [pr 21764](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21764) the datadog receiver drops the span.Resource field - since this is where dd-java-agent put the db.statement field, this means that db statements are no longer available

## Steps to Reproduce

Instrument an application with dd apm, and check any db span

## Expected Result

span.Resource should be available as a tag on spans

## Actual Result

span.Resource is not available as a tag on spans

### Collector version

v0.78.0

## Environment
N/A

### OpenTelemetry Collector configuration

```yaml
N/A
```

**Comment by boostchicken** [comment]
I'll get to this early next week.

**Comment by hughsimpson** [comment]
I got around to it myself here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23814
