### ISSUE TITLE
[receiver/kafka] Consume metrics published by Telegraf

### ISSUE THREAD

**Issue by ledor473** [open-telemetry/opentelemetry-collector-contrib#23181]
### Component(s)

receiver/kafka

### Is your feature request related to a problem? Please describe.

Currently, my metrics are collected using Telegraf and then sent to Kafka using [Kafka output plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/kafka). It's then consumed by another set of Telegraf that will write it to the storage layer.
I'd like to use a few features of the OpenTelemetry Collector but need to move to it in a phased manner. The plan would be to have the OpenTelemetry Collector consume the same messages that are published by Telegraf (using a different consumer group) and from there use the wanted features. 

### Describe the solution you'd like

Add a new Telegraf to the [unmarshalers](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkareceiver/unmarshaler.go#L67-L72) supported by `receiver/kafka`.
I'm thinking it could support only the `influx` format at first. Since Telegraf [supports various formats](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md), it might be best to take that into consideration while adding the features.

### Describe alternatives you've considered

I looked into having Telegraf publish directly in OTLP format but it doesn't seem to be possible based on the [output formats documentation](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md).
I also looked into the [OpenTelemetry output plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/opentelemetry), but it would skip Kafka which isn't ideal for my use case.

### Additional context
Ultimately, if there's little interest in this feature request, I think I can still make it work by building an OpenTelemetry Collector and manually invoking the [WithMetricsUnmarshalers](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkareceiver/factory.go#L52-L59) method. But I figured that Telegraf is common enough that it might be interesting to host it here.

**Comment by atoulme** [comment]
@ledor473 would you like to work on this?

**Comment by atoulme** [comment]
@ledor473 are you offering to make this contribution? We are moving encodings to extensions, so they can be reused across components. See https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding
