### ISSUE TITLE
googlecloudpubsubreceiver: Accept Cloud Logging logs routed to pub/sub

### ISSUE THREAD

**Issue by kamalmarhubi** [open-telemetry/opentelemetry-collector-contrib#23184]
### Component(s)

receiver/googlecloudpubsub

### Is your feature request related to a problem? Please describe.

There are logs in GCP that we'd like in our OpenTelemetry pipeline. GCP's supported way to send logs to other destinations in near real-time is [via Pub/Sub](https://cloud.google.com/logging/docs/export/pubsub). Logs are encoded as [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) messages in protojson format.

Our immediate use case: so that our traces cover as much of the request path as possible, we want to include Google Cloud Load Balancer (GCLB) spans. GCP doesn't have an obvious way to get spans out of the GCLB, but it does have a way to log all requests. So, we currently process GCLB logs into spans.  We've routed our GCLB logs to a Pub/Sub topic, and at the moment process those into spans using a custom consumer that exports spans to our otelcol deployment.

I'd like to remove that custom component, and replace it with the OpenTelemetry Collector using the logtospanconnector proposed in #23182 (whether upstreadmed or not).

But the problem of accepting logs from GCP into an OpenTelemetry pipeline is a lot more general than my precise use case though. For example, one might want to have [AuditLog](https://cloud.google.com/logging/docs/reference/audit/auditlog/rest/Shared.Types/AuditLog) events flow through their unified pipeline.

There's already a googlecloudpubsubreceiver, but it seems designed to use Pub/Sub as a message queue to between collector deployments. I'd like to extend it to be an entrypoint for Cloud Logging logs too.

### Describe the solution you'd like

I'd like to be able to specify `cloud_logging` as an [encoding for the receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/googlecloudpubsubreceiver#encoding). 

### Describe alternatives you've considered

We've already done most of the work for this, so we'd likely shift our current use case over to a custom build of the collector if this or something similar doesn't get upstreamed.

### Additional context

Doing this correctly probably needs a bit more work on the resource semantic conventions for GCP.

I'm open to this being a new receiver, but given that the existing receiver exists and has multiple encodings, I figured it wasn't worth duplication of the PubSub subscriber code.

**Comment by alexvanboxel** [comment]
@kamalmarhubi could you explain why setting the encoding to `otlp_proto_logs` doesn't suite your use-case? see: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/googlecloudpubsubreceiver#encoding

**Comment by kamalmarhubi** [comment]
@alexvanboxel the format from GCP when setting up a log sink is not OTLP, it's JSON-encoded [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) messages.

I guess the most surprising thing to me about trying with `otlp_proto_log` is that it doesn't print errors, it just hangs.

Also I should mention that I've implemented this, though am not yet using it in production, and it would need some tidying before it could be merged. I've pushed up a draft in #25175 for you to look at whenever you have time. (I'm about to be on vacation for a couple of weeks, so no rush!)

**Comment by alexvanboxel** [comment]
Okay, it's been a while; I meant the raw_text; having this in the receiver makes sense. Let me investigate (I'll have a look at your draft)

**Comment by kamalmarhubi** [comment]
@alexvanboxel have you had a chance to take a peek?

**Comment by alexvanboxel** [comment]
Adding comment on the PR

**Comment by alexvanboxel** [comment]
Follow along https://github.com/open-telemetry/opentelemetry-specification/issues/3774 for making sure the receiver aligns with the description.

**Comment by alexvanboxel** [comment]
Thank you, @djaglowski, for merging the issue. This related ticket can be closed.

**Comment by alexvanboxel** [comment]
@open-telemetry/collector-contrib-triagers, can this be closed? This has been merged some time ago.
