### ISSUE TITLE
[receiver/prometheus] Incomplete normalization with `pkg.translator.prometheus.NormalizeName` feature gate

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#23208]
The normalization applied with the enabled `pkg.translator.prometheus.NormalizeName` feature gate in the Prometheus receiver is quite limited. It performs only a few transformations, including:

- Removing the `_total` suffix from Sum metrics.
- Removing unit suffixes only for OpenMetric format and setting the value to the OTel metric Unit field as is. However, the exporter performs a more complicated conversion, such as translating `milliseconds` in OpenMetrics to `ms` in OTel.

To bring the normalization in the Prometheus receiver closer to the behavior of the Prometheus exporter, several changes would be required. These changes include:

- Translating OpenMetrics units to the [Unified Code for Units of Measure](http://unitsofmeasure.org/ucum.html).
- Converting OpenMetrics units like `foo_per_bar` into `foo/bar` OTel metric units.
- Replacing the `_ratio` suffix with `1` OTel metric unit.
- Replacing the `_percent` suffix with `%` OTel metric unit.
- Replacing the `_dollars` suffix with `$` OTel metric unit.

Implementing these changes in the Prometheus receiver would introduce more breaking changes. Do we want to do that by introducing another feature gate?

It appears that the `pkg.translator.prometheus.NormalizeName` feature gate was switched to beta prematurely. Ideally, these Prometheus receiver changes should have been made prior to promoting the feature gate to beta. It would have been better to wait until the status of the [OpenTelemetry specification for Prometheus and OpenMetrics compatibility](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md) is promoted from Experimental. It is unclear if it's possible to revert the feature gate back to alpha at this point, but that may be an option worth considering.

**Comment by codeboten** [comment]
Decision was made at the June 7 SIG call to flip the feature gate back to alpha state

**Comment by codeboten** [comment]
@dmitryax you asked the question whether or not the receiver should stop doing any normalization and leave that to the exporter. Currently the flag impacts both as it's used in the common translator package. Should there be a separate flag for each?

**Comment by dmitryax** [comment]
@codeboten, do you suggest deprecating this flag and introducing the following instead:
- `reciever.prometheus.NormalizeName` in alpha
- `exporter.prometheus.NormalizeName` in beta (or alpha?)

**Comment by codeboten** [comment]
@dmitryax i would do this after reverting the flag to alpha, but maybe? i'm not sure if we have a clear picture of the best way to move forward yet, but it does sound like having control over each (receiver/exporter) may be beneficial.

**Comment by dmitryax** [comment]
> @dmitryax you asked the question whether or not the receiver should stop doing any normalization and leave that to the exporter

Yes, I'm still not sure if the prometheus receiver should do the full normalization and change the prometheus metric names in any way as long as the normalization on the prometheus exporter handles it gracefully, e.g. not adding `_total_total` etc. I, as a Prometheus client user, would like to see the same names in the exposed Prometheus endpoint as long as anywhere else in the Collector or after any Collector exporter.

I would like to discuss it with @open-telemetry/wg-prometheus in a separate issue or in a Prometheus WG SIG

**Comment by dmitryax** [comment]
> @dmitryax i would do this after reverting the flag to alpha, but maybe? i'm not sure if we have a clear picture of the best way to move forward yet, but it does sound like having control over each (receiver/exporter) may be beneficial.

Sounds good to me, given that this is not the only issue related to this feature gate, I think we can roll it back to alpha first and reconsider how to move forward after.
