### ISSUE TITLE
Clickhouse exporter

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-collector-contrib#2320]
I would be interested to hear opinions about the [clickhouse](https://clickhouse.tech) exporter.
This is a controversial question, as the clickhouse is not an observability tool. It is more of an analytical platform
How does such an exporter fit into the scope of opentelemetry?

**Comment by hanjm** [comment]
I am very interesting to implement it.

**Comment by jpkrohling** [comment]
@open-telemetry/collector-contrib-approvers, do we have volunteers to sponsor this component? A sponsor is an approver that is willing to be responsible for reviewing PRs related to this component and will act as the second code owner.

**Comment by dmitryax** [comment]
I'd like to be a sponsor for this component

**Comment by bogdandrutu** [comment]
@morigs now that a sponsor is identified please provide the issue for new components using the template we have.

**Comment by bogdandrutu** [comment]
Closing this, and will wait for the issue for new components to be sent.
