### ISSUE TITLE
Move and rename stanzareceiver

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#2321]
Related to #2264 and #2306.

Since `stanzareceiver` is becoming a helper package, it should be moved and renamed.

Current suggestion is `internal/logreceiverhelper`.

Open question - should code be managed as a seperate go module?

**Comment by tigrannajaryan** [comment]
>Open question - should code be managed as a seperate go module?

Since it is an internal package it cannot be consumed outside this repo so we should be able to make it a separate module easily in the future if needed. So, I suggest we just keep it in the main module for now.

**Comment by djaglowski** [comment]
I'm fine with that. I noticed that other packages in internal used their own modules, so just followed that pattern.

**Comment by tigrannajaryan** [comment]
>I noticed that other packages in internal used their own modules, so just followed that pattern.

You are right, I did not know that. Some packages do. Up to you, I don't have a strong opinion. I think for internal packages it doesn't really matter since they are not consumable as modules anyway, right? I may be missing something.
