### ISSUE TITLE
[processor/k8sattributes] Store only necessary data in the pod/replicaset/namespace informers

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#23226]
Apply the same optimization as done in https://github.com/SumoLogic/sumologic-otel-collector/pull/593 to all the informers in order to reduce the memory footprint per suggestion from @swiatekm-sumo.

Hopefully, it'll make the heap usage less than before introducing cluster-wise replicaset informers, as reported in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23067.

**Comment by swiatekm-sumo** [comment]
Are we sure we want to do namespaces? Relatively speaking, there tends to be a small number of them in the cluster, and they don't carry a lot of data. Maybe the memory savings aren't worth the additional complexity in their case?

**Comment by dmitryax** [comment]
> Are we sure we want to do namespaces? Relatively speaking, there tends to be a small number of them in the cluster, and they don't carry a lot of data. Maybe the memory savings aren't worth the additional complexity in their case?

I agree. Let's keep the namespaces informer as is. 

Closing this issue. Thank you, @swiatekm-sumo!
