### ISSUE TITLE
Metrics in k8s processor needs refactor

### ISSUE THREAD

**Issue by pmatyjasek-sumo** [open-telemetry/opentelemetry-collector-contrib#2322]
**Describe the bug**
Metrics exposed by k8s processor lacks meaningful description, and have invalid format.

**Additional context**
As mentioned in comment https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2199#discussion_r573754727 there is need to provide some additional information about meaning of those metrics. Also need to change their format to fit standard.

**Comment by dmitryax** [comment]
Whoever is willing to help with this can use the https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2971 as a reference, just make sure the review feedback is addressed (use `.` instead of `_`)

**Comment by fatsheep9146** [comment]
I will solve this ASAP
