### ISSUE TITLE
[pkg/ottl] Grammar cannot handle multiple string parameters where the first string ends with `\\"`

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#23238]
### Component(s)

pkg/ottl

## Description
The exact statement, simplified, that does not work is `a("\\", "b")`.  This should be interpreted as an Editor named `a` with two string parameters, `"\\"`, and `"v"`.  But instead the parser fails complaining about backslashes.

This happens because the lexer token we use to identify strings is matching too much content from the incoming statement. The String token is
```
`"(\\"|[^"])*"`
```
Since we use backticks, this will match a double quote, followed by 0 or more exactly 2 backslashes followed by a double quote OR anything that isn't a double quote, followed by a double quote.  You can see the regex in action with the troublesome text here: https://regex101.com/r/oqpxQ4/1.

What is happening is that the parser is treating `\\"` as literal backslash, backslash, double quote, and so it matches the first part of the token and since there is another double quote later on that is the greediest match possible. This was confirmed by debugging the lexer token selection.

I don't have a good solution to fix this yet.  The `\\"` exists in the token to allow double quotes in the eventually strconv.Unquoted strings.  Removing the `\\"` part of the regex does solve the problem, but doesn't let use to do statements like `set(body, "the cat said \\"meow\\"")`, which seems limiting.

To be clear, **this is only an issue if there is a string parameter following a string parameter that ends in `\\"`**.  Statements like `a("\\")` work.

At the time of writing this Issue the following `ottlfuncs` functions are affected:
- replace_match
- replace_all_matches
- replace_pattern
- replace_all_patterns
- IsMatch
- Split

### Workaround

For now, the workaround is to place any character after the `\\`.  In this case if you're trying to match a single backslash your regex could be `"\\{1}"`.

## Steps to Reproduce
Try to run the transformprocessor with `a("\\", "b")` as a statement.

### Collector version

v0.79.0

**Comment by TylerHelmuth** [comment]
The root cause of the error is actually when the parser calles `strconv.Unquote`.

**Comment by quentinmit** [comment]
I think this regex would fix the problem:

```
"(\\.|[^\\"])*"
```

That is, match a backslash followed by any character, or any character that isn't a backslash or double-quote.

**Comment by TylerHelmuth** [comment]
@quentinmit I did some real quick testing and I think you're right.  Would you like to submit a PR to fix this issue?

**Comment by quentinmit** [comment]
@TylerHelmuth Sure, I just sent #30839
