### ISSUE TITLE
Remove pjanotti from codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23246]
### Component(s)

receiver/carbon

### Describe the issue you're reporting

After helping through the years maintaining collector components, @pjanotti is no longer active as codeowner on this repository.

I have reached out to him and discussed the issue, and he would like to be removed as codeowner and for others who are active on the collector to take over.

I would like to thank @pjanotti for his hard work on establishing the components carbonreceiver and wavefrontreceiver.

I will create a PR to remove him from the components. If you are interested in becoming a codeowner to help maintain this code, please comment on the issue.

**Comment by crobert-1** [comment]
Is there a process to find volunteer codeowners for these components? As noted in the PR this leaves the `carbonreceiver`, `carbonexporter`, and `wavefrontexporter` unmaintained. It would be good as a part of this issue to broadcast this to the OpenTelemetry community to see if anyone's able to step in. Maybe at least bring it up in the sig meeting for a broader audience than anyone who sees this issue?

**Comment by atoulme** [comment]
The process is to open this issue and hope someone will comment they want in, or mark the components unmaintained and threaten to remove them unless someone steps up. It is definitely worth bringing up at a SIG meeting, please feel free to go ahead and do so.

**Comment by mx-psi** [comment]
@atoulme the carbon components should be added to the ALLOWLIST file under the 'unmaintained components' header https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6249ae8d927ec984dab887af0efbec79659263ed/.github/ALLOWLIST#L25

I think we should also create issues stating that this components are missing codeowners

**Comment by atoulme** [comment]
Will do and close this issue once done, thanks.
