### ISSUE TITLE
Enable exhaustive in missing components

### ISSUE THREAD

**Issue by fatsheep9146** [open-telemetry/opentelemetry-collector-contrib#23266]
According the suggestion here https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23266#issuecomment-1636947735

We should enable exhaustive in a way that makes sure only check for the enum type `pmetric.MetricType`. So I should do following things 
- [x] enable exhaustive with option `explicit-exhaustive-switch` #24412
- [x] search for all components that use `pmetric.MetricType` with switch, and then determine if the related code should be added with `//exhaustive:enforce` comment. And if  the linter is failed after the comment is added, we should solve the failure in the meantime. 

### all components that used `pmetric.MetricType`
following list is generated by command
```
grep -E 'pmetric.MetricType.*' -r . | awk -F '/' '{print "- [ ] " $2"/"$3}' | uniq
```

- [x] ~~cmd/mdatagen~~: no need
- [x] ~~processor/cumulativetodeltaprocessor~~: no need
- [x] processor/metricstransformprocessor #24559
- [x] processor/groupbyattrsprocessor #24919
- [x] processor/attributesprocessor #24977
- [x] processor/filterprocessor #25062
- [x] processor/transformprocessor #25140
- [x] internal/coreinternal #25907
- [x] internal/filter #25908
- [x] ~~receiver/saphanareceiver~~: no need, metric is auto-generated
- [x] ~~receiver/bigipreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/elasticsearchreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/hostmetricsreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/vcenterreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/rabbitmqreceiver~~: no need, metric is auto-generated 
- [x] ~~receiver/expvarreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/aerospikereceiver~~: no need, metric is auto-generated
- [x] ~~receiver/snowflakereceiver~~: no need, metric is auto-generated
- [x] ~~receiver/nsxtreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/sqlserverreceiver~~: no need, metric is auto-generated
- [x] receiver/googlecloudspannerreceiver: #24035
- [x] ~~receiver/couchdbreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/mongodbreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/nginxreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/postgresqlreceiver~~: no need, metric is auto-generated
- [x] receiver/filereceiver #25180
- [x] ~~receiver/kubeletstatsreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/haproxyreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/redisreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/zookeeperreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/kafkametricsreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/memcachedreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/mysqlreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/sshcheckreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/mongodbatlasreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/filestatsreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/activedirectorydsreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/chronyreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/httpcheckreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/dockerstatsreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/prometheusreceiver~~: no need
- [x] ~~receiver/apachereceiver~~: no need, metric is auto-generated
- [x] ~~receiver/apachesparkreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/iisreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/oracledbreceiver~~: no need, metric is auto-generated
- [x] ~~receiver/flinkmetricsreceiver~~: no need, metric is auto-generated
- [x] receiver/k8sclusterreceiver #25818
- [x] ~~receiver/riakreceiver~~: no need, metric is auto-generated
- [x] connector/countconnector: #24779
- [x] exporter/splunkhecexporter #23882
- [x] exporter/dynatraceexporter #25155
- [x] exporter/awsemfexporter #24812
- [x] exporter/skywalkingexporter #25158
- [x] exporter/googlecloudpubsubexporter #25156
- [x] ~~exporter/prometheusexporter~~: no need
- [x] exporter/azuremonitorexporter #25131
- [x] ~~exporter/carbonexporter~~: no need
- [x] exporter/sumologicexporter #25159
- [x] exporter/azuredataexplorerexporter #25130
- [x] exporter/clickhouseexporter #25133
- [x] exporter/alibabacloudlogserviceexporter #25877
- [x] pkg/ottl #26311
- [x] pkg/translator #26106
- [x] pkg/pdatatest #26105
- [x] pkg/resourcetotelemetry #26075

**Comment by dmitryax** [comment]
It's pretty annoying to have the exhaustive linter requiring all the options to be listed while the `default` case is also required by some other linter which becomes a no-op in that case. Is there a way to do anything with that? Maybe not requiring `default` anymore? Otherwise, it doesn't seem like an improvement IMO. cc @open-telemetry/collector-contrib-approvers

**Comment by codeboten** [comment]
I agree that from the reviews I've done, I don't see a lot of value in this linter. I've seen it cause problems where `fallthrough` logic was missed for example. In other places we just end up with many `fallthrough` cases, that end up falling through to the default. 

I'm ok with moving forward w/ this if the community wants it, but it seems like the value isn't tremendous.

**Comment by mx-psi** [comment]
The original use case for this is checking all metric types as mentioned on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7532#issue-1122323323. IMO this linter is useful rarely but can catch real issues when it is.

**Comment by dmitryax** [comment]
Ok, if we keep it, does anyone know if there is a way to remove the `default` case with unreachable code?

**Comment by mx-psi** [comment]
I think @codeboten mentioned something? But I can't find it now.

**Comment by TylerHelmuth** [comment]
I think it is the `-default-signifies-exhaustive` flag

**Comment by fatsheep9146** [comment]
I'm sorry for the inconvenience caused by the activation of this linter. After some consideration, I have the following suggestion. Since the purpose of enabling this linter is to prevent [this issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7532#issue-1122323323) from happening, I suggest optimizing it to _**only check the usage of the `pmetric` package**._

However, at present, "exhaustive" does not support checking only a certain type, but supports ignoring certain types from being checked(`--ignore-enum-types`). Therefore, I suggest using the "--explicit-exhaustive-switch" option for now. This option only checks switch statements that have been marked with "//exhaustive:enforce". For example, 

```go
package main

type Token int

const (
	Add Token = iota
	Subtract
)

func func1(t Token) {
	switch t {
	case Add:
	default:
	}
}

func func2(t Token) {
	//exhaustive:enforce
	switch t {
	case Subtract:
	default:
	}
}

func main() {
	func1(Add)
	func2(Add)
}
```
In the example above, with the "--explicit-exhaustive-switch" option added, the non-exhaustive switch in `func2` can be diagnosed, but the one in `func1` is ignored.

The only issue with this approach is that developers need to manually add "//exhaustive:enforce" to all switch statements that reference "pmetric.MetricType", which is prone to oversight. However, this problem can be better solved once "exhaustive" supports the ability to check only a certain type of object.

@open-telemetry/collector-contrib-approvers

**Comment by TylerHelmuth** [comment]
The one downside to this approach is that it requires the contributor to know to add the comment and it requires Reviewers to know that the comment is expected to be on certain switch statements.  There is potential that situations will be missed due to human error.

**Comment by fatsheep9146** [comment]
> The one downside to this approach is that it requires the contributor to know to add the comment and it requires Reviewers to know that the comment is expected to be on certain switch statements. There is potential that situations will be missed due to human error.

I think the best solution for this it to push exhaustive linter to support `--force-enum-types` which means only check the specific enum types and ignoring others. I will try to push this into implementation in exhaustive. @TylerHelmuth

**Comment by fatsheep9146** [comment]
all tasks are done
