### ISSUE TITLE
[filelogreceiver] Add examples for using filelogreceiver

### ISSUE THREAD

**Issue by shivanshu1333** [open-telemetry/opentelemetry-collector-contrib#23277]
### Component(s)

receiver/filelog

### Describe the issue you're reporting

At the moment it's not straight forward to start using filelogreceiver due to lack of documentation, and latest examples around it.
As an end user I've faced this, this issue aims to improve examples and documentation around using filelog receiver.

**Comment by djaglowski** [comment]
Closed by #23609

**Comment by shivanshu1333** [comment]
Wanted to have a step by step ready to use sample configs for end to end setup of filelog receiver, added a PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25136 to that
