### ISSUE TITLE
Elasticsearch Exporter ES Index Management Settings Problem

### ISSUE THREAD

**Issue by zhaohongda1987** [open-telemetry/opentelemetry-collector-contrib#23275]
### Component(s)

exporter/elasticsearch

### Describe the issue you're reporting

Hi,
    I use elasticsearch exporter to output the log into ES, but i found that the ES index for shard/replica are both 1, also not support index max docs for split index. I try to find the way to config them but found no place to do it. So anyone could help to figure a way that how to manage elasticsearch index?
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/19568031/1c03e0d9-6f9d-4f54-a837-ae217e8a0cb2)

**Comment by zhaohongda1987** [comment]
Hi @JaredTan95 , i just see that elasticsearch exporter Stability is still beta, so i guess it doesn't support manage es index for now. could you please help to see that maybe can support it? thanks

**Comment by zhaohongda1987** [comment]
I can use Elasticsearch index template and index lifecycle policies to control the index, but still suggest to add the configuration for default index(shard and replica) which created by elasticsearch exporter.

**Comment by JaredTan95** [comment]
yeah, I think this is a reasonable requirement.

**Comment by zhaohongda1987** [comment]
Thanks @JaredTan95 , hope it will support in future😄
