### ISSUE TITLE
Log receivers - Improve translation to pdata, avoid emitting entire pdata.Logs for each log record.

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#2330]
Currently this translation is 1:1. Need to define and implement a more efficient translation.

**Comment by pmalek-sumo** [comment]
I'd be willing to work on this but I'll need some guidance on the desired direction of this.

My understanding is that there is a [`func Convert(obsLog *entry.Entry) pdata.Logs`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/078648896a9ad5e841d6770c5333cfc095cbca9b/internal/stanza/converter.go#L25-L61)
which does the actual conversion.

If we'd like to somehow make this not 1:1 translation then ... we'd need to aggregate `entry.Entry`s and then using a particular interval send them further for processing? Or is there a different vision for this that I'm not seeing yet?

**Comment by pmalek-sumo** [comment]
I've prepared something that might address this issue in https://github.com/SumoLogic/opentelemetry-collector-contrib/tree/issue-2330-improved-logs-translation

Compare across forks: https://github.com/open-telemetry/opentelemetry-collector-contrib/compare/main...SumoLogic:issue-2330-improved-logs-translation

@djaglowski  If this is more or less the direction we'd like to this in I can add some tests, refactor it a little bit and submit a PR so that we can take it from there.

**Comment by djaglowski** [comment]
@pmalek-sumo This is more or less what I was expecting. Looks like a great start.

**Comment by pmalek-sumo** [comment]
I've created https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2694 as a proposal for this issue.

Current implementation allows configuration via 2 knobs:
* `flush_trigger_count` - amount of entries aggregated so far in current batch. If this is exceeded then a flush of (all aggregated) log entries will be scheduled
* `flush_interval` - an interval at which flushes will be scheduled.

Waiting for your feedback.

**Comment by tigrannajaryan** [comment]
@pmalek-sumo @djaglowski do we expect more improvements or we consider done with this?

**Comment by pmalek-sumo** [comment]
I'd like to propose a variant of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2949 for consideration as design improvement.

The only concern I have about this not being accepted though is that it increases the cpu consumption by a few percent.
If there's will to take a look at it ( a rebased, cleaned up version of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2949) I'll prepare it then

**Comment by djaglowski** [comment]
@pmalek-sumo If you are ok with it, I would like to consider this issue done.

We can open a new issue to track further proposed changes.

cc @tigrannajaryan

**Comment by tigrannajaryan** [comment]
Sounds good. I am closing this issue. We can continue looking at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2949
