### ISSUE TITLE
Add syslog receiver

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#2331]
Dependent on #2268 and https://github.com/open-telemetry/opentelemetry-log-collection/issues/13

**Comment by tigrannajaryan** [comment]
@WPH95 is working on this (can't assign because they are not Otel Github member).

**Comment by djaglowski** [comment]
@WPH95 open-telemetry/opentelemetry-log-collection#13 is resolved an available in version `v0.15.1`.
