### ISSUE TITLE
Move codeowners to status metadata

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23367]
### Component(s)

cmd/mdatagen

### Is your feature request related to a problem? Please describe.

Currently, codeowners are listed directly under .github/CODEOWNERS.

However, we have need to start to show those codeowners even after they have left the project, and we could use showing them to associate them with the component status (no codeowners means that the component is now considered unmaintained).

### Describe the solution you'd like

I would like to move codeowners info under the metadata.yaml file of the component.

The .github/CODEOWNERS file would be then generated from this document.

The README.md should also show the codeowners of a component.

I am looking to implement this in steps:
* [x] Implement the changes to mdatagen, supporting new fields in status metadata and README.
* [x] Add the metadata to all components to the status section of metadata.yaml
* [x] Generate the CODEOWNERS file from status metadata and check it in CI
* [x] Change the documentation to offer to change code owners through the status metadata

**Comment by dmitryax** [comment]
I like the idea

**Comment by atoulme** [comment]
I am looking to implement this in steps:
* [ ] Implement the changes to mdatagen, supporting new fields in status metadata and README.
* [ ] Add the metadata to all components to the status section of metadata.yaml
* [ ] Generate the CODEOWNERS file from status metadata and check it in CI
* [ ] Change the documentation to offer to change code owners through the status metadata
