### ISSUE TITLE
Open issues every 6 months asking for codeowners of components to provide status reports

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23385]
### Describe the issue you're reporting

As discussed in SIG meeting on 6/14, one direction we might want to take is to prod actively codeowners to show that they are still actively involved with the project by opening an issue tagging the component and its codeowners, and making sure they close the issue with an update and a nod that they are still around.

**Comment by mx-psi** [comment]
Thinking about this a bit more after the SIG I think we should be mindful of the amount of toil we put into being a code owner. Some code owners are doing completely voluntary, unpaid work; while we definitely don't want to have unmaintained components, we want to be reasonable and avoid putting additional work on their shoulders. In particular, I believe we should try and identify automatically via the Github API active owners to avoid pinging those.

I am also undecided on whether we should ping people if a component has no unanswered issues; it seems like additional toil for both us and code owners with not much clear benefit.

**Comment by astencel-sumo** [comment]
> we should try and identify automatically via the Github API active owners to avoid pinging those.

This is a good point, I agree with this one 💯 

> whether we should ping people if a component has no unanswered issues

I lean towards still pinging the inactive code owners. I'd say let's only ping those code owners who haven't been active for the last X time (6 months sounds good for me).

We could have a GitHub Action that runs weekly, checking the last activity in the contrib repo for each code owner, and creating an issue for each code owner whose last activity is further than X. This means the issue would be created for a specific code owner, not a specific component. What do you think?

**Comment by mx-psi** [comment]
> We could have a GitHub Action that runs weekly, checking the last activity in the contrib repo for each code owner, and creating an issue for each code owner whose last activity is further than X days ago. 

This sounds reasonable at least as something we can try; I asked around on #otel-collector https://cloud-native.slack.com/archives/C01N6P7KR6W/p1686819432180289 to see if there are concerns from the community.
