### ISSUE TITLE
[exporter/tanzuobservability] Update codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23395]
### Component(s)

exporter/tanzuobservability

### Describe the issue you're reporting

Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 for context.

The tanzuobservabilityexporter is lucky to count @keep94 and @thepeterstone as codeowners, however they are not currently registered as a member of OpenTelemetry.

Please work towards a resolution:
* [ ] Work with @keep94 and @thepeterstone towards their OpenTelemetry membership, following steps detailed in #20868.
* [ ] Open a PR to remove @keep94 and @thepeterstone from codeowners. They should review and approve the change.

If no action is taken by January 2024, I will open a PR to remove them from the codeowners, and after a delay for their review, eventually will merge the PR.

**Comment by oppegard** [comment]
Hi @atoulme, our nearish-term plan is to deprecate and eventually delete the Tanzu Observerability Exporter. We have better ways to ingest native OTLP protobufs now, so OTel Collector users can just switch to the OTLP Exporter if needed. I believe @keep94 is the one who will be doing the deprecation PR, followed by the eventual deletion PR.

**Comment by atoulme** [comment]
Understood. Please open a new issue to deprecate the exporter and we can close this one, linking to it.

**Comment by atoulme** [comment]
I haven't heard back. so I will file the issue to deprecate and eventually delete the exporter from your comment. Thanks!
