### ISSUE TITLE
[exporter/logzio] Update codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23390]
### Component(s)

exporter/logzio

### Describe the issue you're reporting

Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 for context.

The logzioexporter is lucky to count @Doron-Bargo as codeowner, however they are not currently registered as a member of OpenTelemetry.

Please work towards a resolution:
* [ ] Work with @Doron-Bargo towards their OpenTelemetry membership, following steps detailed in #20868.
* [ ] Open a PR to remove @Doron-Bargo from codeowners. They should review and approve the change.

If no action is taken by January 2024, I will open a PR to remove them from the codeowners, and after a delay for their review, eventually will merge the PR.

**Comment by codeboten** [comment]
Addressed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30138
