### ISSUE TITLE
[receiver/azureblob] Update codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23394]
### Component(s)

receiver/azureblob

### Describe the issue you're reporting

Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 for context.

The azureblobreceiver is lucky to count @eedorenko as codeowner, however they are not currently registered as a member of OpenTelemetry.

Please work towards a resolution:
* [x] Work with @eedorenko towards their OpenTelemetry membership, following steps detailed in #20868.
* [ ] Open a PR to remove @eedorenko from codeowners. They should review and approve the change.

If no action is taken by January 2024, I will open a PR to remove them from the codeowners, and after a delay for their review, eventually will merge the PR.

**Comment by eedorenko** [comment]
I am working towards OpenTelemetry membership

**Comment by atoulme** [comment]
I will be happy to be a sponsor if you're looking for a member to sponsor you. Thanks!

**Comment by eedorenko** [comment]
@mx-psi could you please be a sponsor for my membership?

**Comment by mx-psi** [comment]
> @mx-psi could you please be a sponsor for my membership?

@eedorenko Sure :) please send me the link to the issue I have to sponsor and I will gladly do so

**Comment by eedorenko** [comment]
> > @mx-psi could you please be a sponsor for my membership?
> 
> @eedorenko Sure :) please send me the link to the issue I have to sponsor and I will gladly do so

Thanks a lot!

**Comment by eedorenko** [comment]
https://github.com/open-telemetry/community/issues/1785
