### ISSUE TITLE
[exporter/azuremonitor] Update codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23399]
### Component(s)

exporter/azuremonitor

### Describe the issue you're reporting

Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 for context.

The azuremonitorexporter is lucky to count @pcwiese as codeowner, however they are not currently registered as a member of OpenTelemetry.

Please work towards a resolution:
* [x] Work with @pcwiese towards their OpenTelemetry membership, following steps detailed in #20868.
* [ ] Open a PR to remove @pcwiese from codeowners. They should review and approve the change.

If no action is taken by January 2024, I will open a PR to remove them from the codeowners, and after a delay for their review, eventually will merge the PR.

**Comment by pcwiese** [comment]
I have an outstanding request to join the otel org
https://github.com/open-telemetry/community/issues/1622
