### ISSUE TITLE
[receiver/pulsar] Update codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23406]
### Component(s)

receiver/pulsar

### Describe the issue you're reporting

Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 for context.

The pulsarreceiver is lucky to count @tjiuming as codeowner, however they are not currently registered as a member of OpenTelemetry.

Please work towards a resolution:
* [ ] Work with @tjiuming towards their OpenTelemetry membership, following steps detailed in #20868.
* [ ] Open a PR to remove @tjiuming from codeowners. They should review and approve the change.

If no action is taken by January 2024, I will open a PR to remove them from the codeowners, and after a delay for their review, eventually will merge the PR.

**Comment by tjiuming** [comment]
@atoulme  You can update the codeowner to @dao-jun , it's my another github account, and joined OTEL as a member.

**Comment by atoulme** [comment]
I am sorry, I cannot do this on your behalf. Please open a PR to update the codeowners @tjiuming @dao-jun

**Comment by dao-jun** [comment]
OK，I'll do it
