### ISSUE TITLE
[exporter/tencentcloudlogservice] Update codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23407]
### Component(s)

exporter/tencentcloudlogservice

### Describe the issue you're reporting

Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 for context.

The tencentcloudlogserviceexporter is lucky to count @wgliang and @yiyang5055 as codeowners, however they are not currently registered as a member of OpenTelemetry.

Please work towards a resolution:
* [x] Work with @wgliang and @yiyang5055 towards their OpenTelemetry membership, following steps detailed in #20868.
* [ ] Open a PR to remove @wgliang and @yiyang5055 from codeowners. They should review and approve the change.

If no action is taken by January 2024, I will open a PR to remove them from the codeowners, and after a delay for their review, eventually will merge the PR.

**Comment by wgliang** [comment]
REF:https://github.com/open-telemetry/community/issues/1550

**Comment by atoulme** [comment]
Thanks @wgliang ! Can you please contact @yiyang5055 and follow up with them to become a member as well? Thanks!

**Comment by yiyang5055** [comment]
ref: https://github.com/open-telemetry/community/issues/1564

**Comment by atoulme** [comment]
Thanks! Closing :)
