### ISSUE TITLE
[extension/basicauth] Update codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23402]
### Component(s)

extension/basicauth

### Describe the issue you're reporting

Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 for context.

The basicauthextension is lucky to count @svrakitin as codeowner, however they are not currently registered as a member of OpenTelemetry.

Please work towards a resolution:
* [ ] Work with @svrakitin towards their OpenTelemetry membership, following steps detailed in #20868.
* [x] Open a PR to remove @svrakitin from codeowners. They should review and approve the change.

If no action is taken by January 2024, I will open a PR to remove them from the codeowners, and after a delay for their review, eventually will merge the PR.

**Comment by jpkrohling** [comment]
@svrakitin, are you interested in becoming a member of the organization, in order to retain the code ownership of this module?

**Comment by jpkrohling** [comment]
Given the lack of response, I'd unfortunately decide to remove them from the code owners for that module.
