### ISSUE TITLE
[receiver/snmp] Update codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23404]
### Component(s)

receiver/snmp

### Describe the issue you're reporting

Please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 for context.

The snmpreceiver is lucky to count @tamir-michaeli as codeowner, however they are not currently registered as a member of OpenTelemetry.

Please work towards a resolution:
* [x] Work with @tamir-michaeli towards their OpenTelemetry membership, following steps detailed in #20868.
* [ ] Open a PR to remove @tamir-michaeli from codeowners. They should review and approve the change.

If no action is taken by January 2024, I will open a PR to remove them from the codeowners, and after a delay for their review, eventually will merge the PR.

**Comment by djaglowski** [comment]
@tamir-michaeli, are you interested in applying for membership? If not, please let us know and we will open a PR to remove you as code owner.

**Comment by tamir-michaeli** [comment]
@djaglowski Yes i am interested, will apply soon :)

**Comment by atoulme** [comment]
https://github.com/open-telemetry/community/issues/1554 is open.

**Comment by atoulme** [comment]
Closing as done, thanks!
