### ISSUE TITLE
List code owners and emeritus owners on components' README files

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#23411]
### Component(s)

cmd/mdatagen

### Describe the issue you're reporting

On https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22781#discussion_r1228615513, we discussed how to list emeritus code owners.

@atoulme suggested listing them on the components' README, which I think can be a good idea both for visibility of current owners and for listing emeritus owners if wanted, similar to what we do for more 'official' roles like triagers, approvers and maintainers.

This is blocked by #23367

**Comment by dmitryax** [comment]
@atoulme this can be closed now, right?

**Comment by atoulme** [comment]
Correct! Closing.
