### ISSUE TITLE
elasticsearch exporter support jaeger mode mapping

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-collector-contrib#23427]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

elasticsearch exporter support `ecs` mapping mode default currently, more users wish to support jaeger mode.

### Describe the solution you'd like

add `jaeger` mode optional configuration and keep `ecs` mode default.

**Comment by MovieStoreGuy** [comment]
I am hesitant to suggest this work goes ahead given https://github.com/jaegertracing/jaeger/issues/3362, I believe the pathway should be to adopt OTLP here instead.

cc: @jpkrohling

**Comment by JaredTan95** [comment]
Yes, I also noticed that Jaeger plans to migrate to OTLP proto, but now, jaeger still stores span within its own format. and we could not use any tools to query spans exported by `elasticsearch exporter`. 

So, this issue plans to store spans in `jaeger es` format, then, we could use `jaeger-ui` to analyze data quickly. BTW, I'm also looking forward Jaeger could query `OTLP` directly.
