### ISSUE TITLE
Enhance validation of metadata.yaml

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-collector-contrib#23424]
### Component(s)

cmd/mdatagen

### Describe the issue you're reporting

Currently, some validation already exists here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/mdatagen/loader.go#L238-L290.

However, the validation done does not cover all cases.  For instance, it is not checked whether class is one of the supported values  (e.g. one of `receiver|processor|exporter|connector|extension` for class) -- it is only checked that this is not empty.

This is to add validation so that:
- We check that all required fields are present.
- We check that all values match the supported values.

This is the first step in order to add a [CI test](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23376).

**Comment by mackjmr** [comment]
Can someone please assign this to me ? I have started working on this.

**Comment by mackjmr** [comment]
Can someone please assign this to me ? I would like to work on this.

**Comment by dmitryax** [comment]
Thanks @mackjmr for tacking care of it!
