### ISSUE TITLE
Recoverable errors are not handled by stanza operators

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#23443]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

Stanza input operators do not differentiate between regular and recoverable errors:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b719459a0dba0dad5a1ceec5569e5f2c29c37935/pkg/stanza/adapter/receiver.go#L123-L128

Therefore, if only part of the logs has been unsuccessfully processed, we assume that all of them failed and we do not retry to send failed items

related PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16452

**Comment by djaglowski** [comment]
@sumo-drosiek, I have not followed closely how other components handle recoverable errors. Is there an obvious solution here? Do you want to be assigned the issue?

**Comment by sumo-drosiek** [comment]
I'm wasn't investigating it in solution context yet. You can assign me so we don't loose a track on it
