### ISSUE TITLE
[receiver/sqlquery] Flaky test TestPostgresIntegrationLogsTrackingWithStorage

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#23568]
### What happened?

Seen in https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5316701845/jobs/9626920066?pr=23564

```
--- FAIL: TestPostgresIntegrationLogsTrackingWithStorage (6.55s)
    integration_test.go:159: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sqlqueryreceiver/integration_test.go:159
        	Error:      	Condition never satisfied
        	Test:       	TestPostgresIntegrationLogsTrackingWithStorage
        	Messages:   	failed to receive more than 0 logs
{"level":"error","msg":"error collecting logs","error":"error getting rows: dial tcp [::1]:15431: connect: connection refused","query":"query-0: select * from simple_logs where id > $1"}
```

**Comment by dmitryax** [comment]
@astencel-sumo, this seems to be related to the functionality you added recently. Can you please take a look?

**Comment by dmitryax** [comment]
Another case https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5324584393/jobs/9644100177?pr=23575

**Comment by djaglowski** [comment]
@astencel-sumo, I think it may be possible to stabilize the test by generalizing or borrowing from https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/coreinternal/scraperinttest/scraperint.go. The package adds some resiliency by retrying the most fragile parts of integration tests.
