### ISSUE TITLE
[receiver/statsd] Improve logging for better troubleshooting

### ISSUE THREAD

**Issue by marcsanmi** [open-telemetry/opentelemetry-collector-contrib#23570]
### Component(s)

receiver/statsd

### Is your feature request related to a problem? Please describe.

The receiver's main aggregating process is [failing silently](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9a5f72317d1e2af34c69eae68a0b9836451958d7/receiver/statsdreceiver/receiver.go#L112). Was this a design choice? While troubleshooting why a metric wasn't being processed by the receiver, I had to manually modify the receiver to log the error in the collector. Here's the main culprit:

```golang
for {
  select {
  case <-ticker.C:
  // ...
  case metric := <-transferChan:
     _ = r.parser.Aggregate(metric.Raw, metric.Addr)
  case <-ctx.Done():
  // ...
  }
}
```

### Describe the solution you'd like

Exposing these errors and making them accessible in the collector logs would be beneficial. For example, this could be accomplished by including them as a debug log.

**Comment by paologallinaharbur** [comment]
Also `r.Flush(batchCtx, batch.Metrics, r.nextConsumer)` is failing silently

**Comment by afzal442** [comment]
Look like good first issue, how I can approach this. thanks

**Comment by marcsanmi** [comment]
Sure, @afzal442, feel free to take this on.

If any aggregation or flushing error occurs, I would log the error using the `OnDebugf` function from the already defined `Reporter` interface. It might also be worth considering whether logging it as a warning would be more appropriate.

**Comment by alexandreliberato** [comment]
@afzal442 are you still working on this? If not I can tackle this issue. Thanks

**Comment by afzal442** [comment]
Sorry @alexandreliberato! You can go ahead. I got something else to cook off.

**Comment by dmitryax** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24282
