### ISSUE TITLE
Add a Dockerfile that can build the binary too

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector-contrib#236]
Currently, it seems that there is a Dockerfile that can create an image from a binary built on the host machine. It would be nice to have a Dockerfile that can actually build the binary too, for example this one - https://github.com/anuraaga/opentelemetry-collector-contrib/blob/custom/Dockerfile

This way, it's easy to locally build a docker image for master without worrying about tooling using something like `docker build -t opentelemetry-collector:test https://github.com/opentelemetry/opentelemetry-collector-contrib.git` or similarly for local changes. This can work especially well with `docker-compose` which will always start up containers after building source without any other steps.

If this seems like a reasonable idea, I can send a PR with the Dockerfile I linked.

**Comment by anuraaga** [comment]
@bogdandrutu @trask Sorry for bugging, wondering if you have any thoughts on this? I'm having to maintain a branch to keep the Dockerfile since it really helps me with integration work between many services and the collector, and think it could help others. Building / running the code from master is how I find bugs :)

In case it helps, here's where I'm using it, and wish it was just the upstream master repo https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/blob/both-otel-and-xray/docker-compose.yml#L25

**Comment by flands** [comment]
@anuraaga sounds good -- put up a PR for review
