### ISSUE TITLE
tailsamplingprocessor composite policy documentation can be improved

### ISSUE THREAD

**Issue by utezduyar** [open-telemetry/opentelemetry-collector-contrib#23638]
### Component(s)

processor/tailsampling

### Describe the issue you're reporting

Maybe it is just me but I got confused about the features of the tailsamplingprocessor, especially composite policy. Policies have OR relationship between them. The policies inside the composite policy though have AND relationship. All the policies must be satisfied for item to be sampled in the composite policy. 

I played around with following policy:

```
{
          name: composite-policy,
          type: composite,
          composite:
            {
              max_total_spans_per_second: 4,
              policy_order: [composite-policy-errors, test-composite-always],
              composite_sub_policy:
                [
                  {
                    name: composite-policy-errors,
                    type: status_code,
                    status_code: {status_codes: [ERROR]}
                  },
                  {
                    name: test-composite-always,
                    type: always_sample
                  }
                ],
              rate_allocation:
                [
                  {
                    policy: composite-policy-errors,
                    percent: 50
                  },
                ]
            }
        },
```

This only captures the traces that have error. I was hoping it would capture everything with 4 span / sec limit and would allocate 50% of this budget to error spans. 

I propose that we make AND relationship of the composite policy more clear in the documentation. Second suggestion I have is to provide more reasonable examples instead of a dump of all possible configuration. One example is what @reese-lee has written on https://newrelic.com/blog/best-practices/open-telemetry-tail-sampling which I found very beneficial.

**Comment by miparnisari** [comment]
>  Policies have OR relationship between them.

this isn't documented anywhere either 🤔

**Comment by jpkrohling** [comment]
That's true, although I'm not sure I would call them "or". The decision tree is listed in the readme, but there are a few possible decisions for a sampler: unspecified, sample, not sample, inverted (sampled and not sampled), error, ... If something is marked as "sample" by one sampler and "not sample" by another, the trace is sampled. But an "inverted not sample" plus a "sample" results in "not sample".

I agree that the documentation is confusing though and I will gladly review your PRs to improve it. Perhaps some real-world examples would be really useful.
