### ISSUE TITLE
Add otel.jmx.remote.registry.ssl option in JMX receiver

### ISSUE THREAD

**Issue by fvaliquette-splunk** [open-telemetry/opentelemetry-collector-contrib#23641]
### Component(s)

receiver/jmx

### Describe the issue you're reporting

JMX Metric Gatherer introduced `otel.jmx.remote.registry.ssl` option in `version 1.26` via this [pull request](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/835), although this option is not available in JMX receiver yet.

**Comment by crobert-1** [comment]
Makes sense to me, it should be pretty simple to add a new config option and [add it to the JMX gatherer config in this method.](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/faf9f207df86390fe1a9bbe8a0df3166063d9647/receiver/jmxreceiver/receiver.go#L157)
