### ISSUE TITLE
Support Workspace-based Application Insights

### ISSUE THREAD

**Issue by gerron** [open-telemetry/opentelemetry-collector-contrib#23656]
### Component(s)

exporter/azuremonitor

### Is your feature request related to a problem? Please describe.

Microsoft has recently released [Workspace-based Application Insights](https://learn.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource). With this new option Application Insights now supports storing data within a Log Analytics workspace. This comes with a new [Table Structure](https://learn.microsoft.com/en-us/azure/azure-monitor/app/convert-classic-resource#table-structure), [Table Schema](https://learn.microsoft.com/en-us/azure/azure-monitor/app/convert-classic-resource#table-schemas), and a few other changes. Also worth noting that classic mode will deprecate early next year.

As of now the [azuremonitorexporter ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter) supports sending [Span Events](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter#span-events), [Logs](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter#logs), and [Metrics ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter#metrics) to Application Insights that uses the classic option.

Specific use case:
We would like to leverage the opentelemetry exporter for azuremonitor to support sending logs to a log analytics workspace. This would allow us to collect logs seamlessly using the opentelemetry-collector and export them to a workspace which can be used by Azure Sentinel. 

### Describe the solution you'd like

We would like the [azuremonitorexporter ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter)to be updated to support [Workspace-based Application Insights resources.](Workspace-based Application Insights resources)

### Describe alternatives you've considered

Alternative solutions would be using the opentelemetry-collector to export logs to an Azure blob and then pull from the blob. Not ideal.

### Additional context

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/2373574/0c10ac1c-4a7f-4d63-b15c-2457fa28cb8b)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/2373574/351f295c-324b-4af0-9e46-336deea5f7fd)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/2373574/dd6c296c-9209-4562-b759-b9bf73632a17)

"Classic Application Insights is deprecated and will be retired in February 2024."
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/2373574/6406d235-ef3e-4064-ba09-983f855e3f13)

**Comment by bunkrur** [comment]
I think this is already possible since the ingress to classic App Insights and the newer version are the same. On the backend, LTM are routed to Log Analytics as part of the App Insights configuration without any modification to the ingress.

I am using Workspace based Application Insights without issue.
