### ISSUE TITLE
Add service.instance.id for the generated metrics

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-collector-contrib#23663]
### Component(s)

connector/servicegraph, connector/spanmetrics, processor/servicegraph, processor/spanmetrics

### What happened?

When multiple replicas of the collector are run, the spanmetrics/servicegrap generated gets duplicated, resulting in an incorrect result. I believe any kind of metrics produced by a collector should have a single originating source of truth similar to the single-write principle for SDKs https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#single-writer.

### Collector version

any

## Environment
any

**Comment by srikanthccv** [comment]
I also believe the resource attributes of built metrics should be the resource attribute of collector service and not the incoming spans as it is currently implemented https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/da5df85e77bb717e87096c20663ddc8bbb5ebf8a/connector/spanmetricsconnector/connector.go#L226-L230

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/da5df85e77bb717e87096c20663ddc8bbb5ebf8a/connector/spanmetricsconnector/connector.go#L270-L279

Let me know what do you folks think; I will be happy to send a PR for this.

**Comment by Frapschen** [comment]
I think multiple replicas don't generate duplicate data, in a classic use case, there will be an SVC before those replicas,  if a request arrives at the SVC, it will route the request to only one of those endpoints(replicas). can you give me a example how that happen(if I wrong,please correct me)

**Comment by srikanthccv** [comment]
I am referring to the metrics generated, not the incoming requests to replicas. Say there are two instances of the collector running, and both these collectors have the span metrics processor configured. As highlighted here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c247210d319a58665f1988e231a5c5fcfc9b8383/processor/spanmetricsprocessor/README.md?plain=1#L23-L28 The metric `calls_total` has a set of labels and value associated with it. It is certainly possible that other collector also has an entry with the same set of labels and some counter value (count will be different). When the data is sent to the destination backend, it will calculate the fingerprint based on labels, and as the labels are the same the fingerprint will also be the same, which would result in inaccurate results.

**Comment by Frapschen** [comment]
Yes, you are right otel collector will generate the same label set. If you use Prometheus, it has already done it for you(e.g. it will add an instance label to distinguish them), as for other backends you can add a metrics processor, and manually set a identify key to quickly finish your job

**Comment by jpkrohling** [comment]
@Frapschen is right, but the collector does have a service instance id already, so, it's a matter of just using that, which I think is reasonable.
