### ISSUE TITLE
[exporter/prometheusremotewrite] Add debug logs to confirm when data was written to the backend

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-collector-contrib#23680]
### Component(s)

exporter/prometheusremotewrite

### Is your feature request related to a problem? Please describe.

It would be nice if this component produced debug logs to show how many data points were succesfullly written to a backend.

I understand that this data is also available in the form of self-telemetry metrics, but logs provide a faster mechanism for troubleshooting the collector components.

### Describe the solution you'd like

I'd like debug log messages for written data points.

**Comment by JaredTan95** [comment]
make sense
