### ISSUE TITLE
[exporter/datadog] Support exporting to in-cluster agents

### ISSUE THREAD

**Issue by adityasundaramurthy-maersk** [open-telemetry/opentelemetry-collector-contrib#2375]
**Is your feature request related to a problem? Please describe.**
The collector in its current state only supports exporting directly to Datadog. It is not possible to export telemetry to an in-cluster agent as the collector failed at the key validation step.

**Describe the solution you'd like**
I have Datadog agents deployed in Kubernetes clusters. The dd-java-agent support exporting to both the Datadog API and in-cluster agents. Can the collector be enhanced to behave the same way? This way, I don't have to distribute the Datadog API key to every namespace as a secret and there is the opportunity to enrich telemetry with additional tags in the host agent.

**Describe alternatives you've considered**
No alternatives other than exporting directly to the API.

**Additional context**
- The collector performs key validation and there is no way to disable this.

**Comment by ericmustin** [comment]
@adityasundaramurthy-maersk 👋 hey there, i'm a bit confused on the use case. you want to export from the opentelemetry-collector to a datadog-agent? Is the main reason here the api key management bit or is there specific metadata that gets added by the datadog-agent that we're missing in the opentelemetry-collector datadogexporter?

For context, we're discussing internally exposing an OTLP ingest endpoint for the datadog-agent but it's non trivial to add and wouldn't be available in the short term.

**Comment by BinaryHexer** [comment]
Just as a sidenote, another way to solve the key management issue is to run two tiers of collectors (one in each namespace) and then one in a common namespace.

The tier 1 collectors can export using OTLP protocol to tier 2 collectors. And tier 2 collectors can export to datadog using datadogexporter. This way you only need to manage keys to tier 2 collectors.

**Comment by ericmustin** [comment]
@BinaryHexer indeed, ty for highlighting that. And for anyone who may find this thread, we suggest this approach for k8s environments: https://docs.datadoghq.com/tracing/setup_overview/open_standards/#kubernetes

**Comment by tonglil** [comment]
I would like to reduce the reliance on datadog agents and avoid exporting to them.

**Comment by ericmustin** [comment]
This is probably going to encompass this issue and will be the right place to stay up to date on work here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3804

**Comment by mx-psi** [comment]
If you want to export OTLP metrics and traces to the Datadog Agent, you can do so via OTLP ingest. You can read more details about it [here](https://docs.datadoghq.com/tracing/setup_overview/open_standards/otlp_ingest_in_the_agent/?tab=host).

I am closing this issue since we consider that this use case is supported by the OTLP ingest feature. For issues related or help with the Datadog Agent OTLP ingest, please [contact Datadog support](https://www.datadoghq.com/support/) (prefered) or open an issue over at [the Datadog Agent repository](github.com/DataDog/datadog-agent/), thanks!
