### ISSUE TITLE
receiver/vcenterreceiver - 8.0 support?

### ISSUE THREAD

**Issue by timlopezarcurve** [open-telemetry/opentelemetry-collector-contrib#23769]
### Is your feature request related to a problem? Please describe.

We're looking to update it across the board. Is there any timelines / plans for it?

### Describe the solution you'd like

Is there any plans to support VSphere 8.0 for the vcenterreceiver.

**Comment by apfuzz** [comment]
@timlopezarcurve @djaglowski Upgraded to vCenter and ESXi to 8.0 Update 1 and there do not appear to be any issues.

**Comment by djaglowski** [comment]
Thanks for verifying @apfuzz. I'll close the issue then.
