### ISSUE TITLE
[receiver/filelog]: Log glob IO errors

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#23768]
### Component(s)

receiver/filelog

### Describe the issue you're reporting

Currently, we are globbing and ignoring any IO errors, which is the default behavior of the [glob library](https://github.com/bmatcuk/doublestar) we are using. However, this means that any errors that are gotten here are swallowed silently by the receiver.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c15794f8b3ad8bdf1bbf5abfba8486df4ad1b7c9/pkg/stanza/fileconsumer/finder.go#L21C2-L21C2

Instead, I think it would be ideal if we used the `WithFailOnIOErrors` option (https://pkg.go.dev/github.com/bmatcuk/doublestar/v4#WithFailOnIOErrors) initially, and if fails, log a warning (or maybe even just a debug level log?), and fall back to using the current behavior. 

This would help to debug instances where globbing is actually failing (can't access dir because of permissions, for instance), and silently leads to files not being picked up by the receiver.

**Comment by djaglowski** [comment]
@BinaryFissionGames, makes sense to me. Should I assign this to you?

**Comment by BinaryFissionGames** [comment]
@djaglowski Yes, please do. Thanks!

**Comment by djaglowski** [comment]
@BinaryFissionGames, are you still planning to work on this?
