### ISSUE TITLE
update of prometheus from 0.43.1 to 0.45.0 causes issues

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#23784]
### Component(s)

receiver/prometheus

### Describe the issue you're reporting

The upgrade causes the following error, see 
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5391588621/jobs/9788795226?pr=23778 for full details:

```
Error: internal/metricfamily_test.go:233:94: too many arguments in call to labels.NewBuilder(tt.labels).Set(tv.extraLabel.Name, tv.extraLabel.Value).Labels
```

Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23758

**Comment by dashpole** [comment]
We are now on v0.47.0: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/098e0fb92bd923ec7068322c6b1afa169c015cdf/go.mod#L551

**Comment by codeboten** [comment]
This was fixed
