### ISSUE TITLE
[receiver/filelog] Active File Grouping

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-collector-contrib#23787]
### Component(s)

receiver/filelog

### Is your feature request related to a problem? Please describe.

The current sorting rules may present a potential challenge for users who wish to categorize files into various groups and apply different sorting criteria within each group, while keeping multiple files active simultaneously.

### Describe the solution you'd like

Introduce an additional field named `group_by` to the ordering criteria. This field would enable users to specify a capture field in the regex, and files with the same value in this field will be treated as a group. Each of these groups can then be sorted independently based on the `sort_by` rules. In the absence of a `group_by` field, all file names will be treated as a single group. This enhancement will facilitate managing multiple active files concurrently.

### Additional context

This is an additional feature that could be added as a follow on to: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22998

**Comment by djaglowski** [comment]
I'm reopening this as I don't believe this has been implemented yet but would still be a good feature.

**Comment by andrzej-stencel** [comment]
Looks like it needs the `never stale` label?

**Comment by odubajDT** [comment]
Hi, I would like to look at this feature of possible
