### ISSUE TITLE
[receiver/filelog] Support for Multiple Current Sorted Files

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-collector-contrib#23788]
### Is your feature request related to a problem? Please describe.

Another potential issue is the presence of multiple active files within a sorted group. It would be beneficial to have an option to specify the number of files at the top of the sorted list that should be considered as active.

### Describe the solution you'd like

Introduce an additional field named 'top_n' to the ordering criteria. This field would allow users to specify the number of files to be considered from the top of the sorted list.

### Additional context

This is an additional feature that could be added as a follow on to: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22998

**Comment by djaglowski** [comment]
Closed by #27844
