### ISSUE TITLE
Track the deprecation of the SkyWalking exporter

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#23796]
### Component(s)

exporter/skywalking

### Describe the issue you're reporting

I'm listed as the code owner for the SkyWalkling exporter, as I volunteered for it when it was first proposed (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4956). A follow-up PR that was promised at that time (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6116) hasn't been done, and the code owner is not responsive even after being pinged directly.

I would like to start the deprecation process for this component.

- [x] Wait 6 weeks for the code owner to provide feedback, either here or in the linked issue
- [x] Attempt to recruit new code owners, potentially from the SkyWalking community (cc @wu-sheng)
- [x] On Jan 26th, the component will be labeled as unmaintained if the original code owner is still unresponsive and no other code owner for the component has been found
- [ ] On June 14th the component will be removed

https://github.com/open-telemetry/opentelemetry-collector#unmaintained

**Comment by wu-sheng** [comment]
@liqiangz I think you were keeping eyes on this. How about now?

**Comment by wu-sheng** [comment]
#6116 @jpkrohling Is there something required in it?

**Comment by jpkrohling** [comment]
The linked issue is about converting the benchmarks from the original PR into proper Go benchmarks.

**Comment by wu-sheng** [comment]
I just know these exporters are used by some SkyWalking users, although, SkyWalking has supported Otel native log and metrics formats too.
What do you expect to change? Finish that PR or something else?

**Comment by liqiangz** [comment]
@jpkrohling @wu-sheng  Sorry, someone was assigned this issue before, I didn't pay attention to this issue anymore.  I will finish this recently.

**Comment by jpkrohling** [comment]
Not only finishing that but handling user's questions related to the components:

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aopen+is%3Aissue+label%3Acomp%3Askywalking

**Comment by jpkrohling** [comment]
@wu-sheng, @liqiangz , was there any progress on the listed issues?

**Comment by wu-sheng** [comment]
I think I have answered most of it, and only one is pending as the https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26315 is still in review.

**Comment by atoulme** [comment]
@jpkrohling please follow up on this issue, as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30294 will impact the exporter.

**Comment by jpkrohling** [comment]
I believe the component is not in a better state than it was since this was first opened. In fact, it's a worse condition, given that the last code owner has been moved to emeritus due to inactivity. It's time to deprecate this component.

**Comment by jpkrohling** [comment]
Great news to SkyWalking users: you should now rely on SkyWalking's native OTLP ingestion port, as mentioned here: https://github.com/apache/skywalking/pull/11909

Therefore, I think we should remove the SkyWalking exporter without fear that it would badly affect users.

**Comment by codeboten** [comment]
@jpkrohling the component status was updated to unmaintained on Jan 26, should the timeline in this issue be updated to reflect this?

**Comment by jpkrohling** [comment]
Done!

**Comment by codeboten** [comment]
Thanks @jpkrohling

**Comment by kellis5137** [comment]
You probably don't even want to talk about this, but does it work? did it ever work?

**Comment by atoulme** [comment]
@jpkrohling it looks like we are past the June 14th date, and it’s time to remove the code.
