### ISSUE TITLE
[pkg/stanza] Reconsider aggresive sampling policy for logger

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#23801]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

Stanza pipelines are built with a very aggressive sampling policy. 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2d23e4d9e0eb313da5d192e1066f444d19b8601f/pkg/stanza/pipeline/config.go#L38C2-L38C2

If I'm reading and understanding this correctly, this means that every second, 1 initial log of a particular message is allowed, then only 1/10000 logs of that particular message is allowed. 

This seems overly aggressive. In fact, it actually makes the file consumer only log the first log it finds on startup here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2d23e4d9e0eb313da5d192e1066f444d19b8601f/pkg/stanza/fileconsumer/file.go#L188C35-L188C35

Meaning, if you have 10 files that are picked up on startup, only one of them is logged. That poses a challenge for debugging whether a file is picked up at all.

In my opinion, we should rely on the logger already being sampled. The collector already [supports sampling](https://github.com/open-telemetry/opentelemetry-collector/blob/827882466634dd4de2991bfa0445c41ca5658a2f/service/telemetry/config.go#L56). It also [samples by default](https://github.com/open-telemetry/opentelemetry-collector/blob/827882466634dd4de2991bfa0445c41ca5658a2f/otelcol/unmarshaler.go#L47) with initial = 100, and thereafter = 100.

**Comment by codeboten** [comment]
After #29886 was merged, I noted a change in the benchmarks. It looks like a 5-10% increase in CPU usage for at least some of the benchmark tests:

![Screenshot 2023-12-19 at 3 15 16 PM](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/223565/2e02741c-7ae0-4c27-b40f-674fdb5f266d)

**Comment by djaglowski** [comment]
I'm looking into the change in benchmarks. My immediate observation is that the tests which jumped up appear to be reporting errors due to malformed inputs, so this is likely not a reason to keep a custom logging configuration.

**Comment by djaglowski** [comment]
I spent quite some time looking into this today and found nothing conclusive. However, there was a preexisting problem, fixed by #30301, which would may have contributed to excess logging. I can't see the full history but it appears these two tests specifically show better performance than before this change. I'm closing this issue but we feel free to reopen if there is more to discuss.

<img width="977" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/5255616/00ab9c06-cef4-4c33-9978-a42565cd521f">
