### ISSUE TITLE
[receiver/wavefront] Wavefront receiver is unmaintained

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#23800]
### Component(s)

receiver/wavefront

### Describe the issue you're reporting

The wavefront receiver is unmaintained.

If no OpenTelemetry member steps up, this receiver will be eventually deprecated and removed from the repository.

Please comment on this issue to volunteer, and open a PR to add yourself to the component maintainers.

- [ ] On Dec 28th, 6 months from now, the component will be removed

https://github.com/open-telemetry/opentelemetry-collector#unmaintained

**Comment by samiura** [comment]
I intend to become the maintainer for the wavefront receiver.

**Comment by samiura** [comment]
@atoulme I think this issue can be closed now.
