### ISSUE TITLE
vCenter capping CPU utilization

### ISSUE THREAD

**Issue by padraicbc** [open-telemetry/opentelemetry-collector-contrib#23813]
### Component(s)

receiver/vcenter

### What happened?

Not sure if this is a bug or simply how vCenter works but we ran a VM to test something under load and noticed CPU util spikes > 100%. The below example shows ~109% and some related values:
 
  ```
  Name ->  CMO_latency_test
  CPU USAGE -> 3263
  vm.Config.Hardware.NumCoresPerSocket*hs.Summary.Hardware.CpuMhz ->  2994
  NUM CPU ->  1
  RUNTIME MAX ->  0
  HOST Mhz  2994
  hs.Summary.Hardware.NumCpuCores ->  16
  hs.Summary.Hardware.NumCpuCores * HOST Mhz ->  47904
  CPU UTIL  108.98463593854376
  ```

Looking in vCenter - some usage spikes were even higher but util never hit > 100%. We thought it may be related to CPU turbo boost, but some reported usage seemed to also rule that out.  We came across similar situations in the community forum posts but no reponses. 

Essentially, it seems VCenter caps util in the graphs. I am not sure it is of any real significance, as utilization is something to be monitored over over a period of time, and within some threshold. 

Capping util at 100% seems a logical resoultion, unless there is something else at hand that we missed.  

### Collector version

N/A

### Environment information

N/A

**Comment by djaglowski** [comment]
Thanks for reporting.

Can you clarify whether this is `vcenter.host.cpu.utilization`, `vcenter.vm.cpu.utilization`, or both?

**Comment by padraicbc** [comment]
> Thanks for reporting.
> 
> Can you clarify whether this is `vcenter.host.cpu.utilization`, `vcenter.vm.cpu.utilization`, or both?

In our case, it's the `vcenter.vm.cpu.utilization`. Not sure if it's the same issue with the host usage.

**Comment by djaglowski** [comment]
I've not been able to find anything definitive, but it seems that the `overallCpuUsage` value reported by vcenter must be higher than the limit. I'm wondering if the way it's calculated is imprecise.

@padraicbc, have you seen the value go substantially over 100% Does it average above 100% for, let's say, 30+ minutes?

@schmikei, any other ideas here?

**Comment by padraicbc** [comment]
> I've not been able to find anything definitive, but it seems that the `overallCpuUsage` value reported by vcenter must be higher than the limit. I'm wondering if the way it's calculated is imprecise.
> 
> @padraicbc, have you seen the value go substantially over 100% Does it average above 100% for, let's say, 30+ minutes?
> 
> @schmikei, any other ideas here?

Pretty sure 109% was about the limit. The CPU specs suggest it has 3.0ghz and turbo boost to up to 3.3. The 2994 reported seemed about right. It hit over 4k according to the vcenter UI graph, 
and at no point did anything show > 100% in the utilisation chart. I think there's definitely something weird with vCenter.

**Comment by djaglowski** [comment]
Thanks for following up @padraicbc.

It sounds like vCenter allows the CPU to run slightly over the requested limit (turbo boost or otherwise), so as best I can tell we are reporting this metric correctly. Does that align with your understanding? If so, I'm not sure we can or should make any change here.

**Comment by padraicbc** [comment]
No worris @djaglowski .  

I think it is fine to mimick the behaviour when the data is presented, which is what we are doing. You can see a flat line in the vCenter charts where it has cut off a peak so it is definitely going above 100%. It's just not shown.

**Comment by crobert-1** [comment]
Hello @padraicbc, it sounds like this question has been answered, and there isn't any work necessary. Is that accurate? If so, we can close this issue.

**Comment by padraicbc** [comment]
> Hello @padraicbc, it sounds like this question has been answered, and there isn't any work necessary. Is that accurate? If so, we can close this issue.

Hi @crobert-1. Sure, I am happy to close it out.
