### ISSUE TITLE
Add Resiliency Features to the Splunk HEC Exporter

### ISSUE THREAD

**Issue by cparkins** [open-telemetry/opentelemetry-collector-contrib#23821]
### Component(s)

exporter/splunkhec

### Is your feature request related to a problem? Please describe.

When using the Splunk HEC Exporter we have run into issues where the Splunk Endpoint is not available for extended periods of time but we have an alternative Splunk Endpoint that can receive the traffic.  It would be nice to have the ability to send to the failover endpoint in the event of a failure.  In addition having the ability to turn off an endpoint that is considered faulty with a circuit breaker pattern would also help reduce the traffic that is attempting to hit the already failing endpoints.

### Describe the solution you'd like

I'd like to be able to send to have an alternative Splunk Server to send data to in the event the primary endpoint is unreachable with the ability to bypass the primary endpoint in the event that it is failing for an extended period of time.

### Describe alternatives you've considered

The other option is to use the retry feature, but that will still send traffic to endpoints that may already be having issues.

**Comment by atoulme** [comment]
> It would be nice to have the ability to send to the failover endpoint in the event of a failure.
That's not a splunkhecexporter specific feature, but probably something to try to implement at the collector level.

> In addition having the ability to turn off an endpoint that is considered faulty with a circuit breaker pattern would also help reduce the traffic that is attempting to hit the already failing endpoints.
That's not specific to this exporter.

> I'd like to be able to send to have an alternative Splunk Server to send data to in the event the primary endpoint is unreachable with the ability to bypass the primary endpoint in the event that it is failing for an extended period of time.

Typically this is best handled with a load balancer. Maybe a nginx load balancer or similar can help here.

**Comment by cparkins** [comment]
>  It would be nice to have the ability to send to the failover endpoint in the event of a failure.
> That's not a splunkhecexporter specific feature, but probably something to try to implement at the collector level.
I tried this route initially and ran into issues, I believe this issues where related to the fact that the Splunk HEC Exporter uses a buffer to send the requests.
> In addition having the ability to turn off an endpoint that is considered faulty with a circuit breaker pattern would also help reduce the traffic that is attempting to hit the already failing endpoints.
> That's not specific to this exporter.
I agree, this is not specific to this Collector but since I want to control the both sets of endpoints it makes sense to implement this way for now.
> I'd like to be able to send to have an alternative Splunk Server to send data to in the event the primary endpoint is unreachable with the ability to bypass the primary endpoint in the event that it is failing for an extended period of time.
> Typically this is best handled with a load balancer. Maybe a nginx load balancer or similar can help here.
I'll look into this and see if it can help resolve our issues or not.

**Comment by crobert-1** [comment]
It looks like this feature request may be implemented by #20766. Is there any value in keeping this issue open or can we close it?

**Comment by crobert-1** [comment]
I'm going to close, but feel free to let us know if there's any feature specific to the Splunk HEC exporter that the failover connector can't handle. We can discuss specifics if necessary.
