### ISSUE TITLE
num_traces many spans that passed decision_wait time are still kept in the memory

### ISSUE THREAD

**Issue by utezduyar** [open-telemetry/opentelemetry-collector-contrib#23825]
### Component(s)

processor/tailsampling

### Is your feature request related to a problem? Please describe.

I have noticed this issue after I reported https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23648. Seems like we always keep num_traces many spans in the memory even though the spans decision_wait time has passed for the spans in the memory, meaning that the spans have been through the decision processes and they have no use anymore.

### Describe the solution you'd like

A suggestion by @jiekun is to set up a go routine to drop them from the memory which I believe is a good way.

**Comment by mizhexiaoxiao** [comment]
read this comment，more discussion is welcome
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23648#issuecomment-1617733950
