### ISSUE TITLE
lokiexporter: Replace logprotos with 'loki-client-go' when a version is released

### ISSUE THREAD

**Issue by gramidt** [open-telemetry/opentelemetry-collector-contrib#2386]
**Is your feature request related to a problem? Please describe.**
In #2385 github.com/grafana/loki was replaced by copied 'logproto' files from the repository, due to incompatible dependency issues. At this time,  the 'loki-client-go' is marked experimental and has not released a version yet. Once this project has released a supported version, we should remove the files added in #2385 and depend on 'loki-client-go'.

**Describe the solution you'd like**
Swap 'exporter/lokiexporter/logproto' for 'loki-client-go' when an official release is ready.

**Describe alternatives you've considered**
- Continue to use the solution implemented in #2385

**Additional context**
This issue has been created  for tracking purposes and cannot be resolved until https://github.com/grafana/loki-client-go has an official supported release.

Loki exporter issue for tracking: #1894

**Comment by bogdandrutu** [comment]
We are not going to do this since they are changing their license and we cannot depend on that
