### ISSUE TITLE
[exporter/awsemf] Metric type IntHistogram is not supported

### ISSUE THREAD

**Issue by pingleig** [open-telemetry/opentelemetry-collector-contrib#2388]
**Is your feature request related to a problem? Please describe.**

When generating IntHistogram using `Int64ValueRecorder` the metric data type is `MetricDataTypeIntHistogram`. Current conversion logic in emf exporter supports all the other metrics types except int histogram.

Is it limitation on cloudwatch backend or just missed during implementation?

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/27dbdd3497cceecec65ca585467278aeb0e2a8e6/exporter/awsemfexporter/datapoint.go#L250-L314

**Describe the solution you'd like**

Implement the conversion logic.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by sethAmazon** [comment]
@alolita should we close this ticket?

**Comment by anuraaga** [comment]
Yup there aren't int histograms in OTel anymore
