### ISSUE TITLE
Unit test coverage upload failed in CircleCI and reported invalid results for the coverage check

### ISSUE THREAD

**Issue by gramidt** [open-telemetry/opentelemetry-collector-contrib#2392]
**Describe the bug**
In #2385 I added third-party code in a directory that should have caused the code coverage check to fail, but it did not. My code passed the checks and was able to be merged. It turns out there was an error in the 'Upload unit test coverage step' and it didn't report it correctly ( https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/9774/workflows/f6ca94b4-38be-459d-800f-d0658cb96918/jobs/81580/parallel-runs/0/steps/0-105 ).

**Steps to reproduce**
TBD

**What did you expect to see?**
The unit test coverage check should have failed.

**What did you see instead?**
All checks on the PR passed.

**What version did you use?**
'main' branch.

**What config did you use?**
N/A

**Environment**
N/A

**Additional context**

**Comment by gramidt** [comment]
@bogdandrutu - This issue is for tracking what happened with the code coverage check in #2385

**Comment by atoulme** [comment]
This is fixed, we now use Github actions.
