### ISSUE TITLE
elasticsearch exporter supports metrics

### ISSUE THREAD

**Issue by zzccctv** [open-telemetry/opentelemetry-collector-contrib#23989]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

We want to store the collected metrics in ES, but we found that this feature is not supported, which makes it difficult for us to integrate

### Describe the solution you'd like

Elasticsearchexporter supports metrics

**Comment by JaredTan95** [comment]
pls have a look https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15345
