### ISSUE TITLE
[exporter/awsemf] set default `dimension_rollup_option ` to `NoDimensionRollup`

### ISSUE THREAD

**Issue by abarganier** [open-telemetry/opentelemetry-collector-contrib#23997]
### Component(s)

exporter/awsemf

### Is your feature request related to a problem? Please describe.

Currently, the `dimension_rollup_option` defaults to `ZeroAndSingleDimensionRollup`. This leads to an expensive explosion of metric counts in CloudWatch once ingested. 

For example, if you have a metric:
`my_metric{label1="a", label2="b"}`

The CloudWatch exporter was exporting this as three unique metrics (potentially more?):
```
my_metric{label1="a", label2="b"}
my_metric{label1="a"}
my_metric{label2="b"}
```

As with most standard timeseries databases/monitoring systems, the *default* behavior here should be to just treat this is a **single metric**, `my_metric{label1="a", label2="b"}`. 

To have the default behavior be anything different leads to large CloudWatch bills, where billing is done **per-metric**. This means that exploding a single metric into multiple drives the bill up considerably, and quite frankly, since I don't see any utility in decomposing a label set into multiple metrics per-label, it seems like the bill is high for no good reason.

### Describe the solution you'd like

The default value of `dimension_rollup_option` should be `NoDimensionRollup` to avoid unexpected huge CloudWatch bills, where users can "opt-in" to the more expensive options if they choose to.

**Comment by bryan-aguilar** [comment]
Hi @abarganier, thanks for bringing up this issue. I think the cost of the `z, and one we have seen before. While I can't comment on the reasoning for the default being set to `ZeroAndSingleDimension` rollup I do agree that `NoDimensionRollup` would be better suited as a default option. I will work on a PR for this and will link to this issue when ready.
