### ISSUE TITLE
[receiver/{dockerstatsreceiver, kubeletstatsreceiver}] Collision with metric container.cpu.utilization

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-collector-contrib#24008]
### Component(s)

receiver/dockerstats, receiver/kubeletstats

### Describe the issue you're reporting

Both `dockerstatsreceiver` and `kubeletstatsreceiver` emit metric with same name `container.cpu.utilization`.

- In `dockerstatsreceiver` the metric is pulled from: https://pkg.go.dev/github.com/docker/docker@v24.0.2+incompatible/api/types#CPUUsage.PercpuUsage

- In `kubeletstatsreceiver` the metric is pulled from:
https://pkg.go.dev/k8s.io/kubelet@v0.27.3/pkg/apis/stats/v1alpha1#CPUStats.UsageNanoCores

I believe one should be renamed to avoid the collision.

**Comment by crobert-1** [comment]
From [the spec](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/#name-reuse-prohibition), metrics should never have the same name, so this is a valid issue.

Links to duplicate named metrics:
[dockerstats](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ac29d5b3823272bfae7ed26694ca8607728d4e00/receiver/dockerstatsreceiver/metadata.yaml#L134)
[kubeletstats](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/metadata.yaml)

**Comment by crobert-1** [comment]
My apologies, from comments on #24229 it looks like I misread the spec and it's likely referring to metrics being unique within a receiver vs. across receivers.

The outcome of this bug will be determined by the decision on #26499.
