### ISSUE TITLE
[pkg/translator/loki] The attributes information under the InstrumentationScope is lost during translation

### ISSUE THREAD

**Issue by xieyuguang** [open-telemetry/opentelemetry-collector-contrib#24027]
### Component(s)

pkg/translator/loki

### Is your feature request related to a problem? Please describe.

I need to set some common attributes for all logs, which I set through "InstrumentationScope", but the attributes info is lost during the Loki conversion process. By reviewing the code in /pkg/translator/loki/encode.go, it was found that the func Encode currently only use the name and version from pcommon.InstrumentationScope.

### Describe the solution you'd like

The attributes information in the pcommon. InstrumentationScope structure needs to be translated and transmitted to loki.

**Comment by mar4uk** [comment]
Thank you for reporting this issue. Currently only `name` and `version` are supported in instrumentation scope in loki exporter. 

Would you like to submit a PR to add attributes support?

**Comment by mar4uk** [comment]
was released in [v0.84.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.84.0) version of the collector
