### ISSUE TITLE
[receiver/prometheus] Invalid timeseries cause the whole scrape to fail

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-collector-contrib#24030]
### Component(s)

receiver/prometheus

## Description
When scraping an endpoint, if any timeseries is rejected by the receiver (for example, because it's missing the required metadata, see #23995), then the whole scrape fails and no data is ingested.

## Steps to Reproduce
A small modification to prometheus receiver's unit tests suffices. I'm going to create a draft PR with a demonstration.

## Expected Result
We should ingest valid data instead of failing the whole scrape.

### Collector version

0.81.0

### Additional context

This is also a partial solution to #23995, where invalid Summaries trigger this problem.

**Comment by dashpole** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24032
