### ISSUE TITLE
[pkg/stanza] syslog input not initializing OctetMultiLineBuilder 

### ISSUE THREAD

**Issue by timannguyen** [open-telemetry/opentelemetry-collector-contrib#24073]
### Component(s)

pkg/stanza

## Description

the following change in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/input/syslog/syslog.go#L64-L66 is being over written on https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/input/syslog/syslog.go#L68. the lines

```
if syslogParserCfg.EnableOctetCounting {
	tcpInputCfg.MultiLineBuilder = OctetMultiLineBuilder
}
```

should be moved to set after 

```
tcpInputCfg.BaseConfig = *c.TCP
```

to prevent being overwritten.

## Steps to Reproduce

enable `enable_octet_counting`  = `true` and the multiline builder is using the default.

### Collector version

v0.81.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
go 20.0

**Comment by djaglowski** [comment]
Thanks @timannguyen. I can't assign the issue to you because you are not yet a member of the OpenTelemetry org, but I'll happily review your PR.
