### ISSUE TITLE
[receiver/mongodbatlas] turn on the resource attribute mongodb_atlas.user.alias by default

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#24071]
### Component(s)

receiver/mongodbatlas

### Is your feature request related to a problem? Please describe.

The PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18881 added the ability to surface `mongodb_atlas.user.alias` but didn't allow for it to be enabled by default.

### Describe the solution you'd like

This issue tracks enabling this resource attribute by default.

**Comment by djaglowski** [comment]
@JonathanWamsley, is this something you could pick up?

**Comment by sakulali** [comment]
Hi @JonathanWamsley, are you still working on this issue? If you are busy, i could try to implement it. I think we would need a feature gate to enable this functionality, right?  I can't find the `mdatagen built-in feature-gate system` refer to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18881#issuecomment-1450474770

**Comment by djaglowski** [comment]
Looking at this again, I'm unclear on what change is being requested. Is the idea to add a feature gate and migrate towards having this resource enabled by default? Generally when adding new _metrics_, we've just left them as disabled by default, but I'm not sure if resource attributes have been or should be handled differently.
