### ISSUE TITLE
Component short names and types do not match

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#24171]
### Describe the issue you're reporting

As reported in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24045#discussion_r1257739023, we currently have 2 competing standards for the short names of components.

On one hand, we have the factory type used to register the component in distros.
On the other hand, we have a name derived off the folder name of the component - called short name for this issue.

Those names do not match and this is starting to impact the following elements:
* The scope name is derived off the short name
* The Github labels are derived off the short name

The type is used everywhere else, including in configuration.

The fix is to choose one option and stick to it moving forward, which may create breaking changes.

**Comment by dmitryax** [comment]
I think it's ok to keep user configuration a bit different and allow `_` for readability. but golang modules should not include them and always have `exporter|processor|receiver|connector|extension` suffix unless they are extension type defining interfaces like `extension/storage`

**Comment by atoulme** [comment]
This isn't blocking anything at the moment ; it's just a weird annoyance for a few components, especially receivercreator.
