### ISSUE TITLE
Link badges to issue filter

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#24181]
## Context

With the most recent changes , https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24045 , adding the issue badges to the readmes, it would be nice to have the badge's link to the issue filter in the contrib for ease of use.

## Definition of done

- Clicking the badge on the readme should open the issue filter in github

**Comment by DewaldDeJager** [comment]
Please assign this to me

**Comment by dmitryax** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24642
