### ISSUE TITLE
[processor/k8sattribute] e2e test fails to setup pod in required time limit

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#24223]
### Component(s)

processor/k8sattributes

## Description

Logs from test failure:

```
=== RUN   TestE2E
    k8s_telemetrygen.go:64: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/k8stest/k8s_telemetrygen.go:64
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/k8sattributesprocessor/e2e_test.go:75
        	Error:      	Condition never satisfied
        	Test:       	TestE2E
        	Messages:   	telemetrygen pod of Workload [Job] in datatype [logs] haven't started within 3 minutes, latest pod phase is 
W0710 [14](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5509366365/jobs/10042200389?pr=24065#step:11:15):50:11.23[17](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5509366365/jobs/10042200389?pr=24065#step:11:18)66   17282 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
W0710 14:50:11.427792   17282 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
W0710 14:50:11.628093   17282 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
--- FAIL: TestE2E ([19](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5509366365/jobs/10042200389?pr=24065#step:11:20)7.01s)
```
[Test failure link](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5509366365/jobs/10042200389?pr=24065)

This occurred on an unrelated [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24065), so I assume it's a flaky test and just wasn't able to set up the environment within the time limit. I have not investigated further to confirm though.

### Collector version

v0.81.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
+1 frequency: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5540434478/jobs/10112716619?pr=24229

**Comment by atoulme** [comment]
This is happening quite often and across all versions of Kubernetes. It makes the e2e tests flaky and I have to retry them quite often.

**Comment by fatsheep9146** [comment]
> This is happening quite often and across all versions of Kubernetes. It makes the e2e tests flaky and I have to retry them quite often.

I will try to dig about this soon.

**Comment by atoulme** [comment]
I recommend we load the telemetrygen docker image into kind to avoid a download. This will help.

**Comment by atoulme** [comment]
Since we merged this PR, we now face a different issue, #25849. We are trying to revert this change with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25853 but the build fails consistently despite rerunning several times.

**Comment by fatsheep9146** [comment]
I think we should close this issue and reopen #25849 
@atoulme

**Comment by crobert-1** [comment]
+1 [frequency](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6018327582/job/16326460441?pr=26076), hit in #26076

**Comment by fatsheep9146** [comment]
> +1 [frequency](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6018327582/job/16326460441?pr=26076), hit in #26076

Got it, I will try to dig this again.
