### ISSUE TITLE
Deprecate and eventually delete the Tanzu Observability Exporter

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#24225]
Hi @atoulme, our nearish-term plan is to deprecate and eventually delete the Tanzu Observerability Exporter. We have better ways to ingest native OTLP protobufs now, so OTel Collector users can just switch to the OTLP Exporter if needed. I believe @keep94 is the one who will be doing the deprecation PR, followed by the eventual deletion PR.

_Originally posted by @oppegard in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23395#issuecomment-1599161238_

* [x] Open a PR to mark the component as deprecated
* [ ] Open a PR to delete the component after deprecation period.

**Comment by keep94** [comment]
@atoulme No, I don't plan to work on this during this quarter.

**Comment by atoulme** [comment]
@keep94 next quarter maybe then? Please let us know, see #23395 for context. We will need to assess by January 2024 what to do with the component.

**Comment by atoulme** [comment]
@oppegard ok to open a PR to delete the exporter?

**Comment by oppegard** [comment]
@atoulme the deprecation warning in the exporter's [readme](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/tanzuobservabilityexporter) states that it will be unavailable after 2023. I'd prefer to wait until the beginning of next year for deleting.

**Comment by atoulme** [comment]
This has been completed. Closing.
