### ISSUE TITLE
[receiver/kubeletstatsreceiver] prepend container. metrics with k8s.

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-collector-contrib#24238]
### Component(s)

receiver/kubeletstats

### Describe the issue you're reporting

There are currently metric collisions between the `dockerstatsreceiver` and `kubeletstatsreceiver`:
- `container.cpu.utilization` #24008
- `container.memory.rss` #24009

And there may arise additional collisions in the future if the metric naming does not differentiate between the two.

This is a proposal to prepend all the `container.*` metrics in the `kubeletstatsreceiver` by `k8s.`. For example, `container.cpu.utilization` will become `k8s.container.cpu.utilization`.

All other metrics in the `kubeletstatsreceiver` are already prepended by `k8s.`.

This could be done in multiple steps (similarly to what was done in #22823). If we take metric `container.cpu.utilization` as an example:
- **Release N**: Add metric `k8s.container.cpu.utilization` disabled by default and deprecate `container.cpu.utilization`
- **Release N+2**: Make `k8s.container.cpu.utilization` enabled by default and `container.cpu.utilization` disabled by default
- **Release N+4**: Remove `container.cpu.utilization`

**Comment by dmitryax** [comment]
This wasn't prepended intentionally because it's essentially the same metric. If you have a container in kubernetes, you extract it with kubelet receiver where there is no bocker engine anymore. If you run a container with docker (on ECS or somewhere else), you use docker receiver. Resource attributes for the containers will always be different. Not sure what collision users can encounter. Please elaborate.

**Comment by mackjmr** [comment]
Looking at how `container.cpu.utilization` is calculated in `dockerstatsreceiver` ([here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/dockerstatsreceiver/metric_helper.go#L23-L40)) vs `kubeletstatsreceiver` ([here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/internal/kubelet/cpu.go#L21-L27)), it seems like they don't represent the same thing (please correct me if I am wrong). For the `dockerstatsreceiver`, it looks like the CPU utilization represents the percentage CPU utilization over a timeframe, whereas for the `kubeletstatsreceiver` it looks like the CPU utilization represents the CPU usage in Cores at a given time (avg of a sample window).

There are some differences as to how they are computed, as they are not pulled from the same place and don't represent the same thing. This doesn't pose an issue if the metric is queried with specific attributes, so that when the metric is being vizualized it only shows values that are pulled from one or the other receiver. That said, I believe having a single metric being pulled from different place can lead to confusion, and having a disctinction between the two allows it to be clearer to the end user as to what the metric they are looking at represents.
