### ISSUE TITLE
Integration tests using test containers are currently skipped

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/opentelemetry-collector-contrib#24240]
### Component(s)

extension/observer/dockerobserver, receiver/dockerstats, receiver/snmp, receiver/sqlquery

### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24213 and https://github.com/testcontainers/testcontainers-go/issues/1359

**Comment by djaglowski** [comment]
Additionally, the `scraperinttest` package is used in many scrapers.

The full list of `Skip` commands can be seen [here](https://github.com/bryan-aguilar/opentelemetry-collector-contrib/pull/3/files).

**Comment by TylerHelmuth** [comment]
List of components that depend on `scraperinttest`

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/12352919/ae286c9e-384f-460f-a026-5af737f92993)

**Comment by TylerHelmuth** [comment]
I believe that means at least 23 components are impacted by this issue

**Comment by mx-psi** [comment]
Labeled this as `release:blocker` since there seems to be agreement among maintainer/approvers that we should hold off from releasing until this is solved to ensure proper testing of all components.

**Comment by jpkrohling** [comment]
@bryan-aguilar, should this be assigned to you? I believe you are tracking this, having it assigned to you would make it more explicit.

**Comment by djaglowski** [comment]
@mdelapenya, is there any way you could help us out here? We've had to temporarily disable all use of testcontainers and are blocking our release until https://github.com/testcontainers/testcontainers-go/pull/1361 is resolved.

**Comment by mdelapenya** [comment]
Hey @djaglowski I'm on parental leave until August 1st. I'll prioritize those open PRs to unblock you 🙏

**Comment by djaglowski** [comment]
Enjoy your time @mdelapenya! Thanks for the response

**Comment by bryan-aguilar** [comment]
@jpkrohling yes feel free to assign this to me. I have been actively monitoring the issue throughout the day and will update my draft PR as soon as a new release is available. 

Maintainers, feel free to push to my PR #24247 if I happen to be AFK when a fix becomes available.

**Comment by mx-psi** [comment]
Can we close this given #24247 was merged, @bryan-aguilar?

**Comment by bryan-aguilar** [comment]
Fixed in #24247
