### ISSUE TITLE
Mapping json in kafka receiver to log record fields

### ISSUE THREAD

**Issue by thmshmm** [open-telemetry/opentelemetry-collector-contrib#24265]
### Component(s)

receiver/kafka

### Describe the issue you're reporting

The implementation of the `json` encoder creates an empty log record and sets the parsed json as body. Additionally it sets the log record timestamp to the current processing time.

Having json log messages in Kafka like

```
{"timestamp": 1689323017, "message": "this is a log message", "logLevel": "info", ...}
```

what is the intended way of mapping the json to a log record that is not just an empty wrapper?

**Comment by crobert-1** [comment]
Hello @thmshmm, from the original issue #20734, it looks like the intention was a pretty simple conversion from `raw` to `json` encoding.

Do you have suggestions on how this could be done better, or any specific requests here?

**Comment by thmshmm** [comment]
Solutions is to just use transformations to extract the body json fields into OTel log record fields. Please close.
