### ISSUE TITLE
[receiver/statsd] Missing obsreport metrics from statsdreceiver

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-collector-contrib#24278]
### Component(s)

receiver/statsd

## Description
The `statsdreceiver` does not properly expose `obsreport` metrics.

## Steps to Reproduce
Send some OTLP and statsd metrics to a collector configured with both receivers.

## Expected Result
I should see `otelcol_receiver_accepted_metric_points_total` timeseries for both receivers.

## Actual Result
I see only a `otelcol_receiver_accepted_metric_points_total` timeseries for the `otlp` receiver.

```
$ curl http://localhost:8888/metrics | grep accepted_metric
# HELP otelcol_receiver_accepted_metric_points_total Number of metric points successfully pushed into the pipeline.
# TYPE otelcol_receiver_accepted_metric_points_total counter
otelcol_receiver_accepted_metric_points_total{receiver="otlp",transport="grpc"} 41
```

### Collector version

v0.81.0

## Environment
Linux

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
  statsd:
exporters:
  logging:
    verbosity: detailed
service:
  telemetry:
    logs:
      level: DEBUG
      development: true
      encoding: console
  pipelines:
    metrics:
      receivers:
      - statsd
      - otlp
      processors: []
      exporters:
      - logging
```

### Log output

```shell
2023-07-14T17:12:54.340-0400    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-07-14T17:12:54.341-0400    info    ResourceMetrics #0
Resource SchemaURL: 
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/statsdreceiver development
Metric #0
Descriptor:
     -> Name: synthetic.counter
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: Delta
NumberDataPoints #0
Data point attributes:
     -> library: Str(statsd)
StartTimestamp: 2023-07-14 21:11:54.340264544 +0000 UTC
Timestamp: 2023-07-14 21:12:54.34085576 +0000 UTC
Value: 1
        {"kind": "exporter", "data_type": "metrics", "name": "logging"}
```

### Additional context
The receiver does seem to be instrumented with obsreport https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5133f4ccd69fa40d016c5b7f2198fb6ac61007b4/receiver/statsdreceiver/reporter.go#L92 so maybe there is a more subtle bug somewhere.

**Comment by sirianni** [comment]
Looks like the call to `reporter.OnMetricsProcessed()` was removed [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/763713b04dae16bd4a63f330246b7853acef7d9f#diff-1e83c4d00a62c67cf42205bfb4f9ab5ad84e98338274460f17f80ab8fa636dc4L123)

**Comment by hardproblems** [comment]
I'd like to reopen this issue as we need some metrics for the receiver to monitor it in production (right now there is none)

**Comment by sirianni** [comment]
I opened #31839 to address this.  We are already using this code in production.

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33415
