### ISSUE TITLE
[exporter/loadbalancingexporter] improve docs for k8s service resolver

### ISSUE THREAD

**Issue by fyuan1316** [open-telemetry/opentelemetry-collector-contrib#24287]
### Component(s)

exporter/loadbalancing

### Describe the issue you're reporting

This issue is a refinement of the FEAT #22776 document.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22776#pullrequestreview-1526872048

**Comment by jpkrohling** [comment]
I believe this has been done already. Closing.

**Comment by awangc** [comment]
@fyuan1316 Thank you for providing support for resolving k8s service. Apologies for asking questions on a closed issue, if there are other preferred venues for clarification questions, please let me know and I can follow up there.

The example provided uses the opentelemetry-operator for deployment. We're on a much older version of kubernetes and the operator won't work. Is it possible to just deploy the loadbalancerexporter as service and connect a different backend service? 

I think the main question I have is if the operator is enabling something that the exporter will need to be able to get updates when there are changes to the endpoints. TIA for the help!
