### ISSUE TITLE
Awsxray exporter requires OTLP trace id to be xray compatible trace Id

### ISSUE THREAD

**Issue by dluongiop** [open-telemetry/opentelemetry-collector-contrib#24389]
### Component(s)

exporter/awsxray

### Is your feature request related to a problem? Please describe.

We are using the awsxray exporter to send traces to AWS X-Ray backend but the exporter is not able to translate the span from OTLP format due to invalid xray trace id.

Other people have encounter this problem: https://github.com/open-telemetry/opentelemetry-cpp/discussions/1259

### Describe the solution you'd like

I think the awsxray exporter should generate a new xray trace id and incorporate the original trace id from OTLP into the xray trace format.  This solution wouldn't require the client to generate the xray compatible trace id.  Also the instrumentation library doesn't need to change to accommodate this.

**Comment by dhilgarth** [comment]
@dluongiop

The issue with this is that X-Ray requires the first 8 hex digits to be a timestamp, specifically the timestamp at which the trace was started.  
In a distributed system, you don't have this info at every point in the system and it's therefore impossible to create a valid X-Ray ID from a trace ID without having the complete trace available.

**Comment by srprash** [comment]
@dhilgarth is right, and that's why it is must for the x-ray format trace id to be generated in the instrumentation.
