### ISSUE TITLE
Custom port connection for CassandraExporter

### ISSUE THREAD

**Issue by TheOxFromOutOfTheBox** [open-telemetry/opentelemetry-collector-contrib#24391]
### Component(s)

exporter/cassandra

### Describe the issue you're reporting

I'm running Cassandra on a Docker container which can't map to to the same ports because I already have another instance running.However, I can't find any way to setup Cassandra exporter on ports other than 7000 and 9042.My docker container exposes those ports at 50000 and 50001 on my host machine.There is no place for me to define the ports to connect to, only the URL of the Cassandra db server.

**Comment by emreyalvac** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25179

**Comment by crobert-1** [comment]
@TheOxFromOutOfTheBox Can you confirm this issue has been resolved? If so, you can close this issue.

**Comment by crobert-1** [comment]
Resolved by #25179
