### ISSUE TITLE
[connector/exceptions] Add trace id and span id to generated logs from exceptions

### ISSUE THREAD

**Issue by marctc** [open-telemetry/opentelemetry-collector-contrib#24407]
### Component(s)

connector/exceptions

### Is your feature request related to a problem? Please describe.

The current implementation generates logs from recorded exceptions in spans, but is not possible to see which traces and spans generated those logs.

### Describe the solution you'd like

It would be useful to correlate spans to generated logs, specially for debugging purpouse during outages. Adding trace id and span id to generated logs from exceptions would make this work.

**Comment by crobert-1** [comment]
The suggestion makes sense to me. 

I'm not familiar with this connector so I went to check if you could get the `SpanID` or `TraceID` from the `dimensions` config option, but they can't. It should be pretty simple to add the attributes to the logs, we would just need some additional config option to set whether or not the user wants this information.

**Comment by jpkrohling** [comment]
@crobert-1 , I think those are issues that @marctc created for himself after creating the component.

@marctc, do you still have this on your radar?
