### ISSUE TITLE
[connector/exceptions] Relate generated metrics from the source trace/span

### ISSUE THREAD

**Issue by marctc** [open-telemetry/opentelemetry-collector-contrib#24409]
### Is your feature request related to a problem? Please describe.

The current implementation generates metrics from recorded exceptions in spans, but is not possible to see which traces and spans generated those metrics.

### Describe the solution you'd like

It would be useful to correlate spans to generated metrics, specially for debugging purpouse during outages. Using exemplars with the generated metrics would this make work.

**Comment by crobert-1** [comment]
_Removing `needs triage` as this was filed by the original author of the component._

**Comment by crobert-1** [comment]
@marctc Would you be interested in being a [code owner](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner) for this component, seeing as you're the main contributor here? It would be great to get some more help on this if you have the availability!

**Comment by marctc** [comment]
> @marctc Would you be interested in being a [code owner](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner) for this component, seeing as you're the main contributor here

Yes, definitely. But I think I have to be maintainer, first right? In any case, I'm interested in both. Thanks!
