### ISSUE TITLE
[exporter/splunkhec] - Add a heartbeat check while exporter startup

### ISSUE THREAD

**Issue by VihasMakwana** [open-telemetry/opentelemetry-collector-contrib#24411]
### Component(s)

exporter/splunkhec

### Is your feature request related to a problem? Please describe.

If there's a faulty HEC token or if the index isn't selected for the given HEC token, then the exporter will start up without errors, and later on it will start failing with 4xx errors. 
It makes sense to run a heartbeat check once with the configs before startup and return an error, if any.
We have a similar thing for health checks, but that doesn't take tokens or indexes into account.

### Describe the solution you'd like

Add a configurable param and add a heartbeat check while startup, something similar to `health_check_enabled`.

**Comment by crobert-1** [comment]
@VihasMakwana Since your PR has been merged for this issue, can we close it?
