### ISSUE TITLE
 [connector/exceptions] Make list of collected HTTP attributes configurable

### ISSUE THREAD

**Issue by marctc** [open-telemetry/opentelemetry-collector-contrib#24410]
### Is your feature request related to a problem? Please describe.

Current implementation collects all span attributes that start with `http.` and includes them to logs. This has two main problems:

- It causes that the generation of logs is not deterministic. Some uses cases might want to collect exceptions from different sources and present consistently in a UI. Instrumentation libraries are using different version of the semantic conventions, therefore, the captured http attributes are different.

- Is not so flexible as some attributes have different prefixes (such as `net.`) or someone would like to capture gRPC attributes.

### Describe the solution you'd like

Add a two new entries in the config (`CollectAttributes`, `RejectAttributes`?) where users can define specific list of attributes that are willing to collect or reject when generating exceptions. The attributes can be specified with a wildcard (`http.`) or with the full path (`http.request.method`). The rejection would allow users to avoid expose in logs sensitive attributes (like HTTP body or any attributes that accidentally could contain secrets) in case some broader collect attribute is defined.

**Comment by crobert-1** [comment]
Have you tried using the [attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor) in your pipeline? It should be able to do what you're looking for here.

**Comment by jpkrohling** [comment]
@marctc, is this still on your radar?

**Comment by crobert-1** [comment]
Now that I come back to this, the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) is probably best to use here, with the [delete_key](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#delete_key) function. 

I see very little value in having to implement, test, and maintain duplicate logic unless there's a very good reason. Let me know if I'm missing something though.

**Comment by marctc** [comment]
@crobert-1 I was on PTO. I'll take a look at your suggested alternative and get back to you. Thanks!

**Comment by marctc** [comment]
Sorry for getting back to this so late! I'm looking at your option. What are you suggesting is to copy all span attributes (instead of only ones starting with `http.`) and recommend using transform processor _before_ the connector to drop unwanted attributes?

**Comment by crobert-1** [comment]
> What are you suggesting is to copy all span attributes (instead of only ones starting with http.) and recommend using transform processor before the connector to drop unwanted attributes?

Yes, that's the idea. My goal is to try to avoid duplicating logic as much as possible, especially if it's something that another widely used component does.
