### ISSUE TITLE
[receiver/sshcheck] Unused resource attribute definition in metadata.yaml

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#24441]
metadata.yaml defines `ssh.endpoint` resource attribute, but it's not applied to the emitted metrics

**Comment by DewaldDeJager** [comment]
@dmitryax I'm keen to take on this issue. I just want to clarify: Do we want to remove the `ssh.endpoint` resource attribute from the `metadata.yml` definition or change the receiver to start applying it?

**Comment by dmitryax** [comment]
This is up to the code owners. I think this should be set, not removed

**Comment by dmitryax** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24676
