### ISSUE TITLE
AWS S3 Receiver

### ISSUE THREAD

**Issue by mpostument** [open-telemetry/opentelemetry-collector-contrib#24448]
### Is your feature request related to a problem? Please describe.

I have EMR which store logs on s3, and i need to have ability receive those logs from s3 and send them to elasticsearch

### Describe the solution you'd like

Configure s3 receiver which point to bucket with emr logs and stream this data to elasticsearch exporter

**Comment by atoulme** [comment]
That’s a whole new receiver. Would you like to contribute it?

**Comment by mpostument** [comment]
Reading docs how to add new component. Let me finish them first and maybe i will contribute

**Comment by atoulme** [comment]
Haven't heard back, so closing as inactive. Please reopen if you have further need here.

**Comment by limberger** [comment]
> That’s a whole new receiver. Would you like to contribute it?

But this component is working? 
I Would like to contribute but not know how ...

**Comment by atoulme** [comment]
Please consider coming to a SIG meeting and talk to other contributors. Join the CNCF slack and ask in the #opentelemetry channel.
