### ISSUE TITLE
[tailsamplingprocessor] does not count count_traces_sampled by policies and service.name

### ISSUE THREAD

**Issue by LaserPhaser** [open-telemetry/opentelemetry-collector-contrib#24449]
### Component(s)

processor/tailsampling

### Is your feature request related to a problem? Please describe.

As I see in metrics:
tailsamplingprocessor does not count count_traces_sampled by policies
by labels by policy are present in metrics

Also I would like too see service labels in this metrics.

### Describe the solution you'd like

I would like too see metrics that are split by service.name and policy. To be able to understand who produce traffic and what rules are in use.

**Comment by jpkrohling** [comment]
I think I understand your request, but to make it more explicit, can you please add an example of a metric as we have today and how you'd like them to be in the future?

I think it's unlikely that we'll have the service.name as a dimension enabled by default, as it could potentially be a high-cardinality metric, but we could have it as configuration parameter, or enabled only when "detailed" is used for the telemetry level of the collector.

**Comment by LaserPhaser** [comment]
Right now I have 5 rules for example. 
And as well I have metrics with 5 labels 

```
count_traces_sampled{service_name="test-service-A", policy="keep_error_http_status", sampled="true", service="otel-collector",  service_version="0.81.0"}    1
count_traces_sampled{service_name="test-service-A", policy="keep_error_status", sampled="true", service="otel-collector",  service_version="0.81.0"}    4123
count_traces_sampled{service_name="test-service-A", policy="keep_force_sampling_header", sampled="true", service="otel-collector",  service_version="0.81.0"}    1223
count_traces_sampled{service_name="test-service-A", policy="keep_force_sampling_header_compat", sampled="true", service="otel-collector",  service_version="0.81.0"}   0
count_traces_sampled{service_name="test-service-A", policy="keep_sampled_success", sampled="true", service="otel-collector",  service_version="0.81.0"} 12133
```

As you may see in my example: 
1) The value of metrics is absolutely the same, so I can't figure out what of rules is most used. 
Adding the service name optionally to the metrics could help to figure out what exact service produce most of traces that were sampled and the reason of sampling. 

So I would like to see somehting like


```
count_traces_sampled{service_name="test-service-B", policy="keep_error_http_status", sampled="true", service="otel-collector",  service_version="0.81.0"}    12312
count_traces_sampled{service_name="test-service-B", policy="keep_error_status", sampled="true", service="otel-collector",  service_version="0.81.0"}    1141
count_traces_sampled{service_name="test-service-B", policy="keep_force_sampling_header", sampled="true", service="otel-collector",  service_version="0.81.0"}    0
count_traces_sampled{service_name="test-service-B", policy="keep_force_sampling_header_compat", sampled="true", service="otel-collector",  service_version="0.81.0"}   1223
count_traces_sampled{service_name="test-service-B", policy="keep_sampled_success", sampled="true", service="otel-collector",  service_version="0.81.0"} 13```


I can implement it if you agree with this proposal.

**Comment by jpkrohling** [comment]
Thanks, that's indeed what I had in mind. Is this taking the service name only for the first span?

**Comment by jpkrohling** [comment]
From which span? There are spans from multiple services belonging to the same trace. If you have a trace with spans from multiple services, are you marking the only the first span that caused the trace to be sampled, or are you taking the service name from the root span?

**Comment by LaserPhaser** [comment]
Ideally... 
I would like to see all matches. 
Like for example if in single trace we match several rules by several different span from different services 

I would see the increment in all [service x rule] metrics.

But I understand that it may cause an additional computations....

**Comment by LaserPhaser** [comment]
@jpkrohling what do you think about it ?

**Comment by jpkrohling** [comment]
I'm still concerned about the cardinality, but let's before anything, could you give me a few examples on how it would look like? Like, show me the traces you'd receive and the metrics that would be generated by them. If you can do that in form of a unit test that can be reused in the future, even better.
