### ISSUE TITLE
Invalid Encoding Values in Kafka Receiver

### ISSUE THREAD

**Issue by akshadhaswamyKH** [open-telemetry/opentelemetry-collector-contrib#24458]
### Component(s)

receiver/kafka

### Describe the issue you're reporting

We are unable to use the following encoding values to receive logs through Kafka Receiver:
`json`, `text` and `text_utf-8`. What's the preferred encoding to use if we want to use Kafka as both exporter and receiver of logs?

> Error: failed to build pipelines: failed to create "kafka/logs" receiver for data type "logs": unrecognized encoding
2023/07/23 20:34:33 collector server run finished with error: failed to build pipelines: failed to create "kafka/logs" receiver for data type "logs": unrecognized encoding

**Comment by atoulme** [comment]
I am pretty sure we talked about this [here](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1690221667751489). Please use the latest release.
