### ISSUE TITLE
[receiver/sqlquery] Logs should support more columns than one

### ISSUE THREAD

**Issue by kago-dk** [open-telemetry/opentelemetry-collector-contrib#24459]
### Component(s)

receiver/sqlquery

### Is your feature request related to a problem? Please describe.

The documentation example on https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/sqlqueryreceiver indicates the SQL query reads the complete column set, which could be log level, severity, user, etc. Unfortunately, log queries (in the sqlquery receiver) do not support _"attribute_columns(optional): a list of column names in the returned dataset used to set attributes on the datapoint."_ 

`receivers:
  sqlquery:
    driver: postgres
    datasource: "host=localhost port=5432 user=postgres password=s3cr3t sslmode=disable"
    queries:
      - sql: "select * from my_logs where log_id > $$1"
        tracking_start_value: "10000"
        tracking_column: log_id
        logs:
          - body_column: log_body`

### Describe the solution you'd like

The sqlqueryreceiver should support mapping SQL columns to attributes (on logs) similar to the workflow on the file log receiver. It will make the receiver more powerful.

**Comment by kago-dk** [comment]
@dmitryax @pmcollins Is it something that could be considered?

**Comment by crobert-1** [comment]
Sounds like a good idea to me. 

For context, log support was added after metric support and is still at `development` stability. The issue to add log support (#20284) acknowledges its state as minimal support, and that there are lots of possible enhancements to be made. I think this is simply something that hasn't been done yet.

Any help is appreciated! You're welcome to submit a PR if you're interested.

**Comment by astencel-sumo** [comment]
💯 agree it's a good direction. This is on my roadmap, but I don't know if and when I'll have time to contribute this. If you @kago-dk or anyone else can contribute this, it would be great.

**Comment by Grandys** [comment]
Hi @crobert-1, I'd appreciate if you could check my PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34485. Cheers

**Comment by crobert-1** [comment]
Resolved by #34599
