### ISSUE TITLE
[receiver/datadog] otlp runtime logs reported error

### ISSUE THREAD

**Issue by callmediaomao** [open-telemetry/opentelemetry-collector-contrib#24562]
### Component(s)

receiver/datadog

### Describe the issue you're reporting

I am using receiver/datadog to export data from datadog agent,but open-telemetry keeps reporting errors.
My demo project is very simple, with step-by-step installation and deployment.I don't know why this is a problem.
datadog-agent version:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/63587783/29c6fced-cf90-4369-ad52-de7bc1c7c99c)

dd-java-agent version(latest):
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/63587783/a706da1c-58fc-4b2d-a5bf-5cde29863a82)

open-telemetry-collector-contrib version:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/63587783/32c00a63-941f-4692-af69-26ade8e760f7)

otel-conf.yaml:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/63587783/78844a1c-1d6f-434f-b7b2-64a5740149e7)

otel error logs:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/63587783/0f44d2b7-57d3-4559-8200-4d333c01db2a)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/63587783/0f44d2b7-57d3-4559-8200-4d333c01db2a)

**Comment by jpkrohling** [comment]
@boostchicken, @MovieStoreGuy , are you able to look into it?

**Comment by callmediaomao** [comment]
@jpkrohling 
I suspect there's something wrong with this part of the code.
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/63587783/c8d017dc-0124-4f9d-9353-85b01d6dbfad)
This code returns null resulting in the following NulPointerException.
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/63587783/8ed933e2-3fd0-446e-b793-042c1c221e3f)
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/63587783/99abfdbf-91bc-4976-bd8c-e18c78640596)

**Comment by MovieStoreGuy** [comment]
> @jpkrohling I suspect there's something wrong with this part of the code. ![image](https://user-images.githubusercontent.com/63587783/256717072-c8d017dc-0124-4f9d-9353-85b01d6dbfad.png) This code returns null resulting in the following NulPointerException. ![image](https://user-images.githubusercontent.com/63587783/256717099-8ed933e2-3fd0-446e-b793-042c1c221e3f.png) ![image](https://user-images.githubusercontent.com/63587783/256717264-99abfdbf-91bc-4976-bd8c-e18c78640596.png)

Amazing detective work! Should be rather easy for me to submit a patch :) 
Thank you.
