### ISSUE TITLE
Allow Transfroms Processor to Truncate log events

### ISSUE THREAD

**Issue by matthewmodestino** [open-telemetry/opentelemetry-collector-contrib#24578]
**Is your feature request related to a problem? Please describe.**

When collecting k8s pod logs with filelog receiver, I use the recombine operator to merge lines to create "multiline events" (ie. docker (16384) or containerd (8192) partial logs). Sometimes these recombined log lines are very large. ie. > 1MB up to 50MB+

After I do this I would like a processor to TRUNCATE the resulting log event aka "body", to protect downstream systems from massive events logged by an application, while retaining some arbitrary number of characters to get minimum value or insight into the log event. For example, many systems default to 10000 characters and allow config to increase to 100K, up to 1MB. etc. 

There is a OTTL transform function that does this, for other data:

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#truncate_all

**Describe the solution you'd like**

The ability to apply truncate_all like option to stings in body for logs as a transforms processor. 

**Describe alternatives you've considered**

Tried using some regex based transforms, like replace_match, etc, but could not get it to allow me to control the length of the "body.string"

Also, while recombine operator lets you set max recombine lines or size, it doesnt let you recombine to a point then drop the rest and start recombining again with a start of line rule. 

**Additional context**

**Comment by TylerHelmuth** [comment]
Is is kind of a duplication of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23847.  You can use `Substring` today to truncate `body.string`.  Once `Len` exists the optimal solution for your use case will be:

`set(body.string, Substring(body.string, 0, 1000)) where Len(body.string) > 1000`

**Comment by TylerHelmuth** [comment]
I am gonna close this in favor of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23847 since they are for the same request.  Please ping me if you feel the issue should be reopened.

**Comment by matthewmodestino** [comment]
Yep, thanks! Will watch for `Len`!

**Comment by matthewmodestino** [comment]
Tested and works like a dream! Thanks Team!
