### ISSUE TITLE
Support for table creation on cluster

### ISSUE THREAD

**Issue by dimei-BT** [open-telemetry/opentelemetry-collector-contrib#24649]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

Hi, it seems the current implementation will create the tables on the current server. Could we add the support for `ON CLUSTER` [clause](https://clickhouse.com/docs/en/sql-reference/distributed-ddl)? Thanks!

### Describe the solution you'd like

Potentially, we can add a config flag to control whether the query will include the `ON CLUSTER` clause.

### Describe alternatives you've considered

Or we can have the query with `ON CLUSTER` clause by default.

**Comment by Frapschen** [comment]
we can have a section to config cluster relate param and I think we also need to consider support config [Data Replication](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#converting-from-mergetree-to-replicatedmergetree) relate params:
```yaml
cluster_model:
  enabled: true
  zoo_path_prefix: /clickhouse/tables/{shard}
  replica_name: {replica}
```
zoo_path_prefix is the prefix of `/clickhouse/tables/{shard}/table_name`, for trace table, it will be `/clickhouse/tables/{shard}/otel_traces`.

if `zoo_path` and `replica_name` are not empty we need to create tables with `Replicated` prefix.


@dimei-BT @hanjm any other suggestion?

**Comment by hanjm** [comment]
I think no need to config zoo_path_prefix and replica_name, it is a common pattern.
in cluster mode, should config collector write local table or distributed table. write local table by default for allowing for better scalability.

**Comment by hanjm** [comment]
> So, for simplicity, it's a good idea to connect the endpoint on every inserting

Agree, we can set short connection simply via `db.SetMaxIdleConns(-1) `.

**Comment by rauanmayemir** [comment]
I manually created tables with `ReplicatedMergeTree` and it works, but what would be a proper DDL for `otel_traces_trace_id_ts_mv`?

**Comment by Frapschen** [comment]
> I manually created tables with `ReplicatedMergeTree` and it works, but what would be a proper DDL for `otel_traces_trace_id_ts_mv`?

you can refer: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/exporter_traces.go#L251

assume you had created a table manually for trace named `otel.otel_trace` , then create the id_ts table and mv table:
```
create table IF NOT EXISTS otel.otel_trace_id_ts (
     TraceId String CODEC(ZSTD(1)),
     Start DateTime64(9) CODEC(Delta, ZSTD(1)),
     End DateTime64(9) CODEC(Delta, ZSTD(1)),
     INDEX idx_trace_id TraceId TYPE bloom_filter(0.01) GRANULARITY 1
) ENGINE MergeTree()
TTL toDateTime(Timestamp) + toIntervalDay(1)
ORDER BY (TraceId, toUnixTimestamp(Start))
SETTINGS index_granularity=8192;
```

```
CREATE MATERIALIZED VIEW IF NOT EXISTS %s_trace_id_ts_mv
TO otel.otel_trace_id_ts
AS SELECT
TraceId,
min(Timestamp) as Start,
max(Timestamp) as End
FROM
otel.otel_trace
WHERE TraceId!=''
GROUP BY TraceId;
```
