### ISSUE TITLE
How does the opentelemetry-collector-contrib use exporters, receivers, processors, etc. of opentelemetry-collector?

### ISSUE THREAD

**Issue by stephenhong** [open-telemetry/opentelemetry-collector-contrib#2467]
I am aware that the opentelemetry-collector-contrib repository and its releases are a superset of the core repository but how does it work? For example, the hostmetricsreceiver is only in the opentelemetry-collector repository but when I run the otel collector with otelcontribcol_linux_amd64 (binary of opentelemetry-collector-contrib), I'm able to use hostmetricsreceiver when it doesn't exist in the opentelemetry-collector-contrib repository. Is there something in the Makefile or another file that references the core repository when making a binary or Docker image of opentelemetry-collector-contrib?

**Comment by Jammicus** [comment]
The project imports the opentelemetry-collector in the main go.mod files in the root of the project.

As far as I can see, in this [file](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/components.go#L85), it calls the default components method from the [collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/defaultcomponents/defaults.go#L52). It then adds the additional components from this project into the relevant variables which gives us access to them.
