### ISSUE TITLE
[exporter/clickhouse] Grafana Dashboard variables loads slow due to OTEL Table-Attributes column

### ISSUE THREAD

**Issue by MacNale** [open-telemetry/opentelemetry-collector-contrib#24675]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

**Here is the scenario -** 
Streaming metrics to clickhouse using clickhouse exporter.  Worked nicely so far.  Created few grafana dashboards.  Added few filter variables in the dashboard so that user can select the system/database/resource to render the dashboard for.  

I am using following query - 
```
SELECT distinct(Attributes['system'])  as system from otel.otel_metrics_gauge where system !='test' order by system;
```
This query performs poorly.  I got 300Mil metric events in the table. It triggers a full scan. The initial dashboard rendering is slow.

### Describe the solution you'd like

- Advice on the sample queries to populate the variables (Attributes) in grafana dashboards.  
- Sample grafana dashboards.

### Describe alternatives you've considered

**Solution** -  Use PREWHERE and time filter to populate the grafana variable
```
SELECT distinct(Attributes['system'])  as system from otel.otel_metrics_gauge PREWHERE $__timeFilter(StartTimeUnix) where system !='test' order by system;
```
This improves the query significantly. Initial dashboard loading time improved.  Is there any better way?

### Additional context
Here is the default table structure created by exporter - 
```
CREATE TABLE IF NOT EXISTS %s_gauge (
....
Attributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
INDEX idx_attr_key mapKeys(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1,
INDEX idx_attr_value mapValues(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1
)
```
The Attributes column is a MAP type. 

Questions - 
1) Why the MAP has been chosen to store Attributes than two associative arrays as shown in the below picture?
2) Will arrays instead of map improve the performance?
3) Can materialized view help here?

**Comment by hanjm** [comment]
The clickhouseexporter table schema is design for most of query scenario, However, it is not efficient if the 'where' condition does not contain any primary key，always add a time filter to the query will speed it up.

1. Clickhouse map type implement as two array underlying.
2. No.
3. It will be fast If you add a materialized view according to the hot query in dashboard.

**Comment by MacNale** [comment]
Reference - https://clickhouse.com/docs/knowledgebase/improve-map-performance

**Comment by MacNale** [comment]
I failed to improve the performance of the filters from Attributes column.  

Looked at gitlab schema - https://docs.gitlab.com/ee/architecture/blueprints/gitlab_observability_backend/

**Comment by Frapschen** [comment]
> https://docs.gitlab.com/ee/architecture/blueprints/gitlab_observability_backend/

Have you tested this idea https://clickhouse.com/docs/knowledgebase/improve-map-performance ?

**Comment by MacNale** [comment]
> > https://docs.gitlab.com/ee/architecture/blueprints/gitlab_observability_backend/
> 
> Have you tested this idea https://clickhouse.com/docs/knowledgebase/improve-map-performance ?

Thank you for sharing the link.  Here is the solution from the web page -

`To improve the query, we can add another column with the value defaulting to a particular key in the Map column, and then materializing it to populate value for existing rows. This way, we extract and store the necessary value at insertion time, thereby speeding up the lookup at query time.
`
I tested this solution and indeed it improves the performance using materlized column. I have 100 unique KEYS in the MAP, I am not sure if it is against best practices to materlize these columns.

**Comment by MacNale** [comment]
> Hi @MacNale This blog https://altinity.com/blog/too-wide-or-not-too-wide-that-is-the-clickhouse-question talks about the wide columns. its say:
> 
> > 10,000 columns seem pretty demanding, but 1000 work just fine out of the box.

"When handling thousands of columns is not desirable, the Map data type can be used. It can provide a good compromise between convenience and performance, especially for sparse tables, when only a fraction of the 10K columns is used in a row."

Although this exporter uses the MAP type, the performance for lookup queries for the 'resource' is not good.
