### ISSUE TITLE
[pkg/ottl] Add Converters for converting `time.Time` and `time.Duration` into an number

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#24686]
With the progress toward supporting `time.Time` in our contexts, we are losing the ability to view times at a specific precision.  Currently all times are represented as unix nano times, which can be easily converted to milliseconds, seconds, minutes, hours, etc.

We need to add Converters for the `time.Time` functions that allow representing the time as a number with specific precision:
- [`UnixNano(time.Time) int64`](https://pkg.go.dev/time#Time.UnixNano)
- [`UnixMicro(time.Time) int64`](https://pkg.go.dev/time#Time.UnixMicro)
- [`UnixMilli(time.Time) int64`](https://pkg.go.dev/time#Time.UnixMilli)
- [`UnixSeconds(time.Time) int64`](https://pkg.go.dev/time#Time.Unix)

We need to add Converters for the `time.Duration` functions that allow representing the duration with specific precision:
- [`Nanoseconds(time.Duration) int64`](https://pkg.go.dev/time#Duration.Nanoseconds)
- [`Microseconds(time.Duration) int64`](https://pkg.go.dev/time#Duration.Microseconds)
- [`Milliseconds(time.Duration) int64`](https://pkg.go.dev/time#Duration.Milliseconds)
- [`Seconds(time.Duration) float64`](https://pkg.go.dev/time#Duration.Seconds)
- [`Minutes(time.Duration) float64`](https://pkg.go.dev/time#Duration.Minutes)
- [`Hours(time.Duration) float64`](https://pkg.go.dev/time#Duration.Hours)

These functions will allow current statement that look like:
- `set(attributes["ms_duration"], (start_time_unix_nano - end_time_unix_nano) / 1000 / 1000))`
- `set(attributes["as seconds"], start_time_unix_nano / 1000 / 1000 / 1000)`

to become:
- `set(attributes["ms_duration"], Milliseconds(start_time - end_time))`
- `set(attributes["as seconds"], UnixSeconds(start_time))`

**Comment by ramu115511** [comment]
OTEL collector is converting time to milliseconds, can you help how can I fix this ? 
FROM:
"rfcTime": "2023-10-30T21:38:17Z"
TO:
rfcTime:  1698701897000
