### ISSUE TITLE
AWS Kinesis Firehose logs receiver

### ISSUE THREAD

**Issue by GilAddaCyberark** [open-telemetry/opentelemetry-collector-contrib#24683]
### Describe the issue you're reporting

Hi All, 
We are trying to use the open telemetry collector to receive logs (managed in AWS CloudWatch Logs) via AWS Kinesis Firehose destinations and ship them to Grafana or OpenSearch. 
AFAIK the firehose receiver handles metrics only.
Does it make sense to handle AWS Kinesis Firehose HTTP Endpoint records as logs as well?
If yes, can we add that as a feature request to the Kinesis Firehose Receiver?

**Comment by Vlaaaaaaad** [comment]
I'd also love to see Amazon Data Firehose (ex-Kinesis) better supported 🙂
