### ISSUE TITLE
Add support for plugins / predefined formats.

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#2471]
Support Stanza-like plugins for log format, see https://github.com/observIQ/stanza/blob/master/docs/plugins.md

Preferably this should be a generic mechanism for importing templated configurations that can be used not just with logs but for other data types, and generally with any configuration section.

Details TBD.

**Comment by bogdandrutu** [comment]
I think this is a "config" change, so probably needs to be in core?
