### ISSUE TITLE
[receiver/sshcheck] Update test config and validate it in tests

### ISSUE THREAD

**Issue by DewaldDeJager** [open-telemetry/opentelemetry-collector-contrib#24739]
The test config file for the SSH check receiver is currently outdated - It uses `keyfile` in the config rather than `key_file`. This needs to be updated and the tests extended to pick up issues like this in future.

See the discussion in a related PR here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24676#discussion_r1279199227_

**Comment by codeboten** [comment]
Thanks @DewaldDeJager!

**Comment by nslaughter** [comment]
I apologize. I've been absent from notifications, but I'm back. I see the issue. Thank you, @DewaldDeJager. Let me know if you would like assistance or I can handle.
