### ISSUE TITLE
[exporter/awsemf] Config validation warning is always ignorred

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#24756]
`Config.Validate` writes a warning "Dropped unsupported metric desctriptor" that is never shown. 

`Config` has `logger` field, which is set to `zap.NewNop()`. So the warning message is always ignored. It should be moved from `Validate` to a start method where logger is available

**Comment by DewaldDeJager** [comment]
I would like to work on this please 😁

**Comment by bryan-aguilar** [comment]
@DewaldDeJager any update on this?
