### ISSUE TITLE
[receiver/splunkhecreceiver] improve docs to tls configuration

### ISSUE THREAD

**Issue by timannguyen** [open-telemetry/opentelemetry-collector-contrib#24799]
### Component(s)

receiver/splunkhecreceiver

### Describe the issue you're reporting

As like many other Receivers, this uses the otel-collector configtls and the current documentation of splunkhec is lacking. A link to the configtls would be useful for users to know what are the available configs.

**Comment by atoulme** [comment]
The [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/562dc48d100ddd87626b898e843c59d14353e57b/receiver/splunkhecreceiver/README.md#L41) contains the following:
```
* `tls_settings` (no default): This is an optional object used to specify if TLS should be used for
  incoming connections.
    * `cert_file`: Specifies the certificate file to use for TLS connection.
      Note: Both `key_file` and `cert_file` are required for TLS connection.
    * `key_file`: Specifies the key file to use for TLS connection. Note: Both
      `key_file` and `cert_file` are required for TLS connection.
```

Please feel free to propose improvements to the documentation.
