### ISSUE TITLE
awsxray exporter doesn't create new segment for an otlp span unless span kind is client or server

### ISSUE THREAD

**Issue by dluongiop** [open-telemetry/opentelemetry-collector-contrib#24807]
### Component(s)

exporter/awsxray

### Describe the issue you're reporting

I have two trace spans between service A and service B. 

I instrumented two services: A and B.  A sends a message to B.

Span.kind of service A is producer and the span.kind of service B is consumer.  I expected the exporter to create two segments and two services should be on the trace map. The result is one service on the trace map and there are two sub-segments representing the producer span and consumer span.

In cloudwatch I expected the traces to be separated under two services like this:

```
Service A:
  doSomething-A

Service B: 
  doSomething-B
```

But this is the result:

```
Service A: 
  doSomething-A
     doSomething-B
```

I am not sure if this is an awsxray exporter problem or a span creation problem.  If I used client and server span kind, the result is what I expected.  However since the service invocation from A->B is asynchronous, the span kind of producer and consumer respectively is the correct convention. 

I've read in https://aws-otel.github.io/docs/getting-started/x-ray that only span.king=server will result in a segment being created. Will producer/consumer be supported in the future?

Please advise.

**Comment by bryan-aguilar** [comment]
I believe this is the current expected behavior and the producer/consumer relationship in X-Ray is still being fleshed out. 

@wangzlei @srprash can you provide any more details here?

**Comment by atshaw43** [comment]
This is the expected behavior today. We are enhancing the experience of consumer spans as Bryan mentioned.

In the future, consumer spans will be promoted to segments with the same naming strategy as server spans. This will make them merge into a single node for the service map.

I am interested in hearing how you would like to see the trace graph look. Perhaps we can setup some time to discuss?
