### ISSUE TITLE
[receiver/azuremonitorreceiver] Consider reducing Go API

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#24850]
### Component(s)

receiver/azuremonitor

### Describe the issue you're reporting

The current Go API exposes the following items:
```
{
  "structs": [
    "ArmClient",
    "Config",
    "MetricsDefinitionsClientInterface",
    "MetricsValuesClient"
  ],
  "functions": [
    {
      "name": "NewFactory",
      "receiver": "",
      "return_types": [
        "receiver.Factory"
      ]
    }
  ]
}
```

Are any of those elements a good target to be unexported?

**Comment by mwear** [comment]
@altuner any chance you can put this on your todo list?

**Comment by nslaughter** [comment]
Would like to remove the -stale label as I've opened #30224 to resolve this.
