### ISSUE TITLE
[pkg/ottl] Remove `ottlarg` struct tag

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#24874]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

The `ottlarg` struct tag was originally introduced to disambiguate the argument ordering of a field in an OTTL `Arguments` struct. Now that it's been implemented, it doesn't seem like it is worth the additional complexity of handling it in the OTTL parser. Top-to-bottom is a natural way to read the fields, and all of our tags match the field ordering anyway.

### Describe the solution you'd like

Make a breaking change as early as possible and remove `ottlarg`, instead having functions simply rely on field ordering within the `Arguments` struct.

**Comment by rnishtala-sumo** [comment]
@evan-bradley I could spend some time on this. It does seem like this will have changes that touch all the Functions/Editors.

**Comment by evan-bradley** [comment]
Thanks for volunteering. It will touch a lot of code, but should be a straightforward change since we're removing functionality.
