### ISSUE TITLE
Monitoring specific ports for hostmetricsreceiver/network

### ISSUE THREAD

**Issue by Vibhu-Ag** [open-telemetry/opentelemetry-collector-contrib#24898]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

We are trying to migrate our monitoring infrastructure from collectd to Open Telemetry. Collectd plugin TCPConns provides a way to monitor specific ports - https://collectd.org/wiki/index.php/Plugin:TCPConns. 

However, the corresponding Open Telemetry implementation for network in hostmetricsreceiver (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/networkscraper/documentation.md) doesn't provide an option to drill down metrics to port level. 

### Describe the solution you'd like

Provision of a field that allows monitoring specific ports similar to how it is achieved in collectd.

**Comment by crobert-1** [comment]
My understanding is that this is not currently implemented by `gopsutil`, the package we rely on for all of the hostmetrics. Would you be able to submit an enhancement request [there](https://github.com/shirou/gopsutil) first? Once it's possible to do with `gopsutil` we'd be able to add the functionality here.

Sorry for the delay!
