### ISSUE TITLE
[PROPOSAL] Change codeowner rules to better match code ownership of modules

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#24907]
### Describe the issue you're reporting

I would like to propose that we change the rules of engagement related to code reviews and make it more clear that codeowners of components must approve changes to their components.

Right now, we have the ability the following set up for each component:
```
exporter/splunkhecexporter/                              @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
```

I propose we change to:

```
exporter/splunkhecexporter/factory.go            @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
exporter/splunkhecexporter/config.go             @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
exporter/splunkhecexporter/README.md        @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
exporter/splunkhecexporter/Makefile                @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
exporter/splunkhecexporter/doc.go                   @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
exporter/splunkhecexporter/metadata.yaml     @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
exporter/splunkhecexporter/go.mod                  @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
exporter/splunkhecexporter/go.sum                   @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
exporter/splunkhecexporter/internal/metadata/ @open-telemetry/collector-contrib-approvers @atoulme @dmitryax
exporter/splunkhecexporter/                                @atoulme @dmitryax
```

Using githubgen, we can generate those rules. What this enforces is that any code change related to the logic of the component itself must be approved by either a codeowner or a maintainer. Approvers can approve but their approval is not binding.

In practice, this changes little: right now, approvers approve and maintainers also approve whenever a change is made.
But sometimes we really want to get codeowners to approve changes related to their code logic, and this would help bring more attention to those occasions.

For changes related to files that are "boilerplate", and often require change across all components, such as changes to mdatagen, it is imo fine to have approvers be binding approvers.

**Comment by MovieStoreGuy** [comment]
Would it be better to have an action that you can request a code owner to review a PR?

```
/notifiy-codeowner # Or something to that affect?
```

**Comment by mx-psi** [comment]
Out code owners file contains many users that don't have write access and thus it does not really work with Github, but rather only with our manual tooling. This change would make no difference as to what approvals are required for a PR to be mergeable, and no difference for the manual tooling, so I think it wouldn't make a difference at all

**Comment by atoulme** [comment]
We can make our tooling fail the PR unless our codeowners approve it. That's still our manual tooling but I guess it works for the occasion. We can notify codeowners right now with a label of the component, albeit only one time.

**Comment by mx-psi** [comment]
> We can make our tooling fail the PR unless our codeowners approve it. That's still our manual tooling but I guess it works for the occasion. We can notify codeowners right now with a label of the component, albeit only one time.

Okay, that's fair! To be honest in that case I would rather move the logic as to what files need codeowner approval to the CI check (if we change the CODEOWNERS file in the proposed way it would end up being 2.4k+ lines long). I also think it's important to have clear rules as to when can we skip codeowners approval (we discussed this internally and there are at least a few exceptions)

**Comment by atoulme** [comment]
That's fair too! Indeed no need to change CODEOWNERS then. This is turning into a lot less work if we can just add a simple check and use a label to override.
