### ISSUE TITLE
Failure exporting _created metrics

### ISSUE THREAD

**Issue by ikstewa** [open-telemetry/opentelemetry-collector-contrib#24915]
### Component(s)

exporter/prometheusremotewrite

## Description

When attempting to enable the `export_created_metric` feature introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17417 the metrics are generated however they're being rejected due to missing a timestamp.

## Steps to Reproduce

Enabled the `export_created_metric` on the prometheusremotewrite exporter and attempt to export to a Cortex instance.

## Expected Result

New metric `my_metric_created` is visible in Cortex.

## Actual Result

Metric is rejected with the following error: `HTTP code 400 (timestamp too old: 0 metric: \"my_metric_created\""`

### Collector version

v0.82.0

### Additional context

My assumption is this is related to the Sample being created without a timestamp: https://github.com/kovrus/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheusremotewrite/helper.go#L496-L516

However it's not clear to me what timestamp it should use. Current time?

**Comment by jmichalek132** [comment]
still relevant

**Comment by jmichalek132** [comment]
Started to looking into fixing this, given plans within prometheus to improve counter behaviour using this metrics.
Accepted proposal within prometheus for this topic https://github.com/prometheus/proposals/blob/main/proposals/2023-06-13_created-timestamp.md.

**Comment by jmichalek132** [comment]
Hi, @bryan-aguilar could you please close this one. It has been fixed in the last release.
