### ISSUE TITLE
httpchecker receiver allow redirects and test tags for hit or absence

### ISSUE THREAD

**Issue by lpegoraro** [open-telemetry/opentelemetry-collector-contrib#24913]
### Component(s)

receiver/httpcheck

### Is your feature request related to a problem? Please describe.

It is not related to a problem, I want to extend the httpchecker to check if endpoint allow redirects, and to test in the content of the request, for a hit or absence of a given string.

### Describe the solution you'd like

1. Add new feature checking if endpoint allow redirects
2. Add new feature testing if content contains or 

### Describe alternatives you've considered

None

**Comment by codeboten** [comment]
Both of these sound like good improvements. @lpegoraro are you interested in working on these? I'd suggest implementing each in a separate PR

**Comment by sakulali** [comment]
> * 1.Add new feature checking if endpoint allow redirects
> * **2.Add new feature testing if content contains or**

Hello @lpegoraro, i just try to implement the second you mentioned with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27015, let's work together to make progress and complete both of these features?

**Comment by lpegoraro** [comment]
Folks, for complete understanding of the issue, this is what the use case I work with is really looking forward.

If this is not the proper channel to have this discussion, you can hit me on slack on CNCF too.

The use case is for this kind of checks
```
{
    "target": "https://my.domain.com/"
    "method": "GET",
    "follow_redirect": true,
    "fail_if_not_tls": true, 
    "tags": ["app-abc", "org-abc", "test2"]
    "contains_text": ["login", "0.0.1", "logo"]
},
{
    "target": "https://my.domain.com/login/"
    "method": "GET",
    "follow_redirect": false,
    "fail_if_not_tls": true, 
    "tags": ["app-abc", "org-abc", "test1"]
    "contains_text": ["login", "3.6.5", "logo"]
}
```

These tags would help us to track better the health checks in each target, and each "contains_text", could be an attribute within these. 
The follow_redirect flag would to prevent any unwanted redirects, iex. login pages. and fail if there is no tls also.
