### ISSUE TITLE
[reciever/haproxy] Default resource attributes are not set on the emitted metrics

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#24920]
The following resource attributes defined in metadata.yaml as enabled by default but not being set on the emitted metrics: `haproxy.url`, `haproxy.pid`, `haproxy.sid`, `haproxy.iid`, `haproxy.type`, `haproxy.algo`. They should be either removed from metadata.yaml or set on the metrics. 

Only `haproxy.addr`, `haproxy.proxy_name` and `haproxy.service_name` are used

**Comment by codeboten** [comment]
Thanks @sakulali!
