### ISSUE TITLE
influxdb receiver does not understand precision=n

### ISSUE THREAD

**Issue by kes2464** [open-telemetry/opentelemetry-collector-contrib#24974]
## Description
By default, Influxdb java client sends nanosecond as precision which is sent as `n` in the precision query string. Based on [TimeUtil.java](https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/TimeUtil.java#L63) 

However, influxdb receiver accepts the precision based on the [line-protocol](https://github.com/influxdata/line-protocol/blob/v2/lineprotocol/precision.go#L55) and it expects to receive nanosecond as `ns`. 

This causes the below error:

```
org.influxdb.impl.BatchProcessor.write Batch could not be sent. Data will be lost
org.influxdb.InfluxDBException: unrecognized precision 'n'
at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:511)
at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:312)
at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:248)
at org.influxdb.impl.BatchProcessor$1.run(BatchProcessor.java:202)
```

## Steps to Reproduce
Enabled influxdb receiver.
Use an influxdb java client to write to the otel collector's influxdb receiver port.

## Expected Result
Should accept the write request.

## Actual Result
Throws an error.

### Collector version

0.82.0

## Environment
Java Compiler: 11.0.15

### OpenTelemetry Collector configuration

```yaml
receivers:
  influxdb:
    endpoint: 0.0.0.0:9999
```

**Comment by jacobmarble** [comment]
I forgot to add "fixes #XXX" in my PR. This issue is fixed.

**Comment by jacobmarble** [comment]
@open-telemetry/collector-contrib-triagers this issue was fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25791 and can be closed.
