### ISSUE TITLE
[metricstransformprocessor] Support `count` aggregation type for `aggregate_labels` action

### ISSUE THREAD

**Issue by musaprg** [open-telemetry/opentelemetry-collector-contrib#24978]
### Component(s)

processor/metricstransform

### Is your feature request related to a problem? Please describe.

I'd like to substitute aggregation by `metricstransformprocessor` for some of our recording rules. It's performing very well, however, it currently doesn't support counting aggregated metrics up by specified `label_set`, which is our blocker. It would be useful for users to support aggregation_type `count` in `metricstransformprocessor`.

### Describe the solution you'd like

I haven't looked into the code base yet, but a simple implementation would be [returning the number of data points (`dps.Len()`) at a specific time](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/74cffb53bead5dd364342772d9b8b58508c7bc3a/processor/metricstransformprocessor/operation_aggregate_labels.go#L156-L201).

We could configure aggregation with the `count` type as:
```
    "metricstransform":
        "transforms":
        - "action": "insert"
          "include": "kube_pod_info"
          "match_type": "strict"
          "new_name": "cluster_namespace:pod:count"
          "operations":
          - "action": "aggregate_labels"
            "aggregation_type": "count"
            "label_set":
            - "namespace"
```

### Describe alternatives you've considered

I don't have any other alternatives for now.

**Comment by dmitryax** [comment]
Hi @musaprg, feel free to submit a PR

**Comment by musaprg** [comment]
@dmitryax OK, thanks! Let me try preparing a PR.
BTW I saw the `needs-triage` label was still there, but is this PR accepted or going to be considered after the PR submission?

**Comment by crobert-1** [comment]
I removed `needs triage` based on @dmitryax's comment. Thanks for your help @musaprg!

**Comment by crobert-1** [comment]
@musaprg Do you still plan on submitting a PR for this enhancement?

**Comment by lopes-felipe** [comment]
Implemented here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32935

**Comment by lopes-felipe** [comment]
Hey @crobert-1 and @dmitryax, would you mind taking a look at that PR? :)

**Comment by musaprg** [comment]
This feature seems to be now landed by https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33442, so let me close this issue. Thanks @lopes-felipe!
