### ISSUE TITLE
SignalFxExporter translation piece "converter" has no active tests with histogram metrics

### ISSUE THREAD

**Issue by samiura** [open-telemetry/opentelemetry-collector-contrib#25067]
### Component(s)

exporter/signalfx

### Describe the issue you're reporting

There are no active tests for histogram metrics conversion to SingalFx datapoints. This [method ](https://github.com/samiura/opentelemetry-collector-contrib/blob/main/exporter/signalfxexporter/internal/translation/converter.go#L67) is used to convert Pmetric metrics  into SignalFx datapoints.  Even though in the test setup we create histogram metrics [here](https://github.com/samiura/opentelemetry-collector-contrib/blob/main/exporter/signalfxexporter/internal/translation/converter.go#L67), however it is not used anywhere subsequently in any actual tests.

**Comment by samiura** [comment]
@atoulme  thanks!

**Comment by dmitryax** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25127
