### ISSUE TITLE
[pkg/ottl] Prevent digit-only function or parameter names

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#25118]
>I just realized our tokens allow for function, and now parameter, names like `1` or `0`.  We should probably not allow that, but we can fix that in a separate PR.

_Originally posted by @TylerHelmuth in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24456#discussion_r1287710484_

**Comment by TylerHelmuth** [comment]
I tested this today and our tokens prevent function names or argument names starting with a digit.
