### ISSUE TITLE
Use Go 1.20 `errors.Join` instead of `go.uber.org/multierr`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#25121]
### Describe the issue you're reporting

Go 1.20 includes new builtin [error joining support](https://pkg.go.dev/errors#Join) that can replace the usage of `go.uber.org/multierr`. We should switch to using these and ban the usage of `go.uber.org/multierr` via `depguard` (same as [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/68c4e181b0d08fbe04931df51218584df2482099/.golangci.yml#L111-L112)).

Counterpart of https://github.com/open-telemetry/opentelemetry-collector/issues/8210.

This is blocked by https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25116

**Comment by bryan-aguilar** [comment]
Would we prefer to see this per component or one big search and replace PR?

**Comment by mx-psi** [comment]
> Would we prefer to see this per component or one big search and replace PR?

I guess it is up to whoever takes this, my experience is that per component (or at least not everything at once) is a bit less frustrating for contributors given the churn of conflicts

**Comment by shivanshu1333** [comment]
I can work on this, @mx-psi kindly assign, would once the blocker PR is merged.

**Comment by gord02** [comment]
Hello everyone. Are there any other components that need to migrate over to the new built-in error support?

**Comment by mx-psi** [comment]
Hey @gord02! There are still components that you can migrate, I think e.g. @shivanshu1333 has not gotten started with processors and most exporters are not done either.

Please see https://github.com/open-telemetry/opentelemetry-collector/pull/8225#discussion_r1302127905 when making a PR: if replacing `multierr.Append` prefer appending to a slice and then using `errors.Join` on the slice!

**Comment by bagmeg** [comment]
Hi I'm interested in working on it. Can i work on it?

**Comment by mx-psi** [comment]
Sure, feel free to open a PR @bagmeg :)

**Comment by bryan-aguilar** [comment]
Feel free to send PRs for components which are still using `multierr` to join errors.
