### ISSUE TITLE
Kafka: Support auth via keystore and truststore

### ISSUE THREAD

**Issue by pranavmarla** [open-telemetry/opentelemetry-collector-contrib#25152]
### Component(s)

exporter/kafka, receiver/kafka

### Is your feature request related to a problem? Please describe.

Currently, although the built-in Kafka console clients let you authenticate via keystore and truststore files (see [here](https://kafka.apache.org/documentation.html#producerconfigs_ssl.keystore.location)), the OTel Kafka clients (i.e. exporter and receiver) do not support that. This makes it more difficult to transition from the built-in clients to the OTel agent.

### Describe the solution you'd like

The OTel Kafka clients (i.e. exporter and receiver) should have new auth settings that take in keystore and truststore files, just like the built-in Kafka clients [do](https://kafka.apache.org/documentation.html#producerconfigs_ssl.keystore.location) -- this allows you to authenticate via the keystore and truststore files.

### Describe alternatives you've considered

Currently, the only way to get around this gap is to manually extract the individual key and certificates from the keystore and truststore files, and then supply those individual key and certificates to the OTel agent -- see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24602#issuecomment-1673854508) for an example.

**Comment by frzifus** [comment]
Sounds reasonable to me. Wdyt @MovieStoreGuy @pavolloffay ?

@pranavmarla would you like to work on this?

**Comment by pranavmarla** [comment]
Thanks @frzifus! Unfortunately, I don't think I'll have time to implement this myself any time soon

**Comment by frzifus** [comment]
Any update on this?
