### ISSUE TITLE
Kafka: Support encrypted TLS keys

### ISSUE THREAD

**Issue by pranavmarla** [open-telemetry/opentelemetry-collector-contrib#25154]
### Component(s)

exporter/kafka, receiver/kafka

### Is your feature request related to a problem? Please describe.

Currently, the OTel Kafka clients (exporter and receiver) support TLS authentication via a private key (`auth.tls.key_file`). However, that key has to be unencrypted, which seems like a security risk. By contrast, the built-in Kafka clients support encrypted TLS keys (specifically, they have an extra param that takes in the password for the TLS key: [link](https://kafka.apache.org/documentation.html#producerconfigs_ssl.key.password))

### Describe the solution you'd like

The OTel Kafka clients should have an extra param that takes in a password for the TLS key, just like the built-in Kafka clients. This enables us to authenticate via encrypted TLS key, instead of requiring the key to be unencrypted.

### Describe alternatives you've considered

Currently, the only alternative seems to be to remove password protection from the TLS key and supply the unencrypted key to the OTel agent, which seems like a security risk.

**Comment by atoulme** [comment]
This would be best handled through a config provider that would inject the configuration. One such possibility is to use an environment variable for example.

**Comment by pranavmarla** [comment]
> This would be best handled through a config provider that would inject the configuration. One such possibility is to use an environment variable for example.

Thanks @atoulme. So you're saying you don't think this isn a feature that should be built into OTEL itself?

**Comment by atoulme** [comment]
I am saying it should not be specific to this field. It should be a feature available for any field.
