### ISSUE TITLE
[XRay] Promote consumer span to segment

### ISSUE THREAD

**Issue by atshaw43** [open-telemetry/opentelemetry-collector-contrib#25177]
### Component(s)

X-Ray Exporter

### Is your feature request related to a problem? Please describe.

Consumer spans are translating to subsegments. The console does not display span links on subsegments.
When the segments are promoted they will create a new node in the console, so we are renaming the segments to the resource service name. This will ensure they are merged into the same node.

### Describe the solution you'd like

Promote consumer spans to segments.
Follow server span naming conventions for consumer spans.

### Describe alternatives you've considered

Only renaming the consumer spans that are local roots.
We do not have access to that information in the console and it will lead to a reduced experience for customers.

**Comment by bryan-aguilar** [comment]
@atshaw43 I see you have a draft PR open. Should I assign this issue to you?
