### ISSUE TITLE
StatsdReceiver: Add support for timers and histograms

### ISSUE THREAD

**Issue by jatan28** [open-telemetry/opentelemetry-collector-contrib#2566]
What is the timeline on adding support for timers to statsd_receiver. Also currently it seems like is in Beta, what is the timeline on getting it to a stable release?

**Comment by gavindoudou** [comment]
I am working on it now. The counter and gauge are already stable.

**Comment by gavindoudou** [comment]
We plan to finish in May this year.

**Comment by tigrannajaryan** [comment]
Collector maintainers are focused on making the [GA release](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/ga-roadmap.md). However if there is an easy to read PR that does not require a lot of time to review we will review it.

**Comment by gavindoudou** [comment]
Can we close that?

**Comment by jmacd** [comment]
This was done.
