### ISSUE TITLE
[metricstransform] Add resource attribute to label support

### ISSUE THREAD

**Issue by seanhoughton** [open-telemetry/opentelemetry-collector-contrib#2568]
**Is your feature request related to a problem? Please describe.**
Resource attributes are not applied as labels to metrics (at least not for the prometheus or stackdriver exporters). Examples include node name, username, pod name, k8s namespace, and other common resource attributes which users may wish to differentiate in metrics analysis tools.

**Describe the solution you'd like**

I would like to be able to use the value of a resource attribute as the source value of an `add_label` action.

**Describe alternatives you've considered**

The only alternative I can think of is to alter the instrumentation in the application and explicitly add the label values to each usage of the metrics instruments. This is slow and intrusive. Being able to quickly manage cardinality in the collector without changing the instrumented application is a very valuable feature.

**Additional context**

I think this is related to another feature request in the opentelemetry-collector project but the prototype solution there is more liberal copy of all resource attributes and only applies to the prometheus exporter https://github.com/open-telemetry/opentelemetry-collector/issues/2412 .

**Comment by pmalek-sumo** [comment]
I'd love to see this type of feature as well.

Some of the features of `metricstransformprocessor` can be achieved with `resourceprocessor` (granted the attributes are at resource level like described in this issue) but without the metric name matching capability (unless it's there but I wasn't able to find it) which might produce unwanted effects (amending metrics that were not supposed to be changed):

```yaml
processors:
  resource:
    attributes:
    - key: X-Host
      from_attribute: host
      action: insert
```

`resource_to_telemetry_conversion` (as stated here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2630#issuecomment-799934380) doesn't really solve this problem because it's an exporterhelper not a processorhelper so it doesn't allow further data manipulation of said data which is just about to be exported not processed by further processors in the pipeline.

If https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2630 got rejected because it "can be already done with `resource_to_telemetry_conversion`", perhaps we should propose a similar helper for the processors?

**Comment by singku** [comment]
@dmitryax Any chance we can review this issue and related PR again?

**Comment by dmitryax** [comment]
@singku, this processor will be eventually replaced by transform processor. So we would like to avoid any new features to metricstransform processor. Please take a look at transform processor to see if it already does what you want.

**Comment by ItsLastDay** [comment]
@dmitryax Does that mean that if I want some feature (for example, this particular issue "resource attribute to label support") to be implemented in metricstransform processor, I'll need to propose that feature to transform processor instead? In other words, is it true that I'll commit the same code, but into another folder? :)

**Comment by dmitryax** [comment]
> Does that mean that if I want some feature (for example, this particular issue "resource attribute to label support") to be implemented in metricstransform processor, I'll need to propose that feature to transform processor instead?

Yes, correct.

> In other words, is it true that I'll commit the same code, but into another folder? :)

It's not the same code. They are completely different codebases providing similar functionality using different configuration approaches.

**Comment by singku** [comment]
Transformprocess support operation like:
```
 set(attributes["the name the new attribute"], resource.attributes["the name of the resource attribute you want to copy"]). 
```

I believe this meet our needs.

**Comment by thediveo** [comment]
> Transformprocess support operation like:
> 
> ```
>  set(attributes["the name the new attribute"], resource.attributes["the name of the resource attribute you want to copy"]). 
> ```
> 
> I believe this meet our needs.

Can someone explain how this is supposed to work in the metrics context? This context provides no attributes element (while it provides `resource.attributes`), so it is impossible to set any metric attribute other then the few predefined ones, such as `name`. How is this supposed to work?

**Comment by BugelNiels** [comment]
@thediveo I ran into the same issue. Looking at the [transformProcessor documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#general-config), it seems that `metrics_statements` exposes the [datapoint](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/contexts/ottldatapoint/README.md) Path prefix. This in turn allows you to update/change the attributes of your metrics .

 The following worked for me:

```
 set(datapoint.attributes["the name the new attribute"], resource.attributes["the name of the resource attribute you want to copy"])
```

**Comment by thediveo** [comment]
Yes that works fine for me too, thank you! I now found out by staring hard at the protobuf stuff that that's the intended way. Funny that all the LLMs out there totally fail at this, but then number interpolation doesn't necessary conclude intelligence.
