### ISSUE TITLE
Had loki.tenant hint attribute is present in both resource and log attributes, but X-Scope-OrgID is not being added to requests header for loki exporter. 

### ISSUE THREAD

**Issue by sairamsadanala** [open-telemetry/opentelemetry-collector-contrib#25730]
### Component(s)

exporter/loki, processor/attributes, processor/resource

## Description

Use case: Setting up oteclcol-contrib as an abstraction layer to receive telemetry and export to Grafana suite. Abstraction layer receives telemetry and forward to exporter by setting up X-scope-OrgID.  Otelcol-contrib reads a log file using "filelog" receiver, fetches Kubernetes namespace from log and sets X-scope-OrgID while exporting to loki endpoint. 
sample log*****(json format)
{"timestamp": "xxxxxxxxxxxxxxx", "kubernetes": {"host": "ip-xx-xx-xx-xx", "namespace_name": "xxxxx-xxx"}}

## Steps to Reproduce

Added tranform processor to fetch Kubernetes namespace from log body and setting as attribute "loki.tenant". Also added resouce processor to set attribute "loki.tenant". I believe it is not required though.
## Expected Result
Suppose to see  loki.tenant in resource attributes and X-scope-OrgID in the request header while  sending to loki exporter.
## Actual Result
 1) loki.tenant is missing in resource attribute from above log, however we could see loki.tenant exists in log attrubutes. 
2) tcpdump output shows no X-Scope-OrgID present in the request header.

### Collector version

0.82.0

## Environment
OS: AWS Linux/UNIX

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
    endpoint: 0.0.0.0:13133     
  headers_setter:
    headers:
      - action: insert
        key: X-Scope-OrgID
        from_context: loki.tenant
receivers:
  filelog:
    include: [/var/log/*.log]
processors:
  resourcedetection/general:
    detectors: [env,ec2,system]
  resource:
    attributes:
    - action: insert
      key: loki.tenant
      from_attribute: loki.tenant
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - merge_maps(cache, ParseJSON(body), "insert") where IsMatch(body, "^\\{")             
          - set(attributes["loki.tenant"], cache["kubernetes"]["namespace_name"])
exporters:
  logging:
    verbosity: detailed
  loki:
    endpoint: "http://XXXXXXX.XXXX.com/loki/api/v1/push"
    tls:
        insecure: false
        insecure_skip_verify: true
    headers:
       "authorization": "Basic **********************"
service:
  extensions: [health_check, headers_setter]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [resourcedetection/general, transform, resource]
      exporters: [logging, loki ]
```

### Log output

```shell
otelcol-contrib log details. 
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: Resource SchemaURL: https://opentelemetry.io/schemas/1>
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: Resource attributes:
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> cloud.provider: Str(aws)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> cloud.platform: Str(aws_ec2)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> cloud.region: Str(XXXXXXXXXXXX)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> cloud.account.id: Str(XXXXXXXXXX)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> cloud.availability_zone: Str(XXXXXXXXXXX)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> host.id: Str(XXXXXXXXXXX)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> host.image.id: Str(************)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> host.type: Str(XXXXXXXXXXXXXX)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> host.name: Str(XXXXXXXXXXXXXXX>
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> os.type: Str(linux)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: ScopeLogs #0
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: ScopeLogs SchemaURL:
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: InstrumentationScope
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: LogRecord #0
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: ObservedTimestamp: 2023-08-14 19:47:01.873016191 +0000>
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: Timestamp: 1970-01-01 00:00:00 +0000 UTC
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: SeverityText:
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: SeverityNumber: Unspecified(0)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: Body: Str({"timestamp": "2023-08-14T19:47:01.772377Z",>
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]: Attributes:
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> log.file.name: Str(XXXXXXX.log)
Aug 14 19:47:01 XXXXXXXXXXXXXXXXXXXX.[1408]:      -> loki.tenant: Str(XXXXXXXXX)



tcpdump output: no X-scope-OrgID present in the request header.

 *********************.33138 > *************.http: Flags [P.], cksum 0x37a5 (incorrect -> 0x07b2), seq 1743:2633, ack 221, win 491, options [nop,nop,TS val 3084851300 ecr 3036626246], length 890: HTTP, length: 890
        POST /loki/api/v1/push HTTP/1.1
        Host: XXXXXXXX-***********.com
        User-Agent: Go-http-client/1.1
        Content-Length: 628
        Authorization: Basic ************
        Content-Type: application/x-protobuf
        Accept-Encoding: gzip
```

### Additional context

- As per loki exporter documentation if the loki.tenant hint attribute is present in one of resource or log attributes, loki exporter adds X-Scope-OrgID in the request header which is not happening.
- Tried with transform processor alone which sets loki.tenant  attribute hint however loki exporter is not setting X-Scope-OrgID in the request header.
- Added both tranform and resource processors but the same result, no X-Scope-OrgID in the request header.
- Added headers_setter extension to set X-Scope-OrgID from loki.tenant hint which was also not helpful.

**Comment by mar4uk** [comment]
`loki.tenant` attribute value should be equal to the name of the attribute you want to use as a tenant.
For example, if the log record has an attribute:
```
{
   "loki.tenant": "tenant",
}
```
that means that loki exporter will try to find the attribute "tenant" to use its value for X-Scope-OrgID.

So to make your config work the next change is needed:
```
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["cache"], ParseJSON(body)) where IsMatch(body, "^\\{")
          - set(attributes["tenant"], attributes["cache"]["kubernetes"]["namespace_name"])
          - set(attributes["loki.tenant"], "tenant")
          - delete_key(attributes, "cache")
```

headers_setter and resource processors are not needed if transform processor is used in this case

**Comment by sairamsadanala** [comment]
Thank you so much Irina. I quickly tested the suggested configuration and able to see X-Scope-Orgid in the request header now. I will conduct more testing and close the bug. 

        POST /loki/api/v1/push HTTP/1.1
        Host: grafana-lokiXXXXXXXX.com
        User-Agent: Go-http-client/1.1
        Content-Length: 627
        Authorization: Basic *********
        Content-Type: application/x-protobuf
        X-Scope-Orgid: XXXXXXXXXXXX
        Accept-Encoding: gzip

**Comment by mar4uk** [comment]
nice! One more thing: you can keep using the `cache` variable as you did before (I haven't used it before that's why rewrote it to atttributes["cache"] to be safe)
```
  transform:
    log_statements:
      - context: log
        statements:
          - merge_maps(cache, ParseJSON(body), "upsert") where IsMatch(body, "^\\{")
          - set(attributes["tenant"], cache["kubernetes"]["namespace_name"])
          - set(attributes["loki.tenant"], "tenant")
``` 
this configuration should work

**Comment by sairamsadanala** [comment]
yep, thanks.

**Comment by jpkrohling** [comment]
Is there anything else to do here, or can this be closed?

**Comment by sairamsadanala** [comment]
Sorry for the late reply. We can close it.

**Comment by jpkrohling** [comment]
Thank you for the confirmation!
