### ISSUE TITLE
When can this vulnerability Prompted by Dependabot "A stored XSS in jaeger UI might allow an attacker who controls a trace to perform arbitrary jaeger queries" be solved?

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#25817]
### Describe the issue you're reporting

Hi,

I tried to push the Opentelemetry Source Code Vesion 0.82.0 into my Company Github Repository and the dependabot prompts the following vulnerability.

Vulnerability Name: A stored XSS in jaeger UI might allow an attacker who controls a trace to perform arbitrary jaeger queries
CWE No: [CWE-79](https://cwe.mitre.org/data/definitions/79.html)
CVE ID: -

May I know when can this vulnerability be solved, please? OR
When is the expected timeline for this vulnerability be solved, please?

Thank you.

Best Regard,
Erica Ooi

**Comment by ericashi** [comment]
Hi @codeboten,

Can we have a rough timeline (eg: 1week, 2weeks, 1month, etc) on when this can be solved, please?
We saw this vulnerability and wanted to know when it can be addressed to estimate when we can use Opentelemetry in our company development environment.

Thank you.

Best Regards,
Erica Ooi

**Comment by codeboten** [comment]
@ericashi I'm not involved in #18485, I would suggest asking on that PR for any update. Once that PR is merged, we'll be able to update the dependency. The release cadence for the collector is every two weeks, you can see the schedule here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#release-schedule

**Comment by frzifus** [comment]
Link: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18485#issuecomment-1689396275

**Comment by crobert-1** [comment]
From comments linked, this is not a valid issue for the repository itself, and there are workarounds available. Closing based on this information.
