### ISSUE TITLE
[pkg/ottl] Introduce function to extract matched regex groups into a map

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#25834]
As suggested in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25128#issuecomment-1679074031

The purpose of the function is to be able to parse a string with a regex and put values from matched groups as key/value pairs to a map.

It can be called `extract`, or `extract_pattern` to avoid possible conflicts in the future.

```
extract_pattern(<target_map>, <source_string>, <pattern>, deleteOriginal=<bool, default: false>)
```

Example:

```
- extract_pattern(attributes, attributes["k8s.change_cause"], "GIT_SHA=(?P<git.sha>\w+)", deleteOriginal=true)
```

If pattern `"GIT_SHA=(?P<git.sha>\w+)"` matches against `attributes["k8s.change_cause"]`, `git.sha` attribute will be set in `attributes` with the value from the matched group. Optional `deleteOriginal` argument is used to make sure that `attributes["k8s.change_cause"]` is removed after the operation is complete regardless `git.sha` was set or not.

**Comment by newly12** [comment]
I was thinking something like a function that returns a map, similar to `ParseJson`.

```
ExtractPattern(<source_string>, <pattern>)
```

So it can be combined with `merge_maps`, and delete original key if needed can be done by another `delete_key` statement, Please let me know your thought on this.

```
merge_maps(attributes, ExtractPattern(body, "^(?P<timestamp>\\w+ \\w+ [0-9]+:[0-9]+:[0-9]+) (?P<hostname>([A-Za-z0-9-_]+)) (?P<process>\\w+)(\\[(?P<pid>\\d+)\\])?: (?P<message>.*)$"))
```

**Comment by dmitryax** [comment]
@newly12, the suggestion LGTM. It's probably better to keep functions as simple as possible. @TylerHelmuth WDYT?

**Comment by newly12** [comment]
I had one implementation in #25878, PTAL, thanks in advance.

**Comment by TylerHelmuth** [comment]
@newly12 I like your proposal.  @evan-bradley do you agree?
