### ISSUE TITLE
[receiver/vcenter] Integration test emits duplicate resources

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#25831]
The integration test emits two identical resource metrics https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/vcenterreceiver/testdata/integration/expected.yaml#L602-L657.

The test client returns two `ResourcePool` objects with the following inventory paths in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/vcenterreceiver/scraper.go#L217:
- /DC0/host/DC0_H0/Resources
- /DC0/host/DC0_C0/Resources

The resource attribute `vcenter.resource_pool.name` is set to the last part of the inventory paths: `Resources`.

It's unclear if this is just an integration test or if the same is happening in the real world. 

If it's not just an integration test, we need to either adjust the resource attributes to be distinct or introduce some deduplication logic

**Comment by schmikei** [comment]
It is my understanding that it is *very* uncommon to have 2 resource pools named the same from an operations standpoint... I can look into if this is actually limited in vCenter though. 

The simulator that govmomi is providing is the source of this issue, but I'll try and do some exploration on what the best way to safeguard against this would be if its the receiver's responsibility to add the InventoryPath as an attribute or more internal object references to safeguard against this.

Snippet from simulator: https://github.com/vmware/govmomi/blob/main/simulator/esx/resource_pool.go

**Comment by djaglowski** [comment]
> seems like we may want to add the inventory path as a resource attribute

Will this account for the three possible scenarios mentioned by @Dylan-M?

> Parents being one of the following: A host that is not in a cluster, a DRS enabled cluster, or another resource pool.

**Comment by Dylan-M** [comment]
@djaglowski It should. The example from the OP is with hosts, but the other 2 options should also have an inventory path. In the event they don't, there is also a unique object ID that can be gathered via another API call. @schmikei should be able to find out from the documentation. I can continue to assist him in looking into it as well.

**Comment by djaglowski** [comment]
Ok, sounds like a good solution. Thanks @schmikei, @Dylan-M
