### ISSUE TITLE
Support Persistent_Queue in Azure Monitor Exporter

### ISSUE THREAD

**Issue by codesmon** [open-telemetry/opentelemetry-collector-contrib#25859]
### Component(s)

exporter/azuremonitor

### Is your feature request related to a problem? Please describe.

To make the exporter robust enough for production use, it needs to support the persistent_queue capabilities used elsewhere, such as the Elastic Search Exporter. 
When the connection to Applicaiton Insight breaks, we need to persist the telemetry data to disk, not just hold it in memory to safeguard it against container recycling.

### Describe the solution you'd like

Implementation of the persistent queue capability for logs, metrics and traces.
To use sending_queue configuration to be able to determine which storage location to send the data to.

### Describe alternatives you've considered

Reusing the existing persistent queue capabilities already supported by the exporterHelper would be the most efficient way of achieving this.

**Comment by crobert-1** [comment]
I was able to look into this a bit, and it sounds like a good idea to me. The `azuremonitor` exporter is already relying on the `exporterhelper` exporter to send metrics, traces, and logs, so it shouldn't be too hard to add another configuration option for the existing `QueueSettings` option.

**Comment by crobert-1** [comment]
Apologies for the delay! You're welcome to submit a PR for this if you're interested!
