### ISSUE TITLE
improve mntr regex to match user specific keys

### ISSUE THREAD

**Issue by freyayunfu** [open-telemetry/opentelemetry-collector-contrib#25851]
### Component(s)

receiver/zookeeper

## Description
Seeing below warning messages from `zookeeperreceiver`
```
{"level":"warn","ts":1692234961.9064589,"caller":"zookeeperreceiver@v0.82.0/scraper.go:144","msg":"unexpected line in response","kind":"receiver","name":"receiver_creator/zookeeper","data_type":"metrics","name":"zookeeper//receiver_creator/zookeeper{endpoint=\"10.212.193.34:2181\"}/k8s_observer/9d39a24e-2e8d-46bf-bffd-2b45edc90a75","command":"mntr","line":"zk_max_pkc-supreme-fox_write_per_namespace\t42343"}
```

## Steps to Reproduce
Currently, if the line includes uses specific keys, like `zk_max_pkc-supreme-fox_write_per_namespace\t42343`, our regex would not be able to parse it. And would give `unexpected line in response` warning message.

## Expected Result
If we update the regex into 
```
	var zookeeperFormatRE = regexp.MustCompile(`^(zk_\w[\w\.\-]*)\s+([\w\.\-]+)`)
```

Then line `zk_max_pkc-supreme-fox_write_per_namespace\t42343` would be successfully split into
```
key: zk_max_pkc-supreme-fox_write_per_namespace
value: 42343
```
Similar issue handled by the other repo: https://github.com/influxdata/telegraf/pull/7533

### Collector version

v0.82.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
Since the code owner has commented positively on the PR I'll remove the needs triage label, and assign to @freyayunfu as a PR has been opened. Please let me know if this is incorrect.
