### ISSUE TITLE
Substring function: use IntGetter argument 

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#25852]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

I am trying to trim a few characters of a string with `Substring` function, however following statement produces error.

```
set(attributes["substring"], Substring(body, 16, Len(body) - 16))
```

```
invalid config for "transform" processor unable to parse OTTL statement "set(attributes[\"substring\"], Substring(body, 16, Len(body) - 16))": error while parsing arguments for call to "set": invalid argument at position 1: error while parsing arguments for call to "Substring": invalid argument at position 2: must be an int
```

### Describe the solution you'd like

change argument type from `int64` to `ottl.IntGetter`

**Comment by TylerHelmuth** [comment]
@newly12 you're totally right.  Is this something you want to work on?
