### ISSUE TITLE
Load balance metrics for cumulative to delta

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#25858]
### Component(s)

exporter/loadbalancing

### Is your feature request related to a problem? Please describe.

The cumulative to delta processor cannot be scaled right because the same metrics need to end up in the same Collector. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/cumulativetodeltaprocessor#warnings

### Describe the solution you'd like

Extend the load balancing exporter to also support load balancing metrics.

**Comment by jpkrohling** [comment]
Do you think it's sufficient to take only the metric name into consideration, or should it take the resource attributes (names and values) as well?

**Comment by gouthamve** [comment]
It should also have attributes. There could be one metric name which is 90% of all the metrics. 

We've seen this in Cortex. Before we used to only shard on metric name and this caused extreme hot spotting. We then switched to include the labels too.

**Comment by jpkrohling** [comment]
Given we have code for both logs and traces, I'm marking this as "good first issue" before working on that myself.

**Comment by claudiobastos** [comment]
@jpkrohling I would like to contribute on this one

**Comment by claudiobastos** [comment]
@jpkrohling 

Does it make sense that routing based on Service and Routing based on Metric (+Resource attr/values) should be mutualy exclusive?

When balancing metrics, if service routing is defined, it should only balance a subset of them ?

**Comment by jpkrohling** [comment]
@gouthamve, it would be nice to get your opinion, but I think the routing_key for metrics should be one of: service, metric, resource, attribute:

* when service is provided, the service.name resource attribute alone is used for load-balancing
* when metric is provided, the metric name alone should be used
* when resource is used, the metric name plus all resource attribute names and their values should be used
* when attribute is used, the metric name plus all resource attribute names and their values should be used, in addition to the data point's attribute names and values

**Comment by gouthamve** [comment]
While it makes sense, which would be the default?

**Comment by claudiobastos** [comment]
How about one routing key specific for metrics ? @jpkrohling @gouthamve

**Comment by jpkrohling** [comment]
I think `service` could be a good default, as it probably has the best performance of them all while still being reasonably good for deployments with a good number of services. Otherwise, `resource`, which would provide the best balancing but with higher costs.

I think we should not implement `attribute` at the beginning, as it requires going too deep into the metric data points.
