### ISSUE TITLE
Timeout cannot be configured for snmp receiver

### ISSUE THREAD

**Issue by technimad-splunk** [open-telemetry/opentelemetry-collector-contrib#25885]
### Component(s)

receiver/snmp

### Is your feature request related to a problem? Please describe.

Some devices are slow to respond. It can take more than the hard coded 5 seconds to get a reply. Currently these requests fail, as they time out. 

the following message is logged when this happens:
```
2023-08-18T12:39:55.762Z	error	scraperhelper/scrapercontroller.go:200	Error scraping metrics	{"kind": "receiver", "name": "snmp", "data_type": "metrics", "error": "problem with getting indexed data: problem with SNMP WALK for OID '.1.3.6.1.4.1.14988.1.1.1.2.1.9': request timeout (after 0 retries)", "scraper": "snmp"}
```

### Describe the solution you'd like

Make the timeout configurable. Use a `timeout` parameter at the level the connection is defined i.e.:
```
receivers:
  snmp:
    collection_interval: 30s
    version: 2c
    timeout: 25s
```

### Describe alternatives you've considered

Alternative for now is to limit the number of oid to retrieve per receiver configuration. Effectively splitting a configuration in multiple receivers, and hope all will receive data within 5 seconds.

### Additional context

Current timeout is defined here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/snmpreceiver/client.go#L65

**Comment by djaglowski** [comment]
Seems reasonable. Is this a change you could contribute @technimad-splunk?

**Comment by technimad-splunk** [comment]
I will give it a go. Seems trivial to add.
