### ISSUE TITLE
[receiver/kubeletstats] Discuss if `*.uptime` metrics should be enabled by default 

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#25915]
### Component(s)

receiver/kubeletstats

### Describe the issue you're reporting

The kubeletstatsreceiver recently gain the new metrics `k8s.node.uptime`, `k8s.pod.uptime`, and `container.uptime` to measure the time, in seconds, since the object's `StartTime`.  Following the scrapping metrics procedure, these metrics are disabled by default.

I'd like to discuss whether these metrics should be default metrics for the receiver. Based on [our documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/scraping-receivers.md#how-to-identify-if-new-metric-should-be-default-or-optional), we need to consider the following:

1. Is `*.uptime` essential to determine the healthiness of nodes/pods/containers?
2. Is `*.uptime` redundant with any other optional metric?
3. Does `*.uptime` create disproportionately high cardinality of resource and/or data points?
4. Does `*.uptime` have a performance impact?
5. Does `*.uptime` require configuration in an unusual way?

I believe 2-5 are answered. The new metric is not redundant, it does not create disproportionately high cardinality of resource and/or data points, it does not have a performance impact, and does not require any unusual configuration.

For 1, I feel the `*.uptime` metrics are essential to determine the healthiness of a `pods/containers`. Here is the situation that I believe justifies a default status for `k8s.pod.uptime`, and `container.uptime`:

Many runtime frameworks, such as Java and JS. take up large amounts of memory on startup. Any alert based solely on memory usage would be sensitive to a pod/container restart as the restart could cause a spike in memory that triggers the alert. `*.uptime` provides the essential information to handle this issue by allowing the alert to trigger only when memory is high AND uptime is greater than X.

Uptime is a metric Honeycomb includes by default in its [Honeycomb Kubernetes Agent](https://github.com/honeycombio/honeycomb-kubernetes-agent) and the [Datadog Agent](https://docs.datadoghq.com/containers/kubernetes/data_collected/) (@mx-psi I am claiming this based on the docs I found, but have not run the agent myself). Kube-state-metrics also reports a similar metrics, `kube_pod_start_time` and `kube_pod_container_state_started`, that represent when the pod/container started, which can be used to achieve the same goals as our `*.uptime` metrics.

For these reason I feel `k8s.pod.uptime`, and `container.uptime` should be enabled by default.

**Comment by TylerHelmuth** [comment]
Update from our discussion during the SIG today:

@dmitryax proposes that `*.uptime` does not pass item 2, that default metrics should not be redundant. The argument presented was that `uptime` could be inferred from other existing default metrics, specifically restart count and the start-time value on existing default metrics.

**Comment by mx-psi** [comment]
> and the [Datadog Agent](https://docs.datadoghq.com/containers/kubernetes/data_collected/) (@mx-psi I am claiming this based on the docs I found, but have not run the agent myself).

I think this is correct, these are sent by default indeed by the Datadog Agent

**Comment by TylerHelmuth** [comment]
On the topic of inferring, I've been trying to think about how I'd use `restart_count` in an alert in different backends to detect a restart, similar to the query mentioned in the description (`trigger only when memory is high AND uptime is greater than X).

To start, the kubeletstatsreceiver does not provide a `restart_count` metric.  The k8sclusterreciever does, but it specifically mentions not to rely on specific values, only if the value is greater than 0. I don't like setting a precedence that in order to infer a metric you need multiple receivers.

When using the k8sclusterreceiver's `restart_count`, I believe writing a query to detect restarts would be unreliable.  Although you could write "trigger only when memory is high AND restart_count = 0", that type of query will be very dependent on how the cluster's kubelet is configured to removed dead containers. 

Depending on metric start time also assumes your backend exposes that field for querying and provides time functions so you can calculate uptime yourself. Do Metric Time Series databases normally allow using `start_time` in a query? I was not able to find an example for Prometheus, but I admit I am not a Prometheus user (@jpkrohling, @dashpole  can you weigh in?). While this is a query that would be writable in Honeycomb, I don't like the idea of depending on backends having specific capabilities in order to infer the metric.

**Comment by jpkrohling** [comment]
> I don't like the idea of depending on backends having specific capabilities in order to infer the metric

To me, this is reason enough to have the suggested metric. I agree with @dmitryax that there might be ways to find this value for some (most?) databases, but even when it's possible, it might be easier to build queries when those values are stored as metrics as well.

**Comment by gouthamve** [comment]
You could do `time() - kube_pod_container_state_started{namespace="your-namespace", container="your-container"}` to get the uptime in Prometheus.

https://prometheus.io/docs/prometheus/latest/querying/functions/#time

**Comment by gouthamve** [comment]
It is possible and would look like: `(time() - kube_pod_container_state_started > 3600 * 10) and (process_memory_bytes > 10 * 1024 * 1024)`

However the labels on the left and right should match and you can do that through: https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching. Further, I typically don't see `uptime` as a metric in the Prometheus world, but rather `time() - *_start_time_seconds`.

Having said that, I agree its kinda Prometheus specific, and I am not super involved in the `kubeletstats` development to comment on if it makes sense to be included by default tbh.

**Comment by TylerHelmuth** [comment]
@gouthamve I might be confused.  In my understanding `kube_pod_container_state_started` is a Kube State Metrics metric that represents when a container started.  It is not a representation of the OTLP metric field `start_time_unix_nano ` right?

I ask because @dmitryax proposed a counter argument to point 2 from the description stating that for kubeletstats metrics the `start_time_unix_nano` field could be used in a similar way to `uptime`.  He is right, but I want to make sure that common metric databases allow using this field in queries.

As for KSM's use of `kube_pod_container_state_started`, I agree that they have implemented that metric instead of calculating `uptime` for users automatically.  But our equivalent otel component, k8sclusterreceiver, does not, nor would I want to require users to implement the k8sclusterreceiver or KSM to infer `uptime`.

**Comment by dmitryax** [comment]
> I don't like the idea of depending on backends having specific capabilities in order to infer the metric

I don't think we should consider this argument. Every backend has different capabilities. We should not enable all metrics to cover all possible capabilities that backends can miss. We should focus on what data we send in OpenTelemetry format. The meaning of the second rule is that we should not enable metrics OOTB that provide information that can be determined from other default metrics. 

> To me, this is reason enough to have the suggested metric

@jpkrohling to clarify, we already have those metrics. They are just optional, not enabled by default

**Comment by TylerHelmuth** [comment]
I do like pointing to KSM as an example of why this metric is important by default. KSM presents it a different way, but does give the capability by default.  Unless `start_time_unix_nano` really is usable by most backends, I do not believe there is another way to represent `uptime` with kubeletstatsreceivers current default metrics.

**Comment by gouthamve** [comment]
Aaah, you were referring to something else. [`start_time_unix_nano`](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#temporality) is currently not usable in Prometheus. We discard that part altogether on ingest.

**Comment by TylerHelmuth** [comment]
I dug into Honeycomb and we drop the value as well (although if someone moved it to an attribute via the transformprocessor they could use it).

This makes me feel stronger that `uptime` is a unique enough metric to be included by default. @dmitryax I believe I've provided evidence that we can't infer `uptime` from other metrics/data coming from kubeletstats receiver.  If you agree, I believe that would warrant `uptime` being a default metric as it meets the other criteria.

**Comment by TylerHelmuth** [comment]
@gouthamve do you know if Prometheus alerting allows calculating how long a metric time series has existed and using that information in the trigger criteria? The use case I am thinking about is when a container restarts and preventing an triggering until a certain amount of time has passed.

This capability is easy with a metric like `uptime`: `trigger only when memory is high AND uptime is greater than X`.  Does Prometheus have any way to represent that alert with only the `memory` metric and the fact that  a new metric time series would be created when the container starts up (because it would have a unique container id associated to it).

**Comment by gouthamve** [comment]
Prometheus doesn't have a good way of determining how long a metric has existed, unfortunately.

It will require either `uptime` or `_started_seconds` metric.

**Comment by jinja2** [comment]
Would a query like below example work? 

`present_over_time({process_memory_bytes[1m] offset 10m) and (process_memory_bytes > 10 * 1024 * 1024)`

From my limited understanding of promql, this should return a value iff the timeseries started reporting more than 10 minutes ago (the over_time interval should be greater than scrape interval).
