### ISSUE TITLE
Request to add @crobert-1 as triager

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#26023]
### Describe the issue you're reporting

I'd like to volunteer to be a triager. I've been an active member of the OpenTelemetry community for some time and would like to be able to contribute more to the collector.

Contributions in the contrib repository:
[Pull requests](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3Acrobert-1+)
[Issues](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+author%3Acrobert-1+)

**Comment by MovieStoreGuy** [comment]
I support!

**Comment by fatsheep9146** [comment]
I support!

**Comment by fatsheep9146** [comment]
I support~
