### ISSUE TITLE
[receiver/postgresql] Additional metric: number of sequential scans.

### ISSUE THREAD

**Issue by bjandras** [open-telemetry/opentelemetry-collector-contrib#26096]
### Component(s)

receiver/postgresql

### Is your feature request related to a problem? Please describe.

A number of sequential scans per database/table would be a very useful metric, as sequential scans can usually be a symptom of unoptimized queries/schema.

### Describe the solution you'd like

An existing metric,`postgresql.operation`, already counts the number of row insertions, deletions, hot updates, etc., per database and table. These numbers are directly obtained from the `pg_stat_user_tables` internal PostgreSQL view. The `seq_scan` column of `pg_stat_user_tables` contains the number of sequential scans.

We can add an additional value to the `operation` attribute of the `postgresql.operation` metric -- `seq_scan` -- and write out an additional "operations" data point with that attribute value.

### Describe alternatives you've considered

If we don't want to add new `operation` attribute types to `postgresql.operation` metric, we can introduce a completely new metric, e.g. `postgresql.sequential_scans`.

**Comment by djaglowski** [comment]
The current `operations` metric is focused on CRUD operations, so sequential scans seems like a separate concern. I'd favor adding this as a new metric.

**Comment by bjandras** [comment]
Closing this PR. New metric PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26122
