### ISSUE TITLE
[extension/pprof] Improve documentation with a focus on non-Go developers

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#26095]
### Component(s)

extension/pprof

### Is your feature request related to a problem? Please describe.

Using the pprofextension can be tricky if you are not a Go developer or experienced with Go's tooling.

### Describe the solution you'd like

Update the README with a set of instructions for basic interaction with the extension.

**Comment by Jamie-Ullerich** [comment]
Hello, I would like to work on this issue.

**Comment by TylerHelmuth** [comment]
@Jamie-Ullerich thanks!
