### ISSUE TITLE
Document/refine all k8sattributes config fields and their functionality

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-collector-contrib#26110]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

Currently the k8sattributes readme doesn't describe all available config fields and their purpose or functionality. It's currently missing all `filter` items that aren't `node` and `node_from_env_var` (`namespace`, `fields`, and `labels` with associated functionality). It's also not clear that the `metadata`, `annotations`, and `labels` examples/descriptions are part of `extract` configuration and a complete example isn't provided. `exclude` isn't documented or demonstrated either.

### Describe the solution you'd like

The existing readme is a great improvement of the previous godoc link but could be reorganized and made more complete to reflect its capabilities.

**Comment by zzadxz** [comment]
Hey! I can help with this. May I be assigned?

**Comment by Frapschen** [comment]
Thank you, @zzadxz

**Comment by fatsheep9146** [comment]
nicely ping @zzadxz
