### ISSUE TITLE
K8S Processor Passthrough mode not working with Jaeger

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector-contrib#262]
Among changes in internal data format is [removal of SourceFormat attribute](https://github.com/open-telemetry/opentelemetry-collector/commit/e44607a8045f327d4e98dcb60d689f4d184c9115#diff-0e6ca11168918e81d990fd9005b9671cL356), which was used by the [processor logic in certain cases](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/k8sprocessor/processor.go#L102-L106). 

The passthrough mode seems to no longer work when spans are sent using Jaeger gRPC (and possible some of the other formats as well)

**Comment by tigrannajaryan** [comment]
@owais can you take a look?

**Comment by owais** [comment]
Yes, this would break passthrough mode for Jaeger. I've seen zipkin libraries do the same. I'll confirm what OC libs do and if they have the same behavior or at least not conflicting behavior, may be we can remove the jaeger check and rely on the IP tag as a fallback in all cases.

**Comment by tigrannajaryan** [comment]
@owais k8sprocessor also still uses old interfaces, right? If you are spending time on this perhaps also migrate it to new interfaces (if you have time).
