### ISSUE TITLE
Clarify kubernetes logs attributes names

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#2628]
There are some attributes for kubernetes container logs, which can be useful (or not) and doesn't have naming convention so far:
 - stream (either stdout or stderr) which can be used for example for keeping only stderr logs
 - run_id - I don't know proper name of this attribute. This is run number of container (pods? maybe) (starts from 0 and it's increased with every container restart). This is name of a file log (`/var/log/pods/<namespace>_<pod-name>_<pod-uid>/<container-name>/<run-id>.log`)
 
 Another question is if `container-name` is more like `k8s.container.name` or `container.name`
 
 [semantic convention](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions)
 [k8s convention](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md#container)
 [container convention](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/container.md)

**Additional context**
#2606

**Comment by tigrannajaryan** [comment]
Note that names like `stream` and `run_id` are not compliant with Otel spec recommendations: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-and-label-naming.md

We need to put them in some reasonable namespaces, I don't think they can be top-level fields.

**Comment by tigrannajaryan** [comment]
Seems like `run_id` can belong to `container.*` Otel semantic conventions namespace.

**Comment by tigrannajaryan** [comment]
I can't find the concept of run id in K8s docs. Does anyone have a link?

**Comment by sumo-drosiek** [comment]
I did some research around it and see some references in code as `instance number` [link](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go#L1091) or `container instance` [link](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/google/cadvisor/container/crio/handler.go#L123)

Didn't find anything useful in documentation

**Comment by sumo-drosiek** [comment]
Also, we won't be able to ensure that container_id taken by enrichment is truly the container id related to container instance (as container can be restarted meantime)

**Comment by dmitryax** [comment]
@sumo-drosiek @tigrannajaryan @pmm-sumo Looks like the `run_id` part of the logs path represents [number of container restarts](https://github.com/kubernetes/kubernetes/blob/2e93b3924ae6eb2b6a2b914fe400a006bd676308/pkg/kubelet/kuberuntime/helpers.go#L169) from k8s API. I would like to suggest to call the attribute `container.restart_count`.

I want to settle a semantic convention for this attribute, so it can be used along with `k8s.pod.uid` and `container.name` to fetch a particular container status in [this issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5235).

Please let me know what do you think

**Comment by sumo-drosiek** [comment]
@dmitryax for me it sounds good. more intuitive than `instance`/ `instanceNumber`/`run_id`

**Comment by dmitryax** [comment]
Ok, I submitted a PR to add this as a semantic convention https://github.com/open-telemetry/opentelemetry-specification/pull/1945

**Comment by tigrannajaryan** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/1945 resolved the `run_id` attribute.

https://github.com/open-telemetry/opentelemetry-specification/pull/1980 is open to clarify `container.name` and `k8s.container.name`. Please review/comment.

The `stream` attribute is not addressed at all yet.

**Comment by dmitryax** [comment]
I think we can close this issue since all the attributes now added to the OTel conventions cc @tigrannajaryan @djaglowski

**Comment by tigrannajaryan** [comment]
Closing. Feel free to reopen if there is anything else to be done or create a new issue.
