### ISSUE TITLE
ClickHouse - Materialized view contains duplicates on the grouping key

### ISSUE THREAD

**Issue by StarpTech** [open-telemetry/opentelemetry-collector-contrib#26301]
### Component(s)

exporter/clickhouse

## Description

Hello, we experience duplicates in the[ `otel_traces_trace_id_ts_mv`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/exporter_traces.go#L262) when ingesting spans from multiple services. This looks like a race condition or limitation of how the schema was designed. We work around this by querying the `otel_traces_trace_id_ts` table directly.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/1764424/735f657f-4f2b-4155-a372-a48dd7736ae0)

Reading the blog post https://clickhouse.com/blog/storing-traces-and-spans-open-telemetry-in-clickhouse from clickhouse the value of the materialized view is very limited. I recommend deleting it to avoid this. I also saw that the README examples don't use the materialized view at all.

## Expected Result

No duplicates are in the `otel_traces_trace_id_ts_mv` table because the idea is to use this table as a root spans overview.

## Actual Result

Duplicates. See image above.

### Collector version

0.81.0

## Environment
OS: (e.g., "Ubuntu 20.04") PopOs 22.04 LTS
Compiler(if manually compiled): (e.g., "go 14.2") 1.2.0

**Comment by hanjm** [comment]
The duplicates data is normal beacuse it is inserted when a batch of spans write to clickhouse. A traceID may exist in more than more batch. so we query with `min(start)` and `max(end)+1` as the time index of traceID.

The mv is high effectly when spans count grow high especially more than billon level. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13442#issuecomment-1235284835

If you query traceID is very fast without this time index mv in small dataset, you can just delete it.

**Comment by StarpTech** [comment]
@hanjm thanks for clarifying. That means In order to get correct results, I'd GROUP again on the `otel_traces_trace_id_ts_mv` table?

```sql
SELECT
	TraceId,
	min(Timestamp) as Start,
	max(Timestamp) as End
FROM
otel_traces_trace_id_ts_mv
WHERE TraceId !=''
GROUP BY TraceId;
```

**Comment by hanjm** [comment]
@StarpTech Yes. as the readme.md example https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3ec9d2203552d42d089a31e827888d321bcb4b67/exporter/clickhouseexporter/README.md?plain=1#L154

**Comment by hanjm** [comment]
@StarpTech No, this mv is just a insert trigger, you can select from the distination table `otel_traces_trace_id_ts ` but can not query `otel_traces_trace_id_ts_mv ` directly.  https://clickhouse.com/blog/using-materialized-views-in-clickhouse

**Comment by StarpTech** [comment]
@hanjm Thank you, that makes sense.

**Comment by StarpTech** [comment]
I think this is not 100_5 correct. I know where my confusion came from. In clickhouse, you can also use mv differently. Looks at https://altinity.com/blog/clickhouse-materialized-views-illuminated-part-1

**Comment by hanjm** [comment]
The diffence is the `to table` when create a mv, you can see the best practices from altinity. from https://kb.altinity.com/altinity-kb-schema-design/materialized-views/#best-practices
