### ISSUE TITLE
CrashLoopBackOff on using opentelemetry-collector-contrib image from private repository

### ISSUE THREAD

**Issue by anand3493** [open-telemetry/opentelemetry-collector-contrib#26307]
### Component(s)

cmd/otelcontribcol

## Description
In our organization we have the policy to use docker images from our own AWS ECR repo.
Hence I had pulled this image "otel/opentelemetry-collector-contrib:0.83.0" and pushed into our AWS ECR and mapped it in the values file.
The pods are getting into CrashLoopBackOff state, while if I simply use "otel/opentelemetry-collector-contrib:0.83.0" this image, the deployment is working fine.

## Expected Result
Expecting to deploy using our own docker images

## Actual Result
**Error:**
failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/otelcol-contrib": stat /otelcol-contrib: no such file or directory: unknown

### Collector version

0.83.0

## Environment
Kubernetes

### Log output

```shell
failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/otelcol-contrib": stat /otelcol-contrib: no such file or directory: unknown
```

**Comment by anand3493** [comment]
Sorry, my bad. I had supplied operator image incorrectly

**Comment by saiganeshkABI** [comment]
Can you help us by sharing the correct operator image?

This is the command I used to deploy otel in our aks:
![image](https://github.com/user-attachments/assets/78e43076-1fc1-4767-a58c-a8d51415ce24)
