### ISSUE TITLE
[checkapi] Make sure all components follow the API guidance

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#26304]
### Describe the issue you're reporting

The following components do not follow the guidance of the checkapi tool.

For each component, remove the name of the component from the [allowlist.txt](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/checkapi/allowlist.txt) file and run `go run cmd/checkapi/main.go .` from the root of the repository.

For each change, make sure to create a breaking change changelog entry targeting the api changelog.

* [ ] connector/servicegraphconnector
* [x] exporter/alibabacloudlogserviceexporter
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26366
* [X] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27057
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26305
* [x] exporter/azuremonitorexporter
* [x] exporter/coralogixexporter
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26339
* [X] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27048
* [x] exporter/elasticsearchexporter
* [x] exporter/f5cloudexporter
* [x] exporter/jaegerexporter
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27583
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26992
* [x] exporter/logzioexporter
* [x] exporter/lokiexporter
* [x] exporter/pulsarexporter
* [x] exporter/sentryexporter
* [x] exporter/sumologicexporter
* [x] extension/observer/ecsobserver
* [ ] extension/observer
* [x] extension/observer/k8sobserver
* [x] processor/groupbyattrsprocessor
* [x] processor/groupbytraceprocessor
* [x] processor/probabilisticsamplerprocessor
* [ ] processor/servicegraphprocessor
* [x] processor/tailsamplingprocessor
* [x] receiver/carbonreceiver
* [x] receiver/collectdreceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27086
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26727
* [x] receiver/jaegerreceiver
* [x] receiver/journaldreceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26306
* [x] receiver/kafkareceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27032
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27021
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26705
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26509
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26308
* [x] receiver/podmanreceiver
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27029
* [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26471
* [x] receiver/windowseventlogreceiver

**Comment by swar8080** [comment]
Is there any information on what the checkapi rules are and what the goal is? It's unclear when we can export functions without closely reading the checkapi code

**Comment by atoulme** [comment]
So to your code:
https://github.com/swar8080/opentelemetry-collector-contrib/pull/1/files#diff-ee9adf1ebf9796ce04cbb1424312725b7a6a545e1c8bb4e75105593a99e5ee2d
`AmqpClient` can be `ampqClient`
`WrappedConnection` can be `wrappedConnection`
`WrappedChannel` can be `wrappedChannel`
`WrappedDeferredConfirmation` can be `wrappedDeferredConfirmation`

`LogsMarshaler` can be `logsMarshaler`

**Comment by swar8080** [comment]
Got it, thanks for reviewing that 

I also just realized checkapi allows exporting from within a component's `internal` directory. I'm assuming that could help with maintainability/readability
