### ISSUE TITLE
[receiver/kubeletstats] tls verify config not being respected

### ISSUE THREAD

**Issue by jinja2** [open-telemetry/opentelemetry-collector-contrib#26319]
### Component(s)

receiver/kubeletstats

## Description
The receiver exposes the config `InsecureSkipVerify` which let's user decide if the receiver should verify the server's certificate chain and hostname. The [documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver#optional-parameters) implies that this config is respected for all modes of `auth_type` but it is not respected with the [auth mode service_account](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/kubelet/client.go#L170) where is it set to true always

## Expected Result
insecure_skip_verify option should be honored when the auth mode with kubelet is service_account

## Actual Result
insecure_skip_verify option is not used  when the auth mode with kubelet is service_account

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
This was originally introduced in #324. All examples in the original PR set `insecure_skip_verify: true`, but there aren't any comments on why. There is an [example config used in testing](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3a6f54773c1c494bb95e31307c2faefa6bd38403/receiver/kubeletstatsreceiver/testdata/config.yaml#L27) that technically hits this case, but it just makes sure the config is valid, it doesn't check the end value.

The solution here is to either honor the `insecure_skip_verify` setting, or include reasoning in documentation for why it's always ignored.

**Comment by crobert-1** [comment]
I checked with the original author and it sounds like this wasn't intentional, so the solution will be to honor the `insecure_skip_verify` setting.

**Comment by jinja2** [comment]
Thank you @crobert-1! You can assign this to me.

**Comment by crobert-1** [comment]
Fixed by #27070. Thanks @jinja2!
