### ISSUE TITLE
Additional metric number of database locks

### ISSUE THREAD

**Issue by samiura** [open-telemetry/opentelemetry-collector-contrib#26317]
### Component(s)

receiver/postgresql

### Describe the issue you're reporting

Component(s)

receiver/postgresql

Is your feature request related to a problem? Please describe.

PostgreSQL locks often called “write locks” or “exclusive locks,” restrict users from modifying a row or a PostgreSQL table's contents. Rows that have undergone a DELETE or UPDATE operation will be locked solely until the transaction is finished. Hence, this metric will be useful for users to assess the number of locks.

Describe the solution you'd like.

We can query pg_locks, pg_class to count the number of process PIDs

**Comment by crobert-1** [comment]
@samiura Did PR #26318 resolve this issue? If so we can close it.

**Comment by crobert-1** [comment]
I checked with @samiura and confirmed this issue has been resolved.
