### ISSUE TITLE
Add DisablePAFXFAST option to kafka exporter

### ISSUE THREAD

**Issue by swythan** [open-telemetry/opentelemetry-collector-contrib#26345]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

When attempting to use kerberos authentication against ActiveDirectotry in the kafka exporter, I get the following error:

```
[Root cause: KRBMessage_Handling_Error] KRBMessage_Handling_Error: AS Exchange Error: AS_REP is not valid or client password/keytab incorrect < KRBMessage_Handling_Error: KDC did not respond appropriately to FAST negotiation
```

I'm told that this is because our ActiveDirectory controller doesn't support FAST.

### Describe the solution you'd like

Looking further it seems that the sarama library added an option for this, so hopefully it should just be a question of plumbing the config through.

Sarama PR: https://github.com/IBM/sarama/pull/1466
Sarama config docs: https://pkg.go.dev/github.com/IBM/sarama#GSSAPIConfig.DisablePAFXFAST

**Comment by swythan** [comment]
This seems trivial to add, so I've speculatively [made a PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26346).

**Comment by swythan** [comment]
This is still something that is needed. Can I get someone interested in reviewing it I update my PR for the refactoring that has happened underneath me?

**Comment by swythan** [comment]
@open-telemetry/collector-contrib-triagers is there any point me resolving the conflicts caused by the refactoring on main? How would I get the resulting changes merged?

**Comment by swythan** [comment]
Still awainting a response from a maintainer.

**Comment by sy-be** [comment]
We are having the same issue. Would love to have a fix for this.

**Comment by sy-be** [comment]
@pavolloffay / @MovieStoreGuy any chance you could look at this issue and the related PR? I think PR needs some rework, but changes look trivial. @swythan , would you be able to update the PR if we all agree on the issue? Thanks all!

**Comment by sy-be** [comment]
I've created an updated PR to address this: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33086

**Comment by sy-be** [comment]
The fix has been released now in https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.103.0
This issue can be closed.
