### ISSUE TITLE
Omit multiline pattern from log 

### ISSUE THREAD

**Issue by haim6678** [open-telemetry/opentelemetry-collector-contrib#26381]
### Component(s)

pkg/stanza, receiver/udplog

### Is your feature request related to a problem? Please describe.

We have a scenario where we use OTEL in a very high-scale environment. We have solid concerns that we will hit our network limits. TO reduce network traffic we tried sending multiple logs over 1 packet using UDP receiver and multiline configuration.  During the tests, we've noticed that the multiline delimiter is included in the log record.
For example, if we send set line_end_pattern to be 'PATTERN' and we send a UDP packet: log1 PATTERN log2, the final result is an array of 2 records [log1 PATTERN , log2], when what we actually need is [log1, log2].

### Describe the solution you'd like

I would like to add a flag to the multiline config that if set to true will omit the pattern from the logs.
If the solution is OK with you I can open a pull request.

**Comment by haim6678** [comment]
@djaglowski I'd be glad to hear your opinion.

**Comment by djaglowski** [comment]
@haim6678, makes sense to me. I'd be happy to review a PR.

**Comment by haim6678** [comment]
> @haim6678, makes sense to me. I'd be happy to review a PR.

Published my PR :)
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26460/files

**Comment by djaglowski** [comment]
resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26460
