### ISSUE TITLE
[exporter/alibabacloudlogservice] Upgrade github.com/aliyun/aliyun-log-go-sdk dependency

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#26456]
Upgrade the library and adopt https://github.com/aliyun/aliyun-log-go-sdk/pull/216. This requires replacing deprecated `UpdateStsToken`, `AccessKeyID`, and `AccessKeySecret` fields of `ProducerConfig` struct. Otherwise, the linter is failing with:

```
Error: alibabacloudlogserviceexporter/uploader.go:56:3: SA1019: producerConfig.UpdateStsToken is deprecated: use CredentialsProvider and UpdateFuncProviderAdapter instead. (staticcheck)
```

**Comment by Mihai22125** [comment]
Hi @dmitryax, I'd like to work on this issue. Can you assign it to me, please?

**Comment by dmitryax** [comment]
Thank you, @Mihai22125

**Comment by qiansheng91** [comment]
Hi @dmitryax, This issue will be fixed at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30243.

**Comment by dmitryax** [comment]
Thanks @qiansheng91
