### ISSUE TITLE
[receivers/tcplog] - syslog_parser not registered

### ISSUE THREAD

**Issue by jangaraj** [open-telemetry/opentelemetry-collector-contrib#26452]
### Component(s)

pkg/stanza

## Steps to Reproduce

I use OpenTelemetry Collector Builder (ocb) with this config for receivers:
```
receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tcplogreceiver v0.84.0
```
I use syslog_parser operator in the collector config for tcplog receiver:
```
  tcplog:
    listen_address: 0.0.0.0:12345
    operators:
    - id: syslogparser
      protocol: rfc3164
      type: syslog_parser
```

I'm able to build collector with ocb and Golang 1.21 successfully, but my collector is not able to start. It produces error:
```
023/09/02 00:11:35 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'receivers': error reading configuration for "tcplog": 1 error(s) decoding:

* error decoding 'operators[0]': unsupported type 'syslog_parser'
```

## Expected Result

syslog_parser operator is available

### Collector version

v0.84.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Additional context

Workaround is to replace broken version, with my patched version:
```
replaces:
  - github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza v0.84.0 => github.com/jangaraj/opentelemetry-collector-contrib/pkg/stanza v0.84.1
```

**Comment by crobert-1** [comment]
Removed needs-triage label as a fix has been proposed and the codeowner has approved it.
