### ISSUE TITLE
[exporter/clickhouse] [Usage][BugReport] Data is lost while using collector.

### ISSUE THREAD

**Issue by mioyui88** [open-telemetry/opentelemetry-collector-contrib#26465]
**Describe the bug**
I'm using collector to gather data from multi agents. Collector executing insert SQL into ClickHouse, and error like 'context deadline exceeded'.

**Steps to reproduce**
I use collector to gather data.
Collector executes insert into ClickHouse.

**What did you expect to see?**
SQL insertion successes.

**What did you see instead?**
error report like 'context deadline exceeded'.

**What version did you use?**
signoz-otel-collector: v0.76.2

**What config did you use?**
I will paste later.

**Environment**
OS: Centos 3.10.0
Compiler(if manually compiled): go 17.2

Additional context

**Comment by mx-psi** [comment]
> > > error report like 'context deadline exceeded'.
> > 
> > 
> > This usually comes from a timeout. What Collector components are you using? Are you perhaps using the ClickHouse Exporter?
> 
> I check the Clickhouse to the different Clickhouse instance, then the insert failed disappear, so I think maybe is the clickhouse instance problem.

Alright, I am going to label this as 'waiting for author' until you verify this. I also transferred this to contrib and labeled it under the clickhouse exporter.

**Comment by hanjm** [comment]
please provide and check the collector full config and more log at debug level. batch_size, send_timeout. 

please check the clickhouse endpoint work. (curl endpoint it will response some text)

please check the collector and clickhouse resource usage( cpu mem disk)
