### ISSUE TITLE
Question about the meaning of `container.cpu.utilization` from kubeletstats receiver

### ISSUE THREAD

**Issue by chenlujjj** [open-telemetry/opentelemetry-collector-contrib#26463]
### Component(s)

receiver/kubeletstats

### Describe the issue you're reporting

Hi Team,
We are trying to use the kubeletstats receiver, but don't understand the `container.cpu.utilization` metric very well.

1. From the [documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.79.0/receiver/kubeletstatsreceiver/documentation.md), its type is **gauge** and unit is 1, but the plot of the metric indicates it is more like a **counter** and has a unit of seconds.
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17081528/dbd72a90-aece-477c-a9a1-67ada5e9075a)

Note: we are using signalfx to store and visualize metrics.

2. I apply a rate function to the raw metric and scale it with a factor of 0.01, then the metric value is consistent with another metric `container/cpu/core_usage_time` from GCP (you can find the metric description [here](https://cloud.google.com/monitoring/api/metrics_kubernetes#kubernetes)). I'm confused why we need the 0.01 scale factor, does it mean the metric is a percent in fact?

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17081528/79334676-31cd-4e60-aad9-bc74b28babda)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17081528/2f778530-7948-4d63-89f9-8e895866e912)

**Comment by chenlujjj** [comment]
@TylerHelmuth Thanks. How about the 2nd question ?  Do we need to scale it with 0.01 to get the accurate cpu usage ?

**Comment by TylerHelmuth** [comment]
[The cpu usage being reported is in "CPU core-nanoseconds per second".](https://github.com/kubernetes/kubernetes/blob/7d309e0104fedb57280b261e5677d919cb2a0e2d/staging/src/k8s.io/kubelet/pkg/apis/stats/v1alpha1/types.go#L199-L209) Scaling it with `0.01` changes it from nanoseconds to milliseconds I think.

**Comment by chenlujjj** [comment]
@TylerHelmuth  I think it is normalized to `second` unit [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/82e8c13e711994205b71767d7bfd280859c0477f/receiver/kubeletstatsreceiver/internal/kubelet/cpu.go#L25). I'm wondering if you have some real-life examples using this metric, and could you please share it out ?

**Comment by TylerHelmuth** [comment]
@chenlujjj you're right, we do normalize it to `seconds`. Maybe @dmitryax from Splunk can answer the question.

**Comment by jinja2** [comment]
@chenlujjj are you by any chance also sending in data from the `signalfx-agent`'s kubelet-metrics monitor? Specifically the metric `container_cpu_utilization`

**Comment by dmitryax** [comment]
Hi @chenlujjj, there are some query time mappings on the Splunk Observability backend that causing this confusion. We are going to resolve it. Can you please submit a Splunk support ticket and we will engage there?

**Comment by chenlujjj** [comment]
@jinja2 Not sure how to use `signalfx-agent`, it has reached End of Support. We are using `splunk-otel-collector` to collect metrics/logs/traces.

**Comment by chenlujjj** [comment]
@dmitryax ok, I'll raise a ticket there.
