### ISSUE TITLE
[extension/jaegerremotesampling]: Remove featuregate switch from Thrift-gen with Proto-gen

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-collector-contrib#26483]
### Component(s)

extension/jaegerremotesampling

### Describe the issue you're reporting

Its a follow-up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18485.

Right now there is a feature flag to use the `Protobuf-gen` struct used in the Jaeger 1.42 `samplingStore` impl. instead of the old `Thrift-gen` struct. With version `0.88.0` the `Thrift-gen` struct implementation should be dropped.

See: 
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18047#issue-1557535235

**Comment by jpkrohling** [comment]
@frzifus, time to drop the feature flag?

**Comment by frzifus** [comment]
We agreed on dropping it after the next release, since it was not operational in the beginning.

**Comment by frzifus** [comment]
Done 
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27636
