### ISSUE TITLE
[cmd/telemetrygen] Add Support for specifying Log Severity

### ISSUE THREAD

**Issue by SeamusGrafana** [open-telemetry/opentelemetry-collector-contrib#26498]
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

Using Telemetrygen you can generate some sample Logs, but everything is logged with a Severity of Info.

### Describe the solution you'd like

It would be great if you could specify the Log Severity (like you can for the Trace Status), so you could simulate various Log Events. An additional command line parameter to specify the severity to use e.g. Error

**Comment by mx-psi** [comment]
I think this would be a nice improvement :) Would you be willing to open a PR for this @SeamusGrafana ?

**Comment by SeamusGrafana** [comment]
> Would you be willing to open a PR for this @SeamusGrafana ?

I dont have much experience with it, but will try to  give it a go.

**Comment by Frapschen** [comment]
@mx-psi I pick it up, pls review
