### ISSUE TITLE
New component: OTel-Arrow Exporter and Receiver

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector-contrib#26491]
### The purpose and use-cases of the new component

The OpenTelemetry Arrow project has been donated to OpenTelemetry, as described here:
https://github.com/open-telemetry/community/issues/1332

This donation included two components, an exporter and receiver, which (as the donation states) are intended to live in the contrib repository. These components have been developed across two repositories:
1. https://github.com/open-telemetry/otel-arrow houses the producer and consumer "adapter" library and the tooling that was built to debug and qualify the primary OTel Arrow components
2. https://github.com/open-telemetry/otel-arrow-collector houses the original branch history as the core OTLP exporter and receiver components were modified to produce the corresponding OTel-Arrow components.

### Example configuration for the component

For the receiver, no configuration is necessary. Like the OTLP exporter, but gRPC is presumed, thus nothing to configure.
```
receivers:
  otelarrow:
```

For the exporter, (like the OTLP exporter), `endpoint` and `tls` are usually set:
```
  otelarrow/insecure:
    endpoint: agent.local:4317
    tls:
      insecure: true
```

### Telemetry data types supported

Traces, Logs and Metrics.

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@codeboten

### Sponsor (optional)

jmacd, gramidt

### Additional context

The OTel Arrow protocol was researched and documented in [this OTEP](https://github.com/open-telemetry/oteps/blob/main/text/0156-columnar-encoding.md).

**Comment by jmacd** [comment]
This project has sponsorship, as described in the Arrow community donation, https://github.com/open-telemetry/community/issues/1332. I am acting as the @open-telemetry/technical-committee sponsor. The recommendation to include these components in contrib is taken from https://github.com/open-telemetry/community/issues/1332#issuecomment-1538916171, 

> The Arrow-based protocol implementations in the Collector should be added as a dedicated contrib receiver and exporter instead of being incorporated in the OTLP receiver and exporter.

Thank you for reviewing. I have updated the CODEOWNERS to refer to @open-telemetry/arrow-approvers which includes currently members of the two donating organizations. Interested in contributing? Join us at [open-telemetry/otel-arrow](github.com/open-telemetry/otel-arrow).

**Comment by jmacd** [comment]
@gramidt Are you willing to be codeowner for these two components?
@moh-osman3 Are you willing to be codeowner for these two components?

For the record, I wish to avoid asking @lquerel to take on this responsibility. The two donating company affiliations matter, too:

@lquerel and @gramidt work for F5.
@moh-osman3 and I work for ServiceNow (a.k.a. Lightstep). 

Since I'm the primary author of the Arrow-specific component code, I should be codeowner, and I want someone from F5, which is why I propose @gramidt in addition to @moh-osman3. Thanks!

**Comment by jmacd** [comment]
@moh-osman3 are you willing to be named as CODEOWNER?
@lquerel are you willing to be named as CODEOWNER? (Even better, IMO, would be for F5 to delegate a new collector maintainer, including a replacement for its current `f5cloudexporter` owner who has left the company.)

**Comment by moh-osman3** [comment]
Yes happy to be a codeowner for these components. Thanks @jmacd!

**Comment by lquerel** [comment]
@jmacd I am checking internally to see if we have someone for the role of collector maintainer. If not, I will volunteer.

**Comment by jmacd** [comment]
There is an open question in https://github.com/open-telemetry/otel-arrow/issues/43

**Comment by lquerel** [comment]
@jmacd you can also add me as CODEOWNER for these components.

**Comment by jmacd** [comment]
Discussed in the SIG today. Resolution: I will return with a new proposal.

@atoulme has suggested if the core OTLP component were turned into a shared library, usable by multiple components, then the components implemented for Arrow could be reduced significantly.

**Comment by jmacd** [comment]
We will renew our efforts to make this contribution in the coming months.

**Comment by jmacd** [comment]
I think this can be closed? We did it.
