### ISSUE TITLE
Spans waiting for Tail Sampling Processor decision are lost if OTEL Collector restarts

### ISSUE THREAD

**Issue by lsolovey** [open-telemetry/opentelemetry-collector-contrib#26490]
### Component(s)

processor/tailsampling

### Describe the issue you're reporting

We noticed that spans waiting in memory for Tail Sampling Processor decision (based on `decision_wait` setting of Tail Sampling Processor) are lost if OTEL Collector is restarted. 

Should Tail Sampling Processor support graceful shutdown to avoid loss of spans?

**Comment by jpkrohling** [comment]
It would certainly be interesting to have this feature. How are you planning to approach that?

**Comment by jpkrohling** [comment]
There's no plan for adding a WAL to this component at this point. I'm closing, unless we have someone willing to create a design doc with a proposal for it.
