### ISSUE TITLE
[cmd/telemetrygen] Add support for metric name/attributes customization

### ISSUE THREAD

**Issue by claudiobastos** [open-telemetry/opentelemetry-collector-contrib#26505]
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

So far we can't set metrics attributes or customize it's name

### Describe the solution you'd like

I would like to customize metrics attributes in order to improve toolchain and ecosystem

**Comment by crobert-1** [comment]
A code owner has stated support for the idea in the submitted PR, so I've removed the `needs triage` label.
