### ISSUE TITLE
[connector/spanmetrics] clarification around README.md

### ISSUE THREAD

**Issue by karmingc** [open-telemetry/opentelemetry-collector-contrib#26520]
### Component(s)

connector/spanmetrics

### Describe the issue you're reporting

I believe the README.md could specify that the metrics generated are the following:
- `calls`
- `duration`

Though, I'm not too sure if the "error" metric is indeed generated as the README.md suggests, maybe I missed something in the code?

**Comment by albertteoh** [comment]
I like your suggestion to clearly state what metrics the spanmetrics connector generates, @karmingc. 

There's indeed _no_ `error` metric generated, and is, instead derivable from a `status_code=STATUS_CODE_ERROR` dimension.

Would you like to make a contribution to the README?

**Comment by karmingc** [comment]
> I like your suggestion to clearly state what metrics the spanmetrics connector generates, @karmingc.
> 
> There's indeed _no_ `error` metric generated, and is, instead derivable from a `status_code=STATUS_CODE_ERROR` dimension.
> 
> Would you like to make a contribution to the README?

Sounds good, thanks for clarifying as well! I'll ping you for a review once it's up.

**Comment by crobert-1** [comment]
Assigning to @karmingc, let me know if that's incorrect!
