### ISSUE TITLE
Rename the copy package to avoid collision with reserved golang term

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#26539]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

The package https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/transformer/copy/ uses the reserved word "copy" as package name, which makes the linter predeclared fail.

1. Remove the exclusion from `.golangci.yml` by removing those lines:
```
        predeclared:
    ignore: copy
```
2. Rename the package so the linter no longer fails.

**Comment by djaglowski** [comment]
I'd prefer not to make any change here because it would be breaking. The package is named consistently with other operators and it seems like a simple enough exception to note in the linter config.

**Comment by djaglowski** [comment]
Closing as not planned. Please reopen if you feel strongly about this.
