### ISSUE TITLE
When can this vulnerability "SecureJoin: on windows, paths outside of the rootfs could be inadvertently produced" be solved?

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#26531]
### Describe the issue you're reporting

Hi,

The Opentelemetry Source Code Version 0.83.0 in my Company GitHub Repository dependabot flagged the following vulnerability.

Vulnerability Name: SecureJoin: on windows, paths outside of the rootfs could be inadvertently produced
CWE No: -
CVE ID: -

May I know when can this vulnerability be solved, please? OR
When is the expected timeline for this vulnerability be solved, please?

Thank you.

Best Regard,
Erica Ooi

**Comment by atoulme** [comment]
Looks like this was resolved yesterday: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26508
