### ISSUE TITLE
[processor/resourcedetection, receiver/hostmetrics] Report host CPU info as resource attributes

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/opentelemetry-collector-contrib#26532]
### Component(s)

processor/resourcedetection, receiver/hostmetrics

### Describe the issue you're reporting

With https://github.com/open-telemetry/semantic-conventions/issues/130 we introduce new semantic conventions attributes regarding the host's cpu. These are info coming from `/proc/cpuinfo` of [Linux kernel data](https://www.kernel.org/doc/html/latest/filesystems/proc.html#kernel-data).

This issue keeps track of the addition of these attributes. As described at https://github.com/open-telemetry/semantic-conventions/issues/130#issuecomment-1709824213, most of the attributes are static resource attributes of the `host` while the frequency is a metric.
Based on this, the static attributes could be added as part of the [`resourcedetectionprocessor` system detector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor#system-metadata) while the frequency could be added as part of the `hostmetricsreceiver` (?).

cc: @mx-psi @frzifus @dmitryax

**Comment by mx-psi** [comment]
Assigning to you @ChrsMark :) I think it should be straightforward to do this with gopsutil

**Comment by ChrsMark** [comment]
So regarding CPU's frequency I see that the common used library `gopsutil` it provides the max frequency instead of the current frequency that cpuinfo provides: https://github.com/shirou/gopsutil/blob/2fabf15a16dca198f735a5de2722158576e986a9/cpu/cpu_linux.go#L145-L148.
Verified that with some manual tests as well. So I guess that won't be aligned with the goal of https://github.com/open-telemetry/semantic-conventions/pull/337. I think we should look for an alternative implementation so as to get the current frequency. @mx-psi thoughts on this?

**Comment by ChrsMark** [comment]
I have found another alternative that provides the actual value of frequency coming from `proc/cpuinfo`: https://github.com/prometheus/procfs/blob/894a5e86981799e073eddf8011c5f835992d1105/cpuinfo.go#L120-L125.

So @mx-psi @frzifus I think we can go for it? WDYT?

**Comment by cforce** [comment]
@ChrsMark  Is this fixed now with MR  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27445 ?

**Comment by ChrsMark** [comment]
I think we can consider it as completed yes @cforce.

cc: @mx-psi

**Comment by cforce** [comment]
Tx for the update. AT least the outcome still seems not yet to be optimal. Please check the discussion i have started. Happy to get some feedback/advice/ideas there  from you
https://github.com/open-telemetry/opentelemetry-collector/discussions/8711

**Comment by mx-psi** [comment]
@cforce I think we can track this in a separate issue and close this one since the aims of this issue are completed. I would encourage you to turn this comment https://github.com/open-telemetry/opentelemetry-collector/discussions/8711#discussioncomment-7443848 into an issue describing what you want to see improved on the hostmetrics receiver. Thanks!

**Comment by cforce** [comment]
@ChrsMark  Tx, i have done as proposed https://github.com/open-telemetry/opentelemetry-collector/issues/8789
