### ISSUE TITLE
Prometheus receiver is not enabling native histograms feature

### ISSUE THREAD

**Issue by rishabhkumar92** [open-telemetry/opentelemetry-collector-contrib#26555]
### Component(s)

receiver/prometheus

## Description
Prometheus receiver is not enabling native histograms feature. We have a usecase where we are using Prometheus receiver and PRW exporter to export metrics. 

## Steps to Reproduce
I have verified that Prometheus receiver is not able to scrap native histogram metrics while vanilla prometheus works with enabling [native histogram feature](https://prometheus.io/docs/prometheus/latest/feature_flags/#native-histograms).

## Expected Result
Native histogram should be able to be scraped.

## Actual Result
Not able to see native histogram after verifying from logging exporter.

### Collector version

0.80

**Comment by bryan-aguilar** [comment]
I believe it may be best to wait for histogram textual representation to be defined in the prometheus community instead of supporting the protobuf format. I don't think anything has been documented around that decision though. 

This is the prometheus issue that was found regarding text format for histogram https://github.com/prometheus/prometheus/issues/11265

cc'ing @gouthamve also on this one.

**Comment by dashpole** [comment]
We would need to implement this to add support for native histograms: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/faf9f207df86390fe1a9bbe8a0df3166063d9647/receiver/prometheusreceiver/internal/transaction.go#L206-L209

I haven't tried it, so it may not be enough... There may be other config or something we need to change for the prometheus server to support it.

I'm OK adding support for native histograms, as long as it is behind an alpha feature gate (disabled by default) until the prometheus server itself promotes native histogram support out of experimental and (presumably) stabilizes the native histogram format.

**Comment by jmichalek132** [comment]
Not stale being worked on in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28663
