### ISSUE TITLE
Don't make cloudflare receiver require TLS

### ISSUE THREAD

**Issue by xbglowx** [open-telemetry/opentelemetry-collector-contrib#26562]
### Component(s)

receiver/cloudflare

### Is your feature request related to a problem? Please describe.

Trying to expose a cloudflare logpush endpoint using the cloudflare receiver and noticed that it is a requirement to configure TLS. This is not need in all setups, especially when the service is being hosted behind a LB or proxy that handles TLS

### Describe the solution you'd like

Make TLS optional

**Comment by djaglowski** [comment]
@xbglowx, would you be willing to make a PR for this?

**Comment by xbglowx** [comment]
> @xbglowx, would you be willing to make a PR for this?

I could try, but I am really rusty at golang. Any tips before I attempt to start on this?

**Comment by dehaansa** [comment]
The cloudflare LogPush integration itself had a strict TLS requirement when this was implemented.

Do you have some evidence that LogPush no longer strictly required TLS?

**Comment by xbglowx** [comment]
> The cloudflare LogPush integration itself had a strict TLS requirement when this was implemented.
> 
> Do you have some evidence that LogPush no longer strictly required TLS?

It still requires TLS, but if this receiver is sitting behind a proxy that handles TLS, do you also need this? For example, I am trying to run this on k8s and we already have TLS configured with cert-manager and Solo's Gloo VirtualService.

**Comment by dehaansa** [comment]
> It still requires TLS, but if this receiver is sitting behind a proxy that handles TLS, do you also need this? For example, I am trying to run this on k8s and we already have TLS configured with cert-manager and Solo's Gloo VirtualService.

I misunderstood your original question, I think that could most likely work.

**Comment by xbglowx** [comment]
Is there a slack channel that we can use, so that I can ask you some questions?

**Comment by xbglowx** [comment]
For the time being, I came up with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26629

**Comment by xbglowx** [comment]
Should be able to close this as fixed.

**Comment by djaglowski** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26629
