### ISSUE TITLE
[Prometheus Compliance Tests] - Incorrect workflow status during failure

### ISSUE THREAD

**Issue by vasireddy99** [open-telemetry/opentelemetry-collector-contrib#26570]
## Description

The Prometheus compliance workflow are reporting incorrect status when the tests have a Failure,
[reference](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6148073831/job/16680972872#step:8:77). This will not help to identify which change has broke the tests.

## Expected Result

The workflow should be shown as failure with error when tests are FAIL

## Actual Result

The workflow is success when tests are FAIL

**Comment by bryan-aguilar** [comment]
The exit code of the step will be determined by [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/25de0b3714e779521c647651b12bc8a90cc8fd15/.github/workflows/prometheus-compliance-tests.yml#L53C10-L53C10) line
```
go test -v --tags=compliance -run "TestRemoteWrite/otel/.+" ./ |& tee ./test-report.txt
```
I am not familiar with the `|&` but what I assume this is giving an exit code 0 from the tee when we expect the exit code to be 1 from the go test. This behavior should be able to be replicated locally by running the above command and then checking exit code with `echo $?`.
