### ISSUE TITLE
Extract attribute values from a span to generate a new metric

### ISSUE THREAD

**Issue by ssidhu-apm** [open-telemetry/opentelemetry-collector-contrib#26628]
### Is your feature request related to a problem? Please describe.

Assume there is a span with the following data:  
name = order.data
service = my.service
location = IN
revenue = 42
status = OK

I'd like to use this span to extract metric data and send it via a metrics exporter. 
datapoint = 42
metric.name = order.data
location = IN

I'd like the option to drop the span or retain it in the trace exporter at this stage. 

### Describe the solution you'd like

Extrapolating the `spanmetricsconnector` to extract an attribute value from the span to generate the data point from the metric.

**Comment by crobert-1** [comment]
Hello @ssidhu-apm, sorry for the delay. I'm not sure the `spanmetrics` connector is the best place for this functionality.

From the [README's overview](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector#overview):
```
Aggregates Request, Error and Duration (R.E.D) OpenTelemetry metrics from span data.
```
It looks like your request is a more general functionality approach of being able to generate any kind of new metric from incoming trace data.

Can you share some more context for your request here? In general, metric receivers should be used to get metrics from whatever source is necessary. Do you have a specific scenario where a receiver can't accomplish what you're trying to do?

**Comment by crobert-1** [comment]
Hello @ssidhu-apm, without more information we can't really make progress on this enhancement request. I'm going to close this issue for now, but please feel free to reopen and add more information, we'd be happy to help!

**Comment by ssidhu-apm** [comment]
Looks like I cannot reopen the issue @crobert-1 . Is that something you could do?

**Comment by albertteoh** [comment]
Thanks @crobert-1. Yeah, I agree with you, spanmetrics connector wasn't designed for emitting metrics of individual spans' attribute values, but instead is designed specifically to aggregate the number of occurrences of spans with common attributes.

@ssidhu-apm  I'm not aware of other alternative components that can meet your requirements. Have you tried asking in the #opentelemetry/#otel-collector slack channels or SIG groups?

**Comment by zacps** [comment]
I'll preface by saying that I'm not super familiar with the project structure, and don't really care where this is implemented as long as it's something that's possible. Is there a repo for general feature requests/user story kind of issues that might be better suited?

This is something we'd really like to have as well. One of the values of opentelemetry for us is the automatic instrumentation across a large number of libraries. If we could leverage this to almost automatically (with some collector configuration) generate metrics as well that would be a huge help.

**Comment by crobert-1** [comment]
I think the best path forward is probably to [propose](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components) a new [connector component](https://opentelemetry.io/docs/collector/building/connector/) with this functionality.

**Comment by crobert-1** [comment]
I'm going to close this issue for now, feel free to reference in a new issue for context.
