### ISSUE TITLE
New component: Honeycomb Event Marker Exporter

### ISSUE THREAD

**Issue by fchikwekwe** [open-telemetry/opentelemetry-collector-contrib#26653]
### The purpose and use-cases of the new component

This event marker exporter will create makers to be consumed by the Honeycomb Markers API to highlight user events. This exporter will start off with preset applications but more customization may be added in the future. 

### Example configuration for the component
```
type Config struct {
	APIKey string `mapstructure:"api_key"`
	APIURL string `mapstructure:"api_url"`
	Presets presets `mapstructure:"presets"`
}

type presets struct {
	K8sEvents bool `mapstructure:"k8s_events"`
}
```

### Telemetry data types supported

Logs

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

Honeycomb Collection Team

### Sponsor (optional)

@TylerHelmuth

**Comment by TylerHelmuth** [comment]
I will sponsor

**Comment by fchikwekwe** [comment]
This component will now create custom marker configurations rather than using presets. Follow #27001 for updates regarding how configuring markers will work.

**Comment by fchikwekwe** [comment]
Issue for component functionality: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27666
