### ISSUE TITLE
New Relic support

### ISSUE THREAD

**Issue by nsathyan-aus** [open-telemetry/opentelemetry-collector-contrib#26657]
### Is your feature request related to a problem? Please describe.

I noticed there is a feature branch that supports newrelic exporter. Any reasons why this branch has not yet been merged into main? We have a scenario to integrate Otel to newrelic. Right now, it is failing with error like 'error decoding 'exporters': unknown type: "NewRelic". Are there are any plans to merge NewRelic exporter branch to main in near future??

### Describe the solution you'd like

Ability to export telemetry data into NewRelic.

**Comment by crobert-1** [comment]
Hello @nsathyan-aus, the New Relic exporter was removed in favor of using native OTLP ingest instead.

PR: #9894, [changelog entry for source](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9894/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)

I found a basic example [here.](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic/)
