### ISSUE TITLE
Telemetrygen fails to parse ip for otlp-endpoint provided

### ISSUE THREAD

**Issue by asreehari-splunk** [open-telemetry/opentelemetry-collector-contrib#26659]
### Component(s)

cmd/telemetrygen

## Description
We've used this tool to generate load in the recent past but when we tried this last week with the following command, the tool complained that parsing the IP and port failed
```
telemetrygen traces --duration 30m --otlp-endpoint 127.0.1.1:8080 --otlp-header "X-SF-Token=\"MyToken\"" --otlp-header "Content-Type"="\"application/x-protobuf\"" --workers 3 --otlp-insecure true --rate 6000
```
## Expected Result
To send traffic like it did before

## Actual Result
2023-09-08T08:48:38.590-0700	INFO	grpc@v1.57.0/clientconn.go:1791	[core][Channel #1] dial target "127.0.1.1:8080" parse failed: parse "127.0.1.1:8080": first path segment in URL cannot contain colon	{"system": "grpc", "grpc_log": true}

### Collector version

latest

## Environment
OS: Mac OSx Ventura
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
2023-09-08T08:48:38.590-0700	INFO	grpc@v1.57.0/clientconn.go:1791	[core][Channel #1] dial target "127.0.1.1:8080" parse failed: parse "127.0.1.1:8080": first path segment in URL cannot contain colon	{"system": "grpc", "grpc_log": true}
```

### Additional context

.

**Comment by codeboten** [comment]
I see the same error, but my traffic is still being sent, can you confirm whether or not that happens in your case as well? The address shown in the example above is `127.0.1.1`, did you mean to use to use `127.0.0.1`?

**Comment by atoulme** [comment]
I will work on this with adding an integration test first.

**Comment by atoulme** [comment]
It appears this issue is not blocking telemetrygen. The error message is misleading. Adding the scheme `passthrough` to the endpoint helps: `passthrough:///192.168.0.1:9080`

**Comment by atoulme** [comment]
After a bit of research, it appears we specifically disable warn logging for the collector as info is deemed chatty. I think we can do that as well here, as logs emitted at info level by grpc are causing confusion.

See https://github.com/open-telemetry/opentelemetry-collector/blob/e116f8c928eb49ba6816751397f5e9e3cf867856/otelcol/internal/grpclog/logger.go#L15C9-L15C53 for how we mirror the behavior of setting the grpc logger.

**Comment by asreehari-splunk** [comment]
@Antoine Toulme ***@***.***> After updating to the latest per your
recommendation, I did not need the "passthrough" prefix and the load gen
worked as expected. I do see that parsing error message but it was just
information and did not affect functionality.

**Comment by atoulme** [comment]
Right, there was no bug in the behavior, but this log was misleading. Excluding this class of logs makes sense to reduce confusion, and we have done so now.
