### ISSUE TITLE
Specify which context to use with "KubeConfig" auth type

### ISSUE THREAD

**Issue by overmeulen** [open-telemetry/opentelemetry-collector-contrib#26665]
### Component(s)

internal/k8sconfig

### Is your feature request related to a problem? Please describe.

I have a kubeconfig with multiple clusters and multiple contexts.
It does not seem possible today to specify which context to use when using "KubeConfig" auth type.
For example if I want to monitor a cluster that is not the one refrerenced in the "current-context" using the kubeletstats receiver.

### Describe the solution you'd like

I would like to be able to specify the context I want to use:

receivers:
  kubeletstats:
    collection_interval: 20s
    auth_type: "kubeConfig"
    context: "my-secondary-k8s-context"
    insecure_skip_verify: true
    endpoint: "${env:K8S_NODE_NAME}"

**Comment by OverOrion** [comment]
This seems to be solved by #27240, can this be closed? @dmitryax @TylerHelmuth
