### ISSUE TITLE
settle on container metrics naming 

### ISSUE THREAD

**Issue by toxic0berliner** [open-telemetry/opentelemetry-collector-contrib#26663]
**Describe the bug**
In the last few weeks container metrics got renamed twice first to container_cpu_usage_total then back to container_cpu_usage_nanoseconds_total
Same for memory which lost then got back a _bytes suffix.

**Steps to reproduce**
Start a container with otel/opentelemetry-collector-contrib image and enable docker-stats in it's config
Start a watchtower container to keep the image up to date on a daily basis
Observe your grafana graphs being broken regularly as metrics seem to disappear as they get renamed 

**What did you expect to see?**
A warning in the release notes?

**What did you see instead?**
Empty graphs on grafana 

**What version did you use?**
Latest from docker hub

**What config did you use?**
Enable docker-stats 

**Environment**
OS: Ubuntu 22.04

It works just fine with minimal performance impact, so very good but I believe stability in naming would be great. I'm all for removing bytes and nanoseconds which seem redondant or can be explained in the help section

**Comment by mx-psi** [comment]
This sounds related to the Prometheus mapping cc @open-telemetry/wg-prometheus

**Comment by dashpole** [comment]
We are really sorry about the disruption.  We have no naming changes planned for the future (this is the last set to be compliant with the specification. The initial change to metric names was made prematurely, and had to be reverted, hence the unfortunate back-and-forth.

Here are the changelog entries:

* Initial enablement: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CHANGELOG.md#v0761
* Revert: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CHANGELOG.md#-breaking-changes--5
* Re-enabled: See https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CHANGELOG.md#-breaking-changes- for the changelog entry for this.

Feel free to reopen if you have further questions.

**Comment by toxic0berliner** [comment]
Thanks a lot @dashpole and sorry I missed this in the change log.
Happy to see this is to match spec and not just a sideffect or something out of control, very deliberate and understood changes are good, it's up to me to better read the change logs 😁
