### ISSUE TITLE
[cmd/telemetrygen] Use exporter per worker for better metrics throughput

### ISSUE THREAD

**Issue by marcelbirkner** [open-telemetry/opentelemetry-collector-contrib#26709]
### Component(s)

cmd/telemetrygen

### Describe the issue you're reporting

When running `telemetrygen metrics` with multiple workers the `exporter` gets used by all workers. This results in limited throughput. On my machine that means about 1000-2000 exported metrics no matter the number of workers. 

I am proposing to give each **worker** its own **exporter**. This would allow scaling metrics throughput when adding more workers.

### Step 1: Install latest version of telemetrygen

```
go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen@latest
```

### Step 2: Create metrics using **1 worker**:

```
telemetrygen metrics \
    --duration 60s \
    --workers 1 \
    --otlp-http=false \
    --otlp-header authorization=\"Bearer\ AUTH TOKEN\" \
    --otlp-endpoint <HOSTNAME>:4317 \
    --otlp-attributes "service.name"=\"telemetrygen\"
```

Output
```
metrics/worker.go:67	metrics generated	{"worker": 0, "metrics": 1226}
```

### Step 3: Create metrics using **10 worker**:

```
telemetrygen metrics \
    --duration 60s \
    --workers 1 \
    --otlp-http=false \
    --otlp-header authorization=\"Bearer\ AUTH TOKEN\" \
    --otlp-endpoint <HOSTNAME>:4317 \
    --otlp-attributes "service.name"=\"telemetrygen\"
```

Output
```
metrics/worker.go:67	metrics generated	{"worker": 1, "metrics": 126}
metrics/worker.go:67	metrics generated	{"worker": 0, "metrics": 126}
metrics/worker.go:67	metrics generated	{"worker": 2, "metrics": 128}
metrics/worker.go:67	metrics generated	{"worker": 9, "metrics": 127}
metrics/worker.go:67	metrics generated	{"worker": 3, "metrics": 127}
metrics/worker.go:67	metrics generated	{"worker": 4, "metrics": 127}
metrics/worker.go:67	metrics generated	{"worker": 5, "metrics": 127}
metrics/worker.go:67	metrics generated	{"worker": 6, "metrics": 127}
metrics/worker.go:67	metrics generated	{"worker": 7, "metrics": 127}
metrics/worker.go:67	metrics generated	{"worker": 8, "metrics": 127}
```

Total number of metrics is the same, no matter how many workers we use.

# Test results with proposed code change

With [this code change](https://github.com/marcelbirkner/opentelemetry-collector-contrib/pull/3) each worker gets its own exporter instance and can export about 1200-1300 metrics per second. When you add more worker the number of metrics exported increases almost linear. Without that change my CPU only reaches 1-1.5% usage. With the change it can go to 60-70% when configuring 1000 workers. 

```
metrics/worker.go:119	metrics generated	{"worker": 4, "metrics": 1326}
metrics/worker.go:119	metrics generated	{"worker": 3, "metrics": 1286}
metrics/worker.go:119	metrics generated	{"worker": 9, "metrics": 1265}
metrics/worker.go:119	metrics generated	{"worker": 0, "metrics": 1240}
metrics/worker.go:119	metrics generated	{"worker": 7, "metrics": 1213}
metrics/worker.go:119	metrics generated	{"worker": 6, "metrics": 1235}
metrics/worker.go:119	metrics generated	{"worker": 8, "metrics": 1377}
metrics/worker.go:119	metrics generated	{"worker": 2, "metrics": 1212}
metrics/worker.go:119	metrics generated	{"worker": 1, "metrics": 1212}
metrics/worker.go:119	metrics generated	{"worker": 5, "metrics": 1172}
```

If you are fine with the proposal, I can create a PR to implement the change.

**Comment by codeboten** [comment]
Thanks for opening the issue, this change sounds great. I can assign the issue to you if you'd like to submit a PR for it!

**Comment by marcelbirkner** [comment]
> Thanks for opening the issue, this change sounds great. I can assign the issue to you if you'd like to submit a PR for it!

Feel free to assign the issue to me. I will link the PR once its ready.
