### ISSUE TITLE
[receiver/postgresql] replication_stats: failure to convert int8 values to int64

### ISSUE THREAD

**Issue by kyle-watershed** [open-telemetry/opentelemetry-collector-contrib#26714]
### Component(s)

receiver/postgresql

## Description
On opentelemetry-collector-contrib:0.84.0 and postgres 14, getting errors like: 

```go
scraperhelper/scrapercontroller.go:200 Error scraping metrics  {
  "kind": "receiver", 
  "data_type": "metrics", 
  "error": "sql: Scan error on column index 2, name \"extract\": converting driver.Value type []uint8 (\"0.000538\") to a int64: invalid syntax", 
  "scraper": "postgresql"
}
```

which I think is related to this query: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/postgresqlreceiver/client.go#L496

## Steps to Reproduce

Enable the replication metrics collection on a postgres database which has replication enabled. 

## Expected Result

The replication metrics are successfully scraped and exported

## Actual Result

The replication metrics fail to scrape and export

### Collector version

0.8.4

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by michalpristas** [comment]
going to take a look at this next week.

**Comment by michalpristas** [comment]
can we close this, should be addressed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28824
