### ISSUE TITLE
UpdateStsToken is deprecated: use CredentialsProvider and UpdateFuncProviderAdapter instead

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#26987]
### Component(s)

exporter/alibabacloudlogservice

### Describe the issue you're reporting

The following error occurred when deps were updated:

```
alibabacloudlogserviceexporter/uploader.go:56:3: SA1019: producerConfig.UpdateStsToken is deprecated: use CredentialsProvider and UpdateFuncProviderAdapter instead. (staticcheck)
                producerConfig.UpdateStsToken = tokenUpdateFunc
                ^
```

**Comment by songy23** [comment]
Dup of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26456, will be fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26510.

**Comment by codeboten** [comment]
thanks @songy23!
