### ISSUE TITLE
Is there a central place where I am able to get the list of available vulnerabilities flagged by Opentelemetry?

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#26995]
### Describe the issue you're reporting

Hi,

May I know if there is a central place where it is listing all the flagged vulnerabilities which has been flagged and has not been closed, please?
a. If yes, can you provide me the path to the central vulnerability page, please?
b. If no, can you publish the vulnerabilities flagged moving forward in a release note, please?

Thank you.

Best Regards,
Erica Ooi

**Comment by crobert-1** [comment]
Hello @ericashi, [the security tab](https://github.com/open-telemetry/opentelemetry-collector-contrib/security) should have the information you're looking for. It looks like there aren't any published security vulnerabilities at this time.
