### ISSUE TITLE
Circuit breaker for receiver/prometheus and exporter/prometheusremotewrite

### ISSUE THREAD

**Issue by premendrasingh** [open-telemetry/opentelemetry-collector-contrib#26996]
### Component(s)

cmd/otelcontribcol, exporter/prometheusremotewrite, receiver/prometheus

### Is your feature request related to a problem? Please describe.

We use receiver/prometheus to scrape prometheus metrics and exporter/prometheusremotewrite to write those metrics using otelcol to Prometheus. Sometimes the applications don't expose metrics to harvest and sometimes when prometheus server or network issues cause otel-collector queues to get filled and get OOM killed.

### Describe the solution you'd like

I would like to propose a circuit breaker implemented at receiver and exporter level so that when an endpoint is unresponsive, the circuit breaker pattern can help prevent cascading failures, while the services are trying to recover. It will handle errors gracefully, reduce application downtimes and help the services to recover more efficiently. State changes of the circuit breaker can be used for error monitoring.

### Describe alternatives you've considered

A retry option with back-off can work, but circuit breaker will be much more efficient.

**Comment by dashpole** [comment]
I would consider using the memory limiter processor, and reducing the size of the queue in the queued retry section of the prometheus remote write exporter.  You may also consider using the (disk-based) WAL in the prometheus remote write exporter to buffer to disk instead of memory.

**Comment by premendrasingh** [comment]
Thanks for the suggestions, I will try them.

**Comment by crobert-1** [comment]
@premendrasingh Have you been able to try the memory limiter processor yet? Does this fit your use case?
