### ISSUE TITLE
[receiver/splunkenterprise] Refactor component to better utilize SDK

### ISSUE THREAD

**Issue by shalper2** [open-telemetry/opentelemetry-collector-contrib#27026]
### Component(s)

receiver/splunkenterprise

### Is your feature request related to a problem? Please describe.

The current logic of the Splunkenterprise receiver does not utilize the provided SDK as comprehensively as it could. Specifically, `httpauth`, `configauth`, and `basicauthextension` could all be leveraged to reduce custom code and improve the readability of the component. Additionally there is a custom timeout setting that can be replaced by using the `ScraperControllerSettings.Timeout` field. 

### Describe the solution you'd like

A refactor of the component to leverage the above mentioned pieces of the opentelemetry SDK to replace custom code implementing the same functionality.

### Describe alternatives you've considered

Currently the component works well but relies on custom implementations of functionality which exists in the codebase.

**Comment by shalper2** [comment]
please assign to me

**Comment by codeboten** [comment]
This is closed by #27205
