### ISSUE TITLE
Allow the collector's prometheus receiver to do protobuf negotiation

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-collector-contrib#27027]
### Component(s)

receiver/prometheus

### Is your feature request related to a problem? Please describe.

Right now if I wanted to scrape metrics using the protobuf format for native-histograms, i wouldn't be able to because they are only available via the protobuf format.

### Describe the solution you'd like

I would like to be able to set [this option](https://github.com/prometheus/prometheus/blob/v0.47.0/scrape/manager.go#L137).

**Comment by dashpole** [comment]
+1.  Do you know if it is safe to always set that option?  Or does it need to be configurable?

Another question is the default.  If native histograms are going to be recommended in the future, we might want to at least enable this by default.

**Comment by jaronoff97** [comment]
I'm not sure if it's safe to always set as an option, i'm making it configurable to start so as to not disrupt anyones configuration.

**Comment by jaronoff97** [comment]
I think we could adjust the default when [this is complete](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26555)

**Comment by codeboten** [comment]
Solved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27030
