### ISSUE TITLE
[exporter/kafka] move kafka configures authentication to internal pkg

### ISSUE THREAD

**Issue by sakulali** [open-telemetry/opentelemetry-collector-contrib#27093]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

Function `kafkaexporter.ConfigureAuthentication` is referenced by the `kafkametricsreceiver` and `kafkareceiver` packages as shown below. We can extract that and place it in an internal package so that the references become clearer. 
Additionally, we can fix this error when use checkapi tool(`go run cmd/checkapi/main.go .`): 
```
2023/09/25 15:37:17 exporter/kafkaexporter has more than one function: "ConfigureAuthentication,NewFactory,WithLogsMarshalers,WithMetricsMarshalers,WithTracesMarshalers"
exit status 1
``` 
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/3955787/2ef9c179-65d4-49e9-831a-f7e80baa0ba1)

### Describe the solution you'd like

**Before the adjustment, the directory structure:**
exporter/kafkaexporter
├── authentication.go
├── authentication_test.go
├── internal
│   ├── awsmsk
│   │   ├── doc.go
│   │   ├── iam_scram_client.go
│   │   └── iam_scram_client_test.go
├── scram_client.go

**After the adjustment, the directory structure** (add new directory **`internal/kafka`**):
internal/kafka
├── Makefile
├── authentication.go
├── authentication_test.go
├── awsmsk
│   ├── doc.go
│   ├── iam_scram_client.go
│   └── iam_scram_client_test.go
├── go.mod
├── go.sum
├── metadata.yaml
└── scram_client.go

**Comment by pavolloffay** [comment]
+1
