### ISSUE TITLE
[receiver/filelog] Limiting "finding files: no files match the configured criteria" logs

### ISSUE THREAD

**Issue by omrozowicz-splunk** [open-telemetry/opentelemetry-collector-contrib#27094]
### Component(s)

receiver/filelog

### Is your feature request related to a problem? Please describe.

Some users use filelog receiver as a part of a tool for Kubernetes logs monitoring. They configure agents as `Deamonset` with one config for every physical node, and on some of them the file does not exist - which is an expected behaviour.

On an older version `0.70.0`, only one `finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog/localhostlog"` message was produced, while on the latest version it is logged on every `poll()`:

```
2023-09-24T23:21:00.934Z	info	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog/localhostlog", "data_type": "logs", "component": "fileconsumer"}
2023-09-24T23:21:02.134Z	info	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog/localhostlog", "data_type": "logs", "component": "fileconsumer"}
2023-09-24T23:21:03.334Z	info	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog/localhostlog", "data_type": "logs", "component": "fileconsumer"}
2023-09-24T23:21:04.334Z	info	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog/localhostlog", "data_type": "logs", "component": "fileconsumer"}
```

And it's flooding agent's log.

### Describe the solution you'd like

I know that this can be treated as an expected behaviour, but this is not an `error` message, just an `info` - so I am not sure if logging it out as frequently is absolutely required. I was thinking about adding a log limiter just for this `finding files` log.

### Describe alternatives you've considered

A workaround for this is setting logging level to `warn`, but this also removes any other `info` message user considered important.

**Comment by dlorent** [comment]
Was just about to submit this issue.

It's quite annoying with the excessive logging.

In my case, i'm using it to log some specific otel-collectors which is not necessarily running on each host. producing constant warnings with.

`opentelemetry-collector-agent-29mkc opentelemetry-collector 2023-09-25T10:10:05.739Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-fdvrw opentelemetry-collector 2023-09-25T10:10:05.936Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-kw5jv opentelemetry-collector 2023-09-25T10:10:06.152Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-q8jgb opentelemetry-collector 2023-09-25T10:10:06.423Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-xxxdk opentelemetry-collector 2023-09-25T10:10:06.693Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-29mkc opentelemetry-collector 2023-09-25T10:10:06.739Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-fdvrw opentelemetry-collector 2023-09-25T10:10:07.136Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-kw5jv opentelemetry-collector 2023-09-25T10:10:07.352Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-q8jgb opentelemetry-collector 2023-09-25T10:10:07.623Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-xxxdk opentelemetry-collector 2023-09-25T10:10:07.893Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-29mkc opentelemetry-collector 2023-09-25T10:10:07.940Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-fdvrw opentelemetry-collector 2023-09-25T10:10:08.336Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
opentelemetry-collector-agent-kw5jv opentelemetry-collector 2023-09-25T10:10:08.552Z	warn	fileconsumer/file.go:118	finding files: no files match the configured criteria	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}`
