### ISSUE TITLE
swap sqlserver drivers: denisenkom/go-mssqldb -> microsoft/go-mssqldb

### ISSUE THREAD

**Issue by cwegener** [open-telemetry/opentelemetry-collector-contrib#27200]
### Component(s)

receiver/sqlquery

### Describe the issue you're reporting

Round about the same time as the sqlqueryreceiver was created in 2022, Microsoft has created an official fork of https://github.com/denisenkom/go-mssqldb at https://github.com/microsoft/go-mssqldb in agreement with the original project maintainers https://github.com/denisenkom/go-mssqldb/issues/729

Since then, there have been plenty of fixes and enhancement delivered under the new Microsoft umbrella and 3 official versioned releases.

And the original project is receiving the minimum maintenance effort.

From the above it seems to me that  the otel collector should adopt the new fork of go-mssqldb in the sqlqueryreceiver.

**Comment by dmitryax** [comment]
Sounds reasonable to me. @cwegener do you have a chance to help with this?

**Comment by cwegener** [comment]
Right. Looks like I better jump through all the hoops to get this out ...

Questions:

1. Would this change be considered a 'behaviour change' in the eyes of the Contributing doc? https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#refactoring-work

```diff
--- a/upstream/receiver/sqlqueryreceiver/db_client.go
+++ b/upstream/receiver/sqlqueryreceiver/db_client.go
@@ -8,9 +8,10 @@ import (

        // register db drivers
        _ "github.com/SAP/go-hdb/driver"
-       _ "github.com/denisenkom/go-mssqldb"
        _ "github.com/go-sql-driver/mysql"
        _ "github.com/lib/pq"
+       _ "github.com/microsoft/go-mssqldb"
+       _ "github.com/microsoft/go-mssqldb/integratedauth/krb5"
        _ "github.com/sijms/go-ora/v2"
        _ "github.com/snowflakedb/gosnowflake"
        "go.uber.org/multierr"
```


I think it might be possible to split out the krb5 addition into a separate change, but then the swap from the old to the new driver could be considered broken ... I'll have to test out if the new MS driver works without the `krb5` module ....

**Comment by astencel-sumo** [comment]
> Would this change be considered a 'behaviour change' in the eyes of the Contributing doc? https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#refactoring-work

I wouldn't sweat over it and would just add this new dependency `"github.com/microsoft/go-mssqldb/integratedauth/krb5"` if there's a chance that not adding it could break existing functionality.

**Comment by cwegener** [comment]
I'll just need to write up a CHANGELOG entry and then I'm good to go I think. I'll send through the patch via GH PR soon.

**Comment by astencel-sumo** [comment]
Resolved in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29694
