### ISSUE TITLE
Do you have a Secure Development Lifecycle (SDL) in place that includes a vulnerability management process and timely closure of vulnerabilities?

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#27236]
### Describe the issue you're reporting

Hi,

I am currently doing a security checking based on my company's policy. Following is the question I was requested to ask.

Do you have a Secure Development Lifecycle (SDL) in place that includes a vulnerability management process and timely closure of vulnerabilities?

Thank you.

Best Regards,
Erica Ooi

**Comment by ericashi** [comment]
Hi,

May I follow-up on this question, please?

Thank you.

Best Regards,
Erica Ooi

**Comment by ericashi** [comment]
Hi,

May I follow-up on this question, please?

Thank you.

Best Regards,
Erica Ooi

**Comment by ericashi** [comment]
Hi,

May I follow-up on this question, please?

Thank you.

Best Regards,
Erica Ooi

**Comment by ericashi** [comment]
Hi,

May I follow-up on this question, please?

Thank you.

Best Regards,
Erica Ooi

**Comment by ericashi** [comment]
Hi,

May I know do you have a Secure Development Lifecycle (SDL) in place that includes a vulnerability management process and timely closure of vulnerabilities?

Thank you.

Best Regards,
Erica

**Comment by ericashi** [comment]
Hi,

May I kindly request to follow up on this particular item? Your attention to this matter is greatly appreciated, and I would be grateful for an answer you can provide. 

Thank you for your kind consideration, and I look forward to hearing from you soon.

Best Regards,
Erica Ooi

**Comment by bryan-aguilar** [comment]
Hi @ericashi, would you be able to attend a Collector SIG meeting to ask these questions? I think collector maintainers may be the best ones to answer this. Our SIG meeting schedule can be found [here](https://github.com/open-telemetry/community#implementation-sigs). \

cc: @open-telemetry/collector-contrib-maintainer

**Comment by codeboten** [comment]
@ericashi the Security SIG is putting together a recommendation for the OpenTelemetry org. There's a PR here: https://github.com/open-telemetry/sig-security/pull/18/files

Please take a look at leave comments on that pull request.

**Comment by ericashi** [comment]
Hi @codeboten and @bryan-aguilar ,

I sincerely appreciate you taking the time to provide information on this matter.

Best Regards,
Erica Ooi
