### ISSUE TITLE
ElasticExporter README does not mention TYPE of telemetry supported

### ISSUE THREAD

**Issue by MacNale** [open-telemetry/opentelemetry-collector-contrib#2726]
**Describe the bug**
ReadMe does not mention whether exporter support - Metrics/Traces/Logs or all.

**Steps to reproduce**
NA

**What did you expect to see?**
A clear documentation

**What did you see instead?**
Ambiguous mention of APM.

**Comment by TylerHelmuth** [comment]
The readme has been update.
