### ISSUE TITLE
lokiexporter container failing to start

### ISSUE THREAD

**Issue by scumpah** [open-telemetry/opentelemetry-collector-contrib#2735]
Pulling otel-collector (otelcontribcol:latest)...
           **ERROR: pull access denied for otelcontribcol, repository does not exist or may require 'docker login': denied: requested       
           access to the resource is denied**

Update: 
              Found **otel/opentelemetry-collector-contrib:latest**  and is working fine so I am guessing maybe the example image is not updated to the latest??

Config:

Docker version 20.10.3
Macbook Pro M1

Steps to reproduce:

1) clone the repo
2) go to lokiexporter example folder
3) docker-compose up -d

Due to issue #2463 made changes in config/compose files based on this PR -> https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2547/files

As you can see from log above, docker pull is failing. Alternatively tried docker build option which failed as well. you can check error logs of build below.

Docker build fail logs:

                **ERROR [build 4/4] RUN make otelcontribcol 218.2s
                   [build 4/4] RUN make otelcontribcol:
                 #14 94.31 GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelcontribcol_linux_arm64
                 #14 94.31 -ldflags "-X github.com/open-telemetry/opentelemetry-collector- 
                 contrib/internal/version.GitHash=f8c550fe -X github.com/open-telemetry/opentelemetry-collector- 
                contrib/internal/version.Version=v0.22.0-41-gf8c550fe -X 
                go.opentelemetry.io/collector/internal/version.BuildType=release" ./cmd/otelcontribcol
                #14 207.3 go build github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-10-01/network: 
                /usr/local/go/pkg/tool/linux_arm64/compile: signal: killed
               #14 217.4 make: *** [Makefile:180: otelcontribcol] Error 1**

             **executor failed running [/bin/sh -c make otelcontribcol]: exit code: 2
              ERROR: Service 'otel-collector' failed to build**

Update:

Tried changing docker file to arm64 version(since my system is M1) I found -> https://gist.github.com/gramidt/d54b104af1d06649b4d77f8d5504fac8
Issues faced:
. when I tried docker-compose up collector did not start at all, only 3 others started 
. Error log of failed container (otel-collector) : 
       
           **Error: cannot load configuration: unknown exporters type "loki" for loki
          2021/03/18 06:42:21 application run finished with error: cannot load configuration: unknown exporters type "loki" for loki**

Steps to reproduce arm64 image build issue:

1) Update docker file to https://gist.github.com/gramidt/d54b104af1d06649b4d77f8d5504fac8
2) docker-compose up
3) docker-compose ps -a (you will see 3 up and 1(collector) down)

          **ERROR: for example_flog_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
           ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information**

4) docker-compose down (takes very long time) - problem lies with example_flog_1 as it doesn't quit
5) try any docker-compose command in the same folder and you should see the below error:

           **ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
            If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT 
            to a higher value (current value: 60).**

A quick workaround for this is to restart docker in local but there must be something wrong going on here that needs to be fixed.

**Comment by scumpah** [comment]
Config:

Docker version 20.10.3
Macbook Pro M1

**Comment by scumpah** [comment]
Update: Docker build failed as well

 => ERROR [build 4/4] RUN make otelcontribcol                                                                                                                        218.2s
------
 > [build 4/4] RUN make otelcontribcol:
#14 94.31 GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelcontribcol_linux_arm64 \
#14 94.31       -ldflags "-X github.com/open-telemetry/opentelemetry-collector-contrib/internal/version.GitHash=f8c550fe -X github.com/open-telemetry/opentelemetry-collector-contrib/internal/version.Version=v0.22.0-41-gf8c550fe -X go.opentelemetry.io/collector/internal/version.BuildType=release" ./cmd/otelcontribcol
#14 207.3 go build github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-10-01/network: /usr/local/go/pkg/tool/linux_arm64/compile: signal: killed
#14 217.4 make: *** [Makefile:180: otelcontribcol] Error 1
------
executor failed running [/bin/sh -c make otelcontribcol]: exit code: 2
ERROR: Service 'otel-collector' failed to build

**Comment by scumpah** [comment]
Update:

Replace image with otel/opentelemetry-collector-contrib:latest and it'll work fine. Docs need to be updated

**Comment by gramidt** [comment]
I apologize for the dealy, @scumpah!

I'm glad you were able to resolve this issue. I would expect that once a few other key tasks are completed within collector project, I'll be able to finish the multi-platform contain image build that would include ARM64, so that you don't have to use the gist that I created. I'll update the gist now so that others don't run into the same issue if they use it between now and when multi-platform images are built.

**Comment by gramidt** [comment]
@tigrannajaryan @bogdandrutu - Please close this issue.
