### ISSUE TITLE
update Docker tag to v3.12 causes failure

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#27413]
This change causes a failure to build the image, will need to investigate why

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27403#issuecomment-1745471379_

**Comment by codeboten** [comment]
See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6388311502/job/17337951714?pr=27403

**Comment by codeboten** [comment]
After some brief investigation, the library installed by the Dockerfile requires a member that's no longer available in python 3.12. The library has been inactive for over 3 years. Either the library has to be updated, or the version of the container pinned to python 3.11

**Comment by gustavomfc** [comment]
I'd like to try to fix this issue during the contribfest
