### ISSUE TITLE
[pulsarreceiver] - Receive logs in normal JSON or plain text from pulsar topics 

### ISSUE THREAD

**Issue by VihasMakwana** [open-telemetry/opentelemetry-collector-contrib#27438]
### Is your feature request related to a problem? Please describe.

We can send raw strings or JSON format messages to the pulsar topic. 
Currently, the pulsar receiver only expects `otlp` format for logs and metrics.

### Describe the solution you'd like

I'd like to add a string and JSON unmarshler. 

### Describe alternatives you've considered

No alternative, I will work on a PR.

**Comment by crobert-1** [comment]
I don't have a lot of context here, so I'm just trying to get an understanding of the purpose of the request. It looks like Pulsar publishes messages to [topics](https://pulsar.apache.org/docs/3.1.x/concepts-messaging/#topics), and it's always in the same [format](https://pulsar.apache.org/docs/3.1.x/developing-binary-protocol/). 

Your request is that once the data is received by the collector it should be able to be unmarshalled (decoded) into raw text or JSON. Is that correct? Do you have a specific use-case where this is really helpful? I'm wondering what the shortcoming here is of the OTLP format.

**Comment by VihasMakwana** [comment]
Yes, you're spot on.
Many tools/cloud services can use text/json format for sending logs.
We had a similar request for kafka receiver as well https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20734

And we're facing similar thing with pulsar.

**Comment by VihasMakwana** [comment]
I'm currently working on getting a PR up.

**Comment by crobert-1** [comment]
I'll defer to the code owners if they have any thoughts otherwise, but sounds good to me. Thanks for your help here!

**Comment by dmitryax** [comment]
We recently started working on a new way to specify encoding for receiver/exporters. I believe this is a good opportunity to test it in real life instead of introducing the encoding embedded into the receiver which will be replaced at some point. We already have text encoder, see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding and https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27478. We need to introduce a json encoding extension and add ability to use the encoding extensions in the pulsar receiver

**Comment by VihasMakwana** [comment]
@dmitryax sounds great. Will work on it.

**Comment by dao-jun** [comment]
> We recently started working on a new way to specify encoding for receiver/exporters. I believe this is a good opportunity to test it in real life instead of introducing the encoding embedded into the receiver which will be replaced at some point. We already have text encoder, see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding. We need to introduce a json encoding extension and add ability to use the encoding extensions in the pulsar receiver

Great! So we can move the encoding/decoding logics from receiver/exporter to extensions and use configuration item to specify which encoding/decoding to use

**Comment by dao-jun** [comment]
Related PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27564
