### ISSUE TITLE
[receiver/kubeletstats] Improve unit test assertions

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#27468]
```
I see. Thanks for clarifying. Given that `fakeRestClient` provides static values, I think we should generate pdata output and use it for validation the way we do it in most oh other tests. Maybe worth filing an issue with `good first issue` label for this. WDYT?
```

_Originally posted by @dmitryax in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27276#discussion_r1348989756_

Currently the unit tests in `scraper_test.go` check the results of scraping by cycling through the returned metrics. The tests could be improved by comparing the ResourceMetrics returned by `.Scrape()` with a expected ResourceMetrics struct that is setup by the test.

**Comment by TylerHelmuth** [comment]
@hamzmu yes, would you like to work on it?

**Comment by hamzmu** [comment]
yes can i work on it. thanks

**Comment by ChrsMark** [comment]
Ah sorry folks, didn't claim the issue when I started working on this yesterday (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30348) before @hamzmu 's comments here 😞 .

**Comment by dmitryax** [comment]
Reassigning to @ChrsMark as there is an open PR already
