### ISSUE TITLE
mdatagen: Expose consumer data mutation capability

### ISSUE THREAD

**Issue by bripkens** [open-telemetry/opentelemetry-collector-contrib#27476]
### Component(s)

cmd/mdatagen

### Is your feature request related to a problem? Please describe.

Tooling around the collector can benefit from knowledge about consumers'/processors' data handling behavior. Specifically, to highlight undesired data copying when there are two pipelines reading data from the same receiver.

### Describe the solution you'd like

Consumers must already define [Capabilities](https://github.com/open-telemetry/opentelemetry-collector/blob/80d704deb46021176c3fc408f63496773388f3b1/consumer/consumer.go#L10-L18) as part of which the `MutatesData` flag is defined. Ideally, the value of this flag is somehow part of the `metadata.yaml` for automatic processing. 

Example:

 - [attributesprocessor's metadata.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8a4348cb009d1448dc647f2bdad27304b8ce53d3/processor/attributesprocessor/metadata.yaml)
 - [attributesprocessor's capabilities](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9a6dd6061cdcb410be2d70a70463aaf8253d19b7/processor/attributesprocessor/factory.go#L22)

### Describe alternatives you've considered

 - New CLI command for the collector to get this information

**Comment by dmitryax** [comment]
Sounds reasonable to me. @bripkens do you have a chance to contribute and add this functionality?

**Comment by bripkens** [comment]
@dmitryax: Looking closer at this, it does not seem like we could easily expose values from `Capabilities` as part of the metadata, as the `Capabilities` are only available at runtime. There could be options to

 - Statically analyze the code or to
 - instantiate the consumer (so runtime).

But neither option really seems desirable to me. This makes me wonder whether we should go the manual route. Potential approach:

 1. Extend the metadata schema:
    - `mutatesData: [<metrics|traces|logs|traces_to_metrics|metrics_to_metrics|logs_to_metrics>]`
 2. Manually backfill this information to all collector components' `metadata.yaml` file
 3. Extend the generation logic for `generated_status.go` to include information from the `metadata.yaml` file
 4. Use the generated constants within the creation of the `Capabilities` struct.

That would be a lot of (one-time) manual labor.

WDYT?
