### ISSUE TITLE
github.com/antonmedv/expr does not exist anymore

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-collector-contrib#27566]
### Component(s)

exporter/datadog, internal/filter, pkg/stanza, processor/attributes, processor/filter, processor/logstransform, receiver/azureeventhub, receiver/filelog, receiver/journald, receiver/mongodbatlas, receiver/otlpjsonfile, receiver/receivercreator, receiver/sqlquery, receiver/syslog, receiver/tcplog, receiver/udplog, receiver/windowseventlog

## Description

`github.com/antonmedv/expr` is used as dependency for several of the components in collector-contrib.

[Search](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-collector-contrib+github.com%2Fantonmedv%2Fexp&type=code&p=2).

However it seems that the repository `github.com/antonmedv/expr` was removed and the account deleted. 

## Steps to Reproduce

run `go mod tidy` with `GOPROXY='direct'`

After that you should get this error:
```
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter: github.com/antonmedv/expr@v1.14.3: reading github.com/antonmedv/expr/go.mod at revisio
n v1.14.3: git ls-remote -q origin in /home/rapphil/go/pkg/mod/cache/vcs/70dfb0ccd5a0e6a21da465bbcd6696e359a57b885c18bf5d832ebab507766bdb: exit status 128:
```

I understand that we can rely on the public module proxy to deal with this situation, but if this is permanent, we will need a plan to migrate to another dependency.

### Collector version

v0.84.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by djaglowski** [comment]
The author appears to have stated on social media that their github account was flagged for unknown reasons. They point out that they recently created a backup [here](https://github.com/expr-lang/expr). I've forked this backup as a possible escape hatch if the author's account is not restored.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/5255616/62f6482f-f667-44c9-9c43-6628b9660f93)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/5255616/92843692-228c-466c-b8d0-fb2ba14bd0d0)

**Comment by djaglowski** [comment]
[This search](https://github.com/search?q=expr++language%3AGo+fork%3Aonly&type=Repositories&ref=advsearch&l=Go&l=&s=updated&o=desc) includes several recent forks of the original repository, as well as some which were restored from sourceforge.

**Comment by mx-psi** [comment]
The copy we use on CI via the Go proxy lives at https://proxy.golang.org/github.com/antonmedv/expr/@v/v1.14.3.zip. We should verify any fork we use against this copy

**Comment by djaglowski** [comment]
The original account and repo have been restored.

https://github.com/antonmedv/expr

**Comment by TylerHelmuth** [comment]
Can we call this closed since it is back?
