### ISSUE TITLE
[receiver/azureeventhub] Better handling of timestamp parsing

### ISSUE THREAD

**Issue by tesharp** [open-telemetry/opentelemetry-collector-contrib#27589]
### Component(s)

receiver/azureeventhub

## Description

Trying to use the `azureventhub` receiver to read diagnostic logs from Azure but its receiving a lot of timestamp parsing errors. It seems like the diagnostic records in event hub are either missing timestamp or have a different format in some cases. Would be good with some better handling, for instance option to ignore and set current time.

## Steps to Reproduce

Set up diagnostic logs and send to event hub

## Expected Result

Able to parse all logs

## Actual Result

Many many error message with Invalid timestamp

### Collector version

v0.85.0

## Environment
OS: Ubuntu 20.04

### OpenTelemetry Collector configuration

```yaml
receivers:
  azureeventhub:
    connection: $CONNECTION_STRING
    format: "azure"
    storage: file_storage/logs
```

### Log output

```shell
azureeventhubreceiver@v0.85.0/azureresourcelogs_unmarshaler.go:106      Invalid Timestamp       {"kind": "receiver", "name": "azureeventhub", "data_type": "logs", "time": ""}
azureeventhubreceiver@v0.85.0/azureresourcelogs_unmarshaler.go:106      Invalid Timestamp       {"kind": "receiver", "name": "azureeventhub", "data_type": "logs", "time": "10/10/2023 13:26:34"}
```

**Comment by nslaughter** [comment]
I just noticed this, because I needed to use this receiver. I will look it up and see if we should copy the parser used in Azure's SDK or import it. Our code currently uses ISO8601, whereas they use RFC3339 and explicitly allow for a further variation with the T or Z.

**Comment by atoulme** [comment]
@nslaughter are you interested in fixing this issue?
