### ISSUE TITLE
[receiver/kubeletstats] Can we have CSI information as Resource Attributes of k8s.volume.* metrics?

### ISSUE THREAD

**Issue by haihh05** [open-telemetry/opentelemetry-collector-contrib#27580]
### Component(s)

receiver/kubeletstats

### Is your feature request related to a problem? Please describe.

I would like to use OTEL with receiver/kubeletstats instead of kube-state-metrics for K8s monitoring, but I need some csi information.
In my current K8s, I had ceph cluster for k8s storage, then I can map csi_volume_handle to the image in ceph to get I/O metrics of each pv on k8s.
I believe that we will need that if we use the external storage.

### Describe the solution you'd like

It is nice to have csi_volume_handle and csi_drive labels (like kube_persistentvolume_info metric in kube-state-metrics)

**Comment by dmitryax** [comment]
Sounds like a reasonable addition as optional attributes. @haihh05 do you want to contribute and add them?

**Comment by jinja2** [comment]
I think this would be a useful addition. Fwiw, the 3 k8s in-tree volume sources, `AWSElasticBlockStore, GCEPersistentDisk and GlusterFs`, we support right now were deprecated a few versions ago, and the recommendation is to use their corresponding CSI equivalent provisioners. So fetching the csi specific attributes would be useful for the more common managed distros (eks/gke/aks) too.
