### ISSUE TITLE
pmetrictest doesn't support ignore data point attribute values

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#27599]
### Component(s)

pkg/pdatatest

### Is your feature request related to a problem? Please describe.

pmetrictest supports ignoring resource attribute values and metric attribute values, but does not support ignoring data point attribute values.

right now the workaround is to modify the data set with:
```
func ignoreMetricDataPointAttributes(t *testing.T, metrics pmetric.Metrics, attributeNames ...string) {
	for i := 0; i < metrics.ResourceMetrics().Len(); i++ {
		for j := 0; j < metrics.ResourceMetrics().At(i).ScopeMetrics().Len(); j++ {
			for k := 0; k < metrics.ResourceMetrics().At(i).ScopeMetrics().At(j).Metrics().Len(); k++ {
				metricToChange := metrics.ResourceMetrics().At(i).ScopeMetrics().At(j).Metrics().At(k)
				switch metricToChange.Type() {

				case pmetric.MetricTypeGauge:
					for l := 0; l < metricToChange.Gauge().DataPoints().Len(); l++ {
						dp := metricToChange.Gauge().DataPoints().At(l)
						dp.Attributes().Range(func(k string, v pcommon.Value) bool {
							for _, attributeName := range attributeNames {
								if k == attributeName {
									v.SetStr("*")
									break
								}
							}
							return true
						})
					}
				}
			}
		}
	}
}
```

### Describe the solution you'd like

I would like to have the exact same option as offered by `pmetrictest.IgnoreMetricAttributeValue`

**Comment by djaglowski** [comment]
Is the function just poorly named? If I'm not mistaken, metrics do not directly have attributes, so this function is actually operating data point attributes.

**Comment by atoulme** [comment]
Ah. It is. It also is surprising because it takes an attribute name and multiple metric names. Ideally I'd like both, but I can bear with it. I'll try it out and report back. Thank you for looking.

**Comment by atoulme** [comment]
Going to close for now ; this is not a serious issue and while the API could be a bit clearer, I'm not sure it warrants a breaking change.
