### ISSUE TITLE
Elasticsearch exporter lack duration in traces.

### ISSUE THREAD

**Issue by pengweiqhca** [open-telemetry/opentelemetry-collector-contrib#27618]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

Because the duration field is missing in traces index, there is no way to filter the span time directly.

### Describe the solution you'd like

Add duration field.

**Comment by JaredTan95** [comment]
what version do you use?

**Comment by pengweiqhca** [comment]
OK, I will upgrade it, thanks.
