### ISSUE TITLE
[processor/k8sattribute] Handle resource deletion on DeletedFinalStateUnknown

### ISSUE THREAD

**Issue by c-kruse** [open-telemetry/opentelemetry-collector-contrib#27632]
### Component(s)

processor/k8sattributes

## Description

We have a similar component that we develop in the sumo logic collector distribution. This bug was discovered there. It appears that it exists here as well, although it is comparatively benign as it will just leak a bit of memory rather than panic as was the case in our processor.

Related issue: https://github.com/SumoLogic/sumologic-otel-collector/issues/1277

Relevant doc snippet from [pkg.go.dev/k8s.io/client-go](https://pkg.go.dev/k8s.io/client-go/tools/cache#ResourceEventHandler):
> OnDelete will get the final state of the item if it is known, otherwise it will get an object of type DeletedFinalStateUnknown. This can happen if the watch is closed and misses the delete event and we don't notice the deletion until the subsequent re-list.

## Steps to Reproduce

Running the collector in a k8s cluster, create a network segmentation between the kube apiserver and the collector. Wait long enough for the open connections to break, then re-establish connectivity. You should see log entries for this and similar cases: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/internal/kube/client.go#L236

Happy to share info on the setup I used to reproduce on our distro, but it won't likely be worth much more than inspiration for y'all.

## Expected Result

I think the resource should be deleted as usual.

## Actual Result

An error is logged and the resource is left hanging.

### Collector version

v0.86.0, v0.85.0

### Environment information

N/A

**Comment by TylerHelmuth** [comment]
@c-kruse thanks for opening this issue.  Do you plan to submit a fix?

**Comment by c-kruse** [comment]
@TylerHelmuth I would be glad to. May be a day or two out.

**Comment by dmitryax** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27847
