### ISSUE TITLE
Cassandra timeout

### ISSUE THREAD

**Issue by raavianil** [open-telemetry/opentelemetry-collector-contrib#27633]
### Component(s)

exporter/cassandra

### Describe the issue you're reporting

Receiving the error when I try to run the custom Otel contributor . Below are the details 

Created a builder using 

**GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@latest**

**used the below config to generate the custom collector** 

builder-config.yaml

dist:
  name: otelcol-custom
  description: Local OpenTelemetry Collector binary
  output_path: /tmp/dist
exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/cassandraexporter v0.86.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.86.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.86.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.86.0

**builder --config=builder-config.yaml**

**running the Otel-custom with this configuration** 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/cassandraexporter/example/otel-collector-config.yml

Otel-custom --config=otel-collector-config.yaml

This returns the below error

**Error: cannot start pipelines : gocql : no response received from Cassandra within timeout period**

I am running latest Cassandra docker image in my box

docker run -p 9042:9042 --rm --name cassandra -d cassandra:latest

**Comment by raavianil** [comment]
By the way it created the "otel" key space is my Cassandra cluster 
Next time I try to run the program it complains about the key space already existing 

Error: cannot start pipelines: Cannot add existing key space "otel"

**Comment by emreyalvac** [comment]
I'm working on it..

**Comment by raavianil** [comment]
Can you post the updates please ?

**Comment by emreyalvac** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27681

@raavianil

**Comment by crobert-1** [comment]
Resolved by #27681.
