### ISSUE TITLE
[Flaky test] TestTraceExporter times out on CI

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#27630]
### Component(s)

exporter/datadog

### What happened?

Example: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6485792155/job/17612673255

```
--- FAIL: TestTraceExporter (5.01s)
    traces_exporter_test.go:277: Timed out
FAIL
```

Cannot reproduce the failure with my local test run.

### Collector version

mainline

## Environment

go version go1.21.1 darwin/arm64

**Comment by mx-psi** [comment]
Is this still an issue?
