### ISSUE TITLE
[exporter/datasetexporter] Documentation does not contains all the options

### ISSUE THREAD

**Issue by martin-majlis-s1** [open-telemetry/opentelemetry-collector-contrib#27649]
### Component(s)

exporter/dataset

## Description

For example configuration option - `logs.export_resource_info_on_event` is missing in the documentation.

## Steps to Reproduce

The configuration exists - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datasetexporter/config.go#L36C41-L36C70 - and is used - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datasetexporter/logs_exporter.go#L214 - but it's not mentioned in the https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datasetexporter/README.md.

## Expected Result

All the configuration options are mentioned in the README.

## Actual Result

Some of them are missing

### Collector version

v0.85.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
_Removing `needs triage` as a code owner filed this issue, and the enhancement makes sense to me._
