### ISSUE TITLE
Elasticsearch exporter lack status description in traces.

### ISSUE THREAD

**Issue by pengweiqhca** [open-telemetry/opentelemetry-collector-contrib#27645]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

Trace status has description but Elasticsearch exporter not export.

> [trace api](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status)
> [trace.proto](https://github.com/open-telemetry/opentelemetry-proto/blob/724e427879e3d2bae2edc0218fff06e37b9eb46e/opentelemetry/proto/trace/v1/trace.proto#L264)

### Describe the solution you'd like

Add `TraceStatusDescription`.

**Comment by crobert-1** [comment]
This makes sense to me. Also, the status code is already being encoded [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6e02e73b2624731a35b8a531d6a7b656761a91af/exporter/elasticsearchexporter/model.go#L73), so the message would fit right next to it.
