### ISSUE TITLE
[exporter/datasetexporter] Make export of resources and scopes more flexible

### ISSUE THREAD

**Issue by martin-majlis-s1** [open-telemetry/opentelemetry-collector-contrib#27651]
### Component(s)

exporter/dataset

### Is your feature request related to a problem? Please describe.

Now it's possible to decide whether attributes from `Resource` or `Scope` are exported by specifying configuration options - `export_resource_info_on_event` and `export_scope_info_on_event`. When this option is set to `true`, then they are available as `resource.attributes` and `scope.attributes`. 

### Describe the solution you'd like

Make the prefix string configurable.

**Comment by crobert-1** [comment]
_Removing `needs triage` as a code owner filed this issue, and the enhancement makes sense to me._
