### ISSUE TITLE
[exporter/datasetexporter] Make sending debugging information configurable

### ISSUE THREAD

**Issue by martin-majlis-s1** [open-telemetry/opentelemetry-collector-contrib#27652]
### Component(s)

exporter/dataset

### Is your feature request related to a problem? Please describe.

Currently the exporter is adding additional attributes `bundle_key` which is useful for debugging grouping. It's also adding attribute `sca:ingestTime` time.

These attributes are not always needed.

### Describe the solution you'd like

Make it configurable whether they should be added or not.

**Comment by crobert-1** [comment]
_Removing `needs triage` as a code owner filed this issue, and the enhancement makes sense to me._

**Comment by martin-majlis-s1** [comment]
This issue was closed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29446
