### ISSUE TITLE
spanmetrics connector has memory leak

### ISSUE THREAD

**Issue by bripkens** [open-telemetry/opentelemetry-collector-contrib#27654]
### Component(s)

connector/spanmetrics

## Description

The `spanmetrics` connector has a memory leak that occurs when the cumulative temporality is used. The `connectorImp#resourceMetrics` map is only ever cleaned up in delta temporality.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/628a6cb5f3ef1c2c615c3f9a066ae4a29e718fda/connector/spanmetricsconnector/connector.go#L253-L271

## Steps to Reproduce

 1. Enable cumulative temporality
 2. Observe many changing resources

## Expected Result

`connectorImp#resourceMetrics` is eventually cleaned up.

## Actual Result

`connectorImp#resourceMetrics` keeps growing over time.

### Collector version

628a6cb5f3ef1c2c615c3f9a066ae4a29e718fda

### Environment information

Not relevant

**Comment by bryan-aguilar** [comment]
Thanks for the report @bripkens, are you interested in working on a fix?

**Comment by mfilipe** [comment]
@bripkens do you think the comments I made [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27080) are related to your issue?

**Comment by bripkens** [comment]
Sounds related, yes. I'd argue however that just pruning histograms is not sufficient. See my (open) PR which would fix this: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28847
