### ISSUE TITLE
[exporter/clickhouse] Add persistent queue configuration to clickhouseexporter

### ISSUE THREAD

**Issue by fredthomsen** [open-telemetry/opentelemetry-collector-contrib#27653]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

Currently the clickhouseexporter only supports setting `QueueSize` from `exporterhelper.QueueSettings`: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/config.go#L81, thus in the event of the collector going down, data queued for export is not persisted.

### Describe the solution you'd like

Update clickhouseexporter configuration to add the ability to specify `*component.ID` to enable persistence.

**Comment by dmitryax** [comment]
It's unclear to me why the queue in this exporter was implemented in such a hardcoded way. It seems pretty reasonable to make it support the whole set of queue configurations. @fredthomsen do you want to submit a PR?

**Comment by fredthomsen** [comment]
@dmitryax I had the same question, and yes, I will submit a PR.

**Comment by crobert-1** [comment]
_Removing `needs triage` based on Dmitrii's comment._
