### ISSUE TITLE
Add support to scrape  nginx status on https

### ISSUE THREAD

**Issue by batman9326** [open-telemetry/opentelemetry-collector-contrib#27676]
### Component(s)

receiver/nginx

### Is your feature request related to a problem? Please describe.

Based on the current documentation, Looks like nginx receiver supports only scraping the /status page on HTTP. When tried with HTTPS it returns a cert error. tls failed to validate the X509 certificate. 

### Describe the solution you'd like

```receivers:
  nginx:
    endpoint: "https://localhost:443/status"
    collection_interval: 10s
     ssl_verify: False
```

if we can add something like above that skips the SSL check only for the status endpoint, it might work.

**Comment by djaglowski** [comment]
I believe the correct approach would be to embed a `configtls` struct in the configuration. See https://github.com/open-telemetry/opentelemetry-collector/blob/35512c466577036b0cc306673d2d4ad039c77f1c/config/configtls/configtls.go#L28

**Comment by batman9326** [comment]
@djaglowski  Thanks for pointing me to the doc. I tried various configs based on the readme under config tls but still ran into the issue. This is the actual error message. 

```
Error scraping metrics {'kind" : "receiver", "name": "nginx", "data_type":"metrics", "error": "failed to get https://localhost:443/status: get\"https://localhost:443/nginx-status\" :tls failed to verify certificate: x509: certificate is valid for example.com not locahost", 'scrapper': "nginx"}
```
This error looks legit as the certificate doesn't have "localhost" as part of it. I  have "n" instances behind a load balancer, where I want to scrape nginx metrics, so I need to hit the localhost/status to scrape the metrics.

**Comment by batman9326** [comment]
After playing around, I realized that I can have another server block and run Nginx on port 80 to scrape the metrics. 
OTEL is able to scrape the nginx metrics now.  I am closing the issue. Thanks for looking into it.
