### ISSUE TITLE
servicegraph connector: Add metrics_flush_interval

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#27679]
### Component(s)

connector/servicegraph

### Is your feature request related to a problem? Please describe.

spanmetrics connector has a `metrics_flush_interval` that controls how frequently metrics are pushed. Service graph connector should have the same.

### Describe the solution you'd like

Add `metrics_flush_interval` to service graph connector.

**Comment by jpkrohling** [comment]
> However, I looked into the implementation side of things and it looks like the servicegraph connector is really just a wrapper of the servicegraph processor, which is actually now deprecated. This means all of the logic being used is the processor's functionality.

We really should have it the other way around, with the connector being the reference implementation, and the processor wrapping it.

**Comment by ptodev** [comment]
@gouthamve @mapno Can this issue be closed now, given that #27879 was merged?
