### ISSUE TITLE
No Github Tag for opensearch exporter => go get fails

### ISSUE THREAD

**Issue by iFrozenPhoenix** [open-telemetry/opentelemetry-collector-contrib#27804]
### Component(s)

exporter/opensearch

### What happened?

Currently there is no tag for the opensearch exporter, resulting in go get failing.

### Collector version

*

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by bryan-aguilar** [comment]
[Opensearch is currently an excluded module](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/cf8ea3abaef311b593abe39a1106128c90c33a12/versions.yaml#L245) within the release workflow.
