### ISSUE TITLE
Opensearch exporter 

### ISSUE THREAD

**Issue by Gauravmeenu** [open-telemetry/opentelemetry-collector-contrib#27801]
### Describe the issue you're reporting

Hello everyone, actually I was trying to using opensearch exporter reagrding traces but when I use docker latest image (otel/opentelemetry-collector-contrib:latest)  but gives error on opensearch exporter in config.yaml file 

### error:

*** error decoding 'exporters': unknown type: "opensearch" for id: "opensearch/trace" (valid values: [otlp coralogix instana signalfx prometheus pulsar azuremonitor dataset googlecloudpubsub influxdb opencensus jaeger_thrift logicmonitor parquet awsemf awsxray dynatrace file googlecloud awss3 azuredataexplorer kafka sumologic otlphttp elasticsearch logzio sapm skywalking mezmo logging alibabacloud_logservice clickhouse cassandra loki loadbalancing awscloudwatchlogs carbon f5cloud googlemanagedprometheus jaeger tanzuobservability tencentcloud_logservice zipkin awskinesis datadog prometheusremotewrite sentry splunk_hec])**

**Comment by KrisBuytaert** [comment]
@Gauravmeenu  this is still the case with the latest release ,  was this supposed to be fixed  ?

**Comment by Gauravmeenu** [comment]
@KrisBuytaert Actually this Opensearch exporter is still in development release tag so this is not the part of distribution of opentelemetry contrib.
