### ISSUE TITLE
Authorization for exporter cassandra

### ISSUE THREAD

**Issue by go-follow** [open-telemetry/opentelemetry-collector-contrib#27827]
### Component(s)

exporter/cassandra

### Describe the issue you're reporting

Hi, could you please tell me if it is possible to include username and password in Cassandra Exporter configuration when configuring OpenTelemetry Collector?

**Comment by emreyalvac** [comment]
Working on it..

**Comment by emreyalvac** [comment]
Working on it..

**Comment by go-follow** [comment]
I can help with this implementation and make a pull request

**Comment by emreyalvac** [comment]
Ok, go for it.
