### ISSUE TITLE
Distribute cmd utilities as binary files

### ISSUE THREAD

**Issue by theletterf** [open-telemetry/opentelemetry-collector-contrib#27856]
### Component(s)

cmd/configschema, cmd/githubgen, cmd/mdatagen, cmd/opampsupervisor, cmd/otelcontribcol, cmd/oteltestbedcol, cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

It'd be great if one could install the cmd utilities directly, using a package manager or a downloader, instead of having to clone the entire repo and compile each package. This is especially relevant for tools like telemetrygen, which are key to testing and learning.

### Describe the solution you'd like

It'd be great to distribute the binary files of the cmd utilities.

**Comment by mx-psi** [comment]
> This is especially relevant for tools like telemetrygen, which are key to testing and learning.

For telemetrygen we have a Docker image:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pkgs/container/opentelemetry-collector-contrib%2Ftelemetrygen

But I agree it would be nice to also release binaries for it.

I am not sure we want to release binaries for the rest just yet; most are meant for internal usage and may heavily change from one version to the next, and the supervisor is under development yet.

**Comment by theletterf** [comment]
Any news on this?

**Comment by mx-psi** [comment]
I personally don't think we are at the point where we can guarantee any stability on anything other than telemetrygen. I would like to consider them case by case, and possibly move them to opentelemetry-go-build-tools instead of this repository if they are meant for public consumption

**Comment by atoulme** [comment]
You can install telemetrygen with one line using:
```
go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen@latest
```

Unfortunately, I don't think we can otherwise distribute binaries at release time - it's easier to use go install on your local machine.

I'm going to close this as such, please reopen and vote up if you feel this can be done better.
