### ISSUE TITLE
[exporter/datadog] Add support for Live Processes metrics upload to Datadog

### ISSUE THREAD

**Issue by ZenykK** [open-telemetry/opentelemetry-collector-contrib#27858]
### Component(s)

exporter/datadog

### Is your feature request related to a problem? Please describe.

Currently `datadogexporter` supports only sending Metrics, Traces, Logs and HostMetadata onto Datadog SaaS (at least judging by configuration options):
```go
// createDefaultConfig creates the default exporter configuration
func (f *factory) createDefaultConfig() component.Config {
	return &Config{
		TimeoutSettings: defaulttimeoutSettings(),
		RetrySettings:   exporterhelper.NewDefaultRetrySettings(),
		QueueSettings:   exporterhelper.NewDefaultQueueSettings(),

		API: APIConfig{
			Site: "datadoghq.com",
		},

		Metrics: MetricsConfig{
			TCPAddr: confignet.TCPAddr{
				Endpoint: "https://api.datadoghq.com",
			},
			DeltaTTL: 3600,
			ExporterConfig: MetricsExporterConfig{
				ResourceAttributesAsTags:           false,
				InstrumentationScopeMetadataAsTags: false,
			},
			HistConfig: HistogramConfig{
				Mode:             "distributions",
				SendAggregations: false,
			},
			SumConfig: SumConfig{
				CumulativeMonotonicMode:        CumulativeMonotonicSumModeToDelta,
				InitialCumulativeMonotonicMode: InitialValueModeAuto,
			},
			SummaryConfig: SummaryConfig{
				Mode: SummaryModeGauges,
			},
		},

		Traces: TracesConfig{
			TCPAddr: confignet.TCPAddr{
				Endpoint: "https://trace.agent.datadoghq.com",
			},
			IgnoreResources: []string{},
		},

		Logs: LogsConfig{
			TCPAddr: confignet.TCPAddr{
				Endpoint: "https://http-intake.logs.datadoghq.com",
			},
		},

		HostMetadata: HostMetadataConfig{
			Enabled:        true,
			HostnameSource: HostnameSourceConfigOrSystem,
		},
	}
}
```

### Describe the solution you'd like

We'd like to have the ability to send Process level metrics we're scrating with the `hostmetrics` receiver onto Datadog and have them appear on [Live Processes](https://docs.datadoghq.com/infrastructure/process/) menu.
Judging by `datadog-process-agent` code, processes metrics are expected to arrive at a different Endpoint rather then Metrics: https://github.com/DataDog/datadog-agent/blob/45a28e222a96fb99954eaa84e3cff52058d7b65f/comp/forwarder/defaultforwarder/endpoints/endpoints.go#L37
And probably with the different `data_type` rather than "metric".

### Describe alternatives you've considered

To replicate whatever the Datadog's own [Process Agent](https://github.com/DataDog/datadog-agent/blob/45a28e222a96fb99954eaa84e3cff52058d7b65f/cmd/process-agent/README.md) is doing and how it's formatting data is arguably the best option here.

**Comment by mackjmr** [comment]
Thanks for reaching out. This is not supported today, please reach out to [our support team](https://www.datadoghq.com/support/) so we can track this request.
