### ISSUE TITLE
Remove generated code from `cmd/otecontribcol` or `cmd/otetestbedcol`

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#27850]
Don't need to keep the generated code. We can keep the builder yaml manifests only, and generate the code when it's needed. 

1. Find a better place for the collector builder yaml manifests
2. Update all the CI steps and make targets to generate the code before building artifacts
3. Remove the `cmd/otecontribcol` or `cmd/otetestbedcol` modules

**Comment by codeboten** [comment]
come on github-actions, do you not see all the PRs opened on this issue? 😄

**Comment by mowies** [comment]
I started working on this, draft PR is open but still in progress.

@dmitryax what about the test files found in `cmd/otelcontribcol`?
Also, I will maybe have to keep the dockerfiles to build images of the collector that are needed in the pipeline.

**Comment by mowies** [comment]
@dmitryax any updates on this?

**Comment by mowies** [comment]
maybe somebody else from @open-telemetry/collector-contrib-maintainers ?

**Comment by mowies** [comment]
or @atoulme since you worked in removing things here as well?
