### ISSUE TITLE
[pkg/ottl] New `Unix` converter to convert epoch timestamp to `time.Time`

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#27868]
### Component(s)

pkg/ottl

### Describe the issue you're reporting

[### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has no way to create a `time.Time` from an epoch time. 

### Describe the solution you'd like

A new `Unix` converter function. similar to [Golang's Unix function](https://pkg.go.dev/time#Unix), that converts the integer input to a `time.Time`.

The function should have 2 parameters.  The first parameter should be the seconds input and is a `IntGetter`.  The second input should be an [optional](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b10bbca010111d692b49cb55c1464a3c32670e0a/pkg/ottl/ottlfuncs/func_replace_match.go#L19) `IntGetter` and represents the nanoseconds.  

The implementing PR should
- [ ] Implement the function
- [ ] Add new unit tests for the function
- [ ] Add the function to `pkg/ottl/ottlfuncs/functions.go`
- [ ] Update the README at `pkg/ottl/ottlfuncs/README.md`

**Comment by kentquirk** [comment]
I'll take this one.

**Comment by codeboten** [comment]
All yours, thanks @kentquirk!

**Comment by iblancasa** [comment]
I think this issue can be closed since it was solved as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29088

**Comment by TylerHelmuth** [comment]
@iblancasa this issue has not yet been resolved.  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29088 was closed since it is a duplicate of this issue.

**Comment by iblancasa** [comment]
Oh. Sorry. I can work on it

**Comment by iblancasa** [comment]
I'll apply the changes requested in the PR today

**Comment by TylerHelmuth** [comment]
Closed via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31556
