### ISSUE TITLE
[pkg/ottl] Add `String` converter

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#27867]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL currently provides no way to convert from another type to a String.

### Describe the solution you'd like

A new `String` converter function, similar to `Int` and `Double` that converts the input to a string.

The implementing PR should
- [ ] Implement the function
- [ ] Add new unit tests for the function
- [ ] Add the function to `pkg/ottl/ottlfuncs/functions.go`
- [ ] Update the README at `pkg/ottl/ottlfuncs/README.md`

Example PR for `Double`: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27457

**Comment by nhAnik** [comment]
Hi @TylerHelmuth , can I give it a try?

**Comment by Palecha** [comment]
@TylerHelmuth  I think this should be closed, I could see func_is_string.go and it's test function already been committed to repo.

**Comment by TylerHelmuth** [comment]
@Palecha the `IsString` function is used to check if a path is a string or not.  This issue is to create a function that converts the input into a string.

**Comment by victorhauvi** [comment]
Hey Tyler, I would love to be assigned this issue and work on this!

**Comment by led0nk** [comment]
should be solved by #31790
