### ISSUE TITLE
[pkg/ottl] Add `IsList` Converter

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#27870]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has no way to check if a value is a `pcommon.Slice` type.

### Describe the solution you'd like

Add a new Converter, `IsList` that returns true if the given type is a `pcommon.Slice` (or equivalent type).  It will work similarly to the `IsMap` function.

The implementing PR should
- [ ] Implement the function
- [ ] Add new unit tests for the function
- [ ] Add the function to `pkg/ottl/ottlfuncs/functions.go`
- [ ] Update the README at `pkg/ottl/ottlfuncs/README.md`

Implementing this function will mean introducing a new `PSliceGetter` interface, similar to the `PMapGetter` interface. If the type is a slice but cannot be converted to a `pcommon.Slice`, then an error should be returned.

**Comment by strawgate** [comment]
I'd like to do this one at contribfest!

**Comment by codeboten** [comment]
Thanks @strawgate!

**Comment by evan-bradley** [comment]
@strawgate Just checking in, are you still able to work on this?

**Comment by strawgate** [comment]
@evan-bradley sorry, was on partial leave for a little bit. I'll pick this up this week!

**Comment by strawgate** [comment]
Re-opened PR at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32392

**Comment by strawgate** [comment]
The pr has been merged so I think this can be closed!
