### ISSUE TITLE
awss3export to support gzip

### ISSUE THREAD

**Issue by rahnarsson** [open-telemetry/opentelemetry-collector-contrib#27872]
### Component(s)

exporter/awss3

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

When using AWS S3 exporter it would be nice to have ability to select compression for stored objects i.e. gzip

### Describe alternatives you've considered

Current workflow for storing gzipped data is to use AWS Kinesis Exporter and then through Firehose store data to s3 gzipped. But having ability to straightly upload gzipped files to S3 would drop the need to use separate Kinesis stream for just gzipping the data.

**Comment by crobert-1** [comment]
Sounds like a good idea to me!

For solution details, most of the changes could be done with an added config option and then changes to this method:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0a79aa816637b30c38e5b374303f9f54cdbf5754/exporter/awss3exporter/s3_writer.go#L76

The AWS s3 uploader's `Upload` method that we're already using takes another optional argument `ContentEncoding`. We can specify `gzip` here when the config option is enabled to properly upload data.

I believe using golang's `compress/gzip` module, we could create a [NewWriter](https://pkg.go.dev/compress/gzip#NewWriter) on a new buffer, then call [Write](https://pkg.go.dev/compress/gzip#Writer.Write) on the passed in variable `buf`, and lastly call [Close](https://pkg.go.dev/compress/gzip#Writer.Close) to ensure data is written to the new buffer before uploading the newly compressed buffer contents.

We could just have an if statement for the new config option and keep existing functionality or use the gzip logic. I believe we'd want gzip disabled by default so this isn't a breaking change.

**Comment by atoulme** [comment]
What's the rotation strategy? Do we accumulate data into gzip and update in place files? Do we upload in bigger chunks? Please help understand how this would work.

**Comment by rahnarsson** [comment]
My original idea was just that if the exporter now uploads raw json files and now with the new config option there would be possibility to upload that same json but just with compressed format.

All the other logic like rotation etc. would work just like now with json writer.

**Comment by bortojac** [comment]
@atoulme @pdelewski Is this work still being considered? Would love to use this if so.

**Comment by atoulme** [comment]
It's still being considered. Contributions welcome!
