### ISSUE TITLE
Rename remoteobserverprocessor to remotetapprocessor

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#27873]
### Component(s)

processor/remoteobserver

### Describe the issue you're reporting

Rename remoteobserverprocessor to remotetapprocessor - observer is used as a set of processors to observe and dynamically configure the collector, so this naming collides.

**Comment by crobert-1** [comment]
There was some discussion on this in the weekly collector sig meeting and it sounded like this was a generally acceptable name. I'll remove `needs triage` with the understanding there may be some feedback in the PR if anyone has other thoughts.
