### ISSUE TITLE
[receiver/k8scluster] codeowner proposal

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#27876]
### Component(s)

receiver/k8scluster

### Describe the issue you're reporting

I would like to become Code Owner for k8scluster receiver, 

My PRs:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3Apovilasv+is%3Aclosed

Issues that I worked on:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26487
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21234
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27617
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10553
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24425

**Comment by crobert-1** [comment]
Hi @povilasv, feel free to [open a PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner) instead of any issue. 👍
