### ISSUE TITLE
ServiceGraph: support specifying time unit and histogram type, and buckets

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-collector-contrib#27881]
### Component(s)

connector/servicegraph

### Is your feature request related to a problem? Please describe.

I want to use simultaneously the [Service Graph Connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/servicegraphconnector) and the [Span Metrics Connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector) with a Prometheus backend and to have both processors produce measurements in `s` rather than `ms` and have the same ~~histograms~~ histogram characteristics (units and time buckets).

### Describe the solution you'd like

Add a `histogram/timeunit` configuration option in the [Service Graph Connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/servicegraphconnector) and be consistent with the [Span Metrics Connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector) `histogram/timeunit` configuration setting.

A lower priority would be to add support for specifying the histogram type `explicit|exponential` and bucket details similar to what the [Span Metrics Connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector)  offers

### Describe alternatives you've considered

Convert Service Graph Connector metrics from `ms` to `s` in a downstream OTel Collector processor.

### Additional context

See also:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27488

**Comment by crobert-1** [comment]
_Please note that all of my comment can be overruled by the code owners, I don't have a lot of experience here._

I think this is a valid request, but as described below this would be a heavily involved breaking change.

1. All of the relevant logic is still in the `servicegraph` processor, so we'd be adding logic to the `deprecated` component.
2. Also, the [histogram metric names themselves](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/servicegraphconnector#metrics) have units as suffixes:
```
traces_service_graph_request_server_seconds
traces_service_graph_request_client_seconds
```
It would be a breaking change to rename the metrics to no longer include the `seconds` suffix.

3. Variables are also created and set in multiple places across the processor, and also include the suffix `Seconds` more often than not. This is more complexity to deal with in implementation.

Also, a clarification on your comment `and have the same histograms`. Do you want the `servicegraph` connector to create the histogram metrics with the exact same names as the `spanmetrics` connector? Or could you clarify what exactly you're looking for there?

**Comment by cyrille-leclerc** [comment]
Thanks @crobert-1!

> Also, a clarification on your comment `and have the same histograms`. Do you want the `servicegraph` connector to create the histogram metrics with the exact same names as the `spanmetrics` connector? Or could you clarify what exactly you're looking for there?

Great catch, I clarified, I meant the same characteristics (time unit and buckets).

I see a broader topic of aligning better the Span Metrics and Service Graph connectors but it's a longer term topic initiated by @jpkrohling in:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26648

**Comment by crobert-1** [comment]
Thanks for the reference to #26648, I wasn't aware of that effort. Good to know!
