### ISSUE TITLE
[pkg/ottl] Add `IsDouble` Converter

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#27895]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has no way to check if a value is an `double` type.

### Describe the solution you'd like

Add a new Converter, `IsDouble` that returns true if the given type is a `double` (or equivalent type).  It will work similarly to the `IsString` function.

The implementing PR should
- [ ] Implement the function
- [ ] Add new unit tests for the function
- [ ] Add the function to `pkg/ottl/ottlfuncs/functions.go`
- [ ] Update the README at `pkg/ottl/ottlfuncs/README.md`

**Comment by swar8080** [comment]
Would this match on integers or doubles in string form like "2.0"?

**Comment by etiennep** [comment]
I'm interested in working on this.

**Comment by codeboten** [comment]
All yours @etiennep, thanks!

**Comment by graphaelli** [comment]
anything left here now that #29076 is merged?
