### ISSUE TITLE
[pkg/ottl] Add `IsInt` Converter

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#27894]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has no way to check if a value is an `int` type.

### Describe the solution you'd like

Add a new Converter, `IsInt` that returns true if the given type is a `int` (or equivalent type).  It will work similarly to the `IsString` function.

The implementing PR should
- [ ] Implement the function
- [ ] Add new unit tests for the function
- [ ] Add the function to `pkg/ottl/ottlfuncs/functions.go`
- [ ] Update the README at `pkg/ottl/ottlfuncs/README.md`

**Comment by swar8080** [comment]
Would this just match on any of the built-in `int` types and `pcommon.ValueTypeInt`? Or could it include values like `2.0` and `"2"`?

Also, maybe an `IsNumber`/`IsNumeric` function is helpful for when it's unclear if instrumentation emits integers or doubles

**Comment by lazyplatypus** [comment]
i'm interested in working on this issue :)

**Comment by codeboten** [comment]
Thanks @lazyplatypus, its all yours!

**Comment by lkwronski** [comment]
It can be closed because the #31307 was merged.
