### ISSUE TITLE
[pkg/ottl] Add `IsBool` Converter

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#27897]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has no way to check if a value is an `bool` type.

### Describe the solution you'd like

Add a new Converter, `IsBool` that returns true if the given type is a `bool` (or equivalent type).  It will work similarly to the `IsString` function.

The implementing PR should
- [ ] Implement the function
- [ ] Add new unit tests for the function
- [ ] Add the function to `pkg/ottl/ottlfuncs/functions.go`
- [ ] Update the README at `pkg/ottl/ottlfuncs/README.md`

**Comment by els0r** [comment]
I'd love to have a look at this.

**Comment by codeboten** [comment]
All yours @els0r, thanks!
