### ISSUE TITLE
how to pass the authentication extension username to processor

### ISSUE THREAD

**Issue by pkalvagit** [open-telemetry/opentelemetry-collector-contrib#27902]
### Describe the issue you're reporting

hi There,

I have implemented basic auth extension. (which is similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension).  Implemented our own custom logic to authenticate.

In Authenticate method, i am getting credentials and successfully able to validate and return client.auth data as well(same as : https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/basicauthextension/extension.go#L111).   In Processors, when i try to access metadata using `md, _ := metadata.FromIncomingContext(ctx)` i am getting empty list in processors. if call same code  `md, _ := metadata.FromIncomingContext(ctx)`  in authentication extension, i am getting headers with `authorization`  key. 

Now, question is how to can pass cleint.username(https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/basicauthextension/config.go#L26)  from config.yaml ( where i define pipeline with extensions, receivers, processors, exporters) which is returned from authentication  extension https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/basicauthextension/extension.go#L111.

Any help is highly appreciated! 

In opentelemetry collector i have seen comments to access client info form authentication to processor authprinter processors but there is no clear example https://github.com/open-telemetry/opentelemetry-collector/blob/extension/auth/v0.87.0/client/client.go#L68 .. i tried to refer as mentioned in documentiaon https://github.com/open-telemetry/opentelemetry-collector/blob/extension/auth/v0.87.0/client/client.go#L68.. not sure how to refer that

**Comment by jpkrohling** [comment]
Can you share the config for your collector? Are you setting the IncludeMetadata flag in your receiver?

**Comment by crobert-1** [comment]
Hello @pkalvagit, without the full configuration you're using we can't provide any more guidance than what @jpkrohling has shared. I'm going to close for now, but please feel free to reopen and share more information!
