### ISSUE TITLE
New component: otlptest

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#28559]
### The purpose and use-cases of the new component

We have the need to test our compliance with otlp. We would like to offer the creation of a toolkit that any implementor of the otlp protocol can use to perform checks against the protocol:
* Testing against HTTP/gRPC variants
* Testing JSON deserialization

We also want to check compliance when sending OTLP data. We want to cover every other edge case of data ingestion with OTLP data such as:
* Gauges with no data points
* Histograms with no buckets
* Histograms with many buckets
* Histograms with invalid buckets

We would like to make this an extensible framework. The assertion is left to the implementor, we will create the test case and offer a way to point data to an endpoint.

### Example configuration for the component

It's unclear how this component would work - we can make it a series of test cases, which can be partially implemented.

### Telemetry data types supported

metrics would be first tested.

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

atoulme

**Comment by bryan-aguilar** [comment]
Would you envision this being similar to [Prometheus compliance](https://github.com/prometheus/compliance) tests?

**Comment by atoulme** [comment]
> Would you envision this being similar to [Prometheus compliance](https://github.com/prometheus/compliance) tests?
Sure, certainly seems like it has similar intent.

Maybe this repository is not the right place for this initiative btw.

**Comment by atoulme** [comment]
https://github.com/atoulme/otlptest is a thing now. I'll close here and open a new issue with community to see if there's interest to contribute this to OpenTelemetry.

**Comment by atoulme** [comment]
Reopening this issue as the community is pushing towards making this a contrib component (see discussion https://github.com/open-telemetry/community/issues/1880).

Anyone interested in supporting this component?
