### ISSUE TITLE
Filelog receiver state file grows without bound in 0.87.0

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-collector-contrib#28567]
### Component(s)

pkg/stanza, receiver/filelog

## Description

When using the filelog receiver to collect Kubernetes logs, I've noticed our CPU usage slowly grow over time ever since the upgrade to 0.87.0. Looking at the CPU profile showed the receiver spending most of its time loading and saving state to disk. I've examined the state file manually, and it had over 4000 entries while the number of actual files present on disk was around 50. 

## Steps to Reproduce

I haven't tried yet, but I strongly suspect this can be reproduced just by having the receiver watch a directory, and creating and deleting differently named small files in it. 

## Expected Result

The receiver's CPU usage shouldn't grow over time without any correlation with the actual workload.

### Collector version

0.87.0

## Environment
I've originally seen this in AWS EKS 1.24.

### Additional context

Reverting to 0.86.0 appears to fix the problem. Looking at filelog receiver changes, the culprit appears to be https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27416. The problem appears to be fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27775, which only saves files which were read in a given cycle to the state, but I haven't verified this yet.

**Comment by swiatekm-sumo** [comment]
@djaglowski looking at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28491, it seems like you're aware of the possibility of known files growing unboundedly. I'm filing this to show that it actually comes up in practice, though the real problem is that we also persist it to disk in `0.87.0`.

**Comment by djaglowski** [comment]
Thanks for reporting @swiatekm-sumo. 

While I think #28491 will remove the unbounded memory for file _paths_, this is separate from what is persisted as part of the checkpoint information. 

It's not clear to me why or how we would be growing persistent information indefinitely. If you have any more insight on this I'd certainly appreciate it. Otherwise, I'm sure it'll surface as I further decompose and test the package.

**Comment by swiatekm-sumo** [comment]
@djaglowski I think I found the root cause. After #27416, we update `knownFiles` this way:

```go
func (m *Manager) saveCurrent(readers []*reader.Reader) {
	forgetNum := len(m.knownFiles) + len(readers) - cap(m.knownFiles)
	if forgetNum > 0 {
		m.knownFiles = append(m.knownFiles[forgetNum:], readers...)
		return
	}
	m.knownFiles = append(m.knownFiles, readers...)
}
```

However, when building the manager, we set the capacity of `knownFiles` to [10*MaxConcurrentFiles](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c9f18650927b91fa675c956ff2d91686619ce02b/pkg/stanza/fileconsumer/config.go#L185), which by default equals 10240.

If the capacity is much higher than the current length, `forgetNum` in the code is negative, and so we just add current readers to `knownFiles`.

This looks somewhat intentional, and if we weren't serializing this list to JSON and saving it on disk every loop, it might not even be a problem. We do end up keeping a whole bunch of copies of readers this way, though. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27775 doesn't actually fix the root cause, but it greatly reduces the practical impact.

**Comment by djaglowski** [comment]
Thanks for investigating. I understand now.

This design change was intentional but the arbitrary sizing of `knownFiles` was not considered carefully enough. Previously, the size of the history was correlated to the number of files matched per poll cycle, which in many situations is a smaller number. I think we can get back to something along these lines once #27823 is merged. From there, we may be able to tune it in even further.

**Comment by swiatekm-sumo** [comment]
Would you prefer if I close this ticket after verifying 0.88.0 fixes the immediate problem? Or should I wait until we cut down on the in-memory slice as well?

**Comment by djaglowski** [comment]
Let's leave it open for now. I'd like to stabilize this area of the code before closing the issue.
