### ISSUE TITLE
address lint issues: Implicit Memory Aliasing 

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#28584]
### Component(s)

receiver/kubeletstats

### Describe the issue you're reporting

This issue is to remove the `// nolint G601` comments in `receiver/kubeletstatsreceiver/internal/kubelet/metadata.go`

**Comment by codeboten** [comment]
This comment is added in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28572

**Comment by etiennep** [comment]
I'd like to work on this.

**Comment by TylerHelmuth** [comment]
@etiennep it's yours!

**Comment by atoulme** [comment]
Closing as complete.
