### ISSUE TITLE
linting: address indent-error-flow failure

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#28589]
### Component(s)

exporter/influxdb

### Describe the issue you're reporting

This issue is to remove address the `// nolint indent-error-flow` in `exporter/influxdcexporter/writer.go` introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28572

**Comment by yukinakanaka** [comment]
I'm working on this issue.

**Comment by codeboten** [comment]
Thanks @yukinakanaka! All yours
