### ISSUE TITLE
Move internal/golden to pkg/golden

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#28594]
### Is your feature request related to a problem? Please describe.

I have found the internal/golden package useful and would like to draw more on it. Unfortunately, I cannot import it in my projects as it is internal.

### Describe the solution you'd like

Move internal/golden to pkg/golden.

**Comment by atoulme** [comment]
@djaglowski Please let me know if you have an opinion on this.

**Comment by djaglowski** [comment]
@atoulme, I've always hoped we'd do this eventually. I support.
