### ISSUE TITLE
 [pkg/ottl] Add IsNaN Converter

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/opentelemetry-collector-contrib#28591]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has no way to check if a double value is `NaN`. https://pkg.go.dev/math#IsNaN

### Describe the solution you'd like

Add a new Converter, IsNaN that returns true if the given value is NaN. It should return false if the value is not a double. 

The implementing PR should

- [ ] Implement the function
- [ ] Add new unit tests for the function
- [ ] Add the function to pkg/ottl/ottlfuncs/functions.go
- [ ] Update the README at pkg/ottl/ottlfuncs/README.md

**Comment by sethallen** [comment]
I will work on this one! (Contribfest)

**Comment by TylerHelmuth** [comment]
@bryan-aguilar can you remind me of the situation you experienced that requires this function?

**Comment by TylerHelmuth** [comment]
Closing for now.  If anyone can come up with a way to produce `NaN` that would need checked please comment.

**Comment by huw0** [comment]
I have a situation where I'm scraping an OpenMetrics (Prometheus) endpoint that returns metrics that can be NaN when the application has started or is idle.

These are then sent via otlphttp to APM (Elastic), which throws a content parsing exception.

What I'd like to do is filter the metrics when the value is NaN.

Example of metrics, as taken from [Trino metrics with OpenMetrics](https://trino.io/docs/current/admin/openmetrics.html).

```
# TYPE io_airlift_http_client_type_HttpClient_name_ForDiscoveryClient_CurrentResponseProcessTime_Min gauge
io_airlift_http_client_type_HttpClient_name_ForDiscoveryClient_CurrentResponseProcessTime_Min NaN
# TYPE io_airlift_http_client_type_HttpClient_name_ForDiscoveryClient_CurrentResponseProcessTime_P25 gauge
io_airlift_http_client_type_HttpClient_name_ForDiscoveryClient_CurrentResponseProcessTime_P25 NaN
# TYPE io_airlift_http_client_type_HttpClient_name_ForDiscoveryClient_CurrentResponseProcessTime_Total gauge
io_airlift_http_client_type_HttpClient_name_ForDiscoveryClient_CurrentResponseProcessTime_Total 0.0
# TYPE io_airlift_http_client_type_HttpClient_name_ForDiscoveryClient_CurrentResponseProcessTime_P90 gauge
io_airlift_http_client_type_HttpClient_name_ForDiscoveryClient_CurrentResponseProcessTime_P90 NaN
```

@TylerHelmuth - please can you re-open this issue and the associated PR?
