### ISSUE TITLE
exporter/datadog: skip trace stats computation via feature flag

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/opentelemetry-collector-contrib#28615]
### Component(s)

exporter/datadog

### Is your feature request related to a problem? Please describe.

In some setups the exporter can not detected if stats have already been computed by the connector.

### Describe the solution you'd like

There should be a feature flag to disable stats computation.

**Comment by songy23** [comment]
This is fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28616.
