### ISSUE TITLE
[exporter/loki] Do not promote log level to loki label

### ISSUE THREAD

**Issue by mar4uk** [open-telemetry/opentelemetry-collector-contrib#28612]
### Component(s)

exporter/loki

### Is your feature request related to a problem? Please describe.

Currently, if the log record has a `severityNumber` attribute, `lokiexporter` adds `level` label corresponding to the `severityNumber`: see the mapping [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/loki/logs_to_loki.go#L228-L254)

For example, if the log record has the attribute `severityNumber=plog.SeverityNumberDebug4` label `level=DEBUG4` would be added in Loki

It is [not a good practice to promote log level to the label in Loki](https://grafana.com/blog/2020/08/27/the-concise-guide-to-labels-in-loki/).

### Describe the solution you'd like

`level` shouldn't be promoted to loki label automatically

**Comment by crobert-1** [comment]
_Removing `needs triage` as this was filed by a code owner and it makes sense from links provided._ 

Thanks for including relevant links, very clear and easy to understand!

**Comment by jpkrohling** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27446

**Comment by mar4uk** [comment]
I'm a little bit delaying on this one to make sure we aligned with native loki otlp enpoint

**Comment by mar4uk** [comment]
Since the loki exporter is going to be deprecated soon in favor of otlp exporter (Loki now supports otlp), I don't think we should make new changes to the loki exporter.

Will close this issue
