### ISSUE TITLE
Prometheus exporter should allow conflicting help and unit metadata

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#28617]
## Description

Original report: https://github.com/istio/istio/issues/47397

The prometheus exporter fails to gather metrics if the description differs between two metrics with the same name.

## Steps to Reproduce

With a prometheus receiver, scrape two endpoints with the same metric name, but different HELP (description).  Use the prometheus exporter to export the metrics.

## Expected Result

No error.  Per the [OTel specification](https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#metric-metadata-1):

> Exporters MUST drop entire metrics to prevent conflicting TYPE comments, but SHOULD NOT drop metric points as a result of conflicting UNIT or HELP comments. Instead, all but one of the conflicting UNIT and HELP comments (but not metric points) SHOULD be dropped. If dropping a comment or metric points, the exporter SHOULD warn the user through error logging.

I.e. we should be accepting the conflicting description, choosing one description to keep, and one to drop, and warning the user.

## Actual Result
 
The prometheus exporter fails incoming scrapes.

### Collector version

Don't know

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
2023-09-29T15:24:02.049Z        error   prometheusexporter@v0.80.0/log.go:23    error gathering metrics: 2 error(s) occurred:
* collected metric istio_build label:{name:"app"  value:"istiod"}  label:{name:"cluster"  value:"glooplatform-central"}  label:{name:"component"  value:"pilot"}  label:{name:"install_operator_istio_io_owning_resource"  value:"unknown"}  label:{name:"instance"  value:"10.108.2.7:15014"}  label:{name:"istio"  value:"istiod"}  label:{name:"istio_io_rev"  value:"1-18"}  label:{name:"job"  value:"istiod-metrics"}  label:{name:"namespace"  value:"istio-system"}  label:{name:"operator_istio_io_component"  value:"Pilot"}  label:{name:"pod_name"  value:"istiod-1-18-5f7964bccd-jlfwh"}  label:{name:"pod_template_hash"  value:"5f7964bccd"}  label:{name:"sidecar_istio_io_inject"  value:"false"}  label:{name:"tag"  value:"1.18.2-solo"}  gauge:{value:1} has help "Istio component build info" but should have ""
* collected metric istio_build label:{name:"app"  value:"istiod"}  label:{name:"cluster"  value:"glooplatform-east"}  label:{name:"component"  value:"pilot"}  label:{name:"install_operator_istio_io_owning_resource"  value:"unknown"}  label:{name:"instance"  value:"10.104.3.14:15014"}  label:{name:"istio"  value:"istiod"}  label:{name:"istio_io_rev"  value:"1-18"}  label:{name:"job"  value:"istiod-metrics"}  label:{name:"namespace"  value:"istio-system"}  label:{name:"operator_istio_io_component"  value:"Pilot"}  label:{name:"pod_name"  value:"istiod-1-18-7d66654c46-c5frb"}  label:{name:"pod_template_hash"  value:"7d66654c46"}  label:{name:"sidecar_istio_io_inject"  value:"false"}  label:{name:"tag"  value:"1.18.2-solo"}  gauge:{value:1} has help "Istio component build info" but should have ""
        {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.80.0/log.go:23
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
        github.com/prometheus/client_golang@v1.16.0/prometheus/promhttp/http.go:144
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2109
net/http.(*ServeMux).ServeHTTP
        net/http/server.go:2487
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
        go.opentelemetry.io/collector/config/confighttp@v0.80.0/compression.go:111
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2109
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
        go.opentelemetry.io/collector/config/confighttp@v0.80.0/clientinfohandler.go:28
net/http.serverHandler.ServeHTTP
        net/http/server.go:2947
net/http.(*conn).serve
        net/http/server.go:1991
```
```


### Additional context

_No response_

**Comment by jroper** [comment]
To work around this bug, does anyone know if it's possible to define a processor that can update the description of a metric? I can't see anything on any processor that allows editing it.

**Comment by krisztianfekete** [comment]
I _think_ you can enforce a description with a `transformprocessor`, although I would prefer to solve this properly.

**Comment by mjarosie** [comment]
Hi, I believe this issue is still relevant (pinging code owner: @Aneurysm9). It's causing issues with using one of the OTel libraries (linked above). Same as @krisztianfekete, I would also be happy to take a look at this, but would need guidance.

**Comment by martinrw** [comment]
We are having a similar issue... We are collecting metrics from some python and some Java Otel agents and depending on which one we get conflicting errors in our log:

the Python metrics give this error:
`http_client_request_size_bytes has help "Measures the size of HTTP request messages." but should have "The size of HTTP request messages"`

the Java ones give:
`http_client_request_size_bytes has help "The size of HTTP request messages" but should have "Measures the size of HTTP request messages."`

These errors appear to contradict each other.
At one point we added the following to our collector but it doesn't seem to have helped for this particular metrics
```
    transform:
      error_mode: ignore
      metric_statements:
        - context: metric
          statements:
            - set(description, "The size of HTTP request messages") where name == "http.client.request.size_bytes"
            - set(description, "The size of HTTP response messages") where name == "http.client.response.size_bytes"
```

It seems strange to me the a tiny difference in the description would cause metrics to be dropped... but if that's the way it has to be does anyone know another workaround or the reason I am getting this problem?

**Comment by martinrw** [comment]
Commenting to keep this open as it's still a problem for us

**Comment by eemehmet** [comment]
I 've faced the same issue.

**Comment by oncilla** [comment]
FWIW, the problem actually happens in prometheus/client_golang. 

https://github.com/prometheus/client_golang/blob/89f21b2cba4ea0f9cf449b454945f53047697158/prometheus/registry.go#L638

We are looking into forking client_golang to allow a clash of the description. But to solves this long term, I think we will need to file an issue with prometheus/client_golang instead.

**Comment by martinrw** [comment]
commenting to keep it open
