### ISSUE TITLE
Distro should include owners

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#28628]
### Component(s)

cmd/mdatagen

### Describe the issue you're reporting

There's a list of distros available in mdatagen:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5e285f0ebdb35e103b292a232fa65910f4c9c879/cmd/mdatagen/statusdata.go#L14-L24

However, this list doesn't include any owners. This makes it difficult to review PRs that include adding a component to any particular distro. I propose that owners should be listed, much like code owners for each of the listed distro.

**Comment by crobert-1** [comment]
Sounds good to me. 

To complete this we'll also need to add automation to ping the distribution owners when necessary.

Do we want labels for each distribution as well? We can use that as the event to ping the relevant owners. Maybe something of the form `distro:core`, `distro:contrib`, etc.

**Comment by dmitryax** [comment]
> Do we want labels for each distribution as well? We can use that as the event to ping the relevant owners. Maybe something of the form distro:core, distro:contrib, etc.

Sounds like a good idea 👍

**Comment by codeboten** [comment]
I like the label idea... I don't know how often we would end up using it. The only changes I can think of that are distro specific are changes to readme files to include a component in a distro, which i don't know if it opens often enough to warrant automation.

**Comment by atoulme** [comment]
I propose the following: we will create a file describing the contents of a distro generated via mdatagen, and have a CODEOWNERS entry generated from the owners of the distribution so we can tag anyone managing a specific distribution and make sure to notify them of any changes to their distribution.
