### ISSUE TITLE
Azure Event Hub Receiver: Update Metric Documentation

### ISSUE THREAD

**Issue by cparkins** [open-telemetry/opentelemetry-collector-contrib#28622]
### Component(s)

receiver/azureeventhub

### Describe the issue you're reporting

It appears that the documentation surrounding the Metrics created by the Azure Event Hub Receiver is out of date when compared to that of Logs.  This documentation should be updated to include the fields that the Metrics values are being converted to.  In addition the data regarding how the Metrics are created should also be updated to reflect what the code is actually doing.

**Comment by crobert-1** [comment]
@cparkins I see your PR has been merged. Can we mark this issue as complete, or is there more left to do here?

**Comment by cparkins** [comment]
Yes, I don't know of any other issues with the updated documentation.
