### ISSUE TITLE
[kafkareceiver] improve metrics and logs to include more information to debug consumers

### ISSUE THREAD

**Issue by ben-childs-docusign** [open-telemetry/opentelemetry-collector-contrib#28631]
### Component(s)

receiver/kafka

### Is your feature request related to a problem? Please describe.

We were seeing issues with our consumers not consuming all the data from our kafka broker (skipping messages) but we didn't have enough logs / metrics data to effectively debug until we added it manually.

### Describe the solution you'd like

1. Log topic name, and initial offset when logging start-consumer-group this will help to identify consumer groups where the offset is not being committed successfully.
2. Update the name tag on consumer metrics to include the partition / topic name or add a new tag with the partition / topic. Currently each partition consumer ends up emitting the metrics with the same tags and they overwrite eachother.

### Additional context
Here is an example update that we found helpful:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/73303353/2722a5dd-5205-4c82-bf4c-76233d819503)

**Comment by crobert-1** [comment]
Sounds like a good idea to me, feel free to open a PR if you're interested. 👍
