### ISSUE TITLE
[kafkareceiver] support session timeout configs (and maybe more) in kafka receiver.

### ISSUE THREAD

**Issue by ben-childs-docusign** [open-telemetry/opentelemetry-collector-contrib#28630]
### Component(s)

receiver/kafka

### Is your feature request related to a problem? Please describe.

We are trying to configure our kafka receiver based on the azure event hub recommendations but some of the configuration values are not available. We were seeing unecessary consumer failovers in our collector. The default session timeout is 10s but eventhub recommends a timeout of 30 seconds for event hub consumers.

These are the recommended settings from Azure: https://learn.microsoft.com/en-us/azure/event-hubs/apache-kafka-configurations

### Describe the solution you'd like

Add consumer.group.session.timeout config. E,g,

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/73303353/e9af5e9b-1138-414e-ba69-f13d5e4cb4ab)

### Describe alternatives you've considered

N/A

**Comment by VihasMakwana** [comment]
Hi @ben-childs-docusign, thanks for raising this request! 
Sounds like a valid ask. Let's see what owners have to say on this.
Also, would you be willing to raise a PR, as you already shared a snippet?

**Comment by strawgate** [comment]
@ben-childs-docusign I've linked a PR that adds these settings
