### ISSUE TITLE
[receiver/azureeventhub] Allow the Consumer Group to be set in Configuration

### ISSUE THREAD

**Issue by cparkins** [open-telemetry/opentelemetry-collector-contrib#28633]
### Component(s)

receiver/azureeventhub

### Is your feature request related to a problem? Please describe.

Currently there is no way to configure the Consumer Group used when using the Event Hub Receiver.  This feature is present in the Kafka Receiver and could be useful if another Client is already listening to the $Default Consumer Group.

### Describe the solution you'd like

Allow the Consumer Group to be specified in the Configuration.

### Describe alternatives you've considered

Using the Connection configuration to specify the Consumer Group (doesn't appear to be possible with the current library).

### Additional context

This is an issue I ran into because of the described problem where an unidentified Client was connecting and consuming all messages.  Which made it appear that no data was transiting the Event Hubs instance.  This idea came up because I was trying to troubleshoot this issue, which was possible with the Kafka Receiver.

**Comment by djaglowski** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28634
