### ISSUE TITLE
remove koanf v1.5 dependency

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#28647]
### Describe the issue you're reporting

i'm trying to get the last of the koanf v1.5 dependencies cleaned up, once the next jaeger release (v1.51.0) is out, we'll be down to a single dependency in the contrib repo that relies on koanf v1.5: the jaegerexporter

That component has been removed from the repo at v0.85.0, but it remains as a dependency for the testbed (to generate jaeger data for the jaeger receiver tests)... there's a couple of things we could do here and i was curious what people here thought of the options:

1. remove the jaeger generation test from the testbed
2. remove the jaegerexporter and generate data using some other tool
3. release a v0.85.1 patch for jaegerexporter to remove the koanf dependency

**Comment by atoulme** [comment]
Could we run with 2. using the sapmexporter?

**Comment by codeboten** [comment]
If it emits jaeger protos, i don't see why not

**Comment by codeboten** [comment]
Following up on this, the sapm exporter doesn't support sending gRPC, so the original question remains :)
