### ISSUE TITLE
Move collectdreceiver to beta

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#28658]
### Component(s)

receiver/collectd

### Describe the issue you're reporting

Consider moving collectdreceiver from alpha to beta stability.

**Comment by crobert-1** [comment]
@atoulme I see you're the sole code owner here, are there any known TODOs that are in the way of moving this to beta? 

(It looks like you have an open PR for the only issue against this component which appears to be part of this effort.)

**Comment by atoulme** [comment]
Not that I'm aware of. Some work required maybe to isolate this receiver from wavefrontreceiver, they somehow depend on each other. checkapi has collectdreceiver in its allowlist because of it, and that might need to be fixed.
