### ISSUE TITLE
[exporter/clickhouse] Add support for short data TTL

### ISSUE THREAD

**Issue by Hazuwall** [open-telemetry/opentelemetry-collector-contrib#28675]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

I want to save disk space by reducing retention to several hours, which is more than enough for me. I cannot achieve this without manual schema migration or complex workarounds.

### Describe the solution you'd like

It would be great to have the possibility to configure TTL by using a ttl_hours parameter instead of ttl_days if the duration is less than a day.

### Describe alternatives you've considered

I have considered more general alternative approaches:
- Allow the user to use a custom script for table creation. This seems like overkill and is not very convenient for both users and developers.
- Add the TTL expression to the parameters. As I understand, this is not enough because the partition expression also needs to be changed. Additionally, I cannot imagine a use case for TTL other than days/hours.

**Comment by dmitryax** [comment]
This makes sense. I think TTL should be `time.Duration` field, not the days count. @Hazuwall do you have a chance to apply this change yourself? We would need to deprecate `ttl_days` (don't delete it for now) in favor of the new `ttl` option.

**Comment by Hazuwall** [comment]
I will give it a try in my spare time. To be honest, I have limited experience in contributing to open-source projects and working with Golang, so it may take some time.

**Comment by dmitryax** [comment]
Timeline is not a problem. I don't think anyone else is interested in this. I can still put a `help wanted` label, maybe someone else is interested in picking it up. Once you have time, please take a look at https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md before starting to work on it.

**Comment by leartbeqiraj1** [comment]
I will make this change within this week, or next week at the latest.
