### ISSUE TITLE
[Flaky test] coreinternal/consumerretry/logs_test.go failed on windows

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#28694]
### Component(s)

internal/core

### What happened?

`internal/coreinternal/consumerretry/logs_test.go` is broken on Windows test matrix on mainline https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/workflows/build-and-test-windows.yml?query=branch%3Amain

```
--- FAIL: TestConsumeLogs (0.12s)
    --- FAIL: TestConsumeLogs/retry_success (0.10s)
        logs_test.go:66: 
            	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/coreinternal/consumerretry/logs_test.go:66
            	Error:      	Not equal: 
            	            	expected: <nil>(<nil>)
            	            	actual  : *errors.errorString(&errors.errorString{s:"retry later"})
            	Test:       	TestConsumeLogs/retry_success
--- FAIL: TestConsumeLogs_ContextDeadline (0.07s)
    logs_test.go:92: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/coreinternal/consumerretry/logs_test.go:92
        	Error:      	"retry later" does not contain "context is cancelled or timed out retry later"
        	Test:       	TestConsumeLogs_ContextDeadline
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/consumerretry	0.569s
```

### Collector version

mainline

## Environment
OS: Windows

**Comment by pjanotti** [comment]
I tried multiple runs on my box and got no repro. However, by code inspection I can see, that due to some concurrency on the test code, how both errors could happen. In theory the fix can happen on any system not only Windows. The fix should be entirely on the test code. Giving that this one seems hard to repro I'm giving it a low priority on my work queue, if some volunteer wants to fix them, please do so.

**Comment by crobert-1** [comment]
_Removing `needs triage` based on @pjanotti's comment._

**Comment by pjanotti** [comment]
Hit the first one on my fork - documenting here to give a sense of frequency so we can prioritize them accordingly

https://github.com/pjanotti/opentelemetry-service-contrib/actions/runs/6789094249/job/18455541281#:~:text=%2D%2D%2D%20FAIL%3A%20TestConsumeLogs%20(0.12s,588
```terminal
--- FAIL: TestConsumeLogs (0.12s)
    --- FAIL: TestConsumeLogs/retry_success (0.11s)
        logs_test.go:66: 
            	Error Trace:	D:/a/opentelemetry-service-contrib/opentelemetry-service-contrib/internal/coreinternal/consumerretry/logs_test.go:66
            	Error:      	Not equal: 
            	            	expected: <nil>(<nil>)
            	            	actual  : *errors.errorString(&errors.errorString{s:"retry later"})
            	Test:       	TestConsumeLogs/retry_success
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/consumerretry	0.251s
```

**Comment by pjanotti** [comment]
Another hit https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6797762319/job/18480554554#:~:text=%2D%2D%2D%20FAIL%3A%20TestConsumeLogs%20(0.19s,592

**Comment by pjanotti** [comment]
It keeps happening, e.g.: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7631311059/job/20788982979#step:7:601

**Comment by pjanotti** [comment]
Hi @david-sevcik - I don't think this one is happening at this time. We can always re-open if appropriate.
