### ISSUE TITLE
splunkhecreceiver doesn't set resource attributes

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector-contrib#2871]
See https://github.com/open-telemetry/opentelemetry-collector/issues/2805

The component doesn't use resource attributes at all but puts host, etc. into the log attributes. This means that if you use something like the resourcedetection processor it updates the resource attributes but the splunkhecreceiver may have put host.name in the log attributes.

**Comment by atoulme** [comment]
Dup for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13997

**Comment by atoulme** [comment]
Closing as duplicate.
