### ISSUE TITLE
[connector/count] possible to collect the amount of traces, instead of spans, before sampling?

### ISSUE THREAD

**Issue by brightzheng100** [open-telemetry/opentelemetry-collector-contrib#28845]
### Component(s)

connector/count

### Is your feature request related to a problem? Please describe.

It should be a common concern about some metrics when sampling is enabled:
- How many traces do we have before sampling?
- How many traces are sampled?

I checked through the receivers, exporters, and connectors but I don't know how I can achieve it.
The solution may most likely use the connector/count with something like this:

```yaml
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler]
      exporters: [count,logging]
    metrics:
      receivers: [count]
      exporters: [logging]
```

However, the count can only count the spans, not traces.

### Describe the solution you'd like

Not sure whether it's the right solution to use the connector/count but the ideal solution might be something like this:
1. Count the amount of the traces before processors where sampling will be performed;
2. Export the metrics, which might be `trace.count`, so that other exporter can export/log the metrics.

```yaml
service:
  pipelines:
    traces:
      receivers: [otlp,count]
      processors: [probabilistic_sampler]
      exporters: [logging]
    metrics:
      receivers: [count]
      exporters: [logging]
```
> Note: above configuration is for illustration only, it actually won't work: connector "count" used as receiver in traces pipeline but not used in any supported exporter pipeline.

**Comment by jpkrohling** [comment]
You can see how many _spans_ a collector instance received by checking the receiver metrics:

```
otelcol_receiver_accepted_spans{receiver="otlp",service_instance_id="7039ddbe-2a58-46e4-b13d-7e52d9acd007",service_name="otelcol-contrib",service_version="0.87.0",transport="grpc"} 2000
```

When using the tail-sampling processor, the following metric will show many trace IDs were "seen" by the processor:

```
otelcol_processor_tail_sampling_new_trace_id_received{service_instance_id="a304d362-a55e-4f22-a71b-955a008029fa",service_name="otelcol-contrib",service_version="0.87.0"} 1000
```

The count connector will not keep track of trace IDs, so it provides only a view of spans, not traces. In that case, you can use a configuration like this:

```yaml
receivers:
  otlp:
    protocols:
      grpc:

processors:
  tail_sampling:
    decision_wait: 5s
    num_traces: 50_000
    expected_new_traces_per_sec: 10_000
    policies:
      [
        {
          name: only-10-percent,
          type: probabilistic,
          probabilistic: { sampling_percentage: 10 },
        },
      ]

exporters:
  logging/metrics:
    verbosity: detailed
  logging/traces:

connectors:
  count:
  forward:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - count
        - forward
    traces/sampling:
      receivers:
        - forward
      processors:
        - tail_sampling
      exporters:
        - logging/traces
    metrics:
      receivers:
        - count
      processors: []
      exporters:
        - logging/metrics
```

In this test, you can see 4 metrics:

```
2023-11-01T10:21:35.261-0300    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging/metrics", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-11-01T10:21:35.261-0300    info    ResourceMetrics #0
Resource SchemaURL: 
Resource attributes:
     -> service.name: Str(telemetrygen)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/countconnector 
Metric #0
Descriptor:
     -> Name: trace.span.count
     -> Description: The number of spans observed.
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Delta
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-11-01 13:21:35.261343837 +0000 UTC
Value: 512
        {"kind": "exporter", "data_type": "metrics", "name": "logging/metrics"}
2023-11-01T10:21:35.267-0300    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging/metrics", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-11-01T10:21:35.267-0300    info    ResourceMetrics #0
Resource SchemaURL: 
Resource attributes:
     -> service.name: Str(telemetrygen)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/countconnector 
Metric #0
Descriptor:
     -> Name: trace.span.count
     -> Description: The number of spans observed.
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Delta
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-11-01 13:21:35.267388013 +0000 UTC
Value: 512
        {"kind": "exporter", "data_type": "metrics", "name": "logging/metrics"}
2023-11-01T10:21:35.273-0300    info    ResourceMetrics #0
Resource SchemaURL: 
Resource attributes:
     -> service.name: Str(telemetrygen)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/countconnector 
Metric #0
Descriptor:
     -> Name: trace.span.count
     -> Description: The number of spans observed.
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Delta
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-11-01 13:21:35.273588744 +0000 UTC
Value: 512
        {"kind": "exporter", "data_type": "metrics", "name": "logging/metrics"}
2023-11-01T10:21:35.279-0300    info    ResourceMetrics #0
Resource SchemaURL: 
Resource attributes:
     -> service.name: Str(telemetrygen)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/countconnector 
Metric #0
Descriptor:
     -> Name: trace.span.count
     -> Description: The number of spans observed.
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Delta
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-11-01 13:21:35.278994289 +0000 UTC
Value: 464
        {"kind": "exporter", "data_type": "metrics", "name": "logging/metrics"}
```

The first three metrics with a count of 512 and the last one with 464, totaling 2k spans, which matches the number I sent via telemetrygen (`telemetrygen traces --traces 1000 --otlp-insecure`). It also matches the number of spans recorded by the receiver:

```
otelcol_receiver_accepted_spans{receiver="otlp",service_instance_id="4f1b7cdc-5f31-4dfd-aa0d-bf4550d8e00a",service_name="otelcol-contrib",service_version="0.87.0",transport="grpc"} 2000
```

**Comment by jpkrohling** [comment]
I'm closing this, but feel free to reopen if there are still questions.

**Comment by brightzheng100** [comment]
I learned something here about how to use `count` and `forward` connectors. Thanks @jpkrohling 

But I believe my questions haven't been addressed, which may not link to `count` connector:
1. How many traces do we have before sampling?
2. How many traces are sampled? 

Please feel free to advise here. Thank you!

**Comment by jpkrohling** [comment]
Sorry that it wasn't clear on my previous message.

The only way to determine how many traces were seen before sampling was done is with this metric from the tail-sampling processor:

```
otelcol_processor_tail_sampling_new_trace_id_received{service_instance_id="a304d362-a55e-4f22-a71b-955a008029fa",service_name="otelcol-contrib",service_version="0.87.0"} 1000
```

Using the same processor, you can see the metrics on how many traces were sampled and how many weren't:

```
otelcol_processor_tail_sampling_global_count_traces_sampled{sampled="false",service_instance_id="a304d362-a55e-4f22-a71b-955a008029fa",service_name="otelcol-contrib",service_version="0.87.0"} 889
otelcol_processor_tail_sampling_global_count_traces_sampled{sampled="true",service_instance_id="a304d362-a55e-4f22-a71b-955a008029fa",service_name="otelcol-contrib",service_version="0.87.0"} 111
```

All other components in the collector report metrics for _spans_, the tail-sampling is likely the only one that reports metrics for _traces_.

**Comment by brightzheng100** [comment]
Indeed, these metrics are very helpful, thanks for pointing that out. Thank you very much @jpkrohling.

However, they are `counter`s so the values are always accumulative.
So currently my way to "reset" them is to:
1. manually restart the Collector (so that the `service_instance_id` will be changed); and 
2. use the `service_instance_id` to filter the metrics; and
3. group them by `sampled` so I eventually have the numbers: sampled=true and sampled=false, thus total will be the sum of true and false values.

But I believe there must be a better way to reset the counters so that I can answer questions like:
1. How many traces do we have, since some specific time?
2. How many traces are sampled, since some specific time?

Would you might to share some guidance on this?

**Comment by jpkrohling** [comment]
> How many traces do we have, since some specific time or between time 1 and time 2?
> How many traces are sampled, since some specific time or between time 1 and time 2?

That's a job for your backend, likely a time-series database of sorts.

**Comment by brightzheng100** [comment]
Counter might be harder to use compared to Gauge.

As per the definition [here](https://prometheus.io/docs/concepts/metric_types/#counter):
```
Counter
A counter is a cumulative metric that represents a single monotonically increasing counter
whose value can only increase or be reset to zero on restart. 
For example, you can use a counter to represent the number of requests served, tasks completed, or errors.
```

I'm curious whether current Counter-based metrics can even achieve the goals to visulize in a time-series tool like Prometheus (+Grafana).
