### ISSUE TITLE
[chore][testbed] Do not use export function `carbonreceiver.New()`

### ISSUE THREAD

**Issue by sakulali** [open-telemetry/opentelemetry-collector-contrib#28857]
### Component(s)

testbed

### Is your feature request related to a problem? Please describe.

`testbed` module depends on the export function `carbonreceiver.New()`. When i use checkapi tool(go run cmd/checkapi/main.go .), found error as shown below:

>  2023/11/02 11:00:40 receiver/carbonreceiver has more than one function: "New,NewFactory"
>  exit status 1

That seems function `carbonreceiver.New()` should not export.

### Describe the solution you'd like

For `testbed` module, we can replace export function `carbonreceiver.New()` with `factory.CreateMetricsReceiver`. Then, we can adjust `carbonreceiver` to make it pass the checkapi tool.

**Comment by crobert-1** [comment]
Resolved by #28858. Thanks @sakulali!
