### ISSUE TITLE
[Processor/Tailsampling] How to retrieve metrics for the processor and send it to otlp exporter?

### ISSUE THREAD

**Issue by brightzheng100** [open-telemetry/opentelemetry-collector-contrib#28861]
### Component(s)

processor/tailsampling

### Describe the issue you're reporting

I'm seeing some interesting metrics, like `count_traces_sampled`, within the tailsampling processor.
And I'm curious how I can export them to my `otlp` exporter so that I can consume them at the backend.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/metrics.go#L22-L35

This might be a very newbie question but I'd appreciate it if anyone could shed some light on it. Thank you!

**Comment by brightzheng100** [comment]
Oh, after reading some more code, I realized that the metrics are actually exposed through `localhost:8888/metrics` in Prometheus format.

Is this documented somewhere?

**Comment by jpkrohling** [comment]
Surprisingly enough, we don't! Would you be interested in contributing to it? Some info can be found here:

https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md

**Comment by brightzheng100** [comment]
Indeed, the information pieces are there already but are scattered across different places.

It might be ideal to consolidate the doc with both:
- Here in the "Troubleshooting": https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#metrics
- And here in the official doc: https://opentelemetry.io/docs/collector/configuration/#telemetry

Let me have a try to make it clearer.

**Comment by brightzheng100** [comment]
One finding, after testing and digging into the code, is that the metrics endpoint is actually exposed to all interfaces by default, which is not aligned with the documentation.

https://github.com/open-telemetry/opentelemetry-collector/blob/main/otelcol/unmarshaler.go#L63

Do you think the current default exposure is expected? @jpkrohling

**Comment by jpkrohling** [comment]
> One finding, after testing and digging into the code, is that the metrics endpoint is actually exposed to all interfaces by default, which is not aligned with the documentation.

That should definitely not be the case!

**Comment by brightzheng100** [comment]
> That should definitely not be the case!

Do you mean 1) my understanding is wrong, or 2) the code is not as expected as the endpoint should be exposed at `127.0.0.1:8888` by default as documented for security reasons?

**Comment by jpkrohling** [comment]
2 - we should NOT expose internal metrics on all interfaces.

**Comment by atoulme** [comment]
It looks like the original issue is addressed and question was answered. Closing as complete. Please reopen if more discussion is needed.
