### ISSUE TITLE
New component: Tinder Log Service exporter

### ISSUE THREAD

**Issue by syllr** [open-telemetry/opentelemetry-collector-contrib#28862]
### The purpose and use-cases of the new component

[Tinder Log Service](https://www.volcengine.com/docs/6470) is a one-stop service for log data provided by volcengine, this exporter will convert OpenTelemetry data directly into Tinder Log service logs, which can be searched by Tinder Log Service.

### Example configuration for the component

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  volcenginetlsexporter/traces:
    # TLS Endpoint, https://www.volcengine.com/docs/6470/73641
    endpoint: "https://tls-cn-beijing.ivolces.com"
    # TLS topic id
    topic_id: "39f0bce1-e37e-4dc5-ab06-801d310b****"
    # Volcengine access key
    access_key: "AKKTNTA1OTlsJSAQ1NT5SNBXk5OIWANsSmMTg0ZWU****"
    # Volcengine secret key
    secret_key: "T0RPLS5EUTFZVsLrTmpAKOSKaGCVRGsxTjJVMkjlIATBNV1ULAJXJMLNj****"
    # Volcengine region
    region: "cn-beijing"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ volcenginetlsexporter/traces ]

### Telemetry data types supported

 traces

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

syllr(https://github.com/syllr)

**Comment by crobert-1** [comment]
Hello @syllr, thanks for proposing this component! It looks like in the description of the log service product it's used for log data. However, under `Telemetry data types supported` it says `traces`. Can you explain why this new component would be for exporting traces instead of logs?

**Comment by syllr** [comment]
> Hello @syllr, thanks for proposing this component! It looks like in the description of the log service product it's used for log data. However, under `Telemetry data types supported` it says `traces`. Can you explain why this new component would be for exporting traces instead of logs?
> 
> Also, can you share more information about what log formats the log service supports? There are existing exporters that can send logs in quite a few formats, so I want to make sure none of those work for you before we create a new component.

Hello   @crobert-1 ，We will support metrics and logs later，But now we only support traces，which can be related with user     logs which already in log service.

There should be no other export that supports Tinder Log Service, because we use our own defined pb format,This is the pb format log we defined.

`syntax = "proto3";
package pb;
option go_package = "./;pb";
message LogContent
{
  string Key = 1;
  string Value = 2;
}

message Log
{
  int64 Time = 1;// UNIX Time Format

  repeated LogContent Contents = 2;

}
message LogTag
{
  string Key = 1;
  string Value = 2;
}
message LogGroup
{
  repeated Log Logs = 1;
  string Source = 2;
  repeated LogTag LogTags = 3;
  string FileName = 4;
  string ContextFlow = 5;
}

message LogGroupList
{
  repeated LogGroup LogGroups = 1;
}`

**Comment by syllr** [comment]
@crobert-1 hello hello

**Comment by syllr** [comment]
Is there any more information need me to provide?
