### ISSUE TITLE
New component: value generator(a kind of receiver)

### ISSUE THREAD

**Issue by hiwayama** [open-telemetry/opentelemetry-collector-contrib#28882]
### The purpose and use-cases of the new component

Currently, OpenTelemetry only allows pipelines to run by obtaining values from outside.
So I propose a plugin that periodically generates fixed values in the ootel-collector in the receiver's phase.

use-cases of the new component
* Simplification of preparation for operation verification of processors and exporters
* Simplification of health check for monitoring pipeline after otel-collector
etc.

This may be out of OpenTelemetry's custom receiver policy, 
but I would be happy to be advised if there is a better way.

### Example configuration for the component

`items` : Array holding key/value combinations of values to be generated
`name` : a key value of generated value
`value` : generated Value
`interval`: Interval to generate values (unit: second)

example:
```
receivers:
  mock-generator:
    items:
      - name: value1
         value: 1
   interval: 10s
```

### Telemetry data types supported

* metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Additional context

If you think this idea is a good one I will try to create a PR about this custom plugin.

**Comment by mx-psi** [comment]
There are two existing components that may help you with this:
1. [telemetrygen](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/telemetrygen#metrics), which can generate mock metrics
2. The [otlpjsonfile receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/otlpjsonfilereceiver) which can read an OTLP/JSON file and send its data down the pipeline

Could you take a look at those and see if they help with your use case? We can consider enhancements to either if you have suggestions.

**Comment by hiwayama** [comment]
Thank you for your comment.

telemetrygen helps with my usecase.

Thank you.
