### ISSUE TITLE
UDP-receiver improve high-scale performance by skipping usage of decoder when nop encoding is defined

### ISSUE THREAD

**Issue by hovavza** [open-telemetry/opentelemetry-collector-contrib#28899]
### Component(s)

pkg/stanza, receiver/udplog

### Is your feature request related to a problem? Please describe.

Udp receiver needs to to be maximally optimized since in high-scale scenarios, it's very easy to lose data.
Specifically, udp-receiver calls the decoder even when nop encoding is defined. That is unnecessary, since all the decoder does is copy the byte array to a new byte array (see here: https://cs.opensource.google/go/x/text/+/refs/tags/v0.14.0:transform/transform.go;l=313). The udp-receiver immediately converts that byte array to a string anyway.

### Describe the solution you'd like

In handleMessage, in nop encoding is configured, don't run the decode method.
This saves a memory allocation for each packet. In high scale scenarios, it can mean hundred of thousands less allocation per second, which reduces load on the GC, and reduces memory usage.

### Describe alternatives you've considered

None. This is a very specific suggestion.

**Comment by djaglowski** [comment]
Thanks for the issue @hovavza. Seems reasonable to me.

**Comment by djaglowski** [comment]
Closed by #28901
