### ISSUE TITLE
[processor/resourcedetection] Additional docker attributes

### ISSUE THREAD

**Issue by schewara** [open-telemetry/opentelemetry-collector-contrib#29018]
### Component(s)

processor/resourcedetection

### Describe the issue you're reporting

It would be super helpful if the Docker Metadata would support more attributes, like the ones proposed in https://opentelemetry.io/docs/specs/semconv/resource/container/

An example use case would be a CI/CD Pipeline where multiple integration tests are running in parallel for different feature branches, which can only be distinguished by a unique container.name or container.image.tag

**Comment by crobert-1** [comment]
I think this is a good idea. [Here's](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor#docker-metadata) the current list of resource attributes we're getting from Docker.

This will require some level of plumbing of these resource attributes. The resource detection processor is getting docker data from `internal/metadataproviders/docker` ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/metadataproviders/docker/metadata.go)), which is getting data from [Docker's golang client package](https://pkg.go.dev/github.com/docker/docker/client). For any new container resource attribute we'll have to add it to the internal metadata provider, and then get it from there. (This also means we're blocked by the Docker client if data we want isn't exposed.)

@schewara would you be interested in adding these resource attributes?

**Comment by schewara** [comment]
@crobert-1 Generally I would be interested, but therefore I need to learn Go first, which might take a while until I get around it.

**Comment by crobert-1** [comment]
> @crobert-1 Generally I would be interested, but therefore I need to learn Go first, which might take a while until I get around it.

Fair point 🙂

**Comment by socheatsok78** [comment]
I have a question regarding to the `internal/metadataproviders/docker`. It seem that the internal `metadataproviders` get data from the mounted `docker.sock`. In this case how to cross-reference metric with what the `processor/resourcedetection` based on the `metadataproviders`?

**Comment by hq-conf** [comment]
Has there been any work on pulling additional docker attributes, either as part of resourcedetection or dockerstats? Specifically, I am looking for the `container.image.tag` - as it stands, am I correct in saying that I would need to write a transform to extract this as a custom attribute?

**Comment by crobert-1** [comment]
@hq-conf You might want to try the [k8s attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor), it looks like it can get the`container.image.tag`.

**Comment by schewara** [comment]
How would the actual configuration for the k8s attribute processor look like to grab the labels from a docker container?

**Comment by crobert-1** [comment]
> How would the actual configuration for the k8s attribute processor look like to grab the labels from a docker container?

The [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md) has information for how to accomplish this. There's also a [config example](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor#config-example) that shows how to extract metadata from the k8s environmnent.
