### ISSUE TITLE
Support IsMatch function take pattern parameter from attributes

### ISSUE THREAD

**Issue by rtekdogan** [open-telemetry/opentelemetry-collector-contrib#29011]
### Is your feature request related to a problem? Please describe.

While collecting stdout logs, we would like to filter some containers based on pod annotations. With current filterprocessor and static string can be used as pattern, I request to IsMatch function to accept attributes as second parameter

### Describe the solution you'd like

I suggested my solution with this [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29007)

**Comment by evan-bradley** [comment]
I'd also like to allow providing dynamic values in any function arguments that hold arbitrary strings. We definitely can find a way to keep our current functionality for static-value arguments, but I think we will need to add to the language to enable that.

**Comment by TylerHelmuth** [comment]
I wonder if we could add to the Getter interface some sort of IsStatic function that helps identify this Getter as returning a static value.

**Comment by TylerHelmuth** [comment]
If you can come up with a way to perform regex validation of static strings when the `pattern` parameter is a `StringGetter` that would be the preferred option, but I'm willing to move to a `StringGetter` even if that isn't possible.

Please add some benchmarks to the function so we can compare the performance before and after.

**Comment by rtekdogan** [comment]
Hi @TylerHelmuth 
I wrote some benchmark test in my [fork](https://github.com/rtekdogan/opentelemetry-collector-contrib/blob/performance_test/pkg/ottl/ottlfuncs/func_is_match_test.go#L200) 

In proposed solution, I cached compiled patterns and wrote 2 benchmark test, 1 for same pattern with same target and the other one for changing pattern in each iteration and keeping target same.

Results for proposed change:

> goos: darwin
> goarch: arm64
> pkg: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/ottlfuncs
> Benchmark_performance_same_pattern-8             2390307               503.1 ns/op
> Benchmark_performance_different_pattern-8         466681              3142 ns/op
> PASS
> ok      github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/ottlfuncs    3.950s


Results for existing:

> goos: darwin
> goarch: arm64
> pkg: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/ottlfuncs
> Benchmark_performance_same_pattern-8              705002              1683 ns/op
> Benchmark_performance_different_pattern-8         610514              2195 ns/op
> PASS
> ok      github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/ottlfuncs    3.325s

**Comment by TylerHelmuth** [comment]
@rtekdogan thank you for those benchmarks.  I have not had time to work on this issue yet, but I think there is still a way for a Getter to announce that it is static and can be called before hot-path execution.
