### ISSUE TITLE
[processor/resourcedetection] failed to convert cpuinfo family to integer

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#29025]
### Component(s)

processor/resourcedetection

## Description

system resource detection fails with:
```
{"level":"warn","ts":1699364976.361069,"caller":"system/system.go:102","msg":"failed to get host cpuinfo","kind":"processor","name":"resourcedetection/env","pipeline":"metrics","error":"failed to convert cpuinfo family to integer: strconv.ParseInt: parsing \"POWER\": invalid syntax"}
```

The issue is that system detector expects the family to be int in:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c26444b0069e86501f551dee5d1fbe488c94b051/processor/resourcedetectionprocessor/internal/system/system.go#L150

But the actual library returns `POWER` string in certain cases:

SEE: https://github.com/shirou/gopsutil/blob/e74324b6a726997ce756b8f79dbbd7a3a0999ba0/cpu/cpu_linux.go#L264

Also looking at this repo which has a lot of example of cpuinfo, there seems to be a lot of families that are not numbers:

https://github.com/search?q=repo%3Arandombit%2Fcpuinfo%20Family&type=code

## Steps to Reproduce

-

## Expected Result
No error

### Collector version

v0.88.0

### Additional context

I believe we need to change `host.cpu.family` to be a string resource attribute instead of int and get rid of parsing.

**Comment by mx-psi** [comment]
This is actually wrong at the spec level https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/host.md cc @ChrsMark I think we should change the type to string

**Comment by mx-psi** [comment]
Filed open-telemetry/semantic-conventions/issues/495

**Comment by mx-psi** [comment]
@povilasv I filed #29152 for this, PTAL
