### ISSUE TITLE
Change import go.opentelemetry.io/collector/config/configmodels to config

### ISSUE THREAD

**Issue by WPH95** [open-telemetry/opentelemetry-collector-contrib#2903]
**Describe the bug**
https://github.com/open-telemetry/opentelemetry-collector/pull/2808
opentelemetry-collector change configmodels move to config
a lot of code needs to upgrade
e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/awsemfexporter/factory.go#L21

**Comment by bogdandrutu** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2899
