### ISSUE TITLE
Add Kubernetes component metrics

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-collector-contrib#29053]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

Right now, there's no good way to pull metrics from the apiserver, controller, scheduler other than using prometheus scraping. It would be great if I didn't need to configure all of the components required for those, and I could just use the k8scluster receiver instead.

### Describe the solution you'd like

Scrape metrics from kubernetes components in the k8scluster receiver, these would need to be explicitly enabled.

### Describe alternatives you've considered

Scrape with prometheus using the target allocator and servicemonitors.

**Comment by jaronoff97** [comment]
argh, that's a bummer. I really want to avoid running the prometheus receiver as I would prefer the metrics to match otel semantic conventions where possible without having to run a bunch of transformations. I can update my config as such for now.

**Comment by crobert-1** [comment]
> components provide metric in Prometheus format.

@povilasv To make sure I understand: You're saying kubernetes cluster components expose metrics in Prometheus format? So to make this possible the k8s cluster receiver would need to be modified to be able to accept Prometheus formatted metrics, then translate them into the pmetric format?

**Comment by jaronoff97** [comment]
@povilasv sure! np. Yes, of course we can just use the prometheus receiver w/ the target allocator for service monitor discovery etc. which I already do in the kube-otel-stack. I have another chart the [otel-cloud-stack](https://github.com/lightstep/otel-collector-charts/blob/main/charts/otel-cloud-stack) whose goal is to get all of your kubernetes metrics using otel semantic convention rather the prometheus conventions. I was hoping to avoid mixing these two formats (prometheus and otel) in this new chart by having a collector receiver which emits the metrics in the otel convention.

Separately, I'm also working through some improvements to finally close [this issue](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/562) in the coming weeks.

**Comment by danielgblanco** [comment]
> I was hoping to avoid mixing these two formats (prometheus and otel) in this new chart by having a collector receiver which emits the metrics in the otel convention.

I agree this would be a really good end goal for OTel "native" components to avoid having to include a `prometheus` receiver for cluster-level metrics.
