### ISSUE TITLE
Add support for exporting es apm data to otlp-collector

### ISSUE THREAD

**Issue by LHB6540** [open-telemetry/opentelemetry-collector-contrib#29082]
### Is your feature request related to a problem? Please describe.

My organization's original APM efforts were all based on Elastic APM, and when we tried to migrate to OTLP, some parts went very smoothly, such as the Java application, while other languages encountered problems, such as PHP, whose auto-detection required us to upgrade PHP Recent major version updates and code changes. After evaluation, we decided to retain Elastic APM, but our current visualization work has shifted to LOKI, Prometheus, and Grafana stacks. APM is left alone in Elastic APM, which makes our work experience feel more fragmented.

### Describe the solution you'd like

Therefore, a good solution is to add support for Elastic APM to OTLP conversion in otlp-collector, so that we can collect data to Tempo, and all observability work will be completed in Grafana. I noticed that opentelemetry-collector can already convert OTLP to ES APM data, I'm not sure if this part of the job should be done by opentelemetry-collector, so I raised the same issues with ES APM. Sorry if this has caused you the wrong confusion.

### Describe alternatives you've considered

One alternative that has been considered is to enable Grafana to parse the Trace data of ES APM. Grafana already has an Elasticsearch data source, but it does not support drawing as a Trace view. I have opened issues under Grafana's repository.
https://github.com/grafana/grafana/issues/77907

**Comment by crobert-1** [comment]
Am I correct in summarizing your request in that you want to add trace support to the existing [ElasticSearch receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/elasticsearchreceiver)?

**Comment by crobert-1** [comment]
Hello @LHB6540, I'm having a bit of a hard time understanding your use case and request. It looks like your goal is to no longer use Elasticsearch for your APM data. Are you trying to extract existing traces from Elasticsearch? Is that the correct summary here? Am I missing something?

**Comment by LHB6540** [comment]
> Hello @LHB6540, I'm having a bit of a hard time understanding your use case and request. It looks like your goal is to no longer use Elasticsearch for your APM data. Are you trying to extract existing traces from Elasticsearch? Is that the correct summary here? Am I missing something?

Yes, I plan not to use Elastic to process data anymore, but the workload of migrating the collector or code integration framework from Elastic Agent to otlp is huge. I hope otlp-collector can receive the data collected by Elastic Agent and then output it to a storage or processing system that supports otlp.

**Comment by crobert-1** [comment]
I have two suggestions here:

1. Add Elasticsearch's data format to the [encoding extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding). I assume this is the best option as it gives extra flexibility in using different components with this data format. 
2. Add trace support to the [Elasticsearch receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/elasticsearchreceiver). This may not work exactly though as the receiver currently is querying Elasticsearch for performance metrics, not actually getting data stored in the platform.

I'll defer to others at this point to give feedback on which would be preferable, or if there's another option I'm missing.
