### ISSUE TITLE
[pkg/ottl] Add Epoch Time Parsing Functionality

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-collector-contrib#29088]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

There's currently no easy way to get an epoch time from a value.  
here's an example of the best way I've come up with to parse a simple epoch time.

example:
```
- set(time, Time("1970-01-01T00:00:00.000000+0000", "%Y-%m-%dT%H:%M:%S.%f%z") + Duration(Concat([body["timestamp"], "ms"], "")))
```
We have to add the duration to the beginning of the epoch to be able to parse the timestamp. So, we are using additional computation to parse the beginning of the epoch's timestamp every time this statement runs.

### Describe the solution you'd like

The [Time](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#time) function to take in a float value with a passed in the format of something like `s`, `ms`, `s.ms`, or `s.ns`.

### Describe alternatives you've considered

Alternatively, there could be new functions that were the inverse of the [Unix Time functions](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#unixseconds).

**Comment by TylerHelmuth** [comment]
@Mrod1598 does https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27868 solve your issue?

**Comment by Mrod1598** [comment]
> @Mrod1598 does #27868 solve your issue?

Ah, yes sorry missed that one.
