### ISSUE TITLE
Filter out/reject traces with a single span with "and logic" based on an attribute

### ISSUE THREAD

**Issue by droonee** [open-telemetry/opentelemetry-collector-contrib#29093]
### Component(s)

processor/filter

### Is your feature request related to a problem? Please describe.

I am ingesting traces into a backend and processing trace data to control cost.

I have a few examples of traces that only contain a single span.  Span A will usually be nested in a full trace but sometimes will populate a unique trace with one span, i.e. Trace with only Span A.  I want to eliminate the occurrence of Span A when it is the only span in a trace but don't want to eliminate other traces with a single span - in this case, I will need to also be specific about the span based on an attribute, i.e. span name.

### Describe the solution you'd like

I'd like to reject traces with a single span that also contain a specific span name (or customer attibrute).

**Comment by crobert-1** [comment]
Hello @droonee, I believe this is actually a pretty involved request. The filter processor [filters traces](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/55a7d9df87ac01a2215f6d13cca4c4a30cf8838d/processor/filterprocessor/traces.go#L73) at the span level, with no context of the trace as a whole. This means we'd need to re-architect the scope of the filtering logic in the processor itself and make sure it's backwards compatible to existing filters.

Also, the filtering logic is done by [OTTL](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl) at the [span context level](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottlspan). The span context in OTTL only has span-level information available, not trace. So this **may** require a whole new trace context to be added to OTTL.

For context, I'll just share that there's another open request (#28875) to compare values across spans within the same trace, so multiple people are looking for functionality similar to this.

I'll defer to code owners for more information though. I'm not super familiar with the internal workings of these components so I may have even missed something obvious. I'm also aware this may get into much bigger architectural discussions that others would be much better suited for.

**Comment by TylerHelmuth** [comment]
@droonee, @crobert-1 is correct that the filterprocessor doesn't know about the state of a trace as a whole. I do believe you could do this with the tailsamplingprocessor. 

IF the name of the span is consistent, you could look for the parent span id to be nil to identify it as a root span. If your situation means that the solo span scenario is the root span, you could do this in the filterprocessor. 

`parent_span_id == nil and name == "something"`

**Comment by jiekun** [comment]
Hi. I feel like `span_count` tail sampling policy could help you.

It's easy to impl the following logic with tail sampling processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor
```go
    if span_name == "xxx" and span_count_in_a_trace == 1 {
            drop_the_trace
    }
```

I cannot write the whole config on phone but I believe that's not difficult for ya. Feel free to comment if you need further help.

**Comment by jpkrohling** [comment]
Agree, a combination of span_count and string_attribute should accomplish what's been requested.

**Comment by crobert-1** [comment]
@droonee Were you able to get this working? Is there anything left here or can we close the issue?

**Comment by jpkrohling** [comment]
I'm closing this, feel free to reopen if it's still a problem.
