### ISSUE TITLE
[question] Is there a way to load balance the exportation of telemetry data to multiple Clickhouse instances using the endpoint param `connection_open_strategy` in exporter/clickhouse?

### ISSUE THREAD

**Issue by ceevaaa** [open-telemetry/opentelemetry-collector-contrib#29155]
### Component(s)
exporter/clickhouse

## Description
Is there a way to balance the exportation load (client-side load balancing) to multiple Clickhouse DBs while using the exporter/clickhouse.

As explained in this [configuration](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/clickhouseexporter#configuration-options) here, will it be possible to use this [parameter](https://github.com/ClickHouse/clickhouse-go/blob/b2f9409ba1c7bb239a4f6553a6da347f3f5f1330/clickhouse_options.go#L260C14-L260C14) in the `endpoint` param to achieve the same ?

Something like this -
```
clickhouse:
    endpoint: http://addr1:port,addr2:port?connection_open_strategy=round_robin
    database: otel
```

Thanks & Regards
Shiva Pundir

### Collector version
v0.0.88

**Comment by crobert-1** [comment]
Hello @ceevaaa, from what I'm reading in the code this should be possible. 

All data types (logs, metrics, traces) go through the same call stack of [creating a ClickHouse client](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9de22efdd7ffef7c2de3a4ac2613d874ffcb7f3a/exporter/clickhouseexporter/exporter_logs.go#L201). The client will [use the endpoint](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9de22efdd7ffef7c2de3a4ac2613d874ffcb7f3a/exporter/clickhouseexporter/config.go#L70) provided in the config to [build a DSN](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9de22efdd7ffef7c2de3a4ac2613d874ffcb7f3a/exporter/clickhouseexporter/config.go#L113) and then open [the DB connection](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9de22efdd7ffef7c2de3a4ac2613d874ffcb7f3a/exporter/clickhouseexporter/config.go#L121). During the `buildDSN` method all parameters of the provided endpoint will be encoded into the DSN url. (The specified endpoint is [validated on startup](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9de22efdd7ffef7c2de3a4ac2613d874ffcb7f3a/exporter/clickhouseexporter/config.go#L62C27-L62C27) to make sure it can properly be parsed by ClickHouse).

I may be missing something here though, I don't have much experience with this component, so the code owners may have to correct me here. Have you been able to test it to see if it's working as expected?

**Comment by ceevaaa** [comment]
Hey @crobert-1, I tested this out today. And it worked well!
So as usual, thanks again for being the query solving superman. Cheers!

Regards 
Shiva Pundir
![3u04h5](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/36535845/2856f54b-d148-472f-91d3-7ee545660252)
