### ISSUE TITLE
[flaky test][receiver/jaegerreceiver/internal/jaegerreceiverdeprecated] TestPortsNotOpen: hard coded port already in use

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector-contrib#29276]
### Component(s)

receiver/jaeger/internal/jaegerreceiverdeprecated

### Describe the issue you're reporting

Many failures for this test at #28682

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6865022333/job/18668070125#step:6:351

```
--- FAIL: TestPortsNotOpen (0.00s)
    trace_receiver_test.go:129: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jaegerreceiver/internal/jaegerreceiverdeprecated/trace_receiver_test.go:129
        	Error:      	Received unexpected error:
        	            	listen tcp 127.0.0.1:14250: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
        	Test:       	TestPortsNotOpen
        	Messages:   	should have been able to listen on 14250.  jaeger receiver incorrectly started grpc
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver/internal/jaegerreceiverdeprecated	1.731s
```

**Comment by crobert-1** [comment]
Looks like a flaky test to me. The jaeger receiver [requires access to port 14250](https://www.jaegertracing.io/docs/next-release/getting-started/) from what I can tell, so the test itself is valid ensuring it can correctly connect to 14250. Also seems flaky as we don't have any other occurrences of this test failing.

I think it would make sense to update the test to add a check at the beginning to ensure the environment is not already using port 14250. Maybe skip the test if it's already in use?

**Comment by jpkrohling** [comment]
> Maybe skip the test if it's already in use?

I don't think this is the right solution: we might have the false impression that this test is running and passing. I'd rather try to gather as much information about the test owning the port as possible, and ensure that all tests are releasing the resources they allocate.
