### ISSUE TITLE
from_context values isn't passed in the headers_setter if pipeline contains batch process

### ISSUE THREAD

**Issue by romanvogman** [open-telemetry/opentelemetry-collector-contrib#29271]
## Description
Using the latest image 0.88.0, I've noticed that the limitation that was perviously mentioned [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/d50e094b89ff6b5db1ad84dc855d6901ef1b2fc7) was still happening - otel collector with batch process doesn't retrieve the header value passed in `from_context` section. Removing batch process from the pipeline resolves it.

## Steps to Reproduce
Add batch process to pipelines and a headers setter section with `from_conext` 
Example:

```
headers_setter config section:
    extensions:
      headers_setter:
        headers:
        - from_context: tenant_id
          key: X-Scope-OrgID
```

Headers sent:

```
POST /v1/traces HTTP/1.1
Host: localhost:4319
User-Agent: OTel-OTLP-Exporter-Python/1.20.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
tenant_id: foo
Content-Type: application/x-protobuf
Content-Length: 226 
```

Headers received:
```
POST /v1/traces HTTP/1.1
Host: ubuntu:4319
User-Agent: OpenTelemetry Collector Contrib/0.88.0 (linux/amd64)
Content-Length: 214
Content-Encoding: gzip
Content-Type: application/x-protobuf
X-Scope-Orgid:
Accept-Encoding: gzip
```

Removing batch process from the pipeline fixed this issue and X-Scope-Orgid header contains the expected value 

### Collector version

0.88.0

**Comment by crobert-1** [comment]
Hello @romanvogman, can you share the full configuration of the collector that you're using?

**Comment by jpkrohling** [comment]
@romanvogman, can you confirm you used `metadata_keys` with the batch processor?

**Comment by romanvogman** [comment]
Hey, 

Most of the configuration came as is from [otel-collector](https://github.com/open-telemetry/opentelemetry-helm-charts) helm chart
The batch processor is added from the default values.yaml, which we removed at this point to fix the headers_setter issue.
It's empty in the batch configuration, but is used in the pipeline section
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L100
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L141

Here's how it looks like when we apply it:
```
    processors:
      batch: {}

      pipelines:
        traces:
          exporters:
          - otlphttp
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888

Haven't found reference to `metadata_keys`

**Comment by jpkrohling** [comment]
Without that, the batch processor won't take the context into consideration, which explains what you are seeing. Please, take a look at the documentation for the batch processor, linked from @crobert-1's earlier comment:

https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor#batching-and-client-metadata

**Comment by romanvogman** [comment]
Thanks for your feedback @jpkrohling, but in our case batch processor isn't needed (at the moment), it just wasn't working correctly with the default configuration from helm chart which has `batch: {}`

wish is was easier to find though, would have saved me a good few hours debugging it :)
