### ISSUE TITLE
[receiver/hostmetrics] Support collecting process cgroup as dimension

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#29282]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

I would like to collect the cgroup associated with a process when collecting process information through the hostmetrics receiver.

### Describe the solution you'd like

The cgroup information should be offered as an additional dimension of the metric related to processes.

**Comment by atoulme** [comment]
Opening a PR to support collect cgroup info in gopsutil: https://github.com/shirou/gopsutil/pull/1552

**Comment by astencel-sumo** [comment]
I suppose it makes sense. Do you want to assign yourself to the issue?

**Comment by atoulme** [comment]
gopsutil turned down the enhancement of exposing cgroups, but we can probably perform this data capture in the receiver instead directly. I will turn my attention to that aspect.
