### ISSUE TITLE
[receiver/hostmetrics] Add braydonk as a code owner

### ISSUE THREAD

**Issue by braydonk** [open-telemetry/opentelemetry-collector-contrib#29287]
### Component(s)

receiver/hostmetrics

### Describe the issue you're reporting

I am proposing that I be added as a receiver/hostmetrics code owner. I have contributed to the component in the past, and am already part of the System Semantic Conventions working group. I am now able and intending to dedicate more time to contribute to the component and help with the existing issue queue.

CC @dmitryax, with whom I've already discussed joining the component as a codeowner.

**Comment by dmitryax** [comment]
I support 👍  @braydonk can you please submit a PR?
