### ISSUE TITLE
Max span attribute size limited

### ISSUE THREAD

**Issue by nmiculinic** [open-telemetry/opentelemetry-collector-contrib#29346]
### Is your feature request related to a problem? Please describe.

With tracing, user's can send arbitary large spans, with dozens of attributes, and span attribute values have unbounded size. This causes issues with downstream receivers (e.g. gRPC server-side max message limit), and beyond certain point data isn't really useful, and causing bloat in BE span storage. 

### Describe the solution you'd like

 I want to be able to set size limits to:

* total span size
* max attribute value size (and truncate if exceeding it)

This would be a processor processing spans and truncating too long attributes, whether it's resource attribute, span attribute, or span event attribute

**Comment by crobert-1** [comment]
Hello @nmiculinic, I believe this is possible using the `truncate_all` [function](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#truncate_all) of the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor).

Can you test this out and see if it works for your use case?

**Comment by nmiculinic** [comment]
Awesome, works like a charm :)
