### ISSUE TITLE
The  main branch of  opentelemetry-collector   does not contain the path  docs/performance.md 

### ISSUE THREAD

**Issue by jshawatsplunk** [open-telemetry/opentelemetry-collector-contrib#29341]
## Description
`main` branch of opentelemetry-collector does not contain the path  docs/performance.md. 
The repo https://github.com/open-telemetry/opentelemetry-collector-contrib displays a Performance link that is broken.

## Steps to Reproduce
Click on `Performance` in the repo README.md https://github.com/open-telemetry/opentelemetry-collector-contrib 

## Expected Result
Link works to performance considerations or sizing recommendations page. Perhaps: 
https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/monitoring.md

## Actual Result
404

### Collector version

v0.89.0

### Environment information

n/a

**Comment by JaredTan95** [comment]
as https://github.com/open-telemetry/opentelemetry-collector/commit/99a4825c15dd0c03e829d55eaeb9dc8a6e45f8e6 removed, I think we need to remove it here.
