### ISSUE TITLE
Publish tags for subdirectories with Go modules

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector-contrib#294]
See official documentation: https://github.com/golang/go/wiki/Modules#publishing-a-release (look for the ___prefix___ part specifically).

Currently we only tag root Go module, e.g. [v0.3.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.3.0)

According to Go modules documentation, for multi-module repos, we need to tag each module subdirectory separately, e.g. we should have a tag `exporter/stackdriverexporter/v0.3.0` for https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.3.0/exporter/stackdriverexporter/go.mod, and similarly for all other components.

Otherwise, when I add a dependency on `github.com/open-telemetry/opentelemetry-collector-contrib/exporter/stackdriverexporter`, I get the latest HEAD version by default, and have to pin a Git commit hash to override it with a commit matching `v0.3.0`, e.g. `v0.0.0-20200403235504-f41c7ec63bd0`.

Doing so manually is cumbersome, so there should be some automation script tagging all modules at once.

**Comment by owais** [comment]
Are you planning to work on this @nilebox? If not, I'll assign to myself.

**Comment by nilebox** [comment]
@owais I don't plan to work on this, but happy to review.

**Comment by nilebox** [comment]
Might be useful as an example for automation script: https://github.com/open-telemetry/opentelemetry-go/blob/ba0203a2084e97ba7daaeec7ae1da255db031f52/tag.sh#L76-L82
