### ISSUE TITLE
HTTP Request Server Span semantic convention seems broken?

### ISSUE THREAD

**Issue by sncariad** [open-telemetry/opentelemetry-collector-contrib#29423]
### Component(s)

exporter/azuremonitor

### Describe the issue you're reporting

[Semantic Conventions for HTTP Spans #Status](https://github.com/open-telemetry/semantic-conventions/blob/126059d99dc29fd9a59893091f56500d4b9674b7/docs/http/http-spans.md?plain=1#L98C1-L99C57) states the following:

> _For HTTP status codes in the 4xx range span status MUST be left unset in case of SpanKind.SERVER and MUST be set to Error in case of SpanKind.CLIENT._

However Azure Monitor Exporter does not consider SpanKind when setting Success=false/true. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/103eb7b60b3d0ce11e06a5e834f148f804e972b9/exporter/azuremonitorexporter/trace_to_envelope.go#L698-L702

So in Log Analytics workspace, trace table all activities of Kind=Server with 404 gets Success=false. I believe it is incorrect and the code should consider SpanKind when deciding success or failure.

## Expected Result

As per Semantic Convention for HTTP Span, when trace is of Server Kind, the 400 status codes are considered successful.

## Actual Result
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/148149940/2ca6f00d-5c1a-4b01-b7d9-7997e37d5052)

**Comment by crobert-1** [comment]
Hello @sncariad, thanks for filing and including the references! I believe there's currently some level of ambiguity before this can be declared a bug or not. It seems like we're currently dealing with an issue of deciding the correct way to convert data from pdata to the format AppInsights uses.

As you're showing, the `data.ResultCode` variable is initially being set to the span's status code, which will be [0, 1, or 2](https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/ptrace/status_code.go#L15-L17). However, later on in the same call stack, this same `data.ResultCode` is being set to the HTTP status.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/103eb7b60b3d0ce11e06a5e834f148f804e972b9/exporter/azuremonitorexporter/trace_to_envelope.go#L368

Note the comment on the `RemoteDependencyData.ResultCode` member that's being set here:
```
	// Result code of a dependency call. Examples are SQL error code and HTTP
	// status code.
	ResultCode string `json:"resultCode"`
``` 

So I believe the first question that needs answered here is whether the RemoteDependencyData struct's `ResultCode` [member](https://github.com/microsoft/ApplicationInsights-Go/blob/9194eea52d6fe5313a2b109056254baca9ab3194/appinsights/contracts/remotedependencydata.go#L21-L23) should be the span status, or HTTP status code? @pcwiese Do you have a thought here?

I realize that maybe a check should be added just in case in the method you've referenced, but no matter what value it's set to (or not set to) it will be overwritten in the current call stack you're hitting.

**Comment by rajkumar-rangaraj** [comment]
@sncariad This behavior is intentional. The Azure Monitor Exporter sets the status field to `false` when the HTTP status code exceeds 400. This approach differs from Semantic Conventions but is consistent with Azure Monitor’s practices. You can refer to a .NET implementation for more details - 

https://github.com/Azure/azure-sdk-for-net/blob/bed75c756d48bb742254ba83b4c4536ad2e0cd56/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Customizations/Models/RequestData.cs#L60

**Comment by crobert-1** [comment]
Thanks for the help here @rajkumar-rangaraj! It looks like by setting the value by default lines up with Azure's expectations, and works as a placeholder in case it isn't set again later in the call stack.

Please let us know if you have any other questions @sncariad, I'm going to close for now.

**Comment by bunkrur** [comment]
> @sncariad This behavior is intentional. The Azure Monitor Exporter sets the status field to `false` when the HTTP status code exceeds 400. This approach differs from Semantic Conventions but is consistent with Azure Monitor’s practices. You can refer to a .NET implementation for more**** details - 
> 
> 
> 
> https://github.com/Azure/azure-sdk-for-net/blob/bed75c756d48bb742254ba83b4c4536ad2e0cd56/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Customizations/Models/RequestData.cs#L60

Can you confirm the same for the scenario where we export via otlp to a collector and then into azure monitor via the golang azure monitor exporter?

Previously it was possible to override the success/failure within Azure App Insights SDK to allow 404s to be seen as successes. I've written a processor within a dotnet otel extension to try and recreate this functionality but are you saying that app insights will swap any client error to failure in otel regardless? @

**Comment by sncariad** [comment]
> @sncariad This behavior is intentional. The Azure Monitor Exporter sets the status field to `false` when the HTTP status code exceeds 400. This approach differs from Semantic Conventions but is consistent with Azure Monitor’s practices. You can refer to a .NET implementation for more details -
> 
> https://github.com/Azure/azure-sdk-for-net/blob/bed75c756d48bb742254ba83b4c4536ad2e0cd56/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Customizations/Models/RequestData.cs#L60

Thanks for response and sharing the reference to .net version of exporter which does same as go version. But to my understanding; in either case they don't follow Semantic Conventions where they ignore to check if it is Request trace and not Dependency before considering Status to be Success or Failure for http status codes above 400.

**Comment by crobert-1** [comment]
From @sncariad:
> But to my understanding; in either case they don't follow Semantic Conventions where they ignore to check if it is Request trace and not Dependency before considering Status to be Success or Failure for http status codes above 400.

The Semantic Conventions referenced apply only to the OpenTelemetry data format. In the code here, data is being converted to the format used by AppInsights. What we're saying here is that the Semantic Conventions are not relevant once converted to this other format, since it's no longer within the OpenTelemetry realm.

If data was being exported using OTLP, then your point would be correct, the status code would need to be set to the values you're expecting. However, since it's being exported in this ApplicationInsights format, it follows different conventions.

Please let me know if I've misunderstood your comment here.
