### ISSUE TITLE
Adding support for Kafka partition key (based on OTEL attribute value)

### ISSUE THREAD

**Issue by nirb-s1** [open-telemetry/opentelemetry-collector-contrib#29433]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

Currently the kafka exporter doesn't provide a way to define a partition key at all which means that messages aren't orders in kafka topic if topic includes multiple partitions.

If also means that if metrics are re-send due to timeouts, we are required to handle duplications on consumer side instead of using kafka compaction on topic option which is also based on partition key.

### Describe the solution you'd like

Define in kafka exporter configuration an attribute that will be used as partition key, if not set use the existing default behaviour.

Example:
Use attribute os.hostname as partition key, than all metrics of same hostname will arrive to same consumer eventually.

### Describe alternatives you've considered

Without such capabilities, we are required to build dedup capabilities on consumer side

**Comment by crobert-1** [comment]
Hello @nirb-s1, from my understanding this sounds like a valid request. 

The exporter is currently relying on the sarama package, [which exposes this option](https://github.com/IBM/sarama/blob/d09a287f30bdf73b1c9f53c3f7a4b2ecc2bd41d3/async_producer.go#L157). We'd simply add the specified partition [when marshalling messages](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4beb5c119b858a0e8f34d384b24b350c67ee54f0/exporter/kafkaexporter/pdata_marshaler.go#L23C19-L23C19).

I don't have enough context to be able to answer to how to handle failures, so I'll have to defer to others there. I also don't have a lot of kafka experience in general, so the code owners may overrule what I've said here in case I've misunderstood something.

**Comment by VihasMakwana** [comment]
I'll have a crack at this. Will open up a PR soon.

**Comment by nirb-s1** [comment]
btw, another idea / ask from this feature is to be able to use the metric timestamp in the partition key somehow so we can use Kafka topic compaction

**Comment by nirb-s1** [comment]
@VihasMakwana thanks for jumping on this, I see that it will be auto closed if no one will work on it, did you had a chance to check it?

**Comment by VihasMakwana** [comment]
Hi, sorry about it.
I got busy with some other stuff at work.
Will work on it to finish what I started

**Comment by michpev** [comment]
A question about this issue. The new attribute partition_metrics_by_resource_attributes still does not allow to select a specific way of determining keys, it will instead create a hash based on the resource attributes. Are there plans to add the ability to define the exact way in which the key will be derived from the message (like in the example provided in the original ask, with "os.hostname")?

The reason I need it is that in the project I'm working on, there is one place that receives info about some objects from various different sources (some of them don't use otel at all, though the ones that don't use sarama directly) and then does stuff based on the information it receives. However, that one place needs to be scaled into several pods, and each pod will have a consumer in a consumer group. We want to make sure that all messages about the same object will come to the same pod. So we wanted all places to send their messages with the key of the object's name (a unique identifier), and then they would all go into the same partition (sarama's default partitioner is a deterministic hash based on the key). But the current implementation doesn't allow for that.
