### ISSUE TITLE
[pkg/ottl] Allow indexing any slice type

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#29441]
I was just shown the scenario 

`set(resource.attributes["my.environment.2"], Split(resource.attributes["host.name"],"-")[1])`

that produces an error:

```
{"kind": "processor", "name": "transform", "pipeline": "logs", "error": "type, []string, does not support int indexing", "statement": "set(resource.attributes[\"my.environment.2\"], Split(resource.attributes[\"host.name\"],\"-\")[1])"}
```

Although the language does support indexing the return value of the Converter, it only supports indexing `pcommon.Slice` and `[]any`, but `Split` returns a `[]string`. We need to make indexing slices more generic.  This might need to be its own issue. Related code: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/60430e1f4c2bdb8579fc080d5f3a6c8f15730a4b/pkg/ottl/expression.go#L98-L112

_Originally posted by @TylerHelmuth in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26108#issuecomment-1821560835_

**Comment by SplitThePotCyrus** [comment]
Yes please, fix for this would be great. 

I've been trying to figure out this issue for a half a day, until I found this just now. 😓
Now I have to figure out how to accomplish what I need in a different way.

**Comment by evan-bradley** [comment]
At a minimum, we should achieve type coverage for all types that OTTL supports. If possible, a generic solution would be nice, assuming we can do this with either reflection or some creative type casting.

**Comment by evan-bradley** [comment]
#35581 only added support for string slices, we still need support for slices of types that OTTL supports.

**Comment by znd4** [comment]
I'd like to work on this

**Comment by znd4** [comment]
should that be `[][]byte`?

**Comment by znd4** [comment]
Also, no need to support int32?

**Comment by TylerHelmuth** [comment]
@znd4 no need to support `int32`, OTTL uses `int64` and `float64` exclusively for ints and floats.
