### ISSUE TITLE
[question] receiver/redis works for KeyDB also?

### ISSUE THREAD

**Issue by ceevaaa** [open-telemetry/opentelemetry-collector-contrib#29457]
### Component(s)
receiver/redis

### Question
Can the Redis receiver also fetch metrics for KeyDB, as KeyDB is a fork of Redis and uses the same "INFO" command ?

### Answer
I tested it. And voila, it works.
So my question is, was this intentional/planned OR just a happy coincidental usecase ?

Regards

### Collector version
v0.89.0

**Comment by crobert-1** [comment]
I did a quick search and didn't see any reference to `KeyDB` in the history of this component, so my guess would be that it was not planned. I'll leave it open for the code owners though in case they want to provide more information here.

**Comment by atoulme** [comment]
Closing as complete.
