### ISSUE TITLE
[exporter/awsemf] Add StorageResolution config to support high-resolution metrics

### ISSUE THREAD

**Issue by bviolier** [open-telemetry/opentelemetry-collector-contrib#29506]
### Component(s)

exporter/awsemf

### Is your feature request related to a problem? Please describe.

We want to be able to push high-resolution metrics from the opentelemetry-collector. This means that we should be able to set StorageResolution to 1.

### Describe the solution you'd like

Have the option in the AWSEMF config to turn on high-resolution metrics through the StorageResolution config.

### Describe alternatives you've considered

There doesn't seem to be another way of doing this, except for creating a new exporter that uses either this setting, or directly uses [PutMetricData](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html), which would mean a completely new exporter.

### Additional context

I will be creating a PR soon.

**Comment by bryan-aguilar** [comment]
More information on storage resolution can be found [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html) for anyone interested. 

@bviolier what is your idea for the configuration changes necessary to support this? We would need to be able to specify metrics by their name and then give them an associated storage resolution right?

I could see how this could be a useful feature but understanding the configuration required for it first would be a good start.

**Comment by bviolier** [comment]
Thanks for the quick reply @bryan-aguilar. I created a [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29507) for it. I chose to put it at the same level as things like `dimension_rollup_option` and `log_retention` as that seemed like things on the same configuration level. 

Also, I am assuming (as was done before, I believe) that people can create multiple exporters if they want different settings for different metrics.

If you think it should look different, let me know. I'll try to devise a different way of setting this configuration value.

**Comment by bryan-aguilar** [comment]
I had thought about how we could adopt storage resolution in the past and I thought that having a global `storageresolution` option would lead to more user pain. With a global storage resolution flag like what was proposed in the PR, users would have to configure a high and low storage resolution pipeline in their collector config. Then, users would have to drop high resolution metrics from the low resolution pipelines and vise versa. Is my understanding here correct? If you did not drop you could end up with duplicated metrics right? 

I think it would behoove us to consider other options for this. Here are two thoughts that come to mind
1. A configuration option where you can supply a list of metric name which will have high storage resolution applied. A list of regex strings should be accepted.
```
awsemf:
  high_resolution: 
    - metric_name_foo
    - metric_name_bar_selector*
```

2. We could also look for a high resolution, or storage resolution, attribute. If it is set then we would add the high or low storage resolution to the metric. The benefit of this is that this could be done at the collector level using available processors, and would require no configuration change, or at the point at which the metric is generated. The downside would be that relying on a metric attributing name starts to move into the territory of semantic conventions and we may want to consider ironing the naming first.

**Comment by bviolier** [comment]
I think doing an attribute might get hairy pretty quickly indeed. It does give you the power on the client to force specific metrics into high-resolution, but in our case, we specifically wouldn't want the client to have that power (that being said, that can easily be fixed with filters also).

The `high-resolution` attribute with a list seems like a good option, but I didn't think that would be acceptable as the value on AWS is 1/60 (and specifically not true/false). And I assumed there was a reason behind it (to maybe add more values in the future?).

**Comment by bryan-aguilar** [comment]
> The other option I can think of is making it part of metric_declarations with as a new attribute called storage_resolution, that gives you the freedom to define it for every metric you want.

Putting it as part of metric declarations may be a good idea also. It may be even more appropriate then my suggestion also. Putting it within the metric declarations object would give more flexibility.

> The downside is that it does force you to define the metrics in metric_declarations if you want to use the storage_resolution.

Agreed, but I think this is an acceptable tradeoff when comparing the user experience of a top level `storageresolution` configuration option. 


> I think doing an attribute might get hairy pretty quickly indeed. It does give you the power on the client to force specific metrics into high-resolution, but in our case, we specifically wouldn't want the client to have that power (that being said, that can easily be fixed with filters also)

I think it's fine to strike that idea, especially if it does not fit your use case. I have not heard a request for this either and was just throwing out ideas. The good thing is that this can always be added in the future if we do get a feature request for this functionality. 


> I didn't think that would be acceptable as the value on AWS is 1 or 60 (and specifically not true/false). And I assumed there was a reason behind it (to add more values in the future maybe?).

This is a good call out and I don't know the exact reasoning for that. I can see if I can find out though. We shouldn't back ourselves into a corner right away if there's the chance that there could be additional values in the future.

**Comment by bviolier** [comment]
I am up for updating the PR with either the array option (assuming true/false is ok) or going the `metric_declarations` way! Let me know what you think will be the best option.

On our side, we are now testing this on sandbox (with the current PR) and our Alarm for auto-scaling ECS containers went from 220+ seconds to between 40 and 50 seconds after load increase.

**Comment by bviolier** [comment]
The Metrics Descriptor is interesting indeed! I was thinking though that the metric-directive also gives you the option to store the same metric in different resolutions when using different dimensions - which is also an interesting case.

Just let me know when you have come to a conclusion and I will pick this up again. No hurry from my side, as we can already use it by building our own collector.

**Comment by bviolier** [comment]
I did a first pass for moving the storage resolution. Please let me know what you think, I had to dive deep a bit for the declaration to work, but I got something working. Open to improve, of course.

I didn't test it locally, but I updated the tests.

**Comment by bviolier** [comment]
@bryan-aguilar it seems the PR has been closed due to inactivity. Do you know when you have some time to review and get this merged? Thanks!

**Comment by zehsor** [comment]
@bryan-aguilar  any updates on this? I'd love to help if there's anything needed, we're desperate for this functionality!

**Comment by zehsor** [comment]
@Aneurysm9 @shaochengwang @mxiamxia @bryan-aguilar
any updates on this?

**Comment by zehsor** [comment]
@Aneurysm9 @shaochengwang @mxiamxia @bryan-aguilar
it feel like this is not maintained anymore at all after not receiving any answer for almost half a year..

**Comment by jpbarto** [comment]
@bryan-aguilar this feature is still needed by users of opentelemetry. Is there any update on its implementation?
