### ISSUE TITLE
Enhance Logging for PrometheusRemoteWrite Exporter

### ISSUE THREAD

**Issue by meijeran** [open-telemetry/opentelemetry-collector-contrib#29547]
### Component(s)

exporter/prometheusremotewrite

### Describe the issue you're reporting

I've recently been working with the PrometheusRemoteWrite exporter and encountered a notable lack of logging output. This absence of detailed logs makes it difficult to understand what the exporter is doing, particularly in scenarios where things might be going wrong or when verifying successful operations.

I have already created a merge request aimed at addressing this issue by introducing enhanced logging. This addition will ensure users can track the exporter's activities and troubleshoot more efficiently.

**Comment by crobert-1** [comment]
I see no problem with this request. One thing we want to avoid is log spam, so we want to set most messages to the `debug` level. Thanks for submitting a PR as well!

**Comment by monoxono** [comment]
I'd like to see errors in logs like previous versions otherwise it's very difficult to understand why metrics sending failed, I created #30271.
