### ISSUE TITLE
[CI] opentelemetry-collector-contrib builds linux/arm64 binary with wrong arm version

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#29542]
### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7021964134/job/19105712226 as example.

It runs: 
```
make GOOS=linux GOARCH=arm64 GOARM=7 otelcontribcol
```

It should run:
```
make GOOS=linux GOARCH=arm64 GOARM=8 otelcontribcol
```

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
I believe this is coming from [here.](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4beb5c119b858a0e8f34d384b24b350c67ee54f0/.github/workflows/build-and-test.yml#L406-L409) Blame shows it was [updated to version 7 a few months ago here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23436).

Can you provide more context as to why it should be 8 instead? From [documentation](https://pkg.go.dev/cmd/go#hdr-Environment_variables) it looks like 8 isn't a valid value, unless I'm missing something.

**Comment by crobert-1** [comment]
Good point, it looks like when `GOARCH=arm64` we need to leave `GOARM` unset. [Official source.](https://github.com/golang/go/wiki/GoArm#supported-architectures)

**Comment by mowies** [comment]
I think this is basically almost a typo. The PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23436 tried to add a single matrix entry to the `cross-compile` job, but accidentally added three:
```yaml
- os: linux
- arch: arm
- arm: 7
```

This should have been:
```yaml
- os: linux
  arch: arm
  arm: 7
```


I will file a PR to fix that.
If you could assign the issue to me, that would be great :)

**Comment by mowies** [comment]
Since this is an older issue, I'll ping @crobert-1 here :)
