### ISSUE TITLE
Add additional metric to Mysql receiver

### ISSUE THREAD

**Issue by samiura** [open-telemetry/opentelemetry-collector-contrib#29545]
### Component(s)

receiver/mysql

### Is your feature request related to a problem? Please describe.

When monitoring a MySQL database, few useful metrics are the number of  qcache hits, qcache not cached, number of queries in qcache in each database. Prior to Mysql 5.7.20 qcache metrics are used hence the need for these metrics

### Describe the solution you'd like

The mysql receiver already queries global status variables  information. I would add the three additional metrics to the list

**Comment by samiura** [comment]
@djaglowski yes correct.

**Comment by djaglowski** [comment]
@samiura, 5.7 was recently deprecated and we claim support for 8.0+, so I think we shouldn't add these metrics.

The sqlquery receiver should be able to handle these though, so I'd recommend using that instead. It might be worth adding an example configuration [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples).

**Comment by atoulme** [comment]
Closing this issue as not planned as the enhancement was rejected as MySQL 5.7 is not supported.
