### ISSUE TITLE
[exporter/splunkhec] Do not allow nil event values when exporting

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#29551]
## Description
We see errors when sending HEC events with an event field set to a null value. We should always replace nil with an empty string to work around this limitation.

### Collector version

0.89.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
_Removing `needs triage` as a PR has been opened by the code owner that resolves this issue._
