### ISSUE TITLE
service.name is not mapping to service anymore

### ISSUE THREAD

**Issue by daianmartinho** [open-telemetry/opentelemetry-collector-contrib#29561]
### Component(s)

exporter/datadog

### What happened?

service.name is not mapping to service anymore after upgrading from v0.82.0 to v0.83.0.
The problem persist in the latest version v0.90.0.

## Description

The problem is that we can't filter by service on Datadog, and logs are also not correlated with traces.

![Captura de tela de 2023-11-29 10-23-35](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/8451484/cf6d108b-504f-4f3b-9d21-d0660ba7f797)

Seems that this change is related to #24674, where we bump the opentelemetry-mapping-go version from v0.5.2 to v0.6.0.
Looking for changes between these versions, i found [this PR](https://github.com/DataDog/opentelemetry-mapping-go/pull/138)  that was merged at v0.5.5.

## Steps to Reproduce

publish this payload to opentelemetry collector at versions 0.82.0 and 0.83.0, with datadog exporter.

```{
    "resource_logs": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "service.name",
                        "value": {
                            "string_value": "otlp-test"
                        }
                    },
                    {
                        "key": "service.namespace",
                        "value": {
                            "string_value": "foundation"
                        }
                    },
                    {
                        "key": "host.name",
                        "value": {
                            "string_value": "my-machine-name"
                        }
                    },
                    {
                        "key": "service.version",
                        "value": {
                            "string_value": "1.0.0"
                        }
                    },
                    {
                        "key": "deployment.environment",
                        "value": {
                            "string_value": "local"
                        }
                    }
                ]
            },
            "scope_logs": [
                {
                    "scope": {
                        "name": "otlp_log_ingestion"
                    },
                    "log_records": [
                        {
                            "body": {
                                "string_value": "This is the body message."
                            },
                            "time_unix_nano": "{{timestamp}}",
                            "observed_time_unix_nano": "{{timestamp}}",
                            "severity_text": "ERROR",
                            "severity_number": 17
                        }
                    ]
                }
            ]
        }
    ]
}```

## Expected Result

Datadog service mapped with the value from service.name.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/8451484/462fbf93-4366-4621-aa13-11ddaceaf76a)

## Actual Result

Datadog `service` is mapped with the value of `service`, an dictionary.
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/8451484/6dcf960f-54dd-448b-91be-e8e919963a33)



### Collector version

v0.90.0

### Environment information

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")


### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

**Comment by karmingc** [comment]
I recently dealt with this, there's a section that talks about it here: https://docs.datadoghq.com/opentelemetry/otel_collector_datadog_exporter/?tab=onahost#remap-otels-servicename-attribute-to-service-for-logs.

the README includes this link but adding in the example or the README would be beneficial as well IMO.

**Comment by daianmartinho** [comment]
thank you @karmingc, we will use this as workaround.. 

as we use the opentelemetry-mapping-go to do the mapping from otlp to datadog, we should expect it to do the job, wright?
seems that this change broke the contract :/

we should add something to the datadog exporter or move the discussion to opentelemetry-mapping-go?

**Comment by songy23** [comment]
Thanks for raising this - I copied the note to README in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29645.

This is due to a constraint in our dependency HTTP log client. We are currently doing migration to use the Datadog logs agent to submit logs instead. Once that is done, the workaround should no longer be needed.
