### ISSUE TITLE
Dropping Metrics in Datadog Exporter

### ISSUE THREAD

**Issue by TRAD-Anthony-CKO** [open-telemetry/opentelemetry-collector-contrib#29585]
### Component(s)

exporter/datadog

### Is your feature request related to a problem? Please describe.

Multiple applications are usually pushed to the same central OTEL collector. I am trying to drop certain metrics via a name match so they would be ignored and not sent to Datadog. 

I would ask the same question as well for tags, I want to drop certain high cardinality tags if I see them on ANY (or regex) metric name.

Reading the docs, I don't think this is possible today.  

### Describe the solution you'd like

* An action to drop certain metrics based on a metric's name regex match in the OTEL Collector yml.
* An action to drop tags via exact name matches in the OTEL Collector yml.

### Describe alternatives you've considered

Tried to use the [Metric Transform](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor) and [Attribute Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor) but doesn't seem possible as well.

**Comment by liustanley** [comment]
Hi @TRAD-Anthony-CKO, this behavior of dropping metrics would be better suited in a processor as opposed to an exporter.   The [filter processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#dropping-metrics-with-invalid-type) should work for this use case, and the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) may work for this as well.

**Comment by TRAD-Anthony-CKO** [comment]
Hi @liustanley, thanks for taking the time to respond!

Noted, the filter processor should have those as I saw from the docs. Closing the issue!
