### ISSUE TITLE
Auto append Service Name to Metric Name

### ISSUE THREAD

**Issue by TRAD-Anthony-CKO** [open-telemetry/opentelemetry-collector-contrib#29586]
### Component(s)

exporter/datadog

### Is your feature request related to a problem? Please describe.

Changing a Metric's Type in Datadog is a very serious breaking change where the existing ingested data points will be deleted. 

With that in mind, I want to be able to append the service_name to the metric name on publish so that each metric is localized to a certain service. I know that this is usually done on the `processor` side, but I don't see that in the [metric transform](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor) processor. It only allows appending static values as a prefix and not values coming from attributes.

### Describe the solution you'd like

Should be done on the processor, so only requesting a general guideline on how to approach this. 

Otherwise a flag that does that on the Exporter would solve the issue.

### Describe alternatives you've considered

[Processors](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor)

**Comment by mx-psi** [comment]
I think you should be able to do this with https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor

**Comment by TRAD-Anthony-CKO** [comment]
Thanks for taking the time to respond. I'll try and close the issue.
