### ISSUE TITLE
New component: Sumo Logic Extension

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#29601]
### The purpose and use-cases of the new component

Code: https://github.com/SumoLogic/sumologic-otel-collector/tree/main/pkg/extension/sumologicextension

This extension is to be used as part of Sumo Logic collector in conjuction with Sumo Logic Exporter in order to export telemetry data to [Sumo Logic](https://www.sumologic.com/).

It manages:

- authentication (passing the provided credentials to sumologicexporter when configured as extension in the same service)
- registration (storing the registration info locally after successful registration for later use)
- heartbeats

### Example configuration for the component

- `installation_token`: (required) collector installation token for the Sumo Logic service, see
  [help][credentials_help] for more details
- `collector_name`: name that will be used for registration; by default the hostname is used. In the event of a conflict, a timestamp will be appended to the name. See [here][clobber] for more information.
- `collector_description`: collector description that will be used for registration
- `collector_category`: collector category that will be used for registration
- `collector_fields`: a map of key value pairs that will be used as collector
  fields that will be used for registration.
  For more information on this subject please visit [this help document][fields_help]
- `discover_collector_tags`: defines whether to auto-discover collector metadata
  tags (for local services, e.g. mysql) (default: `true`)

  **NOTE**: collector metadata tag auto-discovery is an alpha feature.
- `api_base_url`: base API URL that will be used for creating API requests,
  see [API URLs](#api-urls) details
  (default: `https://open-collectors.sumologic.com`)
- `heartbeat_interval`: interval that will be used for sending heartbeats
  (default: `15s`)
- `collector_credentials_directory`: directory where state files with registration
  info will be stored after successful collector registration
  (default: `$HOME/.sumologic-otel-collector`)
- `clobber`: defines whether to delete any existing collector with the same name. See [here][clobber] for more information.
- `force_registration`: defines whether to force registration every time the
  collector starts.
  This will cause the collector to not look at the locally stored credentials
  and to always reach out to API to register itself. (default: `false`)

  **NOTE**: if clobber is unset (default) then setting this to true will create
  a new collector (with new unique name) on Sumo UI on every collector start
  and create a new one upon registration.
- `ephemeral`: defines whether the collector will be deleted after 12 hours
  of inactivity (default: `false`)
- `time_zone`: defines the time zone of the collector. For a list of all possible
  values, refer to the `TZ database name` or `Time zone abbreviation` columns in
  https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
- `backoff`: defines backoff mechanism for retry in case of failed registration.
  [Exponential algorithm](https://pkg.go.dev/github.com/cenkalti/backoff/v4#ExponentialBackOff) is being used.
  - `initial_interval` - initial interval of backoff (default: `500ms`)
  - `max_interval` - maximum interval of backoff (default: `1m`)
  - `max_elapsed_time` - time after which registration fails definitely (default: `15m`)

[credentials_help]: https://help.sumologic.com/docs/manage/security/installation-tokens
[fields_help]: https://help.sumologic.com/docs/manage/fields
[clobber]: https://help.sumologic.com/docs/send-data/installed-collectors/collector-installation-reference/force-collectors-name-clobber/

```
extensions:
  sumologic:
    installation_token: <token>
    collector_name: my_collector
    time_zone: CET

receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      load:

processors:

exporters:
  sumologic:
    auth:
      authenticator: sumologic # Specify the name of the authenticator extension

service:
  extensions: [sumologic]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: []
      exporters: [sumologic]
```

### Telemetry data types supported

- logs
- metrics
- traces

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@sumo-drosiek

### Sponsor (optional)

@astencel-sumo 

### Additional context

This extensions works in conjuction with Sumo Logic Exporter, however exporter in this repository is in very old version and is not supported

We decided to go with the extension first, as it doesn't require exporter to work, but exporter in new version requires this extension by default

**Comment by astencel-sumo** [comment]
I'm happy to sponsor this component.

It's been used in the [Sumo Logic distro](https://github.com/SumoLogic/sumologic-otel-collector/) for probably more than two years now. The component is crucial for users to easily send data to Sumo Logic by just providing the Sumo [Installation Token](https://help.sumologic.com/docs/manage/security/installation-tokens/) in the extension's configuration.

**Comment by sumo-drosiek** [comment]
cc: @SumoLogic/open-source-collection-team

**Comment by sumo-drosiek** [comment]
It is active: #31031
