### ISSUE TITLE
Service graph - exponential histogram support 

### ISSUE THREAD

**Issue by 0x006EA1E5** [open-telemetry/opentelemetry-collector-contrib#29628]
### Component(s)

connector/servicegraph, processor/servicegraph

### Is your feature request related to a problem? Please describe.

Current use of "traditional" histograms creates many timeseries, which is prohibitively expensive (in our org).

### Describe the solution you'd like

Config option to use exponential histogram, similar to span metrics connector.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/spanmetricsconnector/README.md#L92

### Additional context

As mentioned above, this config option is available for span metrics
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/spanmetricsconnector/README.md#L92

**Comment by JaredTan95** [comment]
make sense. @0x006EA1E5  If you do not have time to contribute and to enhance, I will make time to finish this.
