### ISSUE TITLE
Collect data from sidecars

### ISSUE THREAD

**Issue by tzneal** [open-telemetry/opentelemetry-collector-contrib#29623]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

The Sidecars feature is enabled by default in Kubernetes 1.29 (https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/). This receiver (and maybe more) should be updated to support them.

### Describe the solution you'd like

[This](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d7b940b7c3feacf7c8d39fb1f7466edc7e25e373/receiver/k8sclusterreceiver/internal/pod/pods.go#L83C1-L83C1) code only reports metrics from from containers in the pod. Sidecars are an init container with a restart policy of Always and run for the lifetime of the pod, so they should probably be reported here as well.

**Comment by bryan-aguilar** [comment]
I believe this could affect any component which collects pod request metrics. Such as https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awscontainerinsightreceiver
