### ISSUE TITLE
Update to latest semantic conventions

### ISSUE THREAD

**Issue by stonkie** [open-telemetry/opentelemetry-collector-contrib#29687]
## Description

Semantic conventions have settled on a slightly different set of properties for HTTP clients than those implemented : https://github.com/open-telemetry/semantic-conventions/blob/v1.23.0/docs/http/http-spans.md#http-client

The main one is using http.url instead of url.full. http.response.status_code should also be used instead of http.status_code

When used with the latest OpenTelemetry.Instrumentation.Http 1.6.0-rc.1 (see this change : https://github.com/open-telemetry/opentelemetry-dotnet/pull/5068), the AppInsight integration is quite bare.

The logic here would need to be updated to take url.full into account : https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/azuremonitorexporter/trace_to_envelope.go

## Steps to Reproduce

Instrumented dotnet application with OpenTelemetry.Instrumentation.Http 1.6.0-rc.1 and a collector using the azuremonitorexporter.

## Expected Result

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/4596002/6c31ff47-48c8-47e7-b55a-db0555ca4609)

## Actual Result

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/4596002/5f68af24-9cca-41d7-87e0-c8b3d4fcedc9)

### Collector version

'otel/opentelemetry-collector-contrib:0.90.1'

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by aygalinc** [comment]
I open an MR on repository collector to generate appropriate specification file : https://github.com/open-telemetry/opentelemetry-collector/pull/9593

**Comment by kamilzzz** [comment]
Is there any update on this?

**Comment by codeboten** [comment]
The correct semantic convention attributes are available in the [v1.25.0](https://pkg.go.dev/go.opentelemetry.io/collector/semconv/v1.25.0) of the semconv package so making this change should be unblocked
