### ISSUE TITLE
[receiver/purefa] Purefa Receiver implementation for logs telemetry

### ISSUE THREAD

**Issue by dgoscn** [open-telemetry/opentelemetry-collector-contrib#29709]
### Component(s)

receiver/purefa

### Is your feature request related to a problem? Please describe.

The Pure Storage FlashArray Receiver supports only **metrics** telemetry and is necessary for the implementation of logs telemetry to collect **health & alerts data** and **audit data**.

### Describe the solution you'd like

The current receiver should include support for logs.

### Additional context

cc @chrroberts-pure @jpkrohling

**Comment by crobert-1** [comment]
@dgoscn Do you have a description or link on how to collect logs from a Pure Storage FlashArray? No worries if not, functionality can be discussed in a PR.

_Removed `needs triage` as the code owner and original implementer is the one who submitted this enhancement._
