### ISSUE TITLE
[exporter/logzioexporter] Logzio exporter is unmaintained

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29719]
### Component(s)

exporter/logzio

### Describe the issue you're reporting

The logzio exporter is unmaintained.

If no OpenTelemetry member steps up, this component will be eventually deprecated and removed from the repository.

Please comment on this issue to volunteer, and open a PR to add yourself to the component maintainers.

- [ ] On June 8th, 6 months from now, the component will be removed

https://github.com/open-telemetry/opentelemetry-collector#unmaintained

Issues/PRs that have not had responses

- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20768
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23390

**Comment by yotamloe** [comment]
Hey @codeboten I'm actively responsible for this component from the logz.io side, and I will be happy to be a maintainer of this component from the open telemetry side too (I'm a community member)

**Comment by yotamloe** [comment]
@codeboten How can I apply to be a maintainer of the `logzioexporter` component?

**Comment by tamir-michaeli** [comment]
@codeboten Im also actively responsible for this component from the logz.io side, i opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20768 many months ago and requested multiple times reviews after the requested changes, with no response.

**Comment by codeboten** [comment]
@yotamloe thanks for reaching out! you're already listed as code owner, if you could take a look at the two linked issues/PRs. After looking at those, if you could open a PR to change the status from unmaintained, that would be great.

@tamir-michaeli thanks for the note, if you can get a review from a code owner, that will usually get things moving more quickly!

**Comment by yotamloe** [comment]
Hey @codeboten now that #20768 is merged, can we close this issue? or anything else needed from my side?

**Comment by yotamloe** [comment]
> Hey @codeboten now that #20768 is merged, can we close this issue? or anything else needed from my side?

Hey checking again @codeboten

**Comment by codeboten** [comment]
Thanks @yotamloe, yup this issue can be closed 👍🏻 Appreciate your contributions!
