### ISSUE TITLE
[receiver/kubeletstats] Include sidecar initContainers to pod/container utilization metrics

### ISSUE THREAD

**Issue by jinja2** [open-telemetry/opentelemetry-collector-contrib#29712]
### Component(s)

receiver/kubeletstats

### Is your feature request related to a problem? Please describe.

[Running initContainer as sidecars](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) is beta in k8s v1.29. A few metrics in the `kubeletstats` receiver need to be updated since it is now possible for initContainers (`restartPolicy == Always`) to keep running for the entirety of pod's lifecycle.

### Describe the solution you'd like

K8s pod/container utilization wrt to request/limit metrics should [iterate over initContainers](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.90.1/receiver/kubeletstatsreceiver/internal/kubelet/metadata.go#L94) also to include any sidecars. 

Below metrics for pods should be updated s.t. they now consider sidecar initContainer's limits/request when deciding whether to compute these, and the metric values should add any sidecar container's usage to the calculation.
```
k8s.pod.cpu_limit_utilization
k8s.pod.cpu_request_utilization
k8s.pod.memory_limit_utilization
k8s.pod.memory_request_utilization
```

Below metrics computed for main containers should also be computed for sidecar containers
```
k8s.container.cpu_limit_utilization
k8s.container.cpu_request_utilization
k8s.container.memory_limit_utilization
k8s.container.memory_request_utilization
```

PS - Should we calculate these (`k8s.container.*_utilitzation`) for non-sidecar initContainers when they are running? We have the raw usage metrics from initContainers being reported from the receiver, but this is an inconsistency we might want to fix.

**Comment by TylerHelmuth** [comment]
> PS - Should we calculate these (k8s.container.*_utilitzation) for non-sidecar initContainers when they are running? We have the raw usage metrics from initContainers being reported from the receiver, but this is an inconsistency we might want to fix.

I think we should since they are contributing to the pod-level request/limit utilization metrics.

**Comment by bryan-aguilar** [comment]
I believe this is a duplicate (or very similar to) #29623

**Comment by jinja2** [comment]
Similar but this to track work for `kubeletstats` receiver. [#29623](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29623) is for `k8scluster` receiver.
