### ISSUE TITLE
[processor/servicegraph] documentation inconsistency in README

### ISSUE THREAD

**Issue by rlankfo** [open-telemetry/opentelemetry-collector-contrib#29723]
### Component(s)

processor/servicegraph

### Describe the issue you're reporting

The README indicates the default value of the store TTL is 2ms when this should be 2s:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/servicegraphprocessor/README.md?plain=1#L122

See the default config:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/servicegraphprocessor/factory.go#L78

**Comment by crobert-1** [comment]
Good catch, looks like the README is wrong. Thanks for fixing as well!
