### ISSUE TITLE
Tail-sampling processor: drop spans matching an attribute

### ISSUE THREAD

**Issue by LukeMathWalker** [open-telemetry/opentelemetry-collector-contrib#2972]
It is currently possible to prescribe that spans matching a certain condition are always sampled.
As far as I can see, there is no mechanism to do the opposite (even in other processors): how do I instruct the collector to always drop spans matching a certain condition?

E.g. drop all spans where the HTTP path is `/health_check`.

Looking at the source, it would be fairly simple to add this functionality to the tail-sampling processor and I'd be happy to open a PR for it, but I am also aware of #1797 - what is the best way forward here?

**Comment by HuBaX** [comment]
Is anyone working on this? I'm asking because I'd like to implement this.

**Comment by jpkrohling** [comment]
The string attribute now has an `invert_match` attribute that allows you to achieve this.
