### ISSUE TITLE
New component: pkg/sampling

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector-contrib#29738]
### The purpose and use-cases of the new component

New pkg/sampling component will contain common library code for:
1. Parsing a W3C tracestate header
2. APIs for extracting modifying, interpreting an OpenTelemetry tracestate header
3. APIs for Threshold, Randomness, conversion to/from probability values
4. Consistent probability sampling mechanism using all of the above.

### Example configuration for the component

No direct configuration in yaml. This module supports a strictly defined translation between IEEE 754 floating point values and so-called "Threshold" values.

A simple component that uses this library (e.g., probabilisticsamplerprocessor) will extract probabilities from yaml configuration and convert them into a `Threshold` value using one of two methods:

1. `ProbabilityToThreshold`: exact translation from floating point to threshold, preserves all significant bits, in which case Threshold-to-Probability is an exact round trip.
2. `ProbabilityToThresholdWithPrecision`: approximate translation from floating point to threshold, will round probability value to limit the encoding size, in which case Threshold-to-Probability is not a round trip.

### Telemetry data types supported

Tracing receives direct support, in the sense that `Randomness` can be extracted from `pcommon.TraceID`. However, the `Randomness` type can be used directly and this package may be extended to apply consistent probability sampling to other data types.

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

jmacd, kentquirk

### Sponsor (optional)

codeboten

### Additional context

This implements the draft specification proposal in https://github.com/open-telemetry/oteps/pull/235
This implements the already-specified rules for tracestate handling: https://opentelemetry.io/docs/specs/otel/trace/tracestate-handling/

This is one step in an umbrella issue, the overall goal is stated here: https://github.com/open-telemetry/opentelemetry-specification/issues/1413

**Comment by codeboten** [comment]
I'm happy to sponsor this module

**Comment by TylerHelmuth** [comment]
I'd also like to sponsor.  Go sampling!

**Comment by jiekun** [comment]
I would like to subscribe it as well.

Probabilistic sampling policy is also available in [tail-sampling processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/internal/sampling/probabilistic.go). And I've seen discussion on Slack complaining it: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27044.

So I have been looking forward to the probabilistic sampling being unified in SDKs, processors, and maybe other components, being managed in a unified manner.

**Comment by jpkrohling** [comment]
This was done as part of #29720.
