### ISSUE TITLE
[exporter/logicmonitorexporter] Support resource mapping configurations for logs

### ISSUE THREAD

**Issue by avadhut123pisal** [open-telemetry/opentelemetry-collector-contrib#29732]
### Component(s)

exporter/logicmonitor

### Describe the issue you're reporting

As per the LogicMonitor's [Log Ingestion documentation](https://www.logicmonitor.com/support/lm-logs/sending-logs-to-the-lm-logs-ingestion-api), if more than one resource property exists, only the first property will be mapped. In case of OTLP logs, there can be multiple resource attributes and its order also cannot be guaranteed.

Recently, the LogicMonitor has made the resource mapping for logs more flexible. To opt for the flexible resource mapping for logs, LogicMonitor platform expects some params to be present in the log ingestion request.  

Changes need to be done in the LogicMonitor exporter also in order to get the input of this resource mapping configuration for logs.

**Comment by crobert-1** [comment]
_Removing `needs triage` as it was filed by a code owner and the suggestion makes sense to me._

**Comment by avadhut123pisal** [comment]
Closing this issue, as pull request has been merged.
