### ISSUE TITLE
renovatebot should not run CI checks on initial PR

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29784]
### Describe the issue you're reporting

The initial PR created by renovatebot should not trigger CI, as it will always fail. Instead, it should skip checks, until the opentelemetrybot commit to run tidy on the PR.

**Comment by TylerHelmuth** [comment]
I believe we need https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/tidy-dependencies.yml to run still.
