### ISSUE TITLE
resourcedetection/eks instructions are unclear

### ISSUE THREAD

**Issue by jakeforge** [open-telemetry/opentelemetry-collector-contrib#29850]
### Component(s)

processor/resourcedetection

### Describe the issue you're reporting

The documentation says 

> Note: The kubernetes cluster name is only available when running on EC2 instances, and requires permission to run the `EC2:DescribeInstances` [action](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html)

However, it is unclear what exactly a user needs to do in order to grant this permission to the resource detector.  The same issue exists for other parts of the aws related resourcedetection components.

**Comment by crobert-1** [comment]
Hello @jakeforge, the permissions are inherited from the user deploying the collector, I believe. So whichever permissions you have in your AWS environment, the collector (and this processor) would have as well.

In my own testing, I was using `kubectl` to set context to the EKS cluster, and then running `kubectl apply` to deploy the collector. `kubectl` uses [kubeconfig files](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/) to list valid contexts, an example of which would be your EKS cluster. In my case, I setup a context for the EKS cluster, and included the role for my user in the `args` list of the [execconfig](https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#ExecConfig). This included role was an [IAM role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html) with the permission required.

I don't have a lot of AWS experience though, so others may be able to share more information here.
