### ISSUE TITLE
Document how to modify distribution information

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29858]
### Describe the issue you're reporting

It would be great to have a section in CONTRIBUTING.md describing what needs to happen when distributions info are being modified.

**Comment by codeboten** [comment]
Assigning @atoulme as he volunteered to work on it in the collector SIG call 😬

**Comment by crobert-1** [comment]
As discussed, it may be good to add another `make` command that encompasses all of the necessary metadata/code owner updates, but at the bare minimum all of the existing required commands should be documented. 

Also, there are specific requirements for the GitHub personal access token (PAT) to be able to successfully run the `make update-codeowners`, and possibly `make gendistributions`. Specific information on what access is required for the PAT should be added for these commands.

**Comment by atoulme** [comment]
Closing as no-op
