### ISSUE TITLE
Post cache step failures

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29856]
### Describe the issue you're reporting

Seeing failures in the post cache step in several jobs, see https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7197160693/job/19603646422?pr=29842:

```
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib --files-from manifest.txt --use-compress-program zstdmt
Warning: Failed to save: Cache service responded with 429 during upload chunk.
Warning: Cache upload failed because file read failed with EBADF: bad file descriptor, read
Cache saved with key: prometheus-Linux-go-c9ea3a9ff9bf34216ee3170c2c699f5837b95c4fada7c28308862f3818f3d372
Warning: Cache upload failed because file read failed with EBADF: bad file descriptor, read
Error: The action has timed out.
```

**Comment by songy23** [comment]
Saw a few more: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7464167867/job/20310552827?pr=30350
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7464165679/job/20310513816?pr=30346
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7464165679/job/20310513816?pr=30346

**Comment by codeboten** [comment]
Another one here https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7892576803/job/21539367441?pr=31234
