### ISSUE TITLE
Migrate from opencensus library

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29867]
### Describe the issue you're reporting

This is an encompassing issue to capture all the components using the opencensus library to generate metrics today. Migrating them to use OpenTelemetry should be a fairly quick process, and once `telemetry.useOtelForInternalMetrics` is stable, we should be able to move all components on this list to emit metrics with the OTel SDK

- [x] #33472
- [x] #30170
- [x] #33471
- [x] #33469
- [x] #30734
- [x] #30763
- [x] #33464
- [x] #33466
- [x] #33465
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29917
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31581
- [x] #33467
- [x] #30733
- [x] #33468
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29900
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32261

**Comment by atoulme** [comment]
How can I help with `exporter/splunkhec`? What is the equivalent API to adopt?

**Comment by codeboten** [comment]
> How can I help with `exporter/splunkhec`? What is the equivalent API to adopt?

@atoulme i'm trying to put an example together, unfortunately, the two components i started with didn't work out, one was using census without needing it (see the statsd PR) and the other, well i ended up not changing it (healthcheck extension) 😆 

Will comment on here once i have an example 👍🏻

**Comment by codeboten** [comment]
@atoulme here's an example of migrating from opencensus to otel: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29917

**Comment by sumo-drosiek** [comment]
Another Issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32261
