### ISSUE TITLE
scope -> name missing in cloudwatch logs exporter

### ISSUE THREAD

**Issue by MaGaudin** [open-telemetry/opentelemetry-collector-contrib#29884]
## Description
Our ADOT Collector is receiving this log:
{
   "resourceLogs": [
       {
           "resource": {
               "attributes": [...]
           },
           "scopeLogs": [
               {
                   "scope": {
                       "name": "xxxxxxx"   
                   },
                   "logRecords": [
                       {
                           "timeUnixNano": "xxx",
                           "observedTimeUnixNano": "xxxx",
                           "severityNumber": 9,
                           "severityText": "Information",
                           "body": {
                               "stringValue": "GET / \r\n"
                           },
                           "attributes": [...],
                           "traceId": "xxxx",
                           "spanId": "xxxx"
                       }
                   ]
               }
           ]
       }
   ]
}

but in AWS Cloudwatch we are not able to see the field scope.name. We saw from the file exporter.go (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awscloudwatchlogsexporter/exporter.go) that is missing the logic to retrieve the field from line 143-146. 
## Expected Result
We would like to have this field in our cloudwatch logs.
## Actual Result
this field is missing

### Collector version

v0.90.1 for OTEL and v0.36.0 for ADOT

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by sgarzo10** [comment]
I have the same problem

**Comment by crobert-1** [comment]
Hello @MaGaudin, I was able to confirm your findings and agree the scope and scope name should be included in the log being sent to CloudWatch. Code owners can correct me if there's a specific reason this should not be included.

**Solution proposal:**

The exporter is essentially copying all data it wants to send into a local struct called `cwLogBody`, which will then [marshal all of the information into JSON](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/091195a844d4a0e5e70a8e49482b49e0dcda80f2/exporter/awscloudwatchlogsexporter/exporter.go#L217). This JSON will then be [converted to a string](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/091195a844d4a0e5e70a8e49482b49e0dcda80f2/exporter/awscloudwatchlogsexporter/exporter.go#L226) called `Message`.

I believe the solution here is to modify the function signature to accept `plog.Scope` as well here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/091195a844d4a0e5e70a8e49482b49e0dcda80f2/exporter/awscloudwatchlogsexporter/exporter.go#L174
We can get `Scope` from `sl.Scope` here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/091195a844d4a0e5e70a8e49482b49e0dcda80f2/exporter/awscloudwatchlogsexporter/exporter.go#L142
`cwLogBody` would also need to be modified to introduce scope here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/091195a844d4a0e5e70a8e49482b49e0dcda80f2/exporter/awscloudwatchlogsexporter/exporter.go#L162
Then the scope information could just be added here alongside `resource`:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/091195a844d4a0e5e70a8e49482b49e0dcda80f2/exporter/awscloudwatchlogsexporter/exporter.go#L215


**Note:**
At some point the code owners here may want to evaluate moving to a well-defined central marshaller for logs. I see there are some specific formatting changes being done, but having to manually copy all the data and then marshall what you've copied is prone to errors and hard to maintain. Something like what the [ExporterHelper does](https://github.com/open-telemetry/opentelemetry-collector/blob/9d2e43d93aeaa02af8a3a4bc3085405aaf41ffad/exporter/exporterhelper/logs.go#L46), if that works for the use case here.

**Comment by crobert-1** [comment]
One thing to note: My proposed solution will not work when the [configuration option](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awscloudwatchlogsexporter#configuration) `raw_logs` is set to `true`. I'll defer to code owners on how to handle that situation if necessary.

**Comment by MaGaudin** [comment]
Thank you so much for the propose solution @crobert-1! So, we need to wait for an opinion from the code owners?

@boostchicken @bryan-aguilar @rapphil

**Comment by bryan-aguilar** [comment]
Thank you for your investigation @crobert-1, it was very thorough and helpful. I agree with everything that has been said so far. I believe it would make sense for the InstrumentationScope to be included. 

> My proposed solution will not work when the [configuration option](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awscloudwatchlogsexporter#configuration) raw_logs is set to true.

raw_log should really be looked through as a `passthrough` mode with a little logic to handle EMF messages. I think it would be okay to ignore this case. 

> At some point the code owners here may want to evaluate moving to a well-defined central marshaller for logs.

Agreed, this would be nice if it could fit nicely into the existing CWL logic, but I do not think and would not suggest for whoever takes on this PR to tackle this now. I would request a separate PR.

**Comment by MaGaudin** [comment]
hi

**Comment by bryan-aguilar** [comment]
I was suggesting to have separate PRs for the instrumentation scope pr and new, consistent marshaling behavior. This PR is not blocked and awaiting for a contributor to pick up the work.
