### ISSUE TITLE
add `Meter` method to mdatagen to simplify collecting telemetry

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29921]
Idea: Since I see we started to use "metadata" yaml at leas for the type. Can we have in there a "component metrics" section (similar but different than the "scraper metrics" we already have) than essentially generate a function where we can pass a "MeterProvider" and creates all instruments and simplifies this boilerplate?

Kind of an "obsreport" per component custom generated via the metadata yaml?

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29917#discussion_r1428313934_

**Comment by bogdandrutu** [comment]
I would also have a followup issue to generate instruments as well.
