### ISSUE TITLE
[receiver/sshcheck] do not skip lifecycle tests

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29993]
This test should not be skipped. 

              note: need to add an issue to not skip lifecycle tests

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29978#discussion_r1429193816_

**Comment by prakrit55** [comment]
hey @codeboten, I would like to grab it

**Comment by led0nk** [comment]
@codeboten seems like the test is generated now as mentioned in #31538

**Comment by codeboten** [comment]
Thanks @led0nk
