### ISSUE TITLE
[receiver/wavefront] do not skip lifecycle tests

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29995]
These tests should not be skipped.

              add issue to not skip these

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29982#discussion_r1429196678_

**Comment by ChrsMark** [comment]
Filed https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30325 to fix this.
