### ISSUE TITLE
[receiver/opencensus] do not skip lifecycle tests

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29998]
These tests should not be skipped

              add issue to not skip lifecycle tests

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29953#discussion_r1429206166_

**Comment by atoulme** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31648
