### ISSUE TITLE
[receiver/pulsar] do not skip lifecycle tests

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#29996]
These tests should not be skipped.

              add issue to not skip these tests

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29961#discussion_r1429203946_

**Comment by hamzmu** [comment]
@codeboten is this issue still open?

**Comment by codeboten** [comment]
@hamzmu yup! You can see the config currently still skips the tests: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5965ee64e4e45476beb71b8e2a7eb6116a09a9a0/receiver/pulsarreceiver/metadata.yaml#L12

**Comment by hamzmu** [comment]
@codeboten great, can i pick up this issue? Also do i simply change skip_lifecycle to false?

**Comment by Sanket-0510** [comment]
@codeboten it works but there seems some issue with LifeCycle test it fails upon running.....
![Screenshot from 2024-03-03 18-03-17](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/104385297/a3dd8257-cb19-4366-b63a-0e9733dc8c68)

Error- connection refused by `localhost:6650`
