### ISSUE TITLE
exporter/stackdriver: allow configuration for buffer, delay, etc.

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector-contrib#3]
See: https://github.com/census-instrumentation/opencensus-service/issues/474

**Comment by songy23** [comment]
Also we need to allow default metric labels/trace attributes to be configured: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/09504ed717c748c8fd802ba78924d6ca322c27d8/stackdriver.go#L208-L228, so that the default "task" label can be overridden.

/cc @dinooliva @rghetia

**Comment by flands** [comment]
@mtwo is this still applicable? can it be closed?

**Comment by mtwo** [comment]
Closing
