### ISSUE TITLE
Elastic receiver

### ISSUE THREAD

**Issue by fuleow** [open-telemetry/opentelemetry-collector-contrib#3002]
We have a mixed tracing environment running a combination of Zipkin, OpenTelemetry and Elastic APM. Using the OpenTelemetry collector configured with an Elastic exporter we can export our Zipkin and OpenTelemetry traces to the Elastic APM server to give us a complete trace.

We also export from our OpenTelemetry collector to Jaeger, but we can't see the traces created by our services running the Elastic APM Agent. Would it be feasible to create an Elastic receiver for the OpenTelemetry collector so that Elastic APM Agent created spans can be exported to other backends like Jaeger?

**Comment by cyrille-leclerc** [comment]
Hello @fuleow . 
Thank you very much for using Elastic.
It should be possible to create a receiver for the Elastic APM protocol but we unfortunately have not prioritised this task. 
Our focus at Elastic for the moment is to improve our native support for the OpenTelemetry protocol directly on Elastic Observability.

Could you please share with us your use case so we better understand?

**Comment by fuleow** [comment]
Thanks for reaching out @cyrille-leclerc. I am glad to see Elastic's commitment to OpenTelemetry and new features such as the ability to use the native OTLP exporter with the latest APM Server 7.12.

Our early distributed tracing efforts began with using the Elastic APM Agent since OpenTelemetry was not stable yet. With the Elastic agent we ran into some [scaling problems with high volume services](https://discuss.elastic.co/t/all-spans-grouped-into-servletwrappingcontroller/253765/5) so we used OpenTelemetry agents on those services.

With the OpenTelemetry agent we can use multiple backends and can visualize our traces in both Jaeger and Kibana APM. The issue is the traces are incomplete in Jaeger because we have no way to export traces from the Elastic APM agents to our OpenTelemetry collector or Jaeger directly.

Does Elastic have plans to make the APM Agents have native support for OpenTelemetry too? We have been happy with the agent for the most part, but with OpenTelemetry reaching stable status and the APM Server accepting OTLP natively it starts to make more sense for us to migrate away from the APM Agent as OpenTelemetry gives us more flexibility.

**Comment by cyrille-leclerc** [comment]
Hello @fuleow,
Thank you very much for your feedback and for your kind words regarding our support of OpenTelemetry.

First, regarding the scalability challenges you reported back in Oct 2020, we are happy to confirm you that the solutions to solve your problems are in progress. We work both on a new persistence model we referred to as "Metric based storage of transaction data" and  and on tail based sampling. We wished we could have moved faster and we are confident we will ship soon these features.

Second, regarding your integration pattern to articulate Elastic Observability and OpenTelemetry, I understand your point about the Elastic APM Agent integrated with the OpenTelemetry Collector, we will track this in our backlog.

Thanks again for your feedback, Cyrille

**Comment by jkowall** [comment]
Another company similar to the new relic announcement who says they support otel with their agents but only support taking data from otel. 

I hope these vendors build OTLP interfaces in the future but I'm not holding my breath for that to happen. If you want to use otel youll have to use otel instrumentation. Sad truth as evidenced here.
