### ISSUE TITLE
[receiver/azuremonitor] do not skip lifecycle tests

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#30038]
add issue to not skip lifecycle tests

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30024#discussion_r1430218942_

**Comment by ChrsMark** [comment]
This one should be fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30198.

**Comment by nslaughter** [comment]
I believe this issue should be closed. 
The issue is that lifecycle tests were skipped. And 30198 removed the `skip_lifecycle` flag.

**Comment by codeboten** [comment]
Thanks @ChrsMark @nslaughter
