### ISSUE TITLE
[receiver/awscontainerinsight]  do not skip lifecycle tests

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#30037]
add issue to not skip lifecycle tests

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30027#discussion_r1430206540_

**Comment by professorabhay** [comment]
Hey, @codeboten! I would like to do this.
Please tell me something more about that.
By just changing the status from `true` to `false`, it will resolved?

**Comment by hamzmu** [comment]
@codeboten is this issue still open?

**Comment by codeboten** [comment]
@hamzmu yup, still marked as skipped: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5965ee64e4e45476beb71b8e2a7eb6116a09a9a0/receiver/awscontainerinsightreceiver/metadata.yaml#L14

@professorabhay you can remove the line that says to skip the tests in metadata.yaml above, run:

```
make generate,
make -C receiver/awscontainerinsightreceiver test
```

To see what needs to be fixed. If the tests pass, then that's all that's needed.

**Comment by professorabhay** [comment]
Ok, I'm working on it 🙂
@hamzmu I'll raise PR soon

**Comment by professorabhay** [comment]
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/76243309/cd598676-005f-4f0c-b224-8d7394b357ac)

Do I need UNIX-based OS for testing?

**Comment by Sanket-0510** [comment]
hey the `skip_lifecycle` does affect the lifecycle test, but the problem is in the testing code, it fails if I run it making it `true` 
can you please elaborate how do I address this issue further?
![Screenshot from 2024-03-03 16-40-29](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/104385297/82ea8a96-29b6-43e4-8b37-f2a05ec37d8a)

looks like the Start methods returns some error-  https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5965ee64e4e45476beb71b8e2a7eb6116a09a9a0/receiver/awscontainerinsightreceiver/generated_component_test.go#L81

**Comment by lkwronski** [comment]
@Sanket-0510 Hi, I tried to work on this issue and I had the same error as you, but I stop when I had to prepare the environment to connect to aws, and maybe there is an easier way to run this test. BTW to fix your problem If I remember correctly you have to run:

```
$ mkdir /rootfs
$ ln -s /proc  /rootfs/proc
```

I'm not sure if this is the right solution or only workaround.

**Comment by Sanket-0510** [comment]
Hey I tried this but still the lifecycleTest throws error can you please verify, does the above fix worked for you? 
![Screenshot from 2024-03-03 18-34-37](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/104385297/49148ef6-1600-441c-af78-0e3cec573426)

**Comment by lkwronski** [comment]
I suppose now you need to connect to AWS, you need to create a configuration to be able to connect to aws. There may be a simple solution (I'm not a maintaner, I'm new to this project), but from what I understand, you need to configure your aws account to be able to download some telemetry data from aws.

For example, for error which you include you need to setup `AWS_REGION` evn variable.

**Comment by Sanket-0510** [comment]
> I suppose now you need to connect to AWS, you need to create a configuration to be able to connect to aws. There may be a simple solution (I'm not a maintaner, I'm new to this project), but from what I understand, you need to configure your aws account to be able to download some telemetry data from aws.
> 
> For example, for error which you include you need to setup `AWS_REGION` evn variable.

if thats the case then it shall not fail anyways, its issue from my system

**Comment by Sanket-0510** [comment]
hey @lkwronski  I just checked my aws configurations, the id and default region is already set and I can also access ec2 info's from using aws CLI, but still the lifecycle test is failing showing 
```
Error:      	Received unexpected error:
        	            	failed to create aws session: NoAwsRegion: Cannot fetch region variable from config file, environment variables and ec2 metadata.
        	Test:       	TestComponentLifecycle/metrics-lifecycle
