### ISSUE TITLE
Request for Multiarch Support in Telemetrygen Container Image.

### ISSUE THREAD

**Issue by IshwarKanse** [open-telemetry/opentelemetry-collector-contrib#30072]
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

The OpenTelemetry Operator and Collector are compatible with multiple architectures including linux/amd64, linux/arm64, linux/ppc64le, and linux/s390x. However, the E2E tests in the operator repository rely on Telemetrygen, which currently lacks multiarch support.

To enable testing on all supported platforms, it’s crucial that the Telemetrygen image is built with multiarch support. This enhancement will allow us to run our E2E tests across all supported architectures, ensuring comprehensive coverage and compatibility.

We propose that the Telemetrygen image be built directly from the project repository, which would streamline the process and maintain consistency. This change would be a significant improvement for our testing infrastructure.

### Describe the solution you'd like

Update the Telemetrygen [workflow](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/telemetrygen.yml) to build and publish multiarch images.  

### Describe alternatives you've considered

Build the multiarch images from the forked repo and publish it to a container registry. Replace the image in tests.

**Comment by crobert-1** [comment]
Sounds like a good idea to me! A code owner has also approved the PR, so I'm removing the `needs triage` label.
