### ISSUE TITLE
sqlqueryreceiver does not support histogram metric types

### ISSUE THREAD

**Issue by zdelagrange** [open-telemetry/opentelemetry-collector-contrib#30097]
### Component(s)

receiver/sqlquery

### Is your feature request related to a problem? Please describe.

the sqlquery receiver does not support histogram data types.

### Describe the solution you'd like

I would like to be able to create histograms from sql queryies, for example the datadog snowflake receiver supports a histogram datatype, where it creates *.avg *.count *.max *95percentile *.max *.median from a query

**Comment by crobert-1** [comment]
I think this is a valid request. Any PRs to add support for this would be welcome!
