### ISSUE TITLE
Dependencies only support go1.21

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#30101]
### Describe the issue you're reporting

Starting an issue here to capture some of the packages that cannot be upgraded due to minimum go requirements in those packages:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30260
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26265   
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29839

**Comment by djaglowski** [comment]
I believe this can move forward once https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34244 is merged.
