### ISSUE TITLE
Unable to upgrade to `upload-artifact` and `download-artifact` to v4

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#30102]
### What happened?

When we bumped to `upload-artifact@v4` and `download-artifact@v4` our CI started failing. I think it is related to https://github.com/actions/upload-artifact/issues/471 but I'm not entirely sure.  We need to investigate what we are doing that no longer works in `v4`.

Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30098

**Comment by astencel-sumo** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31236
