### ISSUE TITLE
[connector/datadog] Parity with trace stats options for datadog exporter

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-collector-contrib#30143]
### Component(s)

connector/datadog

### Is your feature request related to a problem? Please describe.

Currently, I'm able to configure options for trace stats generation on the `datadogexporter`, but not on the `datadogconnector`
* `peer_tags_aggregation`
* `peer_service_aggregation`
* `compute_stats_by_span_kind`

### Describe the solution you'd like

I'd like to be able to set these options when configuring the `datadogconnector`.

**Comment by songy23** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30787, the configs will be available in the next release.
