### ISSUE TITLE
Resource Attrs + Operation based routing in loadbalancing exporter for traces

### ISSUE THREAD

**Issue by aishyandapalli** [open-telemetry/opentelemetry-collector-contrib#30146]
### Component(s)

exporter/loadbalancing

### Is your feature request related to a problem? Please describe.

Right now, we have traceID and service based routing for traces in loadbalancing exporter. We see the traffic is unbalanced for both the routing types. We want to add a new entry for resource attributes+operation combination to balance the traffic across backends.

### Describe the solution you'd like

Add a new entry key for resource attributes+operation routing and route the traffic based on the ids computed with resource attributes+operation combination

**Comment by jpkrohling** [comment]
> We see the traffic is unbalanced for both the routing types

That's surprising: balancing via trace ID should be relatively acceptable. I'd be curious to see the load-balancer metrics for that. Would you be able to share them? 

> We want to add a new entry for resource attributes+operation combination to balance the traffic across backends.

Do you mind sharing more details about this? Which concrete values would you be using to improve the balancing? "Operation" (span name, I assume) cannot be used for the load balancing, as it would result in spans from the same trace reaching different backends.
