### ISSUE TITLE
examples for clickhouse exporter are broken

### ISSUE THREAD

**Issue by neyguvj** [open-telemetry/opentelemetry-collector-contrib#30159]
### Component(s)

exporter/clickhouse

## Description

There is an error in clickhouseexporter makefile go build command.

Also `tracegen` was removed from the repository. It needs to be replaced with `telemetrygen`.

## Steps to Reproduce
Run the following commands
```
cd exporter/clickhouseexporter
make local-run-example
```
## Expected Result

all containers are running.

## Actual Result

Got error:
```
cd ../../ && GOOS=linux go build -o ./local/otelcontribcol ./cmd/otelcontribcol
main module (github.com/open-telemetry/opentelemetry-collector-contrib) does not contain package github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
make: *** [Makefile:4: local-run-example] Error 1
```

After fixing the Makefile I still get the error
```
cd ../../ && GOOS=linux go build -o ../../local/otelcontribcol  -C cmd/otelcontribcol
cd example && docker-compose up -d
ERROR: build path /home/golov-rg/work/cloud/opentelemetry-collector-contrib/cmd/tracegen either does not exist, is not accessible, or is not a valid URL.
make: *** [Makefile:5: local-run-example] Error 1
```

### Collector version

2008304e57

## Environment
OS: Ubuntu 22.04
Compiler: go 1.20.9

### OpenTelemetry Collector configuration

```yaml
``
```

**Comment by crobert-1** [comment]
I was able to confirm it's broken, and I've submitted a fix PR.
