### ISSUE TITLE
Compatibility metric type summary 

### ISSUE THREAD

**Issue by maokitty** [open-telemetry/opentelemetry-collector-contrib#30156]
### Component(s)

processor/cumulativetodelta

### Is your feature request related to a problem? Please describe.

As there is a summary in [prometheus](https://prometheus.io/docs/concepts/metric_types/#summary) and [opentelemetry-summary-legacy](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#summary-legacy), convert it to delta for compatibility.

### Describe the solution you'd like

Convert sum and count to delta and leave quantiles unchanged as quantile are time window based values.

**Comment by mx-psi** [comment]
@maokitty A summary does not have an aggregation temporality field https://github.com/open-telemetry/opentelemetry-proto/blob/ea449ae0e9b282f96ec12a09e796dbb3d390ed4f/opentelemetry/proto/metrics/v1/metrics.proto#L245-L247 as opposed to all other metric types handled by the cumulative to delta processor. 

I think a solution here would be for something like the transform processor to allow you to split a summary into its constituent parts (count, sum, quantiles  as separate metrics) and then apply cumulative-to-delta to them.

**Comment by TylerHelmuth** [comment]
There already are some summary conversion functions:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#convert_summary_count_val_to_sum
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#convert_summary_sum_val_to_sum

Are these helpful?

**Comment by mx-psi** [comment]
I think they should be, maybe a quantiles one would be helpful as well but IMO we should wait until someone explicitly asks for it
