### ISSUE TITLE
opampsupervisor own metrics should support headers

### ISSUE THREAD

**Issue by thmshmm** [open-telemetry/opentelemetry-collector-contrib#30157]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

Currently the supervisor only supports setting an endpoint for its own metrics. It should additionally support the headers provided via `TelemetryConnectionSettings`. This is needed to support e.g. authentication.

### Describe the solution you'd like

The config could be a template and rendered with `text/template` to support more complex scenarios than single values.

**Comment by thmshmm** [comment]
feel free to assign it to me, i can work on it.

**Comment by crobert-1** [comment]
_Removing `needs triage` based on a code owner assigning the issue._
