### ISSUE TITLE
SplunkHecExporter. Add option to provide certificates for SSL verification

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-collector-contrib#3015]
**Is your feature request related to a problem? Please describe.**
Feature Request
SplunkHecExporter doesn't receive any certificates for SSL verification to HEC endpoint. 

Need additional TLSConfig from here
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/520d7619f2ba4a00e84d90603d7db3534be8e1bb/exporter/splunkhecexporter/exporter.go#L97

**Comment by chaitanyaphalak** [comment]
Addresses - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3204

**Comment by chaitanyaphalak** [comment]
The PR was merged @tigrannajaryan this can be closed :)

**Comment by tigrannajaryan** [comment]
Done via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3204
