### ISSUE TITLE
Revisit documentation

### ISSUE THREAD

**Issue by hughesjj** [open-telemetry/opentelemetry-collector-contrib#30166]
### Describe the issue you're reporting

Imo `CONTRIBUTING.md` is getting a bit big.  I saw that the upstream `opentelemetry-collector` has a `docs` folder and was wondering about possibly doing similar on our side.

I wanted to document some things around running integration tests and build constraints that I didn't see elsewhere.  I can instead make a PR against `CONTRIBUTING.md` if that's preferable.

I'll also note that some `opentelemetry-collector-contrib` specific documentation lives in `opentelemetry-collector` (ex stuff around mdatagen).  While I'd love to see mdatagen upstreamed, I'm of the opinion said docs would better live here (maybe with a link from upstream ?) until we merge it upstream.

Lastly, I'd like to reuse these markdown files for the opentelemetry.io site if possible, but that's for the future.

In general I want to connect with other people in the collector-contrib and collector spaces to improve documentation, and intend to use this as a centralized place to discuss such unless/until we get more inertia and consensus around documentation improvements..

**Comment by crobert-1** [comment]
Any documentation PRs are welcome! To make it easiest on reviewers, please keep content and re-organization changes as distinct as possible. It's a lot easier to review if you know it's just content being moved vs. moved and modified. Sometimes it's impossible to separate, but just a thought.

Some kind of landing page would be helpful to direct users to whatever information they're looking for. Obviously one big document is hard to process, but it at least allows one central search of contents, so we want to make sure we don't make it harder to find what someone's looking for by breaking it up into different files.

Specifics can probably be discussed in PRs.
