### ISSUE TITLE
Remove vendor/external distros from components readme

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#30164]
### Component(s)

ALL

### Describe the issue you're reporting

We got some feedback about the fact that we keep per component list of distros (vendor specifically). We will remove this because the list is hard to maintain with accuracy and will simply keep just a list in the main README or on the website with all distributions and point to their readme where they can list all the components they include.

**Comment by codeboten** [comment]
The original intent of listing distros was for users to be able to see which component was included in the core and in the contrib distros. 

I would be ok with returning to this reduced list of distros in each readme. I would also be ok with removing this altogether if folks don't find it useful.

**Comment by atoulme** [comment]
We have a set of rules in place regarding those distributions:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/distributions.yaml#L3-L4

We keep tabs on those distributions to make sure we work with distribution maintainers when we deprecate components.

If OpenTelemetry doesn't want to link to other distributions, even if they are themselves open source, that's understandable.

+1 to keep it for at least core and contrib, and any other upcoming distribution managed by OpenTelemetry.

**Comment by codeboten** [comment]
Marking this as completed
