### ISSUE TITLE
Can't build image for loadbalancingexporter

### ISSUE THREAD

**Issue by heruv1m** [open-telemetry/opentelemetry-collector-contrib#3016]
There is a build log
`opentelemetry-collector-contrib/exporter/loadbalancingexporter$ docker build -t otelcontribcol example/
Sending build context to Docker daemon  9.728kB
Step 1/13 : FROM golang:1.16 AS build
 ---> 0debfc3e0c9e
Step 2/13 : WORKDIR /src
 ---> Using cache
 ---> 78737b61e091
Step 3/13 : ADD . /src
 ---> Using cache
 ---> 4efbc7201390
Step 4/13 : RUN make otelcontribcol
 ---> Running in 890008575b44
make: *** No rule to make target 'otelcontribcol'.  Stop.
The command '/bin/sh -c make otelcontribcol' returned a non-zero code: 2
`

**Comment by heruv1m** [comment]
@BinaryHexer Can you help with it?

**Comment by BinaryHexer** [comment]
Can you give the output of the following commands?
- `docker build -t otelcontribcol . -f exporter/loadbalancingexporter/example/Dockerfile`
  - Please run it from the root of this repo.
- `cd exporter/loadbalancing/exporter; docker-compose up`

**Comment by heruv1m** [comment]
It works! Thank you.
May be you should update readme to make it more clearly
