### ISSUE TITLE
configschema future

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30187]
### Describe the issue you're reporting

`configschema` imports all the components of the repository and needs upkeep to generate configuration. It is not used by OpenTelemetry currently and maintainers are not aware of its design.

This is similar to #27849 - we want to generate docs per module instead.

The experiment #30186 shows a possible path forward.

As result, we can use the following path forward:
* [ ] Duplicate the logic of `cmd/configschema` into `internal/configschema` so it becomes available as a library
       Offer this new approach via mdatagen, so it generates docs for components opting in
       Enable this for at least one component to show the effect
       #30188
* [x] #30190
* [ ] Delete configschema and `internal/components`

**Comment by mx-psi** [comment]
@atoulme What's the status of this? I am not sure if there were other PRs after #30188
