### ISSUE TITLE
when running go install of latest telemetrygen version, nothing happens.

### ISSUE THREAD

**Issue by snir-nym** [open-telemetry/opentelemetry-collector-contrib#30273]
### Component(s)

cmd/telemetrygen

### Describe the issue you're reporting

when running go install of latest telemetrygen version, nothing happens - no output and no error.
the folder /go/bin doesn't update and telemetrygen doesn't show.
i'm using linux debian 11

**Comment by mx-psi** [comment]
@snir-nym Thanks for opening the issue. I have not been able to reproduce this on the official

 `golang` Docker image.  `go install` will install the binary under the bin folder in the `GOPATH`. It may be that your Go install does not install under `/go/bin`. Can you run 

```
ls $(go env GOPATH)/bin
```

and check if `telemetrygen` is there? It may be that you need to add the `GOPATH` to your `PATH`.

**Comment by cobar79** [comment]
@snir-nym First time golang user.

Is the current [Telemetry generator for OpenTelemetry](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/telemetrygen) out of date? It is very vague on where or how to run telemetrygen

The assumption is that it should really be running a go module? go run telemetrygen.go???

go is installed, go is on the path. However, there is no reference to telemtrygen in  ~/go/pkg/mod/go.opentelemetry.io 
```
$ ls $(go env GOPATH)/bin
docker-credential-ecr-login.exe*
```

~/go/pkg/mod/go.opentelemetry.io
|
---> collector
| 
---> otel
|
---> otel@v1.22.0
|
---> proto

```
go run pdata\@v1.0.1/internal/cmd/pdatagen/main.go
pdata@v1.0.1\internal\cmd\pdatagen\main.go:7:2: no required module provides package go.opentelemetry.io/collector/pdata/internal/cmd/pdatagen/internal: go.mod file not found in current directory or any parent directory; see 'go help modules'

```

**Comment by mx-psi** [comment]
Closing since there was no reply to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30273#issuecomment-1875263184
