### ISSUE TITLE
Incompatibility between default retry settings and timeout settings

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-collector-contrib#30305]
### Component(s)

exporter/prometheusremotewrite

## Description

The prometheus remote write exporter implements its own retry logic (implemented in [this PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23842)) and does not use the queued_retry from the exporter helper. This has to be done so that we avoid out of order samples - data is split into smaller chunks and then submitted to workers that will send it to the backend using a retry strategy in case of failure. Each time series is guaranteed to be only in a single chunk, which guarantees that there won't be out of order samples.

This component is using the default timeout setting of 5s. However the retry settings are not consistent with this value: the max time that each request performed by a worker can be retried is 1 minute.

Therefore we can see that there is a great chance of timeout errors happening in case os consecutive retries.

## Expected Result

We expect that the timeout settings is consistent with the retry logic implemented inside the component.

## Actual Result

Consecutive retries can generate timeout errors.

## Proposal

we would like to propose to remove [the timeout from the exporter helper](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/factory.go#L54) and instead set a timeout on the context just before [requests are sent to the backend](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/exporter.go#L240)

### Collector version

v0.90.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jmacd** [comment]
> we would like to propose to remove [the timeout from the exporter helper](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/factory.go#L54) and instead set a timeout on the context just before [requests are sent to the backend](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/exporter.go#L240)

I support this idea.
