### ISSUE TITLE
exporter/fileexporter: Ability to add custom Log and Metric Marshalers

### ISSUE THREAD

**Issue by sinkingpoint** [open-telemetry/opentelemetry-collector-contrib#30331]
### Component(s)

exporter/fileexporter

### Is your feature request related to a problem? Please describe.

Similar to #14514 , it would be useful to be able to extend the file exporters list of marshalers without having to fork the exporter. Concretely, our usecase is to export syslog formatted logs to a file for our auditing pipeline.

### Describe the solution you'd like

Similarly to #16514 , I'd like to introduce factory options that allow custom marshalers on top of the existing `json` and `proto`

### Describe alternatives you've considered

We could submit some of these marshalers to the contrib repo, but there are quite a few usecases here for weird marshalers so it seems impractical to manage them all here

**Comment by mx-psi** [comment]
I support this. However, I would like to see this in a `pkg` module instead of being exposed directly on the `filexporter` module itself.
