### ISSUE TITLE
[receiver/kafka] Move Authentication configuration struct from internal to pkg/

### ISSUE THREAD

**Issue by vincentfree** [open-telemetry/opentelemetry-collector-contrib#30377]
### Component(s)

receiver/kafka

### Is your feature request related to a problem? Please describe.

Authentication configuration item is internal making it unusable within other applications. 

When using config structs in other projects, it's not great if one out of the 13 fields of the struct is placed in an internal folder. This limits the use of all `.go` files in that folder to be unusable for other projects to use.

In this case I am trying to use `kafkareceiver.Config` it has 13 fields of which one uses a struct in the 
I have also commented on the following conversation between @dmitryax and the original creator of the move to the internal folder @sakulali. 
Both agreed that moving to the `pkg/` folder might be a better move but didn't do it so far since no one faced an issue with it so far.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27289#issuecomment-1883650823

### Describe the solution you'd like

Move the code to `pkg/`, this isn't invasive but makes it possible to actually use the structs used by the exported `kafkareceiver.Config` and other structs that use this on other receivers/exporters etc.

### Describe alternatives you've considered

Move to an other folder but the pkg/ folder seems closest to the standards used in go projects

### Additional context

<img width="770" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/820860/71d1d7bc-3844-4b94-8d24-4a603299b25d">

**Comment by dmitryax** [comment]
@vincentfree, thanks for reporting the issue. All the fields in config structs must be available outside. do you have a chance to submit a PR?

**Comment by vincentfree** [comment]
Hi @dmitryax, I already started :)
I hope I can submit a PR by tomorrow.
