### ISSUE TITLE
[exporter/splunk_hec] Batch by resource attributes index and access token

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30404]
### Component(s)

exporter/splunkhec

### Is your feature request related to a problem? Please describe.

The Splunk HEC exporter gets a 400 error on sending batches if at least one element in the batch has a bad index value.

The fix is to batch per index, so we have a clean way to try batches without partial retries.

### Describe the solution you'd like

Batch per index ; we already batch per access token, so batch by both.

**Comment by crobert-1** [comment]
_This makes sense to me and was filed by a code owner, removing `needs triage`._
