### ISSUE TITLE
Document clarity re: sampling_priority configuration

### ISSUE THREAD

**Issue by pierzapin** [open-telemetry/opentelemetry-collector-contrib#30410]
### Component(s)

processor/probabilisticsampler

### Describe the issue you're reporting

It's not very clear how the sampling_priority configuration in the probabilistic_sampler is intended to work. 
The readme bullet point for this processor just above the **Hashing** heading states:

> sampling_priority (default = null, optional): The optional name of a log record attribute used to set a different sampling priority from the sampling_percentage setting. 0 means to never sample the log record, and >= 100 means to always sample the log record.

which is somewhat ambiguous - is this meant to be a _string_ (i.e. an attribute name as stated) or a _int_ between 0 and 100? 

My initial expectation based on the readme and the example config here was that this setting works in tandem with the from_attribute to provide some sort of override mechanism to the blanket sampling rate. i.e:

```
processors:
  probabilistic_sampler/logs:
    sampling_percentage: 15
    attribute_source: record 
    from_attribute: foo
    sampling_priority: 100
```
Which would suggest that if the data included the attribute "foo" that it'd be sampled at 100%

However testdata/config.yaml#L43 implies that another attribute name is used to drive the sampling_priority. I have no idea how this would work if the attribute value is itself a string?

I'd be happy to contribute wording updates based on your advise about which way this is intended to function.

**Comment by crobert-1** [comment]
The `sampling_priority` configuration option will hold the `string` name of a log attribute. The processor will get the log attribute's value and then use it as the sampling rate, overriding the value of `sampling_percentage`. [Here's the code for reference.](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/aee7b7073a0776241a0b4f4123ef7a00566cf9d7/processor/probabilisticsamplerprocessor/logsprocessor.go#L70-L80)

`from_attribute` will determine which log attribute's value will be used as the hashing value, it's unrelated to the sampling rate. [The processor will get the attribute value](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/aee7b7073a0776241a0b4f4123ef7a00566cf9d7/processor/probabilisticsamplerprocessor/logsprocessor.go#L64-L69) and then [compute a hash on it](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/aee7b7073a0776241a0b4f4123ef7a00566cf9d7/processor/probabilisticsamplerprocessor/logsprocessor.go#L82), then use the sampling priority (either set by `sampling_percentage` or the log attribute `sampling_priority's` value) to determine if the log itself is sampled or not.

I agree this could be made more clear in the README, a PR would be welcomed!

**Comment by crobert-1** [comment]
> Should this be closed?

I don't think so, my PR was mostly unrelated to this. We still need to update the README to close this, from my understanding.

**Comment by jmacd** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31946#discussion_r1597799522

**Comment by jpkrohling** [comment]
@kentquirk , would you be able to transform your comment in documentation at the readme for the component?
