### ISSUE TITLE
[exporter/elasticsearch] Deprecate `mode: ecs` configuration option and change default to `mode: none`

### ISSUE THREAD

**Issue by ycombinator** [open-telemetry/opentelemetry-collector-contrib#30441]
### Component(s)

exporter/elasticsearch

### Describe the issue you're reporting

Summarizing relevant bits from [this conversation](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29619#discussion_r1439417638):

The `elasticsearch` exporter supports a `mode` configuration option.  The default value of this option is `ecs`.  Other supported values are `none` and, after #29619 is merged, `raw`.

Looking at the exporter's code, it appears that the `mode: ecs` configuration doesn't have any effect and is functionally the same as `mode: none`.  So the proposal is to deprecate `mode: ecs` and make `mode: none` the default instead.  After a sufficient amount of deprecation time — 3 months? 6 months? — remove `mode: ecs` altogether.

**Comment by j-kap-t** [comment]
@JaredTan95 is this change the future plan for the component? I had previously submitted https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30454 but wasn't able to follow up before it got closed as stale. I can reopen the PR if there is interest in that alternate direction.

**Comment by JaredTan95** [comment]
> @JaredTan95 is this change the future plan for the component? I had previously submitted #30454 but wasn't able to follow up before it got closed as stale. I can reopen the PR if there is interest in that alternate direction.

@j-kap-t Sorry for the late reply, I think you can reopen your PR and push forward it~

**Comment by j-kap-t** [comment]
Thanks @JaredTan95 , I had to recreate it since I don't have permissions to re-open: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31553.
