### ISSUE TITLE
Generate logs from trace pipeline

### ISSUE THREAD

**Issue by ewoolsey** [open-telemetry/opentelemetry-collector-contrib#30459]
### Is your feature request related to a problem? Please describe.

`opentelemetry-rust` is still very immature and the logging pipeline isn't well supported. I would like the collector to generate logs purely from events that occur within the tracing pipeline. I think this is a pretty common use case and it would make instrumenting programs with otel much easier!

### Describe the solution you'd like

The collector should be able to generate logs directly from trace events.

### Describe alternatives you've considered

In rust using the `tracing` ecosystem it us currently very cumbersome to implement logging. There isn't really any great alternative for those already using `tracing`.

**Comment by crobert-1** [comment]
Hello @ewoolsey, sorry for the delayed response. Can you share some more context for your request? Are you suggesting adding [logging to the collector's telemetry](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/observability.md#how-we-expose-telemetry) in trace pipelines? Are you proposing a new component that generates logs from a traces pipeline, and sends the generated logs to a log pipeline?

What kind of logs are you looking for that would be helpful?

Is this feature request specific to `opentelemetry-rust`, or do you mention it just as the source your proposal? Would it be used for any possible sources of traces?
