### ISSUE TITLE
TestMetric10kDPS always failing for carbon

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#30478]
### Component(s)

receiver/carbon

## Description

The `TestMetric10kDPS/Carbon` test is consistently failing:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7478876839/job/20362056744
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7479409466/job/20363485203
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7479508235/job/20366731153

I believe the flaky started with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29893

### Collector version

latest

**Comment by TylerHelmuth** [comment]
@rmfitzpatrick @atoulme @astencel-sumo @crobert-1 please take a look.

**Comment by rmfitzpatrick** [comment]
If https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30481 doesn't reliably resolve I have no objection to skipping or removing the test. The initial underlying issue of missing metric names was the main cause but if general test env or component flake are concerns there are probably few benefits running the case.

**Comment by TylerHelmuth** [comment]
Looks like that worked: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7505221979/job/20434162668
