### ISSUE TITLE
[connector/datadog] Shutdown hangs

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30487]
### What happened?

When running collector components, we need to make sure that we can shutdown without starting them first. This is the expectation set forth with https://github.com/open-telemetry/opentelemetry-collector/issues/6507.

When running the datadog connector with traces, we see that shutdown hangs.

I have created a test to show how to reproduce this issue:
```
func Test_Shutdown_Traces(t *testing.T) {
	factory := NewFactory()

	creationParams := connectortest.NewNopCreateSettings()
	cfg := factory.CreateDefaultConfig().(*Config)

	traceToMetricsConnector, err := factory.CreateTracesToMetrics(context.Background(), creationParams, cfg, consumertest.NewNop())
	require.NoError(t, err)
	err = traceToMetricsConnector.Shutdown(context.Background())
	require.NoError(t, err)
}
```

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30486 for a PR with the test.

The fix consists in changing the behavior of the connector to check whether the exitChan is active, by moving its initialization to the Start function.

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
I'm actually hitting this as well here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30500

**Comment by mx-psi** [comment]
I don't have much specific to share yet but just that I have shared this internally and someone will look into this

**Comment by mx-psi** [comment]
Did #31811 fix this?

**Comment by crobert-1** [comment]
It looks like it fixed it, but I'll defer to @mackjmr in case there was still some action item here.

**Comment by mackjmr** [comment]
@mx-psi @crobert-1 No action items remaining, we are good to close here 👍

**Comment by mx-psi** [comment]
Closing per the comment above
