### ISSUE TITLE
[mdatagen] Automatically generate goleak tests for packages

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#30483]
### Component(s)

cmd/mdatagen

### Is your feature request related to a problem? Please describe.

While working on #30438 a lot of identical code is being copied into many different places in the repository.

### Describe the solution you'd like

As @dmitryax suggested [here:](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30451#issuecomment-1888413325)
> It would be great to generate this test along with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27849. If we need to skip it for some packages we can add skip_goleak: true with a comment to the tests section metadata.yaml

**Configurable metadata options:**

1. There should be an option to skip the goleak tests if necessary. This would likely mean the `package_test.go` file is not generated, and even deleted if it currently exists. To my knowledge, there's no way to include `TestMain` with the `goleak` call and also skip the resulting goleak check.
2. A configurable list of leaks to ignore. This would make use of the function [`goleak.IgnoreTopFunction`](https://pkg.go.dev/go.uber.org/goleak#IgnoreTopFunction). There are sometimes known issues that can't be addressed and irrelevant to the collector itself that can be safely ignored. PR #30457 has examples of this.

**Comment by crobert-1** [comment]
_Removing `needs triage` as this suggestion was made by the mdatagen code owner, and multiple maintainers/approvers agreed with the idea._

**Comment by crobert-1** [comment]
Currently, the level of granularity between `metadata.yaml` files and `goleak` test packages is different. There's currently one `metadata.yaml` file for each component, but `goleak` is required for each `golang` package. An example is helpful to understand the difference.

The `spanmetrics` connector has a single top-level `metadata.yaml` file. However, for all tests to be covered by `goleak`, it requires `./package_test.go`, `internal/cache/package_test.go`, and `internal/metrics/package_test.go`.

This means there will need to be a way to have multiple paths provided for generating goleak tests, each with its own configuration options, as proposed.

**Comment by crobert-1** [comment]
Another thing to consider is what I pointed out [here,](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30438#issuecomment-1887849348) the fact that some packages already have `TestMain`. I need to investigate how to get existing functionality to work with adding `goleak` for those cases.

**Comment by dmitryax** [comment]
> Currently, the level of granularity between metadata.yaml files and goleak test packages is different. There's currently one metadata.yaml file for each component, but goleak is required for each golang package. An example is helpful to understand the difference.

> The spanmetrics connector has a single top-level metadata.yaml file. However, for all tests to be covered by goleak, it requires ./package_test.go, internal/cache/package_test.go, and internal/metrics/package_test.go.

> This means there will need to be a way to have multiple paths provided for generating goleak tests, each with its own configuration options, as proposed.

As the first step, we should make sure that the test is generated per component/module. Then, we will see if it can be generated per module

**Comment by dmitryax** [comment]
> Another thing to consider is what I pointed out https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30438#issuecomment-1887849348 the fact that some packages already have TestMain. I need to investigate how to get existing functionality to work with adding goleak for those cases.

We can have another option in metadata like `tests.goleak.addtional_test=true` which would generate a function call like 
```
func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
	additionalTestMain(m)
}
```

end expect user to implement additionalTestMain

**Comment by crobert-1** [comment]
> We can have another option in metadata like tests.goleak.addtional_test=true which would generate a function call like

That would be super helpful. There are a number of test suites in `contrib` that rely on an existing `TestMain` 👍
