### ISSUE TITLE
Datadog Receiver does not collect service.version

### ISSUE THREAD

**Issue by backjo** [open-telemetry/opentelemetry-collector-contrib#30526]
### Component(s)

receiver/datadog

## Description
The Datadog Receiver does not pick up the service version correctly from Datadog spans. 
## Steps to Reproduce
Use [dd-trace-dotnet](https://github.com/DataDog/dd-trace-dotnet) with DD_VERSION set. Send trace spans to the DD receiver.
## Expected Result
The DD receiver should collect service.version correctly.
## Actual Result
The DD receiver does not pickup the service version from the datadog spans.

### Collector version

v0.92.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jpkrohling** [comment]
@boostchicken, are you interested in picking this up?
