### ISSUE TITLE
Consider moving Splunk HEC encoding out of Splunk HEC receiver and Splunk HEC exporter into an extension

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30553]
### Describe the issue you're reporting

Under `extensions/encoding`, we now have extensions that specify encodings that can be used by components. The HEC format can be parsed and marshaled to pdata as evidenced by the hec receiver and exporter.

The work would probably go into multiple steps by identifying easiest targets first, most likely traces and receiver first.

**Comment by crobert-1** [comment]
_Removing `needs triage`, this makes sense to me and was filed by a code owner._

**Comment by atoulme** [comment]
Most likely if we land this encoding extension, we will do it separately from the exporter as it right now has multiple tricks in place to enhance performance. We can close this issue as not planned.
