### ISSUE TITLE
[exporter/awss3] Move encodings to extensions

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30554]
### Component(s)

exporter/awss3

### Is your feature request related to a problem? Please describe.

The aws s3 exporter has encodings directly listed under it, they should each be moved to a separate extension. The exporter should then allow any encoding extension to be registered against it.

### Describe the solution you'd like

as above

**Comment by crobert-1** [comment]
_Removing `needs triage`, this makes sense to me and was filed by a code owner._
