### ISSUE TITLE
[exporter/elasticsearch] support sending OTLP metrics to Elasticsearch

### ISSUE THREAD

**Issue by devamanv** [open-telemetry/opentelemetry-collector-contrib#30562]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

Currently, the elasticsearch exporter only supports OTLP Traces/Logs directly to Elasticsearch but not Metrics. Is that by choice? If not, I'd like to contribute to the exporter and add support for Metrics to it. 

### Describe the solution you'd like

The elasticsearch exporter is able to export OTel metrics using OTLP to Elasticsearch.

**Comment by crobert-1** [comment]
My apologies if I'm missing something simple, but it looks like [Elasticsearch supports OTLP natively](https://www.elastic.co/guide/en/observability/current/open-telemetry-direct.html#connect-open-telemetry-collector), so you can just use the `otlp` exporter for metrics. Is there a reason this doesn't fit your use case?

**Comment by JaredTan95** [comment]
pls ref https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23989

**Comment by crobert-1** [comment]
Closing as not planned based on @JaredTan95's comment
