### ISSUE TITLE
Mismatch Between Routing Processor Limitations Docs and Prior Issue?

### ISSUE THREAD

**Issue by bdschaap** [open-telemetry/opentelemetry-collector-contrib#30560]
### Component(s)

routingprocessor

### Describe the issue you're reporting

The routingprocessor documentation mentions that "OTTL statements can be applied to resource attributes".  However, a previously filed issue may indicate that there may be support for routing based on log attributes.  Though the fix may have been limited to resolving a crash and the functionality may not actually be supported.

Docs - https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor#limitations
Previous issue - #26462

**Comment by crobert-1** [comment]
Good catch @bdschaap, I agree the comment doesn't line up with functionality.

Currently the following contexts are used for routing each telemetry type:
[`ottlspan` for traces](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2c7c039c51e5386bc435eea9e72fd1d38ca5f84b/processor/routingprocessor/traces.go#L33C41-L33C41) - [ottlspan context README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/contexts/ottlspan/README.md)
[`ottldatapoint` for metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2c7c039c51e5386bc435eea9e72fd1d38ca5f84b/processor/routingprocessor/metrics.go#L33) - [ottldatapoint context README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottldatapoint)
[`ottllog` for logs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/routingprocessor/logs.go#L33) - [ottllog context README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottllog)

As shown in each of the OTTL context READMEs, more things than just resource attributes are available for comparison and routing. 

From `git blame` it looks like these contexts and the README comment have all been in place for multiple years, so I assume if this functionality was wrong it would have created issues by now. Also, if we ended up changing code to match the README it would be a very impacting and breaking change. For these reasons I believe the README should be updated to be more clear, but I'll have to defer to code owners to know if we're missing something here.

**Comment by bdschaap** [comment]
@crobert-1 Thank you.  Though I've tried routing based on severity text of the log but have been unsuccessful.  Though perhaps I was doing it wrong if the functionality does exist.  It would be great to get confirmation as well as an example added to the docs if the functionality exists .

As a workaround, I've been using 1) the groupbyattrs processor to group logs by the log attribute, 2) the transform processor to create a new resource attribute from the log attribute, and 3) routing processor to route based on the resource attribute.  It's a roundabout approach that complicates the configuration but it does work.

**Comment by bdschaap** [comment]
Gotcha.  Just providing additional context that my experience seemed to align with the documentation and not the previous issue where the crash was fixed.

**Comment by TylerHelmuth** [comment]
The processor's readme is correct: the routingprocessor (and routingconnector) only make decisions based on resource telemetry.  The processor was created before the ottlresource context was added and since it is deprecated it hasn't been updaed.  You can see here how it only takes the resource into account: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/bcc7163f7a8a7c2611fe74ba23f998a7fc0889a2/processor/routingprocessor/logs.go#L107-L111

**Comment by crobert-1** [comment]
Thanks for the reference @TylerHelmuth. I was looking at metrics and should have seen that the transform context was being passed the `nil` datapoint and `pmetric.NewMetric()` rather than actual metrics coming in. 🤦

So the behavior here is that since these are valid OTTL statements they won't raise an error in initialization, but they'll just always fail to match incoming data since there are no attributes to compare against. Is that correct?

**Comment by TylerHelmuth** [comment]
Yes that is correct (and confusing). The routing connect does it correctly: it only uses ottlresource and therefore would allow a statement that uses a field from a log like serverity_text.

**Comment by crobert-1** [comment]
Closing as the README is correct here.
