### ISSUE TITLE
[receiver/podman] lifecycle test failure on windows

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#30561]
### Component(s)

receiver/podman

### Describe the issue you're reporting

This is currently breaking tests in main:

```
--- FAIL: TestComponentLifecycle (0.00s)
    --- FAIL: TestComponentLifecycle/metrics-shutdown (0.00s)
        generated_component_test.go:67: 
            	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/podmanreceiver/generated_component_test.go:67
            	Error:      	Received unexpected error:
            	            	podman receiver is not supported on windows
            	Test:       	TestComponentLifecycle/metrics-shutdown
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/podmanreceiver	0.061s
FAIL
```

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7532146479/job/20502194154 for full logs

**Comment by codeboten** [comment]
Looks like this change broke things: https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/755ae7b44ecfa398c552884ef86f975e89594b1e

**Comment by crobert-1** [comment]
_Looks like a PR is open to resolve this, removing `needs triage`._
