### ISSUE TITLE
[extension/observer/dockerobserver] Remove deprecated use of `host.ReportFatalError`

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30583]
### Component(s)

extension/observer/dockerobserver

### Describe the issue you're reporting

Refactor to remove use of `host.ReportFatalError`, you can use `settings.TelemetrySettings.ReportStatus(component.NewFatalErrorEvent(err))` instead.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30505 for an example.

**Comment by codeboten** [comment]
I don't see a call to host.ReportFatalError in this observer. Closing, please re-open if I'm mistaken

**Comment by atoulme** [comment]
It's used here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c9b9e199eed3a6d178bf8adc277078a477c11cf4/extension/observer/dockerobserver/integration_test.go#L33

Granted, it's just an integration test, but should be possible to move off of it.
