### ISSUE TITLE
[receiver/influxdbreceiver] Remove deprecated use of `host.ReportFatalError`

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30590]
### Component(s)

receiver/influxdb

### Describe the issue you're reporting

Refactor to remove use of `host.ReportFatalError`, you can use `settings.TelemetrySettings.ReportStatus(component.NewFatalErrorEvent(err))` instead.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30505 for an example.

**Comment by codeboten** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30568
