### ISSUE TITLE
[receiver/vcenter] Add support for caching traversing data

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30612]
### Component(s)

receiver/vcenter

### Is your feature request related to a problem? Please describe.

The vCenter receiver currently parses the whole tree on each scrape.

This doesn't scale well when you have a very large structure.

### Describe the solution you'd like

Offer caching of the tree parsed by the receiver, separately from the scraping action.

**Comment by djaglowski** [comment]
This is an interesting idea at a high level but I'm not sure I understand what is being proposed.

First, is parsing the json really the performance bottleneck, or is the goal to avoid requesting such a large structure (if that's even possible).

If we'd still request the same payload, do we just use portions of the raw payload as keys, and the parsed equivalent as values? Is this generalizable or is the cached "typed" e.g. a "vm cache", a "disk cache"? Does the cache need to be purged periodically or does it naturally ?

**Comment by atoulme** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30624 is open for discussion.

**Comment by djaglowski** [comment]
I looked over the PR but still don't understand the intention behind this. From what I can tell, we would _actually_ scrape data in the background every `refresh_ttl` interval. Then, each `collection_interval`, we just return the most recently collected data. Is that right?
