### ISSUE TITLE
Transform opentelemetry spans log event

### ISSUE THREAD

**Issue by strelok29** [open-telemetry/opentelemetry-collector-contrib#30635]
### Component(s)

processor/transform

### Describe the issue you're reporting

I've been working with OpenTelemetry Collector using `opentelemetry-collector-contrib:0.85.0`. I have set up the auto instrumentation using opentelemetry `laravel` auto instrumentation and started receiving spans. but I realized in the spans log event I saw the Token printed out like this.

```
event = Token: abcdefghijklmn......
context = []
level   = info
```
is there a way to maybe hide or transform it into another string? to be something like this

```
event = Token: ********
context = []
level   = info
```

**Comment by crobert-1** [comment]
Hello @strelok29, if the `Token` value is of the same format for all spans you can use the `blocked_values` configuration option of the [redaction processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/redactionprocessor#processor-configuration). If you simply want to drop the key and its value you can do that as well.

Let me know if those options don't work, with more information we can look at other options.

**Comment by mx-psi** [comment]
Closing as wontfix due to lack of response. Feel free to comment to reopen.
