### ISSUE TITLE
kafkaexporter: Keying log and metric data 

### ISSUE THREAD

**Issue by bgranetzke** [open-telemetry/opentelemetry-collector-contrib#30666]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

Prior to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27583, I was able to extend the marshaling logic to add a key to log/metric/trace data.  I understand the reason for making With*Marshaler functions non-exported, but I'm trying to determine the best way to move past being version-locked.

### Describe the solution you'd like

I'm looking for a discussion, but my starting point is a solution that is similar to the `partition_traces_by_id` option.  I'd like to add `partition_logs_by_resource` and `partition_metrics_by_resource` configuration options.

The logic for both would essentially call `pdatautil.MapHash(pcommon.Resource.Attributes())` and use that for the partition key.  Also, pmetric.Metrics/plog.Logs will also need to be split into a sarama.ProducerMessage for each ResourceMetrics/ResourceLogs.

### Describe alternatives you've considered

I also considered an external Kafka Streams re-keying process that would consume the unkeyed topic and re-send to a keyed topic.  I think this works for most of the similar requests for custom marshaler support, but I think message keying is different than a custom format of the payload.  It is a less favored solution because the further away from ingestion we get, the less we can trust ordering.

Another possible option is to fabricate a resource attribute on the agent side and then have a configuration on the kafka exporter for which attribute to use for the message key.  The exporter will still need to break up the payload into multiple ProducerMessages on Resource boundaries.  This is my least favorite option.  This is similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29433, but I'm not a fan of the proposed solution there because I personally would not be able to pick a single, "naturally-occurring" attribute that would be unique enough across all my telemetry producers.

**Comment by crobert-1** [comment]
This mostly duplicates https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29433 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31675, but each have slightly different proposals and scope. Adding references so it's easier to track.

@bgranetzke This is being implemented for metrics in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31315. If you're able, could you provide input there on the proposed solution for metrics? It would be good to know if the PR works for you or not.

**Comment by bgranetzke** [comment]
@crobert-1 That will work for me if we do the same for logs as well.
