### ISSUE TITLE
[connector/spanmetrics] Support multiple instrumentation scopes

### ISSUE THREAD

**Issue by fstab** [open-telemetry/opentelemetry-collector-contrib#30678]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

OpenTelemetry has the concept of [instrumentation scopes](https://opentelemetry.io/docs/concepts/instrumentation-scope/). In most cases, the instrumentation scope is the name and version of the Instrumentation Library.

Here's an example where this is particularly useful: We have an eBPF-based auto-instrumentation tool that produces HTTP spans. However, if an application is already instrumented with an OTel SDK on the on the application level we get duplicate spans: Spans from the OTel SDK and spans from the eBPF tool. Thanks to instrumentation scopes that is not an issue: The spans will have different scopes, and we can use that in the monitoring backend to distinguish these spans.

Now, the spanmetrics connector does not keep the original instrumentation scope, but replaces it with a hard-coded scope name `spanmetricsconnector`. As a result, spans with different scopes are collapsed into the same spanmetrics leading to incorrect results when multiple libraries / tools instrument the same calls.

I think this is the line where the hard-coded `spanmetricsconnector` scope is coming from: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/spanmetricsconnector/connector.go#L257-L258

### Describe the solution you'd like

Keep the original instrumentation scope when producing span metrics.

**Comment by crobert-1** [comment]
It looks like this was an intentional design decision to show that the metrics are being generated from incoming spans in the connector. Context in this [issue](18502) and the [PR](#19216) for it.

Would it work for you to use the `dimensions` or `namespace` config options to differentiate metrics from each other?

**Comment by fstab** [comment]
Thanks @crobert-1. I don't see how to solve this with `dimensions`, maybe I'm missing something.

* The triplet `service.namespace`,`service.name`,`service.instance.id` uniquely identifies an instance of a service. If we choose different values for any of these, then it has to be interpreted as multiple instances, not as a single instance with multiple instrumentation scopes.
* `dimensions` will not differ if the same calls are instrumented with multiple instrumentation scopes. Whatever span attribute we select should have the same value for all instrumentation scopes.

The only way I can see to differentiate multiple instrumentation scopes is to produce spanmetrics with different instrumentation scopes when the incoming spans have different instrumentation scopes.

I also think this issue will become increasingly relevant over time. Maybe today having an eBPF-based instrumentation for a service that's also instrumented with an SDK is an uncommon scenario. However, more and more application frameworks are adding built-in OpenTelemetry support (like Java's Spring Boot for example), and thus duplications of built-in instrumentation and auto-instrumentation will become more common. As I understand it instrumentation scope is intended to differentiate between multiple instrumentations in these cases.

**Comment by fstab** [comment]
An alternative would be to prefix the original instrumentation scope name, something like

```
"spanmetrics/" + <orig scope name>
```

That way we would not reuse the original scope, but still produce different scopes if there are multiple different original scopes.

**Comment by gouthamve** [comment]
Hi I opened the issue about resource attributes and I didn't give scopes much thought tbh. I am not sure setting the scope name to `spanmetrics` makes much sense. The typical usage of the metrics involves setting the namespace to something like `span.metrics`, so that the metrics produced are `span_metrics_calls_total`, etc. 

I think the namespace is much better place to indicate where the metrics are coming from rather than using use OTel scopes.

**Comment by Frapschen** [comment]
As you said 

_Thanks to instrumentation scopes that is not an issue: The spans will have different scopes, and we can use that in the monitoring backend to distinguish these spans_

The key problem is that the spanmetrics processor cannot directly access span instrumentation scopes.

Have you tried the `transformprocessor`? According to its doc, you can modify telemetry based on a configuration like this:
```yaml
transform:
  error_mode: ignore
  trace_statements:
    - context: span
      statements:
        - set(attributes["scope.name"], instrumentation_scope.name)
        - set(attributes["scope.version"], instrumentation_scope.version)
```

then you can add the two span attributes into spanmetrics's `dimensions `

@fstab hope it can help you.

**Comment by sirianni** [comment]
> The key problem is that the spanmetrics processor cannot directly access span instrumentation scopes.

Isn't that the issue to fix?

The `spanmetrics` connector should expose the `name` and `version` fields from the scope as elements that can be set in the `dimensions` configuration.

This is how Datadog trace stats work
```
trace.go.opentelemetry.io_contrib_instrumentation_github.com_gorilla_mux_otelmux.server.hits
trace.go.opentelemetry.io_contrib_instrumentation_net_http_otelhttp.client.hits
trace.io.opentelemetry.jetty_11.0.server.hts
```

Needing to use the `transform` processor is a workaround.  The spanmetrics processor should support this directly.
