### ISSUE TITLE
iis.connection.anonymous should be iis.request.anonymous

### ISSUE THREAD

**Issue by vijayaggarwal** [open-telemetry/opentelemetry-collector-contrib#30696]
### Component(s)

receiver/iis

### What happened?

`anonymous` is a property of request and not of connection. Hence, the metric name should be `iis.request.anonymous` instead of `iis.connection.anonymous`.

### Collector version

all recent versions

**Comment by djaglowski** [comment]
Since this would be a name change, we'll have to use a feature gate to toggle the metric name. [Additional guidance here](https://github.com/open-telemetry/opentelemetry-collector/blob/a952082f73302cfa22880cc7afd933eb0fffac59/docs/scraping-receivers.md?plain=1#L135-L137).

**Comment by vijayaggarwal** [comment]
@djaglowski Thanks for the link to the guidance!

Another approach I can think of is to create a new metric `iis.request.anonymous` and mark `iis.connection.anonymous` deprecated as per the guidance on [removing a default metric](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.92.0/docs/scraping-receivers.md#removing-a-default-metric).

If this approach is acceptable, I will have a slight preference for this approach over the feature gate approach as I feel that transitioning will be simpler for users this way. That said, I leave the final decision to you as you know this better than I do.

**Comment by djaglowski** [comment]
@vijayaggarwal, good suggestion. I think that's fine, as long as the new metric is marked optional.
