### ISSUE TITLE
testbed's `make install-tools` fails to install tools with `go1.16`

### ISSUE THREAD

**Issue by pmalek-sumo** [open-telemetry/opentelemetry-collector-contrib#3069]
**Describe the bug**

testbed's `make install-tools` fails to install tools with `go1.16`

**Steps to reproduce**

1. Use `go1.16`
2. `cd testbed`
3. `make install-tools`

**What did you expect to see?**

No error, tools (`github.com/jstemmer/go-junit-report`) installed.

**What did you see instead?**

```
go install github.com/jstemmer/go-junit-report
missing go.sum entry for module providing package github.com/jstemmer/go-junit-report; to add:
        go mod download github.com/jstemmer/go-junit-report
make: *** [install-tools] Error 1
```

**What version did you use?**

Version: `f1ee616c4d90c4726cb73e4a4e6b4268e382cf66`

**What config did you use?**

Config:  N/A

**Environment**
OS: MacOS
Compiler(if manually compiled): `go 1.16.3`

**Additional context**

This command works without any problem up until (excluding) `go1.16`.

This is due to the [change in go1.16](https://golang.org/doc/go1.16#go-command): 

> **Build commands like go build and go test no longer modify go.mod and go.sum** by default. Instead, they report an error if a module requirement or checksum needs to be added or updated (as if the -mod=readonly flag were used). Module requirements and sums may be adjusted with go mod tidy or go get.

> go install now accepts arguments with version suffixes (for example, go install example.com/cmd@v1.0.0). This causes go install to build and install packages in module-aware mode, ignoring the go.mod file in the current directory or any parent directory, if there is one. This is useful for installing executables without affecting the dependencies of the main module.

This could be rectified by using

```
go install github.com/jstemmer/go-junit-report@latest
```

instead of

```
go install github.com/jstemmer/go-junit-report
```

but this is not supported in `<go1.16`.

**Comment by codeboten** [comment]
Closing this issue.
