### ISSUE TITLE
Incorrect result for memcached.operation_hit_ratio

### ISSUE THREAD

**Issue by vijayaggarwal** [open-telemetry/opentelemetry-collector-contrib#30695]
### Component(s)

receiver/memcached

## Description
The memcached.operation_hit_ratio actually calculates miss ratio instead of hit ratio.

The function `calculateHitRatio()` (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.92.0/receiver/memcachedreceiver/scraper.go#L175) expects arguments in the order (misses, hits) but is being passed arguments in the order (hits, misses). Thus, it actually calculates miss ratio instead of hit ratio.

Also, on a separate note, this metric calculates the ratio since the memcached instance start/restart, and hence the result changes on instance restart. This is counterintuitive in my opinion, as I would expect the metric to represent "recent" hit ratio. Since there is not universal definition of recent, I feel this metric should be deprecated and people should be encouraged to calculate the hit ratio from the memcached.operations metric as per their requirement.

### Collector version

all recent versions

**Comment by djaglowski** [comment]
Thanks for reporting @vijayaggarwal. I'm in support of deprecating the metric.

**Comment by kernelpanic77** [comment]
@djaglowski Can I take this up ?

**Comment by djaglowski** [comment]
Yes, thanks @kernelpanic77

**Comment by kernelpanic77** [comment]
@djaglowski Should we deprecate this metric or disable it in the `metadata.yaml` of `memcachedreciever` ?

**Comment by djaglowski** [comment]
@kernelpanic77 we should follow the process described [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/scraping-receivers.md#removing-a-default-metric).
