### ISSUE TITLE
[mdatagen] support generating lifecycle test in a better way for components don't support windows(or others) 

### ISSUE THREAD

**Issue by fatsheep9146** [open-telemetry/opentelemetry-collector-contrib#30691]
> this configuration can also be used to generate the liftcycle test to skip windows when the component does not support windows

My understanding is that we should be testing all components on all OSes giving that we expect proper error messages and the that the collector configuration can be parsed on different platforms. Not testing the lifecycle on such platforms as of recently risks crashes without proper error message and regressions in this regard, see:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29505
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29553
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28679

_Originally posted by @pjanotti in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30640#issuecomment-1901066155_

As suggested, `mdatagen` should generate the lifecycle test, which could check whether the component who don't support windows(or other platforms) could throw expected error, not crash.

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30640
