### ISSUE TITLE
[all] Use of `component.UseLocalHostAsDefaultHost`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#30702]
### Describe the issue you're reporting

Once open-telemetry/opentelemetry-collector/pull/8622 gets merged and we add a similar package to contrib, we need to use the feature gate in the following components:

- [x] #30818
- [x] #30986
- [x] #30984
- [x] #30982
- [x] #30979
- [x] #30977
- [x] #30843
- [x] #30844
- [x] #30911
- [x] #30823
- [x] #30867
- [x] #30816
- [x] #30819
- [x] #30821
- [x] #30825
- [x] #30845
- [x] Use localhost feature gate on `receiver/jmxreceiver`
- [x] Use localhost feature gate on  `processor/remotetapprocessor`

For each component we should:
1. Change the default configuration to use the helper function
2. Update documentation to say that this feature gate will change the default behavior
3. Update any examples to use `0.0.0.0` if needed

See #30820 for an example

~~This is **on hold** for now, will remove the label and add more detailed instructions when we can move forward with this~~

**Comment by atoulme** [comment]
For processor/remotetapprocessor, given that it's alpha, I will elect to make a direct breaking change. I will post the PR here for review and make sure folks can :+1: / :-1: as needed

**Comment by mx-psi** [comment]
No longer on hold. I marked JMX receiver as done since the endpoint is for an internal OTLP exporter, not for a receiver.

**Comment by atoulme** [comment]
Change of plans for remotetapprocessor, it will use the feature gate after all: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30905
