### ISSUE TITLE
[receiver/splunkenterprise] Add additional Indexer metrics to the Splunk Enterprise receiver

### ISSUE THREAD

**Issue by greatestusername** [open-telemetry/opentelemetry-collector-contrib#30704]
### Component(s)

receiver/splunkenterprise

### Is your feature request related to a problem? Please describe.

No problem. But there are additional useful metrics related to Indexer instances that should to be added. 

E.G. index usage, indexer/bucket total size / avg size, indexing latency, Indexing IOPs/CPU/Raw write, etc

### Describe the solution you'd like

Add additional searches and scraper functions for these indexer specific metrics.

### Describe alternatives you've considered

There really aren't alternatives. They are either added or not.

**Comment by crobert-1** [comment]
_Removed `needs triage` as this was filed by a code owner and is a simple add metrics enhancement._

**Comment by crobert-1** [comment]
I believe this was resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30757.
