### ISSUE TITLE
Add metrics to understand cost of telemetry

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector-contrib#30729]
### Is your feature request related to a problem? Please describe.

I would like to use the collector to understand the cost of telemetry data collection. Usually, observability vendors charge per ingest volume.

### Describe the solution you'd like

I would like to have internal telemetry metrics that will help me understand how much data is collector processing/sending.

I want to understand how much each instrumented process (service) reports bytes. What is average span size and attribute cardinality?

**Comment by crobert-1** [comment]
Am I correct in understanding that you're proposing to add these to the [internal metrics the collector exposes](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/observability.md#current-values)? Would these values be per telemetry pipeline, or for the running collector as a whole?

**Comment by crobert-1** [comment]
Related: https://github.com/open-telemetry/oteps/pull/249
