### ISSUE TITLE
prometheusexporter: metrics plummeted without prior notification.

### ISSUE THREAD

**Issue by shaj13** [open-telemetry/opentelemetry-collector-contrib#30751]
## Description
If the client sends, for instance, sum metrics without configuring AggregationTemporality, which is evidently incorrect, it leads to the otel prometheusexporter.Accumulator discarding those metrics without any prior notification.

example -> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusexporter/accumulator.go#L168

## Steps to Reproduce
send metrics without setting AggregationTemporality.

## Expected Result
Warn/Info Log describes the dropped metrics including a reason.

## Actual Result
The absence of logs necessitates debugging the entire metrics pipeline, encompassing otel and clients. 

### Collector version

latest 

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
I agree that it's good to log in this case to let users know why metrics are being dropped, but I would worry about log spam if it's anything more than `debug`. This isn't really an error or anything wrong in the collector, so it may be better suited to a lower log level. 

If this log message occurs what can be done to resolve the issue? It seems like it would be useful the first time it's seen when debugging, but after that it would be known to the user and then just fill logs from then on.
