### ISSUE TITLE
Hasura Cloud OpenTelemetry Configuration Issue: Data Not Sent to Datadog

### ISSUE THREAD

**Issue by ezopstheta** [open-telemetry/opentelemetry-collector-contrib#30769]
### Component(s)

connector/datadog, exporter/datadog, internal/datadog, receiver/datadog

### Describe the issue you're reporting

Hello OpenTelemetry Team,

I hope this message finds you well. I am encountering an issue with the configuration of OpenTelemetry within Hasura Cloud, specifically with the OpenTelemetry Beta integration. The goal is to send OpenTelemetry data to Datadog for observability purposes.

![Screenshot from 2024-01-24 21-58-43](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/119686681/9ea6d643-c458-48fb-81bb-2c54da71a63d)

I have followed the provided documentation and successfully configured OpenTelemetry on the Datadog agent using the YAML configuration from [this GitHub link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/examples/otlp.yaml). However, it appears that the OpenTelemetry data is not being sent to Datadog.

To provide more context, I have already initiated a support ticket with Hasura as this integration is critical for our observability needs. However, I am reaching out to the OpenTelemetry community for additional insights or assistance that could help in resolving this issue.

References Docs: 

1 - https://hasura.io/docs/latest/observability/cloud/datadog/
2 - https://hasura.io/docs/latest/observability/opentelemetry/
3 - https://docs.datadoghq.com/opentelemetry/collector_exporter/?tab=onahost

I would greatly appreciate any guidance or support you can provide to help resolve this issue. If additional information or logs are required, please let me know.

Thank you for your time and assistance.

**Comment by ezopstheta** [comment]
Any feedback on this?

**Comment by jpkrohling** [comment]
Unless you can provide us with the Collector config showing something that is not working, your best bet is to ask Hasura Cloud.
