### ISSUE TITLE
Be able to include file owner and group as attribute on filelogreceiver

### ISSUE THREAD

**Issue by tprelle** [open-telemetry/opentelemetry-collector-contrib#30775]
### Component(s)

receiver/filelog

### Is your feature request related to a problem? Please describe.

When you want to filter log on a shared host with multiple user, you want to be able to add owner and group of the file log. Currenly this lookup it's not possible so it's hard to filter after.

### Describe the solution you'd like

During the resolver code on the file consumer, we can retrieve these infos

**Comment by djaglowski** [comment]
I think this is reasonable assuming the following:
- By default, this information is not attached.
- When not enabled, there is no performance impact from adding this capability.
- The settings are feature gated until semantic conventions have been established for these attributes.
- We clearly document whether these are applicable to Windows or not and handle appropriately in code.

Additionally, I think we should separate this into two config flags e.g. `include_file_owner` and `include_file_group`, (and two corresponding feature gates).

**Comment by djaglowski** [comment]
Closed by #30776
