### ISSUE TITLE
Document the mute_process_*_error configuration options available in the process scraper

### ISSUE THREAD

**Issue by woody1872** [open-telemetry/opentelemetry-collector-contrib#30779]
### Component(s)
receiver/hostmetrics

### Describe the issue you're reporting
At the time of writing, there are four `mute_process_*_error` configuration options, those are:

```
mute_process_name_error
mute_process_exe_error
mute_process_io_error
mute_process_user_error
```

However, there doesn't appear to be any documentation for these options. It's not clear what they are or why they exist - so they presently exist in the documentation unexplained.

I was looking to modify and test some existing process scraping configuration, and I wanted to understand if any of these options were applicable to the changes I was making, but I was unable to find any information that helped.

**Comment by rogercoll** [comment]
unstale
