### ISSUE TITLE
Multiple channel receiver configuration

### ISSUE THREAD

**Issue by MichaelBriggs-Coralogix** [open-telemetry/opentelemetry-collector-contrib#30799]
### Component(s)

receiver/windowseventlog

### Is your feature request related to a problem? Please describe.

Not related to a problem, necessarily. This feature request is more of a quality of life improvement than a missing feature.

### Describe the solution you'd like

When configuring the windowseventlog receiver, you have to specify a single channel. It's likely that we'll want to monitor multiple channels instead of just one. An option to allow configuration of multiple channels through a single receiver would be useful.

### Describe alternatives you've considered

It's certainly possible to create multiple receivers and add each to your pipeline, but this might be better managed through a single receiver configuration.

**Comment by djaglowski** [comment]
I am not intricately familiar with this receiver but after a quick look I don't see any reason why this couldn't be done. 

In terms of configuration, we could add a `channels` parameter which is mutually exclusive with `channel`, or we could just enhance `channel` to be `[]string` (and continue allowing a single value). Do you seen any problems or have any reservations with this @pjanotti?

**Comment by pjanotti** [comment]
@MichaelBriggs-Coralogix I assume you are not using the other configuration options under `channel` and we could guess that this is true for many other users of the `windowseventlog` receiver. However, options like `exclude_providers`, `storage` (check-pointing) should be configurable per `channel`, so it seems that we would have to support something like
```yaml
receivers:
    windowseventlog:
        - channel: application
          excluded_providers: [abc, xyz]
        - channel: system
```
which is breaking change. If we go with `channels` custom configs like `storage` can't be applied automatically to all specified channels.

It is almost easier to start with a new receiver just to support that convenience. It seems very low priority to me.

**Comment by MichaelBriggs-Coralogix** [comment]
@pjanotti @djaglowski 

Correct, I haven't used any of the exclude_providers in my configuration. Though I suspect starting with the ability to do multiple channels with the same excluded_providers, and then creating secondary exporter configurations for channels that need different exclusions would still be preferable, and shouldn't require as large of a change.
