### ISSUE TITLE
[flaky test][receiver/collectdreceiver] Lifecycle test failing due to bind: address already in use

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#30805]
### Component(s)

receiver/collectd

### Describe the issue you're reporting

Failure link: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7673900683/job/20917582102?pr=30803

```
go test -race -timeout 300s -parallel 4 --tags="" ./...
?   	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/collectdreceiver/internal/metadata	[no test files]
--- FAIL: TestComponentLifecycle (0.00s)
    --- FAIL: TestComponentLifecycle/metrics-lifecycle (0.00s)
        generated_component_test.go:82: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/collectdreceiver/generated_component_test.go:82
            	Error:      	Received unexpected error:
            	            	listen tcp 127.0.0.1:8081: bind: address already in use
            	Test:       	TestComponentLifecycle/metrics-lifecycle
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/collectdreceiver	1.046s
FAIL
make[2]: *** [../../Makefile.Common:124: test] Error 1
```

**Comment by crobert-1** [comment]
It looks like the lifecycle test starts a [receiver, shuts it down, then starts another with the exact same config](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d418cbd63fa2e543857d8889d6ae439b868b1240/receiver/collectdreceiver/generated_component_test.go#L53-L58), binding to [the same endpoint](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d418cbd63fa2e543857d8889d6ae439b868b1240/receiver/collectdreceiver/factory.go#L21).

I believe there may be a goroutine leak going on here that's causing this, judging by the context of the test failure, the low frequency of the test failure, and the fact that `goleak` isn't enabled for this package (meaning it has a failure, at least intermittently).

**Comment by atoulme** [comment]
Appreciated, it looks like the tests are catching an interesting issue. Thanks for the report.
