### ISSUE TITLE
Use localhost feature gate on `extension/healthcheck`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#30818]

**Comment by mx-psi** [comment]
@dmitryax @bogdandrutu on open-telemetry/opentelemetry-collector/pull/2828 we changed this to `0.0.0.0`. Do we want to revert this change?

**Comment by mx-psi** [comment]
Also cc @mwear @jpkrohling

**Comment by jpkrohling** [comment]
Yes! Health check and monitoring ports are exactly the cases where we want to use local addresses (127.0.0.1) vs. broader ones (0.0.0.0)
