### ISSUE TITLE
[internal/azure] Move cluster name discovery mechanism to an internal package

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#30834]
Extract the logic to fetch k8s.cluster.name from `exporter/datadogexporter` to `internal/azure` and use it in `processor/resourcedetectionprocessor/internal/azure/aks`. 

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29328#discussion_r1445482243 for more details

**Comment by jsirianni** [comment]
Sounds good, will take care of it.

**Comment by jsirianni** [comment]
@dmitryax I was taking a look at this and I am wondering where the new package should live? I cannot call resource detection's [parse cluster name function](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/internal/azure/aks/aks.go#L95) (after exporting it) as it is part of an internal package.

```
package github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter/internal/hostmetadata/internal/azure
	provider.go:14:2: use of internal package github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal/azure/aks not allowed
```

Also, there are small differences between the two implementations. Resource detection is stricter and requires exactly four values after splitting the string. Datadog's implementation returns an error. Error handling won't be an issue but I am concerned about modifying datadog's cluster name handling.

**Comment by dmitryax** [comment]
It should be a new module called `azure` inside https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal. It'll be available for all the packages in this repo. 

Try to consolidate the logic in a way that makes sense and let DataDog folks to review
