### ISSUE TITLE
Remove tests from cmd/otelcontribcol

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30884]
### Component(s)

cmd/otelcontribcol

### Describe the issue you're reporting

Those tests take a long time to compile and slow down execution of CI. They are replaced by generated tests.

**Comment by crobert-1** [comment]
The problem was generally discussed in the Collector sig meeting today, it sounds like suggestions are welcome to alleviate this. Removing `needs triage`.

**Comment by mowies** [comment]
if this is still relevant, it will be fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34844
