### ISSUE TITLE
[receiver/prometheus] update github.com/prometheus/prometheus to v0.49.1 breaks build

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#30883]
### Component(s)

receiver/promethues

### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7715094549/job/21028827561?pr=30881

### Collector version

mainline

**Comment by dashpole** [comment]
PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30881

**Comment by crobert-1** [comment]
The `NewManager` function signature was updated to require an extra registerer argument, and now also return an error in addition to the newly created manager. [Reference](https://pkg.go.dev/github.com/prometheus/prometheus@v0.49.1/scrape#NewManager)

It's a trivial change for the receiver to handle a returned error, I'm not familiar enough to know how much effort is required to pass in a [prometheus](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus).[Registerer](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#Registerer) variable.

Prometheus change that caused issue: https://github.com/prometheus/prometheus/commit/5752050b42195d87d7dd0760f7ec3b088f115cd3
