### ISSUE TITLE
cicd: contrib tests are taking too long

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#30880]
### Describe the issue you're reporting

The contrib-tests job in the collector core repo runs all the tests and takes upwards of 45min to complete. This leads to long wait times for even simple PRs like dependency updates.

**Comment by TylerHelmuth** [comment]
We run the Contrib tests to check if changes we make in Core are gonna break Contrib right? But when we do breaking changes that are definitely gonna break Contrib the PR gets merged and we go update contrib right?

**Comment by TylerHelmuth** [comment]
Some quick ways we could speed up the tests:
1. do not block the build-and-test from continuing on e2e/integration tests
2. remove tests from otelcontribcol
3. Maybe more parallelization for unit/lint

**Comment by atoulme** [comment]
I can volunteer for 2.

**Comment by TylerHelmuth** [comment]
A harder think to investigate: I am pretty sure our cache just doesnt work and we re-download dependencies every single time we need them

**Comment by atoulme** [comment]
> A harder think to investigate: I am pretty sure our cache just doesnt work and we re-download dependencies every single time we need them

Maybe a run without cache would tell us if there's a time difference as a way to verify your hunch

**Comment by TylerHelmuth** [comment]
> A harder think to investigate: I am pretty sure our cache just doesnt work and we re-download dependencies every single time we need them

I take this back, I see evidence of the cache working

**Comment by TylerHelmuth** [comment]
For integration tests, there are a couple things I'd like to change:
1. Enforce `go:build integration` is only used in a file called `*integration_test.go`
2. Add more parallelism.  This is tricky because most of the jobs are in the receivers (I think all but 2), so splitting by component type isnt very helpful.

**Comment by TylerHelmuth** [comment]
Reading through the merge queue doc I am definitely curious to try it out.  It looks to PR at the front of the queue must pass required checks against the latest commit to merge and is kicked out of the queue if there are new conflicts.

**Comment by mx-psi** [comment]
Will wait until end of week to raise a request to enable this on the community repository. @open-telemetry/collector-contrib-approvers if you disagree please speak up before then

**Comment by mx-psi** [comment]
Should we use https://github.com/gotestyourself/gotestsum ? Among other benefits we can detect the slowest tests that way

**Comment by mx-psi** [comment]
Requested enabling the merge queue on open-telemetry/community/issues/1936
