### ISSUE TITLE
Need to make Docker API Version default to 1.24+

### ISSUE THREAD

**Issue by samiura** [open-telemetry/opentelemetry-collector-contrib#30900]
### Describe the issue you're reporting

Currently, the Docker Observer's client API version is set to 1.22 as default. But due to this [change](https://github.com/moby/moby/commit/08e4e88482d640b9543d4ba6332109e6b6f2495d) on Docker upstream project, we need to make the Client API version default to 1.24. Most of the other projects except Otel have already updated. Also this impending [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30853) once merged will cause problems like the following error message below. Right now, if someone uses the latest Docker API version 1.44, otel collector's docker observer will throw the following error: 

    _"Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"_

**Comment by samiura** [comment]
@atoulme thanks for adding the labels.

**Comment by jamesmoessis** [comment]
As a rule of thumb we are just trying to keep the API at minimum version as possible. Seems like this change in docker means that the minimum becomes 1.24, so I think we should do it. Would need dockerstatsreceiver changes too.

**Comment by luckwings** [comment]
Now, the Client Docker API version is 1.44
When I try "docker pull wordpress:latest", I have an error:

error during connect: this error may indicate that the docker daemon is not running: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=wordpress&tag=latest": open //./pipe/docker_engine: The system cannot find the file specified.

Please help me
