### ISSUE TITLE
[pkg/golden]: Make metric timestamp normalization optional

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#30919]
### Component(s)

pkg/golden

### Is your feature request related to a problem? Please describe.

Right now, I'm writing some tests for doing some metric filtering. One thing I do in this filtering is filtering based on a timestamp. 

Unfortunately, golden.WriteMetrics modifies the timestamp so they are always the same. But my input metrics need a diff in the timestamps in order to test the filtering!

In this case, I'd like to skip the timestamp normalization when writing out the metrics to file. 

### Describe the solution you'd like

I'm thinking of adding some functional options to WriteMetrics
```go
func WriteMetrics(t testing.TB, filePath string, metrics pmetric.Metrics, opts ...WriteMetricsOption) error
```
Then have a `SkipMetricTimestampNormalization` option that can be specified when writing goldens.

**Comment by BinaryFissionGames** [comment]
This issue can be assigned to me.

**Comment by djaglowski** [comment]
Makes sense to me. This normalization functionality was designed with git diffs in mind, but it should be possible to skip it if desired.
