### ISSUE TITLE
Consider allowing configuring journald receiver to turn on `--all` flag

### ISSUE THREAD

**Issue by meridional** [open-telemetry/opentelemetry-collector-contrib#30920]
### Component(s)

journald receiver.

### Is your feature request related to a problem? Please describe.

Currently, journald receiver works by piping data from 
`journalctl -u <unit> -output=json ...`.

Without `--all` flag, journalctl will output a json object where `.MESSAGE=null` if the message has more than 4096 characters  (see https://man7.org/linux/man-pages/man1/journalctl.1.html), effectively dropping the log line.

### Describe the solution you'd like

Add a configuration to journald receiver to allow users to turn on the `--all` flag. This config defaults to be turned off.

### Describe alternatives you've considered

Add `--all` flag unconditionally. This might have performance implications as indicated by journalctl documentation.

**Comment by djaglowski** [comment]
Seems reasonable to me as long as it's optional and off by default. WDYT @sumo-drosiek?

**Comment by sumo-drosiek** [comment]
Totally agree. This flag seems to be worth to add it.

@meridional Would you like to add it by yourself? I can do it if not :)

**Comment by meridional** [comment]
> Totally agree. This flag seems to be worth to add it.
> 
> @meridional Would you like to add it by yourself? I can do it if not :)

Yes, I can take a stab at it.

**Comment by sumo-drosiek** [comment]
I will have to look at it closer. @RobertFloor Could you share example logs, and what do you expect them to be?
I don't think we can easily switch from JSON output to another one, so I am thinking more about some postprocessing and converting from byte array to string

**Comment by RobertFloor** [comment]
Hi unfortunately I cannot provide company logs, but this example shows the gist of it:

```bash
# We add binary data to a journalctl log
-bash-4.3# printf "hey\rho\n" | systemd-cat -t HOLA

# It is shown as binary 
-bash-4.3# journalctl -t HOLA --no-pager -q
systemd-testsuite HOLA[251]: [6B blob data]

# JSON logging creates a byte array 
-bash-4.3# journalctl -t HOLA --no-pager -q -o json
{......,"MESSAGE":[104,101,121,13,104,111],"....."}

# JSON logging creates a byte array, --all has no effect 
-bash-4.3# journalctl -t HOLA --no-pager -q -o json --all
{......,"MESSAGE":[104,101,121,13,104,111],"....."}

# This shows the binary data
journalctl -t HOLA --no-pager -q  --all
HOLA[3416096]: hey
```

This behavior is necessary, otherwise, a non-printable character would break the json structure

```bash
$ printf '{"key": "value\rvalue"}' | jq
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 1, column 21
```

I agree that not using json is impossible, but the ``--all`` option will never have an effect as it is implemented currently.

**Comment by sumo-drosiek** [comment]
> This behavior is necessary, otherwise, a non-printable character would break the json structure

Yes, but we could convert it to the following form (which is correct as I think):

```
➜  ~ printf '{"key": "value\\rvalue"}' | jq
{
  "key": "value\rvalue"
}
```
