### ISSUE TITLE
Collector fails to start when `system` detector cannot obtain FQDN of the host

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#3092]
**Problem description**
If we have OTel Collector with `system` detector enabled (resource detection processor), running on a VM that cannot provide fully qualified domain name for a reason, the collector is failing to start. The detector tries to set FQDN to `host.name` resource attribute, but  [OTel conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/host.md#host) don't specify that it has to be FQDN. So I don't see a reason why it should be failing.

**Suggested solutions**
I see two options to solve the problem:
1. If FQDN cannot be provided by the system, fall back to `os.Hostname()`
2. Introduce another resource attribute, e.g. `host.fqdm` which (if present) will always contain fully qualified domain name of the host.

@jrcamp @mx-psi @tigrannajaryan thoughts?

**Comment by tigrannajaryan** [comment]
>If FQDN cannot be provided by the system, fall back to os.Hostname()

This sounds right to me given that Otel conventions say:

>host.name - Name of the host. On Unix systems, it may contain what the hostname command returns, or the fully qualified hostname, or another name specified by the user.


Regarding your second point:

>Introduce another resource attribute, e.g. host.fqdm which (if present) will always contain fully qualified domain name of the host.

Yes, we can do it in the future if necessary. For now I would suggest to go with option 1.

**Comment by mx-psi** [comment]
I opened #3099 to fix this using option 1, PTAL
