### ISSUE TITLE
Sharecomponent logic lacks error support

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector-contrib#30924]
## Expected Result

In migrating the otel-arrow code base into this repository, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30766, we observe that the "sharedcomponent" library in this repo is different than the one in core, and deficient in terms of error handling support.

The GetOrCreate() method does not allow the function to return an error. This means the object will be cached whether the constructor succeeds or not, which means that subsequent calls to get the shared component will get an object for which the (shared) constructor returned an error, but the subsequent caller will not see the error.  

## Actual Result

Notice that the same library in the core repo, which the OTLP receiver uses, allows errors and does not update the cache when there is an error:

https://github.com/open-telemetry/opentelemetry-collector/blob/main/internal/sharedcomponent/sharedcomponent.go

### Collector version

v0.93.0

### Environment information

n/a

### OpenTelemetry Collector configuration

```yaml
n/a
```

### Log output

```shell
n/a
```

### Additional context

The core library also supports generics, which is slightly easier to use. Can we unify these two libraries?

**Comment by jmacd** [comment]
IMO this change, adapting to a library without error support, both introduces a potential bug --GetOrCreate() returns an object for which an error was already generated -- and yields less-readable code: [fce4631](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30766/commits/fce4631867347440311cb34c1afd46153f52b8a7)

**Comment by atoulme** [comment]
The goal is to move sharedcomponent from contrib and adopt it from core once it is promoted to component/sharedcomponent. See https://github.com/open-telemetry/opentelemetry-collector/issues/4266
