### ISSUE TITLE
Missing release notes for v0.93.0

### ISSUE THREAD

**Issue by danelson** [open-telemetry/opentelemetry-collector-contrib#30922]
### Describe the issue you're reporting

The [v0.93.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.93.0) release does not have any release notes. They are however visible in the [changelog](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.93.0/CHANGELOG.md). Could this be updated?

**Comment by codeboten** [comment]
This has been fixed now. Thanks for opening the issue @danelson
