### ISSUE TITLE
receiver/postgresql: bump PostgreSQL minimal supported version to latest official supported

### ISSUE THREAD

**Issue by kevinnoel-be** [open-telemetry/opentelemetry-collector-contrib#30923]
### Component(s)

receiver/postgresql

### Is your feature request related to a problem? Please describe.

I see that this receiver is marked as supporting PG 9.6+ in the [README](https://github.com/collibra/opentelemetry-collector-contrib/blob/816671e3a2378b40c1d24114a09efc93b0c2e63d/receiver/postgresqlreceiver/README.md?plain=1#L24). Do we still want to keep this much backwards compatibility given that this is quite an old, and unsupported for 2+ years, version now ([list of PG versions here](https://www.postgresql.org/support/versioning/)). It seems that the latest supported version is PG 12 with still ~9 months of support and we should maybe align on this?
This can make improvements, using more recent features (a bit?) harder or use less maintained/out-of-date modules versions (e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30831)

### Describe the solution you'd like

Update the prerequisites requirements for using this receiver (+ integration tests) to the latest officially supported PostgreSQL version

**Comment by djaglowski** [comment]
I'm in support of this. Let's leave the issue open for a couple weeks so others can weigh in.

**Comment by djaglowski** [comment]
No one has argued otherwise. I suggest we initially add a deprecation warning to the changelog, then remove in a subsequent version.

**Comment by kevinnoel-be** [comment]
Created following PR for adding a deprecation notice in the changelog: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32093
