### ISSUE TITLE
translate messaging conventions to Elastic destination fields in Elastic exporter

### ISSUE THREAD

**Issue by gbanasiak** [open-telemetry/opentelemetry-collector-contrib#3093]
**Is your feature request related to a problem? Please describe.**

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/671 introduced translation of `http.*` and `db.*` semantic conventions into Elastic equivalent, i.e. `span.destination.*` fields. The missing bit are `messaging.*` [conventions ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md) which make service map presentation of services using components such as Kafka or RabbitMQ incomplete.

**Describe the solution you'd like**

Expand [existing translation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.24.0/exporter/elasticexporter/internal/translator/elastic/traces.go#L293-L349) to include `messaging.*` conventions.

**Describe alternatives you've considered**

The alternative would be to use semantic convention for which translation exists (e.g. `db.*`) while manually instrumenting messaging spans, but that's hacky.

**Comment by cyrille-leclerc** [comment]
Thanks @gbanasiak .

As Elastic Observability is adding native support for the OpenTelemetry Protocol (OTLP) with the purpose of removing the need for the OpenTelemetry Collector exporter for Elastic, we will solve this problem directly in Elastic APM Server.

I have recopied your issue on https://github.com/elastic/apm-server/issues/5094.

**Comment by paulgrav** [comment]
@cyrille-leclerc Do you recommend that users continue to use the Elastic exporter? Does this mean that improvements to the Elastic exporter will cease?

**Comment by cyrille-leclerc** [comment]
@paulgrav we are working hard at making the native support for OTLP on Elastic Observability / Elastic APM Server generally available as soon as possible. Once it's done, we will deprecate the Otel Collector for Elastic and users will be able to keep the same architecture with the same OpenTelemetry Collector replacing the elastic exporter by an OTLP exporter. It will also be possible to have Otel Agents (java, node.js...) sending OTLP data directly to Elastic Observability / Elastic APM Server.

Please note that recent improvements brought on the native OTLP support in Elastic Observability / Elastic APM Server are unfortunately not backported to the OpenTelemetry Collector Exporter for Elastic, we focus our energy on the native support.

**Comment by paulgrav** [comment]
@cyrille-leclerc That makes complete sense. Thanks for the update.

**Comment by cyrille-leclerc** [comment]
FYI we are progressing on this topic, see https://github.com/elastic/apm-server/issues/5094

**Comment by atoulme** [comment]
Since the elastic exporter has been removed, can this issue now be closed please?
