### ISSUE TITLE
Http semantic convention breaking changes in 1.23

### ISSUE THREAD

**Issue by wangzlei** [open-telemetry/opentelemetry-collector-contrib#30935]
## Description

http semantic convention 1.23.0 is declared as stable and introduces some attribute changes. For example, `AttributeHTTPMethod` is from **http.method** to **http.request.method**. Now most of language SDKs have moved to the latest http semantic convention and removed support environment variable `OTEL_SEMCONV_STABILITY_OPT_IN`.

Right now some vendors' exporter in Collector have translation logic like
```
import conventions "go.opentelemetry.io/collector/semconv/v1.6.1"

span.Attributes().Range(func(key string, value pcommon.Value) bool {
		switch key {
		case conventions.AttributeHTTPMethod:  // only handle http.method, cannot handle http.request.method
			translate to vendor's span format...
```
If we cannot control what version of OTel SDK user is using, how does Collector ensure both forward and backward compatibility?

## Expected Result
OTel Collector can handle both old and new version of SDK.

### Collector version

0.93.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jsultana-leap** [comment]
Thanks so much for the quick PR to address this :) Can I ask when the fix will be released in a new version?
