### ISSUE TITLE
Default collector config is not created on startup

### ISSUE THREAD

**Issue by pranavmarla** [open-telemetry/opentelemetry-collector-contrib#3097]
**Describe the bug**
As per the [collector documentation](https://opentelemetry.io/docs/collector/getting-started/), when the agent is installed on a Linux machine, it should automatically create a default config file:

> Every Collector release includes DEB and RPM packaging for Linux amd64/arm64 systems. The packaging includes a default configuration that can be found at /etc/otel-collector/config.yaml post-installation.
...
By default, the otel-collector systemd service will be started with the --config=/etc/otel-collector/config.yaml option after installation.

However, when I tried that out on an Ubuntu machine, it only worked for the _core_ collector -- the _contrib_ collector did not create a default config file, and failed to start up!

**Steps to reproduce**
- Download `v0.24.0` of the contrib collector deb file ([otel-contrib-collector_0.24.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.24.0/otel-contrib-collector_0.24.0_amd64.deb)) onto an Ubuntu machine
- Install: `dpkg --install otel-contrib-collector_0.24.0_amd64.deb`

**What did you expect to see?**
I expect to see the same behaviour that I see with the core collector ([otel-collector_0.24.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector/releases/download/v0.24.0/otel-collector_0.24.0_amd64.deb)) -- specifically:
- When I check collector status after installation, it should be running and should mention the default config file:
```
> systemctl -l status otel-collector
● otel-collector.service - OpenTelemetry Collector
   Loaded: loaded (/lib/systemd/system/otel-collector.service; enabled; vendor preset: enabled)
   Active: active (running) since ...
 ...
   CGroup: /system.slice/otel-collector.service
           └─... /usr/bin/otelcol --config=/etc/otel-collector/config.yaml

```

**What did you see instead?**
- When I check collector status after installation, it is not running:
```
> systemctl -l status otel-contrib-collector
● otel-contrib-collector.service - OpenTelemetry Contrib Collector
   Loaded: loaded (/lib/systemd/system/otel-contrib-collector.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
```
- If I look inside the `/etc` folder, there is no default collector config file
- If I manually restart the agent, it fails to start:
```
> systemctl restart otel-contrib-collector
> systemctl -l status otel-contrib-collector
● otel-contrib-collector.service - OpenTelemetry Contrib Collector
   Loaded: loaded (/lib/systemd/system/otel-contrib-collector.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-04-13 15:09:20 EDT; 2s ago
  Process:  ExecStart=/usr/bin/otelcontribcol --config /etc/otel-contrib-collector/config.yaml (code=exited, status=
 Main PID:  (code=exited, status=1/FAILURE)

Apr 13 15:09:20 ip-10-249-29-79 systemd[1]: otel-contrib-collector.service: Main process exited, code=exited, status=1/F
Apr 13 15:09:20 ip-10-249-29-79 systemd[1]: otel-contrib-collector.service: Failed with result 'exit-code'.
Apr 13 15:09:20 ip-10-249-29-79 systemd[1]: otel-contrib-collector.service: Service hold-off time over, scheduling resta
Apr 13 15:09:20 ip-10-249-29-79 systemd[1]: otel-contrib-collector.service: Scheduled restart job, restart counter is at
Apr 13 15:09:20 ip-10-249-29-79 systemd[1]: Stopped OpenTelemetry Contrib Collector.
Apr 13 15:09:20 ip-10-249-29-79 systemd[1]: otel-contrib-collector.service: Start request repeated too quickly.
Apr 13 15:09:20 ip-10-249-29-79 systemd[1]: otel-contrib-collector.service: Failed with result 'exit-code'.
Apr 13 15:09:20 ip-10-249-29-79 systemd[1]: Failed to start OpenTelemetry Contrib Collector.
```
- If I look at `journalctl`, I can see that the reason it fails to start is because it cannot find any config file:
```
> journalctl -u otel-contrib-collector
-- Logs begin at Mon 2021-03-08 03:06:12 EST, end at Tue 2021-04-13 15:54:46 EDT. --
Apr 13 15:09:19 ip-10-249-29-79 systemd[1]: Started OpenTelemetry Contrib Collector.
Apr 13 15:09:19 ip-10-249-29-79 otelcontribcol[...]: 2021-04-13T15:09:19.548-0400        info        service/application.go:280        Starting OpenTelemetry Contrib Collector...        {"Version": "v0.24.0", "GitHash": "f564404d", "NumCPU": 2}
...
Apr 13 15:09:19 ip-10-249-29-79 otelcontribcol[...]: 2021-04-13T15:09:19.552-0400        info        service/application.go:250        Loading configuration...
Apr 13 15:09:19 ip-10-249-29-79 otelcontribcol[...]: Error: cannot load configuration: error loading config file "/etc/otel-contrib-collector/config.yaml": unable to read the file /etc/otel-contrib-collector/config.yaml: open /etc/otel-contrib-collector/config.yaml: no such file or directory
Apr 13 15:09:19 ip-10-249-29-79 otelcontribcol[...]: 2021/04/13 15:09:19 application run finished with error: cannot load configuration: error loading config file "/etc/otel-contrib-collector/config.yaml": unable to read the file /etc/otel-contrib-collector/config.yaml: open /etc/otel-contrib-collector/config.yaml: no such file or directory
Apr 13 15:09:19 ip-10-249-29-79 systemd[1]: otel-contrib-collector.service: Main process exited, code=exited, status=1/FAILURE
```

**What version did you use?**
`v0.24.0` of the contrib collector ([otel-contrib-collector_0.24.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.24.0/otel-contrib-collector_0.24.0_amd64.deb))

**What config did you use?**
None -- I was relying on the collector to create its own config file by default

**Environment**
OS: `Ubuntu 18.04`

**Additional context**
N/A

**Comment by Jammicus** [comment]
Inspecting the deb it seems that the /etc/ directory is missing 

```
root@1892009c82f3:/# dpkg -c otel-contrib-collector_0.24.0_amd64.deb
drwxrwxr-x otel/otel         0 2021-04-06 22:59 ./
drwxr-xr-x otel/otel         0 2021-04-06 22:59 ./usr/
drwxr-xr-x otel/otel         0 2021-04-06 22:59 ./usr/share/
drwxr-xr-x otel/otel         0 2021-04-06 22:59 ./usr/share/doc/
drwxr-xr-x otel/otel         0 2021-04-06 22:59 ./usr/share/doc/otel-contrib-collector/
-rw-r--r-- otel/otel       176 2021-04-06 22:59 ./usr/share/doc/otel-contrib-collector/changelog.gz
drwxr-xr-x otel/otel         0 2021-04-06 22:59 ./usr/bin/
-rwxr-xr-x otel/otel 136748576 2021-04-06 22:57 ./usr/bin/otelcontribcol
drwxr-xr-x otel/otel         0 2021-04-06 22:59 ./lib/
drwxr-xr-x otel/otel         0 2021-04-06 22:59 ./lib/systemd/
drwxr-xr-x otel/otel         0 2021-04-06 22:59 ./lib/systemd/system/
-rw-r--r-- otel/otel       270 2021-04-06 22:54 ./lib/systemd/system/otel-contrib-collector.service
```

Suspect this this the same for the RPM as well, I've raised the following to fix this: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3122
