### ISSUE TITLE
[cmd/mdatagen] Provide config with all metrics disabled

### ISSUE THREAD

**Issue by braydonk** [open-telemetry/opentelemetry-collector-contrib#30993]
### Component(s)

cmd/mdatagen

### Is your feature request related to a problem? Please describe.

There are some scenarios where it would be nice to easily receive a metric builder config with all metrics disabled. (Example scenario in Additional Context)

### Describe the solution you'd like

I would like to add a new function called `DefaultMetricsConfigAllDisabled` (or something to that effect) to the generation template that will provide a metric builder config with all metrics disabled.

### Describe alternatives you've considered

Currently the only way to do this is to get a default config and manually set all the metrics enabled fields to false, or to use reflection.

### Additional context

I encountered a scenario in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30894 where this would have been useful. I would have liked to be able to provide a test where only 2 of the metrics in the config were enabled, but it would have been very repetitive to write disabling every other metric. This also applies to how I would have liked to provide fields on the `processscraper` config that might enable/disable groups of metrics for convenience.

**Comment by braydonk** [comment]
I know this is moving to collector core soon, but I opted to open the issue and PR here for now and will move it over if/when needed.

**Comment by crobert-1** [comment]
_Sounds good to me, removing `needs triage`._

**Comment by braydonk** [comment]
Closing in favour of #31285
