### ISSUE TITLE
[Spanmetrics processor] - Exemplars for calls_total metric

### ISSUE THREAD

**Issue by aishyandapalli** [open-telemetry/opentelemetry-collector-contrib#31009]
### Is your feature request related to a problem? Please describe.

Hello team, I am trying to add exemplars to **calls_total** metric for RED metrics and I tried calling **setExemplars** method [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/processor.go#L327). But, I see the calls_total metric is being dropped to decimals. For example, we have a service that have 14k calls/sec but the metric is being dropped to 0.5 calls/sec. Removing setExemplars method fixes the issue.

Any insights here would really help. Thanks in advance

### Describe the solution you'd like

I've tried restricting the number of exemplars to 5 per datapoint and it seems to work fine

### Describe alternatives you've considered

I've tried restricting the number of exemplars to 5 per datapoint and it seems to work fine

**Comment by mx-psi** [comment]
The spanmetrics processor is deprecated, but I believe this issue is also applicable to the spanmetrics connector. Should we relabel with spanmetrics connector @crobert-1 ?

**Comment by crobert-1** [comment]
> The spanmetrics processor is deprecated, but I believe this issue is also applicable to the spanmetrics connector. Should we relabel with spanmetrics connector @crobert-1 ?

Agreed, thanks for calling this out @mx-psi!

**Comment by crobert-1** [comment]
Hello @aishyandapalli, can you share some more context around this change? Are you attempting to add this as a feature to the processor/connector?

> I tried calling setExemplars method [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/processor.go#L327).

Can you share what the method call looks like that you're adding? It would be helpful to see what the inputs are to further debug.

**Comment by aishyandapalli** [comment]
We have worked this out with spanmetrics connector and it looks good now. We completely moved from processor to connector and everything looks fine now. Closing the issue
