### ISSUE TITLE
[exporter/syslog] Support octet framing on syslog exporter messages

### ISSUE THREAD

**Issue by sinkingpoint** [open-telemetry/opentelemetry-collector-contrib#31013]
### Component(s)

exporter/syslog

### Is your feature request related to a problem? Please describe.

Some non open telemetry syslog receivers (e.g. syslog-ng's syslog driver) expect that rfc5424 messages come with rfc6587 octet framing, but this isn't supported in the open telemetry syslog exporter

### Describe the solution you'd like

I would like to see a config value in the syslog exporter that allows toggling on and off octet counting

**Comment by sinkingpoint** [comment]
I note that the syslog _receiver_ supports sending it: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/syslogreceiver

**Comment by astencel-sumo** [comment]
This is correct, this feature was missing from the Syslog exporter. Thank you for contributing it! :pray:
