### ISSUE TITLE
awsemf exporter tests fails if a valid aws configuration is found locally

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#31010]
### Component(s)

exporter/awsemf

### Describe the issue you're reporting

Running the command `make -C exporter/awsemfexporter test` to run the unit tests for awsemfexporter fails when a valid configuration is present on the system. 

Ideally the tests shouldn't be impacted by the configuration on the local system

**Comment by berkeli** [comment]
Happy to look into this one

**Comment by bryan-aguilar** [comment]
Thank you @berkeli! Give me a shout if you run into any issues.

**Comment by berkeli** [comment]
Hi @bryan-aguilar could you tell me which config needs to be present for tests to fail?

I've tried with a local otel config file but tests work fine

**Comment by bryan-aguilar** [comment]
I believe it is a set of valid AWS credentials. Which should be in `~/.aws/`. It may honestly be for any set of valid credentials because the go sdk will use it's standard tool chain. https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials
