### ISSUE TITLE
[exporter/clickhouse] Update module github.com/clickhouse/clickhouse-go/v2 to v2.18.0 breaks build

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#31087]
### Component(s)

exporter/clickhouse

### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31065. 

> Error: ../../internal/docker/docker.go:245:28: cannot use event.Action (variable of type events.Action) as string value in argument to zap.String

github.com/clickhouse/clickhouse-go/v2 v2.18.0 depends on github.com/docker/docker v25.0.1+incompatible. That is not compatible with the version used in this repo: v24.0.8+incompatible

### Collector version

mainline

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by samiura** [comment]
fwiw, I'm getting similar issues when upgrading  a dependency github.com/hashicorp/vault in our distribution

**Comment by samiura** [comment]
This should take care of the problem->  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31658

**Comment by songy23** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31658
