### ISSUE TITLE
[pkg/stanza/operator/parser/regex] Leaking goroutine when cache size is set to non-zero

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#31093]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

While working on adding `goleak` checks to the `pkg/stanza/operator/parser/regex` package as a part of #30438, I found the following leak:
```
=== RUN   TestMemory
=== RUN   TestMemory/basic
--- PASS: TestMemory (0.00s)
    --- PASS: TestMemory/basic (0.00s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 20 in state sleep, with time.Sleep on top of the stack:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:195 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex.(*atomicLimiter).init.func1.1()
	/Users/crobert/dev/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex/cache.go:162 +0xf8
created by github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex.(*atomicLimiter).init.func1 in goroutine 19
	/Users/crobert/dev/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex/cache.go:157 +0x56
]
```
(More tests are failing, but this is a good basic example of the leak)

The `regex` parser [has an in-memory cache](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/dcf66ce0a5a9a9cf804ce045fdef8d1401cc4d7c/pkg/stanza/operator/parser/regex/regex.go#L83) that starts an atomic rate limiter [upon initialization](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/dcf66ce0a5a9a9cf804ce045fdef8d1401cc4d7c/pkg/stanza/operator/parser/regex/cache.go#L30). This rate limiter [runs in a background goroutine indefinitely](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/dcf66ce0a5a9a9cf804ce045fdef8d1401cc4d7c/pkg/stanza/operator/parser/regex/cache.go#L157), without any way to stop it.

We need to add a `Stop` method that can be called during components' shutdown that properly stops this goroutine.

**Comment by djaglowski** [comment]
Thanks for documenting it. I'll take a look.
