### ISSUE TITLE
process.uptime otel config feature failing on linux machine

### ISSUE THREAD

**Issue by krantishetty** [open-telemetry/opentelemetry-collector-contrib#31107]
### Component(s)

processor/metricsgeneration

### Describe the issue you're reporting

We try to add the uptime metrics value under process, but its failing. could you please help to advise on this.

my config file:
process:
   metrics:
        process.uptime:
            enabled: true

**Comment by krantishetty** [comment]
process:
   metrics:
        process.uptime:
        enabled: true

error details

'metrics' has invalid keys: process.uptime. collector server run finished with error: failed to get config: cannot unmarshal the confiuration: 1 error(s) decoding:

**Comment by krantishetty** [comment]
![process-uptime](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/151011155/bb094066-400c-4e20-995f-67ed15294f87)

**Comment by krantishetty** [comment]
Can you help on this

**Comment by krantishetty** [comment]
My goal to config add process attributes in otel configuration for linux to find the top high process usage with pid. How I can configure this using with attributes, please advise

**Comment by crobert-1** [comment]
Hello @krantishetty, can you share the full contents of your configuration file? Also, can you share the full error output?

A good place to start may be to use the hostmetrics receiver, specifically the [`process` source](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver#process).

**Comment by krantishetty** [comment]
receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.time:
            enabled: true
          system.cpu.physical.count:
            enabled: true
          system.cpu.logical.count:
            enabled: true
    
      process:
        metrics:
          process.cpu.utilization:
          enabled: true
          process.cpu.time:
          enabled: true
          process.disk.io:
          enabled: true
          process.memory.utilization:
          enabled: true
          process.disk.operations:
          enabled: true
          process.uptime:
          enabled: true
          process.pid:
          enabled: true


processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 10000
    spike_limit_mib: 200


  resourcedetection:
    detectors: [env, system]
    system:
      hostname_sources: ["os"]
      resource_attributes:
        host.id:
          enabled: true
        host.name:
          enabled: true


exporter:
  otlphttp:
    endpoint: https://xxxxxxx/
    headers:
    Authorization: "xxxxxxxx"
  logging:
    loglevel: debug


service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter, resourcedetection]
      exporters: [logging, otlhttp]



Error: failed to get config: cannot unmarshal the configuration: 1 errors(s) decoding:

* error decoding 'receivers': error reading configuration for "hostmetrics": error reading settings for scraper type "process": 1 error(s) decoding:

* 'metrics' has invalid keys: process.pid, process.uptime





otel version is .88

**Comment by krantishetty** [comment]
![otel-1](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/151011155/2bf1911f-6c31-4b3d-a045-1e9be7e76cfb)
![otel-2](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/151011155/246489a8-1eab-4e74-8fe6-6379d9cef8a7)

**Comment by krantishetty** [comment]
Please advise

**Comment by krantishetty** [comment]
Hi @crobert-1 , please advise my query

**Comment by krantishetty** [comment]
Hi @crobert-1 , can you please advise

**Comment by krantishetty** [comment]
@tmc @indrekj @dazuma  can someone advise my query

**Comment by braydonk** [comment]
`process.uptime` is not a supported metric. You can see the full list at: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/metadata.yaml

**Comment by krantishetty** [comment]
Apologies, we are barely get the response and we are looking some help to get the system level process details and process owner when the high cpu memory usage triggered to find the exact process details which cause the problem

**Comment by braydonk** [comment]
A couple things to note. 

Firstly, GitHub Issues are intended for reporting problems with reproduction steps, not for getting support on usage. I would recommend instead joining the CNCF Slack and asking these sorts of questions in the #otel-collector channel. https://communityinviter.com/apps/cloud-native/cncf

Secondly, when posting configuration files it is strongly recommended that you use GitHub's Markdown support to post the yaml in code blocks within your comments. yaml is indentation dependent, so it is important that the indentation is maintained. You can follow those instructions here: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

I will guide you to getting a working config, after which point I think this issue can be considered closed (I don't have the ability to actually close it but someone who is able to may do so).

---

There are a few errors with the configuration you posted in the screenshot:
* `process.uptime` is not a real supported metric.
* `process.pid` is a Resource Attribute, not a metric. It goes under a `resource_attribute` setting, not `metric`.
* The indentation in the `metrics` section is off. `enabled` should be nested under the metric name.

So the process config you want it:
```yaml
process:
  metrics:
    process.cpu.utilization:
      enabled: true
    process.cpu.time:
      enabled: true
    process.disk.io:
      enabled: true
    process.memory.utilization:
      enabled: true
    process.disk.operations:
      enabled: true
  resource_attributes:
    process.pid:
      enabled: true
```

A few things you have enabled are already enabled by default and can be removed, so you can simplify it further:

```yaml
process:
  metrics:
    process.cpu.utilization:
      enabled: true
    process.memory.utilization:
      enabled: true
    process.disk.operations:
      enabled: true
```

With this `process` configuration you should have all the metrics you need.

**Comment by krantishetty** [comment]
Thank you very much @braydonk , i will test it with attributes config and will share it.
