### ISSUE TITLE
[processor/resourcedetection]  stepping should be a string

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#31136]
### Component(s)

processor/resourcedetection

## Description

Same as #29025 but for CPU stepping number (which surprisingly is not a number).

## Steps to Reproduce

See open-telemetry/semantic-conventions/issues/495

## Expected Result

`host.cpu.stepping` should be set to a string

## Actual Result

It is set to an integer

### Collector version

any

## Environment
not relevant

### Additional context

cc @ChrsMark interested in taking this?

**Comment by ChrsMark** [comment]
> cc @ChrsMark interested in taking this?

Sure @mx-psi, happy to take it :)
