### ISSUE TITLE
Running Multiple OpenTelemetry Collectors on the Same Linux VM

### ISSUE THREAD

**Issue by wamik25apr** [open-telemetry/opentelemetry-collector-contrib#31166]
### Component(s)

cmd/otelcontribcol

### Describe the issue you're reporting

is it possible to run multiple instance of collector in a single linux vm in different port.

**Comment by crobert-1** [comment]
Yes, this is possible. Setting a different port for where [internal metrics are exposed](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#metrics) should be the only thing necessary that I'm aware of.
