### ISSUE TITLE
[receiver/mongodbatlasreceiver]  

### ISSUE THREAD

**Issue by nunodomingues-td** [open-telemetry/opentelemetry-collector-contrib#31181]
### Component(s)

receiver/mongodbatlas

### Describe the issue you're reporting

Greetings everyone,

I have an inquiry regarding Logs permissions, specifically related to the [receiver documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mongodbatlasreceiver), which states:

> To collect access logs, the requesting API key must possess the appropriate permission, necessitating either the Project Owner or Organization Owner role. Access logs are specific to each cluster.

Are these permissions indeed essential? Is this limitation imposed solely by MongoDB Cloud, or is it a constraint inherent to the receiver?

Thanks in advance

**Comment by djaglowski** [comment]
We generally strive to determine the least permissions necessary to pull the data. I don't recall specifically how these permissions were determined but perhaps @schmikei does. In any case, feel free to propose lesser permissions and we can validate whether they work.

**Comment by schmikei** [comment]
> Are these permissions indeed essential? Is this limitation imposed solely by MongoDB Cloud, or is it a constraint inherent to the receiver?

These permissions are only required for access logs. This is a limitation based off the MongoDB Atlas functionality to request these database access logs. 

https://www.mongodb.com/docs/atlas/access-tracking/#required-access

**Comment by djaglowski** [comment]
Thanks @schmikei.

I'm closing this since there doesn't appear to be any action to take. Please let us know if there is anything further @nunodomingues-td.

**Comment by nunodomingues-td** [comment]
Hello @djaglowski @schmikei 
Thanks for the replies 🙏
