### ISSUE TITLE
[receiver/vcenter] Add support for per network/nic metrics

### ISSUE THREAD

**Issue by wally007** [open-telemetry/opentelemetry-collector-contrib#31218]
### Component(s)

receiver/vcenter

### Is your feature request related to a problem? Please describe.

Currently, the vCenter network metrics are exported per host.  Most, if not all ESXi hosts have several nics/network assigned. In my case, I'm administering hosts with 12+ networks. It is impossible to monitor network utilization of ESXi hosts.

### Describe the solution you'd like

It would be useful if network metrics were **NOT** aggregated per host but exported per host + nic/network in order to be able to effectively monitor for network errors and network congestion.
(metrics like network bandwidth, network errors, packets etc ..)

### Describe alternatives you've considered

Currently we use telegraf to monitor vsphere environment but we'd like to move to OpenTelemetry. Telegraf exports network metrics per vnic (which makes it easy to map it to the nic/network)

**Comment by djaglowski** [comment]
Any thoughts on this @schmikei?

**Comment by schmikei** [comment]
@wally007 

Sorry for the delay are you familiar with the [object](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/vcenterreceiver/documentation.md#vcenterhostnetworkusage) metric attribute? It records network metric data per vnic already unless I'm missing something? 

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/32067685/904d1ae4-b6c6-418d-903e-23eb0131c627)

**Comment by wally007** [comment]
I am sorry for the duplicate issue. I will close this now
