### ISSUE TITLE
[receiver/azureeventhub] Add cparkins to codeowners

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#31269]
### Component(s)

receiver/azureeventhub

### Describe the issue you're reporting

I would like to add @cparkins to become a codeowner of the azure event hub receiver. Please let me know if you accept and I'll open a PR with the changes.

**Comment by cparkins** [comment]
I've discussed this with @atoulme and agree that I can help!
