### ISSUE TITLE
Support latest DogStatsD version

### ISSUE THREAD

**Issue by jverce** [open-telemetry/opentelemetry-collector-contrib#31295]
### Component(s)

receiver/statsd

### Describe the issue you're reporting

When using recent versions of the DogStatsD client (e.g. [Java client](https://github.com/DataDog/java-dogstatsd-client)) I noticed that metrics sent by the client weren't captured by the `statsd` receiver. The cause of this issue boils down to the `statsd` receiver rejecting metrics that contain unrecognized parts, and DogStatsD emits metrics with extra fields that are currently unsupported by the receiver.

In particular, there are 2 new fields that are currently unsupported by the receiver:
- Container ID (since DogStatsD [v1.2](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell?tab=metrics#dogstatsd-protocol-v12))
- Timestamp (since DogStatsD [v1.3](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell?tab=metrics#dogstatsd-protocol-v13))

Example of a metric that the `statsd` receiver drops due to the unrecognized parts:
```
workflow_execution.failure:1|c|#workflow.version:2,workflow.name:Telemetry 2|c:abc123"
```

**Comment by jverce** [comment]
PR to fix this: #31296

**Comment by dmitryax** [comment]
I'm wondering if this additional support should be configurable. But given that we already support tags that are part of the DogStatsD, I think supporting these additional parts OOTB is ok. Later, if we want to define the format in the configuration explicitly, we can have `dogstatsd` as a default option to keep the backward compatibility.

**Comment by crobert-1** [comment]
I believe this was completed by #31296, so I'm going to close. Let me know if I misunderstood.
