### ISSUE TITLE
[exporter/loki] Documentation incorrect on mapping severity to level

### ISSUE THREAD

**Issue by alexgenon** [open-telemetry/opentelemetry-collector-contrib#31333]
### Component(s)

exporter/loki

### Describe the issue you're reporting

The [Loki exporter documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter#severity) states that the `record.severity` is mapping to `record.attributes.level` (used by Loki) but it appears that it is the severityNumber which is used for the mapping ([code reference](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/loki/logs_to_loki.go#L204))

**Comment by crobert-1** [comment]
Sorry if this is obvious, but what's the difference from the code vs. documentation? From my understanding of the [OTLP log spec](https://opentelemetry.io/docs/specs/otel/logs/data-model/#log-and-event-record-definition), severity would be the `SeverityNumber` that's being used, and then `record.attributes.level` is what's being used in code. Where's the mismatch that you're seeing? 

Is the expectation from documentation that the exporter should actually be getting the severity from a different field in a log that's explicitly named `severity`? I guess in my reading I assumed `severity` in this case is equivalent to `SeverityNumber`, but if that's the case maybe documentation should be updated to match more exactly?

For context, it looks like this functionality along with the README comment came in [the same change](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14560).

**Comment by alexgenon** [comment]
@crobert-1, indeed, the goal is to correct the documentation on the mapping.
There are 2 fields in the OTLP log spec: `SeverityText` and `SeverityNumber`.
In the documentation of the loki exporter, it is stated that `record.severity` (which corresponds to `SeverityText` is used to defined loki's `record.attributes.level` but in the code, it is actually `SeverityNumber` which is used. 
This is linked to #28612 which is asking for the entire removal of the promotion of the severity as a Loki label.

**Comment by crobert-1** [comment]
Okay, thanks for the clarification! I didn't know there was an understanding that `record.severity` corresponds to `SeverityText` here. 👍
