### ISSUE TITLE
deltatocumulative aborts after first sample

### ISSUE THREAD

**Issue by sh0rez** [open-telemetry/opentelemetry-collector-contrib#31350]
### Component(s)

processor/deltatocumulative

## Description

`deltatocumulativeprocessor` only updates the first sample of each stream

## Steps to Reproduce

send a stream with more than two samples

## Expected Result

all samples are converted to cumulative

## Actual Result

only first sample is converted

### Collector version

d4dda619ba45df1df52086797ca8036a01bd5351

**Comment by crobert-1** [comment]
_Issue filed by a code owner, and the other code owner has approved the PR, so I'm removing `needs triage`._
