### ISSUE TITLE
[exporter/fileexporter] Enable appending as an option instead of always truncating

### ISSUE THREAD

**Issue by OverOrion** [open-telemetry/opentelemetry-collector-contrib#31364]
### Component(s)

exporter/file

### Is your feature request related to a problem? Please describe.

It might be desirable to let the user configure the fileexporter's file opening mode so in the event of a restart it would continue writing to the same file without losing the previous progress.

### Describe the solution you'd like

I think a simple `write_mode: append / truncate` or `append: true` configuration field would be the way to go.  

### Describe alternatives you've considered

Using an external script to make a backup of the currently written file and only after that should the collector be restarted. 

### Additional context

If you agree with this proposal I would be happy to work on it once we agreed on how this option should be implemented :rocket:.

**Comment by atingchen** [comment]
Thank you for your issue~ @OverOrion 
Are you worried that when the Collector restarts, it overwrites the previously exported files, causing data loss?Wouldn't it be simpler to add the start time of the Collector as a suffix to the file name?

**Comment by OverOrion** [comment]
Hey @atingchen,

>Are you worried that when the Collector restarts, it overwrites the previously exported files, causing data loss?

Yes, that is the problem I've described.

>Wouldn't it be simpler to add the start time of the Collector as a suffix to the file name?

I do not see how that could be simpler (received messages scattered across multiple files or just having one file), could you please elaborate?

**Comment by OverOrion** [comment]
Thank you for your quick response @atingchen! Could you please allow the CI to run on the PR? (Not sure if you have the permission, just being hopeful that you do).

**Comment by atingchen** [comment]
Thank you very much for your work @OverOrion~  I have provided you with some suggestions, and you are more than welcome to create a PR.

**Comment by OverOrion** [comment]
Hey @atingchen,
Thanks for the quick reply, but I do not see any comments / review notes on the PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31369.
Can you please double check that you submitted your review?

**Comment by atingchen** [comment]
Hi @OverOrion,
I have  submitted my review.

**Comment by atoulme** [comment]
Can this issue be closed now that https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31369 is merged?
