### ISSUE TITLE
[extension/opamp] Support HTTP transport

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#31390]
### Component(s)

extension/opamp

### Is your feature request related to a problem? Please describe.

The OpAMP extension currently only supports WebSocket transport, but some cases (e.g. bootstrapping) may be more amenable to using an HTTP transport.

### Describe the solution you'd like

Implement an option to configure HTTP transport in the extension.

**Comment by jaronoff97** [comment]
@evan-bradley this should have been closed by #31392
