### ISSUE TITLE
Port k8s object receiver filters to the k8scluster receiver

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#31399]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

Users report they would like to selectively monitor kubernetes data, be it specific pods, namespaces.

### Describe the solution you'd like

The k8sobjects receiver has a neat set of filters that seem to invite a great deal of flexibility and would be reusable with the k8s cluster receiver. The idea would be to reuse the logic and user configuration.

**Comment by crobert-1** [comment]
_Sounds like this enhancement is supported by code owners. Implementation details are still being discussed, but we can remove `needs triage`._
