### ISSUE TITLE
[receiver/K8scluster] Add additional attributes to the k8s.container.restarts metric

### ISSUE THREAD

**Issue by avanish-vaghela** [open-telemetry/opentelemetry-collector-contrib#31418]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

Currently, the `k8s.container.restarts` metric does not include the metadata such as the reason for the restart and the exit code

### Describe the solution you'd like

Add `terminated_reason` and `exit_code` attributes to the `k8s.container.restarts` metrics where appropriate

### Describe alternatives you've considered

The current alternative is to use the Kube State Metrics's `kube_pod_container_status_terminated_reason` and `kube_pod_container_status_last_terminated_exitcode` metrics

### Additional context

A related metric issue has been raised: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31282#issuecomment-1964590709

**Comment by TylerHelmuth** [comment]
I like this attribute.

**Comment by avanish-vaghela** [comment]
I will try and raise a draft PR
