### ISSUE TITLE
[Weekly Report] Add section for components looking for new code owners

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#31419]
### Describe the issue you're reporting

Filing from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31115#issuecomment-1939215836

This request is to add a section to the weekly report that lists components that are looking for new code owners, in an effort to communicate with interested contributors where they can help out.

**Comment by LucaLanziani** [comment]
Duplicates? https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32490

**Comment by crobert-1** [comment]
> Duplicates? #32490

Not quite. This request is to include a list of components that have the following in their `metadata.yaml`:
```
status:
  ...
  codeowners:
    seeking_new: true
```
This is meant to let OpenTelemetry contributors know that this component welcomes help from anyone, and that contributors are welcome to [become code owners](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner).

#32490 is to list issues/PRs that have the label `waiting-for-code-owners`. This label is meant to notify code owners that there's something they need to take a look at.

**Comment by LucaLanziani** [comment]
Would something like this work?

## Components Report
<ul>

<li> deprecated: 1
<details>
    <summary> Components </summary>

- [ ] instanaexporter: {"deprecated":["traces"]}
</details>
</li>

<li> unmaintained: 1
<details>
    <summary> Components </summary>

- [ ] skywalkingexporter: {"unmaintained":["metrics","logs"]}
</details>
</li>
<li> looking for owners: 25
<details>
  <summary> Components </summary>

- [ ] [connector-grafanacloudconnector](../blob/master/connector/grafanacloudconnector/metadata.yaml) 
- [ ] [connector-spanmetricsconnector](../blob/master/connector/spanmetricsconnector/metadata.yaml) 
- [ ] [extension-filestorage](../blob/master/extension/storage/filestorage/metadata.yaml) 
- [ ] [pkg-ottl](../blob/master/pkg/ottl/metadata.yaml) 
- [ ] [receiver-activedirectorydsreceiver](../blob/master/receiver/activedirectorydsreceiver/metadata.yaml) 
- [ ] [receiver-aerospikereceiver](../blob/master/receiver/aerospikereceiver/metadata.yaml) 
- [ ] [receiver-awscloudwatchreceiver](../blob/master/receiver/awscloudwatchreceiver/metadata.yaml) 
- [ ] [receiver-azureeventhubreceiver](../blob/master/receiver/azureeventhubreceiver/metadata.yaml) 
- [ ] [receiver-bigipreceiver](../blob/master/receiver/bigipreceiver/metadata.yaml) 
- [ ] [receiver-cloudflarereceiver](../blob/master/receiver/cloudflarereceiver/metadata.yaml) 
- [ ] [receiver-cloudfoundryreceiver](../blob/master/receiver/cloudfoundryreceiver/metadata.yaml) 
- [ ] [receiver-couchdbreceiver](../blob/master/receiver/couchdbreceiver/metadata.yaml) 
- [ ] [receiver-elasticsearchreceiver](../blob/master/receiver/elasticsearchreceiver/metadata.yaml) 
- [ ] [receiver-flinkmetricsreceiver](../blob/master/receiver/flinkmetricsreceiver/metadata.yaml) 
- [ ] [receiver-iisreceiver](../blob/master/receiver/iisreceiver/metadata.yaml) 
- [ ] [receiver-memcachedreceiver](../blob/master/receiver/memcachedreceiver/metadata.yaml) 
- [ ] [receiver-mongodbatlasreceiver](../blob/master/receiver/mongodbatlasreceiver/metadata.yaml) 
- [ ] [receiver-mongodbreceiver](../blob/master/receiver/mongodbreceiver/metadata.yaml) 
- [ ] [receiver-rabbitmqreceiver](../blob/master/receiver/rabbitmqreceiver/metadata.yaml) 
- [ ] [receiver-riakreceiver](../blob/master/receiver/riakreceiver/metadata.yaml) 
- [ ] [receiver-sqlserverreceiver](../blob/master/receiver/sqlserverreceiver/metadata.yaml) 
- [ ] [receiver-syslogreceiver](../blob/master/receiver/syslogreceiver/metadata.yaml) 
- [ ] [receiver-vcenterreceiver](../blob/master/receiver/vcenterreceiver/metadata.yaml) 
- [ ] [receiver-windowsperfcountersreceiver](../blob/master/receiver/windowsperfcountersreceiver/metadata.yaml) 
- [ ] [receiver-zookeeperreceiver](../blob/master/receiver/zookeeperreceiver/metadata.yaml) 
</details>
</li>
</ul>

**Comment by LucaLanziani** [comment]
Variation

<ul>
<li> looking for owners: 25
<details>
  <summary> connector: 2 </summary>

- [ ] [grafanacloudconnector](../blob/master/connector/grafanacloudconnector/metadata.yaml) 
- [ ] [spanmetricsconnector](../blob/master/connector/spanmetricsconnector/metadata.yaml) 
</details>
<details>
  <summary> extension: 1 </summary>

- [ ] [filestorage](../blob/master/extension/storage/filestorage/metadata.yaml) 
</details>
<details>
  <summary> pkg: 1 </summary>

- [ ] [ottl](../blob/master/pkg/ottl/metadata.yaml) 
</details>
<details>
  <summary> receiver: 21 </summary>

- [ ] [activedirectorydsreceiver](../blob/master/receiver/activedirectorydsreceiver/metadata.yaml) 
- [ ] [aerospikereceiver](../blob/master/receiver/aerospikereceiver/metadata.yaml) 
- [ ] [awscloudwatchreceiver](../blob/master/receiver/awscloudwatchreceiver/metadata.yaml) 
- [ ] [azureeventhubreceiver](../blob/master/receiver/azureeventhubreceiver/metadata.yaml) 
- [ ] [bigipreceiver](../blob/master/receiver/bigipreceiver/metadata.yaml) 
- [ ] [cloudflarereceiver](../blob/master/receiver/cloudflarereceiver/metadata.yaml) 
- [ ] [cloudfoundryreceiver](../blob/master/receiver/cloudfoundryreceiver/metadata.yaml) 
- [ ] [couchdbreceiver](../blob/master/receiver/couchdbreceiver/metadata.yaml) 
- [ ] [elasticsearchreceiver](../blob/master/receiver/elasticsearchreceiver/metadata.yaml) 
- [ ] [flinkmetricsreceiver](../blob/master/receiver/flinkmetricsreceiver/metadata.yaml) 
- [ ] [iisreceiver](../blob/master/receiver/iisreceiver/metadata.yaml) 
- [ ] [memcachedreceiver](../blob/master/receiver/memcachedreceiver/metadata.yaml) 
- [ ] [mongodbatlasreceiver](../blob/master/receiver/mongodbatlasreceiver/metadata.yaml) 
- [ ] [mongodbreceiver](../blob/master/receiver/mongodbreceiver/metadata.yaml) 
- [ ] [rabbitmqreceiver](../blob/master/receiver/rabbitmqreceiver/metadata.yaml) 
- [ ] [riakreceiver](../blob/master/receiver/riakreceiver/metadata.yaml) 
- [ ] [sqlserverreceiver](../blob/master/receiver/sqlserverreceiver/metadata.yaml) 
- [ ] [syslogreceiver](../blob/master/receiver/syslogreceiver/metadata.yaml) 
- [ ] [vcenterreceiver](../blob/master/receiver/vcenterreceiver/metadata.yaml) 
- [ ] [windowsperfcountersreceiver](../blob/master/receiver/windowsperfcountersreceiver/metadata.yaml) 
- [ ] [zookeeperreceiver](../blob/master/receiver/zookeeperreceiver/metadata.yaml) 
</details>
</li>
</ul>

**Comment by crobert-1** [comment]
Sure, that format works for me 👍

**Comment by crobert-1** [comment]
Support for this was added in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33397, view the [most recent weekly report](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34301) to see the `Seeking new code owners` section.
