### ISSUE TITLE
[exporter/loadbalancing] otlp port must specified in loadbalancing config to pass validation

### ISSUE THREAD

**Issue by atmask** [open-telemetry/opentelemetry-collector-contrib#31426]
### Component(s)

exporter/loadbalancing

## Description

As a result of the otel-collector [issue 9505](https://github.com/open-telemetry/opentelemetry-collector/issues/9505), there is a new condition in the validation of otlpexporter's config struct. This validation is meant to cause invalid config to fail fast rather than failing while running. 

The loadbalancing config has a dependency on the otlpexporter config struct. The change to the otlpexporter config's validation impacts this package. Changes to this package are required to unblock [PR 9632](https://github.com/open-telemetry/opentelemetry-collector/pull/9632) on the otel-collector. 

## Steps to Reproduce
Run `go test` on loadbalancing exporter while using `replace`  to point "go.opentelemetry.io/collector/exporter/otlpexporter" module to the version of otlpexporter at e6f58dc4e

## Expected Result
All tests pass

## Actual Result
Tests fail to unmarshal and validate configs where no otlp port is specified in the endpoint

### Collector version

e6f58dc4e04e51afe587d66835bc70445e82bcee

### Environment information

N/A

**Comment by astencel-sumo** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31425
