### ISSUE TITLE
Systemd environment file and config are missing

### ISSUE THREAD

**Issue by pranavmarla** [open-telemetry/opentelemetry-collector-contrib#3143]
**Describe the bug**
Similar to issue #3097, an out of the box collector feature that is mentioned in the documentation is present in the _core_ collector, but missing in the _contrib_ collector.

Specifically, as per the [collector documentation](https://opentelemetry.io/docs/collector/getting-started/), when the agent is installed on a Linux machine, it should create a systemd environment file where you can define custom environment variables (eg. `HTTP_PROXY`) for the collector to use:

> To customize these options, modify the OTELCOL_OPTIONS variable in the /etc/otel-collector/otel-collector.conf systemd environment file with the appropriate command-line options ... Additional environment variables can also be passed to the otel-collector service by adding them to this file.

**Please see the _Additional context_ section at the end for exact details on which files need to be added/modified to fix this issue.**

**Steps to reproduce**
- Download contrib collector deb file ([otel-contrib-collector_0.24.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.24.0/otel-contrib-collector_0.24.0_amd64.deb)) onto an Ubuntu machine
- Install the contrib collector: `dpkg --install otel-contrib-collector_0.24.0_amd64.deb`
- After installing the contrib collector, note that the systemd environment file (`/etc/otel-contrib-collector/otel-contrib-collector.conf`) does not exist
- Manually create it
- Define a custom environment variable in that file
- Reference that custom environment variable in place of a required parameter value in the collector config file (`/etc/otel-contrib-collector/config.yaml`)
- Restart the collector: `systemctl restart otel-contrib-collector` 
- Look at the collector logs: `journalctl --unit otel-contrib-collector -f`

**What did you expect to see?**
I expect to see the collector start up successfully.

**What did you see instead?**
The collector fails to start up and complains about a missing parameter (the one where I referenced my custom environment variable).

**What version did you use?**
`v0.24.0` of the contrib collector ([otel-contrib-collector_0.24.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.24.0/otel-contrib-collector_0.24.0_amd64.deb))

**What config did you use?**
Any config where you substitute a custom environment variable in place of a required parameter value.

**Environment**
OS: Ubuntu 18.04

**Additional context**
The simplest way to see what is missing is to just look at pull request [2822](https://github.com/open-telemetry/opentelemetry-collector/pull/2822) -- that's where this feature was added to the _core_ collector 20 days ago.

Specifically:
- As part of its installation process, the _contrib_ collector should create a systemd environment file similar to the one created by the _core_ collector ([otel-collector.conf](https://github.com/open-telemetry/opentelemetry-collector/blob/main/internal/buildscripts/packaging/fpm/otel-collector.conf)): 
```
# Systemd environment file for the otel-collector service

# Command-line options for the otel-collector service.
# Run `/usr/bin/otelcol --help` to see all available options.
OTELCOL_OPTIONS="--config=/etc/otel-collector/config.yaml"
```

- The _contrib_ collector service should be configured so that systemd knows that the above file contains environment variables 
i.e. If we look at [otel-contrib-collector.service](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/buildscripts/packaging/fpm/otel-contrib-collector.service), we see this:
```
...
[Service]
ExecStart=/usr/bin/otelcontribcol --config /etc/otel-contrib-collector/config.yaml
...
```

Instead, it should look more like the equivalent file from the _core_ collector ([otel-collector.service](https://github.com/open-telemetry/opentelemetry-collector/blob/main/internal/buildscripts/packaging/fpm/otel-collector.service)):
```
...
[Service]
EnvironmentFile=/etc/otel-collector/otel-collector.conf
ExecStart=/usr/bin/otelcol $OTELCOL_OPTIONS
...
```

**Comment by pranavmarla** [comment]
FYI @Jammicus @jchengsfx

**Comment by Jammicus** [comment]
Will do as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3123
