### ISSUE TITLE
Use `confighttp` for target allocator http client

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-collector-contrib#31449]
### Component(s)

receiver/prometheus

### Is your feature request related to a problem? Please describe.

We'd like to use TLS client authentication for communication between the collector and target allocator. A detailed discussion about the reasons can be found here: https://github.com/open-telemetry/opentelemetry-operator/issues/1669.

### Describe the solution you'd like

We should use `go.opentelemetry.io/collector/config/confighttp`. This is a standard for collector components and users should be comfortable with it. It will also give us a lot more customization for very little additional maintenance burden.

### Describe alternatives you've considered

We could implement just the TLS options ourselves, but there doesn't seem to be any upside to that.

**Comment by dashpole** [comment]
This seems reasonable to me.  Is it breaking, or additive?

**Comment by swiatekm-sumo** [comment]
Additive, the only common field is `Endpoint`, and the yaml key is the same. So it should be transparent to the user.

**Comment by dashpole** [comment]
Sounds great.  Feel free to open the PR.

**Comment by atoulme** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31452 is merged, can we close this issue?
