### ISSUE TITLE
[exporter/file] Support setting permissions on opened files

### ISSUE THREAD

**Issue by sinkingpoint** [open-telemetry/opentelemetry-collector-contrib#31459]
### Component(s)

exporter/file

### Is your feature request related to a problem? Please describe.

Currently, all files opened by the file exporter are opened with 0600 (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/output/file/file.go#L80). This precludes anything except the user that the collector is running on from reading the files that it outputs. I want to be able to configure that, so that we can have more finely grained permissions.

### Describe the solution you'd like

I want to add a configuration option to the file exporter to allow setting the permissions bits, and the user/group of the file that the file exporter makes. This configuration should be generic enough that it can be used in other file-like exporters (see: namedpipeexporter)

**Comment by atingchen** [comment]
Hi,@sinkingpoin~I concur with the proposal to incorporate a configuration option into the file exporter for setting the permissions bits. Concurrently, I believe that the user/group associated with the file should be granted read-only permissions.
What you think?
