### ISSUE TITLE
Move Sumo Logic Exporter from Sumo Logic Repository to OpenTelemetry Contrib

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#31479]
### Component(s)

exporter/sumologic

### Is your feature request related to a problem? Please describe.

Right now, Sumo Logic Exporter in this repository is way too much different from the Sumo Logic Repository, which is intended to be use by Sumo Logic Customers. We would like to synchronize code, and then use and maintain code in this repository

### Describe the solution you'd like

Just moving code. Deprecations in the README.md have already be done, so we should be good to replace old exporter with the new one

### Describe alternatives you've considered

Creating another exporter, but this doesn't sound right and unnecessary multiples exporters

**Comment by crobert-1** [comment]
_This was filed by the component's code owner and makes sense to me, so I'm removing `needs triage`._

**Comment by sumo-drosiek** [comment]
We can close this issue. It has been finally done with `v0.102.0`
