### ISSUE TITLE
[pkg/ottl] Add Base64Decode Converter

### ISSUE THREAD

**Issue by DougManton** [open-telemetry/opentelemetry-collector-contrib#31543]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has no way to convert a base64 encoded string to plaintext, preventing the import of logs where the vendor encodes strings

### Describe the solution you'd like

Add a new Converter, Base64Decode, that accepts a base64 encoded string and returns the decoded string.

### Describe alternatives you've considered

Intermediary software to process inbound logs and decode base64 strings before passing to opentelemetry collector

### Additional context

I am currently running a local fork with my implementation of a base64 decode function, I will create a branch and link it here.

**Comment by evan-bradley** [comment]
Closing as resolved via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31730. If you'd like to also add an encoding function, please feel free to reopen this issue or create another issue to track it.
