### ISSUE TITLE
Use `internal/aws/awsutil` for AWS session configuration in the `awsproxy`

### ISSUE THREAD

**Issue by jefchien** [open-telemetry/opentelemetry-collector-contrib#31554]
### Component(s)

extension/awsproxy, internal/aws

### Is your feature request related to a problem? Please describe.

The awsproxy session and credential configuration differs slightly from the `internal/aws/awsutil` implementation. This results in different behavior between the two particularly in the region detection. The `internal/aws/awsutil` does not support using the `AWS_DEFAULT_REGION` environment variable or ECS metadata to determine the region.

### Describe the solution you'd like

Consolidate the implementation for AWS session configuration to `internal/aws/awsutil`.

awsutil also has a `ProxyServerTransport` function, which is currently unused. 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b16a03f946b7e26c94bf2aae11b429cd8931013f/internal/aws/awsutil/conn.go#L164

It has the same implementation as the one in `internal/aws/proxy` and can be reused as well.

**Comment by KyriosGN0** [comment]
@jefchien i would like to give this a go but i am kinda confused about what ar trying to solve
the `internal/aws/awsutill` should be the "canon" implementation ? 
as in the `internal/aws/proxy` should use `awsutil? `
