### ISSUE TITLE
collectd receiver is not writing anything to debug log on start

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#31593]
### Component(s)

receiver/collectd

### Is your feature request related to a problem? Please describe.

When debugging if collectd is properly configured and loading i would epect an logs in debug level.

### Describe the solution you'd like

Collectd shall report as loaded receiver  plugin and on what host and port it is serving

**Comment by crobert-1** [comment]
Sounds like a valid enhancement to me. I did a quick scan of the receiver and didn't see any log messages that describe this information. _Removing `needs triage`._

**Comment by atoulme** [comment]
Sure, would you like to offer a patch?

**Comment by kernelpanic77** [comment]
@atoulme @crobert-1 Can I take this up ?

**Comment by kernelpanic77** [comment]
@atoulme @crobert-1 Can we discuss this issue in the weekly SIG ?

**Comment by crobert-1** [comment]
Do you have a specific question or problem you're wanting to discuss?

**Comment by kernelpanic77** [comment]
@crobert-1 I am a bit unsure if understood the problem correctly. From what I understood only the `ServeHTTP` method of the `collectdReceiver` struct has to be changed to add the debug logs for Host and Port. 

> Collectd shall report as loaded receiver plugin
Also, @atoulme  @crobert-1 Could you also explain this requirement in a little more detail ?

**Comment by atoulme** [comment]
FWIW you can always come to a SIG meeting and ask any question. In this instance, it feels like something we can resolve over Github.

Yes, I believe you are correct, just need to add a bit of logging in that method.

**Comment by kernelpanic77** [comment]
> FWIW you can always come to a SIG meeting 
Sure @atoulme 

> Collectd shall report as loaded receiver plugin
I am not sure if I understood this sentence correctly.

**Comment by atoulme** [comment]
> I am not sure if I understood this sentence correctly. Could you explain this part ?

Just that the receiver started ok. As in, it reports in debug in the `Start` method that it started.
