### ISSUE TITLE
[receiver/jmx] Ability to discovery jmx endpoints dynamically

### ISSUE THREAD

**Issue by neo-waiariki-koia** [open-telemetry/opentelemetry-collector-contrib#31599]
### Component(s)

receiver/jmx

### Is your feature request related to a problem? Please describe.

At the moment, the endpoint for jmx receiver has to be hardcoded. Unfortunately, for my use case, this isn't feasible. I was hoping some sort of service discovery mechanism could be implemented to find endpoints dynamically? The prometheus receiver has this and, although different, Datadog agents can facilitate similar functionality. 

### Describe the solution you'd like

I'd like for the ability to discover jmx endpoints dynamically within a Kubernetes cluster. This could be done by filtering pods based on fields, labels or annotations.

**Comment by JaredTan95** [comment]
From your description, I think it might be more appropriate to put this requirement into `otel-operator`?
