### ISSUE TITLE
Update github.com/aws/aws-sdk-go-v2/service/s3 to v1.51.2 breaks build

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#31592]
### Component(s)

cmd/configschema

### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8149526970/job/22274417890?pr=31557

> Error: /home/runner/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.31.0/api_client.go:766:25: undefined: presignedurlcust.AddAsIsPresigingMiddleware

**Comment by crobert-1** [comment]
Issue: https://github.com/aws/aws-sdk-go-v2/issues/2529

This should be fixed by upgrading to `v1.51.2`, but it looks like the renovate PR is failing using `v1.31.0`. Looks like the indirect `go.mod` references are still on the old version.

**Comment by songy23** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31557 bumps to a newer version, build succeeds.
