### ISSUE TITLE
Add README for azuremonitor exporter

### ISSUE THREAD

**Issue by asuresh4** [open-telemetry/opentelemetry-collector-contrib#316]

**Comment by pplavetzki** [comment]
Is there any work towards this?  I'm trying to implement the azure monitor exporter in my service, but the lack of any example is making it very difficult.

**Comment by verysonglaa** [comment]
The following config was working for me, just replace $AI_INSTRUMENT_KEY with your instrument key

`---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: crt-otel
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      zipkin:
        endpoint: "0.0.0.0:9411"
    processors:
      queued_retry:
        num_workers: 16
        queue_size: 10000
        retry_on_failure: true
      batch:
        send_batch_size: 1024
        timeout: 5s
    extensions:
      health_check: {}
    exporters:
      azuremonitor:
      azuremonitor/2:
        # endpoint is the uri used to communicate with Azure Monitor
        endpoint: "https://dc.services.visualstudio.com/v2/track"
        # instrumentation_key is the unique identifer for your Application Insights resource
        instrumentation_key: "$AI_INSTRUMENT_KEY"
        # maxbatchsize is the maximum number of items that can be queued before calling to the configured endpoint
        maxbatchsize: 100
        # maxbatchinterval is the maximum time to wait before calling the configured endpoint.
        maxbatchinterval: 10s
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [zipkin]
          processors: [batch, queued_retry]
          exporters: [azuremonitor/2]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: crt-otel
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: opencensus # Default endpoint for Opencensus receiver.
    port: 55678
    protocol: TCP
    targetPort: 55678
  - name: jaeger-grpc # Default endpoing for Jaeger gRPC receiver
    port: 14250
  - name: jaeger-thrift-http # Default endpoint for Jaeger HTTP receiver.
    port: 14268
  - name: zipkin # Default endpoint for Zipkin receiver.
    port: 9411
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: crt-otel
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - command:
          - "/otelcontribcol"
          - "--config=/conf/otel-collector-config.yaml"
#           Memory Ballast size should be max 1/3 to 1/2 of memory.
          - "--mem-ballast-size-mib=683"
          - "--log-level=debug"
        env:
        - name: GOGC
          value: "80"
        image: otel/opentelemetry-collector-contrib:0.6.0
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55678 # Default endpoint for Opencensus receiver.
        - containerPort: 14250 # Default endpoint for Jaeger HTTP receiver.
        - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
        - containerPort: 9411 # Default endpoint for Zipkin receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
#        - name: otel-collector-secrets
#          mountPath: /secrets
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
#        - secret:
#            name: otel-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem
`
