### ISSUE TITLE
[processor/deltatocumulative] internal/streams.TestExpiry fails on Windows

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#31615]
### Component(s)

processor/deltatocumulative

### What happened?

TestExpiry fails on Windows. See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8165426471/job/22322842022

```
=== Failed
=== FAIL: internal/streams TestExpiry (0.78s)
    expiry_test.go:81: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/streams/expiry_test.go:81
        	Error:      	Not equal: 
        	            	expected: 1m0s
        	            	actual  : 1m1s
        	Test:       	TestExpiry

=== FAIL: internal/streams TestExpiry (re-run 1) (0.82s)
    expiry_test.go:81: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/streams/expiry_test.go:81
        	Error:      	Not equal: 
        	            	expected: 1m0s
        	            	actual  : 1m1s
        	Test:       	TestExpiry

DONE 2 runs, 14 tests, 2 failures in 15.740s
make[2]: *** [../../Makefile.Common:126: test] Error 1
make[1]: *** [Makefile:165: processor/deltatocumulativeprocessor] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by dmitryax** [comment]
Must be caused by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31337

**Comment by RichieSams** [comment]
Investigating

**Comment by RichieSams** [comment]
@sh0rez It looks like you're using sleeps in the test code. But this isn't deterministic (and it slows down the testing). We should instead utilize setting NowFunc / similar for the expiry code. Perhaps for now we just remove the test to unblock CI, and then we can look at this again as part of the refactor discussion here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31337#discussion_r1513138107
