### ISSUE TITLE
Making six more metrics from MySQL receiver enabled by default

### ISSUE THREAD

**Issue by samiura** [open-telemetry/opentelemetry-collector-contrib#31613]
### Component(s)

receiver/mysql

### Describe the issue you're reporting

We need to make the following metrics enabled by default ( which are disabled now).

1. mysql.commands
2. mysql.client.network.io](http://mysql.client.network.io/)
3. mysql.connection.count
4. mysql.connection.errors
5. mysql.query.count
6. mysql.query.slow.count

**Comment by djaglowski** [comment]
> We need to make the following metrics enabled by default

What makes this a need?

Unfortunately we have have a policy of not enabling metrics by default which were added after the component was labeled beta. (Although this restriction was put in place after the component was labeled beta.)

Personally, I would like to enable many metrics by default but each one will be considered a breaking change at this point. In theory we may be able to do this but it will require a feature gate and

**Comment by samiura** [comment]
@djaglowski Understood! I will close the issue and try to find a workaround from our distribution.
