### ISSUE TITLE
Add pulsar exporter and receiver

### ISSUE THREAD

**Issue by hanjm** [open-telemetry/opentelemetry-collector-contrib#3164]
**Is your feature request related to a problem? Please describe.**
Export metrics, traces, logs data to pulsar. 
Receive metrics, traces, logs data from pulsar. 

opentelemetry-collector has kafkaexporter and kafkareceiver, [Apache Pulsar](https://pulsar.apache.org/) is a cloud-native, distributed messaging and streaming platform. 

I am implementing pulsarexporter and  pulsarreceiver.

**Comment by tech4gk** [comment]
Hi, @hanjm 
 Thanks for doing this. This is a very important piece of the puzzle that is missing for lot of use cases.
Any ETA on when this feature will be available for us to test it out ? I would be very happy to part of testing and validating the framework. Thanks

**Comment by hanjm** [comment]
done by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9791
