### ISSUE TITLE
Handle spans in the Loki exporter

### ISSUE THREAD

**Issue by jean** [open-telemetry/opentelemetry-collector-contrib#3166]
**Is your feature request related to a problem? Please describe.**

- We want to instrument code using the web SDK (PWA running on edge devices).
- We'd like to add spans for something that we'll call e.g. "task logs".
- We'd like to route the "task log" spans to Loki for long-term storage and display to clients (each client getting to see logs from their org, which may be coming from many devices).
- We'd also like to route the traces including these "log" spans to analysis backends such as Datadog and/or Zipkin. 

I think that sending these as *spans* makes sense, since we want to send the full traces to e.g. Datadog as well, for analysis. (In fact the immediate reason for sending them as spans is that the web SDK doesn't support sending logs. That's coincidental, but may also be the case for other clients as noted in e.g. #3071.)

**Describe the solution you'd like**

Loki is format-agnostic, although it does support various [parsers](https://grafana.com/docs/loki/latest/logql/#parser-expression). A span serialized to JSON would work just fine.

**Describe alternatives you've considered**

- Implement logging in the web client. This seems like make-work. There's no real difference between logs and traces:
  > [...] I don't believe tracing and logs are two separate things, [...] [Ted Young, on InfoQ](https://www.infoq.com/podcasts/observability-open-telemetry-release/).

**Additional context**

From @gramidt on [slack](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1617374532174000?thread_ts=1617261598.157500&cid=C01N6P7KR6W):

> The Loki exporter also only supports "Logs" at this time and not "Traces/Spans". The effort to add this should be rather minimal for a basic implementation, but effort none the less since signal translation hasn't been added to the collector yet. 

In a case like this: is signal translation actually necessary? Could the `lokiexporter` just accept spans and send them through to Loki, pretending that they're logs?

Transform logs to spans (PR WIP - #3003): https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3071

**Comment by jpkrohling** [comment]
@jean, I believe this is beyond the scope of the Loki exporter. Translating between Traces and Logs (or the other way around) is something that should be done at a different level, perhaps using the proposed "connectors" feature (cc @djaglowski). I'm closing this issue, but feel free to reopen if you think there's something specific about Loki that I'm not considering.

cc @mar4uk

**Comment by jean** [comment]
@jpkrohling I'm fine with closing this. The better way is probably just to enable sending logs from the web client.
