### ISSUE TITLE
Add an ability to select Kafka partition based on resource tags for metrics

### ISSUE THREAD

**Issue by SHaaD94** [open-telemetry/opentelemetry-collector-contrib#31675]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

Our metric aggregation backend consumes Kafka partitions and needs each metrics from each server to land into the same Kafka partition. 

### Describe the solution you'd like

I would like to have a flag in kafka exporter, which would indicate the result kafka payload would have a partitioning key, calculated based on sorted resource tags.

### Describe alternatives you've considered

Alternative to this would be to write an additional balancing middleware.

### Additional context

I have already implemented the feature in the pull request https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31315
Would really appreciate any feedback on it.

Thank you!

**Comment by SHaaD94** [comment]
Closing, since the change was merged.

**Comment by crobert-1** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31315 👍
