### ISSUE TITLE
Can't run tests because of missing 'newAssertNoErrorHost'

### ISSUE THREAD

**Issue by bouk** [open-telemetry/opentelemetry-collector-contrib#31678]
### Component(s)

cmd/otelcontribcol

## Description

I'm unable to run the tests because `newAssertNoErrorHost` is missing

```
> # github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol [github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol.test]
> ./exporters_test.go:608:10: undefined: newAssertNoErrorHost
> ./receivers_test.go:504:10: undefined: newAssertNoErrorHost
```

## Steps to Reproduce

`go test ./...`

## Expected Result

The tests run

## Actual Result

The tests fail to run

### Collector version

6dcabb2ea3d31b833fddfc27e1fb827a0344a932

**Comment by astencel-sumo** [comment]
Looking at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30901#discussion_r1473238409 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30884, the tests in `cmd/otelcontribtests` are not supposed to be run. They are being replaced and are not being run in CI.
