### ISSUE TITLE
Datadog APM Receiver: Supported Datadog API  v1+

### ISSUE THREAD

**Issue by jay-steyn** [open-telemetry/opentelemetry-collector-contrib#31688]
### Component(s)

receiver/datadog

### Is your feature request related to a problem? Please describe.

Currently trying to sync traces from the latest datadog agent to OTEL collector, and unable to.

### Describe the solution you'd like

Currently there is only support till v0.7
Would be great if we can get support for v1 + v2

**Comment by jpkrohling** [comment]
@jay-steyn, would you be interested in providing a PR to support this API?

**Comment by crobert-1** [comment]
_Removing `needs triage` based on code owner response._

**Comment by jay-steyn** [comment]
> @jay-steyn, would you be interested in providing a PR to support this API?

If I wrote in GO, I probably would have :)

**Comment by jpkrohling** [comment]
This receiver is community driven, without volunteers to implement this feature, it's likely that it won't be added. The stale marker will be removed for now, but without community support, this will be closed automatically in the future.

**Comment by jpkrohling** [comment]
I'm assuming you are talking about traces in this issue here, but it's worth noting that the v1 for metrics is being added right now.
