### ISSUE TITLE
Generate gauge metrics from traces

### ISSUE THREAD

**Issue by blizzah** [open-telemetry/opentelemetry-collector-contrib#31696]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

Some OTLP endpoints do not support the histogram metric type and therefore will not accept duration metrics generated by the spanmetrics connector.

### Describe the solution you'd like

A configurable option in the spanmetrics connector to generate duration metrics in gauge format as an alternative to histogram metrics.

### Describe alternatives you've considered

There are options to convert histogram metrics to summary or gauge metrics, however, fidelity is lost when converting histogram metrics to summary or gauge format.

**Comment by Frapschen** [comment]
can you give more detail about your use case?
