### ISSUE TITLE
[receiver/kubeletstats] volume metrics should include pvc reference

### ISSUE THREAD

**Issue by stoetti** [open-telemetry/opentelemetry-collector-contrib#31728]
### Component(s)

receiver/kubeletstats

### Is your feature request related to a problem? Please describe.

We want to monitor the available disk space of persistent volumes but the receiver does not provide any information to differentiate by volume type (pvc, emptydir, configmap, ...)

### Describe the solution you'd like

The stats endpoint of the kubelet returns a field "pvcref" for volumes of type persistentVolumeClaim. Adding the name and namespace from that field as label would make it possible to monitor actual disk usage for persistent volumes.

**Comment by TylerHelmuth** [comment]
@stoetti does the [resource attribute `k8s.volume.name`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9355dce6c04b89e76ef80e043709b5cc40c0de23/receiver/kubeletstatsreceiver/metadata.yaml#L37) contain the information you're looking for?

**Comment by stoetti** [comment]
Unfortunately not as we want to monitor the data for all resources in the cluster and the volume name is not an indicator for the type of the volume.

**Comment by jinja2** [comment]
We do support a [subset of volume types](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/internal/kubelet/volume.go#L24) and the pvc name is available as attr. You'll need to enable it with the below config
```
kubeletstats:
  extra_metadata_labels:
    - k8s.volume.type
```

Example metric with the attribute `k8s.persistentvolumeclaim.name`
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/22205748/9ff03065-1f96-4cda-8fad-ad2dbc85a970)

**Comment by stoetti** [comment]
> We do support a [subset of volume types](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/internal/kubelet/volume.go#L24) and the pvc name is available as attr. You'll need to enable it with the below config
> 
> ```
> kubeletstats:
>   extra_metadata_labels:
>     - k8s.volume.type
> ```
> 
> Example metric with the attribute `k8s.persistentvolumeclaim.name` ![image](https://private-user-images.githubusercontent.com/22205748/313303674-9ff03065-1f96-4cda-8fad-ad2dbc85a970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTc4NzgsIm5iZiI6MTcxMDc1NzU3OCwicGF0aCI6Ii8yMjIwNTc0OC8zMTMzMDM2NzQtOWZmMDMwNjUtMWY5Ni00Y2RhLThmYWQtYWQyZGJjODVhOTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEwMjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OWI1MDY2NmYzMmUxYjIxMjVlYTE5NDBhZTE0ZTkyYjdkNmI0OWM1MTI2NWZjZmNlMDRiMjMyYmVmOGE4NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IHhD-fhkDrsJRqtrxeavAtbRkZpUhJQYAxXH296Pfsg)

Great that is exactly what I was looking for :clap: 
It would be helpful to point that out in the docs.
