### ISSUE TITLE
Add support for TLS in memcachedreceiver

### ISSUE THREAD

**Issue by nitrotm** [open-telemetry/opentelemetry-collector-contrib#31729]
### Component(s)

receiver/memcached

### Is your feature request related to a problem? Please describe.

When memcached is executed with `--enable-ssl`, the scraper must support TLS DialContext.

### Describe the solution you'd like

Add the option to configure the TLS DialContext by adding new config settings. Probably the best is to embed the existing [TLS config module](https://github.com/open-telemetry/opentelemetry-collector/blob/ef9caab844a75d567f33eb3e9d62145b75e7ea92/config/configtls/configtls.go#L86C6-L86C18)

See [here](https://github.com/bradfitz/gomemcache/blob/24af94b0387418c51cc45a2e1fe6d4d1bef8a0fd/memcache/memcache_test.go#L151) for a sample implementation when building a new memcache client (currently, the go dep is pointing to a fork of this project, but the fork lags behind in term of features).

**Comment by djaglowski** [comment]
Makes sense to me. Will you make a PR @nitrotm?

**Comment by nitrotm** [comment]
do we know if that repo is still the best client implementation https://github.com/grobie/gomemcache?

sounds like the original author did some work since then (but still lacking the `Stats` command though):

This branch is [12 commits ahead of](https://github.com/grobie/gomemcache/compare/bradfitz%3Agomemcache%3Amaster...master), [30 commits behind](https://github.com/grobie/gomemcache/compare/master...bradfitz%3Agomemcache%3Amaster) bradfitz/gomemcache:master.

**Comment by nitrotm** [comment]
that being said, grobie implementation has support for TLS, so maybe best to use that: https://github.com/grobie/gomemcache/commit/331774faa4ecc88a33babb51f65f2f2d88746f53

**Comment by kernelpanic77** [comment]
@nitrotm I'd like contribute as well, let me know if there is anything I can do.
