### ISSUE TITLE
[loadbalancingexporter] provide timeout to k8s resolver

### ISSUE THREAD

**Issue by grzn** [open-telemetry/opentelemetry-collector-contrib#31757]
### Is your feature request related to a problem? Please describe.

With the default k8s client so sometimes get timeout errors like this
```
E0314 08:24:19.610919       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://172.20.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3Dip-10-0-17-162.eu-north-1.compute.internal&resourceVersion=4141611754": dial tcp 172.20.0.1:443: i/o timeout
```

### Describe the solution you'd like

it would be nice to configure the k8s client with a larger timeout.

**Comment by crobert-1** [comment]
Makes sense to me, especially since other resolvers are able to have their own timeout specified.

I investigated, it looks pretty straightforward to implement this.

**Comment by jpkrohling** [comment]
Even though I don't think I would increase the timeout in this case, I agree that users should be able to set a timeout.
