### ISSUE TITLE
[exporter/instana] Consider deprecating component

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#31765]
### Component(s)

exporter/instana

### Describe the issue you're reporting

I bumped into this while reading https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30048, but for context, IBM Instana Observability is a vendor-specific backend that accepts trace data.

[According to their documentation](https://www.ibm.com/docs/en/instana-observability/current?topic=apis-opentelemetry), this exporter is deprecated for usage. The [officially recommended way to use the OpenTelemetry Collector to export telemetry is to use the OTLP exporter](https://www.ibm.com/docs/en/instana-observability/current?topic=opentelemetry-sending-data-instana-backend), and set a specific setting in your Instana backend.

Is there a reason to keep this exporter? Note that marking it as deprecated is not deleting it, but simply a notification that users should migrate to what Instana officially supports. [Read here for deprecation information in the collector](https://github.com/open-telemetry/opentelemetry-collector?tab=readme-ov-file#deprecated).

**Comment by jpkrohling** [comment]
Sounds good to me, but given this is owned by a vendor, I'd request their input on this.

**Comment by hickeyma** [comment]
@joshleecreates Do you mind answering this?

**Comment by joshleecreates** [comment]
Yes, we should mark this as deprecated, thank you!

**Comment by joshleecreates** [comment]
No problem at all, thank you for catching the discrepancy!
