### ISSUE TITLE
How to use pprof extension for profiling

### ISSUE THREAD

**Issue by mmynk** [open-telemetry/opentelemetry-collector-contrib#31781]
### Component(s)

extension/pprof

### Describe the issue you're reporting

I am trying to use the `pprof` extension in an OpenTelemetry collector.

I have added the following to my config `otelcol.yaml`:
```yaml
extensions:
  pprof:
  pprof/1:
    endpoint: "127.0.0.1:1777"
    block_profile_fraction: 3
    mutex_profile_fraction: 5
    save_to_file: "cpu.pprof"
```

However, I am not seeing anything at that endpoint. Also the following command errors out:
```sh
$ go tool pprof http://localhost:1777/debug/pprof/profile\?seconds\=30

Fetching profile over HTTP from http://localhost:1777/debug/pprof/profile?seconds=30
http://localhost:1777/debug/pprof/profile?seconds=30: Get "http://localhost:1777/debug/pprof/profile?seconds=30": dial tcp 127.0.0.1:1777: connect: connection refused
failed to fetch any source profiles
```

I am sure I am missing something but being inexperienced with using profilers, I am not sure what. Do I need to `ListenAndServe` manually? Would appreciate any guidance.

**Comment by honeychaudharyc** [comment]
Hi @mmynk,
Can you try below configuration in your otelcol.yaml file-
```
receivers:
  otlp:
    protocols:
      http:
      grpc:

extensions:
  pprof:
    endpoint: localhost:1777

exporters:
  debug:
     verbosity: detailed 
    
service:
  extensions: [pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
```

I used this and it works-
![pprof_extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/161001105/6ff09fc9-f56f-46b3-b4ab-565738521fee)

**Comment by mmynk** [comment]
I missed adding:
`extension: [pprof]` to `service`.
Thank you, @honeychaudharyc.
