### ISSUE TITLE
CloudWatch logGroup support encryption at rest using KmsKey

### ISSUE THREAD

**Issue by edwin-Marrima** [open-telemetry/opentelemetry-collector-contrib#31788]
### Component(s)

internal/aws

### Is your feature request related to a problem? Please describe.

Organizations maintain rigorous standards regarding data encryption. In my organization, it's imperative to encrypt all eligible data on AWS at rest utilizing our designated KMS key.

However, there's a significant limitation within the [internal/aws/cwlogs](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal/aws/cwlogs) package designed for AWS CloudWatch interaction. This limitation arises from its inability to create CloudWatch LogGroups while specifying a custom KMS key, aside from the default option. Consequently, tools like [exporter/awsemfexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter), which rely on this package, are unable to encrypt log data within CloudWatch LogGroups at rest using a custom KMS key.

### Describe the solution you'd like

Enhance the functionality of the internal/aws/cwlogs package to enable encryption of CloudWatch LogGroup data at rest using a specified KMS key. This addition will empower tools such as exporter/awsemfexporter to encrypt log data within CloudWatch LogGroups using a custom KMS key.

**Comment by trc-ikeskin** [comment]
This feature would be extremely beneficial for the the [exporter/awscloudwatchlogsexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awscloudwatchlogsexporter) as well and should be considered basic a basic mandatory feature for automatic log group creation.

Any news on this?
