### ISSUE TITLE
ottl test cases should not use Local timezone

### ISSUE THREAD

**Issue by ppalsingh** [open-telemetry/opentelemetry-collector-contrib#31797]
## Description
ottl test cases fail when executed from India timezone. The test case uses Local timezone which should be not be used. We should use UTC timezone in test cases.

## Steps to Reproduce
Execute testcases in India timezone.
## Expected Result
Testcases should pass.
## Actual Result
Testcases fail.

### Collector version

v0.96.0

## Environment
OS:  Ubuntu 20.04
Compiler(if manually compiled): go1.21.3

### Log output
```
--- FAIL: Test_TruncateTime (0.00s)
    --- FAIL: Test_TruncateTime/truncate_old_time (0.00s)
        func_truncate_time_test.go:76: 
                Error Trace:   opentelemetry-collector-contrib/pkg/ottl/ottlfuncs/func_truncate_time_test.go:76
                Error:          Not equal: 
                                expected: 337318200000000000
                                actual  : 337320000000000000
                Test:           Test_TruncateTime/truncate_old_time
FAIL
FAIL    github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/ottlfuncs    0.031s
```

**Comment by crobert-1** [comment]
Fixed by #31798
