### ISSUE TITLE
Exporting docker_events in `splunk_hec` to Splunk Enterprise results in 400 Bad Request

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector-contrib#3179]
**Describe the bug**
Exporting in `splunk_hec` to Splunk Enterprise results in 400 Bad Request

**Steps to reproduce**
- Deploy a fluent-bit Docker container with input docker_events and output forward
- Configure OTelCol 0.24.0 to receive `fluentforward` and export `splunk_hec` to Splunk Enteprise 8.1.4

**What did you expect to see?**
Data in Splunk Enterprise

**What did you see instead?**
400 Bad Request

**What version did you use?**
0.24.0 (no issues with 0.23.0)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: Docker on MacOS
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
Possible regression due to #3036?

**Comment by dmitryax** [comment]
The 0.24.0 has a known bug fixed here https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/f1ee616c4d90c4726cb73e4a4e6b4268e382cf66
Can you try the latest build instead?

**Comment by atoulme** [comment]
Is this a dup of #3180?

**Comment by dmitryax** [comment]
The bug was fixed in 0.25.0
