### ISSUE TITLE
Exporting cpu/mem in splunk_hec to Splunk Enterprise results in 400 Bad Request

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector-contrib#3180]
**Describe the bug**
Exporting in `splunk_hec` to Splunk Enterprise results in 400 Bad Request

**Steps to reproduce**
- Deploy a fluent-bit Docker container with input cpu (or mem) and output forward
- Configure OTelCol 0.24.0 to receive `fluentforward` and export `splunk_hec` to Splunk Enteprise 8.1.4

**What did you expect to see?**
Data in Splunk Enterprise

**What did you see instead?**
400 Bad Request

**What version did you use?**
0.24.0 (tested back to 0.21.0 and same issue)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: Docker on MacOS
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by atoulme** [comment]
Can you post more context, for example the yaml used?

**Comment by dmitryax** [comment]
The bug was fixed in 0.25.0
