### ISSUE TITLE
Sampling race condition causes initial metric to be reported with a 0 value

### ISSUE THREAD

**Issue by sergiuiacob1** [open-telemetry/opentelemetry-collector-contrib#31807]
### Component(s)

exporter/datadog

## Description
I've set up a counter metric to track "events". The counter is emitted using Prometheus Push Gateway and scraped by an Open Telemetry agent. I've set OTel to export data to Datadog. I've set it to report only the delta for the counters, i.e.
```
      datadog:
        metrics:
          sums:
            cumulative_monotonic_mode: to_delta
          histogram:
            counters: true
        api:
          site: datadoghq.com
          key: ${env:DATADOG_API_KEY}
```

I can see OTel scraping the first 2 values for my metric with the new set of label values
```
OTEL reports first datapoint:
NumberDataPoints #2
Data point attributes:
     -> app: Str(shoreline)
     -> customer_id: Str(cust0)
     -> exported_instance: Str(cust0-proxy-backend-0)
     -> exported_job: Str(ops_backend)
     -> exported_namespace: Str(cust0-backend)
     -> name: Str(a2)
     -> namespace: Str(cust0-backend)
     -> operation: Str(create)
     -> service: Str(cust0-proxy-backend-0)
     -> status: Str(succeeded)
     -> type: Str(action)
StartTimestamp: 2024-03-15 16:35:05.515 +0000 UTC
Timestamp: 2024-03-15 16:35:05.515 +0000 UTC
Value: 1.000000

OTEL reports second datapoint:
NumberDataPoints #2
Data point attributes:
     -> app: Str(shoreline)
     -> customer_id: Str(cust0)
     -> exported_instance: Str(cust0-proxy-backend-0)
     -> exported_job: Str(ops_backend)
     -> exported_namespace: Str(cust0-backend)
     -> name: Str(a2)
     -> namespace: Str(cust0-backend)
     -> operation: Str(create)
     -> service: Str(cust0-proxy-backend-0)
     -> status: Str(succeeded)
     -> type: Str(action)
StartTimestamp: 2024-03-15 16:35:05.515 +0000 UTC
Timestamp: 2024-03-15 16:36:05.515 +0000 UTC
Value: 1.000000
```

Datadog receives new time series at 18:36:05. Because the value difference between the 2 timestamps is 0, the initial metric value (initial delta) is 0 as well.
The previous Datadog metric timestamp was at 18:35:05.

<img width="1119" alt="Screenshot 2024-03-15 at 18 43 36" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/22725336/168c6b19-973a-443e-8f86-4f9ec6421a20">

## Steps to Reproduce
1. Create a counter
2. Set up Datadog exporter
3. Emit datapoints through OTel with new label values
4. Eventually, there will be a "miss" and the delta for a new label set will be `0`

## Expected Result

OTel should always report the delta for an initial set of label values for a counter to be that metric's value – in my case, 1.

Specifically, in my screenshot in Datadog, I should have seen the initial delta, which is `1` for my metric.

## Actual Result

Sometimes the initial counter value is the true initial delta (the first value counted), sometimes it's 0.

### Collector version

0.96.0

## Environment
OS: Ubuntu 20.04
OTel version: 0.96.0. Also reproduced on 0.71.0

### OpenTelemetry Collector configuration

```yaml
datadog:
        metrics:
          sums:
            cumulative_monotonic_mode: to_delta
          histogram:
            counters: true
        api:
          site: datadoghq.com
          key: ${env:DATADOG_API_KEY}
```
```


### Log output

_No response_

### Additional context

_No response_

**Comment by sergiuiacob1** [comment]
And here is an example where things worked as expected:

First sample reported at `2024-03-19 14:11:07.844 +0000 UTC`
```
NumberDataPoints #0
Data point attributes:
     -> app: Str(shoreline)
     -> customer_id: Str(cust0)
     -> exported_instance: Str(cust0-proxy-backend-0)
     -> exported_job: Str(ops_backend)
     -> exported_namespace: Str(cust0-backend)
     -> name: Str(sergiu_test)
     -> namespace: Str(cust0-backend)
     -> operation: Str(create)
     -> service: Str(cust0-proxy-backend-0)
     -> status: Str(succeeded)
     -> type: Str(action)
StartTimestamp: 2024-03-19 14:11:07.844 +0000 UTC
Timestamp: 2024-03-19 14:11:07.844 +0000 UTC
Value: 1.000000
```

Second sample reported at `2024-03-19 14:12:07.844 +0000 UTC`:
```
NumberDataPoints #0
Data point attributes:
     -> app: Str(shoreline)
     -> customer_id: Str(cust0)
     -> exported_instance: Str(cust0-proxy-backend-0)
     -> exported_job: Str(ops_backend)
     -> exported_namespace: Str(cust0-backend)
     -> name: Str(sergiu_test)
     -> namespace: Str(cust0-backend)
     -> operation: Str(create)
     -> service: Str(cust0-proxy-backend-0)
     -> status: Str(succeeded)
     -> type: Str(action)
StartTimestamp: 2024-03-19 14:11:07.844 +0000 UTC
Timestamp: 2024-03-19 14:12:07.844 +0000 UTC
Value: 1.000000
```

Datadog received the first metric datapoint correctly, with a value of `1`:
<img width="613" alt="Screenshot 2024-03-19 at 16 21 20" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/22725336/6c4c3cfd-a7ad-4ca7-a574-67d7be2f510e">

**Comment by mx-psi** [comment]
Hi @sergiuiacob1, can you try using the [cumulative to delta processor](ttps://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/cumulativetodeltaprocessor#cumulative-to-delta-processor) instead of the `metrics::sums::cumulative_monotonic_mode` option?

This is what we [currently recommend](https://docs.datadoghq.com/opentelemetry/guide/otlp_delta_temporality/#converting-to-delta-temporality-on-the-collector) for these setups, and I want to verify if the issue persists when using this component instead of the fallback logic in the exporter.
