### ISSUE TITLE
[exporter/awss3] When using encoding extension, file format extension should be configurable

### ISSUE THREAD

**Issue by adcharre** [open-telemetry/opentelemetry-collector-contrib#31818]
### Component(s)

exporter/awss3

### Describe the issue you're reporting

When using the new encoding extension option to marshal data introduced in PR #31801, the generated key contains the ID of the extension. This can be long and contain characters that either don't make sense for a file extension or could be invalid for an S3 key.
For example given an extension defined in the config file as:

```yaml
extension:
   textencoding/myspecialtextencoding:
```

A key would be generated similar to the following:
`mytrace/year=2024/month=03/day=18/hour=12/minute=02/myprefixtrace_12345.textencoding/myspecialtextencoding`

(where `keyprefix=mytrace`, `prefix=myprefix` and `metadata=trace`)

A better approach would be to allow the user to specify the required extension as part of the AWS S3 configuration or to have no extension at all.

**Comment by crobert-1** [comment]
_Removing `needs triage`, code owner requested this issue be filed originally, and has approved PR._

Thanks for filing and making the change @adcharre!

**Comment by crobert-1** [comment]
Can this issue be closed? It looks like it's been resolved by #31833.

**Comment by adcharre** [comment]
> Can this issue be closed? It looks like it's been resolved by #31833.

Closing, as indeed fixed by that PR.
