### ISSUE TITLE
[receiver/vcenter]: Optimize vCenter Receiver to use concurrency

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#31837]
### Component(s)

receiver/vcenter

### Is your feature request related to a problem? Please describe.

I'm lead to believe that larger environments have a harder time using the receiver due to the large number of requests that need to be made.

For larger environments the amount of requests can show how the current synchronous code has some room for improvement. I think once we scaled up it was pretty evident that we were bottlenecking on requests, particularly for VMs. 

### Describe the solution you'd like

From my recollection I don't think that the MetricsBuilder maintains some state that prevented easy parallelization, however we could parallelize/batch the requests to get better performance.

The tooling [mitmproxy](https://mitmproxy.org/) really helped us identify the issue as the massive number of requests made individually were stacking up to be quite a time sink. 

### Additional context

For an environment of 2000 VMs it was taking sometimes minutes to complete a collection, based off of early experiments, hoping to cut it down to a collection interval of seconds.

**Comment by schmikei** [comment]
Me and @StefanKurek plan to be taking this effort on, feel free to assign us to it

**Comment by atoulme** [comment]
maybe this spike can help: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30624

**Comment by StefanKurek** [comment]
@schmikei I think this can be closed now with the recent performance enhancements. I'll let you decide.
