### ISSUE TITLE
Loki Receiver + HeaderSetter + Loki Exporter Issue

### ISSUE THREAD

**Issue by outofsight** [open-telemetry/opentelemetry-collector-contrib#31847]
### Component(s)

exporter/loki, extension/headerssetter, receiver/loki

### Describe the issue you're reporting

I'm trying to deploy a Loki collector agent that collect logs from network agents on a Loki endpoint and forward them on several Loki backend.

The agents correctly send Authorization header and X-Scope-OrgID header to the collector. The collector is expected to forward these headers to Loki backend for proper tenant assignment of logs.

The idea is the same [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24682#issuecomment-1660017012) but with a Loki receiver and multiple exporters.

I'm still not sure if possible to add multiple Loki exporter, but by first test it seems that with the adapted above setup Loki backend is not receiving Authorization and X-Scope-OrgID headers when using a Loki receiver while correctly receiving header when using the otlp receiver.

**Comment by jpkrohling** [comment]
Can you share a minimal configuration file that depicts the issue?

**Comment by jpkrohling** [comment]
I'm removing Loki exporter from the equation, as I'm confident this would affect any other exporter as well.
