### ISSUE TITLE
Cluster name disabled for mongodbatlasreceiver metrics

### ISSUE THREAD

**Issue by preshit1505** [open-telemetry/opentelemetry-collector-contrib#31842]
### Component(s)

receiver/mongodbatlas

### Is your feature request related to a problem? Please describe.

We are trying to create mongodb atlas grafana dashboard where we using the mongodbatlasreceiver in our OTEL collector to get the metrics. Since the  mongodb_atlas.cluster.name in metadata.yaml has been disabled, which causes not able to filter the metrics data based on the cluster name
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/mongodbatlasreceiver/metadata.yaml#L34C2-L37

### Describe the solution you'd like

solution for the above issue would be enabling the cluster name filter in the metrics

### Describe alternatives you've considered

As of now, we dont really have an alternative to resolve this issue in our dashboards

**Comment by preshit1505** [comment]
Hello @crobert-1 , I have not been able to make it work. How can i enable it in my collector config? Do we have any flag to enable? I only see labels like projects, organization, page_size, types in EVENTS

**Comment by crobert-1** [comment]
The configuration I shared in my comment should enable the resource attribute to be ingested by the collector. Are you able to add the `resource_attributes` block to your config? (If this doesn't make sense, can you share your current config?)

**Comment by preshit1505** [comment]
ohh so this block can be added directly in the collector config. This is my current config:
`config:
  receivers:

    mongodbatlas:
      public_key: ${MONGODB_PUBLIC_KEY}
      private_key: ${MONGODB_PRIVATE_KEY}
      events:
        projects:
          - name: bedrock-control-plane-preview
        organizations:
          - id: XXXXX
        poll_interval: 1m
        page_size: 100
        max_pages: 50`

**Comment by preshit1505** [comment]
@crobert-1 omg it WORKED. Thank you so much for this help.

**Comment by crobert-1** [comment]
Glad to hear it! Happy to help 👍
