### ISSUE TITLE
[connector/servicegraph] New labels for service disambiguation and identification

### ISSUE THREAD

**Issue by t00mas** [open-telemetry/opentelemetry-collector-contrib#31889]
### Component(s)

connector/servicegraph

### Is your feature request related to a problem? Please describe.

The `connection_type` label currently allows `database`, `messaging_system`, and `virtual_node` values.

For `virtual_node` values, there’s no clear distinction between which of the nodes is the `virtual_node` (e.g. client vs server), and has to be inferred from other attributes.

There’s also the case where just having a value of `database` or `messaging_system` falls short to identify if it’s also un-instrumented / `virtual_node`.

### Describe the solution you'd like

1. In the cases where `connection_type` had the value of `virtual_node`, generate a new label `virtual_node` with a value of either `client` or `server`.

2.1. In the cases where `connection_type` is of value `database`, surface either `client_db_system` or `server_db_system` labels, with the same value as the `db.system` resource attribute.

2.2. In the cases where `connection_type` is of value messaging_system, then surface either `client_messaging_system` or `server_messaging_system` labels, with the same value as the messaging.system resource attribute.

**Comment by jpkrohling** [comment]
I understand this wouldn't be a breaking change, right? All the changes are about adding new labels when specific values are specified.

**Comment by t00mas** [comment]
Absolutely, the idea is for this to be fully optional, and about just adding a new label if enabled.

Also as an update to the issue, I think the change would only affect adding 1 new label, `virtual_node`, since the other 4 are covered under a combination of existing features (dimensions and prefixes).

**Comment by jpkrohling** [comment]
@t00mas, was this handled by #32826 ?

**Comment by t00mas** [comment]
> @t00mas, was this handled by #32826? I'm assuming it was and I'm closing this issue, but let me know if there's still something pending and I'll reopen.

That's right, I don't think anything is pending. Thanks!
