### ISSUE TITLE
[connector/spanmetrics] Add maximum span duration metric

### ISSUE THREAD

**Issue by swar8080** [open-telemetry/opentelemetry-collector-contrib#31885]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

Hello, adding a `duration_max` span metric would be helpful for finding anomalies in latency

### Describe the solution you'd like

The connector flushes metrics at a configurable interval, so maybe it could emit a gauge with the highest latency seen since the last flush

For cumulative span metrics, I suppose it could flush a value of zero if no spans are seen in-between flushes? For delta span metrics it would not emit anything in that case?

I'm also assuming new configuration would be good for disabling this metric

### Describe alternatives you've considered

Lmk if there's an alternative

### Additional context

I can implement this change

**Comment by crobert-1** [comment]
Span duration metrics are currently exported from the connector in the form of histograms with buckets that can be modified as users see fit. Is there a reason this is insufficient for your use case?

**Comment by crobert-1** [comment]
Would the idea be to then have a datapoint within the metric representing each application that's sending data in?

That generally makes sense to me, but one question I have is how much effort is required to allow the connector to export metrics that aren't histograms. It looks like metrics are all output as histograms from the README, so I'm wondering what this change would entail from that perspective. (Correct me if I'm wrong here and it's already exporting gauges.)

**Comment by swar8080** [comment]
>Would the idea be to then have a datapoint within the metric representing each application that's sending data in?

I was picturing it working like the existing `calls` counter span metrics. Just like how `calls` creates a counter metric for each unique combination of specific span attributes seen, like span name, span kind, status code, etc., a corresponding `maximum` gauge metric could be created too. The gauge could track max latency seen for spans with those same attributes within the `metrics_flush_interval`.

>That generally makes sense to me, but one question I have is how much effort is required to allow the connector to export metrics that aren't histograms 

The control flow seems mostly the same as the `calls` metric and needs to be adapted for the gauge and maximum tracking. That might still be a couple hundred lines of non-test code.

The tasks coming to mind are:
- Where the count for the `calls` metric is incremented, also determine the new maximum for those span attributes. Only exemplars for spans with the maximum latency would be kept
- When flushing metrics to the exporters, conversion from the struct used to track the maximums to gauge metrics
- Resetting the maximum after flushing. That way a new maximum can be tracked for the next flush and also omitted from flushing until there's a new matching span
- Configuration to opt-out of the `maximum` metric

**Comment by portertech** [comment]
I suppose it would be too cumbersome to support specific service (and/or span type) explicit histogram bucket configuration?

**Comment by swar8080** [comment]
> I suppose it would be too cumbersome to support specific service (and/or span type) explicit histogram bucket configuration?

That's a workaround but creates more effort for the (1 person) observability team to maintain and explain how it works to other teams. I suppose it'd need a filter, span metric component, and pipeline configured for each customization
