### ISSUE TITLE
aws: Move duplicated ECS metadata clients into internal/aws

### ISSUE THREAD

**Issue by pingleig** [open-telemetry/opentelemetry-collector-contrib#3188]
**Is your feature request related to a problem? Please describe.**

Currently there are two places using ECS metadata endpoint to get info like cluster name

- `resourcedetectionprocessor/internal/aws/ecs`
- `awsecscontainermetricsreceiver`

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/88782b0cbdf9f3f7f4f3c15900ba153e3cb7bf56/processor/resourcedetectionprocessor/internal/aws/ecs/metadata_ecs.go#L24-L24

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e663b5991a04d1ae3477aacb1b6f2e64d186dc20/receiver/awsecscontainermetricsreceiver/awsecscontainermetrics/metadata.go#L18

For #1395 prometheus ecs discovery, we need cluster detection using ECS metada API so user don't need to config it manually. We can't make use of neither components along the pipeline. The extension runs at the start of the pipeline and needs the cluster name to generate a prometheus file sd config for receiver.

**Describe the solution you'd like**

There is a `internal/aws` package for sharing common aws specific logic. There is no official ECS metada client (and struct definitions). I think we should merge into the common logic to a package like `internal/aws/ecsutil` 

**Describe alternatives you've considered**

It's possible to import resource detector processor in other components but it's kind of strange and makes the dependency more complex.

**Additional context**

N/A

**Comment by rmfitzpatrick** [comment]
Opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5994 to meet this requirement

**Comment by rmfitzpatrick** [comment]
This has been resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5994

**Comment by pingleig** [comment]
@rmfitzpatrick thanks!
