### ISSUE TITLE
koanf parsing uses the same delimiter

### ISSUE THREAD

**Issue by mike1997-code** [open-telemetry/opentelemetry-collector-contrib#31925]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

I found that in addition to the code here([url](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/008f032b04c39e5812046cf1f54cd41a7b3d32bb/cmd/opampsupervisor/supervisor/supervisor.go#L535)) using `.` as the delimiter, `opampsupervisor` and `otel` parsing configurations both use `::`. Maybe it would be a better practice to use `::` uniformly?

**Comment by odubajDT** [comment]
Hi! I would like to start this issue! cc @evan-bradley
