### ISSUE TITLE
[receiver/httpcheck] Support log pipeline for httpcheck events

### ISSUE THREAD

**Issue by smithclay** [open-telemetry/opentelemetry-collector-contrib#31933]
### Component(s)

receiver/httpcheck

### Is your feature request related to a problem? Please describe.

When the httpcheck receiver runs a check, optionally allow users to capture the result of the check as an OTLP log, optionally with the response body.

### Describe the solution you'd like

Support for emitting log related to the status of checks in the httpcheck receiver. Attributes should be consistent with https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/httpcheckreceiver/documentation.md

### Describe alternatives you've considered

This could be done via a connector (turn the metrics from httpcheck into logs), but this seems more appropriate as a native capability of the http check to emit OTLP logs.

**Comment by carlosalberto** [comment]
I have a draft PR on how this could be supported: https://github.com/carlosalberto/opentelemetry-collector-contrib/pull/2

Please provide feedback on whether this is a feasible approach ;) @codeboten
