### ISSUE TITLE
[cmd/opampsupervisor] Errors during bootstrapping will fail to shut down collector

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#31943]
### Component(s)

cmd/opampsupervisor

## Description

If collector bootstrapping fails, the Stop method will not be called for the collector command. This causes the collector to outlive the supervisor, which ends up blocking any attempts for the supervisor to start up again (collector occupies port 8888)

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/011256c9ba76bac0d55bed1e1d414572dc8073c5/cmd/opampsupervisor/supervisor/supervisor.go#L308

Solution would be to use `defer` statements to ensure the command is always stopped before returning from the `getBootstrapInfo` method.

### Collector version

f8627a7041d7c1bfda9b641d35265a10e8e1ffc0

## Environment
OS: macos
Compiler(if manually compiled): go 1.22

**Comment by crobert-1** [comment]
I don't have very much experience with the area of the collector, but from your description and PR it makes sense to me. Thanks for filing and submitting a fix!
