### ISSUE TITLE
Character encoding issue in logs

### ISSUE THREAD

**Issue by psneha716** [open-telemetry/opentelemetry-collector-contrib#32000]
### Component(s)

receiver/filelog

### Describe the issue you're reporting

I've been trying to send logs from my ECS cluster through opentelemetry collector. Some of the characters are not displaying properly in the logs, seems like some encoding issue. Is there any way to fix it?
"\u0006stdout\u0010�������\u0017\u001a�\u00172023-12-14 03:10:49,602

**Comment by crobert-1** [comment]
Hello @psneha716, do you know what encoding the logs files are in? 

You can set the expected encoding value using the `encoding` option in the receiver. The supported encoding list for this receiver can be found [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver#supported-encodings).

**Comment by codeboten** [comment]
@psneha716 any update on this issue? did setting the encoding fix the problem?
