### ISSUE TITLE
[extension/opamp] Add support for custom messages

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#32021]
### Component(s)

extension/opamp

### Is your feature request related to a problem? Please describe.

Some components may provide extra capabilities that can be leveraged by an OpAMP server. In the [OpAMP specification, these are codified as custom messages](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#custom-messages), but there is currently no way for a collector component to take advantage of these custom messages.

Since [support for custom messages has been released](https://github.com/open-telemetry/opamp-go/pull/209) in the opamp-go library, we should be able to start using them in the opamp extension.

### Describe the solution you'd like

The opampextension is the sole communication point between the OpAMP server and the collector. Because of this, it follows that other components that wish to communicate with the OpAMP server will need to do so through the opampextension. 

Similar to the storage extension interface, we propose the following interface for interacting with the opampextension:

```go
type CustomMessageCallback func(*protobufs.CustomMessage)

type CustomCapabilityRegistry interface {
    Register(capability string, callback CustomMessageCallback) (CustomCapability, error)
}


type CustomCapability interface {
    SendMessage(messageType string, message []byte) (messageSendingChannel chan struct{}, err error)
    Unregister()
}
```

Here, opampextension would satisfy the `CustomCapabilityRegistry` interface, allowing for other components to register the custom capability it supports. The opampextension will then keep track of what capabilities have been registered, and a list of callbacks for each capability, since multiple components may register as supporting the same capability.

The list of supported custom capabilities that the opampextension has will be the union of all unique capability strings registered.

When a custom message for the registered capability is sent from the server to the agent, it is broadcast to all callbacks for the capability. These callbacks are called asynchronously (in their own separate goroutines).

When registering, an object satisfying the `CustomCapability` interface is returned that can be used to send messages for the custom capability, as well as to unregister the custom capability. 

This design allows the registry to keep track internally of which calls to register correspond to which calls of unregister, so that a single instance of a component cannot unregister a capability for a different component. It also restricts sending a message until after the capability has been registered.

Calling `SendMessage` after `Unregister` will return an error and the message will not be sent.

The supervisor will simply proxy custom messages between the agent and the OpAMP server, as it does for other messages.

**Comment by andykellr** [comment]
For context, I added the CustomMessage feature to [opamp-spec](https://github.com/open-telemetry/opamp-spec) and [opamp-go](https://github.com/open-telemetry/opamp-go) and reviewed this proposal with Brandon. Looking forward to feedback.

**Comment by BinaryFissionGames** [comment]
I update the proposal to add:
1. An error to `Register`, since `SetCustomCapabilities` can return an error
2. Copy the return signature of the OpAMP client for `SendMessage`, so that the caller can decide how to handle what to do when a custom message is already sending (see the [comment on `SendCustomMessage`](https://github.com/open-telemetry/opamp-go/blob/c7fc5850ffdf65e97a39b080d73f1f23346bf52a/client/client.go#L126) for the opamp client)

**Comment by BinaryFissionGames** [comment]
Closing as completed with #32951
