### ISSUE TITLE
[connector/failover] Ability to skip `max_retries` for levels

### ISSUE THREAD

**Issue by sinkingpoint** [open-telemetry/opentelemetry-collector-contrib#32031]
**Is your feature request related to a problem? Please describe.**

The failover connector currently has `max_retries` setting that allows setting a maximum number of retries before completely removing an exporter from the pool. In our case, our high priority receiver might be out for hours, or even days, so there's no real setting that makes sense for us. 

**Describe the solution you'd like**

We should have a way to disable the max_retries setting so that the connector will continue to poll the higher priority receivers, regardless of how long they have been out. Other components use a magic value of 0 for this purpose, but in the failover connector a `max_retries` of 0 automatically rejects every pipeline and errors.

**Describe alternatives you've considered**

 The alternative is just to set this to a very large value, potentially calculated based off of the retry time, and some maximum acceptable length of time, but this just sets a time bomb

**Comment by akats7** [comment]
Hi @sinkingpoint, thanks this is a good add.
