### ISSUE TITLE
Ensuring Consistency between `service.instance.id` and `instanceId` in `opampextension`

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#32034]
### Component(s)

extension/opamp

### Is your feature request related to a problem? Please describe.

While using `opampextension`, I found that when I wanted to query self-monitoring metrics and only knew the `instanceId` but not the `service.instance.id`, due to the inconsistency in their values, I was unable to query using `instanceId`.

If it were possible for `instanceId` and `service.instance.id` to be kept consistent as they are in `opampsupervisor`, then it would be convenient for me to query using the `instanceId`.

### Describe the solution you'd like

"Considering the [OpAMP](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agenttoserverinstance_uid) and [OTEL](https://github.com/open-telemetry/semantic-conventions/blob/5a94098c2a80417f4d5bde58ed470314290ed7da/docs/resource/README.md?plain=1#L115-L119) specifications, where `instanceId` must be a ULID and `service.instance.id` is recommended to use UUID, I suggest the following:
1. `service.instance.id` uses ULID by default
2. `opampextension` directly reuses `service.instance.id` without setting the `instanceId` configuration item.

**Comment by evan-bradley** [comment]
Thanks for the detailed write-up. I will have to think over the solution more, but I think this is valid.

**Comment by mike9421** [comment]
Information can be synchronized at https://github.com/open-telemetry/opamp-spec/pull/186

**Comment by mike9421** [comment]
> FYI, we may move from ULID to UUID in opamp too: [open-telemetry/opamp-spec#186](https://github.com/open-telemetry/opamp-spec/pull/186)

Hi @tigrannajaryan It seems that OpAMP already uses UUID, this issue can be closed.
