### ISSUE TITLE
Optimize OTEL agent memory usage

### ISSUE THREAD

**Issue by rahuldimri** [open-telemetry/opentelemetry-collector-contrib#32035]
### Describe the issue you're reporting

Currently we see that OTEL agent (deployed on user's K8s cluster) consumes lot of memory as data increases. It would be helpful if we could optimize agent so it uses less memory.

**Comment by crobert-1** [comment]
Hello @rahuldimri, can you the full configuration that you're using that is consuming a lot of memory? Do you see memory usage growing over time? Can you expand on what you mean `as data increases`?

This will all be helpful in trying to determine the root cause of the issue you're seeing.
