### ISSUE TITLE
Why not use "--version" to get the version of OTEL?

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#32049]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

The way the version number is obtained in function [getBootstrapInfo](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e867aa84edb2dbe0570b57681ba62bdbf92e1d37/cmd/opampsupervisor/supervisor/supervisor.go#L432) is by `opampextension` connecting to `opampsupervisor`, then `opampsupervisor` traverses the data.

Why not use "`--version`" to let otel return the version number? I think this method will be more convenient.

**Comment by evan-bradley** [comment]
Hi @mike9421, thanks for raising this. In short, using the OpAMP extension instead of the `--version` flag on the Collector binary allows us to Collect additional information about the Collector outside of the information baked into the binary that the `--version` flag has access to. You can see a few attributes [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e867aa84edb2dbe0570b57681ba62bdbf92e1d37/extension/opampextension/opamp_agent.go#L185), but more may be reported to the Supervisor in the future.

**Comment by mike9421** [comment]
> Hi @mike9421, thanks for raising this. In short, using the OpAMP extension instead of the `--version` flag on the Collector binary allows us to Collect additional information about the Collector outside of the information baked into the binary that the `--version` flag has access to. You can see a few attributes [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e867aa84edb2dbe0570b57681ba62bdbf92e1d37/extension/opampextension/opamp_agent.go#L185), but more may be reported to the Supervisor in the future.

Do you mean that more information about the agent will be retrieved in getBootstrapInfo()  in the future, https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5c765a3303696554000c7259a1683c92b41f052b/cmd/opampsupervisor/supervisor/supervisor.go#L237 but for now, only the version number has been obtained, right?

If that's the case, then I have no issues. Initially, I thought if we are just retrieving the version number, we could simply use --version instead of establishing an OpAMP connection and then disconnecting it.

It seems that from version v0.93.0 onwards, the supervisor no longer retrieves the version number in getBootstrapInfo().
v0.93.0
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c06bed3f5befcb4cc9d2bd53610545d7fa269475/cmd/opampsupervisor/supervisor/supervisor.go#L247

v0.92.0
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e833bc5e1ace83593225d714f16f8f221b4c46ad/cmd/opampsupervisor/supervisor/supervisor.go#L172

@evan-bradley  Thank you for your reply, I am about to close this issue.
