### ISSUE TITLE
[Bug] AWS cloudwatch receiver doesn't use next token while discovering log groups

### ISSUE THREAD

**Issue by gsc2001** [open-telemetry/opentelemetry-collector-contrib#32053]
### Component(s)

receiver/awscloudwatch

## Description
AWS cloudwatch receiver while receiving log groups calls a paged API (DescibleLogGroups) which requires multiple calls using nextToken to get full response, the code does record next Token but never uses it. 

## Steps to Reproduce
Use aws cloudwatch receiver
## Expected Result
Discover all configured logs and collect logs
## Actual Result
Keeps discovering same log groups

### Collector version

v.0.93.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
_Removing `needs triage` as a code owner has opened a PR to resolve this issue._
