### ISSUE TITLE
 Update module github.com/kineticadb/kinetica-api-go to v0.0.4 breaks tests

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#32115]
### Component(s)

exporter/kinetica

### What happened?

The dependency upgrade in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32092 breaks tests, see https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8523629192/job/23346590004?pr=32092#step:8:315.

### Collector version

mainline

**Comment by am-kinetica** [comment]
Working on this now. Thanks.

**Comment by am-kinetica** [comment]
Updated the `kinetica-go-api` to version `0.0.4` and ran all the tests. I didn't find any issue and all the four tests ran just fine.

**Comment by am-kinetica** [comment]
@songy23 - Could you please share what you are getting on upgrade ? Which tests are failing ?

**Comment by songy23** [comment]
I did not run the tests, CI failed in the renovbot PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8523629192/job/23346590004?pr=32092#step:8:315

May be a flaky test then.
