### ISSUE TITLE
DataPoint Attributes to Resource Attributes Conversion

### ISSUE THREAD

**Issue by AlessandroFazio** [open-telemetry/opentelemetry-collector-contrib#32120]
### Component(s)

receiver/prometheus

### Describe the issue you're reporting

Hello, I have setup the Collector with a Prometheus Receiver to scrape metrics from targets and added to the scrape_config some prometheus metrics labels. I need these informations to be able to store metrics data in Opensearch indexes based on the value of these labels. 

The prometheus receiver put these metrics labels into metric data point attributes when converting in Otel format. However for my use case I need them to be placed in the resource attributes instead. So, I started looking at processors which could help me in this regard. 

Unfortunately, I hadn't find anything yet for my use case. This is what I found:

- Resource Processor seems to be scoped to resource attributes, not being able to lookup metric data point attribute
- Attribute Processor and Metrics Transform Processor both deals with telemetry data point attributes, but it seems they cannot add resource attributes

Maybe you can help me pointing to some material which I overlooked or some other workaround. Thanks in advance for your time.

**Comment by dashpole** [comment]
You are probably looking for the groupbyattrs processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor

**Comment by dashpole** [comment]
Let me know if you run into any issues

**Comment by AlessandroFazio** [comment]
Much thanks for the quick reply @dashpole.

It definitely looks like the right tool for the job. I tried it and it works perfectly. It seems that this processor gives other advanced capability which looks interesting. Much thanks.

Unfortunately it is not included yet in AWS Otel Collector (ADOT). Hope the will add it to their OtelCol distro.

**Comment by dashpole** [comment]
happy to help
