### ISSUE TITLE
Failed to connect to opensearch in TLS mode

### ISSUE THREAD

**Issue by Sidhartha-Biswal** [open-telemetry/opentelemetry-collector-contrib#32139]
**Describe the bug**
Opentelemetry-collector installation is failing after adding the configuration parameters for opensearch with certificates in values.yaml

**Steps to reproduce**
Update the below exporter configuration in values.yaml and then install opentelemetry-collector helm chart.

**What did you expect to see?**
Installation to be successful

**What did you see instead?**

The installation of opentelemetry-collector service is failing and the below error is showing in the logs.

Error: cannot start pipelines: failed to load TLS config: failed to load CA CertPool File: failed to load cert ca.crt: open ca.crt: no such file or directory; failed to shutdown pipelines: no existing monitoring routine is running; no existing monitoring routine is running
2024/03/27 12:58:11 collector server run finished with error: cannot start pipelines: failed to load TLS config: failed to load CA CertPool File: failed to load cert ca.crt: open ca.crt: no such file or directory; failed to shutdown pipelines: no existing monitoring routine is running; no existing monitoring routine is running

**What version did you use?**
0.80.1

**What config did you use?**
exporters:
opensearch/trace:
endpoint: myserver:9200
tls:
insecure: false
ca_file: ca.crt
cert_file: client.crt
key_file: client.key

**Environment**

**Additional context**

**Comment by YANG-DB** [comment]
We will review and address it ASAP

**Comment by Sidhartha-Biswal** [comment]
Hi @crobert-1,

I have kept the certificate files in the same folder where values.yaml is present and added the below code in values.yaml.

exporters:
opensearch/trace:
endpoint: myserver:9200
tls:
insecure: false
ca_file: ca.crt
cert_file: client.crt
key_file: client.key

**Comment by Sidhartha-Biswal** [comment]
Hi @crobert-1,

Is there any update regarding this issue?

**Comment by crobert-1** [comment]
> Is there any update regarding this issue?

No update from my side, we're mainly waiting on more feedback from code owners or any others that have more experience in this area.
