### ISSUE TITLE
[CI] `build-examples` build is broken

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#32138]
### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8532718349/job/23374328167?pr=32137

```
docker-compose -f examples/demo/docker-compose.yaml build
/bin/bash: line 1: docker-compose: command not found
make: *** [Makefile:350: build-examples] Error 127
Error: Process completed with exit code 2.
```

**Comment by BinaryFissionGames** [comment]
Looks like using `docker compose` instead of `docker-compose` may fix, according to this discussion?
https://github.com/orgs/community/discussions/116610

**Comment by crobert-1** [comment]
Thanks for the reference @BinaryFissionGames, looks right to me. The [active discussion](https://github.com/actions/runner-images/issues/9557) shows that runners are being actively upgraded. From what I can tell, it looks like that should be all that's necessary according to the [migration doc](https://docs.docker.com/compose/migrate/).
