### ISSUE TITLE
'memory request' feature for OTEL

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#32142]
### Component(s)

cmd/otelcontribcol

### Is your feature request related to a problem? Please describe.

During the use of OTEL, we found that when the system memory is insufficient, the startup of OTEL will cause a system OOM, which in turn causes user processes to exit. This can cause production accidents. This issue is related to #29347.

### Describe the solution you'd like

Before OTEL starts, it reads the available memory of the runtime environment (k8s, docker, etc.) and compares it with the value configured in 'memory request'. If the system memory cannot meet the 'memory request', then OTEL will not start and notify that the system memory is insufficient.

The configurable solution is as follows:
Expose the 'memory request' configuration item to users. OTEL can set the default value for this configuration item.

### Additional context

Here's an example:
The total memory of the server is 500MB. Assume that the current peak memory usage of the business process is 400MB (this situation is generally due to the increase in user activity of the business process).

At this time, if the network administrator deploys and starts OTEL, during the process of starting all components in the OTEL configuration file (he components have not all been started at this time, and no telemetry data has been received), the following may occur:

If the memory usage of OTEL exceeds 100MB, the system OOM will be triggered. At this time, the business process is likely to be killed by the system;

If OTEL provides the 'memory request' feature and the user configures the 'memory request' value to 120MB, in the above situation, OTEL will stop creating and starting components and prompt insufficient memory, so that it will not cause system OOM. This can ensure that the business process is still running, and at the same time, it can remind the user that the current available memory is not enough to start OTEL, and they can try to start OTEL again after a while.

The 'memory request' is the minimum requirement for the currently available system memory before all OTEL components are started. This ensures that the business process continues running before OTEL is completely started.

**Comment by mike9421** [comment]
I hope you could take a look at it amidst your busy schedule. @atoulme @crobert-1 @djaglowski

**Comment by crobert-1** [comment]
Hello @mike9421, is there any difference between this request and #29347?

**Comment by mike9421** [comment]
> Hello @mike9421, is there any difference between this request and #29347?

There is no difference, just because #29347 was closed by GitHub.

**Comment by crobert-1** [comment]
I've reopened the original issue. I'll close thissince that one has more discussion 👍
