### ISSUE TITLE
[pkg/ottl] [Append] Support for appending items into an array

### ISSUE THREAD

**Issue by michalpristas** [open-telemetry/opentelemetry-collector-contrib#32141]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

havent find a way to append an item to a slice easily

### Describe the solution you'd like

Append converter should append one or more values to an existing array if the field already exists and it is an array.
It should convert scalar values into an array if the field exists but is not an array
Creates an array containing the provided values if the field doesn’t exist

should be simple as `append(target, [Optional] source_single, [Optional] source_multi)` e.g `append(attributes['array.target'], "value")` or `append(attributes['array.target'],  attributes["array.source"])`

`append(attributes['array.target'], "value", attributes["array.source"])` is still valid
`append(attributes['array.target'])` with no optional should not yield error and act as noop

**Comment by TylerHelmuth** [comment]
Although OTTL supports it, we've gotta further away from parameters that can take multiple input types (essentially an `any`).

Instead I think we could have 2 parameters, both optional, 1 for single value and 1 for slice value.  Validation could check that at least 1 optional parameter is set.

**Comment by michalpristas** [comment]
updated description to reflect 2 optional argument

**Comment by ycombinator** [comment]
I think this issue can be closed now, as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33017 has been merged?

**Comment by evan-bradley** [comment]
Closing as solved via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33017.
