### ISSUE TITLE
Include ImageID in Resource attributes detected by k8sattributes processor

### ISSUE THREAD

**Issue by evantorrie** [open-telemetry/opentelemetry-collector-contrib#32152]
### Component(s)

`k8sattributes` procesor

### Is your feature request related to a problem? Please describe.

We currently make use of the `k8sattributes` processor to augment Resource attributes from pods running in our k8s clusters.

We are interested in obtaining the full sha256 digest version of the image associated with the container in a Kubernetes pod that is emitting telemetry, rather than relying on just the image name + tag.

### Describe the solution you'd like

If we include `container.id` in the `k8sattributes::metadata` array, we'd like to get not only `container.image.name`, `container.image.tag`, but also `container.image.id` added to the resource for that signal.

### Describe alternatives you've considered

Scrape information from kube-state-metrics (which does provide the image digest) and somehow cross-join that with the resource attributes determined by k8sattributes processor?

### Additional context

Currently it seems like the k8sattributes processor extracts the image name and image tag from the `v1.Pod.Spec.Containers` data structure.  The image digest is available in `v1.Pod.Status.ContainerStatuses[].ImageID`.

**Comment by TylerHelmuth** [comment]
This seems reasonable to me

**Comment by evantorrie** [comment]
Closed in favor of #34029 Enable populating `container_image.repo_digests` attribute
