### ISSUE TITLE
[receiver/azuremonitor] Add the ability to scrape more than 10 records 

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-collector-contrib#32165]
### Component(s)

receiver/azuremonitor

### Is your feature request related to a problem? Please describe.

The receiver only returns up to 10 records/dimensions of each metric. This is the [default value](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/monitor/armmonitor/options.go#L637) when using the Go SDK. One might also be interested in more than these default 10 records.

### Describe the solution you'd like

Add a setting to customize the `top` value

**Comment by crobert-1** [comment]
Do you mean the [`Top` member variable of the `MetricsClientListOptions` struct](https://github.com/Azure/azure-sdk-for-go/blob/0aded7668b60263a6e0105a4cb51b6aef3b821d0/sdk/resourcemanager/monitor/armmonitor/options.go#L637)? I see references to that struct in the receiver, but not the one linked in the description of this issue.

It makes sense to me, either way, from my limited understanding here.

**Comment by cmergenthaler** [comment]
> Do you mean the [`Top` member variable of the `MetricsClientListOptions` struct](https://github.com/Azure/azure-sdk-for-go/blob/0aded7668b60263a6e0105a4cb51b6aef3b821d0/sdk/resourcemanager/monitor/armmonitor/options.go#L637)? I see references to that struct in the receiver, but not the one linked in the description of this issue.
> 
> It makes sense to me, either way, from my limited understanding here.

Thanks for the link, seems like I've copied the wrong ref. Have adjusted my description!
