### ISSUE TITLE
Azure monitor exporter authentication

### ISSUE THREAD

**Issue by arjunmahishi** [open-telemetry/opentelemetry-collector-contrib#32163]
### Component(s)

exporter/azuremonitor

### Is your feature request related to a problem? Please describe.

The current implementation of the Azure monitor exporter does not support EntraID based authentication out of the box. So, One has to use [aad-auth-proxy](https://github.com/Azure/aad-auth-proxy) along with OTel. This additional tool adds a bit of maintenance overhead.

### Describe the solution you'd like

Are there any plans to add support for EntraID based auth in the future?

If not, can the exporter use an HTTP client created using the [confighttp](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/confighttp) package instead of a default HTTP client? A lot of other exporters seem to be doing this. This will allow us to create an [auth extension](https://opentelemetry.io/docs/collector/building/authenticator-extension/) with the capabilities of [aad-auth-proxy](https://github.com/Azure/aad-auth-proxy). I think a lot of users would prefer using an extension instead of deploying a whole other tool.

### Additional context

The `confighttp`'s HTTP client can be injected somewhere here perhaps https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/886c4b4b0257aab5c501d1e0f247deb4850ad3af/exporter/azuremonitorexporter/factory.go#L128-L132

**Comment by Ricky-G** [comment]
Hi @arjunmahishi does this solve the issue 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/azuremonitorexporter/AUTHENTICATION.md#aadentra-authentication

**Comment by arjunmahishi** [comment]
> Hi @arjunmahishi does this solve the issue
> 
> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/azuremonitorexporter/AUTHENTICATION.md#aadentra-authentication

No it does not. This is what is currently possible. My post is about asking for a better alternative.
