### ISSUE TITLE
[pkg/stanza] `TimeParser` unmarshaling ignores original configuration

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#32169]
### Component(s)

pkg/stanza

## Description

The `TimeParser` struct seems to ignore the original configuration if the struct was initialized with something other than the default values: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b25b78a1a7b1228414249265c08178ca40ef0cf9/pkg/stanza/operator/helper/time.go#L49-L57

## Steps to Reproduce

This test reproduces it

```go
func TestUnmarshal(t *testing.T) {
	conf := confmap.NewFromStringMap(map[string]any{
		"location": "America/Shiprock",
	})
	tp := TimeParser{
		Layout: "1/2/2006 15:04:05",
	}

	require.NoError(t, tp.Unmarshal(conf))
	assert.Equal(t, "America/Shiprock", tp.Location) // ok
	assert.Equal(t, "strptime", tp.LayoutType)           // ok, although weird
	assert.Equal(t, "1/2/2006 15:04:05", tp.Layout)  // FAIL --> empty
}
```

## Expected Result

All assertions pass

## Actual Result

The last assertion fails

### Collector version

Tested as of b25b78a1a7b1228414249265c08178ca40ef0cf9

### Additional context

I think `NewTimeParser` should be part of the default configuration of time parser instead of this, and we should do the 'set to nil' trick from https://github.com/open-telemetry/opentelemetry-collector/blob/c72092e00151ce8e4cfef32c73b3a80d54076278/receiver/otlpreceiver/config.go#L68-L70 if we want to only set default config if the key exists.

**Comment by mx-psi** [comment]
Found on https://github.com/open-telemetry/opentelemetry-collector/pull/9862#issuecomment-2031893490, cc @atoulme

**Comment by atoulme** [comment]
Agreed that this can be considered a bug.

**Comment by atoulme** [comment]
I believe https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31802 addresses this bug.
