### ISSUE TITLE
ClickHouse Logs table sub-optimal primary key (SeverityNumber vs SeverityText)

### ISSUE THREAD

**Issue by cwegener** [open-telemetry/opentelemetry-collector-contrib#32215]
### Component(s)

exporter/clickhouse

## Description

The `otel_logs` table definition in the ClickHouse exporter uses `SeverityText` as part of the primary key.

And `SeverityNumber` is not even listed at all in the primary key.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/25e300afa69ce35f01e62d376a50f6115c1b6d70/exporter/clickhouseexporter/exporter_logs.go#L158

## Steps to Reproduce

N/A. Primarily raising this as a design issue for now. There might be implications to insert and query performance.

## Expected Result

`SeverityNumber` should be part of the primary key, since it is the field that the source system's severities are mapped to when translating from an external log model into OTEL Logs data model. And `SeverityText` comes from the external log source and is not a representation of severity as it is defined in OTEL's Log data model.

## Actual Result

`SeverityText` is part of the primary key.

### Collector version

v0.97.0

## Environment
OS: "Ubuntu 22.04"

**Comment by SpencerTorres** [comment]
Hey @cwegener,

Thank you for submitting this issue. I am actively reviewing the logs table schema with the ClickHouse core team. I hope to submit a revised table schema soon with optimizations similar to the one you described here. I will forward this to them so we can consider it in the updated schema.

Thanks!

**Comment by hanjm** [comment]
still valid
