### ISSUE TITLE
[receiver/k8scluster] Add more debug logging to the receiver

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#32236]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

Right now, there’s no information about the behavior of the receiver explicitly logged. We didn't see anything additionally logged at the debug level when trying to debug a situation where we didn't know if the cluster receiver would send metadata updates.

### Describe the solution you'd like

Add more debug logs to the k8sclusterreceiver to make sure we can see when it starts to send dimension updates, or when it doesn’t have any to sync, such as no exporter is detected.

**Comment by crobert-1** [comment]
Sounds good to me, and a code owner has responded with approval as well. Removing `needs triage`.

**Comment by TylerHelmuth** [comment]
Good with me

**Comment by atoulme** [comment]
@povilasv our config is a bit complex, here is the helm template for it: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/config/_otel-k8s-cluster-receiver-config.tpl
