### ISSUE TITLE
host.ip adds type configuration options, for example, only collects ip or collects mac

### ISSUE THREAD

**Issue by zhangjiabin1010** [open-telemetry/opentelemetry-collector-contrib#32251]
### Component(s)

processor/resource, processor/resourcedetection

### Is your feature request related to a problem? Please describe.

Currently, host.ip collects many types of data, which cannot be aggregated. Can it be made Attribute configurable, for example, only IP is collected, and only Mac is collected?

### Describe the solution you'd like

host.ip:
  attributes: [ip,mac]
or
host.ip:
  attributes: [ip4,mac,ip6]

### Additional context

Or adjust the default order so that ip4 is ranked first in the list.

**Comment by crobert-1** [comment]
Hello @zhangjiabin1010, can you share an example of current data that you're getting, vs. what you want? I don't currently have a clear understanding of your request here.
