### ISSUE TITLE
[exporter/sumologic] Move metrics from OpenCensus to OTel

### ISSUE THREAD

**Issue by andrzej-stencel** [open-telemetry/opentelemetry-collector-contrib#32261]
### Component(s)

exporter/sumologic

### Is your feature request related to a problem? Please describe.

We are introducing code to generate metrics based on OpenCensus here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31480. We should get rid of this deprecated method of generating metrics in favor of the OTel way. 

### Describe the solution you'd like

The component should be generating metrics with the OTel libraries.

This can be done after the migration of Sumo Logic exporter's code from the [Sumo Logic repository](https://github.com/sumologic/sumologic-otel-collector) to Contrib is completed.

**Comment by crobert-1** [comment]
_Removing `needs triage` based on code owner response._

**Comment by sumo-drosiek** [comment]
Related to: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29867
