### ISSUE TITLE
Support component health setting

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-collector-contrib#32304]
### Component(s)

extension/opamp

### Is your feature request related to a problem? Please describe.

OpAMP [now supports component health](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#componenthealth-message) it would be great if the opamp extension sent this with its messages.

### Describe the solution you'd like

Use component status reporting as described [here](https://github.com/open-telemetry/opentelemetry-collector/blob/de3ef01bff4f1e4db0eee94abce862c66582f208/extension/extension.go#L54-L63)

**Comment by evan-bradley** [comment]
This should be fairly after the health check extension gets this functionality and the lifecycle-specific parts are refactored into a library. This issue will likely be the starting point for that: https://github.com/open-telemetry/opentelemetry-collector/issues/9957

cc @mwear
