### ISSUE TITLE
slurm processor

### ISSUE THREAD

**Issue by luccabb** [open-telemetry/opentelemetry-collector-contrib#32312]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

open telemetry processor that enriches log, metrics, and traces with [slurm](https://github.com/SchedMD/slurm) metadata. Some of the metadata that would be helpful to include: jobid, jobname, nodelist, user

**Comment by JaredTan95** [comment]
> jobid, jobname, nodelist, user

Sorry, I don't know about slurm, but I have a question，Does those metadata injected by [slurm](https://github.com/SchedMD/slurm)？

**Comment by luccabb** [comment]
> Does those metadata injected by [slurm](https://github.com/SchedMD/slurm)?

would need to shell out and query slurm info (assuming the environment has their binaries available, like [sinfo](https://github.com/SchedMD/slurm/tree/master/src/sinfo)).

my understanding is that it's possible to write a processor that shells out grabs some metadata from slurm and enrich metrics, traces, and logs with those metadata.

**Comment by atoulme** [comment]
Could this be part of the resourcedetectionprocessor? Seems like a natural fit for it.
