### ISSUE TITLE
CI failing due to `vmmeter port not found`

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#32324]
### Describe the issue you're reporting

Have seen a few intermittent failures with the following message:

![Screenshot 2024-04-11 at 9 35 21 AM](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/223565/36fcd2fa-8991-4225-b9cf-d6c6f3b7eb20)

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8649717519/job/23716914434?pr=32267

**Comment by crobert-1** [comment]
For some context, the [vmmeter-action](https://github.com/self-actuated/vmmeter-action) was added recently as a part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32135, adding support for ARM-based testing.

**Comment by crobert-1** [comment]
I've filed https://github.com/self-actuated/vmmeter-action/issues/1 as this may be an issue in the GitHub action itself.
