### ISSUE TITLE
make update-otel should update builder configuration

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#32354]
### Describe the issue you're reporting

Currently `make update-otel` (target in the [Makefile](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/247a9f996e09a83cdc25addf70c05e42b8b30186/Makefile#L324)) doesn't update the builder configuration files for [otelcontribcol](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/builder-config.yaml) and [oteltestbedcol](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/oteltestbedcol/builder-config.yaml). It would be great if it did, simplifying the work needed to update the core dependencies.

**Comment by led0nk** [comment]
is this a dupe of #21632 ?
Because it should be resolved by #32038

**Comment by codeboten** [comment]
@led0nk you're right! this is a dupe, closing
