### ISSUE TITLE
[exporter/elasticsearch] Replace go-elasticsearch with go-docappender BulkIndexer to prepare for reliability fixes

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector-contrib#32378]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

This is required by https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32377 to fix https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30792.

go-elasticsearch BulkIndexer does not have the Flush function required by exporterhelper batch sender to guarantee that a bulk index request is sent.

### Describe the solution you'd like

Replace go-elasticsearch with go-docappender for the Flush function

**Comment by crobert-1** [comment]
_Issue was filed by a code owner and another code owner has added a +1, removing `needs triage`._
