### ISSUE TITLE
Missing Permission (DBA_TABLESPACE_USAGE_METRICS ) in README.md of oracledbreceiver

### ISSUE THREAD

**Issue by inola-ww** [open-telemetry/opentelemetry-collector-contrib#32373]
### Component(s)

oracledbreceiver 

## Description

In the Documentation (receiver/oracledbreceiver/README.md), the grant for DBA_TABLESPACE_USAGE_METRICS is missing, but required (see receiver/oracledbreceiver/scraper.go, line 42)

## Steps to Reproduce

Start Scraping oracle metrics

## Expected Result

Tablespace Metrics are scraped.

## Actual Result

collector logs:
`error executing 
select um.TABLESPACE_NAME, um.USED_SPACE, um.TABLESPACE_SIZE, ts.BLOCK_SIZE FROM DBA_TABLESPACE_USAGE_METRICS um INNER JOIN DBA_TABLESPACES ts ON um.TABLESPACE_NAME = ts.TABLESPACE_NAME: ORA-00942: table or view does not exist`

### Collector version

0.98.0

## Environment
OS: Docker Image (otel/opentelemetry-collector-contrib:0.98.0)
DBMS: Oracle (ver. Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production  Version 19.3.0.0.0)

### OpenTelemetry Collector configuration

```yaml
receivers:
  oracledb/mydb:
    endpoint: dbhost:1521
    service: dbservice
```

### Log output

```shell
{"level":"error","ts":1713161036.1126792,"caller":"scraperhelper/scrapercontroller.go:197","msg":"Error scraping metrics","kind":"receiver","name":"oracledb/mydb","data_type":"metrics","error":"error executing \n\t\tselect um.TABLESPACE_NAME, um.USED_SPACE, um.TABLESPACE_SIZE, ts.BLOCK_SIZE\n\t\tFROM DBA_TABLESPACE_USAGE_METRICS um INNER JOIN DBA_TABLESPACES ts\n\t\tON um.TABLESPACE_NAME = ts.TABLESPACE_NAME: ORA-00942: table or view does not exist\n","scraper":"oracledb","stacktrace":"go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\tgo.opentelemetry.io/collector/receiver@v0.98.0/scraperhelper/scrapercontroller.go:197\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\tgo.opentelemetry.io/collector/receiver@v0.98.0/scraperhelper/scrapercontroller.go:173"}
```

**Comment by crobert-1** [comment]
My apologies, this is a result of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32028. I've filed https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32389 to add the necessary documentation. Thanks for filing this issue!
