### ISSUE TITLE
[exporter/elasticsearch] Use batch sender exporter helper for reliability

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector-contrib#32377]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

This is a way to fix the issue reported in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30792.

In case of a collector crash, the events buffered within the bulk indexer in memory will be lost, even with a persistent queue.

### Describe the solution you'd like

Move the buffering from bulk indexer to exporterhelper batch sender introduced in https://github.com/open-telemetry/opentelemetry-collector/issues/8122, such that events are deleted from the queue only when they are flushed by bulk indexer.

### Additional context

I'm already working on a draft and related PRs are on their way.

exporterhelper batch sender https://github.com/open-telemetry/opentelemetry-collector/issues/8122 is WIP and interface may change. Some features (e.g. batching by bytes) may not be available yet.

Blockers
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32378

**Comment by crobert-1** [comment]
This enhancement makes sense to me, and sounds like a good idea. I'll defer to code owners in case there are component-specific thoughts here.

_Removing `needs triage`._

**Comment by ycombinator** [comment]
> This enhancement makes sense to me, and sounds like a good idea. I'll defer to code owners in case there are component-specific thoughts here.

Agreed, +1

**Comment by carsonip** [comment]
Closing as completed via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34238 . Requires opt-in for the new behavior.
