### ISSUE TITLE
[receiver/azureeventhub] Support base64 string body as an alternative to raw bytes

### ISSUE THREAD

**Issue by jsirianni** [open-telemetry/opentelemetry-collector-contrib#32382]
### Component(s)

receiver/azureeventhub

### Is your feature request related to a problem? Please describe.

Currently, the following error is given by the transform processor if you attempt to decode the event hub receiver's raw output:
```
expected string but got []uint8
```

### Describe the solution you'd like

Now that OTTL support decoding base64, it would be nice if the Event Hub receiver supported proper base64 string output. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31730.

A third format, "base64" (or something similar) would allow allow this receiver to be combined with the ottl base64 decode function.

### Describe alternatives you've considered

A format that converts the payload to a human readable string, with the understanding that the resulting object does not conform to semantic conversions. This would need to be a receiver change as well.

### Additional context

The byte output is not useful if you cannot convert it to something readable. The new OTTL base64 functionality looks promising.

**Comment by atoulme** [comment]
This is not specific to the azure event hub receiver: any receiver can set the body to be a byte array and you'll run into this issue. To fix the issue, you need ways to convert byte array bodies to string bodies according to a given string encoding. You can see here the beginning of that conversion story: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#string You might need to evaluate if this fits your needs, but there's no reason for this receiver to have a custom behavior.

**Comment by jsirianni** [comment]
I guess the main issue is that the receiver accepts perfectly valid data but outputs it in such a way that is not human readable. The OTTL string function will not solve this because it returns hexadecimal.

My suggestion for base64 was really so we could couple it with the new ottl decode function to have something usable. My usecase is for logs specifically. Currently, if the data does not fit the "azure" format's model, you cannot use the receiver.
