### ISSUE TITLE
[CI] Checksum mismatch for cadvisor in Install dependencies

### ISSUE THREAD

**Issue by kkujawa-sumo** [open-telemetry/opentelemetry-collector-contrib#32381]
### Describe the issue you're reporting

Install dependencies fails with checksum mismatch for cadvisor, example failure: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8680678623/job/23801791610

```
verifying github.com/google/cadvisor@v0.49.1: checksum mismatch
	downloaded: h1:L9S9Pdb/uu1HA2PGmgBG4q/V3s9Ct3VWsLicarHVvfQ=
	go.sum:     h1:9M++63nWvdq6Oci6wUDuAfQNTZpuz1ZObln0Bhs9xN0=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

It looks like the issue is related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32368, at least I'm able to reproduce this issue setting `GOPROXY` to `https://goproxy.cncf.actuated.dev,direct`

**Comment by atoulme** [comment]
I see https://github.com/google/cadvisor/issues/3508 caused this and created issues with proxies. We can revert cadvisor to 0.49.0 to fix the issue for now, as was done here: https://github.com/flightctl/flightctl/pull/206

**Comment by crobert-1** [comment]
The [bump to `0.49.1` of cadvisor](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31568) wasn't for any noteworthy purpose (no CVE fixes, major functionality introduced), so I have no problem with rolling back.

**Comment by codeboten** [comment]
If this all happened 3 weeks ago.... i guess cache somewhere expired causing the problem only now?
