### ISSUE TITLE
Include service.version in prom to otlp

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-collector-contrib#32398]
### Component(s)

receiver/prometheus

### Is your feature request related to a problem? Please describe.

Right now service.name, service.instance.id, and a few others are converted to OTLP semantic convention. `service.version` is currently not converted.

### Describe the solution you'd like

I think it would be great if the value for service_version were converted with similar logic to allow for compatibility with otel recommendations.

### Describe alternatives you've considered

I've considered using a transform processor, which would make this work, but I don't think it would let me move something from the attribute to the

**Comment by jaronoff97** [comment]
Actually, shouldn't this be set on all my telemetry from [here](https://github.com/open-telemetry/opentelemetry-collector/blob/e8cabb785bb7bffd6c2e49f09563f132719495ea/service/internal/resource/config.go#L38-L43)?

**Comment by dashpole** [comment]
Not sure I understand.  The prometheus receiver converts from Prometheus' `job` and `instance` to `service.name` and `service.instance.id`.  It will take all attributes of the target_info metric, if present, and convert it to other resource attributes.  However, until Prometheus has UTF-8 support, the attributes will have underscores (e.g. service_version).

**Comment by jaronoff97** [comment]
sorry – i mean right now we get in `service_version` as a prometheus label for the collector's own metrics (and other services potentially using the prometheus metrics exporter in the otel SDKs). I'm suggesting that we do a similar conversion for service_version as we currently do for [otel_scope_version](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/97db72a5db6848f98f4d9b07b935a0d303a17050/receiver/prometheusreceiver/internal/transaction.go#L417-L445) so that we can set the resource attribute's `service.version` so that it's propagated. 

You're probably right that until prometheus has that support this may add too much complexity.
