### ISSUE TITLE
[sqlquery]: Command invoked during init statement

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#32420]
### Component(s)

receiver/sqlquery

## Description

On invocation of the binary, the function https://github.com/snowflakedb/gosnowflake/blob/3b14581d78684b783c0b2c86ae5873cf338fdec4/driver.go#L70 is called which can cause lock contention within the kernel if binary is invoked frequently enough. (Ie, via a docker health command.

## Steps to Reproduce
- Have `github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.98.0` installed
- Invoke the binary
- Error message should be reported

```
# Err Message
level=warning msg=\"DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null.\" func=\"gosnowflake.(*defaultLogger).Warn\" file=\"log.go:228\"\nPassed healthcheck\n
```

## Expected Result
Ideally not having this error reported or function invoked.

## Actual Result
High amount of invoked called to dbus

### Collector version

v0.97.0

## Environment
Compiler: v1.21.2 + cgo

**Comment by MovieStoreGuy** [comment]
The ideal situation is that the upstream dep moves their init function to an optional watchdog process that can called manually by the service.

**Comment by crobert-1** [comment]
Thanks for filing @MovieStoreGuy! Looks like this is https://github.com/99designs/keyring/issues/103 and https://github.com/snowflakedb/gosnowflake/issues/773. Unfortunately from those issues it looks like there's nothing that can be done on our side at this time, from what I understand. I'll leave it open though in case others run into this issue and someone has an idea on how to resolve. 👍

**Comment by crobert-1** [comment]
Note that this is not a sqlquery receiver issue, but also impacts the Snowflake receiver, Pulsar receiver, and docsgen and configschema packages as well, if not more.
