### ISSUE TITLE
Report errors to log.Error channel in the spam exporter

### ISSUE THREAD

**Issue by LukaszByczynski** [open-telemetry/opentelemetry-collector-contrib#32429]
### Component(s)

exporter/sapm

### Describe the issue you're reporting

Currently, the spam exporter reports errors only to the debug channel. From an operational perspective, this setting is incorrect because if I want to monitor errors, I have to enable all debug logs, which is not my intention.

For instance, `zipkin` exporter logging errors to the correct log channel: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e4d4bc944e135c05e1a9aed88dacf5474544672d/exporter/zipkinexporter/zipkin.go#L79

**Comment by crobert-1** [comment]
_Code owner approved PR resolving this issue, removing `needs triage`_

**Comment by codeboten** [comment]
Fixed by  #32430
