### ISSUE TITLE
[attributesprocessor] Support a 'keep' action

### ISSUE THREAD

**Issue by tpaschalis** [open-telemetry/opentelemetry-collector-contrib#32435]
### Component(s)

processor/attributes

### Is your feature request related to a problem? Please describe.

If I want to standardize the spans coming from a certain service, I can use the attributes processor and its delete action to drop attributes I'm not interested in.

In a growing/dynamic environment, or when dealing with a new service this requires listing all the exact attribute names to drop, having to update the configuration.

### Describe the solution you'd like

We could introduce a new 'keep' action that drops all attributes that don't match a specific pattern, or a list of patterns. Prometheus relabeling rules use a similar approach.

### Describe alternatives you've considered

It's not immediately clear to me if the delete regex fields supports negation and whether _that_ could be an alternative solution here, might have to check that out.

**Comment by crobert-1** [comment]
Apologies for the delay @tpaschalis, I believe you can use the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) to accomplish this. Using the [`ottlspan` context](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottlspan) you should be able to access the span attributes, and then you can use the [keep_keys](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#keep_keys) function to only keep the attributes you're interested in.

From what I can tell it only accepts a string for direct matching, not regex. If you need regex matching here it may not work at this point, but it may be able to be added in a new function, depending on code owners' feedback.

**Comment by tpaschalis** [comment]
Hey, sorry I totally missed your response there. :( 

I'd be OK with either solution, but IMHO being able to do everything via the attributes processor (which already supports regexes) would be more straightforward instead of doing it in a roundabout way in the transform processor and needing a new feature.

What does everyone else think about this? To start, do y'all think the initial usecase is worth solving?

**Comment by evan-bradley** [comment]
Thanks for catching this one @crobert-1.

@tpaschalis I think the new [`keep_matching_keys`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#keep_matching_keys) function should be able to handle this in a straightforward way. Do you think that would work for your case?

We're working on deprecating the attributes processor in favor of the transform processor, so I would prefer to not add additional functionality to the attributes processor. If the attributes processor has functionality that the transform processor is missing, we should consider that something to address on the transform processor.

**Comment by tpaschalis** [comment]
Yeah, fits the usecase nicely, thanks for the heads-up, didn't know about the addition of `keep_matching_keys`! 🙌 

Closing this issue as completed then
