### ISSUE TITLE
[CI] ARM CNCF workers starvation

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#32447]
### Describe the issue you're reporting

We are now running on ARM CI workers, and our build is taxing the infrastructure.
It looks like we push too many jobs on the infra, and therefore starve other projects from accessing workers.

This issue tracks efforts to reduce our usage of CI resources.

**Comment by atoulme** [comment]
To start with, we will limit the Go version that we run on for CI testing. We will only run on 1.22 for ARM.

**Comment by crobert-1** [comment]
Potentially related: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32445

**Comment by atoulme** [comment]
OK, the fix is in place, I'll circle back once we have more data on how much this helps with pressure.

**Comment by atoulme** [comment]
I think we can close this issue, we have moved the ARM build to a separate workflow and this is no longer seen as an issue. I could not access stats to verify.
