### ISSUE TITLE
[CI] Unit tests are failing due to timeout for setup-go

### ISSUE THREAD

**Issue by kkujawa-sumo** [open-telemetry/opentelemetry-collector-contrib#32445]
### Describe the issue you're reporting

Unit tests are failing due to timeout for setup-go
<img width="575" alt="Screenshot 2024-04-16 at 17 11 34" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/73836361/02171bee-7abd-4e7e-8261-dd16c9c0641d">
For example:
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8707136104/job/23882045056
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8707700094/job/23883544181

**Comment by crobert-1** [comment]
Thanks for filing @kkujawa-sumo! I believe this is a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32330 👍

**Comment by crobert-1** [comment]
More frequencies:

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8668725178/job/23774313271?pr=32200
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8696281407/job/23849232881

**Comment by crobert-1** [comment]
+1 freq for `Post Cache Go` failure, I assume they're the same underlying cause: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8708439881/job/23885966005?pr=32443

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8708439881/job/23885948254?pr=32443

**Comment by crobert-1** [comment]
Potentially alleviated by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32450

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8743009049/job/23992771585?pr=31915
