### ISSUE TITLE
[cmd/opampsupervisor] use nop components during bootstrapping

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#32455]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

The OpAMP Supervisor needs to create a no-op pipeline to start the Collector with just the OpAMP extension during the bootstrapping process. Most existing components are not universally-present or have some issue (e.g. they bind to a port) that makes them non-ideal.

### Describe the solution you'd like

The best components to use here are the [nopexporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/nopexporter) and [noprecevier](https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/nopreceiver), which are lightweight, won't stop the Collector from starting, don't require special configuration, and should not be difficult to include in a distro. Switch the Supervisor's bootstrap config to use these components instead of the current components used in the no-op pipeline.

**Comment by dmolenda-sumo** [comment]
I will be happy to take care of this issue

**Comment by srikanthccv** [comment]
this can be closed now?

**Comment by evan-bradley** [comment]
Good catch, looks like the issue wasn't linked to the PR.
