### ISSUE TITLE
[pkg/ottl] Ability to discard/sample exemplars

### ISSUE THREAD

**Issue by swar8080** [open-telemetry/opentelemetry-collector-contrib#32460]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

Some observability vendors like grafana have a limit on the number of exemplars they keep at a time. For high volume, that means only recent exemplars are available to help with debugging

### Describe the solution you'd like

The ability to conditionally discard exemplars so that more useful exemplars count towards the vendor's limit. For example, only keeping exemplars for error counter increments or other interesting metric data points. Currently `transformprocessor` doesn't support this

A nice to have is the ability to probabilistically discard exemplars with an ottl statement like `set(exemplars, nil) where rand() < 0.1` , which could keep exemplars 10% of the time. A function like `rand()` currently doesn't exist in ottl though

### Describe alternatives you've considered

We plan to use this for span metrics which is either all or nothing for exemplars. I didn't see another component that can conditionally remove them

**Comment by TylerHelmuth** [comment]
We will need to implement examplar context in order to achieve filtering or modifying examplars.

`Rand` would be an easy function we could add separately.

**Comment by swar8080** [comment]
Hey @TylerHelmuth, could a new function like `truncate_array`/`Subarray` to use on the `ExamplarSlice` of the `datapoint` context be an option here? Ex: `truncate_slice(examplars, 0)` or `Subarray(examplars, 0, 0)` to clear the exemplars

**Comment by TylerHelmuth** [comment]
Yes that would work, although might be a bit too specific.  We could add a way to generically interact with slices

**Comment by tdakkota** [comment]
Is there any reason why this issue was closed without resolving? It does seem like none of the ottl functions have been particularly useful in that regard:

- `set` has no effect
- `truncate_all`/`limit` is incompatible with slices  
- `delete_index` only handles `pcommon.Slice`, not `pmetric.ExemplarSlice`
