### ISSUE TITLE
Update module github.com/prometheus/prometheus to v0.51.2 causes CI failures

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#32488]
### Component(s)

receiver/prometheus

### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8724975405/job/23936835634?pr=32418

```
Error: /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusreceiver/metrics_receiver.go:319:22: r.discoveryManager.UnregisterMetrics undefined (type *"github.com/prometheus/prometheus/discovery".Manager has no field or method UnregisterMetrics)
Error: /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusreceiver/metrics_receiver.go:320:19: r.scrapeManager.UnregisterMetrics undefined (type *scrape.Manager has no field or method UnregisterMetrics)
```

**Comment by dashpole** [comment]
We won't be able to use this patch release.  We will have to wait until the next minor release.

**Comment by dashpole** [comment]
It looks like the released fix only applies to the alert manager, which we don't use: https://github.com/prometheus/prometheus/pull/13861

**Comment by codeboten** [comment]
@dashpole should https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32418 be closed then?

**Comment by dashpole** [comment]
Yep, closed

**Comment by codeboten** [comment]
Closing as per the last comment
