### ISSUE TITLE
[exporter/elasticsearch] Add micro/macro benchmarks to reason about improvement PRs

### ISSUE THREAD

**Issue by lahsivjar** [open-telemetry/opentelemetry-collector-contrib#32504]
### Component(s)

exporter/elasticsearch

### Describe the issue you're reporting

Elasticsearch exporter currently doesn't have any benchmarks. There is an uptick in the proposed enhancements and improvements in the exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32377, https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30792, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32359. Many of the improvements in the pipeline introduce major changes to the exporter. As such, it is vital to have a quantifiable way to measure performance and identify any bottlenecks as early as possible.

**Comment by crobert-1** [comment]
Sounds like a good idea to me. Out of ignorance, would this be in the form of tests added to run in CI/CD? How sure are we that the results can be consistent and reproducible? Are there ways to make sure these tests are testing the exporter itself and not an Elasticsearch backend?

If this is being added to GitHub's CI/CD tests, we need to make sure there isn't flakiness introduced. 👍

**Comment by lahsivjar** [comment]
> would this be in the form of tests added to run in CI/CD?

Not quite, my main goal is to have benchmarks to give the developers a way to objectively discuss performance improvements and degradations.

> How sure are we that the results can be consistent and reproducible?

Good question. There are a lot of factors that can introduce inconsistencies in the benchmarks if we were to publish those or run them in CI, however, since the current goal is to have the benchmarks as a development aid we mostly care of diffs between commits.

**Comment by lahsivjar** [comment]
This is still WIP, many benchmarks have been added but we might want to add an e2e macro benchmark too with the recommended collector configuration.

**Comment by carsonip** [comment]
#32632 contains a new macro benchmark. @lahsivjar will it be good enough to close this issue?

**Comment by lahsivjar** [comment]
We don't have an e2e macro benchmark yet (with the required receivers, processors and esexporter) but at this point I am not sure how useful that would be. Closing this and we can revisit the e2e benchmark at a later point if required.
