### ISSUE TITLE
[receiver/windowsperfcounters] Unit tests are not running on CI

### ISSUE THREAD

**Issue by alxbl** [open-telemetry/opentelemetry-collector-contrib#32508]
### Component(s)

receiver/windowsperfcounters

## Description
While attempting to add unit tests for #32384 I realized that the windowsperfcounters were failing. After pinging on Slack, it turns out that the windows test might not be running on CI.

## Steps to Reproduce
cd $src/receivers/windowsperfcountersreceiver
go test

## Expected Result
```
PASS
```

## Actual Result
```
--- FAIL: TestCreateMetricsReceiver (0.00s)
panic: invalid character(s) in type "nop/498597c0-fa00-45b1-84cd-8971618f7d89" [recovered]
        panic: invalid character(s) in type "nop/498597c0-fa00-45b1-84cd-8971618f7d89"

goroutine 23 [running]:
testing.tRunner.func1.2({0x1139ae0, 0xc00021d240})
        C:/Program Files/Go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
        C:/Program Files/Go/src/testing/testing.go:1634 +0x377
panic({0x1139ae0?, 0xc00021d240?})
        C:/Program Files/Go/src/runtime/panic.go:770 +0x132
go.opentelemetry.io/collector/component.MustNewType(...)
        C:/Users/abeaulieu/go/pkg/mod/go.opentelemetry.io/collector/component@v0.98.1-0.20240412014414-62f589864e3d/config.go:156
go.opentelemetry.io/collector/receiver/scraperhelper.NewScraper({0xc00023c2a0?, 0x1236eff?}, 0xc00021d220, {0xc000091d10, 0x2, 0xc00023c1b0?})
        C:/Users/abeaulieu/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.98.1-0.20240412014414-62f589864e3d/scraperhelper/scraper.go:70 +0x114
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver.createMetricsReceiver({0x1163260?, 0x1198020?}, {{{{0x1236eff, 0x3}}, {0xc00023c1b0, 0x24}}, {0xc000224400, {0x134dde0, 0xc00021cd20}, {0x134de08, ...}, ...}, ...}, ...)
        C:/git/opentelemetry-contrib/receiver/windowsperfcountersreceiver/factory_windows.go:27 +0x318
go.opentelemetry.io/collector/receiver.CreateMetricsFunc.CreateMetricsReceiver(...)
        C:/Users/abeaulieu/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.98.1-0.20240412014414-62f589864e3d/receiver.go:134
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver.TestCreateMetricsReceiver(0xc0002111e0)
        C:/git/opentelemetry-contrib/receiver/windowsperfcountersreceiver/factory_windows_test.go:34 +0x343
testing.tRunner(0xc0002111e0, 0x128c180)
        C:/Program Files/Go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
        C:/Program Files/Go/src/testing/testing.go:1742 +0x390
exit status 2
FAIL    github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver  0.104s
```

### Collector version

v0.98.0

## Environment
Windows 11

### OpenTelemetry Collector configuration

```yaml
N/A
```

### Log output

```shell
N/A
```

### Additional context

N/A

**Comment by mx-psi** [comment]
cc @pjanotti as the Windows platform owner

**Comment by mx-psi** [comment]
A sample of last runs from receivers: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8727122415/job/23943929465 and https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8727122415/job/23943929947

I am not able to see any references to windowsperfcounters :thinking:

**Comment by mx-psi** [comment]
For the specific issue mentioned: I believe the error comes from https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/52cc8e84604778e0b32e1d2b2b8b6763fd16a797/receiver/windowsperfcountersreceiver/factory_windows.go#L28

which passes a component Type with a `/` in it, so it's not something specific to OP's environment

**Comment by alxbl** [comment]
As @mx-psi says, I replaced `params.ID.String()` (which is `nop/$uuid` and causes the panic due to `/` and `-` characters) by `metadata.Type.String()` as was done in #31135 for other components and the tests started passing.

**Comment by dashpole** [comment]
@braydonk

**Comment by pjanotti** [comment]
First thing it is not running because the build and test was not updated after groups were further split from the original 2, see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30901/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R29.

Re-enabling those will likely cause a bunch of failures, but, it is the way to go: I will open that PR first and then we fix the failures one by one until we can merge the updated test for Windows.
