### ISSUE TITLE
[exporter/loadbalancing] Add the ability to load balance by Metric stream ID

### ISSUE THREAD

**Issue by RichieSams** [open-telemetry/opentelemetry-collector-contrib#32513]
### Component(s)

exporter/loadbalancing

### Is your feature request related to a problem? Please describe.

The LoadBalancing exporter is a great idea. It currently exposes a number of ways to route metrics coming in:

```
const (
	traceIDRouting routingKey = iota
	svcRouting
	metricNameRouting
	resourceRouting
)
```

However, there are many situation where these routing methods can lead to non-uniform distributions of metrics. For example, if datapoints use lots of labels, or med to high cardinality labels. The finest grain routing we can currently do is metric name routing. But if the majority of the datapoints are all the same metric name, then this doesn't help.

### Describe the solution you'd like

I would like to propose adding a new value to the routing enum: `streamIDRouting`. This would route individual datapoints based on their unique ID. We could use the new `internal/exp/metrics/identity` package: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/exp/metrics/identity/stream.go#L29

I'm willing to be the implementer

**Comment by JaredTan95** [comment]
@RichieSams Hi, Thanks for the proposal. It's yours

**Comment by skandragon** [comment]
I am also needing something similar to this, but likely need to dig a bit deeper and make this per-metric-attribute.

My use case is, I have a custom processor that decorates telemetry with an attribute, placed either on the log, metric, or span.  This key is what I want to partition on, and send to each back-end to be gathered and ultimately written to the same s3 output file.

What is the recommended way to add this, as the PR associated with this change seems to be rejected?  I know the PR is not sufficient as it only looks at resource attributes, and I would need to look deeper, and I assume split deeper as well.

**Comment by jpkrohling** [comment]
I believe @RichieSams will work on this, the PR was closed in favor of breaking it into smaller chunks of work.

**Comment by RichieSams** [comment]
Correct. I already split up the commits, I just got busy at work last week. I'll create new PRs today

**Comment by RichieSams** [comment]
This is the first PR. Just a trivial helper function: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32794

Then there are these 4 commits that will be applied on top. @jpkrohling How do you want me to do them? I can serially make each a PR, get it merged, then go on to the next. Or do you want to combine any?

1. chore: Add str const variables for the routingKeys https://github.com/RichieSams/opentelemetry-collector-contrib/commit/bb473e14a7b430ec14de4887dbe6d518742e86bb
2. [exporter/loadbalacing] Refactor how metrics are split and then re-joined after load-balacing https://github.com/RichieSams/opentelemetry-collector-contrib/commit/89a14afc1ea57961e6edaa6eb311579871a3300b
3. [exporter/loadbalancer] Refactor the metrics export benchmarks https://github.com/RichieSams/opentelemetry-collector-contrib/commit/891bdfad1ecbb32402baed5ad40189dcd58d6048
4. [exporter/loadbalancer] Add a new routing key: streamID https://github.com/RichieSams/opentelemetry-collector-contrib/commit/5314b93fd82cd7c9562cdea4fd142a8a566f9a98

**Comment by RichieSams** [comment]
This issue is still valid. Currently waiting for this PR to be merged, and then I can create the final PR that will close this issue.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33676

**Comment by jpkrohling** [comment]
The dependent PR has been merged!

**Comment by jpkrohling** [comment]
@RichieSams , can this be closed?
