### ISSUE TITLE
Supervisor: exporters.debug.* not valid cfg 

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#32541]
### Component
supervisor

## Description
This property is no supported in collector master, is it? 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/29d1f4fb97d42f5ef09a3132570d64321a9c1449/cmd/opampsupervisor/supervisor/templates/bootstrap.yaml#L7

shall be renamed to “exporters.logging.”

## Steps to Reproduce
Use buggy cfg and start app

### Collector version

0.99/master

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
The [logging exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/loggingexporter) has been deprecated in favor of the [debug exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter). Are you seeing an error when using the debug exporter?

**Comment by tjuchniewicz** [comment]
Yes. We are using collector v0.98.0. In which version it was deprecated?

**Comment by crobert-1** [comment]
Can you share the error you're seeing? The logging exporter [has been deprecated since `v0.86.0`.](https://github.com/open-telemetry/opentelemetry-collector/pull/8378)
