### ISSUE TITLE
splunkhec exporter: Allows users to enable exporter batching via config

### ISSUE THREAD

**Issue by splunkericl** [open-telemetry/opentelemetry-collector-contrib#32545]
### Component(s)

exporter/splunkhec

### Is your feature request related to a problem? Please describe.

With exporter batching introduced in https://github.com/open-telemetry/opentelemetry-collector/pull/9738, users should be able to leverage this for splunk hec exporter so they can enable batching in the exporter side.

### Describe the solution you'd like

Adds exporter batching config in the splunk hec exporter config, if the batching is enabled, add the batching options when creating a new log/metrics instance.

```
type Config struct {
   // ...
   BatcherConfig exporterbatcher.Config    `mapstructure:"batcher"`
}

func createLogsExporter() {
 var options []exporterhelper.Option

  cfg := config.(*Config)
  if cfg.BatcherConfig.Enabled {
      options = append(options, exporterhelper.WithBatcher())
  }
  
  return exporterhelper.NewLogsExporter(..., options...)
}
```

### Describe alternatives you've considered

N/A. Users can utilitize batcher processor but the functionality introduce an async gap in the pipeline. This is what the exporter batching can eliminate.

**Comment by splunkericl** [comment]
Happy to take this change and submit a PR

**Comment by crobert-1** [comment]
Sounds like a good idea to me. _Removing `needs triage`._
