### ISSUE TITLE
[awss3exporter] Use dynamic values ​​such as resource.attributes for file prefix, s3 prefix, etc.

### ISSUE THREAD

**Issue by NobleTuna** [open-telemetry/opentelemetry-collector-contrib#32553]
### Component(s)

awss3exporter

### Is your feature request related to a problem? Please describe.

hello.
When saving a file through AWS S3 exporter, I would like to specify the path as k8s.deployment.name and use k8s.pod.name as the file name to save the log for each pod separately.
I tried various methods, but it was only saved with a static name.

### Describe the solution you'd like

If OTTL variables are supported in **s3_prefix** and **file_prefix** so that files can be classified and saved in the format below, it would be good for use in a k8s environment, etc.

bucket/logs/attributes["k8s.deployment.name"]/year=XXXX/month=XX/day=XX/hour=XX/minute=XX/attributes["k8s.pod.name"]_XXXXX.log

**Comment by crobert-1** [comment]
_Removing `needs triage` based on code owner's response._

**Comment by atoulme** [comment]
I would also recommend you look at the groupbyattrs processor to create successive batches. You can then route batches based on the value of the resource attributes to different awss3exporters.

**Comment by lazyboson** [comment]
@atoulme are we considering this? is there any workaround?

**Comment by atoulme** [comment]
The issue is closed and I offered a workaround above. Please review and offer further development as adequate.

**Comment by lazyboson** [comment]
> The issue is closed and I offered a workaround above. Please review and offer further development as adequate.

do you guys contribution from outside?

**Comment by Hankier** [comment]
> I would also recommend you look at the groupbyattrs processor to create successive batches. You can then route batches based on the value of the resource attributes to different awss3exporters.

Do you have any example for this?
