### ISSUE TITLE
Some data couldn't be associated with k8s metadata when the agent was just started.

### ISSUE THREAD

**Issue by h0cheung** [open-telemetry/opentelemetry-collector-contrib#32556]
### Component(s)

processor/k8sattributes

## Description

When the agent is first started, the k8s metadata has not been fully synchronized by the k8sattributes processor. If any data passes through the component at this point, they will not be associated with metadata.

## Steps to Reproduce

- start a service that continuously sends a large amount of data to the agent.
- (re)start the agent.

## Expected Result

All data should be associated with k8s metadata.

## Actual Result

There may be a little data that hasn't be assosicated.

### Collector version

v0.95.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Additional context

I think it's the best solution to wait for an initial sync when starting k8sattributes processor.

Or we can block data util an initial sync is finished.

**Comment by TylerHelmuth** [comment]
I wonder if we could add something to the processor's start function that waits for the kube client connections to be made.

**Comment by h0cheung** [comment]
> I wonder if we could add something to the processor's start function that waits for the kube client connections to be made.

I think it's not enough to only wait for connections. If the connections are just made but metadata hasn't been synced yet, data won't be associated still. We need to wait for an initial complete sync like the implementation in #32622.

**Comment by orloffv** [comment]
Oh noo
