### ISSUE TITLE
Updating the Mongodb configuration on Readme

### ISSUE THREAD

**Issue by samiura** [open-telemetry/opentelemetry-collector-contrib#32561]
### Describe the issue you're reporting

Without ` transport: tcp` on the mongodb.hosts otelcollector fails to start properly ( Please see the attached screenshots).
![image (1)](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/86324446/ba3445bb-bdaa-48f9-98dc-57548ff1acad)
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/86324446/4cf02a1d-9154-4c6d-9699-d4a719a6e59c)
![image (2)](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/86324446/e22609c4-2eeb-442a-83e2-9e3e7634f9fc)

**Comment by crobert-1** [comment]
Hello @samiura, can you share the configuration of the receiver that you're using?
