### ISSUE TITLE
[exporter/elasticsearch] Make retry statuses configurable and default to 429 only

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector-contrib#32584]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

Elasticsearch exporter retries on 500, 502, 503, 504, 429 by default, on both request level and document level. This is not ideal and may lead to duplicates.

### Describe the solution you'd like

The retriable statuses should be configurable such that users may decide whether they prefer guaranteed delivery or no duplicates. It should default to retrying on 429 only.

### Additional context

Integration tests need to be updated since it is testing with document level 500s now.

**Comment by crobert-1** [comment]
It looks like the current thought, from what I'm gathering in the PR discussion, is that the default will stay the same for now, with warnings that functionality will change in the near future. A code owner was involved in this discussion and has signed off, so I'm removing `needs triage`.

**Comment by carsonip** [comment]
#32585 will add the config option and another PR in the future will change the default.

**Comment by carsonip** [comment]
> @carsonip as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32585 has been merged, can this be closed or is there more to do?

It will be closed via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34684
