### ISSUE TITLE
[k8sattributesprocessor]  The sources.from types add enum metric_attribute

### ISSUE THREAD

**Issue by halleystar** [open-telemetry/opentelemetry-collector-contrib#32596]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

I want to add  pod labels  to some metric。But I can not  finish  this easily。for example  when I get some metric about pod by intermediary system。

### Describe the solution you'd like

we can add sources.from a  enum metric_attribute to match data point's  attribute  and then fetch pod labels。

**Comment by TylerHelmuth** [comment]
@halleystar I think your need would be better served by the transformprocessor, have you looked into that processor yet? It can add resource attributes based on datapoint attributes.

**Comment by TylerHelmuth** [comment]
Or are you saying the pod association would come from a datapoint attribute instead of a resource attribute?

**Comment by TylerHelmuth** [comment]
@halleystar is your goal to do pod association using a datapoint attribute or to add pod labels to only some metrics?

**Comment by halleystar** [comment]
yeah,   do pod  association using a datapoint attribute

**Comment by TylerHelmuth** [comment]
I don't think that would be impossible, but would be very tricky as not all the datapoints in a payload would be guaranteed to have the same value.  How would the association work if there are 2 datapoints that have different attribute values?

In the meantime you can solve your problem using a transformprocessor before the k8sattributesprocessor to set a resource attribute using a datapoint attribute

```
set(resource.attributes["test"], attributes["test"])
```
