### ISSUE TITLE
[extension/opamp]: Allow configuring extra identifying attributes

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#32644]
### Component(s)

extension/opamp

### Is your feature request related to a problem? Please describe.

We have a user that would like to be able to add extra identifying information (a separate unique ID) to OpAMP's agent description message.

Currently, identifying attributes are determined wholly by the extension. However, [the spec](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes) specifies that `any other attributes that are necessary for uniquely identifying the Agent's own telemetry.` may also be specified for identifying attributes. 

I think the user should be able to add extra identifying attributes if they have other information that helps identify the agent.

### Describe the solution you'd like

I'd like a similar solution to #32153 - where extra attributes are merged into the agent description from the config.

```yaml
extension:
  opamp:
    agent_description:
      identifying_attributes:
        custom.attribute: value
        another.custom.attribute: "another value"
``` 

### Describe alternatives you've considered

An alternative is to just add the attribute to non-identifying attributes. This feels semantically wrong, because the attribute is used as an identifier for the agent, but is placed in non-identifying attributes.

**Comment by tigrannajaryan** [comment]
The problem with this is that if you supply extra identifying attributes then you can no longer guarantee that Collector's own telemetry uses these same attributes, which [is a requirement](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes) in OpAMP.

I think it is possible to support this feature in Supervisor, which also controls full Collector config file and can specify additional Resource attributes for Collector's own telemetry, but I don't see how we can make this work without Supervisor, just in the extension.

**Comment by BinaryFissionGames** [comment]
> I think it is possible to support this feature in Supervisor, which also controls full Collector config file and can specify additional Resource attributes for Collector's own telemetry, but I don't see how we can make this work without Supervisor, just in the extension.

This is our end goal, actually. I hadn't thought of it, but it makes sense that the Supervisor could modify the AgentDescription message received from the extension.

Would we be opposed to allowing configuration of the agent description in the supervisor?

```yaml
agent:
  description:
    identifying_attributes:
      some_id: "some-value"
    non_identifying_attributes:
      cloud.provider: "aws"
```

> if you supply extra identifying attributes then you can no longer guarantee that Collector's own telemetry uses these same attributes, which [is a requirement](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes) in OpAMP.

This is tangential and a separate issue, but the implementation of the OpAMP extension already allows for a different instance ID between self-telemetry and the one reported via OpAMP (`service.instance.id` in resource can be configured differently than the extensions `instance_id`). If this is a hard requirement, we should probably look into making that not possible.

**Comment by tigrannajaryan** [comment]
>Would we be opposed to allowing configuration of the agent description in the supervisor?

I think this sounds reasonable.

BTW, there is already a `collector` section in the Supervisor config where these settings can go to.

>This is tangential and a separate issue, but the implementation of the OpAMP extension already allows for a different instance ID between self-telemetry and the one reported via OpAMP (service.instance.id in resource can be configured differently than the extensions instance_id). If this is a hard requirement, we should probably look into making that not possible.

opamp extension uses `service.instance.id` value by default unless explicitly overridden, see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3736ec8f939fd4f4ce6c423850258f82c7474004/extension/opampextension/opamp_agent.go#L155

This is probably good enough since by default it does the right thing.

**Comment by andykellr** [comment]
> BTW, there is already a `collector` section in the Supervisor config where these settings can go to.

It appears that it was renamed to `agent` and that is the proposed location of these settings. I think we should either rename it to `collector` or update the spec to keep it in sync with the implementation.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/opampsupervisor/supervisor/config/config.go

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/opampsupervisor/specification#supervisor-configuration

**Comment by tigrannajaryan** [comment]
> I think we should either rename it to `collector` or update the spec to keep it in sync with the implementation.

I am fine either way, I agree we need to make sure they are in sync.

**Comment by BinaryFissionGames** [comment]
I'm closing this in favor of a new issue #32824 since we want to do this in the supervisor and not the extension.
