### ISSUE TITLE
New component: processor for external/remote processing

### ISSUE THREAD

**Issue by aofodo** [open-telemetry/opentelemetry-collector-contrib#32664]
### The purpose and use-cases of the new component

Sometimes need very flexible telemetry processing capabilities. For example, for greater security, it is necessary to analyze and mask some data from the logs using neural network processing or other various methods that are difficult to account for within standard collector components.

### Example configuration for the component

```yaml
remoteprocessor:
  protocol: http
  url: localhost:6060
  secure: true
  timeout: 10s
```

### Telemetry data types supported

All types of telemetry

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Additional context

Unlike `processor/remotetapprocessor`, for this component, the external application must return the processed telemetry, and then it will then go further along the pipeline

I drew a diagram of an example of interaction to make it easier to understand. 
![remoteproccc](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/165767272/e13be47a-335e-49a4-9faf-f2d24f82e9b8)

**Comment by thiagogcm** [comment]
This would be very helpful.
some prior related discussion: https://github.com/open-telemetry/opentelemetry-collector/issues/7961

I think the offload to an external processor instance could be inspired by the Envoy solution: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto

**Comment by seankhliao** [comment]
Why not just feed it the output of an exporter and have it feed back in a receiver?
