### ISSUE TITLE
[servicegraph/connector]wrong latency for server and client

### ISSUE THREAD

**Issue by zhangtong007** [open-telemetry/opentelemetry-collector-contrib#32689]
### Component(s)

connector/servicegraph

## Description
 reversed the latency settings for the server and client, adjusted accordingly

### Collector version

v0.96

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by mapno** [comment]
It's been fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34562
