### ISSUE TITLE
metricstransformprocessor: for filtering with label use OTLP metric type instead of OpenCensus type

### ISSUE THREAD

**Issue by hossain-rayhan** [open-telemetry/opentelemetry-collector-contrib#3269]
**Description**

This issue is for tracking an upcoming refactoring.

Metrics transform processor using OpenCensus metric type. The community is planning to rewrite the whole plugin to use OTLP metric type instead of OpenCensusu metric type. @hossain-rayhan added a new feature on that processor which enables to filter metrics matching metric name as well as label values. As Rayhan is approaching his deadline, community decided to include this change on top of our existing codebase. Once we plan to rewrite the processor after the deadline, Rayhan will contribute to re-write his code and possibly help with other parts of the metrictransform processor.

Here is the PR link #3201 .

**Comment by hossain-rayhan** [comment]
@alolita can you assign this to me. Thanks.

**Comment by locmai** [comment]
Hi @hossain-rayhan , I noticed that since the metric transform processor using OpenCensus metric type, it will also drop some properties (while doing add_label, update metric ...) of the OTLP metrics on the processing way, since you had taking a look, could we somehow bypass that?

For example, there are some properties like IsMonotonic and AggregationTemporality being drop. This will make the aggregation logic of some exporters turned out wrong (Prometheus Exporter for example)

**Comment by hossain-rayhan** [comment]
Hi @locmai , did you mean bypassing the drop of OTLP properties like IsMonotonic/AggregationTemporality? If so, I don't have an answer for that right now. 

Also, if the whole plugin is rewritten using OTLP metric type, this won't be an issue anymore, right? If you have other concerns, we can also discuss in our weekly SIG meeting.

**Comment by locmai** [comment]
> Also, if the whole plugin is rewritten using OTLP metric type, this won't be an issue anymore, right?

Yes, this is the best I think, is there a near-future plan for that?

**Comment by hossain-rayhan** [comment]
> > Also, if the whole plugin is rewritten using OTLP metric type, this won't be an issue anymore, right?
> 
> Yes, this is the best I think, is there a near-future plan for that?

Upstream is actively working on the plan but I don't have an ETA.

**Comment by locmai** [comment]
Thank you for being so responsive :D looking forward to the change! (going to 👀 on the upstream :D )

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10817
