### ISSUE TITLE
[receiver/azureblob] Support Service Principal authentication for Azure storage

### ISSUE THREAD

**Issue by sebastiean** [open-telemetry/opentelemetry-collector-contrib#32705]
### Component(s)

receiver/azureblob

### Is your feature request related to a problem? Please describe.

Requiring Storage account key does not support the Principal of Least Privilege 

### Describe the solution you'd like

Allow Entra ID authentication using a Service Principal that can be assigned a role with reduced scope

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by mx-psi** [comment]
Fixed by #32706
