### ISSUE TITLE
Unable to ingest logs, traces to Azure monitor (Azure Application Insights, Azure Log Analytics Workspace)

### ISSUE THREAD

**Issue by manashbob** [open-telemetry/opentelemetry-collector-contrib#32708]
### Component(s)

exporter/azuremonitor

## Steps to Reproduce
We deployed Opentelemetry crontrib 0.97.0 both as a deployment and daemonset to Azure Kubernetes Sevice with version 1.27.7, we have done required configuration to ingest logs and traces to Azure application insight.
## Expected Result
Logs and Traces should ingest in Azure Application Insights
## Actual Result
Unable to see any log or traces in Azure Application Insights. 

### Collector version

0.97

### Environment information

Azure Kubernetes Cluster with Kubernetes version 1.27.7

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
  resource:
    attributes:
    - key: example.trace
      value: "via-collector"
      action: insert

exporters:
  logging:
    loglevel: debug
  azuremonitor:
    endpoint: "https://qatarcentral-0.in.applicationinsights.azure.com/"
    instrumentation_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
      namespace: camunda
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [azuremonitor, logging]
      namespace: camunda

logs:
  - name: kubernetes-app-logs
    kubernetes:
      api_server: https://kubernetes.default.svc:443
      insecure: true
      namespace: camunda
      format: json
      ids:
        - container_id
  - name: container-logs
    filelog:
      path: /var/log/containers/*.log
```

### Log output

```shell
2024-04-26T07:47:19.170Z        info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "debug", "resource metrics": 1, "metrics": 18, "data points": 18}
2024-04-26T07:47:19.171Z        info    ResourceMetrics #0
Resource SchemaURL:
Resource attributes:
     -> service.name: Str(otel-collector)
     -> service.instance.id: Str(0.0.0.0:8888)
     -> net.host.port: Str(8888)
     -> http.scheme: Str(http)
     -> service_instance_id: Str(f068caee-be9e-4c65-bf23-84960dd9ff36)
     -> service_name: Str(otelcol-contrib)
     -> service_version: Str(0.97.0)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope otelcol/prometheusreceiver 0.97.0
Metric #0
Descriptor:
     -> Name: otelcol_process_memory_rss
     -> Description: Total physical memory (resident set size)
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> service_instance_id: Str(f068caee-be9e-4c65-bf23-84960dd9ff36)
     -> service_name: Str(otelcol-contrib)
     -> service_version: Str(0.97.0)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2024-04-26 07:47:19.161 +0000 UTC
Value: 161996800.000000
Metric #1
Descriptor:
     -> Name: otelcol_process_uptime
     -> Description: Uptime of the process
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> service_instance_id: Str(f068caee-be9e-4c65-bf23-84960dd9ff36)
     -> service_name: Str(otelcol-contrib)
     -> service_version: Str(0.97.0)
StartTimestamp: 2024-04-25 13:57:39.161 +0000 UTC
Timestamp: 2024-04-26 07:47:19.161 +0000 UTC
Value: 64187.437243
Metric #2
Descriptor:
     -> Name: otelcol_processor_batch_metadata_cardinality
     -> Description: Number of distinct metadata value combinations being processed
     -> Unit:
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> service_instance_id: Str(f068caee-be9e-4c65-bf23-84960dd9ff36)
     -> service_name: Str(otelcol-contrib)
     -> service_version: Str(0.97.0)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2024-04-26 07:47:19.161 +0000 UTC
Value: 1.000000
Metric #3
Descriptor:
     -> Name: otelcol_receiver_accepted_metric_points
     -> Description: Number of metric points successfully pushed into the pipeline.
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> receiver: Str(prometheus)
     -> service_instance_id: Str(f068caee-be9e-4c65-bf23-84960dd9ff36)
     -> service_name: Str(otelcol-contrib)
     -> service_version: Str(0.97.0)
     -> transport: Str(http)
StartTimestamp: 2024-04-25 13:57:49.161 +0000 UTC
Timestamp: 2024-04-26 07:47:19.161 +0000 UTC
Value: 115518.000000
Metric #4
Descriptor:
     -> Name: otelcol_exporter_send_failed_metric_points
     -> Description: Number of metric points in failed attempts to send to destination.
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> exporter: Str(debug)
     -> service_instance_id: Str(f068caee-be9e-4c65-bf23-84960dd9ff36)
     -> service_name: Str(otelcol-contrib)
     -> service_version: Str(0.97.0)
StartTimestamp: 2024-04-25 13:57:49.161 +0000 UTC
Timestamp: 2024-04-26 07:47:19.161 +0000 UTC
Value: 0.000000
Metric #5
Descriptor:
     -> Name: otelcol_process_cpu_seconds
     -> Description: Total CPU user and system time in seconds
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
```

**Comment by frzifus** [comment]
Hi @manashbob,

You configuration looks a bit mixed up. Also if I am seeing it right, your logs show a metric output. But its not part of your configuration.
Can you share the collector logs after startup?

```diff
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
-      namespace: camunda
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [azuremonitor, logging]
-      namespace: camunda
```
Where did you get this from?
```
logs:
  - name: kubernetes-app-logs
    kubernetes:
      api_server: https://kubernetes.default.svc:443
      insecure: true
      namespace: camunda
      format: json
      ids:
        - container_id
  - name: container-logs
    filelog:
      path: /var/log/containers/*.log
```

**Comment by manashbob** [comment]
Hi @frzifus,

I got this configuration from chatgpt as I struggled after following OTEL official document. My requirement is here,

    1. I have Kubernetes cluster in Azure, AWS, GCP, Oracle Cloud. 
    2. I want to collect logs, traces from application containers and metrics for clusters and ingest to Azure Application Insights ( a central place to store). 
    3. Wherever feasible, I used OTEL SDK integrated with application. But for some 3 party applications (e.g. Mulesoft, Camunda) I cannot integrate OTEL SDK, hence I am trying to setup opentelemetry collector in a separate namespace either a daemonset or a deployment. This OTEL Collector should able to collect traces, logs from application container and ingest into Azure Application Insights or Azure Log Analytics Workspace. 

If you think it is feasible, I request you to share a working configuration.

**Comment by frzifus** [comment]
In general I think that is feasible and not an issue with the exporter. (Btw I think chatgpt is one of the worst resources for this topic).
I am closing this issue, but let me point you to the docs you would need to pick up container logs on your cluster.

- Configure the [filelogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/b7d2395d54574a60eb51668ea49d60c7fa430c64/receiver/filelogreceiver)  to collect k8s logs. (Could look similar to [this example](https://github.com/pavolloffay/kubecon-eu-2023-opentelemetry-kubernetes-tutorial/blob/714b3918006c915fb99f3704c78318b0613b3e47/backend/05-collector-daemonset.yaml)).
- Configure the [journaldreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/b7d2395d54574a60eb51668ea49d60c7fa430c64/receiver/journaldreceiver) for system logs.

Both should be deployed as a daemonset and have access to the logs on each node.

---

For reporting your trace data you may want to use another collector rolled as a deployment.

**Comment by manashbob** [comment]
Though I have been directed to OTEL Document, but I still unable to resolve ingestion issue to Azure Log Analytics workspace.

**Comment by manashbob** [comment]
I want a simple configuration which can ingest logs, traces from Kubernetes containers to Azure Log Analytics workspace.
