### ISSUE TITLE
Splunk HEC receiver - pass otel attributes

### ISSUE THREAD

**Issue by brettplarson** [open-telemetry/opentelemetry-collector-contrib#32718]
### Component(s)

receiver/splunkhec

### Describe the issue you're reporting

Hi, I was wondering if it is possible to pass abitrary otel attributes to the splunk hec receiver - it looks like there are only four attributes that are accepted.

* `hec_metadata_to_otel_attrs/source`
* `hec_metadata_to_otel_attrs/sourcetype`
* `hec_metadata_to_otel_attrs/index`
* `hec_metadata_to_otel_attrs/host`

Is there a trick to sending more attrs in the body of a HEC log / metric? We use attrs heavily in our pipeline, but also want to support HEC as a receiver - it may not be native, so we fear that we need to parse the body of the message in order to do this or statically code this into our pipelines.

Thank you in advance!

**Comment by atoulme** [comment]
No, you can pass any resource attribute. We just map specific resource attributes to source/sourcetype/index/host as those are of particular importance to the HEC event.

**Comment by atoulme** [comment]
For reference in the receiver we read all attributes here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/splunkhecreceiver/splunkhec_to_metricdata.go#L28C13-L28C28

Then we stick them for each data point here for example:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/splunkhecreceiver/splunkhec_to_metricdata.go#L109
