### ISSUE TITLE
Support newer Mongodb versions

### ISSUE THREAD

**Issue by samiura** [open-telemetry/opentelemetry-collector-contrib#32716]
### Component(s)

receiver/mongodb

### Describe the issue you're reporting

Currently, Mongodb receivers are supported for 4.0+ - 5.0 per this[ statement.](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mongodbreceiver#prerequisites). Can we support newer version (for e.g. 6.0? As far as we can see the latest version is [7.0](https://www.mongodb.com/docs/manual/release-notes/)

**Comment by djaglowski** [comment]
Yes ideally someone would validate the receiver against newer versions and report if it works as is, or if there are any issues. Are you interested in testing it out for us?

**Comment by crobert-1** [comment]
_Removing `needs triage` as this is a valid request, but with the understanding that the amount of work necessary is still unknown._

**Comment by samiura** [comment]
> Yes ideally someone would validate the receiver against newer versions and report if it works as is, or if there are any issues. Are you interested in testing it out for us?

I will validate and update the integration test for 6.0 and 7.0. Sounds good?
