### ISSUE TITLE
Encoding Extensions not in Contrib Distribution

### ISSUE THREAD

**Issue by blakeromano** [open-telemetry/opentelemetry-collector-contrib#32723]
### Component(s)

extension/encoding, extension/encoding/jsonlogencoding

### Describe the issue you're reporting

When trying to use the encoding extension on contrib distribution I got the error saying this extension was not in the contrib provider using `otel/opentelemetry-collector-contrib:0.99.0` image. 

Encoders are going to be important for having more encoding options for various other components.

**Comment by blakeromano** [comment]
@crobert-1 With the recent release promoting to Alpha does that mean the contrib distribution will now have the encoding extensions or does this require additional work?

**Comment by crobert-1** [comment]
It looks like some encoding extensions are currently included in releases: Jaegar, OTLP, and Zipkin.

[From here.](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/5176736aba29bf6984fb2624c31a209307061dac/distributions/otelcol-contrib/manifest.yaml#L9)

**Comment by blakeromano** [comment]
Correct the JSON log encoding extension is the big one I am looking at. I am happy to PR that repo if that is the best way to go about it.

**Comment by crobert-1** [comment]
@VihasMakwana @atoulme Do you think the JSON log encoding extension is ready to be upgraded to `alpha`? If not, what remaining work is necessary?

**Comment by blakeromano** [comment]
Any updates on this?

**Comment by crobert-1** [comment]
It's been [upgraded to `alpha`](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32697), but hasn't been added to collector releases yet. I've opened https://github.com/open-telemetry/opentelemetry-collector-releases/pull/558 to add.
