### ISSUE TITLE
exporter/clickhouse cannot operate without `create database`, `create table` permissions

### ISSUE THREAD

**Issue by earwin** [open-telemetry/opentelemetry-collector-contrib#32738]
### Component(s)

exporter/clickhouse

## Description
1. exporter/clickhouse unconditionally runs `CREATE DATABASE IF NOT EXISTS`, `CREATE TABLE IF NOT EXISTS` on target DB;
2. In production environment you normally have service users heavily restricted and all required databases and tables pre-created;
3. ClickHouse verifies `CREATE DATABASE` and `CREATE TABLE` permissions before checking for the db/table presence, so exporter/clickhouse fails with "Not enough privileges" even if CREATE would be a noop.

### Collector version

0.99.0

**Comment by mshustov** [comment]
@SpencerTorres should be fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32282?

**Comment by SpencerTorres** [comment]
Yes, absolutely fixed by #32282. We can close this @dmitryax 👍

**Comment by crobert-1** [comment]
Thanks for following up @SpencerTorres, really appreciate it!

Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32282
