### ISSUE TITLE
[exporter/elasticsearch] When using `mapping.mode: ecs`, drop scalar fields in case of object/scalar conflicts

### ISSUE THREAD

**Issue by ycombinator** [open-telemetry/opentelemetry-collector-contrib#32745]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

When `mapping.mode: ecs` is used, certain OTel + SemConv fields are [converted](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31694) to ECS fields to ensure that dashboards and other assets currently using ECS fields continue to work.  Due to this conversion, it's possible to run into object/scalar conflicts in the source field set, for example, `{"foo": 1, "foo.bar": 2}`.

### Describe the solution you'd like

In such cases, we should drop the scalar value. For example, `{"foo": 1, "foo.bar": 2}` should be converted to `{"foo": { "bar": 2}}`.

**Comment by ycombinator** [comment]
cc: @axw

**Comment by crobert-1** [comment]
_This was filed by a code owner, so I'm removing `needs triage`._

**Comment by axw** [comment]
This is still relevant. I _think_ it's only relevant with the config `dedup: false`, but need to confirm that. I'll take a stab at it as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33776

**Comment by axw** [comment]
It's only relevant in the case of `dedup: false`, which I'm removing in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33776. I've added a test case to that PR.

The existing behaviour is that `{"foo": 1, "foo.bar": 2}` will be translated to `{"foo": {"value": 1, "bar": 2}}` with de-dotting. If the input is rather `{"foo": 1, "foo.value": 2}`, then the result will be `{"foo": {"value": 2}}`.

I'm not a fan of this magical ".value" addition, but inclined to leave it alone for now.
