### ISSUE TITLE
multi-target and custom queries

### ISSUE THREAD

**Issue by lucian-vanghele** [open-telemetry/opentelemetry-collector-contrib#32741]
### Component(s)

receiver/oracledb

### Is your feature request related to a problem? Please describe.

I want to be able to use use custom queries against multiple targets. having hardcoded queries is not the best ideas, sometimes there are differences between oracle versions.
I tried to add 2 receivers towards 2 different targets, I only received one set of metrics not even sure for which db.

### Describe the solution you'd like

whatever solves the problem is better than current way.

**Comment by crobert-1** [comment]
Can you give more information on what `custom queries` would look like? Are you wanting to enable/disable different metrics from different targets, or are you wanting to write your own query that would then be used to generate custom metrics?

(Also, if you're interested in getting some help debugging your problem of only receiving one set of metrics, please include your full configuration 👍 )

**Comment by lucian-vanghele** [comment]
@crobert-1 - thanks for replying.

First issue about custom queries: I want to be able to create metrics using my own queries (you know how creative DBAs could be). See for eg https://github.com/iamseth/oracledb_exporter or https://github.com/free/sql_exporter. I see sqlqueryreceiver uses this principle, I will also give it a try but then ... what is the purpose of this oracledb receiver?

Second problem: I was able to fix it by enabling the resource_to_telemetry_conversion on prometheus exporter. I'm only interested now if queries towards these multiple targets are actually performed in paralel.

**Comment by crobert-1** [comment]
Thanks @lucian-vanghele, the sqlquery receiver would definitely be the better fit here for custom queries. I believe you could use it with the Oracle DB receiver to gather all the metrics you're looking for.

There is overlap between the sqlquery receiver and most (if not all) of the other SQL receivers. The benefit of the dedicated receivers is the ability to simply enable/disable metrics, without having to worry about underlying queries. There's more flexibility with the sqlquery receiver, but then it's up to the user to figure out how to query the backend DB properly, what format and naming scheme the metrics should have, etc.

**Comment by lucian-vanghele** [comment]
@crobert-1 - I believe most, if not all, of the Oracle users (administrators actually) would like to have full control on these queries. So, I'm not sure how many will see the benefit you mentioned. 
collection_interval is also a critical aspect which is missing in oracledb receiver.
