### ISSUE TITLE
[exporter/elasticsearch] Create micro-benchmarks for `mapping.mode: ecs` field conversions

### ISSUE THREAD

**Issue by ycombinator** [open-telemetry/opentelemetry-collector-contrib#32746]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

When `mapping.mode: ecs` is used, certain OTel + SemConv fields are [converted](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31694) to ECS fields to ensure that dashboards and other assets currently using ECS fields continue to work.  This conversion, at scale, could prove to be expensive.

### Describe the solution you'd like

It would be good to have micro-benchmarks in place exercising the conversion code to ensure they do not become too expensive at scale.

**Comment by ycombinator** [comment]
cc: @axw

**Comment by crobert-1** [comment]
_This was filed by a code owner, so I'm removing `needs triage`._
