### ISSUE TITLE
[pkg/stanza] tcp and udp input configurable to open both ipv4 and ipv6 ports

### ISSUE THREAD

**Issue by timannguyen** [open-telemetry/opentelemetry-collector-contrib#32775]
### Component(s)

pkg/stanza

### Is your feature request related to a problem? Please describe.

when the dataplane is mainly on ipv4, tcp and udp are using `net.listen("tcp", address)` or `net.listenudp("udp", address)`, respectably. `net.listen`, without explicit tcp4 or udp4, will only open one ipv6 port, then ipv4 port if it cannot open ipv6. Currently, the work-around is to disable ipv6 on the interface. This will force `net.listen` open a ipv4 port or use other tools to relay from ipv6 to ipv4 port.

### Describe the solution you'd like

To allow a configurable option to open only ipv4, ipv6 or both for udp and tcp inputs.

### Describe alternatives you've considered

- socat relays from ipv6 to ipv4
- disabling ipv6 on the interface

**Comment by djaglowski** [comment]
Seems reasonable as a general idea, but will you propose how this should work in configuration?

**Comment by crobert-1** [comment]
_Removing `needs triage` as it's a valid enhancement, with the understanding that implementation/configuration hasn't been agreed upon yet._
