### ISSUE TITLE
Suggestions for Collector name in BuildInfo

### ISSUE THREAD

**Issue by dhruv-vora** [open-telemetry/opentelemetry-collector-contrib#3277]
The `ApplicationStartInfo` (which will be renamed to `BuildInfo`) does not currently contain a field to store the full name of the Collector. I wanted to add this field for using it in the awsprometheusremotewriteexporter and wanted suggestions for the full name to use for the Collector and also for changing the ExeName from `otelcontribcol`.

1 suggestion would be to use the same names as being used in the Collector repo, that is `otelcol` for ExeName and `OpenTelemetry Collector` as the full name. 

If a difference in names is needed between the core collector and the contrib collector, we could use the one of the following in the contrib collector:

- `OpenTelemetry Collector Add-ons` as the full name and `otelcoladdons` as the ExeName
- `OpenTelemetry Collector Extensions` as the full name and `otelcolextensions` as the ExeName

**Comment by dhruv-vora** [comment]
@bogdandrutu @alolita @Aneurysm9

**Comment by Aneurysm9** [comment]
Why would these names need to change?  `otelcontribcol` and `OpenTelemetry Collector Contrib` seem fine and reasonable to me.

**Comment by dhruv-vora** [comment]
The discussion with @alolita was that since people can also contribute to the core OpenTelemetry Collector, adding Contrib to this Collector does not make sense. So that is why I suggested to use the same name as the core Collector, or something different such as Add-ons or Extensions or Plugins.

**Comment by bogdandrutu** [comment]
@alolita please add more details about this, I am not sure I understand from @dhruv-vora comment what is wrong with this.

**Comment by Aneurysm9** [comment]
> @alolita please add more details about this, I am not sure I understand from @dhruv-vora comment what is wrong with this.

I believe this issue can be closed.  There was apparently a question regarding whether the values in the `BuildInfo` initialized by `otelcontribcol` were appropriate, but they seem fine and nobody has made a clear case for changing them.  Feel free to re-open or create a new issue if this needs to be revisited.
