### ISSUE TITLE
Support for 128-bit traces on Datadog receiver

### ISSUE THREAD

**Issue by danielbdias** [open-telemetry/opentelemetry-collector-contrib#32789]
### Component(s)

receiver/datadog

### Describe the issue you're reporting

Hi folks!

During the writing of one article for OTel Blog (https://github.com/open-telemetry/opentelemetry.io/pull/4334) we noticed that `datadog` receiver does not have support for 128-bit trace ids, as described on this CNCF Slack iteration: https://cloud-native.slack.com/archives/C02UN96HZH6/p1714508550552239?thread_ts=1713805772.172779&cid=C02UN96HZH6

Can we add an option on this receiver to give support for 128-bit trace ids?

**Comment by danielbdias** [comment]
Since I am a Go lang dev too, and I have a test bed to validate this scenario [here](https://github.com/kubeshop/tracetest/tree/main/examples/datadog-propagation) I can help and open a PR about this.

**Comment by codeboten** [comment]
Assigned the issue to you @danielbdias

**Comment by danielbdias** [comment]
Giving a heads up on this issue, I was able to fork it and start building this change. I should have a draft PR by tomorrow.
