### ISSUE TITLE
Move to run tests on ARM similarly to Windows

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#32801]
### Describe the issue you're reporting

This issue is the result of the discussion in the SIG meeting on 5/1/2024.

The current way we run ARM runners is too tight and wastes resources.
Instead, given that it is tier 2 support, we should run it just like Windows tests.

* Make it non-blocking
* Run it on main only by default
* Run it with a label "Run on ARM"

**Comment by crobert-1** [comment]
_Removing `needs triage` as this approach was approved of in the sig meeting._
