### ISSUE TITLE
Prometheus receiver uses Deprecated attributes from old semconv version 

### ISSUE THREAD

**Issue by robincw** [open-telemetry/opentelemetry-collector-contrib#32814]
### Component(s)

receiver/prometheus

### Is your feature request related to a problem? Please describe.

The Prometheus receiver [uses semconv/v1.6.1 since 2 years ago](https://github.com/open-telemetry/opentelemetry-collector-contrib/blame/main/receiver/prometheusreceiver/internal/prom_to_otlp.go#L12)
to add resource attributes to convert from the Prometheus to the OpenMetrics convention [when scraping](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/prom_to_otlp.go#L42-L48)
but these are confusing in meaning and deprecated according to [latest documentation](https://github.com/open-telemetry/semantic-conventions/blob/5d7e48746a1f01059b86bc59f62c4daa09f86903/docs/attributes-registry/network.md#deprecated-network-attributes).

In addition, there are many dependencies (alerts, dashboards, recording rules) in the world which depend on the job and instance labels in metrics but the receiver is dropping these without any option to keep them.

### Describe the solution you'd like

The attributes should be updated to match the spec [described here](https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#resource-attributes).

Dropping job and instance attributes in the receiver should be configurable so Prometheus labels can be kept in addition to the semconv labels added. Or this should not be done by receivers at all as it can be done be attribute processor.

### Describe alternatives you've considered

Currently using the attributes processor to re-add the job and instance attributes, and to remove the confusing net.* attributes.

**Comment by robincw** [comment]
Similar issue found for mongodb receiver https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32810

**Comment by dashpole** [comment]
> Dropping job and instance attributes in the receiver should be configurable so Prometheus labels can be kept in addition to the semconv labels added.

Are you referring to job + instance being translated to service.name and service.instance.id?  That is required by the translation specification, as service resource attributes are required to uniquely identify timeseries in OTel.

I've opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32829 to update other attributes used

**Comment by robincw** [comment]
job + instance being translated to service.name and service.instance.id is not a problem, and required by the spec, but dropping them could be a configurable opt-out , I think? This would aid migration of downstream dependencies on the data.
