### ISSUE TITLE
Proposing a new attribute to identity Mongodb endpoint host(s)

### ISSUE THREAD

**Issue by samiura** [open-telemetry/opentelemetry-collector-contrib#32810]
### Component(s)

receiver/mongodb

### Is your feature request related to a problem? Please describe.

Currently, if we have multiple MongoDB server running on different hosts there is no way from collector's point view to count them and show the exact number of them. It can only be done in agent mode where collector is running side by side with a MongoDB server.  Can we have something similar like Prometheus receiver, where it uses net.host.name for this purpose (deprecated as of now). 
However, it’s changed in semconv to server.address and server.port. We can add this to the MongoDB.
https://github.com/open-telemetry/semantic-conventions/blob/651d779183ecc7c2f8cfa90bf94e105f7b9d3f5a/docs/attributes-registry/server.md

### Describe the solution you'd like

Add a new attribute to extract the MongoDB server address and port. Details of the implementation is subject to discussion at this stage.

**Comment by dmitryax** [comment]
Sounds reasonable to me
