### ISSUE TITLE
spanmetrics: Add a default namespace

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#32818]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

`calls` and `duration` are the default metrics output by the `spanmetrics` connector. They are pretty bad default names imo, and converting them into Prometheus yields `calls_total` and `duration_seconds_.*` which are also pretty bad.

It is different in `servicegraph` connector with `traces_service_graph_request_total` . It's just a better metric name.

### Describe the solution you'd like

Make `traces.span.metrics` as the default for namespace , so the metrics end up being `traces_span_metrics_calls_total`.

**Comment by JaredTan95** [comment]
finished by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34485
