### ISSUE TITLE
syslog data being output from device using stream protocol over tcp

### ISSUE THREAD

**Issue by yosiasz** [open-telemetry/opentelemetry-collector-contrib#32822]
### Component(s)

receiver/syslog, receiver/tcplog

### Is your feature request related to a problem? Please describe.

We have proprietary devices that can be configured to dump syslog data (rfc5424) to disk or to use stream protocol over tcp on a certain port. I want to capture this data

### Describe the solution you'd like

ability to point syslogreceiver or tcplogreceiver to be able to capture data being streamed

### Describe alternatives you've considered

some intermediary service between the device and syslog/tcplog receiver

**Comment by djaglowski** [comment]
Both receivers support receiving syslog over tcp. Can you provide any more information about what problem you are experiencing?

**Comment by yosiasz** [comment]
the device software cannot be changed to push data to the collector's port

```
receivers:
  syslog:
    tcp:
      listen_address: "0.0.0.0:54526"
    protocol: rfc5424
exporters:
  debug:
    verbosity: detailed    
service:
  pipelines:
    logs:
        receivers: [syslog]
        exporters: [debug]  
```

**Comment by yosiasz** [comment]
this document might help https://www.ietf.org/archive/id/draft-gerhards-syslog-plain-tcp-07.html

**Comment by djaglowski** [comment]
@yosiasz, I'm sorry this wasn't more helpful but I don't have enough information to identify a problem. Please feel free to reopen if you have any additional info that would indicate that the receiver isn't capable of receiving syslog over tcp.

**Comment by yosiasz** [comment]
not sure what more I can add. I would not have opened this thread if I had not tried.

our device can dump out syslog data to log files or stream it using stream protocol on tcp on port `10004` using python I can read the stream via socket library.

```
s = socket.socket(socket.AF_INET, socker.SOCK_STREAM)
s.connect((HOST, 10004))

while True:
  trace = s.recv(1024_
  parseStream(trace)

def parseStream(trace):
   parse trace using regex etc

```
kind of thing.

So now what I would like is for this otel receivers to be able to do the same as the this sample python code. the device in question is proprietary and cannot be changed to push data to the collector. otel needs to somehow listen on the 10004 port, no idea how to get this data. I am not sure how to do that part on otel side.

**Comment by djaglowski** [comment]
Thanks for the additional detail. If I'm understanding correctly, the device opens the port, and you want the receiver to pull logs from the port. This is as opposed to the current receiver behavior which stands up a server and listens for logs to be pushed to it. Does that sound right?

**Comment by yosiasz** [comment]
exactly!!

**Comment by djaglowski** [comment]
Thanks, I understand what you're asking for now. I've never heard of this approach before, where syslogs are pulled, rather than pushed. As far as I can find in the docs you shared, there is only discussion of a "sender" and "receiver", which is the push model that we support.

**Comment by yosiasz** [comment]
therefore this feature is to implement a pull from otel side, like promtail
does with target ip adress kind of thing

**Comment by djaglowski** [comment]
Ok, got it. I think I'm the absence of a demonstrable or broader need, this is not a feature I'm motivated to spend time implementing or maintaining.

**Comment by yosiasz** [comment]
I will just build one on my own. thanks
