### ISSUE TITLE
Dependencies blocked waiting on v1.22.0+ support

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#32834]
### Describe the issue you're reporting

This issue tracks dependencies that are unable to be upgraded as they've upgraded the minimum go version before we can move ours.

**Comment by codeboten** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32770/files

**Comment by crobert-1** [comment]
More kubernetes packages blocked: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32626

**Comment by mx-psi** [comment]
Also #32888

**Comment by TylerHelmuth** [comment]
Probably related https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33153

**Comment by mx-psi** [comment]
I unpinned this one temporarily to pin #33896. I will revert this change in two weeks if we don't get more comments on that issue.

**Comment by songy23** [comment]
With https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34658 should this be closed now?

**Comment by songy23** [comment]
should be fixed now
