### ISSUE TITLE
[exporter/splunkhec] allow queryString to be set from data

### ISSUE THREAD

**Issue by alexl-splunk** [open-telemetry/opentelemetry-collector-contrib#32846]
### Component(s)

exporter/splunkhec

### Is your feature request related to a problem? Please describe.

When sending events to /events endpoint, we can set metadata (source/sourcetype etc) from data via `hec_metadata_to_otel_attrs` 

However when sending data to /raw endpoint, we can only set it via query string which is not possible at the moment.

Additionally, the top level `source`, `sourcetype` configs do not work once `exportRaw` is set to true.

### Describe the solution you'd like

Add query string to  `hec_metadata_to_otel_attrs` or another config entirely to be processed when exportRaw=true.

**Comment by atoulme** [comment]
Go for it!
