### ISSUE TITLE
[cmd/opampsupervisor]: Add config validation to startup

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#32843]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

Currently, we don't validate the config in any way. It would be good to validate the config in order to pass more useful error messages if the user has misconfigured the supervisor.

### Describe the solution you'd like

I'd like to add validation to the config. With the currently implemented config we could validate:
1. Endpoint is a URL with an `http` or `ws` scheme
2. TLS settings are valid
3. Agent executable exists

We should also harden against misconfiguration in general, as the config stands right now you can get a nil dereference simply by forgetting to fill out the agent section.

**Comment by crobert-1** [comment]
_Removing `needs triage` as a code owner has supported this suggestion, and it makes sense to me._
