### ISSUE TITLE
Map metric type to field of Splunk HEC metric

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#3289]
**Is your feature request related to a problem? Please describe.**
When a metric is converted to Splunk HEC, some metadata information is lost. In particular, the type of metric is not passed on (counter, gauge, histogram, summary).

**Describe the solution you'd like**
Add a `metric_type` field to the Splunk HEC metric event that maps to the type of metric being ingested.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
As comparison, statsd documents metric types with values reflecting the type using a single character (`c`, `g`).
https://github.com/statsd/statsd/blob/master/docs/metric_types.md
The metric type field is mapped to `metric_type`.

**Comment by Saber-W** [comment]
Hi, I want to give this one a try.
cc @alolita
