### ISSUE TITLE
k8sobjectreceiver image pull failed

### ISSUE THREAD

**Issue by gyliu513** [open-telemetry/opentelemetry-collector-contrib#32909]
## Description
k8s object receiver deployment creation failed due to no image.

```
  ----     ------     ----               ----               -------
  Normal   Scheduled  32s                default-scheduler  Successfully assigned default/otelcontribcol-5fff8c474c-b2rnh to otel-control-plane
  Normal   Pulling    18s (x2 over 31s)  kubelet            Pulling image "otelcontribcol:latest"
  Warning  Failed     18s (x2 over 30s)  kubelet            Failed to pull image "otelcontribcol:latest": failed to pull and unpack image "docker.io/library/otelcontribcol:latest": failed to resolve reference "docker.io/library/otelcontribcol:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed     18s (x2 over 30s)  kubelet            Error: ErrImagePull
  Normal   BackOff    4s (x2 over 30s)   kubelet            Back-off pulling image "otelcontribcol:latest"
  Warning  Failed     4s (x2 over 30s)   kubelet            Error: ImagePullBackOff
```
### Collector version

default

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
Hello @gyliu513, I just tested and was able to successfully pull [the image](https://hub.docker.com/r/otel/opentelemetry-collector-contrib).

```
docker pull otel/opentelemetry-collector-contrib
```

Maybe your authentication is incorrect, or you're using the wrong path to pull from?

**Comment by gyliu513** [comment]
Thanks @crobert-1, this is the image `otelcontribcol:latest`, but not `otel/opentelemetry-collector-contrib`.

**Comment by ChrsMark** [comment]
Hey @gyliu513 , I'm not sure if the image `otelcontribcol:latest` is valid. Where is this defined? Could you share how you deploy the Collector (Helm, custom manifest)?

If you are using a custom manifest or chart you would need to replace the image with `otel/opentelemetry-collector-contrib` (or any other valid distro), otherwise if you are using a predefined config or example from the Opentelemetry project most probably that's outdated and needs to be fixed.

**Comment by gyliu513** [comment]
@ChrsMark From here https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sobjectsreceiver#deployment , but I think the document is not right and needs some update, right? Thanks

**Comment by crobert-1** [comment]
> From here https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sobjectsreceiver#deployment , but I think the document is not right and needs some update, right? Thanks

When working locally with the collector, the `otelcontribcol` docker image is generated when you run `make docker-otelcontribcol`. If you're not developing the collector locally, you can use the image we've referenced. 

You're right, the README documentation could probably be updated to make this more clear.
