### ISSUE TITLE
[CI] arm-unittest-matrix runs without timeouts

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#32914]
### Describe the issue you're reporting

The build for ARM should have a timeout of 30 minutes globally.

**Comment by crobert-1** [comment]
Out of ignorance, why would the timeout be 30 minutes for the entire run, instead of a specific step or part of the run?

**Comment by asreehari-splunk** [comment]
I believe it was mostly related to the cost associated with the github action runners. CNCF asked to put a limit on it

**Comment by crobert-1** [comment]
Is this limit the running time of tests, or run count? (Or both?)
