### ISSUE TITLE
I would like to ask if there are any official plans to support the RocketMQ receiver?

### ISSUE THREAD

**Issue by foscvaiijz** [open-telemetry/opentelemetry-collector-contrib#32938]
### Describe the issue you're reporting

I would like to ask if there are any official plans to support the RocketMQ receiver?

**Comment by crobert-1** [comment]
Hello @foscvaiijz, is there an existing receiver for RocketMQ that you're referring to that you want to be added to this repository, or are you requesting a new receiver to be created?

**Comment by foscvaiijz** [comment]
> Hello @foscvaiijz, is there an existing receiver for RocketMQ that you're referring to that you want to be added to this repository, or are you requesting a new receiver to be created?

It is creating a new receiver

**Comment by syron** [comment]
Being aware that I might sound stupid.
Don't know much about the protocols rocketmq supports, but I assume standards like AMQP and/or MQTT. Wouldn't it make sense to have an AMQP / MQTT Exporter instead of a vendor specific one? I assume authentication is also standardized within rocketmq.

**Comment by atoulme** [comment]
@foscvaiijz there are no plans to make a RocketMQ receiver. Please check existing receivers. If you would like to make a proposal for a new component, please create a new issue and provide information on the need and best approach to deliver this new component.
