### ISSUE TITLE
Need extract k8s.pod.ip using k8sattributes processor

### ISSUE THREAD

**Issue by owenchenxy** [open-telemetry/opentelemetry-collector-contrib#32960]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

I need to know the relationship between pod name and it's ip address. But there is no such informations from the otel datum

### Describe the solution you'd like

make k8s.pod.ip as a supported metadata

**Comment by TylerHelmuth** [comment]
We already use the ip for association, allowing it to be an extracted resource feel reasonable
