### ISSUE TITLE
[pkg/ottl] Support for locale

### ISSUE THREAD

**Issue by michalpristas** [open-telemetry/opentelemetry-collector-contrib#32978]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

When timestamp is in non-english language normal golang parsing will fail.

example:
when the tool i'm observing is producing Italian logs in a form of mercoledì set 4 2024 parsing with a layout Monday Jan 2 2006 should yield 4th September 2024 correctly

### Describe the solution you'd like

Depending on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32977 

DoD:
- Add an `ottl.Optional[string]` argument to `Time` converter named `locale`.
- Check locale is valid and we have a mapping for it at startup not in expression function
- Date in non-english locales are parsed correctly
- Support for different formats e.g [stdLongWeekDay](https://github.com/golang/go/blob/master/src/time/format.go#L133), [stdWeekDay](https://github.com/golang/go/blob/master/src/time/format.go#L134)
- Unit tests verifying known locales

**Comment by TylerHelmuth** [comment]
Is this closed by https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32140?
