### ISSUE TITLE
Dimensions on an Edge that is used as a Key in a Metric aggregation must be managed as a separate Config.

### ISSUE THREAD

**Issue by bourbonkk** [open-telemetry/opentelemetry-collector-contrib#32973]
### Component(s)

connector/servicegraph

## Description
When our system collects trace data, it uses AppKeys for categorization. We take advantage of this by adding AppKeys as Dimensions in Config. However, in usertDimensions, we prefix this Dimensions. such as `client_app_key`, `server_app_key`

However, when creating a key to aggregate edge information, we also use the dimensions set in Config in the edge's Dimesions.
Naturally, we can't find it because it's already prefixed.

The config Dimensions are app_key
Edge's dimensions are server_app_key, client_app_key

## Steps to Reproduce
1. config
```yaml
  servicegraph:
    dimensions: [ "app.key" ]
```
2. usertDimensions Method
```go
func (p *serviceGraphConnector) upsertDimensions(kind string, m map[string]string, resourceAttr pcommon.Map, spanAttr pcommon.Map) {
	for _, dim := range p.config.Dimensions {
		if v, ok := findAttributeValue(dim, resourceAttr, spanAttr); ok {
			m[kind+"_"+dim] = v
		}
	}
}
```
3. buildMetricKey Method
```go
func (p *serviceGraphConnector) buildMetricKey(clientName, serverName, connectionType string, edgeDimensions map[string]string) string {
	var metricKey strings.Builder
	metricKey.WriteString(clientName + metricKeySeparator + serverName + metricKeySeparator + connectionType)

	for _, dimName := range p.config.EdgeDimensions {
		dim, ok := edgeDimensions[dimName]
		if !ok {
			continue
		}
		metricKey.WriteString(metricKeySeparator + dim)
	}

	return metricKey.String()
}
```

## Expected Result
Aggregates the metric based on the set Dimensions.

## Actual Result
Contrary to expectations, when creating a MetricKey with Edge, it looks for dimensions that do not contain a prefix.
<img width="992" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/25188468/b5c873e7-628a-425b-979c-38932bc926b9">

You could have a setting with the prefix in the Dimensions setting, but this can be confusing, so,
I think you need a separate EdgeDimensions setting (with the prefix)

### Collector version

0.100.0-dev

## Environment
OS: Sonoma 14.4.1
Compiler(if manually compiled): go 1.22.1

### OpenTelemetry Collector configuration

```yaml
connectors:
  servicegraph:
    dimensions: [ "application.key" ]
```

**Comment by t00mas** [comment]
Just to confirm, you are trying to avoid the prefixing of some labels, right?
I think it's a good feature to have, generically. Leaving some comments on your PR.
