### ISSUE TITLE
[extension/k8sobserver] ingress ressources

### ISSUE THREAD

**Issue by M0NsTeRRR** [open-telemetry/opentelemetry-collector-contrib#32971]
### Component(s)

extension/k8sobserver

### Is your feature request related to a problem? Please describe.

I would like for otel to automatically discover my Ingress resources to enable tools like blackbox exporter to monitor SSL certificate expiration through [receivercreator](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/receivercreator).

### Describe the solution you'd like

Similar to pod and node endpoints, I would like to have an integration to dispatch this endpoint url to different exporters url as parameter.

### Describe alternatives you've considered

Create a static list with a scrape config.

**Comment by M0NsTeRRR** [comment]
Wrong repository x')

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33005

Thanks, @M0NsTeRRR
