### ISSUE TITLE
[pkg/ottl] Adding support for locale into our time parsing library

### ISSUE THREAD

**Issue by michalpristas** [open-telemetry/opentelemetry-collector-contrib#32977]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

This is a followup to #32140

When timestamp is in non-english language normal golang parsing will fail.

example:
when the tool i'm observing is producing Italian logs in a form of `mercoledì set 4 2024` parsing with a layout `Monday Jan 2 2006` should yield `4th September 2024` correctly

### Describe the solution you'd like

Similar support as implemented in https://github.com/ruang-guru/monday for our stanza time library

We could use [CLDR](https://github.com/unicode-org/cldr-json/releases/tag/45.0.0) data and generate mapping using `ca-generic.json` file from specified locale to English.

then use golang standard library to parse translated English date

**Comment by edmocosta** [comment]
Hi there! may I get this issue assigned? I'm working on a lib for doing exactly this and could be submitting a PR soon.

**Comment by edmocosta** [comment]
@michalpristas @TylerHelmuth, I think we should close this issue as it was done by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34353. Thanks!
