### ISSUE TITLE
Otel Processor metric filter is not working as expected

### ISSUE THREAD

**Issue by VJ1313** [open-telemetry/opentelemetry-collector-contrib#32982]
### Describe the issue you're reporting

This is reference to this ticket - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28585

We are using aws managed prometheus. 

Can someone help here? 

I am trying to stop entire bucket but its not working. Basically dont need any data from this bucket - http_server_duration_milliseconds_bucket

receivers:
otlp:
protocols:
grpc: null
http: null
processors:
memory_limiter:
limit_mib: 20
check_interval: 5s
batch: null
filter/uri:
error_mode: ignore
metrics:
metric:
- IsMatch(name, "http_server_requests_.")
datapoint:
- IsMatch(attributes["uri"], "./health.")
- IsMatch(attributes["uri"], "./version.")
- IsMatch(attributes["uri"], ". /actuator.*")
filter/http:
error_mode: ignore
metrics:
- name == "http_server_duration_milliseconds_bucket"
datapoint:
- attributes["net_protocol_name"] == "http"

**Comment by crobert-1** [comment]
The best way to start is to add a [debug exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter) to your pipeline, and see what the metrics look like coming out of the collector. This will help determine if the metric names are matching what the filter processor is expecting.
