### ISSUE TITLE
[splunkhecreceiver] Align acking behavior with that of Splunk Enterprise

### ISSUE THREAD

**Issue by zpzhuSplunk** [open-telemetry/opentelemetry-collector-contrib#32995]
### Component(s)

receiver/splunkhec

### Is your feature request related to a problem? Please describe.

Currently, the channelID used for hec Ack in Splunk Enterprise is not case sensitive, but it is in the hecreceiver.

In addition, Splunk enterprise supports channelId input via the query params, but the hec receiver only supports passing of channelID through the header. 

The hecreceiver's supported features/behaviors should mirror that of Splunk Enterprise more closely. 

### Describe the solution you'd like

- Make the channelID header case-insensitive
- Make hecreceiver endpoints able to extract channelID from query params

**Comment by zpzhuSplunk** [comment]
I have a PR up to address this

**Comment by crobert-1** [comment]
@zpzhuSplunk Can we close this issue, or is there still work to do here?

**Comment by zpzhuSplunk** [comment]
The PR to address this issue is merged. Closing this issue.
