### ISSUE TITLE
Does OpenTelemetry Operator Manage OpenTelemetry Collector-contrib in kUbernetes ? 

### ISSUE THREAD

**Issue by ashishstationcasinos** [open-telemetry/opentelemetry-collector-contrib#32997]
### Is your feature request related to a problem? Please describe.

Does OpenTelemetry Operator Manage OpenTelemetry Collector-contrib in kUbernetes ? 

### Describe the solution you'd like

```
I would like to Deploy OpenTelemetry Collector on Kuberentes with Helm Charts, And Would like to deploy OpenTelemetry collector contirb with helm chart/Manifest  on the same kubernetes cluster, Wants Operator to Manage Collector-contirb
```

**Comment by ChrsMark** [comment]
You can define the Collector image using the [`manager.collectorImage`](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/2f4e7a8f960366b961d621c9bc7c6ae389129af3/charts/opentelemetry-operator/values.yaml#L43) option.

See the installation example at https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator#install-chart.

I guess that issue fits better in the [opentelemetry-helm-charts](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main) repository in case there are more questions that need to be clarified.

/cc @crobert-1

**Comment by frzifus** [comment]
Agree, we should move it. 

But to answer your question around contrib. By today the operator ships the contrib image but it may changes in the future to the k8s distro. There is currently an ongoing discussion.

**Comment by crobert-1** [comment]
I'm going to close as this would be better suited for the helm chart repo referenced above, and has been answered sufficiently. @ashishstationcasinos if you have any more questions about the operator or helm chart, feel free to file issues there!
