### ISSUE TITLE
K8S processer observability unit test fails randomly

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector-contrib#330]
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/1356/workflows/3f27459b-bf16-4352-ae64-4395fcdfde75/jobs/4063

**Comment by tigrannajaryan** [comment]
Failed again https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/1382/workflows/598536d8-8b0d-4b8b-ac74-3caa622d48a4/jobs/4226/steps
