### ISSUE TITLE
Consider adding data transformation information when `debug` level logging is enabled.

### ISSUE THREAD

**Issue by bixu** [open-telemetry/opentelemetry-collector-contrib#33009]
### Component(s)

exporter/prometheusremotewrite

### Is your feature request related to a problem? Please describe.

Metric name suffixes are added automatically by default, but enabling `debug` level logging or the `debug` exporter does not show the final, Prometheus metric name in logs. This makes troubleshooting difficult in environments with very large numbers of metric names. In our case, we were stumped by this for a couple of days.

### Describe the solution you'd like

For `debug` level logging only, it would be helpful to see the Prometheus payload in the log, or at least any data properties that have been mutated but he exporter, similar to how the OTLP `debug` exporter works when `verbosity` is set to `detailed`.

**Comment by crobert-1** [comment]
It may end up being excessive logging, but I guess that's generally acceptable with `debug` logging level. I'll remove `needs triage` for now, but code owners or others may have more thoughts.

**Comment by bixu** [comment]
```It may end up being excessive logging```

I definitely understand the concern here. Since the `debug` Exporter is so verbose, it was surprising that the `prometheusremotewrite` exporter was not. This led to a couple of days of head-scratching in my team, even though we've been running Collectors in production for about 3 years. I'm guessing for newer users this could be even more puzzling.
