### ISSUE TITLE
Preserve processor order in testbed Yaml config creator

### ISSUE THREAD

**Issue by swamisriman** [open-telemetry/opentelemetry-collector-contrib#33003]
### Component(s)

testbed

### Is your feature request related to a problem? Please describe.

In testbed scenarios.go, there is a function createConfigYaml(...) ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/testbed/tests/scenarios.go#L54)) to get yaml config from given parameters.
As it takes the processor argument as a map, the processor order is not maintained.

This way, it's not possible to test scenarios where the processor order is important.

### Describe the solution you'd like

Would be better if the function takes processors argument as an ordered data structure(say list).
or
The function may also take an additional argument with the list of processors (in the required order)

### Describe alternatives you've considered

An alternate solution would be to get the config generated and then update the processors list to the required order

**Comment by crobert-1** [comment]
Good point, it should be ordered 👍  Thanks for calling this out!

**Comment by swamisriman** [comment]
Hi @crobert-1 

Any suggestions on the solution?
I can raise a PR.

**Comment by crobert-1** [comment]
> Hi @crobert-1
> 
> Any suggestions on the solution? I can raise a PR.

Since a map is inherently unordered, I'd start with trying to understand if a map in this case is absolutely required. If not, we should try to move to using an ordered type, like an array. I'm not very familiar with the internal logic of the testbed, so that's as much information as I have at this point.

A PR is welcome!

**Comment by swamisriman** [comment]
Yeah...if we are open to changing the datatype, we can go with a 2D string array.
I don't think this will affect any internal working of the testbed. This is just used to supply the config.
But for those who are already using this function, it will break.
