### ISSUE TITLE
[processor/deltatocumulative]: evicts all streams under heavy load

### ISSUE THREAD

**Issue by sh0rez** [open-telemetry/opentelemetry-collector-contrib#33014]
### Component(s)

processor/deltatocumulative

## Description

When running with a limit that is much lower than the ingested stream rate, the deltatocumulativeprocessor deletes all its streams from tracking.

This is because of its eviction logic, which deletes the oldest stream (whether stale or not) once the stream limit is exceeded.
On a high load this happens all the time, deleting all streams over and over again.

## Expected Result

Only stale streams are deleted. New streams that don't fit are dropped, making the processor operate on the subset it can track within the limit.

## Actual Result

The processor admits evicts live (non-stale) streams, admits a new one which is subsequently evicted as well.

### Collector version

a133a8efefbe34dd45d8d4c8473ebbd75f4bdcc3

**Comment by crobert-1** [comment]
_The proposed solution/expected behavior makes sense to me, and was filed by a code owner. Removing `needs triage`._
