### ISSUE TITLE
Tail Sampling Processor Enhancement for Span-Based Latency Sampling

### ISSUE THREAD

**Issue by EOjeah** [open-telemetry/opentelemetry-collector-contrib#33034]
### Component(s)

processor/tailsampling

### Is your feature request related to a problem? Please describe.

Feature Request: Tail Sampling Processor Enhancement for Span-Based Latency Sampling

The current implementation of the tail sampling processor in the OpenTelemetry Collector Contrib repository allows for sampling decisions based on the latency of an entire trace. This approach, while useful, does not accommodate scenarios where sampling decisions need to be made based on the latency of individual spans within a trace. 

### Describe the solution you'd like

I propose enhancing the tail sampling processor to include a policy that allows for sampling based on the latency of individual spans. This policy should be configurable to target specific spans based on resource attributes, enabling users to focus on spans of particular interest or relevance to performance analysis.

### Describe alternatives you've considered

To address this need, I attempted to configure the tail sampling processor with a combination of `and` sub-policy, incorporating both `latency` and `string_attribute` policies. The goal was to selectively sample traces based on specific span attributes and their latency. However, this approach does not achieve the desired outcome because the `latency` policy applies to the entire trace's latency rather than the latency of individual spans. Consequently, this method fails to capture traces based solely on the performance of specific spans, especially when those spans do not significantly impact the overall trace latency.

**Comment by EOjeah** [comment]
thanks!! @swar8080 
For anyone else looking at this issue 
```yaml
policies: [
  {
    name: test-polciy,
    type: ottl_condition,
    ottl_condition: {
      span: [
        'IsMatch(resource.attributes["service.name"], "service-a") and Seconds(end_time - start_time) > 2',
      ]
    }
  }
]
```

**Comment by jpkrohling** [comment]
Nice, thank you! I'm closing, as there's a valid solution for the original problem.

**Comment by AkshayAwate** [comment]
Even i tried couple of scenarios, while sampling it does not consider floating values. If sampling `Seconds(end_time - start_time) > 2.5` it would consider as `2s`. It does not consider spans, that are in nested traces.
