### ISSUE TITLE
[vcenterreceiver] standalone ESXi not working

### ISSUE THREAD

**Issue by suprnova1** [open-telemetry/opentelemetry-collector-contrib#33073]
### What happened?

As per documentation "This receiver fetches metrics from a vCenter or ESXi host running VMware vSphere APIs."

However, because there is no cluster within standalone ESXi, I receive the following error:

level=error msg="Error scraping metrics" component_path=/ component_id=otelcol.receiver.vcenter.default error="unable to get cluster lists: cluster '*' not found" scraper=vcenter

### Collector version

v0.100.0

**Comment by StefanKurek** [comment]
Taking a look into this now

**Comment by StefanKurek** [comment]
@djaglowski 
So this actually was an issue back in v0.96.0. It was fixed (not sure if intentionally or as a side effect) in v.097.0.

This did made me double check the current state of the client to see if any other client calls could cause failures like this. Most of the client calls have been updated to a new method, which don't automatically return errors on empty results.  

There are still two client calls which intentionally use the older methods and do return these errors at the moment. One for resource pool paths and one for virtual app paths. Resource Pools should always exist (there is something very wrong if they do not), but it's very reasonable that Virtual Apps might not exist in an environment. I have a PR which modifies the Virtual App method to ignore the error if it is a `NotFound` error for the internal client which simply means that it did not find any Virtual Apps. I also added more client unit tests to test for these types of conditions. This PR will be up shortly.

**Comment by StefanKurek** [comment]
@suprnova1 Hello! Are you sure that you're using v0.100.0 of the collector? Looking at the error message you posted, it definitely seems like you're using an older version. If you can verify this, using the newest version of the collector should solve your problem. Let me know. Thanks!
