### ISSUE TITLE
[opampsupervisor] e2e test failing: Permission denied

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#33093]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

CI/CD failure links:
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9114560087/job/25059098980?pr=32177
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9115126246/job/25061035790

Failure output:
```
=== RUN   TestSupervisorAgentDescriptionConfigApplies
    e2e_test.go:143: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/e2e_test.go:143
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/e2e_test.go:469
        	Error:      	Received unexpected error:
        	            	error creating storage dir: mkdir /var/lib/otelcol: permission denied
        	Test:       	TestSupervisorAgentDescriptionConfigApplies
    e2e_test.go:115: Shutting down
```

**Comment by evan-bradley** [comment]
@BinaryFissionGames I think this is related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32618, could you take a look?

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9115269204/job/25061515803?pr=31773

**Comment by BinaryFissionGames** [comment]
Taking a look...

**Comment by BinaryFissionGames** [comment]
It looks like the merge of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32819 and https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32618 resulted in failing tests.

#33095 should fix it.

**Comment by evan-bradley** [comment]
Tests pass now: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9115821831/job/25063271280

Thanks @crobert-1 and @BinaryFissionGames!
