### ISSUE TITLE
Running Docker Image Failed

### ISSUE THREAD

**Issue by ayusheesingh** [open-telemetry/opentelemetry-collector-contrib#331]
**Describe the bug**
After pulling the docker image linked in the README.md of this repo, I am unable to successfully run it.

**Steps to reproduce**
docker pull otel/opentelemetry-collector-contrib
docker run -it otel/opentelemetry-collector-contrib:latest bash

**What did you expect to see?**
Built image.

**What did you see instead?**
{"level":"info","ts":1592333331.6485825,"caller":"service/service.go:418","msg":"Starting OpenTelemetry Contrib Collector...","Version":"latest","GitHash":"9925e07","NumCPU":8}
{"level":"info","ts":1592333331.6486208,"caller":"service/service.go:193","msg":"Setting up own telemetry..."}
{"level":"info","ts":1592333331.6487808,"caller":"service/telemetry.go:147","msg":"Serving Prometheus metrics","port":8888,"legacy_metrics":true,"new_metrics":false,"level":0,"service.instance.id":""}
{"level":"info","ts":1592333331.648805,"caller":"service/service.go:227","msg":"Loading configuration..."}
Error: cannot load configuration: config file not specified
2020/06/16 18:48:51 Application run finished with error: cannot load configuration: config file not specified

**What version did you use?**
Docker version 19.03.11, repo updated from Tue Jun 9 14:03:57 2020

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: "Ubuntu 20.04"

**Additional context**

**Comment by jrcamp** [comment]
You need to provide a config file. See Docker example in the docs: https://opentelemetry.io/docs/collector/about/#docker

**Comment by flands** [comment]
PR to fix https://github.com/open-telemetry/opentelemetry.io/pull/202
