### ISSUE TITLE
[cmd/opampsupervisor] Make persistent state configurable

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#33101]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

The Supervisor's persistent state feature is currently required, we should make it optional; things like the instance ID or prior configuration aren't critical for running the Supervisor.

### Describe the solution you'd like

Add a configuration option to disable persistent state, and if we can't access the persistent state, log an error and disable the persistent state functionality instead of exiting.

cc @BinaryFissionGames

**Comment by BinaryFissionGames** [comment]
Is there a reason why someone would want to disable persistent state? I'm curious if there's particular use-case.

The main thing I can think of is if we need to run somewhere with a read-only file system, but we need somewhere to write the effective config to disk either way. So I figured making it a requirement made sense. But is there some other reason someone would like to disable it?

**Comment by evan-bradley** [comment]
Sorry, I lost track of this.

>The main thing I can think of is if we need to run somewhere with a read-only file system, but we need somewhere to write the effective config to disk either way.

That was my main thought, but you're right; since we can't write config directly to the Collector without a file right now, there's not much to be gained by this. I'm going to close this and we can come back to this one later if there's a need.
