### ISSUE TITLE
Access to journal files running in container on k8s

### ISSUE THREAD

**Issue by omri-cavnue** [open-telemetry/opentelemetry-collector-contrib#33104]
### Component(s)

receiver/journald

## Description
I was able to set up my own custom docker image that has the journalctl binary for arm64. However, I now get the following error: 
```
journalctl command failed (exit status 1): No journal files were opened due to insufficient permissions.
```

I tried running the container as privileged, but the error is still there. What permission is required to read it from a container? I am mounting `/run/log/journal`.

On host I can run journalctl as user without any root auth needed
### Collector version

arm64:latest

## Environment
Jetson Jetpack 35.4.1
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```
journald:
    directory: /run/log/journal
    units:
      - ssh
    priority: info
```

**Comment by sumo-drosiek** [comment]
Could you run `ls -al /run/log/journal` inside the container?

**Comment by omri-cavnue** [comment]
Looks like it's from the base otel [image](https://hub.docker.com/layers/otel/opentelemetry-collector-contrib/latest-arm64/images/sha256-dfb4bdba4049130bb2f8226cc1b45977e2b34eab3ae0858eca95a98215aea5ba?context=explore)

**Comment by omri-cavnue** [comment]
I was finally able to figure out by building a custom image. This doesn't seem very scalable IMO

**Comment by sumo-drosiek** [comment]
@omri-cavnue Did you try to run container with the root user (using `--user` argument)?
