### ISSUE TITLE
exporter/sumologic: reuse Sender instead of creating it every time

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#33105]
### Component(s)

extension/sumologic

### Is your feature request related to a problem? Please describe.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33021#discussion_r1603799203

### Describe the solution you'd like

Initilize sender once and reuse it later

### Additional context

We should check if there is any reason to initilize exporter with every request, but I don't see any at first sight

**Comment by crobert-1** [comment]
_Filed by code owner, removing `needs triage`._
