### ISSUE TITLE
Support export otel data to Google Cloud Storage

### ISSUE THREAD

**Issue by chenlujjj** [open-telemetry/opentelemetry-collector-contrib#33109]
### Is your feature request related to a problem? Please describe.

We need  to export some rarely used logs data to Google Cloud Storage, which is cheaper 

### Describe the solution you'd like

Use GCS exporter to send data

### Describe alternatives you've considered

I find a [odigos/collector/exporters/googlecloudstorageexporter at main · odigos-io/odigos](https://github.com/odigos-io/odigos/tree/main/collector/exporters/googlecloudstorageexporter) which seems like compatible with otel, maybe it can be a good start point

**Comment by crobert-1** [comment]
Out of ignorance, would the [Google Cloud exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudexporter) work for your use case?

**Comment by crobert-1** [comment]
Glad to hear it! I'm going to close for now, but feel free to open another issue if you run into any trouble 👍
