### ISSUE TITLE
[pkg/ottl] Support Minute/Day/Month/Year for time.Time's in OTTL

### ISSUE THREAD

**Issue by sinkingpoint** [open-telemetry/opentelemetry-collector-contrib#33106]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

Under https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29468 we currently support `Hour` as a method to get the Hour from a time.Time , but we don't support any other converters to get the other components of the time. 

Specifically, I want the day/month/year so that I can use the new grouping support in the file exporter to output "$day/$month/$year.log" files

### Describe the solution you'd like

We should fill in the other components, mapping to the `Minute`, `Day`, `Month`, and `Year` methods that go supports on `time.Time`s

**Comment by TylerHelmuth** [comment]
@sinkingpoint do you want to do one more for `Minute`?

**Comment by sinkingpoint** [comment]
Yep! https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33200
