### ISSUE TITLE
[exporter/splunk_hec] Support session cookies

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#33115]
### Component(s)

exporter/splunkhec

### Is your feature request related to a problem? Please describe.

Current implementation of the hec exporter has no load balancing logic related to sticky session cookies.

### Describe the solution you'd like

Support cookies passed down from the server to the exporter. The exporter will reuse cookies for each request after receiving a cookie in response from the server.

**Comment by atoulme** [comment]
Note https://github.com/open-telemetry/opentelemetry-collector/issues/10175 exists for the general use case.

**Comment by crobert-1** [comment]
_Removing `needs triage` as this was filed by code owner and makes sense to me._

**Comment by atoulme** [comment]
This is now implemented since confighttp supports cookies.
