### ISSUE TITLE
[sumologicexporter]: remove deprecated compression_encoding

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#33138]
### Component(s)

exporter/sumologic

### Is your feature request related to a problem? Please describe.

Remove deprecated feature

### Describe the solution you'd like

I would like to deprecate it in few steps:

1. inform users by printing logs about deprecation
2. Remove the configuration option few releases later

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by crobert-1** [comment]
_Filed by code owner, removing `needs triage`._
