### ISSUE TITLE
 batchprocessor/batch_processor.go:209   Sender failed   {"kind": "processor", "name": "batch",

### ISSUE THREAD

**Issue by chengtangzheng2021** [open-telemetry/opentelemetry-collector-contrib#3315]
**Describe the bug**
using otel javaagent send otlp metrics with basic level to otel collector with otlp receiver and newrelic exporter, got this error message:

2021-05-03T19:52:52.923-0400    warn    batchprocessor/batch_processor.go:209   Sender failed   {"kind": "processor", "name": "batch", "error": "[unsupported metric processedSpans (IntSum); unsupported metric runtime.jvm.memory.pool (IntSum); unsupported metric runtime.jvm.memory.area (IntSum); unsupported metric runtime.jvm.gc.count (IntSum); unsupported metric runtime.jvm.gc.time (IntSum)]"}
2

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by a-feld** [comment]
Thanks @bogdandrutu !

Hi @chengtangzheng2021 - we do not support cumulative type metrics in the New Relic exporter. This is detailed [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3091#issue-614477670).

**Comment by bogdandrutu** [comment]
@a-feld I would suggest that for cumulative you better export them as Gauges then at least 🗡️

**Comment by a-feld** [comment]
Ah good idea @bogdandrutu !

**Comment by a-feld** [comment]
@chengtangzheng2021 we're working on #3322 for you!

**Comment by a-feld** [comment]
Hi @chengtangzheng2021 - this fix is merged and the edit has been rolled out to our [OTLP endpoint](https://forms.gle/fa2pWcQxgVQYMggEA). If you're interested in trying out the behavior, feel free to direct your traffic to our OTLP endpoint via an OTLP exporter!
