### ISSUE TITLE
[receiver/receivercreator] Add ability to use endpoint as different config options

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#33187]
### Component(s)

receiver/receivercreator

### Describe the issue you're reporting

The receiver creator uses configured rules to try to match endpoints passed in from observer extensions. If an endpoint's details match a rule, the receiver creator will then create a receiver to target that endpoint.

The receiver creator attempts to create the target receiver with an `endpoint` config attribute. If successful, the `endpoint` is set, otherwise the target receiver's default configuration is used. Relevant logic [here.](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/98b5dcf92c50a3def82d1cd114cb5b1f3f2ba63a/receiver/receivercreator/runner.go#L145)

The enhancement that I'm proposing is to be able to parse a given endpoint in the receiver creator to try to set different configuration options in the target receiver's config. The referenced method above could be modified to try to parse the end point into a `host` and `port`, then try to set different config options in a receiver with those. The SQL Server receiver, for example, uses `server` and `port`, and is the receiver I'm currently working to add this functionality for.

**Comment by samiura** [comment]
👍🏽

**Comment by crobert-1** [comment]
Looks like I was a bit premature with filing an issue here. The receiver creator actually exposes `host` and `port` as env variables, so the target receiver's specified config can simply use these the same way `endpoint` is used for different config options. Closing as there's nothing to do here 🎉
