### ISSUE TITLE
Add the job and instance labels to resource attributes

### ISSUE THREAD

**Issue by chenlujjj** [open-telemetry/opentelemetry-collector-contrib#33212]
### Component(s)

receiver/prometheus

### Is your feature request related to a problem? Please describe.

We are moving from prometheus to otel-collector to collect metrics, but the metrics collected by prometheus receiver don't have `job` and `instance` labels any more, which are default labels for prometheus metrics( see https://prometheus.io/docs/concepts/jobs_instances/) and used by many popular dashboards and alert rules.

### Describe the solution you'd like

Add the job and instance labels to resource attributes.
A few lines of codes in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/prom_to_otlp.go#L35 can solve this.

### Additional context

It can be optional

**Comment by dashpole** [comment]
OpenTelemetry uses `service.instance.id` and `service.name`.  Prometheus exporters rename these to `job` and `instance` per the [specification](https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/).  You can also use the resource processor to rename from `service.instance.id` and `service.name` to `job` and `instance` if you want.

**Comment by chenlujjj** [comment]
@dashpole Thanks for your answer, the resource processor can solve this.
