### ISSUE TITLE
Establish consistency in metric naming for span metrics connector

### ISSUE THREAD

**Issue by vjsamuel** [open-telemetry/opentelemetry-collector-contrib#33227]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

span metrics connector today establishes metric names as `calls_total` and `duration` which lacks proper namespacing

### Describe the solution you'd like

similar to service graph connector if we could do:
`traces_spanmetrics_.*` for the metric names it would ensure consistency across all connectors

### Additional context

This would also help use the grafana service graph view when using the open telemetry collector directly.

**Comment by vjsamuel** [comment]
@jpkrohling

**Comment by Frapschen** [comment]
> similar to service graph connector

Can you give more context about the relate work of graph connector(issue or PR)?

**Comment by vjsamuel** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/servicegraphconnector#metrics

as you can see here, the metrics are neatly namespaced with signal type followed by connector name and finally the actual metric.

**Comment by gouthamve** [comment]
Also see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32818

**Comment by Frapschen** [comment]
I agree that we need to add a component identification to the metrics name.

It's a big breaking change, we need to keep both `traces_span_metrics_calls_total` and `calls_total` for one or two releases and then remove `calls_total` WDYT @dmitryax

**Comment by JaredTan95** [comment]
finished by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34485
