### ISSUE TITLE
filestat - not clear how to add multiple patterns in include 

### ISSUE THREAD

**Issue by lucian-vanghele** [open-telemetry/opentelemetry-collector-contrib#33262]
### Component(s)

receiver/filestats

### Describe the issue you're reporting

I'm looking at how to add different paths in the include config key. From what I see the only option is to create new receiver for each path. Is that correct?

**Comment by lucian-vanghele** [comment]
1. you mean something like /*(etc|var)/*.config ...hmm, might work in some cases
2. I already have it, works for other metrics but not for file.count. And btw, what would be the value of file.count for an input value like the one above? One single value but then what will be the file.path value?

**Comment by lucian-vanghele** [comment]
anyone?

**Comment by atoulme** [comment]
No, globbing means: `/var/log/*.log` https://man7.org/linux/man-pages/man7/glob.7.html
file.count reports the number of files reporting in.

**Comment by atoulme** [comment]
Closing - feel free to reopen or open new issues as needed.
