### ISSUE TITLE
[attributeprocessor] How to create a new span attribute from span's resource attribute

### ISSUE THREAD

**Issue by bendanye** [open-telemetry/opentelemetry-collector-contrib#33279]
### Component(s)

processor/attributes

### Describe the issue you're reporting

Hi there, i have a scenario where i need to create a new span attribute from a span's resource attribute. I understand that the from_attribute is only applicable only on span's attribute, not included span's resource attribute.

How can i create it?

**Comment by crobert-1** [comment]
Hello @bendanye, the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) should work here, using the [span context](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottlspan#span-context).

**Comment by bendanye** [comment]
Hello @crobert-1 sorry i did not specify more details but my current use case is that using [aws otel collector](https://github.com/aws-observability/aws-otel-collector) which does not support transform so i am not able to use transform
