### ISSUE TITLE
[docs]: Is the healthcheckv2 extension actually active, or just baked into the release but not available?

### ISSUE THREAD

**Issue by diranged** [open-telemetry/opentelemetry-collector-contrib#33301]
### Component(s)

extension/healthcheckv2

## Description

The `healthcheckv2` extension doesn't seem active or available in the https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.101.0 or https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.100.0 docker images - even though it was listed as being released in the `New Components` section of the https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.100.0 readme:

<img width="1141" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/768067/feecb4fe-bef0-4a72-94fb-70e14fb12999">

If it's not available yet - can we update the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/healthcheckv2extension/README.md) to indicate that?

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32523

```
error decoding 'extensions': unknown type: "healthcheckv2" for id: "healthcheckv2" (valid values: [asapclient basicauth otlp_encoding http_forwarder k8s_observer file_storage zpages ack ecs_task_observer sigv4auth db_storage awsproxy zipkin_encoding docker_observer ecs_observer opamp pprof jaeger_encoding headers_setter health_check jaegerremotesampling oauth2client host_observer oidc memory_ballast bearertokenauth])
```

### Collector version

0.101.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by mwear** [comment]
@diranged, thanks for your report. Only the skeleton exists at this point. The rest of the extension is written, but it's being reviewed merged in smaller chunks. We can update the readme as you suggest.

**Comment by twistypigeon** [comment]
Agreed README needs an update. I've spent most of today building a custom collector that includes this component but it appears it doesn't actually work or do anything as none of the ports are listening. A note on the README to indicate that it shouldn't be used yet would be very helpful.
Saying that I am looking forward to seeing it complete so that gRPC can be used for health checks as well as the runtime config view HTTP endpoint. Thanks for your work on this.

**Comment by mwear** [comment]
Apologies for the confusion. I sincerely hope we can get the extension in a usable form shortly. In the meantime, the readme has been updated to note that it's not currently ready for use. If you'd like any further changes to the readme, comment and I'll address them.

**Comment by diranged** [comment]
@mwear I noticed that the `healthcheckv2extension` has been in the collector `go.mod` since `v0.100.0`... what is the current status for this thing? Is it ready for use yet?
