### ISSUE TITLE
Filter Processor Not Working as per the Doc/TestData

### ISSUE THREAD

**Issue by meSATYA** [open-telemetry/opentelemetry-collector-contrib#33333]
### Component(s)

processor/filter

### Details

Code owners for this component have explicitly stated they will no longer maintain the code
or have been unresponsive to issues/pull requests.

- [ ] Wait 6 weeks for the code owner to provide feedback, either here or in the linked issue
- [ ] Attempt to recruit new code owners, potentially from the community (cc <code owners>)
- [ ] On <date 6 weeks from now>, 6 weeks from now, the component will be labeled as unmaintained if the original code owner is still unresponsive and no other code owner for the component has been found
- [ ] On <date 6 months from now>, 6 months from now, the component will be removed

https://github.com/open-telemetry/opentelemetry-collector#unmaintained

## Pull requests / Issues

[filter/logs_mix_config](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ed0cf9065022ce01233ee342fe9f385e2f9eabaa/processor/filterprocessor/testdata/config_ottl.yaml#L50)
[filter/metrics_mix_config](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ed0cf9065022ce01233ee342fe9f385e2f9eabaa/processor/filterprocessor/testdata/config_ottl.yaml#L41)
[filter/traces_mix_config](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ed0cf9065022ce01233ee342fe9f385e2f9eabaa/processor/filterprocessor/testdata/config_ottl.yaml#L31)

In the testdata section for filter processor, I found that config_ottl.yaml having such examples which doesn't work with the latest versions of opentelemetry-collector-contrib. For mixed logs, mixed metrics or mixed traces filter configurations, it throws error that "2024/06/03 09:31:55 collector server run finished with error: invalid configuration: processors::filter/logs-preprod-2: cannot use ottl conditions and include/exclude for logs at the same time". 

It is appreciated if the testdata/documentation is updated with properly working filter configurations.

**Comment by TylerHelmuth** [comment]
@meSATYA the linked configuration are for [test cases](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/41486419ef000be542bd1f623a7cd9e29900fff1/processor/filterprocessor/config_test.go#L883-L894) that are expected to fail.
