### ISSUE TITLE
Missing JSON section on Weekly Report will make future execution fail

### ISSUE THREAD

**Issue by LucaLanziani** [open-telemetry/opentelemetry-collector-contrib#33388]
## Description

In order to [fix](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/c7ae39b72de203bbae0cea031728ed630f1dc293) a [previous problem](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8887820197/job/24403690250) with the weekly report a new issue was introduced where by trying to load a non existent JSON section from the previous issue to generate a "diff" the job [will fail](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9359713179) with "Unhandled error: Error: JSON data not found".

## Steps to Reproduce

You can run the job or look a the latest execution.

## Expected Result

Two options:
- if there is no plan to add the JSON section back the code handling it should be removed
- if there is a plan to add it back we could avoid throwing the error and just log that the JSON section is missing waiting for it to be added back.

**Comment by crobert-1** [comment]
I'm fine with simply logging a message for now. The comparison to the previous week is helpful, but it's not worth breaking the weekly report for it at this point, in my opinion. 👍

**Comment by LucaLanziani** [comment]
Closing this and opening a new issue to add back the comparison functionality.
