### ISSUE TITLE
[pkg/ottl] OTTL Sprintf Function 

### ISSUE THREAD

**Issue by sinkingpoint** [open-telemetry/opentelemetry-collector-contrib#33405]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

When using OTTL, it's often useful to be able to construct strings in various ways. We do have a few ways of doing this already (e.g. `Concat`), but nothing as flexible as a generic `Sprintf`. For example, we have no way of padding ints (`%02d` in Sprintf)

### Describe the solution you'd like

I would like to introduce a new OTTL function, `Sprintf` which takes a format string, and an array of fields, and calls `fmt.Sprintf` with those arguments.

This would require introducing a new `Getter` which gets a generic `interface{}`, rather than the existing Getters which return concrete types.

### Describe alternatives you've considered

We can sort of get there with creative uses of `Concat`, but this quickly becomes unruly with complex definitions. e.g. this is one we have:

```
Concat([attributes["appname"], attributes["hostname"], Concat([Year(Now()), Month(Now()), Day(Now())], "-"), Concat(["service-", Hour(Now()), ".log"], "")], "/")
```

Which would look like:

```
Sprintf("%s/%s/%d-%d-%d/service-%d.log", attributes["appname"], attributes["hostname"], Year(Now()), Month(Now()), Day(Now()), Hour(Now()))
```

**Comment by evan-bradley** [comment]
I think this makes sense. It should be fairly easy to implement, we already have a untyped getter (`ottl.Getter`).
