### ISSUE TITLE
No `AggTemp` column in `otel.otel_metrics_histogram` Table

### ISSUE THREAD

**Issue by jwafle** [open-telemetry/opentelemetry-collector-contrib#33424]
### Component(s)

exporter/clickhouse

## Description

The `otel.otel_metrics_histogram` table has no `AggTemp` column, so it is impossible to tell the difference between `Delta` and `Cumulative` metrics stored in this table.

## Expected Result

`AggTemp` in the `otel.otel_metrics_sum` table is stored from the `metric.AggregationTemporality()`. The same should be the case for `otel.otel_metrics_histogram`

## Actual Result

No `AggTemp` column in `otel.otel_metrics_histogram`.

### Collector version

v0.102.0

### Environment information

No environment information necessary. This affects all environments.

### OpenTelemetry Collector configuration

```yaml
Any implementation of the clickhouseexporter would have this bug.
```

### Log output

```shell
N/A
```

### Additional context

Current `otel.otel_metrics_histogram` schema: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/internal/histogram_metrics.go#L21-L60

Current `otel.otel_metrics_sum` schema: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/internal/sum_metrics.go#L21-L57

I am planning on opening a PR to fix this as well.

**Comment by SpencerTorres** [comment]
Appreciate the explanation in this issue, hope to get the PR merged soon. Thanks!

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33425
