### ISSUE TITLE
vcenter.cluster.vm.count reports datacenter VMs as amount for all member clusters 

### ISSUE THREAD

**Issue by nicolai-hornung-bl** [open-telemetry/opentelemetry-collector-contrib#33445]
### Component(s)

receiver/vcenter

## Description
The vcenter.cluster.vm.count that should provide the number of virtual machines in a cluster only works correctly if the managing vCenter only has a single cluster. If there are multiple clusters registered the metric will be the same for all member clusters and reports the total number of VMs in the datacenter for each of them.

## Steps to Reproduce
- Have a vCenter with two or more clusters, each with VMs

## Expected Result
- Each cluster should be reported with it's own number of VMs
## Actual Result
- All clusters have the amount VMs in the Datacenter

### Collector version

v0.87.0

## Environment
Running the embedded receiver in Grafana Alloy however as the rest of the data seems to be formatted correctly I suspect this is an issue in the upstream component.

**Comment by StefanKurek** [comment]
@djaglowski 

@nicolai-hornung-bl Are you able to try a newer version of the collector? This should have been fixed starting at version 0.97.0. Thanks!

**Comment by nicolai-hornung-bl** [comment]
Hi @StefanKurek in that case I will ask whether [grafana/alloy ](https://github.com/grafana/alloy) can update their dependency. I couldn't find exactly what version they were pulling anyway but their docs linked to the 0.87.0 version so I took this. I will come back to you once I have more info.

**Comment by StefanKurek** [comment]
@nicolai-hornung-bl Do you know exactly what version of Alloy you were using? I think at one point they were using an older version of the collector but the newest version should not have this issue.

**Comment by nicolai-hornung-bl** [comment]
Hi Stefan, currently I'm running Alloy version 1.0.0 as 1.1 is bugged.

**Comment by StefanKurek** [comment]
@nicolai-hornung-bl ah. Well whenever you are able to switch to a newer version of Alloy, that should take care of it. Starting with version v1.1.0 of Alloy, this issue should no longer be there.

**Comment by nicolai-hornung-bl** [comment]
Hi @StefanKurek I upgraded to v1.2.0 and can confirm it's fixed. Sorry for the confusion and thanks for checking!
