### ISSUE TITLE
Migrate from opencensus library: receiver/solacereceiver

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#33468]

**Comment by djaglowski** [comment]
@mcardy, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30736/files is a good example of the migration.

**Comment by codeboten** [comment]
An updated example that uses mdatagen: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33426
