### ISSUE TITLE
Unnecessary call to config.Validate during component's initialization

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-collector-contrib#33498]
### Component(s)

exporter/dataset, exporter/elasticsearch, exporter/opensearch, receiver/dockerstats, receiver/podman

### Describe the issue you're reporting

All collector's components must implement the `component.ValidateConfig` [interface](https://github.com/open-telemetry/opentelemetry-collector/blob/main/component/config.go#L28). During collector's startup, it goes through all components and [calls](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.101.0/otelcol/config.go#L45) the `Validate` method. Its execution is finished if any component returns an error. Nonetheless, some components call the Validate method during its initialization, which is redundant taking into account the collector life cycle. (e.g. [Podman receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/podmanreceiver/receiver.go#L69))

I think that the `Validate` interface should be called by the configuration validator consumer (e.g. collector) instead of the configuration producers (components).

Context for Podman's receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32981/files#r1621849257

I linked to this issue the components that seems to be internally calling the configuration `Validate` method. I would not say calling `Validate` is forbidden, just that might be redundant during collector's execution. However, feel free to unlink your component from this issue if the Validate method call is necessary for your specific use case or if it performs additional checks that are not covered during the startup validation phase.

**Comment by mx-psi** [comment]
@rogercoll Do you know what components from your original list still do the unnecessary call?

**Comment by rogercoll** [comment]
I think all but [podman receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33555). I will try to work on the docker one asap.

**Comment by rogercoll** [comment]
exporter/dataset does not call Validate :heavy_check_mark:
