### ISSUE TITLE
Metrics for StatefulSet deployments cannot easily be aggregated together

### ISSUE THREAD

**Issue by jbeemster** [open-telemetry/opentelemetry-collector-contrib#33507]
### Component(s)

receiver/awscontainerinsight

### Is your feature request related to a problem? Please describe.

Currently all deployment types _but_ StatefulSet expose the `PodName` as the name of the deployment itself (see: https://github.com/open-telemetry/opentelemetry-collector-contrib/blame/main/receiver/awscontainerinsightreceiver/internal/stores/podstore.go#L590-L597).

We have started exploring using StatefulSet's and this difference means we cannot easily set alarms or dashboards against the aggregate metric view as each `PodName` value is unique rather than consistent across the pool of pods being used.  For example being able to set a general alarm against the CPU utilization of the entire pool of auto-scaling pods in use.

### Describe the solution you'd like

Ideally I would like to expose a parameter that allows this behavior to be changed so that we can set the `PodName` value to be consistent with other deployment types.

Something like:

```
prefer_controller_name_for_statefulset: true|false
```

With the default maintaining the current behavior.

### Describe alternatives you've considered

We are exploring deploying each application into an isolated namespace to be able to get that aggregate alarm capability back.

**Comment by gthomson31** [comment]
This is still an issue - awaiting [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34901) Review
