### ISSUE TITLE
ottlfunc regex doesn't support double quotes

### ISSUE THREAD

**Issue by Marty1703** [open-telemetry/opentelemetry-collector-contrib#33534]
### Component(s)

pkg/ottl

### Describe the issue you're reporting

Using the replace_pattern ottl func, I am nog able to use a double quote within the regex param. Which i require to transform within my JSON body

I would like to use something like this:
`- replace_pattern(attributes["Body"], (?U)name\":\"(.*)\", name\":\"**********\",)`

But it gives me the error:
`Error: invalid configuration: processors::transform/avg: unable to parse OTTL statement "replace_pattern(attributes[\"Body\"], (?U)name\\\":\\\"(.*)\\\", name\\\":\\\"**********\\\",)": statement has invalid syntax: 1:38: invalid input text "?U)name\\\":\\\"(.*)..."
2024/06/13 05:45:43 collector server run finished with error: invalid configuration: processors::transform/avg: unable to parse OTTL statement "replace_pattern(attributes[\"Body\"], (?U)name\\\":\\\"(.*)\\\", name\\\":\\\"**********\\\",)": statement has invalid syntax: 1:38: invalid input text "?U)name\\\":\\\"(.*)..."`

**Comment by TylerHelmuth** [comment]
`(?U)name\":\"(.*)\", name\":\"**********\",` should become `"(?U)name\":\"(.*)\", name\":\"**********\","`

**Comment by Marty1703** [comment]
Doing so, the Collector fails with error:

`2024-06-17T08:02:14.204Z warn expandconverter@v0.101.0/expand.go:73 Variable substitution using $VAR will be deprecated in favor of ${VAR} and ${env:VAR}, please update $$ {"variable": "$"}`
`Error: invalid configuration: processors::transform/avg: unable to parse OTTL statement "replace_pattern(attributes[\"Body\"], \"(?U)name\\\":\\\"(.*)\\\", \"name\\\":\\\"**********\\\")": statement has invalid syntax: 1:64: invalid input text "\\\":\\\"**********\\..."`
`2024/06/17 08:02:14 collector server run finished with error: invalid configuration: processors::transform/avg: unable to parse OTTL statement "replace_pattern(attributes[\"Body\"], \"(?U)name\\\":\\\"(.*)\\\", \"name\\\":\\\"**********\\\")": statement has invalid syntax: 1:64: invalid input text "\\\":\\\"**********\\..."`

**Comment by TylerHelmuth** [comment]
You'll need to escape `*` as well: `replace_pattern(attributes["Body"], "(?U)name\":\"(.*)\", name\":\"\*\*\*\*\*\*\*\*\*\*\",")`.

I suggest testing that your regex is well formatted and then adding it to your config.

**Comment by Marty1703** [comment]
Hi @TylerHelmuth ,

This one is correct, so it has nothing to do with the `*` thats has to be escaped
`          - replace_pattern(attributes["Body"], "(?U)name(...)(.*),{1}", "name$$1**********\",")`
 
We are using this image and it does the parsing, as far as i can see: **otel/opentelemetry-collector-contrib:0.101.0**

**Comment by TylerHelmuth** [comment]
I got mixed up on the number of parameters. The second parameter is a regex string.  The third parameter is the replacement string, not regex, so you're right that nothing needs escaping.

OTTL requires string literals to be in double quoates (`""`).  This statement compiles: `replace_pattern(attributes["Body"], "(?U)name\":\"(.*)\"", "name\":\"**********\",")`

**Comment by aa-shalin** [comment]
Came across a weird case where i had to replace `\` with `\\` and the code ended up looking like this 
```
- 'replace_pattern(attributes["labels"]["test"], "\\\\", "\\\\")'
```
Reading it makes no sense.
