### ISSUE TITLE
[receiver/gitprovider] checks CI/CD action failing due to token limit

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#33551]
### Component(s)

receiver/gitprovider

### Describe the issue you're reporting

[Failing CI/CD action link](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9501426674/job/26186986302?pr=33549)

Failure output:
```
running go generate ./... in ./receiver/gitproviderreceiver
invalid schema: exceeded token limit of 15000
internal/scraper/githubscraper/github_scraper.go:4: running "../../../../../.tools/genqlient": exit status 1
make[1]: *** [Makefile:158: for-all] Error 1
make[1]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
```

**Comment by adrielp** [comment]
Taking a look.

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9500399386/job/26188486002?pr=33044

Looks like this has been failing every time for the last 7 hours or so on main and PRs.
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/workflows/build-and-test.yml?query=branch%3Amain

**Comment by adrielp** [comment]
yup, it was from this dependency update @crobert-1  https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9496272176

**Comment by crobert-1** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33552
