### ISSUE TITLE
Create internal/arrow package for common code used in otelarrowexporter, otelarrowreceiver

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector-contrib#33567]
### The purpose and use-cases of the new component

There is some shared code that lives in the otel-arrow repository that depends on unstable collector APIs. It will be a headache to continue maintaining these shared libraries because of it, and it would help to create internal/arrow for all the common code used in these two components.

### Example configuration for the component

No config, just an internal group of packages. These include:
- netstats: counting network bytes compressed and uncompressed (generally useful)
- admission: limiting receiver in-flight data size (generally useful)
- compression: improved Zstd configuration support (generally useful)
- testdata, testutil: common test helpers (arrow-specific)

### Telemetry data types supported

All

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

jmacd, moh-osman3

**Comment by crobert-1** [comment]
Sounds good!

_Removing `needs triage` as it makes sense to me and was filed by a code owner._

**Comment by odubajDT** [comment]
Hi, I would like to work on this cc @evan-bradley

**Comment by odubajDT** [comment]
Just for clarification, do I understand correctly that the dependencies on `github.com/open-telemetry/otel-arrow/pkg` and `github.com/open-telemetry/otel-arrow/api` will stay also after moving the business logic from other packages from `otel-arrow` repository to `internal/arrow`?

Thank you
