### ISSUE TITLE
[testbed/mockdatasenders/mockdatadogagentexporter] Broken load test

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#33577]
### Component(s)

testbed, testbed/mockdatasenders/mockdatadogagentexporter

### Describe the issue you're reporting

The `load tests` GitHub action is currently broken with the following error from [this line](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8522b4ee0d2d9db917f0bcd68a84e339c9c53125/.github/workflows/load-tests.yml#L64):
```
Error when evaluating 'strategy' for job 'loadtest'. .github/workflows/load-tests.yml (Line: 64, Col: 15): Unexpected value ''
```
Upon further investigation, the failing variable expansion is a result of the `.github/workflows/scripts/setup_e2e_tests.sh` failing the [`splitloadtests` step](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8522b4ee0d2d9db917f0bcd68a84e339c9c53125/.github/workflows/load-tests.yml#L57) of the dependent action:
```
Run ./.github/workflows/scripts/setup_e2e_tests.sh
main module (github.com/open-telemetry/opentelemetry-collector-contrib/testbed) does not contain package github.com/open-telemetry/opentelemetry-collector-contrib/testbed/mockdatasenders/mockdatadogagentexporter
/bin/bash: line 1: -v: command not found
make: *** [Makefile:5: list-tests] Error 1
```

**Comment by codeboten** [comment]
This has been broken at least since February :(

**Comment by mowies** [comment]
@codeboten if that's fine with you, I'd like to look into this :)
maybe you could re-run one of the latest load test run from main branch for me with debug logging enabled? then i could investigate the job matrix that's not liked by github actions

**Comment by mowies** [comment]
I filed a fix PR for this @codeboten @crobert-1 :)

**Comment by mowies** [comment]
Now, that the load tests are running again, it seems that they have some other issues as well. Pipeline runs are still red...

Taking this run for example: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9769350633

The load tests are successfully executed but something is still broken with the result upload.

**Comment by mowies** [comment]
@codeboten @crobert-1 I filed a follow-up PR that fixes the rest of the load test pipeline. Although I noticed that some tests are broken..
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33885
