### ISSUE TITLE
make update-otel shouldn't update the toolchain

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#33600]
### Describe the issue you're reporting

This is a problem that blocks releases every time:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33593/files#diff-a130a63473f70bd378b211cd809cb20b6629b62ae603fd1b280445412a2dfa95R7

**Comment by codeboten** [comment]
A workaround is to run the command w/ the same go version as what's in the repo

**Comment by mowies** [comment]
I may have found a way to somewhat fix this issue. You can run `go get toolchain@none` and that will remove the toolchain directive from a go.mod file. I'll set up a PR with some new make targets for this, but maybe that also needs to be changed in the multimod tool, not sure yet. I'll dig a bit more tomorrow.

**Comment by mowies** [comment]
@codeboten PR is open: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35490
