### ISSUE TITLE
`go generate` fails with `mdatagen` error

### ISSUE THREAD

**Issue by jlg-io** [open-telemetry/opentelemetry-collector-contrib#33603]
### Component(s)

receiver/vcenter

## Description

Trying to add a new metric for an existing receiver (`vcenterreceiver`) following [CONTRIBUTING.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-metrics-to-existing-receivers) and got the following error :

```
doc.go:4: running "mdatagen": exec: "mdatagen": executable file not found in $PATH
```

## Steps to Reproduce

- Run `cd receiver/redisreceiver`
- Run `go generate ./...`

## Expected Result

It should update documentation and the `generated_*` files

## Actual Result

```
doc.go:4: running "mdatagen": exec: "mdatagen": executable file not found in $PATH
```

## Additional tests

I also tried to run `make generate` from the root directory, it fails with a similar error:

```
running go generate ./... in ./cmd/telemetrygen
config.go:5: running "mdatagen": exec: "mdatagen": executable file not found in $PATH
make[1]: *** [Makefile:158: for-all] Error 1
make[1]: Leaving directory '/<MY_DEV_DIR>/opentelemetry-collector-contrib'
make: *** [Makefile:287: generate] Error 2
``` 

### Collector version

v0.102-2.0

## Environment
OS: Ubuntu 20.04 in WSL2 (Windows 11)

### Additional context

This open issue may be related: https://github.com/open-telemetry/opentelemetry-collector/issues/9281

**Comment by crobert-1** [comment]
Hello @jlg-io, it looks like you need to add `GOBIN` to your shell's PATH. `mdatagen` is installed to your GOBIN directory when you run `make generate`.

[GOBIN documentation](https://pkg.go.dev/cmd/go#hdr-Environment_variables)

**Comment by jlg-io** [comment]
Thanks @crobert-1, my GOBIN env was empty... Here what I've added to $HOME/.zshrc (I use zsh, would be different if you bash), in case it can help someone else:

```
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH
export PATH=$PATH:$GOBIN
```
