### ISSUE TITLE
[kafkareceiver] add support for otlp_json which accepts json formated for Otel Collector kafka receiver

### ISSUE THREAD

**Issue by govardhanda-Kore** [open-telemetry/opentelemetry-collector-contrib#33627]
### Component(s)

receiver/kafka

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

add support for otlp_json which accepts json formatted oltp data same as http/json in otel collector (Receiver)

const otelresourcespans = {
    "resourceSpans": [
        {
            "resource": {
                "attributes": [
                    {
                        key: 'service.name',
                        value: { stringValue: 'serviceName' }
                    }
                ]
            },
            "scopeSpans": [
                {
                    "scope": {
                        "name": "my.library",
                        "version": "1.0.0",
                        "attributes": [
                            {
                                "key": "my.scope.attribute",
                                "value": {
                                    "stringValue": "some scope attribute"
                                }
                            }
                        ]
                    },
                    "spans": []
                }
            ]
        }
    ]
};

**Comment by frzifus** [comment]
Is this about the `receiver/kafka` in the collector or in some sdk?

**Comment by govardhanda-Kore** [comment]
hey, thanks your response, yes it's about the receiver/kafka in the collector

**Comment by atoulme** [comment]
Implemented with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34840 closing
