### ISSUE TITLE
Require Grafana Dashboard for Azure Monitor

### ISSUE THREAD

**Issue by harishkumarrajasekaran** [open-telemetry/opentelemetry-collector-contrib#33649]
### Is your feature request related to a problem? Please describe.

I need a Grafana dashboard for "Azure Monitor" as receiver and collector, using the OpenTelemetry collector.

### Describe the solution you'd like

Azure Monitor (Storage Accounts,CosmosDB) Grafana Dashboards built based on receiver and collector, using the OpenTelemetry collector.

**Comment by codeboten** [comment]
@harishkumarrajasekaran we don't usually have grafana dashboards in this repository for any of the components, maybe @jpkrohling knows of a different repo where that's stored?

**Comment by jpkrohling** [comment]
I asked internally, but I would ask on the Grafana Community slack as well.

**Comment by atoulme** [comment]
This request is out of scope for the contrib repository. Please ask the Grafana community.
