### ISSUE TITLE
[receiver/hostmetrics] replace unmaintained library `github.com/leoluk/perflib_exporter`

### ISSUE THREAD

**Issue by andrzej-stencel** [open-telemetry/opentelemetry-collector-contrib#33652]
### Component(s)

receiver/hostmetrics

### Describe the issue you're reporting

The repository https://github.com/leoluk/perflib_exporter has been archived since July 2023 and has a note that the `perflib` package is now maintained under https://github.com/prometheus-community/windows_exporter.

> The perflib library has been [integrated](https://github.com/prometheus-community/windows_exporter/issues/1240) into [windows_exporter](https://github.com/prometheus-community/windows_exporter) and development continues there. Both library users of perflib as well as perflib_exporter users should migrate to windows_exporter, which is actively maintained and has well-defined metrics.

Let's switch from https://pkg.go.dev/github.com/leoluk/perflib_exporter/perflib to https://pkg.go.dev/github.com/prometheus-community/windows_exporter/pkg/perflib.

**Comment by andrzej-stencel** [comment]
Should be resolved by:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33653

**Comment by crobert-1** [comment]
Closing as resolved by #33653, thanks @andrzej-stencel!
