### ISSUE TITLE
Don't execute  otel collector if  configuration  is "noop" 

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#33680]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

Reduce overhead of overall runtime footprint  in large fleets with a default of "wait and listen for commands" but being not operational sending telemetry, do not execute the collector

### Describe the solution you'd like

Imagine a scenario  where the supervisor is installed  as basic part of a host (container or device) broadcasting DNS and searching for an OPAMP Backend until connected.
There no local "non default" config  for the collector  setup, just the default  "Noop" cfg which would not send any telemetry but health of the collector.

The supervisor is just waiting to get connected to opamap Backend and afterwards waiting for a configuration update from remote for the collector.

To reduce overhead until collect receives a "job" the supervisor shall no execute  the collector  at all. As soon as an config is sent which overwrites noop default, only then execution (deamon) shall be started

**Comment by BinaryFissionGames** [comment]
This would be nice improvement in more resource restricted environments.

I also think, beyond this being an initial state, it would be nice if the opamp supervisor could also send an empty config (e.g. an empty configmap) to stop running the collector until it gets another config.

**Comment by cforce** [comment]
Currently, bootstrapping operates as described below (excerpt from the documentation):

### Bootstrapping
To obtain the remote configuration from the OpAMP Backend, the Supervisor must send an AgentDescription to the Backend. Initially, the Supervisor doesn't have this information because the AgentDescription becomes available only after the Collector process is started and the AgentDescription is sent from the opamp extension to the Supervisor. However, it's impossible to start the Collector without a configuration.

To address this issue, the Supervisor starts the Collector with a "noop" configuration that doesn't collect any data but allows the opamp extension to start. The "noop" configuration consists of a single pipeline with an OTLP receiver listening on a random port, a debug exporter, and the opamp extension. The purpose of this "noop" configuration is to ensure that the Collector starts and the opamp extension communicates with the Supervisor.

Once the initial Collector launch is successful and the Supervisor receives the remote configuration, the Supervisor restarts the Collector with the new configuration. The new configuration is also cached by the Supervisor in a local file. This caching means subsequent restarts no longer need to use the "noop" configuration. It also allows the Supervisor to start the Collector without waiting for the OpAMP Backend to provide the remote configuration, mitigating any OpAMP Backend unavailability.

---

I don't understand why the AgentDescription needs to be managed specifically by the Collector, requiring the Collectors to start in order to connect the Supervisor to an OpAMP Backend. This dependency seems to have only disadvantages, especially if the Supervisor needs to manage multiple Collectors. This will be a particular limitation if the Supervisor has to manage many Collectors simultaneously (see issue #33682).

Why is the Collector considered the agent in a setup where the Supervisor is used? It would make more sense for the Supervisor to be the agent of OpAMP, with any connected Collector being transparent to the OpAMP Backend. Collectors should represent "any" host system as part of a subsystem registered via the Supervisor. In IoT systems, the Supervisor would act as an Hub, which serves as a gateway for all connected Collectors to connect to an OpAMP Backend that they cannot connect to directly for various reasons.

**Comment by tigrannajaryan** [comment]
> Why is the Collector considered the agent in a setup where the Supervisor is used? It would make more sense for the Supervisor to be the agent of OpAMP, with any connected Collector being transparent to the OpAMP Backend. Collectors should represent "any" host system as part of a subsystem registered via the Supervisor. In IoT systems, the Supervisor would act as an Hub, which serves as a gateway for all connected Collectors to connect to an OpAMP Backend that they cannot connect to directly for various reasons.

The assumption is that users want to manage their Collector not their Supervisor. Supervisor is just the means to do it. OpAMP server needs to know what Collector it is managing so that it supplies the right configuration for example. And knowing what Collector it is requires receiving an AgentDescription that correctly describes the Collector (e.g. Collector's version number). The Supervisor does not have this knowledge and uses the bootstraping process to get that information from the Collector.

**Comment by cforce** [comment]
The supervisor must always be aware of the presence of a collector. However, certain registration details, initially set and persistently maintained like the agent ID, should not change, as the supervisor manages the collector.

Bootstrapping can be done without any prerequisites besides the supervisor. This means the collector is downloaded and installed the first time, and the supervisor has information about its capabilities (processors, extensions, receivers, exporters, etc.) through descriptive metadata (e.g., ocb build.yaml). Thus, the supervisor doesn't need to execute the collector to understand its characteristics.

Alternatively, if the collector is already installed (managed by a third-party update) and the "opamp update feature" is off, descriptive metadata—available without execution but requiring maintenance or a persisted state file—is used. This metadata is established after the initial setup, similar to the agent ID.

The supervisor should cache this metadata for each agent. Permanent execution of collectors is not mandatory; instead, the supervisor initializes essential groundwork and can start the collector when necessary, optionally based on configuration changes (e.g., when cfg!=noop).

This approach also supports future scenarios where one supervisor may manage multiple collectors.

**Comment by tigrannajaryan** [comment]
The implementation of the Supervisor currently follows [this design](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/opampsupervisor/specification).

What you are describing appears to be a different design. If you would like to propose an alternate design please post a complete design document so that it can be considered by Supervisor maintainers. (Please note: I do not know if the alternate design will be considered and whether it will be accepted, it may be worth attending a Collector SIG to gauge the interest first).

**Comment by cforce** [comment]
According to @evan-bradley 
"The Supervisor will only restart the Collector when it receives new configuration from the OpAMP server; changes to files on disk will not restart the Collector."
"https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32959#issuecomment-2103249472"

If we follow this logic there are some inherited use cases, aren't there?
* The Supervisor will start the Collector when it receives a !=nop configuration 
* The Supervisor will stop the Collector when it receives a nop configuration

**Comment by BinaryFissionGames** [comment]
Bootstrapping does not require any connection to an outside OpAMP server. It connects to an OpAMP server that is internal to the supervisor, the communication during bootstrapping is only between the collector and the supervisor. 

Bootstrapping also is not to generate an agent ID (the supervisor actually generates the UUID), but rather the AgentDescription message, which contains metadata about the agent (e.g. the "name" of the agent, the version of the agent) that the supervisor doesn't necessarily know without somehow executing the collector.

Bootstrapping is only concerned with getting this AgentDescription message, so once the message is received, the supervisor can (and currently does) stop the collector.

**Comment by cforce** [comment]
Tx for clarification

**Comment by cforce** [comment]
Is there already a decision on what criterai it is decided if the collector kept running or terminated until another cfg is sent with is !=noop or not empty

Alternative A:
"empty configmap" is sent (default startup state as well )

Alternative B:

condition of  below rules  is true
```
receivers:
  nop:
```

AND

```
exporters:
  nop:  
```

AND

extension: []

--
* I am nor sure if it makes sense at all to run a collector with only extensions
* I am not sure if processors without receiver (AND even exporter) makes sense

**Comment by BinaryFissionGames** [comment]
I personally like the empty config map solution. To me it seems natural to expect that having no config to run implies not running anything.

**Comment by cforce** [comment]
I tested collector and supervisor with version 0.117.0.
When started supervisor for first time, collector was not started ( as expected )
Next, I sent nop config .


```
receivers:
  nop:
exporters:
  nop:

service:
  pipelines:
    traces:
      receivers: [nop]
      exporters: [nop]

```
 However, Collector process started with nop config
