### ISSUE TITLE
[receiver] vcenter - Multiple datacenters causes failures to collect Resource Pools, vApps, & VMs

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#33734]
### Component(s)

receiver/vcenter

## Description
Currently when collecting against an environment which contains multiple Datacenters, there is an issue with two of the client calls (`ResourcePoolInventoryListObjects` and `VAppInventoryListObjects`). The underlying `govmomi` client can only handle a default datacenter for these calls, and therefore only resources for 1 datacenter are being returned. This has a side effect of VMs not being created for the non returned objects as well.

## Steps to Reproduce
Collect against an environment with multiple datacenters.

## Expected Result
Collect metrics for resources under each datacenter.

## Actual Result
Many metrics are failed to be created with errors in the logs.

### Collector version

v0.102.0

**Comment by crobert-1** [comment]
@StefanKurek It looks like the PR for this issue has been merged. Is there anything left to do here, or can we close this issue?

**Comment by StefanKurek** [comment]
Should be good to close!
