### ISSUE TITLE
move deltatocumulativeprocessor to the contrib distribution

### ISSUE THREAD

**Issue by lukasmrtvy** [open-telemetry/opentelemetry-collector-contrib#33764]
### Describe the issue you're reporting

This is already included in the latest version of Grafana Alloy ( https://grafana.com/blog/2024/06/18/translate-datadog-metrics-into-otlp-with-the-opentelemetry-collector-and-grafana-alloy/ ) 

Thanks

**Comment by crobert-1** [comment]
This effort is already underway as a part of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30479. Once this component is deemed to be [`Alpha` stability](https://github.com/open-telemetry/opentelemetry-collector?tab=readme-ov-file#alpha) it will be available in future releases of the contrib distribution of the Collector.

Please let me know if there's anything else here that would be helpful 👍
