### ISSUE TITLE
[prometheus] Unable to run prometheus receiver in namespaced mode

### ISSUE THREAD

**Issue by alita1991** [open-telemetry/opentelemetry-collector-contrib#33810]
### Component(s)

receiver/prometheus

### What happened?

I aim to install an opentelemetry-collector with prometheus receiver in a K8S environment, where I only have access to a specific namespace. The first step was to create a role and attach it to the service account of the collector. The problem is that the prometheus receiver is still looking for cluster-wide resources and I wasn't able to find an option to configure the receiver to only monitor namespace resources.

### Collector version

0.102.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by dashpole** [comment]
See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config.  Specifically, you should be able to set:

```yaml
namespaces:
    own_namespace: true
```
or
```yaml
namespaces:
    names:
    - mynamespace
 ```

I'm going to opportunistically close this, as a solution exists.  Feel free to reopen if it doesn't work for you.
