### ISSUE TITLE
Remove Loki exporter due to incompatible license changes (Apache 2 -> AGPLv3)

### ISSUE THREAD

**Issue by gramidt** [open-telemetry/opentelemetry-collector-contrib#3382]
**Is your feature request related to a problem? Please describe.**
Grafana Labs recently re-licensed Grafana, Loki, and Tempo to AGPLv3 which is incompatible with CNCF license guidelines.

https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/

**Describe the solution you'd like**
Remove the Loki exporter that I contributed.

Notes: 

- For those interested in using it, feel free to copy it into a custom distribution and modify as you see fit. 
- This exporter was never an official component released by Grafana Labs, but rather just a community contribution to assist those using or investigating Loki.

**Describe alternatives you've considered**
- Hard fork of Loki with the Apache 2 license. (This is not something I want to maintain, nor do I believe the community would use it.)

**Comment by gramidt** [comment]
@bogdandrutu - Per our conversations. I will tag the community members I know this may impact.

**Comment by gramidt** [comment]
cc @jean @gillg @joshuali925 @scumpah @MacNale

**Comment by gillg** [comment]
Noooooo ! 😭
I understand the cncf guidelines and I'm not really enthousiast to their license change.
But what is the relationship with the exporter itself ? Elasticsearch is in the same case, and datadog, new relic are pure non open source solutions. So what is the problem to format logs in an expected format for Loki ?

**Comment by slim-bean** [comment]
I don't believe the license change should have any affect here, the client code and libraries within Loki remain Apache 2

**Comment by gramidt** [comment]
This is great news, @slim-bean! Will that client code be split out into a new repository?

**Comment by slim-bean** [comment]
No plans at the moment to split this out, however the [Licensing Doc](https://github.com/grafana/loki/blob/main/LICENSING.md) gives some more details here on what areas of the project will remain Apache2.

We did attempt to consolidate the Apache2 and client code as much as possible to make it easier to consume, we are considering a separate go mod file for the client code as well (however this comes with some pros and cons as well)

A separate repo isn't out of the question either, currently it's combined for ease of development and maintenance!

**Comment by gramidt** [comment]
Thank you for the details, @slim-bean! One thing to take into account is that many projects use automated tools for tracking licenses of components, so ensuring the final solution of the client code works with these automated scans would be great.

**Comment by gramidt** [comment]
@bogdandrutu - Do you foresee any CNCF challenges with the current way they have detailed the areas that will remain Apache 2?

**Comment by bogdandrutu** [comment]
@gillg it is not about being open-source it is about the license under what they release the "client" code that we depend on. If that license forces us to have a dependency that will affect our customers we will not maintain that dependency.

@alolita @lizthegrey is it ok to depend on the sub-part of the project that says it is apache2? Can you check with someone from CNCF?

**Comment by lizthegrey** [comment]
> @gillg it is not about being open-source it is about the license under what they release the "client" code that we depend on. If that license forces us to have a dependency that will affect our customers we will not maintain that dependency. With the new license everything built on top of the collector distro, or users of the distro MUST open-source their entire stack :))
> 
> @alolita @lizthegrey is it ok to depend on the sub-part of the project that says it is apache2? Can you check with someone from CNCF?

https://github.com/cncf/foundation/blob/master/agpl-recommendations.md

```
The Governing Board may refuse to grant exceptions at its discretion; however, some of the considerations that the Governing Board might take into account are as follows:

[...]

if the optional AGPL-3.0 component's licensor has made available interface tools (such as client libraries) that are under Apache-2.0 or a similar permissive license, that may also make it more acceptable as an exception.
```

Apply to the governing board, it seems like a slam dunk.

**Comment by bogdandrutu** [comment]
@caniszczyk can you tell me how I can apply for an "exception" (I think is more like a sanity check)? The part of code that we need is in https://github.com/grafana/loki/tree/main/pkg/logproto which seems to be apache-2 based on their [license doc](https://github.com/grafana/loki/blob/main/LICENSING.md).

**Comment by lizthegrey** [comment]
Does checking out the code in that module also place AGPL code on the filesystem? I remember Google had a policy against even downloading any AGPL code, even if it was unused.

**Comment by bogdandrutu** [comment]
We actually copied the code from there (here https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter/internal/third_party/loki/logproto), so we don't download that modules.

**Comment by caniszczyk** [comment]
This is a bit of a strange case of logoproto has that LICENSE_APACHE2 file but the copyright headers don't specify any specific license (which is way it's always nice to have copyright/license headers in each source file)

The simple solution here could be to copy those files before the AGPL license change and reference them at that point.

I'm reaching out to Grafana to get clarity, my assumption is they wanted to keep those files Apache 2.0

**Comment by gramidt** [comment]
@caniszczyk  - To help out, @slim-bean is the maintainer of Loki at Grafana Labs and he commented above on their intention.

**Comment by gramidt** [comment]
cc @tomwilkie - Is there anything else we should know that we may have missed?

**Comment by caniszczyk** [comment]
ideally I'd love Grafana to add license/copyright headers to those source files that indicate the Apache 2.0 license, should be a simple PR

**Comment by gramidt** [comment]
@slim-bean @tomwilkie - Do you foresee any issue adding the license/copyright headers to the source files per @caniszczyk suggestion?

**Comment by RichiH** [comment]
(@slim-bean summoned me)

@caniszczyk : The best course of action seems to be to add [SPDX IDs](https://spdx.dev/ids/) to the files in question to make the information machine readable and thus lintable. If you agree, I can propose this to the team leads.

**Comment by lizthegrey** [comment]
I think from my end concerns are resolved with SPDX IDs and ensuring the files are either hand-copied into our project, or are available to go import from a repo that doesn't intermix apache2 and agpl code.

(I remember this was a problem with elasticsearch where the commingling of the Free and non-Free components in one repo checkout made it challenging to build a pure Free distribution)

**Comment by jpkrohling** [comment]
I believe this should now be closed. If this is still a concern, feel free to reopen.
