### ISSUE TITLE
Add support for GELF receiver for logging

### ISSUE THREAD

**Issue by BharatKJain** [open-telemetry/opentelemetry-collector-contrib#33859]
### Component(s)

receiver/udplog

### Is your feature request related to a problem? Please describe.

I have added the code for GELF receiver, please follow this https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33858.

We're using GELF based logging for all application logs, which have a GELF client in them - refer to go GELF client.

We want to support server-side reception for GELF based logs.

### Describe the solution you'd like

Please check the PR

### Describe alternatives you've considered

We're already using the tremor's implementation of GELF - [link to tremor docs](https://www.tremor.rs/docs/0.12/reference/preprocessors/gelf-chunking/)

### Additional context

None

**Comment by djaglowski** [comment]
I see in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33858 you have proposed to implement this as a new receiver but here you state this is related to udplog.

If this would be an enhancement to the udplog receiver, please provide links to documentation of the gelf protocol and articulate how the receiver would be enhanced to support it.

**Comment by BharatKJain** [comment]
Closing this issue, linking this one:

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33861


This is not directly related to udplog receiver, I have forked some of the code from it but it's a separate receiver.
