### ISSUE TITLE
[awskinesisexporter] [RESOLVED] Cross account support

### ISSUE THREAD

**Issue by chepati** [open-telemetry/opentelemetry-collector-contrib#33891]
### Component(s)

exporter/awskinesis

### Is your feature request related to a problem? Please describe.

My OTel collector is in AWS account A and my Kinesis datastream is in AWS account B.  It seems the awskinesisexporter can't send metrics to the datastream in another AWS account.  If I specify just the stream_name, the exporter assumes it's in the same account/region and complains that it can't find it.

### Describe the solution you'd like

Ideally, I can use the ARN of my kinesis datastream in stream_name:

exporters:
  awskinesis:
    aws:
      stream_name: arn:aws:kinesis:REGION:ACCOUNT_ID:stream/stream_name

and as long as I have my IAM roles / policies set up correctly, the exporter should be able to talk to the kinesis datastream in the other AWS account.

**Comment by chepati** [comment]
Bump.

**Comment by MovieStoreGuy** [comment]
Mmm, interesting. 

Makes sense. I don't think it would be too hard of a change to implement.

**Comment by parambath92** [comment]
Hi @MovieStoreGuy , I would like to work on this issue.

**Comment by HongChenTW** [comment]
Hi @parambath92, are you still working on this issue? If not, I would like to implement this feature.

**Comment by parambath92** [comment]
Hi @HongChenTW , I couldn't work on this feature. Please go ahead.

**Comment by HongChenTW** [comment]
Hi @chepati, would you mind to share the details of how you deploy the otel collector? While developing this feature, I was also checking the abilities of this exporter, and found out that we could send metrics to another AWS account by specify `role` to assume role and specify `region` to locate the stream region.
