### ISSUE TITLE
How to config opensearch exporter to create new data streams, instead of new index?

### ISSUE THREAD

**Issue by PDCuong** [open-telemetry/opentelemetry-collector-contrib#33909]
### Component(s)

exporter/opensearch

### Describe the issue you're reporting
When i set :
```
exporters:
   opensearch/log:
      logs_index: user-abcd
```
It will create new index name user-abcd.  But i want to create new data streams. Can you help me?

**Comment by flenoir** [comment]
Hi @PDCuong , did you manage to solve your issue ? i'm kind have same question

**Comment by PDCuong** [comment]
First, just create new index template type datastream, in which index pattern contain `logs_index: user-abcd` . After that, push logs from otel-collector with logs_index: user-abcd`.  It will automatically create new data stream. sorry for my bad English.
