### ISSUE TITLE
[exporter/loki] Deprecate component

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#33916]
### Component(s)

exporter/loki

### Describe the issue you're reporting

Loki is able to ingest OTLP natively for a few months now. As one of the code owners for this component, I feel that we are ready to deprecate this in favor of OTLP natively. This issue is a tracker for this deprecation, composed of:

- [ ] #33917
- [ ] Remove the component from distributions by September 2024
- [ ] Remove the code for this component by October 2024

**Comment by jameshulse** [comment]
Is it possible to document, or provide a sample configuration for the OTLP exporter that would simulate any of the transformation that the loki exporter was doing under the hood (if any).

**Comment by mar4uk** [comment]
> Is it possible to document, or provide a sample configuration for the OTLP exporter that would simulate any of the transformation that the loki exporter was doing under the hood (if any).

@jameshulse the loki exporter [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter) was just updated. Please find migration instructions and sample configuration there. Please let us know if something is not clear or missing

**Comment by chennin** [comment]
The above link is now broken. Permanent link to the last version: [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/release/v0.130.x/exporter/lokiexporter/README.md#migration-instructions)
