### ISSUE TITLE
Do Filelog operators process slices?

### ISSUE THREAD

**Issue by MJ12301** [open-telemetry/opentelemetry-collector-contrib#33932]
### Component(s)

receiver/filelog

### Is your feature request related to a problem? Please describe.

I have log files which contain JSON arrays, when I try using json_array_parser, OTEL says that the operator is disabled, and refuses to start. I am using version OTEL collector contrib 0.104.0.

How can I apply operations or access slice elements (e.g. attributes.my_array[0])?

### Describe the solution you'd like

To be able to process elements inside slices, or a certain operator to copy a slice element (Or extract them) to a field.

**Comment by djaglowski** [comment]
If you are using a recent version of the collector, you can enable the `logs.jsonParserArray` feature gate to enable this operator. I've opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33948 to upgrade this gate to beta, which will enable it by default going forward.

**Comment by crobert-1** [comment]
_Removing `needs triage` based on code owner's feedback._

@MJ12301 Is there anything else that is needed here? If not, we can close this issue.

**Comment by andrzej-stencel** [comment]
Closing as the [json_array_parser](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.111.0/pkg/stanza/docs/operators/json_array_parser.md) operator is available now.
