### ISSUE TITLE
Introduce label to trigger load tests for a Pull Request

### ISSUE THREAD

**Issue by mowies** [open-telemetry/opentelemetry-collector-contrib#33979]
### Describe the issue you're reporting

As discussed in [this PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33975#issuecomment-2217376243), we could introduce a label called "Run Load Tests" (similar to the "Run Windows" label) that triggers the load tests for a pull request.

This would make development and maintenance of the load tests much easier, since they only run on `main` right now, and also only on self-hosted runners.
Right now, the load tests are fairly hard to maintain, since they are not fully reproducible for contributors, without access to the same self-hosted runners and the `main` branch limitation which doesn't run on PRs. Especially so, since the tests take hardware consumption into account as well, which differs between self-hosted and github-hosted runners (I assume).

**Comment by mowies** [comment]
I'd be up for working on this

**Comment by crobert-1** [comment]
Sounds good to me, removing `needs triage`. You're welcome to work on this @mowies!

**Comment by mowies** [comment]
@crobert-1 @mx-psi PR is ready for review :)

**Comment by mowies** [comment]
closing this since it's not feasible. more details in the attached PR
