### ISSUE TITLE
Support float64 rates for telemetrygen

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-collector-contrib#33982]
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

Using float values in `--rate` returns the following error:

```
Error: invalid argument "0.1" for "--rate" flag: strconv.ParseInt: parsing "0.1": invalid syntax
```

The `--rate` flag for telemetrygen is an [Int64Var](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/562b7b66f6247eeeb0da8fd1a0e0c10dc5873212/cmd/telemetrygen/internal/common/config.go#L118), however this is ultimately [parsed to a `rate.Limit` value](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/562b7b66f6247eeeb0da8fd1a0e0c10dc5873212/cmd/telemetrygen/internal/metrics/metrics.go#L80), which is an alias for [float64](https://pkg.go.dev/golang.org/x/time/rate#Limit).

I propose changing this flag to a Float64Var to allow non-integer rates. My specific use case is to set this value to something like `0.2`, to send a metric once every 5 seconds. Currently, the slowest rate I can set is `1`, exporting a metric every second (which is an aggressive rate).

### Describe the solution you'd like

Support rates <1/second

### Describe alternatives you've considered

We could also use [`rate.Every()`](https://pkg.go.dev/golang.org/x/time/rate#Every) to specify something like this, which might be clearer. But this just parses to a `rate.Limit`, so I think it is just syntactical sugar

**Comment by damemi** [comment]
Opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33984 as a fix

**Comment by crobert-1** [comment]
_A code owner has approved the PR to resolve this issue, I'm going to remove the `needs triage` label._
