### ISSUE TITLE
Specify requirements for components to be added to the repo

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector-contrib#34]
We intend to build distribution of the contrib repo with all components present. In order to ensure that quality of this build we should define a minimum set of requirements (test, documentation, etc) for all components available in the repo.

**Comment by evan-bradley** [comment]
The requirements for new components are described [in the CONTRIBUTING.md file](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components), and existing components meet most if not all of these requirements. I'm closing this issue for now, feel free to reopen it if there's anything else that we would like to do here.
