### ISSUE TITLE
Not able to get traces into kafka consumer from otel collector

### ISSUE THREAD

**Issue by edificeinsightworksapp** [open-telemetry/opentelemetry-collector-contrib#34010]
### Component(s)

exporter/kafka

### Describe the issue you're reporting

Hello,

Not able to get traces into Kafka consumer output from collector. please find the below otel-config file:
Our pipeline is from our app--otel-kafka, spans are getting generated and displayed in the otel output debug log. But not going to Kafka topic and no error msg either. If I post a msg directly to Kafka from any other producer, data is received to Kafka. Request to let me know what would be the issue or any way i can debug more?

Starting the collector with below command:

`docker run -d \ -p 4317:4317 -v $(pwd)/otel-collector-config.yaml:/etc/otelcol/otel-collector-config.yaml \ otel/opentelemetry-collector:latest`

otel-collector-config.yaml

```
`receivers:
otlp:
protocols:
grpc:

processors:
batch:
queued_retry:

exporters:
debug:
verbosity: detailed
kafka:
brokers:
- localhost:9092
#topic: jaeger-spans
protocol_version: 3.7.1
logging:
verbosity: detailed
loglevel: debug

service:
pipelines:
traces:
receivers: [otlp]
processors: [batch]
exporters: [debug,kafka,logging]
telemetry:
logs:
level: "debug"
encoding: "json"
development: true
```
`

Thanks

**Comment by harshalschaudhari** [comment]
Would you be able to share a functional Kafka exporter configuration that works with the Otel Collector Docker image, along with its setup?

**Comment by Frapschen** [comment]
close for  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34010
