### ISSUE TITLE
[processor/geoip] Detect source.address from signal's attributes

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-collector-contrib#34036]
### Component(s)

processor/geoip

### Is your feature request related to a problem? Please describe.

The current GeoIP processor looks for the `source.address` field in the resource attributes of every signal. The processor should be able to detect the IP from other contexts too, for example, the `source.address` might be located in the attributes instead of the identifying resource attributes. 

### Describe the solution you'd like

Detect the IP from the signal's attributes if not present in the resource ones, and add the corresponding geographical attributes to the same context.

**Comment by crobert-1** [comment]
_Makes sense to me, and was filed by a code owner, removing `needs triage`._

One thing to note: The README currently specifies that `source.address` is taken from the resource attributes. This will need updated as a part of this change. (You're probably already aware, just wanted to point it out so we don't miss it 👍)

**Comment by rogercoll** [comment]
In order to let the user configure whether to look in the resource attributes or the signal's attributes (in the future could be any other source), I purpose to add the following configuration structure in the processor.

```yaml
geoip:
  source:
    from: resource_attributes
```

The source configuration option would tell the processor whether to look for the `source.address` from the `resource_attributes` or `attributes`. The configuration naming is similar to the [k8sattributes](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor) processor.

I think being a map configuration option would ease the addition of future options for narrowed IP look ups, for example, specifying a different attribute name to override the default `source.address`:

```yaml
geoip:
  source:
    from: attributes
    name: upstream.address
```

**Comment by rogercoll** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34214
