### ISSUE TITLE
Otel agent service start stop script not provided for RHEL 6 version

### ISSUE THREAD

**Issue by krantishetty** [open-telemetry/opentelemetry-collector-contrib#34090]
### Component(s)

cmd/otelcontribcol

### Collector version

v100

### Environment information

Rhel6 os not able to find start stop script for otel agent. Can you confirm if we can get the service start/stop details?

**Comment by krantishetty** [comment]
Can someone please advise on this?

**Comment by atoulme** [comment]
Please help with release support under https://github.com/open-telemetry/opentelemetry-collector-releases.

However, https://endoflife.date/rhel RHEL 6 is EOL. Closing as not planned since RHEL 6 is no longer maintained.
