### ISSUE TITLE
Issue in calls_total metric of spanmetric connector

### ISSUE THREAD

**Issue by namkattor123** [open-telemetry/opentelemetry-collector-contrib#34126]
### Component(s)

connector/spanmetrics

### Describe the issue you're reporting

I installed opentelemetry java agent and using [opentelemetry-collector-contrib] to expose metrics which displayed SPM on JaegerUI. But metric calls_total doesn't increase, it increase and decreas over time.![Screenshot 2024-07-17 at 08 47 38](https://github.com/user-attachments/assets/6f2a5f4d-6e20-4a7f-a6e4-55ad149988b0)

**Comment by namkattor123** [comment]
My metric graph 
![Uploading Screenshot 2024-07-17 at 08.49.53.png…]()

**Comment by namkattor123** [comment]
My metric graph
![Screenshot 2024-07-17 at 08 49 53](https://github.com/user-attachments/assets/1f1cb955-5903-4690-b258-9a0c1ea8fdda)

**Comment by namkattor123** [comment]
My SPM monitor on Jaeger
![Screenshot 2024-07-17 at 08 51 33](https://github.com/user-attachments/assets/4fc730c9-af07-437b-99a9-56e22a02ce06)

**Comment by crobert-1** [comment]
Hello @namkattor123, from what I can tell, the metric is the current batch's total, rather than the total count of all spans seen ever. I believe this is on purpose.

I'll defer to code owners though in case there's something I'm missing.

**Comment by namkattor123** [comment]
Thank @crobert-1 , This photo is my value of call_totals metric. As documents of spanmetric connector, it's counter type. I don't understand why it can decrease

**Comment by namkattor123** [comment]
![Screenshot 2024-07-18 at 10 25 47](https://github.com/user-attachments/assets/73417642-835b-4105-b880-cfdc117e0aa7)
This is my pipeline config

**Comment by namkattor123** [comment]
![Screenshot 2024-07-18 at 10 25 28](https://github.com/user-attachments/assets/300faaec-fb37-4b69-864d-d34970753d4b)
This is my data value of metric

**Comment by Frapschen** [comment]
@namkattor123 Please check your spanmetrics connector `aggregation_temporality` config, if the value is `AGGREGATION_TEMPORALITY_DELTA`, the `call_totals` will be gauge metrics.

**Comment by Frapschen** [comment]
more like this: https://github.com/open-telemetry/opentelemetry.io/issues/4368

**Comment by namkattor123** [comment]
I config spanmetric with default, it means that aggregation_temporality config must be AGGREGATION_TEMPORALITY_CUMULATIVE, why it's setten to AGGREGATION_TEMPORALITY_DELTA . Can you explain for me @Frapschen

**Comment by Frapschen** [comment]
@namkattor123 have you add `resource_metrics_key_attributes` to your spanmetrics connector?  please see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21101#issuecomment-1910295920

**Comment by Frapschen** [comment]
> @namkattor123 have you add `resource_metrics_key_attributes` to your spanmetrics connector? please see [#21101 (comment)](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21101#issuecomment-1910295920)

@namkattor123  if the above solution does not work for you, you can use [the UUID() function](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.99.0/pkg/ottl/ottlfuncs/README.md#UUID) in [the transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#transform-processor) to add a unique UUID to metrics attributes in each collector. I have tested this method, it works for me.
