### ISSUE TITLE
[processor/tailsamplingprocessor] documentation to drop trace

### ISSUE THREAD

**Issue by mangkoran** [open-telemetry/opentelemetry-collector-contrib#34145]
### Component(s)

processor/tailsampling

### Describe the issue you're reporting

In [tailsampling readme](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor#readme) there is no mention on how to drop a trace. What I understand from [this part](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2997a9018fb4bdfd21f35c890c1fa6c0cc532365/processor/tailsamplingprocessor/README.md?plain=1#L54) is that each policy will result in either "sample" or "not sample" decision. However, there is also no mention how to create a "not sample" decision.

How can I drop a certain trace? e.g. match the trace using `string_attribute` and drop the matched trace. Initially I thought this could be done using filter processor. However, as stated in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31355 filter processor can only drop span and not the entire trace.

**Comment by jpkrohling** [comment]
You can set an "invert" match: if a trace has a span with a specific attribute value for a given attribute, it would normally yield a "Sample" decision. An inverted match would yield a "Not Sample"  decision.

**Comment by mangkoran** [comment]
Thank you for the explanation. However I still couldn't understand the meaning of this line:
> When there's an "inverted not sample" decision, the trace is not sampled;

So is it possible to have an "inverted not sample"?

**Comment by jpkrohling** [comment]
I think both are right:

- the "string" policy, for instance, would do an invert match on a specific string
- the invert match would generate an inverted don't sample, which means "do not sample"

Here's an example from the docs:

```
         {
            name: test-policy-9,
            type: string_attribute,
            string_attribute: {key: http.url, values: [\/health, \/metrics], enabled_regex_matching: true, invert_match: true}
         },
```

In this case, if the URL contains `/metrics`, we are dropping the trace.
