### ISSUE TITLE
Improve regex replacement.

### ISSUE THREAD

**Issue by h0cheung** [open-telemetry/opentelemetry-collector-contrib#34146]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

The standard `regexp` in Go is sometimes powerless, which make us hard to do some replacement.

For example, I want to replaces pure number path segment in a http url. I tried to use some expression: `/\d+(/|$)` to `/?$1`.

However, if there are continuous segments, they won't be replaced at once: `/12/34/56/78` -> `/?/34/?/78`. As positive lookahead is not supported, the only workaround I find this to replace by this expression again, but it will cause 2x cpu usage.

`(/\d+){1,}(/$)` can match perfectly, but I can't find a way to replace each match of `(/\d+)` to `/?`.

### Describe the solution you'd like

1. Consider supporting some powerful regex engine, such as https://github.com/dlclark/regexp2. Let users choose which engine to use according to their needs.
2. Enhance the functions to replacing each match of some expression ends with `{x,}`

**Comment by evan-bradley** [comment]
I think it would likely make sense to offer a more powerful alternative regex engine for cases like this where the built-in Go engine isn't sufficient. We could probably add an `engine` or `lang` optional parameter to our functions to allow selecting what is used.

**Comment by TylerHelmuth** [comment]
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32167
