### ISSUE TITLE
Create otelarrow exporter instance per distinct metadata combos

### ISSUE THREAD

**Issue by kristinapathak** [open-telemetry/opentelemetry-collector-contrib#34178]
### Component(s)

exporter/otelarrow

### Is your feature request related to a problem? Please describe.

I want to open Arrow streams where specified metadata sent per stream message all match on a per stream basis, similar to configuring `metadata_keys` in the [batch processor](https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor).

### Describe the solution you'd like

Similar to the batch processor, add the below configuration fields:
```
metadata_keys (default = empty): When set, this exporter will create one arrow exporter instance per distinct combination of values in the client.Metadata.
metadata_cardinality_limit (default = 1000): When metadata_keys is not empty, this setting limits the number of unique combinations of metadata key values that will be processed over the lifetime of the exporter.
```
Then, for each unique combination of metadata keys, an arrow exporter object is created. This object creates the number of streams specified by `num_streams`. The maximum possible number of open streams would be `metadata_cardinality_limit * num_streams`.

Note: there is nothing arrow exporter specific about this logic. It could be used for any exporter where unique objects are desired per metadata combination.

**Comment by jmacd** [comment]
@kristinapathak Thanks for filing! I agree with the stated goal here. While the Arrow components can pass headers on a per-request level, this can present authorization challenges for vendors that would prefer to authorize based on HTTP-level headers. 

As you wrote, this sounds like functionality that could be implemented in an exporterhelper module, but there may not be many components that want this. The only reservation I have is that this method will tie us to the legacy style of batching in processor components and will restrict us from using the new exporterhelper-based batching. Ideally, I think we could look for ways to improve exporterhelper to support both batching and exporting by metadata, but that can be a future project. I support adding this functiolnaity directly in the Arrow exporter especially if the logic can be kept mostly separate, which seems natural.

**Comment by kristinapathak** [comment]
@jmacd, I think this was fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34827? Can I close this?
