### ISSUE TITLE
Move @bryan-aguilar to emeritus

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#34186]
Hi @dmitryax, sorry to ping you for this PR that wasn't assigned to you. @bryan-aguilar isn't active in OpenTelemetry, I suppose we may need to move him to `emeritus` status. Could you help again to approve/merge this PR in his place?

_Originally posted by @jj22ee in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33798#issuecomment-2206953350_

@bryan-aguilar please voice if you believe you should not move to emeritus status.

**Comment by mx-psi** [comment]
I removed @bryan-aguilar from the review auto-assignment so that PRs get reviews until we get a reply/move to emeritus

**Comment by crobert-1** [comment]
> I removed @bryan-aguilar from the review auto-assignment so that PRs get reviews until we get a reply/move to emeritus

FYI: It looks like this may not have been completed successfully, a [PR opened today](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34521) was assigned to @bryan-aguilar.

**Comment by mx-psi** [comment]
I changed the auto-assignment for reviewers, but not for assignees (sorry, it's confusing). The assignees are handled via a file somewhere, we can also make this change

**Comment by crobert-1** [comment]
> I changed the auto-assignment for reviewers, but not for assignees (sorry, it's confusing). The assignees are handled via a file somewhere, we can also make this change

Ah, my bad, thanks for clarifying! Looks like the assignment should be resolved by #34523 👍
