### ISSUE TITLE
 Xray Exporter Missing Documentation on Annotation Indexing Feature

### ISSUE THREAD

**Issue by arun-annamalai** [open-telemetry/opentelemetry-collector-contrib#34182]
### Component(s)

exporter/awsxray

## Description
The following PR adds the functionality to index span attributes as Xray annotations in code. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17855. 

## Expected Result
This new functionality should be documented in the AWS Xray exporter readme

### Collector version

Latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by srprash** [comment]
@arun-annamalai Since the PR is merged, can we close this issue?
