### ISSUE TITLE
Consider replacing `github.com/tilinna/clock` to with a more maintained library

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/opentelemetry-collector-contrib#34190]
### Describe the issue you're reporting

https://github.com/tilinna/clock is used in several places in the project:

```console
/extension/jaegerremotesampling/internal/remote_strategy_cache.go
./extension/jaegerremotesampling/internal/remote_strategy_cache_test.go
./receiver/chronyreceiver/internal/chrony/client.go
./receiver/chronyreceiver/scraper_test.go
./receiver/chronyreceiver/scraper.go
./connector/spanmetricsconnector/factory.go
./connector/spanmetricsconnector/connector.go
./connector/spanmetricsconnector/connector_test.go
```

However at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34128#discussion_r1681061469 it was proposed to switch to another similar library which is better maintained. The proposed library is https://github.com/jonboulle/clockwork and is already tried at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34128 and https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34174.

https://github.com/jonboulle/clockwork has notably more contributors and counts quite a few usages by other projects/repositories.

Based on this, the current issue proposes to gradually start switching from https://github.com/tilinna/clock to https://github.com/jonboulle/clockwork.

/cc @djaglowski @pjanotti

**Comment by odubajDT** [comment]
Hi, if possible I would like to pick up this issue
