### ISSUE TITLE
v0.4.0 modules have a non-release Collector dependency

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector-contrib#342]
**Describe the bug**
All `v0.4.0` Contrib tags have and outdated Collector dependency, e.g.
see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6b1462efb5e704404ebcf9342c4ca3164e758f80/exporter/stackdriverexporter/go.mod#L11

This is because the tags were created for https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/6b1462efb5e704404ebcf9342c4ca3164e758f80 rather than https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/df7ec20cb291a79e04c5344e712e2b7bf4f416a5 (or after it).

**Steps to reproduce**
```
go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/stackdriverexporter@v0.4.0
```
will result in
```
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/stackdriverexporter v0.4.0
        go.opentelemetry.io/collector v0.3.1-0.20200615181810-b28cbd9c8e2e
```
in `go.mod`.

**What did you expect to see?**
```
go.opentelemetry.io/collector v0.4.0
```

/cc @owais

**Comment by owais** [comment]
These are technically outdated but in practice provide the same "software" but yes contrib release should depend on the corresponding core release numbers. I've added it to list release the process steps that we'll be adding to the repos soon.

**Comment by owais** [comment]
Is this causing you any problems? If so, we could release v0.4.1 to fix this.

**Comment by nilebox** [comment]
> Is this causing you any problems?

No, but would be nice to fix in the next release.

**Comment by owais** [comment]
Noted.
