### ISSUE TITLE
[exporter/elasticsearch] Missing Scope.name Field in elasticsearch Exporter with ECS Mapping Mode

### ISSUE THREAD

**Issue by dominicqi** [open-telemetry/opentelemetry-collector-contrib#34209]
### Component(s)

exporter/elasticsearch

## Description

I'm using the Elasticsearch exporter with mapping.mode: ecs, and I noticed that the Scope.name field is missing from the documents stored in Elasticsearch.

Any help resolving this would be appreciated!

### Collector version

v0.103

## Environment

Kubernetes

### OpenTelemetry Collector configuration

```yaml
mapping:
  mode: ecs
```

**Comment by carsonip** [comment]
Hi @dominicqi , it is expected that Scope.name is ignored in ecs mapping mode. That is consistent with the existing handling of otlp scope attributes in apm-server. In contrast, resource attributes are always stored in the document in ecs mapping mode. Is there a specific reason why you need Scope.name in the resulting ES document?

**Comment by dominicqi** [comment]
> Hi @dominicqi , it is expected that Scope.name is ignored in ecs mapping mode. That is consistent with the existing handling of otlp scope attributes in apm-server. In contrast, resource attributes are always stored in the document in ecs mapping mode. Is there a specific reason why you need Scope.name in the resulting ES document?

Hi, Our Application language is Java uses opentelemetry java instrumentation, the Scope.name of Log is Java Logger Name, default is java class name. It is important for Java log.  
If there are any other ways to resolve this, please let me know. Thanks!

**Comment by dominicqi** [comment]
Oh, I know , the caller should be put into scope.attr , but the java-agent log4j v1.2 not support capture code attributes。I use transformer copy Scope.name to attribute now , I will close this.
