### ISSUE TITLE
[processor/resourcedetection] Produce docs based on metadata.yaml 

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/opentelemetry-collector-contrib#34210]
### Component(s)

processor/resourcedetection

### Describe the issue you're reporting

Based on the discussion at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34140, it would be nice and more straightforward to produce docs files for this processor based on the `metadata.yaml` files.

We can follow what the [hostmetricsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/README.md) does and from the main readme link to the various sub-components.

/cc @codeboten

**Comment by crobert-1** [comment]
Thanks for filing @ChrsMark!

I ended up filing https://github.com/open-telemetry/opentelemetry-collector/issues/10705 because I was a bit confused as to why there isn't a `documentation.md` file for the EKS detector's resource attributes. Once we have one we'll be able to link to it from the top-level README.

**Comment by ChrsMark** [comment]
Since https://github.com/open-telemetry/opentelemetry-collector/issues/10705 is completed we can proceed with tuning the processor's docs accordingly once the latest version of `mdatagen` is pulled in contrib.

**Comment by ChrsMark** [comment]
The documentation pages were generated with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35701/files#diff-a118362df118f1449a78a69e67f50a87d9c86e3b3bbeadb5d01fb15129fd5cc7R1 🎉 .

Filed https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35737 as an attempt to adjust the processor's docs accordingly.
