### ISSUE TITLE
Need a common utils to call k8s api server

### ISSUE THREAD

**Issue by pxaws** [open-telemetry/opentelemetry-collector-contrib#3424]
**Is your feature request related to a problem? Please describe.**
Existing otel components contain some duplicate functionalities for calling the kubernetes api server:
* Kubernetes Cluster Receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver
  * `watcher` use kubernetes `informers.SharedInformerFactory` to listen for resources changes continuously: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sclusterreceiver/watcher.go. 
* K8s processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sprocessor
  * uses the same kubernetes informers to call api server but the code is quite different. See https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sprocessor/kube/informer.go and https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sprocessor/kube/client.go

In addition, the AWS Container Insights project is also introducing another way to call the kubernetes api server through a lower-level `cache.reflector` api: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3367. Unlike Kubernetes informers that automatically maintain all the resource metadata in cache, `cache.reflector` requires you to manage your own cache. So you can selectively keep only the things that are really needed. This is beneficial as we want to keep the memory usage as small as possible especially when you are monitoring a big cluster with a large number of different resources (e.g. pod, node, job, endpoint, service ...)

**Describe the solution you'd like**
The duplicate functionalities doesn't seems to be a big issue at this moment. But as more receivers/processors begin to call k8s api server in the future, there is a need to provide a common k8s util for code reuse. I think the ideas is to provide at least two set of apis (one using kubernetes informers and one using `cache.reflector`). To design an easy-to-use and extendable k8s utils seems to be a big effort and will involve owners of multiple otel components. I don't imagine that this can be done in a short time. So I am proposing that we use the current feature request to track the relevant discussions and plans. 

For now, we still want to merge the [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3367) into a aws internal folder for Container Insight usage due to the project timeline. But we are happy to discuss any refactoring about the code to make it also useful for other otel components.

**Comment by pxaws** [comment]
@alolita @mxiamxia

**Comment by jrcamp** [comment]
See also https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/observer/k8sobserver
