### ISSUE TITLE
Datadog receiver capability to set sampling.priority attribute

### ISSUE THREAD

**Issue by melchiormoulin** [open-telemetry/opentelemetry-collector-contrib#34267]
### Component(s)

receiver/datadog

### Is your feature request related to a problem? Please describe.

Problem:
When using [Probabilistic Sampling Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/probabilisticsamplerprocessor/README.md) sampling.priority helps to control the sampling on traces:

> For trace spans, this sampler supports probabilistic sampling based on a configured sampling percentage applied to the TraceID. In addition, the sampler recognizes a sampling.priority annotation, which can force the sampler to apply 0% or 100% sampling

When using datadog receiver i can't setup sampling.priority attribute with datadog receiver.

### Describe the solution you'd like

x-datadog-sampling-priority is the header in datadog to set sampling priority
It would be nice to parse this HTTP header and set sampling.priority attribute 
This HTTP header would allow to force the sampling or not.

**Comment by jpkrohling** [comment]
Sounds like a valid feature request. Would you like to work on that?

**Comment by melchiormoulin** [comment]
yes for sure !
