### ISSUE TITLE
Splunk metric names should be validated via regex

### ISSUE THREAD

**Issue by spiffyy99** [open-telemetry/opentelemetry-collector-contrib#34275]
### Component(s)

internal/splunk

### Describe the issue you're reporting

Currently, while parsing splunk metric fields from events (starting with `metric_name`), no validation is done to ensure the metric names actually fit with Splunk criteria. According to the [Splunk documentation](https://docs.splunk.com/Documentation/Splunk/9.2.2/Metrics/Overview#What_is_a_metric_data_point.3F), metric names have the following restriction:

> Metric names can include only upper-case letters, lower-case letters, numbers, underscores, dots, and colon symbols. 
Metric names cannot include spaces or the reserved term metric_name. Metric names cannot begin with numbers or underscores.

It follows that field names that don't follow this convention should be designated as dimensions rather than metric datapoints.

**Comment by crobert-1** [comment]
Hello @spiffyy99, thanks for filing! Since #34291 has been merged, can we close this issue?

**Comment by spiffyy99** [comment]
yes, i'll close it now. thanks for the review.

**Comment by crobert-1** [comment]
Thanks for resolving, really appreciate the help!
