### ISSUE TITLE
filelog  strogae   directory must exist: stat /var/lib/otelcol/file_storage: no such file or directory

### ISSUE THREAD

**Issue by wangjinxiang0522** [open-telemetry/opentelemetry-collector-contrib#34277]
### Component(s)

 extension/storage

### Describe the issue you're reporting

version: v0.105.0

 extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      file_storage/default:
        directory: /var/lib/otelcol/file_storage   

Error: invalid configuration: extensions::file_storage/default: directory must exist: stat /var/lib/otelcol/file_storage: no such file or directory

**Comment by ChrsMark** [comment]
I guess the error message is quite precise: `Error: invalid configuration: extensions::file_storage/default: directory must exist: stat /var/lib/otelcol/file_storage: no such file or directory`

Indeed, the directory for the file_storage must exist: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage#file-storage

Hence we can close it, unless the purpose is to propose to change this behavior.

**Comment by VihasMakwana** [comment]
@wangjinxiang0522 create a directory with `mkdir -p /var/lib/otelcol/file_storage` and it should work when you restart it.

**Comment by wangjinxiang0522** [comment]
I'm running in a Kubernetes  environment, and the directory is not created in the otel-contrib-collector image.

`yaml`
      initContainers:
        - name: init-filelog-receivers
          image: reg.sprucetec.com/monitor/docker.io/library/busybox:1.28
          command: ['sh', '-c', 'mkdir -p /var/lib/filelog/receivers && chmod 777 /var/lib/filelog/receivers']
          volumeMounts:
            - name: filelog-receivers
              mountPath: /var/lib/filelog/receivers
      containers:
        - name: opentelemetry-collector
          command:
            - /otelcol-contrib
            - --config=/conf/relay.yaml
          securityContext:
            {}
          image: "reg.sprucetec.com/monitor/mc-otel-contrib-collector:0.105.25"
          imagePullPolicy: IfNotPresent

I created the file using an initContainer, which solved the problem. Thanks, everyone!

**Comment by VihasMakwana** [comment]
@ChrsMark I think this is good to close

**Comment by ChrsMark** [comment]
@wangjinxiang0522 since you are on K8s you can check how the Collector Helm Charts deal with that. 

Specifically the `storeCheckpoints` preset at https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_pod.tpl#L170 defines the `hostPath` with [DirectoryOrCreate](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath-volume-types). This can remove the need for the `initContainer`.
