### ISSUE TITLE
Add K8s Container Waiting Reason Information in attributes

### ISSUE THREAD

**Issue by Bhogayata-Keval** [open-telemetry/opentelemetry-collector-contrib#34280]
### Component(s)

`receiver/k8scluster`

### Is your feature request related to a problem? Please describe.

For the metric `k8s.container.ready`, 
The attributes should have information about Container Waiting Reason ( If container is in Waiting State )

### Describe the solution you'd like

A possible solution is to record this information using ...
https://pkg.go.dev/k8s.io/api/core/v1#ContainerStateWaiting > Reason

**Comment by ChrsMark** [comment]
Isn't this captured by https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32457?

/cc @povilasv

**Comment by Bhogayata-Keval** [comment]
Oh, right ! 
Thanks @ChrsMark, This is exactly what I was looking for. 
We can close this issue then.

**Comment by crobert-1** [comment]
Closing in favor of #32457. Thanks all!
