### ISSUE TITLE
[testbed][filelog] - large file tests for filelog receiver.

### ISSUE THREAD

**Issue by VihasMakwana** [open-telemetry/opentelemetry-collector-contrib#34288]
### Component(s)

receiver/filelog, testbed

### Describe the issue you're reporting

- Add automated test cases for `filelog` receiver to test very large files.
- Use the existing `testbed` for this.

---

Large files would typically range in a couple of GBs

**Comment by djaglowski** [comment]
@VihasMakwana, I don't have a strong opinion on this other than that the test should generate the large file each time, rather than store it in the repo, and assuming that this can be done without too much trouble on systems as small as CI runners.

**Comment by VihasMakwana** [comment]
@djaglowski I see. That’s what I’m thinking.

We can make use of `t.TempDir(..)` style file creation to ensure that we remove our log files immediately after test succeeds/fails.

We recently had an [issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31074) reported for `filelog` in which the user consistently loses +1k log out of ~600k. The file size is not even that big (it would range in MBs for this particular issue). 

In my opinion, it makes sense to have some sort of correctness tests for large files to ensure that we don't drop any log out of the blue.

**Comment by VihasMakwana** [comment]
I would appreciate if anyone from @open-telemetry/collector-approvers can share some thoughts on this issue.

**Comment by VihasMakwana** [comment]
Can someone from @open-telemetry/collector-triagers assign this to me?

**Comment by VihasMakwana** [comment]
Can someone from @open-telemetry/collector-contrib-triagers assign this to me?

**Comment by djaglowski** [comment]
Closed by #34417
