### ISSUE TITLE
[exporter/elasticsearch] Data stream routing does not sanitize values

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector-contrib#34285]
### Component(s)

exporter/elasticsearch

## Description

Data stream attributes are not sanitized, resulting in non-compliant data stream names. Sanitization should be implemented according to https://www.elastic.co/guide/en/ecs/current/ecs-data_stream.html. There is also an [implementation of DS fields sanitization in ES](https://github.com/elastic/elasticsearch/blob/33d63fa9c2fc3afb9184f31e2681942cfd8dc7fd/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/RerouteProcessor.java#L203-L206), but in this implementation there is in incorrect handling of an edge case where string limit should be 100 unicode characters instead of 100 bytes.

## Steps to Reproduce

Supply a value with `-` in resource attributes `data_stream.dataset` or `data_stream.namespace`

## Expected Result

The value is sanitized so that the resulting data stream does not contain `-`

## Actual Result

The resulting data stream contains `-`.

### Collector version

v0.105.0

**Comment by crobert-1** [comment]
_Removing `needs triage` as this was filed by a code owner and makes sense to me._
