### ISSUE TITLE
[AlibabaCloudLogServiceExporter] metric exporter contains special character

### ISSUE THREAD

**Issue by shabicheng** [open-telemetry/opentelemetry-collector-contrib#3429]
**Describe the bug**

OpenTelemetry metric's labels contains '.' or others none Letter or Digit characters, the alibabacloudlogserviceexporter do not replace these characters, so promQL will cause errors like "promql error: 1:33: parse error: unexpected character inside braces: '.'"

According to opentelemetry collector prometheus exporter, we can replace any none Letter or Digit characters with '_'

eg : https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/prometheusexporter/sanitize.go

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by shabicheng** [comment]
I will fix this issuce soon.

**Comment by codeboten** [comment]
@shabicheng has this issue been fixed?

**Comment by qiansheng91** [comment]
@codeboten  Hi, Merging PR #13393 will fix this issue

**Comment by codeboten** [comment]
This was fixed, updating labels accordingly
