### ISSUE TITLE
Metric tags are being dropped when using ObserverType: summary

### ISSUE THREAD

**Issue by jatan28** [open-telemetry/opentelemetry-collector-contrib#3431]
Currently, the statsd receiver supports the conversion of timings to either gauge/summary. While using gauge we can see that the tags of the original incoming metric are correctly translated to output metric labels but this does not happen when using summary which is seen https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/statsdreceiver/protocol/metric_translator.go#L71

**Steps to reproduce**
Use config:
```  
statsd:
    endpoint: 0.0.0.0:<port>
    aggregation_interval: 60s
    enable_metric_type: false
    timer_histogram_mapping:
    - statsd_type: histogram
      observer_type: summary
    - statsd_type: timing
      observer_type: summary

And send timing metrics with labels.

**Comment by gavindoudou** [comment]
Thanks! The summary part does not have tags. I will add.

**Comment by gavindoudou** [comment]
Are working on a fix, will have the PR tomorrow.

**Comment by gavindoudou** [comment]
Fixed by that PR 3440.

**Comment by gavindoudou** [comment]
Cam we close that?

**Comment by jmacd** [comment]
Done.
