### ISSUE TITLE
 Configuration to retrieve password from the environment or elsewhere

### ISSUE THREAD

**Issue by nicacioliveira** [open-telemetry/opentelemetry-collector-contrib#34355]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

For security reasons, it is bad when we have to pass the password directly to the collector configuration. I would like to have a way to get the password from the environment or from another location so as not to expose the password within the exporter configuration.

### Describe the solution you'd like

Considering a Kubernetes environment, we can use the crd secret type to save the password.
Here, at my company we use the ExternalSecrets module configured with AWS secrets Manager because we rotate keys and because we would not like to expose credentials within a github repository.

Therefore, a simple way to recover the password from the env solves the problem.

**Comment by Frapschen** [comment]
Hi,@nicacioliveira  otel config file already support use env, please see https://opentelemetry.io/docs/collector/configuration/#environment-variables

**Comment by nicacioliveira** [comment]
Thanks @Frapschen
