### ISSUE TITLE
[cmd/opampsupervisor]: Refactor NewSupervisor to take a config instead of a filepath

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#34379]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

The supervisor currently takes in a path to a config file.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/20d6bae9ee577822cc72301d1eea4cfbd909040a/cmd/opampsupervisor/supervisor/supervisor.go#L141

Instead, it should take in a config struct (this config can be read from disk in main). This makes it easier to unit test and easier to use as a library, since the config would not need to be written to disk in order to run the supervisor.

**Comment by crobert-1** [comment]
_Removed `needs triage` as this makes sense to me, was filed by a code owner, and another code owner responded with +1._

**Comment by crobert-1** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34597
