### ISSUE TITLE
New component: NTP receiver

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#34375]
### The purpose and use-cases of the new component

 This receiver retrieves clock offset from ntp server, respecting the TOS https://www.pool.ntp.org/tos.html.

It emits one metric, the offset in seconds from the NTP server.

### Example configuration for the component

```
receivers:
  ntp:
    host: 0.pool.ntp.org
```

### Telemetry data types supported

metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

atoulme

### Sponsor (optional)

@MovieStoreGuy

**Comment by MovieStoreGuy** [comment]
I am happy to sponsor this.

**Comment by KieranP** [comment]
Saw this got released in 0.112.0. We use OTP MFA, so clock sync is important to us. So just tried to use it, but getting this error when validating the config and trying to restart the collector:

```
error decoding 'receivers': unknown type: "ntp" for id: "ntp" (valid values: [prometheus_simple solace splunk_hec azuremonitor otlpjsonfile jmx oracledb postgresql rabbitmq splunkenterprise wavefront awsxray filestats bigip docker_stats k8s_cluster kubeletstats nop awsfirehose apachespark couchdb iis otelarrow signalfx skywalking statsd azureeventhub chrony haproxy jaeger memcached mongodbatlas opencensus podman_stats apache collectd vcenter purefb tcplog carbon prometheus sshcheck webhookevent pulsar riak azureblob expvar github kafkametrics receiver_creator snowflake otlp awscontainerinsightreceiver zipkin sapm windowsperfcounters hostmetrics kafka namedpipe k8sobjects loki sqlserver syslog snmp zookeeper cloudfoundry journald fluentforward httpcheck nsxt active_directory_ds awscloudwatch filelog googlecloudmonitoring nginx redis datadog elasticsearch flinkmetrics googlecloudpubsub influxdb mongodb purefa sqlquery aerospike awsecscontainermetrics udplog windowseventlog mysql cloudflare k8s_events])
```

Any ideas?

**Comment by atoulme** [comment]
It's not shipping in contrib yet. See https://github.com/open-telemetry/opentelemetry-collector-releases/pull/723

**Comment by atoulme** [comment]
Marking this issue as closed as the receiver has landed.
