### ISSUE TITLE
[cmd/opampsupervisor]: Move start logic into separate "Start" function

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#34380]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

NewSupervisor currently constructs the supervisor object and additionally starts the supervision processes (e.g. it bootstraps, starts the collector, connects to opamp server).

Instead, NewSupervisor should simply construct the Supervisor object, and the actual supervision process should happen on "Start". 

This would help with unit testing, where we currently manually construct supervisor objects, leading to failures in unit tests in some PRs where logic is updated to access a field that wasn't initialized properly.

**Comment by crobert-1** [comment]
_Removed `needs triage` as this makes sense to me and was filed by a code owner._

**Comment by odubajDT** [comment]
Hi, I would like to take this ticket @crobert-1

**Comment by BinaryFissionGames** [comment]
Resolved via #34509
