### ISSUE TITLE
Update components using configgrpc.ToDialOptions and confighttp.ToClient to the new interfaces.

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector-contrib#3438]
**Is your feature request related to a problem? Please describe.**

https://github.com/open-telemetry/opentelemetry-collector/pull/3128 in the core introduces changes to ToDialOptions and ToClient methods to use configuration from extensions to get hold of authentication configuration for clients. 

**Describe the solution you'd like**
- Fix the clients to use new interfaces
- Fix the corresponding tests 

**Additional context**

These exporters use the interfaces above. 

- dynatraceexporter
- sumologicexporter
- signalfxexporter
- lokiexporter
- extension/httpforwarder

**Comment by gramidt** [comment]
@pavankrish123 - Are you taking this or should I?

**Comment by gramidt** [comment]
Starting now.

**Comment by gramidt** [comment]
The final list of components:

- lokiexporter
- httpforwarderextension
- dynatraceexporter
- sumologicexporter
- influxdbexporter
- signalfxexporter
- f5cloudexporter
- awsprometheusremotewriteexporter
- humioexporter
- uptraceexporter
- nginxreceiver

**Comment by gramidt** [comment]
@pavankrish123 - Could we change the title to "Update components with Client Auth Extension changes" or something of that sort? This work impacted receivers, extensions, and exporters in this contrib repo.

**Comment by pavankrish123** [comment]
Done @gramidt - Let me know
