### ISSUE TITLE
jaeger_legacy receiver results in panic

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector-contrib#344]
**Describe the bug**

**Steps to reproduce**
Configure jaeger_legacy receiver

**What did you expect to see?**
Jaeger_legacy receiver working

**What did you see instead?**
panic: interface conversion: *jaegerlegacyreceiver.Factory is not component.ReceiverFactoryOld: missing method CreateMetricsReceiver

**What version did you use?**
v0.4.0

**What config did you use?**
receivers:

  jaeger_legacy:
    protocols:
      thrift_tchannel:
        endpoint: "0.0.0.0:14268"

**Comment by keitwb** [comment]
Jaeger legacy receiver no longer exists so this should be closed.
