### ISSUE TITLE
Reopen Pull Request #32500 

### ISSUE THREAD

**Issue by donald-cheung** [open-telemetry/opentelemetry-collector-contrib#34403]
### Component(s)

cmd/otelcontribcol, exporter/kafka, internal/kafka, receiver/kafka, receiver/kafkametrics

### Describe the issue you're reporting

Hello, we would like to reopen this Pull Request #32500 because the CLA is signed. Please take a look. Thank you very much.

**Comment by crobert-1** [comment]
I've reopened the PR, please mark as ready for review when it's ready 👍
