### ISSUE TITLE
Explicitly define processors that drop the client context

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#34453]
We have a few processors that drop client metadata (context), which potentially can carry important authentication data that exporters are supposed to use. 

It's important to clearly document the processors dropping the context. Can be done in metadata.yaml as another warning added to https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/standard-warnings.md#unsound-transformations.

### Action items

1. Identify processors dropping the context
2. Fix those that drop it unintentionally
3. Document those that drop it intentionally

**Comment by Neema-Joju** [comment]
Hi,
May I work on this issue? 
It would be my first time contributing to this issue.
Thanks
