### ISSUE TITLE
Enable Dependabot for Github Actions

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#3445]
Dependabot has support for updating the Github Actions we use on our CI. Since we are moving most of our CI to Github Actions it can be useful to enable it for this too.

_Originally posted by @mx-psi in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3432#issuecomment-845860777_

**Comment by andresbeckruiz** [comment]
I'd like to take on this issue.

cc: @alolita

**Comment by andresbeckruiz** [comment]
Quick question: in order to enable Dependabot for GitHub actions, I have to edit the dependabot.yml file. There is a comment on the top of the file that says "File generated by 'make gendependabot'; DO NOT EDIT." Is it okay to edit this file just for this issue?

**Comment by mx-psi** [comment]
> Is it okay to edit this file just for this issue?

No, you should modify the `make gendependabot` task to add this (and do so also on the `opentelemetry-collector` repo!)

> How often should the Dependabot check for new updates (weekly or daily)?

Since this should be rather easy to change I would just pick whichever frequency you think it's best (maybe weekly?) and we can discuss it on the PR
