### ISSUE TITLE
Exporting trace-derived metrics and logs for Grafana/Loki

### ISSUE THREAD

**Issue by LouisStAmour** [open-telemetry/opentelemetry-collector-contrib#3447]
**Is your feature request related to a problem? Please describe.**
Grafana is the first company I'm aware of to not automatically derive metrics and logs from traces sent via OTLP to Tempo.

I believe this is a valid use case for Collector to handle, but I'm open also to a new Grafana exporter that merges Prometheus publishing with Loki publishing and OTLP publishing. That said, it's also possible that a processor for traces could export logs and metrics separately, if exemplars could be exported separately from real-time metric values for Prometheus: https://github.com/open-telemetry/opentelemetry-specification/issues/1719

**Describe the solution you'd like**
A way for the Otel Collector to export spans as logs, or perhaps only span events as logs, and of exporting selected span durations or attributes as metrics such as histogram metrics while also sampling outliers or interesting traces for exemplars with trace IDs and reasons for sampling as labels and ensuring that exemplars don't get deleted when traces are sampled later (perhaps by labelling the span with an exemplar attribute). Ideally it would publish metrics separate from exemplars so that the FE ion on which traces to include as exemplars can be delayed but a metric such as real-time running average of span durations could be updated as soon as the next span arrives.

**Describe alternatives you've considered**
Alternatively, this kind of merging of traces into metrics and logs appears common in exporters that can support all three. The unique part here is that Grafana has adopted standard Prometheus and OTLP and as such, it seems strange to have an exporter potentially re-use another exporter's functions as an implementation. But perhaps not unheard of, since StackDriver tends to be a thin wrapper over OTLP anyway. But if we push for a less generic solution, you'll end up with a lot of exporters that are actually processing and deriving logs and metrics from span events, durations and exceptions.

**Additional context**
To see how Grafana views OpenTelemetry and its parts, have a look at this demo video: https://youtu.be/qVITI34ZFuk

**Comment by jpkrohling** [comment]
I just became aware of this issue. Some things might have changed, especially the metrics generation based on trace data. I'll have internal discussions about this one, but I would be grateful if you could share any up-to-date information you might have about this one.

**Comment by jpkrohling** [comment]
I'm closing this, as @bboreham pointed to resources showing how to achieve what the reporter of this issue requested. If there's still anything unclear, let me know and I'll reopen this.

**Comment by ewoolsey** [comment]
> I'm closing this, as @bboreham pointed to resources showing how to achieve what the reporter of this issue requested. If there's still anything unclear, let me know and I'll reopen this.

I think this issue is still relevant. Exporting trace Events as logs can be very useful in many circumstances. Having a single pipeline is great as it reduces the overhead of adding another layer, and it keeps things more consistent. The link from @bboreham to do this is broken, but I found the docs on Grafana and it can only be done with the Grafana Agent, which I would prefer not to run and just stick with the collector.

**Comment by ewoolsey** [comment]
Any chance we could get this reopened? I would love to see this feature.

**Comment by jpkrohling** [comment]
The collector way of doing this would be to have a "span to logs" connector, converting span events into logs. But at this point, there's no support in the Loki exporter to accept traces and export logs. I've forwarded the idea to the internal teams ( I'm quite sure I did it in the past already), as I think it does make sense to split this into our backends. I do encourage you to send this feature request over the appropriate channels though, including the Grafana community slack.

**Comment by ewoolsey** [comment]
Perhaps I'm misunderstanding, why does loki need to support this? Isn't the point that logs are generated from incoming spans, and then we can use any log exporter that we want? Wouldn't the connector do the translation so that the loki exporter can understand what it's looking at? Forgive me I have no idea how the internals work here.

**Comment by jpkrohling** [comment]
Sorry I wasn't clear before: I see two possible solutions here. One following the collector-way, which is what you alluded to, having a "spans to logs" connector. The other, which I understand was the initial request, is to get the Loki exporter to have this feature natively.
