### ISSUE TITLE
Support redaction of Metrics and Logs

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-collector-contrib#34479]
### Component(s)

processor/redaction

### Is your feature request related to a problem? Please describe.

Hi all, was wondering if there was a reason behind omitting Metrics (and at this point logs) from the scope of the redaction processor. We would like the ability to also scrub the other signals of sensitive data before making its way out of the pipeline.

### Describe the solution you'd like

Add support for metrics and logs to the redaction processor

**Comment by mx-psi** [comment]
I don't think there was any reason for this, if somebody wants to add support for this I would be supportive of it

**Comment by bacherfl** [comment]
If this is still available to work on, I would gladly look into this

**Comment by strawgate** [comment]
Is there any part of this request that isn't fulfilled by #34609  or can this be closed?

**Comment by mx-psi** [comment]
I think we can close this, thanks @strawgate !
