### ISSUE TITLE
Add googlecloudpubsubreceiver to contrib distribution

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#34480]
### Component(s)

receiver/googlecloudpubsub

### Is your feature request related to a problem? Please describe.

It is not used anywhere.

### Describe the solution you'd like

Add googlecloudpubsubreceiver to contrib distribution

**Comment by crobert-1** [comment]
I'm not sure I understand the request here. From what I can tell, the receiver referenced is already included in [contrib releases](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/73a756f723721dd5c9a21beae765670609ba40a0/distributions/otelcol-contrib/manifest.yaml#L143), and is marked as beta in its [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/googlecloudpubsubreceiver).

Can you clarify what you're requesting, or what I'm missing in this request?

**Comment by atoulme** [comment]
Weird. I have no remembrance of opening this bug. Closing.
