### ISSUE TITLE
Upgrade docker/moby dependancies to v27

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#34489]
We need to upgrade docker libraries. It cannot be done automatically. See
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33757
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34486

**Comment by TylerHelmuth** [comment]
As far as I can tell only the snmpreceiver's is still broken after bumping to testcontainers 0.34.0 and docker to v27.3.1 everywhere.
