### ISSUE TITLE
cannot load configuration: unknown processors type "k8s_tagger" for k8s_tagger

### ISSUE THREAD

**Issue by deepakkhetwal** [open-telemetry/opentelemetry-collector-contrib#3448]
**Describe the bug**

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
k8_tagger part as a processor. I am using collector operator in kubernetes. below is collector config deployed in kubernetes environment

**What did you see instead?**
cannot load configuration: unknown processors type "k8s_tagger" for k8s_tagger

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)
# Reference - https://github.com/open-telemetry/opentelemetry-operator
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: aks-otlp-collector
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      kafka/1:
        brokers:
          - 10.80.18.89:9092
        topic: otlp.traces
        encoding: jaeger_json
        protocol_version: 2.0.0
      jaeger/1:
        endpoint: simple-streaming-collector.keda-functions.svc.cluster.local:14250
        insecure: true
      zipkin/1:
        endpoint: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
        insecure: true
      

    service:
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [batch]
          exporters: [kafka/1]
        traces/2:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger/1]
        traces/3:
          receivers: [otlp]
          processors: [batch]
          exporters: [zipkin/1]

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by pramenn** [comment]
@deepakkhetwal which otel collector image are you using? If you are using `opentelemetry-collector` you might have to switch to `opentelemetry-collector-contrib`.

**Comment by dmitryax** [comment]
`k8s_tagger` was renamed to `k8sattributes`, please update your config https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5384
