### ISSUE TITLE
Add metric to record the number of aggregated log records

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-collector-contrib#34579]
### Component(s)

processor/logdedup

### Is your feature request related to a problem? Please describe.

It would be useful to have a metric to record the number of deduplicated logs.

### Describe the solution you'd like

Add a metric to track the number of deduplicated log records.

**Comment by crobert-1** [comment]
_Removing `needs triage` as this was filed by a code owner, and makes sense to me._
