### ISSUE TITLE
Update Span Kind string values to match collector's current values

### ISSUE THREAD

**Issue by awangc** [open-telemetry/opentelemetry-collector-contrib#34588]
### Component(s)

exporter/elasticsearch

### Describe the issue you're reporting

Currently elasticsearch exporter is encoding a span's `kind` using string values that do not match opentelemetry-collector's updated values (https://github.com/open-telemetry/opentelemetry-collector/pull/6250) and which have been deprecated according to https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottlspan 

It'd be great if we could have updated matching string values for `kind`

**Comment by crobert-1** [comment]
_Removing `needs triage` based on response from code owner._
