### ISSUE TITLE
Provide string representation for Span Status field

### ISSUE THREAD

**Issue by awangc** [open-telemetry/opentelemetry-collector-contrib#34590]
### Component(s)

exporter/elasticsearch

### Describe the issue you're reporting

Currently in encoding a span, for Span `Kind` the exporter is adopting a string representation, but the Span `Status` adopts an integer representation (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/elasticsearchexporter/model.go#L396-L397). It'd be great if we could adopt string representation for both, as it is more descriptive of the `status`.

**Comment by crobert-1** [comment]
_Removing `needs triage` based on response from code owner._
