### ISSUE TITLE
[receiver/azuremonitor] add support for AzureGermanCloud 

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#34614]
As listed [here](https://learn.microsoft.com/en-us/azure/azure-government/documentation-government-get-started-connect-with-cli), there's an AzureGermanCloud option as well. It would be good to add support for that.

              Would be good to add support for "AzureGermanCloud" as well, i'll open a follow up issue

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34402#discussion_r1714068375_

**Comment by mahadzaryab1** [comment]
@codeboten It looks like the go sdk doesn't have configuration for AzureGermanCloud (https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/cloud/cloud.go#L9-L22)

**Comment by codeboten** [comment]
Thanks for following up @mahadzaryab1, it looks like it's not needed as that's no longer supported by microsoft https://learn.microsoft.com/en-us/previous-versions/azure/germany/germany-welcome
