### ISSUE TITLE
[opampsupervisor] configure agent healthcheck port

### ISSUE THREAD

**Issue by dpaasman00** [open-telemetry/opentelemetry-collector-contrib#34643]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

I'd like to programmatically determine if the agent is healthy after being started by the supervisor without using an opamp connection to the supervisor. I want to do this by checking the agent's healthcheck extension endpoint. This would be particularly useful when updating an existing agent to be ran with the supervisor. Currently the port picked by the supervisor is non-deterministic making it difficult to determine which port should be targeted. I'd like to change this by making the healthcheck extension port configurable.

### Describe the solution you'd like

The port assigned to the agent's healthcheck extension should be configurable in the supervisor config. A new parameter in the `agent` configuration section, maybe even in `agent.description`. 

### Additional context

The relevant [code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/opampsupervisor/supervisor/supervisor.go#L1326-L1342) for picking a random port.

**Comment by dpaasman00** [comment]
I'd like to take this on if this is wanted

**Comment by tigrannajaryan** [comment]
>The port assigned to the agent's healthcheck extension should be configurable in the supervisor config.

Please add the motivation for this request to the description. It is not clear why this is needed. What problem is this solving? Why does the port need to be user selectable?

**Comment by dpaasman00** [comment]
@tigrannajaryan Updated the description, let me know if I need to add additional context.

**Comment by BinaryFissionGames** [comment]
I think we want the port to be configurable regardless of actually checking it outside the supervisor, grabbing a random port is error-prone in that:
1. Between generating the port and binding to the port, a different process may bind to that port
2. The supervisor may choose a random port that conflicts with another application that starts after the supervisor.

These are both rare scenarios, but with enough time + users I could imagine these things happening more than once.

**Comment by tigrannajaryan** [comment]
> 1. Between generating the port and binding to the port, a different process may bind to that port

This indeed can happen. A possible fix is instead of Supervisor choosing a port, the healthcheck extension can choose a port and the opamp extension will report this port to Supervisor via effective config. Not entirely clear how opamp extension will learn about the port number though.

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan Updated the description, let me know if I need to add additional context.

Thanks, looks good.
