### ISSUE TITLE
[exporter/elasticsearch] Double values encoded without decimal point causes wrong dynamic mapping

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector-contrib#34680]
### Component(s)

exporter/elasticsearch

## Description

In objmodel, a double value e.g. 1.0 is encoded as 1 in the resulting json, causes it to be dynamically mapped in Elasticsearch as a long instead of a double / float.

## Steps to Reproduce

1. Send 1.0 to Elasticsearch to a field with dynamic mapping
2. Query it back
3. Check resulting mapping

## Expected Result

Getting 1.0 back, mapped as double.

## Actual Result

Get 1 back, mapped as long

### Collector version

v0.107.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
_Removing `needs triage` as this was filed by a code owner._
