### ISSUE TITLE
Specify connection name for the RabbitMQ exporter from config

### ISSUE THREAD

**Issue by snichme** [open-telemetry/opentelemetry-collector-contrib#34681]
### Component(s)

exporter/rabbitmq

### Is your feature request related to a problem? Please describe.

Having a lot of agents connecting to the same RabbitMQ server makes it difficult to detect which connection might be having issue and from where the connection comes from.

### Describe the solution you'd like

Be able to specify the name of the connection in the config for the agent.

**Comment by crobert-1** [comment]
_Removing `needs triage` as code owner has approved PR for this change`._
