### ISSUE TITLE
Remove internal/buildscripts/packaging/

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#34748]
### Describe the issue you're reporting

We have internal/buildscripts/packaging/, which was used in the past when we used to generate the binaries from this repository. It's still there, and it's unclear what's the purpose.

Unless we have a clear purpose, I'd propose to remove it, because:

1. its Dockerfile's have vulnerabilities (ie, this module requires active maintenance)
2. it's spending CI cycles for... nothing? that's bad for the environment ;-)

**Comment by atoulme** [comment]
I agree that it should be removed, especially if the CI coverage it offers is best provided elsewhere already. Do we have good test coverage of the `-releases` artifacts as well?

**Comment by jpkrohling** [comment]
I believe so. In fact, I think I just caught this work mid-flight: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/604

@mowies, do you plan on removing the buildscripts from this repository?

**Comment by mowies** [comment]
I did and I have a PR open already with some ongoing discussions: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34372

**Comment by jpkrohling** [comment]
Thank you for the confirmation! I linked this to the PR, so that it gets closed once a resolution is found.
