### ISSUE TITLE
[extension/opamp] Make the polling interval configurable for HTTP client

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-collector-contrib#34749]
### Component(s)

extension/opamp

### Is your feature request related to a problem? Please describe.

Currently, the OpAMP extension's HTTP client is using the default 30 second interval and it cannot be configured. I would like to use a bigger interval for polling. The OpAMP specification states that this should be configurable on the client, as well (see https://opentelemetry.io/docs/specs/opamp/#plain-http-transport).

### Describe the solution you'd like

Add a configuration option for polling interval and apply it to the HTTP client.

**Comment by matej-g** [comment]
Assuming there are no objections, I prepared a PR for this - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34811. Thanks.

**Comment by haoqixu** [comment]
I believe this issue has been resolved, and we can close it now.

**Comment by tigrannajaryan** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34811
