### ISSUE TITLE
[cmd/opampsupervisor] Add support for running as a Windows service

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#34774]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

To run a binary as a windows service, it needs to handle the control signals from the Windows service manager.

The supervisor does not currently implement what is needed to run as a Windows service. See https://pkg.go.dev/golang.org/x/sys/windows/svc#Run

### Describe the solution you'd like

Implement handling the Windows service signals. See https://github.com/open-telemetry/opentelemetry-collector/blob/main/otelcol/collector_windows.go#L36 for how the collector implements this.

**Comment by dpaasman00** [comment]
I can take this task on!
