### ISSUE TITLE
[exporter/elasticsearch] Support exponential histogram

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector-contrib#34813]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

There is no exponential histogram support in elasticsearch exporter now. It means exponential histograms are ignored. As Elasticsearch does not support native exponential histogram at the moment, exponential histograms in opentelemetry should be converted to T-digest and indexed.

### Describe the solution you'd like

Convert to exponential histograms to Elasticsearch compatible format and index them.

**Comment by crobert-1** [comment]
_This makes sense to me, and the issue was filed by code owner. Removing `needs triage`._
