### ISSUE TITLE
[processor/deltatocumulative]: investigate possible int overflows in `internal/data/expo`

### ISSUE THREAD

**Issue by sh0rez** [open-telemetry/opentelemetry-collector-contrib#34828]
### Component(s)

processor/deltatocumulative

### What happened?

`gosec` linter started flagging possible integer overflow errors in recent versions:

```
deltatocumulativeprocessor/internal/data/expo/expotest/bins.go:45:25: G115: integer overflow conversion int -> int32 (gosec)
	buckets.SetOffset(int32(start - 3))
	                       ^
deltatocumulativeprocessor/internal/data/expo/expotest/bins.go:62:36: G115: integer overflow conversion int -> int32 (gosec)
			bs.SetOffset(bs.Offset() + int32(idx))
			                                ^
deltatocumulativeprocessor/internal/data/expo/expotest/histogram.go:57:19: G115: integer overflow conversion int -> int32 (gosec)
	dp.SetScale(int32(hist.Scale))
```

while these are not necessarily real security implications, we must investigate

### Collector version

bddc8c25e7294a4aa81c0ae4a4cb7e657766599d

**Comment by odubajDT** [comment]
I was not able to reproduce the problem locally with the current state of main branch and with [gosec](https://github.com/securego/gosec). Are you able to reproduce it with `gosec ./...` or did you use some special parameters?

Thanks!
