### ISSUE TITLE
Documentation for chrony receiver incorrectly references `address`

### ISSUE THREAD

**Issue by twistypigeon** [open-telemetry/opentelemetry-collector-contrib#34839]
### Component(s)

receiver/chrony

## Description
Documentation examples show the `address` key being used but this is no longer a valid key. The correct key is `endpoint`

## Steps to Reproduce
Use the sample config and run a chrony receiver on a collector

## Expected Result
The collector to start

## Actual Result
The collector errors with the following:

```
 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'receivers': error reading configuration for "chrony": 1 error(s) decoding:

* '' has invalid keys: address
```

### Collector version

v0.102.1

## Environment
OS: Ubuntu 20.04

### OpenTelemetry Collector configuration

```yaml
receivers:
  chrony:
    address: unix:///var/run/chrony/chronyd.sock

service:
  pipelines:
    metrics:
      receivers:
        - chrony
      processors:
      exporters:
```

### Log output

```shell
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'receivers': error reading configuration for "chrony": 1 error(s) decoding:

* '' has invalid keys: address
2024/08/24 16:50:19 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'receivers': error reading configuration for "chrony": 1 error(s) decoding:

* '' has invalid keys: address
```

### Additional context

This appears to be a simple documentation update: ~address:~ endpoint:

**Comment by crobert-1** [comment]
Thanks for filing @twistypigeon, agreed this is incorrect. I've opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34846 to fix it.
