### ISSUE TITLE
Windows Services receiver

### ISSUE THREAD

**Issue by syron** [open-telemetry/opentelemetry-collector-contrib#34887]
### Is your feature request related to a problem? Please describe.

In order for us to get an entire overview of whats going on on our windows environments, we need to get the state of windows services.

### Describe the solution you'd like

Metrics about the windows services would be great. The idea is to create a simple receiver that continuously checks the services using golang.org/x/sys/windows/svc/mgr and creates metrics for each of the services. If a windows service is disabled, running, stopped or anything else, the metric will show what windows service this is about.

### Describe alternatives you've considered

My alternative is to develop a dotnet service using otel library that pushes metrics about the Windows Services to an otel endpoint. My alternative solution could provide a way to collect that information even about remote servers reachable from the server running on a windows machine within the same network.

**Comment by pjanotti** [comment]
This is basically the same request as #31377

**Comment by syron** [comment]
That is true, my bad. Didn't realize there was a similar one. didn't come up when I searched. Will close this one.
