### ISSUE TITLE
splunkhec receiver memory leak

### ISSUE THREAD

**Issue by clheikes** [open-telemetry/opentelemetry-collector-contrib#34886]
### Component(s)

receiver/splunkhec

## Description
We've uncovered what appears to be a memory leak in the splunkhec receiver that surfaced around version 0.102.0. We run the the receiver in both a metric and log pipeline. We are not sending logs using hec yet the collector is holding 2gb of heap under (*ObsReport).StartLogsOp (obsreport.go:L#95).
## Steps to Reproduce
splunkhec receiver in logs and metrics pipeline 

## Expected Result
Memory remains stable

## Actual Result
Memory grows until we trigger the memory limiter then the collector gc's

![35C08CF1-ECDD-4999-AFE6-21BEA453619A_1_105_c](https://github.com/user-attachments/assets/c86fc95d-105a-44ed-b7fc-703a4ca23346)

![49D534B1-3EF8-4949-B671-7B4C66E8E1E7](https://github.com/user-attachments/assets/67813c35-790c-47a5-bb20-7f79e6857a1f)

### Collector version

0.106.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Additional context

When we remove the splunhecreceiver from the logs pipeline the memory is stable. At the moment we only have applications sending metrics to the hec receiver in the impacted clusters.

**Comment by brettplarson** [comment]
+1

**Comment by atoulme** [comment]
Thanks for the report, the code is pure spaghetti, sorry. I have a fix out for review: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34911

Ideally we should have tests that look for this type of leaks - might be good for us to have generated tests for all components that do that down the road.
