### ISSUE TITLE
[processor/transform] Tracing taking more CPU resources than expected

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#34890]
### Component(s)

processor/transform

## Description

Not sure if "bug" is the right label for this, but the tracing component for the transform processor seems to be taking a significant amount of process time in high throughput scenarios. 

We had a report of high CPU usage on a collector (monitoring ~10k files), and we got a profile for it. One interesting insight to come out of the profile is that ~40% of the path for the transform processor was taken by tracer::Start. 

<img width="596" alt="Screenshot 2024-08-27 at 4 16 03 PM" src="https://github.com/user-attachments/assets/1154defa-2f00-42cf-9be8-4f0615fc0480">

That seems like a lot of resource spent there, and this is a scenario where the collector is not configured to emit traces at all, so this effectively does nothing. I'm wondering if this is something we can optimize? I haven't looked deep enough into it just yet to understand the pitfalls.

### Collector version

0.105.0

**Comment by BinaryFissionGames** [comment]
OK, so I dived into the code a bit, and it looks like there's a span created for each statement. So if I execute, say, 10 statements, I'll get 10 spans for each log record flowing through the transform processor (this is actually for everywhere using OTTL statements, not just in the transform processor AFAICT).

I think it would be nice to be able to dial that back a bit, maybe through some config setting. It just seems like a lot of tracing for the smaller contexts (datapoint, spanevent, logrecord), and eats up a decent amount of CPU.

**Comment by TylerHelmuth** [comment]
@codeboten and I were looking at this for https://github.com/open-telemetry/opentelemetry-collector/issues/10858. The tracing is also consuming a lot of memory. 

The only thing we've been able to identify is that the CT's that is passed into the SDK is very large. But it isn't clear to me why the OTEL Go SDK is under performing in this scenario.

**Comment by TylerHelmuth** [comment]
Also, scaling back the per-statement spans won't help much, as most of the performance hit is from the first, outer span based on our testing.

**Comment by BinaryFissionGames** [comment]
Thanks for pointing me to that other issue. I'll probably end up investigating more myself tomorrow.
