### ISSUE TITLE
[extension/filestorage] - Provide an option to the user to create a directory for them

### ISSUE THREAD

**Issue by VihasMakwana** [open-telemetry/opentelemetry-collector-contrib#34939]
### Component(s)

extension/storage/filestorage

### Is your feature request related to a problem? Please describe.

When using the `filelog` receiver with persistence enabled, I need to ensure that the directory exists before starting the collector; otherwise, it will throw an error. 
It would be a great help if collector could automate this part for me.

### Describe the solution you'd like

It would be convenient if the `file_storage` option had a setting that, when enabled, would automatically create the directory for you.
We can name the option `auto_create_directory` or `create_directory` and set it to `false` by default (existing behaviour), but if the user wants the collector to handle the directory creation, they can just turn this option on.

**Comment by andrzej-stencel** [comment]
I think this would be a useful feature.

What would be the permissions on the created directory? Would `0750` (`rwxr-x---`) be a good default? Do we need to let the user customize the permissions?

**Comment by VihasMakwana** [comment]
@andrzej-stencel I think 0750 is a good default.

> Do we need to let the user customize the permissions?

I think it would be sufficient to document that the default directory creation mode is `0750`.

**Comment by andrzej-stencel** [comment]
> > Do we need to let the user customize the permissions?
> 
> I think it would be sufficient to document that the default directory creation mode is `0750`.

Ok let's start with that. 👍

**Comment by VihasMakwana** [comment]
@andrzej-stencel can you assign this to me (or should we wait for @djaglowski to be back from vacation)?

**Comment by Frapschen** [comment]
@VihasMakwana assigned

**Comment by VihasMakwana** [comment]
Addressed via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34985. Closing.
