### ISSUE TITLE
[receiver/filelog] Receiver name clarification

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#34943]
### Component(s)

receiver/filelog

### Describe the issue you're reporting

The receiver's title is `Filelog Receiver`, but I assume it should split `File` and `Log` into two words, `File Log Receiver`. It's a simple change to post a PR to update the README title, but I wanted to clarify first to make sure I'm not missing something.

For consistency, I see the `filestatsreceiver` has a title of `File Stats Receiver`, and other similarly named receivers also include a space in their title.

There's also a reference in the file log receiver's README to itself as the `File Log Receiver`.

The reason I'm not opening a PR to change it yet is I see a lot of third-party references to the `Filelog receiver` so I don't want to cause any unnecessary confusion here.

**Comment by rogercoll** [comment]
I agree, the `filelog` receiver parses files which might contain logs, but it is not tied to any specific format named `filelog` as the `syslog` receiver is. In my opinion, `File Log Receiver` makes it more clear that is a generic log format solution.
