### ISSUE TITLE
[receiver/kubeletstats] how to get kuberbetes metrics as percent-based  

### ISSUE THREAD

**Issue by NamanGajjar26** [open-telemetry/opentelemetry-collector-contrib#34952]
### Component(s)

receiver/kubeletstats

### Describe the issue you're reporting

hello

opentelemetry in configure kubeletstats in receiver there are get pod cpu,memory (usage) in float  i want to get in percent-based  
how to get metrics percent-based 
opentelemetry in configure like below 

          `kubeletstats:      
                insecure_skip_verify: true  
                collection_interval: 30s     
                metrics:
                  container.cpu.time:
                    enabled: true
                  container.cpu.utilization:
                    enabled: true
                  container.memory.available:
                    enabled: true
                  container.memory.usage:
                    enabled: true
                  k8s.node.cpu.time:
                    enabled: true
                  k8s.node.cpu.usage:
                    enabled: true
                  k8s.node.memory.available:
                    enabled: true
                  k8s.node.memory.usage:
                    enabled: true
                  k8s.pod.cpu.time:
                    enabled: true
                  k8s.pod.cpu.usage:
                    enabled: true        
                  k8s.pod.memory.available:
                    enabled: true
                  k8s.pod.memory.usage:
                    enabled: true 
                  k8s.container.memory_limit_utilization:
                    enabled: true 
                  k8s.container.memory_request_utilization:
                    enabled: true
                  k8s.container.memory.node.utilization:
                    enabled: true
                  k8s.container.cpu_request_utilization:
                    enabled: true
                  k8s.container.cpu_limit_utilization:
                    enabled: true
                  k8s.container.cpu.node.utilization:
                    enabled: true
                  k8s.pod.memory_request_utilization:
                    enabled: true
                  k8s.pod.memory_limit_utilization:
                    enabled: true
                  k8s.pod.memory.node.utilization:
                    enabled: true
                  k8s.pod.cpu_request_utilization:
                    enabled: true
                  k8s.pod.cpu_limit_utilization:
                    enabled: true  `

**Comment by atoulme** [comment]
You typically capture metrics as is, and make computations at query time by dividing one by the other.
