### ISSUE TITLE
k8s_tagger not working

### ISSUE THREAD

**Issue by deepakkhetwal** [open-telemetry/opentelemetry-collector-contrib#3499]
**Describe the bug**
I have added k8s_tagger as a processor before my otlp receiver logs could be exported to jaeger/zipking and kafka. I am expecting processor to add kubernetes host/pod information before being exported to destinations. But it's not happening. Please advise if I am missing anything and what's the best way to debug this processor to see what it is doing.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: aks-otlp-collector
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-contrib
  config: |
    receivers:
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu:
          memory:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      k8s_tagger:
        passthrough: true
    exporters:
      kafka/1:
        brokers:
          - 10.80.18.89:9092
        topic: otlp.traces
        encoding: jaeger_json
        protocol_version: 2.0.0
      jaeger/1:
        endpoint: simple-streaming-collector.keda-functions.svc.cluster.local:14250
        insecure: true
      zipkin/1:
        endpoint: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
        insecure: true
    service:
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [k8s_tagger]
          exporters: [kafka/1]
        traces/2:
          receivers: [otlp]
          processors: [k8s_tagger]
          exporters: [jaeger/1]
        traces/3:
          receivers: [otlp]
          processors: [k8s_tagger]
          exporters: [zipkin/1]

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by chaitanyaphalak** [comment]
Hey @deepakkhetwal your config is incorrect. Please look at this example and try again 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sprocessor/testdata/config.yaml
Thanks

**Comment by dmitryax** [comment]
As @chaitanyaphalak mentioned, configuration of k8s_tagger (now k8sattributes) processor is incorrect. Please use the provided example instead
