### ISSUE TITLE
Add ability to build multiple binaries from this repo

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector-contrib#35]
We should be able to build multiple binaries of OpenTelemetry Contrib Collector from this repository. The binaries would bundle a different set of components, use different libraries or protocols etc.

In future, we could even have a form on the OpenTelemetry website that would allow users to check which components they want and generate a custom build for them. For now we just need the ability to generate more than one builds i.e, add another `cmd/<buildName>` directory and the tooling to support it.

**Comment by mx-psi** [comment]
@jpkrohling should this be closed, given that we have opentelemetry-collector-releases?

**Comment by jpkrohling** [comment]
Yes
