### ISSUE TITLE
[exporter/elasticsearch] Workaround TSDB limitation on array dimension fields

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector-contrib#35004]
### Component(s)

exporter/elasticsearch

## Description

Elasticsearch TSDB does not accept dimension fields which are arrays. It will result in ingestion failures. 

We have [a related fix](https://github.com/elastic/elasticsearch/pull/112345) for non-TSDB index mode, but TSDB index mode still has this limitation.

As all attributes are dimensions, and that the exporter currently emits attribute values which are arrays as actual arrays in the document, it will be affected by this TSDB limitation. Elasticsearch exporter should workaround this limitation specifically for metrics.

## Steps to Reproduce

Send an attribute with array value to an ES index that uses TSDB index mode

## Expected Result

No errors

## Actual Result

Fail to index

```
2024-09-04T14:55:22.350+0100    error   elasticsearchexporter@v0.108.0/bulkindexer.go:332       failed to index document        {"kind": "exporter", "data_type": "metrics", "name": "elasticsearch", "index": "metrics-generic.otel-default", "error.type": "illegal_argument_exception", "error.reason": "Error extracting routing: Routing values must be strings but found [START_ARRAY]"}
```

### Collector version

v0.108.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
_This issue was filed by a code owner, and generally makes sense to me. Removing `needs triage`._
