### ISSUE TITLE
[stanza/fileconsumer] unit fail 

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#35018]
### Component(s)

pkg/stanza/fileconsumer

## Description
Unit test fails. See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10705129981/job/29679830691?pr=34999 

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by djaglowski** [comment]
I believe this was resolved by #35012. I pulled in the fix on #34999 and it appears to have passed the relevant checks.
