### ISSUE TITLE
New component: Demo Logs receiver 

### ISSUE THREAD

**Issue by legendary-acp** [open-telemetry/opentelemetry-collector-contrib#35024]
### The purpose and use-cases of the new component

While debugging data path from collector to desired location we sometime need some random data that generate some random logs generated for debugging purpose. It would be great if we create a dummy log receiver within collector which will solve our use case.

### Example configuration for the component

```
receivers:
  dummyLogs:
    body: "This is a demo log"
```

This is very vague overview. Can be changed in future depending on usecase.

### Telemetry data types supported

Primarily for logs but later can be extended to traces and metrics.

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

**Comment by legendary-acp** [comment]
I would love to take this up if this sounds interesting

**Comment by atoulme** [comment]
Thank you for submitting this proposal!

We already have telemetrygen and the otlpjsonfilereceiver to produce data according to a rate and signal, or a fixed static file. Would you please investigate if those provide enough coverage for your use case?

Only an approver or maintainer may be a sponsor of new components. Please review https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components for more information.

**Comment by legendary-acp** [comment]
telemetrygen is exactly my use case. But I was wondering instead of making it a separate command can't we convert it into receiver component? Something like fluentbit [dummy input](https://docs.fluentbit.io/manual/pipeline/inputs/dummy) does.
