### ISSUE TITLE
[exporter/splunkhecexporter] Support separate metric index for hec exporter

### ISSUE THREAD

**Issue by spiffyy99** [open-telemetry/opentelemetry-collector-contrib#35039]
### Component(s)

exporter/splunkhec

### Is your feature request related to a problem? Please describe.

Users of `splunkhecexporter` may be sending both logs and metrics data at the same time, so the config should provide a separate default metrics index to support this, since metrics and logs indexes support different data.

### Describe the solution you'd like

To avoid regressions in existing clients, metrics index can be configured as such:
- Config introduces an extra optional param `MetricsIndex`
- Have an additional config flag `UseMetricsIndex`. If this is set, metrics exporter will set the default index to be `MetricsIndex` for metrics data.

**Comment by atoulme** [comment]
It doesn't look to me like we would need a `UseMetricsIndex` field. We can just check if MetricsIndex is set.

If MetricsIndex is set, we use it when converting metrics to splunk events. If it is not set, we should default back to the Index config field to preserve the current behavior.

**Comment by spiffyy99** [comment]
> It doesn't look to me like we would need a `UseMetricsIndex` field. We can just check if MetricsIndex is set.
> 
> If MetricsIndex is set, we use it when converting metrics to splunk events. If it is not set, we should default back to the Index config field to preserve the current behavior.

good point. that's fine as well.

**Comment by crobert-1** [comment]
_Removing `needs triaged` based on response from code owner._

**Comment by atoulme** [comment]
@spiffyy99 are you still working on this?

**Comment by spiffyy99** [comment]
No, we decided to go with a different approach. Lets close this out.
