### ISSUE TITLE
[receiver/hostmetrics] Filesystem scraper doesn't respect env var when set

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#35043]
### What happened?

When setting the environment variable HOST_PROC_MOUNTINFO, the filesystem scraper will read mount points from the proper location, but will still apply the root_path prefix to each mount point to read its information.

Instead, when the env var HOST_PROC_MOUNTINFO is set, we should not prefix the mount point with the root_path prefix.

### Collector version

v0.108.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by rogercoll** [comment]
Is there any documentation about the HOST_PROC_MOUNTINFO env variable? I couldn't find any in the scraper's README https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/documentation.md but on the internal gopsutil package

Should we create a followup documentation issue?
