### ISSUE TITLE
Add `pmetrictest.IgnoreMetricsFloatPrecision(),

### ISSUE THREAD

**Issue by greatestusername** [open-telemetry/opentelemetry-collector-contrib#35060]
### Component(s)

pkg/pdatatest

### Is your feature request related to a problem? Please describe.

I'm currently writing a connector for summing attribute values into metrics values. Due to needing to use floats (some values may be decimals) I'm running into issues with float precision during testing with `CompareMetrics`. This has cropped up while writing tests for the main summing logic of the component when we expect something like `23.9` and get back `23.899999`. 

### Describe the solution you'd like

I'd like to create another optional flag for `pmetrictest` to allow ignoring float discrepancies below a certain threshold. Say an expected `23.9` is actually coming back as `23.899999` this slight difference should be ignorable and countable as a pass.

This would be an optional flag similar to `pmetrictest.IgnoreMetricsOrder()` and the like.

### Describe alternatives you've considered

This is the best option I've been able to come up with.

### Additional context

PR where this issue cropped up:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34797

The insidious part of this is that `CompareMetrics` doesn't seem to be reporting the discrepancy properly. My test output will look like this:
```
double value doesn't match expected: 23.900000, actual: 23.900000
```
But if I output the value in question to console it is `23.899999`

Currently I've added a rounding function to get around this temporarily, get tests passing, and get my logic reviewed.

**Comment by djaglowski** [comment]
Makes sense to me. Want to make the pr @greatestusername?

**Comment by greatestusername** [comment]
Yup! will do! Thanks!

**Comment by greatestusername** [comment]
PR is merged!
