### ISSUE TITLE
[ottl] ParseTime should pre-convert from strptime to gotime format

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#35078]
### Component(s)

pkg/ottl

### Describe the issue you're reporting

Currently, the `Time` function runs [`timeutils.ParseStrptime`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b3e952f46a686953d298ba9de880057d060722cf/pkg/ottl/ottlfuncs/func_time.go#L56) for every string that needs to be parsed as a `time.Time`. This in turn calls `ctimefmt.ToNative`, which is doing a deterministic string replacement operation.

The OTTL function should instead call `timeutils.StrptimeToGotime` once at collector startup, and then call `timeutils.ParseGotime` during normal operations.

**Comment by djaglowski** [comment]
For context, `ToNative` was observed to be wasting ~5% of compute on a real world configuration.

![image](https://github.com/user-attachments/assets/5da52a9c-cfb2-4293-b1bc-101e7a7d2289)

**Comment by TylerHelmuth** [comment]
@djaglowski I'm interested in fixing this performance issue, but I don't see any connection to `timeutils.ParseStrptime` from [ParseJSON](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/ottlfuncs/func_parse_json.go).

I only see `timeutils.ParseStrptime` called from the `Time` converter. I suspect your proposal could be implemented there.

**Comment by djaglowski** [comment]
Sorry,  I got some wires crossed looking at several issues at once. `ParseJSON` is not the function in question. It should read `Time` instead. I've now corrected the wording above.
