### ISSUE TITLE
[pkg/ottl] Enhance ParseXML function with intuitive parse format and add MarshalXML function to convert parsed output back to XML

### ISSUE THREAD

**Issue by shazlehu** [open-telemetry/opentelemetry-collector-contrib#35076]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

The current implementation of the ParseXML produces output that is difficult for users to manipulate, particularly when the XML is complicated. The current design loses the sense of key:value pairs which is helpful for understanding the data, and, more importantly, parses the XML into arrays, which are difficult to manipulate in OTTL, and don't provide a stable path that can be used to access the data.

### Describe the solution you'd like

[PR 35210](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35210) has a proposed new parsing version that maintains backward compatibility with the current implementation. (Updated to point to PR off observIQ repo)

**Comment by djaglowski** [comment]
For context, discussion about the current design can be found on #31133.

**Comment by djaglowski** [comment]
I'm going to make a few comments on #35210 but I think it's going to be worth bringing the discussion back here to focus on proposed changes to the format.
