### ISSUE TITLE
`hec_metadata_to_otel_attrs` option is confusing on exporter/splunkhec

### ISSUE THREAD

**Issue by bderrly** [open-telemetry/opentelemetry-collector-contrib#35092]
### Component(s)

exporter/splunkhec

### Describe the issue you're reporting

The config option `hec_metadata_to_otel_attrs` is confusing when used with the splunkhec _exporter_ as the actual effect is the opposite, i.e. taking otel attributes and using them as HEC metadata when sending to some destination.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/bd66cebb0a7848c5e38a8d29a26532ee2c5a1d91/exporter/splunkhecexporter/config.go#L120

**Comment by atoulme** [comment]
Would you like to offer a PR to fix the naming?

**Comment by bderrly** [comment]
I could do that. Before I set out to do it, is there agreement that the naming is confusing enough that we should change it?

**Comment by atoulme** [comment]
Yes, I think so. As you change the name, we will want to mark the current field deprecated and keep it around for a little while, and introduce a new field. Best to discuss the name of the new field in this issue. I guess it should be `otel_attrs_to_hec_metadata`?

**Comment by bderrly** [comment]
> I guess it should be `otel_attrs_to_hec_metadata`?

That is what I was thinking.
