### ISSUE TITLE
Make Headers Setter extension context default value configurable

### ISSUE THREAD

**Issue by kyo-ke** [open-telemetry/opentelemetry-collector-contrib#35151]
### Is your feature request related to a problem? Please describe.

We are pushing traces to Tempo via opentelemetry collector.
when we push trace to multitenant Tempo we need to handle X-Scope-OrgID header using Headers Setter extension.
in current version if user do **not specify X-Scope-OrgID this extension automatically use "" as value**.(Default value is hardcoded)
and sometimes we want to use specific tenant to store user's trace with no X-Scope-OrgID

problem is we cannot configure default value when specified key is missing.
(https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/headerssetterextension/internal/source/context.go#L24) 

### Describe the solution you'd like

Make default value configurable for Headers Setter extension's context functionality.
we will create PR for this.

**Comment by crobert-1** [comment]
Hello @kyo-ke, thanks for filing this issue! Is this the same problem as reported in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34412? If so, it would be preferable to only have one issue open for a given issue, but let me know if I'm missing something here 👍

**Comment by kyo-ke** [comment]
yes this is same with #34412.
will close this issue.
I created PR for this. Is it ok to keep my PR open with changing issue number in changelog?

**Comment by crobert-1** [comment]
Thanks @kyo-ke!

Closing in favor of #34412
