### ISSUE TITLE
[CI] Avoid toolchain updates on `make gotidy` runs

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#35160]
### Component(s)

cmd/otelcontribcol, cmd/oteltestbedcol

### Describe the issue you're reporting

Recent Go versions added the [`toolchain` directive](https://go.dev/ref/mod#go-mod-file-toolchain) to indicate the Go version suggested for use. 

This is annoying in that if running something like `make gotidy` locally the directive will be updated to reflect the local Go version, but the local Go version may not match the CI Go version on the specific job that checks this.

We could get the correct Go version from CI and manually `sed` for reverting any updates to the `toolchain` directives.

**Comment by Ali-Alnosairi** [comment]
@mx-psi  , Can I take this one ?

**Comment by mx-psi** [comment]
Sure!

**Comment by Ali-Alnosairi** [comment]
@mx-psi 
would you please guide me how to setup the environment so I can reproduce it then fix it .
I am new to this repo

**Comment by mowies** [comment]
this should be fixed with #34844

**Comment by mowies** [comment]
@mx-psi I created https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35490 that somewhat also fixes this

**Comment by mowies** [comment]
@mx-psi i think this should be fixed by #35490

**Comment by mx-psi** [comment]
Right, thanks!!
