### ISSUE TITLE
Single Makefile target for all CI checks

### ISSUE THREAD

**Issue by ankitpatel96** [open-telemetry/opentelemetry-collector-contrib#35264]
### Is your feature request related to a problem? Please describe.

Hi!
When I am developing on a branch, I'd find it very helpful to have a single Make target / script to run to run every CI check - everything from multimod to generate to unit tests.  Often I forget to run one of our many linters / generators, and it takes extra roundtrips to fix them.  I'd prefer to run into the problem locally!

### Describe the solution you'd like

A single Make target that runs all the different linters / checks / tests.

**Comment by mowies** [comment]
Isn't this covered by https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/Makefile#L545-L558 ?

**Comment by ankitpatel96** [comment]
.... yes that seems like it would do it.  completely missed it lol.  Thanks!!!
