### ISSUE TITLE
Splunk Hec Receiver - Memory Leak (Cont of #34886)

### ISSUE THREAD

**Issue by brettplarson** [open-telemetry/opentelemetry-collector-contrib#35294]
### Component(s)

receiver/splunkhec

## Description
We are still seeing an issue with the collector memory after upgrading to 0.109.0 with the fix. The behavior changed and we are now seeing more memory in the stack vs heap. Although the heap still grows slowly over time. Similar to before, removing the hec receiver from the logs pipeline gets rid of the issue. This is a test cluster where I can reproduce this sending metrics to the hec receiver.
- i'm wondering if this is still a continuation of the issue noted in #34886
![image](https://github.com/user-attachments/assets/23b3ee05-23a7-49b5-9cc3-e232f79ee588)

![image](https://github.com/user-attachments/assets/c20a0632-38db-4eff-8191-4d3285376728)

![image](https://github.com/user-attachments/assets/07b6e1f7-a173-4686-b58a-a72612de2528)

One clue is that this is all under startlogop - the memory in startmetricsop seems normal - perhaps the way hec events are processed, as events first, is causing these to never end. forgive my speculation :) 

## Steps to Reproduce
send a ton of metrics to a hec endpoint and profile the memory.

## Expected Result
memory should not be held in this way

### Collector version

0.109.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Additional context

We opened splunk case 3554107 as well.

**Comment by brettplarson** [comment]
Just bumping this. Thank you!

**Comment by atoulme** [comment]
looking into it now.
