### ISSUE TITLE
Nominate @pjanotti as triager

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#35303]
@pjanotti has been very active as a contributor to this repository and needs help to turn on the label "Run Windows" on PRs. Paulo is a former maintainer of the collector who is finding his way back. I would like to nominate him to become a triager of the project to unblock him in his efforts.

**Comment by pjanotti** [comment]
This privilege will be helpful given that I'm providing [tier 2 support for `windows/amd64`](https://github.com/open-telemetry/opentelemetry-collector/blob/1edd31145fb83d321312cc12cb8a5bf33e329bde/docs/platform-support.md#tier-2--secondary-support) and having being paying special attention to Windows related issues, having reviewed and submitted many related PRs.

**Comment by djaglowski** [comment]
I fully support this.
