### ISSUE TITLE
How to send 'A' collector logs to collector 'B' for self monitoring via 'service::telemetry::logs'

### ISSUE THREAD

**Issue by vaibhhavv** [open-telemetry/opentelemetry-collector-contrib#35308]
## Description

I have two collectors 'A' & 'B'.
Use case is I want to send logs of collector 'A' to collector 'B' for self-monitoring, with the help of the otel pipelines itself.
I am little stuck as I have enabled the telemetry block for logs by the below configuration.

However, after enabling it I am still not getting any logs on collector 'B'. 

```
service:
  telemetry:
    logs:
        level: debug
```
`service::telemetry::logs` documentation is very limited and I did not get any idea how to enable this feature.
Could some one help out here?
1. For the particular use case, this is the correct approach? If not, could you suggest the correct one
2. If yes, could you add what part I am missing here.

### Collector version

0.93.3

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by bacherfl** [comment]
Hi @vaibhhavv - I was also just looking into this and it seems like while for [metrics](https://opentelemetry.io/docs/collector/internal-telemetry/#configure-internal-metrics) there is the possibility to directly send them to another collector via `otlp`, the self monitoring logs only provide the option to store the logs in a file, using the `output_paths` config option (see https://opentelemetry.io/docs/collector/internal-telemetry/#configure-internal-logs) and https://github.com/open-telemetry/opentelemetry-collector/blob/1e29f99536c300a877454b52ac372a91a6c05344/service/telemetry/config.go#L87

So with the following example, the logs would be stored in the file `otelcol.log`:

```
service:
  telemetry:
    logs:
      level: debug
      output_paths:
        - otelcol.log
 ```

One potential option to try out, provided that the log file generated by collector A is accessible by collector B, would be to then use the `filelogreceiver` to read the log file generated by collector A.

**Comment by Amoolaa** [comment]
> One potential option to try out, provided that the log file generated by collector A is accessible by collector B, would be to then use the filelogreceiver to read the log file generated by collector A.

I've tried this and it didn't work (probably for good reason) - it can be a source of infinite logging

**Comment by mowies** [comment]
@vaibhhavv FYI: there was an update to the docs in regards to this and also new features to be able to define a normal exporter for internal telemetry logs.
see https://github.com/open-telemetry/opentelemetry.io/pull/5702

**Comment by vaibhhavv** [comment]
Thanks @mowies for mentioning it. I would say many important use cases will be solved under this implementation. ❤️

**Comment by mowies** [comment]
Can this issue be closed with this new info?
