### ISSUE TITLE
Sentry exporter: Add Span Event to sentry

### ISSUE THREAD

**Issue by afifurrohman-id** [open-telemetry/opentelemetry-collector-contrib#35313]
### Component(s)

exporter/sentry

### Is your feature request related to a problem? Please describe.

There may related in sentry-go: https://github.com/getsentry/sentry-go/issues/691

### Describe the solution you'd like

none

### Describe alternatives you've considered

none

### Additional context

 none

**Comment by AbhiPrasad** [comment]
This is currently a won't do in the exporter until Sentry itself supports the span event protocol. I would close this and wait for Sentry support until then.

**Comment by crobert-1** [comment]
Thanks for filing @afifurrohman-id, and thanks for the quick response and explanation @AbhiPrasad, appreciate it!

_Closing based on code owner response._
