### ISSUE TITLE
azuredataexplorerexporter: telemetry data Ingestion fails on ADX

### ISSUE THREAD

**Issue by asaharn** [open-telemetry/opentelemetry-collector-contrib#35353]
### Component(s)

exporter/azuredataexplorer

## Description
Metric Traces Logs data fails to ingest with error, Bad request

## Steps to Reproduce
![image](https://github.com/user-attachments/assets/f13670e4-f079-408d-ba16-3b824e433d04)

## Expected Result
Data should ingest successfully

### Collector version

v0.108.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by crobert-1** [comment]
_Removing `needs triage` as a code owner has approved the PR that resolves this issue._

**Comment by andrzej-stencel** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35354
