### ISSUE TITLE
Production Usage

### ISSUE THREAD

**Issue by Svastikkka** [open-telemetry/opentelemetry-collector-contrib#35365]
### Component(s)

receiver/hostmetrics, receiver/loki, receiver/prometheus

### Describe the issue you're reporting

Can we use these  receivers in  our  Production environment

1. hostmetrics https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver
2. prometheus https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
3. loki https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/lokireceiver

Are they still in development ?

**Comment by dashpole** [comment]
You can see the stability of each component in the README: e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver#prometheus-receiver.  Many users use each of these components in production, but it will depend on organizational policies, etc.  For components which are not marked stable, there may be breaking changes over time to configuration or telemetry they generate.

**Comment by dashpole** [comment]
Hopefully that answers your question.  I'm going to close this as usage questions are better suited for support channels, such as the otel-collector channel on slack.
