### ISSUE TITLE
error in contrib collector 0.27: unknown exporters type "elasticsearch" 

### ISSUE THREAD

**Issue by PCDiver** [open-telemetry/opentelemetry-collector-contrib#3537]
**Describe the bug**
I downloaded release 0.27 from the contrib collector (windows version).  When I start the collector I get the error: cannot load configuration: unknown exporters type "elasticsearch" for elasticsearch.  Is the elasticsearch exporter for logs already in this release?  If not, when will it be? 

**Steps to reproduce**
run: .\otelcontribcol_windows_amd64.exe --config=config.yaml

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
S C:\Program Files\OpenTelemetry\collectoragent> .\otelcontribcol_windows_amd64.exe --config=config.yaml
2021-05-26T05:16:55.568+0200    info    service/application.go:277      Starting otelcontribcol...      {"Version": "v0.27.0", "NumCPU": 4}
2021-05-26T05:16:55.569+0200    info    service/application.go:185      Setting up own telemetry...
2021-05-26T05:16:55.570+0200    info    service/telemetry.go:98 Serving Prometheus metrics      {"address": ":8888", "level": 0, "service.instance.id": "3d858d74-ed08-489b-a55c-bff28481603d"}
2021-05-26T05:16:55.570+0200    info    service/application.go:220      Loading configuration...
Error: cannot load configuration: unknown exporters type "elasticsearch" for elasticsearch
2021/05/26 05:16:55 application run finished with error: cannot load configuration: unknown exporters type "elasticsearch" for elasticsearch

**What version did you use?**
Version: 0.27

**What config did you use?**
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
exporters:
  elasticsearch:
    endpoints: [http://elk1.submerge.local:9200]
    insecure: true
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [elasticsearch]

**Environment**
OS: Windows 10
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by gramidt** [comment]
@urso @faec @blakerouse - I quickly took a look and noticed that the "elasticsearchexporter" was not in the components file. Is this intentional?

**Comment by urso** [comment]
Yes, it is still in development. Although events can already be send, not all feature can be configured, which will result in a panic.

**Comment by vchirikov** [comment]
I'm waiting for the same thing.

Issues for tracking:
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1800
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4610

**Comment by jpkrohling** [comment]
It's being added to the contrib distribution as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6002 and https://github.com/open-telemetry/opentelemetry-collector-releases/pull/50

**Comment by vincentfree** [comment]
> Yes, it is still in development. Although events can already be send, not all feature can be configured, which will result in a panic.

In my experience it doesn't start when you use something like metrics instead of logs or traces.

I am going to contribute with a colleague to this exporter in the future since we could really use the metrics functionality with elastic search. 

Could you describe what is missing so we could take a look into it and help out?
@urso

**Comment by vincentfree** [comment]
> It's being added to the contrib distribution as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6002 and https://github.com/open-telemetry/opentelemetry-collector-releases/pull/50

I was not aware of the exporter not being ready for prime time. One of my goals was adding metrics to the elasticsearch exporter but if more is needed I can also take a look into getting it production ready.

**Comment by codeboten** [comment]
The initial issue has been addressed as the component is now part of the contrib distribution. Please open follow up items for any additional issues.
