### ISSUE TITLE
[receiver/splunkenterprise] Adding Telemetry around KV Store

### ISSUE THREAD

**Issue by michael-burt** [open-telemetry/opentelemetry-collector-contrib#35445]
### Component(s)

receiver/splunkenterprise

### Is your feature request related to a problem? Please describe.

Currently, the Splunk Enterprise Receiver lacks the ability to report on the status of KV Store, KV Store replication, and KV Store backups. This information can be gathered from the `/services/kvstore/status` API endpoint in Splunk.

### Describe the solution you'd like

I would like to add metrics around the KV Store to splunkenterprisereceiver.

**Comment by shalper2** [comment]
I think this would be a great addition to the receiver and I’d be happy to work on it.

**Comment by crobert-1** [comment]
_Removing `needs triage` based on response from code owner._
