### ISSUE TITLE
[processor/logdedup] Add OTTL Condition Field to logdedup processor

### ISSUE THREAD

**Issue by colelaven** [open-telemetry/opentelemetry-collector-contrib#35440]
### Component(s)

processor/logdedup

### Is your feature request related to a problem? Please describe.

It would be useful to have a condition field on the logdedup processor to only perform the deduplication on logs that pass said condition.

### Describe the solution you'd like

Add a condition field to the logdedup processor. Only logs that pass this condition are deduped.

**Comment by colelaven** [comment]
I have the code change ready for this one, putting a PR out soon.

**Comment by BinaryFissionGames** [comment]
It makes sense to me that you may have some logs that are more "low-latency" or you otherwise want to omit from deduplication.
