### ISSUE TITLE
[exporter/prometheus] Shutdown method does not shutdown server

### ISSUE THREAD

**Issue by Argannor** [open-telemetry/opentelemetry-collector-contrib#35464]
### Component(s)

exporter/prometheus

## Description

When the collector receives a `NOHUP` signal, it reloads the current configuration and calls the `Shutdown` method. The Shutdown method of the prometheusexporter however does only close the listener, not the `http.Server`. This means that the old server does not accept any new connections, but all existing connections may continue to live forever. If a client (like Prometheus) keeps the connection between scrapes alive, the requests will be served by the old instance, meaning the metrics will no longer get any updates until they disappear. This is especially difficult to debug, since requests using `curl` or `wget` will be served by the new instance, seeing completely different metrics.

## Steps to Reproduce

- Setup otel-collector with the prometheus exporter
- Setup prometheus to scrape this instance every 60s
- Send a NOHUP signal to prometheus
- No metric updates will be recorded by prometheus after the NOHUP

## Expected Result

- The old server must be shutdown, so that prometheus reconnects and receives the latest metrics

## Actual Result

- The old HTTP connection continues to live on and metrics go stale in prometheus

I will provide a Pull Request for this issue

### Collector version

v0.109.0/v0.110.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by dashpole** [comment]
Good find.  I'll follow-up on the PR

**Comment by dashpole** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35465
