### ISSUE TITLE
[extension/opamp]: Support auth extensions

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#35507]
### Component(s)

extension/opamp

### Describe the issue you're reporting

Like #32762 but for the extension, we need to support using auth extensions with the opamp extension. 

We can currently implement a hacky version, and transition to a more robust solution later when we are able to implement websocket support in the upstream auth package.

**Comment by crobert-1** [comment]
_Removing `needs triage` as this was filed by a code owner and makes sense to me._
