### ISSUE TITLE
[processor/metricsgeneration] Metrics should be calculated when second metric value is 0

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#35533]
### Component(s)

processor/metricsgeneration

### Describe the issue you're reporting

**Bug**
The metrics generation processor is used to create new metrics by using calculations on existing metrics. As explained in the configuration example [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricsgenerationprocessor#configuration), the config specifies the first metric, second metric, and operation type for calculations.

Existing logic for this processor simply skips the calculation when the value of the second metric's datapoint is 0 ([reference](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5f96c1ae634456a382a64caaa61b1a7839a54765/processor/metricsgenerationprocessor/processor.go#L64)). This means that even when it's a valid operation, and the result may be relevant for users, no metric is created.

**Example showing bug**
Relevant example configuration:
```
experimental_metricsgeneration:
  rules:
    - name: available_capacity
      unit: bytes
      type: calculate
      metric1: total_capacity
      metric2: used_capacity
      operation: subtract
```

This configuration should create a new metric called `available_capacity`, which will be the result of `total_capacity - used_capacity`. If the value of `used_capacity` is 0, the processor won't create a new metric called `available_capacity`, when I believe it should.

**Proposed Solution**
I think the solution here is to allow the calculation to be done and to create the resulting metric.

**Open Question**
How should we handle the `divide` and `percent` operations for the case of dividing by 0? We can either add a data point with a value of `0` or not add any data point at all. Since dividing by 0 is an invalid operation, I believe the right thing to do would be log an error and not add a data point in that case. I'm open to feedback from others though.

**Comment by dmitryax** [comment]
> Since dividing by 0 is an invalid operation, I believe the right thing to do would be log an error and not add a data point in that case.

I agree

**Comment by crobert-1** [comment]
Had a discussion with Dmitrii offline, we also agreed that if no valid data points are generated for the new metric, the new metric should not be created. I'll add a note in the README to clarify this for users.
