### ISSUE TITLE
[extension/opampextension] Report `os.description` semantic convention

### ISSUE THREAD

**Issue by dpaasman00** [open-telemetry/opentelemetry-collector-contrib#35555]
### Is your feature request related to a problem? Please describe.

I'd like to communicate the exact operating system and version my collector is running on over OpAMP. Currently the extension only reports the OS and arch which doesn't tell me the version of the OS.

### Describe the solution you'd like

I'd like to add the semantic convention `os.description` as a non-identifying attribute in the agent description message sent by the extension.

### Additional context

The semantic convention definition for `os.description` can be found [here](https://opentelemetry.io/docs/specs/semconv/attributes-registry/os). Additionally I'd like to take on contributing this enhancement.

**Comment by crobert-1** [comment]
_Removing `needs triage` as a code owner has responded 👍 to this issue._
