### ISSUE TITLE
[pkg/stanza] Windows input operator leaks remote session handle

### ISSUE THREAD

**Issue by kuiperda** [open-telemetry/opentelemetry-collector-contrib#35577]
### Component(s)

pkg/stanza

## Description

@pjanotti noticed this [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35520#pullrequestreview-2341397957) (#35520)

## Steps to Reproduce

See the comment above. Since `Subscription::Close` does not close the remote session handle, it is leaked. This will happen when the operator resubscribes due to the remote host restarting, for example. 

## Expected Result

The remote session handle should be closed properly so it does not get leaked. 

### Collector version

v0.110.0

### Environment information

N/A

### OpenTelemetry Collector configuration

```yaml
N/A
```

### Log output

```shell
N/A
```

### Additional context

N/A

**Comment by VihasMakwana** [comment]
Based on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35520#issuecomment-2391437750, it seems as @kuiperda wouldn't have time to work on this.

I can have a crack at this though. @djaglowski can you assign this to me?

**Comment by crobert-1** [comment]
_Removing `needs triage` as a triager pointed out this issue._
