### ISSUE TITLE
[k8sobserver] Add documentation for required RBAC permissions

### ISSUE THREAD

**Issue by bacherfl** [open-telemetry/opentelemetry-collector-contrib#35595]
### Component(s)

extension/observer/k8sobserver

### Describe the issue you're reporting

Currently the k8sobserver readme lacks a description of how to setup the required RBAC permissions (ClusterRole/ClusterRoleBinding) for the collector to be able to observe the K8s resources, such as in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sobjectsreceiver. 
To make setting up this component easier, this should be added here as well.

I'm happy to work on a PR for this.

**Comment by kumarrishav4** [comment]
hey i am fairly new to contibution community can you provide me the details on what documentation is required and i could look into it

**Comment by ChrsMark** [comment]
Thank's @kumarrishav4, but as @bacherfl mentioned there is already a PR up. I have fixed the assignment here.
