### ISSUE TITLE
make otelcontribcol is now failing due to no Go files in ./cmd/otelcontribcol

### ISSUE THREAD

**Issue by developer-guy** [open-telemetry/opentelemetry-collector-contrib#35631]
### Component(s)

cmd/otelcontribcol

### What happened?

I was trying to build otelcontribcol using a make target `otelcontribcol` but it started failing after v0.111.0 because there are no Go files anymore in .cmd/otelcontribcol, is this some sort of a bug or is there any new way of building the project?

Thanks.

### Collector version

x.x.x

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by BharatKJain** [comment]
I am facing the same issue, let me know if you find something.

**Comment by developer-guy** [comment]
I can confirm that it worked yeah!

**Comment by swamisriman** [comment]
I've been banging my head since noon 🤦🏻‍♂️.
Thanks @BharatKJain !

**Comment by BharatKJain** [comment]
I think we should update the Makefile like add genotelcontribcol step for both docker and binary targets, @mowies What's your thought on it? I can help with it, if you want.

**Comment by mowies** [comment]
Yeah i think we should add the generate targets where needed. I'll create a PR

**Comment by BharatKJain** [comment]
My vscode debugger is also failing, any suggestions for it? Please help!

It was working before... 😞 


`launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch file",
            "cwd": "${workspaceRoot}/cmd/otelcontribcol",
            "type": "go",
            "trace": "verbose",
            "logOutput": "dap",
            "showLog": true,
            "request": "launch",
            "mode": "debug",
            "env": {"GO111MODULE": "on","CGO_ENABLED": "0"},
            "program": "${workspaceRoot}/cmd/otelcontribcol",
            "args": ["--config", "./../../test-config-exporter-gelf.yaml"]
        } 
    ]
}
```
