### ISSUE TITLE
Binary is not PIE (Position-independent code)

### ISSUE THREAD

**Issue by DanTulovsky** [open-telemetry/opentelemetry-collector-contrib#35634]
### Component(s)

cmd/otelcontribcol

### Is your feature request related to a problem? Please describe.

It looks like the binary for linux produced from this repo is not PIE (Position-independent code).  I was wondering if this was a conscious decision.  If not, would it be possible to start publishing PIE binaries for otel-collector-contrib?

My specific use case right now is that I am trying to run this on Unikraft Cloud (https://unikraft.org/docs/concepts/compatibility) and they require that binaries be PIE.

My workaround is to build from source, but I'd prefer to not have to do that.

### Describe the solution you'd like

Linux binaries published by this project are PIE.

### Describe alternatives you've considered

Building from source is a viable alternative.

### Additional context

This is the error returned by the platform (confirmed by the people who run it).

```
Powered by Unikraft Telesto (0.16.2~83244528)
[    0.004302] ERR:  [appelfloader] otelcol-contrib: ELF executable is not position-independent!
[    0.005081] ERR:  [appelfloader] otelcol-contrib: Parsing of ELF image failed: Exec format error (-8)
```

**Comment by atoulme** [comment]
Binary for this repository is used for internal testing, please see https://github.com/open-telemetry/opentelemetry-collector-releases for our released binaries.
