### ISSUE TITLE
Release notes of 0.109.0 has incorrect feature gate for spanmetrics

### ISSUE THREAD

**Issue by tbeemster** [open-telemetry/opentelemetry-collector-contrib#35766]
### Component(s)

connector/spanmetrics

### Describe the issue you're reporting

The v0.109.0 release notes on page https://github.com/open-telemetry/opentelemetry-collector-contrib/releases talks about:

> The feature flag connector.spanmetrics.legacyLatencyMetricNames

**Steps to reproduce**

1. Dockerfile with Otelcollector built together with spanmetrics. Final line of Dockerfile:
`CMD ["/otelcol-custom", "--config=/etc/otel-collector-config.yml", "--feature-gates=connector.spanmetrics.legacyLatencyMetricNames" ]`

2. Build docker image
3. Run docker image

**Expected result**
Running instance of the otelcollector

**Actual result**
`Error: invalid argument "connector.spanmetrics.legacyLatencyMetricNames" for "--feature-gates" flag: no such feature gate "connector.spanmetrics.legacyLatencyMetricNames". valid gates: [component.UseLocalHostAsDefaultHost connector.spanmetrics.legacyMetricNames processor.tailsamplingprocessor.metricstatcountspanssampled service.noopTracerProvider telemetry.disableHighCardinalityMetrics telemetry.useOtelWithSDKConfigurationForInternalTelemetry]
`

*Proposed change*
Since the software is already released with the feature gate **connector.spanmetrics.legacyMetricNames**, I propose to change the Release notes of v0.109.0 to mention the correct feature gate.

**Comment by atoulme** [comment]
I have gone ahead and edited the release notes, thank you for your report. Please consider opening a PR to update CHANGELOG.md.

**Comment by tbeemster** [comment]
Hi @atoulme, thank you for changing the release notes.
I've just opened a PR to update the CHANGELOG.md file
