### ISSUE TITLE
[cmd/opampsupervisor] Strictly unmarshal the supervisor configuration

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#35838]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

The supervisor configuration currently may contain keys that aren't actually configuring anything. These keys are currently ignored, and the supervisor starts happily.

The issue here is that if you typo a setting, the supervisor will not notify you of your error and the setting will be silently ignored.

Instead, we should do a strict unmarshal of the config in order to error on any extra/unknown keys being present.

**Comment by Annosha** [comment]
As a beginner, I'm willing to work on it once the maintainers approve!
