### ISSUE TITLE
[receiver/datadog] Support for Span Links

### ISSUE THREAD

**Issue by lopes-felipe** [open-telemetry/opentelemetry-collector-contrib#35963]
### Component(s)

receiver/datadog

### Is your feature request related to a problem? Please describe.

Currently, there is no way to create [Span Links](https://opentelemetry.io/docs/concepts/signals/traces/#span-links) from Datadog spans, through the Datadog receiver.

### Describe the solution you'd like

Provide the span link data via an attribute (`otlp.link.%d`?) and have the attribute translated to a span link, in the same lines as the [existing Zipkin one](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/zipkin/zipkinv2/to_translator.go#L186-L242).

### Describe alternatives you've considered

I'm aware that the Datadog span entity already has a proper `SpanLink` [attribute](https://github.com/DataDog/datadog-agent/blob/main/pkg/proto/pbgo/trace/span.pb.go#L162), but considering that it isn't exposed in most ([all except PHP?](https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/php/dd-api/?tab=currentspan#adding-span-links-beta)) tracing libraries, we can't leverage that.

### Additional context

I can implement this once accepted.

**Comment by MovieStoreGuy** [comment]
I am conscious that this is somewhat of deviation from the Datadog agent offers which makes interoperability more changeling, as well as platform trying to support both methods. (from a complete customer end to end experience)

I know that this is community lead component but I do want to make sure the enhancements are reasonable and aligned with the direction that the company is going and not trying to diverge too much.

May I suggest reaching out to the support team and working with them on this issue first?
It will help to show more customers are interested and keen to use it 😄

**Comment by lopes-felipe** [comment]
Hey @MovieStoreGuy, thanks for the response.

Sure, I'll open a feature request with them, although something tells me that they won't have it implemented anytime soon (if ever) 😄

**Comment by MovieStoreGuy** [comment]
I can't speak for Datadog and their roadmap, but I can say that the engineers advocating for the feature appreciate hearing customer excitement :) 

Considering that this is on their roadmap (at least in beta) on the public docs, I am tempted to park this issue so the development teams can do it right without having to be concerned about open source community implementation. 

For the time being, I suggest if you want to adopt Span Links in earnest then using Otel native instrumentation to get a complete experience.
