### ISSUE TITLE
Move Makefile common targets to Makefile.Common

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector-contrib#36]
There is some redundancy between the Makefile that builds the contrib executable and the Makefile.Common that is used to build individual components. We should have a single source for the "common" targets to keep the convenience of quick builds and custom targets for components while avoiding divergence of targets between Makefile and Makefile.common. /cc @owais

**Comment by tigrannajaryan** [comment]
@pjanotti perhaps we can remove makefiles from individual component directories? Are they needed if there is a full build now?

**Comment by owais** [comment]
I agree. We should remove the individual ones. If the components need some special targets, we can add them to root makefile and have an argument that allows users to run targets against a component. Something like `make test-component COMPONENT='receiver/zipkin'`

**Comment by pjanotti** [comment]
This is a convenience in order to avoid full build as the number of components increases, it can be replaced by adding targets but it seems simpler to simply factor out the common parts and have Makefile using some of the same targets from common.

**Comment by pjanotti** [comment]
I think my initial description gave the impression about keeping them in sync, that was not my intention: the intention is to have a single source for the common targets.

**Comment by pjanotti** [comment]
Edited the initial description.
