### ISSUE TITLE
supervisor: configurable opamp listener port range

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#36001]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

In restricted environments with perimeter security, the firewall is preconfigured to allow specific ports or port ranges for designated users or processes. In this setup, it is essential that a service cannot choose ports on its own.

Instead, the configuration must be predetermined and statically assigned to the supervisor, with a dedicated network interface managing these settings.

### Describe the solution you'd like

Configure the network interface and port range on which  the opamp server will listen and setup the opamp cfg to connect to which is used by the collector.

**Comment by dpaasman00** [comment]
I can take this on! I'll add a new parameter to the `agent` section of the supervisor config called `opamp_server_port`.

**Comment by dpaasman00** [comment]
This would run the supervisor's OpAMP server on `localhost:<opamp_server_port>`. Would this resolve your issue, or is there a use case to not use `localhost`?

**Comment by cforce** [comment]
It would be great if you can add the port . 👍 
Ii will check next week if localhost is ok or a dedicated ip is needed. I assume as long not 0.0.0.0 (all) is used i think its fine, but i will check,
