### ISSUE TITLE
Request to add @VihasMakwana as triager for contrib

### ISSUE THREAD

**Issue by VihasMakwana** [open-telemetry/opentelemetry-collector-contrib#36025]
### Describe the issue you're reporting

I’d like to nominate myself as a triager to help manage issues in this repository. I’ve been an active contributor to the community for a while now.

My [PRs](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3AVihasMakwana)
[Issues](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+is%3Aopen+VihasMakwana) I've been involved with

**Comment by andrzej-stencel** [comment]
I support :+1:

**Comment by atoulme** [comment]
I support. Vihas has been active for a while and we can use his help in this new role.

**Comment by evan-bradley** [comment]
I support.

**Comment by mx-psi** [comment]
I support.

**Comment by songy23** [comment]
I support

**Comment by MovieStoreGuy** [comment]
I support

**Comment by atoulme** [comment]
I support

**Comment by JaredTan95** [comment]
I support.
