### ISSUE TITLE
Request for Update on prometheusremotewritereceiver Initial Implementation in OpenTelemetry Collector

### ISSUE THREAD

**Issue by Wudadada** [open-telemetry/opentelemetry-collector-contrib#36088]
### Component(s)

receiver/prometheusremotewrite

### Is your feature request related to a problem? Please describe.

I’m interested in using the prometheusremotewritereceiver within the OpenTelemetry Collector but noticed that there isn’t a functional implementation available yet. This feature would be incredibly useful for environments that rely on Prometheus Remote Write to transmit metrics to the collector without needing to adapt the data source.

### Describe the solution you'd like

I would like to know if there are any plans or a timeline for implementing an initial version of the prometheusremotewritereceiver in otelcol. Having even a preliminary implementation available would be beneficial for early testing and integration.

### Describe alternatives you've considered

I have considered using other methods to transfer Prometheus metrics data, such as exporters and different collectors. However, the prometheusremotewritereceiver would streamline this process, allowing direct integration with Prometheus Remote Write.

### Additional context

This feature could greatly simplify data pipeline configurations for Prometheus users in environments where direct Remote Write support is needed. Any insight into the development timeline or potential obstacles would be highly appreciated.

**Comment by ArthurSens** [comment]
Hi @Wudadada, we agree that a prometheus remote-write receiver would help a ton here! [I'm currently working on this](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusremotewritereceiver), I'm hoping to get this component to an alpha version in one or two months. (Hopefully 1!!!)

**Comment by Wudadada** [comment]
> Hi @Wudadada, we agree that a prometheus remote-write receiver would help a ton here! [I'm currently working on this](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusremotewritereceiver), I'm hoping to get this component to an alpha version in one or two months. (Hopefully 1!!!)

Thanks so much for your contribution! We’re really looking forward to seeing the results of your work!

**Comment by Wudadada** [comment]
Hi @ArthurSens , I hope you’re doing well! I noticed that it’s been about two months since the discussion about the Prometheus remote-write receiver feature. I was wondering if there are any updates or progress you could share with us. We’re really excited about this feature and looking forward to seeing it in action. Thanks for your hard work!

**Comment by ArthurSens** [comment]
Hey @Wudadada, unfortunately the implementation was harder than initially thought and we spent some time re-thinking the implementation.

You can see all the open/closed PRs [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+label%3Areceiver%2Fprometheusremotewrite+is%3Aopen). And what's left is documented as "TODO" in the codebase itself. I'm still working on it but I'd love some help :)
