### ISSUE TITLE
[exporter/elasticsearch] Handle errors for 413 Entity Too Large

### ISSUE THREAD

**Issue by mauri870** [open-telemetry/opentelemetry-collector-contrib#36163]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

The exporter has experimental batching support with the syncronous bulk inserter which can circunvent the request size limitation from Elasticsearch. Unfortunately if the batch is whithin the configured range but the documents are quite large (for example logs containing stacktraces) we can still hit  the `http.max_content_length`, which is 100mb by default.

The underlying [`go-docappender`](https://github.com/elastic/go-docappender/issues/210) library used by the exporter does not seem to handle this case, resorting to the client to handle it. I have opened [an upstream issue](https://github.com/elastic/go-docappender/issues/210) to see if the library can do anything to help in this case.

Another problem is that error 413 is not returned as permanent, the client will be instructed to retry it with no effect.

### Describe the solution you'd like

I believe the exporter should do a best effort to circunvent the 413, maybe by splitting the batch again internally to make it fit within the limit and then retry, if possible.

### Describe alternatives you've considered

Extend the exporterhelper batcher to support batch splitting or by a max_size config.

Another option is to provide a sentinel error for Entity Too Large, allowing the receiver/processor to split the data and retry again. Currently if a 413 happens the returned error is:

```txt
flush failed (413): [413 Request Entity Too Large]
```

This error is specific to Elasticsearch, I believe we should have a more universal error that other exporters can return when facing a similar error.

### Additional context

Relates to https://github.com/elastic/ingest-dev/issues/3677

**Comment by mauri870** [comment]
It appears that there is a similar, more general proposal available at https://github.com/open-telemetry/opentelemetry-collector/issues/8272. Allowing the batcher config to have a max size in bytes seems to be a more straightforward solution.

**Comment by carsonip** [comment]
I have opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36396 to reduce the chance of 413 for sync bulk indexer (used when exporterhelper batcher is active), instead of handling the error, because there is no good way to handle such an error other than to send them in appropriately sized chunks in the first place.
