### ISSUE TITLE
[pkg/ottl] unexpected behavior of `flatten` function when handling slice attributes at top level

### ISSUE THREAD

**Issue by bacherfl** [open-telemetry/opentelemetry-collector-contrib#36161]
### Component(s)

pkg/ottl

## Description

Currently, when setting the `depth` to `0`, slices at the top level of the input of the `flatten` function will still be flattened.

## Steps to Reproduce

Consider the following input for the `flatten` function:

```json
{
  "things": [
    {
       "name": "a"
    }
  ]
}
```

And use the `flatten` function with a depth of `0`:

```
flatten(attributes, depth=0)
```

## Expected Result

According to the [docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/58c0120dfabd48a132b8e1e4011efe8e73b0ec35/pkg/ottl/ottlfuncs/README.md?plain=1#L200 ), there should be no flattening when the depth is set to `0`, i.e. the input should be left unchanged: 

```json
{
  "things": [
    {
       "name": "a"
    }
  ]
}
```

## Actual Result

The slice elements are flattened, regardless of the `depth`

```json
{
  "things.0": {
    "name": "a"
  }
}
```

### Collector version

v0.112.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by TylerHelmuth** [comment]
It kinda feels like a bug to let you set a depth of 0.  That is the same as not calling the function.

**Comment by bacherfl** [comment]
> It kinda feels like a bug to let you set a depth of 0. That is the same as not calling the function.

Yes that seemed a bit odd to me that setting the depth to 0 is a supported option. Is it possible to set this parameter dynamically as well, based on e.g. another attribute or the result of another transformation? In this case it may be justified to also support 0, even though I cannot think of a realistic use case where this might be required

**Comment by TylerHelmuth** [comment]
@bacherfl the `depth` parameter has to be a static value, it is not defined as a getter: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d0f4d09549758c41e698f0ec39fa9d0e213ea848/pkg/ottl/ottlfuncs/func_flatten.go#L19.

I think the best fix to this issue is to not allow a depth to be < 1

**Comment by bacherfl** [comment]
> @bacherfl the `depth` parameter has to be a static value, it is not defined as a getter:
> 
> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d0f4d09549758c41e698f0ec39fa9d0e213ea848/pkg/ottl/ottlfuncs/func_flatten.go#L19
> 
> I think the best fix to this issue is to not allow a depth to be < 1

Got it - in this case I will adapt the PR accordingly
