### ISSUE TITLE
[pkg/pdatatest] Support profiles signal comparison

### ISSUE THREAD

**Issue by odubajDT** [open-telemetry/opentelemetry-collector-contrib#36232]
### Component(s)

pkg/pdatatest

### Is your feature request related to a problem? Please describe.

With introduction of profiles signal, we should add the adequate functionality also for profiles signal comparison library for testing.

### Describe the solution you'd like

Add `CompareSignals` function same as it's done for other signal types

**Comment by odubajDT** [comment]
I will start working on this issue and open a PR soon

**Comment by odubajDT** [comment]
@mx-psi

**Comment by mx-psi** [comment]
Makes sense to me :)
