### ISSUE TITLE
[cmd/githubgen] Make checking OpenTelemetry membership optional

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#36263]
### Component(s)

cmd/githubgen

### Is your feature request related to a problem? Please describe.

The cmd/githubgen check only runs on main right now as it requires access to a github token to check the contributors membership with the OpenTelemetry project.

### Describe the solution you'd like

We could make the check with github optional so we can at least regenerate the CODEOWNERS file. This will deter manual changes to the CODEOWNERS file. We can then run githubgen on any PR.

**Comment by Aneurysm9** [comment]
I'll try tackling this.
