### ISSUE TITLE
[exporter/clickhouse] Incorrect ServiceName set for Logs Records

### ISSUE THREAD

**Issue by Fiery-Fenix** [open-telemetry/opentelemetry-collector-contrib#36349]
### Component(s)

exporter/clickhouse

## Description
In some corner cases, for Log Records `clickhouseexporter` inserts incorrect ServiceName value
For example, `clickhouseexporter` receives 2 Log Records in this order:
* First record with Resource Attribute `service.name` is equal to `someservice`
* Second record - without Resource Attribute `service.name`
In this case - both records will be written to ClickHouse with `ServiceName = someservice`
That is happened because of this line: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/exporter_logs.go#L74
Variable `serviceName` defined **outside** of the loop and keep last value between loops
This variable should be defined **inside** of the loop to keep data only for current Resource Log
Traces part is already have correct code - see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/exporter_traces.go#L78
Metrics part is also unaffected - for example see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/internal/gauge_metrics.go#L112

## Steps to Reproduce
Feed to `clickhouseexporter` 2 Log Records:
* First record with Resource Attribute `service.name` is equal to `someservice`
* Second record - without Resource Attribute `service.name`

## Expected Result
Written data should have following values in `ServiceName` field of `otel_logs` table:
* someservice
* Empty string

## Actual Result
Actual written data have following values in `ServiceName` field of `otel_logs` table:
* someservice
* someservice

### Collector version

v0.113.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by VihasMakwana** [comment]
_Removing triage label as this looks like a valid bug and has a bugfix PR linked_
