### ISSUE TITLE
MongoDB Atlas receiver proxy support

### ISSUE THREAD

**Issue by williamlord-wise** [open-telemetry/opentelemetry-collector-contrib#36412]
### Is your feature request related to a problem? Please describe.

MongoDB Atlas receiver doesn't appear to respect the proxy environment variables https://opentelemetry.io/docs/collector/configuration/#proxy-support, https://pkg.go.dev/go.mongodb.org/atlas/mongodbatlas.

### Describe the solution you'd like

It would be ideal if the receiver supported proxy environment to that network controls could be easily implemented.

### Describe alternatives you've considered

Moving the exporter to a network that allows access to the MongoDB Atlas API.

**Comment by dehaansa** [comment]
This looks like a pretty straightforward fix, but I do not have an environment to validate. If you have the ability to validate https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36513 that would be helpful!
