### ISSUE TITLE
Followup on Pull Request #32500

### ISSUE THREAD

**Issue by donald-cheung** [open-telemetry/opentelemetry-collector-contrib#36427]
### Component(s)

internal/kafka

### Describe the issue you're reporting

Hello,

I am writing to kindly request a follow-up on #32500, which has been open for several months. We are keen to see it progress and would appreciate any updates at your earliest convenience.

If there are any additional procedures or steps we should follow, please let us know. Thank you very much for your support and assistance.

**Comment by golem1987** [comment]
+1 for merge this PR
