### ISSUE TITLE
[datadog exporter] not aggregate counter values properly

### ISSUE THREAD

**Issue by tonglil** [open-telemetry/opentelemetry-collector-contrib#3654]
**Describe the bug**
The value recorded by Datadog does not align with the metrics that are being collected by the collector.
It seems to under count/ingest the metric values that are being sent to the collector.

Here is an example (but it is actually also happening elsewhere):

Our app is sending a metric that should have a count of 2 for `visibility: cluster-internal`, however Datadog is only reporting a value of 1.
The collector log debug shows that it is receiving a value of 1, then 2, shortly after.

Here is the output of the collector logging exporter (see `cluster-internal`):

```ResourceMetrics #1
Resource labels:
     -> cloud.account.id: STRING(redacted)
     -> cloud.provider: STRING(redacted)
     -> cloud.zone: STRING(redacted1-c)
     -> deployment.environment: STRING(prd)
     -> host.id: STRING(112504395174149891)
     -> host.name: STRING(redacted-1622072700-n55bw)
     -> k8s.cluster.name: STRING(redacted-v1)
     -> k8s.namespace.name: STRING()
     -> k8s.pod.name: STRING(redacted-1622072700-n55bw)
     -> service.name: STRING(status-check)
     -> service.version: STRING(360)
     -> telemetry.sdk.language: STRING(go)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(0.19.0)
InstrumentationLibraryMetrics #0
InstrumentationLibrary status-check 
Metric #0
Descriptor:
     -> Name: status_check/apps_processed
     -> Description: The current number of Apps processed
     -> Unit: 
     -> DataType: IntSum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
IntDataPoints #0
Data point labels:
     -> has_endpoint: true
     -> status: success
     -> visibility: private
StartTimestamp: 2021-05-26 23:45:06.477150675 +0000 UTC
Timestamp: 2021-05-26 23:46:11.47804578 +0000 UTC
Value: 3
IntDataPoints #1
Data point labels:
     -> has_endpoint: true
     -> status: failure
     -> visibility: cluster-internal
StartTimestamp: 2021-05-26 23:45:06.477150675 +0000 UTC
Timestamp: 2021-05-26 23:46:11.47804578 +0000 UTC
Value: 1
IntDataPoints #2
Data point labels:
     -> has_endpoint: false
     -> status: success
     -> visibility: private
StartTimestamp: 2021-05-26 23:45:06.477150675 +0000 UTC
Timestamp: 2021-05-26 23:46:11.47804578 +0000 UTC
Value: 49

... shortly after in the log ...

ResourceMetrics #1
Resource labels:
     -> cloud.account.id: STRING(redacted)
     -> cloud.provider: STRING(redacted)
     -> cloud.zone: STRING(redacted1-c)
     -> deployment.environment: STRING(prd)
     -> host.id: STRING(112504395174149891)
     -> host.name: STRING(redacted-1622072700-n55bw)
     -> k8s.cluster.name: STRING(redacted-v1)
     -> k8s.namespace.name: STRING()
     -> k8s.pod.name: STRING(redacted-1622072700-n55bw)
     -> service.name: STRING(status-check)
     -> service.version: STRING(360)
     -> telemetry.sdk.language: STRING(go)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(0.19.0)
InstrumentationLibraryMetrics #0
InstrumentationLibrary status-check 
Metric #0
Descriptor:
     -> Name: status_check/apps_processed
     -> Description: The current number of Apps processed
     -> Unit: 
     -> DataType: IntSum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
IntDataPoints #0
Data point labels:
     -> has_endpoint: false
     -> status: failure
     -> visibility: private
StartTimestamp: 2021-05-26 23:45:06.477150675 +0000 UTC
Timestamp: 2021-05-26 23:48:41.477717578 +0000 UTC
Value: 14
IntDataPoints #1
Data point labels:
     -> has_endpoint: true
     -> status: failure
     -> visibility: cluster-internal
StartTimestamp: 2021-05-26 23:45:06.477150675 +0000 UTC
Timestamp: 2021-05-26 23:48:41.477717578 +0000 UTC
Value: 2
IntDataPoints #2
Data point labels:
     -> has_endpoint: true
     -> status: failure
     -> visibility: private
StartTimestamp: 2021-05-26 23:45:06.477150675 +0000 UTC
Timestamp: 2021-05-26 23:48:41.477717578 +0000 UTC
Value: 1
```

**Steps to reproduce**
The code is very simple:
```go
	counter := metric.Must(o.Meter).
		NewInt64Counter(
			"status_check/apps_processed",
			metric.WithDescription("The current number of Apps processed"),
		)
	counter.Add(ctx, 1, labels...)
```

Something of note, the `StartTimestamp` is the same for all, but `Timestamp` is different between first set and second set. Not sure what this means.

**What did you expect to see?**
I want to see the value for this metric with the tag `visibility: cluster-internal` to be 2.

**What did you see instead?**
Instead datadog only seems to record the first set's `IntDataPoints #1` and ignores the second set's update, therefor under counting, reporting only 1.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/3250776/119747591-e6db0180-be47-11eb-80ef-becce5c6eda4.png">

*note this apps runs periodically, and each period the value should be 2, but only shows 1.

**What version did you use?**
Version: latest as of 2 days ago (0.27.0?)

**What config did you use?**
```
receivers:
  otlp:

processors:
  batch:
    timeout: 10s
  memory_limiter:
    # Same as --mem-ballast-size-mib CLI argument
    ballast_size_mib: 165
    # 80% of maximum memory up to 2G
    limit_mib: 400
    # 25% of limit up to 2G
    spike_limit_mib: 125
    check_interval: 5s

exporters:
  logging:
    loglevel: debug
  datadog/api:
    metrics:
      resource_attributes_as_tags: true
    tags:
      - source:otel
    api:
      key: "${DD_API_KEY}"

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [datadog/api, logging]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [datadog/api, logging]

```

**Environment**
Doesn't matter

**Additional context**
none

**Comment by tonglil** [comment]
Thanks, I'll give it a try.

Just to let you know, I don't really understand the explanation or the documentation.
It still seems like a weird thing I have to config for, and don't know the implications of this elsewhere.

Perhaps you can help by elaborating on which metrics this is "working as intended", or where this setting makes a difference..

**Comment by tonglil** [comment]
Something just doesn't seem "right" with the data, in either way.

This is the before and after of making that change:
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/3250776/120694340-eef5fb00-c45e-11eb-9fbf-d405f5a9ede5.png">

You can see before, it was reporting a constant value of 1.

After, for some reason Datadog is reporting that the max values include halves and quarters, when the app doesn't record that.

> default we send cumulative monotonic metrics as the one in your example as deltas between successive measurements

Are you saying that when `send_monotonic_counters=true`, it only showed 1 because I recorded 1 then 2 (2-1=1), and I need to first record 0, then 1, then 2, in order for the counter to show 2 in datadog (2-0=2)?

**Comment by mx-psi** [comment]
👋 , sorry for the delay, let me try to clarify this a little to see if we are on the same page. 

In your case, the OpenTelemetry Go SDK is mapping the Counter instrument to an IntSum that has cumulative aggregation and is monotonically increasing. As you can see in [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.3.0/specification/metrics/datamodel.md#sums) this means the metric values are supposed to increase on each successive measurement. For example, let's say you use a Counter on Go and send a value of 1  at times t = 0, t = 1 and t = 2. The Go SDK will report this as an IntSum cumulative and monotonic with values 1 at t = 0, 2 at t = 1 and 3 at t = 2. It will also set the StartTimestamp value so that we can know if there has been a reset of the value (so that we can distinguish between you sending another 1 (t = 4, startTimestamp = 0, value = 4) from the SDK resetting the count and the user sending a value of 4 (t = 4, startTimestamp = 4, value = 4)).

By default on the Datadog exporter we do the reverse process: given the sequence we had before of 1,2,3 at times 0, 1 and 2 we will report a Datadog Count of value 1 at times t = 1 and t =2 (we currently don't report the very first value of the metric for cumulative monotonic sums). If you change the value of `send_monotonic_counters` we just report the raw values we get as a Datadog Gauge (so 1,2,3 at times 0,1 and 2.

Your SDK might also do other stuff like aggregating values which might make this analysis a bit more difficult, but that's the gist of it.

I will take a closer look to double check that this works properly since your graph looks off but I hope this at least helps understand things a bit better. I also want to improve our documentation on the mapping since we don't have good docs on this at the moment and I understand it can be confusing.

**Comment by tonglil** [comment]
Thanks for elaborating on this here.

I ran into this and spent a lot of time thinking it was something wrong with my collectors:
> (we currently don't report the very first value of the metric for cumulative monotonic sums)

Why is that so? I've changed my app to count and emit one single counter value per execution so I don't have to do aggregation in Datadog, however this value is dropped because it's the only value being emitted.

FWIW I ended up switching to a updowncounter because of this.

**Comment by mx-psi** [comment]
> Why is that so? 

Datadog counts expect a fixed interval (i.e. report the count every 10 seconds) but OpenTelemetry cumulative monotonic sums do not need to have this (they can have an arbitrary interval). The instrumentation APIs report with a fixed frequency but the first value may be for a larger interval in some cases. To avoid a possible weird-looking peak on the first point, we took the decision (on OpenMetrics and then here) of not reporting this first value (at least by default).

We may add a flag to flush the first value if that is useful for you; it's something we have in the Datadog Agent for OpenMetrics and that would not be hard to add here. If that is something useful for you please do let me know so we can prioritize internally.

**Comment by mx-psi** [comment]
We now have more detailed docs on the mapping here: https://docs.datadoghq.com/metrics/otlp. I am closing this since I was keeping this open until we documented it.
