### ISSUE TITLE
[exporter/elasticsearch] Encode geo location attributes as geo_point in Elasticsearch

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector-contrib#36565]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

Geo location attributes `geo.location.lat` and `geo.location.lon` ([SemConv](https://github.com/open-telemetry/semantic-conventions/blob/main/model/geo/registry.yaml#L59-L70)) are stored as separate attributes in ES.

### Describe the solution you'd like

They should be mapped as [geo_point](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html).

**Comment by carsonip** [comment]
@felixbarny @gregkalapos
- should `geo.location.lon` and `geo.location.lat` be removed after creating a new `geo.location` from the two of them?
- WDYT about using the format `Geopoint expressed as a [Well-Known Text](https://docs.opengeospatial.org/is/12-063r5/12-063r5.html) POINT with the format: "POINT(lon lat)"` in https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html ?

**Comment by felixbarny** [comment]
> should geo.location.lon and geo.location.lat be removed after creating a new geo.location from the two of them?

Hm, I think so, yes. We're not losing information by combining them.

> WDYT about using the format Geopoint expressed as a [Well-Known Text](https://docs.opengeospatial.org/is/12-063r5/12-063r5.html) POINT with the format: "POINT(lon lat)" in https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html ?

An advantage of that could be that it's easier to auto-detect geo fields without having to rely on naming conventions. But that would also require SemConv to adopt that format. The disadvantage is that it's more heavy in terms of bandwidth and storage, especially for backends that don't have native support for geo points. They'd need to store it as a string rather than an array of double values.

So overall, I'd lean towards storing it similar to Well-Known-Text, but as a double array (`[lon, lat]`).

We could then either introduce a naming convention (`*.geo.location`) or introduce type hints in OTLP.

**Comment by carsonip** [comment]
> We're not losing information by combining them.

I haven't tried, but will querying for `geo.location.lon` return the same value after merging `lon` and `lat` into `geo.location`?

**Comment by gregkalapos** [comment]
> @felixbarny @gregkalapos
> 
> * should `geo.location.lon` and `geo.location.lat` be removed after creating a new `geo.location` from the two of them?

Yeah +1 on not storing those - also nice to see, we still can query only one if needed.

> * WDYT about using the format `Geopoint expressed as a [Well-Known Text](https://docs.opengeospatial.org/is/12-063r5/12-063r5.html) POINT with the format: "POINT(lon lat)"` in https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html ?

In which layer do you mean? If we really want to introduce that to attributes, then that'd be a new data type, so I'm with Felix on this, that'd be very hard with little benefit. But the ES exporter is still free to ingest it in whatever format we feel best from https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html.

**Comment by carsonip** [comment]
> In which layer do you mean?

I've ended up implemented using [lon, lat] in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36594 . Felix made a good call about storage size.
