### ISSUE TITLE
Open Telemetry Issue in asp.net core

### ISSUE THREAD

**Issue by muneernet** [open-telemetry/opentelemetry-collector-contrib#3656]
I Have installed the opentelemetry-collector-contrib as windows service here is the configuration file .

# # receivers:
  # # otlp:
    # # protocols:
      # # grpc:
      # # http:

# # processors:
  # # batch:

# # exporters:
  # # otlp:
    # # endpoint: otelcol:55680
  # # datadog:
     # # service: SampleDataDog.exe
     # # api:
       # # key: "6ca8109dcba5f9420f0ec55c342fc0df"

# # extensions:
  # # health_check:
  # # pprof:
  # # zpages:

# # service:
  # # extensions: [health_check,pprof,zpages]
  # # pipelines:
    # # traces:
      # # receivers: [otlp]
      # # processors: [batch]
      # # exporters: [datadog]
    # # metrics:
      # # receivers: [otlp]
      # # processors: [batch]
      # # exporters: [datadog]
    # # logs:
      # # receivers: [otlp]
      # # processors: [batch]
      # # exporters: [datadog]

# receivers:
  # otlp:
    # protocols:
      # grpc:

# processors:
  # batch:
    # timeout: 10s
# exporters:
  # datadog:
    # service: sampledatadog.exe
    # api:
      # key: "6ca8109dcba5f9420f0ec55c342fc0df"
      # site: datadoghq.eu
    # # traces:
      # # sample_rate: 1
      # # endpoint: https://api.datadoghq.com
    # # - type : file (mandatory) type of log input source (tcp / udp / file)
    # #   port / path : (mandatory) set port if type is tcp or udp. set path if type is file
    # #   service : (mandatory) name of the service owning the log
    # #   source : (mandatory) attribute that defines which integration is sending the log
    # #   sourcecategory : (optional) multiple value attribute. can be used to refine the source attribute
    # #   tags: (optional) add tags to each log collected

    # # - type: file
        # # path: c:\users\mshaik\source\repos\sampledatadog\sampledatadog\bin\debug\application-logs.json
        # # service: sampledatadog.exe
        # # source: csharp
        # # sourcecategory: sourcecode  
# service:
  # pipelines:
    # traces:
      # receivers: [otlp]
      # processors: [batch]
      # exporters: [datadog/api]

receivers:
  otlp:
    protocols:
      grpc:
      http:
       # endpoint:"https://localhost:44310/"

processors:
  batch:
    timeout: 1s
exporters:
  datadog/api:
    hostname: IN46TAAL0615XJ
    api:
      key: "6ca8109dcba5f9420f0ec55c342fc0df"
      
      
      # site: datadoghq.eu
      
    # traces:
      # sample_rate: 1
      # endpoint: https://trace.agent.datadoghq.com

    # tags:
      # - geo.country:fr

    
      
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/api]

Now i am using .net core application using open telemetry exporter to export my tarces to data dog .

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;
using OpenTelemetry;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace app2
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllers();
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "app2", Version = "v1" });
            });
            services.AddOpenTelemetryTracing(
                (builder) => builder
                    .SetResourceBuilder(
                          ResourceBuilder.CreateDefault().AddService("example-app2"))
                    .AddAspNetCoreInstrumentation()
                    .AddConsoleExporter()
                    .AddOtlpExporter(opt =>
                    {
                        opt.Endpoint = "http://localhost:55680";
                    })
                    );
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "app2 v1"));
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}

But am not able to see my tarces on the data dog and error also how do i debug and verify the issues.

**Comment by ericmustin** [comment]
hi @muneernet this sounds like an issue with your dotnet instrumentation, i would ask over in https://github.com/open-telemetry/opentelemetry-dotnet . Can you confirm traces are reaching the collector? If you add a `logging` exporter to your pipeline you can verify this.

One thing that stands out is you should confirm  whether `"http://localhost:55680"` is the right endpoint here, and not 4317.

Also you are consistently posting sensitive information in these issues. please remove and update your keys.

**Comment by mx-psi** [comment]
@muneernet did you get to solve your issue? If not, can you look at Eric's message above?

**Comment by codeboten** [comment]
Closing this issue as there has been no response from the author. If the issue persist, please re-open with the additional information requested
