### ISSUE TITLE
[pprof] - Save heap profile to the file on `Shutdown`

### ISSUE THREAD

**Issue by VihasMakwana** [open-telemetry/opentelemetry-collector-contrib#36576]
### Component(s)

extension/pprof

### Is your feature request related to a problem? Please describe.

Currently, there is no straightforward way to get heap profile of the collector right before it gets terminated. Same functionality exists for CPU. 
It would be highly beneficial to have the ability to write the heap profile to a file at that point.

### Describe the solution you'd like

`runtime/pprof` has a function, `WriteHeapProfile`, that saves current heap profile to the file. We can introduce a config for this, similar to what we do for CPU profile.

**Comment by VihasMakwana** [comment]
@MovieStoreGuy when you have a moment, can you take a look at it?

**Comment by atoulme** [comment]
heap profile on shutdown? But everything is shut down then? What are you hoping to capture?

**Comment by VihasMakwana** [comment]
I think I misunderstood the shutdown sequence. 
You're right. If we want to save heap profile, we need to save it right before shutdown and not in extension. The extensions are last in line when it comes to shutdown and all the relevant components will already be shut. I'll try to find a place for this feature.

**Comment by MovieStoreGuy** [comment]
It sounds like you almost want Continuous Profiling_ or _Always On Profiling_ which will take snapshots of the application throughout its lifetime.
