### ISSUE TITLE
[Feature]attributesprocessor supports keeping only the matching fields

### ISSUE THREAD

**Issue by tttoad** [open-telemetry/opentelemetry-collector-contrib#36620]
### Component(s)

processor/attributes

### Is your feature request related to a problem? Please describe.

I want to keep only some of the fields in the attribute, such as those starting with ‘abc’ or ‘def’.

### Describe the solution you'd like

attributesprocessor supports reserved actions, reserved fields by regular matching.

**Comment by VihasMakwana** [comment]
@tttoad have you considered `pattern`? If possible, can you share your config and use case?

**Comment by tttoad** [comment]
> @tttoad have you considered `pattern`? If possible, can you share your config and use case?

You mean `RegexPattern ` ? `regexp`  does not support syntax like `^(?<!abc)`. 
attributes{ "db":"*" ,"any":"*" .... ,"abc":"*"} , I just want to keep `abc`.

**Comment by VihasMakwana** [comment]
@tttoad wouldn't something like following work, using [include feature](https://github.com/codeboten/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor#includeexclude-filtering)?

```yaml
attributes:
   match_type: strict
   include:
     attributes:
       - key: abc
```

**Comment by tttoad** [comment]
> @tttoad wouldn't something like following work, using [include feature](https://github.com/codeboten/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor#includeexclude-filtering)?
> 
> ```yaml
> attributes:
>    include:
>      match_type: strict
>      attributes:
>        - key: abc
> ```

@VihasMakwana  Error: attributes: missing required field "actions".
If I understand correctly, include just selects the Span to be processed.

**Comment by VihasMakwana** [comment]
Oh! I misunderstood the configs.

Anyway, can you take a look at https://github.com/codeboten/opentelemetry-collector-contrib/tree/main/processor/transformprocessor? It has `keep_keys`.

**Comment by VihasMakwana** [comment]
@tttoad does that help resolve the issue you were having?

**Comment by tttoad** [comment]
> @tttoad does that help resolve the issue you were having?

Yes, it can work. Thank you.
