### ISSUE TITLE
Extract githubgen to opentelemetry-go-build-tools

### ISSUE THREAD

**Issue by mowies** [open-telemetry/opentelemetry-collector-contrib#36691]
### Component(s)

cmd/githubgen

### Describe the issue you're reporting

Since the `cmd/githubgen` tool will soon be used in https://github.com/open-telemetry/opentelemetry-collector (see https://github.com/open-telemetry/opentelemetry-collector/pull/11756), I propose to move the tool to https://github.com/open-telemetry/opentelemetry-go-build-tools/ so that it can be maintained in a more central place.

The tool would also need to be slightly parameterized to be able for it to work for both collector-core and -contrib (e.g. file templates shall be configured from the outside and an ignore list would also be helpful to be able to ignore test components for example).

**Comment by atoulme** [comment]
Sounds good to me.

**Comment by mowies** [comment]
Cool! I'll start working on this.
