### ISSUE TITLE
[Failed test][cmd/opampsupervisor] TestSupervisorStopsAgentProcessWithEmptyConfigMap constantly failed

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#36764]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

E.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12257185021/job/34195668020

```
    e2e_test.go:1351: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/e2e_test.go:1356
        	            				C:/Users/runneradmin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.windows-amd64/src/runtime/asm_amd64.s:1695
        	Error:      	An error is expected but got nil.
    e2e_test.go:1351: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/e2e_test.go:1351
        	Error:      	Condition never satisfied
        	Test:       	TestSupervisorStopsAgentProcessWithEmptyConfigMap
```

**Comment by pjanotti** [comment]
Another hit https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12262901594/job/34213584856#step:8:791

**Comment by bacherfl** [comment]
I think I have found the reason for that - My recent PR (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35892) introduced a change to the opamp agent to listen for status updates for the individual components, and it seems like in the shutdown function of the opamp agent there is a channel that is not properly closed. I'm already working on a fix and should have a PR ready today
