### ISSUE TITLE
GoogleCloudExporter: Metric with too many labels should be dropped, not exported & retried

### ISSUE THREAD

**Issue by tmodelsk** [open-telemetry/opentelemetry-collector-contrib#3677]
**Describe the bug**
GPC Monitoring has limit for number of labels for metric = [max 10 labels per metric descriptor](https://cloud.google.com/monitoring/quotas). 
GoogleCloudExporter is trying to : 
- unnecessarily export such metrics (always rejected by GCP monitoring api)
- retries exporting of previously failed metrics with too many labels (if retry_on_failure is enabled)

This can lead to v. high memory consumption when there's even small ( < 1 %) but constant flow of such corrupted metrics.
( See: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3676 )

**Steps to reproduce**
Metric pipeline example: prometheus receiver > googleCloudExporter
Feed prometheus receiver with metric with more than 10 labels, ex: 
```
# HELP tm_metric_g_3 Custom Metric 3 Name
# TYPE tm_metric_g_3 gauge
tm_metric_g_3{i="3", j="1", l3="3", l4="4", l5="5", l6="6", l7="7", l8="8", l9="9", l10="10",  l11="11"}  9999
```

**What did you expect to see?**
GoogleCloudExporter should drop metrics with more than 10 labels before exporting to GCP monitoring, because such metric's export will 100% fail. 
Also, such 'failed' metrics should not be exported again when retry_on_failure is enabled. 
Or there should be some processor to filter out such metrics with > 10 labels. 

**What did you see instead?**
Metrics with > 10 labels are unnecessarily exported to GCP monitoring & then always rejected by GPC api.
Also such failed metrics are retried to export when retry_on_failure is enabled. 

**What version did you use?**
v0.24

**Additional context**
Fixing this one could partially mitigate another issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3676 
_(GoogleCloudExporter: retry_on_failure on single metric failure : whole batch is exported again)_

**Comment by tmodelsk** [comment]
I've made simple fix on our fork with additional config setting: labels_limit . 
It works fine, if labels_limit is set (ex 10) it will drop such metrics from batch. 
https://github.com/SabreOSS/opentelemetry-collector-contrib/commit/8201531c81fe29297c98f1b6b4ab569c1fb7a3be 
IMO its missing one feature: to report dropped metrics as otelcol_exporter_send_failed_metrics_points (increment this with each dropped metric)
Now I'm just logging this 'event' to console.

**Comment by dashpole** [comment]
The limit has since been updated to 30 labels.  It can also differ per-metric-domain (the prefix on metrics), which is why we generally don't try to enforce the API's limits.  Sorry I didn't see this until now.

I agree that correctly using retry_on_failure is what we should be doing.
