### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by Faig92** [open-telemetry/opentelemetry-collector-contrib#36890]
Hi, everyone!

I"m facing with this error while trying scrape logs from rancher audit logs (using otel operator) :

2024-12-18T14:41:27.020Z	error	fileconsumer/file.go:189	Failed to open file	{"kind": "receiver", "name": "filelog/2", "data_type": "logs", "component": "fileconsumer", "error": "open /var/lib/rancher/rke2/server/logs/audit.log: permission denied"}

    receivers:
      filelog/2:
        include:
          - /var/lib/rancher/rke2/server/logs/audit.log
        include_file_path: true
        include_file_name: true
        start_at: end
        operators:
          - type: json_parser
            id: parse_rancher_audit
            timestamp:
              parse_from: body.stageTimestamp
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
              
       exporters:
      loki:
        endpoint: 

    service:
      pipelines:
        logs:
          receivers: [filelog/2]
          processors: []
          exporters: [loki]

Volumes wich i use in config   

volumes:
  - name: auditlogs
    hostPath:
      path: /var/lib/rancher/rke2/server/logs
  volumeMounts:      
    - name: auditlogs
      mountPath: /var/lib/rancher/rke2/server/logs
      readOnly: true
          
Any clue how to resolve this?

**Comment by songy23** [comment]
Moved to contrib since this is on file log receiver

**Comment by bacherfl** [comment]
Hi @Faig92! Can you also provide the spec of the collector Pod where the hostVolume is mounted? One thing to check there might be if the `securityContext` of the pod is set up properly, as this defines the access privileges for the containers within the pod - for more info see https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod

**Comment by Faig92** [comment]
@bacherfl 
I have removed sensitive data, but in general, it looks like this:

```
spec:
  volumes:
    - name: otc-internal
      configMap:
        name: otel-cluster-logs-collector
        items:
          - key: collector.yaml
            path: collector.yaml
        defaultMode: 420
    - name: varlogpods
      hostPath:
        path: /var/log/pods
        type: ''
    - name: auditlogs
      hostPath:
        path: /var/lib/rancher/rke2/server/logs
        type: ''
    - name: kube-api-access-****
      projected:
...
...
        defaultMode: 420
  containers:
    - name: otc-container
      image: docker-proxy.service.core/otel/opentelemetry-collector-contrib:0.93.0
      args:
        - '--config=/conf/collector.yaml'
      ports:
        - name: metrics
          containerPort: 8888
          protocol: TCP
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
      resources: {}
      volumeMounts:
        - name: otc-internal
          mountPath: /conf
        - name: varlogpods
          readOnly: true
          mountPath: /var/log/pods
        - name: auditlogs
          mountPath: /var/lib/rancher/rke2/server/logs
...
...
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: otel-cluster-logs-collector
  serviceAccount: otel-cluster-logs-collector
  nodeName: master-0
  shareProcessNamespace: false
  securityContext: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchFields:
              - key: metadata.name
                operator: In
                values:
                  - master-0
  schedulerName: default-scheduler
  tolerations:
...
...
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority

**Comment by bacherfl** [comment]
Thanks for the info - it seems like the `securityContext` of the pod is empty, so that may be a potential explanation for the permission issue. Can you try to edit the deployment to specify the security context, e.g. as in https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod ?

**Comment by Faig92** [comment]
@bacherfl We discussed with colleagues about this case and decided solve this issue on OS level.
THX!
