### ISSUE TITLE
Consider merging awsemfexporter and awscloudwatchlogsexporter

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector-contrib#3697]
**Is your feature request related to a problem? Please describe.**
As of today, Cloud Watch metrics export is available via the awsemfexporter, and we are working on a Cloud Watch logs exporter (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3453). This is confusing to our users not just because they are split exporters but also "EMF" is not very well recognized and not every user can easily tell by name it's the canonical metrics exporter for CW.

**Describe the solution you'd like**
To improve the visibility issue and the burden of setting up two exporters, we can introduce a new exporter, cloudwatchexporter, as a composite exporter in the future. We don't want to take any actions right now until the awscloudwatchlogsexporter is stable.

This is a long-term tracking bug.

**Comment by rakyll** [comment]
cc @alolita @mxiamxia

**Comment by aateeqi** [comment]
@alolita can you assign me to this?
