### ISSUE TITLE
Extract API from internal/stanza

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#3744]
**Is your feature request related to a problem? Please describe.**
The `internal/stanza` package allows one to easily build a log receiver from an [otel-log-col](https://github.com/open-telemetry/opentelemetry-log-collection) operator. However, because it is an internal package, it cannot be used outside of the contrib collector.

**Describe the solution you'd like**
Extract an API from the package. This would likely include most, but not necessarily all of:
- [internal/stanza/factory.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/stanza/factory.go)
- [internal/stanza/config.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/stanza/config.go)

**Key questions to answer**
1. Is such a change acceptable to the maintainers?
2. Where should a new package be created? (maybe `receiver/logreceivercreator`?)
3. This API is likely to change. Is it sufficient to mark the package as experimental?

**Additional context**
#3734

**Comment by AJ-54** [comment]
Hi, Are there any updates on this?

**Comment by djaglowski** [comment]
I believe this has been solved in spirit by [`pkg/stanza/adapter`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/stanza/adapter).
