### ISSUE TITLE
Allow to specify resource label as 'from_attribute' in routingprocessor

### ISSUE THREAD

**Issue by maxsivkov** [open-telemetry/opentelemetry-collector-contrib#3746]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently *from_attribute* can reference http header only. Allowing to specify resource label (from the ResourceSpansSlice struct) as *from_attribute* allows to route traces based on attributes gathered earlier. For example to route trace to specific exporter based on a pod name (gathered by *k8sprocessor*)

**Describe alternatives you've considered**
Cannot find out any

**Additional context**
Each resource should be processed individually based on a resource's attribute value.
In this case batching will not work.
may be we need to introduce additional parameter like *attribute_source* with values _FromHeader_ and _FromResource_.

Currently I am studying opentelemetry, so I may be wrong with terminology.
with 'resource attributes' I mean attribute from the following map
https://github.com/open-telemetry/opentelemetry-collector/blob/c71f5bbe77492603f52a19a857d5db3de3bce2d3/consumer/pdata/generated_resource.go#L47

**Comment by pmalek-sumo** [comment]
@maxsivkov 👋 

Haven't https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5694 and https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5869 covered what you've described above?

**Comment by kovrus** [comment]
@maxsivkov The routing processor is able to do that with both conventional configuration and OTTL statements, see [Readme](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor#tech-preview-opentelemetry-transformation-language-statements-as-routing-conditions). 

@jpkrohling can you please close the issue?
