### ISSUE TITLE
The Repo Doesn't Build

### ISSUE THREAD

**Issue by Aditya-Gollapudi** [open-telemetry/opentelemetry-collector-contrib#3795]
The repo won't build from lib or from tree after the most recent pull. I'm on Mac if that matters. The error is the following: processor/metricstransformprocessor/operation_scale_value.go:24:110: op.configOperation.Scale undefined (type Operation has no field or method Scale)
processor/metricstransformprocessor/operation_scale_value.go:26:98: op.configOperation.Scale undefined (type Operation has no field or method Scale)

I'm doing sudo make otelcontribcol from my terminal (zsh)

**Comment by mx-psi** [comment]
Hi, can you double check that you are on the right branch? 4906c262cf9a833059973acb059dbbf2ab29a3f7 builds correctly for me (and it also builds on CI)

**Comment by Aditya-Gollapudi** [comment]
I'm on the main branch with the most recent commit being 9c6bc6e00097d81ac59528d4b03fae88f26bb4f6 by Bogdan. 

After doing another fresh clone and redownloading al the dependencies building from lib works but building from tree still fails (although with a different error)

GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ./bin/otelcontribcol_darwin_amd64 \
		-ldflags "-X github.com/open-telemetry/opentelemetry-collector-contrib/internal/version.GitHash=9c6bc6e00 -X github.com/open-telemetry/opentelemetry-collector-contrib/internal/version.Version=v0.28.0-46-g9c6bc6e00 -X go.opentelemetry.io/collector/internal/version.BuildType=release" ./cmd/otelcontribcol
# go.opentelemetry.io/collector/receiver/kafkareceiver
../opentelemetry-collector/receiver/kafkareceiver/zipkin_unmarshaler.go:90:41: not enough arguments in call to transport.ReadListBegin
	have ()
	want (context.Context)
../opentelemetry-collector/receiver/kafkareceiver/zipkin_unmarshaler.go:100:19: not enough arguments in call to zs.Read
	have (*thrift.TBinaryProtocol)
	want (context.Context, thrift.TProtocol)
# go.opentelemetry.io/collector/receiver/jaegerreceiver
../opentelemetry-collector/receiver/jaegerreceiver/trace_receiver.go:409:20: not enough arguments in call to tdes.Read
	have (*"github.com/jaegertracing/jaeger/thrift-gen/jaeger".Batch, []byte)
	want (context.Context, thrift.TStruct, []byte)
make: *** [otelcontribcol] Error 2


because it is only a local tree error it's possible there's some issue with my local ENV although I'm not sure what that would be

**Comment by codeboten** [comment]
I couldn't reproduce this building from `main`, is it still a problem?

**Comment by Aditya-Gollapudi** [comment]
It was a problem with my local env
