### ISSUE TITLE
Documentation to export to DataDog Agent (docker)

### ISSUE THREAD

**Issue by neoaisac** [open-telemetry/opentelemetry-collector-contrib#3804]
Looking at documentation both in the OpenTelemetry Collector and in the DataDog Agent sites, it seems that there is a possibility of either using the OpenTelemetry Collector to send data directly to DataDog's cloud, or to run a local DataDog Agent but bypass OpenTelemetry (use native integration with DataDog).

How would one go about using OpenTelemetry to export application traces in an open format, and then use the Collector to send this to a local DataDog Agent, which would then send the logs to the cloud?

Context:
- My application is in .NET Core 5.0, using OpenTelemetry for observability and Logs.
- Ideally I don't want to use any vendor-specific libraries, so if we wanted to change DataDog for another vendor solution we could without changing much (or anything) in the codebase.
- I want to be able to test the structure locally, using `docker` and `docker compose`.

Alternatives:
- We could be sending OpenTelemetry information directly to the DataDog Agent, if the Agent had a OTEL-friendly interface. Is this available?

**Comment by pratimsc** [comment]
It will be great if someone from Datadog can provide an answer to this. 
This is a good pattern which allows all the apps to use the OTEL API to export the traces and metrics to using OTEL client to OpenTelemetry (Agent or Collector) and the Collector can send it to existing DataDog agents install in the Kubernetes cluster. 

App OTEL Client --> OTEL Agent/Collection --> DD Agent --> DD Remote/Cloud Server

DD Agents are typically installed by the Infrastructure team, and App team does not have to learn about DD but just use the OTEL Client APIs.

**Comment by ericmustin** [comment]
👋 The upcoming release of the datadog-agent (v7.30) will include experimental support for OTLP for Traces. I can update on this issue when it's out. 

OTLP support in the datadog-agent for Metrics and Logs is on the roadmap but we have no timeline at this time. 

Upon the next release, the support for OTEL and datadog will include:

1. > App OTEL Client --> OTEL Agent/Collection --> DD Remote/Cloud Server
2. > App OTEL Client --> DD Agent --> DD Remote/Cloud Server
3. > App Datadog Client --> DD Agent --> DD Remote/Cloud Server

That being said, I suppose technically you could do the following:

> App OTEL Client --> OTEL Agent/Collection --> DD Agent --> DD Remote/Cloud Server

By enabling OTLP export on the Otel agent/collector, but I'm not sure the use case for end users there as it would involve deploying more infra and resources associated with that infra than simply choosing one of the previous 3 options listed above.

Does that help?

**Comment by pratimsc** [comment]
Thanks @ericmustin.

Do you have any example for :
`App OTEL Client --> DD Agent --> DD Remote/Cloud Server`
Is it by using https://github.com/Datadog/dd-opentelemetry-exporter-js , for NodeJS application? 
The advice from Datadog is to move away from it, as go the OTEL Agent/Collector route (ref: https://github.com/DataDog/dd-opentelemetry-exporter-js/issues/15)

I agree that both 1 and 2 (if 2 is still officially supported) would less infra, but when it comes to a Kubernetes based infra with multiple different app team working (and a central Infra) it become difficult to meet requirement of every app team. 
 
For the, option 4. `App OTEL Client --> OTEL Agent/Collection --> DD Agent --> DD Remote/Cloud Server`, the responsibility is : 
- App OTEL Client  -> App Team
- OTEL Agent Collection -> App Team (injected as sidecar, to K8s pod)
- DD Agent -> Infra Team (installed as Daemon on K8s nodes)
- DD Remote/Cloud Server -> Infra team (non-tech management) + Data Dog

The 4th pattern allows team to use different pipelines and importers, as well. It especially helps when there are existing apps exporting traces+metrics using Zipkin and Jaeger client. From app team perspective, they do not have to re-write their code - which can be chunkier effort based on the app design. And all the traces can still hit DataDog.

**Comment by gumshoe2020** [comment]
We are looking at this same problem now.  
> That being said, I suppose technically you could do the following:
> 
> > App OTEL Client --> OTEL Agent/Collection --> DD Agent --> DD Remote/Cloud Server
Is there any documentation on how to get this to work in the interim? What kind of keyword are we looking for?  "OpenTelemetry Collector Forwarding"?

**Comment by ericmustin** [comment]
-----

@gumshoe2020 @pratimsc Per my previous response

> The upcoming release of the datadog-agent (v7.30) will include experimental support for OTLP for Traces. I can update on this issue when it's out.

So, when [that work](https://github.com/DataDog/datadog-agent/pull/8079) is released, we'll also release documentation and examples for

> App OTEL Client --> DD Agent --> DD Remote/Cloud Server

It's not out yet, ideally in the next week or two it should be out and I can update this issue then. 

I hope that's clear enough for now. I don't work on the same team as the datadog-agent folks so I can't give more specifics than that unfort, but as soon as this is released I can provide more info. feel free to reach out to `support@datadoghq.com` if you have other Qs, that's the best way to ensure your specific use case  is heard  and taken into account.

-----

@pratimsc Regarding your  use case, I appreciate the explanation of how your org handles different areas of responsibility. I guess i'm confused why option `(1)` doesn't address your requirements  as well, as the OpenTelemetry-Collector  itself allows multiple pipelines, with various receivers/processors/exporters.

From docs: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md

![ex](https://github.com/open-telemetry/opentelemetry-collector/raw/main/docs/images/design-processors.png).

That being said, If you wanted to additionally run the datadog-agent or an opentelemetry-collector-as-service as daemon on k8 nodes both those options would technically be possible (you would simply enable your otel-collector-as-agent's `otlp` exporter to the appropriate host/port), or you could simply export directly from otel-collector-as-agent to datadog. We hadn't planned to document this 4th path using a datadog-agent, but if there's interest in it I don't see why not. I'll have to touch base with some folks internally to see if there's any concerns around tagging or billing that could arise from this setup.

-----

Again, just to recap, any otel tracing pathways involving the datadog-agent are not released yet. It _will be soon_, i believe, with _experimental_ support. We'll ping on here when that's out.

Hope that helps, cheers.
Eric

**Comment by gumshoe2020** [comment]
>I hope that's clear enough for now. I don't work on the same team as the datadog-agent folks so I can't give more specifics than that unfort, but as soon as this is released I can provide more info. feel free to reach out to support@datadoghq.com if you have other Qs, that's the best way to ensure your specific use case is heard and taken into account.
Yep, I can do that, thanks!

**Comment by gumshoe2020** [comment]
It looks like this got merged: https://github.com/DataDog/datadog-agent/pull/8079
Any outlook on when 7.30.0 is going to be released?

**Comment by ericmustin** [comment]
@gumshoe2020 coming weeks, the test and release process for the agent has some variability so it's hard to be more specific than that. I can absolutely ping this thread when it's out though.

**Comment by gumshoe2020** [comment]
Thanks, we will begin integrating and testing it now.  I'll let our Datadog CSM know too.

**Comment by gumshoe2020** [comment]
Question for you, where is the `experimental` tag supposed to go in the `datadog-agent-daemonset.yaml`?

**Comment by ericmustin** [comment]
@gumshoe2020 i think you could either set the env vars in the Daemonset container spec, or it would be (i think, i usually use env vars) top level in the yaml file, per: https://github.com/DataDog/datadog-agent/blob/edc9a3076e9869008a551cd0fa7c43121de1e545/pkg/trace/config/testdata/full.yaml#L70-L73

**Comment by pratimsc** [comment]
@ericmustin  - Any timelines on when this feature in *Datadog-Agent v7.30 * will be promoted to Mainstream from experimental. 

This meets our requirement. Sadly, in my present organisation the tag of experimental is makes it a difficult sell in prod env.

**Comment by ericmustin** [comment]
No timeline at this time, off the top of my head i'd say it will probably be at least 1, if not 2, more datadog-agent releases before anything here is marked GA on our side. The Datadog-agent doesn't have a set release schedule, but back of envelope i'd say there's usually a month or two between releases.  Again, for those interested, please sync with `support@datadoghq.com` for tracking. 

Anyways as a side note this is my last week as an employee of datadog so `support@datadoghq.com` will be the best place to stay up to date on this.

**Comment by mx-psi** [comment]
If you want to export OTLP metrics and traces to the Datadog Agent, you can now do so via OTLP ingest. You can read more details about it [here](https://docs.datadoghq.com/tracing/setup_overview/open_standards/otlp_ingest_in_the_agent/?tab=host).

I am closing this issue since this use case is supported by the OTLP ingest feature. For issues related to or help with the Datadog Agent OTLP ingest, please [contact Datadog support](https://www.datadoghq.com/support/) (prefered) or open an issue over at [the Datadog Agent repository](github.com/DataDog/datadog-agent/), thanks!
