### ISSUE TITLE
Add operators config block to `tcplog` receiver 

### ISSUE THREAD

**Issue by ttomsu** [open-telemetry/opentelemetry-collector-contrib#3805]
**Describe the solution you'd like**
Much like the `operators` block in the [filelog receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver#operators), it'd be really nice to reuse all the operators from `opentelemetry-log-collection` on the tcplog input.

cc @djaglowski

**Comment by djaglowski** [comment]
Good new, I believe this is just a documentation issue. See #3806
