### ISSUE TITLE
[exporters/splunkhec] TraceID and SpanID aren't included in log events

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector-contrib#3807]
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fa68c59476a33009aecbb925d4f1304e95d6e3ec/exporter/splunkhecexporter/logdata_to_splunk.go#L41

@breedx-splk reports neither `TraceID` nor `SpanID` on the `LogRecords` are sent. Need to decide what to name them in the HEC field.

@tigrannajaryan thoughts on naming these for the HEC output? I didn't see a semantic convention for them since I guess they're part of the record itself.

**Comment by breedx-splk** [comment]
Hey @jrcamp the current thought is to [follow the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/overview.md#trace-context-in-legacy-formats) and use underscores. Cool?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan thoughts on naming these for the HEC output? I didn't see a semantic convention for them since I guess they're part of the record itself.

See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/overview.md#trace-context-in-legacy-formats
