### ISSUE TITLE
k8sprocessor: observability test can fail if CI is too slow to export metrics in time. Probably should increase the timeout.

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector-contrib#387]
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/1595/workflows/adfe6fa8-3d48-43ba-ac2d-97f5a2ea1b07/jobs/5820

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/1595/workflows/76baf0c0-35d9-4ab3-bbf1-68a38049a847/jobs/5807

**Comment by andrewhsu** [comment]
from the issue triage meeting today, looks like this issue is old and has not been observed as of late. closing this, but if it's still a problem feel free to reopen.
