### ISSUE TITLE
Some components are missing CODEOWNERS

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#3870]
Some components do not have owners listed on CODEOWNERS; this makes it hard to have someone to ping in case we need something.

The list of components missing a CODEOWNER is available [**here**](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/ALLOWLIST).

If you want to maintain any of these components, please **open a PR** to add yourself as a CODEOWNER and remove the component from the allowlist file. Check the [contributing guidelines](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner) to ensure you are eligible to own a component.

**Comment by Aneurysm9** [comment]
I can be listed as an owner for `receiver/awscontainerinsightreceiver`.  Seeking to confirm a second engineer and will update this comment when I've done so.

**Comment by pavankrish123** [comment]
I am fine being owner for `extension/oauth2clientauthextension` once #3848 is merged. Thanks.

**Comment by mx-psi** [comment]
I updated the list based on the output from #4137

**Comment by codeboten** [comment]
Updated the listed components as of f7e2459cc215ab6273ed8e9b4dbf0c94c73faf91

**Comment by dmitryax** [comment]
I can take the following:
- receiver/fluentforwardreceiver
- receiver/zookeeperreceiver
- internal/kubelet

**Comment by bogdandrutu** [comment]
@dmitryax please do a PR :)

**Comment by boostchicken** [comment]
exporter/awscloudwatchlogsexporter I am an AWS expert, I can handole that I am sure

**Comment by mx-psi** [comment]
Updated the list as of 42a06f91316730473b00cee4284acaddd88bd3ff, there are a lot of components with no codeowner after we moved them from core to contrib

**Comment by jpkrohling** [comment]
@pavolloffay, as the original author of the `kafkaexporter`, would you be open to being its code owner?

https://github.com/open-telemetry/opentelemetry-collector/pull/1439

**Comment by pavolloffay** [comment]
I can take care of it

**Comment by bogdandrutu** [comment]
@mx-psi don't let people to have second thoughts :)) when they say yes for a component, quickly add them to the list.

**Comment by MovieStoreGuy** [comment]
I am happy to be added as a code owner for kafka.

**Comment by jpkrohling** [comment]
@djaglowski, should we add you as the owner for the storage extension, or perhaps just file storage extension?

**Comment by djaglowski** [comment]
I'm happy to be code owner on filestorage. The storage interface is defined as [experimental in the core collector](https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/experimental/storage), and just duplicated here, so not sure it needs an owner really. If it does, I can take it as long as it's clear that I'm not necessarily owner on other storage extensions that may be added in the future.

**Comment by pmm-sumo** [comment]
I can help with following, if still available:

 - exporter/fileexporter
 - exporter/zipkinexporter
 - processor/attributesprocessor
 - processor/filterprocessor
 - processor/spanprocessor
 - receiver/journaldreceiver
 - receiver/zipkinreceiver

**Comment by codeboten** [comment]
Thanks @pmm-sumo, please review https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7774

**Comment by MovieStoreGuy** [comment]
If it would help, I am happy to be assigned additional components. I more than likely haven't worked on it, but I do keep a high standard of ensuring it will continue working.

**Comment by mx-psi** [comment]
@MovieStoreGuy feel free to open a PR with the components for which you want to be added as a CODEOWNER!

**Comment by Xunzhuo** [comment]
Hi, I am new here, I am experienced with telemetry and also one of the maintainers in istio, contributing to Extension and Telemetry in Istio. I want to know that if I want to help forks and to be some components` code owner, what requirements should I meet? Should I become OpenTelemetry member first or something else, need some guidelines, thanks!

**Comment by mx-psi** [comment]
@Xunzhuo you need to make some contributions to the project before becoming a CODEOWNER of any component. I don't think being an OpenTelemetry member is _required_ for being an owner, but I would recommend it in any case (see [here](https://github.com/open-telemetry/community/blob/main/community-membership.md) for details).

**Comment by garry-cairns** [comment]
I'm intending to use the influxdbexporter in production but not the receiver. Since it's currently unmaintained I'd be keen to be the owner there but I'm not currently a contributor (and for good reason since I don't know go yet). Is there a path for me to become the owner there or should I try to help find someone more suitable?

**Comment by jpkrohling** [comment]
A code owner is supposed to fix bugs in the code for the component. It also helps to be part of the community by having reviewed PRs and contributing with bug fixes, preferably for the components you want to become a code owner.

**Comment by mx-psi** [comment]
I opened #16174 that will close this issue :tada: 

The rest of components not in CODEOWNERs are either unmantained, deprecated or are packages with common functionality used by many components. We can have a discussion in the future about the common components, but I don't think this issue is the proper way of doing it.
