### ISSUE TITLE
Silent awsxrayexporter problems does not allow debugging (maybe is a bug not a feature, not sure)

### ISSUE THREAD

**Issue by rodrigo-garcia-edo** [open-telemetry/opentelemetry-collector-contrib#3878]
**Is your feature request related to a problem? Please describe.**
I am trying to configure otel-collector awsxrayexporter to send traces to XRay but it silently fails (basically it looks like it works without any console debug errors or http://localhost:55679/debug/tracez logs available)

Note1: using AWS-CLI xray service with the same credentials works fine and a trace is generated.
Note2: I also have a OLTP exporter to tempo backend and traces are received correctly on this backend.

**Describe the solution you'd like**
I would like to be able to debug what is being requested and what is being responded (or a way to activate it). It would be awesome to see if the request is using properly the AWS_ env variables that i prepared in the container.  Anything but silent would be great.

**Describe alternatives you've considered**
It could be part of tracez logs or part of another kind of debug log.

**Additional context**
Using docker: 

> otel-collector:
>     env_file:
>       - .env
>     image: dev-hub.odigeoconnect.com/dockerhub/otel/opentelemetry-collector-contrib:0.29.0
>     command: [ "--config=/etc/otel-collector-config.yml", "--mem-ballast-size-mib=100" ]
>     volumes:
>       - ./otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
>     expose:
>       - 8888/tcp  # Prometheus metrics exposed by the collector
>       - 55681/tcp # OLTP HTTP receiver
>       - 4317/tcp  # OTLP gRPC receiver
>       - 13133/tcp # Healthcheck
>       - 55679/tcp # zPages
>     ports:
>       - 8888:8888
>       - 13133:13133
>       - 55679:55679
>     restart: on-failure

.env file contains AWS_ env variables to configure region id and secret.

collector-config contains both oltp and the amazon xray exporters and properly pipelined

**Comment by mxiamxia** [comment]
Hi @rodrigo-garcia-edo , can you try enable `debug` logs by updating the `command:` setting in your setup config? AWSXRayExporter seems printing the API response error logs in `debug` mode that's why you feel it failed silently.  

`command: [ "--config=/etc/otel-collector-config.yml", "--mem-ballast-size-mib=100", ""--log-level=DEBUG"]`

**Comment by rodrigo-garcia-edo** [comment]
You are absolutely right Min! I was so focused on the exporter logging log level that i totally missed the log level on the collector.
Thanks a lot!
