### ISSUE TITLE
Flaky test: carbonexporter

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector-contrib#396]
**Describe the bug**
A test sometimes times out on CI, causing failed builds for unrelated PRs.

```
make[2]: Entering directory '/home/circleci/project/exporter/carbonexporter'

running go unit test ./... + coverage in /home/circleci/project/exporter/carbonexporter

coverage: 66.9% of statements

panic: test timed out after 30s



goroutine 87 [running]:

testing.(*M).startAlarm.func1()

	/usr/local/go/src/testing/testing.go:1459 +0x11c

created by time.goFunc
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/1629/workflows/d2507113-df0d-4296-993e-a1561c89176b/jobs/6073

**Steps to reproduce**

Can't since it's flaky :)

**Comment by pcwiese** [comment]
This component is causing continuous issues for everyone submitting PRs. Please prioritize this or remove the failing test.

**Comment by bogdandrutu** [comment]
I think this was fixed in the meantime

**Comment by tigrannajaryan** [comment]
Failed again https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/4053/workflows/7870fef6-1126-488c-ad21-5bb10ab06a8d/jobs/28351
