### ISSUE TITLE
faulty conversion of x-ray to Jaeger

### ISSUE THREAD

**Issue by HashemTaheriSonos** [open-telemetry/opentelemetry-collector-contrib#4036]
**Describe the bug**
I'm exporting traces to both AWS and Jaeger. I set up an otel-collector which receives in the x-ray format and export to Jaeger. The traces are fully shown in the Jaeger but the dependency graph is not showing anything and cannot compute the tree. as I checked that's because these traces, do not have any `references` value set, that's why from the jaeger side [it cannot compute the tree.](https://github.com/jaegertracing/spark-dependencies/blob/1e1507ae3b4f5de90d49e6af27a24288ffab6bd3/jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/SpansToDependencyLinks.java#L77)

so I think the way the traces are getting converted from x-ray format to jaeger might have a bug.

**Steps to reproduce**
use ADOT javaagent with a java app to be able to produce traces in x-ray format
then send these traces to the ADOT collector
from ADOT collector redirect it to an OTEL collector
and from OTEL collector export it to the Jaeger

**What did you expect to see?**
Having a dependency graph (the `references` field of the traces shouldn't be null)

**What did you see instead?**
No dependency graph - the `references` value of spans are zero (null)

**What version did you use?**
OTEL collector 0.28.0
ADOT collector 0.10.0
javaagent - version: 1.2.0-aws
Jaeger 1.22.0

**Comment by anuraaga** [comment]
@alolita This issue seems to be about jaeger exporter so the core repo was appropriate I think

**Comment by HashemTaheriSonos** [comment]
@anuraaga I changed the configuration and removed the `awsxray` as an exporter/receiver between the adot agent and adot collector but as expected didn't solve the issue, and basically didn't make any changes to the traces.

**Comment by HashemTaheriSonos** [comment]
@bogdandrutu I don't know if you are experiencing the same issue or not, but in my case this has been solved. The root of my issue was in the usage of java agent. otherwise this pipeline setup is working and we can have traces in both aws and jaeger.

**Comment by sethAmazon** [comment]
@HashemTaheriSonos can this issue be closed?
