### ISSUE TITLE
Split stability tests in a separate GA workflow

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#4045]
* easier to enable/disable 
* smaller build-and-test.yml file

**Comment by alolita** [comment]
@owais are you still planning to work on this issue or can someone else work on this?

**Comment by mustafain117** [comment]
@alolita I can work on this!

**Comment by alolita** [comment]
Hi @mustafain117 thanks! Assigned to you.
