### ISSUE TITLE
Review public API for `datadogexporter`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#4056]

**Comment by mx-psi** [comment]
@ericmustin I am assigning this to you since there are a couple of traces things we can make private:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fba0e93eb5216812fd683660384642f323c88088/exporter/datadogexporter/translate_traces.go#L61
and

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fba0e93eb5216812fd683660384642f323c88088/exporter/datadogexporter/trace_connection.go#L65

Can you have a look and open a PR to make them private?

**Comment by lastchiliarch** [comment]
@mx-psi  It looks like an easy task. If it still active, May I have a try?

**Comment by ericmustin** [comment]
@lastchiliarch absolutely, tbh i don't have bandwidth here in the short term, but can definitely review pr!

**Comment by mx-psi** [comment]
@lastchiliarch thanks for doing this and thanks to Eric for handling this while I was on PTO :) I am closing this since the PR was merged

**Comment by mx-psi** [comment]
@alolita Pinging you to let you know the Datadog exporter public API has been reviewed
