### ISSUE TITLE
Review public API for `tanzuobservabilityexporter`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#4057]
cc @oppegard @thepeterstone see the parent issue for context. Can I assign this to either of you?

I think you can make some things private e.g. this
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fba0e93eb5216812fd683660384642f323c88088/exporter/tanzuobservabilityexporter/transformer.go#L47

**Comment by oppegard** [comment]
@mx-psi you can assign this to me.
