### ISSUE TITLE
Review public API for `awsprometheusremotewriteexporter`

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector-contrib#4075]
See base issue #4055

**Comment by anuraaga** [comment]
@alolita Can you assign anyone from the AMP team to review this component's API to ensure nothing is public except for the collector plugin implementations? Thanks!

**Comment by anuraaga** [comment]
Nevermind, was simple enough to verify with the godoc. Looks good

https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsprometheusremotewriteexporter

**Comment by alolita** [comment]
Thanks @anuraaga - the awsprometheusremotewriteexporter is just a wrapper for sigv4 support.
