### ISSUE TITLE
Review public API for `awsxrayreceiver`

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector-contrib#4077]
See base issue #4055

**Comment by anuraaga** [comment]
@bhautikpip Do you mind reviewing the awsxrayreceiver and making sure it exposes no API that shouldn't be public? Only component interface implementations should need to be public. Thanks!

**Comment by bhautikpip** [comment]
Audited `awsxrayreceiver` to validate exposed APIs, struct, interfaces and variables from [public docs]( https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver)

Summary of auditing:

**root package**
[type Config](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/config.go#L25)
[func (x *xrayReceiver) Start(ctx context.Context, host component.Host) error](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/receiver.go#L89)
[func (x *xrayReceiver) Shutdown(_ context.Context) error](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/receiver.go#L98)
[func NewFactory() component.ReceiverFactory](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/factory.go#L32)

**internal packages**

1. [errors](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/internal/errors/errors.go)
```
type ErrIrrecoverable
func (e *ErrIrrecoverable) Error() string
func (e *ErrIrrecoverable) Unwrap() error

type ErrRecoverable
func (e *ErrRecoverable) Error() string
func (e *ErrRecoverable) Unwrap() error
```

 2. [proxy](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/internal/proxy)
```
type Config
func DefaultConfig() *Config

type Server
func NewServer(cfg *Config, logger *zap.Logger) (Server, error)
```

3. [socketconn](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/internal/socketconn/socketconn.go#L18)
```
type SocketConn
```

4. [tracesegments](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/internal/tracesegment)
```
type Header
func SplitHeaderBody(buf []byte) (*Header, []byte, error)
func (t Header) IsValid() bool

const ProtocolSeparator = '\n'
```

5. [translator](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/internal/translator/translator.go#L37)
```
func ToTraces(rawSeg []byte) (*pdata.Traces, int, error)
```
6. [udppollar](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/receiver/awsxrayreceiver/v0.30.0/receiver/awsxrayreceiver/internal/udppoller)
```
type Config

type Poller
func New(cfg *Config, logger *zap.Logger) (Poller, error)

type RawSegment

Transport = "udp"
```

**Comment by anuraaga** [comment]
Thanks!

**Comment by anuraaga** [comment]
Was verified to be fine
