### ISSUE TITLE
Review public API for `awscontainerinsightreceiver`

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector-contrib#4078]
See base issue #4055

**Comment by anuraaga** [comment]
@pxaws I tried to keep an eye out while reviewing, but it's time to do a through scrub to make sure this receiver doesn't have any unnecessary public API. Can you check it out? Thanks!

**Comment by pxaws** [comment]
I did a check with the code. Since all our logic are inside the `internal` folder, the receiver doesn't expose any unnecessary public APIs.

**Comment by anuraaga** [comment]
@pxaws Do New and MetricsProvider need to be exposed?

https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver#New

**Comment by pxaws** [comment]
I see. I will remove them.
