### ISSUE TITLE
Review public API for `awsecscontainermetricsreceiver`

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector-contrib#4080]

**Comment by anuraaga** [comment]
@JohnWu20 Can you do a scrub of the awsecscontainermetricsreceiver to make sure all API is private unless it needs to be public (only collector interface implementations should need to be public)? Thanks!

/cc @mxiamxia

**Comment by hossain-rayhan** [comment]
checking in. will send a PR.

**Comment by JohnWu20** [comment]
Sorry that I missed this message. I can help too.

**Comment by anuraaga** [comment]
Was fixed in #4204
