### ISSUE TITLE
Dynatrace exporter not recognized

### ISSUE THREAD

**Issue by alanrdel** [open-telemetry/opentelemetry-collector-contrib#4136]
**Describe the bug**
Attempting to configure dynatrace as an exporter but keeps getting an error complaining that it is an unknown exporters type

**Steps to reproduce**
1º - I followed the [link ](https://aws-otel.github.io/docs/getting-started/lambda/lambda-js) to enable the AWS Distro for OpenTelemetry Lambda.
2° Create a config.yaml, describe in "what config did you use", as the [link ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/dynatraceexporter) to add "exporters: [dynatrace]"
3º Create the environment variable OPENTELEMETRY_COLLECTOR_CONFIG_FILE with the path of the config.yml

**What did you expect to see?**
The collector running with no issues

**What did you see instead?**
The collector fatally exiting with application run finished with error: cannot load configuration: unknown exporters type "dynatrace" for dynatrace

**What version did you use?**
Version: aws-otel-nodejs-ver-0-19-0:1

**What config did you use?**
Config: 
[config.zip](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/6785273/config.zip)

**Environment**
OS: lambda nodejs v10

Logs:
> 2021-07-08T11:08:35.082-03:00	2021/07/08 14:08:35 [collector] Launching OpenTelemetry Lambda extension, version: v0.1.0
> 2021-07-08T11:08:35.082-03:00	2021-07-08T14:08:35.080Z info service/application.go:277 Starting otelcol... {"Version": "v0.1.0", "NumCPU": 2}
> 2021-07-08T11:08:35.082-03:00	2021-07-08T14:08:35.080Z info service/application.go:185 Setting up own telemetry...
> 2021-07-08T11:08:35.082-03:00	2021-07-08T14:08:35.080Z info service/application.go:220 Loading configuration...
> 2021-07-08T11:08:35.082-03:00	Error: cannot load configuration: unknown exporters type "dynatrace" for dynatrace
> 2021-07-08T11:08:45.062-03:00	START RequestId: ddea8abc-2a39-4315-affd-d42bda5dc0ea Version: $LATEST
> 2021-07-08T11:08:48.064-03:00	EXTENSION Name: collector State: Started Events: []
> 2021-07-08T11:08:48.065-03:00	END RequestId: ddea8abc-2a39-4315-affd-d42bda5dc0ea
> 2021-07-08T11:08:48.065-03:00	REPORT RequestId: ddea8abc-2a39-4315-affd-d42bda5dc0ea Duration: 3001.97 ms Billed Duration: 3000 ms Memory Size: 128 MB Max Memory Used: 46 MB XRAY TraceId: 1-60e706e2-76b4d77d343a1b5751fd8c09 SegmentId: 61a194a95b1c5a6c Sampled: true
> 2021-07-08T11:08:48.065-03:00	2021-07-08T14:08:48.064Z ddea8abc-2a39-4315-affd-d42bda5dc0ea Task timed out after 3.00 seconds

**Comment by albertteoh** [comment]
@alanrdel Please see: https://github.com/aws-observability/aws-otel-lambda/issues/103#issuecomment-865431233

Basically, although the [AWS Distro for OpenTelemetry Collector docs](https://aws-otel.github.io/docs/releases#whats-included-in-the-aws-distro-for-opentelemetry-collector) indicate that the `dynatrace` exporter is an available component in the distro, the collector components supported in an AWS OpenTelemetry *lambda layer* are stripped down [to core components](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/lambdacomponents/default.go#L18-L29) to keep it lightweight.

It seems (from the above issue comment) that you can create your own custom lambda layer to include `dynatrace`, though I haven't tried this out myself.

**Comment by jkowall** [comment]
Echoing @albertteoh on this one, but you should open an issue in the ADOT repo not here, since you are using the AWS distribution this is not an upstream issue.

**Comment by alanrdel** [comment]
Tks for the answers, I'm closing this issue to open other one in ADOT page.
