### ISSUE TITLE
`awsxrayexporter` not checking cloud platform according to the Opentelemetry Specification

### ISSUE THREAD

**Issue by avocadomaster** [open-telemetry/opentelemetry-collector-contrib#4298]
**Describe the bug**
Using resource detectors for ECS does not seem to work for exported AWS X-ray segments.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c76229eb5330aeb9fd49eba4df264d0012af13d0/exporter/awsxrayexporter/internal/translator/aws.go#L176

As far as I understand the checks here should use the [Opentelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/cloud.md#cloud)

**What did you expect to see?**
Expecting the `cloud.platform` to comply with the [Opentelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/cloud.md#cloud)

For example:
`ECS` should be `aws_ecs`

**What did you see instead?**

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c76229eb5330aeb9fd49eba4df264d0012af13d0/exporter/awsxrayexporter/internal/translator/aws.go#L176

**Comment by mxiamxia** [comment]
This issue should be fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4384
