### ISSUE TITLE
k8sprocessor: enrich metadata if only pod name and pod namespace are available

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#4309]
**Is your feature request related to a problem? Please describe.**
k8sprocessor enriches metadata only for `podUid` or `pod ip`. I have a case when only pod name and pod namespace are obtained by the receiver. In that case I'm unable to enrich metadata using this processor

**Describe the solution you'd like**
I would like to store metadata in additional key [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7332cf3c77c24749d5089f83e046ee1b02351f7a/processor/k8sprocessor/kube/client.go#L368-L401), which would be build as `k8s.pod.name`.`k8s.namespace.name`.

I cannot use `host.name` as it can contains any hostname name.

I will prepare PR with proposal

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sumo-drosiek** [comment]
cc: @dashpole

**Comment by dashpole** [comment]
This makes sense in general, since pod name and namespace are far more common than IP or UID.  The only thing to be wary of is that pod name and namespace are not unique across time.  For example, I could have two pods, run sequentially, with the same name + namespace, but different pod IPs, etc.  I'm not familiar enough with the k8sprocessor to know if that matters.

**Comment by sumo-drosiek** [comment]
Yes, the assumption is that you take always metadata from newest `pod`, `namespace` pair. We can consider looking at timestamp as well, and it should resolve the issue, but it will slightly complicate code and performance. WDYT?

**Comment by dashpole** [comment]
I think the current approach is probably fine to start.  It is maybe just worth noting in documentation that an outdated watch cache can potentially cause telemetry to be assigned to the wrong pod.

**Comment by dmitryax** [comment]
Hi @sumo-drosiek, would you mind sharing the use case where you have only k8s pod name and namespace pair? Is it because you need to read logs from `/var/log/containers`?

**Comment by sumo-drosiek** [comment]
It is because I read metrics from prometheus using `remoteWrite` and it provides only `pod` and `namespace` metadata

**Comment by newly12** [comment]
I have a similar use case that requires such feature, any progress has been made on the implementation so far?

**Comment by sumo-drosiek** [comment]
@newly12 
I recreated PR with my proposed solution, which is to allow to use multiple attributes in order to enrich and store metadata
