### ISSUE TITLE
Some metrics in zookeeperreceiver are defined as Gauge, but they are non-monotonic sums

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#4322]
E.g. `zookeeper.connections_alive`

**Comment by codeboten** [comment]
This issue is fixed https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9e257a3b8d3c56ce3f87ab0f506bdea593ce2b58/receiver/zookeeperreceiver/metadata.yaml#L59. Please re-open if additional fields should be modified.
