### ISSUE TITLE
Some metrics in nginxreceiver are defined as Gauge, but they are non-monotonic sums

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#4326]
E.g. `nginx.connections_current`

**Comment by lBowlin** [comment]
Hi @djaglowski and @bogdandrutu I stumbled upon this change and am curious why it was made? According the nginx documentation `reading` `writing` `waiting` all represent the current values of connections in those states, and go up and down accordingly. This would seem to represent a gauge type metric, and the official nginx-prometheus-exporter also classifies them as gauges. 

What inspired this change? Has there been a fundamental change to how the metric is observed from one that can go up or down, to one that can only go up?

**Comment by djaglowski** [comment]
Hi @lBowlin, there's a subtlety in the OTel data model that was overlooked in this case. 

Basically, our notion of sum metric is a bit broader than just counters and can represent realtime values that go up and down. The key idea here is that we subdivide sums into monotonic (counters) and non-monotonic (gauge-like) types, but we ultimately expect non-monotonic sums to be treated as gauges in most backends. ([This diagram](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/img/model-layers-stream.png) may be helpful.)

What differentiates a non-monotonic sum from a gauge is that the data points can be meaningfully aggregated. For example, with this metric we could:
- Sum `reading` `writing` and `waiting` for a single server to find a total number of connections.
- Sum `waiting` data points across multiple servers to determine the total number of `waiting` connections in a deployment.

This means that gauges are only used for things that cannot be aggregated in a straightforward way. For example, a disk space utilization %.

**Comment by djaglowski** [comment]
This is essentially completed but still behind a feature gate.
