### ISSUE TITLE
Some metrics in kafkametricsreceiver are defined as Gauge, but they are non-monotonic sums

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#4327]
E.g. `kafka.consumer_group.members`

**Comment by zeno-splunk** [comment]
Hi @bogdandrutu 
I'm working on resolving the problem, and I consulted the [document](https://github.com/open-telemetry/opentelemetry-specification/blob/3972c6aafd8f14e305dbbb0b5b6dded9d02d6164/specification/metrics/semantic_conventions/instrumentation/kafka.md). However, I couldn't find the metric` kafka.partition.replicas`. Is it supposed to be an **UpDownCounter** instrument?

Also, for those non-monotonic sums, should we use **cumulative aggregation** or **delta aggregation**?

**Comment by atoulme** [comment]
@zeno-splunk please see here for the definition of the metric: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4ed6328aeadebbe7d86cb35dfae54bce38ff1c68/receiver/kafkametricsreceiver/metadata.yaml#L50

**Comment by atoulme** [comment]
This issue can now be closed, thanks @ZenoCC-Peng !
