### ISSUE TITLE
Review public API for `honeycombexporter`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#4336]
See base issue for details. cc @paulosman @lizthegrey @MikeGoldsmith

**Comment by paulosman** [comment]
@MikeGoldsmith will be looking at this.

**Comment by MikeGoldsmith** [comment]
Hey @mx-psi - I've reviewed the HoneycombExporter and am happy the public API is as concise as possible.

The only custom public function is [RunErrorLogger](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/honeycombexporter/honeycomb.go#L274) which sets up a response queue reader. This is an optional call users can call if wanted.

**Comment by jpkrohling** [comment]
Closing then.
