### ISSUE TITLE
Review public API for `logzioexporter`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#4339]
See base issue for details. cc @yyyogev @jkowall @albertteoh can I assign this to any of you?

**Comment by jkowall** [comment]
I will get you someone, sorry for missing this.

**Comment by Doron-Bargo** [comment]
Hi @mx-psi , kindly please assign @yotamloe for this as he is the maintainer for logzio exporter

**Comment by jkowall** [comment]
Will fix with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4430

**Comment by mx-psi** [comment]
> Hi @mx-psi , kindly please assign @yotamloe for this as he is the maintainer for logzio exporter

I will, but I can't assign them until they comment here :)

**Comment by yotamloe** [comment]
@mx-psi I'm here :)
