### ISSUE TITLE
Review public API for `lokiexporter`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#4340]
See base issue for details. According to the README it looks like this only does logs so there may be nothing to do here but I want a CODEOWNER to confirm this. cc @gramidt

**Comment by jpkrohling** [comment]
@mar4uk, would you be able to work on this one?

**Comment by mar4uk** [comment]
@jpkrohling `lokiexporter` public API looks good. No work needs to be done. Could you please mark it as done (I don't have permissions to mark it)?
