### ISSUE TITLE
Convert k8s_cluster to metadata.yaml and pdata

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector-contrib#4367]
1. Convert to pdata
1. Populate metadata.yaml

_Originally posted by @owais in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4342#discussion_r676839351_

**Comment by owais** [comment]
@jrcamp could you pelase link to an example of metadata.yaml? Not sure what this is about.

**Comment by jrcamp** [comment]
https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/metric-metadata.md

**Comment by alolita** [comment]
@bogdandrutu @jrcamp what else needs to be completed for this issue? please clarify. Thx.

**Comment by dmitryax** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18394 should be resolved before aplying this change

**Comment by dmitryax** [comment]
We have the last piece captured in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24568, so I think close this one
