### ISSUE TITLE
containerinsight: Metrics conversion for uint/uint32/uint64 seems wrong. Should it be intGauge?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#4381]
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/aws/containerinsight/utils.go#L199

**Comment by Aneurysm9** [comment]
I'm not sure either one is really correct.  Maybe `uint32` can be safely represented by `int64`, but `uint64` and `uint` (when using >32 bits) can't.  Do we have general guidance for component authors regarding such type conversions?

**Comment by mxiamxia** [comment]
Thanks, we'll change it to `int64`, it still has a risk to lose the value precision on `uint64` and `uint`. Not sure what's the best way to handle it for now.
