### ISSUE TITLE
filelog receiver include doesn't support multiple directory levels

### ISSUE THREAD

**Issue by overmeulen** [open-telemetry/opentelemetry-collector-contrib#4628]
**Describe the bug**
Using ** in the filelog receiver include pattern only picks up 1 directory level

**Steps to reproduce**
Collector config:
```
receivers:
  filelog:
    include: [ /data/**/*.log ]
```

**What did you expect to see?**
/data/A/B/test.log being watched by the filelog receiver

**What did you see instead?**
/data/A/test.log being watched but not /data/A/B/test.log (check the collector logs)

**What version did you use?**
opentelemetry-collector-contrib v0.31.0

**Comment by gillg** [comment]
I tried it some days ago and it was working for me.
Are you sure you didn't missed to mount your host log folder in you collector container (if you use docker).
Have you a log in console saying it can't find a file with the pattern ?

**Comment by overmeulen** [comment]
I'm not using docker in this case, and there is nothing in the console...

**Comment by gillg** [comment]
If there is nothing on the console it's strange. You should have at least something saying there is no files in the given path. Have you add it on the pipelines section ? 🤔
