### ISSUE TITLE
AWS CloudWatch logs exporter should have an option to automatically create log group/stream

### ISSUE THREAD

**Issue by errordeveloper** [open-telemetry/opentelemetry-collector-contrib#4714]
**Is your feature request related to a problem? Please describe.**

Currently log exporter relies on having an existing log group and log steam, it would be more convenient if auto-create option was available. Being able to set TTL would be nice also.

**Describe the solution you'd like**

Add an auto-create option to the exporter config, it would be nice if it was enabled by default.

**Describe alternatives you've considered**

An alternative requires user to either go to console and click around, or use another tool to automate it. For getting started this seems like extra work one shouldn't have to do. Also, in some cases user might want to generate collector configuration and shouldn't need to worry about CloudWatch setup.

**Comment by errordeveloper** [comment]
xref #4721

**Comment by MovieStoreGuy** [comment]
Being able to create external resources is rather powerful thing, I worry adding something like this could mean that users could spawn too many resources for them to be easily managed, maintained and leading to them being orphaned.

**Comment by aateeqi** [comment]
@alolita could you assign me to this?

**Comment by alolita** [comment]
Assigned @aateeqi

**Comment by MovieStoreGuy** [comment]
Hey @aateeqi ,

Is this done?

**Comment by aateeqi** [comment]
Hey @MovieStoreGuy yes that is supported https://github.com/open-telemetry/opentelemetry-collector-contrib/blame/main/internal/aws/cwlogs/cwlog_client.go#L138

**Comment by bryan-aguilar** [comment]
Creating a new log group and setting retention policies is now supported

**Comment by DzmitryZaitsauIG** [comment]
Current README says 
> log_stream_name: The stream name of the CloudWatch Logs. If it does not exist it will be created automatically.

which might be true for `awsemfexporter` but `awscloudwatchlogsexporter` fails with
`Error: invalid configuration: exporters::awscloudwatchlogs: 'log_stream_name' must be set`

The README is misleading.

Also, looks like there is no possibility create log streams with unique names automatically. They should be preconfigured, and a proper name should be set to a config. Which is rather inconvenient for a Kubernetes setup.

A related PR adding a possibility to parameterise stream names was never merged: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12179
Related issue for reference: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10887
