### ISSUE TITLE
AWSCWLogs Exporter enhancements

### ISSUE THREAD

**Issue by mxiamxia** [open-telemetry/opentelemetry-collector-contrib#4721]
**Is your feature request related to a problem? Please describe.**

Create an issue to list the enhancements need to be done for AWSCWLogsExporter

1. Batch log events and make sure the batch size is less then 1MB when calls PutLogsEvent API
2. Each single logs event size should be less than 256KB. Need to trim or drop if it reaches the maximum size limits.
3. Create Log Group/Stream in flight from Config if it is not yet found in CW logs backend.
4. Gracefully handle CW Logs API exceptions in response
5. ...

cc/ @rakyll @Aneurysm9 @alolita

**Comment by errordeveloper** [comment]
> Create Log Group/Stream in flight from Config if it is not yet found in CW logs backend.

I've also opened https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4714 regarding this, but it's more from the user's perspective. Feel free to close in favour of this, or track as a subtask here.

**Comment by errordeveloper** [comment]
I also noticed that CloudWatch and Kinesis exporters don't used `github.com/open-telemetry/opentelemetry-collector-contrib/internal/aws/awsutil`, but XRay exporter does. I suppose this might result in some inconsistencies, potentially affecting users.

**Comment by willarmiros** [comment]
Is it possible to remove the `comp:aws-xray` label from this issue? It should only be a CloudWatch issue.
