### ISSUE TITLE
Prometheus receiver doesn't support untyped metrics

### ISSUE THREAD

**Issue by gracewehner** [open-telemetry/opentelemetry-collector-contrib#4743]
**Describe the bug**
Prometheus receiver does not convert metrics without the TYPE hint to OTLP correctly and treats them as invalid, whereas Prometheus will treat these metrics as a gauge.

**Steps to reproduce**
Scrape an endpoint that has metrics without the `# TYPE <metric name> <metric type>` hint.

**What did you expect to see?**
Prometheus receiver matching Prometheus functionality and treating the metric as a gauge type.

**Comment by dashpole** [comment]
This was discussed at the prometheus WG today in the context of [additional compliance tests](https://docs.google.com/document/d/1DGdpWKEE666n8bGVBu_7upKJEDbHiaNFPuzMB6bx-cY/edit).  One of the planned tests would check that [MetricTypeUnknown](https://github.com/prometheus/prometheus/blob/39d79c3cfb86c47d6bc06a9e9317af582f1833bb/pkg/textparse/interface.go#L95) metrics, including both ones you describe in the description, and metrics that are renamed (which is also [currently a problem](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5001)), are correctly propagated to prometheus remote_write endpoints from a prometheus receiver.

Correct me if i'm wrong, but I believe https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4865 would change unknown typed metrics to gauges, and wouldn't pass such a test if we added it.

OpenCensus did support a [MetricDescriptor_UNSPECIFIED](https://github.com/census-instrumentation/opencensus-proto/blob/master/gen-go/metrics/v1/metrics.pb.go#L63) type, which would allow this information to be propagated.  pdata has a [MetricDataTypeNone](https://github.com/open-telemetry/opentelemetry-collector/blob/main/model/pdata/metrics.go#L128), but i'm not sure if that is the correct data type to use here.

cc @alolita @Aneurysm9

**Comment by dashpole** [comment]
These are the otlp data types: https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L155-L181

**Comment by Aneurysm9** [comment]
I don't think `MetricDataTypeNone` will work, it's just the zero value for that type.  There's no way to add or retrieve data with that type.

**Comment by Aneurysm9** [comment]
I believe this issue is no longer applicable.  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6708 added tests that ensure we're handling untyped metrics as gauges.  Please re-open if further issues are discovered.
