### ISSUE TITLE
MetricDataTypeSummary not handled in some cases

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#4744]
There are multiple places in the code where a switch statement handles cases like the following example but is missing case pdata.MetricDataTypeSummary.

https://github.com/open-telemetry/opentelemetry-collector/blob/8038673eba9e9d32c5b7bd5bb6a0be94b2ec60cb/exporter/exporterhelper/resource_to_label.go#L74-L79

**Comment by kovrus** [comment]
Please assign it to me.
