### ISSUE TITLE
Allow to set span's Status

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-collector-contrib#4754]
OpenTelemetry spec currently says the following in [the description of `Span.SetStatus` method](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status):

> Application developers and Operators may set the status code to Ok.

From the previous discussions on this topic I assumed that the way for `Operator` to set span status is by using Collector. Unfortunately, Collector does not support setting span status atm. [Span Processor](https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/spanprocessor/README.md) supports only changing span name and [Attributes Processor](https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/attributesprocessor/README.md), naturally, operate only on attributes and cannot change status.

Proposed solution is to expand `Span Processor` and to allow it to change span status.

**Comment by kdroukman** [comment]
Adding my vote to this. The rigid specification around the span status doesn't allow for a variety of use cases in the real world, with the most common request being the ability to override error classification of 4xx status codes.

**Comment by iNikem** [comment]
@bogdandrutu why did you move this issue into contrib? Changing attribute values is the core functionality of the Collector. Changing status value should be the same, no?

**Comment by iNikem** [comment]
Fixed by #5886
