### ISSUE TITLE
Tail-Based Sampling - Scalability Issues

### ISSUE THREAD

**Issue by vikrambe** [open-telemetry/opentelemetry-collector-contrib#4758]
I like the idea of tail based sampling. I would like to enhance tail based sampling in 2 ways:

Consider a case where we are tail-sampling based on span->http.status_code=500. 
1. I would want to sample 100% of all http.status_code "500"s and 10% of http.status_code "200"s. I would like to create a new sampler that combines string_tag_filter and probabilistic sampler.
2. What would happen when Spans for a trace land-up in different Otel-Collector instances, one instance can sample the trace when it find http.status_code as 500 and the other could decide not to sample. I was thinking of using group-cache to solve this problem.
Please, share your thoughts on the above.

**Comment by vikrambe** [comment]
> @vikrambe
> Could you please refer to the contrib PR here or to the fork if created out of contrib.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4396 -> Planning to work on the review comments over the weekend.

**Comment by XiaoWeiKIN** [comment]
it's just what I need

**Comment by vikrambe** [comment]
> #4396

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4958 -> This is already merged. Use Composite Tailsampling Policy.

**Comment by jpkrohling** [comment]
@vikrambe, do you think there's still something to do here?

**Comment by vikrambe** [comment]
> @vikrambe, do you think there's still something to do here?

@jpkrohling I think we have all the pieces here to solve this problem at scale now. 
1. groupByTraceProcessor
2. loadbalancingexporter 
3. tailSampler with composite policy, With latest changes we can also add AND clause to the policy

We can close this issue. We should put all these pieces together in a document/blog ? Please suggest ?

**Comment by vikrambe** [comment]
> Documentation would be great, perhaps starting as a blog post and migrating later to the official docs. Are you up to writing something?

Sure @jpkrohling I would be happy to write a blog on this topic, but i would definitely need your review and suggestions. I will start working on the draft and share it soon.

**Comment by codeboten** [comment]
> We can close this issue.
Closing the issue as per the comment above

**Comment by AkselAllas** [comment]
I have a question though.

Is there a way of making loadbalancerexporter collector layer highly available to ensure no traces get lost due to downtime in availability? 🤔
