### ISSUE TITLE
AWS XRay Exporter - UnprocessedTraceSegments errors on valid traces

### ISSUE THREAD

**Issue by CeeBeeCee** [open-telemetry/opentelemetry-collector-contrib#482]
I'm testing the XRay exporter using the OpenTelemetry collector with a couple of web services. I'm sending traces in Zipkin format to the OpenTelemetry Collector and exporting to a local Jaeger server and also to XRay. I'm able to see the traces in my Jaeger instance correctly but the XRay exporter is throwing "UnprocessedTraceSegments" errors.

**What version did you use?**
otel/opentelemetry-collector-contrib:0.6.0

**What config did you use?**
```
receivers:
  zipkin:
    endpoint: :9411
exporters:
  jaeger:
    endpoint: localhost:14250
    insecure: true
  awsxray:
  awsxray/custom:
    region: us-east-1
    resource_arn: "*******"
    role_arn: "*******"
  logging:
    loglevel: debug
```

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Collector Logs**
```
2020-07-21T18:28:44.330Z        DEBUG   loggingexporter/logging_exporter.go:305 ResourceSpans #0
Resource labels:
     -> service.name: STRING(accountingproxyservice)
InstrumentationLibrarySpans #0
Span #0
    Trace ID       : 57a9f43afe0fd21f2927189d1710561c
    Parent ID      : 227988bf8a8c7eda
    ID             : aca5ba277f751fa8
    Name           : http post
    Kind           : CLIENT
    Start time     : 2020-07-21 18:28:42.232214 +0000 UTC
    End time       : 2020-07-21 18:28:42.355767 +0000 UTC
    Status code    : Ok
    Status message :
Attributes:
     -> http.method: STRING(POST)
     -> http.status_code: INT(200)
     -> http.url: STRING(/crts/wsi/Trading/sendToAccounting)
     -> ipv4: STRING(dedacted)
Span #1
    Trace ID       : 57a9f43afe0fd21f2927189d1710561c
    Parent ID      : 41c2318163ccce83
    ID             : 227988bf8a8c7eda
    Name           : sendtoacccontroller.sendtoaccmulti
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2020-07-21 18:28:42.231731 +0000 UTC
    End time       : 2020-07-21 18:28:42.360204 +0000 UTC
Attributes:
     -> ipv4: STRING(dedacted)
Span #2
    Trace ID       : 57a9f43afe0fd21f2927189d1710561c
    Parent ID      :
    ID             : 41c2318163ccce83
    Name           : /sendtoaccmulti
    Kind           : SERVER
    Start time     : 2020-07-21 18:28:42.229003 +0000 UTC
    End time       : 2020-07-21 18:28:42.360634 +0000 UTC
    Status code    : Ok
    Status message :
Attributes:
     -> http.method: STRING(GET)
     -> ipv4: STRING(dedacted)
     -> http.status_code: INT(200)
     -> http.url: STRING(http://localhost:29012/sendToAccMulti?orderID=3804972981)
     -> net.peer.ip: STRING(dedacted)
     -> net.peer.port: INT(2259)
     -> servlet.context: STRING()
     -> servlet.path: STRING(/sendToAccMulti)
     -> span.origin.type: STRING(org.apache.catalina.core.ApplicationFilterChain)

{"level":"debug","ts":1595356124.3348262,"caller":"awsxrayexporter/awsxray.go:49","msg":"TraceExporter","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray","type":"awsxray","name":"awsxray","#spans":3}

{"level":"debug","ts":1595356124.3352222,"caller":"awsxrayexporter/awsxray.go:87","msg":"request: {\n  TraceSegmentDocuments: [\"{\\\"trace_id\\\":\\\"1-5f1733dc-fe0fd21f2927189d1710561c\\\",\\\"id\\\":\\\"aca5ba277f751fa8\\\",\\\"name\\\":\\\"http post\\\",\\\"start_time\\\":1595356122.232214,\\\"end_time\\\":1595356122.355767,\\\"parent_id\\\":\\\"227988bf8a8c7eda\\\",\\\"origin\\\":\\\"AWS::EC2::Instance\\\",\\\"type\\\":\\\"subsegment\\\",\\\"namespace\\\":\\\"remote\\\",\\\"http\\\":{\\\"request\\\":{\\\"method\\\":\\\"POST\\\",\\\"url\\\":\\\"/crts/wsi/Trading/sendToAccounting\\\"},\\\"response\\\":{\\\"status\\\":200}},\\\"aws\\\":{},\\\"annotations\\\":{\\\"ipv4\\\":\\\"masked\\\"}}\\n\",\"{\\\"trace_id\\\":\\\"1-5f1733dc-fe0fd21f2927189d1710561c\\\",\\\"id\\\":\\\"227988bf8a8c7eda\\\",\\\"name\\\":\\\"sendtoacccontroller.sendtoaccmulti\\\",\\\"start_time\\\":1595356122.231731,\\\"end_time\\\":1595356122.360204,\\\"parent_id\\\":\\\"41c2318163ccce83\\\",\\\"origin\\\":\\\"AWS::EC2::Instance\\\",\\\"type\\\":\\\"subsegment\\\",\\\"aws\\\":{},\\\"annotations\\\":{\\\"ipv4\\\":\\\"masked\\\"}}\\n\",\"{\\\"trace_id\\\":\\\"1-5f1733dc-fe0fd21f2927189d1710561c\\\",\\\"id\\\":\\\"41c2318163ccce83\\\",\\\"name\\\":\\\"accountingproxyservice\\\",\\\"start_time\\\":1595356122.229003,\\\"end_time\\\":1595356122.360634,\\\"origin\\\":\\\"AWS::EC2::Instance\\\",\\\"http\\\":{\\\"request\\\":{\\\"method\\\":\\\"GET\\\",\\\"url\\\":\\\"http://localhost:29012/sendToAccMulti?orderID=3804972981\\\\u0026orderID=3804972979\\\\u0026orderID=3804972977\\\\u0026orderID=3804972975\\\\u0026orderID=3804972973\\\\u0026\\\",\\\"client_ip\\\":\\\"masked\\\"},\\\"response\\\":{\\\"status\\\":200}},\\\"aws\\\":{},\\\"annotations\\\":{\\\"ipv4\\\":\\\"1masked\\\",\\\"servlet_context\\\":\\\"\\\",\\\"servlet_path\\\":\\\"/sendToAccMulti\\\",\\\"span_origin_type\\\":\\\"org.apache.catalina.core.ApplicationFilterChain\\\"}}\\n\"]\n}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}

{"level":"debug","ts":1595356144.6890867,"caller":"awsxrayexporter/awsxray.go:93","msg":"response: {\n  UnprocessedTraceSegments: []\n}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}


```

**Comment by anuraaga** [comment]
@CeeBeeCee Can you confirm that you are not seeing the traces in the X-Ray console? I don't believe the `UnprocessedTraceSegments` is actually an error here since it's an empty array and there is no `ErrorCode`.

**Comment by CeeBeeCee** [comment]
@anuraaga : I dont see the traces in Xray searching by trace id. There is also mention of missing parent id in the logs.

Jul 31 13:08:46  {"level":"debug","ts":1596200926.8846846,"caller":"awsxrayexporter/awsxray.go:93","msg":"response: {  UnprocessedTraceSegments: [{      ErrorCode: "MissingParentId",      Id: "b2995b1c2dda50f1",      Message: "Invalid subsegment. ErrorCode: MissingParentId, Cause: null"    },{      ErrorCode: "MissingParentId",      Id: "f4909af03eaed867",      Message: "Invalid subsegment. ErrorCode: MissingParentId, Cause: null"    },{      ErrorCode: "MissingParentId",      Id: "e8a8bce6971b4a6d",      Message: "Invalid subsegment. ErrorCode: MissingParentId, Cause: null"    }]}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}

**Comment by anuraaga** [comment]
Thanks that's very helpful! Also could you clarify what instrumentation you are using. You mentioned Zipkin, so is it Java + Brave?

**Comment by CeeBeeCee** [comment]
Sorry, I had a copy paste error earlier. I'm using a [Jaeger exporter](https://pypi.org/project/opentelemetry-ext-jaeger/) (not  Zipkin) with OpenTelemetry to send traces to a collector running on an EC2 instance. This is how the collector is configured with one receiver and two exporters. The Jaeger exporter works just fine. Its the Xray exporter that is throwing errors.

receivers:
  jaeger:
    protocols:
      thrift_http:

exporters:
  jaeger:
    endpoint: someserver:14250
    insecure: true
  awsxray:
  awsxray/custom:
    region: us-east-1
    resource_arn: "*******"
    role_arn: "arn:aws:iam::*****OpenTelemetryCollectorPOC"
  logging:
    loglevel: debug

**Python Code snippet** 
from opentelemetry.sdk.trace.export import (
    BatchExportSpanProcessor,
    ConsoleSpanExporter
   )

from opentelemetry.ext import jaeger

**Comment by anuraaga** [comment]
Thanks for the detail, this is definitely a case that should work so will look into it. Seems like enough information to repro the bug but might come back if I need something else. Just one idea is if you are instrumenting with OTel, have you tried to use the OTLP exporter? It's currently what we've tested the most (again, that doesn't mean we won't fix issues with other protocols).

**Comment by CeeBeeCee** [comment]
That was the first thought I had i.e try OTLP. I tried it and got the same error. Here is the span that comes out using OTLP. If we can get OTLP traces to Xray, I'm okay switching from Jaeger to OTLP.

_```
InstrumentationLibrarySpans #0
Span #0
    Trace ID       : 8d8c7ce4c2f23018055b85aa99c1a561
    Parent ID      :
    ID             : ef612d9d17ded8b9
    Name           : ApplicationLaunch
    Kind           : INTERNAL
    Start time     : 2020-07-31 14:31:28.7655757 +0000 UTC
    End time       : 2020-07-31 14:31:28.7885139 +0000 UTC
    Status code    : Ok
    Status message :
```_

And this is what the Xray exporter reports.

{"level":"debug","ts":1596205893.9136646,"caller":"awsxrayexporter/awsxray.go:49","msg":"TraceExporter","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray","type":"awsxray","name":"awsxray","#spans":1}
{"level":"debug","ts":1596205893.9141052,"caller":"awsxrayexporter/awsxray.go:87","msg":"request: {\n  TraceSegmentDocuments: [\"{\\\"trace_id\\\":\\\"1-5f242b45-c2f23018055b85aa99c1a561\\\",\\\"id\\\":\\\"ef612d9d17ded8b9\\\",\\\"name\\\":\\\"ApplicationLaunch\\\",\\\"start_time\\\":1596205888.7655756,\\\"end_time\\\":1596205888.788514,\\\"origin\\\":\\\"AWS::EC2::Instance\\\",\\\"type\\\":\\\"subsegment\\\",\\\"aws\\\":{}}\\n\"]\n}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}
{"level":"debug","ts":1596205915.8065753,"caller":"awsxrayexporter/awsxray.go:93","msg":"response: {\n  UnprocessedTraceSegments: [{\n      ErrorCode: \"MissingParentId\",\n      Id: \"ef612d9d17ded8b9\",\n      Message: \"Invalid subsegment. ErrorCode: MissingParentId, Cause: null\"\n    }]\n}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}

**Comment by anuraaga** [comment]
Thanks for this information - so the trace in the first comment, https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/482#issue-663242141 seems to be valid, and hence we didn't see errors in the logs.

This one we're not handling properly right now since we're currently expecting the root of a trace to be a server span. I don't think this has to be the case though, so I'll look at fixing it, but I'm worried there may be a bug in the instrumentation if the root is INTERNAL - if you were to do a remote call, even just a self loop, then you would have a CLIENT span connected to an INTERNAL span when it must be connected to a SERVER span as per here

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#spankind

You may want to post information about the spans to the opentelemetry-python repo as well to debug why the root is INTERNAL.

**Comment by CeeBeeCee** [comment]
Hi Anurag,

I will post a query to the opentelemetry-python repo asking about the root being INTERNAL.
Meanwhile, I looked for span where the root is SERVER and here is one. It throws the same error and I do not see the trace in XRay. If it is easier to troubleshoot realtime, I'm open to a Zoom session at a time convenient to you. Please let me know.

`2020-08-03T19:02:04.121Z        DEBUG   loggingexporter/logging_exporter.go:305 ResourceSpans #0
Resource labels:
     -> service_name: STRING(Webservice)
InstrumentationLibrarySpans #0
Span #0
    Trace ID       : ab546154cc9aff758562d62c1ab84769
    Parent ID      :
    ID             : c0ec1e0f4ff24c05
    Name           : api.get_systems
    Kind           : SERVER
    Start time     : 2020-08-03 19:01:59.3949063 +0000 UTC
    End time       : 2020-08-03 19:02:00.0145328 +0000 UTC
    Status code    : Ok
    Status message :
Attributes:
     -> component: STRING(http)
     -> http.method: STRING(GET)
     -> http.server_name: STRING(127.0.0.1)
     -> http.scheme: STRING(http)
     -> host.port: INT(8080)
     -> http.host: STRING(localhost:8080)
     -> http.target: STRING(/api/system)
     -> net.peer.ip: STRING(127.0.0.1)
     -> net.peer.port: INT(2852)
     -> http.flavor: STRING(1.1)
     -> http.route: STRING(/api/system)
     -> http.status_text: STRING(OK)
     -> http.status_code: INT(200)

{"level":"debug","ts":1596481324.1255066,"caller":"awsxrayexporter/awsxray.go:49","msg":"TraceExporter","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray","type":"awsxray","name":"awsxray","#spans":1}
{"level":"debug","ts":1596481324.1259167,"caller":"awsxrayexporter/awsxray.go:87","msg":"request: {\n  TraceSegmentDocuments: [\"{\\\"trace_id\\\":\\\"1-5f285f2c-cc9aff758562d62c1ab84769\\\",\\\"id\\\":\\\"c0ec1e0f4ff24c05\\\",\\\"name\\\":\\\"localhost:8080\\\",\\\"start_time\\\":1596481319.3949063,\\\"end_time\\\":1596481320.0145328,\\\"origin\\\":\\\"AWS::EC2::Instance\\\",\\\"http\\\":{\\\"request\\\":{\\\"method\\\":\\\"GET\\\",\\\"url\\\":\\\"http://localhost:8080/api/system\\\",\\\"client_ip\\\":\\\"127.0.0.1\\\"},\\\"response\\\":{\\\"status\\\":200}},\\\"aws\\\":{},\\\"annotations\\\":{\\\"http_flavor\\\":\\\"1.1\\\",\\\"http_route\\\":\\\"/api/system\\\",\\\"http_status_text\\\":\\\"OK\\\"}}\\n\"]\n}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}
{"level":"debug","ts":1596481344.4128273,"caller":"awsxrayexporter/awsxray.go:93","msg":"response: {\n  UnprocessedTraceSegments: []\n}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}
`

**Comment by CeeBeeCee** [comment]
Hello Anurag,

You were on point! I looked at some other traces which had span.kind=SERVER and they are making it to XRay. Looks like the error message was benign. However, I did notice that the resource attributes (in bold) are not being sent to XRay. Is this under process for development? If it is easier for you to troubleshoot real time, I'm available for an online meeting at any time convenient to you. Please let me know.

Resource labels:
     ****-> app.bluegreen: STRING(dev)
     -> service_name: STRING(Webservice)****
InstrumentationLibrarySpans #0
Span #0
    Trace ID       : fc68ed4f519d9d690a9cc2eff1d5cb16
    Parent ID      :
    ID             : 47ccb60e763eb786
    Name           : getIndex.get_index

**Comment by anuraaga** [comment]
@CeeBeeCee Great!

> However, I did notice that the resource attributes (in bold) are not being sent to XRay. 
Yeah passing arbitrary resource attributes is currently being worked, we currently have a specific mapping for some fields into the X-Ray data model. `service.name` would generally be used to name the segment, but it should be set `service.name`, not `service_name` as per the spec here

https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/resource/semantic_conventions#service

@shengxil do you happen to have an estimate on passing arbitrary resource attributes (I think you're working on it as part of general annotation stuff)?

**Comment by CeeBeeCee** [comment]
@anuraaga : Changing service_name to service.name resolved me issue! Thanks so much for your help. The only outstanding request now is to process the resource attributes as XRay annotations and send them to Xray.

**Comment by maciejqantas** [comment]
@anuraaga 
I'm facing a similar issue. `service_name` doesn't apply to me, but my first span is also INTERNAL.

Some data is sent to XRay - I see a trace that contains
```{
    "Duration": null,
    "Id": "1-5f4f4150-cc007f9c953145acaf2c2097",
    "Segments": []
}
```
as raw data.

I'm running `otel/opentelemetry-collector-contrib:0.9.0`

My config is:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  awsxray:

processors:
  batch:
  queued_retry:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [logging, awsxray]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging]
```

My collector logs are:
```
otel-collector_1  | 2020-09-02T06:53:04.466Z	INFO	loggingexporter/logging_exporter.go:300	TraceExporter	{"#spans": 3}
otel-collector_1  | 2020-09-02T06:53:04.467Z	DEBUG	loggingexporter/logging_exporter.go:357	ResourceSpans #0
otel-collector_1  | Resource labels:
otel-collector_1  |      -> service.instance.id: STRING()
otel-collector_1  |      -> service.name: STRING(myservice)
otel-collector_1  |      -> service.namespace: STRING(namespace)
otel-collector_1  |      -> service.version: STRING(3234fsf2)
otel-collector_1  |      -> telemetry.sdk.language: STRING(java)
otel-collector_1  |      -> telemetry.sdk.name: STRING(opentelemetry)
otel-collector_1  |      -> telemetry.sdk.version: STRING(0.7.0)
otel-collector_1  | InstrumentationLibrarySpans #0
otel-collector_1  | InstrumentationLibrary io.opentelemetry.auto.spring-webmvc-3.1
otel-collector_1  | Span #0
otel-collector_1  |     Trace ID       : 5b3a9a20cc007f9c953145acaf2c2097
otel-collector_1  |     Parent ID      : afebd02a77b96f51
otel-collector_1  |     ID             : 4c924146b588cd9b
otel-collector_1  |     Name           : RestController.get
otel-collector_1  |     Kind           : INTERNAL
otel-collector_1  |     Start time     : 2020-09-02 06:53:03.582130921 +0000 UTC
otel-collector_1  |     End time       : 2020-09-02 06:53:03.590252591 +0000 UTC
otel-collector_1  |     Status code    : Ok
otel-collector_1  |     Status message :
otel-collector_1  | Events:
otel-collector_1  | SpanEvent #0
otel-collector_1  |      -> Name: Some Event
otel-collector_1  |      -> Timestamp: 1599029583582321375
otel-collector_1  |      -> DroppedAttributesCount: 0
otel-collector_1  | InstrumentationLibrarySpans #1
otel-collector_1  | InstrumentationLibrary io.opentelemetry.auto.http-url-connection
otel-collector_1  | Span #0
otel-collector_1  |     Trace ID       : 5b3a9a20cc007f9c953145acaf2c2097
otel-collector_1  |     Parent ID      : 4c924146b588cd9b
otel-collector_1  |     ID             : 19b399dd25e5c4e3
otel-collector_1  |     Name           : HTTP GET
otel-collector_1  |     Kind           : CLIENT
otel-collector_1  |     Start time     : 2020-09-02 06:53:03.584534905 +0000 UTC
otel-collector_1  |     End time       : 2020-09-02 06:53:03.605992346 +0000 UTC
otel-collector_1  |     Status code    : Ok
otel-collector_1  |     Status message :
otel-collector_1  | Attributes:
otel-collector_1  |      -> net.peer.name: STRING(node)
otel-collector_1  |      -> http.status_code: INT(200)
otel-collector_1  |      -> net.peer.port: INT(3000)
otel-collector_1  |      -> http.url: STRING(http://node:3000/)
otel-collector_1  |      -> http.method: STRING(GET)
otel-collector_1  | InstrumentationLibrarySpans #2
otel-collector_1  | InstrumentationLibrary io.opentelemetry.auto.servlet-3.0
otel-collector_1  | Span #0
otel-collector_1  |     Trace ID       : 5b3a9a20cc007f9c953145acaf2c2097
otel-collector_1  |     Parent ID      :
otel-collector_1  |     ID             : afebd02a77b96f51
otel-collector_1  |     Name           : /
otel-collector_1  |     Kind           : SERVER
otel-collector_1  |     Start time     : 2020-09-02 06:53:03.581002285 +0000 UTC
otel-collector_1  |     End time       : 2020-09-02 06:53:03.590438247 +0000 UTC
otel-collector_1  |     Status code    : Ok
otel-collector_1  |     Status message :
otel-collector_1  | Attributes:
otel-collector_1  |      -> http.status_code: INT(200)
otel-collector_1  |      -> net.peer.port: INT(32988)
otel-collector_1  |      -> servlet.path: STRING(/)
otel-collector_1  |      -> http.response_content_length: INT(0)
otel-collector_1  |      -> http.user_agent: STRING(Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
otel-collector_1  |      -> http.flavor: STRING(HTTP/1.1)
otel-collector_1  |      -> servlet.context: STRING()
otel-collector_1  |      -> http.url: STRING(http://localhost:8080/)
otel-collector_1  |      -> net.peer.ip: STRING(172.18.0.1)
otel-collector_1  |      -> http.method: STRING(GET)
otel-collector_1  |      -> http.client_ip: STRING(172.18.0.1)
otel-collector_1  |
otel-collector_1  | {"level":"debug","ts":1599029584.467188,"caller":"awsxrayexporter/awsxray.go:49","msg":"TraceExporter","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray","type":"awsxray","name":"awsxray","#spans":3}
otel-collector_1  | {"level":"debug","ts":1599029584.467514,"caller":"awsxrayexporter/awsxray.go:88","msg":"request: {\n  TraceSegmentDocuments: [\"{\\\"name\\\":\\\"RestController.get\\\",\\\"id\\\":\\\"4c924146b588cd9b\\\",\\\"start_time\\\":1599029583.582131,\\\"service\\\":{\\\"version\\\":\\\"3234fsf2\\\"},\\\"origin\\\":\\\"AWS::ElasticBeanstalk::Environment\\\",\\\"user\\\":\\\"\\\",\\\"trace_id\\\":\\\"1-5f4f4150-cc007f9c953145acaf2c2097\\\",\\\"end_time\\\":1599029583.5902526,\\\"fault\\\":false,\\\"error\\\":false,\\\"throttle\\\":false,\\\"aws\\\":{\\\"xray\\\":{\\\"sdk\\\":\\\"opentelemetry for java\\\",\\\"sdk_version\\\":\\\"0.7.0\\\",\\\"auto_instrumentation\\\":false},\\\"account_id\\\":\\\"\\\",\\\"operation\\\":\\\"\\\",\\\"region\\\":\\\"\\\",\\\"request_id\\\":\\\"\\\",\\\"queue_url\\\":\\\"\\\",\\\"table_name\\\":\\\"\\\"},\\\"namespace\\\":\\\"\\\",\\\"parent_id\\\":\\\"afebd02a77b96f51\\\",\\\"type\\\":\\\"subsegment\\\"}\\n\",\"{\\\"name\\\":\\\"node\\\",\\\"id\\\":\\\"19b399dd25e5c4e3\\\",\\\"start_time\\\":1599029583.584535,\\\"service\\\":{\\\"version\\\":\\\"3234fsf2\\\"},\\\"origin\\\":\\\"AWS::ElasticBeanstalk::Environment\\\",\\\"user\\\":\\\"\\\",\\\"trace_id\\\":\\\"1-5f4f4150-cc007f9c953145acaf2c2097\\\",\\\"end_time\\\":1599029583.6059926,\\\"http\\\":{\\\"request\\\":{\\\"method\\\":\\\"GET\\\",\\\"url\\\":\\\"http://node:3000/\\\"},\\\"response\\\":{\\\"status\\\":200,\\\"content_length\\\":0}},\\\"fault\\\":false,\\\"error\\\":false,\\\"throttle\\\":false,\\\"aws\\\":{\\\"xray\\\":{\\\"sdk\\\":\\\"opentelemetry for java\\\",\\\"sdk_version\\\":\\\"0.7.0\\\",\\\"auto_instrumentation\\\":false},\\\"account_id\\\":\\\"\\\",\\\"operation\\\":\\\"\\\",\\\"region\\\":\\\"\\\",\\\"request_id\\\":\\\"\\\",\\\"queue_url\\\":\\\"\\\",\\\"table_name\\\":\\\"\\\"},\\\"namespace\\\":\\\"remote\\\",\\\"parent_id\\\":\\\"4c924146b588cd9b\\\",\\\"type\\\":\\\"subsegment\\\"}\\n\",\"{\\\"name\\\":\\\"myservice\\\",\\\"id\\\":\\\"afebd02a77b96f51\\\",\\\"start_time\\\":1599029583.5810022,\\\"service\\\":{\\\"version\\\":\\\"3234fsf2\\\"},\\\"origin\\\":\\\"AWS::ElasticBeanstalk::Environment\\\",\\\"user\\\":\\\"\\\",\\\"trace_id\\\":\\\"1-5f4f4150-cc007f9c953145acaf2c2097\\\",\\\"end_time\\\":1599029583.5904381,\\\"http\\\":{\\\"request\\\":{\\\"x_forwarded_for\\\":true,\\\"method\\\":\\\"GET\\\",\\\"url\\\":\\\"http://localhost:8080/\\\",\\\"user_agent\\\":\\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36\\\",\\\"client_ip\\\":\\\"172.18.0.1\\\"},\\\"response\\\":{\\\"status\\\":200,\\\"content_length\\\":0}},\\\"fault\\\":false,\\\"error\\\":false,\\\"throttle\\\":false,\\\"aws\\\":{\\\"xray\\\":{\\\"sdk\\\":\\\"opentelemetry for java\\\",\\\"sdk_version\\\":\\\"0.7.0\\\",\\\"auto_instrumentation\\\":false},\\\"account_id\\\":\\\"\\\",\\\"operation\\\":\\\"\\\",\\\"region\\\":\\\"\\\",\\\"request_id\\\":\\\"\\\",\\\"queue_url\\\":\\\"\\\",\\\"table_name\\\":\\\"\\\"},\\\"metadata\\\":{\\\"default\\\":{\\\"http.flavor\\\":\\\"HTTP/1.1\\\",\\\"http.response_content_length\\\":\\\"\\\",\\\"servlet.context\\\":\\\"\\\",\\\"servlet.path\\\":\\\"/\\\"}},\\\"namespace\\\":\\\"\\\",\\\"parent_id\\\":\\\"\\\",\\\"type\\\":\\\"\\\"}\\n\"]\n}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}
otel-collector_1  | {"level":"debug","ts":1599029584.5458813,"caller":"awsxrayexporter/awsxray.go:94","msg":"response: {\n  UnprocessedTraceSegments: [{\n      ErrorCode: \"InvalidParentId\",\n      Id: \"afebd02a77b96f51\",\n      Message: \"Invalid segment. ErrorCode: InvalidParentId\"\n    }]\n}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}
```

**Comment by anuraaga** [comment]
@maciejqantas Thanks for the report - the data looks good as it has a `SERVER` span at the root (the span without a parent ID). Unfortunately, a fix for a critical bug did not make the 0.9.0 cut so the aws exporter is broken in the latest release.

https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/cb45b36c8afb1c2cf17312ca1badbf1ed62758e9

Can you try using `otel/opentelemetry-collector-contrib-dev` to see if it works?

**Comment by maciejqantas** [comment]
@anuraaga 
Thanks for that! I've grabbed `otel/opentelemetry-collector-contrib-dev:31c0d95d7cf9e1b2a1601bbdca6889d7e43ddd11` and that seems to have done the trick - I can now see traces in XRay.

I do however see an error in the response:
```
{"level":"debug","ts":1599436230.8414,"caller":"awsxrayexporter/awsxray.go:94","msg":"response: {\n  UnprocessedTraceSegments: []\n}","component_kind":"exporter","component_type":"awsxray","component_name":"awsxray"}
```
Is that something I should worry about?

**Comment by maciejqantas** [comment]
Also, @anuraaga, I notice that my service is represented as `AWS::ElasticBeanstalk::Environment`. Missing config on my end or a hardcoded string somewhere in the exporter?
