### ISSUE TITLE
Signalfx exporter: event exporter uses only first access token from the logs batch

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#4835]
`BatchPerResourceMetrics` is applied for metrics to make sure that metrics with different access tokens pushed separately. The same approach must be added to [signalfx events/logs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/signalfxexporter/eventclient.go#L47) . Otherwise `batch` processor added to the signalfx events pipeline breaks the Access token passthrough.

**Comment by atoulme** [comment]
It looks like this is implemented with https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4f2660e601229c3e8f38b8d5e4f617d6dd05637e/exporter/signalfxexporter/factory.go#L180 is there anything more to do for this issue?

**Comment by dmitryax** [comment]
@atoulme looks like you're right. I believe this can be closed now
