### ISSUE TITLE
Dynatrace - exporter for traces

### ISSUE THREAD

**Issue by sumitdhameja** [open-telemetry/opentelemetry-collector-contrib#4875]
**Is your feature request related to a problem? Please describe.**
I am able to export metrics to dynatrace using dynatrace exporter. However, when I tried to export traces from service mesh to dynatrace, noticed that there's no exporter for traces. 

**Describe the solution you'd like**
Have a tracer exporter for dynatrace

Is there a way to export traces to dynatrace using otel collector?

**Comment by arminru** [comment]
Hi @sumitdhameja! Sorry for the late answer, I just discovered your issue.
For traces we offer an ingest endpoint that supports OTLP natively, so you can just use the OTLP/HTTP exporter coming with the OTel collector out of the box.
More details and instructions can be found here:
https://www.dynatrace.com/support/help/extend-dynatrace/opentelemetry/#ingest-trace-data
https://www.dynatrace.com/support/help/extend-dynatrace/opentelemetry/opentelemetry-ingest/

**Comment by sumitdhameja** [comment]
Thank you @arminru
