### ISSUE TITLE
use exporters kafka with sasl get error

### ISSUE THREAD

**Issue by jack161641** [open-telemetry/opentelemetry-collector-contrib#4913]
**Describe the bug**
Error: cannot build pipelines: cannot build builtExporters: error creating kafka exporter: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
2021/06/15 17:25:48 application run finished with error: cannot build pipelines: cannot build builtExporters: error creating kafka exporter: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)
collector v0.28.0
kafka 2.2.0
**What config did you use?**
Config: (e.g. the yaml config file)
exporters:
  logging:
    logLevel: debug
  file:
    path: /home/admin/opentelemetry-collector/otel-collector.json
  kafka:
    protocol_version: 2.2.0
    brokers:
      - 10.2.103.187:9094
      - 10.2.103.185:9094
      - 10.2.103.186:9094
    topic: otlp_spans
    auth:
      sasl:
        username: kafka_user
        password: xxxxxx
        mechanism: PLAIN

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]

**Environment**
OS: (e.g., "Ubuntu 20.04") CentOS Linux release 7.2.1511
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by MovieStoreGuy** [comment]
I am going to close this issue off since the version in question is from 2021. If this issue still persists please feel free to ping me here and I will reopen the issue.
