### ISSUE TITLE
attributes processor - regex replace action

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-collector-contrib#4914]
**Is your feature request related to a problem? Please describe.**
I have a need to remove only certain URL parameters from the `http.url` attribute. Some parameters such as email, user, etc can leak PII data.

**Describe the solution you'd like**
A way to rewrite the `http.url` attribute removing only the PII parameters. This could be accomplished with a "regex_replace" type of action that will allow the operator to specify a regex with capture groups, which are referenced in replace string.

For example using this regex/replace
regex: `^(.*)((&|\?)user\=.+?)(&(.*)$|$)`
replace: `$1$4`

We would get the following input / output sets
Input1: `https://otel.io/path?foo=bar&user=hide_me&param2=value2`
Output1: `https://otel.io/path?foo=bar&param2=value2`

Input2: `https://otel.io/path?foo=bar&user=hide_me`
Output2: `https://otel.io/path?foo=bar`

Another potential solution is to have a new action that can "concatenate" multiple attributes. This could then be used in conjunction with the existing `extract` action.
 

**Describe alternatives you've considered**
I have tried to accomplish this using extract, which allowed me to extract any string before and after the `user` parameter, however, concatenating the "before" and "after" attributes back into a single attribute was not possible.

**Comment by floyola** [comment]
Any update or workaround about this? 😥 

It would be a great feature in the collector.

**Comment by leonsp-ai** [comment]
@puckpuck I'm contributing a new redaction processor that's designed for this use case. Right now I'm looking for an existing contributor to sponsor the PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6495
