### ISSUE TITLE
Add compression options for kafka exporter

### ISSUE THREAD

**Issue by bputt-e** [open-telemetry/opentelemetry-collector-contrib#4917]
**Is your feature request related to a problem? Please describe.**
We're storing traces into kafka for downstream processing and we're using quite a bit of disk space. According to the kafka producer docs, there is no compression by default.

**Describe the solution you'd like**
Update the kafka exporter to accept a compression codec and the level of compression, ex:
```
exporters:
  kafka:
    compression:
      codec: zstd
      level: 6
```

**Describe alternatives you've considered**
None, we're setting up jaeger ingester that reads from kafka and are noticing that once we set compression.type=(anything other than none) that it doesn't process the messages

**Additional context**
Referencing the documentation for default compression for the go library that the producer uses
https://github.com/Shopify/sarama/blob/master/config.go#L171

**Comment by Saber-W** [comment]
@C4RTON I'm not working on this. Feel free to implement this feature. You can also refer to my implementation [here](https://github.com/open-telemetry/opentelemetry-collector/pull/3295).

**Comment by bputt-e** [comment]
Related to #6079
