### ISSUE TITLE
k8sTagger - support regex for selecting annotations and labels

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-collector-contrib#4953]
**Is your feature request related to a problem? Please describe.**
Instead of specifying list of annotations and labels to collect, I would like to configure it to get all. 

**Describe the solution you'd like**
support regex match for annotations and labels so that when i use `.*`, it would get all annotations and labels. 

**Describe alternatives you've considered**
make it default to get all unless specified. so list of annotation and labels works as a filter instead of selector. 

**Additional context**
feedback from sck-otel customer. label is important data that they use to filter on collected data. having to specify what to enrich the data with is hard to maintain.

**Comment by mtwo** [comment]
A common use case that I've heard at customer meetings is applying a common set of pod labels as dimensions / annotations on metrics, traces, and logs. Users can custom-define these labels, and there are often too many to efficiently apply all of them, but it would be nice if the Collector captured some common / built-in ones. For example, Datadog's agent does a nice job of this: https://docs.datadoghq.com/agent/kubernetes/tag/?tab=containerizedagent

**Comment by rockb1017** [comment]
Closing since PR for it is merged. Thanks
