### ISSUE TITLE
Problems to use otel-collector as log pipeline

### ISSUE THREAD

**Issue by gillg** [open-telemetry/opentelemetry-collector-contrib#4955]
**Use case sample**
Syslogreceiver > Lokiexporter

**Is your feature request related to a problem? Please describe.**
Hello, as discussed in previous issues (I will search and attach them later) otel logs can have a structured body, and/or attributes. In different case we have very different results.
Ex: fluent forward receiver don't fill any body... We only have attributes.
In opposite, syslogreceiver don't fill attributes and we only have (a structured) body.

Both receivers are correct in term of opentelemtry.
But at the exporter level it can be complex to handle (here impossible for syslog) depending on the technology.
Loki need a body and labels (selected set on metadata), so we need a way to extract them from otel attributes, and/or structured body, and/or resources.

An additional processor to parse an unstructured body could be useful in some cases (even if I'm not fan for perf reasons), to convert it as structured or map extracted parts to attributes.

**Comment by punya** [comment]
Hi @gillg! Would you mind linking the previous issues relevant to this topic? Also, it would be helpful to call out specific enhancements that you're looking for, with as much precision and concrete use cases as possible.

**Comment by gillg** [comment]
Hi @punya thanks for the reminder ! 😅 
A similar issue / brainstorming was on https://github.com/open-telemetry/opentelemetry-collector/issues/2588
It's initially related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2529

A PR is in progress on Loki exporter to allow a better mapping between otel / Loki but it was not plan to be able to map body attributes to Loki labels (specific log metadata similar to attributes but to chose carefully, at least one is mandatory)

I also started some rewrite (pr not ready yet) on fluent receiver to allow a manual mapping from attributes to body and severity.

**Comment by gillg** [comment]
Maybe, an alternative to these pr could be to extend the attributesprocessor (or a new thing) to manipulate a structured body as AttributeMap and be able to move data from attributes to body and vice versa.
