### ISSUE TITLE
Unable to get github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/jaeger

### ISSUE THREAD

**Issue by zalegrala** [open-telemetry/opentelemetry-collector-contrib#4961]
**Describe the bug**

I'm looking to use the translation code for Jaeger and unable to include it in my project due to a versioning issue.

**Steps to reproduce**
```
❯ go get github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/jaeger
go get: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/jaeger@v0.0.0-20210829183103-2d1672ce1a53 requires
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**What did you expect to see?**
I expected the code to download and update my go.mod for including the new module.

**What did you see instead?**

An error describing the revision mentioned in the go.mod for the package is not known.

**What version did you use?**

I'd use any version that contained this translation code.

**What config did you use?**

N/A

**Environment**
OS: Archlinux
Compiler: go 1.17

**Additional context**

If the code exists elsewhere in a different version, please advise.

**Comment by punya** [comment]
@zalegrala could you try again? v0.34.0 of both these modules was tagged soon after you created this issue, and it looks like it sets the dependencies correctly.

Please reopen this issue if the issue continues to appear.
