### ISSUE TITLE
can opentelemetry collector collect data directly from thanos?

### ISSUE THREAD

**Issue by SkrPaoWang** [open-telemetry/opentelemetry-collector-contrib#4970]
as title

**Comment by hwrdthdck** [comment]
That's not what the person meant... seems pretty clear that he/she was asking Thanos -> OTEL ... your answer is OTEL -> Thanos.

**Comment by jpkrohling** [comment]
Sure, but further clarification is needed: what do you mean with the request? Do you want to see Thanos own telemetry being exported to OpenTelemetry? Without further clarification, I'd say that this is a question for the Thanos folks.

cc @bwplotka, who might be able to decipher what's being asked here :-)

**Comment by NikitaVoitov** [comment]
Question was pretty much clear: Thanos -> OTEL. Setup when I want to convert Thanos aggregated telemetry to OTEL and then send it to OTLP compliant backend. Any thoughts how to configure that?

**Comment by jpkrohling** [comment]
I feel like this would be better directed at the Thanos folks.

**Comment by jpkrohling** [comment]
@ArthurSens has helped me confirm with the Thanos folks that this is not possible.

**Comment by ArthurSens** [comment]
Thanos does not receive, nor export metrics in the OTLP format. Although [receiving OTLP is already being discussed](https://github.com/thanos-io/thanos/issues/6932).

[Thanos-Ruler is capable of performing remote-write](https://thanos.io/tip/components/rule.md/#stateless-ruler-via-remote-write), so, in theory, an otel-collector configured with remotewritereceiver would be able to ingest it. I'm not sure if there's a use case where you want to ingest the results from Thanos-ruler though.

That's it for metrics.

Now unrelated to metrics, Thanos produces spans that can be ingested by a otel-collector just like any other application
