### ISSUE TITLE
Prometheus Receiver - Some counter metrics dropped for unknown reason

### ISSUE THREAD

**Issue by gillg** [open-telemetry/opentelemetry-collector-contrib#4974]
**Describe the bug**
Analyzing an opentelemetry collector setup and trying to create dashboards with collected metrics, I discovered some droped metrics for an unknown reason.
I have a bunch of "dropped" metrics without any logs or traces.
Eventualy, 
I have some logs `info    internal/metrics_adjuster.go:357        Adjust - skipping unexpected point      {"kind": "receiver", "name": "prometheus", "type": "UNSPECIFIED"}`
So they seems dropped due to an unspecified type. I added some logs on metricFamily.go to vizualize their metada, and they are empty.

As exemple this list completly disapear between the receiver and the exporter :
```
otel-collector    | cortex_deprecated_flags_inuse_total {Metric: Type: Help: Unit:}
otel-collector    | cortex_experimental_features_in_use_total {Metric: Type: Help: Unit:}
otel-collector    | go_memstats_alloc_bytes_total {Metric: Type: Help: Unit:}
otel-collector    | go_memstats_frees_total {Metric: Type: Help: Unit:}
otel-collector    | go_memstats_lookups_total {Metric: Type: Help: Unit:}
otel-collector    | go_memstats_mallocs_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_admin_user_created_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_dashboard_snapshot_create_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_dashboard_snapshot_external_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_dashboard_snapshot_get_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_login_oauth_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_login_post_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_login_saml_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_models_dashboard_insert_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_org_create_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_response_status_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_user_signup_completed_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_user_signup_invite_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_api_user_signup_started_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_aws_cloudwatch_get_metric_data_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_aws_cloudwatch_get_metric_statistics_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_aws_cloudwatch_list_metrics_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_datasource_request_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_db_datasource_query_by_id_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_emails_sent_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_instance_start_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_page_response_status_total {Metric: Type: Help: Unit:}
otel-collector    | grafana_proxy_response_status_total {Metric: Type: Help: Unit:}
otel-collector    | http_request_total {Metric: Type: Help: Unit:}
otel-collector    | loki_logql_querystats_duplicates_total {Metric: Type: Help: Unit:}
otel-collector    | loki_logql_querystats_ingester_sent_lines_total {Metric: Type: Help: Unit:}
otel-collector    | process_cpu_seconds_total {Metric: Type: Help: Unit:}
```
I had to put custom logs to understand, and the seems dropped because the Type is unspecified and they have no metadata from metricFamily.go

For an unknown reason some other metrics ending with `_total` are working like : 
```
node_cpu_seconds_total{cpu="0",mode="idle"}
```

**Steps to reproduce**
I don't know exactly... Try to scrap a grafana API on http://grafana:3000/metrics

**What did you expect to see?**
Metrics should be kept internaly, then visible at the exporter side.

**What did you see instead?**
No metrics at the exporter side, and probably dropped on metrics_adjuster.go (a log with metric name is definitely missing here)

**What version did you use?**
0.25

**Comment by etiennejournet** [comment]
Hello, I also might have the same problem, running 0.37.1. @gillg have you been able to find a solution ?

 See the metrics points missing :
![image](https://user-images.githubusercontent.com/49070410/139748454-5313b95d-6e2e-4b68-9afc-fdee1f53f096.png)

In this I'm trying to scrape `container_cpu_usage_seconds_total` (which is a counter). 

Might be unrelated but : I'm running the collector in standalone mode (single replica) and I noticed that metrics are always consistent for targets being on the same node as the collector. For targets located on another node it's erratic.

Will update.

**Comment by gillg** [comment]
Hello @etiennejournet for now I don't have any solution about dropped counters. But this scenario seems not match with your graph. In your case you have dropped points and not dropped entire time serie.
I suspect in your case #memorylea

**Comment by etiennejournet** [comment]
Thanks for you answer ;) 

I don't think it's the memory leak problem, I had a careful look to your other thread about that and my opentelemetry setup doesn't show any sign of refused/dropped metrics endpoints in the receiver or exporters, I don't even see the memory leak in my own monitoring.

I'm going to dig that further, thanks for your time ;)

**Comment by gillg** [comment]
This problem seems have disapear with the latest otel collector contrib (v0.42.0 as today).
Not sure how, but my initial guess was once the scapper was converted to internal otel metrics instead of opencensus.

Can be closed for now :)

**Comment by chzhuo** [comment]
Same problem, running v0.78.0!
I am using `prometheusreciver` to scrap `node-exporter` and all metrics ending with `_total` be dropped

**Comment by baez90** [comment]
Same here, although not all with `_total` are dropped but for instance `container_cpu_usage_seconds_total` (from cAdvisor) is dropped although `container_cpu_usage_seconds` is present

**Comment by gillg** [comment]
@chzhuo @baez90 your problem is different.
It's related to this: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20518

Discusstion related here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21743

Workaround in 0.78.0: `--feature-gates=-pkg.translator.prometheus.NormalizeName`
Will be reverted by default in 0.80.0
