### ISSUE TITLE
Allow remote write tuning for the prometheusremotewriteexporter

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector-contrib#4979]
Prometheus server provides a variety of options for the users to fine tune the remote write API calls. These parameters are summarized at https://prometheus.io/docs/practices/remote_write/. prometheusremotewriteexporter should allow users to tweak the exporter in a similar fashion where possible. 

cc @jeromeinsf @alolita

**Comment by bixu** [comment]
We may be hitting this behavior in my org:

```
ts=2024-11-14T16:26:15.172Z caller=write_handler.go:134 level=error component=web msg="Out of order sample from remote write" err="out of order sample" series="{__name__=\"http_server_response_size_bytes_count\", app_name=\"my_app\"}" timestamp=1731601574754
```
