### ISSUE TITLE
Support verbatim prometheus configurations

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#4980]
**Is your feature request related to a problem? Please describe.**

As a new user, I copied the [example configuration for kuberntes](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml) from prometheus/prometheus (see [my copy here](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml)), but it produced errors when trying to scrape my workloads.  For example:
```
2020-11-16T20:48:03.756Z	debug	scrape/scrape.go:1124	Scrape failed	{"component_kind": "receiver",
"component_type": "prometheus", "component_name": "prometheus", "scrape_pool": "kubernetes-service-endpoints",
"target": "http://:/metrics", "err": "Get \"http:///metrics\": http: no Host in request URL"}
```

Eventually, I found another opentelemetry config, and noticed the double $ before variables, which led me to https://github.com/open-telemetry/opentelemetry-collector/issues/1112.  After substituting $$ for $ [in this commit](https://github.com/dashpole/dashpole_demos/commit/eb8d91ab7da48a638000e9cf87e76a4e88681df8#diff-c7af5162b83f7957ea31202293e1117d402b495dd0f823ed4da5acc541eecf02), everything worked fine.

I believe being able to reference a verbatim prometheus configuration would make the opentelemetry collector much easier to adopt, as it would more easily enable sharing between the two ecosystems.

**Describe the solution you'd like**

I'd like to be able to reference an existing prometheus configuration file as an alternative to embedding it in the collector configuration file.  Instead of:
```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
      scrape_configs:
      - job_name: 'foo'
        ...
```
I can instead do:
```
receivers:
  prometheus:
    config_file: prometheus-kubernetes.yaml
```

**Describe alternatives you've considered**
Better documentation around using prometheus configurations.  I think this will help, but can only go so far.

cc @nilebox @james-bebbington

**Comment by odeke-em** [comment]
I've mailed out this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5080, please take a look.
