### ISSUE TITLE
Cumulative Counters - Prometheus receiver- Magnitude of the metrics is lost

### ISSUE THREAD

**Issue by vishiy** [open-telemetry/opentelemetry-collector-contrib#4982]
In using prometheus receiver, i see prometheus counters are being re-calculated from the first data point, which loses the actual value/magnitude of the metric. Is there a way to pass on the initial value in the pipeline so that it can be added back before ingesting to backends like prometheus ?

Also tracking this on proto - https://github.com/open-telemetry/opentelemetry-proto/issues/289
Related on proto - https://github.com/open-telemetry/opentelemetry-proto/issues/229

**Comment by gouthamve** [comment]
Hi, is this still an issue? I've run a `node_exporter` and then start scraping using the OTel Collector, and I can see the absolute values. I am not sure this issue is still relevant.

**Comment by gillg** [comment]
I think it has been addressed since the refactoring. I agree I never had a new issue in recent versions.

**Comment by vishiy** [comment]
This was fixed. Can be closed
