### ISSUE TITLE
Set reasonable defaults to the prometheusremotewriteexporter

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector-contrib#4988]
prometheusremotewriteexporter doesn't have Prometheus-specific default retry settings at this moment and we should set better defaults. This is impacting the overall retry strategy and how aggressive retries should be.

**Comment by khanhntd** [comment]
Hey @alolita, can I possibly try this one?

**Comment by khanhntd** [comment]
Hey @rakyll, good news is that the current prometheusremotewriteexpoter has the [retry and timeout setting](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/34a38f6a52af70f7de946738eda21ca6a1b2c452/exporter/prometheusremotewriteexporter/config.go#L30-L31).

**Comment by khanhntd** [comment]
Hey @alolita. please help me close this issue since the feature has existed.
