### ISSUE TITLE
Open-telemetry collector panic crash with Prometheus

### ISSUE THREAD

**Issue by girishgrover2008** [open-telemetry/opentelemetry-collector-contrib#4990]
**Describe the bug**
I am using opentelemetry collector to collect data from Prometheus which is monitoring our kubernetes cluster. Idea is open telemetry  collector can collect data from Prometheus and report it to our API. While doing so collector is getting panicked and crashing with segmentation fault.  

**Steps to reproduce**
Attaching yaml file for the config that i am using and monitoring the kubernetes cluster.

**What did you expect to see?**
Our API server is running grpc receiver, open telemetry should have collected metrics and forwarded to the API server.

**What did you see instead?**
Segmentation fault with bunch of errors/warnings.

**What version did you use?**
{"Version": "v0.25.0", "GitHash": "d93c9d29", "NumCPU": 16}

**What config did you use?**
Attached config.
[ot-collector.yaml.txt](https://github.com/open-telemetry/opentelemetry-collector/files/6397686/ot-collector.yaml.txt)

**Environment**
Running above yaml file as a pod on a kubernetes server. 

Logs :
Attached.
[logs.txt](https://github.com/open-telemetry/opentelemetry-collector/files/6397766/logs.txt)

**Comment by odeke-em** [comment]
> It appears the PR associated with this issue has been merged but is not in the latest Beta (0.30.0). How can we ensure it gets in the next release?

@ipstatic I believe that code got released in the latest release. @alolita or @Aneurysm9 can we please close this issue?
