### ISSUE TITLE
Proposal: Route `LogRecord` to different exporters

### ISSUE THREAD

**Issue by sincejune** [open-telemetry/opentelemetry-collector-contrib#5007]
### **Is your feature request related to a problem? Please describe.**
We can have multiple `LogRecords` in an `ExportLogsServiceRequest` object and each `LogRecord` can have its own attributes. Now I have no way to send these `LogRecords` to different exporters according to their own attributes.

Assuming I have two `LogRecords` inside one `ResouceLog` of an `ExportLogServiceRequest`, LogRecord-A has an attribute `service=file` and LogRecord-B has an attribute `service=kafka`. In this case, I wanna export `LogRecord-A` to file and `LogReocrd-B` to Kafka.

I can see there are some related processors, but they didn't help much.
##### FilterProcessor ([ref](https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/filterprocessor))
With this design, I have to re-ingest logs because it will discard records that didn't match. (although, it doesn't support logs yet)

##### RoutingProcessor([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor))
It can only route a whole `ExportLogsServiceRequest`.

##### GroupByAttriProcessor([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor))
It can group `LogRecords` into different `ResouceLog` for a single `ExportLogServiceRequest`.

### **Describe the solution you'd like**
I can only think of two solutions for this case:
1. Support invoking `processors` in an `exporter` so that I can filter `LogRecord` in Kafka exporter.
2. Make a processor that can break one `ExportLogsServiceRequest` to multiple `ExportLogsServiceRequest` so that we can achieve the goal by working with `GroupByAttriProcessor` and `RoutingProcessor`.

I'd like to contribute, but either of the solutions needs an architectural change.

**Comment by sumo-drosiek** [comment]
Is there planned any progress with that issue?
I have similar problem now, I would like to be able to route records basing on the resource attributes.

**Comment by jpkrohling** [comment]
> Actually, I didn't find a proper way to route the specified traceId to a specific exporter even with the groupbytrace processor

You are right: we either load balance based on the trace ID, or we route based on other attributes.

> This is a simple, intuitive, and universal solution that will cover my case for multi-tenants (probably not the best one).

This is in line with how it works for traces, from what I remember. It would be my preferred soluton.

**Comment by jpkrohling** [comment]
I believe this has been implemented already. If you think there's still something missing, feel free to reopen.
