### ISSUE TITLE
FileExporter file separation

### ISSUE THREAD

**Issue by EliyaCohen** [open-telemetry/opentelemetry-collector-contrib#5008]
I want to use the FileExporter to transfer files from places where I don't have direct network access to the main collector. For example, when using a DMZ that only allows file transfers. 
The current exporter only allows writing to a single file, so it can't be used reliably to send the file through the DMZ (The file will always be locked under large workloads)

I'd like that the FileExporter will have the option to write data to a directory and separate each trace/metric to a single file.

Alternatively, it can be split based on time interval or file size.

EDIT: Perhaps cronolog can be used in that scenario. 
Any thoughts?

**Comment by adirmatzkin** [comment]
Having the same need, I was wondering if there is any new progress ? @EliyaCohen  @bogdandrutu 
I'm willing to help of course ☺️

**Comment by mladedav** [comment]
@bogdandrutu can this be reopened? I think the file rotation would be a great thing to have here.

**Comment by gitck-scch** [comment]
> @bogdandrutu can this be reopened? I think the file rotation would be a great thing to have here.

Note: the feature 'file rotation' is available since at least v0.60.0 - see documentation for usage: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter
