### ISSUE TITLE
SAPM Exporter - stable component request

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-collector-contrib#5032]
The [SAPM Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/sapmexporter/README.md) has been feature complete since 12/20 and without non-proto based changes since 5/21.  It is the recommended tracing format for reporting distributed traces to Splunk APM and part of all default configurations of the Splunk OpenTelemetry Collector distribution.

This is a request for its status to be marked as stable coinciding with the Collector's stable tracing date*.

(cc: @bogdandrutu, @tigrannajaryan, @flands, @emaderer)

**Comment by tigrannajaryan** [comment]
+1. @bogdandrutu do we already have a system of marking components stable?

**Comment by atoulme** [comment]
+1 what is in the way of declaring sapm exporter and receiver stable?

**Comment by mx-psi** [comment]
I think this and #17435 should be marked as blocked until open-telemetry/opentelemetry-collector/issues/5686 is resolved

**Comment by atoulme** [comment]
Thank you for the link to the issue @mx-psi!
On 1/11, we had during the SIG meeting a discussion of this issue.
There is indeed this ongoing issue to be resolved first.
Juraci also noted that if the component depends on a library such as confighttp or configtls which are not marked stable yet, that blocks the component from being declared stable.

**Comment by atoulme** [comment]
Removing `on hold` since the blocker is closed.
