### ISSUE TITLE
Filter trace based on span attribute

### ISSUE THREAD

**Issue by jack161641** [open-telemetry/opentelemetry-collector-contrib#5035]
**Is your feature request related to a problem? Please describe.**

I want to filter traces based on the span attribute. For example, traces with errors use a 100% sampling rate and traces without errors use a 10% sampling rate. However, I found that the filter processor can only filter metrics

**Describe the solution you'd like**
Filter processor support traces

**Describe alternatives you've considered**

**Additional context**

**Comment by boostchicken** [comment]
That sounds like a sampling processor enhancement.  I am about to write a filter processor enhancement that drops Span's based on tag matching, however what you want sounds like it should be a special type of sampler

**Comment by boostchicken** [comment]
See my PR here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6341

You could chain that in a custom pipeline with static sampling
