### ISSUE TITLE
Need to add k8sEventReceiver

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-collector-contrib#5047]
using 
https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/operators/k8s_event_input.md
to collect k8s objects/events

**Comment by punya** [comment]
Could you add some details about the use case for this receiver, and what sort of OTel data it will produce?

**Comment by hprajapati-splunk** [comment]
Here's the Proposed Design Document for the `k8seventsreceiver`: https://docs.google.com/document/d/1M9M6alW0ftmsBPBftKtH4h3eewpq263Ep678qU0YlB4/edit?usp=sharing
