### ISSUE TITLE
Unable to use AWS Container Insights Receiver

### ISSUE THREAD

**Issue by stephenhong** [open-telemetry/opentelemetry-collector-contrib#5180]
Hello team, I'm trying to enable AWS Container Insights Receiver but the otel collector fails to start with the following message:
`Error: cannot load configuration: unknown receivers type "awscontainerinsightreceiver" for awscontainerinsightreceiver
2021/09/09 20:54:06 collector server run finished with error: cannot load configuration: unknown receivers type "awscontainerinsightreceiver" for awscontainerinsightreceiver`

I'm using v0.34.0 of `otelcontribcol_linux_amd64`

**Comment by mxiamxia** [comment]
'awscontainerinsightreceiver' looks are not enabled in `otelcontribcol` distributions yet. It is only enabled in [AWS Distro for OpenTelemetry Collector](https://github.com/aws-observability/aws-otel-collector) now. 

I don't think this is intended, will submit a fix to enable it in `otelcontribcol`.

**Comment by alolita** [comment]
This is fixed. Closing.
