### ISSUE TITLE
make otelcontribcol failed

### ISSUE THREAD

**Issue by skyduo** [open-telemetry/opentelemetry-collector-contrib#5226]
**Describe the bug**
i met this issue last week in my pr workspace that build failed , and i download OT contrib repo in a new workspace today and directly run `make otelcontribcol` but still failed, not sure what does this issue mean, need someone help to fix it.
```
3c22fb375681:opentelemetry-collector-contrib-newhealthcheckextension tianduo$ make otelcontribcol
GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ./bin/otelcontribcol_darwin_amd64 \
                -ldflags "-X github.com/open-telemetry/opentelemetry-collector-contrib/internal/version.Version=v0.29.0-3102-g403c12aa7" -tags containers_image_openpgp,exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper ./cmd/otelcontribcol
receiver/jaegerreceiver/trace_receiver.go:34:2: //go:build comment without // +build comment
make: *** [otelcontribcol] Error 1
```

**Steps to reproduce**
`make otelcontribcol`

**What did you expect to see?**
succeed

**What did you see instead?**
failed

**What version did you use?**
latest OT repo downloaded today

**Comment by tigrannajaryan** [comment]
Try Go 1.17 and see if it helps.

**Comment by skyduo** [comment]
based on SIG meeting, need to upgrade go to 1.17

**Comment by tigrannajaryan** [comment]
This Go change is the possible reason why https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md

**Comment by mx-psi** [comment]
I opened an upstream issue to report this jaegertracing/jaeger#3268 so that contrib can be built with Go 1.16 if folks want to

**Comment by skyduo** [comment]
already upgrade go to 1.17 and problem resolved, will close this issue
