### ISSUE TITLE
[k8sprocessor] Add an option to fetch container data

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#5235]
We are trying to utilize OTel logs collection instead of fluentd in k8s env. fluentd uses [kubernetes_metadata_filter plugin](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter) that collects container data along with k8s metadata by default, in particular container ID and container image name.

That data is pretty valuable for our use case, so we would like to have an option to collect:

- `container.image.name` and `container.image.tag` (maybe some other Container spec data) when `container.name` provided as resource attribute along with a kubernetes pod identifier.

- `container.id` (maybe some other Container status data) when `container.name` and `run_id` (restart count) provided as a resource attributes along with a kubernetes pod identifier.

I am open to any suggestions.

cc @owais @pmm-sumo

**Comment by rockb1017** [comment]
can we extract those container specs using pod UID? the list of containers is in pod spec https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podspec-v1-core

**Comment by dmitryax** [comment]
> can we extract those container specs using pod UID? 

Yes, we can, but we also need a container identifier along with that -- current k8s logs collection model provides us with `k8s.container.name`

**Comment by owais** [comment]
Sounds good to me. We can also do this for cases where the incoming data does not have any container identifying attributes but there is only one container in the pod.
