### ISSUE TITLE
Avoid usage of github.com/mtrmac/gpgme

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#5241]
**Describe the bug**
Trying to compile the otel collector contrib on MacOs fails within missing definitions. Furthermore, depends on cgo and limits ability to create a static binary that can be shipped anywhere.

**Steps to reproduce**
On an MacOS machine / Windows run `make test`

**What did you expect to see?**
`make test` works without issue.

**What did you see instead?**
```
/Users/smarciniak/go/pkg/mod/github.com/mtrmac/gpgme@v0.1.2/data.go:4:11: fatal error: 'gpgme.h' file not found
 #include <gpgme.h>
          ^~~~~~~~~
```

**What version did you use?**
Version: main @ 0d78df6b0455fd685cf6d9dcb654986e7de7ac86

**Environment**
OS: MacOs 11.6 
Compiler(if manually compiled): go 1.17.0

**Comment by mx-psi** [comment]
This comes from the Podman receiver.

```
❯ go mod why github.com/mtrmac/gpgme
# github.com/mtrmac/gpgme
github.com/open-telemetry/opentelemetry-collector-contrib/internal/components
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/podmanreceiver
github.com/containers/podman/v3/pkg/bindings/containers
github.com/containers/podman/v3/pkg/api/handlers
github.com/containers/common/libimage
github.com/containers/image/v5/signature
github.com/mtrmac/gpgme
```

Also, `make test` is missing `CGO_ENABLED=0` on its task definition. @MovieStoreGuy could you try and see if adding `CGO_ENABLED=0` to `make test` fixes this for you?

**Comment by owais** [comment]
Collector itself excludes these dependencies when building as they are not actually needed for the podman receiver.

You can do the same by using the following build tags:

`containers_image_openpgp,exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper`

Ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/Makefile.Common#L21-L22

**Comment by MovieStoreGuy** [comment]
@mx-psi I actually had issues also running `make golint` and suspected it to be the same issue but present in a different way.
