### ISSUE TITLE
examples/tracing is broken

### ISSUE THREAD

**Issue by RoadRunnr** [open-telemetry/opentelemetry-collector-contrib#5245]
**Describe the bug**

The tracing_otel-collector_1 container from examples/tracing does not start. 
A log entry indicates a podman problem:

```
$ docker logs tracing_backend_1
time="2021-09-15T14:41:07Z" level=error msg="mkdir /rundir/libpod: no such file or directory"
```

**Steps to reproduce**

in examples/tracing, do:
```
docker-compose up -d
docker logs tracing_backend_1
```

**What did you expect to see?**

A running instance of the tracing_backend_1 container

**What did you see instead?**

No instance of the tracing_backend_1 container

**What version did you use?**

master

**What config did you use?**

unmodified config from the example

**Environment**
OS: Ubuntu 21.10

**Comment by mx-psi** [comment]
cc @owais, related to podman receiver?

**Comment by RoadRunnr** [comment]
removing the unprivileged user from the Dockerfile solves it, But I'm not sue that this is the correct fix.

**Comment by piellick** [comment]
Hey @RoadRunnr could you explain your workaround ?

**Comment by RoadRunnr** [comment]
remove these[ two lines ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/tracing/Dockerfile#L13-L14) and rebuild:

```
ARG USER_UID=10001
USER ${USER_UID}
```

**Comment by gebn** [comment]
We ran into this while attempting to upgrade from v0.34.0 to v0.35.0 using the official images. Changing only the tag:

`otel/opentelemetry-collector-contrib:0.34.0`:

```
$ kubectl logs otel-collector-b875885fc-2cdqr
2021-09-19T22:33:29.476Z        info    service/collector.go:303        Starting otelcontribcol...      {"Version": "v0.34.0", "NumCPU": 8}
...
```

`otel/opentelemetry-collector-contrib:0.35.0`:

```
$ kubectl logs otel-collector-567676fbbd-mj2fb
time="2021-09-19T22:23:16Z" level=error msg="mkdir /rundir/libpod: permission denied"
```

In case it's relevant, the pod is running with a custom `serviceAccountName` to allow `k8s_tagger` to function.

**Comment by githubcdr** [comment]
> We ran into this while attempting to upgrade from v0.34.0 to v0.35.0 using the official images. Changing only the tag:

confirmed here

**Comment by gebn** [comment]
This also reproduces with 0.36.0:

```
time="2021-09-21T23:30:39Z" level=error msg="mkdir /rundir/libpod: permission denied"
```
