### ISSUE TITLE
AWS XRay attribute conversion for deeply nested maps

### ISSUE THREAD

**Issue by errordeveloper** [open-telemetry/opentelemetry-collector-contrib#5266]
**Is your feature request related to a problem? Please describe.**

Currently AWS XRay exporter has two modes:
- `index_all_attributes` (bool)
- `index_attributes` (list of attribute keys, seems to only work for top-level keys)

It's possible to have a deeply nested map in the annotations, which the exporter currently doesn't allow to be index at all.

**Describe the solution you'd like**

It'd be nice to be able to have the following options:
- specify paths to any nested value in `index_attributes`
- automatically convert nested maps to a flat map
- automatically convert some/all values to JSON strings

This might be something to implement as a processor that can be used with other exporters.

**Describe alternatives you've considered**

Conversion can be implement on the client side in some cases, but that doesn't seem like a good answer to this problem.

**Comment by willarmiros** [comment]
Hi @errordeveloper,

> It's possible to have a deeply nested map in the annotations

This is not true. X-Ray annotations only support key-value pairs, with supported value types of string, number, and boolean. Only metadata (which is never indexed) can contain arbitrary JSON structures such as deeply nested maps. For more, you can see the X-Ray docs: https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-annotations

> specify paths to any nested value in index_attributes

Does this mean e.g. the path to an otel span attribute? E.g. `index_attributes=my_array_attribute[0].some_key`? If so, I think this is a reasonable suggestion.

> automatically convert nested maps to a flat map

This proposal would be feasible, though it seems like it could quickly run into limitations since X-Ray imposes a limit of 50 annotations per trace, which could easily be exceeded in a flat map conversion.

> automatically convert some/all values to JSON strings

Again, this is feasible but the main value of an X-Ray annotation is that it is searchable, and recording raw JSON strings does not seem like it would be very easy to search.

**Comment by errordeveloper** [comment]
> Hi @errordeveloper,
> 
> > It's possible to have a deeply nested map in the annotations
> 
> This is not true. X-Ray annotations only support key-value pairs, with supported value types of string, number, and boolean. Only metadata (which is never indexed) can contain arbitrary JSON structures such as deeply nested maps. For more, you can see the X-Ray docs: https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-annotations

I was referring to OpenTelemetry annotations, lot XRay ones, but I did also find out after creating this issue that is is not something the spec recommends... It just appears to be possible to encode arbitrarily deep data using protobufs, but that falls into a grey area of the spec...

> > specify paths to any nested value in index_attributes
> 
> Does this mean e.g. the path to an otel span attribute? E.g. `index_attributes=my_array_attribute[0].some_key`? If so, I think this is a reasonable suggestion.

Yes, something like that, perhaps.

> > automatically convert nested maps to a flat map
> 
> This proposal would be feasible, though it seems like it could quickly run into limitations since X-Ray imposes a limit of 50 annotations per trace, which could easily be exceeded in a flat map conversion.

Good to know! This was just one of the suggestions... 

> > automatically convert some/all values to JSON strings
> 
> Again, this is feasible but the main value of an X-Ray annotation is that it is searchable, and recording raw JSON strings does not seem like it would be very easy to search.

That sounds like a good reason not to do it, but dropping data seems a bit worse... Perhaps when coversion of some fields fails, those should be still sent in as metadata?

**Comment by errordeveloper** [comment]
> Therefore, it seems like the most valuable feature request is specifying arbitrary paths to OTel attributes to be indexed as X-Ray annotations, as opposed to only allowing top-level keys.

SGTM!

> We can track this from our end and try to prioritize it. FWIW, the current logic for storing attributes as X-Ray annotations/metadata is here if you're interested in trying a PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6fff7610fdf982db67904ee91006e63faf91a254/exporter/awsxrayexporter/internal/translator/segment.go#L322

I don't think I will get to it, as I have already wrapped up my OTel-related project (https://github.com/cilium/hubble-otel) and will be starting something new.
