### ISSUE TITLE
How to get total number of CPU cores in a K8s cluster

### ISSUE THREAD

**Issue by ankitnayan** [open-telemetry/opentelemetry-collector-contrib#5278]
Is there any receiver that gives you the total CPU cores present in the K8s cluster? I tried `kubeletstatsreceiver`, `k8sclusterreceiver` and `hostmetricsreceiver`. I could find metrics around usage and utilization per node, pod and container. 

In order to show the `percentage(%)` of CPU used in a VM or k8s cluster, we need to know the total number of CPU cores available. Do we have a receiver that gives the total number of cores?

**Comment by gingerwizard** [comment]
@ankitnayan did you find any good solution here?
