### ISSUE TITLE
Fluentforward receiver not shutting down TCP port

### ISSUE THREAD

**Issue by gagansingh355** [open-telemetry/opentelemetry-collector-contrib#5314]
**Describe the bug**

We are using WatchForUpdate() method to monitor our configuration file, and reload if any change comes in. When Fluentforward is started it creates TCP and UDP process at Listen port. But OTEL is not stopping these processes at shutdown. Therefore, when it reloads it is not able to start the receiver again as TCP process is not stopped and port is already occupied. Hence we get the error that _listen tcp 127.0.0.1:8006: bind: address already in use_

I think if this TCP process can be closed correctly similar to UDP process, reload part will work perfectly.

PS: We have tested our reload method with other receivers and exporters and it seems to be working fine.

**What config did you use?**
Config: (e.g. the yaml config file)

receivers:
  fluentforward:
    endpoint: 127.0.0.1:8006

<User defined exporter>:
  <Exporter's respective configuration>

extensions:
  fluentbit:
    executable_path: /opt/td-agent-bit/bin/td-agent-bit
    tcp_endpoint: 127.0.0.1:8006
    config: |
      [SERVICE]
        parsers_file /etc/td-agent-bit/parsers.conf
      [INPUT]
        name tail
        Read_from_Head true
        path /usr/local/apache2/logs/error_stack
        parser apache
        Mem_Buf_Limit     8MB

service:
  pipelines:
    logs:
      receivers: [fluentforward]
      processors: []
      exporters: [exporter]
  extensions: [fluentbit]

**Environment**
OS: Centos

**Comment by dmitryax** [comment]
Seems like a valid bug. @gagansingh355 do you have a chance to submit a fix?

**Comment by dmitryax** [comment]
Actually it's already fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9111. Closing
