### ISSUE TITLE
New stricter prometheusreceiver config validation breaks ecsobserver auto-discovery logic

### ISSUE THREAD

**Issue by straussb** [open-telemetry/opentelemetry-collector-contrib#5373]
**Describe the bug**
A [recent commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/52971307182587f31cb5a0b989402596bc9a31e9#diff-c335f316da4cfd1d6feec64b950de5600d871572b350b1fadfe411c54343e073) made config validation stricter on prometheusreceiver startup.  Specifically, if using [file_sd_configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config), it checks that the file(s) exist and have target groups.  But, when using the [ecsobserver extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/observer/ecsobserver) to auto-discover Prometheus targets, that file will not exist until runtime.

**Steps to reproduce**
The ADOT test framework has a [collector config](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/terraform/testcases/containerinsight_ecs_prometheus/otconfig.tpl) that reproduces the issue.
Example failed run: https://github.com/aws-observability/aws-otel-collector/runs/3668951066?check_suite_focus=true

**What did you expect to see?**
The collector should auto-discover Prometheus targets and scrape them.

**What did you see instead?**
Collector crashed on startup with error message:
```
Error: invalid configuration: receiver "prometheus" has invalid configuration: file "/etc/ecs_sd_targets.yaml" for file_sd in scrape job "ecssd" does not exist
2021/09/22 00:16:09 application run finished with error: invalid configuration: receiver "prometheus" has invalid configuration: file "/etc/ecs_sd_targets.yaml" for file_sd in scrape job "ecssd" does not exist
```

**What version did you use?**
v0.36.0

**What config did you use?**
https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/terraform/testcases/containerinsight_ecs_prometheus/otconfig.tpl

**Comment by straussb** [comment]
Don't think so, looks like the problematic code is still there.

**Comment by c-christophe** [comment]
Any news on this issue ?

**Comment by straussb** [comment]
This is still relevant.

**Comment by mplachter** [comment]
@straussb does a blank file at the location defined by `ecs_observer.result_file` solve this problem?

If so I think maybe the docs should be updated in `ecs_observer.result_file` declaring a blank file be present for `Prometheus`, my thought is, it does validate on startup that the file path is defined and reachable on startup which isn't bad behavior.

**Comment by straussb** [comment]
Disclosure, I don't work on OTel projects anymore, but I have [notified](https://github.com/aws-observability/aws-otel-collector/issues/1636) the owners of the repo that motivated this issue.

**Comment by lpsinger** [comment]
Also broken following the instructions at https://aws-otel.github.io/docs/getting-started/container-insights/ecs-prometheus.

**Comment by pazderak** [comment]
Hi there, this issue is still valid on v0.75 - just tested:
```
2023/04/21 11:32:18 main.go:103: application run finished with error: invalid configuration: receivers::prometheus: file "/etc/ecs_sd_targets.yaml" for file_sd in scrape job "services" does not exist
```

**Comment by PaurushGarg** [comment]
I think we should close this issue as the `ecs_observer` testcase has been re-enabled (https://github.com/aws-observability/aws-otel-collector/pull/2227) and the relevant PR (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21680) for the ecs_observer fix has been merged.
