### ISSUE TITLE
Changing `insecure` per READMEs no longer works

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector-contrib#5385]
See: https://github.com/open-telemetry/opentelemetry-collector/issues/4092

**Comment by hyunuk** [comment]
Hi @alolita , I'd like to work on this issue.

**Comment by ganga-sah** [comment]
"insecure: false" worked for me in previous image: otel/opentelemetry-collector-contrib:0.35.0 but fails with error below in next/latest version 0.36.0. Would like to see this fixed in latest version.
