### ISSUE TITLE
filelog receiver: consider leaving `SeverityText` empty instead of `Undefined`

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#5388]
If user doesn't specify any severity parsing in filelog receiver, all the collected logs are coming with the following fields:
SeverityNumber: 0
SeverityText: "Undefined"

Source code: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/stanza/converter.go#L559

According to the logs data model, [both of them](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-severitytext) are optional.

I'm curious why can't we leave `SeverityText` field empty instead of setting it to `"Undefined"`?

`0` value for `SeverityNumber` marked as `SeverityNumberUNDEFINED` in the filelog receiver, and the data model doesn't define this value. So we can assume that `SeverityNumber: 0` is a zero int value because the field is optional. So I believe `SeverityText` should be also set to zero string value `""` instead of `"Undefined"`.

@djaglowski @tigrannajaryan what do you think?

**Comment by djaglowski** [comment]
This seems reasonable to me.

**Comment by dmitryax** [comment]
> This seems reasonable to me.

@djaglowski sorry, could you please clarify? Is my suggestion reasonable or existing behavior? :)

**Comment by djaglowski** [comment]
@dmitryax, you're suggested change seems reasonable to me.

**Comment by dmitryax** [comment]
Thanks! I'll create a PR
