### ISSUE TITLE
failed to send trace payload to trace edge: Post "https://trace.agent.datadoghq.com/api/v0.2/traces": context deadline exceeded

### ISSUE THREAD

**Issue by grzn** [open-telemetry/opentelemetry-collector-contrib#5420]
Our collector is hitting the following error every few hours:
```
failed to send trace payload to trace edge: Post "https://trace.agent.datadoghq.com/api/v0.2/traces": context deadline exceeded
```

The collector config is as follows:
```
receivers:
prometheus:
# using prometheus receiver
config: to capture all the agent metrics and push them through

scrape_configs:
job_name: 'otelcol'
scrape_interval: 10s
static_configs:
targets: ['0.0.0.0:8888']
metric_relabel_configs:
- source labels: __name__
regex: '.*grpc_io.*'
action: drop
otlp:
protocols:
grpc:
http:
extensions:
health_check: {}
zpages: {}
exporters:
datadog:
api:
key: "$ {DATADOG_API_KEY}"
service:
extensions:
health_check
zpages
pipelines:
metrics:
receivers:
otlp
prometheus
processors:
exporters:
datadog
traces:
receivers:
otlp
processors:
exporters:
datadog
```

(this collector runs as deployment, receiving messages from agents running as a daemonset, and that's where the batch processing happens)

From what I understand, the datadogexporter runs with a 5 second timeout, and there's new option to change that as it does not have a timeout config option so it doesn't pass anything to the exporthelper factory?

is there a way to change the default 5 second timeout or use the queued sender from exporthelper?

**Comment by mx-psi** [comment]
Hey @grzn thanks for your issue. For visibility, the 'context deadline exceeded' error is tracked on #2353, but we can keep this issue open for the FR on exposing the retry queue settings. We will add this to our internal backlog and work on this at some point. I would also be happy to review a PR adding this feature.

**Comment by grzn** [comment]
@mx-psi  here you go https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5422

**Comment by mx-psi** [comment]
The feature has been added (thanks again @grzn!), closing this. For the bug related to this error message, please use the issue linked above
