### ISSUE TITLE
Remove squash on `configtls.TLSClientSetting` in contrib

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-collector-contrib#5433]
**Describe the issue**

Based on this PR (https://github.com/open-telemetry/opentelemetry-collector/pull/4063) in collector repo, configtls.TLSClientSetting should be defined as `mapstructure: "tls,omitempty"`.

Below links are files where changes are needed:

- [x] [/internal/aws/proxy/cfg.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5e4c6d6c91f3ca9aed5464de9a28c29d68dfa860/internal/aws/proxy/cfg.go#L35)
- [x] [/extension/awsxrayproxy/config.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/bccdf0a169fb3ed50c6fe52cd660211a423128c0/extension/awsxrayproxy/config.go#L38)
- [x] [/exporter/elasticexporter/config.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7bf2266a025425993a233f66c77a0810ab11a78b/exporter/elasticexporter/config.go#L27)
- [x] [/exporter/observiqexporter/config.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/56cab1639feaf97b517fc3f4cd9a9e554de5b99d/exporter/observiqexporter/config.go#L35)
- [x] [/exporter/splunkhecexporter/config.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4f83573e9a703de10dc6da5265726c3f95083986/exporter/splunkhecexporter/config.go#L79)
- [x] [/exporter/splunkhecexporter/config.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4f83573e9a703de10dc6da5265726c3f95083986/exporter/splunkhecexporter/config.go#L79)

**Comment by hyunuk** [comment]
@Aneurysm9 , please assign me this issue!
