### ISSUE TITLE
Deprecating SHA-1 as hashing algorithm in the attributesprocessor

### ISSUE THREAD

**Issue by HuBaX** [open-telemetry/opentelemetry-collector-contrib#5576]
**Is your feature request related to a problem? Please describe.**
My organization wants to obscure the content of some attributes in spans for privacy reasons. However, the attributes that contain sensitive data should not be deleted. They want to be able to recognize a correlation between certain values and an error case despite the obscured data. At the moment it is possible to hash certain attributes by the attributesprocessor. SHA-1 is used as the hashing algorithm here even though it is officially insecure. However, to ensure privacy, my organization would like to use a secure hashing method. I also don't understand why SHA-1 is used for attribute hashing in the first place.

**Describe the solution you'd like**
I would like to discuss if it makes sense to offer a secure hashing method besides SHA-1 or even to replace SHA-1 completely with it. If it comes to the decision to use a more secure hashing method I would like to implement this new functionality.

This is a "repost" of a [discussion I wanted to start a few weeks ago](https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/5318) since no one seems to read the discussions.

**Comment by atoulme** [comment]
What hashing algo would you like?

**Comment by atoulme** [comment]
SHA-2 is now on by default. We can close.
