### ISSUE TITLE
collector cannot be started using logzio exporter

### ISSUE THREAD

**Issue by William-LP** [open-telemetry/opentelemetry-collector-contrib#5577]
The collector ends up in error when providing a `logzio` exporter :
```bash
receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  logzio:
    account_token: <TOKEN>
  logging:
    loglevel: debug
processors:
  batch: 
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logzio,logging]
```
Output :
```bash
2021/10/04 13:00:58 application run finished with error: cannot load configuration: unknown exporters type "logzio" for logzio
```

I'm using `otel/opentelemetry-collector:latest` docker image as a collector, mounting my config file as a volume :
```bash
docker run -v "my\path\otel-collector-config.yaml":/etc/otel-collector-config.yaml -p 4317:4317 otel/opentelemetry-collector:latest --config /etc/otel-collector-config.yaml
```

I followed this tutorial : https://docs.logz.io/shipping/tracing-sources/opentelemetry.html#local-host

Please let me know if important information are missing.

**Comment by mx-psi** [comment]
You need to use a distro that includes that exporter, such as the contrib one. The docker image for the contrib distro is `otel/opentelemetry-collector-contrib` (it has the same tagging scheme as the core distro docker image, so you can also use `latest` if you want).
