### ISSUE TITLE
Datadog Exporter should allow custom resource attributes that do not map to conventions.

### ISSUE THREAD

**Issue by jfmyers9** [open-telemetry/opentelemetry-collector-contrib#5668]
**Is your feature request related to a problem? Please describe.**

We would like to rely on the Datadog convention mapping to translate OTEL specification resource attributes to Datadog metric tags. This is only available when `ResourceAttributesAsTags` is `false`.

However, we use the OTEL pipeline to map org specific labels and annotations to custom tags for metrics. For example, we rely on a team annotation to tag metrics with the `team:` tag. 

If we do not specify the `ResourceAttributesAsTags`, it correctly maps the attributes, but it will drop any additional attributes.

When we specify `ResourceAttributesAsTags` we lose the default mappings, and have to reimplement the mappings elsewhere in our pipeline.

**Describe the solution you'd like**

I think it would be reasonable for the Datadog Exporter to convert any non conventional resource attributes to tags when specified. At least provide a way to opt into this behavior.

**Describe alternatives you've considered**

We have considered implementing this mapping using processors in the pipeline, but it is tedious to maintain and feels like a duplication of effort.

**Additional context**

I have a working proposal at: https://github.com/jfmyers9/opentelemetry-collector-contrib/commit/64c44eaa4ed8a23182d311242a4cd16c1ea9f2f6 if this feature request seems agreeable.

**Comment by mx-psi** [comment]
@jfmyers9 #7185 should have addressed this and will be out in the next release: now attributes are mapped even when `resource_attributes_as_tags` is set to `true`. 

I am closing this since we believe it to be fixed, but if you have any comments about this, please let us know!

**Comment by jfmyers9** [comment]
Thanks for the information @mx-psi. Look forward to trying the new functionality out.
