### ISSUE TITLE
Flaky test - TestEndToEnd from prometheusexecreceiver

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#5669]
The test TestEndToEnd from the referenced receiver is intermittently failing with:

```
--- FAIL: TestEndToEnd (6.81s)
    receiver_test.go:118: 
        	Error Trace:	receiver_test.go:118
        	            				receiver_test.go:100
        	            				receiver_test.go:72
        	Error:      	Should be true
        	Test:       	TestEndToEnd
        	Messages:   	timestamp_now metric not found
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusexecreceiver	6.942s
```

Seen here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5511/checks?check_run_id=3824282958

**Comment by jpkrohling** [comment]
And again here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4165561716?check_suite_focus=true

**Comment by atoulme** [comment]
This is duplicated by #5859 - since there is more activity on the other issue, closing this one to pursue work on the other ticket.
