### ISSUE TITLE
Flaky test - TestTraceBallast1kSPSAddAttrs from loadtest job

### ISSUE THREAD

**Issue by ydrozhdzhal** [open-telemetry/opentelemetry-collector-contrib#5671]
The test TestTraceBallast1kSPSAddAttrs from loadtest job is intermittently failing.

Seen here:
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/20979/workflows/5c305175-1f63-4597-a7f9-0d9821ef16d5/jobs/167040/tests#failed-test-0

**Comment by sethAmazon** [comment]
Taking a look

**Comment by alolita** [comment]
Fixed. Closing issue.
