### ISSUE TITLE
ResourceDetectionProcessor: Support GKE resource labels

### ISSUE THREAD

**Issue by ocervell** [open-telemetry/opentelemetry-collector-contrib#570]
When running on GKE, it would be great to have automatic labeling for the metrics going through the collector, like we have with the `ResourceDetectionProcessor` on GCE. 

Using the `stackdriverexporter`, the resource type is set is `global`. The GCE detector from the `k8sprocessor` is changing the resource type to `compute_instance`, but on GKE we should set the resource to `k8s_cluster`, `k8s_node` / `k8s_pod` / `k8s_container`.

Additionally, some attributes are worth having as resource labels: `project_id`, `cluster_name`, `location`, `pod_name`, `node_name`, `namespace_name`, `container_name` (e.g use case: multi-tenant clusters).

Is the `k8sprocessor` designed to support GKE,? I wasn't sure to use it, since it queries k8s APIs and not the GKE metadata server.

As reference, the resource labels for common GKE resources should be set as follows:

### `k8s_cluster` (Kubernetes Cluster): 
**project_id:** The identifier of the GCP project associated with this resource, such as "my-project".
**location:** The physical location of the cluster.
**cluster_name:** The name of the cluster.

### `k8s_container` (Kubernetes Container)
**project_id:** The identifier of the GCP project associated with this resource, such as "my-project".
**location:** The physical location of the cluster that contains the container.
**cluster_name:** The name of the cluster that the container is running in.
**namespace_name:** The name of the namespace that the container is running in.
**pod_name:** The name of the pod that the container is running in.
**container_name:** The name of the container.

### `k8s_node` (Kubernetes Node)
**project_id:** The identifier of the GCP project associated with this resource, such as "my-project".
**location:** The physical location of the cluster that contains the node.
**cluster_name:** The name of the cluster that the node is a part of.
**node_name:** The name of the node.

### `k8s_pod` (Kubernetes Pod)
**project_id:** The identifier of the GCP project associated with this resource, such as "my-project".
**location:** The physical location of the cluster that contains the pod.
**cluster_name:** The name of the cluster that the pod is running in.
**namespace_name:** The name of the namespace that the pod is running in.
**pod_name:** The name of the pod.

**Comment by jrcamp** [comment]
@james-bebbington can you take a look?

**Comment by james-bebbington** [comment]
Interesting - I hadn't actually looked at the k8s processor before.

@nilebox recently added https://github.com/open-telemetry/opentelemetry-collector/pull/1462/files to ensure that when converting from an OT resource that uses OT semantic conventions, the legacy OC type is set correctly so that any exporters still dependent on OC conventions will work correctly.

That won't solve this case though as this processor is using the OC structure, but not setting `type` explicitly. This will be fixed when either:

1. We set the type explicitly here based on [OC semantic conventions](https://github.com/census-instrumentation/opencensus-specs/blob/master/resource/StandardResources.md#kubernetes)
2. We upgrade this processor to the new OT internal data structure

Doing (1) should be relatively straightforward so feel free to raise a PR

**Comment by nilebox** [comment]
@james-bebbington I think what @ocervell is requesting is to add support for GKE auto-detection similar to existing [GCE detection](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/resourcedetectionprocessor/internal/gcp/gce/gce.go) that you've implemented in the Resource Detection Processor.

e.g. if collector is running as a sidecar agent mode, it may inject Pod resource labels into metrics, as defined in [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/k8s.md#pod).

Based on the original description in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/92, the purpose of K8s Processor is quite different - It requires a metric / trace to have the originating Pod IP address specified via label, and uses it to lookup and match relevant Pod metadata to inject as Pod resource labels. I'm not actually sure how reliable that mechanism is, i.e. whether IP address will be always present in OT trace/metric labels and whether it will be set to originating Pod's IP address.

The main difference here is that Resource Detection Processor is producing labels on the client side (agent), while K8s Processor is producing them on the collector side, relying on the IP address and Kubernetes APis.

**Comment by ocervell** [comment]
@nilebox just to follow up on the second issue, should we make sure the `k8sprocessor` works with OT SDKs ? i.e: if running on K8S, should the OT SDKs add the originating Pod IP address automatically so that it's compatible ?

**Comment by nilebox** [comment]
> should the OT SDKs automagically add the originating Pod IP address to the metric / trace labels so that it's compatible

Pod IP address is not defined in [Pod resource's semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/k8s.md#pod), so we can't expect SDKs to add `k8s.pod.ip` resource attribute unless we add it to semantic conventions spec. We may add it as an optional attribute.

/cc @owais @bogdandrutu

**Comment by nilebox** [comment]
On a second thought adding `k8s.pod.ip` to Pod semantic convention doesn't probably make sense since it would be alternative to `k8s.pod.name` rather than additional attribute for the purpose of `k8sprocessor`.

**Comment by ocervell** [comment]
@nilebox got it, how about using `k8s.pod.name` in the `k8sprocessor` instead of `k8s.pod.ip` so that we don't have to change the SDKs at all ? Not sure how feasible this is but it would solve our issue.

**Comment by nilebox** [comment]
Actually sorry, it seems that `host.hostname` is expected to be set to Pod IP in the Kubernetes environment according to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9dbf0fd6ef6707324fbf6fc5d0fbc307304746ea/processor/k8sprocessor/processor.go#L196-L199

which is part of the Host resource: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/host.md#host

`K8sProcessor` will find corresponding Pod based on the `host.hostname` attribute and will set `k8s.pod.name` and other resource attributes, see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9dbf0fd6ef6707324fbf6fc5d0fbc307304746ea/processor/k8sprocessor/kube/client.go#L186 

So as long as SDKs automatically set `host.hostname` as described above, you'll get the desired behavior in `k8sprocessor`.

**Comment by ocervell** [comment]
@nilebox so I've checked and here are the resource attributes we set by default with the Python SDK (no custom resource, simply default OpenCensus Exporter configured):

```
Resource labels:
-> service.name: STRING(custom-metrics-example)
-> opencensus.starttime: STRING(2020-08-11T14:39:31.388278272Z)
-> host.hostname: STRING(custom-metrics-example-774d76d7d9-f59ll)
-> opencensus.pid: INT(1)
-> telemetry.sdk.version: STRING(0.11b0)
-> opencensus.exporterversion: STRING(0.12.dev0)
-> telemetry.sdk.language: STRING(PYTHON)
```

The `host.hostname` attribute is set to the name of the pod, not it's IP, and the `k8sprocessor` fails to tag the metrics because of this.

**Comment by ocervell** [comment]
@nilebox do we have any updates on this ? This has been a major blocker for some of my customers trying to migrate to OT.

**Comment by james-bebbington** [comment]
Apologies for no updates on this for some time. We intend to get to this in the next month or two. If this is a blocker for you in the meantime, you could try writing your own detector based on: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/detectors/gcp/gke.go

**Comment by mx-psi** [comment]
Hi, are there any updates on this issue?

**Comment by ocervell** [comment]
@james-bebbington any updates here ? Really needed for OT to work properly on GKE :/

**Comment by james-bebbington** [comment]
It looks like an initial GKE detector was added recently by @jrcamp.

See the docs here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor

I don't think this collects all the fields needed to export data under the [k8s_* Cloud Monitoring resource types](https://cloud.google.com/monitoring/api/resources#tag_k8s_container) though.

@dashpole or @aabmass, are you able to take a look and see if we can extend this?

**Comment by dashpole** [comment]
If using the collector as a sidecar, i'd recommend using the plain [resourceprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor) combined with the downward API to fill in container name, pod name, and namespace name.  The resourcedetection processor can take care of the rest.

```
processors:
  resource:
    attributes:
    - key: k8s.pod.name
      value: $POD_NAME
      action: upsert
    - key: k8s.namespace.name
      value: $POD_NAMESPACE
      action: upsert
    - key: k8s.container.name
      value:  my-container-name
      action: upsert
  resourcedetection:
    detectors: ["gke", "gce"]
```

Then in the pod spec:
```
env:
- name: POD_NAME
   valueFrom:
     fieldRef:
       fieldPath: metadata.name
- name: POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
```

The only issue after that the opencensus-based exporter that the googlecloud exporter uses relies on opencensus semantic conventions for sending metrics rather than opentelemetry semantic conventions.  So in the meantime, you would need to use `container.name` instead of `k8s.container.name` and `cloud.zone` instead of `cloud.availability_zone` (which is what the gce detector above would collect):

```
processors:
  resource:
    - key: cloud.zone
      value: my-zone
      action: upsert
    - key: k8s.pod.name
      value: $POD_NAME
      action: upsert
    - key: k8s.namespace.name
      value: $POD_NAME
      action: upsert
    - key: k8s.container.name
      value:  my-container-name
      action: upsert
```

We are working on an opentelemetry re-write of the googlecloud exporter, at which point the above will work correctly.

**Comment by nicolasgere** [comment]
no news here? We are using it in a collector way (not sidecar), we are not able to use this properly

**Comment by dashpole** [comment]
This should work now, and i'll try and provide more details.  If you use the `resourcedetection` processor, all metrics should now be associated with k8s_cluster by default (the gcp detector detects location + cluster name).

```
processors:
  resourcedetection:
    detectors: ["gcp"]
```

To associate it with k8s_pod, you would need to additionally add `k8s.namespace.name` and `k8s.pod.name`.  To associate it with k8s_container, you would need `k8s.container.name` in addition to the pod attributes.

If you are using the OTLP receiver, you can add `k8s.namespace.name` and `k8s.pod.name` using the `k8sattributes` processor: https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor#hdr-As_a_collector.

To add `k8s.container.name`, the easiest way would probably be to set the environment variable `OTEL_RESOURCE_ATTRIBUTES=k8s.container.name=my-container-name` on the application sending the telemetry.
