### ISSUE TITLE
Check components that aren't yet wired up

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#5749]
As seen in #5725, it is possible that components that have been completed already aren't wired up in the list of components. Currently, this seems to be the list of exporters and receivers that haven't been wired up yet as of 29-Nov-2022:

- [x] logicmonitorexporter (under development, should not be wired up)
- [x] #16567
- [x] purefareceiver (under development, should not be wired up)
- [x] snowflakereceiver
- [x] jaegerremotesampling
- [x] logstransformprocessor (correctly omitted)
- [x] redactionprocessor
- [x] schemaprocessor

Original description:

```console
$ ls -1 exporter/ > /tmp/exporters-available.txt
$ grep "github.com/open-telemetry/opentelemetry-collector-contrib" internal/components/components.go | sed 's/"//g' | grep exporter | awk -F/ '{print $5}' > /tmp/exporters-wired.txt
$ diff /tmp/exporters-*
2d1
< awscloudwatchlogsexporter
12d10
< elasticsearchexporter
16d13
< googlecloudpubsubexporter
26d22
< observiqexporter
33d28
< skywalkingexporter

$ grep "github.com/open-telemetry/opentelemetry-collector-contrib" internal/components/components.go | sed 's/"//g' | grep receiver | awk -F/ '{print $5}' > /tmp/receivers-wired.txt
$ ls -1 receiver/ > /tmp/receivers-available.txt
$ diff /tmp/receivers-*
1d0
< awscontainerinsightreceiver
5d3
< cloudfoundryreceiver
11,12d8
< googlecloudpubsubreceiver
< googlecloudspannerreceiver
14d9
< httpdreceiver
23,26d17
< memcachedreceiver
< mongodbatlasreceiver
< mysqlreceiver
< nginxreceiver
34d24
< scraperhelper
```

It is possible that some of those components aren't ready yet, but it's possible that some of them just missed this last step. This ticket is to verify which ones should be added, and to create a PR addressing it.

**Comment by koneko096** [comment]
may i take this?

**Comment by rltoSD** [comment]
Hi @alolita can you please assign me this issue?

**Comment by alolita** [comment]
@rltoSD assigned. Thx.

**Comment by rltoSD** [comment]
@jpkrohling Hi! I was just wondering if the best way to approach this would be to look at the code base and identify if these exporters/receivers have individual tests for them in order to verify that they are completed. Thanks!

**Comment by jpkrohling** [comment]
The first step is to get an up-to-date list of components that aren't wired up. Perhaps the list has changed since I checked. Then, you can go two ways:

1. the easy thing would be to create subtasks to this issue, one for each component, and ping the owners of the component, as listed in the [.github/CODEOWNERS](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/CODEOWNERS) file asking for the component's status. If there's no entry there, you can open the PR that introduced the component and ping the author.
2. A more thorough check would be to open the PRs that introduced the components and try to infer the status from them. Typically, components are added in multiple PRs, and the last one is wiring up the component. Perhaps you can identify that two of the 3 PRs got merged, and a third is lined up? In that case, there's no action to take.

**Comment by jpkrohling** [comment]
I just ran the same commands today, and these are the components that need to be wired up. I know that at least one of them is still under development, so, it's not supposed to be there yet. A confirmation from the remaining code owners would be good to have, to determine whether the other components should be wired up already.

* logicmonitorexporter
* azureblobreceiver
* purefareceiver (under development, should not be wired up)
* snowflakereceiver
* jaegerremotesampling
* logstransformprocessor
* redactionprocessor
* schemaprocessor

Commands I ran to get this list:

```
ls -1 exporter/ > /tmp/exporters-available.txt
grep "github.com/open-telemetry/opentelemetry-collector-contrib" internal/components/components.go | sed 's/"//g' | grep exporter | awk -F/ '{print $5}' > /tmp/exporters-wired.txt
diff /tmp/exporters-*

ls -1 receiver/ > /tmp/receivers-available.txt
grep "github.com/open-telemetry/opentelemetry-collector-contrib" internal/components/components.go | sed 's/"//g' | grep receiver | awk -F/ '{print $5}' > /tmp/receivers-wired.txt
diff /tmp/receivers-*

ls -1 extension/ > /tmp/extensions-available.txt
grep "github.com/open-telemetry/opentelemetry-collector-contrib" internal/components/components.go | sed 's/"//g' | grep extension | awk -F/ '{print $5}' > /tmp/extensions-wired.txt
diff /tmp/extensions-*

ls -1 processor/ > /tmp/processors-available.txt
grep "github.com/open-telemetry/opentelemetry-collector-contrib" internal/components/components.go | sed 's/"//g' | grep processor | awk -F/ '{print $5}' > /tmp/processors-wired.txt
diff /tmp/processors-*
```

**Comment by djaglowski** [comment]
`logstransformprocessor` is correctly omitted. See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16045#issuecomment-1302110798

**Comment by khyatigandhi6** [comment]
Hey @jpkrohling,
_logicmonitorexporter_ is under development. So no need to be wired.

**Comment by eedorenko** [comment]
Hey @jpkrohling,
_azureblobreceiver_ should be wired up

**Comment by mx-psi** [comment]
The redaction processor is available on the official contrib build but not on here https://github.com/open-telemetry/opentelemetry-collector-releases/blob/04952c5b522602eead49b016c4c44035d84bb177/distributions/otelcol-contrib/manifest.yaml#L88

I am honestly not sure at this point what the rule is for something to be on components.go, but I assume since this is on releases, it should also be on components.go

**Comment by MovieStoreGuy** [comment]
Scheme processor is still being actively developed.

**Comment by shalper2** [comment]
snowflakereceiver should be wired up

**Comment by dmitryax** [comment]
> snowflakereceiver should be wired up

@shalper2 I don't think it is. It's not in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/builder-config.yaml or https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/components/components.go

**Comment by shalper2** [comment]
should be as in "it should not be omitted from this issue", sorry. opening an issue and PR here shortly!

**Comment by jpkrohling** [comment]
@frzifus, is there a reason to not have the remote sampling extension there? Should I open a PR to include it?

**Comment by atoulme** [comment]
Is this issue about adding components to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/builder-config.yaml or to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/components/components.go ?

**Comment by jpkrohling** [comment]
When this was opened, we didn't have the builder. I would open a new one for builder, but I think we might have some automation for that already.

**Comment by atoulme** [comment]
OK so this is specifically about adding components to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/components/components.go

**Comment by jpkrohling** [comment]
Yes. I'll check the builder config tomorrow and see if they are out of sync, creating a separate issue if that's the case.

**Comment by atoulme** [comment]
I think we can automate that check using the status metadata such that any component with status alpha, beta, deprecated or unmaintained is enforced to be present in cmd/otelcontribcol.

**Comment by atoulme** [comment]
* `jaegerremotesampling`: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/builder-config.yaml#L18
* `redactionprocessor`: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/builder-config.yaml#L97
* `schemaprocessor`: in development.

The check is now present, and ensures that for >= alpha levels, we make sure the component is present. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/34d555c72fc523cd9a907a3e7f01671d4b91e5d7/cmd/otelcontribcol/distribution_metadata_test.go#L41

I think we can close this issue.
