### ISSUE TITLE
Flaky test - prometheusexecreceiver: TestEndToEnd  UT failure

### ISSUE THREAD

**Issue by pmalek-sumo** [open-telemetry/opentelemetry-collector-contrib#5859]
**Describe the bug**
`TestEndToEnd` failed in an unrelated PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5857/checks?check_run_id=3963335983

**Steps to reproduce**
N/A

**What did you expect to see?**
Test to pass

**What did you see instead?**
Test failure:

```
make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusexecreceiver'
go test -race -timeout 300s --tags="" ./...
--- FAIL: TestEndToEnd (6.21s)
    receiver_test.go:118: 
        	Error Trace:	receiver_test.go:118
        	            				receiver_test.go:100
        	            				receiver_test.go:72
        	Error:      	Should be true
        	Test:       	TestEndToEnd
        	Messages:   	timestamp_now metric not found
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusexecreceiver	6.342s
```

**What version did you use?**
Version: ed6dc5dba91389bbd13727de0bd3c854fed75343

**What config did you use?**
Config: N/A

**Environment**
Github Actions CI

---

CC: (as per the CODEOWNERS file) @keitwb

**Comment by jpkrohling** [comment]
Happened again:
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4455720915?check_suite_focus=true

**Comment by jpkrohling** [comment]
@keitwb, are you able to look into this?

**Comment by jpkrohling** [comment]
Happened again: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4969118880?check_suite_focus=true#logs

**Comment by jpkrohling** [comment]
cc @dmitryax

**Comment by djaglowski** [comment]
Again here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5042487663?check_suite_focus=true#step:8:16309

**Comment by djaglowski** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5056740168?check_suite_focus=true#step:8:16313

**Comment by dmitryax** [comment]
I will take a look later this week

**Comment by pmm-sumo** [comment]
Still happening: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5405959324?check_suite_focus=true

**Comment by djaglowski** [comment]
Again here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6024956622?check_suite_focus=true#step:8:17340

**Comment by dmitryax** [comment]
Skipped, not resolved

**Comment by dmitryax** [comment]
the receiver is removed
