### ISSUE TITLE
[cumulativetodeltaprocessor] Improve metric name configuration

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-collector-contrib#5877]
#4444 originally changed the cumulative to delta processor to default to converting all cumulative metrics to delta. This behavior was reverted and currently the configuration requires a user identify each cumulative metric by exact name for conversion to delta.

One proposal is to implement regex support https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4444#discussion_r714556594.

Another thought is to do away with the metric name configuration entirely. That is, by installing this processor into your pipeline you're declaring you want delta metrics. This thought is inspired by https://github.com/open-telemetry/opentelemetry-specification/pull/2032 where the ability to configure aggregation temporality at the view level in an SDK was removed. Aggregation temporality would be overridable at the metric reader/exporter.

**Comment by TylerHelmuth** [comment]
I'd like to take a look at this issue.  @open-telemetry/collector-contrib-approvers what is the appetite for removing the metric name configuration entirely vs regex support?

**Comment by jpkrohling** [comment]
I'll defer to @bogdandrutu and @codeboten, but just make sure that if we decide to change this, we do in stages, so that current users of this processor have a chance of migrating without being caught by surprise.

**Comment by TylerHelmuth** [comment]
If the solution is to use regex instead of converting all metrics, how does everyone feel about providing an "opt-in" and "opt-out" approach?  There may also be times when it is easier to specify which metrics should not be converted.  Regex could be supported for both option.  The config could look something like:


```yaml
cumulativetodelta:
  mode: include | exclude
  match_type: strict | regex
  metrics: [ <metric_name>, <metric_name>, ...] 
  max_staleness: int
```
