### ISSUE TITLE
Ability to scrape filesystem host metrics from a container

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#5879]
**Use case**: 

Scraping underlying host metrics from a container

Existing approach to scrape host metrics from container:
1. Mount host filesystem `/` path to some path inside container, e.g. `/hostfs`.
2. Setup [env variables supported by gosutil](https://github.com/shirou/gopsutil#usage) to point it to different locations, e.g. `HOST_PROC=/hostfs/proc`

**Problem description**:

The described approach works for all `hostmetrics` receiver scrapers except for `filesystem`. 

`filesystem` scraper workflow (assuming `HOST_PROC=/hostfs/proc`) is the following:
1. Fetch list of disc partitions with `gopsutil/disk.Partitions`: all the paths in the returned list are plain **host** paths, not prefixed with `/hostfs`.
2. Read usage stats of the partitions returned at the step 1 with `gopsutil/disk.Usage` using mount points paths: since the mount point paths are used as is (without `/hostfx` prefix), the function reads **container** partition stats instead of **host** partition stats. Obviously, most of the host mount points are not available in the container, and it results in throwing the following errors:
```
2021-10-23T16:39:03.988Z	error	scraperhelper/scrapercontroller.go:198	Error scraping metrics	{"kind": "receiver", "name": "hostmetrics", "error": "no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory; no such file or directory", "scraper": "filesystem"}
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
	go.opentelemetry.io/collector@v0.37.1-0.20211015233822-bd87fb628058/receiver/scraperhelper/scrapercontroller.go:198
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
	go.opentelemetry.io/collector@v0.37.1-0.20211015233822-bd87fb628058/receiver/scraperhelper/scrapercontroller.go:173
```

The issue was uncovered by this change to goputils library https://github.com/shirou/gopsutil/pull/1133. Before that `gopsutil/disk.Partitions` used to return **container** disk partitions, so it looked like it worked well, but it didn't.

**Suggested solution**:

Add new configuration option to `hostmetrics` receiver: `root_path` with `/` as default. The receiver behavior stays the same with default value, but if the `root_path` set to something else:
  - Make sure that all the env variables needed for gopsutil are automatically set (only if not provided by user)
  - Handle all the paths translation between `gopsutil/disk.Partitions` and `gopsutil/disk.Usage` calls in filesystem scraper to fix the described issue. We cannot expect users to always mount the whole `/` host path to the container, so any files misses should throw debug logs instead of errors.

**Comment by rmfitzpatrick** [comment]
@dmitryax does using `HOST_PROC_MOUNTINFO` introduced in https://github.com/shirou/gopsutil/pull/1272 provide a mechanism for this that doesn't necessarily require changes to the scraper?

**Comment by dmitryax** [comment]
Yes looks like it does. We can use it as a workaround for now. It should fix metrics that don't depend on `/proc/` in our distro. But other metrics using `/proc/self` instead of `/proc/1` will be still reporting container value instead of host. I don't remember how critical is that. Probably should be close to accurate.

**Comment by dmitryax** [comment]
Please test it in kubernetes to make sure that no errors are thrown. Thanks for looking into that!

**Comment by rmfitzpatrick** [comment]
Oh my mistake, the `disk.Usage()` call will still fail since the host mount points need to still be coerced to ~`/hostfs`.

**Comment by MovieStoreGuy** [comment]
Hey @dmitryax , it looks like the incorrect label was added here. 
Could I ask you to update the component label?

**Comment by jamesmoessis** [comment]
We are using the aforementioned workaround as well. It has a side affect that `mountpoint` on the filesystem attributes are all prefixed with `/hostfs`. That, combined with the lack of ability to do a regex-replace (`/hostfs(.*)` -> `/(.*)`) in any of the standard processors creates a problem for us.

@dmitryax is anyone currently working on this? I should have time to add the `root_path` config in the upcoming weeks, and solve the mentioned problems here.

**Comment by dmitryax** [comment]
@jamesmoessis I don't believe that anyone is currently working on this. Feel free to take it. I'll be happy to review

**Comment by jamesmoessis** [comment]
@dmitryax I started to look at this today. There's no obvious and clean way to have a `root_path` config at the top level and then have it passed down to the filesystem scraper. Did you have any ideas for that?

**Comment by MovieStoreGuy** [comment]
@jamesmoessis, 

Is there a reason that the sub receivers need to be aware of the `RootPath` ? 
Is it just to trim the prefix from any attributes that the sub receiver needs to be aware of? 

The way I understood this ticket to mean is:

```
func (r *receiver) Start(ctx context.Context) error {
   if r.HostPath  != "" {
      // Set environment variables used by library for those that are unset
   }
   // etc ...
}
```

To make things more testable you could update the internal subconfig to:

```golang
type SubConfig interface {
    SetHostPath(hostPath string)
} 
``

And the Configs can either ignore it if it is not relevant or consume to trim attribute prefixes that way.

**Comment by dmitryax** [comment]
> @dmitryax I started to look at this today. There's no obvious and clean way to have a root_path config at the top level and then have it passed down to the filesystem scraper. Did you have any ideas for that?

As @MovieStoreGuy mentioned, I think `root_path` can be part of `hostmetrics` receiver, but we need to validate that all instances of hostmetrics receiver have the same `root_path` setting.

**Comment by jamesmoessis** [comment]
@MovieStoreGuy @dmitryax 

> Is there a reason that the sub receivers need to be aware of the RootPath ?

The ticket says: 

>  Handle all the paths translation between gopsutil/disk.Partitions and gopsutil/disk.Usage calls in filesystem scraper to fix the described issue. 

Unless I am misunderstanding the requirements, I would expect in order for the FS scraper to achieve this it would need to know the root path.

**Comment by dmitryax** [comment]
I see what you mean. I don't think it's a problem. I believe you can expose a method like `SetRootPath(string)` in each scrapers config which would be called from https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/config.go . Does it make sense?

**Comment by jamesmoessis** [comment]
It makes sense. I considered that method earlier but thought it might be overdoing it if I have to add `func (c *Config) SetRootPath(_ string) {}` to every scraper, even though only filesystem scraper uses root path. However if you think that's the best way, happy to do it.

**Comment by MovieStoreGuy** [comment]
> It makes sense. I considered that method earlier but thought it might be overdoing it if I have to add `func (c *Config) SetRootPath(_ string) {}` to every scraper, even though only filesystem scraper uses root path. However if you think that's the best way, happy to do it (I've got it half-implemented already).

You can use some struct embedding to reduce the repeated code here if you wanted.

**Comment by jamesmoessis** [comment]
During my implementing, it seems there are two ways to do it:

1. Have root path in the hostmetrics receiver config, and set all the `HOST` env variables using it. Must ensure all instances of `hostmetricsreceiver` have the same `root_path`.

2. Have root path in the filesystem scraper config. Allow the user to set the environment variables themselves. No need to check for consistency because env vars are set at process-level by user. Document the env vars, and how to use with root path FS scraper config. No need to have all scrapers aware of root path. 

I've gone with (1) as this is what's the described in the ticket, but I think that there is merit in (2) as well. Wanted to put it out there as a possible approach.

**Comment by dmitryax** [comment]
If it's needed only for `filesystem` scraper, I'm good with (2) as it doesn't require validation of `root_path`. @jamesmoessis can you please double check and confirm that we don't need to do any host path translations like this for other scrapers?

**Comment by jamesmoessis** [comment]
@dmitryax 
> please double check and confirm that we don't need to do any host path translations like this for other scrapers 

The `filesystem` scraper is unique because it does two coordinated calls: one to `mountinfo` to get the mountpoints, another to get the stats of those mountpoints. The mount points returned from `mountinfo` are from the host's perspective as we know. I don't believe anything like this happens for other scrapers. 

I went through and verified: 
- 🟢 `cpuscraper`: One call to `/proc/stat`, `gopsutil` queries via `$HOST_PROC` 
- 🟢  `diskscraper`: One call to `/proc/diskstats` - `gopsutil` queries via `$HOST_PROC`. No mountpoints / filenames involved so no host path translations needed. 
- 🟢 `loadscraper`: Similar to CPU scraper. 
- 🟢  `memoryscraper`: One call to `/proc/meminfo` - `gopsutil` again queries via `$HOST_PROC`. 
- 🟢 `networkscraper`: A few calls to files under `/proc` - nothing that is filesystem related or related to root path, as far as I can see. May be affected by the network namesapce of the container but that is irrelevant to this. 
- 🟡  `pagingscraper`: One call, but it's hard coded to `/proc/swaps`. It doesn't go through `gopsutil`. This scraper should make use of `HOST_PROC`, so it aligns with the other scrapers. I've opened a bug for that here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15998 
- 🟢  `(process | processes)scraper`: Calls via `gopsutil` utilising `HOST_PROC`. Nothing needing to be translated in relation to root path anywhere as far as I can see.

**Comment by dmitryax** [comment]
@jamesmoessis thanks for providing the detailed summary.

> pagingscraper: One call, but it's hard coded to /proc/swaps. It doesn't go through gopsutil. This scraper should make use of HOST_PROC, so it aligns with the other scrapers. I've opened a bug for that here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15998

I'm a bit worried about this one. I don't think that otel collector should support any configuration via env vars. I would leave `HOST_...` vars to gopsutil. Given that, I'd rather lean towards the original solution (1).

Speaking of (1)...

> Have root path in the hostmetrics receiver config, and set all the HOST env variables using it. Must ensure all instances of hostmetricsreceiver have the same root_path.

I don't think we need to introduce any additional env vars. The validation process should be the following:

If `root_path` is set to any value other than the default `/`, we check all the goputil env vars -> if any of them are already set to any value that doesn't match provided `root_path`, the validation fails.

Let me know if it makes sense

**Comment by jamesmoessis** [comment]
Alright, that makes sense. Will go with (1) then.

**Comment by jamesmoessis** [comment]
@dmitryax as the PR is now merged. Can close this 🙂

**Comment by evan-bradley** [comment]
Closing as completed via #16026.
