### ISSUE TITLE
Supplement local development instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by MartinDai** [open-telemetry/opentelemetry-collector-contrib#5883]
**Is your feature request related to a problem? Please describe.**
When i want debug project in GoLand, it throw error info in console
![image](https://user-images.githubusercontent.com/11816720/138636999-106e34ed-74c2-487d-844b-ef687130dade.png)

But the issue #5425 is mentioned this problem, and provided the solution(The Makefile also used this solution).
That is add environment variable `CGO_ENABLED=0`

**Describe the solution you'd like**

Add more useful instructions to CONTRIBUTING.md to help the new Contributor build/debug project.

**Comment by mx-psi** [comment]
I believe this should not happen anymore, our dependency tree only has gopsutil v3 now. It's a good idea to have some list of known build issues, or at the very least a label for this
