### ISSUE TITLE
Evaluate antonmedv/expr for use in filters and transforms

### ISSUE THREAD

**Issue by punya** [open-telemetry/opentelemetry-collector-contrib#5887]
#5680 introduces a [DSL](https://pkg.go.dev/github.com/antonmedv/expr) for filtering logs, and based on prior discussions we want to consider a similar approach for metric transforms/filters too. Before committing to this approach and this library, we'd like to do a deeper evaluation:

* overall performance impact of evaluating DSL at runtime
* comparison with other DSL approaches
* can we handle `filter for resource && inst lib && signal` without evaluating resource multiple times

Thanks @bogdandrutu for the detailed suggestion. Please add any other evaluation criteria that are on your mind.

**Comment by pmalek-sumo** [comment]
Is there anyone working on this? Have we done any of the research mentioned in the description?

**Comment by punya** [comment]
My apologies for not working on this issue. However, in light of @anuraaga's work on a generic transform processor ([design doc](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/processing.md), [WIP implementation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor)), I believe this evaluation is no longer necessary.
