### ISSUE TITLE
Add support for ASAP Authentication

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#5930]
**Describe the solution you'd like**
With the current extensions such as OIDC and OAuth2, we would like to add in [ASAP](https://s2sauth.bitbucket.io/) to allow for services to communicate securely.

**Describe alternatives you've considered**
While there is existing authentication means within the collector contrib already, we are not able to adopt them since our platform primarily supports the use of ASAP.

**Additional context**
I am very happy to implement this and support as issues arises.

**Comment by jamesmoessis** [comment]
@MovieStoreGuy this is implemented now, can be closed

**Comment by MovieStoreGuy** [comment]
Hey @jpkrohling,

I can see that it has been added into the collector (include the tests for extensions) here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6680.

Could I ask that you mark this as done ? (Not sure that is a github state, I am just so use to Jira I don't know any different).
