### ISSUE TITLE
Datadog exporter doesn't include the original trace id

### ISSUE THREAD

**Issue by Yayotron** [open-telemetry/opentelemetry-collector-contrib#5969]
**Describe the bug**
Datadog uses its own format for trace id, however there's no (easy) way to obtain the original trace id from the generated trace.

**Steps to reproduce**
1. Configure open telemetry to use datadog exporter
2. Send a trace
3. Go to datadog APM and look for your trace

**What did you expect to see?**
The original trace id, preferably as a tag, so I could relate this with my logs or with downstream services which receive the trace id in its original format and viceversa, use the original trace id to find traces in datadog.

**What did you see instead?**
I only can find trace id in datadog's format.

**What version did you use?**
Version: v0.37.1

**What config did you use?**
```yaml
  datadog/api:
    env: dev
    tags:
      - service.name
    api:
      key: my_key
      site: datadoghq.com
```

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
I'm aware how to convert the trace_id from one format to the other (https://docs.datadoghq.com/tracing/connect_logs_and_traces/opentelemetry/) and that there are plenty workarounds to send the trace id in its original format to datadog (manual instrumentation, extension in automatic instrumentation, custom processor).
@mx-psi please take a look.

**Comment by Yayotron** [comment]
Keeping the original ids as tags will be extremely helpful 🙂

**Comment by gbbr** [comment]
Cool, I'm fine with that. One thing I can't figure out is how useful this is, in order to answer the question on whether we should have this on by default, or if it should be off by default and enabled by config.

**Comment by Yayotron** [comment]
Having the original trace id is quite important for observability/troubleshooting as it covers two key requirements (which I think are needed by a big portion of developers):
1. We must have a way correlate traces with logs, which usually means searching for the original trace id in the logs.
2. We must be able to request downstream systems information about a request, which usually means sending a different team the original trace id or search details about this trace id in another monitoring backend.

Not having this feature means that users have to do some implementation to satisfy these requirements, a few possibilities:
1. Implement their own instrumentation to include the original trace id as an attribute to use it as a tag in datadog.
2. Implement their own processor to extract the original trace id
3. Log both trace id formats.
4. Have a script to translate between the formats back and forth.

**Comment by gbbr** [comment]
Makes absolute sense. Thanks for providing the details. I have created a ticket internally to add this.

**Comment by gbbr** [comment]
I've set up a PR. @Yayotron would love for you to confirm that this is what you're after.

**Comment by gbbr** [comment]
FYI I'm proposing this change to the original fix: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6432. It is better to group everything under the `otel` group, rather than create a new one. Hope that's ok.

**Comment by gbbr** [comment]
@Yayotron what do you think about the latest PR? Would it be terrible if we changed this already released tag? I am thinking that it's not looking too good as it is, and I've missed that the first time around.

![APM Traces  Datadog 2021-11-25 at 10 40 18 AM](https://user-images.githubusercontent.com/6686356/143465278-02ebc61a-077c-44ed-99d3-7dad91a346fc.png)

If you think it'd be bad to make this breaking change, I can close the PR.

**Comment by Yayotron** [comment]
I'm fine with that, we're still not using this feature and I agree it'll be better this way.
