### ISSUE TITLE
Automate dependabot workflow

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#5971]
Currently dependabot opens many PRs against this repo, but the checks fail because `make gotidy` needs to be run in order for all the dependencies to be updated. This makes for additional work on the maintainers which ideally could be automated away.

It would be great to solve this problem.

**Comment by alolita** [comment]
Fixed. Closing issue.

**Comment by anuraaga** [comment]
There isn't a linked PR that fixed this and I couldn't find one with a quick skim of recent PRs. Please link in the fix and close again if that actually has happened.
