### ISSUE TITLE
kafkaexporter compression

### ISSUE THREAD

**Issue by arnitolog** [open-telemetry/opentelemetry-collector-contrib#6079]
it will be good to have the ability to set Compression and CompressionLevel for Kafkaexporter. This will allow reducing the amount of data transferred over the network. according to the documentation it is already supported options in sarama library: https://pkg.go.dev/github.com/shopify/sarama#Config

**Comment by Sprakhar97** [comment]
Hi @alolita I can work on this issue if no one else is working on it.
