### ISSUE TITLE
Build deb/rpm/msi are failing

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#6092]
The following build jobs are failing in multiple builds.

<img width="400" alt="Screen Shot 2021-11-01 at 4 12 01 PM" src="https://user-images.githubusercontent.com/223565/139753985-4ff8f828-074c-4eb3-9b63-457c393ea6f5.png">

**Comment by codeboten** [comment]
The problem began as a result of this change being merged https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5666

**Comment by jpkrohling** [comment]
Thanks for fixing this, @codeboten. My bad, should have not ignored the check failures in that PR.

**Comment by codeboten** [comment]
> Thanks for fixing this, @codeboten. My bad, should have not ignored the check failures in that PR.

No problem... It's a side effect of too many checks failing :(
