### ISSUE TITLE
kafkaexporter: Unable to use MSK IAM SASL auth due to TLS not being enabled

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#6096]
**Describe the bug**
There is an important part of the MSK IAM Auth missed is that it requires TLS communication between the two peers.

**Steps to reproduce**
Trying to connect to the MSK cluster with IAM auth set will result in error

**What did you expect to see?**
The kafkaexporter freely able to send data to Kafka without issue trying to use the configured authentication means.

**What did you see instead?**
The producer is unable to connect with the MSK cluster

**What version did you use?**
Version: v.0.37.0

**What config did you use?**
Config:

```yaml
+  kafka/metrics:
+    brokers: [ ... omitted ... ]
+    protocol_version: 2.0.0
+    auth:
+      sasl:
+        username: ${AWS_ACCESS_KEY}
+        password: ${AWS_SECRET_KEY}
+        mechanism: AWS_MSK_IAM
```

**Additional context**
It might not be possible to fix this due to limitations with the sarama producer however, I am yet to confirm

**Comment by MovieStoreGuy** [comment]
Following the details listed out here for reference: https://github.com/aws/aws-msk-iam-auth#configuring-a-kafka-client-to-use-aws-iam

Slightly easier to reconcile than the official AWS docs.

**Comment by MovieStoreGuy** [comment]
There is an upstream issue to support this https://github.com/Shopify/sarama/issues/1985

**Comment by MovieStoreGuy** [comment]
:sigh: It looks like the issue was a result of a missing CA cert.

However, the error did not indicate that well.

**Comment by MovieStoreGuy** [comment]
Turns out this was all human error and can be ignored.

**Comment by gfes980615** [comment]
hi, @MovieStoreGuy could you share with me how you solve this issue?
I have the same issue as you.
