### ISSUE TITLE
Convert carbonexporter to not use opencensus

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#6108]
Assigned to @pjanotti as the owner of the config, if not done in 2 weeks the component will be deleted.

**Comment by jpkrohling** [comment]
@jcchavezs, are you interested in working on this one?

**Comment by alolita** [comment]
@bogdandrutu just clarifying - the component will be removed from the collector contrib build not remove the source code - right?

**Comment by jcchavezs** [comment]
Indeed I am interested on working on this.

**Comment by jcchavezs** [comment]
I am working on this BTW
