### ISSUE TITLE
Track the conversion of the benchmark to a real benchmark in skywalking exporter.

### ISSUE THREAD

**Issue by liqiangz** [open-telemetry/opentelemetry-collector-contrib#6116]
Refer to #5690.  This issue is to track the benchmark of skywalking exporter.

**Comment by liqiangz** [comment]
@jpkrohling

**Comment by vasireddy99** [comment]
@liqiangz Can you provide more information about this issue, I would like to give it a try :)

**Comment by jpkrohling** [comment]
Sure! This file contains a test that is measuring the time it takes for some operations:

exporter/skywalkingexporter/skywalking_benchmark_test.go

This thread is relevant for this task: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5690/files#r739082935

Ideally, we would be using real Go benchmarks, as described here: https://pkg.go.dev/testing#hdr-Benchmarks

If benchmarking that isn't straightforward (I think it should), that source file should just be removed. The goal for that test is to assess that concurrent calls to `pushLogs` benefit from the implementation having a connection pooling mechanism like this:  

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1e9005e6fa42a5514bac6f4f4c725f10d64c16f8/exporter/skywalkingexporter/skywalking.go#L100-L113

**Comment by vasireddy99** [comment]
Hi @alolita, Please assign this to me. I would like to start working on this.

**Comment by jpkrohling** [comment]
Assigned.

**Comment by jpkrohling** [comment]
@liqiangz, are you still the code owner for the component?

**Comment by liqiangz** [comment]
> @liqiangz, are you still the code owner for the component?

please assign to me

**Comment by jpkrohling** [comment]
@wu-sheng , any chance we can get this done?

**Comment by wu-sheng** [comment]
@liqiangz Are you still on this?

@jpkrohling I have no update about this too.

**Comment by jpkrohling** [comment]
Given that the component will be removed soon, this should be closed.
