### ISSUE TITLE
[Prometheus Receiver] Modify existing tests to validate metrics using OTLP format instead of OpenCensus format

### ISSUE THREAD

**Issue by PaurushGarg** [open-telemetry/opentelemetry-collector-contrib#6151]
**Describe the Problem**
[Existing Prometheus Receiver test](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/metrics_receiver_test.go#L1295) translates [OTLP format metrics to OpenCensus format](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/metrics_receiver_test.go#L1428), and then uses these translated metrics for validation and assertions. Currently, Prometheus Receiver uses [OpenCensus metricbuilder](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/internal/metricsbuilder.go#L49),  but this is planned to be switched to [OTLP metricbuilder](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/internal/otlp_metricsbuilder.go#L83), in the near future. After this change, [staleNaN](https://github.com/prometheus/prometheus/blob/309b094b92b90061f8e1cc8d26b9577f2313eeac/pkg/value/value.go#L28) can be identified using data-point flags ([MetricDataPointFlagNoRecordedValue](https://github.com/open-telemetry/opentelemetry-collector/blob/0b4e5ec7924c56342c0ab453ca3dc99bbe3642cd/model/pdata/metrics.go#L285)). 
See Issues:
https://github.com/open-telemetry/opentelemetry-proto/pull/316
https://github.com/open-telemetry/opentelemetry-proto/pull/310

In existing Prometheus Receiver tests, [`func TestEndtoEnd`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/metrics_receiver_test.go#L1295) translates the OTLP format metrics to OpenCensus format before proceeding for test validations. The data-point flag to identify staleness markers,  is not accessible using the OpenCensus format, and there are existing issues that cannot be resolved without datapoint flag for staleness markers.
See Issue: 
https://github.com/open-telemetry/wg-prometheus/issues/38

**Describe the solution you'd like**
[Exiting Prometheus Receiver test](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/metrics_receiver_test.go#L1295) receives [metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/metrics_receiver_test.go#L1539) from the `consumertest.MetricsSink` in OTLP format. Modify this test to remove the translation from OTLP to OpenCensus format and modify all the existing functions associated with validations and assertions [(as in the link)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9ceb2fff514995a5b85e89447b02095d3f0c6302/receiver/prometheusreceiver/metrics_receiver_test.go#L202) to accept OTLP format metrics instead of OpenCensus.

**Additional context**
Related to https://github.com/open-telemetry/wg-prometheus/issues/57
Related Issues:
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6000
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6087
cc: @alolita @Aneurysm9

**Comment by PaurushGarg** [comment]
@alolita please assign this issue to me. I would like to work on this one.

**Comment by alolita** [comment]
See issue #6360 for more details. Closing this issue.
