### ISSUE TITLE
Rename httpdreceiver to apachereceiver

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#6206]
The new `httpdreceiver` scrapes metrics from Apache Web Server. Most monitoring solutions refer to this technology as simply "apache", including [Prometheus](https://github.com/Lusitaniae/apache_exporter#collectors), [Telegraf](https://github.com/influxdata/telegraf/blob/release-1.15/plugins/inputs/apache/README.md#measurements--fields), [Munin](https://gallery.munin-monitoring.org/plugins/munin/apache/), [SignalFX](https://docs.signalfx.com/en/latest/integrations/agent/monitors/collectd-apache.html), and [Google](https://cloud.google.com/monitoring/api/metrics_agent#agent-apache).

I propose we rename this component to `apachereceiver` in order to align with user expectations.

**Comment by jpkrohling** [comment]
For the record, I'm not sure I agree with this change. Apache is the foundation under which the `Apache httpd` project exists. I would rather have renamed it to `apachehttpdreceiver` if a rename was really required. In any case, I'm closing this as the rename was made already.
