### ISSUE TITLE
[awsxrayexporter] Replace hardcoded strings with sem conv values

### ISSUE THREAD

**Issue by willarmiros** [open-telemetry/opentelemetry-collector-contrib#6210]
We should replace all hardcoded strings in the [X-Ray exporter segment translator](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ae3a556549ab666bccfb1812730f7818915ea764/exporter/awsxrayexporter/internal/translator/segment.go) references to their semantic convention resource attributes when the next version of sem convs are available in the collector.

For example:

```go
case "aws_app_runner" -> case conventions.AttributeCloudPlatformAWSAppRunner
```

PR comment for reference: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6141/files#r745169174

**Comment by codeboten** [comment]
The new semconv will be available when this https://github.com/open-telemetry/opentelemetry-collector/pull/4452 is merged.

**Comment by Nuatu** [comment]
I'd like to work on this.  This will be my first contribution to this repo. 

Just read through the contribution docs and signed the CLA.

I read through the relevant files/comments in collector-contrib [PR#6141](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6141/files) and collector [PR#4452](https://github.com/open-telemetry/opentelemetry-collector/pull/4452/files).

Should be straightforward for me to submit a PR tomorrow.

**Comment by sethAmazon** [comment]
@alolita please close this ticket.
