### ISSUE TITLE
[Prometheus Receiver] Modify existing TestStartTimeMetricRegex, TestExternalLabels, and TestStartTimeMetric to validate metrics using OTLP format and enable compatability with Staleness Markers

### ISSUE THREAD

**Issue by PaurushGarg** [open-telemetry/opentelemetry-collector-contrib#6212]
**Describe the Problem**
[Existing Prometheus Receiver test](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/metrics_receiver_test.go#L1295) translates [OTLP format metrics to OpenCensus format](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/metrics_receiver_test.go#L1428), and then uses these translated metrics for validation and assertions. Currently, Prometheus Receiver uses [OpenCensus metricbuilder](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/internal/metricsbuilder.go#L49),  but this is planned to be switched to [OTLP metricbuilder](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/internal/otlp_metricsbuilder.go#L83), in the near future. After this change, [staleNaN](https://github.com/prometheus/prometheus/blob/309b094b92b90061f8e1cc8d26b9577f2313eeac/pkg/value/value.go#L28) can be identified using data-point flags ([MetricDataPointFlagNoRecordedValue](https://github.com/open-telemetry/opentelemetry-collector/blob/0b4e5ec7924c56342c0ab453ca3dc99bbe3642cd/model/pdata/metrics.go#L285)). 

Issue #6151 modifies existing `metric_receiver_test.go` [func TestEndtoEnd](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/93a9885459c9406db8ac446f77f290b02542e8d5/receiver/prometheusreceiver/metrics_receiver_test.go#L1295) , to create test that uses pdata directly rather than using OpenCensus data structures. Existing [`TestStartTimeMetricRegex`](https://github.com/open-o11y/opentelemetry-collector-contrib/blob/ae3a556549ab666bccfb1812730f7818915ea764/receiver/prometheusreceiver/metrics_receiver_test.go#L1494) , [`TestExternalLabels`](https://github.com/open-o11y/opentelemetry-collector-contrib/blob/ae3a556549ab666bccfb1812730f7818915ea764/receiver/prometheusreceiver/metrics_reciever_external_labels_test.go#L37) , and [`TestStartTimeMetric`](https://github.com/open-o11y/opentelemetry-collector-contrib/blob/ae3a556549ab666bccfb1812730f7818915ea764/receiver/prometheusreceiver/metrics_receiver_test.go#L1385) are currently dependent upon OpenCensus datastructure. Also, currently these tests do not account for staleness markers that gets emmitted when scrapping metrics accross different endpoints ([see link](https://github.com/open-o11y/opentelemetry-collector-contrib/blob/ae3a556549ab666bccfb1812730f7818915ea764/receiver/prometheusreceiver/metrics_receiver_test.go#L1511)). 

**Describe the solution you'd like**
Using the helper methods of metric_receiver_test.go from Issue #6151, modify the existing `testEndToEndRegex`, `TestExternalLabels`, and `TestStartTimeMetric`, such that these tests use pdata format directly. Also, to make these compatible with staleness markers, remove the failed scrapes that have staleness markers using the method getValidScrapes in issue #6151.

**Additional context**
Related to https://github.com/open-telemetry/wg-prometheus/issues/57
Related Issues:
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6151
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6000
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6087
cc: @alolita @Aneurysm9

**Comment by PaurushGarg** [comment]
@alolita please assign this issue to me. I would like to work on this one.

**Comment by alolita** [comment]
Fixed.
