### ISSUE TITLE
Feature request: Add cloudwatch metrics receiver

### ISSUE THREAD

**Issue by yotamloe** [open-telemetry/opentelemetry-collector-contrib#6226]
**Is your feature request related to a problem? Please describe.**
We need an easy solution to import metric data from cloudwatch to Prometheus remote write compatible backend without using an exporter

**Describe the solution you'd like**
A receiver component That uses cloudwatch getmeticstatistics/getmetricdata API
reference:
* [get-metric-statistics](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/get-metric-statistics.html)
* [get-metric-data](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/get-metric-data.html)

**Describe alternatives you've considered**
Options:
* Using external exporter with `Prometheus` and `Prometheusexec` receivers, for example: [prom/cloudwatch-exporter](https://github.com/prometheus/cloudwatch_exporter), [nerdswords/yet-another-cloudwatch-exporter](https://github.com/nerdswords/yet-another-cloudwatch-exporter)
* Using another agent ([telegraf](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cloudwatch)) but their plugin is buggy and has some limitations (importing tags). Besides that, we would love to stay with one agent like open telemetry for all of our telemetry data (logs, metrics, traces) going forward.

**General notes**
Are there any plans to develop this kind of receiver? I would love the feedback of our community if anyone has more recommendations or other possible solutions, also I would be happy to help implement such a solution.

**Comment by khanhntd** [comment]
Hey @alolita would it possible for me to try this?

**Comment by alolita** [comment]
Hi @yotamloe we're taking a look at this and assessing feasibility. Stay tuned.
