### ISSUE TITLE
Refine policy for unmaintained components

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#6227]
In a SIG meeting today we discussed the need to have a more precise policy about maintaining contributed components. This is also important in the context of having stable tests. Some components have flaky tests and we don't have a policy about who and when is supposed to fix the tests.

One possible approach is this:
- Introduce the concept of "unmaintained" components.
- If the component's authors/codeowners are unresponsive, e.g. they don't fix flaky tests in 4 weeks after begin asked then the component is marked as unmaintained.
- Unmaintained components print a warning in the log when starting saying that they are unmaintained and may be removed.
- If the component remains unmaintained for 6 months (or maybe 12 months?) we remove it from Collector's default build.
- If the authors/codeowners return in that 6 month period and begin maintaining the component (fix flaky tests) we remove the "unmaintained" label.
- If the any PR is submitted against an "unmaintained" component that has a flaky test, the PR is rejected until the flaky tests are fixed.

On flaky tests:
- It is OK to delete flaky tests if we see that the test is poorly written and is not worth fixing.
- It is not OK to delete flaky tests which can’t be easily proven to be flaky tests and not actual component bugs.

@open-telemetry/collector-approvers any thoughts on making this an official policy?

**Comment by tigrannajaryan** [comment]
cc @open-telemetry/collector-contrib-approvers @open-telemetry/collector-contrib-maintainer

**Comment by alolita** [comment]
@tigrannajaryan I suggest we add documentation listing maintainers for each component in contrib. I can create a component-owners.md and link to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/README.md

**Comment by tigrannajaryan** [comment]
> Alolita: I don't support this since the project should be welcoming of all contributions and inclusive. As long as we communicate clearly that the component is unmaintained, as a project we can assign lower priority to the PRs for unmaintained components but not reject them.

@alolita good point. What if we change this a bit and say that we don't accept new feature PRs from component authors until they deal with the maintenance backlog for their components, which includes flacky tests? Other contributors can still submit PRs against unmaintained components, but authors should show they are committed to maintenance.

**Comment by jpkrohling** [comment]
> they don't fix flaky tests in 4 weeks after begin asked

Change it to 8 weeks, and I'm OK with the proposal. I do take 4 weeks PTOs from time to time, and while I hope other folks would take care of a component I'm the sole owner, I would find a shame to come back from PTO and find my component as unmaintained :-)

**Comment by mx-psi** [comment]
This proposal sounds great to me. I would also suggest pinning an issue on this repo with a list of unmaintained components (something like #3870?) so that it's easier for people to find which components are unmaintained (both for end-users and for prospective owners)

**Comment by mx-psi** [comment]
I think we can close this, we already have a policy for unmantained components. Feel free to reopen if you disagree
