### ISSUE TITLE
build fails with duplicate symbol errors in Mac

### ISSUE THREAD

**Issue by ananthmeka** [open-telemetry/opentelemetry-collector-contrib#6234]
Code cloned from opentelemetry-collector-contrib repository is failing while building in Mac 
The build errors generated with make are :
     duplicate symbol '_get_temperature' , duplicate symbol '_open_smc', duplicate symbol '_close_smc

Trace log of the build is provided below:

go test -race -timeout 300s --tags="" ./...
?   	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol	[no test files]

#github.com/open-telemetry/opentelemetry-collector-contrib/internal/components.test
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
**duplicate symbol '_get_temperature' in:**
    /var/folders/bq/107tby_j7259rm4tgx7jgs2w0000gp/T/go-link-3596767389/000024.o
    /var/folders/bq/107tby_j7259rm4tgx7jgs2w0000gp/T/go-link-3596767389/000031.o
**duplicate symbol '_open_smc' in:**
    /var/folders/bq/107tby_j7259rm4tgx7jgs2w0000gp/T/go-link-3596767389/000024.o
    /var/folders/bq/107tby_j7259rm4tgx7jgs2w0000gp/T/go-link-3596767389/000031.o
**duplicate symbol '_close_smc' in:**
    /var/folders/bq/107tby_j7259rm4tgx7jgs2w0000gp/T/go-link-3596767389/000024.o
    /var/folders/bq/107tby_j7259rm4tgx7jgs2w0000gp/T/go-link-3596767389/000031.o
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/internal/components [build failed]

**Comment by cuichenli** [comment]
duplicated to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5425#issuecomment-943128529

this is an upstream issue.
https://github.com/shirou/gopsutil/issues/1175
