### ISSUE TITLE
New Exporter: Simplified local developer view

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#6241]
**Is your feature request related to a problem? Please describe.**
In order to reduce the resource contention on a local developer's machine, having a simplified view resource data in the collector via a web UI that allows for easy filtering instead of using the `fileexporter` and using unix string search tools to examine the data.

**Describe the solution you'd like**
An exporter that keeps a ring buffer of X time window, exposes a port that allows a webclient to load a UI to query data inside the ring buffer and present them in a way that shows a context of time and values of the data.

**Describe alternatives you've considered**
There is `fileexporter` that is a nice means of debugging data when there is issues with the collector but does come with the expectation that you understand what that data represents but doesn't allow for easy visualisations.

Using docker to run local visualisation tools such as zipkin, influxdb, prom, and jaeger isn't an option when the applications that are trying explore open telemetry are already resource intensive.

**Additional context**
This is purely intended to help speed up adoption of open telemetry in a local developer environment, not for production system use.

**Comment by anuraaga** [comment]
I believe this is the zpages extension

https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/zpagesextension

The TraceZ endpoint is basically a ring buffer with a web UI. I haven't used the collector one myself, but the SDK one behaves like that, for reference

https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/zpages

**Comment by MovieStoreGuy** [comment]
Sweet, thanks @anuraaga :) 

Had completely missed it, let me close this off for now and anything more specific I am missing, I will raise as a feature request.
