### ISSUE TITLE
[Prometheus Receiver] Histogram and Summary metric count value outputs minInt64 for non-numerical input values

### ISSUE THREAD

**Issue by PaurushGarg** [open-telemetry/opentelemetry-collector-contrib#6376]
**Describe the bug**

We want to ensure OpenMetrics / Prometheus compatibility in the OpenTelemetry Collector. We have been building compatibility tests to verify the OpenMetrics spec is fully supported on both the OpenTelemetry Collector Prometheus receiver and PRW exporter as well as in Prometheus itself.

Prometheus Receiver should assign a metric  `staleNaN` value, if the metric is missing in the current scrape but was present in the previous scrape. However, currently metric builder do not assign `staleNaN` values to the histogram and summary values, that are passed by the Prometheus scrape loop for failed scrapes. 
Histogram and Summary `count` values are int64, and the casting of float64 type num-numerical values(staleNaN, normalNaN, and +-Inf) assign minInt64(-9223372036854775808)  number to the `count`. 

**Steps to reproduce**

* Run func [TestEndToEnd(t *testing.T) ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1e9005e6fa42a5514bac6f4f4c725f10d64c16f8/receiver/prometheusreceiver/metrics_receiver_test.go#L1295)
* Currently, the validate loop is skipped for the tests, re-enable the validate loop by removing/commenting following lines from func testEndToEnd(...) (lines  [1442-1445](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1e9005e6fa42a5514bac6f4f4c725f10d64c16f8/receiver/prometheusreceiver/metrics_receiver_test.go#L1440))

```
if true {
   t.Log(`Skipping the "up" metric checks as they seem to be spuriously failing after staleness marker insertions`)
   return}

```
*  Note: the test fails in getValidScrapes due to staleness, inspect the [metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1e9005e6fa42a5514bac6f4f4c725f10d64c16f8/receiver/prometheusreceiver/metrics_receiver_test.go#L1423) and find the first failed scrape. The Histogram and Summary count values in the failed scrapes are minInt64(-9223372036854775808) instead of non-numerical values (staleNaN, normalNaN, and +-Inf) 

**What did you see instead?**

Scraping endpoints that contains histogram/summary metric and a failed scrape in between, produces the following graph in Prometheus Web UI. The histogram/summary count value is plotted as the peak in the below graph:
![Screen Shot 2021-11-01 at 9 40 08 PM](https://user-images.githubusercontent.com/62579325/142481772-505c8cb4-e47e-4161-a7ad-6720f9d48ad0.png)

However, if same data is passed directly to the Prometheus Server. Prometheus WebUI produces following graph:
![Screen Shot 2021-11-03 at 7 29 30 AM](https://user-images.githubusercontent.com/62579325/142481813-518ecf37-2823-471b-b102-0d71d0f7e2b0.png)

**Possible Solution**

Since `count` value (int64) for histogram/summary can not be assigned float64 values, one possible solution is to use directly use OTLP format in OTLP Prometheus receiver `metricbuilder`, and assign datapoint flags ([MetricDataPointFlagNoRecordedValue](https://github.com/open-telemetry/opentelemetry-collector/blob/0b4e5ec7924c56342c0ab453ca3dc99bbe3642cd/model/pdata/metrics.go#L285)) to the metric as staleness marker. See linked issue: #6400

**What version did you use?**

Collector-Contrib: v- 0.37.1

**Additional context**
Related to https://github.com/open-telemetry/wg-prometheus/issues/57
Linked Issue: #6400 #6000 #6087

cc @alolita @Aneurysm9

**Comment by bogdandrutu** [comment]
@PaurushGarg I agree, the prometheus receiver should not set that "NaN" value but instead should use the OTLP native no-value present for that (for all metrics not just for histograms).

**Comment by PaurushGarg** [comment]
> @PaurushGarg I agree, the prometheus receiver should not set that "NaN" value but instead should use the OTLP native no-value present for that (for all metrics not just for histograms).

@bogdandrutu thanks. Is there a tracking issue for Prometheus Receiver to directly use OTLP format in metric builder? If not, do we need to create one?
