### ISSUE TITLE
[cmd/mdatagen] mdatagen should fail on unrecognized keys

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#6396]
#6220 renamed the `labels` section on `mdatagen` configuration files to `attributes`, but forgot to change it on mongodbatlasreceiver (addressed by #6395). 

A simple way to have caught this would be for `mdatagen` to fail when the YAML metadata file contains unknown keys. This would also then be checked on CI as part of the lint job.

**Comment by dmitryax** [comment]
I believe it was applicable to the old mdatagen which we fully migrated from
