### ISSUE TITLE
Cannot connect OpenTelemetry to Confluent Kafka using TLS

### ISSUE THREAD

**Issue by perrinj3** [open-telemetry/opentelemetry-collector-contrib#6408]
I'm trying to use the Kafka exporter to connect to an enterprise implementation of kafka which requires TLS authentication. 
I've tested the Kafka exporter with a local version of kafka (without auth) and it writes messages fine. 
I'm running OpenTel on a Windows 2012 server.
I'm using an internally created certificate and have tested this by loading it into the Java Key store and truststore and using the kafka_console_producer to push some test messages into the enterprise kafka. So I know what connectivity to the brokers is good and the certificate matches the acls for the topic I'm producing to.
When I try to use OpenTel to export to Kafka I get the following error 

~~~
Exporting failed. Will retry the request after interval.        {"kind": "export
er", "name": "kafka/eventmeshdev", "error": "Failed to deliver 1 messages due to
 kafka: client has run out of available brokers to talk to (Is your cluster reac
hable?)", "interval": "9.947195732s"}
~~~

I'm a bit unclear on how to configure OpenTel to use the certificate. What I have tried is installing the certificate into the Windows Certificate Store and leaving the TLS fields blank as follows. 

~~~
 kafka/eventmeshdev:
    topic: au.epcoe.TEST.opentelemetry.protobuf
    brokers:   
      - "broker-address:443"     
    protocol_version: 2.0.0
    
    auth:
     tls:
      ca_file:
      cert_file:
      key_file:    
    
    metadata:
      full: false
      retry:
        max: 15
    producer:
      max_message_bytes: 10000000
    timeout: 10s
    
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 10
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_interval: 60s
      max_elapsed_time: 10m  
~~~
The kafka support team aren't seeing any useful error messages. 
How do I configure OpenTel to use TLS correctly given I just have a .cer file?
If Ieave the TLS fields blank how does OpenTel find the correct certificate from the certificate store?

**Comment by jpkrohling** [comment]
>  If Ieave the TLS fields blank how does OpenTel find the correct certificate from the certificate store?

You should explicitly provide the path to the relevant files. I don't think we have support for Windows Cert Store in the collector though.

**Comment by perrinj3** [comment]
@jpkrohling Thanks for that reply. I specified the TLS authentication as follows and it seems to be working ok now. The help is a little confusing as it suggests the cert_file and the ca_file should only have values if insecure = true. However in our case insecure needs to be false. The exporter still reads the cert files even when insecure=false. So all good.
~~~
auth:
     tls:
      ca_file:
      cert_file: certificatefile.cer
      key_file: keyfile.key
      insecure: false
~~~
