### ISSUE TITLE
[kafkareceiver] Log metrics emitted as span metrics

### ISSUE THREAD

**Issue by samanthawalter** [open-telemetry/opentelemetry-collector-contrib#6427]
**Describe the bug**
The kafka log receiver accepted and refused counts are emitted as `receiver_accepted_spans` and `receiver_refused_spans` as opposed to the expected `receiver_accepted_log_records` and `receiver_refused_log_records`.

**Steps to reproduce**
1. Setup and configure a kafka instance 
2. Configure a logs collector pipeline with a `kafkareceiver` receiver component.
3. Expose port 8888 for Prometheus collector metrics. Configure Prometheus to scrape metrics from collector port 8888.

**What did you expect to see?**
Metrics named `otelcol_receiver_accepted_log_records` and `otelcol_receiver_refused_log_records`.

**What did you see instead?**
Metrics named `otelcol_receiver_accepted_spans` and `otelcol_receiver_refused_spans`.

**Comment by jpkrohling** [comment]
Nice catch!
