### ISSUE TITLE
[Prometheus Receiver] Sync test data with the OpenMetrics repository

### ISSUE THREAD

**Issue by mustafain117** [open-telemetry/opentelemetry-collector-contrib#6439]
**Is your feature request related to a problem? Please describe.**
PR #6409 adds a copy of openmetrics test data to receiver/prometheusreceiver/testdata from the OpenMetrics repository.
Link to test data: https://github.com/OpenObservability/OpenMetrics/tree/main/tests/testdata/parsers
We need a way to keep the test data in sync with the OpenMetrics tests to avoid being out of sync with any changes upstream.

**Describe the solution you'd like**
A possible solution is to add a script or makefile target to sync the tests by pulling changes in from the OpenMetrics repository.

**Describe alternatives you've considered**
Please feel free to suggest any alternative solutions.

**Additional context**
Related to #6106

**Comment by alolita** [comment]
This is complete. Closing.
