### ISSUE TITLE
coreinternal package external use

### ISSUE THREAD

**Issue by tanner-bruce** [open-telemetry/opentelemetry-collector-contrib#6455]
**Is your feature request related to a problem? Please describe.**
A large chunk of the functionality inside the `coreinternal` package would be useful for people who are running customer collector distributions with their own custom components. Having this functionality blocked inside of an `internal` package forces you to fork the contrib package, or duplicate the code, which is a fairly poor experience, since you now need to keep up to date on contrib manually rather than simply importing the upstream package.

**Describe the solution you'd like**
Move `coreinternal` out of `internal` and allow use outside of this package.

**Describe alternatives you've considered**
The only alternatives available are to either completely copy the functionality into your own codebase, or fork contrib. Neither of these are developer friendly alternatives.

**Additional context**
A great example is [filterconfig.MatchConfig](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/coreinternal/processor/filterconfig/config.go#L26) -- this is generally useful functionality currently locked to this repo.

Another example is [testdata](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/coreinternal/testdata/trace.go). We currently replicate this functionality on our own for testing spans.

**Comment by mx-psi** [comment]
I think moving the whole `coreinternal` out of internal exposes a whole lot of public API that we probably don't want to maintain indefinitely. It may be easier to argue for individual packages to be moved out of internal, so I would recommend to make a list of specific functionality you need (is it just the two examples you mention, or are there others?)

**Comment by tanner-bruce** [comment]
> I think moving the whole `coreinternal` out of internal exposes a whole lot of public API that we probably don't want to maintain indefinitely. It may be easier to argue for individual packages to be moved out of internal, so I would recommend to make a list of specific functionality you need (is it just the two examples you mention, or are there others?)

I would start with the two I mentioned, particularly the filterconfig. The testdata is easy to work around and we already have the functions written on our end, but filterconfig requires full duplication right now.

Thanks for the quick 👀

**Comment by mx-psi** [comment]
@tanner-bruce if you are still interested please open a PR exposing the part that you need and we can discuss there.
