### ISSUE TITLE
Bug report: CircleCi Build fails for Loadtest

### ISSUE THREAD

**Issue by hossain-rayhan** [open-telemetry/opentelemetry-collector-contrib#646]
**Describe the bug**
After rebasing with master the CircleCi build fails for Loadtest.

Failed Test: `TestTrace10kSPS/OpenCensus`

Link to failed build report:
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/2405/workflows/e215ef4f-2af8-4e51-8074-493257602c0c/jobs/12982/parallel-runs/0/steps/0-104

**Comment by hossain-rayhan** [comment]
**Update:**
After a second try, it passed automatically. I didn't change anything from my side.

**Comment by andrewhsu** [comment]
from the issue triage mtg today, looks like this test was removed so closing this issue
