### ISSUE TITLE
[Prometheus receiver] `host.name` attribute set to `0.0.0.0`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#6465]
**Describe the bug**

When scraping internal metrics as documented [here](https://github.com/open-telemetry/opentelemetry-collector/blob/7ed3f75ef84d9e9d11b175a0859060f765faca0b/docs/troubleshooting.md#metrics) the metrics have a `0.0.0.0` hostname attribute set. The `host.name` semantic convention [is described in the OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/host.md) as:

> Name of the host. On Unix systems, it may contain what the hostname command returns, or the fully qualified hostname, or another name specified by the user.

As e.g. [Wikipedia says](https://en.wikipedia.org/wiki/0.0.0.0),
>  the address 0.0.0.0 is a non-routable meta-address used to designate an invalid, unknown or non-applicable target

so I would argue that this value does not follow the specification (it is not the name of any valid host).

**Steps to reproduce**

Follow the instructions [here](https://github.com/open-telemetry/opentelemetry-collector/blob/7ed3f75ef84d9e9d11b175a0859060f765faca0b/docs/troubleshooting.md#metrics) and add a logging exporter to the pipeline with `logLevel` debug (see below for full config). Run the Collector and wait a few seconds.

**What did you expect to see?**

The internal metrics had a valid hostname or no hostname at all.

**What did you see instead?**

Metric payloads had the `host.name` attribute set to `0.0.0.0`. For example:

```
Resource labels:
     -> service.name: STRING(otelcol)
     -> host.name: STRING(0.0.0.0)
     -> instance: STRING(0.0.0.0:8888)
     -> port: STRING(8888)
     -> scheme: STRING(http)
     -> job: STRING(otelcol)
InstrumentationLibraryMetrics #0
InstrumentationLibrary
Metric #0
Descriptor:
     -> Name: otelcol_exporter_enqueue_failed_log_records
     -> Description: Number of log records failed to be added to the sending queue.
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
Data point attributes:
     -> exporter: STRING(logging)
     -> service_instance_id: STRING(5e515c71-b05f-4735-88a8-9ecf5a4db707)
     -> service_version: STRING(latest)
StartTimestamp: 2021-11-30 15:21:30.96 +0000 UTC
Timestamp: 2021-11-30 15:21:30.96 +0000 UTC
Value: 0.000000
```

**What version did you use?**
Version: 61b560090fa1c0538409f578e0d011a89031e05a
**What config did you use?**
Config: 

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otelcol'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '.*grpc_io.*'
            action: drop
exporters:
  logging:
    loglevel: debug
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [logging]

```

**Environment**

not relevant (happens on any environment).

**Additional context**

This attribute is added by this function: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/61b560090fa1c0538409f578e0d011a89031e05a/receiver/prometheusreceiver/internal/prom_to_otlp.go#L24-L39

cc @Aneurysm9 @dashpole as CODEOWNERS

**Comment by jpkrohling** [comment]
I had a similar discussion on a [recent PR](https://github.com/open-telemetry/opentelemetry-operator/pull/574#discussion_r756047759), and the takeaway is that `0.0.0.0` on the client-side can be safely switched by `127.0.0.1`, as it's the one IP that is always present. Given that `0.0.0.0` represents all the IPs on the host, `127.0.0.1` is part of that set.
