### ISSUE TITLE
Create subprocess extension

### ISSUE THREAD

**Issue by NassimBtk** [open-telemetry/opentelemetry-collector-contrib#6467]
# Use case
The [prometheusexecreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusexecreceiver) launches the specified Prometheus Exporter as a new process (through specified command line) then scrapes it periodically. 
We need to launch an OTLP-instrumented process, that will push the metrics (and traces and logs) it collects to the local OTLP receiver.
Basically, we need a mechanism in the OpenTelemetry Collector that allows the execution of a sub process and monitors it, just like [prometheusexecreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusexecreceiver) does, but without the Prometheus scraping part.

# Solution
A **subprocess** extension makes more sens for this feature. 
Like done in [fluentbitextension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/fluentbitextension), the sub process is started and then monitored.
The **subprocess** extension can be configured using the executable path and the arguments:
```yaml
  sub_process:
    executable_path: 'bin/hws-agent'
    args: [ '--target.config.file=config/hws-config.yaml', "--server.port=24376" ]
```

# More information
![Use-case-otel drawio](https://user-images.githubusercontent.com/14110109/144110553-be56010d-a1fa-49eb-8fe6-d04fa4111bf7.png)

**Comment by jpkrohling** [comment]
@rmfitzpatrick, is this something that you'd benefit from for the JMX Receiver?

**Comment by NassimBtk** [comment]
Sure! creating the command, managing the state, stopping the process is almost the same.

**Comment by rmfitzpatrick** [comment]
I think this would be helpful, and a core set of subprocess management helpers could be used underneath as potentially provided by this issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5060

**Comment by jpkrohling** [comment]
I'm closing this, as we have previously talked about this and decided not to pursue this route.
