### ISSUE TITLE
Standardized testdata config filepath pattern

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-collector-contrib#6480]
**Is your feature request related to a problem? Please describe.**
As mentioned in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6459#discussion_r759550623, there is a current test pattern for specifying config files of the form:

```go
cfg, err := configtest.LoadConfigAndValidate(path.Join(".", "testdata", "config.yaml"), factories)
```

This invocation is slightly problematic for two reasons:

1. the initial "." is unnecessary.
2. `path.Join()` hardcodes the separator as "/" instead of picking it up from the os like `filepath.Join()` does, which is used by the underlying koanf loader. 

**Describe the solution you'd like**
Replace all `path.Join(".",` with `filepath.Join(`

**Describe alternatives you've considered**
Using embed could be preferable to using paths and loaders overall since the underlying byte slice would be available in the packages.  I have superficially confirmed that embedded items in test functions don't make their way to the final build using hexdump, but a more rigorous assessment would be necessary.  Since the existing helper works with paths and uses* the config map loaders, requiring embed directives as replacements and using bytes directly is probably overkill for most cases.

**Comment by jpkrohling** [comment]
Your proposed solution seems simple and effective enough.

**Comment by DiptoChakrabarty** [comment]
@jpkrohling @rmfitzpatrick I would like to work on this.

**Comment by jpkrohling** [comment]
Go for it, @DiptoChakrabarty

**Comment by bogdandrutu** [comment]
@jpkrohling can you track to ensure we do the same in the core repo?

**Comment by jpkrohling** [comment]
@codeboten beat me to it, thanks!
