### ISSUE TITLE
[kubeletstats receiver] Add support for read-only kubelet endpoint

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#6483]
**Is your feature request related to a problem? Please describe.**
Some of the kubernetes distributions (e.g. GKE Autopilot) block access to secure kubelet endpoint which is exposed at 10250 port by default. Most of the metrics collected by the kubeletstats receiver can also be fetched from read-only kubelet endpoint which is exposed at 10255 port by default. But kubeletstats receiver's configuration interface expects only the secure endpoint, it adds `https://` to the provided `endpoint` value and sets auth headers.

**Describe the solution you'd like**
Ability to configure kubeletstats receiver to use read-only kubelet endpoint.

It would be ideal if kubeletstats receiver can be configured in a way that it tries the secure endpoint first and falls back to read-only one.

**Comment by dmitryax** [comment]
cc @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
+1. Since k8s doesn't provide a granular permissions control on secure port, readonly port is often used to prevent overexposure of permissions. It also easy to get started with the readonly port. So I'd advice to allow http to be configured for the reciever.

**Comment by dmitryax** [comment]
Resolved in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6488
