### ISSUE TITLE
[spanmetricsprocessor] Delta metrics support in spanmetricsprocessor

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-collector-contrib#6484]
**Is your feature request related to a problem? Please describe.**

Currently the `spanmetricsprocessor` only supports cumulative metrics. This ticket is intended to track work related to enabling configuration of delta aggregation temporality for this processor.

We did consider using the current `spanmetricsprocessor` in conjunction with the `cumulativetodeltaprocessor`, however this unfortunately doesn't satisfy our use case. 

**Describe the solution you'd like**

A configuration parameter which allows switching to delta. By default, this would be cumulative. 

~~Some parts of the processor may need to be redesigned, as they were written with only cumulative in mind.~~

**Comment by jpkrohling** [comment]
cc @albertteoh

**Comment by jamesmoessis** [comment]
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6489

**Comment by TylerHelmuth** [comment]
@jpkrohling can this issue be closed?

**Comment by jamesmoessis** [comment]
Closing this as it's done.
