### ISSUE TITLE
RPM package doesn't properly mark config files

### ISSUE THREAD

**Issue by bkabrda** [open-telemetry/opentelemetry-collector-contrib#6491]
**Describe the bug**
The built RPM packages, e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.40.0/otel-contrib-collector-0.40.0-1.x86_64.rpm, don't properly mark files under /etc/otel-contrib-collector as config files. This leads to human-modified configuration files being overwritten on update/reinstall. 

**Steps to reproduce**
```
rpm -i otel-contrib-collector-0.40.0-1.x86_64.rpm
echo "foo" > /etc/otel-contrib-collector/config.yaml
rpm --reinstall otel-contrib-collector-0.40.0-1.x86_64.rpm
cat /etc/otel-contrib-collector/config.yaml # contains the default config instead of "foo"
```

**What did you expect to see?**
Both files under `/etc/otel-contrib-collector/` not being overwritten.

**What did you see instead?**
Both files under `/etc/otel-contrib-collector/` being overwritten.

**What version did you use?**
otel-contrib-collector-0.40.0-1.x86_64.rpm

**What config did you use?**
N/A

**Environment**
Fedora 32

**Additional context**
I'm not perfectly familiar with `fpm` which you use for builds, but AFAICS using its `--config-files` argument for config files should work. In rpm terms, you should mark the files as `%config` in the specfile.

**Comment by mx-psi** [comment]
cc @jpkrohling, probably a builder issue that also affects the core distro

**Comment by jpkrohling** [comment]
We do not use the builder (yet) for the contrib repository. We do set the `config` directives for the config files for the core distribution, so, it should not be a problem there:

https://github.com/open-telemetry/opentelemetry-collector-releases/blob/24a0eeeca07ecf09c01b87af3cdb9515d0f07b88/.goreleaser.yaml#L75-L80

**Comment by jpkrohling** [comment]
Closing this, as we now generate the contrib via releases, which doesn't seem to be affected by this.
