### ISSUE TITLE
influxdbreceiver: Unexpected response status code

### ISSUE THREAD

**Issue by perrinj3** [open-telemetry/opentelemetry-collector-contrib#6506]
**Describe the bug**
The influxdbreceiver endpoint returns a "202 Accepted status code" instead of the expected "204 No Content" as defined from the InfluxDB API reference. 

https://docs.influxdata.com/influxdb/v1.8/tools/api/#status-codes-and-responses-2

**Steps to reproduce**
The error occurs when K6 is configured to output test results to the InfluxdbReceiver endpoint. K6 expects a "HTTP/1.1 204 No Content" and when it gets"HTTP/1.1 202 Accepted" it reports this as a error which breaks the pipeline that runs the K6 test.

**What did you expect to see?**
HTTP/1.1 204 No Content

**What did you see instead?**
HTTP/1.1 202 Accepted

**What version did you use?**
Version: v0.4.0

**What config did you use?**
~~~
receivers:
  influxdb:
    endpoint: "0.0.0.0:8087"
          
exporters:
 
  file:
    path: ./jmeter_data.json 
 
service:
  pipelines:

   metrics:
     receivers: [influxdb]
     exporters: [file]
~~~
**Environment**
OS: Windows 2012

**Additional context**

**Comment by jpkrohling** [comment]
cc @jacobmarble, @8none1
