### ISSUE TITLE
Many unit tests fail on windows simply because we sent SIGTERM to end the agent or a process

### ISSUE THREAD

**Issue by boostchicken** [open-telemetry/opentelemetry-collector-contrib#6536]
**Describe the bug**
Run the trace stability tests on windows, all of them will fail because Windows does not support SIGTERM.  Our process handling code in tests should be cross platform if we are.

**Steps to reproduce**
Run any part of the testbed on Windows

**What did you expect to see?**
My test succeed

**What did you see instead?**
I was able to see that my test did succeed by read the logs, it just appeared to fail because we are sending sigterm, and windows doesn't support it so it throws and error and makes the test look as if it failed.

**What version did you use?**
Version: v0.4.0
**What config did you use?**
Config: No config, just testing performance of code in the testbed.
**Environment**
OS: Windows 11
Compiler(if manually compiled): GO 1.17.3

**Additional context**

**Comment by boostchicken** [comment]
![image](https://user-images.githubusercontent.com/427295/144867803-b02d3c37-697f-4bae-8a47-ce0d62843b9b.png)

**Comment by jpkrohling** [comment]
Fancy opening a PR fixing it?

**Comment by boostchicken** [comment]
@jpkrohling I do, i've tried many methods and all are ugly. the problem is it always causes the agent to exit with a non zero exist status which these tests see as a failure, are we comfortable saying if they agent started thats enough, it doesnt really matter how it died (as long as that dying was controlled by us)

**Comment by boostchicken** [comment]
the code isnt ugly, its just the windows binary doesnt listen to tskill, taskkill, anything since its built to be a service, so you have to HARD kill windows always, unix is a bit more elegant but in either situation its always non zero exit codes

**Comment by jpkrohling** [comment]
Is the new code going to be specific to Windows? If so, that's good enough for me, especially as I'm confident we don't have any maintainers familiar enough with Windows. Any help in this area is welcome.

**Comment by boostchicken** [comment]
@jpkrohling I was thinking that,  use the +build flags for the compiler and just make two child process management modules.
