### ISSUE TITLE
k8s_observer node detection

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-collector-contrib#6540]
**Is your feature request related to a problem? Please describe.**
Currently the `k8s_observer` endpoint discovery is limited to pods (and their ports) on a [single node](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/eacfde3fcbd46ba60a6db0e9a41977390c4883bd/extension/observer/k8sobserver/config.go#L28).  This restriction is constrictive in that it requires the "agent" model where each node requires a collector deployment, which can be cumbersome for both simple and nontrivial deployments, and also in that provides no underlying information about the node itself that could be useful for creating receivers (like the `kubeletstats` receiver).  It also difficult to use in servless contexts (AWS Fargate) where a collector in a deployment is unable to reach its own kubelet instance, so discovery must be preformed by collectors on other nodes: https://docs.aws.amazon.com/eks/latest/userguide/fargate.html#fargate-considerations & https://stackoverflow.com/questions/66445207/eks-fargate-connect-to-local-kubelet

**Describe the solution you'd like**
There should be a new endpoint type for a Kubernetes node ([`k8s.node`](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/resource/semantic_conventions/k8s.md#node)) that provides information about node instances roughly equivalent to that provided by the api via `kubectl get node <node_name> -o json`.

**Describe alternatives you've considered**
The only other alternative I've considered was to expand the `HostPort` endpoint to include generic mappings for arbitrary information, but given the target use case is so Kubernetes dependent this seems like an undesirable kludge.

**Additional context**
The SignalFx Smart Agent has an existing implementation of this whose adoption by the `k8s_observer` has proved relatively straightforward in local testing.

**Comment by jpkrohling** [comment]
How would it look like to the end-user, in terms of config?

**Comment by rmfitzpatrick** [comment]
@jpkrohling I've added a proposed endpoint here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6541.

For the `k8s_observer` config update my initial thought was to add two new options:

`observe_nodes` (default false)
`observe_pods` (default true)

And make the existing `node` field optional, where not providing one will lead to setting the `fields.Everything()` selector on the nodes and pods api query. This way backwards compatibility is largely preserved but provides the ability the expand to the full cluster.

**Comment by jpkrohling** [comment]
@rmfitzpatrick, do you know whether the linked PRs completely satisfy the original request from this issue?

**Comment by rmfitzpatrick** [comment]
Closing as resolved.
