### ISSUE TITLE
[Prometheus Remote Write Exporter] Ensure Prometheus Remote Write Exporter respond to OTLP data format from Prometheus Receiver

### ISSUE THREAD

**Issue by JamesJHPark** [open-telemetry/opentelemetry-collector-contrib#6620]
**Is your feature request related to a problem? Please describe.**
In regards to the issue [#6376](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6376), the metric builder does not assign `staleNaN` values to the histogram and summary values for failed scrapes from Prometheus scrape loop. Therefore, the proposed possible solution is to use the OTLP format in the OTLP Prometheus Receiver with datapoint flags as a staleness marker for metrics with no-value present to address this issue.

Accordingly, if the metrics in the Prometheus Remote Write Exporter contain the OTLP flag that indicates [MetricDataPointFlagNoRecordedValue](https://github.com/open-telemetry/opentelemetry-collector/blob/0b4e5ec7924c56342c0ab453ca3dc99bbe3642cd/model/pdata/metrics.go#L285), the Prometheus Remote Write Exporter should be able to handle and respond to the OTLP flag for staleness. This allows end-to-end compatibility in the collector pipeline with the use of OTLP native staleness marker flag, from the Prometheus Receiver to the Prometheus Remote Write Exporter.

**Describe the solution you'd like**
A possible solution is to check every data point for all metrics data types for the OTLP [MetricDataPointFlagNoRecordedValue ](https://github.com/open-telemetry/opentelemetry-collector/blob/0b4e5ec7924c56342c0ab453ca3dc99bbe3642cd/model/pdata/metrics.go#L285)flag, and set the sample value of the data point containing this flag to the `StaleNaN` value. This ensures the Prometheus Remote Write Exporter to handle and respond to the OTLP flag for staleness in the collector pipeline. 

**Additional context**
Related issue: [#6376](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6376) 

cc @alolita

**Comment by alolita** [comment]
Completed. Closing.
