### ISSUE TITLE
[mysqlreceiver] - Client is only initialized in start function

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#6636]
**Describe the bug**
The mysqlreceiver only initializes a client in its start function. This leaves it vulnerable to transient errors.

**What did you expect to see?**
Client should be initialized in the scrape function.

**Comment by bogdandrutu** [comment]
Is the client not smart enough to "reconnect" in case of a transient error?

**Comment by djaglowski** [comment]
> Is the client not smart enough to "reconnect" in case of a transient error?

You're right, the client manages a pool of connections, creates new ones as necessary, etc. As long as instantiation of the client succeeds, it will not fail on transient errors.

Given the above, I still wanted to understand whether it is appropriate that a failure to instantiate the client should make the collector fail to run. In short, it is correct in the case of the `go-sql-driver/mysql` driver, but each driver should be evaluated separately.

---

Further details, for the sake of future reference:

Instantiation of the client can fail in two ways. 
1. `database/sql` does not recognize the driver (e.g. `"mysql"`). This is code level problem where the developer has failed to register the driver, so failure is appropriate.
2. The driver returns an error from its [OpenConnector](https://github.com/go-sql-driver/mysql/blob/bcc459a906419e2890a50fc2c99ea6dd927a88f2/driver.go#L99) function, which it must implement. 

In the case of `go-sql-driver/mysql`, the client makes no attempt to establish a connection. It only only returns an error if the user specified DSN is malformed, so this is also appropriate cause to stop the collector.
