### ISSUE TITLE
Use `confighttp.NewDefaultClientConfig` function to create object of `confighttp.ClientConfig`

### ISSUE THREAD

**Issue by hprajapati-splunk** [open-telemetry/opentelemetry-collector-contrib#6641]
In [config/confighttp/confighttp.go](https://github.com/open-telemetry/opentelemetry-collector/blob/c27c673a5cd4928b34b71f784c0fb5cee477fa10/config/confighttp/confighttp.go) file 4 new pointer type variables (MaxIdleConns, MaxIdleConnsPerHost, MaxConnsPerHost, IdleConnTimeout) has been introduced. The pointer type is used in order to distinguish the user provided input with no-input as discussed [here](https://github.com/open-telemetry/opentelemetry-collector/pull/4188#discussion_r728042038).

In long run, we want to change those variable types to non-pointers as discussed [here](https://github.com/open-telemetry/opentelemetry-collector/pull/4188#discussion_r748475400), so we have introduced [DefaultHTTPClientSettings](https://github.com/open-telemetry/opentelemetry-collector/pull/4188/files#diff-1fadfcd3b4194004717150126d27e8a32fdaa8292ca99e81a937d26abe0998faR84) functions. Once, all the users' of below two repos start to use `DefaultHTTPClientSettings` function to create the object of `HTTPClientSettings`, we'll change those 4 variables's type to non-pointers:

- [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector)
- [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib)

This issue is created to track the progress mentioned above.

**Comment by jpkrohling** [comment]
@vvydier, this one is  also up for grabs, in case you are interested.

**Comment by mattsains** [comment]
I'm working on this issue. I've noticed that a lot of code in contrib defines different timeout values, and a lot of them are shared across packages, so I'm thinking a lot of the explicit timeout setting is just copy-pasting. Anyway, I'm going to preserve these changes in my PR because I can't know whether these timeouts are intentional or not.

I have a lot of work to do to update all the tests since they mostly assume the timeouts will be set to zero/nil whereas now they are set to the defaults in `NewDefaultHTTPClientSettings()`

**Comment by mattsains** [comment]
here's the progress I've made so far. The vast majority of the work is tests, which I'll continue burning through tomorrow:

https://github.com/open-telemetry/opentelemetry-collector-contrib/compare/main...mattsains:opentelemetry-collector-contrib:6641?expand=1

Please let me know if you see any issues with this because I'm repeating the same pattern hundreds of times so it would be good to know earlier if it's wrong :D

**Comment by mattsains** [comment]
I think this is still relevant because the config object still exists and there is a path forward to fixing it, just trying to get some buy in before doing the work.

**Comment by jpkrohling** [comment]
I'm closing this, as it's unlikely to be still relevant. If there's still interest in working on this, please reopen.

**Comment by dmitryax** [comment]
This is still relevant

**Comment by atoulme** [comment]
```
$>  git grep -l HTTPClientSettings | xargs dirname | sort | uniq > using_http_client_settings.txt
$> git grep -l DefaultHTTPClientSettings | xargs dirname | sort | uniq > using_default_http_client_settings.txt
$> diff using_http_client_settings.txt using_default_http_client_settings.txt
```

Gives me:
```
2,15d1
< cmd/opampsupervisor/specification
< cmd/otelcontribcol
< exporter/alertmanagerexporter
< exporter/datadogexporter
< exporter/dynatraceexporter
< exporter/dynatraceexporter/config
< exporter/elasticsearchexporter
< exporter/f5cloudexporter
< exporter/honeycombmarkerexporter
< exporter/influxdbexporter
< exporter/instanaexporter
< exporter/logicmonitorexporter
< exporter/logzioexporter
< exporter/lokiexporter
18,21d3
< exporter/prometheusremotewriteexporter
< exporter/signalfxexporter
< exporter/signalfxexporter/internal/correlation
< exporter/splunkhecexporter
23,28d4
< exporter/tanzuobservabilityexporter
< exporter/zipkinexporter
< extension/httpforwarder
< extension/oauth2clientauthextension
< extension/observer/ecstaskobserver
< internal/aws/ecsutil
30d5
< processor/resourcedetectionprocessor/internal/aws/ec2
32,51d6
< receiver/apachereceiver
< receiver/apachesparkreceiver
< receiver/awscontainerinsightreceiver/internal/ecsInfo
< receiver/awsecscontainermetricsreceiver
< receiver/bigipreceiver
< receiver/cloudfoundryreceiver
< receiver/couchdbreceiver
< receiver/elasticsearchreceiver
< receiver/expvarreceiver
< receiver/flinkmetricsreceiver
< receiver/gitproviderreceiver/internal/scraper/githubscraper
< receiver/haproxyreceiver
< receiver/httpcheckreceiver
< receiver/nginxreceiver
< receiver/nsxtreceiver
< receiver/purefareceiver
< receiver/purefbreceiver
< receiver/rabbitmqreceiver
< receiver/riakreceiver
< receiver/simpleprometheusreceiver
53d7
< testbed/mockdatasenders/mockdatadogagentexporter
```

Quite a few components need to change to accomodate that change.

**Comment by atoulme** [comment]
Usage to review:
* [ ] cmd/opampsupervisor/specification
* [ ] cmd/otelcontribcol
* [ ] exporter/alertmanagerexporter
* [ ] exporter/datadogexporter
* [ ] exporter/dynatraceexporter
* [ ] exporter/dynatraceexporter/config
* [ ] exporter/elasticsearchexporter
* [ ] exporter/f5cloudexporter
* [ ] exporter/honeycombmarkerexporter
* [ ] exporter/influxdbexporter
* [ ] exporter/instanaexporter
* [ ] exporter/logicmonitorexporter
* [ ] exporter/logzioexporter
* [ ] exporter/lokiexporter
* [ ] exporter/prometheusremotewriteexporter
* [ ] exporter/signalfxexporter
* [ ] exporter/signalfxexporter/internal/correlation
* [ ] exporter/splunkhecexporter
* [ ] exporter/tanzuobservabilityexporter
* [ ] exporter/zipkinexporter
* [ ] extension/httpforwarder
* [ ] extension/oauth2clientauthextension
* [ ] extension/observer/ecstaskobserver
* [ ] internal/aws/ecsutil
* [ ] processor/resourcedetectionprocessor/internal/aws/ec2
* [ ] receiver/apachereceiver
* [ ] receiver/apachesparkreceiver
* [ ] receiver/awscontainerinsightreceiver/internal/ecsInfo
* [ ] receiver/awsecscontainermetricsreceiver
* [ ] receiver/bigipreceiver
* [ ] receiver/cloudfoundryreceiver
* [ ] receiver/couchdbreceiver
* [ ] receiver/elasticsearchreceiver
* [ ] receiver/expvarreceiver
* [ ] receiver/flinkmetricsreceiver
* [ ] receiver/gitproviderreceiver/internal/scraper/githubscraper
* [ ] receiver/haproxyreceiver
* [ ] receiver/httpcheckreceiver
* [ ] receiver/nginxreceiver
* [ ] receiver/nsxtreceiver
* [ ] receiver/purefareceiver
* [ ] receiver/purefbreceiver
* [ ] receiver/rabbitmqreceiver
* [ ] receiver/riakreceiver
* [ ] receiver/simpleprometheusreceiver
* [ ] testbed/mockdatasenders/mockdatadogagentexporter

**Comment by astencel-sumo** [comment]
Here's an example pull request, this one fixes the Sumo Logic exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31510

Similar pull requests are needed for all other components that use the `confighttp.ClientConfig{...}` initialization.
