### ISSUE TITLE
status code parsing in awsxrayexporter should parse strings

### ISSUE THREAD

**Issue by xibz** [open-telemetry/opentelemetry-collector-contrib#6662]
Java tracing libraries like brave, which is widely used in the Java community, set all tag key and values as strings. This breaks the current implementation of the AWS Xray exporter as it expects status code to be an int. However, since we know the type of the value, we should check to see if it is a string, and if so, parse.

**Comment by bogdandrutu** [comment]
Brave emits "zipkin" format, so you probably use the zipkin "reeiver" to receive data from Brave. I think the zipkin receiver should do this work and inside collector we should have the status as int.

**Comment by xibz** [comment]
Hmmm, that's also a good place to do it. It definitely makes it consistent across all things considering.

**Comment by xibz** [comment]
So realized there's a `parse_string_tags` in zipkin receiver's config. Closing! Sorry for the noise.
