### ISSUE TITLE
Contribution guideline - add new component to tests

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6667]
New components are expected to be enabled in the related component-specific tests like done in this PR:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6517

We do not seem to have this documented anywhere at this moment and we should. This improvement to the docs should come accompanied by reference PRs for new components. For instance, a new extension could have its first PR similar to this:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6634

**Comment by jpkrohling** [comment]
I can work on this, but it's open for grabs in case someone else is interested. You did something similar recently, @MovieStoreGuy. Would you like to work on this?

**Comment by MovieStoreGuy** [comment]
For sure, please assign it to me :)

**Comment by bogdandrutu** [comment]
@MovieStoreGuy one extra example https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6680#pullrequestreview-828358434 :)

**Comment by MovieStoreGuy** [comment]
No worries, I can also work with @jamesmoessis on that PR since we are on the same team in Atlassian.

**Comment by bogdandrutu** [comment]
@jpkrohling we have this in core: https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component

**Comment by MovieStoreGuy** [comment]
From my understanding of the issue, we should make it clear that extensions (and additional components) are subjected to the integration compliance testing and require a reasonable excuse as to why they are not involved.

To be honest, I wasn't aware of this until I read further into the PRs linked that it was an expectation.

**Comment by jpkrohling** [comment]
Same here, when reading the following, I thought about unit tests of related to the component itself:

> Last PR should enable the new component and add it to the otelcontribcol binary by updating the components.go file. The component must be enabled only after sufficient testing, and there is enough confidence in the stability and quality of the component.

Or did you mean something else, @bogdandrutu?

**Comment by jpkrohling** [comment]
@MovieStoreGuy I believe this is completely done now, but do reopen if there's still something missing.
