### ISSUE TITLE
ASAP client auth missing on the list of components

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6669]
The ASAP client auth extension was added as part of the PR #6627, but it's missing from the list of components here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/components/components.go

It should also be added to the extensions test (#6668 and #6667).

**Comment by jpkrohling** [comment]
@jamesmoessis, would you like to work on this one?

**Comment by jamesmoessis** [comment]
@jpkrohling sure thing I can pick this up

**Comment by jpkrohling** [comment]
I believe this has been done already.
