### ISSUE TITLE
Add OTLP HTTP support for tracegen

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6671]
During the SIG Collector meeting, @bogdandrutu suggested the tracegen to add support for transmitting data using OTLP HTTP as an option. The default should still be gRPC though.

**Comment by nemoshlag** [comment]
Hi 👋  So I guess exposing it as an optional flag? You can assign it to me :)

**Comment by jpkrohling** [comment]
It's yours! Controlling this as a flag is certainly the way to go.
