### ISSUE TITLE
Journaldreceiver - Add documentation and build an "official" docker image for journald-gateway

### ISSUE THREAD

**Issue by gillg** [open-telemetry/opentelemetry-collector-contrib#6672]
**Is your feature request related to a problem? Please describe.**
Journald receiver has been implemented in a non trivial way in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2332 now according to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2332#issuecomment-936726272 we should help users to use it.

**Describe the solution you'd like**

**Solution 1 :**
Document how to build a custom sidecar image to use journalctl

**Solution 2 :**
Add an option in journaldreceiver to use else journalctl, else a remote htttp endpoint for journald-gateway and implement it on log-collection library (@djaglowski any news about that ?)
Build an official docker image "opentelemetry/journald-gateway" to help used deploying it as daemon on each server.
```
FROM debian:stable-slim

RUN apt update && apt install -y systemd-journal-remote && apt clean
# For RHEL : yum install systemd-journal-gateway

EXPOSE 19531
 
# Doc https://www.freedesktop.org/software/systemd/man/systemd-journal-gatewayd.service.html
ENTRYPOINT ["/lib/systemd/systemd-journal-gatewayd"]
# For RHEL : /usr/lib/systemd/systemd-journal-gatewayd

CMD ["--directory=/host/var/log/journal"]
```
Then `docker run -v /var/log/journal/:/host/var/log/journal/ -ti journald-gateway`

Both solution could eventualy be done.

**Comment by djaglowski** [comment]
Can we separate the issue of adding support for `journald-gateway` from the question of what we should do to help users with deploying the dependencies?

I agree that it makes sense to enhance to the log-collection library to enable usage of `journald-gateway`. I'm not clear on whether this should be within the same `journald_input` operator or not. I think this would largely depend on how much the configuration must vary, whether there would be any code reuse, etc. It would be good to see an analysis or even an implementation. This isn't a priority for me but I am happy to review if you want to make the contribution.

As for the latter issue, it's not clear to me that this repo is concerned with advising on how to deploy journalctl / journald-gateway. I'm not necessarily the best person to weigh in on that question, but I'd want to start by validating that it is indeed within scope.

**Comment by gcb** [comment]
The sidecar option only covers k8s. The actual host running all the things is left out of any observability.

**Comment by gillg** [comment]
> The sidecar option only covers k8s. The actual host running all the things is left out of any observability.

Why ? On a bare metal host or a VM you can install the package systemd-journal-gateway
So an otel collector (even without docker) can connect to the endpoint.

But anyway in a non k8s environment (or without docker in general) there is definitely no problem to monitor journald as the needed libs will be found on the system by the otel binary

**Comment by gcb** [comment]
My bad, I meat, if you don't go the sidecar route, this can plug into any journald-gateway, including use cases where you do not want to deploy the collector locally for the host itself, But would allow one container with the collector to reach the gateway ports.
