### ISSUE TITLE
Adopt a pattern for PR titles

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6688]
In order to facilitate the release process, I wanted to propose a guideline for PR titles. Feedback from @open-telemetry/collector-contrib-approvers is appreciated.

There are currently two main patterns I'm seeing related to PR titles, in addition to the "free format" that most are following. The two patterns are:

1. `componentnametype`: description
1. [type/componentname] description

Examples:
1. `lokiexporter`: add complete log record to body
1. [exporter/loki] add complete log record to body

I personally prefer the first option and would like to make it a standard, enforced by approvers and maintainers during the PR review.

If @open-telemetry/collector-contrib-approvers agree with this proposal, I'll send in a PR changing the contributing and reviewing guidelines.

**Comment by tigrannajaryan** [comment]
I have a slight preference for `componentnametype: description` since it is easier to copy/paste the directory name.

**Comment by Aneurysm9** [comment]
I have a slight preference for `type/componentname` since it reflects the directory structure and points to where the changes can be found, but I would be fine with either.

**Comment by dmitryax** [comment]
I have a slight preference for "[type/componentname] description". It is easier to read for me.

**Comment by jpkrohling** [comment]
I have a strong preference for a decision, so I would vote for @dmitryax's proposal, as I can copy/paste the directory and just have to remove the final part of the path to clean it up if needed:

- [extension/jaegerremotesampling], no need to clean up anything
- [extension/oidcauth], removed suffix "extension"

**Comment by mx-psi** [comment]
I have been using `[type/componentnametype]` which is a direct copy-paste of the directory name, but a bit repetitive; @dmitryax's alternative is simpler and still points to the directory in some way so I would favor that one.

A remaining question is what to do with PRs that deal with several components or that deal with non-component modules (e.g. testbed or internal modules).

**Comment by jpkrohling** [comment]
> A remaining question is what to do with PRs that deal with several components or that deal with non-component modules (e.g. testbed or internal modules).

We can treat them as exceptions, like these ones we had during the last release:

- Remap arm64 to aarch64 on rpm/deb packages (6635)
- Update log-collection library to v0.23.0 (6593)

**Comment by tigrannajaryan** [comment]
"[type/componentname] description" works for me, I don't mind. Let's choose and one stick with it.

**Comment by codeboten** [comment]
"[type/componentname] description" works for me as well, to make it easy for releases, are we ok with the same pattern in the changelog/release notes?

**Comment by jpkrohling** [comment]
Yes, we should definitely use the same pattern there.

**Comment by anuraaga** [comment]
Sorry for the late chime in, I was looking for components that don't repeat the type in their folder name and think I only found a few extensions. Should we enforce repeating the type in the folder name and only use that, rather than e.g. `processor/attributesprocessor` which stutters a little?
