### ISSUE TITLE
Require changelog entry for every PR

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6689]
Similar to what we have already in the core repository, every change should be accompanied by a changelog entry. Exceptions are marked with the "Skip changelog" label in the PR.

If @open-telemetry/collector-contrib-approvers agree with this proposal, I'll send in a PR implementing this check based on what we have for the core repository.

**Comment by mx-psi** [comment]
#6093 would address this, but I share @anuraaga's concerns here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6093#pullrequestreview-794851722: with the current approach and repo's activity this means a lot more merge conflicts

**Comment by jpkrohling** [comment]
Not only that, but each PR has to be opened in two steps: send in the PR, get a PR number, update the changelog with the PR number.
