### ISSUE TITLE
Update example configuration for metrics transform processor

### ISSUE THREAD

**Issue by tmorrisonsfx** [open-telemetry/opentelemetry-collector-contrib#6702]
The configuration on https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/metricstransformprocessor/README.md#configuration appears to be missing `metricstransform:` before ` transforms:`. This is confusing to customers.

**Comment by jpkrohling** [comment]
@james-bebbington, I'm assigning this to you as you are listed as the owner of this component. Feel free to unassign if inappropriate.

**Comment by jpkrohling** [comment]
@tmorrisonsfx, if you have a working solution, would you mind opening a PR with the fix?

**Comment by jpkrohling** [comment]
@punya, are you stepping in for the metrics transform processor?

**Comment by dmitryax** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7064
