### ISSUE TITLE
`lokiexporter`: verify resources and attributes encoding for JSON

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6801]
When using the JSON encoding, the lokiexporter might not be taking the resources and attributes into consideration, making them not be recognized as fields in the backend/UI.

**Comment by vvydier** [comment]
yes, definitely! Thanks

**Comment by jpkrohling** [comment]
It doesn't have to, but I just assigned it to you.

**Comment by mar4uk** [comment]
Is there any help needed? Are there any specific resource attributes and attributes that are missing?

**Comment by jpkrohling** [comment]
Given the imminent deprecation of this component, I'm closing this.
