### ISSUE TITLE
[Prometheus Exporter] Ensure Prometheus Exporter respond to OTLP data format from Prometheus Receiver

### ISSUE THREAD

**Issue by hyunuk** [open-telemetry/opentelemetry-collector-contrib#6805]
_This issue is identical with #6620 but for Prometheus Exporter._

**Is your feature request related to a problem? Please describe.**
In regards to the issue #6376, the metric builder does not assign staleNaN values to the histogram and summary values for failed scrapes from Prometheus scrape loop. Therefore, the proposed possible solution is to use the OTLP format in the OTLP Prometheus Receiver with datapoint flags as a staleness marker for metrics with no-value present to address this issue.

Accordingly, if the metrics contain the OTLP flag that indicates MetricDataPointFlagNoRecordedValue, the Prometheus Exporter should be able to handle and respond to the OTLP flag for staleness. This allows end-to-end compatibility in the collector pipeline with the use of OTLP native staleness marker flag, from the Prometheus Receiver to the Prometheus Exporter.

**Describe the solution you'd like**
A possible solution is to check every data point for all metrics data types for the OTLP MetricDataPointFlagNoRecordedValue flag, and drop the metric if the flag is enabled. This ensures the Prometheus Exporter to handle and respond to the OTLP flag for staleness in the collector pipeline.

**Additional context**
Related issue: #6376, #6620

cc @alolita

**Comment by alolita** [comment]
Resolved. Closing issue.
