### ISSUE TITLE
SerializationException in awsxrayexporter if you alternate between compliant X-Ray Trace IDs

### ISSUE THREAD

**Issue by NathanielRN** [open-telemetry/opentelemetry-collector-contrib#6808]
**Describe the bug**

If you configure your OTel SDK to generate AWS X-Ray compliant Trace IDs, but then later a child trace uses a non-compliant X-Ray Trace ID (i.e. W3C format), the Collector will crash due to a `SerializationException` error in the `awsxrayexporter`.

This behavior has a notable use case for AWS Lambda users. When their Lambda function starts, they may already be executing within the context of a parent trace that is tracing the Lambda function. However, they may want to change the parent of subsequent traces using the context they can pull from the `lambda_event`. (i.e. from HTTP headers found in the Lambda event). That context may not necessarily be an X-Ray compliant header.

I suspect that this error is the cause of https://github.com/aws-observability/aws-otel-lambda/issues/124

**Steps to reproduce**

Here is a quick OTel Python SDK program which first generates a trace with an X-Ray compliant trace ID, but then generates a child trace with a non-X-Ray compliant trace ID:

```python
from opentelemetry import trace as trace_api
from opentelemetry.trace import SpanKind, get_tracer

from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.trace.export import BatchSpanProcessor

from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import (
    OTLPSpanExporter,
)

from opentelemetry.sdk.extension.aws.trace import AwsXRayIdGenerator

from opentelemetry.propagators.aws import AwsXRayPropagator

trace_api.set_tracer_provider(
    trace_sdk.TracerProvider(
        id_generator=AwsXRayIdGenerator(),
        active_span_processor=BatchSpanProcessor(OTLPSpanExporter()),
    )
)

tracer = get_tracer(__name__)

parent_context = AwsXRayPropagator().extract(
    { "X-Amzn-Trace-Id": "Root=1-5759e988-bd862e3fe1be46a994272793;Parent=53995c3f42cd8ad8;Sampled=1" }
)

with tracer.start_as_current_span("A good root level span") as span:
    with tracer.start_as_current_span(
        "My ID with a non X-Ray Compatible ID", context=parent_context, kind=SpanKind.SERVER
    ) as child_span:
        print("hello")

```

The install requirements should be the following:

```
pip install \
    opentelemetry-sdk-extension-aws \
    opentelemetry-exporter-otlp-proto-grpc \
    opentelemetry-propagator-aws-xray
```

Then you would want to run the latest collector image with this command:

```
docker run \
    -p 4317:4317 \
    -e HOME=/ \
    -v $HOME/.aws:/.aws \
    -v $(pwd)/:/config \
    otel/opentelemetry-collector-contrib:latest --config /config/collector-config.yml
```

and the config is found below.

**What did you expect to see?**

No errors in the collector. Specifically, the `awsxrayexporter` should not raise an exception just because the Trace ID is incorrect. At minimum the `awsxrayexporter` should post an error like it typically does if the ID is not in X-Ray compatible format:

```
2021-12-15T07:44:17.622Z        debug   awsxrayexporter@v0.40.0/awsxray.go:54   TracesExporter  {"kind": "exporter", "name": "awsxray", "type": "awsxray", "name": "awsxray", "#spans": 1}
2021-12-15T07:44:17.623Z        debug   awsxrayexporter@v0.40.0/awsxray.go:65   Error translating span.   {"kind": "exporter", "name": "awsxray", "error": "invalid xray traceid: ff78ad1769f352d7429468f45dd27eed"}
```

**What did you see instead?**

I saw the `awsxrayexporter` crash the collector with this error:

```
2021-12-15T07:35:42.304Z        error   exporterhelper/queued_retry.go:165      Exporting failed. Try enabling retry_on_failure config option.    {"kind": "exporter", "name": "awsxray", "error": "Permanent error: SerializationException: \n\tstatus code: 400, request id: ef102cf3-23f0-490f-b5d4-8e6eaa0a849e"}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector@v0.36.0/exporter/exporterhelper/queued_retry.go:165
```

**What version did you use?**
`v0.41.0`

**What config did you use?**
Config:

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  awsxray:
    region: us-west-2

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - awsxray
```

**Environment**
OS: macOS
Compiler(if manually compiled): N/A

**Additional context**

cc @jefchien @sethAmazon

**Comment by jpkrohling** [comment]
@anuraaga, I'm assigning this to you as you are a code owner for this component.

**Comment by sethAmazon** [comment]
I'll take a look. Please assign yo me.

**Comment by sethAmazon** [comment]
This is merged and should be available in release 42

**Comment by NathanielRN** [comment]
Thanks for your work @sethAmazon ! 🙂 I think if you edit your #6821 PR Description to say "Fixes #6808" then this issue will be "linked" to that PR so people in the future can confirm that the fix has been merged/released ?

Otherwise I would agree that we are good to close this issue 👍

**Comment by sethAmazon** [comment]
@NathanielRN it is linked. I just made the commit message to large so it was wrapped into the description.

**Comment by NathanielRN** [comment]
@sethAmazon Sorry I don't mean just adding a URL link, I meant [the GitHub feature which scans the PR description for specific keywords like "Closes" and "Fixes"](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to "link" the issue to the PR.

It's not required since you can find the PR in the logs above, but I think this feature is useful because it is more obvious to those searching for the PR that fixes the Issue.

**Comment by jpkrohling** [comment]
I'm closing this as the linked PR was merged. If this isn't accurate, feel free to reopen.
