### ISSUE TITLE
Implement alternative authorization for Stackdriver

### ISSUE THREAD

**Issue by serathius** [open-telemetry/opentelemetry-collector-contrib#688]
**Is your feature request related to a problem? Please describe.**
Stackdriver exporter allows for using exporting to selected project, but only can use GCE default token. 

This is a problem in tenant setups monitoring data is sent do different projects. In such case GCE default service account would need to be authorized to write to different project, which is not great due security. 

**Describe the solution you'd like**
My exact case is that tokens can be created from HTTP server via POST request with custom URL and Body.

**Alternatives**
Have a generic way to inject authorization tokens to exporters.

**Comment by james-bebbington** [comment]
@nilebox can this be closed now?

**Comment by nilebox** [comment]
We have used #1010 as a workaround, so this issue can be closed.
