### ISSUE TITLE
[receiver/memcached] Units need revisiting

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#6881]
Particularly, [memcached.cpu.usage](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4fedae5d026f52dc0cbf26b2a619e7105c0eac9e/receiver/memcachedreceiver/metadata.yaml#L95) appears to be wrong. This should be a unit of time.

Most of the other units should use the `"{things}"` notation.

**Comment by dmitryax** [comment]
Submitted another issue for memcached scraper https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6886
