### ISSUE TITLE
Add otel collector sample in doc page

### ISSUE THREAD

**Issue by slernersplunk** [open-telemetry/opentelemetry-collector-contrib#6884]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jpkrohling** [comment]
Which doc page do you mean? Won't the ones from the following page do it?

https://opentelemetry.io/docs/collector/configuration/

**Comment by slernersplunk** [comment]
sorry let me be more specific- on this page- the issue file didn't link the page...
here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mongodbatlasreceiver

there is an example of the receiver, but not the pipeline which should be:

service:
  pipelines:
    metrics:
      receivers: [mongodbatlas]

make sense? that is missing from:

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mongodbatlasreceiver

**Comment by jpkrohling** [comment]
While I'm a fan of providing fully functional examples, configuring the pipeline is something that should be explained somewhere else in the collector documentation.

cc @zenmoto

**Comment by slernersplunk** [comment]
fair enough- but I work with otel users every day and they stumble quickly when all info needed is not provided... how about simple narrative text:

"Ensure when configuring this receiver that the `mongodbatlas` receiver pipeline is present" 

???

**Comment by jpkrohling** [comment]
@MovieStoreGuy, do you think should become a recommendation for component developers? To provide a full example with nop components?

**Comment by zenmoto** [comment]
It seems a bit redundant to explain how the collector works in every component, but as I was looking at what we do in other receivers, I came across the example [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/windowsperfcountersreceiver#scraping-at-different-frequencies), and I agree that it gives a bit more context.  @slernersplunk does #6893 satisfy your request?

**Comment by slernersplunk** [comment]
@zenmoto yes it would... remember that the user of otelcol don't have the same experience with it as the creators- every single line of help we give will increase adoption... thanks!

**Comment by MovieStoreGuy** [comment]
> @MovieStoreGuy, do you think this should become a recommendation for component developers? To provide a full example with nop components?

Potentially, though as you mentioned, it should be explained in further detail within the higher level collector docs. 

Thinking about this a little more, we could adopt the idea of a configuration builder that would spit a partial built configuration file ready to use. Things like secrets are fine to replace manually.

**Comment by MovieStoreGuy** [comment]
I do like the idea that a developer should provide a min required configuration to be able to use said component of the collector, which could be resolved with having a set template for components so that 3am adopter doesn't need to look through the weeds to understand how to use said component. 

I would say both a reasonable ways to progress forward.
