### ISSUE TITLE
[Receiver:elasticsearch] Support trace and [Exporter:elaticsearch] Support trace

### ISSUE THREAD

**Issue by Roronoa-Z3r0** [open-telemetry/opentelemetry-collector-contrib#6888]
**Is your feature request related to a problem? Please describe.**
I found that the elasticsearch receiver only supports the reception of metrics, but does not support trace and log. Elasticsearch's exporter only supports log, but does not support trace and metrics. 

**Describe the solution you'd like**
The elasticsearch receiver supports the reception of metrics and logs. The exporter of elasticsearch supports trace and metrics. I only want to store these data in es, and don’t want to use other components for indirect storage, such as jaeger and zipkin. 
**Describe alternatives you've considered**
Use jaeger as an exporter, and jaeger will write trace information into elasticsearch

**Comment by jpkrohling** [comment]
I don't think that's the intended goal for the receiver. From what I understand, it supports scraping metrics out of an Elasticsearch instance, not metrics/logs/traces stored in Elasticsearch. But code owners should be able to confirm that.

**Comment by BinaryFissionGames** [comment]
Yes, the (currently being developed) Elasticsearch receiver's purpose is to scrape metrics about an Elasticsearch cluster (e.g. cluster health, number of nodes, etc), not to retrieve data stored in it.

**Comment by jpkrohling** [comment]
I'm closing this issue, but if you think this should be reopened, let me know.

**Comment by JaredTan95** [comment]
`elasticsearch exporter` supported `trace` with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10180
