### ISSUE TITLE
Metadata autogenerate creates invalid name when metrics attributes has a period

### ISSUE THREAD

**Issue by JonathanWamsley** [open-telemetry/opentelemetry-collector-contrib#6896]
**Describe the bug**
Unable to successfully autogenerate valid metadata using the `//go:generate mdatagen --experimental-gen metadata.yaml` tag in a codegen.go file. An invalid string name is created when a metrics attributes has a period within it (i.e. attributes: [ http.method ]) in the metadata.yaml file.

**Steps to reproduce**
Add a metric with an attribute with a period in a metadata.yaml file. Include a codegen.go file with the `//go:generate mdatagen --experimental-gen metadata.yaml` tag. Run `make generate`
<img width="524" alt="Screen Shot 2021-12-17 at 1 58 20 PM" src="https://user-images.githubusercontent.com/13648435/146594526-ba6cbd2e-75e9-49a5-ab02-c93a4dc51854.png">

**What did you expect to see?**
No error.

**What did you see instead?**
An error 
<img width="1206" alt="Screen Shot 2021-12-17 at 1 54 38 PM" src="https://user-images.githubusercontent.com/13648435/146594055-fe8aaac0-f480-4b87-8faf-38ee5eedbcc8.png">
Which led me to examine the generated file.

A generated function with an invalid string name `http.methodAttributeValue` string
<img width="1097" alt="Screen Shot 2021-12-17 at 1 42 48 PM" src="https://user-images.githubusercontent.com/13648435/146592708-bc608022-975f-41ed-b0eb-5d7594bf9a59.png">

**What version did you use?**
Version: v0.41.0

**What config did you use?**
Config: metadata.yaml

**Environment**
MacOS

**Comment by JonathanWamsley** [comment]
@dmitryax I noticed this while responding to your comment on my pr https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6878#pullrequestreview-834841287

**Comment by dmitryax** [comment]
Hi @JonathanWamsley, thank for reporting. Nice catch! Let me fix the builder
