### ISSUE TITLE
Reduce the probability of a conflict for changelog entries

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6924]
The issue #6689 discussed adding a new check to require changelog entries for each PR. Some contributors expressed concern that the way it is implemented is fine for the core repository, but that it might generate a lot of conflicts in the contrib repository. This issue here is to track suggestions and a possible fix for it.

cc @codeboten, @bogdandrutu, @anuraaga, @mx-psi

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6093#pullrequestreview-794851722

**Comment by bogdandrutu** [comment]
I am fixing the CHANGELOG conflicts if that is the only thing left. If there are more conflicts is hard, especially the go[mod|sum].

**Comment by mx-psi** [comment]
In my experience a tool like the one mentioned here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6093#issuecomment-973940497 works well with a lot of contributors. We would probably want to write something custom to support Markdown but it shouldn't be super complex.

**Comment by mx-psi** [comment]
I think this can be closed after the introduction of chloggen, right?
