### ISSUE TITLE
Released MSIs have version 0.0.1 since v0.39.0

### ISSUE THREAD

**Issue by bkabrda** [open-telemetry/opentelemetry-collector-contrib#6925]
**Describe the bug**
It seems that since v0.39.0, the MSIs attached to the releases have version 0.0.1, see e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.39.0 - `otel-contrib-collector-0.0.1-amd64.msi`.

**Steps to reproduce**
Go to https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.39.0

**What did you expect to see?**
`otel-contrib-collector-0.39.0-amd64.msi`

**What did you see instead?**
`otel-contrib-collector-0.0.1-amd64.msi`

**What version did you use?**
v0.39.0

**What config did you use?**
N/A

**Environment**
N/A

**Additional context**
N/A

**Comment by jpkrohling** [comment]
Is it wrong only in the file name? In any case, we are moving the building of the assets to the -releases repository. The bad news is that MSI builds are not part of it yet.

@alolita, you mentioned earlier this year that you might have people available to help with that? I don't have the skills or the resources to work on MSI packages.

**Comment by bkabrda** [comment]
Yeah, I think the problem really is just the filename.

**Comment by jpkrohling** [comment]
I'll assign this to myself to work on fixing the file name, but it's possible that we'll just not have an MSI package for 0.42.0 anymore until someone helps by adding support for it at the -releases repo.

**Comment by jpkrohling** [comment]
I'm unassigning this from me, as I do not have the intention or resources to work on this.

**Comment by evan-bradley** [comment]
The Collector releases repo now handles building all executables and releasing an MSI installer is covered there by this issue: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/157. I'm closing this issue in favor of that one.
