### ISSUE TITLE
Carbon Receiver panics after life cycle tests are completed

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#6978]
**Describe the bug**
From what I understand, the Carbon receiver being tested within https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6974 doesn't not block on shutdown, meaning any error that uses host error reporter during the shutdown of the server will cause a panic outside the scope of the test.

**Steps to reproduce**
using https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6974 and enabling the life cycle tests, then it should be visible.

**What did you expect to see?**
The Carbon receiver should block on shutdown until the server is shutdown.

**What did you see instead?**
The server is unbounded by the shutdown operation, so any failed errors will cause the test to fail
**What version did you use?**

Version: latest

**What config did you use?**
NA

**Environment**
NA

**Comment by jpkrohling** [comment]
@pjanotti, you are listed as the code owner for this component. Would you be able to address this?
