### ISSUE TITLE
Zookeeper receiver panic with default config

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#6979]
**Describe the bug**
After testing all the receivers, using the default configuration for zookeeper, on shutdown the zookeeper receiver will panic due to a nil reference being used.

**Steps to reproduce**
Allow life cycle testing on this change https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6974

**What did you expect to see?**
The zookeeper receiver should return an error on start if there is no valid nodes to communicate with.

**What did you see instead?**
Allowing the life cycle tests, it will panic on shutdown with a nil reference.

**What version did you use?**
Version: latest

**What config did you use?**
Config: The default configuration

**Environment**
NA

**Comment by jpkrohling** [comment]
@djaglowski, as the code owner, could you please take a look at this one?

**Comment by djaglowski** [comment]
> What did you expect to see?
> The zookeeper receiver should return an error on start if there is no valid nodes to communicate with.

I've opened a PR to address the panic, but just a nit on this point - we don't want scrapers to error on start in such a scenario. It's fairly common that the monitored application is only unavailable for a short period of time, after which scraping will succeed. (e.g. collector and application processes started by host w/o concern for ordering, intermittent network issues, etc).
