### ISSUE TITLE
`deltatorateprocessor` ignore int64 counter.

### ISSUE THREAD

**Issue by hanjm** [open-telemetry/opentelemetry-collector-contrib#6981]
**Describe the bug**
The `detatorateprocessor` does not support int value type. always produce 0.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/deltatorateprocessor/processor.go#L77

**Steps to reproduce**
Client report a int64 counter. 

**What did you expect to see?**

**What did you see instead?**

**What version did you use?**
Version: 
0.41.0
**What config did you use?**
Config:

**Environment**
OS: centos
Compiler: go 1.17
**Additional context**

**Comment by jpkrohling** [comment]
cc @hossain-rayhan, as the original author of this component
