### ISSUE TITLE
Status of mysqlreceiver (and postgresqlreceiver)

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-collector-contrib#6983]
mysqlreceiver got intergration tests in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6916. Can it be added to internal/components/components.go? I've tried to enable it locally and everything seems to work fine. I could send a PR if that is the only problem...

Same applies to postgresqlreceiver.

**Comment by jpkrohling** [comment]
Could you take a look at the PRs that introduced them and see if they are complete/ready to be used? If the only thing missing is tying them there, go ahead. Don't forget to add it to the -releases repository as well, in the contrib distribution. Here's a similar PR there: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/50

**Comment by vmihailenco** [comment]
@jpkrohling I've tried to enable both receivers locally and everything rungs smoothly. postgresqlreceiver has only 6 metrics and half of them are not that useful, but it is still better than nothing I guess...

**Comment by vmihailenco** [comment]
Should be fully done once https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7079 is merged
