### ISSUE TITLE
Combine `awsemfexporter` and `awscloudwatchlogsexporter`

### ISSUE THREAD

**Issue by aateeqi** [open-telemetry/opentelemetry-collector-contrib#6991]
**Is your feature request related to a problem? Please describe.**

Currently, the `awscloudwatchlogsexporter` lacks some core functionality such as automatically creating log/group stream in cloudwatch. 
Based on
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4714
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4721

there's a demand for enhancing functionality for `awscloudwatchlogsexporter`. 

**Describe the solution you'd like**

This can be done by incrementally combining `awsemfexporter` and `awscloudwatchlogsexporter` into the `awscloudwatchexporter`. Not only will it enhance the logsexporter, but also would create more visibility around the emfexporter's role in pushing metrics to cloudwatch as discussed in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3697. 

The following outlines the steps intended to combine the 2 exporters, into 1 exporter (`awscloudwatchexporter`)

1) Extract the CW logs client from the EMF exporter https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6969
2) Use that client in the CW logs exporter https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6969
3) Use the extracted version of the client in the EMF exporter
4) Copy the EMF metrics handling to the CW exporter
5) Mark the EMF exporter as deprecated
6) Wait some appropriate period of time and Remove the EMF exporter

[Diagram for incremental steps to combine EMF and Cloudwatchlogs exporter](https://docs.google.com/document/d/1cIP1Xbwv_7gUrhuXFPLNniAq0ZdQhHZNqLiZU2RpZyY/edit?usp=sharing)

**Describe alternatives you've considered**

Another solution would involve having the 2 exporters completely independent and using separate clients and pushers. The downside of this would be much reused code and a confusing user experience that involves 2 exporters to cloudwatch

**Additional context**

**Comment by anuraaga** [comment]
I think the title is something like "Share logs pushing logic between emf and logs exporter". Combining would leave us with only one exporter component, which is not the goal
