### ISSUE TITLE
Lint fails on CI when passing locally for import group count

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector-contrib#6997]
In https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4688228948?check_suite_focus=true

Lint fails with this

```
processor/transformprocessor/config_test.go: Expected no more than 3 groups, got 4
processor/transformprocessor/factory_test.go: Import groups are not in the proper order: ["Std" "Third party" "Third party"]
processor/transformprocessor/internal/traces/processor.go: Expected no more than 3 groups, got 4
```

This is despite when I do this
```
cd processor/transformprocessor
make lint
```

it succeeds. More tediously, `make fmt` also isn't able to fix the trivial import grouping problem. Could something in lint / fmt be misconfigured to cause this situation?

**Comment by anuraaga** [comment]
I noticed another detail - it seems `make fmt` often actually introduces another import group when formatting, it seems to be more interested in order rather than the groups. I'm still not sure why `make lint` would pass locally in this situation though, more important to fix that, but ideally `make fmt` could do the grouping correctly too.

**Comment by jefchien** [comment]
So from what I understand, `goimports` doesn't combine the separate groups and then reorder/split them. It seems to run against each individual existing group. So, it will never decrease the number of groups that exist even if it should. There's an issue filed: https://github.com/golang/go/issues/20818

`make lint` is fine with the imports. It's `make impi` that fails. If you run `make impi` with the imports that were in that PR, it correctly fails.

**Comment by anuraaga** [comment]
Thanks @jefchien - I hadn't noticed the separate `make impi` command. Since linting is linting, should `make lint` also call the imports check?

**Comment by jefchien** [comment]
I think it should. People typically expect the `make lint` command to be comprehensive. The workflows will need to be slightly adjusted though.
