### ISSUE TITLE
Add ip address to host metadata

### ISSUE THREAD

**Issue by xp-1000** [open-telemetry/opentelemetry-collector-contrib#6998]
**Is your feature request related to a problem? Please describe.**
not a problem of course but it could be useful to collect the ip address as host metadata.
in my case, I write a program to manage instances in a load balancer.
to determine if a host is alive and should be in the pool, I check alerts on metrics retrieved by otel collector.
without this information I need create a mapping between ip and host name to known which ip to remove or add in pool depending on the host name present on the monitoring alert.

**Describe the solution you'd like**
We could add a 2 new metadata for the list of private ip addresses https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d8de7408185f94cbf4ac243ee909aa6b808a6c16/exporter/signalfxexporter/internal/hostmetadata/metadata.go
one for ipv4 and another one for ipv6 excluding the local addresses (like 127.0.0.1)

**Describe alternatives you've considered**
as described above we can still dispense of this information and let users do mapping between existing metadata (like host) and their ip address.

**Additional context**
perhaps there is a good reason to not already collect this information I don't know yet?

**Comment by xp-1000** [comment]
Hello @jpkrohling if you think this issue is relevant so I can try to make the PR

**Comment by jpkrohling** [comment]
I think it's definitely useful to have this information, but I have a few comments:

1. perhaps the process that provisions the collector should set this? In the config, you could use the attributes processor to add a new attribute, and the attribute value can be an env var, which is set by the process manager (Kubernetes, wrapper script called by systemd, ...)
2. if the collector is indeed the best place to get this info, how to determine whch IP to add when there are multiple ones available?
3. in any case, it should be opt-in, given that it would repeat the same info for all data points generated by the same node, which might not be desirable (although prior art exists in Jaeger)

**Comment by xp-1000** [comment]
Hello @jpkrohling 
thanks for your answer.

1. It is definitively a solution but the goal of this issue was to bring an automatic and easy way to achieve this.
2. sorry I was probably not clear enough in my first message. what I proposed was to bring the list of all ip addresses (except loopback which seems not relevant)
3. yes you are right, adding dimension could have undesirable side effect

do you have any advice to make an attempt ? 
For now, I am tempted to add these information in hostmetadata of signalfx exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d8de7408185f94cbf4ac243ee909aa6b808a6c16/exporter/signalfxexporter/internal/hostmetadata/metadata.go but I would prefer to try a more generic approach usable no matter the exporter. an idea ?

**Comment by jpkrohling** [comment]
@open-telemetry/collector-contrib-approvers, what do you think about this? I feel like this belongs to the instrumentation layer, not the collector, especially because the collector's IP typically won't be the same as the workload's, except for local agents/sidecars. Most of this can be achieved already with the attributes processor, but automatically detecting the IP address is missing, I believe.

**Comment by jpkrohling** [comment]
We haven't heard other users asking for this, but I'm willing to leave this open so folks can give their opinions.

**Comment by mx-psi** [comment]
Just a FYI, we recently fixed #24765 that adds support for gathering `host.ip` which relates to this. I am therefore going to re-close as completed since we actually did this :smile:
