### ISSUE TITLE
Build fails after merging Add AWS X-Ray Exporter (#41)

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#70]
See https://circleci.com/gh/open-telemetry/opentelemetry-collector-contrib/tree/master

**Comment by tigrannajaryan** [comment]
Reverting ` Add AWS X-Ray Exporter (#41)` fixes the build locally.

**Comment by tigrannajaryan** [comment]
This is blocking other work. Trying reverting.

**Comment by tigrannajaryan** [comment]
@kbrockhoff The commit 2b856d9c your authored broke master build (for some reason it passed PR build). I am reverting the commit and assigning this issue to you as the author of the component.

**Comment by tigrannajaryan** [comment]
For some reason Github doesn't allow me to assign this issue to you. Please have a look.

**Comment by tigrannajaryan** [comment]
Reverting fixed the build: https://circleci.com/gh/open-telemetry/opentelemetry-collector-contrib/239

**Comment by kbrockhoff** [comment]
I will look into this.
