### ISSUE TITLE
`prometheusreceiver`: Flaky test - TestStaleNaNs

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#7002]
Seen on #6630 (test run: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4701378458?check_suite_focus=true)

```
=== RUN   TestStaleNaNs/OpenCensus/target1
    metrics_receiver_helper_test.go:177: 
        	Error Trace:	metrics_receiver_helper_test.go:177
        	            				metrics_receiver_non_numerical_test.go:87
        	            				metrics_receiver_helper_test.go:603
        	Error:      	Not equal: 
        	            	expected: 10
        	            	actual  : 11
        	Test:       	TestStaleNaNs/OpenCensus/target1
        	Messages:   	want 10 total scrapes, but got 11
```

**Comment by jpkrohling** [comment]
cc @Aneurysm9 @dashpole

**Comment by jpkrohling** [comment]
Happened again here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4764766709?check_suite_focus=true

**Comment by Aneurysm9** [comment]
I think #7123 will stop this from being flaky, though I'm open to suggestions if anyone has better ideas for how to do it.

**Comment by jpkrohling** [comment]
Looks like it didn't :-/ I've just seen this in a couple of PRs, including this:

https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5096959006?check_suite_focus=true

**Comment by jpkrohling** [comment]
And again: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5096959006?check_suite_focus=true

**Comment by Aneurysm9** [comment]
Encore! https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7759
