### ISSUE TITLE
[build] docker stats receiver test fails 

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#7023]
The following error occurs in `TestDefaultReceivers` in the [collector repo](https://github.com/open-telemetry/opentelemetry-collector/runs/4707910613?check_suite_focus=true):

```
=== RUN   TestDefaultReceivers/docker_stats
     receivers_test.go:288: 
        	Error Trace:	receivers_test.go:288
        	            				receivers_test.go:254
        	Error:      	Received unexpected error:
        	            	Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.22/containers/json?filters=%7B%22status%22%3A%5B%22running%22%5D%7D&limit=0": dial unix /var/run/docker.sock: connect: permission denied
        	Test:       	TestDefaultReceivers/docker_stats
```

**Comment by jpkrohling** [comment]
@rmfitzpatrick, as the code owner, could you take a look?

**Comment by rmfitzpatrick** [comment]
Attempted to address this in https://github.com/open-telemetry/opentelemetry-collector/pull/4643 but potentially hit diminishing returns. Opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7056.

**Comment by prashant-shahi** [comment]
@jpkrohling Encountered a similar issue when running the `docker_stats` receiver in OtelCollector Agent running in a container.

I had to do a couple of things to resolve from my end:
- `chmod 666 /var/run/docker.sock`
- volume bind `/var/run/docker.sock` from host to container

**Comment by jpkrohling** [comment]
`chmod 666 /var/run/docker.sock` should never be part of the solution, at least not for a production setup. Perhaps you should just add the relevant user to the docker user group?

**Comment by prashant-shahi** [comment]
@jpkrohling Yes, agreed. I do understand the security implications of it and turned to it as last resort to get `docker_stats` to work inside of a container.

> Perhaps you should just add the relevant user to the docker user group

Just for confirmation, do you mean adding the currently logged-in user to the docker group using `usermod`?
If yes, I have already done that and it still returned the same permission error.
