### ISSUE TITLE
loadbalancingexporter: lazy DNS resolution at start

### ISSUE THREAD

**Issue by mapno** [open-telemetry/opentelemetry-collector-contrib#7051]
**Is your feature request related to a problem? Please describe.**

Context: In the [Grafana Agent](https://github.com/grafana/agent), we're layering two collectors for load balancing traces. The first layer uses the [loadbalancing](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/loadbalancingexporter) exporter to group all spans for the same trace in the second layer, that then does some processing.

There is an issue when running this set up in Kubernetes. We create a headless service for the first layer to be able to discover the second layer of collector. The problem happens when the loadbalancing exporter is unable to make the [first DNS resolution](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/resolver_dns.go#L79-L81), because pods are yet not registered in the headless service. But pods won't be able to be registered if the collectors are unable to start. And we've entered and infinite loop.

**Describe the solution you'd like**

We propose to add a lazy init config option that will allow the loadbalacing exporter to start while not resolving at the first try, but it'll keep doing periodic resolutions.

**Describe alternatives you've considered**

We've considered other alternatives but run into race conditions between collector pipelines and the headless service.

**Comment by jpkrohling** [comment]
One thing I had in mind since the beginning but was just looking for a concrete user is to implement a Kubernetes/etcd resolution. This way, we would watch for events related to the target deployment and update the ring when the available replicas changed.

Do you think this would be a better solution?

**Comment by Gentoli** [comment]
I had the same issue with a set of collector taking traces from services and doing load load balancing to themselves.

Here is a simple patch I had to allow the headless service to be empty https://github.com/Gentoli/opentelemetry-collector-contrib/commit/846f77ef016f308fb9876251622d93a3abbb88f9

**Comment by jpkrohling** [comment]
@Gentoli, that looks good! Could you send that as a PR? @mapno, would you be able to review/test it, once @Gentoli opens the PR?

**Comment by mapno** [comment]
Hey, sorry I missed the initial response! :( I'll be glad to review it and test it in our environments.

FWIW, since opening this issue, we've been using as a workaround `publishNotReadyAddresses=true` to set up the k8s service. This allows for pods to get registered before they're ready. This can result in exporting traces to pods that are not ready yet, which is not ideal. A more long term solution will be ideal.

**Comment by jpkrohling** [comment]
I'm closing this, as I believe this has been done as part of #7935
