### ISSUE TITLE
Automate go.mod `replace` statements

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#7055]
Currently the replace statements for dependencies local to this repository is done manually, it would be great to automate this, as it has caused pain in the past.

This was originally suggested in the discussion below:

@codeboten not sure if the replace statements were manually added, but would be great if the tool that updates the version for these local deps also add the replacements 🗡️

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7021#pullrequestreview-844090328_

**Comment by bogdandrutu** [comment]
@Aneurysm9 you own the `go modules` tool, can that be done automatically?

**Comment by Aneurysm9** [comment]
There is a separate tool used by the Go API/SDK that maintains replace directives everywhere, though it currently creates replaces for all modules in all modules, regardless whether they're actually used.  So, yes, it's possible and there's a tool that can help, but it could use some improvement.

**Comment by alolita** [comment]
@Aneurysm9 do you need additional help on making these improvements?

**Comment by Aneurysm9** [comment]
Probably.  I know @bryan-aguilar had expressed an interest in learning more about Go and this might be a good first project.

**Comment by bryan-aguilar** [comment]
`make crosslink` is not available to automatically insert replace statements. I think this can be closed now @codeboten.

**Comment by jpkrohling** [comment]
"is not", or "is now"?

**Comment by bryan-aguilar** [comment]
Oops! Fixed! `is now`. I think it's time for a new keyboard! ha.

**Comment by codeboten** [comment]
Can this issue remain open until crosslink is for the entire repo? Ideally this would be run in the CI as well to notify us when someone has missed replaced lines

**Comment by bryan-aguilar** [comment]
Definitely, sounds good to me!
