### ISSUE TITLE
[tests] TestStaleNaNs failing

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#7070]
Failing tests, see https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4731466863?check_suite_focus=true

```
 --- FAIL: TestStaleNaNs (12.16s)
    --- FAIL: TestStaleNaNs/OpenCensus (6.10s)
        --- FAIL: TestStaleNaNs/OpenCensus/target1 (0.00s)
```

**Comment by codeboten** [comment]
@Aneurysm9 any chance this is related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7043? I'm not sure why the tests didn't fail during the CI checks for the PR though.

**Comment by Aneurysm9** [comment]
I don't think so.  Seems to be the same issue as https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7002.

**Comment by codeboten** [comment]
Ah, i missed that one, thanks!
