### ISSUE TITLE
Add docker image for tracegen tool

### ISSUE THREAD

**Issue by JamesGuthrie** [open-telemetry/opentelemetry-collector-contrib#7080]
**Is your feature request related to a problem? Please describe.**

It would be greatly convenient if you could package tracegen as a docker image. I know that I can make one myself, but I don't really want to do that.

**Comment by jpkrohling** [comment]
Would you like to send us a PR with a proposal?

**Comment by jpkrohling** [comment]
We can publish it to GitHub's container registry, which should be easier to integrate.
