### ISSUE TITLE
[processor/spanmetrics] Inaccurate timestamps on metrics. 

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-collector-contrib#7128]
**Describe the bug**
The processor uses the time since it started up for the start time of all metrics, and this is not very accurate. For delta metrics it is particularly inaccurate. For example here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.42.0/processor/spanmetricsprocessor/processor.go#L125

**What did you expect to see?**
Each metric should probably keep track of the earliest and latest corresponding timestamp, for more accurate results. Or, any feasible way of giving more accurate time results. 

**What version did you use?**
Version: `v0.42.0`

**Comment by jamesmoessis** [comment]
I am happy to work on this in a week or two's time.

**Comment by chenzhihao** [comment]
Can I ask for clarification for a delta temporality timestamps case?
 
1. Let's say the processor emits two metrics `mts_a` and `mts_b` at the time point`t0`. The `StartTimeUnixNano` and `TimeUnixNano` time range for both of them is `(processor_start_time, t0]`.
2. The processor emits `mts_b` at `t1`, `(t0, t1]` is the time range.
3. The processor emits `mts_a` at `t2`. Should its time range be  `(t1, t2]` or `(t0, t2]`?

**Comment by balintzs** [comment]
We are seeing the same issue. We expect metrics with delta temporality to move the start timestamp forward as metrics are emitted. However, when we send our metrics to New Relic, they are being logged at the timestamp of when the collector started at `t0` (see [docs](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics/#start-time)).

According to [otel specs](https://opentelemetry.io/docs/reference/specification/metrics/datamodel/#sums), in your example `mts_a` at `t2` should emit the latter time range `(t1, t2]`.

So, as far as I understand, this leaves us with two issues:
1. the bug that keeps `StartTimeUnixNano` at `t0` for delta temporality, and
2. the issue that we do not emit metrics at consistent time intervals

cc @jack-berg @danielgblanco

**Comment by balintzs** [comment]
@albertteoh, could you help out on this one as well?

**Comment by danelson** [comment]
We are also seeing this in v0.77.0. Same exact use case as @balintzs. Is anyone currently working on this issue?

**Comment by ajsaclayan** [comment]
This has since been released in the latest version @jamesmoessis
Is this good to close?

**Comment by jamesmoessis** [comment]
@ajsaclayan I haven't used this processor in a long time, but I believe you if it's fixed. So it's probably all good to close.
