### ISSUE TITLE
Migrate kubeletstatsreceiver to the new Metrics Builder

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#7143]

**Comment by TylerHelmuth** [comment]
I can work on this

**Comment by TylerHelmuth** [comment]
This receiver is currently setting several different scopes for the metrics it collects.

- [Nodes](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e13ed6d60fe4914b609e74512944ce63ffa578c3/receiver/kubeletstatsreceiver/internal/kubelet/accumulator.go#L70)
- [Pods](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e13ed6d60fe4914b609e74512944ce63ffa578c3/receiver/kubeletstatsreceiver/internal/kubelet/accumulator.go#L93)
- [Container](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e13ed6d60fe4914b609e74512944ce63ffa578c3/receiver/kubeletstatsreceiver/internal/kubelet/accumulator.go#L123)
- [Volume](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e13ed6d60fe4914b609e74512944ce63ffa578c3/receiver/kubeletstatsreceiver/internal/kubelet/accumulator.go#L151)

If I am interpreting the v2 MetricsBuilder correctly I do not see a way to set the scope of recorded data points.  It seems to hardcode the scope to "otelcol/kubeletstatsreceiver". 

I think to convert this receiver we are going to need to allow scope override, either programmatically or via the metadata.yaml.

**Comment by TylerHelmuth** [comment]
@dmitryax what do you think?

**Comment by dmitryax** [comment]
Are you sure they split by scopes? I looked at the code and looks like they split on resource level which is supported by the new metrics builder with `EmitForResource` function

**Comment by dmitryax** [comment]
Oh you saying that Scope name is different. I think we should apply the same scope naming in this scraper as done for all other scrapers. This should be done separately. I see it's tracked in this issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8362

**Comment by dmitryax** [comment]
Created a ticket that should be handled before this PR for cleaner git history https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9399

**Comment by TylerHelmuth** [comment]
The code also currently [sets the names of the metrics differently](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f5f05d5ca4bacef9573fd173a0eafb020f91e3ba/receiver/kubeletstatsreceiver/internal/kubelet/utils.go#L26) than the new metrics builder by including a prefix.  For example, the CPU for pods is being set as `k8s.pod.cpu.utilization` but the metrics builder's generated code sets the metric name to `cpu.utilization`.  Are we able to set it to `k8s.pod.cpu.utilization` during `EmitForResource` or is the name change to `cpu.utilization` ok?

**Comment by dmitryax** [comment]
We need to change https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f5f05d5ca4bacef9573fd173a0eafb020f91e3ba/receiver/kubeletstatsreceiver/metadata.yaml to contain all the metrics exactly how they are emitted. We also have [the metrics documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f5f05d5ca4bacef9573fd173a0eafb020f91e3ba/receiver/kubeletstatsreceiver/documentation.md) generated from it which is currently misleading

So I think we need to make it in two steps. 
1. Update metadata.yaml to list all the metrics and refactor existing code based on it.
2. Migrate to the new metrics builder.

**Comment by dmitryax** [comment]
This one appeared to be more involved than others. Let me know if you don't want to dig into that. I can also handle it soon

**Comment by TylerHelmuth** [comment]
I'm using these issues to help me wrap my head around OTEL metrics and pdata, so I'll stick with it for now. As long as you're ok with all my questions lol

**Comment by TylerHelmuth** [comment]
With the existing metadata.yaml now updated to be more explicit, I will get back to updating to the v2 metrics.
