### ISSUE TITLE
[prometheusreceiver] Update Prometheus libraries to latest versions in prometheus receivers.

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector-contrib#7162]
**Is your feature request related to a problem? Please describe.**

The current prometheus receiver imports a very old version of prometheus libraries ( `github.com/prometheus/prometheus v1.8.2-0.20210621150501-ff58416a0b02` )  and many important features (some features include tls configurations, https2 support) and bug fixes has gone into them ever since. We need to update to latest version  (2.32.1 / 2021-12-17) to pick those changes if possible.

**Comment by Aneurysm9** [comment]
Can be fixed by #7115.

**Comment by pavankrish123** [comment]
Yes! Thank you!!!
