### ISSUE TITLE
[spanmetricsprocessor] Ability to either statefully route or aggregate span metrics across collectors

### ISSUE THREAD

**Issue by vjsamuel** [open-telemetry/opentelemetry-collector-contrib#7171]
**Is your feature request related to a problem? Please describe.**
The span metrics processor along with its examples provide documentation on how we can generate RED metrics and expose it against a prometheus endpoint that can be shipped to Prometheus like systems via remote write exporter. Based on high level experiments what we have observed is that if we are doing RED metric generation at a service, operation level, given that the same service operation name combination can go into several collectors. This means that each collector's prometheus endpoint would have the same set of label combinations. To be able to differentiate metrics coming in, things like `instance` or `collector_host` could be used as Prometheus would only append the first series and drop the rest when the same labels + timestamp combination is seen. 

**Describe the solution you'd like**
We would like to be able to either aggregate at the collector level itself or make sure that all service+operations combination are handled always by the same collector. This will ensure that when ingesting to Prometheus, the data is accurate.

**Describe alternatives you've considered**
adding a `collector_host` dimension as part of the `dimensions` setting of spanmetricsprocessor. this however will multiply the cardinality by N times where N is the total number of collector instances. this also needs the collector to run as a statefulset so that the host name doesnt churn across restarts. 

**Additional context**

**Comment by jpkrohling** [comment]
cc @albertteoh

**Comment by albertteoh** [comment]
Thanks @vjsamuel, yes, this is definitely something that's been on my mind for a while.

> adding a collector_host dimension as part of the dimensions setting of spanmetricsprocessor. this however will multiply the cardinality by N times where N is the total number of collector instances. this also needs the collector to run as a statefulset so that the host name doesnt churn across restarts.

I actually think this is worth exploring and having a discussion over; the main advantage being its simplicity in implementation and configuration (it could just be a simple "addHostAttribute/Dimension" boolean config). As you rightly point out, it does come at a cost of multiplying the number of metrics by N collector instances, but at least it's bound by a relatively finite population of values if deployed as a stateful set, and we leverage the metrics query engine to perform the aggregation. The other downside, also, is the per-collector-host metrics have little value; if there was some value in them, there might be a stronger case to adopt this approach.

> We would like to be able to either aggregate at the collector level itself or make sure that all service+operations combination are handled always by the same collector. This will ensure that when ingesting to Prometheus, the data is accurate.

I think the `tailsamplingprocessor` may also share the same problem in that it also needs spans belonging to the same trace to be routed to the same collector instance. @jpkrohling, are you able to share any insights in this?

Another alternative that I am yet to try is using [Prometheus' Federation feature](https://prometheus.io/docs/prometheus/latest/federation/), which, if I understand correctly, should help aggregate the same metric dimensions together. That's based on what little I've read so far, so I could be wrong. 😄

**Comment by jpkrohling** [comment]
Indeed, and for that purpose, we have the load balancing exporter, which routes spans to backing instances based on their trace IDs: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/loadbalancingexporter#trace-id-aware-load-balancing-exporter

**Comment by albertteoh** [comment]
Great, thanks for confirming @vjsamuel 👍🏼 Are you able to close this ticket please?
