### ISSUE TITLE
Misleading source of the 0.42.0 container image

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-collector-contrib#7184]
I have list quite a lot of time to understand why executing `make docker-otelcontribcol` created something different than I got when pulling `otel/opentelemetry-collector-contrib:0.42.0`. 

I find it misleading that the `Dockerfile` and Make targets still exist in this repo while it looks like starting from `0.42.0` the artifacts are released via https://github.com/open-telemetry/opentelemetry-collector-releases.

At last, there is no information about https://github.com/open-telemetry/opentelemetry-collector-releases in this repository (e.g. in `CONTRIBUTING.md`). I have found that is documented [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#producing-the-artifacts) but I failed to find any hyperlinks that would lead there from this repository.

**Comment by jpkrohling** [comment]
Thank you for pointing this out. We are still in process of removing the parts that are not necessary anymore in contrib after we started creating the distribution as part of the -releases repository. Would you be interested in helping us by removing the mentioned resources, as well as improving our documentation?

**Comment by pellared** [comment]
> Would you be interested in helping us by removing the mentioned resources, as well as improving our documentation?

Sorry, but I have no time to work on it. However, thank you for asking.

**Comment by jpkrohling** [comment]
@vvydier, would you be interested in helping out with this one here?

**Comment by vvydier** [comment]
yes, I can take this one. Thanks @jpkrohling !
From the issue opened by @pellared, it seems like the latest build output of otel-collector using `make docker-otelcontribcol` is not matching with the version number in the release notes. Any time, there is a new release we are not updating the release notes or doc links appropriately?

**Comment by jpkrohling** [comment]
That might be the cause, but I'm not quite sure. Can you do an investigation and check this is the case?

**Comment by jpkrohling** [comment]
I'm closing this, as I don't think this is relevant anymore.
