### ISSUE TITLE
Makefile.Common contains no rule for "checkdoc"

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector-contrib#7238]
**Describe the bug**
When running `make common` from [Makefile.common](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/Makefile.Common#L40-L41) there is a rule called `checkdoc` though this rule does not exist in the `Makefile.Common` but rather in root [Makefile](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/Makefile#L274-L276). I'm not sure if the intention is for the `Makefile.Common` to also have it or if it should be removed.

**Steps to reproduce**
Run `make common`

**What did you expect to see?**
The make command work.

**What did you see instead?**

```shell
> make common
Check License finished successfully
make: *** No rule to make target `checkdoc', needed by `common'.  Stop.
```

**What version did you use?**
4ddc7434b

**What config did you use?**
N/A

**Environment**
Mac OS

**Additional context**
N/A

**Comment by atoulme** [comment]
I cannot reproduce the issue anymore. Closing.
