### ISSUE TITLE
ec2 resourcedetectionprocessor: Improve detection logging for debugging

### ISSUE THREAD

**Issue by jvoravong** [open-telemetry/opentelemetry-collector-contrib#7293]
**Is your feature request related to a problem? Please describe.**
The current ec2 resource detection code uses the `available` method to check if the metadata server is available. The code does not log any messages when the metadata server is unavailable, this can make it hard for a user to debug why the metadata server is missing.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b37ee4c1b1b6d3515625a107f39a855517f3b2b6/processor/resourcedetectionprocessor/internal/aws/ec2/ec2.go#L61

**Describe the solution you'd like**
The ec2 resource detection logic should be refactored to be similar to the azure resource detection code. The ec2 code should try to connect to the metadata server and log any encountered error as a debug message.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b37ee4c1b1b6d3515625a107f39a855517f3b2b6/processor/resourcedetectionprocessor/internal/azure/azure.go#L55

**Additional context**
This issue is being reported by a user at my company.

**Comment by jpkrohling** [comment]
cc @jrcamp @pmm-sumo @anuraaga @dashpole

**Comment by jefchien** [comment]
@alolita can I take a look?

**Comment by sethAmazon** [comment]
@jefchien can this be closed?

**Comment by jefchien** [comment]
It can.
