### ISSUE TITLE
MSI check failure is difficult to troubleshoot

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#7302]
Currently, build failures for the MSI check don't give developers any idea as to what is causing the problem. See example: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4888218835?check_suite_focus=true

The failure was caused by an error on startup from the collector, this information would have greatly helped troubleshoot the problem. My ask of this issue is to somehow collect more information from this step in the build, if at all possible. At the very least msiexec could be called with logging enabled.

**Comment by jpkrohling** [comment]
Should the packaging steps be removed from the CI of this repository? We do not produce MSI/deb/rpm as part of this anymore.

**Comment by codeboten** [comment]
@jpkrohling if i recall correctly, the problem was caused by a change in the core collector's parsing of command line args on windows. The problem that should really be addressed is that the core collector repo doesn't run tests that would show the problem before it is released. There is an issue to track adding better windows testing in the core: https://github.com/open-telemetry/opentelemetry-collector/issues/6455

I don't know if we need this issue anymore, something tells me there should be at least some sanity checks for the contrib components on windows.

**Comment by jpkrohling** [comment]
Alright, I'm closing this then. We can reopen if we still have problems.
