### ISSUE TITLE
[receiver/jmx] Add support for Additional Jars in Classpath

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector-contrib#7358]
**Is your feature request related to a problem? Please describe.**

Add support for adding additional jars to the classpath when running the JMX Metric Gatherer. My company is working on adding an Apache Wildfly JMX Metric Receiver to the java-contrib repo and we found in order to do so you need to include a Wildfly (jboss) specific jar in the class path. Details in JBoss docs [here](https://docs.jboss.org/author/display/WFLY9/JMX%20subsystem%20configuration.html).

**Describe the solution you'd like**

Add an optional field to the configuration to specify multiple other jars to add to the class path.

When the JMX receiver constructs the java subprocess command using the `-cp` flag rather than `-jar` in order to specify multiple jars in the class path.

The basic command would now look something like this

```shell
java -Dorg.slf4j.simpleLogger.defaultLogLevel=info -cp "/opt/opentelemetry-java-contrib-jmx-metrics.jar" io.opentelemetry.contrib.jmxmetrics.JmxMetrics -config -
```

*NOTE*: The full name of the Java class containing the main function will needed to be included. This should likely be hardcoded for now as I can't see a user actually needing that level of configuration.

**Describe alternatives you've considered**

Considered dynamically loading the JARs into the classpath at runtime for the JMX Metric Gatherer JAR but this is much more complex than doing so at launch time.

**Additional context**

The inspiration for this pattern comes from how DataDog does something similar in their JMX collector [config](https://docs.datadoghq.com/integrations/java/?tab=host#configuration-options).

I have code ready to submit in a PR but I would like to hear any discussion on the proposal first before submitting.

**Comment by cpheps** [comment]
@rmfitzpatrick Looks like you're the owner of the receiver do you mind taking a look at the proposal?

**Comment by rmfitzpatrick** [comment]
This sounds useful overall and the only concerns I'd have would be slightly security minded. Would setting `CLASSPATH` be acceptable over `-cp`? If not, there'd need to be some assurances that arbitrary execution isn't possible (along the lines of https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8dbbf09ca8056e215b06728b0a324913af7379dd/receiver/jmxreceiver/integration_test.go#L176).

**Comment by cpheps** [comment]
You mean setting the CLASSPATH env on the subprocess? That should be fine. I think the same config will work we'll just create the ENV on the subprocess config rather than injecting it into the Java command.
