### ISSUE TITLE
Set the log level for awsemfexporter

### ISSUE THREAD

**Issue by harri-omarBish** [open-telemetry/opentelemetry-collector-contrib#7390]
**Is your feature request related to a problem? Please describe.**
currently, the default logging level is set to info. and I want to change the log level to warn in a production environment. and I wasn't able to find anything in the documentation that mentions how I can do this. 

**Describe the solution you'd like**
if there can be a parameter in the awsemf exporter that can help in setting the log level that will be great. and if this feature already exists it will be great to add it to the README as a note on how to achieve such a thing.

**Comment by jpkrohling** [comment]
It's the other way around: instead of changing the level as part of the individual component, you change the level of the collector. If you have the collector's log-level set to INFO, you should get all the INFO log entries emitted by this component.

**Comment by jpkrohling** [comment]
I'm closing this, but feel free to reopen if you think you need more information.
