### ISSUE TITLE
Provide a "SED-like" mechanism to "find and replace" characters in a log record. 

### ISSUE THREAD

**Issue by matthewmodestino** [open-telemetry/opentelemetry-collector-contrib#7396]
**Is your feature request related to a problem? Please describe.**

As an OTel native logging user, I need a way to "find and replace" characters that may exist in the original log record that I don't want/need in the logging backend. This can be useful to anonymize info, but also to make log records more usable in logging backends. 

My current example is removing ANSI colour codes from my log files... 

```
[2022-01-04 01:51:50] [36mINFO[39m "GET /ads.txt" [36m301[39m 10ms
```

**Describe the solution you'd like**

I want to define a SED command processor to find and replace the ANSI colour codes, or any other characters in the log record, as I see fit. Something like:

```
SEDCMD-removecolorcodes = s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?
```

**Describe alternatives you've considered**

I looked through existing OTel processors but I only see REGEX based ones, and none that make it easy to achieve "find and replace" in existing log pipelines

**Additional context**

Sometimes kubernetes or application logs will use colour codes to make pretty printing when viewed in a terminal, or may include strings that need to be anonymized or replaced to make the log more usable by the user in the logging backend.  

![image](https://user-images.githubusercontent.com/31549209/151220075-f3f427b9-a1a5-4c29-8289-17c8ead571f6.png)

**Comment by jpkrohling** [comment]
@bogdandrutu, @anuraaga, is this something the transform processor should take care of?

**Comment by matthewmodestino** [comment]
Bump. 

Any progress on transform processor?

Would be really handy to have the `if` style expressions that the log collection `operators` support.

**Comment by anuraaga** [comment]
Hi @jpkrohling sorry for not responding to the question - yes replacement, possibly with SED syntax or something equivalent, is a function we'd want in the transform processor.

@matthewmodestino Sorry for the delay, just sent #8972 with a big step in being able to add logs support

**Comment by matthewmodestino** [comment]
Sweet!

In the logs signal, we would likely need to apply this conditionally,ie. based on resource or attribute values. Looking forward to seeing how this turns out!

**Comment by matthewmodestino** [comment]
Bump. Still need this.

**Comment by jpkrohling** [comment]
@kovrus, @djaglowski, is this doable today with OTTL?

**Comment by TylerHelmuth** [comment]
@matthewmodestino checkout the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) and the function [replace_pattern](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#replace_pattern). Does that fit your needs?

**Comment by kovrus** [comment]
👍 `replace_pattern(body, regex, "")` probably can address that.

**Comment by matthewmodestino** [comment]
Will give it a shot! Thanks!

**Comment by TylerHelmuth** [comment]
@matthewmodestino I'm going to close this based on the transform processor's capabilities. Please ping me if you think it should stay open.

**Comment by matthewmodestino** [comment]
Sounds good, been meaning to circle back and test. Will hit you  up if need be. Thanks!
