### ISSUE TITLE
ec2 resourcedetectionprocessor: Support configuring the http client used

### ISSUE THREAD

**Issue by jvoravong** [open-telemetry/opentelemetry-collector-contrib#7397]
**Is your feature request related to a problem? Please describe.**
The resource detection processors don't support configuring the http client they use while other exporters and receivers do. This is an issue when you want to configure settings like the http client timeout for processors.

**Describe the solution you'd like**
In the long run, we should make all the resource detection processor http clients configurable by the user. We should have the http clients switch to using the [opentelemetry HTTPClientSettings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/confighttp.go#L36 ) and support the user defining these HTTPClientSettings via a config file.

Here is an example of how this is done in the rabbitmq receiver.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/595b1dd55784e3ef177ab4af748258b88d5fde19/receiver/rabbitmqreceiver/config.go#L42
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/595b1dd55784e3ef177ab4af748258b88d5fde19/receiver/rabbitmqreceiver/client.go#L53

For the scope of this ticket, I suggest only making the ec2 resource detection processor http configurable and file new tickets for the others processors that need to be updated.

**Describe alternatives you've considered**
I haven't come up with any other ways.

**Additional context**
- Some things to consider. The ecs resource detector already uses some AWS utils to setup http clients, perhaps AWS code owners would want to refactor these utils to work with the ec2 detector. This may or may not be worth doing.
- I have a customer at my company needing/requesting this for a support case.
- I (jvoravong) am available to work on this ticket.

**Comment by sethAmazon** [comment]
@Aneurysm9 @anuraaga would this config be added to the resource detection config or just the ec2 config?

**Comment by sethAmazon** [comment]
@alolita can you please assign this ticket to me

**Comment by Aneurysm9** [comment]
> would this config be added to the resource detection config or just the ec2 config?

This should probably be added to the `resourcedetectionprocessor.Config` struct.  Adding it here, even if it is initially only used in the EC2 detector, prevents a situation where we'd need to break user configs to move it later once other detector implementations used it.  It'll also lay some of the groundwork, simplifying later implementations.
