### ISSUE TITLE
Dive deep adot collector state when CPU throttled

### ISSUE THREAD

**Issue by yimipeng** [open-telemetry/opentelemetry-collector-contrib#7398]
Hi OpenTelemetry community, 

Appreciate your time in advance. This is from a customer of opentelemetry. Reach out here per @sethAmazon suggestion to dive deep one AWS Distro For OpenTelemetry resource consumption logic:

if CPU is throttled in instance, what's the expected adot collector status? Will it enter in idle or other state. And what's the expected resource consumption(Mem etc.) from adot collector in that situation. 
Want to understand the logic there because this is a critical use case for one of our product. 

Happy to chat and learn more from your experience and knowledge. Appreciate all the valuable inputs in advance. 

Thanks.

**Comment by Aneurysm9** [comment]
@yimipeng this question applies to the OTel Collector generally, correct?  I'm not sure that there would be anything specific to the ADOT Collector distribution with regard to behavior under CPU-limited conditions.

**Comment by sethAmazon** [comment]
@Aneurysm9 yes this the otel collector generally not the adot distribution

**Comment by yimipeng** [comment]
May I ask is there any update? It has been there for a while. Appreciate inputs in advance. 😊

**Comment by sethAmazon** [comment]
You want want to post the question to https://github.com/open-telemetry/opentelemetry-collector also

**Comment by yimipeng** [comment]
Done. https://github.com/open-telemetry/opentelemetry-collector/issues/4812
