### ISSUE TITLE
routingprocessor: add an option to drop the attribute used for routing

### ISSUE THREAD

**Issue by pmalek-sumo** [open-telemetry/opentelemetry-collector-contrib#7407]
**Is your feature request related to a problem? Please describe.**

Sometimes, due to routingprocessor's limitations (like routing only on one key) a routing key has to be created specifically for this issue.
Because of that users might want to drop this from being sent through the exporter to prevent having "polluted" data in the system that consumes data.
Since routingprocessor has to be placed as a final processor in the pipeline user cannot do any processing after the routing has been done.

**Describe the solution you'd like**

Add an option to drop the key that's used for routing (perhaps we can think at the same time of using more than one key for routing and account for that in the design).

**Describe alternatives you've considered**

N/A - can't do any processing post routing.

**Comment by jpkrohling** [comment]
I think this makes sense, but for the future, the cleanest would be for us to support getting attributes from the context. We should now have all the pieces in place for that.

**Comment by pmalek-sumo** [comment]
I haven't personally used context since most of the routing logic I've needed to write was based on resource attributes (sometimes record attributes but I could leverage [`groupbyattrsprocessor`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor) to work around that)

Is there a mechanism to bridge context with resource attributes somehow that I'm not aware of?

**Comment by jpkrohling** [comment]
No, sorry, I was under the impression that you added things to the resources because of the routing mechanism. In that case, you could have sent an HTTP header instead, which is only sent once per connection. Those headers may now end up in the context as part of `client.Info`, and we should be able to get access to that in the routing processor.

**Comment by pmalek-sumo** [comment]
> No, sorry, I was under the impression that you added things to the resources because of the routing mechanism.

That's exactly what I meant and what I am using as of now. Hence the need to remove it in routingprocessor :)

**Comment by jpkrohling** [comment]
Then you can certainly make use of the feature I mentioned in the future :-) Once we have support for getting info from the context, you can add HTTP headers to your exporters instead of adding resource attributes.

**Comment by pmalek-sumo** [comment]
How far in the future that is :excited: ? And do we want to wait for that or work on my suggested feature?

**Comment by jpkrohling** [comment]
> How far in the future that is :excited: ?

Apparently, we had that in mind already: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4ccaabd802fa420684884b78716e43f099251f12/processor/routingprocessor/extract.go#L54-L77

We might just need to change this to use the `client.Info` instead, which does include gRPC in addition to HTTP metadata.

> And do we want to wait for that or work on my suggested feature?

If you are willing to change your instrumented clients to use this new feature, I would just use the context. If it makes your life easier to have the removal of the attribute now, migrating to the HTTP headers in the future, I'm also OK with that.

> Is there a tracking issue?

No. If you decide that you want to follow the HTTP headers path for now, we could use this one here to track that.

**Comment by pmalek-sumo** [comment]
Hm we might be talking about a different use case. What I'm looking for is to route logs/metrics based on the attributes added by k8s processor. So there's really no notion of HTTP headers in my setup but only resource attributes.

**Comment by jpkrohling** [comment]
> added by k8s processor

**Comment by william-tran** [comment]
>Is there a mechanism to bridge context with resource attributes somehow that I'm not aware of?

**Comment by william-tran** [comment]
On second thought, the approach gave above feels like a misuse of the Resource concept. A Resource represents the thing that generated the spans, and I want those spans of the same resource to be routed to different exporters, which means creating a Resource for each destination, and this artificial resource no longer represents the thing that generated the spans.

**Comment by pmalek-sumo** [comment]
> Looking at the config, it's unfortunate that `from_attribute` only takes from headers and not resource attributes

Well I'm not sure if you've seen that but you can do just that with `attribute_source: resource`. For that matter we do that in [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/a7f9d26ba535b3ddd5f04ab346103ce9cf7d6adc/deploy/helm/sumologic/values.yaml#L3635-L3677) 

> On second thought, the approach gave above feels like a misuse of the Resource concept. A Resource represents the thing that generated the spans, and I want those spans of the same resource to be routed to different exporters, which means creating a Resource for each destination, and this artificial resource no longer represents the thing that generated the spans.

I do agree on that.

**Comment by jpkrohling** [comment]
> A Resource represents the thing that generated the spans

You might have the same application code deployed in two different settings, one for each tenant. The data points generated by this application are the same, except for a `tenant` set as a resource attribute. It does make sense to me to route data based on the `tenant` resource attribute.

**Comment by william-tran** [comment]
>Well I'm not sure if you've seen that but you can do just that with attribute_source: resource

Whoops my mistake, I was looking at a private fork of opentelemetry-collector-contrib which is a bit behind.

**Comment by william-tran** [comment]
@pmalek-sumo thanks for the feature you contributed to enable the use of resource attributes directly. I'll see how far I get with it for my use QoS use case described in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7561. If you have any feedback on that feature I'd appreciate it, it could be a more direct approach for your routing use case as well, without using resource attributes.

**Comment by pmalek-sumo** [comment]
Hmm I believe this is a slightly different problem as I wasn't really aiming at tailsampling or QoS (but maybe I'm mistaken).

In general I'd like to see more flexible routing to be available for the users. This issue tracks one of the pain points of routingprocessor (i.e. leaving stuff behind - like routing keys that were solely used for routing).

**Comment by william-tran** [comment]
@pmalek-sumo If you'd like to continue the conversation about the need for more flexible routing, take a look at what I've been able to get with current functionality in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7561#issuecomment-1032795704. Maybe there's a use case that truly requires a more flexible mechanism, but after playing around with these configs I'm not seeing one yet.

**Comment by pmalek-sumo** [comment]
> @pmalek-sumo If you'd like to continue the conversation about the need for more flexible routing, take a look at what I've been able to get with current functionality in [#7561 (comment)](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7561#issuecomment-1032795704). Maybe there's a use case that truly requires a more flexible mechanism, but after playing around with these configs I'm not seeing one yet.

So that approach seems to be something similar to what we're using in our setup but as I said it seems to be a different problem.

Thanks for letting me know though.

**Comment by pmalek-sumo** [comment]
@jpkrohling Just wanted to ping this. Would you accept a PR adding this feature?

**Comment by jpkrohling** [comment]
Yes

**Comment by pmalek-sumo** [comment]
@jpkrohling Here's the PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8990

**Comment by TylerHelmuth** [comment]
@open-telemetry/collector-contrib-approvers can this issue be closed?
