### ISSUE TITLE
AWS X-Ray Exporter PutTraceSegmentsInput error response is being eaten

### ISSUE THREAD

**Issue by AustinWentz** [open-telemetry/opentelemetry-collector-contrib#7508]
**Describe the bug**
[The debug logging](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsxrayexporter/awsxray.go#L69) for request and response is not giving me anything in the Collector logs.

This is making it incredibly hard for me to debug why the PutTraceSegmentsInput API call is failing when trying to export my traces.

**Steps to reproduce**
1) Incorrectly configure AWS credentials or some other magic to make the PutTraceSegmentsInput API call fail
2) Check log file

**What did you expect to see?**
{2022-01-31 23:36:41.356506158 +0000 UTC m=+2091.033582527, Level:debug, Caller:github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.39.0/awsxray.go:81, Message:response error **<SOME_ERROR_MESSAGE>**, Stack: **<SOME_STACK_TRACE>**}

{2022-01-31 23:36:42.43455569 +0000 UTC m=+3036.111632168, Level:debug, Caller:github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.39.0/awsxray.go:85, Message:response: {
**<SOME_ERROR_MESSAGE>**,
}

**What did you see instead?**
{2022-01-31 23:36:41.356506158 +0000 UTC m=+2091.033582527, Level:debug, Caller:github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.39.0/awsxray.go:81, Message:response error, Stack:}

{2022-01-31 23:36:42.43455569 +0000 UTC m=+3036.111632168, Level:debug, Caller:github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.39.0/awsxray.go:85, Message:response: {

}
**What version did you use?**
Version: v0.15.1

**What config did you use?**
Config: default

**Environment**
OS: Amazon Linux 2
Compiler(if manually compiled): N/A

**Additional context**
I am trying to setup this outside of a Docker container to export traces to AWS

**Comment by Aneurysm9** [comment]
This looks like the custom logging from the ADOT collector.  There was an error in the configuration of that logging that resulted in losing additional context such as the error information you're looking for here.  That was fixed in https://github.com/aws-observability/aws-otel-collector/pull/849 and will be in the `v0.16.0` release that is currently being prepared.

In the interim, the logs output to `STDOUT` should include the full context, including the error details.

**Comment by AustinWentz** [comment]
Thanks for the fast reply. I'll take a look at STDOUT. Looking forward to v0.16.0!

**Comment by AustinWentz** [comment]
Hmm. After checking /var/log/amazon/aws-otel-collector, still nothing. What am I missing?
