### ISSUE TITLE
Documentation of googlecloudpubsubexporter doesn't give service account and user agent details 

### ISSUE THREAD

**Issue by sanjaygopinath89** [open-telemetry/opentelemetry-collector-contrib#7509]
**Describe the bug**
Documentation of googlecloudpubsubexporter  does not give details on how to give service account in configuration to access the pub/sub. 

In the document https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudpubsubexporter  it has given  "The Google Cloud Pubsub export doesn't automatic create topics, it expects the topic to be created upfront. Security wise it's best to give the collector its own service account and give the topic Pub/Sub Publisher permission."

1. In this above description its given  "best to give the collector its own service account" where we need configure the service account if I am running the collector in an AWS environment.? Can you give an example in documentation. 
2. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/googlecloudpubsubexporter/testdata/config.yaml#L12 what is the user agent mentioned in this config ..? Please give more details 
3. The pubsub topic I have to create with proto schema of cloudevent rt ? Is there a sample proto schema file available .?Tried to use https://github.com/cloudevents/spec/blob/v1.0.1/spec.proto but since its having "import"  we cannot directly use it in pubsub

**Environment**
Running otel collector contrib in k8s cluster in AWS

**Comment by jpkrohling** [comment]
cc @alexvanboxel

**Comment by alexvanboxel** [comment]
1 and 2 are valid feedback for the documentation, and I can pick this up after PR is merged... although this comment would be the same for all Google Cloud-related connectors/exporters.

On 3, the proto is already described in the documentation and has nothing todo with CloudEvents, this is only related to the headers. The proto's as payload are described here: https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto/collector

Let's keep this ticket open as it's valuable feedback for the documentation.


>

**Comment by sanjaygopinath89** [comment]
@alexvanboxel 

Thanks for the response .

In document its given that "The message published on the topic are [CloudEvent](https://cloudevents.io/) compliance and uses the binary content mode defined in the [Google Cloud Pub/Sub Protocol Binding for CloudEvents](https://github.com/google/knative-gcp/blob/main/docs/spec/pubsub-protocol-binding.md#31-binary-content-mode) ." . This makes me think that the exported format to Pub/Sub will be proto in CloudEvent format  . So as you mentioned the metric /trace exported to the pub/sub from exporter will be in OTEL proto format rt ..?

Thanks and Regards,
Sanjay

**Comment by alexvanboxel** [comment]
CloudEvent "binary-content" mode pushes all CloudEvent attributes to the message attribute leaving the content (or Body) to the native OTLP proto format (not wrapped in another proto)

**Comment by jessberg** [comment]
For the documentation on service accounts, I had the same issue, except with Google Cloud Platform.  I wrote out how I fixed it at the end of issue #7377.  I found that tutorial there very helpful;  maybe it is a good idea to link to that tutorial, and to note that it often takes a few hours for service account changes to propagate?

**Comment by alexvanboxel** [comment]
ping, to keep open
