### ISSUE TITLE
Resource detection processor sets uppercase values in os.type attribute

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#7522]
According to [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/3a326da59fbf8ecee5cbb44f2a7080cd5c4fe72c/specification/resource/semantic_conventions/os.md) `os.type` resource attribute has to contain one of the predefined values, all of them are written in lowercase. Resource detection processor sets them in uppercase. It should be changed to lowercase according to semantic conventions

**Comment by mx-psi** [comment]
Looks like this changed on open-telemetry/opentelemetry-specification#1598

**Comment by mx-psi** [comment]
Also note that `ZOS` becomes `z_os`

**Comment by mx-psi** [comment]
This amounts to changing this function https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/36623bcdc41f9663c99e247e63b43d6735c0ba27/processor/resourcedetectionprocessor/internal/resourcedetection.go#L218-L224 to do the mapping between `GOOS` and the spec values.
