### ISSUE TITLE
Add Apache Druid Metric Receiver

### ISSUE THREAD

**Issue by rahulbandariSensei** [open-telemetry/opentelemetry-collector-contrib#7524]
**Is your feature request related to a problem? Please describe.**
Metric Receiver for Apache Druid.
**Describe the solution you'd like**
I would like to scrape the metrics from Apache Druid.

**Comment by rahulbandariSensei** [comment]
I would like to work on this feature and contribute here.

**Comment by mx-psi** [comment]
@rahulbandariSensei can you open an issue following the 'New component proposal ' template
![new component](https://user-images.githubusercontent.com/5502710/152192510-3c8208ab-eed0-449c-9c5c-5aa2e9f0a1e0.png)
?

**Comment by rahulbandariSensei** [comment]
sure, @mx-psi.
