### ISSUE TITLE
[exporter/datadog] - Add debug flag to print payload data sent to Datadog API

### ISSUE THREAD

**Issue by kmotupalli-tc** [open-telemetry/opentelemetry-collector-contrib#7528]
**Is your feature request related to a problem? Please describe.**

When sending prometheus metrics to Datadog, some of the host metadata, labels and metrics are missing on Datadog.

**Describe the solution you'd like**

Logging payload data will help debugging this issue.

**Describe alternatives you've considered**
1. Log in stdout
2. Send it to DD logs instead of stdout
3. Log to file

**Comment by kmotupalli-tc** [comment]
0.37.1 version had similar debug logging which got removed in later releases. Want to add similar feature which can be enabled as flag if needed. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5856

**Comment by jpkrohling** [comment]
cc @KSerrania @mx-psi @gbbr @knusbaum

**Comment by mx-psi** [comment]
Sorry, I tagged this but didn't say anything :) We are tracking this internally, I removed the debugging because it was unintended and I want to avoid spammy logs by default, but it may be a good idea to add something like this behind a flag
