### ISSUE TITLE
Check for coverage of all metric types

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-collector-contrib#7532]
Some functions and processors that operate on metrics may not correctly operate on all metric types.  We have observed at least the `resourcetotelemetry` helper not accounting for Summary and Exponential Histogram metrics.  A survey should be undertaken to check for similar failures.

> Is there any linter that we can enable to check this? I know is hard since there is no enum type, but maybe some structure tags can help. This needs to be investigated because I bet there are more places like this.

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7523#discussion_r797906340_

**Comment by mx-psi** [comment]
The exhaustive linter from golangci-lint seems to be able to do this: https://github.com/nishanths/exhaustive

**Comment by mattsains** [comment]
There are quite a lot of cases where [MetricTypeEmpty](https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/pmetric/metrics.go#L106) is not handled by switch statements. eg: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/attributes_metric.go#L73

So we'd need to update all of that code to have a case for Empty / have a default clause but I don't know the code well enough to understand what should be done in those cases.

**Comment by fatsheep9146** [comment]
close by #9109
