### ISSUE TITLE
New component: OpenTSDB Receiver

### ISSUE THREAD

**Issue by foxlegend** [open-telemetry/opentelemetry-collector-contrib#7534]
## The purpose and use-cases of the new component
[OpenTSDB](http://opentsdb.net/) Receiver supports OpenTSDB [HTTP API](http://opentsdb.net/docs/build/html/api_http/index.html) and [Telnet API](http://opentsdb.net/docs/build/html/api_telnet/index.html) for metrics sent by the [TCollector](http://opentsdb.net/docs/build/html/user_guide/utilities/tcollector.html) component.

For information, I already started to develop this component here: https://github.com/foxlegend/opentelemetry-collector-opentsdb-contrib. The builder tool is just awesome for implementing a collector component in another repository :)

## Example configuration for the component

Example:
```
receivers:
  opentsdb:
    endpoint: 0.0.0.0:4242
```
The following settings are configurable:
* `endpoint` (default is 0.0.0.0:4242): host:port on which the collector is going to receive data.

## Telemetry data types supported
 
Supported pipeline types: metrics

**Comment by jpkrohling** [comment]
> The builder tool is just awesome for implementing a collector component in another repository :)

You made my day, thank you :-)
