### ISSUE TITLE
Open telemetry Dlls are not signed

### ISSUE THREAD

**Issue by muneernet** [open-telemetry/opentelemetry-collector-contrib#7539]
As I See both dot net  OpenTelemetry.Dll , OpenTelemetry.Api.Dll are not signed. Is there any possibility in the near future ? As that becomes a concern to move any production kind of environment ?

**Comment by jpkrohling** [comment]
Is this related to #7384?

**Comment by jpkrohling** [comment]
Given that this is about DLLs and not the binary, it seems like this is not the right repository for this issue. The dotnet instrumentation library repositories are:

https://github.com/open-telemetry/opentelemetry-dotnet
https://github.com/open-telemetry/opentelemetry-dotnet-contrib
