### ISSUE TITLE
Surpass activity creation on OpenTelemetry.Sql.Client.Dll and Open.Teletry.Contrib.WCF

### ISSUE THREAD

**Issue by muneernet** [open-telemetry/opentelemetry-collector-contrib#7540]
How can we enable and disable activities on OpenTelemetry.Instrumentation.SqlClient.dll , OpenTelemetry.Contrib.Instrumentation.Wcf.dll  and custom activities in C# . Is there a way to deal with asynchronous calls too ? . The Idea is we want to enable and disable telemetry based on the user configuration might be during initialization or on runtime.

**Comment by jpkrohling** [comment]
This is probably not the right repository for this request. It should go into one of the dotnet instrumentation repositories, like:

https://github.com/open-telemetry/opentelemetry-dotnet
https://github.com/open-telemetry/opentelemetry-dotnet-contrib
