### ISSUE TITLE
[prometheusremotewriteexporter] exporter can send duplicate label keys on metrics

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#7547]
In the PRW translation package, we keep a map of label keys to PRW labels.  However, the label key in the map [is not sanitized](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheusremotewrite/helper.go#L172).  Sanitization replaces invalid characters with `_`.  As a result, the following labels keys would both be sent with the PRW exporter: `host.name` and `host-name` -> `host_name` and `host_name`.  Since the unsanitized keys are unique, both labels will be sent, which violates OpenMetrics' requirement for labels to be unique.

**Comment by sethAmazon** [comment]
@dashpole would you recommend removing the duplicate labels or use a sanitization algo that will give a unique output?

**Comment by dashpole** [comment]
I'm still trying to think through it.  You can see the discussion here: https://github.com/open-telemetry/opentelemetry-specification/pull/2266#discussion_r796901839

**Comment by sethAmazon** [comment]
This is on our road map and will be prioritized when available. Sorry I can't give you any more information.
