### ISSUE TITLE
Remove usage of LogRecord Name field in awscloudwatchlogsexporter

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#7554]
The LogRecord Name field [is removed](https://github.com/open-telemetry/opentelemetry-specification/pull/2271) from the specification and is [going to be removed](https://github.com/open-telemetry/opentelemetry-proto/pull/357) from the OTLP.

Please remove usage of this field in the component.

**Comment by tigrannajaryan** [comment]
@boostchicken can you help?

**Comment by sethAmazon** [comment]
@alolita @tigrannajaryan I can look at this
