### ISSUE TITLE
metricstransformprocessor: rename metric via string substitution

### ISSUE THREAD

**Issue by DanTulovsky** [open-telemetry/opentelemetry-collector-contrib#7580]
**Is your feature request related to a problem? Please describe.**
I would like to rename metrics that look like:  a.b.c to metrics that look like a_b_c.  Essentially, I need to get rid of all the periods in metric names before sending them on.

**Describe the solution you'd like**
Ability to do a string replacement on metric names.  In my case, I want to replace "." with "_".

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jpkrohling** [comment]
cc @punya
