### ISSUE TITLE
Filelog Receiver Blocking File Rotation

### ISSUE THREAD

**Issue by gurpartb** [open-telemetry/opentelemetry-collector-contrib#7593]
**Describe the bug**
Otel Collector Preventing Services From File Rotation

**Steps to reproduce**
Try manually deleting a log file that Otel Collector is actively reading from.

**What did you expect to see?**
In between `poll_intervals` File Log Receiver should release the file resource and not prevent other services from deleting/ rotating files.

**What did you see instead?**
![image](https://user-images.githubusercontent.com/35710086/152839209-fa78bf67-c825-46b3-84ba-72ef689effb8.png)

**What version did you use?**
Latest

**What config did you use?**
receivers:
 
  filelog/grafana:
    include: ["D:/path/to/grafana.log"]
    operators:
     - type: json_parser
       timestamp:
         parse_from: t
         layout_type: strptime
         layout: '%Y-%m-%dT%H:%M:%S.%fZ'

**Environment**
Microsoft Windows Server 2016 Data Center

**Comment by jpkrohling** [comment]
cc @djaglowski

**Comment by djaglowski** [comment]
Thanks for writing this up @gurpartb.

The filelog receiver has some known limitations when it comes to file rotation on Windows via the "Move/Create" strategy. At some point we [decided not to guarantee support for this combination](https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/operator/builtin/input/file/rotation_test.go#L38:L41), though it does actually work most of the time and we want to make reasonable efforts for it to work as much as possible. In any case, we certainly should not be causing problems, as you've described.

A little more background on this - The filelog receiver holds onto file handles just long enough to check for files that have been rotated out of the file matching pattern. This works well enough on non-Windows systems, but has a side effect on Windows that we hadn't realized. I think the correct action here is to accept that we will not be able to track such files on Windows. To that end, I've drafted a change that would release files immediately after reading, on Windows only. Feedback is welcome, especially on the design decision.

**Comment by djaglowski** [comment]
@crobertson-conga, I'm aiming to cut a release and update contrib by the middle of next week. We're very close to wrapping up [this milestone](https://github.com/open-telemetry/opentelemetry-log-collection/milestone/2), and will cut a release as soon as that is done, so possibly will be Monday or Tuesday.

**Comment by djaglowski** [comment]
@gurpartb, @crobertson-conga, the fix has been merged to contrib's main branch. I'm closing this issue but please let me know if you see anything remaining problems.

**Comment by gurpartb** [comment]
> @djaglowski Looks like you have a proposed fix for this issue main trunk of the dependent library. Any ideas when this will become a part of the contrib deployment? We ran into this exact issue yesterday and would like to be able to update our agent and take care of this problem.

For now we are using FluentD to read the logs files into the Otel Collector. You may try that solution.

**Comment by gurpartb** [comment]
> @crobertson-conga, I'm aiming to cut a release and update contrib by the middle of next week. We're very close to wrapping up [this milestone](https://github.com/open-telemetry/opentelemetry-log-collection/milestone/2), and will cut a release as soon as that is done, so possibly will be Monday or Tuesday.

Thank you!

**Comment by gurpartb** [comment]
> @gurpartb, @crobertson-conga, the fix has been merged to contrib's main branch. I'm closing this issue but please let me know if you see anything remaining problems.

Thank you!

**Comment by crobertson-conga** [comment]
Thanks a bunch, we will be trying this out soon.
