### ISSUE TITLE
Failing test: TestStatsReaders_Read/Interval_stats_reader_without_backfill_with_corrupted_metadata

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#7595]
The following test appears to be failing, may be flaky: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5097104076?check_suite_focus=true

```
2022/02/07 17:39:00 spannertest.inmem:         ▹ map[pullTimestamp:{2022-02-07 17:39:00 +0000 UTC {false 7 0}}]
    statsreaders_mockedspanner_test.go:202: 
        	Error Trace:	statsreaders_mockedspanner_test.go:202
        	Error:      	An error is expected but got nil.
        	Test:       	TestStatsReaders_Read/Interval_stats_reader_without_backfill_with_corrupted_metadata
```

**Comment by jpkrohling** [comment]
cc @ydrozhdzhal @asukhyy @khospodarysko @architjugran

**Comment by architjugran** [comment]
I will look into this prioritize fixing this bug by next week. I hope that's okay? Or is this blocking any development?

**Comment by codeboten** [comment]
Thanks @architjugran, I've assigned it to you

**Comment by architjugran** [comment]
Verified that test is flaky. However, locally it is failing once in 100 runs.

Has it been a big problem for open telemetry dev? If yes, I can create a PR to disable the test temporarily, while I root-cause the issue.

**Comment by jpkrohling** [comment]
It just happened again: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5983147705?check_suite_focus=true
