### ISSUE TITLE
MatchProperties.Libraries must match AT LEAST one

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#7755]
MatchProperties.Libraries is supposed to be a match if at least one item in the Libraries list matches. This is not currently the case. The code written attempts to match all entires which is wrong: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3a8ba25ffc593858690829c01f43c1811b1633dc/internal/coreinternal/processor/filtermatcher/filtermatcher.go#L90

**Steps to reproduce**
Use a config with 2 libraries to match and an input that uses a library name that is equal to one of the libraries in the config.

**What did you expect to see?**
A match.

**What did you see instead?**
No match.

**Comment by atoulme** [comment]
This is now living here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/71709339fb66cd6f4f7654ed5b26e002bbe657b1/internal/filter/filtermatcher/filtermatcher.go#L46
