### ISSUE TITLE
MatchProperties.Resources incorrectly says that it matches at least one

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#7756]
MatchProperties.Resources is supposed to be a match if at least one item in the Libraries list matches. This is not currently the case. The code written attempts to match all entires: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3a8ba25ffc593858690829c01f43c1811b1633dc/internal/coreinternal/processor/filtermatcher/attributematcher.go#L96

It is not clear what is the right approach? Should it be AT LEAST one, or ALL? Either we need to fix the docs or fix the behavior. 

Related issue with libraries: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7755

**Steps to reproduce**
Use a config with 2 resource attributes to match and an input that uses a resource attribute that is equal to one of the attributes in the config.

**What did you expect to see?**
A match.

**What did you see instead?**
No match.

**Comment by dmitryax** [comment]
Seems like it's the same issue as reported previously https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5234

Currently supposed and documented behavior it to match all the attributes. @tigrannajaryan do you see where it's documented otherwise?

We probably should have another configuration option that controls this behavior

**Comment by tigrannajaryan** [comment]
@dmitryax The MatchProperties settings [comments](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/522073aec34305beb7b4e2f8f9bc3510178252e9/internal/coreinternal/processor/filterconfig/config.go#L101) say:
>// Resources specify the list of items to match the resources against.
>	// A match occurs if the span's resources matches **at least** one item in this list.
>	// This is an optional field.

**Comment by dmitryax** [comment]
Yeah looks these comments need to be updated. I changed few others [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5280) but missed this

**Comment by tigrannajaryan** [comment]
So what do you think is the right approach? Do we want AT LEAST one, or ALL? I am not sure myself.

**Comment by dmitryax** [comment]
According to @hossain-rayhan as mentioned in [this issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5234) it was designed to be ALL. I don't have strong opinion. Probably we can keep it ALL (with docs fixed) and add an option to reconfigure the behavior.

**Comment by tigrannajaryan** [comment]
I am fine with ALL.

**Comment by hossain-rayhan** [comment]
Requesting some time here. I would love to take a look this week.

**Comment by hossain-rayhan** [comment]
Thanks @tigrannajaryan and @dmitryax for looking into this. Let's keep the functionalities same (match all) and update the doc/comment. As @dmitryax mentioned we have different use cases. We can add an option/flag for configurability without breaking our existing customer experience.

**Comment by dmitryax** [comment]
@hossain-rayhan sounds good. Do you have a chance to update all the comments?

**Comment by atoulme** [comment]
Please indicate if #7755 should have the same resolution.
