### ISSUE TITLE
[receiver/jmx] Update integration tests to cover recent versions of JMX Metric Gatherer

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#7761]
**Is your feature request related to a problem? Please describe.**
The `jmxreceiver`'s integration tests must be kept up to date with [releases of the JMX Metric Gatherer](https://repo1.maven.org/maven2/io/opentelemetry/contrib/opentelemetry-jmx-metrics/) on which it depends. Currently, the integration tests cover the two oldest releases but none of the latest five releases.

**Describe the solution you'd like**
- [ ] Define which versions of the JMX Metric Gatherer are supported by the `jmxreceiver`.
- [ ] Ensure the `jmxreceiver`'s integration tests cover the min & max supported version, as well as any intermediate versions that contain breaking changes.
- [ ] Articulate a strategy for keeping the integration tests up to date with new releases of the JMX Metric Gatherer.
- [ ] Ensure #5874 is resolved

See #5429

**Comment by jpkrohling** [comment]
Is this expected to help fix #5874?

**Comment by djaglowski** [comment]
Yes, thanks for pointing this out @jpkrohling. I've added this to the checklist on this issue.
