### ISSUE TITLE
Cleanup internal modules in order to have translator packages without core collector dependency.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#7791]
Right now the translator packages (jaeger, zipkin, pwr, opencensus, etc.) depend on `coreinternal` which mostly depend on `pdata` but it also has other dependencies.

The proposal is to cleanup the internal packages (which by definition should be internal, which means external users should not depend on them) in:
1. Current `common` package becomes a package of utils that do not have any significant external dependencies (testify is ok; but docker is not).
2. Every significant external dependency (docker, k8s) has its own dedicated internal package to minimize the dependencies.
    * Will have an `modelinternal` (depends only on the collector/model package) and `coreinternal` (depends on the current collector package). 

**Edited:** By `internal` modules we refer to the go modules in `/internal`.

**Comment by dmitryax** [comment]
It makes sense to me

**Comment by jpkrohling** [comment]
Was this completed already? Should it be closed, or are there missing pieces?

**Comment by bogdandrutu** [comment]
Not yet.
