### ISSUE TITLE
[exporter/signalfx] Ensure Validate implementation does the right thing

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#7843]
This [change](https://github.com/open-telemetry/opentelemetry-collector/commit/48c402dbfafd6c53686a7aad193beb1aa47a4b7c) in the collector core added a `Validate` method to `QueueSettings` which caused ambiguity with the `ExporterSettings`’ `Validate` method. As a result, I’ve added a Validate method to this exporter and an issue to ensure it was doing the right thing.

Here is an example of the validate method for the OTLP exporter calling the QueueSettings’ Validate

https://github.com/open-telemetry/opentelemetry-collector/commit/48c402dbfafd6c53686a7aad193beb1aa47a4b7c#diff-a56037437974f775001642d59880ac9dd0c14cab137576b4f4a6df01a230a84cR39-R42

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7779#discussion_r803075520_

**Comment by jpkrohling** [comment]
cc @pmcollins @asuresh4 @dmitryax
