### ISSUE TITLE
dedup internal/aws/metrics and internal/common/ttlmap

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#7903]
Both modules/packages seem to offer a TTL map implementation. Someone needs to investigate and dedup the code if duplicate exists.

**Comment by yankay** [comment]
HI @bogdandrutu ,
The ”internal/common/ttlmap“  is the more common one. And can be used more widely.
Can we use the ”internal/common/ttlmap“  and remove the ”internal/aws/metrics“ ?
