### ISSUE TITLE
OpenSearch exporter support

### ISSUE THREAD

**Issue by thmshmm** [open-telemetry/opentelemetry-collector-contrib#7905]
**Is your feature request related to a problem? Please describe.**
The existing elasticsearch exporter can not be used with OpenSearch as the used elasticsearch client library checks if the target backend is Elasticsearch. The support for OpenSearch should be introduced.

**Describe the solution you'd like**
The OpenSearch client could be integrated into the existing elasticsearch exporter and a configuration parameter could be introduced to switch clients.

**Describe alternatives you've considered**
An alternative would be to create a dedicated opensearch exporter and reimplement/reuse the elasticsearch exporter logic with just the client replaced.

**Additional context**
n/a

**Comment by r3h0** [comment]
In case anyone is wondering, here's the exact error message:

> Bulk indexer error: flush: the client noticed that the server is not Elasticsearch and we do not support this unknown product

I know this because I set everything up only to find that I can't use it because of this.

I guess this is my +1 😭 

Thanks for the hard work y'all are putting into OpenTelemetry. I've been following the project since the first announcement, and I'm looking forward to being a user of it someday.

**Comment by binjip978** [comment]
Hi, our storage solution is based on opendistro, so we have similar issue with elastic rest client. I already forked elasticsearchexporter https://github.com/binjip978/opentelemetry-collector-contrib/tree/opensearch-exporter/exporter/opensearchexporter and it works for our case. 

But it still require proper documentation and some factoring on common code in both exporters. @jpkrohling not sure what "sponsor needed" is about, but I could provide a PR.

**Comment by jpkrohling** [comment]
From https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components :

> **Before** any code is written, [open an issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/new?assignees=&labels=new+component&template=new_component.md&title=New%20component) providing the following information:
> 
> * Who's the sponsor for your component. A sponsor is an approver who will be in charge of being the official reviewer of the code and become a code owner for the component. For vendor-specific components, it's good to have a volunteer sponsor. If you can't find one, we'll assign one in a round-robin fashion. For non-vendor specific components, having a sponsor means that your use case has been validated.

**Comment by TomasLongo** [comment]
@r3h0 Nice! This is exactly what I was looking for. I tried to build your fork of the repo, but am not able to configure  the opensearch-exporter properly. You mentioned that it works for you.

How did you configure the exporter? What key did you use in your `otel-config.yaml`?

Thanks in advance for your kind help. Cheers, Tomas.

**Comment by r3h0** [comment]
Not me, @TomasLongo. @binjip978's the one who built it

**Comment by TomasLongo** [comment]
Hey everyone. We successfully integrated the opensearchexporter into the otel-collector based on the fork of @binjip978. 

We would be more than happy to contribute it back to the project if there is any interest.

**Comment by r3h0** [comment]
@TomasLongo there is interest, for sure. The exporter needs a sponsor, per what jpkrohling said above. Maybe you could read through the contributing docs and see if you are a good fit.

**Comment by KarstenSchnitter** [comment]
Hi everyone, there does not seem to be much progress on #10206. We really like the feature and tested the branch successfully. What can be done, to help the integration?

**Comment by StefanSa** [comment]
Hi there, @TomasLongo 
thanks for this important exporter #10206.
General question about this OpenSearch exporter.
Which pipelines are supported ?
I hope to logs also metrics, because we want to send metrics to opensearch.

**Comment by TomasLongo** [comment]
Hey @StefanSa,

nice to see that there is interest in our contribution. We would be more than happy to provide the functionality you requested. Feel free to create an issue for the signals you want the exporter to support.

We can start working on them as soon, as #10206 got merged.

**Comment by StefanSa** [comment]
Hi @TomasLongo 
done with #12323

**Comment by KarstenSchnitter** [comment]
@jpkrohling we would really like to integrate this exported into the codebase. #10206 was provided from a fork we used internally. Can you assists @TomasLongo in finding a sponsor for this issue? Maybe @dmitryax would be a possibility, since he already gave a lot of comments to #10206? If necessary, we can create another issue, as you suggested using https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components. However, this will be very redundant to this very issue. Please advise, how you want us to proceed with the Opensearch exporter.

**Comment by spakinz** [comment]
Currently, if we want to send our traces to OpenSearch and display them using the [Trace Analytics plugin](https://opensearch.org/docs/1.2/observability-plugin/trace/ta-dashboards/) for OpenSearch Dashboard, we need to use [OTel Collector + Data Prepper](https://opensearch.org/docs/1.2/observability-plugin/trace/get-started/). I believe data is slightly transformed by Data Prepper in order to be displayed by the Trace Analytics plugin.

Should the new OpenSearch exporter have a configuration to allow the traces to be displayed by this plugin? I believe the ElasticSearch exporter has the [mapping mode configuration option](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter#configuration-options) to send raw traces or to make slight transformations to the data. This would be something similar.

**Comment by dlvenable** [comment]
@spakinz , When sending trace data to OpenSearch using the OTel Collector and Data Prepper, Data Prepper does perform some transformations to make the traces display correctly in the Observability plugin. It performs two sets of changes: 1. It enriches each span with overall trace data; and 2) It creates a service map which goes into a second index.

**Comment by dbason** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10206 looks to have stalled, but there are other people willing to work on it (we would still need a sponsor though).  Would it be best to open a new PR?

**Comment by Aneurysm9** [comment]
OpenSearch [accepts OTLP](https://opensearch.org/docs/latest/data-prepper/configuration/sources/sources/) via [DataPrepper](https://github.com/opensearch-project/data-prepper) and [recommends](https://opensearch.org/blog/distributed-tracing-pipeline-with-opentelemetry/) that as an ingestion mechanism.

**Comment by dbason** [comment]
That's true for traces and metrics but not for logs.  I believe it would still be beneficial to have an Opensearch output as this then allows user to have a single agent if they are using Opensearch rather than making it an exception where you have to use DataPrepper.

**Comment by KannappanSomu** [comment]
+1

**Comment by steevex35** [comment]
Hi everyone, do we have any idea if the OpenSearch exporter will be officially added one day or not ?

**Comment by dbason** [comment]
> Hi everyone, do we have any idea if the OpenSearch exporter will be officially added one day or not ?

I'm still trying to chase this up, we need to find someone to sponsor the work.  I currently have a [branch](https://github.com/dbason/opentelemetry-collector-contrib/tree/opensearch-exporter) updated for v0.71.0.  After doing that I've been wondering if it would be worthwhile having a shared [objModel](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter/internal/objmodel) for elasticsearch and opensearch as these are currently identical.

**Comment by steevex35** [comment]
@dbason thanks a lot for your contribution Dan, hope someone will help you to sponsor your work. 
Did you manage to build your custom collector (ocb v0.71.0) with the Opensearch exporter ? 
I tried with this line but unable to fetch the module: - **gomod: github.com/dbason/opentelemetry-collector-contrib/tree/opensearch-exporter/exporter/opensearchexporter v0.71.0**
![Screenshot 2023-02-23 at 17 46 35](https://user-images.githubusercontent.com/6085729/220975023-373a24bc-93e8-4a4a-a943-e5f198ecb9da.png)
![Screenshot 2023-02-23 at 17 47 56](https://user-images.githubusercontent.com/6085729/220975329-bdff7566-5916-45d0-9f3c-030a741b1825.png)

**Comment by steevex35** [comment]
@dbason Hi Dan, Thank you very much for this, it's work perfectly with the last version of OpenSearch.

**Comment by arve0** [comment]
Hi @dbason. Thanks for your update on the OpenSearch exporter.

I'm trying it out with traces:
```yaml
service:
  pipelines:
    traces:
      receivers:
      - otlp
      exporters:
      - opensearch
``` 

but opentelemetry-collector fails with:

> Error: failed to build pipelines: failed to create "opensearch" exporter for data type "traces": telemetry type is not supported

I guess traces are not supported? Any idea how I should go about adding support for traces?
