### ISSUE TITLE
Support of exemplars/trace id in Prometheus exporter for metrics produced with spanmetric processor

### ISSUE THREAD

**Issue by fscellos** [open-telemetry/opentelemetry-collector-contrib#7906]
Goal of this feature is too add trace id examplars in prometheus exporter.
It could be nice if we have trace id information set in prometheus exporter as they are already present in spanmetrics processor.
This feature is already supported by prometheus write exporter.

I would like to have trace_id as examplars produced by a pipeline spanmetrics --> prometheus exporter to be able to see examplars in grafana time series build from metrics generated by span metrics processor.

Problem to implement this feature is that metrics are actually collect before generation of new Histogram/Counter at scraping. The object used are build from existing data point and it is not possible to build a new static Histogram with examplars.

I wonder is a better solution would be not to review implementation of collector to directly load histogram with sample examplars like we will do in a standard application (without rebuilding histogram & counter all the time)

**Comment by jpkrohling** [comment]
cc @albertteoh @gouthamve

**Comment by albertteoh** [comment]
Adding reference to comment referencing PRs adding exemplars to both spanmetrics processor and prometheusremotewrite exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5263#issuecomment-1024203109

**Comment by garry-cairns** [comment]
I'm not sure if this is related but I'm looking to implement a sampling policy of "only retain traces that were exemplars in our generated metrics". I think I can do this by chaining collectors if the exemplars are tagged in some way that I can use for attribute sampling. Does the addition for this issue achieve this? I looked at the code but couldn't see anything obviously mutating the spans in this way.

**Comment by fscellos** [comment]
Hello @garry-cairns : not sure to understand your use-case. 
I think it is not possible to "retain traces that were examplars" as examplars are just tag of trace id on metrics.
As i know, you don't have information on trace itself about the fact that it were used for one or many metrics.
Can you explain a little bit your goal ?

(this current issue is just related to the production of examplars base on metrics calculated with timestamp on span; so for an exporter)

**Comment by garry-cairns** [comment]
@fscellos So my question is whether it's possible/already happening to mutate the traces whose IDs are tagged as exemplars such that they're easily identified by subsequent pipelines.

My use-case here is for a sidecar Otel Collector to output all data to a central collector cluster, and I want to discard all traces whose IDs were not used as exemplars.
