### ISSUE TITLE
K8sattribute processor documentation need updates 

### ISSUE THREAD

**Issue by Yadumathur** [open-telemetry/opentelemetry-collector-contrib#7912]
**Describe the bug**
We have a set up with OtelC as Daemon set and we wanted to send K8 meta data along with Application logs, While going through the whole exercise and available documentation https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor 
We observed that the documentation does not cover below points clearly 
1. daemonset set up and env variable to capture pod ip 
2. config for the above set 
3. using resourcedetectionprocessor to identify pod level information from above 
4. K8sattribute processor config 

**Steps to reproduce**
-- Gap in documentation

**What did you expect to see?**
Daemon set section to add env variables 

    spec:
      containers:
      - env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.pod.ip=$(POD_IP)

Configmap config example for resourcedetectionprocessor
    processors:
      resourcedetection:
        detectors: ["env"]
        timeout: 5s
        override: true

Configmap config example for k8sattributes
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME

        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.cluster.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time

        pod_association:
         - from: resource_attribute
           name: k8s.pod.ip

**What did you see instead?**
Config - TODO 

**What version did you use?**
v0.40.0

**What config did you use?**
Daemon set section to add env variables 

    spec:
      containers:
      - env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.pod.ip=$(POD_IP)

Configmap config example for resourcedetectionprocessor
    processors:
      resourcedetection:
        detectors: ["env"]
        timeout: 5s
        override: true

Configmap config example for k8sattributes
      k8sattributes:
      k8sattributes/2:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME

        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.cluster.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time

        pod_association:
         - from: resource_attribute
           name: k8s.pod.ip

**Environment**
k8 and Otel C as Daemon set 

**Additional context**

**Comment by dmitryax** [comment]
What is your goal of using k8sattribute processor? Do you want to enrich logs with k8s attributes? You don't necessary need `k8s.pod.ip` right? `k8s.pod.ip` is used to find out which pods ending traces data from HTTP client context. If you use filelog receiver to collect logs, association is done by `k8s.pod.uid`, not pod IP. Look at how it's configured in this example https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/kubernetes/otel-collector.yaml#L66.

I do agree that k8sattribute processor's documentation is pretty poor, but looks like https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7913 is not the right way to fix it

**Comment by Yadumathur** [comment]
You are right we need to enrich data using k8sattributes, I have tried the above configuration and it fails as parse_from from the filepath not necessarily have all the same details on our deployments, now while the case is to add metadata while deployed as daemonset and when I looked into more details I found that the daemonset, can `spec.containers.env` should use the downward API ( set in the env variables of pod ) to capture `status.podIP` and add it as part of the `OTEL_RESOURCE_ATTRIBUTES`  env variable. After this is set it is used by the OpenTelemetry Collector's `resourcedetection` and `k8s_tagger` processors to tag k8s metadata and I have validated hence suggested the above change.
This makes the hard design tag from receiver to a dynamic fetch from k8sattributes.
Please let me know if this is something we should consider while suggesting the config samples to consumers

**Comment by pmm-sumo** [comment]
There's an [OTEPS](https://github.com/open-telemetry/oteps/pull/195) on using downward API for injecting various metadata, which is somewhat following the use-case here. I think it's a valid one. Especially for first-party application logs

> I have tried the above configuration and it fails as parse_from from the filepath not necessarily have all the same details on our deployments.

Could you add more details? Did[this expression](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/kubernetes/otel-collector.yaml#L56) fail?

**Comment by Yadumathur** [comment]
Yes , @pmm-sumo  this expression failed and hence I was trying to figure out how I can get pod uuid for the association. The best way seems to me is by using downward apis.

**Comment by Yadumathur** [comment]
@pmm-sumo  I see you have suggested in past for using pod uid https://docs.google.com/document/d/1QlFbXz0eQUaKXK1WrnEs3VqRkcPD2RAdXJdJMjnOSd8/edit#
after going through , I see still not a straight way to get K8sattribute processor tag the meta based on association apart from IP and uid.
both information need to be served back by any possible way ( through file path , cri or something to be explored ) 
is there any other way I can make k8sattribute work apart from using uid or ip ?

**Comment by pmm-sumo** [comment]
I believe [CRI](https://github.com/kubernetes/kubernetes/pull/74441) (so the file path) is a common way to pull this information. Hence I'm wondering why the regex I mentioned earlier did not work. There is perhaps something wrong with it. If you have more data on the file path on which it failed, we could perhaps investigate and fix it

**Comment by Yadumathur** [comment]
Example log file path : otel-collector-hkhqj_logging_otel-collector-2768bd6d70c9ac40b17f477ac1a8427e2f4144771cba61fd3aae405e950f98aa.log
My regex which works with it is : '(?P<pod_name>^.+?)_(?P<namespace>.+?)_(?P<container>.*)-(?P<runid>.+?).log$'

This could be related more how the K8s are set up in my org to mount the file , but I need to verify that

**Comment by Yadumathur** [comment]
So I tried using K8 uid from filepath to pull the meta from k8s processor , @pmm-sumo I don't see that is working as well. For me K8s processor only able to work with pod ip.
I am using 0.40 version , Do I need to upgrade the version ?

**Comment by Yadumathur** [comment]
@pmm-sumo , I think the main issue is around auth type 
const (
	// [AuthType](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/internal/k8sconfig#AuthType)None means no auth is required
	[AuthType](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/internal/k8sconfig#AuthType)None [AuthType](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/internal/k8sconfig#AuthType) = "none"
	// [AuthType](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/internal/k8sconfig#AuthType)ServiceAccount means to use the built-in service account that
	// K8s automatically provisions for each pod.
	AuthTypeServiceAccount AuthType = "serviceAccount"
	// AuthTypeKubeConfig uses local credentials like those used by kubectl.
	AuthTypeKubeConfig AuthType = "kubeConfig"
	// AuthTypeTLS indicates that client TLS auth is desired
	AuthTypeTLS AuthType = "tls"
)

TLS is not yet supported , and serviceAccount only uses default service account.
In case I want to use a existing service account which has Privileges I dont find any documentation on that

**Comment by pmm-sumo** [comment]
@Yadumathur OK, so the issue is not with the regex parsing but with ability to query the API server in your setting as the default service account does not have enough privileges? 

I think we might use updating the documentation, similar as it is the case for `k8seventsreceiver` (there's a section on [setting up service account and RBAC](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/896fb9d97d395a14015e28a71ba4b7215a47ac6d/receiver/k8seventsreceiver/README.md#service-account))

**Comment by Yadumathur** [comment]
@pmm-sumo I was able to get the regex part fixed by appending uuid and extracting it in metadata attributes. Then I could see that only local agent k8 meta it can read even with IP , not much information is in debug logs ( enabled them at telemetry level ) 
I have a service user which has privileges and it is running the daemonset , But I dont think it Otel C is using that service user in setting of "serviceAccount" rather it uses default one which K8 creates per pod.
In case I want to use my service user I dont see a documentation on that. 
Absolutely agree , the current documentation should be updated with below in clarity 
1. RBAC needed for service account and how to set up that 
2. How to use that created service account  in config

**Comment by Yadumathur** [comment]
This issue is fixed by the PR above , Thanks 
I am closing the issue
