### ISSUE TITLE
Collector agent executable not signed 

### ISSUE THREAD

**Issue by panthamm** [open-telemetry/opentelemetry-collector-contrib#7927]
**Describe the bug**
Currently, the otelcontribcol_windows_amd64.exe distributed in releases are not having File Description, File version, Product name, Product version, copyright information, and not signed. 

**Steps to reproduce**
Download the otelcontribcol_windows_amd64.exe from the release

**What did you expect to see?**
We should see otelcontribcol_windows_amd64.exe have metadata like File Description, File Version, Product Name, Production Version, Copyright information, and digital information.

**What did you see instead?**
No metadata information like File Description, File Version, Product Name, Production Version, Copyright information, and digital information.

**What version did you use?**
Version: 0.42.0

**Additional context**
We are able to populate the file metadata, able to sign the executable, and tested the same executable in the local environment.

1. Clone the OpenTelemetry Collector Contrib Repository from the below GitHub URL onto the local machine.
2. https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.42.0
3. After cloning the OpenTelemetry Repository using Git Clone on local machine checkout to latest branch version v0.42.0
4. Install the required Setup and Binary Compilers for Golang Setup and TDM GCC Runtime libraries and tools which contain GNU compiler collection.
    a. https://go.dev/dl/go1.17.6.windows-amd64.msi
    b. https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe
5. Steps to populate file properties
    a. got get github.com/josephspurrier/goversioninfo/cmd/goversioninfo 
    b. Create versionifo.json with all required FileInfo samples located https://github.com/josephspurrier/goversioninfo/blob/master/testdata/resource/versioninfo.json 
6. Modify the main.go file with 
//go:generate C:\Users\murty.pantam\go\bin\goversioninfo
//-icon=..\..\internal\buildscripts\packaging\msi\opentelemetry.ico
7. Populate the resource.syso file for populating the File properties
    go mod tidy → command ensures that the go.mod file matches the source code.
    go mod init → command creates a go.mod file to track code dependencies.
    go generate → command generates a resource.syso file
8. Run the SignTool executable to sign the OTEL Collector agent executable with the Certificate.

**My Question:**
1. Are the above steps are fine?
2. What metadata we can fill for File version, Product name, Product version, Copyright?
3. Can we get the trusted certificate to run the SignTool? 
4. Is anybody planning to populate the metadata and sign the executable?

**Comment by jpkrohling** [comment]
> Run the SignTool executable to sign the OTEL Collector agent executable with the Certificate.

How is it done? Can it be invoked during our CI process?

**Comment by panthamm** [comment]
Yes, We can invoke through the CI process but we need to know File metadata information (File version, Product name, Product version, Copyright) and Trusted certificate to sign the executable.
