### ISSUE TITLE
[processor/spanmetrics] Remove leading zeros in a Traceid

### ISSUE THREAD

**Issue by tonychoe** [open-telemetry/opentelemetry-collector-contrib#7928]
**Describe the bug**
When you visualize the exemplars generated from the spanmetrics processor, you see leading zeros. It's difficult to read the traceid. Can we remove the zeros? 

**Steps to reproduce**
1. Configure the opentelemetry collector with spanmetrics processor, prometheus exporter, and prometheusremotewrite exporter.
2. Search and visualize the resulting metrics in Grafana e.g.
```histogram_quantile(.90, sum(rate(latency_bucket{service_name="app"}[1m])) by (le))```
3. Hover on the exemplars to see the pop up.
4. The traceid in the popup has leading zeros.

**What did you expect to see?**
No leading zeros in the traceid.

**What did you see instead?**
Leading zeros in the traceid.

<img width="1492" alt="leading zero" src="https://user-images.githubusercontent.com/12507518/153990163-d66e009a-c4a3-4636-b49f-a7b8e6ec9655.png">

**What version did you use?**
opentelemetry-collector-contrib:0.44.0

**What config did you use?**
My set up is similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/testdata/config-prometheusremotewrite.yaml

**Environment**
Grafana 8.3
Prometheus 2.31.2
Tempo 1.3

**Comment by jpkrohling** [comment]
I'm afraid the leading zeros cannot be removed from there easily, as we aren't dealing with a number type, but rather a byte[] type. It just so happens that the first bytes are zeroes in this particular case.

cc @albertteoh

**Comment by tonychoe** [comment]
if removal is not possible, do you guys think it's a good idea for Grafana UI to display traceid without the leading zeros?

**Comment by jpkrohling** [comment]
I asked internally at Grafana Labs and there have been a few ideas from @bboreham. Also, @connorlindsey might be able to give some insights about the Grafana UI part.

**Comment by connorlindsey** [comment]
Could something like what the jaeger client does be used here to remove the leading zeros? https://github.com/jaegertracing/jaeger-client-go/blob/8d8e8fcfd04de42b8482476abac6a902fca47c18/span_context.go#L368-L373

If not, let's get an issue opened in the grafana repo and we can edit the UI

**Comment by jpkrohling** [comment]
I think we shouldn't mess with the trace ID in the internals, handling only the way it's presented to users.

**Comment by connorlindsey** [comment]
Sounds good to me. @tonychoe can you open an issue in the grafana repo and reference it here when closing this issue? Thanks

**Comment by tonychoe** [comment]
Thanks. I've opened the grafana/grafana#45576. Closing this.
