### ISSUE TITLE
version command prints jaeger errors

### ISSUE THREAD

**Issue by 06kellyjac** [open-telemetry/opentelemetry-collector-contrib#7931]
**Describe the bug**

version command prints jaeger errors

```
./otelcontribcol --version
2022/02/15 09:48:33 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/02/15 09:48:33 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
otelcontribcol version latest
```

**Steps to reproduce**

build v0.44.0 and run `--version`

**What did you expect to see?**

no warnings

**Comment by ofirshmuel** [comment]
Hi @jpkrohling , we are investigating this issue.

**Comment by mx-psi** [comment]
@ofirshmuel I think this is still happening, do you have any updates?

**Comment by frzifus** [comment]
seems to be still a thing in dc19b911d0bf1f5169e1baf665858b3ad2e11cb5. @ofirshmuel are you going to continue your pr? otherwise i could would like to try.

**Comment by frzifus** [comment]
> This is caused by both the Jaeger receiver and the Coralogix exporter registering the same types

I am surprised that it this exporter workes. :no_good:. There are two definitions of `jaeger.api_v2.PostSpansRequest`, `jaeger` and `coralogix`. For me it looks like `carologix` is adding the message `Metadata` it the request.

```proto
+ message Metadata {
+     string ApplicationName = 1;
+     string SubsystemName = 2;
+ }

message PostSpansRequest {
    Batch batch = 1 [
        (gogoproto.nullable) = false
    ];
+     Metadata metadata = 2;
}
```



```golang
func RegisterType(x Message, name string) {
	if _, ok := protoTypedNils[name]; ok {
		// TODO: Some day, make this a panic.
		log.Printf("proto: duplicate proto type registered: %s", name)
		return
	}
...
```

**Comment by frzifus** [comment]
> This is caused by both the Jaeger receiver and the Coralogix exporter registering the same types

I am surprised that it this exporter workes. :no_good:. There are two definitions of `jaeger.api_v2.PostSpansRequest`, `jaeger` and `coralogix`. For me it looks like `carologix` is adding the message `Metadata` it the request.

```proto
+ message Metadata {
+     string ApplicationName = 1;
+     string SubsystemName = 2;
+ }

message PostSpansRequest {
    Batch batch = 1 [
        (gogoproto.nullable) = false
    ];
+     Metadata metadata = 2;
}
```
As far as I understand, this leads to a few problems:
1. it is not clear which of the two messages is registered first. Seems to be decided at each program start. As a result we can not make sure that `Metadata` will be a part of `PostSpansRequest`. 
2. If the `jaeger` would get extended in the future this could cause issues there too.
3. Maybe in the future the [type registration](https://github.com/gogo/protobuf/blob/b03c65ea87cdc3521ede29f62fe3ce239267c1bc/proto/properties.go#L543-L550) will follow a similar approach as other register methods and will end with a panic in case of a double registration.

---

Any recommendations how to solve this?

cc @oded-dd  @ofirshmuel @jpkrohling

**Comment by oded-dd** [comment]
@frzifus thank you for your help. Adding @povilasv to the thread. He'll probably also attend it soon, and could give you all the insights you need.

**Comment by mx-psi** [comment]
Is this still a thing @povilasv? Or did #13844 fix it?

**Comment by frzifus** [comment]
@mx-psi yes its still a thing. d397c9878974186e6cf66f904b364d7fc983b691
```
2022/11/10 11:29:59 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/11/10 11:29:59 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
```

**Comment by mx-psi** [comment]
Okay, I have labeled this as `exporter/coralogix` instead of Jaeger, AIUI the fix needs to be done in the Coralogix exporter.

**Comment by jpkrohling** [comment]
I'm in favor of disabling the coralogix exporter until this is fixed. The component owners had enough time to fix this already.

**Comment by mx-psi** [comment]
We got no answer here or in the email, thus I added this to today's SIG agenda. cc @oded-dd @ofirshmuel @jpkrohling
