### ISSUE TITLE
[dynatraceexporter] Failure sending prometheus metrics with value NaN

### ISSUE THREAD

**Issue by lancerdima** [open-telemetry/opentelemetry-collector-contrib#7933]
**Describe the bug**
Failure sending prometheus metrics with value NaN

**Steps to reproduce**
* Collect metrics with prometheus receiver. Metric must be Gauge and has NaN value. (metric on the service is exposed by jmx-prometheus-exporter)
* Use collector to deliver metrics to dynatrace, using dynatraceexporter

**What did you expect to see?**
Metric is delivered to dynatrace

**What did you see instead?**
Error message
```
2022-02-15T11:53:26.561Z    error    dynatraceexporter@v0.42.0/metrics_exporter.go:139    failed to serialize Gauge kafka_consumer_RecordsLag: value is NaN.     {"kind": "exporter", "name": "dynatrace"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/dynatraceexporter.(*exporter).serializeMetrics
    github.com/open-telemetry/opentelemetry-collector-contrib/exporter/dynatraceexporter@v0.42.0/metrics_exporter.go:139
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/dynatraceexporter.(*exporter).PushMetricsData
    github.com/open-telemetry/opentelemetry-collector-contrib/exporter/dynatraceexporter@v0.42.0/metrics_exporter.go:101
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).export
    go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/metrics.go:67
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send
    go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/common.go:232
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
    go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/queued_retry.go:176
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
    go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/metrics.go:134
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
    go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/queued_retry_inmemory.go:105
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume
    go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/internal/bounded_memory_queue.go:99
go.opentelemetry.io/collector/exporter/exporterhelper.(*boundedMemoryQueue).StartConsumers.func2
    go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/internal/bounded_memory_queue.go:78
```

**What version did you use?**
Version: 0.42.0 -> 0.44.0

**What config did you use?**
Config: (e.g. the yaml config file)
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "my-service"
          static_configs:
            - targets: [ "my-service:9102" ]

processors:
  batch:
  memory_limiter:
    ...
  filter:
    ...

exporters:
  dynatrace:
    endpoint: "https://dynatrace-endpoint/api/v2/metrics/ingest"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, filter, batch]
      exporters: [dynatrace]

**Environment**
Container: otel/opentelemetry-collector-contrib:0.42.0

**Additional context**
Other metrics are delivered without issues.

**Comment by jpkrohling** [comment]
cc @dyladan @arminru

**Comment by dyladan** [comment]
Please assign me

**Comment by dyladan** [comment]
Dynatrace cannot accept NaN values. The logging has been modified so that it will not print the error stack trace. I believe this issue can be closed but I don't have permission to close it.

**Comment by lancerdima** [comment]
@dyladan, due to the issue, Dynatrace not just reject metric with the NaN value, but all metrics that share the same name.
Consider this list of metrics below. None of the metrics gets delivered to Dynatrace.
```
kafka_consumer_RecordsLag{client_ID="XXXXX",partition="1",topic="XXX,} NaN
kafka_consumer_RecordsLag{client_ID="XXXXX",partition="2",topic="XXX,} NaN
kafka_consumer_RecordsLag{client_ID="XXXXX",partition="3",topic="XXX,} 0.0
```
That does not seem a valid behavior.

**Comment by dyladan** [comment]
hmm no that is not a valid behavior, thanks for the clarification
