### ISSUE TITLE
[prometheusremotewriteexporter] multi-tenancy support based on labels

### ISSUE THREAD

**Issue by foxlegend** [open-telemetry/opentelemetry-collector-contrib#7945]
**Is your feature request related to a problem? Please describe.**

Cortex and Thanos support multitenancy using a HTTP header (such as "X-Scope-OrgID") or maybe a query parameter (I am thinking about Thanos, but I am not 100% sure about that)..
From my understanding, with the current implementation of the prometheusremotewrite exporter, we should configure an exporter per tenant (by setting the header or the endpoint url).

That means each time we want to add a tenant we should modify collector’s configuration, and we should be aware of all tenants of our infrastructure (I want to say exhaustive).

**Describe the solution you'd like**

A tenant may add (or through an intermediate collector) a label to the metrics representing its name (for instance tenant="123abc"), and the collector may automatically configure the header or the query param accordingly. 

**Describe alternatives you've considered**

There are some projects such as https://github.com/blind-oracle/cortex-tenant which does the same.
I think that instead of adding a new component to the workflow the collector/prometheusremotewrite exporter may perform the same.

**Additional context**

I have a working implementation on my fork: https://github.com/open-telemetry/opentelemetry-collector-contrib/compare/main...foxlegend:prometheusremotewriteexporter-multi-tenant 

It allows to specify the header to insert and the label to use as tenant name.

**Comment by jpkrohling** [comment]
cc @Aneurysm9, @gouthamve

**Comment by Aneurysm9** [comment]
This seems reasonable to me.  We should probably include warnings about the risk of trusting user-provided labels for routing/billing purposes, but I assume that most people configuring this would be doing it in a context where they're operating a Cortex instance for multiple teams in their org and have the ability to hunt down and apply a clue-by-four to offenders :)  Just a note that this is not real AuthN/Z is probably sufficient.

**Comment by politician** [comment]
Possible solution posted [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3121#issuecomment-1084007399)

**Comment by kovrus** [comment]
Hi @foxlegend, can you take a look at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12892 would that address your use case?

**Comment by foxlegend** [comment]
I am sorry for the late reply.

In fact, I was not able to use the extension, as I expected to use a label instead of context metadata to send the metric to a specific tenant, as what https://github.com/blind-oracle/cortex-tenant proposes.

If you have any hint about how to do this, it would be really helpful.

**Comment by salvovitale** [comment]
@foxlegend  any further development on this topic?

**Comment by Aneurysm9** [comment]
Would it make sense to have a processor that can take labels from a metric and add them to context metadata?  That would seem to provide a general solution to this issue that doesn't need to be tied to the PRW exporter.

**Comment by jakubsikorski** [comment]
Reopen. Any update on this? `headers setter` does not help if you want to set a header based on a label

**Comment by zorek187** [comment]
+1
