### ISSUE TITLE
[elasticsearchexporter] Crash when using elasticsearch exporter with traces data

### ISSUE THREAD

**Issue by zhangjiabin1010** [open-telemetry/opentelemetry-collector-contrib#7950]
**Describe the bug**
ElasticSearch exporter crash, when combined with the batch processor.I expect to export traces data into elasticsearch.

**Steps to reproduce**
Collect traces data with OTEL receiver;
Push traces records to elasticsearch.

**What did you expect to see?**
I expect to export traces data into elasticsearch.

**What did you see instead?**
Error: cannot build exporters: pipeline "traces" of data type "traces" has an exporter elasticsearch, which does not support that data type
2022/02/17 14:06:41 collector server run finished with error: cannot build exporters: pipeline "traces" of data type "traces" has an exporter elasticsearch, which does not support that data type

**What version did you use?**
Version: 0.44.0

**What config did you use?**
`receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug

  elasticsearch:
    endpoints:
    - "https://localhost:9200"

processors:
  batch:
  
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging,elasticsearch]
      processors: [batch]
    traces:
      receivers: [otlp]
      exporters: [logging,elasticsearch]
      processors: [batch]`

**Environment**
Windows 10:   otelcol-contrib_0.44.0_windows_amd64

**Additional context**
I know that elasticsearch exporter can be added in logs.
But I want to export traces records data to elasticsearch.
Error found: pipeline "traces" of data type "traces" has an exporter elasticsearch, which does not support that data type.
Is there anything wrong with my thinking? thanks for answer

**Comment by jpkrohling** [comment]
cc @urso @faec @blakerouse

**Comment by JaredTan95** [comment]
Did you try following configs for elasticsearch endpoints?
```yaml
exporters:
  elasticsearch:
    endpoints: [https://elastic.example.com:9200]
```

ref https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/elasticsearchexporter/testdata/config.yaml#L9

**Comment by 991216982** [comment]
Looking forward to

**Comment by JaredTan95** [comment]
`traces` export to elasticsearch supported in 0.60.0 version, https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12069
