### ISSUE TITLE
unknown receivers type "k8s_events" error in v0.45.0

### ISSUE THREAD

**Issue by angelluismula** [open-telemetry/opentelemetry-collector-contrib#7951]
**Describe the bug**
K8s_events receiver doesn't work in v0.44.0 or v0.45.0

**Steps to reproduce**
Run docker image otel/opentelemetry-collector-contrib:0.45.0 with provided config.

**What did you expect to see?**
K8s events logs collected with k8s_events receiver

**What did you see instead?**
`
Error: failed to get config: cannot unmarshal the configuration: unknown receivers type "k8s_events" for "k8s_events" (valid values: [hostmetrics journald splunk_hec tcplog awsecscontainermetrics carbon collectd influxdb kafkametrics kubeletstats prometheus filelog mongodbatlas postgresql sapm udplog otlp apache jmx kafka opencensus prometheus_simple awsxray fluentforward googlecloudspanner k8s_cluster memcached zipkin awscontainerinsightreceiver docker_stats dotnet_diagnostics mysql receiver_creator syslog wavefront windowsperfcounters zookeeper jaeger podman_stats prometheus_exec redis signalfx statsd])
2022/02/17 09:36:25 collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown receivers type "k8s_events" for "k8s_events" (valid values: [hostmetrics journald splunk_hec tcplog awsecscontainermetrics carbon collectd influxdb kafkametrics kubeletstats prometheus filelog mongodbatlas postgresql sapm udplog otlp apache jmx kafka opencensus prometheus_simple awsxray fluentforward googlecloudspanner k8s_cluster memcached zipkin awscontainerinsightreceiver docker_stats dotnet_diagnostics mysql receiver_creator syslog wavefront windowsperfcounters zookeeper jaeger podman_stats prometheus_exec redis signalfx statsd])

`
**What version did you use?**
Version: v0.45.0 or v0.44.0 (installed via opentelemety-collector helm chart v0.9.1)

**What config did you use?**
Config: 
`    receivers:
      k8s_events:

    processors:
      nop:

    exporters:
      logging:

    service:
      pipelines:
        logs:
          exporters: [logging]
          processors: [nop]
          receivers: [k8s_events]
`
**Environment**
OS: Kubernetes 1.21 running docker image linux/amd64 otel/opentelemetry-collector-contrib:0.45.0

**Comment by jpkrohling** [comment]
Looks like this component isn't on the contrib manifest: 

https://github.com/open-telemetry/opentelemetry-collector-releases/blob/beffc4362ba0ed802f023aec44306c6a3219f963/distributions/otelcol-contrib/manifest.yaml#L116-L119

cc @dmitryax
