### ISSUE TITLE
awsprometheusremotewrite sign request with expired credentials

### ISSUE THREAD

**Issue by rafaelpereyra** [open-telemetry/opentelemetry-collector-contrib#7955]
**Describe the bug**
When credentials are managed by an external process (i.e. using env AWS_SHARED_CREDENTIALS_FILE), RoundTripper implementation for AWS Prometheus Remote Write is using expired credentials to sign the Sigv4 request, producing a constant server response of 403 and dropping packages until the collector is restarted and credential file is read again.

**Steps to reproduce**
- Create a valid Credential file with temporary credentials (STS). For this explanation let's assume the credentials expires in 1h.
- Define the environment variable AWS_SHARED_CREDENTIALS_FILE and point it to the path of the credential file.
- Configure the exporter (awsprometheusremotewrite) and start the collector process (the user running the process must have read permissions over the shared credential file).
- Wait until the credentials expires
- 403 errors will start appearing in the logs after the credential is expired. 

`error":"Permanent error: remote write returned HTTP status 403 Forbidden; err = <nil>: {\"message\":\"The security token included in the request is expired\"}`

- Generate a new set of temporary credentials and overwrite the shared credential file. This simulates the external process updating the credentials.
- Wait until the next trip, the error won't change.
- Restart the collector, new credentials are read and metrics pushed as expected.

**What did you expect to see?**
When the credential used to sign the request is expired, I expected the module to re-read the credentials from the chain looking for a set of fresh credentials to use in the signing process and no drop of packages.

**What did you see instead?**
Credential chain is not refreshed when credentials expires.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: "Ubuntu 20.04.3 LTS" and "MacOSX (Monterrey)" 
Compiler(if manually compiled): v0.44.0

**Additional context**

@alolita

**Comment by jpkrohling** [comment]
cc @anuraaga @Aneurysm9 @alolita

**Comment by AustinWentz** [comment]
Hi, we are facing a similar issue when exporting with X-Ray. Temporary shared credentials are expired and refreshed, but they are not picked up by the Collector. Restarting the System D service refreshes the credentials, but obviously this is untenable for anyone using short term credentials. The SDK should be doing this automatically. Any updates?

**Comment by Aneurysm9** [comment]
We've investigated and found that the AWS SDK for Go does not refresh these credentials when they expire and instead treats them as static.  We are exploring options for improving the user experience when temporary shared credentials are used.
