### ISSUE TITLE
v0.45.0 release caused dependencies issues in go.mod

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#7959]
The version for some packages have been missed as part of the v0.45.0 release:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsprometheusremotewriteexporter/go.mod#L7

As a result of the fix here, we should have a mechanism to detect a regression, a CI check would be ideal.

**Comment by bogdandrutu** [comment]
I don't think that is a "downgrade" the `v0.0.0-00010101000000-000000000000` does not exists and users will need a `replace` entry for all of these deps.

Anyway, we need a fix for this.

**Comment by Aneurysm9** [comment]
This was masked in the release build by [replace statements](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml#L144-L151) that should probably not exist there.

**Comment by codeboten** [comment]
> I don't think that is a "downgrade" the `v0.0.0-00010101000000-000000000000` does not exists and users will need a `replace` entry for all of these deps.

Right, I've updated the issue name and description. You're right that this is just the behaviour of go mod when it fails to find a version.

**Comment by tigrannajaryan** [comment]
> a CI check would be ideal.

Yes, otherwise it is hard to catch this manually with hundreds of files touched in the release commit.

**Comment by jpkrohling** [comment]
v0.45.1 was released just now. Do we need binaries and container images? I assume that @Aneurysm9's problems are related only to contrib, not the actual binaries/container images.

**Comment by Aneurysm9** [comment]
I believe that having the fixed `go.mod` files tagged will address the issue we had with the ADOT distribution.  It may still be good to have a binary/container image release as there are other changes from v0.45.0.

**Comment by codeboten** [comment]
This issue has been addressed.
