### ISSUE TITLE
Spans that belong to the same distributed transaction are not consolidated in Elastic APM

### ISSUE THREAD

**Issue by object** [open-telemetry/opentelemetry-collector-contrib#8059]
Since this problem is specific to Elastic APM, I am not sure this is the right place to report it. On the other hand, since this project contains elasticsearchexporter, I decided to register an issue here.

**Problem description**
To test OpenTelemetry distributed tracing, I created a trial account and exported telemetry data from 3 applications: 

- Web client
- Web service
- RabbitMQ message consumer.

To verify traces I exported them to Jaeger, Honeycomb.io and Elastic APM. Jaeger and Honeycomb displayed traces across all 3 applications, while Elastic APM showed spans from Web client and Web app as independent transactions.

**Steps to reproduce**
Sample project that reproduces the issue is located here:
https://github.com/object/OpenTelemetryTracingTest

**What did you expect to see?**
A transaction with spans from Web client, Web service and Queue consumer.

**What did you see instead?**
A transaction for Web client with a single span and another transaction for Web service and Queue consumer.

**What version did you use?**
Version 8.0 of Elastic APM

**What config did you use?**
See the sample project

**Environment**
OS: Windows 10, .NET 6.0

**Additional information**

1. Application traces exported via ConsoleExporter:

- https://www.dropbox.com/s/i957ma2s6fl767y/QueueConsumerTraces.txt?dl=0
- https://www.dropbox.com/s/g89pthx4e58riqi/WebAppTraces.txt?dl=0
- https://www.dropbox.com/s/2ju5k0oikmlu54e/WebClientTraces.txt?dl=0

2. Elastic APM screenshots:

- https://www.dropbox.com/s/pmvymei7hy77ffo/Elastic01.png?dl=0
- https://www.dropbox.com/s/6s87byyvvl8qrm6/Elastic02.png?dl=0
- https://www.dropbox.com/s/tm5vk41vv3impbx/Elastic03.png?dl=0
- https://www.dropbox.com/s/h9xf3ab732hc0a9/Elastic04.png?dl=0
- https://www.dropbox.com/s/nhftbetp8h41r55/Elastic05.png?dl=0
- https://www.dropbox.com/s/26ohu6zsmj9opmf/Elastic06.png?dl=0

3. Jaeger screenshots:

- https://www.dropbox.com/s/vgz636q3aw27a8b/Jaeger01.png?dl=0
- https://www.dropbox.com/s/8f53bct5wb9o77l/Jaeger02.png?dl=0

4. Honeycomb screenshots:

- https://www.dropbox.com/s/cmp9nlluutgkidh/Honeycomb01.png?dl=0
- https://www.dropbox.com/s/sxixqj2i26g1sg1/Honeycomb02.png?dl=0

**Comment by jpkrohling** [comment]
cc @axw @simitt @jalvz

**Comment by axw** [comment]
Apologies for the delay in responding, I've been away from my computer for the past couple of weeks.

@object can you please try with the OTLP exporter, sending directly to Elastic APM Server? See https://www.elastic.co/guide/en/apm/guide/current/open-telemetry.html for example opentelemetry-collector config.

If that doesn't help, please use the opentelemetry-collector logging exporter to dump the OTLP payloads as text. I don't think the ConsoleExporter output you provided is entirely relevant, as the activity IDs don't match the span IDs -- otherwise none of the solutions would work.

**Comment by object** [comment]
@axw You suggest sending traces directly to Elastic APM Server. But am I not doing it already?

Here's the part of my .NET app setup for OpenTelemetry:

```
 builder.AddOtlpExporter(configure =>
    {
        configure.Protocol = OpenTelemetry.Exporter.OtlpExportProtocol.Grpc;
        configure.Endpoint = new Uri("https://my-deployment-5de0aa.apm.westeurope.azure.elastic-cloud.com");
        configure.Headers = $"Authorization=ApiKey <REMOVED>";
    });
```

Isn't this equivalent to what's described in a document you refer to? If not, can you please give me a hint of how I should change it?

**Comment by axw** [comment]
@object ah sorry, it is indeed. I wrongly assumed from the description that you were using opentelemetry-collector-contrib with the elastic exporter. In that case, if you can send to opentelemetry-collector using the logging exporter, that would be most helpful.

**Comment by object** [comment]
Alright, then I will send you more traces today.

**Comment by object** [comment]
@axw I just tried to generate more traces, same problem as before. I had to extend my trial (didn't use organizational ES account) so my deployment URL is now https://f340d99a3a0c44cfa164be5628e051b5.apm.us-central1.gcp.cloud.es.io:443.

When I look at spans sent to Honeycomb I see that all spans are included in a single transaction. In Elastic APM I get one transaction per service.

In case you need more info what should I provide? My test app is very simple, you can easily compile and run it if you have access to .NET development tools.

**Comment by object** [comment]
Hmm, actually it's more complicated than that. When look at transactions at OTel_WebApp (which is Web service in the middle, between OTel_WebClient and OTel_QueueConsumer), I can see that individual transactions includes both spans from OTel_WebApp and OTel_QueueConsumer (but no OTel_WebClient). But if I choose Service Map tab, I get a map of not connected 3 services, and if I choose either of them, the view tells me that this is a single service. Which is not.

**Comment by axw** [comment]
> In case you need more info what should I provide? My test app is very simple, you can easily compile and run it if you have access to .NET development tools.

What I need is a dump of the OTLP payload, using https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/loggingexporter/README.md

I can probably do it myself some time, but may not get to it for some time. If you're able to, that will speed things up.

**Comment by object** [comment]
@axw I couldn't use the LoggingExporter with my samples because it's writting in Go and I couldn't set up my .NET applications to use it. However I made another attempt using .NET Console exporter and it does seem to do the job. I am able to trace spans across all 3 applications.

For example:

First app: WebClient

Activity.Id:          00-45afddb76e661b54c8ec735e1d3bb8fd-eae67457154988ba-01
Activity.DisplayName: word_activity_1

Activity.Id:          00-45afddb76e661b54c8ec735e1d3bb8fd-2a81b99827a911de-01
Activity.ParentId:    00-45afddb76e661b54c8ec735e1d3bb8fd-eae67457154988ba-01
Activity.DisplayName: HTTP GET

Second app: WebApp


Activity.Id:          00-45afddb76e661b54c8ec735e1d3bb8fd-b0e2838c556ddb5d-01
Activity.ParentId:    00-45afddb76e661b54c8ec735e1d3bb8fd-2a81b99827a911de-01
Activity.DisplayName: /word

Activity.Id:          00-45afddb76e661b54c8ec735e1d3bb8fd-16a1f7a2d85cd535-01
Activity.ParentId:    00-45afddb76e661b54c8ec735e1d3bb8fd-b0e2838c556ddb5d-01
Activity.DisplayName: get_word

Activity.Id:          00-45afddb76e661b54c8ec735e1d3bb8fd-2784a4ba2c3c95e7-01
Activity.ParentId:    00-45afddb76e661b54c8ec735e1d3bb8fd-16a1f7a2d85cd535-01
Activity.DisplayName: mq_publish

Third app: QueueConsumer

Activity.Id:          00-45afddb76e661b54c8ec735e1d3bb8fd-fc997ff38c4ae578-01
Activity.ParentId:    00-45afddb76e661b54c8ec735e1d3bb8fd-2784a4ba2c3c95e7-01
Activity.ActivitySourceName: MessageHandler
Activity.DisplayName: mq_receive

As you can see, each next span uses previous activityId as parentId. So they all should be included in a single distributed transaction. And they are not.

Here are the trace file:

https://www.dropbox.com/s/6ldxnzhsd30bcy5/WebClientTraces.txt?dl=0
https://www.dropbox.com/s/j4p4ig1ycyvc1im/WebAppTraces.txt?dl=0
https://www.dropbox.com/s/453da4nl40hw1w4/QueueConsumerTraces.txt?dl=0

**Comment by simitt** [comment]
@object would you mind also sharing the documents that end up in Elasticsearch for these transactions? As you mentioned, the `id` / `parent.id` connection looks right, therefore I'd like to take a look at the discrepancy after indexing into Elasticsearch.

**Comment by JaredTan95** [comment]
@object any progress mentioned above about sharing some documents in Elasticsearch?
