### ISSUE TITLE
[exported/datadog] Failed to get config: cannot unmarshal the configuration: unknown exporters type "datadog" for "datadog"

### ISSUE THREAD

**Issue by TriQuach** [open-telemetry/opentelemetry-collector-contrib#8109]
**Describe the bug**
When adding `datadog` as an exporter in the config file and deploying with our serverless app, it raised:
> Failed to start the extension: failed to get config: cannot unmarshal the configuration: unknown exporters type "datadog" for "datadog" (valid values: [otlp otlphttp awsxray awsemf awsprometheusremotewrite prometheus logging])

**Steps to reproduce**
In the AWS lambda that we want to deploy:
1. Set the `Layers` to: `arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python38-amd64-ver-1-9-1:1`
2. Set these two Environment variables for the lambda 
 - `AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument`
 - `OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/config.yaml`
3. Invoke the lambda, it raised that error

**What did you expect to see?**
The lambda works well without errors

**What did you see instead?**
```
2022/02/23 00:21:26 [collector] Launching OpenTelemetry Lambda extension, version:  v0.1.0
2022/02/23 00:21:26 Using config file at path /var/task/config.yaml
2022/02/23 00:21:26 Failed to start the extension: failed to get config: cannot unmarshal the configuration: unknown exporters type "datadog" for "datadog" (valid values: [otlp otlphttp awsxray awsemf awsprometheusremotewrite prometheus logging])

EXTENSION	Name: collector	State: Started	Events: []
```

**What version did you use?**
We are using the layer from this page: https://aws-otel.github.io/docs/getting-started/lambda/lambda-python. It's saying that: `ADOT Collector for Lambda v0.16.0`

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  datadog:
    api:
      key: "our_api_key"
service:
  extensions:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [datadog]
```

**Environment**
OS: Ubuntu 18.04.4 LTS

**Additional context**
We deploy our serverless app, and invoke the lambda through an API. We haven't started a Datadog agent. The config file works well for Honeycomb and AWS X-ray

In this issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1336, it is said that Datadog exporter will be available in 0.14 release. The collector version we're using is 0.16

**Comment by mx-psi** [comment]
Per the

>  (valid values: [otlp otlphttp awsxray awsemf awsprometheusremotewrite prometheus logging])

line, I would say you are not using the ADOT distro since there are [quite a few exporters](https://github.com/aws-observability/aws-otel-collector#adot-collector-built-in-components) that are supported by ADOT but not present in that list. Are you maybe using the AWS 'OpenTelemetry Collector Lambda Extension'?

I am not familiar with the Lambda extension, maybe @Aneurysm9 or @alolita can expand on this? (Also, this should probably be transferred to an AWS repo, since it's distro-specific, but I don't know if Github would allow it)

**Comment by TriQuach** [comment]
> Per the
> 
> > (valid values: [otlp otlphttp awsxray awsemf awsprometheusremotewrite prometheus logging])
> 
> line, I would say you are not using the ADOT distro since there are [quite a few exporters](https://github.com/aws-observability/aws-otel-collector#adot-collector-built-in-components) that are supported by ADOT but not present in that list. Are you maybe using the AWS 'OpenTelemetry Collector Lambda Extension'?
> 
> I am not familiar with the Lambda extension, maybe @Aneurysm9 or @alolita can expand on this? (Also, this should probably be transferred to an AWS repo, since it's distro-specific, but I don't know if Github would allow it)

Thanks for your support. According to [AWS Distro for OpenTelemetry Lambda Support For Python](https://aws-otel.github.io/docs/getting-started/lambda/lambda-python), the lambda layer we are using contains:
1. [OpenTelemetry Python v1.9.1](https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.9.1) with the [AWS Python Extension v2.0.1](https://github.com/open-telemetry/opentelemetry-python-contrib/releases/tag/opentelemetry-sdk-extension-aws%3D%3D2.0.1)
2. The [ADOT Collector for Lambda v0.16.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/pkg%2Flambdacomponents%2Fv0.16.0)

So I assume that we are using both ADOT and Lambda Extension. But I just found this on that page:
> In this section, we consume the Lambda layer for use with Python Lambda Functions. This includes a **reduced version** of the AWS Distro for OpenTelemetry Collector (ADOT Collector)

By _reduced version_, does it mean that there are some exporters that are not supported like you said?

**Comment by Aneurysm9** [comment]
I looks like I can only transfer this issue to another repository in the OpenTelemetry organization.  

The OTel Lambda layer collector has a [small set of supported components](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/lambdacomponents/default.go#L44-L49) to minimize the footprint of the layer in consideration of the size constraints on overall size of Lambda function packages.  The ADOT-provided Lambda layer [expands that set slightly](https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/lambdacomponents/defaults.go#L46-L54) to allow direct export to some AWS services.  

If you need to export to a destination that is not directly supported (such as through accepting OTLP) then  one option is to export from your Lambda functions via OTLP to a full-featured collector instance that can handle the export to the ultimate destination.

**Comment by TriQuach** [comment]
> I looks like I can only transfer this issue to another repository in the OpenTelemetry organization.
> 
> The OTel Lambda layer collector has a [small set of supported components](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/lambdacomponents/default.go#L44-L49) to minimize the footprint of the layer in consideration of the size constraints on overall size of Lambda function packages. The ADOT-provided Lambda layer [expands that set slightly](https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/lambdacomponents/defaults.go#L46-L54) to allow direct export to some AWS services.
> 
> If you need to export to a destination that is not directly supported (such as through accepting OTLP) then one option is to export from your Lambda functions via OTLP to a full-featured collector instance that can handle the export to the ultimate destination.

Thanks for the response. I guess we were a bit confused because this issue #1336 says that the datadog exporter should be available in the collector

**Comment by mx-psi** [comment]
> I guess we were a bit confused because this issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1336 says that the datadog exporter should be available in the collector

There are different [distributions](https://opentelemetry.io/docs/collector/distributions/) of the OpenTelemetry Collector, for example, to name a few mentioned on this issue:
- [core opentelemetry-collector distro](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.45.0), which has a reduced set of core components.
- [opentelemetry-collector-contrib distro](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.45.0), which includes every component on this repository.
- [AWS Distro for OpenTelemetry](https://aws-otel.github.io/), which is AWS-specific
- [AWS Distro for OpenTelemetry Lambda](https://aws-otel.github.io/docs/getting-started/lambda)

Distros have different components available and may also differ in other features. Issue #1336 refers to the opentelemetry-collector-contrib distro. Of the distros mentioned above, the Datadog exporter is available in the opentelemetry-collector-contrib one as well as in the AWS Distro for OpenTelemetry.

**Comment by mx-psi** [comment]
Closing this since it was clarified that vendor-specific exporters like Datadog's are not available on the ADOT lambda distro.
