### ISSUE TITLE
Docker image "lastest" not up to date

### ISSUE THREAD

**Issue by tonglil** [open-telemetry/opentelemetry-collector-contrib#8185]
I noticed today and confirmed that the `latest` image on Docker Hub is not being updated.

https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/3250776/156092194-21551082-2dc2-41e3-be8c-c63e32dda419.png">

Also:

> Hi @Nighttraveler, please try using a later version. It appears the `latest` tag hasn't been updated with the latest versions: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/73
> 
> `otel/opentelemetry-collector-contrib:0.45.0` should work
> 
> _Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7543#issuecomment-1043473871_

**Comment by tonglil** [comment]
Also there seem to be some quirks between the images that were built by `opentelemetrybot` and @bogdandrutu.

The `latest` image (which is actually https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/6a1c2471092b7f62ad1a37f62cbb7b0179676d01) and `0.42.0` images are strange to reason about, given they are suppose to be the same (0.42.0 == 6a1c247).

```
docker run --rm otel/opentelemetry-collector-contrib:latest -v
otelcontribcol version 6a1c247
```

```
docker run --rm otel/opentelemetry-collector-contrib:0.42.0 -v
otelcol-contrib version 0.42.0
```

However, if you run the `latest` image, it doesn't have the problem of spamming output with DEBUG level metrics (https://github.com/open-telemetry/opentelemetry-collector/issues/2212), while if you run the `0.42.0` image, it does have that behavior.

I noticed this because mutual TLS for OTLP receiver was working for `latest` image, but stopped working when I tried to use the newer images, and as I iterated back to the `0.42.0` tag it is still not working for `0.42.0` tag, but works for the `0.40.0` tag.

**Comment by jpkrohling** [comment]
I'm closing this in favor of https://github.com/open-telemetry/opentelemetry-collector-releases/issues/73. We basically switched the way we build the images, and they are now being published via the -releases repo. What you are seeing is likely a different difference in behavior (or bug), not related to how the images are being built.

Please, open a new issue with the mTLS problems you are facing. I tested mTLS recently and confirmed it to be working: https://github.com/open-telemetry/opentelemetry-collector/issues/4676

**Comment by tonglil** [comment]
Thanks.

I realized the mTLS issue was a red herring for the image's entrypoint and cmd being changed from
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/317d2056d6f26aa39b26bf0f05a2f1e0068add5d/cmd/otelcontribcol/Dockerfile#L14-L15

To
https://github.com/open-telemetry/opentelemetry-collector-releases/blob/694055d71c7c5bd7c61ab1015be8f56f5575192a/distributions/otelcol-contrib/Dockerfile#L18-L19
