### ISSUE TITLE
Prometheus dependency is really old

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#8243]
**Description**

We [are on](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/go.mod#L11) version v1.8.2 of prometheus, which is from 2017.  We may see better performance, etc. if we update.

**Comment by dashpole** [comment]
cc @Aneurysm9

**Comment by jpkrohling** [comment]
I thought @gouthamve changed this already?

**Comment by mx-psi** [comment]
We are not using v1.8.2, we are pinning this commit: prometheus/prometheus@4855a0c067e2 from Jan 17th 2022. `v1.8.2-0.20220117154355-4855a0c067e2` is a [pseudo-version](https://go.dev/ref/mod#pseudo-versions). We can't use an actual version because of prometheus/prometheus#8852

**Comment by kwiesmueller** [comment]
That's interesting.
I updated Prometheus yesterday for our 0.37.0 fork and there I had to make a few changes to imports to make it possible.
Maybe that was before you changed your pinned commit.
