### ISSUE TITLE
Logging CI Improvements

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-collector-contrib#8260]
There are some improvements we can do for logging tests.
* using dedicated host for performance sensitive tests.
* Adding new stability test cases

Please take a look at this doc and let's discuss. 
https://docs.google.com/document/d/167J-jkqwIG_H7qq8iTrYFikVF-ULJb1xit0IecG0FCY/edit#heading=h.fqrcxtvpgibe

**Comment by jpkrohling** [comment]
> using dedicated host for performance sensitive tests.

For this, we can probably use CNCF's pool of bare metal servers at Equinix.
