### ISSUE TITLE
jaeger span is in error if tag error=false AND http.status_code >=400 

### ISSUE THREAD

**Issue by ecourreges** [open-telemetry/opentelemetry-collector-contrib#8273]
**Describe the bug**
If I have a tag http.status_code >=400 _and_ a tag error=false on my Span, a tag error=true gets added (so I now have two attributes error with one true and one false) and the overall status of the span switches to error with a tag otel.status_code = ERROR  
Short story: In my app, I don't want client errors to popup as span errors, I want that only for server errors, so I set the error tag explicitly and wish it to be respected at all times.

1. We don't want the http status to override an error explicitly set to false: this is a bug in my opinion and does not seem intended. 
    -  The bug is I think in [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/579334c559a687b6c41341b62e55a60732a2329c/pkg/translator/jaeger/jaegerproto_to_traces.go#L204) where stuff is set only if error=true
    - I may provide a PR for this but I don't have time before end of March so if you want to take care of it, thanks!
2.  There are no docs describing the behavior of automatically relying on the http status code to determine if the span is in error or not. The [README.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/jaegerreceiver/README.md) should have a section at the end describing the translations performed.
3.  There are no logs in the collector showing why the translation was performed, maybe in debug/info log there needs to be something, because here it took me a while to realize that http.status_code=400 was the culprit.

**Environment**
jaeger-client-cpp 0.6.0 -> otelcol-contrib 0.45.0 on jaeger receiver thrift_compact

**Comment by ecourreges** [comment]
Note that the double "error" attribute is only when viewed on jaeger, not in the logging span of the collector:

``` 
Span #4
    Trace ID       : 0000000000000000dc78c3a8bb270073
    Parent ID      : 
    ID             : dc78c3a8bb270073
    Name           : GET /pns/v3/users/{credentialType}/{credentialValue}
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2022-03-07 14:42:16.989341 +0000 UTC
    End time       : 2022-03-07 14:42:16.990673 +0000 UTC
    Status code    : STATUS_CODE_ERROR
    Status message : 
Attributes:
     -> sampler.type: STRING(probabilistic)
     -> sampler.param: DOUBLE(1)
     -> m_req_ok: STRING(OK)
     -> error: BOOL(false)
     -> error.code: INT(13)
     -> error.message: STRING(Invalid Credential Value)
     -> error.description: STRING(A credential value given by the client does not conform to the validation function of this credential type)
     -> http.status_code: INT(400)
```
![image](https://user-images.githubusercontent.com/2752411/157057209-54dbadd0-1cfa-47bb-9a19-9d9bb8cd1043.png)

**Comment by jpkrohling** [comment]
> I may provide a PR for this but I don't have time before end of March so if you want to take care of it, thanks!

I've assigned this to me, but I also don't have time over the next couple of weeks to work on this. If we have volunteers, feel free to grab this.

**Comment by shree007** [comment]
@jpkrohling Please assign me, I may work on it.

**Comment by frzifus** [comment]
Hi guys, I had a look on that and created a pr to the best of my knowledge. Would be nice to get some feedback. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12753

**Comment by jpkrohling** [comment]
@markdingram, are you suggesting a change to the [nginx-opentracing](https://github.com/opentracing-contrib/nginx-opentracing) repository?

**Comment by ecourreges-orange** [comment]
> @markdingram, are you suggesting a change to the [nginx-opentracing](https://github.com/opentracing-contrib/nginx-opentracing) repository?

I think @markdingram is suggesting to add the same logic of nginx-opentracing to opentelemetry-collector-contrib, which could be nice indeed to avoid too many unjustified error=true,  but this is a nice to have that goes above the requirements of my issue, and applies for cases where the error is not yet set in the span.

But @jpkrohling I also agree with you in the sense that if the error status is already set (whether http 200 or whatever), the error status should not be tampered with by the collector and it was the idea behind me filing the issue.

**Comment by suraciii** [comment]
According to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status
> For HTTP status codes in the 4xx range span status MUST be left unset in case of `SpanKind.SERVER` and MUST be set to `Error` in case of `SpanKind.CLIENT`.

**Comment by jpkrohling** [comment]
cc @frzifus for visibility

**Comment by jpkrohling** [comment]
@frzifus, are you able to handle this one?

**Comment by frzifus** [comment]
i will give an update by the end of tomorrow.

**Comment by frzifus** [comment]
I have tried to get everything in shape. In order for the tests to run, the signatures still need to be adjusted. Could someone roughly review the logic? Maybe it is not quite correct. I will look at it tomorrow with clearer eyes. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12753
