### ISSUE TITLE
update `opentelemetry-operations-go/exporter/collector` library

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#8335]
The error in the library is causing `make update-otel` to fail. This will need to be resolved before the next release.

Related: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/329

**Comment by dashpole** [comment]
Let me know if you would like me to handle this as well (bogdan asked me to bump after https://github.com/open-telemetry/opentelemetry-collector/pull/4914).  I've been working in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8316, but if you want to tackle it, thats also fine.

**Comment by codeboten** [comment]
happy to re-assign and review :)
