### ISSUE TITLE
[prometheusreceiver] Support exemplars from Prometheus

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#8353]
**Is your feature request related to a problem? Please describe.**
Currently, the prometheus receiver drops prometheus exemplars: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5cd8dd90659779c0d6f99873de71144a2d5235d1/receiver/prometheusreceiver/internal/otlp_transaction.go#L103-L105

**Describe the solution you'd like**
As described in the [prometheus conversion specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification%2Fmetrics%2Fdatamodel.md#exemplars-1), exemplars on prometheus metrics should be converted to exemplars in OpenTelemetry.

**Comment by dashpole** [comment]
Fixed by #12987

**Comment by bboreham** [comment]
This should be re-opened, as #12987 was reverted in #14000.

**Comment by jeromeinsf** [comment]
What's left to do after https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14132 ?
