### ISSUE TITLE
New component: Varnish Metric Receiver

### ISSUE THREAD

**Issue by JonathanWamsley** [open-telemetry/opentelemetry-collector-contrib#8354]
## The purpose and use-cases of the new component

This Varnish Cache Metric Receiver will collects metrics using the [varnishstat](https://varnish-cache.org/docs/7.0/reference/varnishstat.html#varnishstat-1) command. It will generate backend, cache, thread and session metrics.

This Varnish Cache receiver will collect metrics for [supported versions](https://varnish-cache.org/releases/) 6.0.10+ - 7.0.2+ 

## Example configuration for the component
The following configuration settings are optional:

- `collection_interval` (default = 10s): This receiver collects metrics on an interval. Valid time units are ns, us (or µs), ms, s, m, h.
- `working_dir` (Optional): The -n flag used in [varnishstat](https://varnish-cache.org/docs/7.0/reference/varnishstat.html#description) to get logs from a varnishd working directory.
- `executable_dir` (Optional): The directory where the varnishadm and varnishstat executables are located. 

### Example Configuration
```yaml
receivers:
  varnish:
    collection_interval: 30s
```

## Telemetry data types supported

Metrics

**Comment by djaglowski** [comment]
Can you elaborate on the usage of `executable_dir`? If not specified, is there a default, or does the executable need to be in the path?

**Comment by djaglowski** [comment]
It looks like `varnishstat` can operator as a long or short running process (short running if using `-1`) flag.

@jpkrohling, not sure if you agree, but IMO, if this is a scraper that runs an executable that is not expected to run indefinitely, then I think it probably does not need to be managed by an extension. 

Either way, this is an important detail to note here. @JonathanWamsley, can you clarify whether this would use that flag or not?

**Comment by djaglowski** [comment]
Discussed in the Collector SIG today. 

The primary concern is security related. It was decided a few weeks back that any existing components that run a subprocess will be made as secure as possible. Once that has been done, it will be evaluated whether or not subprocesses can be secured in a generic way, such as discussed in #6467.

**Comment by JonathanWamsley** [comment]
> Can you elaborate on the usage of `executable_dir`? If not specified, is there a default, or does the executable need to be in the path?

When the `varnishstat` is not in the user's path then an executable directory can be specified.
`/executable/path/varnishstat -n` statement can be used to collect the metrics. I don't think it is safe to assume that 'varnishstat' would always be in the user's path.
