### ISSUE TITLE
[prometheusexporter] Add job and instance labels to match federated prometheus

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#8355]
**Description**
As described in the [OpenTelemetry -> prometheus conversion specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification%2Fmetrics%2Fdatamodel.md#resource-attributes-1), prometheus exporters must add job and instance labels to exported metrics in the collector:

> In the collector Prometheus exporters, the service.name and service.namespace attributes MUST be combined as <service.namespace>/<service.name>, or <service.name> if namespace is empty, to form the job metric label. The service.instance.id attribute, if present, MUST be converted to the instance label; otherwise, instance should be added with an empty value.

This allows a user to scrape the prometheuxexporter's endpoint with `honor_labels: true` to preserve the original job and instance labels as described in https://prometheus.io/docs/prometheus/latest/federation/#configuring-federation.

Currently, the prometheus exporter only adds metric attributes: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5cd8dd90659779c0d6f99873de71144a2d5235d1/exporter/prometheusexporter/collector.go#L82-L98

**Comment by gouthamve** [comment]
Hi, I am working on this issue. Just to make sure there are not others working on it as well :)
