### ISSUE TITLE
New component: IIS Metric Receiver

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-collector-contrib#8370]
## The purpose and use-cases of the new component

The IIS Metric Receiver would pull KPI stats from windows performance counters using the `windowsperfcountersreceiver` as a base to build off of. 

Targeted versions would be IIS 8+ because IIS 7- are [EOL](https://docs.microsoft.com/en-us/lifecycle/products/internet-information-services-iis)

## Example configuration for the component

`collection_interval` (default = `10s`): This receiver collects metrics on an interval. Valid time units are ns, us (or µs), ms, s, m, h.

```yaml
receivers:
  iis:
    collection_interval: 10s
```

## Telemetry data types supported

Metrics

**Comment by djaglowski** [comment]
I would like to sponsor this.

@open-telemetry/collector-contrib-maintainer, any reservations about adding a component that depends on another like this? Technically, the collector already supports the ability to collect whatever metrics this one would, but having them predefined in a turnkey solution is a huge value to users. My understanding is that the collector is [designed to support this](https://github.com/open-telemetry/opentelemetry-collector/blob/9d3a8a4608a7dbd9f787867226a78356ace9b5e4/component/host.go#L33).

**Comment by codeboten** [comment]
> I would like to sponsor this.
> 
> @open-telemetry/collector-contrib-maintainer, any reservations about adding a component that depends on another like this? Technically, the collector already supports the ability to collect whatever metrics this one would, but having them predefined in a turnkey solution is a huge value to users. My understanding is that the collector is [designed to support this](https://github.com/open-telemetry/opentelemetry-collector/blob/9d3a8a4608a7dbd9f787867226a78356ace9b5e4/component/host.go#L33).

I think there's already precedent for this in the collector, for example the `simpleprometheusreceiver` exposes a subset of the `prometheusreceiver`. I think this component would be fine.
