### ISSUE TITLE
Exporting failed: span tag key/value cannot be blank

### ISSUE THREAD

**Issue by syamalaids** [open-telemetry/opentelemetry-collector-contrib#8374]
**Describe the bug**
I have instrumented my application with open telemetry. Once in a while I get the following error. Puzzling thing is it does not give me a clue which span is causing the issue. Could you guide me how I can find that out or get more details on the error?

I am using TanzuObservabilityExporter.

![image](https://user-images.githubusercontent.com/54188587/157660944-e87b5629-1091-4a37-b2c0-0c17cb6f2f0c.png)

![image](https://user-images.githubusercontent.com/54188587/157660965-fc098e40-eb94-44b1-8955-c3ec87be7932.png)

**What version did you use?**
[v0.42.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.42.0)

**What config did you use?**
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    logLevel: debug
    
  # Data sources: traces, metrics, logs
  file:
    path: ./collector.json
    
  tanzuobservability:
    traces:
    #hostname and  'customeTracingListenerPorts' of the Wavefront Proxy
       endpoint: "http://dev-proxy-temp.cyracomdev.com:30001"
       

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, tanzuobservability]
      processors: [batch]

**Environment**
OS: Windows Server 2012 R2 standard.
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by jpkrohling** [comment]
cc  @oppegard @thepeterstone @keep94

This message seems to be coming from a dependency of the Tanzu Observability Exporter:

```
$ go mod vendor
$ grep "cannot be blank" . -r
./vendor/github.com/wavefronthq/wavefront-sdk-go/senders/formatter.go:			return "", errors.New("metric point tag value cannot be blank")
./vendor/github.com/wavefronthq/wavefront-sdk-go/senders/formatter.go:			return "", errors.New("histogram tag value cannot be blank")
./vendor/github.com/wavefronthq/wavefront-sdk-go/senders/formatter.go:			return "", errors.New("span tag key/value cannot be blank")
```

**Comment by thepeterstone** [comment]
Thanks @syamalaids for the detailed report and @jpkrohling for the triage! I'll get a fix prioritized.

**Comment by oppegard** [comment]
@syamalaids we're going to improve the error message, but also check if there are empty span tags and drop them, so that the rest of the span can be exported to Wavefront.

In the meantime, I see you've enabled the Collector's logging exporter with debug level. You can search for `STRING()` in the log output and identify which span attributes/tags are empty. Once you've done that, you can use the [attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor) to delete the empty attributes or provide default values.

**Comment by syamalaids** [comment]
@oppegard  Thank you I was able to find the culprit by searching for STRING(). I no longer see this error.

**Comment by jpkrohling** [comment]
Based on the last message, I assume this has been sorted out. I'm closing this issue.
