### ISSUE TITLE
New component: Add Apache Druid Metric Receiver

### ISSUE THREAD

**Issue by rahulbandariSensei** [open-telemetry/opentelemetry-collector-contrib#8466]
## The purpose and use-cases of the new component
Apache Druid Receiver(`apachedruid`) listens on for the metrics emitted by the apache druid endpoint as mentioned in [metrics page](https://druid.apache.org/docs/latest/operations/metrics.html) and generates all the metrics related to different sub-components of a druid cluster.
## Example configuration for the component

```yaml
receivers:
   apachedruid:
    emitterport: 8911
```

## Telemetry data types supported
Metrics Emitted by the apache druid (https://druid.apache.org/docs/latest/operations/metrics.html) would be supported here. 
Will update the names shortly.

**Comment by dmitryax** [comment]
I can sponsor this component. I have experience with Druid
