### ISSUE TITLE
[prometheusreceiver] Staleness Markers for histogram buckets and summary quantiles

### ISSUE THREAD

**Issue by gracewehner** [open-telemetry/opentelemetry-collector-contrib#8492]
**Describe the bug**
Querying the histogram buckets or summary quantiles for a metric displays incorrectly due to those samples not having the stale NaNs set as their value. For example `<histogram_name>_bucket` displays the same value for 5 minutes instead of cutting off when stale whereas `<histrogram_name>_sum` and `<histogram_name>_count` (and the +Inf bucket) display correctly. The 5 minutes of the same value is due to PromQL handling the metric as stale after 5 minutes of no new samples. 

`<histogram_name>_bucket{le=50}` :
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/21349004/158491774-b6fdf4ce-0ba6-41c4-b894-14d2330a40cb.png)
vs. `<histogram_name>_count`:
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/21349004/158491844-70de7c31-bdab-4eae-a014-5c6b0cf3039e.png)

I have verified that when using Prometheus, these display correctly and the same way as `<histogram_name>_sum` and `<histogram_name>_count`. This bug does not have a large impact since these are only useful when queried using range vectors, [which ignore staleness markers](https://www.robustperception.io/staleness-and-promql), for functions like histogram_quantile, but we should still fix to match Prometheus functionality.

This issue is due to the Prometheus Receiver not sending any of the buckets (or quantiles) when sum or count have a stale NaN value and the stale flag is set. The bucket values don't matter, but if we don't send them, then the Prometheus Remote Write Exporter won't ever set a stale NaN value for them.

For histograms:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fa86bb0710afde8cfb00f8413df3e0d62f94d29e/receiver/prometheusreceiver/internal/otlp_metricfamily.go#L147-L154

And similarly for summaries:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fa86bb0710afde8cfb00f8413df3e0d62f94d29e/receiver/prometheusreceiver/internal/otlp_metricfamily.go#L183-L194

The Prometheus Remote Write Exporter has logic to set the stale NaN values for buckets and quantiles, but since the receiver isn't sending any buckets/quantiles, these values aren't actually being set:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fa86bb0710afde8cfb00f8413df3e0d62f94d29e/pkg/translator/prometheusremotewrite/helper.go#L324-L335

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fa86bb0710afde8cfb00f8413df3e0d62f94d29e/pkg/translator/prometheusremotewrite/helper.go#L443-L451

Instead the stale NaN is only set for sum, count, and the +Inf bucket, which are the same metrics which are being displayed correctly when stale.

I have tested that changing the lines above in otlp_metricfamily fixes the issue. I will make a PR for this, but I wanted to get opinions on what exactly we want to change. Do we want to remove the else statement and send everything, even sum and count which have the stale NaN value? Or set just the explicit bounds and bucket counts since sum and count are already handled in the exporter?

**Comment by Aneurysm9** [comment]
I don't believe that we can set the stale `NaN` value for bucket counts as those are `int64` values that cannot hold a `NaN`.  The same applies to the `count` field.  It ends up treated as a very large integer value, which is probably even worse than the receiving end carrying the last known value.

Would it work to set just the bucket bounds but no values?  Summary quantile values might be more problematic since they're combined into a single struct.
