### ISSUE TITLE
Update branch protection

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#8553]
As per the description in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8550:
> In order to merge this PR, an admin for the repo will need to change the branch protection rules for main to require the build-and-test / unittest (1.18) and build-and-test / unittest (1.17) checks instead of the unittest check.

Assigning @bogdandrutu as I don't know if any other maintainers have access to update branch protection.

**Comment by tigrannajaryan** [comment]
I don't see build-and-test / unittest (1.18) and build-and-test / unittest (1.17) in the available github actions to add:
![image](https://user-images.githubusercontent.com/4194920/159567933-570bc452-a9c6-4ced-ad03-e1798a4f6ea6.png)

Are they supposed to be available now or only after https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8550 is merged?

**Comment by codeboten** [comment]
🤔 I would have expected them to be available after the tests were run in that PR. See https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5607180104?check_suite_focus=true

**Comment by tigrannajaryan** [comment]
They are not in the dropdown list. I can check again after the PR is merged.

**Comment by mx-psi** [comment]
> They are not in the dropdown list. I can check again after the PR is merged.

The PR can't be merged (except if it's force-merged) since the name of the `unittest` job changed, so it is forever waiting:

![image](https://user-images.githubusercontent.com/5502710/160145856-c4a9ee57-13f2-47ed-965f-55f379b29756.png)

**Comment by jpkrohling** [comment]
The way I typically solved this in the past is by removing the deprecated/old check, merging the PR, adding the new required check.

**Comment by codeboten** [comment]
This has been done
