### ISSUE TITLE
[exporter/datadog] Doesn't Exports AggregationTemporality.Cumulative Metrics to Backend

### ISSUE THREAD

**Issue by omamoo** [open-telemetry/opentelemetry-collector-contrib#8556]
**Describe the bug**
While configuring the Open Telemetry metrics at Asp.Net web (based on .NET6 )application as above:
```
meterProviderBuilder.AddOtlpExporter(
                                (otlpExporterOptions, metricReaderOptions) =>
                                {
                                    otlpExporterOptions.Endpoint = openTelemetryCollectorUri;
                                    metricReaderOptions.MetricReaderType = Periodic;
                                    metricReaderOptions.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = (int)30.Seconds().TotalMilliseconds;
                                });
```

The metrics are been collected by open telemetry exporter and sent to the open telemetry collector. **But** only the first's metrics measurement are been sent to datadog backend, and the following measurements does not sent to datadog backend. 

**However**:
 when configuring the Open Telemetry metrics at Asp.Net as above (note to the `AggregationTemporality.Delta`):
```
meterProviderBuilder.AddOtlpExporter(
                                (otlpExporterOptions, metricReaderOptions) =>
                                {
                                    otlpExporterOptions.Endpoint = openTelemetryCollectorUri;
                                    metricReaderOptions.MetricReaderType = Periodic;
                                    metricReaderOptions.Temporality = AggregationTemporality.Delta;
                                    metricReaderOptions.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = (int)30.Seconds().TotalMilliseconds;
                                });
```

The metrics are been collected and exported as expected. 

**Steps to reproduce**
1. Create a simple web application with one end-point. 
2. Configure the open telemetry metrics as shown above: 
```
meterProviderBuilder.AddOtlpExporter(
                                (otlpExporterOptions, metricReaderOptions) =>
                                {
                                    otlpExporterOptions.Endpoint = openTelemetryCollectorUri;
                                    metricReaderOptions.MetricReaderType = Periodic;
                                    metricReaderOptions.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = (int)30.Seconds().TotalMilliseconds;
                                });
```
3. At the end-point export some metric measurement.
4. Run the application and execute the end-point once.
5. Wait to see the metric at DD backend.
6. Execute the end-point once again, wait to see the new measurement at DD backend.. which will not appear.
7. Configure again the metrics with the `metricReaderOptions.Temporality = AggregationTemporality.Delta;` as shown above.
8. Execute the end-point once again, and you'll see it at DD backend.

**What did you expect to see?**
I did expect to see the metrics measurements at Datadog backend although the  Temporality is cumulative, or at least to see instructions at the documents that asking to configure metrics temporality to be configured as Delta and no Cumulative.

**What did you see instead?**
No instructions about the temporality of the metrics, nor new metrics measurements at Datadog backend when to temporality was configured as `Cumulative`

**What version did you use?**
Version: `v0.45.0`

**What config did you use?**
Config: 
```
{
  "exporters": {
	"datadog": {
	  "api": {
		"key": "**********",
		"site": "datadoghq.com"
	  },
	  "env": "Dev",
	  "metrics": {
		"resource_attributes_as_tags": true
	  }
	}
  },
  "processors": {
	"batch": {
	  "timeout": "10s"
	},
	"memory_limiter": {
	  "check_interval": "5s",
	  "limit_mib": 800,
	  "spike_limit_mib": 256
	}
  },
  "receivers": {
	"otlp": {
	  "protocols": {
		"grpc": null
	  }
	}
  },
  "service": {
	"pipelines": {
	  "metrics": {
		"receivers": [
		  "otlp"
		],
		"processors": [
		  "batch",
		  "memory_limiter"
		],
		"exporters": [
		  "datadog"
		]
	  },
	  "traces": {
		"receivers": [
		  "otlp"
		],
		"processors": [
		  "batch",
		  "memory_limiter"
		],
		"exporters": [
		  "datadog"
		]
	  }
	}
  }
}
```

**Environment**
OS: Alpine 3.15, docker image
Compiler: `.NET 6.0.201`

**Comment by mx-psi** [comment]
Hi @omamoo, thanks for your issue. 

As described in [the official documentation](https://docs.datadoghq.com/metrics/otlp/?tab=sum), cumulative types are supported, and the behavior is to calculate the delta between points and report the difference. Note that **the first point for cumulative metrics is not currently reported**, to avoid spikes on the backend. 

You should see the same values as with delta aggregation temporality, so this is a bug, either in our exporter or in a different part of the pipeline. If at any point you send an unsupported metric, this will be logged with a debug log indicating the unsupported metric type and/or aggregation temporality. The only metrics we don't support right now are ExponentialHistograms

To troubleshoot this it would help to know what metrics are coming to our exporter. You can do that by adding a [logging](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/loggingexporter#logging-exporter) exporter with `loglevel: debug`, and send a few datapoints, and then pasting here the logs from your Collector.

**Comment by omamoo** [comment]
@mx-psi 
I'll configure logging exporter on debug level, and will paste here the data points. However I'll do it ASAP (currently AFK).

Thanks.

**Comment by omamoo** [comment]
@mx-psi 
I'll describe the code, configuration and tests I did including pictures. Hope it will be informative enough..

Let's start with the OpenTelemetryConfiguration at the Web application:
```
private static IServiceCollection AddMetrics(
            this IServiceCollection services,
            bool enable) =>
            services.
                AddOpenTelemetryMetrics(
                    meterProviderBuilder =>
                    {
                        if (!enable)
                        {
                            return;
                        }

                        meterProviderBuilder.
                            AddDefaultMeter().
                            AddRuntimeMetricsInstrumentation().
                            SetResourceBuilder(CreateResourceBuilder());

                        if (TryGetOpenTelemetryCollectorUri() is { } openTelemetryCollectorUri)
                        {
                            meterProviderBuilder.AddOtlpExporter(
                                (otlpExporterOptions, metricReaderOptions) =>
                                {
                                    otlpExporterOptions.Endpoint = openTelemetryCollectorUri;
                                    metricReaderOptions.MetricReaderType = Periodic;
                                    metricReaderOptions.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = (int)30.Seconds().TotalMilliseconds;
                                });
                        }
                    }).
                AddSingleton(
                    serviceProvider =>
                        serviceProvider.
                            GetRequiredService<MeterProvider>().
                            GetDefaultMeter());
```

Open Telemetry Collector Config file:
```
{
  "exporters": {
	"datadog": {
	  "api": {
		"key": "********",
		"site": "datadoghq.com"
	  },
	  "env": "Dev",
	  "metrics": {
		"resource_attributes_as_tags": true
	  }
	},
	"logging": {
	  "loglevel": "debug"
	}
  },
  "processors": {
	"batch": {
	  "timeout": "10s"
	},
	"memory_limiter": {
	  "check_interval": "5s",
	  "limit_mib": 800,
	  "spike_limit_mib": 256
	}
  },
  "receivers": {
	"otlp": {
	  "protocols": {
		"grpc": null
	  }
	}
  },
  "service": {
	"pipelines": {
	  "metrics": {
		"receivers": [
		  "otlp"
		],
		"processors": [
		  "batch",
		  "memory_limiter"
		],
		"exporters": [
		  "datadog",
		  "logging"
		]
	  },
	  "traces": {
		"receivers": [
		  "otlp"
		],
		"processors": [
		  "batch",
		  "memory_limiter"
		],
		"exporters": [
		  "datadog"
		]
	  }
	}
  }
}
```

The code which suppose to generate the measurements:
```
private readonly HistogramMetric _ofirHistogramTestMetric;
private readonly CounterMetric _ofirCounterTestMetric;

// (using in constructor)
_ofirCounterTestMetric = ObservabilityNamespace.Metrics.CreateCounter(nameof(_ofirCounterTestMetric));
_ofirHistogramTestMetric = ObservabilityNamespace.Metrics.CreateHistogram(nameof(_ofirHistogramTestMetric));


public async Task<ReportControllerGenerateReportResponse> GenerateReportAsync([FromBody] ReportControllerGenerateReportRequest request)
        {
            _ofirCounterTestMetric.Increment(delta: 10);
            _ofirHistogramTestMetric.Record(value: 12);

            return new ReportControllerGenerateReportResponse(report);
        }
    }
```

Well, the fuction GenerateReportAsync is called via API end-point which I executing with Curl\Postman, when the code configured as above (Collector config and Asp Config) the metrics temporality i
s Cumulative and sending metrics won't appear at DD backend **but** will appear at the collector logging exporter set to debug level. I'm attaching the log file.
[metrics-logs.txt](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/8325800/metrics-logs.txt)

Hope it will be enough.

**Comment by mx-psi** [comment]
Thanks for the info and the logs, this is helpful. So, 

- For `ReportController.OfirCounterTest`, we always have `Value: 20`; this means that (from 15:01 UTC to 15:29 UTC) there was no increase of the counter: the total sum stays the same. The  expected behavior of the Datadog exporter in this case is to report a value of 0 for all these points (since the delta, `20-20`, is zero). This is similar to the last row of the example for Counter [here](https://docs.datadoghq.com/metrics/otlp/?tab=sum#example).
- For `ReportController.OfirHistogramTest`, a similar thing happens: the `Count` and `Sum` stay the same (always 2 and 24 respectively, same time period), and all the buckets are zero except for bucket 3 with count 2. This means there was no increase, so the expected behavior of the Datadog exporter in this case is to report a value of 0 for all aggregations (sum, count ...), and NaN for the average. 

This is probably not the behavior you want from your .NET library, since there was no increase on any collection period. I am not sure why the .NET library behaves like this; I would suggest you double check their docs to see if anything is wrong. 

If the same code works with delta aggregation temporality, this is to me an acceptable workaround: the Datadog exporter should report the same values with cumulative and delta temporality (except for the first point).

**Comment by omamoo** [comment]
@mx-psi After upgrading to newest OpenTelemetry Nugets the issue has been solved

**Comment by mx-psi** [comment]
@omamoo Great! Glad to see your issue is fixed and thanks for following up with me 🙇
