### ISSUE TITLE
Add link to opentelemetry.io under About section

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-collector-contrib#8558]
Under the **About** section of this repo (which you can access from the main repo page -- click the gear icon next to the About title):

- Under **Website**, add https://opentelemetry.io

We're looking to do this uniformly for all OTel org repos. 

For example:

> <img width="325" alt="image" src="https://user-images.githubusercontent.com/4140793/158021593-283f25fc-d6cf-4a9b-9bdd-bdc85e8c1ab8.png">

**Comment by bogdandrutu** [comment]
Done.
