### ISSUE TITLE
[processor/attributes] add metrics process self metrics

### ISSUE THREAD

**Issue by hanjm** [open-telemetry/opentelemetry-collector-contrib#8560]
**Is your feature request related to a problem? Please describe.**

The `attributesprocessor` and `resourceprocessor` are very useful to operator telemetry attributes, it seems no self metrics currently, like how many spans delete/update attributes are affected.

**Describe the solution you'd like**
Add some self metrics.
**Describe alternatives you've considered**

**Additional context**

**Comment by jpkrohling** [comment]
There are some prerequisites for this. See https://github.com/open-telemetry/opentelemetry-collector/issues/4198
