### ISSUE TITLE
[Docker build] Tag "latest" is not up to date

### ISSUE THREAD

**Issue by politician** [open-telemetry/opentelemetry-collector-contrib#8787]
**Describe the bug**

The tag "latest" does not correspond to the latest version
https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags

cc @bogdandrutu because I see you are the one pushing the other tags on Docker Hub

**Comment by codeboten** [comment]
@politician this issue is tracked in the collector release repo: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/73. Please see the discussion there.
