### ISSUE TITLE
make "/metrics" for  `prometheusexporter`  configurable 

### ISSUE THREAD

**Issue by jixiuf** [open-telemetry/opentelemetry-collector-contrib#8810]
**Is your feature request related to a problem? Please describe.**
make "/metrics" for  `prometheusexporter`  configurable in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusexporter/prometheus.go#L75

**Comment by jpkrohling** [comment]
cc @Aneurysm9

**Comment by gouthamve** [comment]
Hi, I opened a PR #9239 to fix this, but could you elaborate on your usecase @jixiuf? What would you like to achieve that is not possible right now?

**Comment by jixiuf** [comment]
that PR is ok for me， thanks.

**Comment by gouthamve** [comment]
Hi, @jixiuf Sorry that I am only seeing this now, was away the past few weeks. 

The discussion on the PR suggests that the change might not be required. Could you elaborate on the usecase so we can merge the PR?
