### ISSUE TITLE
[receiver/hostmetrics/process_scraper] Rename metadata conflicting with the metrics package name

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#8815]
The local variable name `metadata` conflicts with the generated package name and makes this less readable.

Originally posted by @djaglowski in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8555#discussion_r833274896

**Comment by hydeenoble** [comment]
@dmitryax I would like to pick this up if no one is currently working on it. 

PS: I am open to ideas for the variable name :)

**Comment by dmitryax** [comment]
Hi @hydeenoble . Thanks. Picking up a variable name is the biggest part of the work :) feel free to suggest any in your PR.
