### ISSUE TITLE
Scrape based receiver startup behavior

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-collector-contrib#8816]
**Background**
I started looking into this issue when I noticed that the kafkametricsreceiver crashes the collector if kafka is not available during startup. I originally started a discussion on #8349, but have found that this issue is more widespread, and that many receivers exhibit the same behavior if the service they monitor is not up at start time.

As a brief recap of the discussion on #8349, I found that the kafkametricsreceiver and roughly a dozen other receivers make use of shared code via the [scraperhelper](https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/scraperhelper). The list of receivers using the scraperhelper includes: apachereceiver, couchdbreceiver, dockerstatsreceiver, elasticsearchreceiver, googlecloudspannereceiver, hostmetricsreceiver, kafkametricsreceiver, kubeletstatsreceiver, memcachedreceiver, mogodbatlasreceiver, mongodbreceiver, mysqlreceiver, nginxreceiver, podmanreceiver, postgresqlreceiver, rabbitmqreceiver, redisreceiver, windowsperfcountersreceiver, zookeeperreceiver.

The `Start` methods of many of these receivers try to establish a connection to the services they monitor, and return an error if the service is not up, which in turn crashes the collector during startup.

Ideally, a receiver would not crash at startup if the monitored service is down, and instead would periodically try to reconnect, and start scraping when the connection is successful.

**Fix in scraperhelper**
I began looking at fixing this in the individual receivers and also looked at fixing this in the shared `scraperhelper` package. I protyped fixes for both approaches. The fix in the scraperhelper started to turn into a can of worms. Without going into all the details, the attempted fix made Start asynchronous, which was a pretty big change to collector startup, and made it impossible to return an error from `Start` which might still be desirable in certain scenarios.

**Fix in receiver**
My attention turned to fixing this in the receiver itself. Moving client creation to the `Scrape` method was enough to fix the issue and introduce retries for the kafkametricsreceiver. I'd like to propose that receivers only return fatal errors from `Start`. If the monitored service is unreachable, it can return an error from `Scrape` without causing a failure.

**PR**
I opened a PR (#8817) for this work as a starting point for discussion. Ideally we'd be able to reach consensus on an approach and apply similar fixes to other receivers with similar problems. Once we are happy with solution we can establish best practices for receivers going forward.

**Comment by carlosalberto** [comment]
>  I'd like to propose that receivers only return fatal errors from Start.

What errors would be included? I can only think of actually bad configuration (one that totally prevents the receiver to be started, ever).

**Comment by jpkrohling** [comment]
I think connections should be *attempted* at `Start`. If all components can be started without errors, we can mark the collector as healthy (in the health check extension). If anything fails, we can either wrap in a permanent error (we have such error in the code base), or in recoverable (not sure we have this). We can then either fail (permanent errors), or assume that the component will attempt to try again periodically. This can then lead the health status to be "degraded".

**Comment by mwear** [comment]
I suppose introducing a recoverable error (instead of using permanent) as you hinted at earliee might be a little more straightforward and less disruptive to add. I might go that route first if there aren't any objections.

**Comment by jpkrohling** [comment]
We had a discussion about it today during the SIG call. The error we have is in the consumer package, which isn't suitable for this. The proposal is then to change the component.Host to allow components to report its state (and continue reporting it), adding another function allowing components to register for callbacks, to be called whenever there's a report. This way, components such as the load balancing exporter and the health check extension can register for callbacks, whereas scrapers and components like the OTLP exporter can report their connection failures in real time.

The call to Start would then not return an error in those cases, so that components would only return errors on permanent, unrecoverable errors. I can't think of any examples right now, which might be a sign that there shouldn't be errors being returned from the Start function?

**Comment by fatsheep9146** [comment]
Although https://github.com/open-telemetry/opentelemetry-collector/pull/5304 is closed, but I think this enhancement is still needed, right? 
@jpkrohling

**Comment by jpkrohling** [comment]
Yes, I believe so.

**Comment by jpkrohling** [comment]
@mwear, do you remember what's the current state about this? I have a feeling that (parts?) of it would be possible with the new health check extension, but not sure if all aspects of this discussion are captured there.

**Comment by mwear** [comment]
I don't think this has been standardized yet. Component status and the new health check extension provide necessary mechanisms to surface recoverable errors during startup without shutting the collector down. Ideally we would be able to standardize behavior and abstract it into scraperhelper. This is somewhat related to the work here: https://github.com/open-telemetry/opentelemetry-collector/issues/9957 and likely here: https://github.com/open-telemetry/opentelemetry-collector/pull/9041.
