### ISSUE TITLE
[attribute processor] `EXTRACT` action's "pattern" regex doesn't support creating attributes w/ period(`.`) separator that adhere to OTEL semconv format

### ISSUE THREAD

**Issue by ericmustin** [open-telemetry/opentelemetry-collector-contrib#8819]
Hello.

Attempting to write a resource processor which extract from an attribute according to a pattern just like in the configuration

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/313873df8c672548ba7afbc1d9208b5e18ac5707/processor/attributesprocessor/testdata/config.yaml#L39-L41
 
The attribute that it creates is specified by a named capture group in the golang regex. This is required by the implementation.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/313873df8c672548ba7afbc1d9208b5e18ac5707/internal/coreinternal/attraction/attraction.go#L48-L56

However, named capture groups in golang regex syntax are invalid if they contain anything beside alphanumerics and underscores. 

- Go playground blowing up getting mad as an example: https://go.dev/play/p/0BSY7P_8HGd
- Go source code: https://github.com/golang/go/blob/947bf333fc2d93e519241b521ddc13c76daa4862/src/regexp/syntax/parse.go#L1108-L1112

Unfortunately, this doesn't play nicely with the OpenTelemetry Specification semantic conventions, which defines basically all stable attributes using the `.` separator, like `service.name` or `service.version` or `deployment.environment` etc etc etc. 

https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions#service

imo i think using named capture groups to define attribute keys is not an appropriate way to implement this feature.

**Comment by mx-psi** [comment]
@anuraaga, would the transform processor have the same limitation?

**Comment by ericmustin** [comment]
Is the transform processor usable currently for trace data? i saw it's been kinda WIP / in flight so have been hesitant to touch it.

**Comment by pmm-sumo** [comment]
As far as I understand this is a limitation of the regex library. As a workaround, one can use a name without dots and then `update` action of the attributes processor (optionally followed by delete). 

If we want to make it nice, we have at least several options:

* rename dots within capture group names to something else when compiling the regular expression (hacky)
* add another config option within the extract to rename keys in-place (so named capture groups would have the actual key names assigned separately)
* make regex library allow dots in capture group names
* something else (?)

**Comment by ericmustin** [comment]
@pmm-sumo thanks for the work around. I went with a custom processor as I'd prefer to avoid doing multiple operations. I think of the long term fixes you mentioned

> add another config option within the extract to rename keys in-place (so named capture groups would have the actual key names assigned separately)

Seems like the most reasonable (ie, have the `capture groups:attribute_key` mapping in a separate config option). But frankly i'd prefer to just see this work done in the `transform` processor, which seems to be a more flexible long term approach to these sort of problems, rather than trying to address all these similar-ish issues across 4/5 different processors.

I think my issue has been addressed here and you're welcome to close the issue if that's your preference, or happy to leave open so other folks can discover the work around you supplied above.

Cheers!

**Comment by ericmustin** [comment]
@mx-psi also to answer your question (@anuraaga and i spoke on slack), the transform processor doesn't allow for regex matching at the moment, although you can define a custom function as an extension that can be referenced in the `transform` processor expression, which could accomplish this. but nothing pure yaml yet.

There are a few PRs in flight that would make this feature easier to accomplish in the future, I have not been following very closely but I believe any additional love/eyeballs on the transform processor PRs would be very welcome.
