### ISSUE TITLE
[k8sattrprocessor] Allow to set namespace/pod annotations/labels to keys without prefix when using key_regex

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#8844]
**Is your feature request related to a problem? Please describe.**
in cases we are interested in all the labels of a pod, which currently can be extracted via key_regex(`.*`), thus all labels are set to attribute `k8s.pod.labels.<key>`, there is no way to trim the prefix `k8s.pod.labels` either as defined in k8sattrprocessor nor resource/attributes processor, as they need keys to be defined explicitly, where regex and match groups are not supported.

**Describe the solution you'd like**
Support replacing key with regex(match and replace with match groups?) in resource/attributes processor.

**Describe alternatives you've considered**
Allow to set the prefix in k8sattrprocessor.

**Additional context**
currently the prefix are [hardcoded](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/internal/kube/client.go#L319-L336) and not configurable.

**Comment by pmm-sumo** [comment]
Although `k8s.pod.labels.*` are not specified in the [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md) they follow the other Kubernetes attributes. If we want to enable non-prefixed labels, we might add a configuration parameter for the prefix, which might default to `k8s.pod.labels.`

I think replacing the key via regex match might a nice addition to resource/attributes but it will face a challenge with matching dots in named groups (similar problem discussed in #8819) for which we don't have an elegant solution currently

**Comment by dmitryax** [comment]
@newly12 thanks for submitting the issue.

@pmm-sumo given that we already have issue to add support for regexp match groups, I don't think we should add another configuration option for prefix here.

@newly12 please take a look at this issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5982 and see if it solves your problem. If it does, I recommend addressing that issue instead.

**Comment by newly12** [comment]
@dmitryax make sense. If I am reading the issue/comment correctly, I assume the approach is that, when KeyRegex is used, tagName could be something like regex that has reference to captured groups from KeyRegex, if tagName is not defined, it defaults to the current default value i.e. `k8s.pod.labels.$0`. Please correct me if anything.

**Comment by pmm-sumo** [comment]
I am not sure if I'm following, please correct me if I'm wrong here. Is the idea that when named capture group is used, the name of the capture group would be the prefix for the tag name?

So having something akin to:

```
extract:
  labels:
    - key_regex: some.tag.(?P<myprefix>.*)
      from: pod
```

When encountering tag like "some.tag.foo=bar" we would anticipate outputting it as "myprefixfoo=bar"?

If that's the idea then unfortunately we hit the limitation of regexp named capture groups not allowing dots in name (BTW, I did quick experiment with the library code and it seems that extending the list of characters allowed for named capture groups is a trivial change there, maybe we could just propose such change)

**Comment by newly12** [comment]
Can I assume that it will take quite some time if we are going to enhance golang regex package? if that's the case, any idea how we can move forward on this one?

**Comment by pmm-sumo** [comment]
@dmitryax what do you think? I am not sure if I understand the suggestion how to achieve this differently and there's a good chance I'm missing something and we could still do it more elegantly than defining prefix (or making it a more generic "template")

**Comment by newly12** [comment]
@dmitryax could you help check the questions?

**Comment by dmitryax** [comment]
> @dmitryax make sense. If I am reading the issue/comment correctly, I assume the approach is that, when KeyRegex is used, tagName could be something like regex that has reference to captured groups from KeyRegex, if tagName is not defined, it defaults to the current default value i.e. k8s.pod.labels.$0. Please correct me if anything.

Yes, you got it right. The idea is to support simple captured groups by numbers when KeyRegex is specified. I don't think we need named groups.

`$0` would always be replaced with whole label/annotation, `$1`, `$2` etc should be replaced with captured groups from `KeyRegex` if they exist, otherwise fail.

E.g for your use case, you would need to setup:

```yaml
    extract:
      labels:
        - key_regex: .+
          from: pod
          name: "custom-prefix.$0"
```

Or, if I want all labels starting with `my-pod-prefix-` to be translated into attributes with another prefix like `another-prefix-*`, I'll use the following:

```yaml
    extract:
      labels:
        - key_regex: my-pod-prefix-(.+)
          from: pod
          name: "another-prefix-$1"
```

**Comment by pmm-sumo** [comment]
Thanks for the clarification @dmitryax So the idea is to overload `tag_name` (since we don't have `name`, I guess that you intended `tag_name`, correct?) and [change this section of code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.49.0/processor/k8sattributesprocessor/options.go#L158-L165) so that when `tag_name` is provided and it's a pattern, it should be filled with regex capture groups. We probably need to validate that `key_regex` has capture groups and that `tag_tame` contains annotations. In any case, I think it's a better idea than the prefix :)

**Comment by dmitryax** [comment]
> since we don't have name, I guess that you intended tag_name, correct?

Yes, sorry, it's `tag_name`. I've updated the snippets
