### ISSUE TITLE
skywalking exporter

### ISSUE THREAD

**Issue by caoheyang** [open-telemetry/opentelemetry-collector-contrib#8854]
I'd like to confirm if we offer skywalking exporter now regarding the trace part, and if not, would it be a good idea to consider offering it? My current application is collecting trace information via opentelemetry java agent and I want to display it via skywalking.

thanks,
Regards.
Heyang

**Comment by JaredTan95** [comment]
The current otpl data can not be converted into skywalking protocol data.

**Comment by caoheyang** [comment]
Hi Jared,

Thanks for your reply😃.  So ,do we have a plan to realization it ? I think this is needed for many people.

regards,

Heyang

**Comment by pmm-sumo** [comment]
FYI @liqiangz

**Comment by XiaoWeiKIN** [comment]
mark

**Comment by XiaoWeiKIN** [comment]
> The current otpl data can not be converted into skywalking protocol data.

I wonder why that is? since we plan to migrate Skywaking to OPTL, we want to be able to collect traces to SkyWalking Server through the Otel Agent.

**Comment by caoheyang** [comment]
Is there any update here?

Thanks & Regards,
Heyang

**Comment by Superskyyy** [comment]
> Is there any update here?
> 
> Thanks & Regards, Heyang
@caoheyang 
https://github.com/apache/skywalking/issues/7848 There have been many discussions on the idea, just letting you know the reasons and current blocks.
I suppose it could happen based on the discussion but will need careful thought and implementations.
