### ISSUE TITLE
ability to filter processes in hostmetricsreceiver based on uptime

### ISSUE THREAD

**Issue by davidmirza408** [open-telemetry/opentelemetry-collector-contrib#8976]
**Is your feature request related to a problem? Please describe.**
HostMetricsReceiver collects telemetry data on all processes running in a system by default.  It would be helpful to be able to filter out short lived processes that may be up for only a few seconds but result in a lot of noise bing reported.

**Describe the solution you'd like**
I would like to create a filter that allows the user to filter out processes that have been running for less than N seconds.  I would also like to volunteer to work on this ticket if approved.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

cc @dmitryax

**Comment by davidmirza408** [comment]
This is what I had in mind: https://github.com/davidmirza408/opentelemetry-collector-contrib/pull/5

**Comment by davidmirza408** [comment]
Another possible solution is to include uptime in the metrics so that it can be filtered out by a processor if needed.  Please advise as to what is the preferable solution to this.

**Comment by dmitryax** [comment]
> Another possible solution is to include uptime in the metrics so that it can be filtered out by a processor if needed. Please advise as to what is the preferable solution to this.

I don't see a clean and safe way to include uptime in the metric. Adding it as an attribute will result in a new timeseries per each datapoint unless the attribute is removed

Let's add this as a configuration parameter for the receiver. Please suggest the configuration interface in this issue.

**Comment by dmitryax** [comment]
Maybe...
```yaml
scraping_delay: 0s
```

**Comment by davidmirza408** [comment]
I like scrape_process_delay: 0s.  I can do the implementation for this issue
