### ISSUE TITLE
Add dockerattributesprocessor to enrich docker logs collected with filelog receiver

### ISSUE THREAD

**Issue by matthewmodestino** [open-telemetry/opentelemetry-collector-contrib#8982]
**Is your feature request related to a problem? Please describe.**

As an OTel native logging user, I would like to collect docker logs and have them enriched the same way we do for k8s logs

**Describe the solution you'd like**

I would like docker logs to be enriched in the OTel logging pipeline with docker metadata from the docker api, including but not limited to:

```
  "docker": {
    "id": "df14e0d5ae4c07284fa636d739c8fc2e6b52bc344658de7d3f08c36a2e804115",
    "name": "k8s_fabric8-console-container.efbd6e64_fabric8-console-controller-9knhj_default_8ae2f621-f360-11e4-8d12-54ee7527188d_7ec9aa3e",
    "container_hostname": "fabric8-console-controller-9knhj",
    "image": "fabric8/hawtio-kubernetes:latest",
    "image_id": "b2bd1a24a68356b2f30128e6e28e672c1ef92df0d9ec01ec0c7faea5d77d2303",
    "labels": {}
  }
```

**Describe alternatives you've considered**

Today the community relies on fluentd/fluent-bit community plugins, which are not widely maintained, or docker logging plugins. Users generally like to avoid needing to touch the docker engine directly, and logging plugins can cause adverse impact to the docker daemon. Picking up the files from disk provides a reliable buffer and is easy for users to adopt.

**Additional context**

While k8s is moving away from docker, we still see docker based deployments a lot in the community and it is a common request for adopting more use of OTel log collection. 

This solution should/could also possibly be flexible or generic enough to collect/enrich from containerd/cri-o sockets. Maybe calling it "containerattributeprocessor" if able to make it that flexible.

**Comment by matthewmodestino** [comment]
I may have found a way forward by using the metadata that the docker `json-file` driver will embed, then just using existing `filelog` operators/processors to add the docker meta to `resource` / `attributes`. Will try it now...

**Comment by djaglowski** [comment]
Did it work?

**Comment by matthewmodestino** [comment]
yep!

I used the docker.json to set the tags the way I wanted them (pipe separated for easy regex), then did something like this:

```
receivers:
  filelog:
    include:
    - /var/lib/docker/containers/*/*-json.log
    encoding: utf-8
    fingerprint_size: 1kb
    force_flush_period: "0"
    include_file_name: false
    include_file_path: true
    max_concurrent_files: 1024
    max_log_size: 1MiB
    operators:
    - id: parser-docker
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: time
      type: json_parser
    - id: filename
      resource:
        com.splunk.source: EXPR($$attributes["file.path"])
      type: metadata
    - id: extract_metadata_from_docker_tag
      parse_from: $$.attrs.tag
      regex: ^(?P<name>[^\|]+)\|(?P<image_name>[^\|]+)\|(?P<id>[^$]+)$
      type: regex_parser
    - attributes:
        log.iostream: EXPR($$.stream)
      resource:
        com.splunk.sourcetype: EXPR("docker:container:"+$$.name)
        docker.container.name: EXPR($$.name)
        docker.image.name: EXPR($$.image_name)
        docker.container.id: EXPR($$.id)
      type: metadata
    - id: clean-up-log-record
      ops:
      - move:
          from: $$.log
          to: $$
      type: restructure
    poll_interval: 200ms
    start_at: beginning

exporters:
  splunk_hec/logs:
    # Splunk HTTP Event Collector token.
    token: "00000000-0000-0000-0000-000000000000"
    # URL to a Splunk instance to send data to.
    endpoint: "https://i-06802fb7334256322.ec2.splunkit.io:8088/services/collector"
    # Optional Splunk source: https://docs.splunk.com/Splexicon:Source
    source: "docker"
    # Splunk index, optional name of the Splunk index targeted.
    index: "main"
    # Maximum HTTP connections to use simultaneously when sending data. Defaults to 100.
    max_connections: 20
    # Whether to disable gzip compression over HTTP. Defaults to false.
    disable_compression: true 
    # HTTP timeout when sending data. Defaults to 10s.
    timeout: 10s
    # Whether to skip checking the certificate of the HEC endpoint when sending data over HTTPS. Defaults to false.
    # For this demo, we use a self-signed certificate on the Splunk docker instance, so this flag is set to true.
    tls:
      insecure_skip_verify: true
   # Debug
  #logging:
  #  loglevel: debug

processors:
  batch:
  resourcedetection:
    detectors:
    - env
    - system
    timeout: 10s
    override: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: :55679

service:
  extensions: 
  - zpages
  - health_check
  pipelines:
    logs:
      receivers:
      - filelog
      processors:
      - batch
      - resourcedetection
      exporters:
      - splunk_hec/logs
      #- logging
```

and deployed the docker image like this:

```
version: "3"
services:
  otelcollector:
    image: "quay.io/signalfx/splunk-otel-collector:latest"
    user: "root"
    privileged: true
    container_name: otelcollector
    command: ["--config=/etc/otel-collector-config.yml", "--set=service.telemetry.logs.level=debug"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      
```

**Comment by fatsheep9146** [comment]
I think the problem is solved. The issue could be closed.

**Comment by matthewmodestino** [comment]
technically its not solved, I had to use a very cumbersome workaround to get the metadata that included customizing the docker daemon, which is not very user friendly....

Still think we should be able to enrich straight docker logs like we do in k8s

**Comment by devtyagi-c** [comment]
@matthewmodestino can you please show your json-file driver configuration? 
Thanks!

**Comment by matthewmodestino** [comment]
@devtyagi-c Sure, Here it is, found it in docker docs here: https://docs.docker.com/engine/logging/log_tags/

# /etc/docker/daemon.json 

`
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m",
    "max-file": "5", 
    "tag": "{{.Name}}|{{.ImageName}}|{{.ID}}"
  }
}`

**Comment by devtyagi-c** [comment]
@matthewmodestino thanks, helps a lot!
Do you know any way to enrich the logs with Docker Labels?

**Comment by huyz** [comment]
@matthewmodestino Do you have updated operator specifications?  All the syntax has changed

**Comment by matthewmodestino** [comment]
The double dollar signs can be removed, and the final move can be updated to move attributes.log to body. see current k8s helm chart config map for updated syntaxes

https://github.com/signalfx/splunk-otel-collector?tab=readme-ov-file#from-0410-to-0420


https://github.com/signalfx/splunk-otel-collector-chart/blob/91433685dd873be8a07b32d25f477c6618384db0/examples/only-logs-otel/rendered_manifests/configmap-agent.yaml#L282-L287

**Comment by irajtaghlidi** [comment]
This workaround actually adds significant disk I/O usage and also extracts container attributes from each individual log entry, which wastes CPU cycles. It should instead extract the container ID from the file path and call the Docker API via the attached socket file to enrich it at the resource level. Just like what the K8S processor does.
I even have some critical runtimes that I cannot interrupt just to add a tag.

**Comment by simonswine** [comment]
For anyone running into this I built a small shim that brings Docker metadata enrichment through the existing `k8sattributesprocessor`: https://github.com/simonswine/docker-k8sattributesprocessor-shim

The idea: it watches the local Docker socket, maps each container to a fake Kubernetes Pod object, and exposes a minimal fake Kubernetes API server. You point `k8sattributesprocessor` at it via a kubeconfig and it enriches your telemetry with container metadata (image name, labels, namespace, container ID, etc.) using only `container.id`.

The mapping covers the fields asked for here: container ID, name, image, image ID, and labels all end up as standard OTel resource attributes.

I still think a native `dockerattributesprocessor` would be better, I am happy to work on this, for a start can we reopen that issue: @open-telemetry/collector-contrib-triagers
