### ISSUE TITLE
Service specific sampling configuration

### ISSUE THREAD

**Issue by satwika007** [open-telemetry/opentelemetry-collector-contrib#8988]
Hi Team,
Our tracing infra looks like this - otel-loadbalancer -> otel-sampler -> jaeger-collector
Currently otel-sampler supports same sampling configuration for all services. We want to have service specific overrides i.e.,
different sampling configurations for different services(different rate limiting, http status code checks for different applications). Has anyone tried this? Or if you have any suggestions please let us know!

**Describe alternatives you've considered**
One of the ways we can think of is using AND policy, for example, combination of string attribute policy(appname = xyz) and ratelimiting policy.
Could you please let us know if there are any other better ways to achieve service specific sampling configurations?

**Comment by jpkrohling** [comment]
I need to play with the "and" policy, but perhaps @mottibec has the answer?

**Comment by mottibec** [comment]
You should be able to use the "and" policy to achieve this behavior, we are running this in production but with the probabilistic policy, but the rate-limiting should work just the same way.

**Comment by satwika007** [comment]
Thanks for your response @mottibec!

@jpkrohling @mottibec 
As of now latency sampling policy is based on time taken by trace. Can we have latency tag available for each span, so that sampling can be done based on each span duration as well?

**Comment by jpkrohling** [comment]
> Can we have latency tag available for each span, so that sampling can be done based on each span duration as well?

This sounds like a new request/issue. While I think it might be a good idea to have a new property for that, I'll close this one here as I think the main topic has been addressed. Feel free to open a new issue for the span duration question/suggestion.
