### ISSUE TITLE
Rename default value of `Attribute` configuration parameter to `Authorization` from `authorization`

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector-contrib#8994]
Prior Art:  https://github.com/open-telemetry/opentelemetry-collector/issues/4982

The client libraries (OAuth2) usually set the authorization tokens as "Authorization: <>". Currently, by default OIDC extension looks for "authorization" header key.

**Comment by jpkrohling** [comment]
As mentioned in the other issue, just changing from "A" to "a" would break gRPC. We'd need a way to match this header in a case-insensitive manner.

**Comment by pavankrish123** [comment]
Got it! @jpkrohling I would like to implement this special case insensitivity only for default (Auth and fallback auth). In other cases I am planning to make it case sensitive. Does this sound good?

**Comment by jpkrohling** [comment]
> Does this sound good?

Perhaps. Note that the RFC for the HTTP spec states that headers are case insensitive. So, a user specifying "authorization" would correctly expect we match both "authorization" and "auTHOrization".

Perhaps we should do an optimistic lookup first, and do a case-insensitive search if no values are found?
