### ISSUE TITLE
[cmd/mdatagen] limited access to metric information 

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-collector-contrib#8997]
**Is your feature request related to a problem? Please describe.**
In order to support better metaprogramming based on the defined metric metadata, that metadata needs to be accessible. In addition, that metadata should be referenceable by metric name. All of this will ensure less required repetition of metric metadata and duplicated code in the client & scraper logic

**Describe the solution you'd like**
Additional functions to be able to access information about a metric. Also, an easy way to link the metric information and whether or not they are enabled.

**Comment by jpkrohling** [comment]
cc @dmitryax

**Comment by dmitryax** [comment]
@Mrod1598 can you please describe your use case why do you need more access to metrics information

**Comment by Mrod1598** [comment]
A use case I'm currently working on is for The[ IIS receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8832/files#diff-f7357a65213f8b912c7e3ac21e1f8763679cbff4b1aedb9bbaa88f49ccda6366R42). I need access to the metric metadata to be able to build the config information for the imbedded windowsperformance counter receiver.

**Comment by dmitryax** [comment]
Given the new approach you took in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8832, I believe this issue can be closed, right?

**Comment by Mrod1598** [comment]
> Given the new approach you took in #8832, I believe this issue can be closed, right?

Yes that should be correct
