### ISSUE TITLE
[Processor] is there a way to calculate service topology with processor?

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-collector-contrib#8998]
Hi, I was recently learning about `optelemetry-collecotr-contrib` and I found that we now have `spanmetricsprocessor ` already, which can generate metrics as follows:

```bash
calls{http_method="GET",http_status_code="200",operation="/Address",service_name="shippingservice",span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_UNSET"} 142
```

So, I wonder if there's a way to compute the service topology, like the effect of `service dependencies` in `jaeger`. 
But through the `prometheus metric` and it might be necessary to reference the `spanmetricsprocessor ` and generates metrics with `source and destination services` lebels,  like:

```bash
service_topology_calls{source_service_name="shippingservice", destination_service_name="demoservice", span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_UNSET"} 142
service_topology_latency{source_service_name="shippingservice", destination_service_name="demoservice", span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_UNSET"} 2
```

If the community already has a solution or I miss something, feel free to correct it, thanks a lot!

**Comment by yeya24** [comment]
I think there is no such feature in the opentelemetry collector contrib now. But Grafana agent supports this kind of feature to generate service topos from traces. Please take a look at https://grafana.com/docs/tempo/next/grafana-agent/service-graphs/#how-they-work. 

I guess https://github.com/grafana/agent/blob/main/pkg/traces/servicegraphprocessor/processor.go is what you want.

**Comment by JaredTan95** [comment]
@yeya24  Thanks, It's a coincidence that I just saw the handling of the `service graph` in the Grafna Agent.

**Comment by JaredTan95** [comment]
> I think there is no such feature in the opentelemetry collector contrib now. But Grafana agent supports this kind of feature to generate service topos from traces. Please take a look at https://grafana.com/docs/tempo/next/grafana-agent/service-graphs/#how-they-work.
> 
> I guess https://github.com/grafana/agent/blob/main/pkg/traces/servicegraphprocessor/processor.go is what you want. Maybe it is also valuable to upstream this feature to otel collector repo.
> 
> cc @mapno I think you did the implementation. Any thoughts?

@mapno hi, Is there any plan for contributing to this upstream repo. :-)

**Comment by mapno** [comment]
Hey! That's right, we developed a solution to recreate a system's topology by deriving metrics from ingested traces. This solution is built as an OTel processor, and currently lives in the Grafana Agent. We're working on adding this same feature to Tempo as well.

The processor is built very ad-hoc to work with the Grafana Agent (and Tempo soon) and Grafana, but it could be modified to make it agnostic and compatible with the collector. There a few changes that we'd need to make, but shouldn't pose a big challenge.

There are two main points I can think of:
1. Metrics are built as Prometheus metrics and pushed to the Agent's registry. The processor would have to be changed to create OTLP metrics which will be pushed to a metrics pipeline (same architecture as the spanmetrics processor)
2. The processor relies on receiving complete traces in the same pipeline. In the Agent is solved by rebalancing traces across instances by layering two collector pipelines within each agent and using the loadbalacing exporter. I assume this would be left to users to configure their pipelines to account for this requirement.

I'd be happy to work on contributing this to contrib or assisting someone else to do it.

**Comment by jpkrohling** [comment]
If this turns out to become a new component, I'll sponsor it.

**Comment by JaredTan95** [comment]
@mapno Thanks for your description, If you have no time, I think I can have a look at  `service graph` processor(Grafana Agent).
And then, I'm happy to work on contributing this after I have fully understood the logic in `Grafana Agent`.  cc @jpkrohling

**Comment by mapno** [comment]
Hey, I'll be able to dedicate some time to contributing this myself. I'm happy to work with anyone who is interesting in helping as well.

From what I see, the first step for new components is opening an issue outlining the component ([docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components)). I'll see to starting that initial conversation some time this week.

**Comment by JaredTan95** [comment]
> Hey, I'll be able to dedicate some time to contributing this myself. I'm happy to work with anyone who is interesting in helping as well.
> 
> From what I see, the first step for new components is opening an issue outlining the component ([docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components)). I'll see to starting that initial conversation some time this week or early next week.

Okay, It would be nice to see this feature merged into upstream.

**Comment by devrimdemiroz** [comment]
Used it with grafana agent. Works perfectly! It is one of the key functionality that was missing in oss. I value it as the second biggest enhancement towards becoming APM after spanmetrics. As an end-user would be looking forward to having it via otelcol.

**Comment by mapno** [comment]
Opened an issue describing a new component: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9232. I believe we will be able to start the implementation shortly.

**Comment by JaredTan95** [comment]
Great, I will close this issue, and following https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9232

**Comment by ovidiubuligan** [comment]
grafana tempo 1.4 was released and if you happen to use it you can enable the metrics generation from there instead of otel collector : https://grafana.com/blog/2022/05/02/new-in-grafana-tempo-1.4-introducing-the-metrics-generator/ 

Generated metrics are pushed with Prometheus remote write
