### ISSUE TITLE
[exporter/datadog] Tags should not be case sensitive

### ISSUE THREAD

**Issue by ransoor2** [open-telemetry/opentelemetry-collector-contrib#9015]
**Describe the bug**
Tags are case sensitive in DD exporter, which results in tags duplication in DD

**Steps to reproduce**
For example : metric enters the collector with tag `namespace:prod-default`. Collector with `resource` processor overrides with `NAMESPACE:prod_default` 

**What did you expect to see?**
I expect to see in DD the same thing I see in the collector's logging exporter - `NAMESPACE:prod_default`

**What did you see instead?**
In DD I see the `namespace` tag with two values: `prod-default` and `prod_default`

**What version did you use?**
v0.45.0

**Environment**
Ubuntu 14

**Comment by mx-psi** [comment]
Hi @ransoor2 thanks for taking the time to open the issue. It would be helpful to have your logging exporter output (in particular, do you see both `NAMESPACE:prod_default` and `namespace:prod-default`?)

**Comment by ransoor2** [comment]
Hi Pablo @mx-psi ,
In the logging exporter I saw only `NAMESPACE:prod_default` (which means the override succeeded)
In DD exporter's output I saw both `NAMESPACE:prod_default` `namespace:prod-default` in the tags list, which correct me if im wrong but this is not the expected behavior

**Comment by mx-psi** [comment]
@ransoor2 Yes, this is not the expected behavior, although I can't think of any likely explanation out of the top of my head.  I will try to reproduce at some point this week; if you don't mind copy-pasting the logging exporter output, it will be helpful to nail down what's happening (e.g. it could be because of other attributes you have or because of resource attributes vs datapoint-level attributes)

**Comment by ransoor2** [comment]
I will try to provide a full config example + client code to reproduce the issue

**Comment by ransoor2** [comment]
Well, when I reproduced it locally then I also get duplications in the logging exporter.
So im guessing this is the expected behavior in DD exporter as well? Which will result in tags duplication in DD

**Comment by ransoor2** [comment]
Thanks Pablo
Closing the ticket
