### ISSUE TITLE
[all] Enable more linters on this repository

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#9109]
The opentelemetry-collector repository has two checks that are not enabled here. This is a meta issue to track these.

### Errcheck

- [x] #9750
- [x] #9749

### Gocritic

- [x] #10465
- [x] #10466

### Depguard (for sync/atomic):

See more context at open-telemetry/opentelemetry-collector#5215.

- [x] #9810
- [x] #9778

### Exhaustive

We also have an existing issue for checking coverage for all metric types that can be tackled with a linter:

- [ ] #7532
- [x] #23242
- [x] #23266

### Vulncheck

- [x] #19154

### Possible additional work

Some more linters that could be enabled here (these are not in the core repo): deadcode, structcheck, unused, ineffassign, tenv, go-errorlint.

## Approach

Fixing all errors at once is a lot of work, so I would suggest doing things in several steps:

1. A first PR enables the linter, excluding it on any components that are not passing right now.
2. Subsequent PRs make it pass on individual components and progressively remove the exclusion rules on faulty components. We can create individual issues for each linter and each component, depending on how hard they are to fix.

**Comment by fatsheep9146** [comment]
I'd love to help with this. If ok, you can assign this to me. @mx-psi

**Comment by lootek** [comment]
I think it'd be great to add [govulncheck](https://go.dev/blog/vuln) as well. The good news is it passes on current `main` when run using go1.19.6 on mac OS:

```
$ govulncheck ./...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Using go1.19.6 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev (last modified 28 Feb 23 22:58 UTC).

Scanning your code and 3181 packages across 587 dependent modules for known vulnerabilities...
No vulnerabilities found.
```

**Comment by mx-psi** [comment]
@lootek can you open a separate issue for this? I can list it on this meta issue once opened. Based on golangci/golangci-lint/issues/3094 it looks like this is not available on golangci-lint but we could run it separately if this is useful

**Comment by lootek** [comment]
@mx-psi, Good idea, thanks. It's done.

Do you think it makes sense to add all the components listed one by one? Since the linter seems to be passing right now it should be straightforward. Or should I list them anyway?

**Comment by lootek** [comment]
Yeah, it's green. Though govulncheck runs against the current Go toolchain / std lib version so the question is which version do we use here in GH actions. I looked for that and it's not defined once but several times as 1.19.6 (and that'd be great) and many times as just 1.19 (with no clue if it's gonna take 1.19.0 or the highest available 1.19.x).

**Comment by mx-psi** [comment]
Let's pin it to 1.19.6, that makes more sense to me

**Comment by fatsheep9146** [comment]
@mx-psi I think this issue is finally ready to be closed :-)
