### ISSUE TITLE
Flaky test - prometheusreceiver - TestOpenMetricsNegative

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#9119]
Seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5869686660?check_suite_focus=true#logs

```
2022-04-07T14:06:18.1333771Z === RUN   TestOpenMetricsNegative/bad_type_1
2022-04-07T14:06:18.1334163Z race: limit on 8128 simultaneously alive goroutines is exceeded, dying
2022-04-07T14:06:18.1334861Z FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver	102.534s
```

cc @Aneurysm9 @dashpole

**Comment by jpkrohling** [comment]
And here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5860025725?check_suite_focus=true

**Comment by gouthamve** [comment]
Looks like it will be fixed in the next release of Go: https://github.com/golang/go/issues/47056#issuecomment-1080968395

**Comment by dmitryax** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5980689286

**Comment by tigrannajaryan** [comment]
Failed again https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5993262462?check_suite_focus=true

**Comment by tigrannajaryan** [comment]
4 failures in 4 days. I think we need to disable the test until it is fixed.

**Comment by jpkrohling** [comment]
It looks like this might have been fixed, but a positive confirmation from the code owner(s) is desirable.

**Comment by dashpole** [comment]
This has been reenabled for a few months without complaint
