### ISSUE TITLE
Replace mock traces exporter with consumertest.TracesSink

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#9123]
I think we have a test facility native to the collector that we could use, right? Doesn't have to be changed on this PR, but perhaps it would make sense to open an issue to track this?

_Originally posted by @jpkrohling in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8990#discussion_r846148040_

**Comment by jpkrohling** [comment]
This is the facility I had in mind: https://github.com/open-telemetry/opentelemetry-collector/blob/main/consumer/consumertest/sink.go#L25-L45

**Comment by mx-psi** [comment]
Sounds like this can be closed?

**Comment by jpkrohling** [comment]
I believe so!
