### ISSUE TITLE
routingprocessor: use native trace sink for tests

### ISSUE THREAD

**Issue by pmalek-sumo** [open-telemetry/opentelemetry-collector-contrib#9125]
I think we have a test facility native to the collector that we could use, right? Doesn't have to be changed on this PR, but perhaps it would make sense to open an issue to track this?

_Originally posted by @jpkrohling in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8990#discussion_r846148040_

**Comment by pmalek-sumo** [comment]
@jpkrohling

**Comment by jpkrohling** [comment]
Thanks for creating this! I ended up creating one as well, but looks like I forgot to link it there: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9123

I'm then closing this in favor of that other one.
