### ISSUE TITLE
[exporter/<logs>] Update timestamp processing logic

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#9130]
The log data model was recently update to include a second timestamp. In order for logging exporters to maintain their current functionality, they must be updated to use `Timestamp` when it is present, and `ObservedTimestamp` otherwise.

A quick search appears to show that the following exporters may be affected:
- `azuremonitorexporter`
- `observiqexporter`
- `lokiexporter`

This issue is dependent upon [collector#5171](https://github.com/open-telemetry/opentelemetry-collector/pull/5171) being completed first.

**Comment by jpkrohling** [comment]
cc @mar4uk

**Comment by mar4uk** [comment]
@djaglowski Do you plan to work on this issue by yourself? Or I can assign it to myself and do it?

**Comment by djaglowski** [comment]
@mar4uk, your help would be very appreciated, thank you! ! I'll assign it to you.
