### ISSUE TITLE
[processor/filter] extend log filtering capabilities with body and severity

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector-contrib#9235]
**Is your feature request related to a problem? Please describe.**

Filter processor currently has very limited log record filtering capabilities (only by matching a record basing on some attributes or resources). We could easily extend it to filter by body or severity though.

**Describe the solution you'd like**

[filterlog](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/coreinternal/processor/filterlog/filterlog.go) already has support for matching log body and [upcoming one for matching log severity](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9132/files)

This code is shared among several components, including filter processor. We could leverage it and add easily add a capability for filtering log records basing on the matching log body or severity.

**Comment by cpheps** [comment]
@pmm-sumo I'd like to volunteer to take this if it's not already being worked on.
