### ISSUE TITLE
Attributes processor from_context should provide access to AuthData attributes

### ISSUE THREAD

**Issue by rkukura** [open-telemetry/opentelemetry-collector-contrib#9241]
**Is your feature request related to a problem? Please describe.**
`ServerAuthenticator` extensions such as BasicAuth and OIDC store `client.AuthData` interface implementations containing attributes describing the authenticated client as `client.Info.Auth`. Attributes processor actions using `from_context` can create span attributes from `client.Info.Metadata`, but not from `client.Info.Auth`. There are use cases where adding `AuthData` attributes such as the authenticated username to spans is needed, but this is not currently possible.

**Describe the solution you'd like**
The Attributes processor should be extended to also extract `from_context` attributes from `client.Info.Auth`. Either `client.Info.Auth` would be searched when the key is not found in `client.Info.Metadata`, or keys beginning with a prefix such as `"Auth."` would be searched for only in `client.Info.Auth`.

**Describe alternatives you've considered**
No existing processor provides the ability to add span attributes based on data from `client.Info.Auth`. A new processor could be added for this, but it would largely duplicate the functionality of the existing Attributes processor.

**Additional context**
N/A

**Comment by jpkrohling** [comment]
> or keys beginning with a prefix such as "Auth." would be searched

This would be my preference. Would you be interested in contributing code for this change?

**Comment by rkukura** [comment]
Yes - sign me up!
