### ISSUE TITLE
azuremonitorexporter: remove usage of LogRecord.Name field

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#9258]
LogRecord.Name field is obsolete in this repo and will be deleted soon (already deleted from OTLP).

The field is [currently used](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6cb401f1f25d2affcf5a10e737ad1c7e10912206/exporter/azuremonitorexporter/log_to_envelope.go#L63) by azuremonitorexporter.

Please eliminate all references to LogRecord Name()/SetName() in azuremonitorexporter. The field is obsolete and there is no replacement for it.

**Comment by tigrannajaryan** [comment]
@pcwiese as a codeowner of azuremonitorexporter can you help with this?

**Comment by bogdandrutu** [comment]
@reyang can you find an owner for the `azuremonitorexporter`?

**Comment by pcwiese** [comment]
I can take it, been busy with other stuff. This exporter isn't directly supported by MSFT

**Comment by tigrannajaryan** [comment]
Thanks @pcwiese, please do. I will assign this issue to you.

**Comment by pcwiese** [comment]
@[eedorenko](https://github.com/open-telemetry/opentelemetry-collector-contrib/commits?author=eedorenko)
Is this something you can take a look at given that you added support for logs? I'm not familiar with the properties you are setting on the envelope for logs/traces. Can this be removed entirely?

**Comment by tigrannajaryan** [comment]
@pcwiese @eedorenko will you be able to have a look at this? This is blocking a change that we need to make in the codebase. The LogRecord Name will be deleted and we can't until it is no longer referenced from anywhere.

**Comment by pcwiese** [comment]
I just commented out the use of it. I'm not sure what the replacement, if any, should be but it should not block forward progress in this repo.

**Comment by tigrannajaryan** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9544
