### ISSUE TITLE
Potential memory leak in prometheus receiver

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#9278]
Investigate whether the prometheus receiver is impacted by the memory leak addressed by the following fix: https://github.com/prometheus/prometheus/pull/10590

**Note: the 0.49.0 release is blocked pending the investigation**

**Comment by codeboten** [comment]
@gouthamve is investigating

**Comment by Aneurysm9** [comment]
We have already tagged `v0.49.0`.  If we need to include the upstream reversion then we need to `retract` `v0.49.0` and ship `v0.49.1`.

**Comment by dmitryax** [comment]
@gouthamve was the potential memory leak introduced after v0.48.0? I see only this dependency update https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8780/files#diff-cbc1780ee44619ffeeb078f84991774b14445d3a192c34b6acc709f00788b421R390

**Comment by Aneurysm9** [comment]
Yes, that dependency update was to pull in https://github.com/prometheus/prometheus/pull/10450 and https://github.com/prometheus/prometheus/pull/10473 to allow access to target info and metric metadata even after `job` and `instance` have been relabeled.

**Comment by mx-psi** [comment]
> We have already tagged `v0.49.0`. If we need to include the upstream reversion then we need to `retract` `v0.49.0` and ship `v0.49.1`.

We should retract both the main module as well as (at least) the modules that depend on prometheus

**Comment by dmitryax** [comment]
@gouthamve do you have any update on this?

**Comment by dmitryax** [comment]
Cross posting update from @gouthamve in CNCF Slack:

> The memory increase is more like 30% when there is a lot of target churn. This is because of the change where we were passing in the scrape cache inside the Context and scrape cache is not being garbage collected quickly enough. I was thinking it was because the context was being held inside TSDB but I think its fully inside the scraping code, hence it does affect the collector as well. I spent all of Thursday on it, and plan to spend today on it as well, but I can't make enough headway because it could not be replicated in any local tests (just prombench, Prometheus' k8s based large scale benchmarking setup).
> I fully agree that we shouldn't block the release on this, I think we should take the hit given it only affects things when there is high churn in targets. I can also prepare a PR to roll things back if required.

**Comment by dmitryax** [comment]
Decision was made during the SIG meeting to not block the release by this issue. The warning about this issue was added to the 0.49.0 release notes.

**Comment by ItsLastDay** [comment]
Since the issue is closed, does it mean the warning "The issue is currently being investigated and will be fixed in one of the new releases. More details: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9278." in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver is now obsolete?

**Comment by dashpole** [comment]
Yes, we can remove that status header
