### ISSUE TITLE
Broken links in README of signalfxexporter

### ISSUE THREAD

**Issue by lindhe** [open-telemetry/opentelemetry-collector-contrib#9361]
There's a broken link at [line 55 of the signalfxexporter's README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e62787567cf7aeec18bfe3e7c77ffa1cd2e3a593/exporter/signalfxexporter/README.md?plain=1#L55).

I'm guessing it should lead to `./internal/translation/default_metrics.go` instead of `./translation/default_metrics.go`, but I don't know for sure.

There may be more broken links, I haven't checked.

**Comment by lindhe** [comment]
Keep open

**Comment by dmitryax** [comment]
All the links in signalfxexporter README were fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11151
