### ISSUE TITLE
[processor/transform] Add ability to truncate and/or limit attributes

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#9366]
**Is your feature request related to a problem? Please describe.**
The [specification recommends SDKs be able to truncate and limit attributes](https://opentelemetry.io/docs/reference/specification/common/common/#attribute-limits).  Doing the truncation in the instrumentation is always most efficient, but not all languages instrumentation supports this feature.  Customer may also wish to handle all their attribute truncating/limits in one place instead of in each instrumentation, trading efficiency for convenience.  Also, some third-party data sources may send data to the collector with attributes that a customer cannot configure, and thus must be handled in the collector.

**Describe the solution you'd like**
The transform processor updated to allow attribute length truncation and attribute count limiting.  

**Describe alternatives you've considered**
I've thought about a new processor, but it feels like this processor is the best spot.

**Additional context**
I'm not entirely sure yet what the impact of a feature like this would mean if the processor is also configured to modify/extract/delete attributes.  It may be that this new feature is incompatible with other config options and should always be its own instance of the transform processor in the pipeline.

**Comment by jpkrohling** [comment]
Perhaps the transform processor would be a better place? cc @anuraaga

**Comment by TylerHelmuth** [comment]
I looks like the transform processor could be extended to meet the same goal.  There is a lot of overlap between the attributes processor and the transform processor.  I think it would be best to add it to whichever processor is going to stay long-term.  If they are both going to stay, I lean more towards the attributes processor because I think more people use it and it is easier to find.

**Comment by TylerHelmuth** [comment]
Based on discussion in the SIG meeting transform processor is the correct place as it is the planned long-term processor.  I have updated this feature request.

**Comment by TylerHelmuth** [comment]
You can assign this to me, I plan to implement it.
