### ISSUE TITLE
[resourceprocessor] Specify list of resource attributes allowed to reach exporters

### ISSUE THREAD

**Issue by Fydon** [open-telemetry/opentelemetry-collector-contrib#9370]
**Is your feature request related to a problem? Please describe.**
As exporters can use [resource_to_telemetry_conversion](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md) to convert resource attributes into metric labels, ideally there should be a way to easily filter resource attributes.

**Describe the solution you'd like**
It is possible use the [delete action](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor), but [include and exclude](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor#includeexclude-filtering) that attributesprocessor has would be helpful.

**Describe alternatives you've considered**
I could look at all the resource attributes that exist and drop them, but, as I only want around 3 resource attributes, include would be easier.

**Additional context**
I'm using [awscontainerinsightreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awscontainerinsightreceiver).

**Comment by Fydon** [comment]
Is the include and exclude in attributesprocessor just determining whether the processor is processing it? Therefore if it is excluded by all processors, it is included in the data to the exporters?

What I essentially want is an allow list so that I can just list off what is going to the exporters.

**Comment by TylerHelmuth** [comment]
Is this the end goal you are trying to reach: "Add a specific set of resource attributes as attributes on metrics" ?

**Comment by Fydon** [comment]
Yes

**Comment by TylerHelmuth** [comment]
@jpkrohling @anuraaga is the ability to copy resource attributes to metrics something that could be added to the transform processor?  It feels weird that the capability currently exists in the exporthelper and I feel like it should be moved to a processor.

**Comment by jpkrohling** [comment]
I think this would be a question for both @dmitryax and @bogdandrutu, but my feeling is that it indeed makes sense to have it as part of a processor.

**Comment by dmitryax** [comment]
@TylerHelmuth please correct me if I'm wrong, but I believe [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) already can conditionally drop resource attributes.

**Comment by TylerHelmuth** [comment]
Yes we now have a [delete_key](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#delete_key) function that can be used to remove attributes.
