### ISSUE TITLE
Review components to give users an indication of the level of support

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#9377]
As we do in the core component, we should label the components in the contrib repository to give users an insight as to what components are planned on being supported for the long term, versus which are experimental.

This requires a definition of what experimental, alpha, beta, stable for components in contrib. This would also need a dimension to specify components supported by a vendor.

Sub-tasks:

- [x] #9379
- [x] #9380
- [x] #9381
- [x] #9382
- [ ] #9518
- [x] #9519

**Comment by codeboten** [comment]
The information to be captured:

```
Owners (who is supporting the component, vendor):
Status:
```

**Comment by codeboten** [comment]
The definition for stability should include the interface with the user, the yaml configuration.

**Comment by mx-psi** [comment]
To be done/discuss: add template for components to fill out https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9412#discussion_r857500184
