### ISSUE TITLE
Define the stability and support level for the Routing exporter

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#9381]

**Comment by jpkrohling** [comment]
@kovrus, would you like to work on this one? I believe this component should be "beta", given that there are folks using it in production.

**Comment by kovrus** [comment]
@jpkrohling it was updated already
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/routingprocessor/README.md. Can you please close it?
