### ISSUE TITLE
Add thread count to metrics reported by hostmetricsreceiver

### ISSUE THREAD

**Issue by davidmirza408** [open-telemetry/opentelemetry-collector-contrib#9415]
**Is your feature request related to a problem? Please describe.**
It would be useful to know the thread count of processes reported on by hostmetricsreceiver

**Describe the solution you'd like**
Add thread count to metrics reported by hostmetricsreceiver

cc @dmitryax

**Comment by astencel-sumo** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12802.

**Comment by atoulme** [comment]
This is now complete. Please close the issue if you agree.
