### ISSUE TITLE
[receiver/sqlserverreceiver] Bug - Gauge Metrics Actual Monotonic Sums

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#9522]
**Describe the bug**
sqlserver.transaction_log.growth.count and sqlserver.transaction_log.shrink.count are both currently gauges. They should actually be monotonic sums.

**Steps to reproduce**
Run collection with sqlserver metric receiver configured.

**What did you expect to see?**
sqlserver.transaction_log.growth.count and sqlserver.transaction_log.shrink.count as Monotonic Sums.

**What did you see instead?**
sqlserver.transaction_log.growth.count and sqlserver.transaction_log.shrink.count as Gauges.

**What version did you use?**
Version: Main (unreleased)

**What config did you use?**
Config: Simple sqlserver configuration

**Environment**
OS: Windows

**Comment by pmm-sumo** [comment]
Fixed through #9520

If you believe this issue was not addressed, feel free to reopen it
