### ISSUE TITLE
[receiver/riak] - Fix issue where user configured metric settings were ignored

### ISSUE THREAD

**Issue by armstrmi** [open-telemetry/opentelemetry-collector-contrib#9560]
**Describe the bug**
Riak receiver's newScraper method currently uses  `DefaultMeticsSettings` when instantiating a metrics builder

**What did you expect to see?**
```
// newScraper creates a new scraper
func newScraper(logger *zap.Logger, cfg *Config, settings component.TelemetrySettings) *riakScraper {
	return &riakScraper{
		logger:   logger,
		cfg:      cfg,
		settings: settings,
		mb:       metadata.NewMetricsBuilder(cfg.Metrics),
	}
}
```
**What did you see instead?**
check out [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1c4dd67f7af084c467ce5378115fa151f7276547/receiver/riakreceiver/scraper.go#L49)

**What version did you use?**
Version: v0.49.0

**What config did you use?**
Unnecessary

**Environment**
OS: (e.g., "macOS Monterey 12.2")
Compiler(if manually compiled): go 18.1

**Additional context**
Only Quick fix needed by changing that singular line

**Comment by djaglowski** [comment]
Closed by #9598
