### ISSUE TITLE
Export `dirty` metric from hostmetricsreceiver/memory for Linux

### ISSUE THREAD

**Issue by ItsLastDay** [open-telemetry/opentelemetry-collector-contrib#9565]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
hostmetricsreceiver/memory currently exports a number of [memory metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.47.0/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/metadata.yaml#L6): `[buffered, cached, inactive, free, slab_reclaimable, slab_unreclaimable, used]`.

I would want to see `dirty` metric among those exported metrics, denoting the number of dirty pages in memory. `gopsutil` [does scrape](https://github.com/shirou/gopsutil/blob/2f8da0a39487ceddf44cebe53a1b563b0b7173cc/mem/mem.go#L56) this metric for Linux, so it should be available for usage [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.47.0/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_linux.go#L27).

**Describe alternatives you've considered**
None.

**Additional context**
I'm working at Google in Google Cloud Platform (GCP). We provide infrastructure metrics to our customers who run on GCP, e.g. "free memory", "disk usage", etc. Currently we use collectd, but we want to use Open Telemetry to provide those metrics.
One of our customers uses the number of dirty pages as one of their critical performance metrics.

**Comment by dashpole** [comment]
cc @dmitryax, codeowner of the hostmetricsreceiver component

**Comment by ItsLastDay** [comment]
Note that I am willing to contribute code to implement this metric.

**Comment by dmitryax** [comment]
Just adding emitting more datapoints with additional attribute would be a breaking change. This will make one of the issues described in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417 even worse. 

But it'll work well if we introduce a concept of optional attributes as proposed in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417#issuecomment-1110328819

cc @djaglowski

**Comment by ItsLastDay** [comment]
Sounds reasonable, thanks!

From the discussion in #7417 I understood that those optional attributes are still in a brainstorming phase. Is that correct?

Does any other receiver have a similar feature/concept?

I'll subscribe to #7417 to keep track of the updates.
