### ISSUE TITLE
[receiver/fluentforwardreceiver] Resource, TraceId, SpanId and SeverityText fields are parsed incorrectly

### ISSUE THREAD

**Issue by stanmarsh2** [open-telemetry/opentelemetry-collector-contrib#9566]
**Is your feature request related to a problem? Please describe.**
The fluentforwardreceiver's log parser lacks correct parsing of several important fields.
By default they're parsed as attributes, but there are special fields in protocol for them `resource`, `severity_text`,  `trace_id`, `span_id` [here](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L43,L221) .
`TraceId` and `SpanId`: needed to tie logs to the specific traces.
`SeverityText`: needed to understand the log severity - error, warn, info, etc.
`Resource[service.name]`: our OTLP collector gathers logs from different containers. Without it `ES Observability APM` shows logs are originated from `unknown service`. 
* There are lots of other `Resource` attributes (cloud provider, cloud platform, region, etc.) - can be implemented all at once or have the extension in mind for future.

**Describe the solution you'd like**
* `TraceId`, `SpanId`, `SeverityText`: parse `Event`'s attribute and populate `severity_text`,  `trace_id`, `span_id` fields.
* `Resource[service.name]`
	* Parse `Event`'s attribute and populate `resource` field.
	* (Optional) Support the rest `Resource` attributes (cloud provider, cloud platform, region, etc.) 
* (Optional) YML Config: to have field aliases as AWS Distro has [here](https://aws-otel.github.io/docs/getting-started/ecs-configurations/ecs-config-section) `from_attribute => key`, `appName => service.name`, `level => SeverityText`.

**Describe alternatives you've considered**
N/A

**Additional context**
`TraceId/SpanId` is an essential part of Opentelemetry philosophy - correlated logs, metrics and traces.

**Comment by stanmarsh2** [comment]
@dmitryax is it possible to contribute the fix? Will you accept/review it please?
If yes, maybe you can point out links to some contributor's guidelines.

**Comment by dmitryax** [comment]
Hey @stanmarsh2.

> TraceId, SpanId, SeverityText: parse Event's attribute and populate severity_text, trace_id, span_id fields.

Are the `severity_text`, `trace_id`, `span_id` standard in fluent format? Or at least defined somewhere in the docs? These are the fields that maybe makes sense trying to fetch, but we need to find good corresponding fields.

> Resource[service.name]

fluent format doesn't have any notion of service AFAIK. So we cannot guess, but we may predefine some otel specific field e.g. `otel.service.name`

Anyway, first you need to suggest a mapping between fluent and OTel format for all the fields discussed above in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#appendix-a-example-mappings

> Parse Event's attribute and populate resource field.

This should not be done. You don't know which fields of an event can be part of a resource and which are part of a log record.

> (Optional) Support the rest Resource attributes (cloud provider, cloud platform, region, etc.)

This is definitely out of the scope of fluentforward receiver.


Alternatively you can setup [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) and convert the log records however you want to. Also [groupbyattribute processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor) can be used to move log attributes to resource attributes
