### ISSUE TITLE
basicauth with receiver prometheus_simple

### ISSUE THREAD

**Issue by raphaelauv** [open-telemetry/opentelemetry-collector-contrib#9570]
I have a Prometheus endpoint that use basic_auth : 

https://help.aiven.io/en/articles/2473061-using-aiven-with-prometheus

![Screenshot from 2022-04-28 19-10-00](https://user-images.githubusercontent.com/10202690/165807526-953d3657-05b1-4813-be45-01ddebd5712d.png)

````yaml
extensions:
  basicauth/client:
    client_auth:
      username: the_user
      password: the_password

receivers:
  prometheus_simple:
    collection_interval: 30s
    endpoint: "aaaaaaaaaaaaaa.com:9273"
    auth:
      authenticator: basicauth/client

exporters:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

processors:

service:
  extensions: [ basicauth/client ]
  pipelines:
    metrics:
      receivers: [ prometheus_simple ]
      processors: [ ]
      exporters: [ logging ]
````

give an error , but I don't know what to do 

```
Error: failed to get config: cannot unmarshal the configuration: error reading extensions configuration for "basicauth/client": 1 error(s) decoding:
2022-04-28T17:05:14.346360155Z 
2022-04-28T17:05:14.346364581Z * '' has invalid keys: client_auth
2022-04-28T17:05:14.346367900Z 2022/04/28 17:05:14 collector server run finished with error: failed to get config: cannot unmarshal the configuration: error reading extensions configuration for "basicauth/client": 1 error(s) decoding:
2022-04-28T17:05:14.346371644Z 
2022-04-28T17:05:14.346374407Z * '' has invalid keys: client_auth
```

is the doc https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension up to date ? thank you

**Comment by raphaelauv** [comment]
look like https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8847 is not part of release 0.49

I have to wait for a 0.50 , is that correct ?

**Comment by jpkrohling** [comment]
Correct. I'll close this, but do reopen if that still doesn't work. v0.50.0 should be available in the next few days.

**Comment by raphaelauv** [comment]
but there is no other way ? Directly by setting the header ?

```
'Authorization': 'Basic ....'
```

**Comment by jpkrohling** [comment]
I'm not 100% familiar with this specific component, but if it uses the standard HTTP Client Settings, that would indeed work.

**Comment by raphaelauv** [comment]
I'm sorry I'm not familiar with otel, where can I find an example or the doc of the HTTP client settings ?

Thanks again

**Comment by jpkrohling** [comment]
My bad, I should have provided the complete information :-) In general, HTTP Clients built by the components (simple prometheus receiver here) would use this: https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/confighttp#client-configuration

Looks like this receiver is **not** using it though: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4259a2bd836e8da5a9b4c1e46bd872579474aa8f/receiver/simpleprometheusreceiver/config.go#L25-L40

**Comment by jpkrohling** [comment]
Actually, I think it's cleaner to just open a new issue.
