### ISSUE TITLE
Simple Prometheus receiver should use HTTP Client Settings

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#9571]
As seen on #9570, the simple Prometheus receiver should make use of the standard HTTP Client Settings, so that it can take advantage of the standard features that it provides, such as access to the client authenticators.

**Comment by raphaelauv** [comment]
@fatsheep9146 thanks ! Let me know if you need a beta tester 👍

**Comment by codeboten** [comment]
@fatsheep9146 @raphaelauv any interest in becoming code owners for the component? It's currently unmaintained https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11504

**Comment by fatsheep9146** [comment]
> @fatsheep9146 @raphaelauv any interest in becoming code owners for the component? It's currently unmaintained #11504

I do have interest in this :),  What should I do to assign me as code owner?

**Comment by dmitryax** [comment]
@fatsheep9146 can you please pick up this issue to get familiar with the receiver since you are going to be a code owner

**Comment by fatsheep9146** [comment]
> @fatsheep9146 can you please pick up this issue to get familiar with the receiver since you are going to be a code owner

Absolutely, I will resolve this ASAP
