### ISSUE TITLE
Hostmetricsreceiver: config setting to allow obfuscating of parameters

### ISSUE THREAD

**Issue by davidmirza408** [open-telemetry/opentelemetry-collector-contrib#9578]
**Is your feature request related to a problem? Please describe.**
I would like to add a config setting to allow users to obfuscate command line parameters if desired.

**Describe the solution you'd like**
The config setting would allow the user to specify a parameter to obfuscate.  For example if the command line is:
"myprogram -password mypassword"
the obfuscated command line would be:
"myprogram -password ************"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

cc @dmitryax

**Comment by davidmirza408** [comment]
Here is the PR I would add once this issue is approved https://github.com/davidmirza408/opentelemetry-collector-contrib/pull/12/files

**Comment by pavankrish123** [comment]
@davidmirza408 - We  have [Redaction Process ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/redactionprocessor)  that achieves the same affect. Please see if you can add enhancements to this processor (if it is not solving this specific use case already). The advantage doing it here is that we can use it for data received from all/any receivers.
