### ISSUE TITLE
[receiver/jmxreceiver] Only accept versions of the JMX Metrics Gatherer jar or additional dependencies with known hashes

### ISSUE THREAD

**Issue by dehaansa** [open-telemetry/opentelemetry-collector-contrib#9687]
**Is your feature request related to a problem? Please describe.**
This issue is a portion of the effort to reduce the potential security risks of running the JMX Metrics Gatherer as a separate executable.

**Describe the solution you'd like**
Hash the known & supported versions of the JMX Metrics Gatherer, then at runtime compare the hash of the found Jar from user input to that list of known hashes.

Also apply this to the "Additional Jars" parameter, which is currently only intended & required for Wildfly support. There are only 3 released versions of the relevant Jar so this should be straightforward.

**Additional context**
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6750

**Comment by djaglowski** [comment]
Closed by #9985
