### ISSUE TITLE
K8S processor: Add detailed user documentation

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector-contrib#97]
Add a README file to k8sprocessor container user documentations. In addition to documenting all the config options and what they do, we should also mention recommended deployment scenarios and configurations.

**Comment by tigrannajaryan** [comment]
Done, see https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor?tab=doc
