### ISSUE TITLE
[processor/k8sattributes] Apply strict regex matching on the full length of labels/annotations

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#9716]
As discussed in [this thread](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9525#discussion_r863292338 ) we should apply `key_regex` value to the full length of annotations and labels. For example:
- `key_regex: an*` should not match `annotation1` pod label, but match `annn` label.
- `key_regex: .*` should match any pod label.

**Comment by erenming** [comment]
Hi, i'd like to solve this issue, could assign it to me?

**Comment by dmitryax** [comment]
@erenming, assigned. Thank you!
