### ISSUE TITLE
Incorrect conversion behavior going from AWS X-Ray trace ID to Datadog trace ID

### ISSUE THREAD

**Issue by IvanTopolcic** [open-telemetry/opentelemetry-collector-contrib#9733]
**Describe the bug**

Datadog trace IDs are using 64 bits of data instead of 63 bits. This is usually not an issue, but in the case where we're converting from x-ray trace to a datadog trace, we're not using the same format that we use internally, which is 63 bits of information from the AWS trace ID.

Given a sample X-Ray trace ID, `1-58406520-a006649127e371903a2de979`, we want to grab the last 16 characters, convert those into an integer, and bitmask it with `0x7FFFFFFFFFFFFFFF`. Right now, we're not doing the last step of bitmasking, so we're using the entire 64 bits. You can see the problematic line [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/translate_traces.go#L504).

**Steps to reproduce**

Convert an AWS X-Ray trace ID to a Datadog trace ID (via the Datadog exporter).

**What did you expect to see?**

A Trace ID with 63 bits of info. 

**What did you see instead?**

A Trace ID with 64 bits of info. 

**Additional context**

I'll submit a PR, I just wanted to open the issue to raise the problem. @gbbr I see that you're a maintainer on this repository, would you mind taking a look once I have the PR ready?

**Comment by dmitryax** [comment]
cc @mx-psi as code owner

**Comment by mx-psi** [comment]
Thanks Dmitrii! @gbbr is working on this

**Comment by mx-psi** [comment]
@gbbr @mackjmr is there anything we want to do for this issue?

**Comment by mx-psi** [comment]
@gbbr any updates on this?

**Comment by mx-psi** [comment]
I looped back with the team that owns this internally, it seems like no changes are needed in the Datadog exporter so I am going to close this as a wontfix
