### ISSUE TITLE
[processor/transform] Add ability to specify attributes that aren't allowed to be dropped during limiting

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#9734]
**Is your feature request related to a problem? Please describe.**
As part of the `limit` function being added in #9552, which attributes are dropped as part of limiting is random.  This could result in priority attributes being dropped.

**Describe the solution you'd like**
The `limit` function should be updated so that users can specify a list of attribute names that should never be dropped during limiting.   The number of "priority attributes" should not be allowed to be more than the limit supplied.

**Additional context**
Issue originated from feedback in #9552

**Comment by kovrus** [comment]
@TylerHelmuth can you assign it to me?
