### ISSUE TITLE
Enable errcheck in missing components

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#9749]
Follow up to #9726. Remaining modules where at least some files are excluded:

- [x] Enable errcheck in examples/demo/server
- [x] Enable errcheck in exporter/awscloudwatchlogsexporter
- [x] Enable errcheck in exporter/awsemfexporter
- [x] Enable errcheck in exporter/awsxrayexporter
- [x] Enable errcheck in exporter/carbonexporter
- [x] Enable errcheck in exporter/coralogixexporter
- [x] Enable errcheck in exporter/datadogexporter
- [x] Enable errcheck in exporter/dynatraceexporter
- [x] Enable errcheck in exporter/elasticexporter
- [x] Enable errcheck in exporter/elasticsearchexporter
- [x] Enable errcheck in exporter/googlecloudexporter
- [x] Enable errcheck in exporter/honeycombexporter
- [x] Enable errcheck in exporter/humioexporter
- [x] Enable errcheck in exporter/jaegerthrifthttpexporter
- [x] Enable errcheck in exporter/loadbalancingexporter
- [x] Enable errcheck in exporter/newrelicexporter
- [x] Enable errcheck in exporter/prometheusexporter
- [x] Enable errcheck in exporter/prometheusremotewriteexporter
- [x] Enable errcheck in exporter/sentryexporter
- [x] Enable errcheck in exporter/signalfxexporter
- [x] Enable errcheck in exporter/splunkhecexporter
- [x] Enable errcheck in exporter/sumologicexporter
- [x] Enable errcheck in exporter/tanzuobservabilityexporter
- [x] Enable errcheck in extension/basicauthextension
- [x] Enable errcheck in extension/fluentbitextension
- [x] Enable errcheck in extension/httpforwarder
- [x] Enable errcheck in extension/oauth2clientauthextension
- [x] Enable errcheck in extension/observer/ecsobserver
- [x] Enable errcheck in extension/storage/dbstorage
- [x] Enable errcheck in extension/storage/filestorage
- [x] Enable errcheck in internal/aws/awsutil
- [x] Enable errcheck in internal/aws/cwlogs
- [x] Enable errcheck in internal/aws/k8s
- [x] Enable errcheck in internal/aws/proxy
- [x] Enable errcheck in internal/aws/xray
- [x] Enable errcheck in internal/components
- [x] Enable errcheck in internal/containertest
- [x] Enable errcheck in internal/docker
- [x] Enable errcheck in internal/scrapertest/golden
- [x] Enable errcheck in pkg/stanza
- [x] Enable errcheck in processor/cumulativetodeltaprocessor
- [x] Enable errcheck in processor/deltatorateprocessor
- [x] Enable errcheck in processor/groupbytraceprocessor
- [x] Enable errcheck in processor/k8sattributesprocessor
- [x] Enable errcheck in processor/metricsgenerationprocessor
- [x] Enable errcheck in processor/metricstransformprocessor
- [x] Enable errcheck in processor/resourcedetectionprocessor
- [x] Enable errcheck in processor/routingprocessor
- [x] Enable errcheck in processor/spanmetricsprocessor
- [x] Enable errcheck in processor/tailsamplingprocessor
- [x] Enable errcheck in receiver/awscontainerinsightreceiver
- [x] Enable errcheck in receiver/awsecscontainermetricsreceiver
- [x] Enable errcheck in receiver/awsxrayreceiver
- [x] Enable errcheck in receiver/carbonreceiver
- [x] Enable errcheck in receiver/collectdreceiver
- [x] Enable errcheck in receiver/couchbasereceiver
- [x] Enable errcheck in receiver/couchdbreceiver
- [x] Enable errcheck in receiver/elasticsearchreceiver
- [x] Enable errcheck in receiver/filelogreceiver
- [x] Enable errcheck in receiver/fluentforwardreceiver
- [x] Enable errcheck in receiver/googlecloudpubsubreceiver
- [x] Enable errcheck in receiver/jmxreceiver
- [x] Enable errcheck in receiver/k8sclusterreceiver
- [ ] Enable errcheck in receiver/kafkareceiver
- [x] Enable errcheck in receiver/kubeletstatsreceiver
- [x] Enable errcheck in receiver/mongodbatlasreceiver
- [x] Enable errcheck in receiver/mongodbreceiver
- [x] Enable errcheck in receiver/opencensusreceiver
- [x] Enable errcheck in receiver/podmanreceiver
- [x] Enable errcheck in receiver/prometheusreceiver
- [x] Enable errcheck in receiver/rabbitmqreceiver
- [x] Enable errcheck in receiver/riakreceiver
- [x] Enable errcheck in receiver/saphanareceiver
- [x] Enable errcheck in receiver/sapmreceiver
- [x] Enable errcheck in receiver/signalfxreceiver
- [x] Enable errcheck in receiver/simpleprometheusreceiver
- [x] Enable errcheck in receiver/splunkhecreceiver
- [x] Enable errcheck in receiver/statsdreceiver
- [x] Enable errcheck in receiver/wavefrontreceiver
- [x] Enable errcheck in receiver/zookeeperreceiver
- [x] Enable errcheck in testbed
- [x] Enable errcheck in tracegen

---

**Note**: To create this I ran:

```
❯ git diff-tree --no-commit-id --name-only -r 652b17a3d348db5754771df06b3fd7e49f62bd25~..HEAD | rg .go$ | xargs dirname | sort | uniq | awk '{print "- [ ] Enable errcheck in " $0}'
```

and the cleaned up the resulting list manually

**Comment by mx-psi** [comment]
Note that @fatsheep9146 is working on the parent issue, so if you are going to work on this please contact them to avoid duplicate work!

**Comment by fatsheep9146** [comment]
Can you assign this to me? @mx-psi

**Comment by DiptoChakrabarty** [comment]
Hi @mx-psi  can you assign me too I can work on some of these

**Comment by fatsheep9146** [comment]
@mx-psi exporter/carbonexporter is solved

**Comment by fatsheep9146** [comment]
@mx-psi add processors part are resolved.

**Comment by mx-psi** [comment]
Thanks, I have tried to update the list with the components that have been addressed so far :)

**Comment by fatsheep9146** [comment]
@mx-psi I summarized the status of this pr, 

following checkboxes can be closed
- exporter/honeycombexporter
- internal/aws/awsutil
- internal/aws/cwlogs
- internal/aws/k8s
- internal/aws/proxy
- internal/aws/xray
- internal/containertest
- internal/docker
- receiver/awsecscontainermetricsreceiver
- receiver/collectdreceiver
- receiver/fluentforwardreceiver
- receiver/googlecloudpubsubreceiver
- receiver/jmxreceiver
- receiver/k8sclusterreceiver
- receiver/kubeletstatsreceiver
- receiver/mongodbatlasreceiver
- receiver/podmanreceiver
- receiver/rabbitmqreceiver
- receiver/riakreceiver
- receiver/saphanareceiver
- receiver/signalfxreceiver
- receiver/wavefrontreceiver

There still exists following issues to be done, some of them may be stale, if the related pr is finally closed due to long-time non-reponse from related owners, I will pick up a new request 

- [ ] exporter/elasticsearchexporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9966
- [ ] internal/components https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12791
- [ ] receiver/awscontainerinsightreceiver https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12325
- [ ] receiver/awsxrayreceiver https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12509
- [ ] receiver/kafkareceiver https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12789
- [ ] receiver/sapmreceiver https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12790
- [ ] receiver/simpleprometheusreceiver https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12622
- [ ] receiver/splunkhecreceiver:  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12665
- [ ] receiver/statsdreceiver:  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12780
- [ ] exporter/loadbalancingexporter : https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10907
- [ ] exporter/signalfxexporter https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12792

**Comment by mx-psi** [comment]
Thanks @fatsheep9146, I updated the issue checklist

**Comment by fatsheep9146** [comment]
> @mx-psi I summarized the status of this pr,
> 
> following checkboxes can be closed
> 
> * exporter/honeycombexporter
> * internal/aws/awsutil
> * internal/aws/cwlogs
> * internal/aws/k8s
> * internal/aws/proxy
> * internal/aws/xray
> * internal/containertest
> * internal/docker
> * receiver/awsecscontainermetricsreceiver
> * receiver/collectdreceiver
> * receiver/fluentforwardreceiver
> * receiver/googlecloudpubsubreceiver
> * receiver/jmxreceiver
> * receiver/k8sclusterreceiver
> * receiver/kubeletstatsreceiver
> * receiver/mongodbatlasreceiver
> * receiver/podmanreceiver
> * receiver/rabbitmqreceiver
> * receiver/riakreceiver
> * receiver/saphanareceiver
> * receiver/signalfxreceiver
> * receiver/wavefrontreceiver
> 
> There still exists following issues to be done, all these issues are tracked with PR. But, some of PRs may be stale or not reponsed from owners.
> 
> If the related pr is finally closed due to long-time non-reponse from related owners, I will pick up a new request
> 
> * [x]  exporter/elasticsearchexporter: [[exporter/elasticsearch] fix lint for exporter/elasticsearch #12933](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12933)
> * [x]  internal/components [[internal/components] fix lint for internal/components #12791](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12791)
> * [x]  receiver/awscontainerinsightreceiver [[receiver/awscontainerinsight] fix lint error for awscontainerinsightreceiver #12325](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12325)
> * [x]  receiver/awsxrayreceiver [[receiver/awsxray] fix lint error for awsxrayreceiver #12509](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12509)
> * [x]  receiver/kafkareceiver [[receiver/kafka] fix lint for kafka receiver #12789](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12789)
> * [x]  receiver/sapmreceiver [[receiver/sapm] fix lint for sapmreceiver #12790](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12790)
> * [x]  receiver/simpleprometheusreceiver [[receiver/simpleprometheus] fix lint for simpleprometheusreceiver #12622](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12622)
> * [x]  receiver/splunkhecreceiver:  [[receiver/splunkh] fix errcheck lint error #12665](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12665)
> * [x]  receiver/statsdreceiver:  [[receiver/statsd] fix lint for statsdreceiver #12780](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12780)
> * [x]  exporter/loadbalancingexporter : [[exporter/loadbalancing] fix lint error for loadbalancingexporter #12954](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12954)
> * [x]  exporter/signalfxexporter [[exporter/signalf] fix lint error for signalfxexporter #12792](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12792)

I think the task list can be updated again, almost all linters are fixed. @mx-psi

**Comment by mx-psi** [comment]
There are only three components left. In particular: 

- A PR seems to have accidentally reverted the Jaeger receiver errcheck enabling (see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14561#discussion_r994550546 )
- Recent PRs to the elasticsearch exporter added some nolint directives. @JaredTan95, would you be able to open a PR removing those?
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14596 will fix remaining issues on the Kafka receiver

Other than that, every other component is ready!

**Comment by fatsheep9146** [comment]
@mx-psi I think the issue is ready to be closed. =D

**Comment by mx-psi** [comment]
Indeed :tada: :rocket: Closing...
