### ISSUE TITLE
[receiver/dockerstatsreceiver] Improvements proposal for dockerstatsreceiver

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-collector-contrib#9794]
Looking to invest in the `dockerstatsreceiver`, and I noticed there are a couple of improvements that we could make to the component. I am happy to implement the below improvements once discussed here.

EDIT: This list below is the initial list. See my below comment for a refined list. 

1. Configuration ability to turn certain metrics on/off. Similar to `hostmetricsreceiver`. A set of default metrics will be on by default, and then the user has the ability to turn each metric on/off as they please. This is achieved by using `mdatagen`.
2. Add a new metric `memory.usage.total_cache`. This is something we need to get a better picture of the container's memory usage. This metric can be off-by-default assuming item (1) is implemented. 
3. Documentation improvements. This also can be achieved by onboarding the component to `mdatagen` since it auto generates the documentation for each metric. 
4. (Breaking change) Rename configuration options to use attributes, not labels. For example, `container_labels_to_metric_labels` would be renamed to `container_attributes_to_metric_attributes`
5. Once these items are implemented, declare the component as `alpha` with the aim to eventually move it into `beta`.

**Comment by jamesmoessis** [comment]
@rmfitzpatrick as the codeowner of this component, I would really appreciate your feedback and thoughts on this :)

**Comment by jamesmoessis** [comment]
I've edited the description of the issue to include onboarding to `mdatagen` in order to align with other similar scrapers in the contrib.

**Comment by rmfitzpatrick** [comment]
Thanks @jamesmoessis for these suggestions (and your patience!). I am a supporter of all of them though I think we may want to have an opt-in/grace period using redundant fields/feature flags as possible.

> 1. Configuration ability to turn certain metrics on/off. Similar to `hostmetricsreceiver`. A set of default metrics will be on by default, and then the user has the ability to turn each metric on/off as they please. This is achieved by using `mdatagen`.

This is similar to my initial implementation but I was [requested to defer to a processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/495#discussion_r470157779). The requested approach doesn't appear to be the de facto standard and metric groups or similar config options are used in other components so I'm still for it. The complexity of filtering can also make it very undesirable as is.

> 3. Documentation improvements. This also can be achieved by onboarding the component to mdatagen since it auto generates the documentation for each metric.

I would really like this to happen.

**Comment by jamesmoessis** [comment]
Thanks @rmfitzpatrick! Yes I do agree about the op-in/grace period. 

It sounds like we are on the same page. I will put some PRs in in the coming weeks to gradually implement these :)

**Comment by jamesmoessis** [comment]
@rmfitzpatrick another thing I recently noticed about this receiver is that it records memory metrics as gauges, while the otel spec says to record these as sums. As I'm unsure how heavily this receiver is used, how much of a pain would that be to change? Ideally they are sums.

**Comment by rmfitzpatrick** [comment]
@jamesmoessis I'm not 100% on the spec but I think the difference between gauges and non-monotic sums/UpDownCounters is the implicit validity of adding their values across attributes, so I think there would be few if any side effects: https://github.com/open-telemetry/opentelemetry-specification/blob/bff2cc1365bb81b03f78a732dec822fff787e288/specification/metrics/supplementary-guidelines.md#guidelines-for-instrumentation-library-authors

(Anecdotally the SignalFx exporter converts non-monotonic sums to SFx gauges.)

**Comment by jamesmoessis** [comment]
After working on the receiver for a decent amount of time, here is an updated list of further (possibly breaking)  changes I want to make.

* Change various units so they more accurately represent the measurements
* Change the blockIO metrics so the operation is an attribute, and so we can divide the number of those metrics by 6. This simplifies the code, and greatly reduces the amount of generated docs/code.
* Change the memory metrics from gauge to sum.
* All metrics are currently enabled by default. We should make it so a sensible set of metrics are enabled by default. 
	* Most of the memory stats can be disabled as they are very specific.
* Only emit entire CPU system usage once (not per container, and with different resource).

**Comment by jamesmoessis** [comment]
Update: I've raised most changes that I want to now. In the coming weeks, we will start using the featuregate-enabled scraper more heavily.

Once I'm happy with the stability of it, I will slowly:
- [] Transition the featuregate to be the default (which is the main breaking change for users)  
- [] Remove the v1 scraper. 
- [] Transition the component into beta.

**Comment by dmitryax** [comment]
@jamesmoessis JFY I created this issue some time ago https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13848. Looks like it covers item 4 in your list.

**Comment by dmitryax** [comment]
> Transition the featuregate to be the default, deprecating the v1 scraper (which is the main breaking change for users)

I believe we should add warning saying that it'll be enabled by default soon so it doesn't happen unexpectedly.

**Comment by jamesmoessis** [comment]
@dmitryax sounds good I commented on that issue. 

> I believe we should add warning saying that it'll be enabled by default soon so it doesn't happen unexpectedly.

I will raise a PR for this next week 👍

**Comment by jamesmoessis** [comment]
This is not stale, aiming to be closed by 0.71.0 release

**Comment by jamesmoessis** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18019 closes this ticket out, once it's merged. 

The next step for this component would be to move it to beta, but I think there can be another ticket for this.
