### ISSUE TITLE
[receiver/statsd] Remove usage of deprecated net.Error.Temporary

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#9808]
See #9782

**Comment by pavankrish123** [comment]
@djaglowski - I can take this and the related issues if you don't mind?

**Comment by djaglowski** [comment]
Awesome, thanks @pavankrish123!

**Comment by pavankrish123** [comment]
cc: @mcmho

**Comment by codeboten** [comment]
fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11857
