### ISSUE TITLE
Code Owners not being requested for review unless they have write permission

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#9815]
I noticed today that Code Owners that do not have write permissions (so it seems) to the repository do not get automatically requested for review on PRs for which they are a code owner.
<img width="656" alt="Screen Shot 2022-05-09 at 11 29 28 AM" src="https://user-images.githubusercontent.com/12352919/167464866-de2127b6-79c2-4123-b004-e4243737d871.png">
[This PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9726), for example, probably should have requested review from a lot more people.

[Whats strange is that it seems like users only need read access in order for the feature to work](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners). Is the code owners for Contrib setup differently?

**Comment by bogdandrutu** [comment]
Nope, this is a known limitation of GH. I also proposed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7063 but the AWS folks seem to not make any progress.

**Comment by TylerHelmuth** [comment]
Nvm, my experiment won't work with a fork.  I'll test another way.

I have a suspicion that `read` access is enough, but you have to be explicitly added in the `Collaborators and teams` section.

**Comment by TylerHelmuth** [comment]
My suspicion was wrong :( definitely need write access, even as a user.
