### ISSUE TITLE
`k8sclusterreceiver` & `k8sattributesreceiver` no longer have `ClusterName`

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#9886]
With recent changes to the k8s api, the `ClusterName` field has been removed. See the following change for more details:
https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/6cdd63f91273803bc81e756cd0973bc153c18bd2

This field was reset by the system and never used as per: https://github.com/kubernetes/apimachinery/commit/430b920312ca0fa10eca95967764ff08f34083a3#diff-35c0c434140e1c1254f58cc21b2f0ae371c7f2e00d15ce5d07da1b74c891ee97R257-R259

This issue is to determine whether there's additional work to be done or not.

**Comment by codeboten** [comment]
@dmitryax assigned to you as a codeowner for both components. pinging @pmm-sumo as well

Please close this issue if the change implemented in the PR to update dependencies is good enough.

**Comment by pmm-sumo** [comment]
Closing via #9968
