### ISSUE TITLE
Proposed guidelines for scoping of Make targets

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#9888]
It would be helpful to clarify the intended roles of `Makefile` and `Makefile.Common`. In particular, it would be helpful to establish some explicit guidelines around how to decide whether a given piece of functionality should be "common" or not. To that end, I propose we adopt the following:

### Common targets
* Common targets are those that can be run for _any individual_ module.
* Common targets should be "module aware", meaning that they do not act on nested modules. eg. running "lint" at the root module _does not_ run lint on individual component modules. (See #9775)
* The default common target should run a substantial set of common targets for an individual module. Ideally, this is all common targets, but exceptions may be made if including a particular target would result in unacceptable latency in the local development loop.

### Top-level targets
* Whenever reasonable, targets should be implemented as common targets. They can then wrapped at the top level using "for each module" targets.
* The root Makefile should contain a "for each module" target corresponding to _each_ common target. In this way, all common functionality is also available as a top-level target (with a different name).
* Some reasonable justifications for _not_ implementing as a common target.
  * The target is clearly meant as repo-wide target. (eg. build the collector)
  * Interaction between modules would be problematic.
  * A necessary tool does not provide a mechanism for scoping its application. (eg. porto)
  * The "for each module" pattern would result in incomplete coverage of the codebase.
* The top-level default target should meaningfully validate the entire repo. This should include running the default common target for each module as well as additional top-level targets.

**Comment by bogdandrutu** [comment]
@djaglowski please don't forget to keep this consistent with core :)

**Comment by jpkrohling** [comment]
Has this been implemented or discussed more broadly with the @open-telemetry/collector-contrib-approvers? The guidelines are looking good to me.

**Comment by djaglowski** [comment]
For the most part I think we are following these guidelines in both contrib and core.

I drafted this when working through some performance and consistency problems in our Makefiles but haven't heard any feedback other than what's on this thread.

I'm happy to discuss in the next SIG if anyone wants. Otherwise, I can add these into documentation and we can validate finer points on the PR.
