### ISSUE TITLE
Clarify usage between testcontainer and containertest

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#9939]
Right now, half of our intergration tests are using the internal package `github.com/open-telemetry/opentelemetry-collector-contrib/internal/containertest` and the other half are using the external package `https://github.com/testcontainers/testcontainers-go`

I think we should consolidate on one of the packages.

**Comment by mdelapenya** [comment]
👋 Hi from testcontainers! We would like to know if we can be of any help if a migration to testcontainers eventually happens.

**Comment by djaglowski** [comment]
Hi @mdelapenya. I do believe we should standardize on `testcontainers`. It would be great to have some help with this if you have capacity.

It appears there are 6 modules that use `containertest`. I propose we migrate these to `testcontainers` one at a time. Then we can look at deprecating `containertest`.

- [ ] `extension/observer/dockerobserver`
- [ ] `receiver/aerospikereceiver`
- [ ] `receiver/redisreceiver`
- [ ] `receiver/zookeeperreceiver`
- [ ] `receiver/memcachedreceiver`
- [ ] `receiver/dockerstatsreceiver`

**Comment by mdelapenya** [comment]
I think we can work on small PRs updating one module at a time, so that we get feedback during the process.

**Comment by djaglowski** [comment]
Closed by #16264
