### ISSUE TITLE
Round-tripping prometheus metrics can produce unexpected extra labels

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector-contrib#9967]
This was raised by @bogdandrutu at the sig meeting today (5/11).

**Describe the issue**
The prometheus receiver splits `instance` into `net.host.name` and `net.port.name`, and also adds `http.scheme`.  If you are running on kubernetes, it also adds many k8s.* resource attributes based on the service discovery labels.

If you use a prometheus receiver, and a prometheus exporter with `resource_to_telemetry_conversion` enabled on the exporter, you will get additional labels on your metrics, which may be surprising to users.

**Note about future plans**

We plan to remove `resource_to_telemetry_conversion` as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8265, since resources will be represented by a single metric, `target_info`.  In this case, the result would be additional labels on the target_info metric, rather than on all metrics.

**Open Questions**

* Should we generally not be adding resource attributes to scraped metrics?  I've been working under the assumption that more resource info is ~always better.
* Is the issue that `net.host.name` and `net.port.name` are duplicate info with `service.instance.id`?  We could possibly standardize on the rule that resource info SHOULD not be duplicated.
* Does the fact that this will soon only impact one metric instead of all metrics change how confusing this behavior is?  Or is it now acceptable?

**Comment by bogdandrutu** [comment]
@dashpole my 2 cents: we should try to produce if possible the result `prometheus(scrape + prw) == otelcollector(promrecv + prwexporter)`

**Comment by bogdandrutu** [comment]
> I'd prefer keeping the additional resource attributes by default, but adding an option to disable/filter the resource attributes added from service discovery.

+ 10

**Comment by bogdandrutu** [comment]
Maybe also the `net.host.name and net.port.name, and also adds http.scheme` can be a config to enable/disable these.
