### ISSUE TITLE
[receiver/nsxt] Add support for file based authentication

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#9969]
**Is your feature request related to a problem? Please describe.**

Submitting this issue for work to be not lost based off  [this comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9738#discussion_r869450327): the receiver should be able to use the `basicauth` extension to achieve file based secret management in order to use the receiver in transient environments like K8s.

**Describe the solution you'd like**

The receiver should be able to support an authenticator by `basicauth` in order to specify file based usernames and passwords. 

**Describe alternatives you've considered**
Since I believe we haven't fully standardized how receivers should do this for http clients there may be a later standard that may be more appropriate

**Additional context**

**Comment by dmitryax** [comment]
@schmikei will you be working on this? Please assign if needed

**Comment by schmikei** [comment]
@dmitryax Yep I plan on working on this!
