### ISSUE TITLE
Splunk HEC Exporter: Increase the max limit for max_content_length_* to match the current Splunk HEC server max of 800 MB

### ISSUE THREAD

**Issue by nirmalmano** [open-telemetry/opentelemetry-collector-contrib#9983]
The current max limit for max_content_length_metrics and max_content_length_logs is 2097152 bytes (2 MiB) for the splunk HEC exporter.  I have constantly hit this limit when I try to use batch processors.
The corresponding max content size on the Splunk HEC server  has been bumped up to 838860800 (~ 800 MB) - [https://docs.splunk.com/Documentation/Splunk/8.2.2/Admin/Limitsconf#.5Bhttp_input.5D]

I request a change to increase the max limit on max_content_length_metrics and max_content_length_logs to match the Splunk HEC server limit.

**Comment by dmitryax** [comment]
Splunk HEC Exporter is used for Splunk Observability as well where we have different limit. So we cannot change this default
