### ISSUE TITLE
Error: unknown processors type "logstransform"

### ISSUE THREAD

**Issue by gurpartb** [open-telemetry/opentelemetry-collector-contrib#9990]
**Describe the bug**
Otel Collector doesn't recognize processor logstranform  `2022/05/12 16:48:29 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
Error: failed to get config: cannot unmarshal the configuration: unknown processors type "logstransform" for "logstransform" (valid values: [batch memory_limiter metricstransform probabilistic_sampler resourcedetection deltatorate resource attributes cumulativetodelta groupbytrace k8sattributes experimental_metricsgeneration routing filter groupbyattrs spanmetrics span tail_sampling])`

**Steps to reproduce**
run otel collector `v0.51.0` using config below

**What did you expect to see?**
move log field value to a different field

**What did you see instead?**
otel collector crashed

**What version did you use?**
Version: `v0.51.0`

**What config did you use?**
```receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006

processors:
  logstransform:
    operators:
    - type: move
      from: attributes.appSourceType
      to: body.key3

exporters:
  file:
    path: "C:/temp/otel-output.json"

service:
  pipelines:
    logs:
      receivers:
      - fluentforward
      processors:
      - logstransform
      exporters:
      - file
```

**Environment**
Windows 10

**Additional context**
NA

**Comment by codeboten** [comment]
@gurpartb the component is experimental and is not currently included in any release. I'll follow up with an update to the readme to clarify this.

**Comment by gurpartb** [comment]
Thanks for looking into it!

**Comment by gurpartb** [comment]
Experimental feature. Closing issue for now.
