### ISSUE TITLE
support string replace for resources/attributes names

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#9994]
**Is your feature request related to a problem? Please describe.**
resources and/or attributes key currently follows semconv, or k8s labels/annotations enriched by `k8sattrs` processor, would contains `.`, `/`, `-`, in cases the backend storage doesn't not allow such characters it will need a processor that converts them to a different character, e.g. `_`. Currently, resource / attributes processor allows doing this only by explicitly define the key name, in cases regexp is used in `k8sattrs` processor that, say captures all labels or annotations, there is no way to define all possible keys.

**Describe the solution you'd like**
Support replace string action for resources/attributes name in resource/attributes processor, which seems to be a general enough solution that would support metrics/traces/logs.

**Describe alternatives you've considered**
Support such action in a dedicated processor that updates resources/attributes keys, or in current `transform` and `metricstransformprocessor`.

**Additional context**

**Comment by dmitryax** [comment]
This should be a feature request for transform processor

**Comment by TylerHelmuth** [comment]
I believe this will be fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12991

**Comment by TylerHelmuth** [comment]
Closing as this capability now exists.
